// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — the ideas, and the winter that followed them.
//
// Six pages about what the MIT AI Lab believed and what happened to the belief.
// A close reading of the blocks world kept by an alum who worked in it; a
// seminar hand-out on micro-worlds; a corrections page on the perceptrons
// affair, written by someone tired of the legend; a piece of student coursework
// on frames; reading-group notes on the Society of Mind; and an oral-history
// timeline of the funding cuts. Names, dates, memo numbers and quotations are
// real; the grumbling and the wonky bibliographies belong to the people who
// kept the pages.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- the blocks world: the showpiece close reading ---------------------------

const BLOCKS_WORLD = P('the-blocks-world.geocities.ws', 'BLOCKS WORLD',
  'THE BLOCKS WORLD // the room where everything worked', [
    '<!--bg:mac-ideas-->',
    '<h1>THE BLOCKS WORLD</h1>',
    '<p><small>notes on the standard testbed of MIT artificial intelligence,',
    'roughly 1968 to 1975, kept by somebody who ran the vision programs on the',
    'ninth floor as an undergraduate and has been trying to explain them at',
    'parties ever since. corrections gratefully received, especially from anybody',
    'who still has the memos. — d.k., course 6</small></p>',
    '<hr>',
    '<p class="fs-epi">“Person: PICK UP A BIG RED BLOCK.<br>',
    'Computer: OK.”<br>— from the SHRDLU dialogue, Terry Winograd, 1971</p>',
    '<p>For about seven years the standard laboratory animal of artificial',
    'intelligence was a tabletop with some coloured blocks on it. Cubes, pyramids,',
    'a box to put things in, a flat surface to stand them on, and an arm that',
    'could pick one up and set it down somewhere else. That was the world. It had',
    'a handful of shapes, a handful of colours, a handful of relations, and no',
    'weather, no history, no other people, and no lies in it.</p>',
    '<p>People outside the field hear this and assume it was a warm-up exercise',
    'that got out of hand. It was not. Choosing a very small world was a',
    'considered research strategy, argued for in print, and for a while it worked',
    'better than anything else anybody had.</p>',
    '<img class="indie-pic" src="assets/media/web/mac/winograd-01.jpg" alt=""><span class="indie-cap">Terry Winograd (photo: boltron, CC BY-SA 2.0)</span>',
    '<p><b>Why the room had to be small</b></p>',
    '<p>Three hard problems get easy at once when you close the world.</p>',
    '<p>The first is reference. If the only things that exist are eight blocks,',
    'then “the big red one” picks out an object by simple elimination. There is a',
    'complete inventory, so a phrase can be checked against it. In a room with a',
    'million things in it there is no inventory to check against, and “the big red',
    'one” means whatever the two of you have been talking about, which is a much',
    'harder problem and arguably not a problem about language at all.</p>',
    '<p>The second is planning. To clear the top of a block you move whatever is',
    'on it. Actions have a small number of preconditions and a small number of',
    'effects, and nothing else in the world changes when the arm moves, because',
    'there is nothing else. You may therefore write down what an action does and',
    'trust the description. Out in the corridor, moving one thing alters the dust,',
    'the balance, the light, the plans of the person walking towards you, and',
    'saying which of those changes matter is the whole difficulty.</p>',
    '<p class="fs-pull">A closed world is one you can hold entirely in the',
    'machine, and a world you can hold entirely is a world in which a plan can be',
    'checked before it is tried.</p>',
    '<p>The third is vision. A scene of flat-faced solid blocks under decent',
    'lighting can be reduced to line drawings, and the junctions where lines meet',
    'come in a small catalogue of types. Adolfo Guzmán’s SEE program grouped',
    'regions into bodies from those junctions; David Huffman and Max Clowes',
    'worked out the labelling of edges as convex, concave or occluding; David',
    'Waltz extended the catalogue to cope with shadows and cracks in his 1972',
    'thesis, and found that propagating the constraints between junctions pruned',
    'the possibilities down astonishingly fast. Waltz filtering is a genuinely',
    'good algorithm and it is still taught. It is also an algorithm about',
    'trihedral corners in good light.</p>',
    '<pre>',
    'WHAT THE WORLD CONTAINED (SHRDLU, as of the 1971 thesis)',
    '',
    '  objects .......  blocks (cubes), pyramids, a box, a table',
    '  colours .......  red, green, blue, white, black',
    '  sizes .........  large, small (relative, within the scene)',
    '  relations .....  ON, IN, AT, BEHIND, SUPPORTS, PART OF',
    '  actions .......  GRASP, MOVE, UNGRASP, PUT ON, PUT IN, CLEAR TOP',
    '  agents ........  one simulated arm, one questioner',
    '  vocabulary ....  a few hundred words, hand-built for this room',
    '',
    '  NOT PRESENT: friction, mass, breakage, ambiguity of purpose,',
    '  a second person, anything happening while nobody looked.',
    '</pre>',
    '<p><b>Planning in the room</b></p>',
    '<p>The blocks world became the standard testbed for planning as well as for',
    'language, and it is where the awkward cases were found. Gerald Sussman’s',
    'HACKER, written up in 1973, learned to debug its own plans by keeping a',
    'library of the ways a plan can go wrong. The problem now called the Sussman',
    'anomaly comes out of that work: two goals, each achievable on its own, which',
    'cannot be achieved one after the other without undoing the first. A planner',
    'that treats goals as independent parcels of work fails on three blocks. Not',
    'on three thousand. On three.</p>',
    '<div class="fs-aside"><p><b>Did you know</b></p><p>The copy demo, run in the',
    'lab around 1970 by Patrick Winston, Gerald Sussman, Eugene Freuder and',
    'others, put the pieces together on real hardware: a camera looked at a',
    'structure of actual wooden blocks, the program worked out what it was made',
    'of, and the arm built a copy. It took a long time, the lighting had to be',
    'right, and the blocks were painted matte so they would not glint. Everyone',
    'who saw it remembers it. It is also the demonstration Marvin Minsky later',
    'said pushed him towards the Society of Mind, because the only way to get the',
    'arm to behave was to have a great many small stupid processes arguing.</p></div>',
    '<img class="indie-pic" src="assets/media/web/mac/minsky-01.jpg" alt=""><span class="indie-cap">Marvin Minsky, 2006 (photo: Steamtalks, CC BY-SA 2.0)</span>',
    '<p><b>What did not carry out of the room</b></p>',
    '<p>The programme assumed that competence in a small world was the first',
    'increment of competence in a large one. That assumption turned out to be',
    'wrong, and it was wrong in an interesting way rather than a stupid one.</p>',
    '<p>Almost every technique that made the blocks world tractable depended on',
    'the world being closed. The line labeller depended on flat faces and straight',
    'edges. The planner depended on a complete list of what an action changes. The',
    'parser depended on a vocabulary written by hand for this table, and on the',
    'fact that a sentence could be turned into a little procedure that interrogated',
    'the scene. Take away the closure and you do not get a slightly worse program.',
    'You get no program, because the thing the program was exploiting has gone.</p>',
    '<blockquote class="fs-quote"><p>“an isolated meaningless domain”</p>',
    '<p>— Hubert Dreyfus’s verdict on the micro-world, <i>What Computers Can’t',
    'Do</i> (revised edition, 1979)</p></blockquote>',
    '<p>Dreyfus was disliked in the lab and he was right about this much: a small',
    'world is not a small piece of the big one. It is a separate place with its own',
    'physics, and the road from it to the kitchen does not exist. Terry Winograd',
    'himself came to something like the same conclusion within a decade and said so',
    'in public, which is more than most people manage about their own thesis.</p>',
    '<p>None of that makes the work worthless. Constraint propagation, plan repair,',
    'the whole vocabulary of preconditions and effects, procedural semantics, the',
    'discipline of building something that actually runs: all of it came out of the',
    'room and all of it is still in use. What did not come out was the promise.</p>',
    '<p>Read the program itself at <a href="shrdlu-blocks.geocities.ws">',
    'shrdlu-blocks</a>, and the research strategy that put the blocks on the table',
    'in the first place at <a href="micro-worlds.geocities.ws">micro-worlds</a>.</p>',
    '<hr>',
    '<p><small>visitors: 02174 · best viewed in Netscape at 800x600 · the memo',
    'list at the foot of this page is still under construction, i am waiting on a',
    'photocopy · last updated 14 Mar</small></p>',
    '<p><small>[ <a href="project-mac-ring.geocities.ws">Project MAC Ring</a> ]</small></p>',
  ]);

// ---- micro-worlds: the seminar hand-out --------------------------------------

const MICRO_WORLDS = P('micro-worlds.geocities.ws', 'MICRO-WORLDS',
  'MICRO-WORLDS // hand-out for the Tuesday seminar', [
    '<!--bg:mac-ideas-->',
    '<h1>MICRO-WORLDS: a research programme</h1>',
    '<p><small>hand-out for the Tuesday reading seminar, week 4. i have typed it up',
    'for the web because three people asked. this is a summary of an argument, not',
    'an endorsement of it, and we will spend most of the hour on the objections.',
    '— the seminar convenor</small></p>',
    '<hr>',
    '<p>The word is Marvin Minsky’s and Seymour Papert’s, and it names the method',
    'the MIT AI Lab ran on through the early 1970s. The proposal is short enough to',
    'state in one sentence. Rather than attack intelligence in general, choose a',
    'domain small enough to be understood completely, build a system that',
    'understands it completely, and then enlarge the domain.</p>',
    '<blockquote class="fs-quote"><p>“Each model, or ‘micro-world’ as we shall call',
    'it, is very schematic; it talks about a fairyland in which things are so',
    'simplified that almost every statement about them would be literally false if',
    'asserted about the real world.”</p>',
    '<p>— Minsky and Papert, MIT AI Laboratory progress report, 1970</p></blockquote>',
    '<p>Notice that they say it themselves, in the document asking for the money.',
    'This was not a hidden assumption that somebody else had to expose. The',
    'fairyland was declared. The bet was that fairylands could be joined up.</p>',
    '<p><b>The case for</b></p>',
    '<p>It is a good bet, and worth saying why before we knock it down. Physics got',
    'a long way with frictionless planes and point masses. A closed domain lets you',
    'know when a program has actually succeeded, which is otherwise very hard to',
    'establish in this field. It produces running code rather than manifestos. And',
    'it lets several groups work on different worlds at once with some hope of',
    'comparing results.</p>',
    '<p>The worlds themselves were various. The tabletop of blocks was the famous',
    'one. There was also a world of electronic circuits for the debugging work, a',
    'world of arch-like structures for Patrick Winston’s learning program, which',
    'induced the concept of an arch from examples and, importantly, from near',
    'misses, and a world of simple line drawings for the vision people. Each was a',
    'room with the door shut.</p>',
    '<div class="fs-aside"><p><b>Method or trap?</b></p><p>The seminar question. A',
    'toy problem is a legitimate scientific instrument when the thing you have',
    'simplified away is genuinely irrelevant to the mechanism you are studying. It',
    'is a trap when the thing you simplified away is the mechanism. The blocks',
    'world removed ambiguity, open-endedness and the need to decide what matters.',
    'Those turn out not to be noise on top of understanding. They are much closer',
    'to being what understanding is for.</p></div>',
    '<p><b>The case against</b></p>',
    '<p>The objection that did the damage is that a micro-world is not a subset of',
    'the world. It is a different world. The techniques that succeed inside it',
    'succeed because of the closure, so enlarging the domain does not extend them,',
    'it destroys their working conditions. Growth outward was assumed to be',
    'addition. It was subtraction of the only thing holding the programs up.</p>',
    '<p>Hubert Dreyfus pressed this from outside the field and was treated badly for',
    'it. The lab’s answer at the time was that he had no programs and therefore no',
    'standing. That answer looks weaker now than it did then.</p>',
    '<img class="indie-pic" src="assets/media/web/mac/minsky-01.jpg" alt=""><span class="indie-cap">Marvin Minsky, 2006 (photo: Steamtalks, CC BY-SA 2.0)</span>',
    '<p><b>For Tuesday</b></p>',
    '<p>Come with an answer to this: is there any micro-world whose lessons did',
    'transfer? Chess is the usual candidate offered and I do not think it works,',
    'because what transferred from chess was search, and search was not what the',
    'micro-world programme claimed to be testing. Bring a better candidate if you',
    'have one.</p>',
    '<p>Background reading is the tabletop itself at',
    '<a href="the-blocks-world.geocities.ws">the-blocks-world</a>, and for where',
    'Minsky went next, once he had accepted that a room full of facts was not',
    'enough, the structured-expectation idea at',
    '<a href="the-frame.geocities.ws">the-frame</a>.</p>',
    '<hr>',
    '<p><small>counter: 00913 · best viewed at 800x600 · photocopies of the 1970',
    'report are in the departmental library, ask at the desk · last updated 2 Oct',
    '</small></p>',
    '<p><small>[ <a href="project-mac-ring.geocities.ws">Project MAC Ring</a> ]</small></p>',
  ]);

// ---- the perceptron: the corrections page ------------------------------------

const PERCEPTRON = P('the-perceptron.geocities.ws', 'PERCEPTRON',
  'THE PERCEPTRON // please get this story right', [
    '<!--bg:mac-ideas-->',
    '<h1>THE PERCEPTRON, AND WHAT THE BOOK ACTUALLY SAID</h1>',
    '<p><small>a corrections page. i have now read the same wrong version of this',
    'story in four magazines and one textbook, so here it is with the maths in it.',
    'i am a graduate student, not a historian, and i have listed my sources at the',
    'bottom so you can check me. — p. avery</small></p>',
    '<hr>',
    '<p class="fs-epi">“the embryo of an electronic computer that [the Navy]',
    'expects will be able to walk, talk, see, write, reproduce itself and be',
    'conscious of its existence”<br>— the New York Times on the perceptron,',
    '8 July 1958</p>',
    '<p><b>1. What Rosenblatt built</b></p>',
    '<p>Frank Rosenblatt was a psychologist at the Cornell Aeronautical Laboratory.',
    'From 1957 he worked on the perceptron, a machine that learned to classify',
    'patterns by adjusting the strengths of its own connections. The Mark I',
    'Perceptron was real hardware: a grid of four hundred photocells looking at a',
    'card, weights held as the settings of potentiometers, and motors to turn the',
    'potentiometers when the machine got an answer wrong. You showed it examples.',
    'It changed itself. Nobody wrote the rule it ended up using.</p>',
    '<p>He also proved something. The perceptron convergence theorem says that if a',
    'set of examples can be separated by a straight cut through the space of',
    'inputs, the learning procedure will find such a cut in a finite number of',
    'steps. That is a real theorem and it is still true.</p>',
    '<p><b>2. What the 1969 book proved</b></p>',
    '<p>Marvin Minsky and Seymour Papert published <i>Perceptrons: An Introduction',
    'to Computational Geometry</i> with MIT Press in 1969. It is a mathematics',
    'book. It asks what a single layer of adjustable weights, sitting over a set of',
    'fixed local feature detectors, can and cannot compute, and it answers with',
    'proofs.</p>',
    '<img class="indie-pic" src="assets/media/web/mac/papert-01.jpg" alt=""><span class="indie-cap">Seymour Papert with the MIT Logo turtle (photo: Matematicamente.it, CC BY-SA 3.0)</span>',
    '<p>The small illustration everyone repeats is exclusive-or. A single layer',
    'draws one straight cut through the input space. Look at what has to be',
    'separated:</p>',
    '<pre>',
    '   A   B  | A XOR B        input space, with the two classes:',
    '  ---------------',
    '   0   0  |   0                B',
    '   0   1  |   1                ^',
    '   1   0  |   1              1 |  1        0',
    '   1   1  |   0                |',
    '                             0 |  0        1',
    '                                +------------> A',
    '                                   0        1',
    '',
    '  No single straight line puts both 1s on one side',
    '  and both 0s on the other.',
    '</pre>',
    '<p>The serious results in the book are not about XOR, which is a homework',
    'exercise. They are about parity and about connectedness, and they show that',
    'these need feature detectors whose size or whose fan-in grows with the size of',
    'the retina. That is a statement about scaling, and it is the interesting part,',
    'and it is the part nobody quotes.</p>',
    '<p><b>3. Three things the book did not do</b></p>',
    '<p>It did not prove that multi-layer networks cannot compute these functions.',
    'They plainly can. The theorems are about one adjustable layer.</p>',
    '<p>It did not claim that Rosenblatt was a fool or that the convergence theorem',
    'was wrong. The book is careful with his results.</p>',
    '<p>It did not, contrary to the legend, silently ignore the multi-layer case. It',
    'raised it and expressed a judgement about it:</p>',
    '<blockquote class="fs-quote"><p>“we consider it to be an important research',
    'problem to elucidate (or reject) our intuitive judgment that the extension is',
    'sterile”</p><p>— Minsky and Papert, <i>Perceptrons</i> (1969)</p></blockquote>',
    '<p>That is a guess, offered as a guess, and it was a wrong guess. It is not a',
    'theorem and it is not disguised as one.</p>',
    '<p><b>4. So what went wrong</b></p>',
    '<p>The reception went wrong. A precise result about one architecture was read',
    'across the field as a verdict on the whole idea of learning machines, and it',
    'was read that way by people who fund things as well as by people who do them.',
    'Through the 1970s connectionist work in the United States lost most of its',
    'support. Rosenblatt drowned in a boating accident in 1971, at forty-three,',
    'which removed the one person best placed to answer back. The training',
    'procedure for multi-layer networks that everyone now uses was described by',
    'Paul Werbos in his 1974 thesis and largely overlooked, and had to be',
    'rediscovered and popularised by David Rumelhart, Geoffrey Hinton and Ronald',
    'Williams in 1986 before anybody took it up.</p>',
    '<p class="fs-pull">The mathematics was correct. The inference the field drew',
    'from it was not, and the money followed the inference.</p>',
    '<p>Minsky and Papert brought out an expanded edition in 1988 with a new',
    'prologue and epilogue. They did not withdraw any of the proofs, because there',
    'was nothing to withdraw, and they rejected the account in which their book',
    'killed a field, pointing out that they had spent that decade arguing about',
    'representation rather than about connections. Papert had co-authored the book',
    'while running one of the most hands-on learning programmes in education, which',
    'is worth holding in mind before anyone paints him as the enemy of learning',
    'machines.</p>',
    '<p><b>5. The bit that is still unsettled</b></p>',
    '<p>Historians of the episode disagree about how much of the funding collapse',
    'the book actually caused. Neural-network research was competing for a shrinking',
    'pot with a symbolic programme that had louder claims and better institutional',
    'position, and the general cuts of the mid-1970s hit both. Blaming one book for',
    'a decade is tidy, and tidy accounts of funding are usually wrong.</p>',
    '<pre>',
    'SOURCES (what i actually read)',
    '  Rosenblatt, Principles of Neurodynamics, 1962',
    '  Minsky & Papert, Perceptrons, MIT Press 1969; expanded edition 1988',
    '  Rumelhart, Hinton & Williams, Nature, 1986',
    '  Olazaran, "A Sociological Study of the Official History of the',
    '    Perceptrons Controversy", Social Studies of Science, 1996',
    '  plus two interviews i cannot cite properly because they were over lunch',
    '</pre>',
    '<p>Papert’s other work, the part about children rather than about geometry, is',
    'at <a href="seymour-papert.geocities.ws">seymour-papert</a>. What the funding',
    'did next is at <a href="the-ai-winter.geocities.ws">the-ai-winter</a>.</p>',
    '<hr>',
    '<p><small>counter: 01608 · best viewed at 800x600 · corrections to my',
    'department address, and please cite a page number · last updated 21 Jan',
    '</small></p>',
    '<p><small>[ <a href="project-mac-ring.geocities.ws">Project MAC Ring</a> ]</small></p>',
  ]);

// ---- the frame: student coursework -------------------------------------------

const FRAME = P('the-frame.geocities.ws', 'THE FRAME',
  'FRAMES // 6.034 term paper, put on the web', [
    '<!--bg:mac-ideas-->',
    '<h1>FRAMES: knowledge as structured expectation</h1>',
    '<p><small>term paper for an artificial intelligence unit, second year, graded',
    'and handed back, now on the web because my tutor said it was clear and i have',
    'nothing else to put here. the bibliography at the foot is exactly as i',
    'submitted it, including the entry i could not find a page number for.',
    '— t. holloway</small></p>',
    '<hr>',
    '<p><b>Introduction</b></p>',
    '<p>In June 1974 Marvin Minsky circulated MIT AI Memo 306, “A Framework for',
    'Representing Knowledge”. It appeared the following year in Patrick Winston’s',
    'collection <i>The Psychology of Computer Vision</i>. It is not a program and',
    'it contains no theorems. It is a proposal about the shape memory has, and it',
    'went on to organise a large part of knowledge representation.</p>',
    '<blockquote class="fs-quote"><p>“A frame is a data-structure for representing a',
    'stereotyped situation, like being in a certain kind of living room, or going',
    'to a child’s birthday party.”</p>',
    '<p>— Minsky, “A Framework for Representing Knowledge”, 1974</p></blockquote>',
    '<p><b>The argument</b></p>',
    '<p>Minsky starts from a complaint about the logical tradition. If knowledge is',
    'a large flat set of true statements, then understanding an ordinary scene',
    'requires deriving what you need from that set, and there is far too much of it',
    'to search. People do not appear to work this way. When you walk into a room you',
    'do not deduce that it has a floor. You arrive already expecting one.</p>',
    '<p>So the proposal is that memory stores whole situations rather than isolated',
    'facts. A frame is a remembered scene with holes in it. The holes are called',
    'slots or terminals, they come pre-filled with default values, and the work of',
    'understanding is matching an incoming situation to a frame and then correcting',
    'the defaults where reality disagrees.</p>',
    '',
    '<pre>',
    'FRAME: ROOM',
    '  is-a .............. ENCLOSED-SPACE',
    '  floor ............. default: horizontal, load-bearing',
    '  walls ............. default: 4        [may be violated]',
    '  ceiling ........... default: present',
    '  door .............. default: 1, in a wall, human-sized',
    '  window ............ default: none     [if absent, no surprise]',
    '  light-source ...... default: overhead',
    '',
    'if a slot-filler contradicts the default, keep the frame and',
    'mark the exception; if too many contradict, the match has failed,',
    'so hand control to a neighbouring frame in the same system.',
    '</pre>',
    '<p><b>Frame-systems</b></p>',
    '<p>Frames are not stored singly. They come in systems whose members are related',
    'by the transformations that take you from one to another, so that the frames',
    'for the four walls of the same room are linked by the effect of turning your',
    'head, and share their fillers. This is Minsky’s answer to a vision problem: how',
    'a scene stays one scene when the viewpoint moves.</p>',
    '<p class="fs-pull">The default is the whole trick. It lets a system act on',
    'ordinary assumptions at once, and be corrected afterwards.</p>',
    '<p><b>Influence</b></p>',
    '<p>The idea spread quickly. Roger Schank and Robert Abelson’s scripts, in',
    '<i>Scripts, Plans, Goals and Understanding</i> (1977), are frames for events',
    'rather than for scenes, and the restaurant script is the example every',
    'undergraduate meets. Daniel Bobrow and Terry Winograd’s KRL, also 1977, was a',
    'representation language built on this family of ideas. Semantic networks',
    'acquired slots. The inheritance of default values from a general class to a',
    'particular case, with local exceptions allowed, is the pattern that later',
    'appears in object-oriented programming, and the resemblance is not a',
    'coincidence.</p>',
    '<p><b>Objections</b></p>',
    '<p>Two, from my reading. First, defeasibility: reasoning with defaults that can',
    'be overridden is not classical logic, and the formal work needed to make it',
    'respectable, non-monotonic logic, came afterwards and is still contested.',
    'Second, acquisition: nothing in the proposal says where the frames come from.',
    'Somebody has to write them, one situation at a time, and the number of ordinary',
    'situations is not small.</p>',
    '<p><b>A note on terminology, because i lost a mark for this</b></p>',
    '<p>The frame problem is a different thing. It is John McCarthy and Patrick',
    'Hayes, 1969, and it concerns how to state that most facts stay the same when an',
    'action occurs without listing them all. It is not Minsky’s frames, the names',
    'collide by accident, and mixing them up is a standard error.</p>',
    '<pre>',
    'BIBLIOGRAPHY',
    '  Minsky, M. "A Framework for Representing Knowledge",',
    '    MIT AI Memo 306, June 1974; in Winston (ed.),',
    '    The Psychology of Computer Vision, McGraw-Hill 1975',
    '  Schank, R. & Abelson, R. Scripts, Plans, Goals and',
    '    Understanding, Erlbaum 1977',
    '  Bobrow, D. & Winograd, T. "An Overview of KRL",',
    '    Cognitive Science 1(1), 1977',
    '  McCarthy, J. & Hayes, P. "Some Philosophical Problems from',
    '    the Standpoint of Artificial Intelligence", Machine',
    '    Intelligence 4, 1969',
    '  a photocopied lecture handout with no author on it (sorry)',
    '</pre>',
    '<p>Where the argument goes when the frames are stacked up into a whole mind:',
    '<a href="society-of-mind.geocities.ws">society-of-mind</a>. Where it came from,',
    'in the laboratory practice of shutting the door on a small domain:',
    '<a href="micro-worlds.geocities.ws">micro-worlds</a>.</p>',
    '<hr>',
    '<p><small>hits: 00446 · best viewed in Netscape at 800x600 · graded B+, the',
    'comment said “good on defaults, thin on the objections”, which is fair ·',
    'last updated 9 May</small></p>',
    '<p><small>[ <a href="project-mac-ring.geocities.ws">Project MAC Ring</a> ]</small></p>',
  ]);

// ---- society of mind: reading-group notes ------------------------------------

const SOCIETY_OF_MIND = P('society-of-mind.geocities.ws', 'SOC. OF MIND',
  'THE SOCIETY OF MIND // notes from the reading group', [
    '<!--bg:mac-ideas-->',
    '<h1>THE SOCIETY OF MIND</h1>',
    '<p><small>notes kept for a small reading group that met in a pub near the',
    'campus for eleven months and got through the whole book, one page-section at a',
    'time. we were three programmers, a nurse and a retired schoolteacher. these are',
    'my notes, so the emphases are mine. — the one who took the notes</small></p>',
    '<hr>',
    '<p class="fs-epi">“The power of intelligence stems from our vast diversity, not',
    'from any single, perfect principle.”<br>— Marvin Minsky, <i>The Society of',
    'Mind</i> (1986)</p>',
    '<p>Minsky published <i>The Society of Mind</i> in 1986, after roughly fifteen',
    'years of working the idea out, much of it in conversation with Seymour Papert.',
    'The book is built as a few hundred sections, each exactly one page, each with a',
    'title, arranged so that you can read them in order or wander. Several of us',
    'found the format irritating for the first month and then could not read',
    'anything else.</p>',
    '<p><b>The claim</b></p>',
    '<p>Mind is not a thing. It is what a very large number of small processes',
    'amount to when they are organised. Minsky calls the small processes agents.',
    'Each one is stupid. An agent that does nothing but keep a grip on a cup is not',
    'a little intelligence, it has no understanding of cups or of thirst, and if you',
    'looked inside it hoping to find a spark you would find a mechanism and be',
    'disappointed. Intelligence is the arrangement, not the material.</p>',
    '<p>The book’s worked example is a child building a tower and knocking it down,',
    'which Minsky treats as a committee: an agency called BUILDER, made of agents',
    'that find a block, grasp it, lift it, place it, and let go, with WRECKER in',
    'competition and PLAY over the top of both. Nothing in the committee is in',
    'charge in the way a person is in charge. Control passes about, and the',
    'appearance of a single intention is produced by the passing.</p>',
    '<div class="fs-aside"><p><b>Where it came from</b></p><p>Minsky said the idea',
    'grew directly out of the robot work at the laboratory: the attempt to get an',
    'arm and a camera to build with children’s blocks. Every time the team tried to',
    'write one coherent procedure for the task it failed, and every time they threw a',
    'crowd of narrow special-purpose routines at it, it worked a little better. He',
    'took that as evidence about minds and not merely about robot arms.</p></div>',
    '<p><b>Some machinery worth the price of the book</b></p>',
    '<p>K-lines, from his 1980 paper on memory: when a mental event goes well, run a',
    'wire through all the agents that were active, and later, pulling that wire',
    'partially restores the state that worked. Remembering becomes re-assembling',
    'rather than retrieving.</p>',
    '<p>Frames appear here too, as the way an agency holds its expectations. The',
    'earlier paper is set out at <a href="the-frame.geocities.ws">the-frame</a>.</p>',
    '<p>And a good deal on failure: on why a child cannot yet see that a tall thin',
    'glass and a short wide one hold the same water, which Minsky reads as two',
    'agents giving different answers with no agent yet appointed to settle between',
    'them. Piaget by way of engineering.</p>',
    '<img class="indie-pic" src="assets/media/web/mac/minsky-01.jpg" alt=""><span class="indie-cap">Marvin Minsky, 2006 (photo: Steamtalks, CC BY-SA 2.0)</span>',
    '<blockquote class="fs-quote"><p>“Minds are simply what brains do.”</p>',
    '<p>— Minsky, <i>The Society of Mind</i> (1986)</p></blockquote>',
    '<p><b>What the group could not agree on</b></p>',
    '<p>The nurse’s objection, which none of the programmers answered well: the book',
    'explains how a system might do a thing without any part of it understanding the',
    'thing, and then treats that as an account of understanding. Either the agents',
    'add up to somebody being there, in which case the adding-up is the whole',
    'question and is not described, or they do not, in which case the theory is about',
    'behaviour and should say so.</p>',
    '<p>The other complaint is methodological. Almost nothing here is stated so that',
    'it could fail. Agents can be posited for any capacity whatever, which makes the',
    'framework very easy to apply and correspondingly hard to test. Two of us thought',
    'this was fatal and three of us thought it was the normal condition of a new',
    'vocabulary in an early science.</p>',
    '<p>Minsky returned to the material in <i>The Emotion Machine</i> twenty years',
    'later, with emotions treated as ways of thinking rather than as interruptions to',
    'thought, which is the same architecture pointed at the part everybody says',
    'machines cannot have.</p>',
    '<p>More about the man, the laboratory he ran and the arguments he enjoyed:',
    '<a href="marvin-minsky.geocities.ws">marvin-minsky</a>.</p>',
    '<hr>',
    '<p><small>counter: 00738 · best viewed at 800x600 · the group has stopped',
    'meeting, the pub changed hands · reading list for the next book still under',
    'construction · last updated 30 Jul</small></p>',
    '<p><small>[ <a href="project-mac-ring.geocities.ws">Project MAC Ring</a> ]</small></p>',
  ]);

// ---- the ai winter: the oral-history timeline --------------------------------

const AI_WINTER = P('the-ai-winter.geocities.ws', 'AI WINTER',
  'THE AI WINTER // what the cuts were actually like', [
    '<!--bg:mac-ideas-->',
    '<h1>THE AI WINTER</h1>',
    '<p><small>i was a research assistant through the worst of it and i have grown',
    'tired of reading about the period as though it were a weather event that',
    'happened to nobody in particular. names, dates and committee reports below. i',
    'have left out the names of people who were made redundant. — j.m.b., formerly',
    'of this parish</small></p>',
    '<hr>',
    '<p>The phrase came later than the thing. It was used at the American',
    'artificial intelligence association’s meeting in 1984, in a panel where Roger',
    'Schank and Marvin Minsky warned the room that the enthusiasm around them would',
    'turn, the way a nuclear winter follows a flash. They were right, and the turn',
    'they predicted was the second one. The first had already happened to us.</p>',
    '<pre>',
    'A TIMELINE OF THE MONEY',
    '',
    '  1969  Mansfield Amendment: US defence funds must be tied to a',
    '        stated military mission. Open-ended laboratory grants',
    '        become harder to renew.',
    '  1972  Dreyfus, What Computers Can’t Do. Widely resented inside',
    '        the field, widely read outside it.',
    '  1973  Lighthill report to the UK Science Research Council.',
    '        BBC debate: Lighthill against Michie, McCarthy and',
    '        Gregory. UK support outside a few departments withdrawn.',
    '  1974  ARPA becomes DARPA in temperament as well as name;',
    '        programme managers ask what each grant is FOR.',
    '  1976  DARPA ends the Speech Understanding Research programme',
    '        after five years, judging the results not worth the',
    '        continuation.',
    '  1980  R1 (XCON) goes into service at Digital configuring',
    '        VAX orders. Expert systems become a business.',
    '  1982  Japan launches the Fifth Generation project. Western',
    '        governments respond with money and press releases.',
    '  1987  The specialist LISP hardware market collapses. Symbolics',
    '        and LMI are undone by ordinary workstations.',
    '  1988  Strategic Computing money redirected towards work with',
    '        nearer-term deliverables.',
    '  1992  Fifth Generation ends without the machines it promised.',
    '</pre>',
    '<p><b>Lighthill</b></p>',
    '<p>Sir James Lighthill was a fluid dynamicist, not an artificial intelligence',
    'man, which was rather the point of asking him. His 1973 survey divided the',
    'field into three: advanced automation, robotics as the bridge between the other',
    'two, and computer-based studies of the central nervous system. He allowed the',
    'first and third some merit and was severe about the middle, and his central',
    'technical charge was the combinatorial explosion, that methods which work on toy',
    'cases scale as the search space grows and stop working.</p>',
    '<blockquote class="fs-quote"><p>“In no part of the field have the discoveries',
    'made so far produced the major impact that was then promised.”</p>',
    '<p>— Lighthill, <i>Artificial Intelligence: A General Survey</i>, 1973</p></blockquote>',
    '',
    '<p>What made that sentence lethal was not its accuracy about the science. It',
    'was the word “promised”, and the fact that the promises were on file. They were',
    'in press releases and after-dinner speeches and interviews given to newspapers,',
    'made by people who knew perfectly well what their programs could do on a',
    'tabletop and let the sentence run anyway. A committee that wants to close you',
    'down does not need to understand your algorithms. It needs your own',
    'predictions, dated.</p>',
    '<p class="fs-pull">The laboratories were not caught out by their results. They',
    'were caught out by their publicity.</p>',
    '<div class="fs-aside"><p><b>What a cut looks like from inside</b></p><p>Not a',
    'closure. The building stays open. What goes is the margin: the second research',
    'assistant, the machine time after midnight, the travel money, the speculative',
    'project with no deliverable, the graduate student you would have taken on. Then',
    'the best people accept offers elsewhere, one at a time, over about three years,',
    'and each departure is reasonable, and at the end of it the group cannot do the',
    'thing it was good at and nobody can point at the day it stopped.</p></div>',
    '<p><b>The second winter</b></p>',
    '<p>The 1980s boom was built on expert systems and on hardware made to run one',
    'language. Both propositions were narrower than the investment assumed. Rule',
    'bases turned out to be expensive to maintain and brittle at their edges, and',
    'the specialist machines were overtaken by general workstations that were',
    'cheaper every year. When the hardware market went in 1987 it took a good deal',
    'of the field’s credibility with it, and for some years afterwards researchers',
    'wrote grant applications about knowledge-based systems, informatics, decision',
    'support, machine learning, anything but the two words on the door.</p>',
    '<p><b>What carried on</b></p>',
    '<p>This is the part the weather-event version leaves out. Knowledge',
    'representation kept developing. Planning became a proper subfield with',
    'benchmarks and competitions. The statistical approach to speech, which the',
    'cancelled programme had helped to start, went on quietly at a few sites and',
    'came good in the following decade. Connectionist work survived in psychology',
    'departments and at a handful of laboratories where nobody had told them to stop,',
    'and surfaced again in 1986. Logic programming had a whole European career. The',
    'money left. A number of people stayed at their desks.</p>',
    '<p>The book at the centre of one of these arguments is examined at',
    '<a href="the-perceptron.geocities.ws">the-perceptron</a>. The laboratory that',
    'lived on the ARPA contracts, and how it was organised, is at',
    '<a href="project-mac.geocities.ws">project-mac</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01245 · best viewed in Netscape at 800x600 · i will add the',
    'grant figures when i can find my old files, this section under construction ·',
    'a webring member since the ring began · last updated 3 Dec</small></p>',
    '<p><small>[ <a href="project-mac-ring.geocities.ws">Project MAC Ring</a> ]</small></p>',
  ]);

export const MAC_F = [BLOCKS_WORLD, MICRO_WORLDS, PERCEPTRON, FRAME, SOCIETY_OF_MIND, AI_WINTER];
