// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH DES_E — fashion. Pages an enthusiast, a student or a collector made
// about the couturiers and dressmakers they loved: the bias cut and the freed
// corset, the sculptor of cloth and the American Look, the London chiffon and
// the surrealist provocations. The names, dates and pieces are real; the
// affection and the marginalia are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Vionnet: the personal fan shrine (SHOWPIECE) ---------------------------

const VIONNET = P('madeleine-vionnet.geocities.ws', 'VIONNET',
  'THE BIAS CUT // a Madeleine Vionnet shrine', [
    '<!--bg:des-fashion-->',
    '<h1>THE ARCHITECT OF CLOTH</h1>',
    '<p><small>a shrine to Madeleine Vionnet (1876&ndash;1975), the greatest',
    'dressmaker who ever lived and the one nobody outside the trade seems to know.',
    'i found her through a museum caption and i have been obsessed ever since. i',
    'sew a little myself, badly, which is how i understand how impossible this is.',
    '&mdash; Ruth</small></p>',
    '<hr>',
    '<p class="fs-epi">"When a woman smiles, the dress must smile with her."<br>',
    '&mdash; Madeleine Vionnet</p>',
    '<p>She trained the hard way, apprenticed young, then years in the London and',
    'Paris houses before she opened her own on the avenue Montaigne in 1912, closed',
    'it for the war, and reopened in 1918. She hated the corset as much as anyone,',
    'but where others draped a fashionable line onto the body she did something',
    'stranger and more difficult. She cut cloth so that the dress hung from the',
    'body itself and moved when the body moved.</p>',
    '<h2>the bias, and why it matters</h2>',
    '<p>Woven cloth is stable along the warp and the weft, the two directions of',
    'its threads, and it has almost no give along them. Turn the pattern forty-five',
    'degrees, onto the true diagonal, the BIAS, and the same cloth suddenly',
    'stretches and clings and falls in a way it never does cut straight. Everyone',
    'knew the bias existed. Tailors used it in small pieces, a collar, a facing.',
    'Vionnet built whole gowns on it, and made the diagonal the whole grammar of a',
    'dress. That is the thing she is remembered for and it sounds simple and it is',
    'fiendishly hard, because bias cloth will not sit still while you work it.</p>',
    '<img class="indie-pic" src="assets/media/web/des/vionnet-01.jpg" alt=""><span class="indie-cap">A Vionnet bias-cut gown (RISD Museum, CC0)</span>',
    '<pre>',
    'THE BIAS, EXPLAINED FOR THE IMPATIENT',
    '  warp .......... the threads running the length of the roll',
    '  weft .......... the threads running across it',
    '  straight grain  cut along warp or weft; firm, holds its shape',
    '  cross grain ... cut along the weft; firm the other way',
    '  TRUE BIAS ..... cut at 45 degrees to both; stretches, drapes,',
    '                  clings, and will squirm out of true if you let it',
    '  the trick ..... hang the cut pieces for days before sewing so the',
    '                  cloth finishes stretching before the wearer does',
    '</pre>',
    '<p class="fs-aside"><b>a note on the half-scale mannequin.</b> She did not',
    'design flat on paper. She draped and pinned and cut on a small articulated',
    'wooden doll, a jointed mannequin about eighty centimetres high, turning the',
    'cloth on it like a sculptor turning clay before she ever scaled the pattern up',
    'to a living woman. The dress was worked out in three dimensions from the first',
    'because a bias dress only exists in three dimensions; laid flat it is a',
    'shapeless lozenge and tells you nothing.</p>',
    '<p>The results looked, on the hanger, like almost nothing: a few seams, a cowl,',
    'a handkerchief hem. On the body they became architecture. She used the Greek',
    'chiton and the kimono as ideas rather than costumes, letting a single width of',
    'silk crepe or satin spiral round the figure. No fastenings where she could',
    'help it, so many of her gowns simply pull on over the head and settle.</p>',
    '<blockquote class="fs-quote"><p>"I have never been able to tolerate the',
    'corset myself. Why should I have inflicted it on other women?"</p></blockquote>',
    '<p>She was fierce about the rights of the people who made the clothes, too. In',
    'her house there was proper daylight and rest and a clinic, and she took the',
    'copying of her designs to court because she believed the cut was the maker\'s',
    'to own. She even had her models photographed from several angles and',
    'registered, an early paper trail against the pirates.</p>',
    '<img class="indie-pic" src="assets/media/web/des/poiret-01.jpg" alt=""><span class="indie-cap">A Poiret gown, from the Gazette du Bon Ton (Rijksmuseum, CC0)</span>',
    '<p class="fs-pull">She did not decorate the body. She learned how cloth wants',
    'to fall, and then she let it.</p>',
    '<p>The house closed in 1939 as the next war came, and she never reopened it.',
    'She lived on until 1975, largely out of the public eye, while the trade that',
    'knew went on treating her as the dressmaker\'s dressmaker. If you only ever',
    'learn one name from behind the famous ones, learn hers.</p>',
    '<hr>',
    '<p>Where to go next. The man who cleared the ground before her, who threw out',
    'the corset with a showman\'s flourish while she threw it out with a scalpel,',
    'is Paul Poiret at <a href="paul-poiret.geocities.ws">paul-poiret</a>. And the',
    'one who took her structural nerve to its furthest, coldest extreme, cutting',
    'like an engineer, is Charles James at',
    '<a href="charles-james.geocities.ws">charles-james</a>. Both worth your',
    'afternoon.</p>',
    '<hr>',
    '<p><small>counter: 00512 &middot; best viewed at 800x600 &middot; this page',
    'is under construction, more scans to come when the library lets me &middot;',
    'last updated 21 Mar</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Poiret: the collector's / catalogue page -------------------------------

const POIRET = P('paul-poiret.geocities.ws', 'POIRET',
  'PAUL POIRET // a collector\'s catalogue', [
    '<!--bg:des-fashion-->',
    '<h1>PAUL POIRET &mdash; THE KING OF FASHION</h1>',
    '<p><small>a collector\'s pages. i deal in and hoard early twentieth-century',
    'fashion plates, pochoir albums and the odd surviving garment, and Poiret is',
    'the centre of my little cabinet. what follows is catalogue notes, not a',
    'biography. prices on request, most items NOT for sale.</small></p>',
    '<hr>',
    '<p>Paul Poiret (1879&ndash;1944) called himself the King of Fashion and for a',
    'decade before the First World War he very nearly was. He is the hinge between',
    'the nineteenth-century silhouette and the modern one. He did not invent the',
    'soft body, but he sold it to the world with more noise and colour than anyone,',
    'and he built the total look, the label, the perfume and the theatre of the',
    'house, that the whole industry still runs on.</p>',
    '<h2>the corset, out; the hobble, in</h2>',
    '<p>Around 1906 to 1908 he showed high-waisted, columnar dresses that hung from',
    'the shoulders and freed the waist from the boned corset. He liked to take the',
    'credit for killing the corset single-handed, which is a stretch, but he',
    'certainly staged its funeral. The catch, and it is a large catch, is that he',
    'freed the waist and then shackled the ankles: the HOBBLE SKIRT of around 1910',
    'was so narrow at the hem that a woman could only take tiny steps, and some',
    'wore a braid or a garter to stop themselves splitting it.</p>',
    '<img class="indie-pic" src="assets/media/web/des/poiret-01.jpg" alt=""><span class="indie-cap">A Poiret gown, from the Gazette du Bon Ton (Rijksmuseum, CC0)</span>',
    '<p class="fs-aside"><b>on the plates.</b> Two albums did more for his fame than',
    'any single dress. <i>Les Robes de Paul Poiret</i> (1908), drawn by Paul Iribe,',
    'and <i>Les Choses de Paul Poiret</i> (1911), drawn by Georges Lepape, are',
    'pochoir works, hand-stencilled in flat brilliant colour, and they sell the',
    'clothes as a mood and a world rather than a fitting. If you collect one thing',
    'from this period, collect these. Condition is everything; foxing on the Lepape',
    'is common and halves the value.</p>',
    '<p>Then the Orientalism. In 1911 he threw the party that everyone still talks',
    'about, the Thousand and Second Night, a fancy-dress fete on the theme of the',
    'Arabian Nights where he dressed his wife Denise and the guests as a sultan\'s',
    'court and unveiled his harem trousers and lampshade tunics in the middle of',
    'the spectacle. The turban, the aigrette, the jupe-culotte, the bold flat',
    'orange and violet and gold: this is the Poiret people picture, part couturier,',
    'part impresario.</p>',
    '<pre>',
    'A SHORT SHELF OF POIRET, FOR THE NEW COLLECTOR',
    '  1903  opens his own house in Paris',
    '  1908  Les Robes de Paul Poiret (plates by Iribe)',
    '  1910  the hobble skirt; the narrow hem',
    '  1911  Les Choses de Paul Poiret (plates by Lepape)',
    '  1911  the "Thousand and Second Night" party; Parfums de Rosine',
    '  1911  the Ecole Martine, his decorative-arts workshop',
    '  1914  the war interrupts everything',
    '  1929  bankrupt; the house is finished',
    '</pre>',
    '<p>He was also first, or near enough, to launch a couture PERFUME as part of',
    'the brand. Parfums de Rosine, named for a daughter, arrived in 1911, years',
    'before Chanel\'s No. 5. He wrapped the clothes, the scent and a whole applied-',
    'arts studio, the Ecole Martine, into one lifestyle you could buy into. The',
    'idea was brilliant and it outlived him by a century.</p>',
    '<p class="fs-pull">He dressed the pre-war dream, and when the dream changed he',
    'could not follow it.</p>',
    '<img class="indie-pic" src="assets/media/web/des/schiaparelli-01.jpg" alt=""><span class="indie-cap">A Schiaparelli evening gown, 1937 (photo: Joe Mabel, CC BY-SA 4.0)</span>',
    '<p>The decline is the sad part of the catalogue. He went off to the war, and',
    'the world that came back wanted the spare, short, easy line of the 1920s, the',
    'garconne, and Poiret\'s theatre looked heavy and old. He overspent, the house',
    'failed in 1929, and he died poor in 1944 while the industry he had helped',
    'invent was booming. The clothes in the museums now are worth fortunes he never',
    'saw.</p>',
    '<hr>',
    '<p>Cross-references in my cabinet. The woman who did the quiet, exacting',
    'version of the liberation he announced with trumpets is Madeleine Vionnet at',
    '<a href="madeleine-vionnet.geocities.ws">madeleine-vionnet</a>. And the next',
    'great showwoman of Paris, who out-shocked even him and feuded gloriously with',
    'Chanel, is Elsa Schiaparelli at',
    '<a href="elsa-schiaparelli.geocities.ws">elsa-schiaparelli</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00347 &middot; best viewed at 800x600 &middot; catalogue',
    'revised whenever a new lot comes in &middot; last updated 8 Feb</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Charles James: the academic summary ------------------------------------

const CHARLES_JAMES = P('charles-james.geocities.ws', 'CHARLES JAMES',
  'Charles James: the couturier as sculptor', [
    '<!--bg:des-fashion-->',
    '<h1>Charles James: the couturier as sculptor</h1>',
    '<p><small>a summary page maintained for a dress-history reading group. this is',
    'an overview with sources, not a fan tribute; corrections welcome by post.',
    '</small></p>',
    '<hr>',
    '<p>Charles James (1906&ndash;1978) was born in England, worked chiefly in New',
    'York, and is generally described as the only true couturier the United States',
    'produced. He made comparatively few garments and sold them at a loss as often',
    'as not, yet his reputation among designers is enormous, because he approached',
    'a dress less as a garment than as a construction problem in three dimensions.',
    'Balenciaga is reported to have called him the greatest, and Dior credited him',
    'as an influence on the New Look.</p>',
    '<h2>method</h2>',
    '<p>Where most couture proceeds from fabric and drape, James proceeded from',
    'structure. He built understructures of buckram, boning, horsehair and layered',
    'nets, engineered like the framing of a building, and only then clothed them in',
    'satin or velvet or faille. He thought in terms of weight and balance and the',
    'distribution of load, and he would rework a single sleeve or a single seam for',
    'years. Contemporaries record that he spoke of his gowns in the language of',
    'mathematics and sculpture rather than of fashion.</p>',
    '<pre>',
    'THE PRINCIPAL GOWNS',
    '  1937  the white satin "Taxi" dress (an earlier line; wraps to fasten)',
    '  1938  the down-filled evening jacket ("the Puffer\'s ancestor")',
    '  1947  the "Clover Leaf" / "Four-Leaf Clover" ball gown',
    '  1951  the "Swan" gown',
    '  1953  the "Tree" and the "Butterfly"',
    '  1954  the "Diamond" and further sculptural ball gowns',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/des/charles-james-01.jpg" alt=""><span class="indie-cap">A Charles James ball gown (photo: Rhododendrites, CC BY-SA 4.0)</span>',
    '<p>The best-known object is the CLOVER LEAF or Four-Leaf Clover gown of 1947,',
    'made for Austine Hearst, a strapless ball gown whose skirt spreads into four',
    'great curved lobes on a shaped and weighted understructure. It weighs several',
    'pounds and, by the maker\'s account, took an extraordinary number of hours and',
    'yards to build. The SWAN gown, with its dark tulle underskirt lifting a pale',
    'body, is the other signature: an evening dress that reads, from across a room,',
    'as a single sculptural mass.</p>',
    '<p class="fs-aside"><b>a note on the difficulty.</b> The record is candid that',
    'James was a difficult man: slow, litigious, chaotic with money, and hard on',
    'clients and staff alike. He completed few collections in the ordinary sense',
    'and left many pieces unfinished. Late in life he lived and worked at the',
    'Chelsea Hotel in New York, teaching and reworking his own patterns, treating',
    'his archive as a body of theory to be handed on.</p>',
    '<blockquote class="fs-quote"><p>"All my seams have meaning. They emphasise',
    'something about the body." <span class="cite">&mdash; attributed to Charles',
    'James</span></p></blockquote>',
    '<p>His importance for design history is that he detached cut from decoration',
    'and made the internal structure the true subject of the dress. The surface',
    'could be plain; the argument was underneath, in the geometry.</p>',
    '<hr>',
    '<p><small>Select reading. Coleman, E. A., <i>The Genius of Charles James</i>',
    '(Brooklyn Museum, 1982). Museum catalogue essays, Metropolitan Museum. Period',
    'press notices, various. (Group members: full citations in the shared folder.)',
    '</small></p>',
    '<hr>',
    '<p>Related pages in the ring. For the democratic opposite of James, American',
    'clothes made to be worn and washed and afforded, see Claire McCardell at',
    '<a href="claire-mccardell.geocities.ws">claire-mccardell</a>. For the showman',
    'who staged the freeing of the body a generation before, see Paul Poiret at',
    '<a href="paul-poiret.geocities.ws">paul-poiret</a>.</p>',
    '<hr>',
    '<p><small>hits: 00203 &middot; best viewed at 800x600 &middot; reading group',
    'pages &middot; last updated 14 Jan</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Claire McCardell: the personal fan shrine ------------------------------

const MCCARDELL = P('claire-mccardell.geocities.ws', 'MCCARDELL',
  'CLAIRE McCARDELL // clothes you can actually live in', [
    '<!--bg:des-fashion-->',
    '<h1>CLOTHES YOU CAN ACTUALLY LIVE IN</h1>',
    '<p><small>a fan page for Claire McCardell (1905&ndash;1958), by a woman who',
    'sews her own summer dresses and got tired of patterns that assume you have a',
    'maid to do you up at the back. Claire is my hero. she designed for people with',
    'jobs and no time. &mdash; Peg</small></p>',
    '<hr>',
    '<p>Everybody knows the Paris names. Almost nobody outside the trade knows',
    'Claire McCardell, and she is the one who dressed the actual twentieth-century',
    'woman, the one who worked, travelled, cooked her own dinner and dressed',
    'herself. She more or less invented what people came to call the AMERICAN LOOK:',
    'ready-to-wear, sporty, practical, affordable, and cut with real intelligence.</p>',
    '<p>She trained in New York and looked at Paris, and instead of copying the',
    'couture she asked a simpler and harder question. What does a woman need to be',
    'able to DO in this dress? Reach, bend, walk, pack it in a bag, wash it in a',
    'sink, put it on without help. Everything followed from that.</p>',
    '<h2>the pieces that mattered</h2>',
    '<p>The MONASTIC (1938) was the breakthrough: a dark, bias-cut tent of a dress',
    'with no waist seam at all, shapeless on the hanger, that you belted wherever',
    'suited YOUR body. One size did a lot of work and every woman made it her own.',
    'It sold and sold and was copied so fast it nearly ruined the firm, which tells',
    'you it was right.</p>',
    '<pre>',
    'THE McCARDELL TOOLKIT',
    '  the Monastic (1938) ... the waistless bias tent you belt yourself',
    '  the Popover (1942) .... wrap denim housedress, sold with an oven mitt',
    '  spaghetti ties ........ thin self-fabric ties instead of fussy fastenings',
    '  the "kitchen dinner"    dresses smart enough to cook and receive in',
    '  ballet flats .......... street shoes off the dance last, in matching colours',
    '  brass hooks, big studs  workwear hardware used as honest fastening',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/des/mccardell-01.jpg" alt=""><span class="indie-cap">A Claire McCardell day dress (RISD Museum, CC0)</span>',
    '<p>The POPOVER (1942) is my favourite thing in the history of clothes. Wartime,',
    'restrictions on everything, and Harper\'s Bazaar asked for a stylish outfit a',
    'woman could do her own housework in. Claire gave them a wrap dress in denim,',
    'proper hard-wearing workman\'s denim, and sold it WITH A MATCHING OVEN GLOVE',
    'stitched in, for a few dollars. A designer dress you could scrub the floor in.',
    'It flew off the rails and she kept a version of it in the line for years.</p>',
    '<p class="fs-aside"><b>a note on denim and the "everyday".</b> She took cloth',
    'that was supposed to be beneath fashion, denim, ticking, calico, cotton',
    'jersey, wool jersey, and made proper clothes out of it. Cheap, sturdy,',
    'washable, and cut so well the cheapness read as ease rather than poverty. She',
    'used the mattress-maker\'s topstitching and the workman\'s rivets and brass',
    'hooks as her ornament, honest fastenings you could actually manage yourself.</p>',
    '<blockquote class="fs-quote"><p>"I have always designed things I needed',
    'myself. It just turns out that other people need them too." <span class="cite">',
    '&mdash; Claire McCardell</span></p></blockquote>',
    '<p>She wrote a book, <i>What Shall I Wear?</i> (1956), that is really a small',
    'manifesto for common sense: buy less, buy well, dress for your own life. She',
    'died young, in 1958, at the height of it. If Paris gave us the dream, Claire',
    'McCardell gave us the wardrobe, and I know which one I wear on a Tuesday.</p>',
    '<hr>',
    '<p>Go and see. For the pure sculptor, the American genius who made a handful',
    'of impossible gowns while Claire made clothes for everyone, see Charles James',
    'at <a href="charles-james.geocities.ws">charles-james</a>. And for the London',
    'designer who a generation later made his own kind of easy, sexy, wearable',
    'modern clothes, see Ossie Clark at',
    '<a href="ossie-clark.geocities.ws">ossie-clark</a>.</p>',
    '<hr>',
    '<p><small>counter: 00631 &middot; best viewed at 800x600 &middot; still under',
    'construction, want to add the pattern diagrams &middot; last updated 2 May',
    '</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Ossie Clark: the exhibition write-up -----------------------------------

const OSSIE_CLARK = P('ossie-clark.geocities.ws', 'OSSIE CLARK',
  'Ossie Clark at the museum // an exhibition write-up', [
    '<!--bg:des-fashion-->',
    '<h1>Ossie Clark: a show, and some notes</h1>',
    '<p><small>notes written up after an afternoon at a retrospective of Ossie',
    'Clark. i went twice. these are my own impressions plus what was on the wall',
    'cards; any errors are mine, not the curators\'.</small></p>',
    '<hr>',
    '<p>Raymond "Ossie" Clark (1942&ndash;1996) was the great cutter of London in',
    'the 1960s and 1970s, the man who dressed the young and the beautiful and the',
    'famous, and, on the evidence of this show, one of the finest technicians of',
    'his generation anywhere. The rooms are arranged more or less by decade, and',
    'the thing that comes through, past all the biography, is the CUT.</p>',
    '<p>He was a northern grammar-school boy who went to the Royal College of Art',
    'and came out already brilliant. By the mid-sixties he was at QUORUM, the',
    'Chelsea boutique that was the centre of the whole scene, and the King\'s Road',
    'set, the models, the Rolling Stones and their circle, came to him. The wall',
    'card had the famous line that you could tell an Ossie Clark dress with your',
    'eyes shut, by the way it moved.</p>',
    '<img class="indie-pic" src="assets/media/web/des/ossie-clark-01.jpg" alt=""><span class="indie-cap">An Ossie Clark trouser suit (photo: Elisa.rolle, CC BY-SA 4.0)</span>',
    '<p>Room two is the heart of it: the BIAS-CUT dresses in chiffon and crepe, the',
    'craft he took, knowingly, straight from Vionnet\'s generation and made new. He',
    'understood, as few of his contemporaries did, how a diagonally cut cloth falls',
    'and clings and swings, and he cut low and soft and close in a way that looked',
    'effortless and was anything but. There is real tailoring underneath the',
    'romance: snake-hipped jackets, precise armholes, a hem that hangs dead level',
    'on the true bias.</p>',
    '<p class="fs-aside"><b>a note on the prints.</b> Half the magic in these rooms',
    'is not his alone. The prints are by CELIA BIRTWELL, the textile designer he',
    'married, and the partnership is the point. Her small, painterly florals and',
    'art-deco revivals and stars, printed on his chiffon and moss crepe, are why an',
    'Ossie Clark dress looks like nothing else. Dress and cloth were designed',
    'together, which is why the pattern always sits right on the seam.</p>',
    '<blockquote class="fs-quote"><p>"He cut like a dream. The dresses moved before',
    'the woman did." <span class="cite">&mdash; a fellow designer, quoted on the',
    'exhibition wall</span></p></blockquote>',
    '<p>The last room turns the show. He was a showman, and his catwalk shows in the',
    'early seventies were among the first to be staged as full spectacle, with music',
    'and models who played to the room, an event as much as a sale. But the story',
    'darkens. The business sense never matched the talent, the licences and the',
    'money went wrong, the marriage to Birtwell ended, and the decade turned',
    'against him. He died in 1996, his reputation only then beginning to recover,',
    'which is part of why a retrospective like this one matters.</p>',
    '<p class="fs-pull">You could tell the dress was his before you saw the label,',
    'from the way it caught the air.</p>',
    '<p>The famous double portrait of Clark and Birtwell by David Hockney hangs',
    'elsewhere, not in this show, but the curators nod to it, and rightly, because',
    'it fixed the pair as the image of a certain London moment.</p>',
    '<hr>',
    '<p>The show sends you two ways in the ring. Back to the source of the bias he',
    'loved, Madeleine Vionnet at',
    '<a href="madeleine-vionnet.geocities.ws">madeleine-vionnet</a>. And across to',
    'the American who solved the same problem, easy modern clothes for real lives,',
    'from the other direction, Claire McCardell at',
    '<a href="claire-mccardell.geocities.ws">claire-mccardell</a>.</p>',
    '<hr>',
    '<p><small>counter: 00288 &middot; best viewed at 800x600 &middot; written up',
    'the week the show closed &middot; last updated 30 Sep</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Schiaparelli: the student coursework -----------------------------------

const SCHIAPARELLI = P('elsa-schiaparelli.geocities.ws', 'SCHIAPARELLI',
  'SURREALISM ON THE BODY // coursework (Schiaparelli)', [
    '<!--bg:des-fashion-->',
    '<h1>Surrealism on the Body: Elsa Schiaparelli</h1>',
    '<p><small>DHIST 214, Dress and Modern Art, essay 2. student no. withheld.',
    'word count 1,480 (over, sorry). this is my coursework put up on my own pages',
    'so my study group can read it. do not nick it, the tutor uses the software.',
    '</small></p>',
    '<hr>',
    '<p>This essay argues that Elsa Schiaparelli (1890&ndash;1973) was the one',
    'couturier who treated a dress as a work of Surrealist art, and that her',
    'clothes are best understood next to the paintings of her friends rather than',
    'next to the other fashion houses of the 1930s.</p>',
    '<p>Schiaparelli was Italian, born in Rome, self-taught, and she arrived in',
    'fashion sideways, through knitwear. Her first hit, around 1927, was a hand-',
    'knitted sweater with a TROMPE-L\'OEIL bow knitted into it, a flat pattern that',
    'read from across the street as a real bow tied at the neck. The trick, a',
    'picture of a thing standing in for the thing, is already pure Surrealism, and',
    'it set the pattern for everything after.</p>',
    '<h2>the collaborations</h2>',
    '<p>Her most discussed work came out of working directly with artists, above all',
    'Salvador Dali. The results are the pieces every textbook reproduces:</p>',
    '<pre>',
    'THE SURREALIST PIECES (approx. dates)',
    '  1927  the trompe-l\'oeil bow sweater',
    '  1937  the Lobster Dress (white silk, a Dali lobster printed on the skirt)',
    '  1937  the Shoe Hat (a hat in the shape of an upturned shoe)',
    '  1937  "shocking pink" launched with the scent "Shocking"',
    '  1938  the Tears Dress (a print of trompe-l\'oeil rips, with Dali)',
    '  1938  the Skeleton Dress (quilted to raise the bones, with Dali)',
    '  1938  the Circus and Pagan and Zodiac collections',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/des/schiaparelli-01.jpg" alt=""><span class="indie-cap">A Schiaparelli evening gown, 1937 (photo: Joe Mabel, CC BY-SA 4.0)</span>',
    '<p>The LOBSTER DRESS of 1937 is the famous one: a simple pale evening gown with',
    'a single enormous lobster, drawn by Dali, printed across the front of the',
    'skirt. (Dali apparently wanted to spread real mayonnaise on it, and',
    'Schiaparelli, sensibly, said no.) The SHOE HAT, worn by her and by Gala Dali,',
    'is a woman\'s high-heeled shoe turned upside down and worn on the head, absurd',
    'and elegant at once, which is the whole Surrealist joke about ordinary objects',
    'made strange.</p>',
    '<p>Then there is the colour. In 1937 she launched a brilliant, hot, almost',
    'fluorescent pink she named SHOCKING PINK, and built a perfume, "Shocking",',
    'around it, in a bottle modelled on the torso of the actress Mae West. She',
    'made a signature of a single loud colour years before it was ordinary to do',
    'so, and the name stuck to the shade for good.</p>',
    '<p class="fs-aside"><b>note on method (for the tutor).</b> I am reading the',
    'clothes as objects in the Surrealist programme: the trompe-l\'oeil, the',
    'displaced everyday object (the shoe, the lobster), the body made strange (the',
    'skeleton, the tears). The argument is that Schiaparelli is not "influenced by"',
    'Surrealism, she is a participant in it, working in cloth the way Dali worked in',
    'paint.</p>',
    '<p>And the rivalry, which is half the fun of the period. Across Paris was',
    'COCO CHANEL, and the two could not have been more opposed. Chanel stood for',
    'restraint, the little black dress, expensive plainness, and she called',
    'Schiaparelli, witheringly, "that Italian artist who makes clothes". Where',
    'Chanel wanted a woman to disappear into good taste, Schiaparelli wanted her to',
    'arrive as an event. The feud ran for years and both of them enjoyed it.</p>',
    '<blockquote class="fs-quote"><p>"In difficult times fashion is always',
    'outrageous." <span class="cite">&mdash; Elsa Schiaparelli</span></p></blockquote>',
    '<p>The war closed her real moment, as it closed Vionnet\'s and Poiret\'s, and',
    'her house never fully recovered its pre-war invention. But the argument of this',
    'essay stands: for a decade in the 1930s she made fashion a branch of modern',
    'art, and no one has quite matched the nerve of it since.</p>',
    '<hr>',
    '<p><small>Bibliography (rough, will tidy for the final).<br>',
    'Schiaparelli, E. <i>Shocking Life</i>. 1954. (her own memoir, use with care)<br>',
    'Blum, D. E. <i>Shocking! The Art and Fashion of Elsa Schiaparelli</i>, Philadelphia, 2003.<br>',
    'White, P. <i>Elsa Schiaparelli</i>. 1986.<br>',
    'lecture notes, weeks 5 and 6 (Surrealism and the object).<br>',
    'that museum website with the Lobster Dress, name to find.</small></p>',
    '<hr>',
    '<p>See also, for the study group. The showman who ran Paris before her and set',
    'the template of the couturier-as-impresario, Paul Poiret at',
    '<a href="paul-poiret.geocities.ws">paul-poiret</a>. And, for a very different',
    'kind of art-into-clothes a generation later, the London prints of Ossie Clark',
    'at <a href="ossie-clark.geocities.ws">ossie-clark</a>.</p>',
    '<hr>',
    '<p><small>counter: 00174 &middot; best viewed at 800x600 &middot; my pages,',
    'my opinions, not the university\'s &middot; last updated 5 Dec &middot;',
    '&mdash; signed, a tired second-year</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

export const DES_E = [VIONNET, POIRET, CHARLES_JAMES, MCCARDELL, OSSIE_CLARK, SCHIAPARELLI];
