// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH DES_C — textiles & rugs.
//
// Cached fan-made pages about the great textile designers and the firms and
// workshops behind the cloth: a firm's own showpiece for Morris and Company;
// a course summary of Anni Albers and the Bauhaus loom; a fan shrine to
// Lucienne Day; a collector's page for Dorothy Liebes; an exhibition write-up
// for Jack Lenor Larsen; and a student's coursework on Sonia Delaunay. The
// names, dates and pieces are real; the enthusiasm and the wonky bibliography
// are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Morris and Company: the firm's own showpiece ---------------------------

const MORRIS_AND_CO = P('morris-and-co.geocities.ws', 'MORRIS & CO',
  'MORRIS &amp; COMPANY — the printed and woven cloth', [
    '<!--bg:des-textiles-->',
    '<h1>MORRIS &amp; COMPANY</h1>',
    '<p class="fs-epi"><i>The textiles page of the firm. If you came looking for',
    'the politics and the lectures, that is another shrine altogether. Here we',
    'keep the cloth.</i></p>',
    '<p>These pages are kept by admirers of Morris and Company, the decorating',
    'firm founded in 1861 and reconstituted under William Morris in 1875. The firm',
    'made stained glass, furniture, wallpaper and much else, but this corner is for',
    'the woven and printed textiles, which many hold to be the finest thing it ever',
    'did. The patterns are still in production more than a century on, which tells',
    'you the drawing was sound.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Have nothing in your houses that you do',
    'not know to be useful, or believe to be beautiful.&rdquo;</p>',
    '<p><small>&mdash; William Morris, from the 1880 lecture &ldquo;The Beauty of',
    'Life&rdquo;</small></p></blockquote>',
    '<p>The firm moved its works to Merton Abbey on the river Wandle in Surrey in',
    '1881, and it was there that the textiles came into their own. Morris wanted',
    'the old vegetable dyes back, indigo for blue, madder for red, weld for yellow,',
    'walnut for brown, at a time when the trade had gone over wholesale to the new',
    'aniline colours. He thought the chemical dyes crude and fugitive, and he went',
    'to old dye-books and to the indigo vat to learn the slow way again.</p>',
    '<img class="indie-pic" src="assets/media/web/des/morris-textile-01.jpg" alt=""><span class="indie-cap">Morris &amp; Co, Strawberry Thief (public domain)</span>',
    '<div class="fs-aside"><p><b>A note on indigo discharge.</b> The most demanding',
    'of the printed cloths were made by the indigo-discharge method. The whole',
    'length was dyed blue in the vat first, and the pattern was then bleached back',
    'out of it with a discharge paste, and other colours printed into the cleared',
    'ground. It is the hard way round, printing by taking colour away rather than',
    'laying it on, and Strawberry Thief (1883) is its masterpiece.</p></div>',
    '<p>The name of that pattern comes from the thrushes Morris watched stealing',
    'fruit in the kitchen garden at Kelmscott Manor. Willow Bough (1887) is the',
    'quieter companion, a wallpaper drawing turned to cloth, all leaves and no',
    'flowers, and it may be the most loved thing the firm produced. Both are still',
    'printed from the drawings today.</p>',
    '<p class="fs-pull">&ldquo;If you want a golden rule that will fit everybody,',
    'this is it: have nothing in your houses that you do not know to be useful, or',
    'believe to be beautiful.&rdquo;</p>',
    '<p>The woven cloths are a separate craft again, worked on the drawloom and the',
    'Jacquard: Peacock and Dragon, Bird, Tulip and Rose, the heavy woollen hangings',
    'that dress a cold room. Morris studied historic weaving, French and Italian and',
    'Persian, and his friend and collaborator on the later work was John Henry',
    'Dearle, who trained in the shop and in time designed many of the patterns sold',
    'under the Morris name. Give Dearle his due; a good deal of what people call',
    '&ldquo;Morris&rdquo; is Dearle.</p>',
    '<pre>THE GREAT PATTERNS (a members&rsquo; short list)\n' +
    '-------------------------------------------------\n' +
    'Marigold ....... 1875 .. printed cotton\n' +
    'Honeysuckle .... 1876 .. printed, drawn by May Morris\n' +
    'Bird ........... 1878 .. woven wool, for his own walls\n' +
    'Peacock &amp; Dragon 1878 .. woven wool hanging\n' +
    'Strawberry Thief 1883 .. indigo-discharge print\n' +
    'Cray ........... 1884 .. the richest of the printed chintzes\n' +
    'Willow Bough ... 1887 .. printed cotton\n' +
    'Compton ........ 1896 .. Dearle, the last great pattern</pre>',
    '<img class="indie-pic" src="assets/media/web/des/albers-01.jpg" alt=""><span class="indie-cap">A jacquard weaving design by Anni Albers (public domain)</span>',
    '<p>The honeycomb of pattern is the thing to understand about a Morris repeat.',
    'The eye is never let rest on a blank; a diagonal growth of stem carries you on',
    'to the next flower and the next, so the surface reads as a living thicket',
    'rather than a stamped grid. It is dense and it is calm at once, and no one has',
    'quite matched it.</p>',
    '<p>For where the firm&rsquo;s ideas went next, the weaving workshop of the',
    'Bauhaus took up the structural side of cloth: see',
    '<a href="anni-albers.geocities.ws">anni-albers</a>. And for the British',
    'thread carried into the modern age, post-war and abstract but still botanical,',
    'see <a href="lucienne-day.geocities.ws">lucienne-day</a>.</p>',
    '<p><small>hits: 03120 · best viewed at 800x600 · a Merton Abbey appreciation',
    'page · this corner still under construction, the woven cloths need better',
    'pictures · last updated 14 Mar</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Anni Albers: the course summary ----------------------------------------

const ANNI_ALBERS = P('anni-albers.geocities.ws', 'ANNI ALBERS',
  'Anni Albers // weaving as a structural art', [
    '<!--bg:des-textiles-->',
    '<h1>Anni Albers: weaving as a structural art</h1>',
    '<p><small>a summary page prepared for a design-history reading group. corrections',
    'welcome. sources listed at the foot.</small></p>',
    '<hr>',
    '<p>Anni Albers (1899&ndash;1994), born Annelise Fleischmann in Berlin, is the',
    'weaver who did more than anyone to argue that cloth is a serious art of',
    'structure and not a soft decorative afterthought. She reached the loom almost',
    'by default. When she entered the Bauhaus in Weimar in 1922 the more prestigious',
    'workshops were effectively closed to women, and the weaving workshop was where',
    'they were steered. She made it the intellectual centre of the school&rsquo;s',
    'work in textiles.</p>',
    '<p>At the Bauhaus she worked toward the idea of the functional fabric: cloth',
    'designed for what it had to do. Her diploma piece in 1930 was a sound-absorbing,',
    'light-reflecting wall covering for an auditorium, a woven material engineered',
    'to a brief, cellophane on one face for reflectance and chenille on the other',
    'for absorption. That is not decoration, that is a solved problem in thread.</p>',
    '<img class="indie-pic" src="assets/media/web/des/albers-01.jpg" alt=""><span class="indie-cap">A jacquard weaving design by Anni Albers (public domain)</span>',
    '<div class="fs-aside"><p><b>Warp and weft, plainly.</b> The warp is the set of',
    'threads held under tension the length of the loom; the weft is the thread',
    'carried across and over and under them. Every woven structure is a decision',
    'about how weft crosses warp. Albers&rsquo;s claim was that this grid of',
    'crossings is a discipline in its own right, closer to building than to',
    'painting, and that a weaver thinks in it the way an architect thinks in',
    'load.</p></div>',
    '<p>When the Nazis forced the Bauhaus shut in 1933, Anni and her husband Josef',
    'Albers left for the United States and for Black Mountain College in North',
    'Carolina, the experimental school in the hills where both taught for years. It',
    'was there, and on her travels in Mexico and Peru, that she deepened her study',
    'of the ancient Andean weavers, whom she called her great teachers. She read',
    'pre-Columbian cloth as a language, a way of setting down meaning in structure',
    'before and without writing.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Threads and the events that happen to',
    'them are what a weaver deals with.&rdquo;</p>',
    '<p><small>&mdash; Anni Albers, <i>On Weaving</i> (1965)</small></p></blockquote>',
    '<p>She drew a distinction that the reading group kept coming back to: between',
    'the <i>pictorial</i> weavings, her free framed pieces meant to be hung and',
    'looked at as one looks at a picture, and the <i>designed</i> fabrics meant to',
    'be woven by the yard for use. She held both in one hand. In 1949 the Museum of',
    'Modern Art in New York gave her a solo exhibition, the first it had ever given',
    'a textile artist, which settled the argument about whether weaving was art in',
    'her favour and in public.</p>',
    '<img class="indie-pic" src="assets/media/web/des/delaunay-01.jpg" alt=""><span class="indie-cap">Sonia Delaunay, Simultaneous Contrasts (photo: J-P Dalbera, CC BY 2.0)</span>',
    '<p>Her book <i>On Weaving</i> (1965) is still the one to read. It is patient',
    'and technical and quietly radical, moving from the bare mechanics of the loom',
    'to the place of cloth in the history of building meaning. Late in life she',
    'turned largely to printmaking, but the thinking is all of a piece; the prints',
    'are the grid by other means.</p>',
    '<p>For the tradition of pattern she partly reacted against, the printed and',
    'woven cloth of the great firm, see',
    '<a href="morris-and-co.geocities.ws">morris-and-co</a>. For a contemporary who',
    'carried colour and geometry from painting straight into cloth, see',
    '<a href="sonia-delaunay.geocities.ws">sonia-delaunay</a>.</p>',
    '<pre>READING GROUP BIBLIOGRAPHY (as handed round, unchecked)\n' +
    '-------------------------------------------------------\n' +
    'Albers, A. On Weaving. Wesleyan Univ. Press, 1965.\n' +
    'Albers, A. Anni Albers: On Designing. (essays)\n' +
    'Weber &amp; Asbaghi. Anni Albers. Guggenheim, 1999.\n' +
    '(someone please confirm the Weber year, i wrote it from memory)</pre>',
    '<p><small>visitors: 01488 · best viewed at 800x600 · design-history reading',
    'group, meets fortnightly · page last tended 9 Feb</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Lucienne Day: the fan shrine -------------------------------------------

const LUCIENNE_DAY = P('lucienne-day.geocities.ws', 'LUCIENNE DAY',
  'CALYX and after // a Lucienne Day shrine', [
    '<!--bg:des-textiles-->',
    '<h1>CALYX and after</h1>',
    '<p><small>a shrine to Lucienne Day (1917&ndash;2010), the woman who put spindly',
    'little abstract plants on the nation&rsquo;s curtains and made post-war Britain',
    'feel modern. i inherited a length of her cloth from my nan and fell down the',
    'rabbit hole. — Ros</small></p>',
    '<hr>',
    '<p>Here is the moment. It is 1951, the Festival of Britain, the country still on',
    'ration books and wanting badly to feel like the future had arrived. Lucienne',
    'Day designs a furnishing fabric called CALYX for the Homes and Gardens Pavilion,',
    'to hang in a room set by her husband Robin Day. Thin black stems, little cups',
    'and saucers of colour balanced on them like a mobile, mustard and olive and',
    'that particular acid chartreuse, all floating on a warm ground. Nobody in',
    'British furnishing was drawing like that. It looked like a Miro had learned to',
    'behave itself and go to work.</p>',
    '<p>The firm that made it, Heal&rsquo;s, were nervous. The story goes they did',
    'not expect it to sell and priced the licence low. It sold and sold, it won a',
    'gold medal at the Milan Triennale in 1951 and a prize in the United States, and',
    'it made her name overnight. Calyx is the pattern people mean when they say',
    '&ldquo;that Festival of Britain look&rdquo;.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I wanted to design things which were',
    'contemporary, which had nothing to do with what had happened before.&rdquo;</p>',
    '<p><small>&mdash; Lucienne Day</small></p></blockquote>',
    '<p>What i love is that the botanical never fully leaves. They are abstract',
    'patterns, yes, but there is always a stem, a leaf, a seed-head hiding in the',
    'geometry. She trained as a painter at the Royal College of Art and you can see',
    'the painter choosing the colours: strange, off, beautifully judged combinations',
    'that should clash and do not.</p>',
    '<img class="indie-pic" src="assets/media/web/des/lucienne-day-01.jpg" alt=""><span class="indie-cap">Calyx, by Lucienne Day (Robin and Lucienne Day Foundation, CC BY-SA 4.0)</span>',
    '<p>After Calyx came a whole decade of them for Heal&rsquo;s. Dandelion Clocks,',
    'Spectators, Herb Antony, Graphica, Sunflower. She worked across ceramics and',
    'carpets and table linen too, and later in life she made one-off &ldquo;silk',
    'mosaics&rdquo;, painstaking pieced silk hangings, when she wanted to work with',
    'her own hands again rather than for the factory.</p>',
    '<p class="fs-pull">Robin did the chairs, Lucienne did the cloth, and between',
    'them they furnished a whole idea of how a modern Briton might live.</p>',
    '<p>She and Robin Day were a design partnership as much as a marriage, the press',
    'loved to call them Britain&rsquo;s answer to the Eameses, which is a lazy line',
    'but not a wrong one. He designed the moulded polypropylene chair you have sat on',
    'in every school hall in the country; she dressed the same modern rooms in cloth.</p>',
    '<p>Two doors to knock on. For the American who was doing something completely',
    'different with colour and metal thread at the same moment, see',
    '<a href="dorothy-liebes.geocities.ws">dorothy-liebes</a>. And for the Bauhaus',
    'weaver whose thinking about structure sits behind so much of the modern loom,',
    'see <a href="anni-albers.geocities.ws">anni-albers</a>.</p>',
    '<p><small>counter: 00967 · best viewed at 800x600 · made on a rainy bank',
    'holiday · under construction, more scans of nan&rsquo;s cloth to come · last',
    'updated 22 May — Ros</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Dorothy Liebes: the collector's page -----------------------------------

const DOROTHY_LIEBES = P('dorothy-liebes.geocities.ws', 'DOROTHY LIEBES',
  'The Liebes Look // a collector&rsquo;s notes', [
    '<!--bg:des-textiles-->',
    '<h1>The Liebes Look: a collector&rsquo;s notes</h1>',
    '<p><small>notes and provenance kept by a collector of mid-century American hand-',
    'weaving. if you have a documented Liebes sample to sell or trade, do get in',
    'touch through the ring.</small></p>',
    '<hr>',
    '<p>Dorothy Liebes (1897&ndash;1972) has fair claim to the title the trade gave',
    'her, the mother of modern weaving in America. She ran a hand-weaving studio,',
    'first in San Francisco from the early 1930s and later in New York, and out of',
    'it came a look so distinctive that people simply called it the Liebes Look:',
    'high, singing colour, and the glint of unexpected materials worked into the',
    'weft.</p>',
    '<p>Where a purist wove wool and linen, Liebes wove in whatever caught the',
    'light. Metallic threads, cellophane, leather strips, bamboo, sequins, plastic,',
    'and above all Lurex, the metallised yarn she took up early and championed. She',
    'made cloth that shone. A Liebes fabric in a room did something to the light',
    'that plain cloth could not, and the decorators of the 1940s and 50s wanted it',
    'badly.</p>',
    '<img class="indie-pic" src="assets/media/web/des/liebes-01.jpg" alt=""><span class="indie-cap">A Dorothy Liebes weaving on a Rohde chair (photo: Sailko, CC BY 3.0)</span>',
    '<div class="fs-aside"><p><b>On identifying a Liebes sample.</b> Look for the',
    'high-contrast colour, often a warp of many close hues read as one shimmer, and',
    'look for the odd material in the weft: a filament of metal, a ribbon of',
    'cellophane, a bamboo slat. The hand is firm and the selvedge clean. Beware',
    'later industrial cloth sold as &ldquo;Liebes style&rdquo;; the studio pieces',
    'and the documented mill collaborations are the ones that hold their',
    'value.</p></div>',
    '<p>The important thing for the collector to grasp is that Liebes was the bridge',
    'between the hand loom and the mill. She hand-wove the sample, the beautiful',
    'one-off, and then worked with industry to translate it into cloth that could be',
    'made by the mile. She consulted for the great fibre companies, for DuPont and',
    'others, telling the chemists what a weaver actually wanted from a synthetic',
    'yarn, and she styled colour ranges for whole industries. Much American',
    'furnishing colour of the 1950s passed across her desk.</p>',
    '<pre>IN MY CASES (documented pieces &amp; ephemera)\n' +
    '---------------------------------------------\n' +
    '- sample card, metallic weft on cotton warp, San Francisco studio\n' +
    '- length, Lurex &amp; wool, chartreuse/rose, mill collaboration\n' +
    '- colour-range card produced for a fibre company, mounted\n' +
    '- exhibition leaflet, Decorative Arts, Golden Gate Expo 1939\n' +
    '(the 1939 leaflet is the prize; she directed a weaving display there)</pre>',
    '<p>She won the industry&rsquo;s Craftsmanship medals and showed at the great',
    'fairs, and yet her name faded faster than it should have after her death, in',
    'part because so much of her best work went out anonymously into industry rather',
    'than under her own label. Collectors are quietly putting the record back',
    'together.</p>',
    '<p>Two names for the ring. For the designer who took the theatrical, textural',
    'weave into architecture and the loft, see',
    '<a href="jack-lenor-larsen.geocities.ws">jack-lenor-larsen</a>. For the British',
    'contemporary working the quieter, printed, botanical vein, see',
    '<a href="lucienne-day.geocities.ws">lucienne-day</a>.</p>',
    '<p><small>hits: 00642 · best viewed at 800x600 · a private collection, shown',
    'for love not profit · page last updated 3 Apr</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Jack Lenor Larsen: the exhibition write-up -----------------------------

const JACK_LENOR_LARSEN = P('jack-lenor-larsen.geocities.ws', 'J L LARSEN',
  'exhibition notes // Larsen, the loft and the loom', [
    '<!--bg:des-textiles-->',
    '<h1>Larsen: the loft and the loom</h1>',
    '<p class="fs-epi"><i>Notes written up after a visit to the touring Larsen',
    'retrospective. My own impressions, so take them as such.</i></p>',
    '<p>You come out of a Jack Lenor Larsen show having changed your mind about what',
    'a curtain can be. Larsen (1927&ndash;2020) opened his New York studio in 1952,',
    'fresh from a graduate degree, and within a year he had a commission to weave',
    'the drapery for the lobby of a Manhattan office building. That is the whole',
    'shape of his career in miniature: hand-weaving&rsquo;s richness, at the scale',
    'and to the brief of modern architecture.</p>',
    '<p>The show made the case room by room. Early on there are the casements, sheer',
    'open-weave hangings full of slubbed and random yarns, cloth that filters light',
    'rather than blocking it, made for the glass towers going up all over the country',
    'that needed something to soften an acre of window. The architects loved him',
    'because he understood their problem.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;The loom is a computer of sorts, the',
    'first binary instrument.&rdquo;</p>',
    '<p><small>&mdash; Jack Lenor Larsen, remembered by a curator on the wall',
    'text</small></p></blockquote>',
    '<p>Then the theatrical pieces, the ones that stop you. Larsen travelled',
    'constantly and drank in the world&rsquo;s textile traditions, the ikats of',
    'south-east Asia, African strip-weaving, the resist-dyes of Africa and Japan,',
    'and he brought them into industrial production without flattening them. He was',
    'an early force in what people came to call the global craft revival, insisting',
    'that hand skill and factory could feed one another rather than the factory',
    'simply killing the craft.</p>',
    '<img class="indie-pic" src="assets/media/web/des/larsen-01.jpg" alt=""><span class="indie-cap">Jack Lenor Larsen (RIT, public domain)</span>',
    '<p>A whole gallery went to Larsen the innovator in fibre. He worked with the',
    'new synthetics as eagerly as any weaver ever had, stretch fabrics, the',
    'flame-resistant cloth developed after a hotel fire, a printed velvet that made',
    'his name in the 1970s. The point the curators kept pressing is that he never',
    'treated a synthetic as a cheap stand-in for something better. He asked what',
    'the new fibre could do that no old one could, and wove to that.</p>',
    '<p class="fs-pull">Not cloth as a flat surface to be looked at, but cloth as',
    'something built, with depth and shadow and the behaviour of a material.</p>',
    '<p>The last rooms turn to LongHouse, the house and sixteen-acre garden he made',
    'on Long Island and left as a public foundation, a place built on the belief',
    'that art should be a daily experience and not a museum visit. It is the summing',
    'up of a life spent refusing the line between art and use, and the show was wise',
    'to end there rather than on a vitrine of samples.</p>',
    '<p>Worth a visit after this one. For the older American weaver whose colour and',
    'metal thread prepared the ground, see',
    '<a href="dorothy-liebes.geocities.ws">dorothy-liebes</a>. For the painter who',
    'brought simultaneous colour from the canvas into cloth, see',
    '<a href="sonia-delaunay.geocities.ws">sonia-delaunay</a>.</p>',
    '<p><small>counter: 00815 · best viewed at 800x600 · exhibition notes, an',
    'amateur&rsquo;s · under construction while i type up the second half · last',
    'updated 30 Jan</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Sonia Delaunay: the student coursework ---------------------------------

const SONIA_DELAUNAY = P('sonia-delaunay.geocities.ws', 'SONIA DELAUNAY',
  'DES204 coursework // Sonia Delaunay, colour into cloth', [
    '<!--bg:des-textiles-->',
    '<h1>Sonia Delaunay: colour into cloth</h1>',
    '<p><small>DES204 History of Modern Design, essay 2, put on my web space so my',
    'study group can read it. mark still pending. please don&rsquo;t copy this,',
    'tutor reads the ring. — Priya</small></p>',
    '<hr>',
    '<p>This essay argues that Sonia Delaunay (1885&ndash;1979) matters not despite',
    'moving from painting into textiles and fashion but because of it. She refused',
    'the line that says a painter descends when she designs a dress or a bolt of',
    'cloth. For Delaunay the same problem, colour in movement, could be worked out',
    'on a canvas, on a coat, or on a length of printed silk, and the cloth was not',
    'the lesser place to work it out.</p>',
    '<p>The theory behind it she developed with her husband Robert Delaunay, and it',
    'is called <b>simultaneous contrast</b>, or simultanism, or Orphism. The idea,',
    'drawn out of the colour theorist Chevreul, is that colours are never seen',
    'alone. Placed side by side they act on one another; a colour changes its',
    'neighbour and is changed by it, and from those interactions you can build',
    'rhythm and depth and the sensation of movement out of pure colour, with no need',
    'to draw a recognisable thing at all.</p>',
    '<div class="fs-aside"><p><b>Simultaneous contrast, in one line.</b> Put',
    'complementary colours next to each other and each makes the other more intense;',
    'the eye does the mixing and the boundary seems to vibrate. Delaunay built whole',
    'compositions, and whole garments, on that vibration.</p></div>',
    '<p>She had proof it worked on cloth before she had the theory fully named. In',
    '1911 she made a patchwork cot cover for her baby son, piecing scraps of colour',
    'in the manner, she later said, of a Russian peasant quilt from her childhood,',
    'and she saw in it the same thing she was after in the paintings. That humble',
    'blanket is treated in the histories as a founding object of the whole',
    'simultaneous idea, which i find a lovely thing about it.</p>',
    '<img class="indie-pic" src="assets/media/web/des/delaunay-01.jpg" alt=""><span class="indie-cap">Sonia Delaunay, Simultaneous Contrasts (photo: J-P Dalbera, CC BY 2.0)</span>',
    '<p>In the 1920s she made it a business. She opened the <b>Boutique',
    'Simultan&eacute;e</b>, showing at the great 1925 Paris exhibition of decorative',
    'arts, and ran a studio, the Casa Sonia name reaching as far as her Spanish',
    'clients, turning out printed textiles, embroidered coats, and her',
    '&ldquo;simultaneous dresses&rdquo;. She designed cloth for the Lyon silk',
    'manufacturers and dressed film stars and the fashionable, and she designed',
    'costumes for the stage. She did not see this as time off from art. She called',
    'the whole of it one practice.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;For me there was no gap between my',
    'painting and what is called my decorative work.&rdquo;</p>',
    '<p><small>&mdash; Sonia Delaunay (as quoted in the exhibition catalogue,',
    'ref. below)</small></p></blockquote>',
    '<p>My conclusion for the essay is that Delaunay is a useful corrective to a',
    'design history that keeps fine art on top and the applied arts underneath. She',
    'worked in both directions at once and thought the hierarchy was a mistake. In',
    '1964 she became the first living woman to have a retrospective at the Louvre,',
    'which suggests the art world came round to her view of it in the end.</p>',
    '<pre>REFERENCES (Harvard-ish, tutor please be kind)\n' +
    '----------------------------------------------\n' +
    'Delaunay, S. — Nous irons jusqu&rsquo;au soleil (memoir), 1978\n' +
    'Baron &amp; Damase — Sonia Delaunay: The Life of an Artist\n' +
    'exhibition catalogue, Sonia Delaunay retrospective (used for the quote)\n' +
    'Chevreul, M-E. — The Principles of Harmony and Contrast of Colours\n' +
    '(need to double-check the Chevreul date, i think 1839??)</pre>',
    '<p>For the Bauhaus weaver working the structural, not the colour, side of the',
    'modern loom, see <a href="anni-albers.geocities.ws">anni-albers</a>. For the',
    'firm that carried pattern from the previous century, see',
    '<a href="morris-and-co.geocities.ws">morris-and-co</a>.</p>',
    '<p><small>visitors: 00398 · best viewed at 800x600 · DES204 study group ·',
    'this page under construction until the mark comes back · last updated 18 Apr —',
    'Priya</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

export const DES_C = [
  MORRIS_AND_CO,
  ANNI_ALBERS,
  LUCIENNE_DAY,
  DOROTHY_LIEBES,
  JACK_LENOR_LARSEN,
  SONIA_DELAUNAY,
];
