// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH MATH_F — the singular figures: the outsiders and wanderers.
//
// Pages a student, a maths society or an enthusiast made about the
// mathematicians they loved. A fan shrine to Erdos with the full kit; an
// academic note on Mandelbrot's fractals; a reading-group's minutes on Nash;
// a lecture write-up on Poincare; a undergraduate's coursework on
// Kovalevskaya; and a summary of Boole. The names, dates and results are real;
// the enthusiasm, the handles and the wonky bibliographies are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Erdos: the personal fan shrine (SHOWPIECE) -----------------------------

const ERDOS = P('paul-erdos.geocities.ws', 'PAUL ERDOS',
  'PAUL ERDOS // the man who loved only numbers', [
    '<!--bg:math-heterodox-->',
    '<h1>PAUL ERDOS</h1>',
    '<p><small>a shrine to Paul Erdos (1913-1996), the wandering mathematician,',
    'kept by an undergraduate who has an Erdos number of 4 and will tell anyone',
    'who stands still long enough. i never met him. i wish i had. — Sam</small></p>',
    '<p class="fs-epi"><i>Another roof, another proof.</i><br>— Paul Erdos, on his',
    'way of living</p>',
    '<hr>',
    '<p>He had no house, no job, no wife, and almost no possessions. What he had',
    'was a suitcase, a plastic bag, and the addresses of a few hundred',
    'mathematicians across the world, and he moved between them for sixty years,',
    'turning up on a doorstep to announce that his brain was open. He wrote, or',
    'co-wrote, around 1500 papers, more than any mathematician in history, and he',
    'wrote most of them with other people. Collaboration was the whole shape of',
    'his life.</p>',
    '<img class="indie-pic" src="assets/media/web/math/erdos-01.jpg" alt=""><span class="indie-cap">Paul Erdos (photo: Topsy Kretts, CC BY 3.0)</span>',
    '<p>Erdos was born in Budapest in 1913 to two mathematics teachers. He was a',
    'prodigy who could multiply large numbers in his head as a small child and',
    'who, it is said, worked out negative numbers for himself by the age of four.',
    'He took his doctorate in Budapest and then, as a Hungarian Jew in the 1930s,',
    'he left, and after that he never really settled anywhere again.</p>',
    '<p class="fs-quote"><blockquote>A mathematician is a machine for turning',
    'coffee into theorems.</blockquote></p>',
    '<p>Everyone gives Erdos this line, and he certainly lived it, on coffee and',
    'later on amphetamines, working nineteen hours a day. To be fair to the',
    'record, the joke is usually credited to his friend Alfred Renyi, and Erdos',
    'made it his own. Either way it is the truest thing anyone said about how he',
    'worked.</p>',
    '<h2>the language he invented</h2>',
    '<p>He spoke a private vocabulary and if you loved him you learned it.',
    'Children were <i>epsilons</i>, because in mathematics the epsilon is the',
    'smallest thing. Women were <i>bosses</i> and men were <i>slaves</i>. To stop',
    'doing mathematics was to <i>die</i>; to actually die was to <i>leave</i>. God,',
    'who he did not believe in but argued with constantly, was the <i>Supreme',
    'Fascist</i>, the SF, who kept the good proofs to himself and hid your socks.',
    'A country you could not enter was one that had <i>joined the SF</i>.</p>',
    '<p class="fs-pull">You do not have to believe in God, but you should believe',
    'in The Book.</p>',
    '<p>THE BOOK is the loveliest of his ideas. He imagined that the SF keeps a',
    'book in which the most beautiful proof of every theorem is written, the',
    'proof from The Book, and that the work of a mathematician is to peek over',
    'the shoulder of the SF and copy one down. A proof was not just correct, it',
    'could be <i>from The Book</i>, and that was the highest praise he had.</p>',
    '<h2>the Erdos number</h2>',
    '<p>Because he wrote with almost everyone, his friends invented a game that',
    'became a real object of study. Erdos himself has Erdos number 0. Anyone who',
    'wrote a paper with him has Erdos number 1, of whom there were around 500.',
    'Anyone who wrote with one of them has number 2, and so on out through the',
    'whole graph of collaboration. Most working mathematicians have a small',
    'finite number, usually under 8. It is the friendship network of a science,',
    'drawn as a graph, with one strange saint at the centre.</p>',
    '<pre>',
    '   ERDOS-NUMBER GRAPH (a tiny corner of it)',
    '',
    '        [ERDOS] 0',
    '        /   |   \\',
    '       /    |    \\',
    '    Renyi  Graham  Selfridge     <- Erdos number 1',
    '      |      |        |',
    '      |      |        |',
    '     Bela   Chung    Pomerance   <- Erdos number 2',
    '               |',
    '               |',
    '             (you?)              <- Erdos number 3',
    '',
    '   an edge = "wrote a paper together"',
    '   your number = shortest path back to ERDOS',
    '</pre>',
    '<p class="fs-aside"><b>THE BET.</b> His friends worried about the',
    'amphetamines. Ronald Graham bet him 500 dollars that he could not stop for a',
    'month. Erdos stopped for a month, won the bet, and complained that',
    'mathematics had been set back a month, that he had stared at a blank sheet of',
    'paper like an ordinary person. Then he started again.</p>',
    '<img class="indie-pic" src="assets/media/web/math/mandelbrot-set-01.jpg" alt=""><span class="indie-cap">A rendering of the Mandelbrot set (image: Wolfgang Beyer, CC BY-SA 3.0)</span>',
    '<p>He gave nearly all the money he earned away, kept a little for travel and',
    'coffee, and set prizes on the problems he could not solve, from 25 dollars',
    'for a hard exercise up to thousands for the ones he thought were deep. People',
    'still collect the cheques and frame them rather than cash them. He worked in',
    'number theory, combinatorics, set theory and probability, and with Mark Kac',
    'and others he helped invent the <i>probabilistic method</i>, proving a thing',
    'exists by showing a random one works often enough, which sounds like a trick',
    'and is one of the deepest ideas of the century.</p>',
    '<p>He died in 1996 in Warsaw, at a conference, doing mathematics, which is',
    'the only way he would have agreed to leave. He had said for years that the',
    'ideal way to go was to finish a lecture, answer the last question from the',
    'audience, and fall down. He nearly managed it.</p>',
    '<hr>',
    '<p>If you want more of this strange, generous corner of the century, read on.',
    'Benoit Mandelbrot, another outsider who never fit one department, is at',
    '<a href="benoit-mandelbrot.geocities.ws">benoit-mandelbrot</a>, and George',
    'Boole, the self-taught schoolmaster whose logic runs under every machine',
    'this page is served on, is at <a href="george-boole.geocities.ws">george-boole</a>.',
    'The friend who probably first said the coffee line, Alfred Renyi, has no page',
    'here yet.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01913 · best viewed at 800x600 · this page is under',
    'eternal construction, like all good proofs · epsilons welcome · last updated',
    '26 Sep · my brain is open — Sam</small></p>',
  ]);

// ---- Mandelbrot: the academic summary ---------------------------------------

const MANDELBROT = P('benoit-mandelbrot.geocities.ws', 'MANDELBROT',
  'Benoit Mandelbrot and the geometry of the rough', [
    '<!--bg:math-heterodox-->',
    '<h1>Benoit Mandelbrot and the Geometry of the Rough</h1>',
    '<p><small>a summary page, compiled for the departmental reading list. corrections',
    'to the maintainer.</small></p>',
    '<hr>',
    '<p>Benoit Mandelbrot (1924-2010) was born in Warsaw, raised partly in France,',
    'and spent most of his working life at the IBM Thomas J. Watson Research',
    'Center in New York, an outsider who moved between mathematics, physics,',
    'economics and engineering without ever quite belonging to one of them. That',
    'freedom was the condition of the work. He was interested in exactly the',
    'shapes that classical geometry had set aside as pathological: the rough, the',
    'broken, the irregular, the shapes of the actual world.</p>',
    '<p>He named them in 1975, coining <i>fractal</i> from the Latin <i>fractus</i>,',
    'broken. A fractal is a shape that looks similar at every scale, so that a',
    'small piece, magnified, resembles the whole. His book <i>The Fractal Geometry',
    'of Nature</i> (1982) opens with the sentence that became his manifesto.</p>',
    '<blockquote><p>Clouds are not spheres, mountains are not cones, coastlines',
    'are not circles, and bark is not smooth, nor does lightning travel in a',
    'straight line.</p></blockquote>',
    '<h2>the coastline paradox</h2>',
    '<p>His 1967 paper asked a deceptively simple question: how long is the coast',
    'of Britain? The answer is that it depends on the length of your ruler. Measure',
    'with a ten-mile stick and you skip the bays; measure with a one-mile stick',
    'and you catch more of them and the total grows; measure round every pebble',
    'and it grows again, without settling. A coastline has no single length. What',
    'it has instead is a <i>fractional dimension</i>, a number between 1 and 2',
    'that measures how thoroughly the line crinkles and fills the plane. A smooth',
    'curve has dimension 1. The west coast of Britain comes out at about 1.25.</p>',
    '<img class="indie-pic" src="assets/media/web/math/mandelbrot-01.jpg" alt=""><span class="indie-cap">Benoit Mandelbrot (photo: Rama, CC BY-SA 2.0 FR)</span>',
    '<h2>the Mandelbrot set</h2>',
    '<p>The object that carries his name is generated by a rule a schoolchild can',
    'follow. Take a complex number c, start with z at zero, and repeat the step',
    'z becomes z squared plus c. For some values of c the numbers stay small',
    'forever; for others they run off to infinity. The Mandelbrot set is simply',
    'the set of c for which they stay bounded. That one line of arithmetic, drawn',
    'on the plane, produces a boundary of infinite intricacy, budding and',
    'branching and repeating itself at every level of magnification, and it was',
    'one of the first deep mathematical objects that could only be seen once there',
    'were computers to draw it.</p>',
    '<p>Mandelbrot argued that this roughness was not an exception but the norm,',
    'and that self-similarity ran through coastlines, mountains, blood vessels,',
    'the clustering of galaxies, the noise on a telephone line, and the wild',
    'swings of cotton prices and financial markets, where he warned that the mild',
    'bell curve badly understates how often the extreme happens. For a long time',
    'the establishment treated him as a showman with pretty pictures. The pictures',
    'turned out to be a new branch of geometry.</p>',
    '<p>He sits close to two other figures who would not stay inside one field.',
    'John Nash, whose geometry of surfaces and of games came from the same refusal',
    'to accept a tidy problem, is at <a href="john-nash.geocities.ws">john-nash</a>,',
    'and the wandering Paul Erdos is at',
    '<a href="paul-erdos.geocities.ws">paul-erdos</a>.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hits: 00512 · best viewed at 800x600 · last updated 4 Mar</small></p>',
  ]);

// ---- Nash: the reading-group / society minutes ------------------------------

const NASH = P('john-nash.geocities.ws', 'JOHN NASH',
  'Nash evening — minutes of the meeting (game theory)', [
    '<!--bg:math-heterodox-->',
    '<h1>Postgraduate Maths Society — Minutes</h1>',
    '<p><small>Meeting of Thursday. Topic: the mathematics of John Forbes Nash Jr.',
    'Present: nine members and two visitors from Economics. Tea provided.',
    'Minutes taken by the secretary.</small></p>',
    '<hr>',
    '<p><b>1. Apologies and opening.</b> Two apologies received. The chair opened',
    'by noting that we would try, for once, to keep the film out of it and talk',
    'about the mathematics, and that we would fail, and we did.</p>',
    '<p><b>2. The thesis (introduced by R.).</b> R. reminded us that Nash',
    '(1928-2015) wrote a doctoral thesis at Princeton in 1950 that was 28 pages',
    'long and changed economics. Before Nash, game theory really handled only',
    'zero-sum games, where what one wins another loses. Nash asked what happens in',
    'a <i>non-cooperative</i> game where players cannot make binding agreements',
    'and each acts in self-interest.</p>',
    '<img class="indie-pic" src="assets/media/web/math/nash-01.jpg" alt=""><span class="indie-cap">John Forbes Nash (photo: Elke Wetzig, CC BY-SA 3.0)</span>',
    '<p><b>3. The equilibrium (discussion).</b> A Nash equilibrium is a set of',
    'strategies, one for each player, such that no player can do better by',
    'changing only their own strategy while the others keep theirs. Everyone is',
    'giving the best reply to everyone else, so nobody has a reason to move. R.',
    'proved to us, using a fixed-point argument, that every finite game has at',
    'least one such equilibrium, possibly in mixed (randomised) strategies. The',
    'visitors from Economics pointed out that the whole discipline now rests on',
    'this, and that the equilibrium need not be the outcome anyone would want, as',
    'the prisoners in the prisoner\'s dilemma both confess. We agreed this was the',
    'unsettling part.</p>',
    '<p><b>4. The other Nash (introduced by the chair).</b> The chair insisted,',
    'rightly, that the economists have stolen a geometer. Among mathematicians',
    'Nash is loved less for the equilibrium than for the <i>embedding theorems</i>',
    'of the 1950s, which showed that any abstract Riemannian manifold can be',
    'embedded isometrically in ordinary Euclidean space, bending without',
    'stretching, so that the intrinsic geometry is preserved exactly. The methods',
    'he invented to do it fed straight into the theory of partial differential',
    'equations. Several present thought this the deeper achievement.</p>',
    '<p><b>5. The lost years (a quieter item).</b> We noted, without dwelling on',
    'it for entertainment, that Nash developed schizophrenia at the end of the',
    '1950s and was ill for roughly three decades, drifting round the Princeton',
    'campus, a presence the students half-knew. He recovered slowly and partly in',
    'later life. In 1994 he shared the Nobel Memorial Prize in Economics for the',
    'equilibrium work of forty years before, and in 2015 he won the Abel Prize for',
    'the geometry, and died in a road accident with his wife Alicia days later. The',
    'meeting stood for a moment.</p>',
    '<p><b>6. Any other business.</b> B. urged everyone to read next about Henri',
    'Poincare, the last man who could hold all of mathematics in one head, at',
    '<a href="henri-poincare.geocities.ws">henri-poincare</a>, since the embedding',
    'work touches his topology. And the chair sent us back to Benoit Mandelbrot at',
    '<a href="benoit-mandelbrot.geocities.ws">benoit-mandelbrot</a> for another',
    'geometer of the awkward shape. Meeting closed. Next fortnight: Ramanujan.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>visitor count: 00287 · best viewed at 800x600 · Postgraduate Maths',
    'Society · minutes posted 15 Feb · this site is under construction</small></p>',
  ]);

// ---- Poincare: the lecture / talk write-up ----------------------------------

const POINCARE = P('henri-poincare.geocities.ws', 'POINCARE',
  'The Last Universalist — a talk write-up (Poincare)', [
    '<!--bg:math-heterodox-->',
    '<h1>The Last Universalist: notes from the evening lecture</h1>',
    '<p><small>write-up of the public lecture given to the society last week. any',
    'errors are the note-taker\'s, not the speaker\'s.</small></p>',
    '<hr>',
    '<p>The speaker began with a claim she said she would defend all evening: that',
    'Henri Poincare (1854-1912) was the last person able to work at the front of',
    'every part of mathematics at once, and much of physics besides. After him the',
    'subject grew too large for one mind. She called him the last universalist and',
    'spent an hour making the phrase earned rather than decorative.</p>',
    '<p>He was born in Nancy in 1854, a cousin of Raymond Poincare who would',
    'become President of France. He was famously absent-minded and short-sighted,',
    'and he worked, she said, by long unconscious incubation, describing how a',
    'solution once arrived complete as he stepped onto a bus, having thought of',
    'nothing mathematical for days. He wrote hundreds of papers across analysis,',
    'algebra, geometry, astronomy and physics.</p>',
    '<h2>the three-body problem</h2>',
    '<p>The heart of the talk was the prize. In 1889 King Oscar II of Sweden',
    'offered a prize for the question of whether the solar system is stable.',
    'Poincare took on the three-body problem, three masses pulling on one another',
    'under gravity, and won the prize. Then, correcting the printed memoir, he',
    'found an error, and in fixing it he found something stranger than a stable',
    'answer. Some orbits were so sensitive to their starting point that the',
    'smallest change in the beginning gave a wholly different end, tangling into a',
    'motion no formula could ever capture. The speaker said, and paused on it,',
    'that this was the first clear sight of what we now call chaos, found not by',
    'looking for it but by an honest man correcting his own mistake.</p>',
    '<img class="indie-pic" src="assets/media/web/math/poincare-01.jpg" alt=""><span class="indie-cap">Henri Poincare (public domain)</span>',
    '<h2>shape without measurement</h2>',
    '<p>She turned then to topology, which Poincare more or less founded as a',
    'systematic subject in his <i>Analysis Situs</i> of 1895, the study of the',
    'properties of shapes that survive stretching and bending, where a doughnut',
    'and a coffee cup are the same and a sphere is different. From this came the',
    'most famous unsolved problem to bear his name, the <i>Poincare conjecture</i>,',
    'which asks, roughly, whether any three-dimensional shape without holes must',
    'really be a sphere. She noted that it stood for nearly a century and was',
    'finally proved by Grigori Perelman around 2003, who then declined both the',
    'million-dollar prize and the Fields Medal, and left the subject.</p>',
    '<p>She closed on the philosopher. Poincare wrote for the public in',
    '<i>Science and Hypothesis</i> and argued that the axioms of geometry are',
    'neither true nor false but conventions, chosen for convenience, a position he',
    'called conventionalism. In the questions afterward someone asked whether he',
    'had nearly reached special relativity before Einstein, and the speaker said',
    'that he had come very close on the mathematics and had held back on the',
    'physics, and that this was a fair evening\'s worth of an argument on its own.</p>',
    '<p>For neighbours the speaker recommended Sofia Kovalevskaya, who worked on',
    'the same mechanics of spinning and orbiting bodies, at',
    '<a href="sofia-kovalevskaya.geocities.ws">sofia-kovalevskaya</a>, and John',
    'Nash at <a href="john-nash.geocities.ws">john-nash</a>, whose geometry of',
    'manifolds grew from the ground Poincare cleared.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 00631 · best viewed at 800x600 · lecture notes posted 9 May',
    '· page under construction</small></p>',
  ]);

// ---- Kovalevskaya: the student coursework -----------------------------------

const KOVALEVSKAYA = P('sofia-kovalevskaya.geocities.ws', 'KOVALEVSKAYA',
  'MATH 214 essay: Sofia Kovalevskaya (coursework)', [
    '<!--bg:math-heterodox-->',
    '<h1>Sofia Kovalevskaya: a life against the rules</h1>',
    '<p><small>MATH 214, History of Mathematics. Term essay, second year. put up on',
    'my own pages because i was proud of the mark. do not copy it, i will know. — Priya</small></p>',
    '<hr>',
    '<p>Sofia Kovalevskaya (1850-1891) was the first woman in modern Europe to hold',
    'a full professorship in mathematics, at the University of Stockholm, and she',
    'got there by refusing every rule that was meant to stop her. This essay looks',
    'at how she got the chair and at the two results that earned it.</p>',
    '<p>She was born in Moscow into a landowning family. As a child, the story',
    'goes, her nursery was papered with pages of lecture notes on the differential',
    'calculus for want of proper wallpaper, and she lay awake trying to read the',
    'walls. Russian universities were closed to women, and a woman could not even',
    'travel abroad to study without the permission of her father or a husband, so',
    'in 1868 she made a <i>marriage of convenience</i> to Vladimir Kovalevsky, a',
    'young palaeontologist, purely so that she could leave the country and study.</p>',
    '<img class="indie-pic" src="assets/media/web/math/kovalevskaya-01.jpg" alt=""><span class="indie-cap">Sofia Kovalevskaya (public domain)</span>',
    '<p>In Germany she was still barred from the lecture halls, so she persuaded',
    'Karl Weierstrass, the great analyst, to teach her privately, and he did, for',
    'years, and came to regard her as one of his finest students. On the strength',
    'of her work the University of Gottingen awarded her a doctorate in 1874,',
    'in absentia, without the usual oral examination, because the work was so',
    'plainly strong. It was the first mathematics doctorate awarded to a woman in',
    'modern Europe.</p>',
    '<p>Her two most important results are these.</p>',
    '<p><b>The Cauchy-Kovalevskaya theorem.</b> One of the doctoral papers gives a',
    'general condition under which a wide class of partial differential equations',
    'is guaranteed to have a solution, and a unique one, near a starting surface,',
    'provided the data are analytic. It is a foundation stone of the whole theory',
    'of PDEs and it still carries her name beside Cauchy\'s in every textbook.</p>',
    '<p><b>The Kovalevskaya top.</b> In 1888 she won the Prix Bordin of the French',
    'Academy of Sciences for solving the motion of a spinning rigid body, a top,',
    'about a fixed point. Euler and Lagrange had each found a special case that',
    'could be solved exactly; she found the third and last, the one now called the',
    '<i>Kovalevskaya top</i>. The prize committee thought the work so good they',
    'raised the prize money.</p>',
    '<p>She was appointed to Stockholm in 1884 and made full professor in 1889. She',
    'also wrote, seriously, publishing a memoir of her Russian childhood and a',
    'novel, <i>Nihilist Girl</i>, and never accepted that the mathematics and the',
    'writing were separate lives. She died of pneumonia in 1891, only forty-one,',
    'at the height of her powers.</p>',
    '<p><b>Bibliography</b> (as far as i could get to the books):</p>',
    '<p><small>- Kovalevskaya, S. <i>A Russian Childhood</i>. (the memoir, in',
    'translation, from the library.)<br>',
    '- the encyclopaedia entry on the Cauchy-Kovalevskaya theorem (photocopied).<br>',
    '- a chapter on women in mathematics, handed out in the seminar, author\'s name',
    'cut off on my copy, sorry Dr M.<br>',
    '- something my tutor said in office hours that i have not been able to find in',
    'print but am sure is right.</small></p>',
    '<p>For where her mechanics leads, see Henri Poincare on the three-body problem',
    'at <a href="henri-poincare.geocities.ws">henri-poincare</a>, and for another',
    'self-made outsider from a different corner, George Boole at',
    '<a href="george-boole.geocities.ws">george-boole</a>.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 00198 · best viewed at 800x600 · a MATH 214 page · under',
    'construction · last updated 21 Nov · — Priya</small></p>',
  ]);

// ---- Boole: the academic summary --------------------------------------------

const BOOLE = P('george-boole.geocities.ws', 'GEORGE BOOLE',
  'George Boole and the Laws of Thought', [
    '<!--bg:math-heterodox-->',
    '<h1>George Boole and The Laws of Thought</h1>',
    '<p><small>a summary page maintained for the first-year logic course. references',
    'at the foot.</small></p>',
    '<hr>',
    '<p>George Boole (1815-1864) was born in Lincoln, the son of a shoemaker, and',
    'was very largely self-taught. There was no money for a university education,',
    'so he read his way into mathematics on his own while working from the age of',
    'sixteen as a schoolteacher, and eventually ran his own small school to support',
    'his family. He published original research while entirely outside the academy,',
    'and on the strength of it was appointed, in 1849, the first professor of',
    'mathematics at the new Queen\'s College in Cork, in Ireland, a post he held',
    'for the rest of his life.</p>',
    '<p>His achievement was to treat logic as a branch of algebra. In two works,',
    '<i>The Mathematical Analysis of Logic</i> (1847) and the fuller <i>An',
    'Investigation of the Laws of Thought</i> (1854), he argued that the operations',
    'of reasoning could be written as equations and solved like equations. Let a',
    'symbol stand for a class of things, let 1 be the universe of everything and 0',
    'the empty class, let multiplication mean "and" and addition mean "or", and the',
    'rules of valid inference become algebraic laws.</p>',
    '<img class="indie-pic" src="assets/media/web/math/boole-01.jpg" alt=""><span class="indie-cap">George Boole (public domain)</span>',
    '<p>One law in particular marks the difference from ordinary algebra. In',
    'Boole\'s system x times x equals x, because the things that are both x and x',
    'are just the things that are x. From this the whole system follows, and its',
    'natural home is the two values 0 and 1, false and true, off and on. He had',
    'built, without any machine in view, the algebra of the switch.</p>',
    '<p>Boole did not live to see any of what he had made. He died in 1864, at',
    'forty-nine, of pneumonia after walking to a lecture through cold rain and',
    'teaching in wet clothes. His wife Mary Everest Boole was herself a',
    'mathematics educator, and their daughters were remarkable, one of them,',
    'Alicia, working on four-dimensional geometry and coining the word polytope.</p>',
    '<p>The importance of the work is easier to state now than it was then. In',
    '1937 a young engineer named Claude Shannon showed, in his master\'s thesis,',
    'that Boole\'s two-valued algebra was exactly the mathematics of electrical',
    'switching circuits, of relays that are open or closed. Every logic gate in',
    'every processor, every line of the reasoning a computer performs, runs on the',
    'algebra a self-taught schoolmaster in Lincoln set down to describe the laws',
    'of thought. The name Boolean is on it still.</p>',
    '<p>For neighbours in this ring, the wandering Paul Erdos, whose combinatorics',
    'lives close to Boole\'s discrete world, is at',
    '<a href="paul-erdos.geocities.ws">paul-erdos</a>, and Sofia Kovalevskaya,',
    'another figure who made a place from the outside, is at',
    '<a href="sofia-kovalevskaya.geocities.ws">sofia-kovalevskaya</a>.</p>',
    '<p><b>References.</b> Boole, <i>An Investigation of the Laws of Thought</i>',
    '(1854); the standard encyclopaedia article on Boolean algebra; Shannon, "A',
    'Symbolic Analysis of Relay and Switching Circuits" (1938).</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hits: 00415 · best viewed at 800x600 · first-year logic course page',
    '· last updated 2 Oct</small></p>',
  ]);

export const MATH_F = [ERDOS, MANDELBROT, NASH, POINCARE, KOVALEVSKAYA, BOOLE];
