// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — the Romantic. Six cached pages made by people who loved this music:
// listening notes on Brahms, a summary of Schubert's short life, a fan's shrine
// to Chopin, a write-up of a Clara Schumann recital, a student's coursework on
// Fanny Mendelssohn, and a lecture on Berlioz. The works, dates and premieres
// are real; the enthusiasm and the wonky bibliographies are the fans' own.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Brahms: the listening notes (SHOWPIECE) --------------------------------

const BRAHMS = P('brahms.geocities.ws', 'BRAHMS',
  'BRAHMS — listening notes on the four symphonies', [
    '<!--bg:comp-romantic-->',
    '<h1>Johannes Brahms (1833–1897)</h1>',
    '<p class="fs-epi"><i>Listening notes, kept for my own use and yours. Play the',
    'record, read the note, play it again. That is the whole method.</i></p>',
    '<p><small>Notes by a listener, not a scholar. Corrections welcome. Best viewed',
    'at 800x600. Under construction, as it will be forever.</small></p>',
    '<hr>',
    '<p>Brahms was born in Hamburg and made his life in Vienna, and the distance',
    'between those two cities is the distance in the music: the northern reserve',
    'and the southern warmth held in one hand. He came up poor, played piano in the',
    'dockside taverns as a boy, and was carried into fame at twenty by Robert',
    'Schumann, who wrote an article calling him the one who was coming. That article',
    'was a gift and a weight. Brahms spent the rest of his life trying to deserve',
    'it, and he was hard on himself past all reason.</p>',
    '<blockquote class="fs-quote"><p>"You have no idea how it feels to hear behind',
    'you the tramp of a giant like Beethoven."</p><p>— Brahms, on why the First',
    'Symphony took him so long</p></blockquote>',
    '<p>That giant is the key to the whole story. Beethoven had finished the',
    'symphony, or seemed to, and after the Ninth nobody knew what a symphony was',
    'for any more. Brahms would not write one until he could stand next to that and',
    'not be ashamed. So the First Symphony waited. He began sketching in his',
    'twenties and did not finish until he was forty-three.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/brahms-01.jpg" alt=""><span class="indie-cap">Johannes Brahms (public domain)</span>',
    '<h2>The four symphonies, one at a time</h2>',
    '<p><b>No. 1 in C minor, Op. 68 (1876).</b> Twenty-one years in the making. The',
    'slow introduction with the timpani pounding underneath is one of the great',
    'openings, dark and straining upward. The finale brings a broad hymn-like tune',
    'that everyone hears as a cousin of the "Ode to Joy", and when a critic said so',
    'to his face Brahms snapped that any fool could see that. The conductor Hans von',
    'Bulow called the work "Beethoven\'s Tenth", which was meant as praise and',
    'stuck like a burr.</p>',
    '<p><b>No. 2 in D major, Op. 73 (1877).</b> Written in a single happy summer at',
    'Portschach on the lake, and it sounds it. People call it his "Pastoral". Do',
    'not be fooled by the sunshine, though. There is a shadow in the low trombones',
    'in the first movement that he told his publisher was a hint of the darkness',
    'underneath. A serene piece with a black thread running through it.</p>',
    '<p><b>No. 3 in F major, Op. 90 (1883).</b> The shortest and, to my ear, the',
    'proudest. It opens with a rising motto, F–A flat–F, that some read as his',
    'personal motto, <i>frei aber froh</i>, free but glad, an answer to his friend',
    'the violinist Joseph Joachim, whose own was <i>frei aber einsam</i>, free but',
    'lonely. The third movement, the poco allegretto, is the tune the world knows,',
    'sad and turning and unable to settle.</p>',
    '<p><b>No. 4 in E minor, Op. 98 (1885).</b> The last, and the most severe. The',
    'finale is a passacaglia, thirty variations built over a repeating bass line he',
    'borrowed from a Bach cantata, an old and strict form filled with grief. Nobody',
    'else in the Romantic century ended a symphony by going that far back and that',
    'far in. It is the summit.</p>',
    '<hr>',
    '<pre>',
    'A SHORT SHELF OF BRAHMS, BY OPUS',
    '  Op. 45   Ein deutsches Requiem (A German Requiem)   1868',
    '  Op. 68   Symphony No. 1 in C minor                  1876',
    '  Op. 73   Symphony No. 2 in D major                  1877',
    '  Op. 77   Violin Concerto in D major                 1878',
    '  Op. 83   Piano Concerto No. 2 in B flat major       1881',
    '  Op. 90   Symphony No. 3 in F major                  1883',
    '  Op. 98   Symphony No. 4 in E minor                  1885',
    '  Op. 115  Clarinet Quintet in B minor                1891',
    '</pre>',
    '<p>The <b>German Requiem</b> deserves a word of its own. It is not the Latin',
    'Mass for the dead. Brahms chose the words himself, out of Luther\'s German',
    'Bible, and he chose them for the living who are left behind, not for the soul',
    'being judged. "Blessed are they that mourn, for they shall be comforted." He',
    'wrote much of it after his mother died, and the fifth movement, the soprano',
    'solo added later, is widely heard as a memorial to her. There is no Day of',
    'Wrath in it. It is the most consoling large sacred work of the century.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/schubert-01.jpg" alt=""><span class="indie-cap">Franz Schubert (public domain)</span>',
    '<h2>The chamber music, where he is most himself</h2>',
    '<p>If the symphonies are Brahms in public, the chamber music is Brahms alone',
    'in a room. Start with the <b>Clarinet Quintet, Op. 115</b>, written near the',
    'end after he had announced he was done composing and then heard the clarinettist',
    'Richard Muhlfeld and could not stop. It is autumn made audible, warm and',
    'resigned at once. Then the three violin sonatas, the two cello sonatas, the',
    'piano quartets and quintet. He wrote for friends and played with them, and the',
    'music keeps that grain of company in it.</p>',
    '<aside class="fs-aside"><p><b>A note on the form: theme and variations.</b>',
    'Brahms loved to take a small tune and turn it over and over, finding what was',
    'hidden in it. The Handel Variations for piano, the Haydn Variations for',
    'orchestra, the finale of the Fourth Symphony: the same patient habit of mind.',
    'He was a great collector of old scores and copied out early music by hand. The',
    'past was not a museum to him. It was a workshop.</p></aside>',
    '<h2>The Schumanns</h2>',
    '<p>You cannot tell Brahms without them. Robert Schumann found him, praised him,',
    'and then fell into madness and died in an asylum in 1856. Brahms went to the',
    'family and stayed, helping <a href="clara-schumann.geocities.ws">Clara</a>',
    'through the worst years, and his love for her, whatever its exact shape, ran',
    'the length of his life. They burned most of their letters. What is left is the',
    'music they showed each other first. Clara championed his work at the keyboard',
    'for decades, and he trusted her ear over everyone\'s. When she died in 1896 he',
    'was undone, and he followed her within the year.</p>',
    '<p class="fs-pull">"After Beethoven" is the phrase people hang on him, and he',
    'earned it, but it sells him short. He is not a late echo. He is the one who',
    'kept the old forms alive by filling them with a new and private grief.</p>',
    '<p>For the man who cast the shadow over that First Symphony, go back to',
    'Beethoven. For the songs, and for the friend whose early death haunted the',
    'whole Romantic generation, hear <a href="schubert.geocities.ws">Schubert</a>,',
    'whom Brahms revered and whose lost manuscripts he helped to gather and print.</p>',
    '<hr>',
    '<p><small>counter: 03118 · best viewed at 800x600 · no MIDIs here, this music',
    'wants a real instrument and a quiet room · last updated 14 Mar</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Schubert: the academic summary -----------------------------------------

const SCHUBERT = P('schubert.geocities.ws', 'SCHUBERT',
  'Franz Schubert // a summary of the life and the song', [
    '<!--bg:comp-romantic-->',
    '<h1>Franz Schubert (1797–1828)</h1>',
    '<p><small>A summary page for a survey of nineteenth-century music. Prepared as',
    'a study aid. Sources listed at the foot. Best viewed at 800x600.</small></p>',
    '<hr>',
    '<p>Schubert lived thirty-one years and wrote as if he knew the time was short.',
    'The catalogue that Otto Erich Deutsch made of his works, from which the D',
    'numbers come, runs past a thousand entries. More than six hundred of them are',
    'songs. He effectively made the German art song, the <i>Lied</i>, into a form',
    'that could carry the weight of a symphony in the space of a few minutes, and',
    'no one has surpassed him at it since.</p>',
    '<h2>The songs</h2>',
    '<p>He was seventeen or eighteen when he wrote <b>Gretchen am Spinnrade</b>',
    '(D 118, 1814), Goethe\'s Gretchen at her spinning wheel, and the piano turns',
    'the wheel while the voice unravels. It is usually taken as the moment the',
    'German Lied comes of age. A year later came <b>Erlkonig</b> (D 328, 1815),',
    'again on Goethe, the father riding through the night with the dying child while',
    'the piano hammers out the horse\'s hooves in relentless triplets and four',
    'voices, narrator, father, child and the Erlking, all sound from one singer.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/schubert-01.jpg" alt=""><span class="indie-cap">Franz Schubert (public domain)</span>',
    '<p>Late in his short life he gathered songs into cycles. <b>Die schone',
    'Mullerin</b> (D 795, 1823) and <b>Winterreise</b> (D 911, 1827), both on poems',
    'by Wilhelm Muller, are the two great song cycles of the century. Winterreise,',
    'the winter journey, follows a rejected lover walking out into the snow, and it',
    'gets colder and stranger as it goes until the last song, <i>Der Leiermann</i>,',
    'the hurdy-gurdy man turning his handle in the ice with nobody listening.',
    'Schubert told his friends he loved these songs more than any others he had',
    'made, and that they had cost him more.</p>',
    '<blockquote class="fs-quote"><p>"When I wished to sing of love, it turned to',
    'sorrow. And when I wished to sing of sorrow, it was transformed for me into',
    'love."</p><p>— Schubert, from a diary-like sketch, 1822</p></blockquote>',
    '<h2>Beyond the songs</h2>',
    '<p>He is too often filed as a songwriter only, which does him wrong. The',
    '<b>Symphony No. 8 in B minor</b> (D 759, 1822), the "Unfinished", breaks off',
    'after two complete movements of such dark beauty that arguments still run over',
    'why he set it aside. The <b>Symphony No. 9 in C major</b> (D 944), the "Great",',
    'was found among his papers by Robert Schumann years after his death and praised',
    'for its "heavenly length". The <b>Trout Quintet</b> (D 667, 1819), for the',
    'unusual scoring of piano and strings with a double bass, takes his own song',
    '<i>Die Forelle</i> and spins a set of variations on it in the fourth movement,',
    'and it is the sunniest thing he wrote.</p>',
    '<aside class="fs-aside"><p><b>A note on the Schubertiade.</b> Schubert never',
    'held a grand public concert until the last year of his life. His music lived',
    'in evening gatherings of friends, singers and players and listeners in a',
    'private room, that came to be called Schubertiades. The intimacy of the',
    'setting is stamped on the music. It was made to be shared at close range, not',
    'broadcast from a stage.</p></aside>',
    '<p>He died in 1828, most likely of the effects of syphilis and its treatments,',
    'at thirty-one, the year after Beethoven, whom he had idolised from a distance',
    'and served as a torch-bearer at the funeral. At his own request he was buried',
    'near him. A generation later <a href="brahms.geocities.ws">Brahms</a> helped',
    'to edit and publish the mass of unheard manuscripts, and the poet of the piano',
    'in Paris, <a href="chopin.geocities.ws">Chopin</a>, worked in a nearby key of',
    'private feeling, though the two never met.</p>',
    '<hr>',
    '<pre>',
    'SOURCES CONSULTED (study aid, not a full bibliography)',
    '  Deutsch, O. E. — Schubert: Thematic Catalogue of All His Works',
    '  Newbould, B. — Schubert: The Music and the Man',
    '  Fischer-Dieskau, D. — Schubert\'s Songs (a singer on the cycles)',
    '  sleeve notes, various recordings of Winterreise',
    '</pre>',
    '<p><small>hits: 01897 · best viewed at 800x600 · a study aid, check everything',
    'against your set texts · last revised 9 Feb</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Chopin: the personal fan shrine ----------------------------------------

const CHOPIN = P('chopin.geocities.ws', 'CHOPIN',
  'the poet of the piano *~* a Chopin shrine', [
    '<!--bg:comp-romantic-->',
    '<h1>~*~ CHOPIN ~*~ the poet of the piano</h1>',
    '<p><small>my little shrine to Fryderyk. i have been playing his nocturnes',
    'badly for six years and loving him more every year. this page is a fan\'s page,',
    'all heart, no degree. sign my guestbook. — Wanda</small></p>',
    '<hr>',
    '<p>Frederic Chopin (1810–1849) was born near Warsaw and left Poland at twenty,',
    'just before the failed rising of 1830, and never went home. He carried a',
    'little cup of Polish soil with him and they buried it with him. Almost',
    'everything he wrote is for the piano, and almost everything for the piano is',
    'perfect. He is the one composer I would call, without blushing, a poet.</p>',
    '<blockquote class="fs-quote"><p>"Hats off, gentlemen, a genius!"</p>',
    '<p>— Robert Schumann, greeting Chopin\'s first published music in print</p>',
    '</blockquote>',
    '<h2>what to play, what to hear</h2>',
    '<p>The <b>nocturnes</b> first, always. Night pieces, the idea borrowed from the',
    'Irishman John Field but made into something deeper. A singing right hand over a',
    'rocking left, and in the middle a storm, and then the song comes back changed.',
    'The one in E flat, Op. 9 No. 2, is the one everybody knows. The one in C sharp',
    'minor, and the one in C minor, Op. 48, are the ones that break your heart.</p>',
    '<p>Then the <b>ballades</b>, four of them, where he took a word from poetry and',
    'made a form nobody had made before, a piece that tells a story without words',
    'and gathers speed until the ending overwhelms you. The <b>mazurkas</b> and the',
    '<b>polonaises</b> are his Poland, the dances of home, the mazurka private and',
    'the polonaise proud, the "Heroic" Polonaise in A flat like a whole country',
    'refusing to kneel. And the <b>preludes</b>, Op. 28, twenty-four of them, one in',
    'every key, some no longer than a breath.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/chopin-01.jpg" alt=""><span class="indie-cap">Chopin, the 1849 Bisson daguerreotype (public domain)</span>',
    '<aside class="fs-aside"><p><b>a note on rubato.</b> Chopin\'s word for the way',
    'the melody bends the time while the accompaniment keeps steady, a give and',
    'take, stolen time (that is what rubato means). He is said to have told pupils',
    'the left hand is the conductor and must not waver, and the right hand may sigh',
    'and hurry over the top. Play it too freely and it turns to mush. That is the',
    'hardest thing in him and it is not in the notes.</p></aside>',
    '<h2>George Sand and Majorca</h2>',
    '<p>The great love of his life was the novelist Aurore Dupin, who wrote as',
    'George Sand, wore trousers, smoked cigars, and scandalised Paris. They were',
    'together for nearly ten years. In the winter of 1838 they went to Majorca for',
    'his health and it went wrong, cold and damp in an old monastery at Valldemossa,',
    'the locals frightened of his coughing, but he finished the preludes there. The',
    'story that the "Raindrop" Prelude came from rain dripping on the roof is Sand\'s',
    'and may be too pretty to be true, but I believe it because I want to.</p>',
    '<p class="fs-pull">He was consumptive most of his adult life and died at',
    'thirty-nine. Tuberculosis, the illness that took so many of them. He asked for',
    'Mozart\'s Requiem at his funeral and they played it.</p>',
    '<p>if you love him you will love the other short-lived one, poor',
    '<a href="schubert.geocities.ws">Schubert</a>, gone at thirty-one, who did for',
    'the song what Chopin did for the piano. and if you want the OPPOSITE of Chopin,',
    'go and hear the wild Frenchman <a href="berlioz.geocities.ws">Berlioz</a>, who',
    'wanted a thousand players where Chopin wanted ten fingers and a candle. Chopin',
    'thought Berlioz far too loud, by the way. he was probably right.</p>',
    '<hr>',
    '<p><small>counter: 02240 · best viewed at 800x600 · a MIDI of the E flat',
    'nocturne used to autoplay here until three people complained, so it is gone,',
    'you are welcome · shrine last tended 21 Feb · ~Wanda~</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Clara Schumann: the concert write-up -----------------------------------

const CLARA = P('clara-schumann.geocities.ws', 'CLARA SCHUMANN',
  'Recital: Clara Schumann, the pianist and the composer', [
    '<!--bg:comp-romantic-->',
    '<h1>Clara Schumann (1819–1896)</h1>',
    '<p><small>A write-up of an all-Clara-Schumann recital, and of the woman it',
    'honoured. Programme and notes below. Best viewed at 800x600.</small></p>',
    '<hr>',
    '<p>The recital opened, rightly, by reminding us who she was before she was',
    'anyone\'s wife. Clara Wieck was one of the supreme pianists of the nineteenth',
    'century, trained by her demanding father Friedrich Wieck, giving public',
    'concerts from the age of nine and touring Europe as a celebrated virtuoso',
    'while still a girl. Her concert career ran for more than sixty years. She was',
    'a working musician into her seventies, and for much of that time the chief',
    'breadwinner of a large family.</p>',
    '<pre>',
    'PROGRAMME',
    '  Piano Concerto in A minor, Op. 7        (composed 1833–35)',
    '  Three Romances for violin and piano, Op. 22   (1853)',
    '  Piano Trio in G minor, Op. 17           (1846)',
    '  Selected Lieder, Op. 13',
    '  encore: a Romance in the composer\'s own hand',
    '</pre>',
    '<p>The concerto came first, and it is astonishing to sit with the fact that',
    'she began it at thirteen and finished it at sixteen, orchestrating it with some',
    'counsel from the young Robert Schumann, who was then her father\'s lodger and',
    'pupil. It is a Romantic concerto full of daring, the soloist and orchestra',
    'passing the argument between them, and it was written by a schoolgirl who then',
    'went out and played it herself.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/clara-schumann-01.jpg" alt=""><span class="indie-cap">Clara Schumann, 1857 (photo: Hanfstaengl, public domain)</span>',
    '<p>The <b>Piano Trio in G minor, Op. 17</b> was the evening\'s centre and, for',
    'my money, her masterpiece. It is a serious, closely argued chamber work, the',
    'equal of anything her husband or her friend Brahms wrote in the form, and for',
    'years it was patronised as "remarkable for a woman". Strike that phrase from',
    'your vocabulary. It is remarkable, full stop, a piece of the first rank that',
    'the concert hall left in a drawer for a century.</p>',
    '<aside class="fs-aside"><p><b>On her own low estimate of herself.</b> She once',
    'wrote in a diary that a woman must not wish to compose, that none had been able',
    'to do it and why should she expect to be the one. We should read that not as',
    'her true opinion of her gift but as the voice of her century speaking through',
    'her. The works answer it. The prejudice was the age\'s, not hers.</p></aside>',
    '<p>She married Robert Schumann in 1840 after a bitter court fight with her',
    'father, who did everything to stop it. The marriage was a partnership of two',
    'composers, though the household and the children and the concert tours that',
    'paid for them fell mostly to her. When Robert broke down and was taken to the',
    'asylum where he died in 1856, she did not fall silent. She raised the family',
    'by her playing, and she became the guardian and the great interpreter of his',
    'music, keeping it before the public until it could not be ignored.</p>',
    '<p class="fs-pull">And she gave the world Brahms. It was Clara, more than',
    'anyone, who saw what the young man was, played his music, advised it, and',
    'carried it into the concert halls of Europe on the strength of her own name.</p>',
    '<p>Her fifty-year friendship with <a href="brahms.geocities.ws">Brahms</a> is',
    'one of the deepest bonds in the history of the art, and each was the other\'s',
    'first reader to the end. She belongs, too, beside the other great woman',
    'composer the century underrated, <a href="fanny-mendelssohn.geocities.ws">Fanny',
    'Mendelssohn</a>, whose songs Clara knew and whose fate, published under a',
    'brother\'s name, was the mirror of the pressures Clara spent her life pushing',
    'against.</p>',
    '<hr>',
    '<p><small>visitors: 01464 · best viewed at 800x600 · recital held in the town',
    'hall, a full house · write-up posted 6 Mar</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Fanny Mendelssohn: the student coursework ------------------------------

const FANNY = P('fanny-mendelssohn.geocities.ws', 'FANNY MENDELSSOHN',
  'MUS204 coursework: Fanny Mendelssohn Hensel', [
    '<!--bg:comp-romantic-->',
    '<h1>Fanny Mendelssohn Hensel (1805–1847)</h1>',
    '<p><small>MUS204 Music and Society, essay 2, "A composer the century would not',
    'hear". submitted work, please do not copy, the tutor runs everything past the',
    'library. best viewed at 800x600. — student no. 9910427</small></p>',
    '<hr>',
    '<p>This essay argues that Fanny Mendelssohn was a composer of the first rank',
    'who was kept from a public career by her family and her class and her sex, and',
    'that the recovery of her roughly four hundred works is one of the important',
    'jobs of music history. She was the elder sister of Felix Mendelssohn, the',
    'famous one, and by the account of everyone who knew them both, including Felix,',
    'she was every bit his equal at the keyboard and on the page.</p>',
    '<h2>1. the wall in front of her</h2>',
    '<p>The Mendelssohns were a wealthy, cultivated Berlin family, and that wealth',
    'did not help her. Her father wrote to her that music could only ever be an',
    '"ornament" for her, never a profession as it would be for Felix. Even Felix,',
    'who loved her and showed her his work first, opposed her publishing, on the',
    'grounds that it was not a woman\'s place. So most of what she wrote was played',
    'in one room, for one circle, and never printed in her lifetime under her own',
    'name.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/fanny-mendelssohn-01.jpg" alt=""><span class="indie-cap">Fanny Mendelssohn (public domain)</span>',
    '<h2>2. the Sunday concerts</h2>',
    '<p>Her outlet was the <i>Sonntagsmusik</i>, the Sunday musicales she ran at the',
    'family house in Berlin, where she conducted, played, and premiered her own',
    'music before an invited audience of the city\'s cultural life. It was a serious',
    'concert series in all but name, and it was hers. It is where much of her choral',
    'and chamber music was first heard.</p>',
    '<aside class="fs-aside"><p><b>the songs under Felix\'s name.</b> Several of',
    'Fanny\'s songs were published in Felix\'s early collections as his own. The',
    'famous story: when Felix visited Queen Victoria, she told him her favourite of',
    'his songs was "Italien", and he had to confess it was Fanny\'s. A charming',
    'anecdote that is also a quiet scandal. Her work was good enough to be a queen\'s',
    'favourite, and it could only reach the queen wearing her brother\'s name.</p>',
    '</aside>',
    '<h2>3. the music itself</h2>',
    '<p>The best case for her is not the biography but the notes. The song cycle and',
    'piano year <b>Das Jahr</b> (1841), twelve character pieces, one for each month,',
    'is her large statement, and it is a major Romantic piano work by any measure.',
    'Her <b>Piano Trio in D minor, Op. 11</b>, written in her last year, is warm and',
    'assured. And there are the <i>Lieder</i>, hundreds of them, songs the equal of',
    'the men who filled the printed anthologies of the day.</p>',
    '<p>Late on, and against Felix\'s wishes, she began at last to publish under her',
    'own name, her Op. 1 appearing in 1846. Then in 1847 she collapsed and died of a',
    'stroke while rehearsing, at forty-one. Felix, stricken, died six months later.',
    'The recognition she was owed came more than a century after that, as the',
    'manuscripts were finally edited and heard.</p>',
    '<p>For the other great woman composer of these decades, and a life that ran the',
    'same gauntlet with a different ending, see',
    '<a href="clara-schumann.geocities.ws">Clara Schumann</a>. For a sense of what a',
    'freely published career in the same years could be, the poet of the piano',
    '<a href="chopin.geocities.ws">Chopin</a> makes the contrast plain.</p>',
    '<hr>',
    '<pre>',
    'WORKS CITED (as far as i could find them in the library)',
    '  Todd, R. Larry — Fanny Hensel: The Other Mendelssohn',
    '  Reich, Nancy B. — chapter in Women Making Music',
    '  sleeve notes to a recording of Das Jahr',
    '  lecture handout, week 6 (see tutor)',
    '</pre>',
    '<p><small>hits: 00612 · best viewed at 800x600 · coursework, marked and',
    'returned · posted 2 Feb, tutor said "more on the music, less on the brother" so',
    'i added section 3</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Berlioz: the lecture write-up ------------------------------------------

const BERLIOZ = P('berlioz.geocities.ws', 'BERLIOZ',
  'Lecture write-up: Berlioz and the orchestra as instrument', [
    '<!--bg:comp-romantic-->',
    '<h1>Hector Berlioz (1803–1869)</h1>',
    '<p><small>My notes from a public lecture, "Berlioz and the invention of the',
    'orchestra", tidied up for the ring. Any errors are mine, not the speaker\'s.',
    'Best viewed at 800x600.</small></p>',
    '<hr>',
    '<p>The lecturer began with a provocation: that Berlioz is the strangest of the',
    'great Romantics because he barely played an instrument. No piano to speak of,',
    'a little guitar and flute. He heard in the orchestra directly, as a single vast',
    'instrument, and that, she argued, is exactly why he could imagine sounds nobody',
    'else could. He was not translating from the keyboard. He was composing in',
    'colour from the start.</p>',
    '<h2>the Symphonie Fantastique</h2>',
    '<p>The central exhibit, of course, was the <b>Symphonie Fantastique</b> (1830),',
    'written when he was twenty-six and mad with love for the Irish actress Harriet',
    'Smithson, whom he had seen on stage and did not yet know. The symphony tells',
    'the story of an artist\'s opium dream about his beloved, in five movements, and',
    'it came only three years after Beethoven died. The lecturer\'s point was how',
    'huge a leap it is: a symphony that is also a drama with a printed plot.</p>',
    '<aside class="fs-aside"><p><b>the idee fixe.</b> Berlioz\'s device, and his',
    'term. A single melody stands for the beloved, and it returns in every movement,',
    'changed each time to fit the scene, tender in the ballroom, uneasy in the',
    'country, and finally jeering and grotesque at the witches\' sabbath where the',
    'artist dreams he has been executed for her murder. One theme, many masks. It is',
    'the ancestor of every recurring film theme you have ever heard.</p></aside>',
    '<img class="indie-pic" src="assets/media/web/comp/berlioz-01.jpg" alt=""><span class="indie-cap">Hector Berlioz (public domain)</span>',
    '<p>The finale, the <i>Dream of a Witches\' Sabbath</i>, quotes the <i>Dies',
    'Irae</i>, the medieval chant for the dead, and hands it to shrieking woodwinds',
    'and tolling bells while the beloved\'s theme comes back as a cackling dance.',
    'Audiences in 1830 had never heard an orchestra do anything so lurid. He got',
    'his Harriet in the end, too, married her, and it did not go well, but that is',
    'another lecture.</p>',
    '<h2>the enormous orchestra</h2>',
    '<p>The speaker was firm that the caricature of Berlioz as the man who just',
    'wanted things LOUD misses the craft. Yes, he scored for forces that alarmed',
    'people, and his <b>Grande Messe des Morts</b> (Requiem, 1837) famously calls',
    'for four separate brass bands at the corners of the performing space and a',
    'great array of timpani. But the point of the size was space and terror and',
    'distance, sound coming from every side, not mere volume. He knew precisely what',
    'each instrument could do, and when to use only a single quiet one.</p>',
    '<blockquote class="fs-quote"><p>"Time is a great teacher, but unfortunately it',
    'kills all its pupils."</p><p>— Berlioz, attributed, from his witty and bitter',
    '<i>Memoirs</i></p></blockquote>',
    '<p>That knowledge became a book. His <b>Grand traite d\'instrumentation et',
    'd\'orchestration modernes</b> (Treatise on Instrumentation, 1844) is the first',
    'great manual of orchestration, studied by everyone who came after, and later',
    'revised by Richard Strauss. Berlioz effectively wrote down how the modern',
    'orchestra works. He also earned much of his living as a sharp and funny music',
    'critic, because France never quite gave the composer his due in his lifetime.</p>',
    '<p class="fs-pull">The frustrated French Romantic: admired abroad, resisted at',
    'home, forever mounting concerts that cost him more than they made. The genius',
    'and the impresario were the same exhausted man.</p>',
    '<p>The lecture closed by placing him among his peers. Against the miniaturist',
    'at the keyboard, the poet <a href="chopin.geocities.ws">Chopin</a>, who found',
    'a world in ten fingers where Berlioz wanted two hundred players, and beside the',
    'pianist-composer <a href="clara-schumann.geocities.ws">Clara Schumann</a>,',
    'whose art was chamber intimacy and long fidelity to a repertoire, so different',
    'a Romanticism from his fever and spectacle, and yet the same decades.</p>',
    '<hr>',
    '<p><small>counter: 00938 · best viewed at 800x600 · lecture given in the arts',
    'building, room full · notes posted 18 Mar</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

export const COMP_C = [BRAHMS, SCHUBERT, CHOPIN, CLARA, FANNY, BERLIOZ];
