// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — the US design canon and the simulation people.
//
// Fan pages, kept on a free host, each ABOUT a maker and never in the maker’s
// own voice. A 2600 kid who worships Carol Shaw and keeps the Women in Games
// ring going; an Activision cartridge collector on David Crane; a wargamer who
// took Chris Crawford’s art-form argument to heart; a “one more turn” Sid Meier
// devotee; and a city-builder who loves that Will Wright never let you win. The
// makers, games and years are real; the enthusiasm and the grudges are the fans’.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Carol Shaw: the 2600 kid who keeps the ring -----------------------------

const SHAW = P('river-raid-shaw.geocities.ws', 'RIVER RAID',
  'RIVER RAID // Carol Shaw flew it first', [
    '<!--bg:arcade-->',
    '<h1>RIVER RAID AND CAROL SHAW</h1>',
    '<p><small>a page for Carol Shaw, kept by a kid with an Atari 2600 and a',
    'joystick with a sticky button. my mum bought River Raid off a market stall',
    'and i have never really put it down. she is my favourite programmer and i',
    'will not hear a word against her. — jetstream</small></p>',
    '<hr>',
    '<p>Carol Shaw is one of the first professional women to design and program a',
    'video game, full stop, and people forget that because the industry has a',
    'short memory. She studied at Berkeley and went to Atari early, when the whole',
    'thing was a few rooms and a lot of nerve, and she wrote for the 2600 when the',
    '2600 was a monster that gave you almost nothing to work with.</p>',
    '<hr>',
    '<p><b>the games</b></p>',
    '<p>Her first cartridge was <i>3-D Tic-Tac-Toe</i> (1978, Atari), which sounds',
    'like a small thing until you try to fit a four-by-four-by-four board and an',
    'opponent that can actually think into a machine with the memory of a doorbell.',
    'She did it.</p>',
    '<p>Then the one everybody knows. <i>River Raid</i> (1982, Activision). You fly',
    'a jet up a river, you shoot the bridges and the tankers and the choppers, you',
    'watch the fuel gauge like a hawk and dip down over the fuel depots instead of',
    'blowing them up. It is tense in a way most 2600 games never managed, and it',
    'goes on and on and on.</p>',
    '<hr>',
    '<p><b>the trick that makes it magic</b></p>',
    '<p>Here is the bit i love. The river is HUGE, it branches, it narrows, it',
    'opens out, and it is the same river every single time you play so you can',
    'learn it. And it is not stored anywhere. The cartridge was about four',
    'kilobytes and there is no room in four kilobytes to draw a river that long.',
    'So she did not store it. She wrote a small routine, a pseudo-random generator',
    'with a chosen seed, that draws the whole river on the fly the same way every',
    'time. The map lives in the maths, not in the memory. That is the cleverest',
    'thing i have ever seen a game do and i have thought about it for years.</p>',
    '<hr>',
    '<p><b>and she got paid, which mattered</b></p>',
    '<p>River Raid came out on Activision, the label the programmers set up so they',
    'would get credit and a cut of what they made instead of being anonymous',
    'factory hands. Shaw was on the box. For a designer in 1982, and a woman',
    'designer at that, having your name on the box was not nothing.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>If you like Shaw you should meet Dona Bailey, who was writing coin-op',
    'assembly at the same time and made a garden of a game, over at',
    '<a href="centipede.geocities.ws">centipede</a>. And her Activision colleague',
    'David Crane, who pulled the same kind of rabbit out of the same kind of tiny',
    'hat, is at <a href="pitfall-crane.geocities.ws">pitfall-crane</a>. Go and',
    'read how Pitfall fits 255 screens in nothing and then come back and admire',
    'the river again.</p>',
    '<hr>',
    '<p><b>why she matters now</b></p>',
    '<p>Because when the machines got big and lazy everyone forgot how to make a',
    'little one sing, and Shaw never forgot, because she never had the room to be',
    'lazy in the first place. Every child who was told girls do not do this can be',
    'shown the box with her name on it. That is worth keeping a page up for.</p>',
    '<hr>',
    '<p><small>high score jar on the shelf: 1,382,140 and climbing · counter:',
    '02271 · best viewed at 640x480 · UNDER CONSTRUCTION, more screens of the',
    'river coming when i can be bothered to photograph the telly · last updated',
    '9 Aug</small></p>',
    '<p><small>',
    '[ <a href="sim-strategy-ring.geocities.ws">Sim &amp; Strategy Ring</a> ]',
    '[ <a href="women-in-games-ring.geocities.ws">Women in Games Ring</a> ]<br>',
    'proud ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- David Crane: the Activision cartridge collector -------------------------

const CRANE = P('pitfall-crane.geocities.ws', 'PITFALL',
  'PITFALL! // David Crane and 255 rooms from nothing', [
    '<!--bg:arcade-->',
    '<h1>PITFALL! AND DAVID CRANE</h1>',
    '<p><small>a page kept by someone who collects Activision cartridges and keeps',
    'them in a shoebox in date order. David Crane is why the box exists. i have two',
    'copies of Pitfall in case one wears out. — the shoebox</small></p>',
    '<hr>',
    '<p>David Crane was one of the Atari programmers who got fed up. The company',
    'would not put their names on the games and would not pay them a share of what',
    'the games earned, and treated the people writing the hits like interchangeable',
    'staff. So in 1979 Crane and three others walked out and founded ACTIVISION,',
    'the first company that made games for someone else’s console and, more to the',
    'point, printed the designer’s name and photo right there in the manual.</p>',
    '<hr>',
    '<p><b>the game</b></p>',
    '<p><i>Pitfall!</i> (1982) is Pitfall Harry running through a jungle, swinging',
    'over tar pits and crocodiles on vines, dodging rolling logs and scorpions,',
    'grabbing treasure against a clock. It sold in the millions and it more or less',
    'invented the running-and-jumping game everyone copied afterwards.</p>',
    '<hr>',
    '<p><b>the trick, because it is the same trick</b></p>',
    '<p>There are 255 screens in Pitfall and the 2600 cartridge could not possibly',
    'hold 255 hand-drawn rooms. So Crane did what the clever ones all did: he did',
    'not store the rooms. The whole jungle is generated by a routine, a polynomial',
    'counter that produces the same sequence of screens every time, so the world',
    'is consistent and learnable and also basically free. You run left, you get one',
    'sequence, you run right, you get the reverse. The map is in the arithmetic.',
    'Read the Carol Shaw page and you will see the exact same idea holding up a',
    'different game.</p>',
    '<hr>',
    '<p><b>the rest of the shelf</b></p>',
    '<p>Crane made a pile of others, but the one i want people to try is <i>A Boy',
    'and His Blob</i> (1989), where you feed jellybeans to a blob and it turns into',
    'a ladder or a trampoline or a hole in the ground depending on the flavour. It',
    'is odd and gentle and nobody else would have thought of it.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>Straight to <a href="river-raid-shaw.geocities.ws">river-raid-shaw</a>,',
    'his Activision colleague Carol Shaw, who squeezed a whole branching river out',
    'of four kilobytes. And for the other Atari programmer who got angry about not',
    'being credited and did something famous about it, see Warren Robinett at',
    '<a href="adventure-robinett.geocities.ws">adventure-robinett</a>, who hid his',
    'own name in a secret room because the company would not put it on the box.</p>',
    '<hr>',
    '<p><b>why it matters now</b></p>',
    '<p>Because the whole story is about who gets the credit and who keeps the',
    'value of the work, and that argument never actually went away, it just moved',
    'buildings. Crane and his friends walked out and built a place where the maker',
    'had a name. Worth remembering who did that, and why.</p>',
    '<hr>',
    '<p><small>cartridges in the shoebox: 61 · counter: 01498 · best viewed at',
    '640x480 · UNDER CONSTRUCTION, scanning the manuals so you can read the credits',
    'yourself · last updated 21 Jul</small></p>',
    '<p><small>',
    '[ <a href="sim-strategy-ring.geocities.ws">Sim &amp; Strategy Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Chris Crawford: the wargamer who believes games are art ------------------

const CRAWFORD = P('balance-crawford.geocities.ws', 'BALANCE OF POWER',
  'BALANCE OF POWER // Chris Crawford, games as art', [
    '<!--bg:adventure-->',
    '<h1>CHRIS CRAWFORD AND BALANCE OF POWER</h1>',
    '<p><small>kept by an old wargamer who used to push cardboard counters around a',
    'hex map on the kitchen table and then a computer took the bookkeeping away and',
    'left the thinking. Crawford is the one who told me a game could be about',
    'something. — hexmap harry</small></p>',
    '<hr>',
    '<p>Chris Crawford came out of Atari’s research lab and never quite fitted the',
    'games business, because he wanted games to be about ideas and the business',
    'wanted them to be about shooting. He is a wargamer at heart and a moralist by',
    'temperament, and he has spent his whole life arguing that this medium is an',
    'art form and ought to behave like one.</p>',
    '<hr>',
    '<p><b>the games</b></p>',
    '<p><i>Eastern Front (1941)</i> (1981, Atari) was a proper strategic wargame on',
    'a home computer, the German invasion of Russia, with an enemy the machine',
    'actually played against you. That alone was a small miracle on eight-bit',
    'hardware.</p>',
    '<p>Then the one that made his name. <i>Balance of Power</i> (1985). You play',
    'the United States or the Soviet Union through the Cold War, and you push for',
    'advantage around the world, and the whole design has a sting in it: if you',
    'push too hard you trigger a nuclear war, and when you do the game does not',
    'show you mushroom clouds. It stops and prints a line telling you that you have',
    'lost, and that there is no winner and no second chance, and it refuses to',
    'dignify the ending with a picture. You win by not starting the war. A game',
    'about restraint, in the middle of the decade that most needed it.</p>',
    '<hr>',
    '<p><b>the campaigner</b></p>',
    '<p>Crawford did as much off the screen as on it. He founded the <i>Journal of',
    'Computer Game Design</i> so the people making these things would write down',
    'what they were learning, and he started the gathering that grew into the game',
    'developers’ conference, where the industry still meets and argues every year.',
    'He wrote <i>The Art of Computer Game Design</i> and put it out where anyone',
    'could read it. He was building a discipline while everyone else was building',
    'products.</p>',
    '<hr>',
    '<p><b>the Dragon Speech</b></p>',
    '<p>In 1992 he stood up in front of the whole conference he had helped start,',
    'said the industry had sold out its promise as an art form, drew a sword,',
    'called on a dragon, and walked off to go and chase the harder dream on his',
    'own. People still talk about it. Whether he was right or just impossible',
    'depends who you ask, but nobody who was there forgot it.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>Two doors along the same corridor. Dani Bunten Berry, who believed a game',
    'was a room you put people in together, is at',
    '<a href="mule-bunten.geocities.ws">mule-bunten</a>, and if Crawford is the',
    'moralist of this street she is its heart. And Sid Meier, who took the strategy',
    'game and made it something millions could not stop playing, is at',
    '<a href="civilization-meier.geocities.ws">civilization-meier</a>. Crawford',
    'wanted games to matter; Meier made the mattering fun. Read them together.</p>',
    '<hr>',
    '<p><b>why he matters now</b></p>',
    '<p>Because he asked, decades early, whether the thing we were building was',
    'going to say anything or just sell, and he was willing to be a nuisance about',
    'it. When the shine comes off a medium the people who cared what it was FOR are',
    'the ones still worth reading. Crawford cared, loudly, from the start.</p>',
    '<hr>',
    '<p><small>counter: 00889 · best viewed at 640x480 · UNDER CONSTRUCTION, typing',
    'up my old Eastern Front notes · last updated 4 Jun</small></p>',
    '<p><small>',
    '[ <a href="sim-strategy-ring.geocities.ws">Sim &amp; Strategy Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Sid Meier: the "one more turn" devotee ----------------------------------

const MEIER = P('civilization-meier.geocities.ws', 'CIVILIZATION',
  'CIVILIZATION // Sid Meier and one more turn', [
    '<!--bg:adventure-->',
    '<h1>SID MEIER AND CIVILIZATION</h1>',
    '<p><small>kept by someone who has lost more nights to this man’s games than to',
    'anything else in my life and regrets none of them. it is always “one more',
    'turn” and then the birds are singing. — dawn patrol</small></p>',
    '<hr>',
    '<p>Sid Meier co-founded MicroProse and spent the eighties and nineties quietly',
    'working out how to make a strategy game that a normal person could not put',
    'down. He is not loud about it. He just keeps making the thing where you say',
    'you will stop after this turn and then it is three in the morning.</p>',
    '<hr>',
    '<p><b>the games</b></p>',
    '<p><i>Pirates!</i> (1987) is still the one a lot of us love best, a whole',
    'Caribbean you sail around doing a bit of everything, sword fights and trade',
    'and treasure and romance, with no single track through it. <i>Railroad',
    'Tycoon</i> (1990) let you lay track and run a network and watch a country grow',
    'up around your lines. And then <i>Civilization</i> (1991), where you take one',
    'people from a single settler in 4000 BC all the way to spaceflight, building',
    'cities, researching everything humans ever worked out, meeting and fighting',
    'and trading with the neighbours. There is nothing else quite like the first',
    'time the map opens up in front of you.</p>',
    '<hr>',
    '<p><b>the one line worth pinning up</b></p>',
    '<p>His definition of what he does, and it is the best short one anybody has',
    'given:</p>',
    '<blockquote><p>“a game is a series of interesting decisions”</p></blockquote>',
    '<p>Not interesting graphics, not an interesting story someone else wrote for',
    'you. Decisions. If a choice is obvious it is not interesting, and if it is',
    'random it is not a decision, so the whole craft is filling the game with',
    'choices where you genuinely cannot tell which is best and you have to weigh it',
    'and commit. Do that turn after turn and you get the thing that eats the night.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>Up the road is Chris Crawford at',
    '<a href="balance-crawford.geocities.ws">balance-crawford</a>, who was making',
    'strategy games about ideas before Meier made them into something everybody',
    'played, and the two of them mark the two poles of this whole street, the',
    'argument and the addiction. And Will Wright at',
    '<a href="sim-city-wright.geocities.ws">sim-city-wright</a> took the other fork',
    'entirely and built games with no way to win at all. Between winning too much',
    'and never winning, this ring has both.</p>',
    '<hr>',
    '<p><b>why he matters now</b></p>',
    '<p>Because he taught a generation to think in systems without ever calling it',
    'that, to hold a hundred moving parts in their head and make a decent call, one',
    'turn at a time. That habit does not stop being useful when the lights get low.',
    'The map still opens up. You still have to choose.</p>',
    '<hr>',
    '<p><small>turns played this week: too many · counter: 03107 · best viewed at',
    '640x480 · UNDER CONSTRUCTION, a strategy guide for the deity difficulty that i',
    'cannot actually beat yet · last updated 14 Aug</small></p>',
    '<p><small>',
    '[ <a href="sim-strategy-ring.geocities.ws">Sim &amp; Strategy Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Will Wright: the city-builder who loves not winning ----------------------

const WRIGHT = P('sim-city-wright.geocities.ws', 'SIMCITY',
  'SIMCITY // Will Wright and the game you cannot win', [
    '<!--bg:adventure-->',
    '<h1>WILL WRIGHT AND SIMCITY</h1>',
    '<p><small>kept by someone who builds cities the way other people do jigsaws, a',
    'bit each evening, no reason, just to see it work. Will Wright made the toy i',
    'never grew out of. — the zoning board</small></p>',
    '<hr>',
    '<p>Will Wright co-founded Maxis and spent his career making things that are',
    'barely games at all, in the best way. He calls them software TOYS, and he',
    'means it. A toy does not tell you what to do with it. You pick it up and you',
    'find out what it does by poking it, and the fun is the finding out, not the',
    'winning, because there is no winning.</p>',
    '<hr>',
    '<p><b>the games</b></p>',
    '<p><i>SimCity</i> (1989) started as the map editor for a shoot-em-up he was',
    'making, and he realised he was having more fun building the city than blowing',
    'it up, so he threw the shooting away. You are the planner. You zone the land,',
    'lay the roads and the power, set the taxes, and the city fills itself in and',
    'pushes back, and traffic snarls and crime rises and you fiddle and watch. No',
    'score, no finish line, no dragon.</p>',
    '<p>Then the same idea pointed at everything. <i>SimEarth</i> (1990), a whole',
    'planet and its climate and its life to tend. <i>SimAnt</i> (1991), a colony',
    'seen from the ants’ own height. And later, most famously, <i>The Sims</i>',
    '(2000), a dolls’ house with the whole of everyday life inside it, which became',
    'one of the best-selling games there has ever been by letting people just live',
    'a little pretend life and rearrange the furniture.</p>',
    '<hr>',
    '<p><b>the central idea</b></p>',
    '<p>The city is a SYSTEM, and Wright’s games hand you the system and let you',
    'poke it and see what the poke does three moves later. There is no way to win a',
    'system, there is only a way to understand it, and understanding it is the',
    'whole pleasure. You are not beating SimCity. You are learning how a city hangs',
    'together by watching yours nearly fall apart. That is a genuinely different',
    'thing from every game with a top score, and he did it first and best.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>Right next door is Sid Meier at',
    '<a href="civilization-meier.geocities.ws">civilization-meier</a>, who builds',
    'systems you very much CAN win, so put the two side by side and you have the',
    'whole question of whether a game needs a winner. And Peter Molyneux at',
    '<a href="populous-molyneux.geocities.ws">populous-molyneux</a> came at the',
    'same god’s-eye idea from the British side and got there around the same time,',
    'a whole world under your hand to prod and watch.</p>',
    '<hr>',
    '<p><b>why he matters now</b></p>',
    '<p>Because he spent his life teaching people to see the systems they live',
    'inside as things you can poke and understand rather than weather you just',
    'suffer. A city, a climate, a household, all of them a set of dials with',
    'consequences down the line. Keep a hand on the dials and keep watching what',
    'the last change did. Wright made a generation want to.</p>',
    '<hr>',
    '<p><small>current metropolis population: 214,900, mostly cross · counter:',
    '02640 · best viewed at 640x480 · UNDER CONSTRUCTION, uploading my no-roads',
    'city that somehow still works · last updated 30 Jul</small></p>',
    '<p><small>',
    '[ <a href="sim-strategy-ring.geocities.ws">Sim &amp; Strategy Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const GAMES_E = [SHAW, CRANE, CRAWFORD, MEIER, WRIGHT];
