// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH ARCH_C — brutalism & the postwar.
//
// The architecture enthusiast's cached web, brutalist wing. A Kahn shrine kept
// by a student who has been to Dhaka; a Niemeyer profile; a close reading of the
// Smithsons at Hunstanton and Robin Hood Gardens; a movement primer on béton
// brut; a building-spotter's love letter to the Barbican; and a Kenzo Tange
// profile. The architects, buildings and dates are real; the enthusiasm is the
// fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Louis Kahn: the showpiece shrine ---------------------------------------

const KAHN = P('louis-kahn.geocities.ws', 'LOUIS KAHN',
  'LOUIS KAHN — what does the brick want to be? // a shrine', [
    '<!--bg:arch-brutalist-->',
    '<h1>LOUIS KAHN</h1>',
    '<p><small>a shrine to Louis I. Kahn (1901&ndash;1974), kept by a fifth-year',
    'student who saved up and went to Dhaka to see the Assembly building and came',
    'back changed. i have redrawn the Salk section by hand more times than i have',
    'redrawn my own studio project. — R., school of architecture</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;A great building must begin with the unmeasurable,',
    'must go through measurable means when it is being designed, and in the end',
    'must be unmeasurable.&rdquo; <br>&mdash; Louis Kahn</p>',
    '<hr>',
    '<p>Kahn came late. He was past fifty before the buildings that made his name',
    'arrived, and for a while he taught and drew and waited. Then in the 1950s and',
    '60s he made a handful of structures so heavy and so still that they seem to',
    'have been dug up rather than built. Brick, concrete, travertine, the light',
    'coming in as if it were a material too. He is often filed under brutalism',
    'because of the weight and the raw surfaces, and the neighbours are close (see',
    '<a href="brutalism.geocities.ws">brutalism</a>), but Kahn is really his own',
    'thing, a modernist who went back past modernism to Rome and the pyramid and',
    'the ruin.</p>',
    '<h2>the Salk Institute</h2>',
    '<p>The one people cross oceans for. At La Jolla in California, finished 1965,',
    'Kahn built two long laboratory blocks for Jonas Salk facing each other across',
    'a court, and the great decision, urged on him by Luis Barragán, was to leave',
    'that court EMPTY. No garden. A plane of travertine split down the middle by a',
    'thin channel of water that runs out toward the Pacific, so the whole thing',
    'aims at the horizon. The study towers turn at an angle to catch the light. It',
    'is the most photographed empty space in modern architecture and standing in',
    'it is very quiet.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/salk-institute-01.jpg" alt=""><span class="indie-cap">The Salk Institute by Louis Kahn (photo: Roman Eugeniusz, CC BY-SA 3.0)</span>',
    '<p>The section is the lesson. Between each working floor Kahn slung a full',
    'storey of SERVICE space, the pipe runs and the ducts and the trunking, so',
    'that the laboratories could be changed forever without ever touching the',
    'served rooms. Which brings us to the idea he is loved for.</p>',
    '<h2>served and servant spaces</h2>',
    '<p>Kahn split every plan into the spaces you SERVE, the rooms where life',
    'happens, and the spaces that SERVE them, the stairs and shafts and ducts and',
    'stores. Most architects hide the servant. Kahn gave it its own body, pulled',
    'it out and made towers and hollow walls of it, so you can read the building',
    'like a plan just by walking round it. At the Richards Medical Research',
    'building in Philadelphia (1960) the brick service towers stand up like a',
    'little city, and the lesson went round the world.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;You say to a brick, what do you want,',
    'brick? And brick says to you, I like an arch. And you say to brick, look, I',
    'want one too, but arches are expensive and I can use a concrete lintel. And',
    'then you say, what do you think of that, brick? Brick says, I like an',
    'arch.&rdquo;</p><p><small>&mdash; Louis Kahn, to his students</small></p></blockquote>',
    '<p>It sounds like a joke and it is not. Asking what the brick WANTS to be is',
    'Kahn insisting that a material has an honest nature, that a form should come',
    'from what the stuff and the making truly are, and not be pressed on from',
    'outside. Give the brick the arch it asks for. This is the deepest thing he',
    'taught and it is why students who never lay a brick still quote him.</p>',
    '<h2>Dhaka</h2>',
    '<p>His masterwork, and he did not live to see it finished. The National',
    'Assembly Building at Dhaka in Bangladesh (Jatiyo Sangsad Bhaban), begun 1962,',
    'completed 1982, eight years after he died. A vast citadel of concrete',
    'poured in bands with strips of marble between the pours, pierced by enormous',
    'circles and triangles and squares cut clean through the walls, so that the',
    'brutal weight is full of daylight. A parliament made to look ancient the day',
    'it opened. That a poor new country built this, and keeps it, and governs from',
    'inside it, is part of why people weep a little when they arrive.</p>',
    '',
    '<p class="fs-pull">He wanted the monumental silence, and the light that makes',
    'it speak.</p>',
    '<p>What he chased, over and over, was that silence. The heavy enclosure, the',
    'small hard-won openings, the light arriving as an event rather than a given.',
    'His late unbuilt and built work all reaches for it: the Kimbell Art Museum',
    'at Fort Worth (1972), with its cycloid vaults and the silver light washing',
    'down the curve of the concrete, is the gentlest proof that heavy need not',
    'mean dark.</p>',
    '<hr>',
    '<p><b>the buildings, if you are making a pilgrimage</b></p>',
    '<pre>',
    '  1953   Yale University Art Gallery ......... New Haven, USA',
    '  1960   Richards Medical Research .......... Philadelphia, USA',
    '  1965   Salk Institute .................... La Jolla, USA',
    '  1965   First Unitarian Church ............ Rochester, USA',
    '  1969   Indian Institute of Management .... Ahmedabad, India',
    '  1972   Kimbell Art Museum ................ Fort Worth, USA',
    '  1974   Yale Center for British Art ....... New Haven, USA  (finished 1977)',
    '  1982   National Assembly Building ........ Dhaka, Bangladesh (begun 1962)',
    '</pre>',
    '<div class="fs-aside"><b>did you know?</b> Kahn died of a heart attack in a',
    'lavatory at Pennsylvania Station in New York in 1974, coming home from Dhaka.',
    'He had crossed out the address on his passport and for two days no one knew',
    'who the body was. The architect of the most monumental buildings of his age,',
    'unclaimed in a railway station. His son Nathaniel later made a film about',
    'searching for him, <i>My Architect</i>.</div>',
    '<hr>',
    '<p>Kahn taught for years at Penn and his students carried the served-and-',
    'servant idea and the love of the ruin out into the world. The nearest kin on',
    'this ring is the raw concrete of <a href="brutalism.geocities.ws">brutalism</a>,',
    'and across the water the other great poured-concrete poet of the age, Oscar',
    'Niemeyer at <a href="oscar-niemeyer.geocities.ws">oscar-niemeyer</a>, who took',
    'the same material and made it curve where Kahn made it stand still.</p>',
    '<hr>',
    '<p><small>counter: 03571 · best viewed in Netscape at 800x600 · this page is',
    'under construction, the Kimbell section wants redrawing · last updated 14 Mar',
    '</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a member of the buildings webring. « prev · random · next »</small></p>',
  ]);

// ---- Oscar Niemeyer: architect profile --------------------------------------

const NIEMEYER = P('oscar-niemeyer.geocities.ws', 'NIEMEYER',
  'OSCAR NIEMEYER // the curve and the century', [
    '<!--bg:arch-brutalist-->',
    '<h1>OSCAR NIEMEYER</h1>',
    '<p><small>a page for Oscar Niemeyer (1907&ndash;2012) by a conservation',
    'volunteer who thinks the man is filed under the wrong heading. yes it is',
    'concrete. no it is not brutalism. keep reading. — F.</small></p>',
    '<hr>',
    '<p>Niemeyer built for the best part of a century. He was drawing curves in',
    'Rio in the 1930s and he was still drawing them past his hundredth birthday,',
    'and in between he built a capital city. If you want one architect to argue',
    'that concrete can be sensual rather than severe, it is this one.</p>',
    '<p class="fs-epi">&ldquo;I am not attracted to straight angles or to the',
    'straight line, hard and inflexible, created by man. I am attracted to',
    'free-flowing, sensual curves.&rdquo; <br>&mdash; Oscar Niemeyer</p>',
    '<p>He said the curve came from the mountains of Rio, from the river, from the',
    'body of the woman, from the clouds. Where the international modern went',
    'rectilinear and cool, Niemeyer poured reinforced concrete into shapes it had',
    'no business making, thin shells and long ramps and domes turned upside down,',
    'because concrete could span and cantilever in ways stone never could and he',
    'wanted to see how far the free plastic form would go.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/brasilia-01.jpg" alt=""><span class="indie-cap">The Cathedral of Brasília by Niemeyer (photo: Ugkoeln, CC BY-SA 3.0)</span>',
    '<h2>Brasília</h2>',
    '<p>The great commission. In 1956 President Juscelino Kubitschek resolved to',
    'build a wholly new capital in the empty central plateau and to do it in under',
    'four years. Lúcio Costa laid out the plan, the famous pilot shape like a bird',
    'or an aeroplane, and Niemeyer designed the monuments along it. It opened in',
    '1960, raised out of red dust at enormous speed and cost, a modern capital',
    'built from nothing by a country that was told it could not.</p>',
    '<p>Two buildings carry it. The Cathedral of Brasília is a crown of sixteen',
    'curved concrete ribs that sweep up and open to the sky, so you enter down a',
    'dark ramp and rise into a flood of light with stained glass hung between the',
    'ribs. And the National Congress sets the two chambers as a shallow dome and a',
    'shallow bowl, one cupped up and one turned down, on a great flat platform',
    'between the twin towers of the secretariat. A whole theory of government',
    'written in two curves and a slab.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Brasília is the capital of hope.&rdquo;',
    '</p><p><small>&mdash; André Malraux, on the new city</small></p></blockquote>',
    '<h2>the convictions</h2>',
    '<p>Niemeyer was a lifelong Communist and never hid it. When the military',
    'took Brazil in 1964 he was harassed and his office raided, and in 1965 he',
    'left for exile in France, where he worked through the years of the',
    'dictatorship, building the headquarters of the French Communist Party in',
    'Paris among much else. He came home when it was safe and went on working. He',
    'kept his politics and his optimism both, which in that century was not easy.</p>',
    '<p>He died in December 2012, ten days short of 105, still with a studio, still',
    'drawing. The obituaries reached for the word "century" and were right to.</p>',
    '<hr>',
    '<p>The nearest company on this ring is Louis Kahn at',
    '<a href="louis-kahn.geocities.ws">louis-kahn</a>, the other poet of poured',
    'concrete, who went heavy and still where Niemeyer went light and moving, and',
    'across the world Kenzo Tange at <a href="kenzo-tange.geocities.ws">kenzo-tange</a>,',
    'who also swept concrete into curves for a nation rebuilding itself.</p>',
    '<hr>',
    '<p><small>visitors: 01206 · best viewed at 800x600 · a buildings webring page',
    '· last updated 22 Feb</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>ring member. « prev · random · next »</small></p>',
  ]);

// ---- The Smithsons: a single-building close reading --------------------------

const SMITHSONS = P('alison-and-peter-smithson.geocities.ws', 'SMITHSONS',
  'THE SMITHSONS // as found, and the streets in the sky', [
    '<!--bg:arch-brutalist-->',
    '<h1>ALISON &amp; PETER SMITHSON</h1>',
    '<p><small>coursework, ARC304 Postwar British Architecture, close-reading',
    'assignment. i have tried to be fair to Robin Hood Gardens because everyone',
    'else just shouts. marks and comments welcome. — a second-year</small></p>',
    '<hr>',
    '<p>Alison Smithson (1928&ndash;1993) and Peter Smithson (1923&ndash;2003)',
    'were a married partnership who gave New Brutalism its theory as much as its',
    'buildings. They wrote and taught and argued as much as they built, and the',
    'writing is half of why they matter. The idea they are known for is the "as',
    'found".</p>',
    '<h2>the "as found"</h2>',
    '<p>Take the materials and the site and the ordinary things of a place as they',
    'actually are, rough and unglamorous, and make architecture out of that rather',
    'than out of an ideal. Show the brick as brick, the concrete as concrete, the',
    'services on the surface where you can see them. It is an ethic before it is a',
    'style, a refusal to prettify, and it runs straight into the raw concrete of',
    '<a href="brutalism.geocities.ws">brutalism</a> proper.</p>',
    '<h2>Hunstanton</h2>',
    '<p>Their first building and the one that started the argument. Hunstanton',
    'Secondary Modern School in Norfolk, won in competition in 1949, built by',
    '1954. A hard clear steel-and-glass frame, owing a great deal to Mies van der',
    'Rohe, but with everything left frankly exposed: the steel structure, the',
    'brick, and famously the water pipes and electrical runs on show rather than',
    'buried. The critic Reyner Banham took Hunstanton as the first true statement',
    'of the New Brutalism, the honest structure with nothing hidden.</p>',
    '',
    '<h2>the streets in the sky</h2>',
    '<p>Their great social idea, and their tragedy. The Smithsons hated the way',
    'modernist slab blocks stacked families in isolation, and they proposed the',
    'STREET DECK: wide access galleries, broad enough that they could be a real',
    'shared street lifted into the air, where children could play and neighbours',
    'could meet, the community of the old terraced street carried upward. They',
    'competed for it at Golden Lane in 1952 and did not win, but the idea travelled.</p>',
    '<p>They finally built it as Robin Hood Gardens in Poplar, east London, two',
    'long concrete blocks of council flats around a green mound, completed in',
    '1972. The streets in the sky were there, the concrete was frankly as found.',
    'And it did not work as they hoped: the decks were troubled, the estate was',
    'neglected and stigmatised, and after a long fight it was demolished from 2017,',
    'with the Victoria and Albert Museum saving a single three-storey section as a',
    'relic. The most famous "streets in the sky" ended as a museum fragment.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Belonging is a basic emotional need.',
    'From belonging comes the enrichment of the idea of association.&rdquo;</p>',
    '<p><small>&mdash; Alison and Peter Smithson</small></p></blockquote>',
    '<p>Bibliography (as far as i could get it): Smithson, A. &amp; P., <i>Urban',
    'Structuring</i> (1967); Smithson, A. &amp; P., <i>The Charged Void:',
    'Architecture</i> (2001); Banham, R., <i>The New Brutalism: Ethic or',
    'Aesthetic?</i> (1966), i only saw the introduction, the library copy is out;',
    'and a magazine piece on the Robin Hood Gardens demolition that i have',
    'photocopied but the date is cut off, i think 1998 or so.</p>',
    '<hr>',
    '<p>See also the wider movement at <a href="brutalism.geocities.ws">brutalism</a>,',
    'and for the other great British concrete estate of the age, kinder handled by',
    'history, the <a href="the-barbican.geocities.ws">the-barbican</a> in the City',
    'of London.</p>',
    '<hr>',
    '<p><small>counter: 00688 · best viewed in Netscape at 800x600 · handed in',
    'late, sorry · last updated 9 Apr</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a student page on the ring. « prev · random · next »</small></p>',
  ]);

// ---- Brutalism: a movement / style primer -----------------------------------

const BRUTALISM = P('brutalism.geocities.ws', 'BRUTALISM',
  'BRUTALISM // béton brut, the raw and the honest', [
    '<!--bg:arch-brutalist-->',
    '<h1>BRUTALISM</h1>',
    '<p><small>a primer for the newly converted, kept by someone who runs the',
    'local "save our concrete" campaign and is tired of the word being used to',
    'mean "a building i find ugly". read this before you sign the demolition',
    'petition. — the campaign secretary</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;Béton brut.&rdquo; &mdash; raw concrete, the phrase',
    'that named a movement</p>',
    '<hr>',
    '<p>First, the name. It does NOT come from the English word "brutal", whatever',
    'the tabloids tell you. It comes from the French <i>béton brut</i>, raw',
    'concrete, the term Le Corbusier used for the rough board-marked concrete of',
    'his Unité d\'Habitation at Marseille (1952), where the grain of the timber',
    'shuttering was left printed in the surface for all to see. The critic Reyner',
    'Banham then pinned "the New Brutalism" to the whole tendency in Britain in',
    'the 1950s. Two roots, one French and one English, twined from the start.</p>',
    '<h2>what it actually means</h2>',
    '<p>Brutalism is an ethic of honesty made visible. The rules, roughly:</p>',
    '<pre>',
    '  1. show the structure       the frame is not hidden, it IS the look',
    '  2. show the material        concrete raw, brick as brick, no facing',
    '  3. show the services        pipes and ducts on view, not buried',
    '  4. weight and mass          heavy, sculptural, monumental form',
    '  5. the honest section       the plan and section are legible outside',
    '</pre>',
    '<p>The love of raw concrete meant you could read a brutalist building the way',
    'you read an engine with the casing off. Nothing pretends to be marble.',
    'Nothing pretends to float. What holds the thing up is what you see.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/barbican-01.jpg" alt=""><span class="indie-cap">The Barbican Estate, London (photo: Colin, CC BY-SA 4.0)</span>',
    '<h2>the postwar reason</h2>',
    '<p>It was not only an aesthetic. After 1945 much of Europe had to be rebuilt',
    'fast and cheap, and concrete was the material that let a poor continent house',
    'its people, build its universities, its civic centres, its arts complexes and',
    'its social housing at speed. Brutalism is the architecture of the welfare',
    'state, of the council estate and the polytechnic and the public library. That',
    'is a large part of why it was later hated: people were hating the estate, and',
    'the politics, and blaming the concrete.</p>',
    '<div class="fs-aside"><b>did you know?</b> The very word turned on the',
    'buildings. By the 1980s "brutalist" was a slur, and dozens of these',
    'structures were demolished as eyesores. Then a new generation looked again,',
    'and now the survivors are photographed, listed, and fought over. The National',
    'Theatre in London, once loathed, is now a listed masterwork of the style.</div>',
    '<h2>the love and the loathing</h2>',
    '<p>No modern style has swung so far in reputation. To some, brutalism is cold,',
    'grey, inhuman, a concrete monster that stained in the rain and dated badly.',
    'To others it is the last time architecture was honest and civic and unafraid',
    'of weight, built for people rather than profit. Both camps are looking at the',
    'same walls. The campaign to save them is a campaign to keep the argument',
    'alive, and the buildings standing while we have it.</p>',
    '<hr>',
    '<p>For the theorists of the British strand see the',
    '<a href="alison-and-peter-smithson.geocities.ws">alison-and-peter-smithson</a>,',
    'who gave New Brutalism its "as found", and for the great survivor, listed and',
    'loved, visit the <a href="the-barbican.geocities.ws">the-barbican</a>.</p>',
    '<hr>',
    '<p><small>counter: 02044 · best viewed at 800x600 · save our concrete ·',
    'last updated 30 Jan</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>ring member. « prev · random · next »</small></p>',
  ]);

// ---- The Barbican: a single-building close reading ---------------------------

const BARBICAN = P('the-barbican.geocities.ws', 'THE BARBICAN',
  'THE BARBICAN // a city within the City', [
    '<!--bg:arch-brutalist-->',
    '<h1>THE BARBICAN</h1>',
    '<p><small>a building-spotter\'s love letter, kept by someone who has learned',
    'the highwalks so well she no longer gets lost, which locals will tell you is',
    'a genuine achievement. follow the yellow line. — the estate\'s unofficial',
    'guide</small></p>',
    '<hr>',
    '<p>The Barbican Estate stands on the northern edge of the City of London, on',
    'ground flattened by the Blitz, and it is the grandest piece of brutalism in',
    'Britain and possibly anywhere. Designed by the practice of Chamberlin, Powell',
    'and Bon, planned through the 1950s and 60s and built in stages, with the arts',
    'centre opened by the Queen in 1982, it is a whole small city of concrete',
    'raised on its own deck above the traffic.</p>',
    '<p class="fs-epi">&ldquo;The Barbican is a city within a city.&rdquo; <br>',
    '&mdash; a line the estate has worn for decades</p>',
    '<h2>the towers and the podium</h2>',
    '<p>Three towers, Cromwell, Lauderdale and Shakespeare, rise to over forty',
    'storeys and were for a time among the tallest residential buildings in Europe.',
    'Around and below them the flats step in long terraced blocks around gardens',
    'and lakes, and the whole estate sits on a raised PODIUM, a pedestrian deck',
    'that lifts residents clear of the roads, reached by the famous elevated',
    'highwalks. The concrete was hammer-dressed by hand, the aggregate exposed by',
    'pick, so that up close the grey surfaces have a rough worked texture rather',
    'than a smooth cast face.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/barbican-01.jpg" alt=""><span class="indie-cap">The Barbican Estate, London (photo: Colin, CC BY-SA 4.0)</span>',
    '<h2>the lakes and the arts centre</h2>',
    '<p>What softens the weight is water and planting. Ornamental lakes run along',
    'the foot of the terraces, with fountains and a residents\' garden, and the',
    'conservatory hides a jungle of tropical plants under glass above the theatre',
    'fly tower. Buried in the middle is the Barbican Centre itself, one of the',
    'largest performing arts complexes in Europe, a concert hall (home to the',
    'London Symphony Orchestra), two theatres, cinemas and galleries, and the',
    'old Guildhall School of Music and Drama alongside.</p>',
    '<div class="fs-aside"><b>did you know?</b> The Barbican was voted London\'s',
    'ugliest building in a poll in the early 2000s, and it is a Grade II listed',
    'structure that people now pay a great deal to live in. The estate is famous',
    'for being hard to navigate; the management painted a yellow line on the floor',
    'to guide visitors from the Tube to the centre, and it is still there.</div>',
    '<p>The name is old. A "barbican" was a fortified outpost or gatehouse of the',
    'city wall, and a stretch of the Roman and medieval London wall survives on the',
    'site, with the church of St Giles-without-Cripplegate marooned among the',
    'concrete, a medieval survivor kept deliberately at the heart of the modern',
    'estate.</p>',
    '<hr>',
    '<p>For the movement it belongs to see <a href="brutalism.geocities.ws">',
    'brutalism</a>, and for another concrete monument built for a nation and a',
    'city remaking itself, Kenzo Tange at <a href="kenzo-tange.geocities.ws">',
    'kenzo-tange</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01590 · best viewed in Netscape at 800x600 · mind the',
    'highwalk · last updated 5 May</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a buildings-webring page. « prev · random · next »</small></p>',
  ]);

// ---- Kenzo Tange: architect profile -----------------------------------------

const TANGE = P('kenzo-tange.geocities.ws', 'KENZO TANGE',
  'KENZO TANGE // the modern and the Japanese', [
    '<!--bg:arch-brutalist-->',
    '<h1>KENZO TANGE</h1>',
    '<p><small>a profile page kept by an exchange student who spent a year in',
    'Tokyo and made a point of visiting everything on this list. the Yoyogi roof',
    'is even better in the rain. — K.</small></p>',
    '<hr>',
    '<p>Kenzo Tange (1913&ndash;2005) was the architect who carried Japan out of',
    'the ruins of the war and into the front rank of world architecture, and he',
    'did it by fusing the concrete of the international modern with something',
    'deeply Japanese: the timber joint remembered in concrete, the raised floor,',
    'the great sheltering roof, the clear frame of the old temple and house.</p>',
    '<h2>Hiroshima</h2>',
    '<p>His first great work and the heaviest to carry. Tange won the competition',
    'for the Hiroshima Peace Memorial Park, on the ground of the atomic bombing,',
    'and built it through the 1950s. The Peace Memorial Museum stands raised on',
    'pilotis, a long clean concrete box lifted so that the view runs straight',
    'through beneath it, along an axis that lines up the cenotaph, the memorial',
    'flame and the skeletal ruin of the Atomic Bomb Dome across the river. A whole',
    'act of mourning and resolve laid out as an architectural line.</p>',
    '',
    '<h2>the Metabolists</h2>',
    '<p>In 1960 a group of young Japanese architects launched METABOLISM, and',
    'Tange was their elder and patron. The idea was biological: a city and its',
    'buildings should be able to GROW and change like a living organism, with',
    'permanent cores and structures onto which smaller replaceable cells could be',
    'plugged, added and removed as needs changed. Tange\'s own plan for Tokyo Bay',
    '(1960), a city extended out over the water on a great structural spine, was',
    'the movement\'s grandest statement, and Kisho Kurokawa\'s Nakagin Capsule Tower',
    'later built the plug-in cell for real.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Architecture must have something that',
    'appeals to the human heart, but even so, the basic forms, spaces and',
    'appearances must be logical.&rdquo;</p><p><small>&mdash; Kenzo Tange</small>',
    '</p></blockquote>',
    '<h2>Yoyogi, and Tokyo 1964</h2>',
    '<p>His masterpiece. For the Tokyo Olympic Games of 1964 Tange built the',
    'National Gymnasia at Yoyogi, two halls whose roofs are hung from steel cables',
    'slung between great concrete masts, a SUSPENSION structure that sweeps the',
    'roof down in a long curve and up into a spiralling peak, so the buildings',
    'seem to swirl. The larger hall roofs the swimming, the smaller the basketball.',
    'It is engineering and sculpture at once, and it reads, unmistakably, as the',
    'curve of a great tiled temple roof brought into the twentieth century.</p>',
    '<p>Tange won the Pritzker Prize in 1987, the first Japanese architect to do',
    'so, and he taught a generation, Kurokawa and Maki and Isozaki among them, who',
    'carried Japanese architecture on to the world stage.</p>',
    '<hr>',
    '<p>For another architect who swept concrete into curves for a nation building',
    'itself anew see Oscar Niemeyer at <a href="oscar-niemeyer.geocities.ws">',
    'oscar-niemeyer</a>, and for the great British concrete city visit the',
    '<a href="the-barbican.geocities.ws">the-barbican</a>.</p>',
    '<hr>',
    '<p><small>counter: 01118 · best viewed at 800x600 · a buildings webring page',
    '· last updated 18 Jun</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>ring member. « prev · random · next »</small></p>',
  ]);

export const ARCH_C = [KAHN, NIEMEYER, SMITHSONS, BRUTALISM, BARBICAN, TANGE];
