// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH H — the open city, and 3D solved.
//
// Fan pages, kept on a free host, each ABOUT a game or the people who made it
// and never in the maker's own voice. A GTA obsessive who followed DMA Design
// up from the Lemmings days; a Nintendo 64 kid who thinks Mario 64 solved a
// problem nobody else had; a sim-racing anorak logging licence tests on Gran
// Turismo; and a puzzle-head keeping a shrine to Alexey Pajitnov and the tangle
// of rights behind Tetris. The titles, years and studios are real; the passion
// and the grudges are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Grand Theft Auto / DMA Design ------------------------------------------

const GTA = P('grand-theft-auto.geocities.ws', 'GRAND THEFT AUTO',
  'GRAND THEFT AUTO // the open city (DMA Design)', [
    '<!--bg:fps-->',
    '<h1>GRAND THEFT AUTO</h1>',
    '<p><small>a page kept by someone who bought it on the strength of the studio',
    'name alone, because i had followed DMA Design since the little green men, and',
    'i was not disappointed. this is a fan page, i do not work for anyone. — Col',
    'from Dundee (by way of the internet)</small></p>',
    '<hr>',
    '<p>Grand Theft Auto came out in 1997 from DMA Design, published by BMG',
    'Interactive, and it started life under a different name entirely: Race’n’Chase.',
    'The plan was a cops-and-robbers driving game. What it turned into was',
    'something the plan did not have a word for, a whole top-down city you were',
    'simply let loose in, free to drive where you liked and misbehave how you',
    'liked, with the missions there if you wanted them and ignorable if you did',
    'not.</p>',
    '<hr>',
    '<p><b>what made it different</b></p>',
    '<p>Nearly every other game of the day drew a corridor and marched you along',
    'it. GTA drew a map and handed you the keys. The city was the thing, not the',
    'level, and the freedom to wander it was the point rather than a bit of',
    'scenery between fights. You could go and cause bother for no reason at all,',
    'and the game kept up with you. That single design decision is what everybody',
    'copied afterwards, though most of them forgot to make the city worth',
    'wandering.</p>',
    '<hr>',
    '<p><b>the fuss</b></p>',
    '<p>There was a great press panic when it came out, the papers in an uproar',
    'about the crime and the mayhem, and the publisher was accused, more or less',
    'openly, of enjoying every column inch. The outrage sold the game. Anyone who',
    'was around remembers that the shouting did the marketing for free.</p>',
    '<hr>',
    '<p><b>who these people are</b></p>',
    '<p>DMA Design were a Dundee outfit, and if you know the name it is probably',
    'from Lemmings, the tiny green-haired creatures you saved by handing out jobs.',
    'The same studio, the same restless cleverness, went on from puzzle to open',
    'city. After GTA the money and the sequels arrived and DMA became Rockstar',
    'North, but the DNA runs straight back to the bedroom-coder years in',
    'Scotland. For the earlier chapter of the same story, and the Lemmings, go to',
    '<a href="lemmings-dma.geocities.ws">lemmings-dma.geocities.ws</a>.</p>',
    '<hr>',
    '<p><b>why it still matters</b></p>',
    '<p>Because it proved a game did not need to tell you what to do to be worth',
    'your evening. Give people a world with its own rules and they will make their',
    'own trouble, their own stories, their own reasons to come back. That lesson',
    'outlived the little top-down sprites by a very long way.</p>',
    '<hr>',
    '<p><b>neighbours worth a visit</b></p>',
    '<p>Same studio, earlier life, the green men:',
    '<a href="lemmings-dma.geocities.ws">lemmings-dma.geocities.ws</a>. And if you',
    'want the other side of the 1990s, the shooter people who were teaching a',
    'different machine to run fast, id Software are logged at',
    '<a href="doom-id.geocities.ws">doom-id.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>joyriders through this page: 03127 · best viewed at 640x480 ·',
    'wanted level: still under construction, more missions to add · last updated',
    '14 Aug</small></p>',
    '<p><small>',
    '[ <a href="fps-3d-ring.geocities.ws">FPS &amp; 3D Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Super Mario 64 ---------------------------------------------------------

const MARIO64 = P('mario-64.geocities.ws', 'SUPER MARIO 64',
  'SUPER MARIO 64 // 3D solved (Nintendo 64)', [
    '<!--bg:console-->',
    '<h1>SUPER MARIO 64</h1>',
    '<p><small>kept by a kid who queued for the Nintendo 64 and has never really',
    'come down from that first afternoon in the castle courtyard. i have played a',
    'lot of games since. this is still the one. — Nao</small></p>',
    '<hr>',
    '<p>Super Mario 64 arrived in 1996 as a launch game for the Nintendo 64, and',
    'Miyamoto’s team used it to answer two hard questions at the same time: how do',
    'you make a platform game work in three dimensions, and how do you point the',
    'camera when the player can go anywhere. Both problems were open. This one',
    'game closed them, and closed them so well that most of what came after simply',
    'borrowed the answers.</p>',
    '<hr>',
    '<p><b>the stick was the whole idea</b></p>',
    '<p>The Nintendo 64 controller had a new analogue stick in the middle, and',
    'that stick is the reason the game exists in the shape it does. A digital pad',
    'gives you eight directions and one speed. The stick gave you every direction',
    'and every speed, a gentle tiptoe or a full run, and Mario answered all of it.',
    'You could feel the difference in your thumb. The movement was not a menu of',
    'commands, it was a dial, and the whole design was built around that dial.</p>',
    '<hr>',
    '<p><b>the camera nobody had cracked</b></p>',
    '<p>Moving in three dimensions is only half the trouble. The other half is',
    'seeing where you are going. The team hung the camera behind Mario and let you',
    'swing it around, and put the idea in the fiction as a little cameraman',
    'following you, which was a tidy way to explain a control the player had never',
    'held before. It was not perfect and everyone who played it has a story about',
    'wrestling the view. It was still the first time the free camera felt like a',
    'tool rather than a fight.</p>',
    '<hr>',
    '<p><b>the castle as a hub</b></p>',
    '<p>Instead of a line of levels there was a castle you explored, with paintings',
    'you jumped into, each a world with its own stars to collect. You went back to',
    'worlds you already knew and found new reasons to be there. The structure said,',
    'quietly, that a game could be a place you returned to rather than a track you',
    'finished once.</p>',
    '<hr>',
    '<p><b>where it comes from and where it goes</b></p>',
    '<p>Miyamoto is the same designer who gave Nintendo Donkey Kong and the flat',
    'Mario and Zelda, and there is a page for the whole run of that at',
    '<a href="donkey-kong.geocities.ws">donkey-kong.geocities.ws</a>. If you want',
    'to see the other big thing a 1997 console pulled off, a sim that took 3D',
    'somewhere completely different, the driving people are at',
    '<a href="gran-turismo.geocities.ws">gran-turismo.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>stars collected by visitors: 02640 · best viewed at 640x480 ·',
    'under construction, still writing up the secret slide · last updated 9 Aug',
    '</small></p>',
    '<p><small>',
    '[ <a href="console-jp-ring.geocities.ws">Japanese Console Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Gran Turismo / Kazunori Yamauchi ---------------------------------------

const GRANTURISMO = P('gran-turismo.geocities.ws', 'GRAN TURISMO',
  'GRAN TURISMO // the real driving simulator (Yamauchi)', [
    '<!--bg:console-->',
    '<h1>GRAN TURISMO</h1>',
    '<p><small>kept by someone who has passed every licence test more times than is',
    'reasonable and still keeps a notebook of lap times. i am not a professional',
    'anything. i just like the cars to behave. — R.T.</small></p>',
    '<hr>',
    '<p>Gran Turismo came out in 1997 on the PlayStation, made by Polyphony Digital',
    'under Kazunori Yamauchi, and it called itself the real driving simulator on',
    'the box and then went and earned the phrase. Where other racers gave you a',
    'handful of made-up cars, this one gave you hundreds of real ones, licensed',
    'from real manufacturers, each meant to weigh and grip and slide like the',
    'genuine article.</p>',
    '<hr>',
    '<p><b>the licence tests</b></p>',
    '<p>You could not just pick the fastest car and go. First you sat the licence',
    'tests, a set of small precise challenges that taught you to brake at the right',
    'marker, to take a corner on the proper line, to lift and settle the car before',
    'you turned in. People grumbled and then they learned to drive. That was the',
    'trick of it. The game refused to let you be sloppy and made the refusal',
    'satisfying.</p>',
    '<hr>',
    '<p><b>the anorak’s game</b></p>',
    '<p>Underneath the racing was a car sim for people who love cars as machines.',
    'You tuned, you tinkered, you earned money and bought a better gearbox and felt',
    'the difference on the next lap. It rewarded the obsessive who wanted to know',
    'why the back end stepped out and how to stop it. Yamauchi built the game he',
    'himself wanted to play, and it turned out a great many people wanted the same',
    'careful, unhurried thing.</p>',
    '<hr>',
    '<p><b>why it mattered</b></p>',
    '<p>It showed that simulation could be popular, that ordinary players would',
    'happily do the homework if the reward was a car that felt real under them. The',
    'humble console was suddenly running the kind of physics the hobbyists had been',
    'chasing on home computers for years.</p>',
    '<hr>',
    '<p><b>neighbours worth a visit</b></p>',
    '<p>The physics tradition it stands on runs back through the man who made',
    'simulation a craft on 8-bit machines, Geoff Crammond, logged at',
    '<a href="stunt-car-crammond.geocities.ws">stunt-car-crammond.geocities.ws</a>.',
    'And for the other big 3D leap the PlayStation carried, the tomb-climbing',
    'Core Design lot are at',
    '<a href="tomb-raider-core.geocities.ws">tomb-raider-core.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>laps logged by visitors: 01988 · best viewed at 640x480 · under',
    'construction, tuning notes still going up · fastest visitor lap in the jar,',
    'beat it if you can · last updated 11 Aug</small></p>',
    '<p><small>',
    '[ <a href="console-jp-ring.geocities.ws">Japanese Console Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Tetris / Alexey Pajitnov -----------------------------------------------

const TETRIS = P('tetris-pajitnov.geocities.ws', 'TETRIS',
  'TETRIS // the falling blocks (Pajitnov)', [
    '<!--bg:arcade-->',
    '<h1>TETRIS</h1>',
    '<p><small>a shrine to Alexey Pajitnov, kept by someone who cannot walk past a',
    'stacked shelf without wanting to rotate a piece into the gap. i owe this man',
    'a great many lost evenings. — Ira</small></p>',
    '<hr>',
    '<p>Alexey Pajitnov made Tetris in 1984 while working at the Soviet Academy of',
    'Sciences, on an Elektronika 60, a machine so plain it drew the pieces out of',
    'bracket characters. The idea was simple to the point of perfection: shapes',
    'made of four squares, the tetrominoes, fall from the top, and you slot and',
    'turn them to build full rows that then vanish. You never win. You only last.</p>',
    '<hr>',
    '<p><b>why it grips</b></p>',
    '<p>There is no story and there is nothing to collect, and yet almost nobody',
    'can put it down. The pieces keep coming a touch faster than is comfortable,',
    'and the tidy part of the brain that wants the row complete will not let you',
    'stop. Pajitnov found a shape of play that fits the human head so snugly that',
    'people report seeing the blocks fall when they close their eyes. Very few',
    'games reach that deep with so little.</p>',
    '<hr>',
    '<p><b>the rights fight</b></p>',
    '<p>Because it was born inside the Soviet Union, the question of who owned it',
    'became a tangle that ran for years, across the USSR and the companies chasing',
    'the licence, with the state involved and the paperwork a maze. The upshot,',
    'and this is the part that stings, is that Pajitnov saw very little of the money',
    'his game made for a long time. The credit was always his. The reward took its',
    'time.</p>',
    '<hr>',
    '<p><b>the little grey box that took it worldwide</b></p>',
    '<p>What carried Tetris to every corner of the world was the Game Boy in 1989,',
    'which shipped with the game in the box. Millions of people met Tetris on that',
    'small green screen, on trains and in playgrounds, and it turned out to be the',
    'perfect fit: a game you could pick up for one minute or one hour, on a machine',
    'built to go in a pocket.</p>',
    '<hr>',
    '<p><b>why it still matters</b></p>',
    '<p>Because it is the proof that a game needs no spectacle, no violence, no',
    'story, only a rule clean enough to feel inevitable. Strip a game back to',
    'almost nothing and, if the nothing is the right nothing, it can outlast every',
    'machine it was ever written for.</p>',
    '<hr>',
    '<p><b>neighbours worth a visit</b></p>',
    '<p>For the man who made a pocket machine tough and cheap enough to carry a',
    'game like this everywhere, Gunpei Yokoi and the Game Boy are at',
    '<a href="metroid-yokoi.geocities.ws">metroid-yokoi.geocities.ws</a>. And for',
    'the other end of the arcade tradition, the aliens marching down in rows, see',
    '<a href="space-invaders.geocities.ws">space-invaders.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>lines cleared by visitors: 04096 · best viewed at 640x480 · under',
    'construction, still adding the scoring tables · high score in the token jar,',
    'nobody has topped it since May · last updated 2 Aug</small></p>',
    '<p><small>',
    '[ <a href="arcade-coinop-ring.geocities.ws">Arcade Coin-Op Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

export const GAMES_H = [GTA, MARIO64, GRANTURISMO, TETRIS];
