// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// The recent cluster: datacentres, chips, weights, and the generations.
//
// A different register from the rest of the cache, because these are about now
// rather than then, and the cache is a crawl that never stopped so it has them.
//
// THE RULE FOR THIS FILE. These pages must ARGUE, and they must not all agree.
// The outside site at www/ is unrelieved boosterism and would be worth nothing
// if the archive answered it with unrelieved refusal; that would be two
// pamphlets. So: the datacentre page is angry and checks its own figures; the
// chips page admires the engineering; the open-weights page thinks the word
// open is being used dishonestly by people it otherwise agrees with; and the
// four generation pages contradict each other on purpose and say so.
//
// Where a number is contested the page says it is contested rather than picking
// the one that suits it. That is the only way any of this is worth reading.

export const NOW_SITES = [
  {
    domain: 'datacentre.geocities.ws',
    name: 'THE SHED',
    title: 'What is actually in the shed',
    body: [
      '<!--bg:grey-->',
      '<h1>What is actually in the shed</h1>',
      '<p><small>Written by somebody who has worked in three of them and is tired',
      'of both sides of this argument.</small></p>',
      '<hr>',
      '<p>A hall. Rows of racks, cold aisle facing cold aisle, hot air out the',
      'back. Overhead trays for the fibre. Under the floor or overhead, the power.',
      'Doors that need two people. It is loud in a way photographs do not convey',
      'and you cannot hold a conversation on the floor.</p>',
      '<h2>The three numbers</h2>',
      '<pre class="jb-list">',
      '  power     what it draws, continuously, day and night.',
      '            a large site is a small town',
      '  water     evaporative cooling, where used. this is the',
      '            contested one and I will come back to it',
      '  land      big, flat, near a substation, near fibre,',
      '            and cheap. that is the whole siting decision',
      '</pre>',
      '<h2>On the water, since everybody argues about it</h2>',
      '<p>The claim you will be given by the industry is that most of the water is',
      'returned. The claim you will be given by the other side is that a site',
      'consumes millions of litres a day.</p>',
      '<p>Both are true and they are not answers to the same question.',
      '<b>Withdrawal</b> is how much you take. <b>Consumption</b> is how much does',
      'not come back, because evaporative cooling works precisely by evaporating',
      'it. Air-cooled sites consume almost none and use much more electricity',
      'instead. So the trade is water against power and a site chooses one.</p>',
      '<p>Anybody quoting a single figure without saying which of those it is, in',
      'either direction, is either confused or managing you.</p>',
      '<h2>What actually annoys me</h2>',
      '<p>Not the buildings. Buildings are how computing works and always has been,',
      'and a mainframe room in 1972 was a hall with a cooling plant too. The scale',
      'is different and the kind is not.</p>',
      '<p>What annoys me is that the siting decisions are made on land price and',
      'grid capacity, and then explained afterwards in the language of the future.',
      'A hall goes where the substation is. It does not go there because of a',
      'vision.</p>',
      '<p>And the jobs. A hall this size runs on a handful of people per shift and',
      'that is the design working, not a scandal, but it should not be sold to a',
      'council as employment. It is not employment. It is rates and a grid',
      'connection.</p>',
      '<h2>The bit both sides skip</h2>',
      '<p>The grid connection queue. In much of the country you cannot get one for',
      'years, and that constraint decides more about where any of this happens than',
      'any policy anybody has announced.</p>',
      '<hr>',
      '<p><small>The other view, at length and with emoji:',
      '<a href="nvidia.geocities.ws">what is in the racks</a>. And somebody who',
      'thinks the whole framing is the problem:',
      '<a href="antiaipolitics.geocities.ws">here</a>.</small></p>',
    ],
  },
  {
    domain: 'nvidia.geocities.ws',
    name: 'THE CHIPS',
    title: 'What is in the racks — a hardware page',
    body: [
      '<!--bg:black-->',
      '<h1>What is in the racks</h1>',
      '<p><small>An admiring page about engineering, by somebody who thinks the',
      'business around it is mostly nonsense.</small></p>',
      '<hr>',
      '<p>I want to separate two things that get argued about as one. The',
      'engineering in these parts is genuinely superb. What is being claimed about',
      'what they will do is a separate matter and mostly marketing.</p>',
      '<h2>Why a graphics chip</h2>',
      '<p>Historical accident that turned into the whole industry. Drawing a screen',
      'means doing the same small arithmetic on millions of independent things at',
      'once. So graphics chips were built wide rather than fast: thousands of',
      'simple units in parallel instead of a few clever ones.</p>',
      '<p>Then it turned out that training a network is also the same small',
      'arithmetic on millions of independent things, and the hardware was already',
      'there, built for teenagers wanting better shadows.</p>',
      '<h2>The bottleneck nobody expects</h2>',
      '<p>Not the arithmetic. <b>Memory bandwidth</b>. The units can multiply far',
      'faster than numbers can be fetched for them to multiply, so most of the',
      'design effort goes into getting data close enough, fast enough, and most of',
      'the cost is in stacked memory sitting next to the die.</p>',
      '<p>Which is why the interesting number on a part is not how many operations',
      'it claims but how many bytes a second it can actually feed itself.</p>',
      '<h2>The interconnect</h2>',
      '<p>And the thing that matters most and gets discussed least. One chip is not',
      'the product. A rack of them behaving as one machine is the product, and that',
      'requires them to talk to each other faster than they talk to anything else.</p>',
      '<p>That is where the real moat is. Anybody can be sold a fast chip. Very few',
      'people can be sold a working cabinet of them.</p>',
      '<h2>Where I get off</h2>',
      '<p>The part I do not accept is the extrapolation. That performance has gone',
      'up steeply is a fact. That it will continue at that rate is a hope, and it',
      'has been printed as a projection, and I have watched this industry do that',
      'before with clock speeds until physics declined.</p>',
      '<p>The heat is the honest constraint. Everything else is negotiable and heat',
      'is not.</p>',
      '<hr>',
      '<p><small>Where they live: <a href="datacentre.geocities.ws">the shed</a>.',
      'What runs on them, and who is allowed to look:',
      '<a href="openweights.geocities.ws">the weights</a>.</small></p>',
      '<p><small>Who else is publishing: <a href="chineseai.geocities.ws">the other labs</a>.</small></p>',
    ],
  },
  {
    domain: 'openweights.geocities.ws',
    name: 'OPEN WEIGHTS',
    title: 'Open weights — a word being used carelessly',
    body: [
      '<!--bg:navy-->',
      '<h1>Open weights</h1>',
      '<p><small>By somebody who has spent twenty-five years on free software and',
      'is watching a word get worn out.</small></p>',
      '<hr>',
      '<p>I am not against any of these releases. Several of them are the most',
      'useful thing anybody has done in this field. My complaint is narrow and it',
      'is about a word.</p>',
      '<h2>What is actually released</h2>',
      '<p>The weights. A very large table of numbers, and enough code to run it.',
      'You may download it, run it locally, adapt it, and in many cases ship what',
      'you build.</p>',
      '<p>That is a great deal and it is worth having. It is not open source.</p>',
      '<h2>The test</h2>',
      '<p>The free software definition turns on one thing: the <b>preferred form',
      'for making modifications</b>. Not the artefact. The thing you would actually',
      'want if you meant to change it properly.</p>',
      '<p>For a program that is the source. For one of these it would be the',
      'training data, the data cleaning, the training code, the hyperparameters and',
      'the schedule. With those you could rebuild it, or build it differently, or',
      'find out why it does the thing it does.</p>',
      '<p>Weights without those are a binary. A very large, very useful binary that',
      'you may run and modify at the edges, and nobody outside the organisation can',
      'reproduce or audit.</p>',
      '<h2>The label people reach for</h2>',
      '<p>Somebody will say freeware, and that is roughly the right shape and',
      'roughly the right decade: run it, no charge, no source. We had a word and it',
      'was not a compliment and it was not an insult either.</p>',
      '<p>The licences are often not free licences either. Field-of-use',
      'restrictions, user-count thresholds, acceptable-use terms. Those may be',
      'perfectly reasonable and they are exactly the clauses that made a licence',
      'non-free when the argument was about software.</p>',
      '<h2>Why I bother</h2>',
      '<p>Because the word was won. It took twenty years to make open source mean',
      'something specific enough that you could check a claim against it, and that',
      'precision is the entire value of the term.</p>',
      '<p>If it comes to mean "you may download this", it means nothing, and the',
      'next time something genuinely open arrives there will be no way to say so.</p>',
      '<h2>What I would call it</h2>',
      '<p>Open weights. Which is accurate, which is what everybody says anyway, and',
      'which nobody should feel embarrassed about, because it is a real thing to',
      'have released.</p>',
      '<hr>',
      '<p><small>The definition being used: <a href="gnu.org">gnu.org</a>. A label',
      'that hit exactly this problem with music and admitted it:',
      '<a href="locarecords.com/licence">what is the source of a song</a>.</small></p>',
    ],
  },
  {
    domain: 'chineseai.geocities.ws',
    name: 'THE OTHER LABS',
    title: 'The labs nobody in Britain reads',
    body: [
      '<!--bg:parch-->',
      '<h1>The labs nobody here reads</h1>',
      '<p><small>Kept by somebody who reads the papers and not the coverage.</small></p>',
      '<hr>',
      '<p>The English-language discussion talks about three or four organisations.',
      'The published literature does not look like that at all, and if you follow',
      'the citations rather than the press you end up somewhere else quite',
      'quickly.</p>',
      '<h2>What I actually observe</h2>',
      '<p>A large volume of work out of Chinese institutions and companies,',
      'published in English, in the same venues, and increasingly the thing being',
      'cited rather than the thing citing. Several of the most-used open weight',
      'releases come from there, under permissive terms, and are what a great many',
      'people outside those countries are actually running.</p>',
      '<p>That is a plain observation about a bibliography and it is not a',
      'political position.</p>',
      '<h2>Two mistakes I keep seeing</h2>',
      '<p><b>Treating it as a copy.</b> It was, in parts, for a while, and it is',
      'not now, and continuing to say so is a way of not reading things.</p>',
      '<p><b>Treating it as a bloc.</b> Enormously different organisations with',
      'different strategies who compete with each other, described in the coverage',
      'here as a single actor with a single intention. Nobody would accept that',
      'description of the American labs.</p>',
      '<h2>What I cannot assess</h2>',
      '<p>And I will not pretend otherwise. Claims about training cost. Claims about',
      'what hardware was used and how it was obtained. Benchmark results in general,',
      'from anybody, in any country, because the incentives on benchmarks are bad',
      'everywhere and the numbers are marketing before they are measurement.</p>',
      '<p>What I can assess is code I can run and papers with enough detail to',
      'follow. That is a smaller set than the discussion assumes and it is the only',
      'set worth having an opinion about.</p>',
      '<h2>The bit that will age badly</h2>',
      '<p>Probably this page. I am writing down what the citations look like in one',
      'month of one year, and the interesting thing in five years will be how wrong',
      'the confident people were, in both directions.</p>',
      '<hr>',
      '<p><small>On what "open" is doing in that sentence:',
      '<a href="openweights.geocities.ws">the weights page</a>.</small></p>',
    ],
  },
  {
    domain: 'antiaipolitics.geocities.ws',
    name: 'AGAINST',
    title: 'Against — but be careful what you are against',
    body: [
      '<!--bg:loca-->',
      '<h1>Against, carefully</h1>',
      '<p><small>Written by somebody who organises, and who is losing patience with',
      'their own side.</small></p>',
      '<hr>',
      '<p>I am against a great deal of this and I want to be against the right',
      'things, because a campaign aimed at the wrong target loses and takes the',
      'good arguments down with it.</p>',
      '<h2>The strong arguments</h2>',
      '<pre class="jb-list">',
      '  the work was taken   people’s writing, pictures and voices',
      '                       used without asking, without payment,',
      '                       and without a way to decline',
      '',
      '  the money            enormous capital deciding what gets',
      '                       built, and the returns going to the',
      '                       people who already had the capital',
      '',
      '  the decisions        systems placed between a person and a',
      '                       decision about them, with no route to',
      '                       a human being who can be held to it',
      '',
      '  the grid             siting, water, and who pays for the',
      '                       connection. see the shed page',
      '',
      '  the work again       not "jobs will go" in general, but',
      '                       specific work, deskilled and cheapened,',
      '                       in specific places, now',
      '</pre>',
      '<h2>The weak arguments, which I would like us to drop</h2>',
      '<p><b>That it is useless.</b> It is not, plainly, and every person who has',
      'said so in a meeting I was in has been contradicted by somebody in the room',
      'within a fortnight. Arguing that a thing does not work, against people using',
      'it daily, loses the room and deservedly.</p>',
      '<p><b>That it is only a statistical trick.</b> True and does not follow.',
      'Whether the mechanism is impressive has nothing to do with whether the',
      'deployment is harmful, and we keep arguing the first because it is more',
      'fun.</p>',
      '<p><b>Machine-breaking as identity.</b> The Luddites were not against',
      'machines. They were skilled workers with a specific complaint about wages,',
      'conditions and who owned the frames, and they said so at the time, and being',
      'called anti-technology is the insult that was invented to avoid answering',
      'them. If we take the name up as a costume we do the insult’s work.</p>',
      '<h2>The thing I am actually frightened of</h2>',
      '<p>Not a takeover. The record. Systems that produce a confident account of',
      'what happened, faster than anybody can check, in institutions that will',
      'accept the account because checking is expensive.</p>',
      '<p>Nobody has to intend anything for that to go badly. It goes badly by',
      'being cheaper.</p>',
      '<hr>',
      '<p><small>Which somebody has documented from the inside:',
      '<a href="itwasnotlikethat.geocities.ws">a man with a filing cabinet</a>. And',
      'the theory: <a href="whatishistory.geocities.ws">whatishistory</a>.</small></p>',
    ],
  },

  // ---- the generations, disagreeing on purpose -----------------------------
  {
    domain: 'boomers.geocities.ws',
    name: 'A REPLY',
    title: 'A reply, from somebody born in 1951',
    body: [
      '<!--bg:lace-->',
      '<h1>A reply</h1>',
      '<p><small>I am seventy-four. I have been told what I think by a great many',
      'people who were not born.</small></p>',
      '<hr>',
      '<p>I am supposed to have had it easy. Let me put down what I actually had,',
      'and then what I actually took, because both belong on the page.</p>',
      '<h2>What I had</h2>',
      '<p>A grant. Not a loan. Full fees and a maintenance grant, and I left with',
      'nothing owing, and that was not a privilege I arranged, it was policy, and',
      'it was withdrawn by people my own age.</p>',
      '<p>A house at three and a half times one salary. Interest rates that went to',
      'fifteen per cent and nearly took it off us, so it was not free, but the',
      'number I was borrowing was a number a person could repay.</p>',
      '<p>A job you could leave on a Friday and replace on a Monday.</p>',
      '<h2>What I did not have</h2>',
      '<p>Central heating until 1979. A phone in the house until I was twenty-two.',
      'Any expectation whatever that work would be interesting. And a father who',
      'had been in the war and did not speak, which was every house on our street',
      'and is left out of the accounting entirely.</p>',
      '<h2>The part where I agree with you</h2>',
      '<p>We voted for it. Not all of us and not always knowingly, but the ladder',
      'was pulled up during my working life, by governments I could have voted',
      'against more often than I did, and the beneficiaries were people in my',
      'position and I was one of them.</p>',
      '<p>I did not personally take anything from anybody. I also did not stop it.',
      'Those are different and only one of them is a defence.</p>',
      '<h2>The part where I do not</h2>',
      '<p>Sorting the whole country into four birth cohorts and assigning blame is',
      'a way of not talking about who owns things. There are people my age in this',
      'town who have nothing at all, and there are people your age who will inherit',
      'a great deal, and a category that puts a retired cleaner and a landlord on',
      'the same side is not analysis.</p>',
      '<p>Ask who owns it. That question works in every decade.</p>',
      '<hr>',
      '<p><small>The pages this is a reply to:',
      '<a href="genx.geocities.ws">X</a>, <a href="genz.geocities.ws">Z</a>. And',
      '<a href="genalpha.geocities.ws">the one about the children</a>, which I',
      'thought was the best of them.</small></p>',
    ],
  },
  {
    domain: 'genx.geocities.ws',
    name: 'GENERATION X',
    title: 'Generation X — the ones in the middle',
    body: [
      '<!--bg:grey-->',
      '<h1>The ones in the middle</h1>',
      '<p><small>Born between about 1965 and 1980. Nobody has ever wanted our',
      'opinion and we have made a personality out of it.</small></p>',
      '<hr>',
      '<p>The last people to grow up entirely without and to spend an adult life',
      'entirely within. That is the whole of what is distinctive about us and',
      'everything else is affectation.</p>',
      '<h2>The hinge</h2>',
      '<p>Childhood: no computer, or one computer, in the corner, that you typed',
      'programs into off a magazine. A phone in the hall that the whole street',
      'could hear. Four channels. Arranging to meet somebody at a time and place',
      'and then simply being there, because there was no way to change it.</p>',
      '<p>Adulthood: all of this. Every bit of it, arriving in our twenties and',
      'thirties, when we were old enough to notice it arriving and young enough to',
      'take it up.</p>',
      '<p>So we remember the before and are fluent in the after, which sounds like a',
      'boast and is mostly just an accident of the year.</p>',
      '<h2>What we are wrong about</h2>',
      '<p>We think the fluency makes us clear-eyed. It does not. We are as taken in',
      'as anybody, and our particular weakness is assuming that because we saw the',
      'last transition we understand this one.</p>',
      '<p>And the nostalgia is getting heavy. There is a version of my cohort that',
      'has turned having owned a particular computer into a personality, and I have',
      'watched myself do it, on this page, in the paragraph above.</p>',
      '<h2>What I would say for us</h2>',
      '<p>We are unimpressed by default and that is occasionally useful. We have',
      'seen a thing announced as inevitable and then not happen, several times,',
      'which is a genuinely rare experience and it does not make you clever, it',
      'just makes you slower to stand up.</p>',
      '<hr>',
      '<p><small><a href="boomers.geocities.ws">Before</a>.',
      '<a href="genz.geocities.ws">After</a>. Both of them think we are',
      'unhelpful.</small></p>',
    ],
  },
  {
    domain: 'genz.geocities.ws',
    name: 'GEN Z',
    title: 'We are not digital natives and we would like that dropped',
    body: [
      '<!--bg:black-->',
      '<h1>Not digital natives</h1>',
      '<p><small>Written because I have been told what I am by people selling',
      'training courses about me.</small></p>',
      '<hr>',
      '<p>The phrase means: born after it, therefore understands it. It is wrong in',
      'a way that has done actual harm and I would like it retired.</p>',
      '<h2>What we actually got</h2>',
      '<p>Not computers. <b>Appliances.</b> Sealed, single purpose, no filesystem',
      'to speak of, nothing to take apart. I can use fifteen applications',
      'fluently and I had never seen a directory tree until university, and I was',
      'not unusual, and my lecturers found it baffling.</p>',
      '<p>The generation before had a machine that did nothing until they made it',
      'do something. We had a machine that did everything and could not be opened.',
      'Fluency with the surface got mistaken for understanding underneath, mostly',
      'by people who wanted it to be true.</p>',
      '<h2>What that cost</h2>',
      '<p>Nobody taught us, because we were assumed to know. Whole years of school',
      'computing replaced with using the software, on the grounds that we were',
      'natives and needed no instruction, and I have had to learn as an adult things',
      'my parents were taught at fourteen.</p>',
      '<h2>What we do have</h2>',
      '<p>A very good nose for being sold something, because we have been sold',
      'something continuously since we were eight and can smell it through a wall.',
      'And no memory whatever of a version of any of this that was not owned by',
      'five companies, which is a real difference: the older pages here mourn',
      'something. We cannot mourn it. We have only read about it.</p>',
      '<h2>On the AI argument</h2>',
      '<p>I use it. Most people I know use it. And I notice the two groups shouting',
      'at each other are mostly not the people whose first job is being priced by',
      'it, and I would like somebody to ask us before the position is announced on',
      'our behalf, in either direction.</p>',
      '<hr>',
      '<p><small><a href="genx.geocities.ws">The ones who keep telling us about',
      'their first computer.</a> <a href="boomers.geocities.ws">The reply from',
      'further back</a>, which I did not expect to like.</small></p>',
    ],
  },
  {
    domain: 'genalpha.geocities.ws',
    name: 'THE CHILDREN',
    title: 'A page about the children, by a primary teacher',
    body: [
      '<!--bg:lace-->',
      '<h1>The children</h1>',
      '<p><small>Year 5. Twenty-nine of them. Thirty-one years in the job and I',
      'would like to record what is different, carefully.</small></p>',
      '<hr>',
      '<p>I am suspicious of pages like this, because every generation of teachers',
      'has said the children are different and most of the time they were describing',
      'being older. So I have tried to write only what I can point at.</p>',
      '<h2>What is genuinely different</h2>',
      '<p><b>They have never known a machine that could be wrong.</b> Not a machine',
      'that malfunctions, which they understand, but one that answers confidently',
      'and is simply mistaken. And so a wrong answer in a confident voice does not',
      'set anything off in them, and it sets something off in me, and I have had to',
      'work out that my alarm is learned and theirs is not absent by choice.</p>',
      '<p><b>They will ask a machine before they ask each other.</b> Not before',
      'they ask me. Before they ask the child at the next table, who often knows.',
      'That is new in about four years and I do not like it, and I cannot yet tell',
      'you whether it matters.</p>',
      '<p><b>Handwriting stamina is down and always was going down.</b> Honest',
      'point: I have said this every decade and been partly wrong every time.</p>',
      '<h2>What is not different at all</h2>',
      '<p>Everything else. They fall out and make up on the same schedule. They are',
      'kind in the same unpredictable ways. They want to be read to, all of them,',
      'including the ones who would deny it, and the room goes quiet for a book in',
      'exactly the way it did in 1995.</p>',
      '<p>And they build things. Give them a box of parts and no instructions and',
      'the same thing happens that has always happened, which is the single most',
      'reassuring fact I have.</p>',
      '<h2>What I would ask for</h2>',
      '<p>That somebody teaches them how the thing works, rather than how to use',
      'it. We made that mistake with the last cohort',
      '(<a href="genz.geocities.ws">they have written about it</a>) and we are',
      'making it faster now.</p>',
      '<p>A child who has taken something apart is not frightened of it and is not',
      'impressed by it either, and both halves of that are the point.</p>',
      '<hr>',
      '<p><small>Also mine: <a href="logo.geocities.ws">the turtle</a>. There was a',
      'floor one with a dome and it was the best thing in the school.</small></p>',
    ],
  },
];
