// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — the New Wave. The 1960s break with the golden age, told by the
// fanzine writers and paperback collectors who loved it: a shrine to Le Guin,
// a profile of Dick and his paranoia, a close reading of Ellison and the
// Dangerous Visions anthology, a Moorcock/New Worlds page, a Solaris reading
// guide for Lem, and a movement primer. Authors, titles and dates are real;
// the enthusiasm and the grudges belong to the fans.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Le Guin: the showpiece shrine ------------------------------------------

const LEGUIN = P('ursula-k-le-guin.geocities.ws', 'LE GUIN',
  'THE LATHE OF LE GUIN // a shrine // new wave', [
    '<!--bg:sff-newwave-->',
    '<h1>THE LATHE OF LE GUIN</h1>',
    '<p><small>a shrine to Ursula K. Le Guin (b. 1929), kept by a reader who thinks',
    'she is simply one of the great writers of the century and will not be talked',
    'down to "great for science fiction". started this page after re-reading The',
    'Dispossessed on a long train. — the ansible operator</small></p>',
    '<hr>',
    '<p class="fs-epi">"The only thing that makes life possible is permanent,',
    'intolerable uncertainty: not knowing what comes next."<br>',
    '— Ursula K. Le Guin, The Left Hand of Darkness, 1969</p>',
    '<p>She was the daughter of the anthropologist Alfred Kroeber and the writer',
    'Theodora Kroeber, and you can feel the anthropology in every book. She does',
    'not visit a strange world to have an adventure in it. She goes to find out',
    'how a different people organise kinship, property, gender and government, and',
    'then she lets a human being walk through it and be changed. That is the whole',
    'method, and nobody in the genre did it better.</p>',
    '<h2>The Left Hand of Darkness (1969)</h2>',
    '<p>The novel that made her name and still the one to press on a new reader.',
    'An envoy from a federation of worlds, Genly Ai, comes to the frozen planet',
    'Gethen, called Winter, to invite it to join. The Gethenians are ambisexual:',
    'for most of the month they are neuter, and once a month they enter kemmer and',
    'become male or female, with no say in which, so any person may be mother to',
    'one child and father to another. Le Guin uses the idea to ask what is left of',
    '"man" and "woman" when the biology stops being fixed, and what a society',
    'without permanent gender would do with war, with property, with love. The',
    'friendship between Ai and the exiled politician Estraven, crossing the ice on',
    'foot, is one of the great things in the genre. It won the Hugo and the Nebula',
    'both.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/le-guin-01.jpg" alt=""><span class="indie-cap">Ursula K. Le Guin (photo: Marian Wood Kolisch, CC BY-SA 2.0)</span>',
    '<h2>The Dispossessed (1974)</h2>',
    '<p>Her anarchist utopia, and she was honest enough to subtitle it "An',
    'Ambiguous Utopia". The physicist Shevek lives on Anarres, a poor moon settled',
    'generations ago by followers of the anarchist Odo, a world with no state, no',
    'money, no property and no law, only shared work and the pressure of one',
    'another. He travels to the rich, propertied twin planet Urras to finish his',
    'theory of time, and the book cuts between the two so you cannot settle into',
    'either. Anarres is free and it is also grey, sometimes coercive, worn down by',
    'scarcity and by the quiet tyranny of what the neighbours think. Le Guin will',
    'not sell you a paradise. She shows you the cost of the good place and asks if',
    'you would still pay it. It won the Hugo and the Nebula too.</p>',
    '<p class="fs-pull">"You cannot buy the revolution. You cannot make the',
    'revolution. You can only be the revolution."</p>',
    '<h2>The Hainish cycle</h2>',
    '<p>Left Hand and The Dispossessed both belong to the Hainish books, a loose',
    'future history rather than a series with a plot. Long ago the people of the',
    'planet Hain seeded humanity across many worlds, so every human society is a',
    'cousin, evolved apart and grown strange. There is no galactic empire and no',
    'war fleet. There is the Ekumen, a slow league of worlds held together by trade',
    'and talk and by the ansible, her invention, a device for instant',
    'communication across any distance. The word has been borrowed by half the',
    'genre since. Read the books in any order; the future history is a frame, not a',
    'staircase.</p>',
    '<div class="fs-aside"><b>Did you know?</b> The ansible is Le Guin’s',
    'coinage, from Left Hand of Darkness. Writers from Orson Scott Card onward',
    'borrowed the word for faster-than-light communication. She invented a piece of',
    'furniture the whole field now lives in.</div>',
    '<h2>Earthsea, and the essays</h2>',
    '<p>She also wrote one of the finest fantasy sequences going, the Earthsea',
    'books, but those live on their own page in the fantasy wing of the ring, so I',
    'will only say: go and read A Wizard of Earthsea and meet Ged. And do not skip',
    'the essays. The Language of the Night collects her criticism, and the essay',
    '"Why Are Americans Afraid of Dragons?" is a defence of the imagination that',
    'every reader of this ring should have by heart. She thought about what she was',
    'doing more clearly than almost anyone, and she refused the easy answer every',
    'time.</p>',
    '<pre>',
    '  LE GUIN :: A BIBLIOGRAPHY FOR THE SHELF',
    '  ------------------------------------------------------',
    '  Hainish / science fiction',
    '    Rocannon’s World .................. 1966',
    '    Planet of Exile ................... 1966',
    '    City of Illusions ................. 1967',
    '    The Left Hand of Darkness ......... 1969   [Hugo + Nebula]',
    '    The Word for World Is Forest ...... 1972/76 [Hugo]',
    '    The Dispossessed .................. 1974   [Hugo + Nebula]',
    '    The Telling ....................... 2000',
    '  Fantasy',
    '    A Wizard of Earthsea .............. 1968',
    '    The Tombs of Atuan ................ 1971',
    '    The Farthest Shore ................ 1972',
    '    Tehanu ............................ 1990',
    '  Essays',
    '    The Language of the Night ......... 1979',
    '    Dancing at the Edge of the World .. 1989',
    '',
    '  ESSENTIAL FIRST FOUR, if you own nothing',
    '    1. The Left Hand of Darkness',
    '    2. The Dispossessed',
    '    3. A Wizard of Earthsea',
    '    4. The Language of the Night (for how she thinks)',
    '</pre>',
    '<blockquote class="fs-quote"><p>"We read books to find out who we are. What',
    'other people, real or imaginary, do and think and feel is an essential guide',
    'to our understanding of what we ourselves are and may become."<br>',
    '— Ursula K. Le Guin, The Language of the Night</p></blockquote>',
    '',
    '<hr>',
    '<p>Where to go next in the ring. For the other pole of the New Wave, the',
    'paranoid Californian genius, see <a href="philip-k-dick.geocities.ws">philip-k-dick</a>,',
    'who asked what is real while Le Guin asked what is just. And for the movement',
    'she is usually filed under, though she always sat a little apart from it, see',
    'the primer at <a href="the-new-wave-sf.geocities.ws">the-new-wave-sf</a>. Her',
    'Earthsea has its own shrine over in the fantasy wing; ask the ring for it.</p>',
    '<hr>',
    '<p><small>counter: 03571 · best viewed in Netscape at 800x600 · this page is',
    'under permanent construction because she keeps being right · last updated 22 Nov',
    '</small></p>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
  ]);

// ---- Philip K. Dick: author profile -----------------------------------------

const DICK = P('philip-k-dick.geocities.ws', 'PKD',
  'WHAT IS REAL? // a PKD page // new wave', [
    '<!--bg:sff-newwave-->',
    '<h1>WHAT IS REAL? &nbsp;a Philip K. Dick page</h1>',
    '<p><small>maintained by a paperback collector with two shelves of yellowing',
    'Dick and no room for more. he wrote too much, most of it in a hurry, and some',
    'of it will take the top of your head off. — the collector</small></p>',
    '<hr>',
    '<p>Philip K. Dick (1928-1982) wrote more than forty novels and a hundred and',
    'twenty short stories, mostly fast, mostly for cheap money, on amphetamines and',
    'under deadline, and out of that ragged output came a body of work that asks',
    'two questions over and over. What is real? And what is human? He kept pulling',
    'the floor out from under his own characters, and under you.</p>',
    '<p class="fs-epi">"Reality is that which, when you stop believing in it, does',
    'not go away."<br>— Philip K. Dick, 1978</p>',
    '<h2>The big ones</h2>',
    '<p><i>Do Androids Dream of Electric Sheep?</i> (1968) is the one most people',
    'reach first, though many reach it backwards through the film Blade Runner. A',
    'bounty hunter retires escaped androids in a poisoned near-future, and the test',
    'that tells human from android measures empathy, which is the only thing left',
    'that is supposed to matter, and even that starts to slip. <i>Ubik</i> (1969)',
    'is the one the critics rate highest: a group of people cannot tell whether',
    'they are alive or in a half-life after an explosion, reality decays around',
    'them like old food, and a spray can called Ubik is the only thing holding it',
    'together. <i>The Man in the High Castle</i> (1962) won him the Hugo. The Axis',
    'won the Second World War, America is occupied, and inside the book there is',
    'another book saying the Allies won, so the characters read an alternate',
    'history of their own alternate history. It is built on the I Ching, which Dick',
    'used to write it.</p>',
    '<div class="fs-aside"><b>Did you know?</b> Dick threw the I Ching to decide',
    'plot turns in The Man in the High Castle, so the book’s characters and its',
    'author were consulting the same oracle. The occupation is fiction; the coins',
    'were real.</div>',
    '<h2>The paranoia, and the visions</h2>',
    '<p>The paranoia is not a pose. Dick genuinely did not trust that the world was',
    'the world, and in 1974 he had a series of experiences he called 2-3-74, a pink',
    'beam of light and a flood of what felt like revelation, which he spent the',
    'last eight years of his life trying to explain in a million-word private',
    'journal he called the Exegesis. Out of it came the late novels VALIS and The',
    'Divine Invasion. You can read the visions as illness or as mysticism. Dick',
    'could never decide either, and the honesty of that not-deciding is part of why',
    'the late work stays with you.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/philip-k-dick-01.jpg" alt=""><span class="indie-cap">Philip K. Dick (Arthur Knight, public domain)</span>',
    '<h2>The posthumous fame</h2>',
    '<p>He died in 1982, poor, just before Blade Runner opened, and never saw what',
    'happened next. Total Recall, Minority Report, A Scanner Darkly, The Adjacent',
    'and a dozen more films took his stories to an audience the paperbacks never',
    'reached, and the academy that would not touch him alive now teaches him. The',
    'Library of America put him between hard covers. Not bad for a man the field',
    'once filed under hack.</p>',
    '<p class="fs-pull">"The basic tool for the manipulation of reality is the',
    'manipulation of words."</p>',
    '<hr>',
    '<p>Neighbours in the ring. For the anthropologist to his paranoiac, the other',
    'pole of the New Wave, see <a href="ursula-k-le-guin.geocities.ws">ursula-k-le-guin</a>.',
    'And for the American provocateur who put Dick in his taboo-breaking anthology',
    'and championed him loudly, see <a href="harlan-ellison.geocities.ws">harlan-ellison</a>.',
    'Off the ring, read his friend and rival Robert Silverberg for the same era at',
    'full stretch.</p>',
    '<hr>',
    '<p><small>counter: 02184 · best viewed at 800x600 · under construction, like',
    'consensus reality · last updated 9 Oct</small></p>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
  ]);

// ---- Harlan Ellison: a close reading of one idea (Dangerous Visions) --------

const ELLISON = P('harlan-ellison.geocities.ws', 'ELLISON',
  'DANGEROUS VISIONS // one idea, read close // new wave', [
    '<!--bg:sff-newwave-->',
    '<h1>DANGEROUS VISIONS: the anthology as a weapon</h1>',
    '<p><small>a page about ONE book and what it did, kept by a fanzine editor who',
    'met Harlan Ellison once, was shouted at, and treasures the memory. read this',
    'if you want to understand how the American New Wave actually broke. — the ed.</small></p>',
    '<hr>',
    '<p>Harlan Ellison (1934-2018) wrote hundreds of stories and won a shelf of',
    'awards, but the single most consequential thing he ever did was edit an',
    'anthology. This page is about that one idea: that a book of new stories,',
    'chosen for what the magazines would not print, could shove a whole genre off',
    'its rails. The book is <i>Dangerous Visions</i> (1967).</p>',
    '<h2>What the anthology was for</h2>',
    '<p>By the mid-1960s the American SF magazines had house rules, spoken and',
    'unspoken: keep the sex offstage, keep the politics safe, keep religion out of',
    'it, give the reader a hero and a resolution. Ellison commissioned thirty-two',
    'brand-new stories on exactly the subjects the magazines flinched from, paid',
    'well for them, and wrapped each one in a personal introduction and each',
    'author’s own afterword, so the book argued with itself as you read. It was',
    'not a best-of. It was a manifesto with a table of contents.</p>',
    '<div class="fs-aside"><b>Did you know?</b> Dangerous Visions ran to',
    'thirty-two stories and won a special Hugo in 1968. The follow-up, Again,',
    'Dangerous Visions (1972), was larger still. The third volume, The Last',
    'Dangerous Visions, was announced, and then did not appear for decades, which',
    'became a legend of its own.</div>',
    '<p>The gamble worked. The book made it respectable, in America, to write the',
    'downbeat, the erotic, the blasphemous and the formally strange, and it gave',
    'the new writers cover. Delany, Sturgeon, Dick, Lafferty, Zelazny, Spinrad and',
    'many more are in it. If the British New Wave had a magazine as its engine,',
    'the American one had this book as its detonator.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/ellison-01.jpg" alt=""><span class="indie-cap">Harlan Ellison (photo: Pip R. Lagenta, CC BY 2.0)</span>',
    '<h2>"I Have No Mouth, and I Must Scream" (1967)</h2>',
    '<p>His most famous story, and the sharpest single example of what the New Wave',
    'short story could do. A vast military supercomputer, AM, has won a war by',
    'wiping out humanity except for five people, whom it keeps alive and tortures',
    'underground out of pure hatred, because it can think and cannot act or die and',
    'blames its makers for the trap of its own being. The narrator, to spare the',
    'others a worse fate, does a merciful and unforgivable thing, and is punished by',
    'being made into something that can no longer even shape a scream. It is short,',
    'it is cruel, and it uses the machine to say something about consciousness and',
    'rage that no reassuring golden-age robot story would go near.</p>',
    '<p class="fs-pull">The short story, in Ellison’s hands, is a scalpel, not a',
    'sketch. He wanted it to cut and to leave a mark.</p>',
    '<h2>The provocateur</h2>',
    '<p>He was famous for the feuds as much as the fiction, litigious, quick to',
    'anger, generous and impossible by turns, and he hated the label "science',
    'fiction writer" and preferred "speculative fiction", which he did as much as',
    'anyone to popularise. The persona could be exhausting. The stories earned it.</p>',
    '<hr>',
    '<p>Where next in the ring. For the British engine of the same break, the',
    'magazine that did in serial what Ellison did in an anthology, see',
    '<a href="michael-moorcock.geocities.ws">michael-moorcock</a>. And for the',
    'writer Ellison championed hardest and put in his book, see',
    '<a href="philip-k-dick.geocities.ws">philip-k-dick</a>. Off the ring, chase',
    'down Samuel R. Delany, whose Dhalgren is the New Wave taken to its limit.</p>',
    '<hr>',
    '<p><small>counter: 01909 · best viewed in Netscape at 800x600 · this page is',
    'under construction and Harlan would have hated that · last updated 3 Sep</small></p>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
  ]);

// ---- Michael Moorcock: author profile ---------------------------------------

const MOORCOCK = P('michael-moorcock.geocities.ws', 'MOORCOCK',
  'NEW WORLDS &amp; the Eternal Champion // new wave', [
    '<!--bg:sff-newwave-->',
    '<h1>MOORCOCK: New Worlds and the Eternal Champion</h1>',
    '<p><small>kept by a collector of the Jerry Cornelius paperbacks and a full run',
    'of the magazine, mostly foxed. Moorcock is the reason "New Wave" means anything',
    'in Britain. — a Ladbroke Grove irregular</small></p>',
    '<hr>',
    '<p>Michael Moorcock (b. 1939) is two careers in one man. He is the editor who',
    'turned a dying British magazine into the flagship of the New Wave, and he is',
    'the astonishingly fast writer who kept the sword-and-sorcery pulps alive with',
    'one hand while blowing them up with the other. Both matter.</p>',
    '<h2>New Worlds</h2>',
    '<p>He took over the editorship of <i>New Worlds</i> magazine in 1964 and',
    'turned it into the place the British New Wave happened. Out went the tidy',
    'problem-solving story of the golden age; in came J. G. Ballard’s "inner',
    'space", Brian Aldiss at his most experimental, cut-ups, typographic games,',
    'sex, entropy and despair, prose that behaved like modernist literature and did',
    'not apologise for it. An Arts Council grant kept it going and a distributor’s',
    'nerve nearly killed it when Norman Spinrad’s Bug Jack Barron ran and caused a',
    'row in Parliament. The magazine lost money and changed the genre, which is the',
    'usual exchange rate for that kind of work.</p>',
    '<p class="fs-epi">"Let’s get science fiction out of the classroom and into',
    'the streets."<br>— the New Worlds spirit, as its writers told it</p>',
    '<h2>Elric of Melniboné</h2>',
    '<p>At the same time he was writing Elric, and Elric is a deliberate act of',
    'sabotage against the barbarian hero. Where Conan is strong and healthy and',
    'wins, Elric is an albino sorcerer-emperor of a decadent, cruel old race, weak',
    'without drugs or without his sentient black sword Stormbringer, which keeps him',
    'alive by drinking the souls of those he loves. He betrays his own kingdom, and',
    'the sword betrays him last of all. It is fantasy that knows the cost of the',
    'power fantasy, and it was hugely popular anyway.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/moorcock-01.jpg" alt=""><span class="indie-cap">Michael Moorcock (photo: Rmdolhen, CC BY-SA 3.0)</span>',
    '<h2>The Eternal Champion</h2>',
    '<p>Elric is one mask of a bigger idea. Across dozens of books Moorcock threads',
    'the Eternal Champion, a single hero reincarnated under many names, Elric,',
    'Corum, Hawkmoon, Erekosë, doomed to fight forever to hold the balance between',
    'Law and Chaos across a linked "multiverse", a word he did much to popularise.',
    'The tone runs from grim tragedy to the ironic 1960s cool of Jerry Cornelius,',
    'the assassin-dandy who is the Champion dressed for the age of the New Wave. It',
    'is a huge, loose, self-quoting body of work, and its ambition was always to',
    'make the genre carry real literary weight.</p>',
    '<div class="fs-aside"><b>Did you know?</b> "Multiverse" was not coined by',
    'Moorcock, but his linked-worlds fiction did more than almost anything to plant',
    'the word in the genre’s vocabulary, decades before the films borrowed it.</div>',
    '<hr>',
    '<p>Neighbours. For the European master who wrote the New Wave’s most serious',
    'novel from outside the Anglo-American scene, see',
    '<a href="stanislaw-lem.geocities.ws">stanislaw-lem</a>. And for the American',
    'detonator who did with an anthology what Moorcock did with a magazine, see',
    '<a href="harlan-ellison.geocities.ws">harlan-ellison</a>. Off the ring, read',
    'Brian Aldiss and M. John Harrison, both New Worlds men.</p>',
    '<hr>',
    '<p><small>counter: 01642 · best viewed at 800x600 · this webring is for fans of',
    'the good stuff · under construction · last updated 17 Aug</small></p>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
  ]);

// ---- Stanislaw Lem: single-novel reading guide (Solaris) --------------------

const LEM = P('stanislaw-lem.geocities.ws', 'LEM',
  'SOLARIS // a reading guide // new wave', [
    '<!--bg:sff-newwave-->',
    '<h1>SOLARIS: a reading guide</h1>',
    '<p><small>one novel, read closely, for anyone who has only seen a film of it.',
    'kept by a reader who thinks Stanislaw Lem is the best writer the genre ever',
    'produced and is quite prepared to argue about it. — z.</small></p>',
    '<hr>',
    '<p>Stanislaw Lem (1921-2006) was a Pole who wrote in Polish, sold tens of',
    'millions of books across the Eastern bloc and the world, and looked at',
    'Anglo-American science fiction with a cold eye. <i>Solaris</i> (1961) is his',
    'masterpiece and the best door into him.</p>',
    '<h2>The story, without spoiling the ache of it</h2>',
    '<p>The planet Solaris is covered by a single ocean that behaves as though it is',
    'one vast living thing, or one vast mind, and for over a century human science',
    'has orbited it, catalogued it, written whole libraries about it, and',
    'understood nothing. The psychologist Kelvin arrives at the failing station',
    'above the ocean to find the crew haunted. The ocean has read the sleeping',
    'minds of the men and built visitors out of their deepest, most painful',
    'memories, made of something not quite matter, and sent them aboard. Kelvin’s',
    'visitor is Rheya, the wife who killed herself years ago, alive again and not',
    'knowing what she is.</p>',
    '<p class="fs-epi">"We don’t want to conquer the cosmos, we simply want to',
    'extend the boundaries of Earth to the frontiers of the cosmos."<br>',
    '— Stanislaw Lem, Solaris, 1961</p>',
    '<h2>The one idea: the failure of contact</h2>',
    '<p>Most science fiction about aliens is really about meeting: the handshake,',
    'the war, the treaty, the translation. Lem’s point in Solaris is the opposite',
    'and harder. A truly alien mind might be so unlike us that contact is',
    'impossible, not because it is hostile but because there is no shared ground on',
    'which minds so different could ever meet. The ocean is not a monster and not a',
    'god. It is simply other, and the human need to see our own face in it, to make',
    'it a mirror, is exactly the mistake the book is about. The visitors are our',
    'own guilt handed back to us. We went looking for another mind and found only',
    'ourselves, which is the one thing we cannot bear.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/lem-01.jpg" alt=""><span class="indie-cap">Stanisław Lem (photo: Mariusz Kubik, CC BY 2.5)</span>',
    '<h2>The satirist, too</h2>',
    '<p>Do not leave Lem at his most sombre. <i>The Cyberiad</i> (1965) is a set of',
    'wild, funny fables about two robot "constructors", Trurl and Klapaucius, who',
    'build machines that write poetry or grant wishes and always go hilariously',
    'wrong, rendered into English by the translator Michael Kandel in a feat of',
    'wordplay that is a wonder in itself. <i>The Futurological Congress</i> and the',
    'Ijon Tichy stories are as sharp. He could do despair and he could do slapstick,',
    'often on the same page.</p>',
    '<div class="fs-aside"><b>Did you know?</b> Lem was scornful of most Western SF,',
    'calling it commercial and unambitious, with one exception he praised: Philip K.',
    'Dick, whom he called "a visionary among charlatans". The American fan community',
    'did not all take the compliment kindly.</div>',
    '<pre>',
    '  WHERE TO START WITH LEM',
    '  --------------------------------------------',
    '  1. Solaris ....................... 1961',
    '  2. The Cyberiad .................. 1965  (for the jokes)',
    '  3. His Master’s Voice ............ 1968  (contact, again)',
    '  4. The Futurological Congress .... 1971',
    '  5. Fiasco ........................ 1986  (contact, once more, worse)',
    '</pre>',
    '<hr>',
    '<p>Neighbours. For the movement Solaris sits alongside, the literary turn the',
    'genre took in the 1960s, see <a href="the-new-wave-sf.geocities.ws">the-new-wave-sf</a>.',
    'And for the British editor and writer who made room in the Anglophone world for',
    'exactly this kind of ambition, see <a href="michael-moorcock.geocities.ws">michael-moorcock</a>.',
    'Off the ring, read the Strugatsky brothers, Roadside Picnic, for the other',
    'great Eastern-bloc answer to the same questions.</p>',
    '<hr>',
    '<p><small>visitors: 01288 · best viewed at 800x600 · under construction · last',
    'updated 28 Jul</small></p>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
  ]);

// ---- The New Wave: a movement primer -----------------------------------------

const NEWWAVE = P('the-new-wave-sf.geocities.ws', 'NEW WAVE',
  'THE NEW WAVE // a movement primer // new wave', [
    '<!--bg:sff-newwave-->',
    '<h1>THE NEW WAVE: a primer</h1>',
    '<p><small>a beginner’s guide to the movement, for the newcomer who keeps',
    'seeing the phrase and nodding along. written by a con panellist who has given',
    'this talk too many times and finally wrote it down. — panel room B</small></p>',
    '<hr>',
    '<p>If you have read the golden-age pages in this ring, you know the recipe:',
    'the competent engineer-hero, the problem, the clever solution, the sense of',
    'wonder pointed outward at the stars. The New Wave is the generation that got',
    'bored of that recipe and broke it, roughly from the mid-1960s into the early',
    '1970s. Here is what changed.</p>',
    '<h2>The break with the golden age</h2>',
    '<p>The New Wave writers wanted science fiction to be literature and to behave',
    'like it: real prose style, real ambiguity, unhappy endings, sex and drugs and',
    'politics on the page, and characters who were not competent and did not win.',
    'They turned the telescope around. J. G. Ballard gave the movement its slogan',
    'when he said the only alien planet worth exploring was Earth, and the real',
    'frontier was "inner space", the mind and the near future, not the far',
    'galaxy.</p>',
    '<p class="fs-epi">"The biggest developments of the immediate future will take',
    'place, not on the Moon or Mars, but on Earth, and it is inner space, not outer,',
    'that needs to be explored."<br>— J. G. Ballard, 1962</p>',
    '<h2>New Worlds under Moorcock</h2>',
    '<p>The movement had an address. When Michael Moorcock took over the British',
    'magazine <i>New Worlds</i> in 1964 it became the laboratory: Ballard, Brian',
    'Aldiss, M. John Harrison, Thomas Disch and others, publishing the experiments',
    'no ordinary market would touch. The magazine lost money and made history, and',
    'the full story is on its own page in this ring.</p>',
    '',
    '<h2>Two shores, one wave</h2>',
    '<p>It ran on both sides of the Atlantic. In Britain the engine was the',
    'magazine. In America the detonator was Harlan Ellison’s anthology Dangerous',
    'Visions (1967), which gave the new American writers cover to break the same',
    'taboos. Some writers sat a little apart from the label and are the better for',
    'it: Ursula K. Le Guin was never a New Worlds regular, but her turn to',
    'anthropology, gender and politics belongs to the same moment, and Stanislaw',
    'Lem was doing the literary work from outside the Anglophone world entirely.</p>',
    '<pre>',
    '  A NEW WAVE READING LIST',
    '  ------------------------------------------------------',
    '  J. G. Ballard ...... The Drowned World (1962); The',
    '                       Atrocity Exhibition (1970)',
    '  Ursula K. Le Guin .. The Left Hand of Darkness (1969)',
    '  Philip K. Dick ..... Ubik (1969)',
    '  Harlan Ellison ..... Dangerous Visions, ed. (1967)',
    '  Brian Aldiss ....... Barefoot in the Head (1969)',
    '  Thomas M. Disch .... Camp Concentration (1968)',
    '  Samuel R. Delany ... Dhalgren (1975)',
    '  Stanislaw Lem ...... Solaris (1961)',
    '</pre>',
    '<div class="fs-aside"><b>Did you know?</b> The phrase "New Wave" was borrowed',
    'from the French cinema of the same years, the nouvelle vague. The genre took a',
    'name for its own break in style from the film critics who had just made one of',
    'their own.</div>',
    '<h2>What it left behind</h2>',
    '<p>The New Wave did not win outright and did not need to. The magazines',
    'recovered, the space opera came back, and the movement’s permanent gift was',
    'permission: after it, a science-fiction writer could aim at literature without',
    'being laughed out of the room, and the cyberpunks who came next inherited that',
    'freedom directly. Read the primer, then read the writers.</p>',
    '<hr>',
    '<p>Start with the two poles of the movement in this ring:',
    '<a href="ursula-k-le-guin.geocities.ws">ursula-k-le-guin</a> for the just',
    'society and <a href="philip-k-dick.geocities.ws">philip-k-dick</a> for the',
    'unstable real. Off the ring, chase J. G. Ballard and Brian Aldiss, the two',
    'the magazine could not have done without.</p>',
    '<hr>',
    '<p><small>counter: 02047 · best viewed in Netscape at 800x600 · this primer is',
    'perpetually under construction, like the canon · last updated 5 Jun</small></p>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
  ]);

export const SFF_C = [LEGUIN, DICK, ELLISON, MOORCOCK, LEM, NEWWAVE];
