// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH SOC_D — social democracy and the parliamentary road.
//
// The reformists and the ballot-box wing of the tradition, kept on a free host
// by students, branch secretaries and old party hands. Book-reading notes on
// Bernstein's revisionism; a rally write-up for Jaures; three org homepages for
// the SPD, the Fabians and the Second International; and a miner's fan shrine
// for Keir Hardie. The names, texts and dates are real; the enthusiasms and the
// grudges belong to the pages.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Bernstein: the book-reading notes (SHOWPIECE) --------------------------

const BERNSTEIN = P('eduard-bernstein.geocities.ws', 'BERNSTEIN',
  'EVOLUTIONARY SOCIALISM — reading notes (Bernstein)', [
    '<!--bg:soc-socialdem-->',
    '<h1>EVOLUTIONARY SOCIALISM</h1>',
    '<p><small>reading notes on Eduard Bernstein, <i>Die Voraussetzungen des',
    'Sozialismus</i> (1899), the book the English-speaking world knows as',
    '<i>Evolutionary Socialism</i>. kept for our Tuesday reading circle. i took',
    'the notes, so the mistakes are mine. — the convenor</small></p>',
    '<p class="fs-epi">"The movement is everything, the final goal nothing."<br>',
    '&mdash; Eduard Bernstein, 1899</p>',
    '<hr>',
    '<p>Some background first, because the quarrel does not make sense without it.',
    'Eduard Bernstein (1850 to 1932) was a close friend of Engels, one of his',
    'literary executors, and for years the keeper of orthodox Marxism inside the',
    'German party. Then, writing from exile in London and reading the Fabians at',
    'close range, he changed his mind in public. The articles that became this',
    'book set off what the Germans called the <i>Revisionismusstreit</i>, the',
    'revisionism dispute, and it split the socialist movement along a line that',
    'has never really closed.</p>',
    '<hr>',
    '<p><b>What he actually argued</b></p>',
    '<p>Bernstein looked at the figures at the end of the century and said the',
    'Marxist forecast was not coming true. Capital was not concentrating into ever',
    'fewer hands as fast as predicted; the middle strata were not vanishing but',
    'multiplying; the crises were not deepening toward a final collapse; and the',
    'condition of the workers was, slowly and unevenly, improving. If the',
    'catastrophe was not on the timetable, then a socialism that sat waiting for',
    'the crash was waiting for a train that was not coming.</p>',
    '<blockquote class="fs-quote"><p>"I frankly admit that I have extraordinarily',
    'little feeling for, or interest in, what is usually termed the final goal of',
    'socialism. This goal, whatever it may be, is nothing to me, the movement is',
    'everything."</p></blockquote>',
    '<p>That single sentence is the one everyone remembers, and it is worth being',
    'careful with. He did not mean he had stopped being a socialist. He meant that',
    'the daily work of the movement, the unions, the cooperatives, the votes',
    'gathered and the reforms won, was the real substance of socialism, and that a',
    'far-off promised end used to justify the present was doing no honest work.',
    'Socialism would come, if it came, by growth and by ballot, not by a single',
    'convulsion.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/bernstein-01.jpg" alt=""><span class="indie-cap">Eduard Bernstein (public domain)</span>',
    '<p class="fs-pull">Democracy is at the same time a means and an end. It is a',
    'means of the struggle for socialism, and it is the form in which socialism',
    'will be realised.</p>',
    '<p>He put a great deal of weight on democracy as the road itself. Where the',
    'workers could vote, organise and win a real share of power, the case for',
    'insurrection weakened; the parliamentary road was not a betrayal of the',
    'destination but a path to it. Universal suffrage, he said, was the alternative',
    'to the barricade, not a trick played on it.</p>',
    '<hr>',
    '<p><b>The theses, as we tried to boil them down</b></p>',
    '<pre>',
    '  THE REVISIONIST CASE, in points',
    '  ------------------------------------------',
    '  1. The collapse of capitalism is not imminent.',
    '     Crises recur but the system adapts and survives.',
    '  2. Capital is not concentrating as the theory said.',
    '     Small and medium firms persist; shareholders multiply.',
    '  3. The middle class grows, it does not disappear.',
    '     Society does not split cleanly into two camps.',
    '  4. The worker\'s lot improves through struggle.',
    '     Wages, hours and conditions can be won under this system.',
    '  5. Democracy is the road, not a detour.',
    '     The ballot and the union do the work the rising was meant to.',
    '  6. Socialism grows into being, it is not seized.',
    '     Reform is not a betrayal of revolution; it is the method.',
    '  7. Ethics matter, and cannot be read off economics.',
    '     "Back to Kant" as much as back to Marx.',
    '</pre>',
    '<hr>',
    '<p class="fs-aside"><b>A note on the fight.</b> Rosa Luxemburg answered him',
    'in <i>Reform or Revolution</i> (1900) and did not spare him: reforms were',
    'necessary, she said, but treating them as a road that arrives at socialism',
    'mistook the labour of Sisyphus for a staircase, because capitalism would',
    'keep restoring the very conditions the reforms softened. Karl Kautsky, the',
    'guardian of orthodoxy, argued against Bernstein from the centre and kept the',
    'party\'s official doctrine revolutionary in word even as its practice grew',
    'more reformist in deed. The party condemned revisionism at Hanover in 1899',
    'and at Dresden in 1903, and went on behaving more and more as Bernstein said',
    'it should.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/jaures-01.jpg" alt=""><span class="indie-cap">Jean Jaures (public domain)</span>',
    '<p>Our circle split about three ways on the night, which felt about right for',
    'the subject. One reading is that Bernstein was simply honest about what the',
    'party was already doing and had the nerve to say it aloud. Another is that he',
    'gave the movement permission to stop being dangerous, and that the road he',
    'praised ran, in 1914, straight to a vote for the Kaiser\'s war. A third is',
    'that the argument between reform and revolution was never going to be settled',
    'by a book, and that we were still having it in an upstairs room a century on.</p>',
    '<hr>',
    '<p>Where to read next in the ring. For the French answer to the same question, the',
    'unifier who tried to hold reform and revolution together, see',
    '<a href="jean-jaures.geocities.ws">jean-jaures</a>. For the party that this',
    'whole quarrel was really about, the machine Bernstein was trying to steer,',
    'see <a href="the-spd.geocities.ws">the-spd</a>. Luxemburg has her own page',
    'elsewhere in the ring; go and read <i>Reform or Revolution</i> before you',
    'decide he won.</p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01899 · best viewed at 800x600 · this page under',
    'permanent revision, which he would appreciate · last updated 14 Mar',
    '</small></p>',
  ]);

// ---- Jaures: the rally / talk write-up --------------------------------------

const JAURES = P('jean-jaures.geocities.ws', 'JAURES',
  'the night we talked about Jaures // a write-up', [
    '<!--bg:soc-socialdem-->',
    '<h1>THE NIGHT WE TALKED ABOUT JAURES</h1>',
    '<p><small>a write-up of the branch social, upstairs at the Institute, the',
    'anniversary of the assassination. i said i would type up the talk for anyone',
    'who missed it. any errors are mine, not the speaker\'s. — c.h.</small></p>',
    '<hr>',
    '<p>About forty of us came, which for a wet Thursday is not bad. The speaker',
    'had been to Paris and stood in the Cafe du Croissant where it happened, and',
    'she began there, at the end, and worked back, which turned out to be the',
    'right way to tell it.</p>',
    '<p>Jean Jaures (1859 to 1914) was the great orator of French socialism, a',
    'philosophy teacher from the Tarn who became the voice of the working class in',
    'the Chamber. He was not born to the movement; he reasoned his way into it,',
    'and he never lost the professor\'s habit of trying to persuade the whole room',
    'rather than only his own side.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/jaures-01.jpg" alt=""><span class="indie-cap">Jean Jaures (public domain)</span>',
    '<p><b>Dreyfus.</b> The speaker spent a good while here. When Captain Dreyfus',
    'was framed, many on the left said it was a quarrel between factions of the',
    'bourgeoisie and no business of the workers. Jaures disagreed, at real cost.',
    'An injustice done to one man, he argued, was an injury to the whole idea of',
    'justice the movement stood on, and socialists could not stand aside from it.',
    'He threw himself into the defence and helped turn the case.</p>',
    '<p><b>Unity.</b> French socialism was a nest of rival sects, and Jaures did',
    'the patient work of binding them. In 1905 the factions came together as the',
    'SFIO, the French Section of the Workers\' International, and though he had to',
    'give ground on doctrine to Jules Guesde\'s harder line, it was Jaures who made',
    'the unity hold and gave it a voice. In 1904 he founded the newspaper',
    '<i>L\'Humanite</i> to carry that voice, and it outlived him by a century.</p>',
    '<p class="fs-pull">Courage is to seek the truth and to speak it; it is not to',
    'submit to the law of the triumphant lie.</p>',
    '<p><b>The war.</b> His last fight was against the war everyone could see',
    'coming. He worked through the Second International for a coordinated general',
    'strike of the workers of every country, so that the armies could not be',
    'raised, and he crossed borders to argue for it in person. It was this, the',
    'speaker said, that got him killed. On the 31st of July 1914, days before the',
    'mobilisation, a nationalist shot him through the window of the cafe as he sat',
    'at supper. The strike never came. Within days the workers of Europe were in',
    'uniform and marching, and the International he had built lay in pieces.</p>',
    '<hr>',
    '<p>Someone asked at the end whether he would have voted the war credits had',
    'he lived, as the German comrades did. The speaker would not guess, and I think',
    'she was right not to. The point she left us with was that he was the one man',
    'both wings trusted, and that his murder took the bridge out from under the',
    'movement at the worst possible hour.</p>',
    '<p>For the wider structure he died trying to hold together, the federation of',
    'parties and its collapse in that same August, read',
    '<a href="the-second-international.geocities.ws">the-second-international</a>.',
    'For the German revisionist whose argument shadowed the French one, and whom',
    'Jaures read closely, see <a href="eduard-bernstein.geocities.ws">',
    'eduard-bernstein</a>.</p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>visitors: 00731 · best viewed at 800x600 · Institute branch social',
    'notes · page put up 04 Aug</small></p>',
  ]);

// ---- The SPD: the org / party homepage --------------------------------------

const SPD = P('the-spd.geocities.ws', 'THE SPD',
  'THE SPD // Sozialdemokratische Partei Deutschlands', [
    '<!--bg:soc-socialdem-->',
    '<h1>THE SPD</h1>',
    '<p><small>an unofficial history page for the Sozialdemokratische Partei',
    'Deutschlands, the German Social Democratic Party, put together for a study',
    'group. corrections welcome. best read alongside the programme texts',
    'themselves.</small></p>',
    '<hr>',
    '<p>For a generation before 1914 the SPD was the largest and best organised',
    'socialist party in the world, the party every other socialist party measured',
    'itself against. It had a daily press, a union federation, choirs, libraries,',
    'cycling clubs and funeral funds; a worker could be born, schooled, married',
    'and buried inside its world. By 1912 it was the biggest single party in the',
    'Reichstag. It was, for many, what victory was going to look like.</p>',
    '<p><b>Two founding programmes.</b> The party\'s history can be read through',
    'its programmes, and two of them matter above the rest.</p>',
    '<pre>',
    '  THE GOTHA PROGRAMME, 1875',
    '  -------------------------------------------',
    '  Union of the two workers\' parties (the Eisenachers,',
    '  led by Bebel and Liebknecht, and the Lassalleans).',
    '  Marx wrote a furious private critique of its muddle,',
    '  the "Critique of the Gotha Programme", not published',
    '  until 1891. Source of the line: "From each according',
    '  to his ability, to each according to his needs."',
    '',
    '  THE ERFURT PROGRAMME, 1891',
    '  -------------------------------------------',
    '  Drafted by Kautsky (theory) and Bernstein (practice),',
    '  before their paths forked. Two parts:',
    '    - a maximum programme, Marxist, on the coming',
    '      collapse of capitalism and the workers\' rule;',
    '    - a minimum programme of reforms to fight for now.',
    '  The template for orthodox social democracy for decades.',
    '</pre>',
    '<p><b>The long argument.</b> Under the surface the party carried an unsettled',
    'quarrel between its revolutionary word and its reformist deed. Bernstein said',
    'aloud that the practice had outgrown the theory and was condemned for it. The',
    'centre held the old doctrine on paper while the trade-union and parliamentary',
    'wing ran the machine day to day.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/spd-01.jpg" alt=""><span class="indie-cap">An SPD election poster, 1932 (public domain)</span>',
    '<p><b>August 1914.</b> The test came with the war. On the 4th of August 1914',
    'the SPD delegation in the Reichstag voted, as a bloc, for the war credits',
    'that funded the German war effort. The party of internationalism voted for',
    'the national war. For the left of the party it was a betrayal beyond',
    'repair, and it began the split that would produce the independent socialists',
    'and, later, the Communists. Karl Liebknecht broke discipline to vote no; the',
    'story of that wing belongs to another corner of the ring.</p>',
    '<hr>',
    '<p>Two neighbours in the ring speak directly to this page. For the party\'s',
    'great theorist, the man who drafted the Erfurt maximum and defended orthodoxy',
    'against Bernstein, see <a href="karl-kautsky.geocities.ws">karl-kautsky</a>.',
    'For the British party that took the parliamentary road without ever adopting',
    'the Marxist theory, a useful contrast, see',
    '<a href="keir-hardie.geocities.ws">keir-hardie</a>.</p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hits: 02071 · best viewed at 800x600 · under construction: the',
    'Weimar years still to add · last updated 19 Feb</small></p>',
  ]);

// ---- The Fabian Society: the org / society homepage -------------------------

const FABIAN = P('the-fabian-society.geocities.ws', 'FABIAN SOCIETY',
  'THE FABIAN SOCIETY // for the slow and the sure', [
    '<!--bg:soc-socialdem-->',
    '<h1>THE FABIAN SOCIETY</h1>',
    '<p><small>a homepage for the Fabian Society, the gradualist British society',
    'founded 1884. kept by a member of no importance for the general reader. we',
    'take our name from Fabius Cunctator, the Roman who beat Hannibal by refusing',
    'to give battle and wearing him down instead.</small></p>',
    '<hr>',
    '<p>The Society was founded in London in 1884, an offshoot of a high-minded',
    'ethical circle, and it set itself against the whole idea of revolution. Where',
    'the Marxists waited for the collapse, the Fabians proposed to bring socialism',
    'in the English way, by inches, by committee, by the slow reform of existing',
    'institutions until the country was socialist without ever having noticed the',
    'crossing. The motto might as well have been: make haste slowly.</p>',
    '<p><b>The people.</b> The early Society gathered a remarkable set. Sidney and',
    'Beatrice Webb were the engine of it, tireless researchers and writers who',
    'produced the factual case for reform in volume after volume. George Bernard',
    'Shaw brought the wit and edited the founding <i>Fabian Essays</i> (1889).',
    'Around them moved Graham Wallas, Annie Besant for a time, and later the young',
    'H. G. Wells, who quarrelled with them and left.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/fabian-01.jpg" alt=""><span class="indie-cap">Sidney and Beatrice Webb (photo: Simon Harriyott, CC BY 2.0)</span>',
    '<p><b>Permeation.</b> The characteristic Fabian tactic was not to build a mass',
    'party but to <i>permeate</i> the existing ones. The idea was to place sound',
    'arguments and well-drilled facts in front of whoever held power, Liberal or',
    'Conservative or the new Labour men, and let good policy seep into the state',
    'through its own officials and committees. Influence, not confrontation. The',
    'critics on the left called it socialism for the drawing room; the Fabians',
    'answered that a reform enacted beat a revolution imagined.</p>',
    '<p><b>What they built.</b> Two lasting things stand out. In 1895, largely on',
    'Webb money and Webb effort, they helped found the London School of Economics',
    'and Political Science, to train the experts a reforming state would need. And',
    'when the Labour Representation Committee formed in 1900, the Society was in at',
    'the founding and became one of the intellectual springs of the Labour Party,',
    'furnishing it with research, pamphlets and a steady supply of policy.</p>',
    '<hr>',
    '<p>Neighbours in the ring. For the Labour politician the Society helped bring',
    'to Parliament, though he came from the coalface and not the committee room,',
    'see <a href="keir-hardie.geocities.ws">keir-hardie</a>. For the guild',
    'socialist who argued with the Fabians from inside, against their faith in the',
    'state, see <a href="gdh-cole.geocities.ws">gdh-cole</a>.</p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01884 · best viewed at 800x600 · this page made slowly,',
    'on principle · last updated 21 Jan</small></p>',
  ]);

// ---- Keir Hardie: the personal fan shrine -----------------------------------

const HARDIE = P('keir-hardie.geocities.ws', 'KEIR HARDIE',
  'KEIR HARDIE // the man in the cloth cap', [
    '<!--bg:soc-socialdem-->',
    '<h1>KEIR HARDIE</h1>',
    '<p><small>a page for James Keir Hardie (1856 to 1915), because my',
    'grandfather kept his photograph on the mantelpiece next to the family and',
    'never quite explained why, and now I do. from a mining family myself, three',
    'generations on. — with a raised fist, w.g.</small></p>',
    '<pre>',
    '        o',
    '       /|\\    an injury to one',
    '      / | \\   is the concern of all',
    '        |',
    '       / \\',
    '</pre>',
    '<hr>',
    '<p>He went down the pit at ten. Ten years old, in the dark, in Lanarkshire,',
    'because his family needed the wage, and he taught himself to read and write',
    'by candle after his shifts. That is where you have to start with Keir Hardie,',
    'because everything else grows out of it: he was not a gentleman who chose the',
    'workers, he was a worker, and he never once let the House of Commons forget',
    'it.</p>',
    '<p>He came up through the miners\' union and then decided the workers needed',
    'their own party, not the charity of the Liberals. In 1888 he helped start the',
    'Scottish Labour Party, and in 1893 the <b>Independent Labour Party</b>, the',
    'ILP, the real beginning of an independent labour politics in Britain. When',
    'the Labour Representation Committee formed in 1900 and became the Labour',
    'Party, Hardie was its first chairman in Parliament. As much as any one man',
    'can be, he is why there is a Labour Party at all.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/hardie-01.jpg" alt=""><span class="indie-cap">Keir Hardie (public domain)</span>',
    '<p><b>The cloth cap.</b> Here is the story everyone tells. When Hardie first',
    'took his seat as the member for West Ham South in 1892, he did not arrive in',
    'the top hat and frock coat the Commons expected. He came in a plain tweed',
    'suit and a cloth cap, the cap of a working man, riding in a wagon, and the',
    'press was scandalised and called him the member for the unemployed. He meant',
    'every stitch of it. He was not there to be absorbed into the gentlemen\'s',
    'club; he was there to sit in it as what he was.</p>',
    '<p class="fs-pull">My work has consisted of trying to stir up a divine',
    'discontent with wrong.</p>',
    '<p><b>What he stood for, and what it cost him.</b> He was for women\'s',
    'suffrage when it was unpopular even on the left, for self-rule for India, and',
    'against the coming war with everything he had. He was a pacifist and an',
    'internationalist, and when the war broke out in August 1914 and the crowds',
    'cheered and even much of his own movement fell into line, he was booed down',
    'trying to speak for peace. It broke his health. He died the next year, in',
    '1915, a disappointed man in the middle of the slaughter he had begged the',
    'workers not to join.</p>',
    '<hr>',
    '<p>Two neighbours worth your time. For the great continental party that took',
    'the parliamentary road on a Marxist theory Hardie never bothered with, and',
    'that made the opposite choice on the war, see',
    '<a href="the-spd.geocities.ws">the-spd</a>. For the middle-class society that',
    'reached the same Labour Party from the drawing room while Hardie reached it',
    'from the pit, see <a href="the-fabian-society.geocities.ws">',
    'the-fabian-society</a>.</p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01856 · best viewed at 800x600 · keep the cap · last',
    'updated 26 Sep</small></p>',
  ]);

// ---- The Second International: the org homepage ------------------------------

const SECOND_INTERNATIONAL = P('the-second-international.geocities.ws', 'SECOND INTL',
  'THE SECOND INTERNATIONAL // 1889 to 1916', [
    '<!--bg:soc-socialdem-->',
    '<h1>THE SECOND INTERNATIONAL</h1>',
    '<p><small>a history page for the Second International, the federation of',
    'socialist and labour parties founded in Paris in 1889. put up for a study',
    'circle. this is the one people mean when they say "the International"',
    'collapsed in 1914.</small></p>',
    '<hr>',
    '<p>Where the First International had been a small body of quarrelling',
    'sections, the Second was a federation of real mass parties, the great',
    'national socialist and labour parties of Europe brought loosely together. It',
    'was founded in Paris in 1889, on the centenary of the French Revolution, and',
    'for twenty-five years it was the visible shape of international socialism, a',
    'parliament of the movement that met in congress after congress and passed',
    'resolutions in the name of the workers of the world.</p>',
    '<p><b>May Day and the eight hours.</b> Its most lasting act came at the very',
    'start. The founding congress of 1889 called for an international demonstration',
    'of the workers on the first of May, to press the demand for the',
    'eight-hour working day. From 1890 the workers of country after country downed',
    'tools and marched on May Day, and the date became the international holiday of',
    'labour it still is. The eight-hour day was the concrete demand that gave the',
    'young federation a common cause across every border.</p>',
    '<pre>',
    '  A FEW OF THE CONGRESSES',
    '  ---------------------------------',
    '  1889  Paris    founding; the May Day call',
    '  1891  Brussels',
    '  1893  Zurich',
    '  1896  London   the anarchists finally excluded',
    '  1900  Paris    the International Socialist Bureau set up',
    '  1904  Amsterdam  on reform, revolution and the war danger',
    '  1907  Stuttgart  the anti-war and anti-colonial debates',
    '  1912  Basel    an emergency congress against the coming war',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/soc/second-international-01.jpg" alt=""><span class="indie-cap">The Second International at Stuttgart, 1907 (public domain)</span>',
    '<p><b>The great debates.</b> Two arguments ran through every congress. One',
    'was reform against revolution, the Bernstein quarrel carried up to the',
    'international level. The other was colonialism, where a wing wanted to accept',
    'a "socialist colonial policy" and the left refused, insisting the movement',
    'stand with the colonised. Above both loomed the question of war: what would',
    'the workers\' parties do if the governments marched them against one another?',
    'Congress after congress swore they would resist, by strike if need be.</p>',
    '<p><b>1914.</b> Then the war came, and the answer was given. The great',
    'parties, the German above all, voted the war credits and backed their own',
    'governments; the promised international resistance did not happen; and the',
    'workers of Europe went to kill one another in their millions. The Second',
    'International did not survive the shock as a living body. Its right went into',
    'national coalitions, its centre floundered, and its revolutionary left broke',
    'away to build something new after 1917.</p>',
    '<hr>',
    '<p>Two roads out of this page. For the French socialist who died in July 1914',
    'trying to make the anti-war resistance real, see',
    '<a href="jean-jaures.geocities.ws">jean-jaures</a>. For the revolutionary',
    'body that rose from the wreckage of 1914 and defined itself against this one,',
    'see <a href="the-third-international.geocities.ws">the-third-international</a>.</p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hits: 01889 · best viewed at 800x600 · under construction: the',
    'Stuttgart resolution text to come · last updated 01 May</small></p>',
  ]);

export const SOC_D = [BERNSTEIN, JAURES, SPD, FABIAN, HARDIE, SECOND_INTERNATIONAL];
