// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH GENX_D — the cult directors (bg:genx-auteurs).
//
// Fan pages a film-obsessed kid kept on a free host in 1998, each ABOUT a
// director and never in the director's own voice. A Lynch shrine with a
// filmography card and dream-diary energy; a Jarmusch interview write-up done
// deadpan; a John Waters Q-and-A dripping with Baltimore filth; a Hal Hartley
// film-studies coursework page with a wonky bibliography; a Linklater Austin
// shrine; and a Coen top-ten filmography. The films, years and casts are real;
// the star ratings and the grudges are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- David Lynch: the personal fan shrine (SHOWPIECE) -----------------------

const LYNCH = P('david-lynch.geocities.ws', 'DAVID LYNCH',
  'THE RED ROOM // a David Lynch shrine', [
    '<!--bg:genx-auteurs-->',
    '<h1>THE RED ROOM</h1>',
    '<p><small>a shrine to David Lynch, kept by a girl who saw <i>Blue Velvet</i>',
    'too young at a friend\'s house and was never the same. i keep the coffee hot',
    'and the curtains red. welcome. — Laura (not that Laura)</small></p>',
    '<hr>',
    '<p class="fs-epi">"It is a strange world." — Sandy, <i>Blue Velvet</i></p>',
    '<p>David Lynch is not a director you watch, he is a weather you get caught in.',
    'The films look like the suburbs and sound like a factory two streets over that',
    'never shuts off. People say "Lynchian" now as if it were a genre, and i',
    'suppose it is: a bright ordinary surface, a lawn, a diner, a nice song from',
    '1958, and underneath it something humming and wrong. He finds the crawling',
    'thing under the manicured grass and he holds the shot too long so you have to',
    'look.</p>',
    '<hr>',
    '<p><b>WHERE TO START (and where NOT to)</b></p>',
    '<p>Do not start with <i>Eraserhead</i>. i love it more than my own family but',
    'it will frighten a beginner off for good. Start with <i>Blue Velvet</i> (1986),',
    'the ear in the field, Kyle MacLachlan playing detective, Isabella Rossellini,',
    'and Dennis Hopper as Frank Booth breathing that gas and saying things i cannot',
    'type on a page my nan might find. It is the perfect key to the whole locked',
    'house.</p>',
    '<pre>',
    '  +------------------------------------------------+',
    '  |  A LYNCH FILMOGRAPHY (the ones that count)     |',
    '  +------------------------------------------------+',
    '  |  1977  Eraserhead ...... the AFI nightmare     |',
    '  |  1980  The Elephant Man  8 Oscar nods, b&amp;w    |',
    '  |  1984  Dune ............ the one he disowns     |',
    '  |  1986  Blue Velvet ..... the masterpiece        |',
    '  |  1990  Wild at Heart ... Palme d\'Or, Cannes     |',
    '  |  1990-91  TWIN PEAKS ... television, ruined tv  |',
    '  |  1992  Fire Walk With Me  the prequel, booed    |',
    '  |  1997  Lost Highway .... the one that loops     |',
    '  +------------------------------------------------+',
    '  format: VHS. hunt the letterboxed tapes if you can.',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/genx/lynch-01.jpg" alt=""><span class="indie-cap">David Lynch (photo: Georges Biard, CC BY-SA 3.0)</span>',
    '<p><b>TWIN PEAKS and the Red Room</b></p>',
    '<p>In 1990 he put all of this on network television and for two years the',
    'whole country wanted to know who killed Laura Palmer. The town, the pie, the',
    '"damn fine cup of coffee", the log lady, and then the RED ROOM, the zig-zag',
    'floor and the backwards-talking dwarf and the curtains, a place that runs on',
    'dream logic and will not translate. Then the network made him name the killer',
    'too soon and the spell cracked, and i will hold that grudge against them until',
    'i die.</p>',
    '<p class="fs-aside"><b>did you know?</b> the dialogue in the Red Room was',
    'shot with the actors speaking their lines BACKWARDS, then the film was',
    'reversed, so the words come out forwards but the bodies move wrong. that is',
    'the whole man in one trick. nothing digital, just patience and a strange idea.</p>',
    '<blockquote class="fs-quote"><p>"The owls are not what they seem."</p>',
    '<p><small>— the Giant, <i>Twin Peaks</i></small></p></blockquote>',
    '<p><b>WILD AT HEART and LOST HIGHWAY</b></p>',
    '<p><i>Wild at Heart</i> (1990) is Nicolas Cage in the snakeskin jacket ("a',
    'symbol of my individuality and my belief in personal freedom") and Laura Dern',
    'on the road, Elvis and <i>The Wizard of Oz</i> put through a blender, and it',
    'won the Palme d\'Or and half the room hated it. <i>Lost Highway</i> (1997) is',
    'the newest and the most locked: a man becomes another man halfway through and',
    'the film never explains, the Mystery Man with the video camera, Robert Blake',
    'with no eyebrows, "we\'ve met before, haven\'t we". Do not try to solve it. Let',
    'it happen to you.</p>',
    '<p class="fs-pull">"This is the way i see it, and that\'s the way it is going',
    'to be." He does not do commentary tracks that explain. He thinks explaining a',
    'dream kills it, and he is right.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/jarmusch-01.jpg" alt=""><span class="indie-cap">Jim Jarmusch (photo: Harald Krichel, CC BY-SA 4.0)</span>',
    '<p><b>the sound, and the weather</b></p>',
    '<p>Half of Lynch is Angelo Badalamenti, who writes the ache under everything,',
    'and half is the ROOM TONE, the industrial rumble Lynch layers so low you feel',
    'it in your chest before you notice it. He trained as a painter and it shows:',
    'he builds a frame like a canvas and lets it rot. He also reads a daily weather',
    'report on the radio out in Los Angeles, "blue skies and golden sunshine all',
    'along the way", which is the most Lynchian thing of all, a man of dread who',
    'loves a clear morning.</p>',
    '<hr>',
    '<p>If you like him, go and see the other patient weirdos. Jim Jarmusch keeps',
    'the same slow nerve without the horror, all deadpan and black-and-white, over',
    'at <a href="jim-jarmusch.geocities.ws">jim-jarmusch</a>. And the Coen brothers',
    'do the bright-surface-dark-underneath trick as comedy, the small-town menace',
    'and the woodchipper, at <a href="the-coen-brothers.geocities.ws">',
    'the-coen-brothers</a>. Buscemi and Harry Dean Stanton wander between all our',
    'pages like ghosts.</p>',
    '<hr>',
    '<p><small>counter: 07213 · best viewed in Netscape at 800x600 · this page is',
    'ALWAYS under construction, like a dream · a flaming coffee cup gif would go',
    'here if i could get it to loop · last updated 14 Aug 1998 · signed, Laura',
    '(not that Laura)</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Jim Jarmusch: the interview write-up -----------------------------------

const JARMUSCH = P('jim-jarmusch.geocities.ws', 'JIM JARMUSCH',
  'SLOW CINEMA, COOL HAIR // a Jarmusch Q&amp;A write-up', [
    '<!--bg:genx-auteurs-->',
    '<h1>SLOW CINEMA, COOL HAIR</h1>',
    '<p><small>i do not have an actual interview with Jim Jarmusch, i am seventeen',
    'and i live in Leeds. what i have done is read every interview with him in',
    'every magazine our library gets and stitched the answers into the',
    'conversation i WISH i\'d had. every answer below is built from things he really',
    'said. — Col</small></p>',
    '<hr>',
    '<p class="fs-epi">"It\'s a sad and beautiful world." — Roberto, <i>Down by Law</i></p>',
    '<p><b>Q: For anyone who\'s never seen a Jarmusch film, what are they like?</b></p>',
    '<p>Slow. Deadpan. Usually black-and-white and proud of it. Not much happens',
    'and that is the point: the plot is a coat-hanger and the film is the coat, the',
    'hang of two odd people in a room saying almost nothing while the silence does',
    'the work. He lets a scene run past where any other director would cut, and',
    'the awkwardness curdles into something funny and then something tender.</p>',
    '<p><b>Q: Start us off. The breakthrough?</b></p>',
    '<p><i>Stranger Than Paradise</i> (1984). Shot on leftover film stock Wim',
    'Wenders gave him, each scene one unbroken take with a black frame between them',
    'like a slide show. A New York guy, his cousin Eva over from Hungary, a trip to',
    'a frozen Cleveland and then Florida, and the whole joke is that America is as',
    'flat and strange wherever you drag yourself. Won the Camera d\'Or at Cannes and',
    'basically drew the map for the American independent film.</p>',
    '<hr>',
    '<p><b>Q: And then?</b></p>',
    '<p><i>Down by Law</i> (1986), which is the one to fall in love with. Three men',
    'in a New Orleans cell: Tom Waits, John Lurie, and Roberto Benigni years before',
    'the world knew him, all teeth and broken English, drawing a window on the wall',
    'and asking them to look out of it. Robby Muller shot it and the black-and-white',
    'swamp light is worth the tape on its own.</p>',
    '<p class="fs-aside"><b>the Jarmusch regulars.</b> he works with musicians more',
    'than actors: Tom Waits, John Lurie of the Lounge Lizards (who scores the early',
    'films), Screamin\' Jay Hawkins, Joe Strummer of the Clash. the man casts with',
    'his record collection and it works.</p>',
    '<p><b>Q: <i>Mystery Train</i>?</b></p>',
    '<p>1989. Three stories in one cheap Memphis hotel, all crossing one night, the',
    'ghost of Elvis over the whole thing, a Japanese couple on an Elvis pilgrimage,',
    'and Screamin\' Jay Hawkins at the front desk being magnificent. Same nightclerk,',
    'same gunshot, three angles. Nobody frames a fleapit lobby like he does.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/jarmusch-01.jpg" alt=""><span class="indie-cap">Jim Jarmusch (photo: Harald Krichel, CC BY-SA 4.0)</span>',
    '<p><b>Q: The new direction, the strange one?</b></p>',
    '<p><i>Dead Man</i> (1995). A black-and-white western with Johnny Depp as a mild',
    'accountant called William Blake, drifting west into a dream of his own death,',
    'a Native companion called Nobody who thinks he is the poet, and a grinding',
    'Neil Young guitar score recorded live to the picture. It baffled people and',
    'the ones it did not baffle it wrecked. A "psychedelic western", he called it.',
    'It is the boldest thing he has done.</p>',
    '<blockquote class="fs-quote"><p>"Have you got any tobacco?"</p>',
    '<p><small>— Nobody, asked a hundred times, <i>Dead Man</i></small></p></blockquote>',
    '<p><b>Q: Last one. Why should a kid in 1998 care?</b></p>',
    '<p>Because he proves you can make a film out of cool and patience and a good',
    'friend with a guitar, on no money, and owe nobody an explosion. If you want',
    'the horror version of the same slow nerve, Lynch is over at',
    '<a href="david-lynch.geocities.ws">david-lynch</a>. And if you want the total',
    'opposite, all filth and shouting and no patience at all, John Waters is at',
    '<a href="john-waters.geocities.ws">john-waters</a>, and Jim would love him.</p>',
    '<hr>',
    '<p><small>hits: 02561 · best viewed in Netscape 3 at 800x600 · shot,',
    'like this page, in black and white · under construction (the Ghost Dog',
    'section, whenever that comes out) · last updated 2 Sep 1998 · — Col</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- John Waters: the zine Q-and-A ------------------------------------------

const WATERS = P('john-waters.geocities.ws', 'JOHN WATERS',
  'FILTH IS MY LIFE // a John Waters Q&amp;A zine', [
    '<!--bg:genx-auteurs-->',
    '<h1>FILTH IS MY LIFE</h1>',
    '<p><small>a badly photocopied fanzine page for the Pope of Trash himself, John',
    'Waters of Baltimore. we could not get a real interview so we made one up out',
    'of his own quotes, printed it on the office copier at 3am, and now it\'s here',
    'too. read it and go take a bath. — the editors, xeroxed with love</small></p>',
    '<hr>',
    '<p class="fs-epi">"Kill everyone now! Condone first-degree murder!" — Divine,',
    '<i>Pink Flamingos</i></p>',
    '<p><b>Q: Introduce yourself for the poor innocents.</b></p>',
    '<p>John Waters, of Baltimore, Maryland, which he has never left because why',
    'would he, it is the most beautiful ugly city in America and he films it like',
    'a love letter written in bad taste. Pencil moustache. The self-described',
    '"Pope of Trash", a title William Burroughs gave him and he took gladly. He',
    'makes films about the wrong people doing the wrong things and being HAPPY',
    'about it, and he means it as a moral position, which it is.</p>',
    '<p><b>Q: <i>Pink Flamingos</i>. Go on then.</b></p>',
    '<p>1972. Divine as "the filthiest person alive" defending the title against a',
    'jealous couple. Shot on 16mm around Baltimore for about ten thousand dollars',
    'with his gang of friends he calls the Dreamlanders. It ends with a thing',
    'Divine does with a poodle that we are not going to describe on a family',
    'webring, done in one real unfaked take, and it played midnight shows for',
    'YEARS. The most notorious film in the American underground, and gleeful with',
    'it, never grim.</p>',
    '<hr>',
    '<p><b>Q: Tell them about DIVINE.</b></p>',
    '<p>Harris Glenn Milstead, Waters\' friend since school, the greatest of the',
    'Dreamlanders, a heavy man in a tight dress and a hairline shaved back to the',
    'crown so the make-up had somewhere to go. Not a drag act exactly, a monster',
    'and a movie star at once, tender and terrifying. He is the beating heart of',
    'nearly every early Waters film. He died in 1988, days after <i>Hairspray</i>',
    'finally made him famous, and it still is not fair.</p>',
    '<p class="fs-aside"><b>the Dreamlanders.</b> Waters\' repertory gang: Divine,',
    'Mink Stole, Edith Massey (the egg lady!), David Lochary, Mary Vivian Pearce.',
    'friends from Baltimore who made the films together for nothing, for the joy of',
    'appalling people. a whole cinema built out of a friendship group.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/waters-01.jpg" alt=""><span class="indie-cap">John Waters (photo: PEN American Center, CC BY 2.0)</span>',
    '<p><b>Q: But then he went... nice?</b></p>',
    '<p><i>Hairspray</i> (1988) is the swerve: a PG film, a sweet one, about a',
    'plump teenager who wants to dance on local television in 1962 Baltimore and',
    'ends up integrating the show. Divine plays her mother AND the racist station',
    'manager. It is warm and it is still subversive, it just smuggles the message',
    'inside a candy shell, and it got him to a wider crowd without selling the',
    'filth out. Cry-Baby came after with Johnny Depp, same trick.</p>',
    '<blockquote class="fs-quote"><p>"Life is nothing if you\'re not obsessed."</p>',
    '<p><small>— John Waters</small></p></blockquote>',
    '<p><b>Q: The philosophy, in one line?</b></p>',
    '<p>Bad taste is the whole point, done with total love and a straight face. He',
    'is never sneering at his characters, he adores them, the shoplifters and the',
    'perverts and the egg-mad. That is what separates him from every edgelord who',
    'thinks shocking people is enough. Waters likes people. That is the secret',
    'ingredient in the filth.</p>',
    '<p><b>Q: Where next for a reader?</b></p>',
    '<p>Total change of temperature: Hal Hartley makes the coldest, cleanest,',
    'most controlled indie films going, the exact opposite of this, and it is worth',
    'the whiplash, at <a href="hal-hartley.geocities.ws">hal-hartley</a>. Or stay',
    'weird and go to Jim Jarmusch, all cool and deadpan, at',
    '<a href="jim-jarmusch.geocities.ws">jim-jarmusch</a>.</p>',
    '<hr>',
    '<p><small>counter: 03390 · best viewed in Netscape at 800x600 on a dirty',
    'monitor · a flaming skull gif lives here in spirit · perpetually UNDER',
    'CONSTRUCTION and proud · last updated 21 Jul 1998 · xeroxed with love</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Hal Hartley: the film-studies coursework -------------------------------

const HARTLEY = P('hal-hartley.geocities.ws', 'HAL HARTLEY',
  'FLAT AFFECT AS METHOD // FILM 214 coursework (Hartley)', [
    '<!--bg:genx-auteurs-->',
    '<h1>FLAT AFFECT AS METHOD: THE CINEMA OF HAL HARTLEY</h1>',
    '<p><small>FILM 214: American Independent Cinema · term paper (draft, do not',
    'circulate) · grade pending · i put it on my web space so my seminar group can',
    'read it before Thursday. yes the bibliography is a mess, i am fixing it.</small></p>',
    '<hr>',
    '<p class="fs-epi">"I\'m an orphan and a slut." — Maria, <i>The Unbelievable Truth</i></p>',
    '<p><b>1. Thesis.</b> This paper argues that Hal Hartley is the most formally',
    'disciplined of the American independents of the late 1980s and early 1990s,',
    'and the most unfairly overlooked. Where his contemporaries chase naturalism,',
    'Hartley builds a deliberately artificial world: actors deliver clever,',
    'aphoristic dialogue in a deadpan monotone, movement is choreographed and',
    'stylised, and emotion is held at arm\'s length until it detonates in a sudden,',
    'formal burst, often a dance. The flatness is not a failure of acting. It is',
    'the method.</p>',
    '<p><b>2. The Long Island trilogy.</b> Hartley shoots his home ground, suburban',
    'Long Island, on tiny budgets. <i>The Unbelievable Truth</i> (1989) pairs a',
    'philosophical ex-convict (Robert Burke) with a fashion-model-cum-doom-obsessed',
    'schoolgirl (Adrienne Shelly). <i>Trust</i> (1990), his best, gives Shelly a',
    'pregnant runaway and Martin Donovan a hand-grenade-carrying electronics genius,',
    'and asks whether respect and trust can be the same as love. <i>Simple Men</i>',
    '(1992) sends two brothers looking for their fugitive anarchist father, and',
    'stops dead for a group dance to Sonic Youth, which should not work and is',
    'perfect.</p>',
    '<hr>',
    '<p class="fs-pull">Hartley\'s people talk like philosophy students who have',
    'been up all night, then stand very still. The stillness is where the feeling',
    'is hiding.</p>',
    '<p><b>3. The Hartley company.</b> He builds a repertory like a theatre',
    'director. Adrienne Shelly and then Martin Donovan are his faces; Elina Lowensohn',
    'joins for <i>Amateur</i>. He writes the scores himself under the name Ned Rifle.',
    'The dialogue is aphoristic and repeated back and forth almost as call and',
    'response, the words handled like objects passed between the actors.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/hartley-01.jpg" alt=""><span class="indie-cap">Hal Hartley (photo: RealTVfilms, CC BY-SA 3.0)</span>',
    '<p><b>4. <i>Amateur</i> and the wider reach.</b> <i>Amateur</i> (1994) is the',
    'move to a bigger canvas: an amnesiac (Donovan), an ex-nun who writes',
    'pornography and believes herself a nymphomaniac (Isabelle Huppert, no less),',
    'a stolen floppy disk, real danger. The deadpan meets a thriller plot and the',
    'contrast sharpens both. It is the widest door into his work for a newcomer,',
    'the coursework tutor was right about that.</p>',
    '<blockquote class="fs-quote"><p>"There\'s no such thing as adventure. There\'s',
    'no such thing as romance. There\'s only trouble and desire."</p>',
    '<p><small>— Thomas, <i>Trust</i></small></p></blockquote>',
    '<p><b>5. Conclusion.</b> Hartley belongs beside Jarmusch as a stylist who',
    'chose control over confession, and beside Linklater as a chronicler of young',
    'people talking their way through ideas, though Hartley is colder and tighter',
    'than either. He is the auteur the video-store crowd forgets and should not.</p>',
    '<hr>',
    '<p><b>BIBLIOGRAPHY (provisional, will tidy)</b></p>',
    '<pre>',
    '  Hartley, H. (dir.) The Unbelievable Truth. 1989. [VHS]',
    '  Hartley, H. (dir.) Trust. 1990. [VHS]',
    '  Hartley, H. (dir.) Simple Men. 1992. [VHS, letterboxed]',
    '  Hartley, H. (dir.) Amateur. 1994. [rented, twice]',
    '  Fuller, G. "Being an Amateur", intro to the screenplays, ~1994',
    '  --- various clippings, Sight and Sound + the local paper',
    '  (NOTE: find a proper page number for the Fuller quote before Thurs)',
    '</pre>',
    '<p>Further viewing for the marker: for the naturalistic opposite of Hartley\'s',
    'stylisation, Richard Linklater and the Austin films at',
    '<a href="richard-linklater.geocities.ws">richard-linklater</a>. For the loud,',
    'filthy, warm-hearted opposite of Hartley\'s cool restraint, John Waters at',
    '<a href="john-waters.geocities.ws">john-waters</a>. Jarmusch is the nearest',
    'cousin but he does not have a slot in the assigned filmography, so i cite him',
    'in the text only.</p>',
    '<hr>',
    '<p><small>counter: 00612 · best viewed at 800x600 · under construction until',
    'i get my mark back · last updated 4 Nov 1998</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Richard Linklater: the personal fan shrine -----------------------------

const LINKLATER = P('richard-linklater.geocities.ws', 'LINKLATER',
  'JUST KEEP TALKING // a Richard Linklater shrine', [
    '<!--bg:genx-auteurs-->',
    '<h1>JUST KEEP TALKING</h1>',
    '<p><small>a shrine to Richard Linklater, patron saint of anyone who has ever',
    'walked around a city all night arguing about nothing that matters and',
    'everything that does. i live in a boring town and these films are my Austin.',
    '— dazed_dave</small></p>',
    '<hr>',
    '<p class="fs-epi">"You just gotta keep on livin\', man. L-I-V-I-N."',
    '— Wooderson, <i>Dazed and Confused</i></p>',
    '<p>Nothing happens in a Linklater film and it is the best thing you will ever',
    'watch. No explosions, no plot machine grinding away. Just people, mostly young,',
    'walking and talking, and the talk IS the film. He believes an ordinary',
    'conversation is dramatic enough if you actually listen to it, and he films it',
    'like it is, patient and warm and a little stoned, in and around Austin, Texas,',
    'where he set up his own outfit rather than move to Hollywood.</p>',
    '<hr>',
    '<p><b>SLACKER (1991)</b></p>',
    '<p>The one that named a generation, or got the name pinned on it. There is no',
    'main character. The camera follows one Austin oddball for a few minutes, then',
    'wanders off after whoever they bump into, and then off again, drifting through',
    'a whole city of conspiracy theorists, students, dreamers and cranks across one',
    'day. Made for almost nothing. It said you could film your own town and your own',
    'friends and call it a movie, and thousands of us believed it.</p>',
    '<p class="fs-aside"><b>did you know?</b> the woman early in <i>Slacker</i>',
    'trying to sell a jar she swears is Madonna\'s pap smear is one of the most',
    'quoted bits in indie film. Linklater himself opens the movie, riding in from',
    'the bus station monologuing to a silent cab driver about roads not taken.',
    'the whole method is right there in the first five minutes.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/linklater-01.jpg" alt=""><span class="indie-cap">Richard Linklater (photo: K.E.B., CC BY 2.0)</span>',
    '<p><b>DAZED AND CONFUSED (1993)</b></p>',
    '<p>The last day of school, 1976, a Texas town, a huge cast of unknowns who',
    'would all turn out to be somebody, and a soundtrack that costs more than the',
    'rest of the film put together. Ben Affleck as the paddle-swinging bully,',
    'Parker Posey as the mean senior girl, and Matthew McConaughey drawling',
    '"alright, alright, alright" as Wooderson, the man who left school but not the',
    'car park. A hang-out movie in the truest sense: you do not watch it, you spend',
    'the evening with it, and you never want the night to end.</p>',
    '<blockquote class="fs-quote"><p>"If I ever start referring to these as the best',
    'years of my life, remind me to kill myself."</p>',
    '<p><small>— Randall "Pink" Floyd, <i>Dazed and Confused</i></small></p></blockquote>',
    '<p><b>BEFORE SUNRISE (1995)</b></p>',
    '<p>And then the swerve into romance, and it is the most romantic film of the',
    'decade because it is nothing but talk. An American boy (Ethan Hawke) and a',
    'French girl (Julie Delpy) meet on a train, get off in Vienna, and walk and',
    'talk through one night before he flies home at dawn. That is the entire plot.',
    'One night, one city, two people deciding to be honest with a stranger they',
    'will probably never see again. It ruins you a little. In the good way.</p>',
    '<p class="fs-pull">Linklater trusts talk the way an action director trusts a',
    'stunt. Give him two smart people and a city at night and he does not need',
    'anything else.</p>',
    '<hr>',
    '<p>If this is your thing, go and see the two other patron saints of the',
    'walk-and-talk and the small budget. The Coen brothers do the plotted,',
    'meticulous, blackly funny opposite over at',
    '<a href="the-coen-brothers.geocities.ws">the-coen-brothers</a>, and Hal',
    'Hartley does the cold, stylised, deadpan version of young-people-talking at',
    '<a href="hal-hartley.geocities.ws">hal-hartley</a>. Parker Posey is in half of',
    'these films and deserves her own shrine, which someone in the ring is building.</p>',
    '<hr>',
    '<p><small>counter: 04128 · best viewed in Netscape at 800x600 · playing:',
    'nothing, go put on a record · under construction, always, like a good night',
    'out · last updated 30 Aug 1998 · — dazed_dave</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- The Coen Brothers: the top-ten / filmography page ----------------------

const COENS = P('the-coen-brothers.geocities.ws', 'COEN BROTHERS',
  'JOEL &amp; ETHAN // a Coen brothers top ten', [
    '<!--bg:genx-auteurs-->',
    '<h1>JOEL &amp; ETHAN: A COEN BROTHERS TOP TEN</h1>',
    '<p><small>two brothers from Minnesota who write together, direct together, and',
    'edit under a fake name (Roderick Jaynes, who does not exist and once got',
    'nominated). i have ranked their films, which is a doomed thing to do and i',
    'have done it anyway. fight me in the guestbook. — R.</small></p>',
    '<hr>',
    '<p class="fs-epi">"The Dude abides." — The Dude, <i>The Big Lebowski</i></p>',
    '<p>The Coens make crime comedies where the crime is stupid, the criminals are',
    'stupider, and something almost holy leaks in around the edges. Kidnappings go',
    'wrong, money goes missing, ordinary greed spirals into carnage, and they film',
    'it with the most precise, controlled camera in America and a script where every',
    'word is nailed down. Blackly funny and secretly serious. Nobody else sounds',
    'like them.</p>',
    '<pre>',
    '  THE RANKING (today\'s, ask me tomorrow)',
    '  ---------------------------------------------',
    '   1. Fargo ................... 1996',
    '   2. The Big Lebowski ........ 1998',
    '   3. Barton Fink ............. 1991',
    '   4. Raising Arizona ......... 1987',
    '   5. Blood Simple ............ 1984',
    '   6. Miller\'s Crossing ....... 1990',
    '   7. The Hudsucker Proxy ..... 1994',
    '  ---------------------------------------------',
    '  (yes only seven are really essential. i padded',
    '   top tens for years and i am done pretending.)',
    '</pre>',
    '<p><b>1. FARGO (1996).</b> "Based on a true story", which is a lie, and a great',
    'one. A car salesman (William H. Macy) hires two men to kidnap his own wife and',
    'it all goes to pieces in the Minnesota snow. Frances McDormand as the pregnant',
    'police chief Marge Gunderson, the kindest, sharpest person in any of their',
    'films, "and here ya are, and it\'s a beautiful day". The woodchipper. Steve',
    'Buscemi bleeding into the white. Their masterpiece, and it won Frances the',
    'Oscar and them the screenplay.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/coens-01.jpg" alt=""><span class="indie-cap">Joel and Ethan Coen (photo: Georges Biard, CC BY-SA 3.0)</span>',
    '<p><b>2. THE BIG LEBOWSKI (1998).</b> Brand new and already a religion in the',
    'making. Jeff Bridges as the Dude, a Los Angeles slacker dragged into a',
    'kidnapping plot over a mistaken identity and a soiled rug that "really tied the',
    'room together". John Goodman as Walter, Vietnam on a hair trigger. White',
    'Russians, bowling, nihilists, a severed toe. It flopped in the cinema this',
    'year and i promise you it will not stay flopped. Full zine writeup on the',
    'ring, i keep linking it.</p>',
    '<blockquote class="fs-quote"><p>"She\'s kidnapped herself." — Walter</p>',
    '<p><small>— <i>The Big Lebowski</i></small></p></blockquote>',
    '<p><b>3. BARTON FINK (1991).</b> A hymn to writer\'s block. A high-minded',
    'playwright (John Turturro) is lured to Hollywood, stuck in a peeling hotel that',
    'seems to be sweating, next door to a friendly insurance salesman (John Goodman)',
    'who is not what he seems. "I\'ll show you the life of the mind!" Won the Palme',
    'd\'Or and two other prizes at Cannes, which basically embarrassed the festival',
    'into changing the rules.</p>',
    '<p class="fs-aside"><b>the Coen company.</b> watch for the regulars: Frances',
    'McDormand (married to Joel), Steve Buscemi (killed inventively in most of',
    'them), John Goodman, John Turturro, Jon Polito, and Carter Burwell on every',
    'score since <i>Blood Simple</i>. Barry Sonnenfeld shot the swooping early ones',
    'before he went off to direct.</p>',
    '<p><b>4 &amp; 5. THE BEGINNINGS.</b> <i>Raising Arizona</i> (1987) is Nicolas',
    'Cage and Holly Hunter stealing a baby, a live-wire cartoon comedy shot like an',
    'action film. <i>Blood Simple</i> (1984) is where it started, a lean Texas noir',
    'about a jealous husband and a botched hit, made for nothing, announcing every',
    'trick they would spend the next fifteen years perfecting.</p>',
    '<hr>',
    '<p>Neighbours worth the walk. David Lynch does the small-town-with-a-rotten-',
    'underside thing as nightmare rather than comedy, over at',
    '<a href="david-lynch.geocities.ws">david-lynch</a>. And Richard Linklater does',
    'the loose, plotless, hang-out opposite of the Coens\' clockwork scripts at',
    '<a href="richard-linklater.geocities.ws">richard-linklater</a>. Buscemi ties',
    'half the ring together and has a shrine of his own somewhere in it.</p>',
    '<hr>',
    '<p><small>counter: 05046 · best viewed in Netscape at 800x600 · a flaming',
    'bowling ball gif belongs here · under construction (adding Miller\'s Crossing',
    'notes) · last updated 9 Oct 1998 · — R., who abides</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

export const GENX_D = [LYNCH, JARMUSCH, WATERS, HARTLEY, LINKLATER, COENS];
