// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — the schools to the Renaissance.
//
// Six pages a reading enthusiast might have kept: a sober academic précis of
// Maimonides; a handed-in undergraduate essay on Aquinas, course code and all,
// with a wonky bibliography; the minutes of a Tuesday reading group arguing
// about Scotus; a clean summary of Ockham; a write-up of a lecture on
// Machiavelli; and a first-person shrine to Montaigne. The works, dates and
// doctrines are real; the tone belongs to whoever built the page.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Maimonides: the academic summary ---------------------------------------

const MAIMONIDES = P('maimonides.geocities.ws', 'MAIMONIDES',
  'Maimonides // the Guide for the Perplexed', [
    '<!--bg:scholastic-->',
    '<h1>Maimonides</h1>',
    '<p><small>a short, sober account of Moses ben Maimon, kept for a study',
    'circle. corrections welcome. best viewed in Netscape at 800x600.</small></p>',
    '<hr>',
    '<p>Moses ben Maimon (1138–1204), known to Jewish tradition as the Rambam and',
    'to the Latin schools as Maimonides, was born in Cordoba in Muslim Spain. When',
    'the Almohad conquest ended the relative tolerance of the city his family went',
    'into exile, and after years of wandering he settled at Fustat, near Cairo,',
    'where he served as a physician to the vizier of Saladin and led the Jewish',
    'community. He wrote the philosophical work in Judeo-Arabic and the legal work',
    'in Hebrew, and he did both at the highest level, which is rare.</p>',
    '<p>His great legal achievement is the <i>Mishneh Torah</i>, a complete code of',
    'Jewish law arranged by subject rather than by the tangle of the Talmud, so',
    'that a reader could find the ruling without following every argument that led',
    'to it. His great philosophical work is the <i>Guide for the Perplexed</i>',
    '(<i>Dalalat al-Ha’irin</i>, finished around 1190). The perplexed reader',
    'it addresses is not the doubter but the believer who has also studied',
    'philosophy and cannot see how the two hold together.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/maimonides-01.jpg" alt=""><span class="indie-cap">Maimonides (public domain)</span>',
    '<p><b>Negative theology</b></p>',
    '<p>The heart of the <i>Guide</i> is the doctrine that we cannot say what God',
    'is, only what God is not. Every positive term we might apply, wise, living,',
    'powerful, drags in the limits of a creature and so falsifies the subject.',
    'Maimonides holds that the divine attributes must be read as negations: to say',
    'God is living is to deny that God is dead matter, no more. Even existence is',
    'not a property God shares with things in the ordinary way. The reward of this',
    'severe method is that it refuses the idols of the imagination, and Maimonides',
    'thought idolatry, not disbelief, was the real danger.</p>',
    '<blockquote class="fs-quote"><p>The bounds of reason stop far short of the',
    'divine, and the wise man keeps silent where the imagination would rush in.</p>',
    '<p>— paraphrase of the Guide, I.59</p></blockquote>',
    '<p><b>Aristotle and the Torah</b></p>',
    '<p>The larger project is the reconciliation of Aristotle with the Law. On most',
    'questions Maimonides follows the Philosopher, but on the eternity of the world',
    'he stops. Aristotle held the cosmos had no beginning; scripture teaches',
    'creation. Maimonides argues that Aristotle did not, in fact, prove eternity,',
    'that the matter is undecided by reason, and that where reason cannot settle a',
    'question the teaching of the Law may stand. It is a careful, guarded position,',
    'and it drew fire from both the pious and the philosophers.</p>',
    '<div class="fs-aside"><p><b>A note on the readers.</b> The <i>Guide</i> was',
    'read hard by Christian scholastics. Aquinas cites Rabbi Moyses with respect on',
    'creation and the divine names. For the Aristotelian tradition Maimonides drew',
    'on, see <a href="avicenna.geocities.ws">Avicenna</a>; for the Latin scholastic',
    'who took up his questions, see <a href="aquinas.geocities.ws">Aquinas</a>.</p>',
    '</div>',
    '<hr>',
    '<p><small>You are visitor 00312 · this corner under construction · last',
    'updated 4 Mar · a study-circle page</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Aquinas: the student coursework essay (SHOWPIECE) -----------------------

const AQUINAS = P('aquinas.geocities.ws', 'AQUINAS',
  'Aquinas // the Five Ways (coursework)', [
    '<!--bg:scholastic-->',
    '<h1>Reason and the Five Ways in Thomas Aquinas</h1>',
    '<div class="fs-epi"><p>The things of God are made known to us by reason and by',
    'grace both.<br>— after Thomas Aquinas</p></div>',
    '<p><small><b>PHIL 204: Medieval Philosophy.</b> Coursework essay, term two.',
    'Word count 1,480. Submitted late (sorry). Please mark against the Aquinas',
    'handout. — a second-year, initials K.T.</small></p>',
    '<hr>',
    '<p>Thomas Aquinas (1225–1274) was born near Aquino in southern Italy and',
    'joined the Dominicans against his family, who are said to have locked him up',
    'for a year to change his mind. It did not work. He studied at Paris and',
    'Cologne under Albertus Magnus, and his fellow students called him the Dumb Ox',
    'for his size and his silence, at which Albert is supposed to have said the',
    'bellowing of this ox would be heard through the whole world. It was. He is now',
    'the Angelic Doctor, and his unfinished <i>Summa Theologiae</i> is the largest',
    'building in medieval thought.</p>',
    '<p>This essay does three things. It sets out what Aquinas wanted the',
    '<i>Summa</i> to do; it gives one of the Five Ways properly, as an argument you',
    'can inspect; and it says a word about natural law and about the essence and',
    'existence distinction, because you cannot understand the proofs without them.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/aquinas-01.jpg" alt=""><span class="indie-cap">Thomas Aquinas, by Carlo Crivelli (public domain)</span>',
    '<p><b>What the Summa is for</b></p>',
    '<p>The <i>Summa Theologiae</i> is a teaching book, written for beginners, which',
    'is a joke that only lands once you have tried to lift it. Its method is the',
    'disputed question: state the position, give the strongest objections against',
    'your own view first, answer with a central argument, then reply to each',
    'objection in turn. It is fair to the other side to a fault. Alongside it sits',
    'the earlier <i>Summa Contra Gentiles</i>, aimed at readers who do not share',
    'the scriptures and so must be met on reason alone.</p>',
    '<p>The governing conviction is that faith and reason cannot finally conflict,',
    'because both come from the one God. Reason can carry you a long way on its own,',
    'far enough to know that God exists and something of what God is not. It cannot',
    'reach the Trinity or the Incarnation, which are held by faith. Grace does not',
    'cancel nature, it completes it, and this is why Aristotle, newly arrived in the',
    'Latin west, could be baptised into a Christian philosophy rather than banned.</p>',
    '<blockquote class="fs-quote"><p>Grace does not destroy nature but perfects it.</p>',
    '<p>— Summa Theologiae, I, q.1, a.8</p></blockquote>',
    '<p><b>One of the Five Ways</b></p>',
    '<p>Early in the <i>Summa</i> (I, q.2, a.3) Aquinas gives five ways to show that',
    'God exists, from motion, from cause, from contingency, from degrees of',
    'perfection, and from the governance of things. They are not meant to move a',
    'heart; they are meant to show that belief is not against reason. Here is the',
    'first, the argument from motion, set out step by step so the shape is clear.</p>',
    '<pre>',
    'THE FIRST WAY (from motion)',
    '  1. Some things in the world are in motion; this the senses show.',
    '  2. Whatever is in motion is moved by another.',
    '  3. To be moved is to be brought from potency to act.',
    '  4. A thing cannot be in potency and act in the same respect at once,',
    '     so nothing moves itself.',
    '  5. If each mover is itself moved by a prior mover, we have a series.',
    '  6. The series of moved movers cannot run back without end, for then',
    '     there would be no first mover and so no motion at all.',
    '  7. Therefore there is a first mover, itself moved by nothing.',
    '  8. This first mover all understand to be God.',
    '</pre>',
    '<p>The weight rests on step six. Aquinas does not argue against an infinite',
    'past as such; his point is about an ordered series acting here and now, where',
    'the later movers have no power to move except as the first one lends it, the',
    'way a stick moves a stone only because a hand moves the stick. Remove the hand',
    'and the whole line goes still. Whether that holds is exactly where the',
    'reading group fell out, but the argument is at least honest about its hinge.</p>',
    '<div class="fs-pull"><p>The proof does not warm the heart. It clears the ground',
    'so that faith is not made to look absurd.</p></div>',
    '<p><b>Essence, existence, and natural law</b></p>',
    '<p>Behind the Ways is a metaphysics. In every creature Aquinas distinguishes',
    'what a thing is, its essence, from that it is, its existence. A creature does',
    'not contain its own existence; it receives it. Only in God are essence and',
    'existence the same, so that God does not have existence but is existence,',
    '<i>ipsum esse subsistens</i>. This is why the proofs end where they do: they',
    'are looking for the one being whose nature is simply to be.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/augustine-01.jpg" alt=""><span class="indie-cap">Augustine, the authority he reworked (public domain)</span>',
    '<p>The same reason that finds God orders human life. Natural law, for Aquinas,',
    'is the way a rational creature shares in the eternal law by grasping the ends',
    'proper to its nature: preserve life, raise the young, seek truth, live in',
    'society. Human law is just only so far as it agrees with this; a law that',
    'contradicts it is, he says, no law but a kind of violence. This is the thread',
    'later natural-rights thinking pulls on, long after the theology is set aside.</p>',
    '<div class="fs-aside"><p><b>Where he stands to his neighbours.</b> Aquinas',
    'inherits the psychology of memory and will from',
    '<a href="augustine.geocities.ws">Augustine</a>, though he leans harder on',
    'Aristotle than Augustine ever would. Within a generation',
    '<a href="duns-scotus.geocities.ws">Duns Scotus</a> would reopen almost every',
    'question here, above all whether being is said of God and creatures in the',
    'one sense or only by analogy. Aquinas says by analogy; Scotus says univocally.',
    'That quarrel runs for centuries.</p></div>',
    '<hr>',
    '<p><b>Bibliography</b> (as handed in)</p>',
    '<ul>',
    '<li>Aquinas, Thomas. <i>Summa Theologiae</i>. (the Dominican translation, the',
    'big blue set in the library, I used vol. 1 mostly)</li>',
    '<li>Aquinas. <i>Summa Contra Gentiles</i>, Book One. Uni Notre Dame edition.</li>',
    '<li>Kenny, Anthony. <i>The Five Ways</i>. 1969 I think. very helpful, a bit hard.</li>',
    '<li>Copleston, F. <i>Aquinas</i> (the Penguin one).</li>',
    '<li>the PHIL 204 lecture handout, week 5.</li>',
    '<li>Chesterton, G.K. <i>St Thomas Aquinas: The Dumb Ox</i>. short and readable,',
    'the tutor said not to lean on it but the ox story is in here.</li>',
    '</ul>',
    '<p><small>You are visitor 00641 · essay page under construction, footnotes to',
    'follow · best viewed at 800x600 · last updated 21 Feb · — K.T.</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Duns Scotus: the reading-group minutes ---------------------------------

const DUNS_SCOTUS = P('duns-scotus.geocities.ws', 'DUNS SCOTUS',
  'Duns Scotus // minutes: the Subtle Doctor', [
    '<!--bg:scholastic-->',
    '<h1>The Subtle Doctor: reading-group minutes</h1>',
    '<p><small>minutes of the medievals reading group. we meet the first Thursday,',
    'back room of the Eagle. present: six of us and a visitor. topic this month:',
    'John Duns Scotus. taken down by the secretary, mistakes are mine.</small></p>',
    '<hr>',
    '<p><b>Housekeeping.</b> Agreed to keep to primary texts in translation where we',
    'can find them. Someone brought the <i>Ordinatio</i> selections and a photocopy',
    'of the <i>Questions on the Metaphysics</i>. Next month provisionally Ockham,',
    'to see how the quarrel came out.</p>',
    '<p><b>The man.</b> John Duns Scotus, born about 1266, a Scot, a Franciscan,',
    'taught at Oxford, Paris and Cologne, dead young in 1308. Called the Subtle',
    'Doctor for the fineness of his distinctions, and later, unfairly, the word',
    '"dunce" was coined by his enemies out of "Duns". We agreed that was a slander',
    'on a very sharp mind.</p>',
    '<p><b>Univocity of being.</b> This took the first hour. The question is whether',
    'the word "being" means the same thing when we say a stone exists and when we',
    'say God exists. Aquinas had said no, only by analogy, so that "being" is',
    'stretched between them. Scotus says there must be one plain sense of being that',
    'covers both, otherwise, he argues, no argument could ever climb from creatures',
    'to God at all, because the middle term would slide under our feet. R. put it',
    'well: if being means something wholly different up there, the ladder has no',
    'rungs. This is the univocity of being, and it is the hinge of everything else.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/duns-scotus-01.jpg" alt=""><span class="indie-cap">Duns Scotus, by Justus van Gent (public domain)</span>',
    '<p><b>Haecceity.</b> The word everyone came for. <i>Haecceitas</i>, "thisness".',
    'The problem: what makes this individual cat this one and not just an instance',
    'of cat in general? The common nature, felineness, is shared; it cannot be what',
    'individuates. Scotus says there is a positive principle of individuality in',
    'each thing, its haecceity, its very thisness, added to the common nature and',
    'contracting it to one. J. objected that this is a name for the problem, not a',
    'solution. The visitor answered that naming it as positive, rather than as mere',
    'matter or an accident, is the whole claim: the individual is not a leftover,',
    'it is a perfection. We did not settle this.</p>',
    '<blockquote class="fs-quote"><p>It is not this by anything added from outside,',
    'but by its own ultimate reality.</p><p>— the group’s gloss on the',
    'Ordinatio, II</p></blockquote>',
    '<p><b>The formal distinction.</b> Scotus wanted a middle between a real',
    'distinction (two separable things) and a merely mental one (a distinction we',
    'make up). The formal distinction is in the thing but not between two things:',
    'the divine mercy and justice differ formally, really there in God, yet God is',
    'utterly one. P. said this is the finest knife in the drawer and also the one',
    'most likely to cut you. Ockham, we noted, will take exactly this knife away',
    'next month.</p>',
    '<p><b>Actions.</b> Someone to find the Wolter translation for June. Agreed the',
    'line to Ockham matters: see <a href="william-of-ockham.geocities.ws">William',
    'of Ockham</a>, who was taught in this tradition and then turned on its',
    'apparatus. For the position Scotus is pushing against throughout, see',
    '<a href="aquinas.geocities.ws">Aquinas</a> on analogy. Meeting closed 9:40,',
    'to the bar.</p>',
    '<hr>',
    '<p><small>You are visitor 00188 · minutes page, under construction · best',
    'viewed in Netscape 800x600 · last updated 6 May</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- William of Ockham: the academic summary --------------------------------

const OCKHAM = P('william-of-ockham.geocities.ws', 'OCKHAM',
  'William of Ockham // the razor and the names', [
    '<!--bg:scholastic-->',
    '<h1>William of Ockham</h1>',
    '<p><small>a plain summary of the Venerable Inceptor, kept for reference.',
    'best viewed at 800x600. corrections by email.</small></p>',
    '<hr>',
    '<p>William of Ockham (c.1287–1347) was an English Franciscan, born in the',
    'village of Ockham in Surrey, who studied and taught at Oxford but never took',
    'the master’s chair, which is why he is called the Venerable Inceptor, an',
    'inceptor being one who has begun but not finished the formal degree. He is',
    'remembered for a principle of economy, for a thoroughgoing nominalism, and for',
    'a late life spent in open conflict with the papacy.</p>',
    '<p><b>The razor.</b> The maxim that carries his name, "do not multiply entities',
    'beyond necessity", he never wrote in those exact words, though the idea is',
    'everywhere in him: what he does say is that plurality is not to be posited',
    'without necessity, and that it is pointless to do with more what can be done',
    'with fewer. It is a rule of method, not a claim about the world. It tells you',
    'to prefer the leaner explanation, all else being equal, and to stop conjuring',
    'extra machinery to save a theory. Applied hard, it clears away a great deal of',
    'the scholastic furniture, which is exactly what Ockham used it to do.</p>',
    '<div class="fs-aside"><p><b>What the razor is not.</b> It does not say the',
    'simplest answer is true. It says do not assume more than you must. A useful',
    'discipline, not an oracle.</p></div>',
    '<p><b>Nominalism.</b> The sharpest use of the razor is against universals. Are',
    'there real, shared natures, humanity, whiteness, standing behind the many',
    'individual humans and white things? The whole tradition from Plato through the',
    'realists said yes in some form; Scotus had given the common nature a subtle',
    'reality of its own. Ockham says no. Only individuals exist. What is general is',
    'the sign, the concept in the mind and the word on the tongue, which stands for',
    'many individuals at once. Universals are how we think and talk about things,',
    'not extra things. This is nominalism, and it takes away at a stroke the common',
    'natures and formal distinctions the previous generation had built.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/ockham-01.jpg" alt=""><span class="indie-cap">William of Ockham (photo: Moscarlop, CC BY-SA 3.0)</span>',
    '<p>The consequences run deep. If only individuals are real, knowledge begins in',
    'the direct grasp of the individual, what Ockham calls intuitive cognition, and',
    'the sciences deal in signs and propositions rather than in contemplated',
    'essences. His logic, worked out in the <i>Summa Logicae</i>, is correspondingly',
    'a logic of terms and their supposition, of how words stand for things, and it',
    'is admired now as some of the best formal work of the age.</p>',
    '<p><b>The poverty dispute.</b> Ockham’s later life was politics. As a',
    'Franciscan he held that Christ and the apostles had owned nothing, and when',
    'Pope John XXII condemned this doctrine of absolute poverty Ockham judged the',
    'pope to be in error, even a heretic. Summoned to Avignon and then fleeing it,',
    'he took refuge with the Emperor Louis of Bavaria, to whom he is supposed to',
    'have said, defend me with the sword and I will defend you with the pen. He',
    'spent his last years writing against papal power over temporal things.</p>',
    '<p>The line forward is long. The turn to the individual and the suspicion of',
    'unseen entities feed, at a distance, into the empiricism that follows; on',
    'universals and on cause the argument runs on to',
    '<a href="hume.geocities.ws">Hume</a>. For the tradition Ockham cut back, and',
    'the thisness he denied any special reality, see',
    '<a href="duns-scotus.geocities.ws">Duns Scotus</a>.</p>',
    '<hr>',
    '<p><small>You are visitor 00276 · reference page · best viewed at 800x600 ·',
    'last updated 9 Apr · this section still under construction</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Machiavelli: the talk write-up -----------------------------------------

const MACHIAVELLI = P('machiavelli.geocities.ws', 'MACHIAVELLI',
  'Machiavelli // notes from a lecture', [
    '<!--bg:earlymodern-->',
    '<h1>Machiavelli: notes from a lecture</h1>',
    '<p><small>I went to hear a public lecture on Machiavelli at the college last',
    'week and typed my notes up. any errors are mine, not the speaker’s. best',
    'viewed in Netscape at 800x600.</small></p>',
    '<hr>',
    '<p>The room was full, which the speaker said was fitting for a man whose name',
    'became an insult in his own century and has stayed one. Niccolò Machiavelli',
    '(1469–1527) was a Florentine, a working official, not a professor. For fourteen',
    'years he was secretary to the republic, running errands of state and watching',
    'princes and popes up close, until the Medici returned in 1512, dismissed him,',
    'and had him tortured on suspicion of a plot. Cleared but shut out, he retired',
    'to a small farm and wrote. The books came out of unemployment and exile.</p>',
    '<p><b>The Prince.</b> The speaker was firm that <i>Il Principe</i> (written',
    '1513, printed 1532, after his death) is not a wicked book but a cold one. Its',
    'scandal is method, not malice. Where the mirror-for-princes tradition told a',
    'ruler how a good man ought to behave, Machiavelli asks what actually keeps a',
    'ruler in power, and reports it. He famously says it is safer to be feared than',
    'loved, if you cannot be both, because love is held by a bond men break when it',
    'suits them, while fear is held by a dread of punishment that does not let go.',
    'He adds, and the speaker stressed this, that the prince must at all costs avoid',
    'being hated, which is fear’s ruinous cousin.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/machiavelli-01.jpg" alt=""><span class="indie-cap">Machiavelli, by Santi di Tito (public domain)</span>',
    '<p><b>Virtu and fortuna.</b> This was the heart of the talk. <i>Fortuna</i> is',
    'fortune, chance, the turn of events no one commands; Machiavelli pictures her',
    'as a river in flood. <i>Virtu</i> is not virtue in the moral sense but a kind',
    'of manly skill and force, the capacity to act well and boldly in the world as',
    'it is. The virtuous man in this sense does not wait on fortune; he builds the',
    'dykes and channels in the calm so that when the flood comes he is ready. The',
    'speaker read the notorious line that fortune is a woman and favours the bold,',
    'noted how it grates on a modern ear, and did not excuse it, only placed it.</p>',
    '<blockquote class="fs-quote"><p>It is better to be impetuous than cautious, for',
    'fortune is a woman, and yields to those who master her.</p>',
    '<p>— The Prince, ch. 25 (the speaker’s rendering)</p></blockquote>',
    '<p><b>The other book.</b> A questioner asked whether Machiavelli was simply a',
    'friend to tyrants. The speaker pointed to the <i>Discourses on the First Ten',
    'Books of Livy</i>, a much longer work written around the same years, where',
    'Machiavelli argues for republics, for the rule of law, even for the usefulness',
    'of open conflict between the classes as a source of Roman liberty. The Prince',
    'is the famous short book; the Discourses are where his heart seems to lie. Read',
    'together they show a republican who had looked hard at how power really moves.</p>',
    '<p><b>Afterwards.</b> In the questions someone brought up Hobbes, who a century',
    'later would build a whole science of politics on fear and self-interest, the',
    'state raised to hold off the war of all against all. The speaker allowed the',
    'family resemblance but drew a line: Hobbes wants a system with a proof,',
    'Machiavelli wants to tell you the truth about particular men in particular',
    'towns. One reasons from a first principle, the other from the news. That was',
    'the last exchange and a good one to end on.</p>',
    '<p>For the sceptical temper that also grew in this century, but turned inward',
    'rather than to the state, see <a href="montaigne.geocities.ws">Montaigne</a>.</p>',
    '<hr>',
    '<p><small>You are visitor 00530 · lecture-notes page, under construction · best',
    'viewed at 800x600 · last updated 30 Nov</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Montaigne: the personal fan shrine -------------------------------------

const MONTAIGNE = P('montaigne.geocities.ws', 'MONTAIGNE',
  'Montaigne // Que sais-je? (a shrine)', [
    '<!--bg:earlymodern-->',
    '<h1>MY FRIEND MONTAIGNE</h1>',
    '<p><small>a shrine to the man who taught me to doubt kindly. this whole page is',
    'first person because he wrote first person and it would be rude to do',
    'otherwise. — kept by a reader who keeps coming back. best in Netscape,',
    '800x600.</small></p>',
    '<hr>',
    '<p>I did not choose Montaigne, he ambushed me. I picked up the <i>Essais</i>',
    'expecting essays in the school sense, arguments with a thesis, and found',
    'instead a man talking to himself on the page about anything at all, his',
    'kidney stones, his cat, the books he loved, whether we can know a single',
    'thing for certain, and doing it so honestly that four hundred years fell away.',
    'Michel de Montaigne (1533–1592) is the friend you did not know was waiting in',
    'the library.</p>',
    '<p>He was a nobleman near Bordeaux, a magistrate who grew sick of the courts,',
    'and in 1571, not yet forty, he retired to a round tower on his estate, lined',
    'the top room with a thousand books, had sentences he loved carved into the',
    'beams, and set out to write himself. He called the pieces <i>essais</i>,',
    'attempts, trials, weighings. The word for the whole genre of the essay comes',
    'from him, and he meant it modestly: not conclusions, only attempts.</p>',
    '<div class="fs-pull"><p>I am myself the matter of my book.</p></div>',
    '<p><b>Que sais-je?</b> Here is the line I have more or less built a life',
    'around. Faced with the endless clash of opinions, the philosophers who cannot',
    'agree, the customs that are holy on one side of a river and monstrous on the',
    'other, Montaigne does not despair and does not dogmatise. He asks a question',
    'and has it struck on a medal: <i>Que sais-je?</i> What do I know? Not "I know',
    'nothing", which would be its own certainty, but a genuine, open, restless',
    'question, held up against every claim including his own.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/montaigne-01.jpg" alt=""><span class="indie-cap">Montaigne (public domain)</span>',
    '<p>This is the sceptical turn, and it is gentle where the ancient sceptics',
    'were fierce. He read Sextus Empiricus and Seneca and Plutarch, and the longest',
    'essay, the <i>Apology for Raymond Sebond</i>, is where he lets the doubt run',
    'furthest, arguing that our senses deceive, our reason wanders, and even the',
    'beasts may judge as well as we do. But the point is never to win. The point is',
    'to loosen our grip on the certainties that make us cruel to one another.</p>',
    '<blockquote class="fs-quote"><p>Every man carries the entire form of the human',
    'condition.</p><p>— Montaigne, "Of Repentance"</p></blockquote>',
    '<p><b>Why I keep coming back.</b> Because he turned himself into the subject',
    'without a scrap of vanity, and in doing so found that the way to write about',
    'everyone is to write honestly about one person. He watches his own mind change',
    'from paragraph to paragraph and does not tidy it. He is afraid of death and',
    'says so, then talks himself round, then is afraid again. There is more real',
    'company in him than in whole shelves of grander books.</p>',
    '<div class="fs-aside"><p><b>Two doors from here.</b> For the political realism',
    'of the same century, the other side of the coin, see',
    '<a href="machiavelli.geocities.ws">Machiavelli</a>. And the young',
    '<a href="descartes.geocities.ws">Descartes</a> read Montaigne’s doubt and',
    'was not content to leave it open; he went looking for one thing that could not',
    'be doubted. Montaigne asked the question and lived in it; Descartes tried to',
    'answer it. I know which one I would rather have dinner with.</p></div>',
    '<hr>',
    '<p><small>You are visitor 00457 · shrine still under construction, more',
    'favourite passages to come · best viewed in Netscape at 800x600 · last updated',
    '14 Jul · signed, a friend of the tower</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

export const PHIL_C = [MAIMONIDES, AQUINAS, DUNS_SCOTUS, OCKHAM, MACHIAVELLI, MONTAIGNE];
