// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH SPRT_B — boxing.
//
// Six fan pages kept on a free host by ringside obsessives: a full shrine to
// Ali, a round-by-round retelling of the second Schmeling fight, a profile of
// Sugar Ray, a serious account of Jack Johnson, a stats page for Marciano's
// 49-0, and an idea-page on the heavyweight title itself. The fighters, dates
// and records are real; the enthusiasm and the "greatest ever" quarrels belong
// to the fans who typed them.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Muhammad Ali: the shrine (SHOWPIECE) -----------------------------------

const ALI = P('muhammad-ali.geocities.ws', 'THE GREATEST',
  'MUHAMMAD ALI // The Greatest of All Time', [
    '<!--bg:sport-boxing-->',
    '<h1>MUHAMMAD ALI &mdash; THE GREATEST</h1>',
    '<p><small>a shrine to the greatest heavyweight who ever laced them on, kept by',
    'a fan who sat up for the satellite fights when the rest of the street was',
    'asleep. i have watched the Kinshasa tape more times than i can count. still',
    'get chills. — Ronnie, ringside in spirit</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;Float like a butterfly, sting like a bee. His hands',
    'can&rsquo;t hit what his eyes can&rsquo;t see.&rdquo; — the corner rhyme of',
    'Drew &ldquo;Bundini&rdquo; Brown, carried by Ali, 1964</p>',
    '<p>He was born Cassius Marcellus Clay Jr in Louisville, Kentucky, on 17',
    'January 1942. He took up boxing at twelve, so the story goes, because someone',
    'stole his bicycle and a policeman who ran a gym told him he had better learn',
    'to fight first. He won light-heavyweight gold at the Rome Olympics of 1960,',
    'turned professional, and started telling anyone who would listen that he was',
    'the greatest. The maddening thing, for those who wanted him quiet, was that he',
    'kept proving it.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/ali-01.jpg" alt=""><span class="indie-cap">Muhammad Ali (Ira Rosenberg, Library of Congress, public domain)</span>',
    '<h2>Clay to Ali, and the first Liston upset</h2>',
    '<p>On 25 February 1964 in Miami Beach he challenged Sonny Liston, the most',
    'feared puncher of the age, and the bookmakers made the challenger a hopeless',
    'outsider. Clay danced, peppered Liston with the jab, and would not be caught.',
    'Liston did not answer the bell for the seventh round. The new champion leaned',
    'over the ropes and shouted that he had shaken up the world, and he had. Soon',
    'after he announced that he had joined the Nation of Islam and would be known',
    'as Muhammad Ali. Many in the press refused the name for years. The rematch in',
    'May 1965 ended in the first round with a short right hand so fast that half',
    'the arena missed it and argued about the &ldquo;phantom punch&rdquo; for',
    'decades.</p>',
    '<p class="fs-pull">&ldquo;I am the greatest. I said that even before I knew I',
    'was.&rdquo;</p>',
    '<h2>The refusal, and the exile</h2>',
    '<p>In 1967 Ali refused induction into the United States Army, citing his',
    'faith and his opposition to the war in Vietnam. He was stripped of his title,',
    'his licence to box was withdrawn in every state, and his passport was taken.',
    'He did not fight for three and a half years, the very years a heavyweight is',
    'usually at his peak, and he stood to go to prison. The conviction was',
    'eventually overturned by the Supreme Court in 1971. He had given up his',
    'championship rather than his conscience, and a great many people who had',
    'wanted him silenced came round to him because of it.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I ain&rsquo;t got no quarrel with them',
    'Viet Cong.&rdquo;</p><p><small>— attributed to Ali, 1966</small></p></blockquote>',
    '<h2>The Rumble in the Jungle, 1974</h2>',
    '<p>He came back in 1970, lost a fierce decision to Joe Frazier in the',
    '&ldquo;Fight of the Century&rdquo; at Madison Square Garden in March 1971,',
    'the first defeat of his professional life, and set about earning another',
    'title shot. It came in Kinshasa, in what was then Zaire, on 30 October 1974,',
    'against George Foreman, who had demolished Frazier and was thought unbeatable.',
    'Ali leaned back on the loose ropes and let Foreman punch himself arm-weary, a',
    'tactic he later called the rope-a-dope, then knocked him out in the eighth.',
    'He had regained the championship ten years after he first won it.</p>',
    '<div class="fs-aside"><p><b>Did you know?</b> The Kinshasa bout began at four',
    'in the morning local time so that it could be shown live in American prime',
    'time. A tropical downpour a few days earlier had nearly postponed the whole',
    'promotion.</p></div>',
    '<h2>The Thrilla in Manila, 1975</h2>',
    '<p>The third and last meeting with Frazier, in the Philippines on 1 October',
    '1975, was the most brutal of the three and by common consent one of the',
    'hardest fights ever made. Ali won when Frazier&rsquo;s corner would not let',
    'him come out for the fifteenth. Ali said afterwards that it was the closest',
    'thing to dying that he knew. He fought on too long, as champions do, lost the',
    'title to Leon Spinks and won it back in 1978 to become the first man to hold',
    'the heavyweight championship three times.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/boxing-gloves-01.jpg" alt=""><span class="indie-cap">Boxing gloves (photo: Andman8, CC BY 2.5)</span>',
    '<h2>The record and the great nights</h2>',
    '<pre>',
    'MUHAMMAD ALI  (b. 17 Jan 1942, Louisville, KY)',
    'Professional record ........ 56 wins (37 KO), 5 losses',
    'Olympic gold ............... light-heavyweight, Rome 1960',
    'World heavyweight champion . 1964-67, 1974-78, 1978-79',
    '',
    'THE NIGHTS THAT MADE HIM',
    '  25 Feb 1964  Miami Beach ... bt Sonny Liston (RTD 7)     won title',
    '  25 May 1965  Lewiston ...... bt Sonny Liston (KO 1)      the phantom punch',
    '   8 Mar 1971  New York ...... lost to Joe Frazier (UD)    first defeat',
    '  30 Oct 1974  Kinshasa ...... bt George Foreman (KO 8)    Rumble in the Jungle',
    '   1 Oct 1975  Quezon City ... bt Joe Frazier (RTD 14)     Thrilla in Manila',
    '  15 Sep 1978  New Orleans ... bt Leon Spinks (UD)         title a third time',
    '</pre>',
    '<p>He carried the Olympic flame at Atlanta in 1996, his hands trembling with',
    'the Parkinson&rsquo;s that his years in the ring had helped bring on, and the',
    'stadium came to its feet. He died on 3 June 2016. He called himself The',
    'Greatest for fifty years, and the argument he started is one that boxing has',
    'never really wanted to settle.</p>',
    '<p>Read on: the prize he chased is set out at',
    '<a href="the-heavyweight-title.geocities.ws">the-heavyweight-title</a>, and',
    'the champion he most admired, the Brown Bomber, is at',
    '<a href="joe-louis.geocities.ws">joe-louis</a>.</p>',
    '<hr>',
    '<p><small>hit counter: 08842 · best viewed in Netscape Navigator at 800x600 ·',
    'this shrine is under eternal construction · last updated 14 Oct</small></p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
  ]);

// ---- Joe Louis: the second Schmeling fight retold ---------------------------

const LOUIS = P('joe-louis.geocities.ws', 'BROWN BOMBER',
  'JOE LOUIS v SCHMELING // the night of 22 June 1938', [
    '<!--bg:sport-boxing-->',
    '<h1>THE NIGHT OF 22 JUNE 1938</h1>',
    '<p><small>a retelling of the second Louis&ndash;Schmeling fight, put together',
    'from the radio scripts and the old ring reports by a club statistician who',
    'thinks it the most important two minutes in the history of the sport. —',
    'W. Harris, hon. sec.</small></p>',
    '<hr>',
    '<p>Joseph Louis Barrow was born in Alabama in 1914 and grew up in Detroit.',
    'They called him the Brown Bomber. He held the world heavyweight championship',
    'from 1937 to 1949, the longest reign the division has known, and he made',
    'twenty-five successful defences, a figure no heavyweight has approached since.',
    'He was calm, economical and terribly hard, a man who wasted no motion and let',
    'his fists do the arguing.</p>',
    '<p>But before the reign there was a wound. On 19 June 1936, before he was',
    'champion, Louis met the German Max Schmeling and was knocked out in the',
    'twelfth round, the first defeat of his career. Schmeling had studied the film',
    'and spotted that Louis dropped his left after the jab. He punished that fault',
    'all night. It was the only thing standing between Louis and the sense that he',
    'was unbeatable.</p>',
    '<div class="fs-aside"><p><b>Did you know?</b> Louis won the title in between the',
    'two Schmeling fights, stopping James J. Braddock in Chicago on 22 June 1937.',
    'He said he would not consider himself champion until he had settled the',
    'Schmeling account.</p></div>',
    '<p>By the rematch the fight had been loaded with a weight no sportsman should',
    'have to carry. Nazi Germany had made Schmeling, against his own wishes in',
    'much of the telling, a symbol of a master race, and Louis had become the hope',
    'of everyone the regime despised. Seventy thousand packed the Yankee Stadium',
    'on 22 June 1938 and tens of millions more crowded around wireless sets on',
    'three continents.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/joe-louis-01.jpg" alt=""><span class="indie-cap">Joe Louis (Carl Van Vechten, public domain)</span>',
    '<p>It lasted two minutes and four seconds. Louis came out without a flicker of',
    'the caution of two years before, drove Schmeling onto the ropes with a right',
    'to the body that reporters said made the German cry out, and put him down',
    'three times. The towel came fluttering in. One round. The account was',
    'settled.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;There is no such thing as a natural',
    'boxer. A natural dancer has to practise hard. A natural painter has to paint',
    'all the time. Even a natural fool has to work at it.&rdquo;</p>',
    '<p><small>— Joe Louis</small></p></blockquote>',
    '<p>When the United States entered the war Louis enlisted in the Army and spent',
    'the war years boxing exhibitions for the troops and giving purses to relief',
    'funds. He came out a poorer man for it and a more admired one. He and',
    'Schmeling became friends in later life, and Schmeling quietly helped pay for',
    'his funeral in 1981. The fight had been made to mean everything; the two men',
    'in it turned out to be smaller than the flags and larger than them at once.</p>',
    '<p>Read on: the fighter many rank the finest of all, pound for pound, is at',
    '<a href="sugar-ray-robinson.geocities.ws">sugar-ray-robinson</a>, and the man',
    'who called Louis his hero is at',
    '<a href="muhammad-ali.geocities.ws">muhammad-ali</a>.</p>',
    '<hr>',
    '<p><small>visitors: 03310 · best viewed at 800x600 · a fans&rsquo; webring page ·',
    'last updated 2 Sep</small></p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
  ]);

// ---- Sugar Ray Robinson: the profile ----------------------------------------

const ROBINSON = P('sugar-ray-robinson.geocities.ws', 'POUND FOR POUND',
  'SUGAR RAY ROBINSON // pound for pound', [
    '<!--bg:sport-boxing-->',
    '<h1>SUGAR RAY ROBINSON</h1>',
    '<p><small>a profile of the man the phrase &ldquo;pound for pound&rdquo; was',
    'coined to describe, kept by a schoolteacher who boxed a little and worships a',
    'lot. — D. Okafor</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;pound for pound, the greatest.&rdquo; — the sportswriters&rsquo;',
    'verdict, and the origin of the phrase itself</p>',
    '<p>He was born Walker Smith Jr in 1921 and boxed under a borrowed amateur card',
    'in the name of Ray Robinson. A newspaperman said he was sweet as sugar, and',
    'the name stuck for the rest of his life. Writers needed a way to say that a',
    'welterweight might be a finer fighter than any heavyweight, and so they',
    'reached for &ldquo;pound for pound&rdquo;, and they reached for it because of',
    'him.</p>',
    '<p>He held the world welterweight championship from 1946, then moved up and',
    'won the middleweight crown, losing and regaining it so often that he ended up',
    'a five-time middleweight champion. He had speed, he had a knockout in either',
    'hand, and he had a grace that made hard work look like dancing. Younger',
    'fighters, Muhammad Ali among them, took the flash and the footwork straight',
    'from him.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/robinson-01.jpg" alt=""><span class="indie-cap">Sugar Ray Robinson (ACME, public domain)</span>',
    '<h2>The LaMotta fights</h2>',
    '<p>His great rival was Jake LaMotta, the Bronx Bull, a middleweight who could',
    'take any amount of punishment and keep coming. The two met six times across',
    'the 1940s and into 1951, and Robinson won five of them. The last, in Chicago',
    'on 14 February 1951, was so one-sided in its closing rounds that the press',
    'named it the St Valentine&rsquo;s Day Massacre. LaMotta, battered and refusing',
    'to fall, was still on his feet when the referee stopped it in the thirteenth,',
    'and always said with pride that Robinson never put him down.</p>',
    '<p class="fs-pull">Six fights, five to Sugar Ray, and LaMotta never off his feet.</p>',
    '<p>The career ran long, past six hundred rounds and well beyond two hundred',
    'bouts. The record book credits him with something close to 174 wins. He tried',
    'his hand at show business, spent his money freely, came back to the ring when',
    'it ran out, and kept fighting into his forties. He died in 1989. Ask a room',
    'of trainers who the best fighter of all was and a great many of them, without',
    'a moment&rsquo;s hesitation, will say his name.</p>',
    '<p>Read on: the man who broke the colour bar at the top of the sport is at',
    '<a href="jack-johnson.geocities.ws">jack-johnson</a>, and the champion of the',
    'dark decade before him is at <a href="joe-louis.geocities.ws">joe-louis</a>.</p>',
    '<hr>',
    '<p><small>counter: 02154 · best viewed at 800x600 · member of a fans&rsquo;',
    'webring · last updated 30 Jul</small></p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
  ]);

// ---- Jack Johnson: the serious profile ---------------------------------------

const JOHNSON = P('jack-johnson.geocities.ws', 'FIRST CHAMPION',
  'JACK JOHNSON // the first Black world heavyweight champion', [
    '<!--bg:sport-boxing-->',
    '<h1>JACK JOHNSON</h1>',
    '<p><small>a page kept with care for John Arthur Johnson, the first Black man to',
    'hold the world heavyweight championship, because the record ought to be set',
    'down plainly and often. — the compiler</small></p>',
    '<hr>',
    '<p>John Arthur Johnson was born in Galveston, Texas, on 31 March 1878, the son',
    'of former slaves. He learned to fight in the rough travelling shows of the',
    'American South, where a Black boxer was expected to entertain white crowds and',
    'to know his place. Johnson refused the second part. He was quick, defensively',
    'brilliant, and he smiled while he worked, which infuriated opponents and',
    'crowds who wanted him humble.</p>',
    '<p>For years the reigning champions drew what was then called the colour line',
    'and would not meet him. He chased the champion Tommy Burns halfway around the',
    'world and finally cornered him for a match in Sydney, Australia, on 26',
    'December 1908. Johnson won when the police stopped the fight in the fourteenth',
    'round. He was the first Black world heavyweight champion, and the sporting',
    'establishment set about trying to take the title back.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/jack-johnson-01.jpg" alt=""><span class="indie-cap">Jack Johnson (Bain News Service, public domain)</span>',
    '<h2>The &ldquo;Great White Hope&rdquo;</h2>',
    '<p>A search began for a white man who could beat him, and the phrase',
    '&ldquo;Great White Hope&rdquo; entered the language. The former champion James',
    'J. Jeffries was coaxed out of six years&rsquo; retirement to, in his own',
    'words, remind the public that a white man was the better. They met in Reno,',
    'Nevada, on 4 July 1910. Johnson dominated from the first bell and stopped',
    'Jeffries in the fifteenth. The result set off riots across the United States,',
    'many of them attacks on Black citizens celebrating in the streets, and the',
    'films of the fight were banned in many places lest they be seen.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I have found no better way of avoiding',
    'race prejudice than to act with people as though it did not exist.&rdquo;</p>',
    '<p><small>— attributed to Jack Johnson</small></p></blockquote>',
    '<h2>The Mann Act</h2>',
    '<p>What the ring could not do to Johnson, the law was turned to instead. He',
    'lived openly with, and married, white women at a time when much of America',
    'treated that as a provocation. In 1913 he was convicted under the Mann Act, a',
    'statute meant to stop the trafficking of women across state lines for immoral',
    'purposes, on charges that were plainly a pretext for punishing his private',
    'life. Rather than serve the sentence he fled the country and spent seven years',
    'in exile in Europe and Mexico. He lost the title to Jess Willard under a',
    'blazing sun in Havana in 1915, in the twenty-sixth round. He returned to the',
    'United States in 1920, gave himself up, and served his time in the federal',
    'penitentiary at Leavenworth.</p>',
    '<div class="fs-aside"><p><b>The record set straight.</b> In 2018, more than',
    'seventy years after his death, Jack Johnson was granted a posthumous',
    'presidential pardon. The conviction had never been anything but an injustice,',
    'and it took the better part of a century for the state to say so.</p></div>',
    '<p>He died in a car crash in North Carolina in 1946, reportedly driving hard',
    'after being refused service at a diner. He had been champion of the world and',
    'was still not served a meal. The defiance that scandalised his own age reads',
    'now as courage, and the fighters who came after him, Joe Louis and Muhammad',
    'Ali among them, walked through a door that Jack Johnson had forced open at a',
    'terrible cost to himself.</p>',
    '<p>Read on: the only heavyweight champion to retire undefeated is at',
    '<a href="rocky-marciano.geocities.ws">rocky-marciano</a>, and the fighter',
    'called pound for pound the best of all is at',
    '<a href="sugar-ray-robinson.geocities.ws">sugar-ray-robinson</a>.</p>',
    '<hr>',
    '<p><small>visitors: 04021 · best viewed at 800x600 · kept as a matter of record ·',
    'last updated 19 Aug</small></p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
  ]);

// ---- Rocky Marciano: the records-and-stats page ------------------------------

const MARCIANO = P('rocky-marciano.geocities.ws', 'FORTY-NINE AND OH',
  'ROCKY MARCIANO // 49-0 // the numbers', [
    '<!--bg:sport-boxing-->',
    '<h1>ROCKY MARCIANO &mdash; 49-0</h1>',
    '<p><small>the numbers page for the only heavyweight champion who quit the game',
    'without a single defeat on his sheet. all figures checked twice against the',
    'record books. — the tallyman</small></p>',
    '<hr>',
    '<p>Rocco Francis Marchegiano was born in Brockton, Massachusetts, on 1',
    'September 1923, the son of Italian immigrants. He came late to boxing, was',
    'short and light for a heavyweight, had a limited reach and, by his own',
    'admission, no great science. What he had was a granite chin, tireless',
    'conditioning and a right hand he called the Suzie Q that ended fights on its',
    'own. They called him the Brockton Blockbuster.</p>',
    '<pre>',
    'ROCKY MARCIANO  (b. 1 Sep 1923, Brockton, MA)',
    'Bouts ........... 49',
    'Wins ............ 49   (100%)',
    'Wins by KO ...... 43   (88% of all bouts)',
    'Losses .......... 0',
    'Draws ........... 0',
    'World heavyweight champion .. 1952-1956',
    'Title defences .. 6',
    '</pre>',
    '<p>He won the title on 23 September 1952, knocking out the veteran Jersey Joe',
    'Walcott in the thirteenth round in Philadelphia after being floored himself',
    'in the first. It was the Suzie Q that did it, a single right hand that',
    'photographers caught landing flush. He was behind on the cards when he threw',
    'it. He did not need the cards.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/marciano-01.jpg" alt=""><span class="indie-cap">Rocky Marciano (LA Daily News, public domain)</span>',
    '<p>The six defences read as a roll-call of the era&rsquo;s best:</p>',
    '<pre>',
    'THE TITLE DEFENCES',
    '  1953  Jersey Joe Walcott ... KO  1   (the rematch)',
    '  1953  Roland LaStarza ...... KO 11',
    '  1954  Ezzard Charles ....... W  15   (the toughest night)',
    '  1954  Ezzard Charles ....... KO  8   (the rematch)',
    '  1955  Don Cockell (GB) ..... KO  9',
    '  1955  Archie Moore ......... KO  9   (his last fight)',
    '</pre>',
    '<div class="fs-aside"><p><b>Did you know?</b> The first Charles fight in 1954',
    'is the only one of Marciano&rsquo;s forty-nine bouts to go the full distance',
    'and be decided on points. Charles opened a fearful cut on Marciano&rsquo;s',
    'nose; the champion won on all three cards and stopped Charles inside the',
    'distance in the return.</p></div>',
    '<p>He retired in April 1956, at thirty-two, while still champion and still',
    'unbeaten, which no heavyweight champion had done before and none has done',
    'since. He was killed in a light-aircraft crash in Iowa on 31 August 1969, the',
    'night before his forty-sixth birthday. The zero on the end of the record is',
    'the thing every heavyweight since has been measured against.</p>',
    '<p>Read on: the story of the prize he never lost is at',
    '<a href="the-heavyweight-title.geocities.ws">the-heavyweight-title</a>, and',
    'the champion who first broke the colour bar is at',
    '<a href="jack-johnson.geocities.ws">jack-johnson</a>.</p>',
    '<hr>',
    '<p><small>counter: 04900 · best viewed at 800x600 · a proud member of a boxing',
    'fans&rsquo; webring · last updated 6 Sep</small></p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
  ]);

// ---- The heavyweight title: the idea page ------------------------------------

const TITLE = P('the-heavyweight-title.geocities.ws', 'THE CHAMP',
  'THE HEAVYWEIGHT TITLE // the most storied prize in sport', [
    '<!--bg:sport-boxing-->',
    '<h1>THE HEAVYWEIGHT TITLE</h1>',
    '<p><small>an appreciation of the richest and oldest prize in the fight game,',
    'compiled by a supporter who has argued the lineage in a hundred pub corners',
    'and lost none of them. — the ring historian</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;the champion of the world&rdquo; — a phrase that in',
    'boxing has never needed a sport named after it</p>',
    '<p>To be the heavyweight champion of the world is to hold the single most',
    'storied title in sport. For a century it meant, in the popular mind, the',
    'toughest man alive, and the men who held it, the ones who did it well, became',
    'figures far larger than their sport.</p>',
    '<h2>From Sullivan on</h2>',
    '<p>The modern lineage is usually traced to John L. Sullivan, the Boston Strong',
    'Boy, the last champion of the bare-knuckle era and the first of the gloved one.',
    'Sullivan lost in 1892 to James J. Corbett in a contest fought under the',
    'Marquess of Queensberry rules, with padded gloves and timed rounds, and that',
    'match is often taken as the start of the championship as we know it. The line',
    'runs on from there through the whole history of the sport.</p>',
    '<pre>',
    'A LINE OF CHAMPIONS (a selection, not the whole roll)',
    '  1882  John L. Sullivan ...... last of the bare-knuckle kings',
    '  1892  James J. Corbett ...... first under Queensberry gloves',
    '  1908  Jack Johnson .......... first Black world champion',
    '  1919  Jack Dempsey .......... the Manassa Mauler',
    '  1937  Joe Louis ............. the longest reign, 25 defences',
    '  1952  Rocky Marciano ........ retired 49-0, undefeated',
    '  1964  Muhammad Ali .......... champion in three separate decades',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/sport/boxing-gloves-01.jpg" alt=""><span class="indie-cap">Boxing gloves (photo: Andman8, CC BY 2.5)</span>',
    '<h2>The belts and the bodies</h2>',
    '<p>For most of its history there was one champion, recognised by acclamation',
    'and by having beaten the last man to hold the honour. That simplicity did not',
    'survive the age of the sanctioning bodies. Today several organisations, the',
    'WBA, the WBC, the IBF and the WBO among them, each award their own belt, and a',
    'fighter who holds all of them at once is called undisputed. The purists still',
    'speak of the lineal champion, the man who beat the man, on the old principle',
    'that a title passes only in the ring.</p>',
    '<div class="fs-aside"><p><b>Did you know?</b> The green-and-gold belt of the',
    'World Boxing Council and the older idea of the &ldquo;lineal&rdquo; title',
    'often disagree about who the real champion is, which is why fight fans can',
    'argue the point for an entire evening and reach no verdict at all.</p></div>',
    '<p>What has not changed is what the word means to a crowd. When the announcer',
    'draws out the phrase and calls a man the heavyweight champion of the world, he',
    'is naming the oldest continuous prize in the sport, and the room still leans',
    'in to hear it.</p>',
    '<p>Read on: the man who held it in three decades is at',
    '<a href="muhammad-ali.geocities.ws">muhammad-ali</a>, and the one who walked',
    'away from it unbeaten is at',
    '<a href="rocky-marciano.geocities.ws">rocky-marciano</a>.</p>',
    '<hr>',
    '<p><small>counter: 05567 · best viewed in Netscape at 800x600 · under',
    'construction, more champions to be added · last updated 11 Nov</small></p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
  ]);

export const SPRT_B = [ALI, LOUIS, ROBINSON, JOHNSON, MARCIANO, TITLE];
