// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — the overlooked women (painters, 1700–1990).
//
// Six cached pages made by the people who loved these painters and could not
// believe the canon kept mislaying them: a dealer showing Vigee Le Brun; a
// museum wall for Paula Modersohn-Becker; a fan shrine to Hilma af Klint; a
// student's summary of Leonora Carrington; a coursework page on Remedios Varo;
// and a private collector on Alice Neel. Titles, dates, media and where the
// work now hangs are real; the enthusiasms and the grudges are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Vigee Le Brun: the gallery showpiece -----------------------------------

const VIGEE = P('vigee-le-brun.geocities.ws', 'VIGEE LE BRUN',
  'ELISABETH VIGEE LE BRUN // painter to a queen', [
    '<!--bg:art-women-->',
    '<h1>ELISABETH LOUISE VIGEE LE BRUN</h1>',
    '<p><small>from the rooms of the Rue Cadran gallery, where we deal in the',
    'eighteenth century and have hung this room for the painter we love best. all',
    'works below are shown for study; enquiries by letter. — R. Coudray, dealer</small></p>',
    '<p class="fs-epi"><i>I painted the Queen, and I painted her often, and I would',
    'do it again.</i><br>— from her <i>Souvenirs</i></p>',
    '<hr>',
    '<p>Elisabeth Louise Vigee Le Brun (1755&ndash;1842) was the finest portraitist',
    'of her age and, for a while, the most sought-after painter in Europe. She was',
    'trained in her father&rsquo;s studio, was earning her own living with the brush',
    'as a girl, and by her twenties was painting the court. In 1778 she was called',
    'to Versailles to paint Marie Antoinette, and the two women, near enough the',
    'same age, took to one another. She would paint the Queen more than twenty',
    'times.</p>',
    '<img class="indie-pic" src="assets/media/web/art/vigee-le-brun-01.jpg" alt=""><span class="indie-cap">Vigee Le Brun, Self-portrait in a Straw Hat (public domain)</span>',
    '<p>Her portraits are warm where the age was often cold. She let her sitters',
    'smile, she softened the hair out of the powdered helmet and let it fall, and',
    'in her own self-portraits she looked out at the viewer with a plain and',
    'friendly directness that was thought a little forward at the time. In 1783 she',
    'was admitted to the Academie royale, over the usual objections, on the King&rsquo;s',
    'own insistence.</p>',
    '<p class="fs-quote"><blockquote>&ldquo;The women reigned then; the Revolution',
    'dethroned them.&rdquo;<br>— Vigee Le Brun, <i>Souvenirs</i></blockquote></p>',
    '<p>When the Revolution came in 1789 her closeness to the Queen made Paris',
    'dangerous. On the night the royal family was taken to Paris she fled with her',
    'young daughter Julie, over the border in a public coach, and did not see',
    'France again for twelve years. Exile did not stop her working. She painted her',
    'way across Italy, then Vienna, then six years at the court of Catherine the',
    'Great and her successor in Saint Petersburg, keeping her hand and her fame the',
    'whole way. She came home at last in 1802.</p>',
    '<p class="fs-aside"><b>A note on her surfaces.</b> Look at how she paints skin.',
    'She built the flesh in thin warm glazes over a smooth ground, so the light',
    'seems to come from just under the surface rather than off the top of it. She',
    'wrote in the <i>Souvenirs</i> that she liked to add a touch of rouge and a',
    'gauze scarf, and to keep her sitters talking so the face would stay alive. It',
    'is why her portraits breathe where a stiffer painter&rsquo;s would only pose.</p>',
    '<p>She left, in the end, something near six hundred and sixty portraits and',
    'some two hundred landscapes, and two volumes of memoirs that are still the best',
    'company you can find on the vanished world she outlived. A woman who kept her',
    'independence, her earnings and her good humour through a revolution that took',
    'the heads of half her sitters.</p>',
    '<img class="indie-pic" src="assets/media/web/art/modersohn-becker-01.jpg" alt=""><span class="indie-cap">Paula Modersohn-Becker, self-portrait (public domain)</span>',
    '<p class="fs-pull"><b>She was elected to four separate academies across Europe',
    'while in exile, a foreigner and a woman, on the strength of the work alone.</b></p>',
    '<pre>',
    'A FEW OF THE PORTRAITS IN THIS ROOM (wall-label copies)',
    '-------------------------------------------------------',
    'Self-Portrait in a Straw Hat      c.1782   oil    National Gallery, London',
    'Marie Antoinette with a Rose      1783     oil    Palace of Versailles',
    'Marie Antoinette and Her Children 1787     oil    Palace of Versailles',
    'Self-Portrait with Her Daughter   1786     oil    Musee du Louvre, Paris',
    'Countess Golovina                 c.1797   oil    Barber Institute, Birmingham',
    'Madame Perregaux                  1789     oil    Wallace Collection, London',
    '</pre>',
    '<hr>',
    '<p>For company across the centuries we point you two ways in this ring. To',
    '<a href="paula-modersohn-becker.geocities.ws">Paula Modersohn-Becker</a>, who',
    'a hundred years later turned the self-portrait inward and painted herself as no',
    'woman had dared; and to <a href="alice-neel.geocities.ws">Alice Neel</a> in New',
    'York, another portraitist who made her sitters sit and made them true.</p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
    '<p><small>counter: 03106 · best viewed at 800x600 · this room is always being',
    're-hung, pardon the dust · last updated 14 Mar · R. Coudray, Rue Cadran</small></p>',
  ]);

// ---- Paula Modersohn-Becker: the museum wall --------------------------------

const PAULA = P('paula-modersohn-becker.geocities.ws', 'MODERSOHN-BECKER',
  'Paula Modersohn-Becker // the wall label (2 images)', [
    '<!--bg:art-women-->',
    '<h1>Paula Modersohn-Becker</h1>',
    '<p><small>a set of wall labels transcribed from the retrospective, kept here',
    'for students who could not travel to see the show in person. all details as',
    'printed on the gallery walls.</small></p>',
    '<hr>',
    '<p>Paula Modersohn-Becker (1876&ndash;1907) stands at the very front of German',
    'modern painting, earlier than almost anyone thinks. She worked at Worpswede,',
    'the artists&rsquo; colony on the moors near Bremen, and grew restless with its',
    'gentle landscape mood. Four times she went to Paris, saw Cezanne and Gauguin',
    'and the ancient Egyptian portraits in the Louvre, and brought back a way of',
    'painting the figure that was simpler, heavier and more still than anything',
    'around her.</p>',
    '<pre>',
    'WALL LABEL 1',
    '------------',
    'Self-Portrait on the Sixth Wedding Anniversary',
    '1906   oil and tempera on board',
    'Paula Modersohn-Becker Museum, Bremen',
    '</pre>',
    '<p>The label calls it, plainly, the first known nude self-portrait by a woman.',
    'She shows herself half-length and bare above a white cloth, hands folded below',
    'a rounded belly, appearing pregnant though she was not yet, looking out with a',
    'calm that has nothing to prove. No one had painted themselves like this before.</p>',
    '<img class="indie-pic" src="assets/media/web/art/modersohn-becker-01.jpg" alt=""><span class="indie-cap">Paula Modersohn-Becker, self-portrait (public domain)</span>',
    '<p>Her still lifes and her paintings of peasant mothers with their children',
    'have the same weight. A bowl, a child, a woman&rsquo;s own body, all given the',
    'gravity of the old Egyptian art she loved, all built in warm earths and thick',
    'quiet paint.</p>',
    '<pre>',
    'WALL LABEL 2',
    '------------',
    'Self-Portrait with Amber Necklace',
    '1906   oil on canvas',
    'Kunstmuseum Basel',
    '</pre>',
    '<p class="fs-aside"><b>On the board she painted.</b> Much of her best work is on',
    'inexpensive board rather than canvas, worked in a mix of oil and tempera. It let',
    'her keep the surface matt and mural-like, closer to fresco than to the glossy',
    'salon finish, and it suited the flattened, monumental figures she was after. The',
    'poverty of the support and the grandeur of the image sit together on purpose.</p>',
    '<img class="indie-pic" src="assets/media/web/art/hilma-af-klint-01.jpg" alt=""><span class="indie-cap">Hilma af Klint, The Ten Largest No. 2 (public domain)</span>',
    '<p>She married the Worpswede painter Otto Modersohn and kept the company of the',
    'young Rainer Maria Rilke and the sculptor Clara Westhoff. In November 1907, some',
    'eighteen days after giving birth to her daughter Mathilde, she died of an',
    'embolism. She was thirty-one. She had sold almost nothing in her life and left',
    'behind more than seven hundred paintings, and a self-portrait that the twentieth',
    'century took decades to catch up with.</p>',
    '<p>Rilke wrote her a long grieving <i>Requiem</i> the year after she died. It is',
    'the poem you should read next to the paintings.</p>',
    '<hr>',
    '<p>In this ring, walk on to <a href="hilma-af-klint.geocities.ws">Hilma af',
    'Klint</a>, another northern woman working years ahead of the men who got the',
    'credit; or back to <a href="vigee-le-brun.geocities.ws">Vigee Le Brun</a> and',
    'the older art of the self-portrait she inherited and overturned.</p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
    '<p><small>visitors: 01488 · best viewed at 800x600 · labels transcribed by hand,',
    'errors are mine not the museum&rsquo;s · page last tended 8 Feb</small></p>',
  ]);

// ---- Hilma af Klint: the fan shrine -----------------------------------------

const HILMA = P('hilma-af-klint.geocities.ws', 'HILMA AF KLINT',
  'HILMA AF KLINT * she got there first *', [
    '<!--bg:art-women-->',
    '<h1>* HILMA AF KLINT *</h1>',
    '<p><small>a shrine, and i mean SHRINE, to the woman who painted the first',
    'abstract pictures and then hid them in a cupboard so the rest of you could',
    'take the credit for another eighty years. i am STILL cross about it. — Tove</small></p>',
    '<hr>',
    '<p>Here is the fact they keep leaving out of the books. Hilma af Klint',
    '(1862&ndash;1944), a Swedish painter, trained and respectable, a member of the',
    'Royal Academy in Stockholm, began painting large abstract canvases in 1906.',
    'That is BEFORE Kandinsky, before Malevich, before Mondrian, before all the men',
    'you were taught invented abstraction. She was first. Say it out loud.</p>',
    '<p>She did not stumble into it. From 1896 she met in secret with four other',
    'women, a group they called De Fem, The Five, holding seances and taking down',
    'what they believed came through. Out of that came the great commission she felt',
    'she had been given: the <b>Paintings for the Temple</b>, around one hundred and',
    'ninety-three works made between 1906 and 1915 for a spiral temple that was never',
    'built.</p>',
    '<img class="indie-pic" src="assets/media/web/art/hilma-af-klint-01.jpg" alt=""><span class="indie-cap">Hilma af Klint, The Ten Largest No. 2 (public domain)</span>',
    '<p>And they are ENORMOUS and they are BEAUTIFUL. The group called The Ten',
    'Largest are each over three metres high, painted flat on the floor, spirals and',
    'shells and flowers and letters and pale sherbet colours, and they are from',
    '1907. Nineteen oh seven!! Look at them and then look at the date and then come',
    'back and tell me who was first.</p>',
    '<blockquote><p>&ldquo;The pictures were painted directly through me, without any',
    'preliminary drawings, and with great force.&rdquo;<br>— Hilma af Klint, from her',
    'notebooks</p></blockquote>',
    '<p>She knew the world was not ready. She wrote in her will that the work was not',
    'to be shown until twenty years after her death. She thought the future would',
    'understand what her own age could not. She left more than a thousand paintings',
    'and some twenty-six thousand pages of notebooks to her nephew.</p>',
    '<p>And then everyone forgot on purpose. The twenty years passed and still',
    'nobody looked properly. It took until the end of the century, and a great',
    'travelling exhibition, before the crowds finally came and the queues went round',
    'the block. Rediscovered, they call it. You cannot rediscover something you never',
    'let yourself see.</p>',
    '<p>go and stand in front of one. that is all i ask. then argue with me.</p>',
    '<hr>',
    '<p>ring neighbours worth your time: <a href="leonora-carrington.geocities.ws">',
    'Leonora Carrington</a>, another one who painted from the hidden and the occult',
    'and did not care what the salon thought; and <a href="paula-modersohn-becker.geocities.ws">',
    'Paula Modersohn-Becker</a>, first at her own frontier and gone too soon.</p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
    '<p>UNDER CONSTRUCTION: a page on De Fem and the notebooks, coming when i can',
    'read enough Swedish.</p>',
    '<p><small>counter: 00762 · best viewed at 800x600 · made with love and spite ·',
    'last updated 21 Apr · — Tove</small></p>',
  ]);

// ---- Leonora Carrington: the academic summary -------------------------------

const CARRINGTON = P('leonora-carrington.geocities.ws', 'CARRINGTON',
  'Leonora Carrington: a short summary', [
    '<!--bg:art-women-->',
    '<h1>Leonora Carrington: a short summary</h1>',
    '<p><small>notes prepared for a reading group on women of Surrealism. kept',
    'brief on purpose; sources at the foot.</small></p>',
    '<hr>',
    '<p>Leonora Carrington (1917&ndash;2011) was an English-born painter and writer',
    'who spent most of her long life in Mexico and became one of the last great',
    'Surrealists. She was born into a wealthy Lancashire family, was expelled from',
    'more than one convent school, and to her family&rsquo;s horror trained as a',
    'painter and then, at nineteen, went to live with Max Ernst. When the war came',
    'and Ernst was interned, she suffered a severe breakdown and was placed in an',
    'asylum in Santander in Spain, an ordeal she later set down without flinching in',
    'the memoir <i>Down Below</i>.</p>',
    '<p>She reached Mexico by way of a marriage of convenience and stayed the rest',
    'of her life. There her painting found its full strange voice. Her canvases are',
    'peopled with hybrid beasts, hooded figures, horses, cooking pots and',
    'many-roomed houses, all handled with the fine deliberate touch of an early',
    'Renaissance panel. The mood is alchemical and folkloric rather than dreamlike in',
    'the loose sense; she read Jung, Celtic myth, the Popol Vuh and the literature of',
    'alchemy, and she meant her symbols.</p>',
    '<img class="indie-pic" src="assets/media/web/art/carrington-01.jpg" alt=""><span class="indie-cap">Leonora Carrington (photo: Iliazd, CC BY-SA 2.0)</span>',
    '<p>Her most read work is the novel <i>The Hearing Trumpet</i>, finished in the',
    'early 1960s though published later, in which a deaf woman of ninety-two is put',
    'into a sinister care home and helps bring about, with great good humour, the',
    'end of the known world. It is funny, visionary and quietly savage about how the',
    'old and the female are treated, and it has never gone out of print for long.</p>',
    '<blockquote><p>&ldquo;I painted for myself. I never believed anyone would',
    'exhibit or buy my work.&rdquo;<br>— Leonora Carrington</p></blockquote>',
    '<p>In Mexico City she formed a deep and lasting friendship with the Spanish',
    'painter Remedios Varo. The two shared a kitchen-table world of recipes,',
    'alchemy, magic and private jokes, and each is the best guide to the other. Late',
    'in life Carrington was honoured across Mexico as a national treasure, and the',
    'wider reappraisal of the women of Surrealism has at last put her where she',
    'belongs, alongside the men and often ahead of them.</p>',
    '<p><b>Sources:</b> Carrington, <i>Down Below</i>; Carrington, <i>The Hearing',
    'Trumpet</i>; Marina Warner&rsquo;s essays; Whitney Chadwick, <i>Women Artists',
    'and the Surrealist Movement</i>.</p>',
    '<hr>',
    '<p>Read on in the ring to <a href="remedios-varo.geocities.ws">Remedios Varo</a>,',
    'her closest friend and fellow exile, and back to <a href="hilma-af-klint.geocities.ws">',
    'Hilma af Klint</a>, an earlier painter of the unseen.</p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
    '<p><small>hits: 00933 · best viewed at 800x600 · reading-group notes, freely',
    'copied · last updated 2 Feb</small></p>',
  ]);

// ---- Remedios Varo: the student coursework ----------------------------------

const VARO = P('remedios-varo.geocities.ws', 'REMEDIOS VARO',
  'REMEDIOS VARO — coursework (ARTH 214)', [
    '<!--bg:art-women-->',
    '<h1>Remedios Varo</h1>',
    '<p><small>ARTH 214: Surrealism Beyond Paris. coursework essay, put up on my',
    'own page because the tutor said it was good and i am proud of it. please do',
    'not copy it, i will know. — greetings from d.f.</small></p>',
    '<hr>',
    '<p>Remedios Varo (1908&ndash;1963) was a Spanish-Mexican painter and one of the',
    'true originals of Surrealism, though she is only now being given her due. She',
    'was born in Angles in Catalonia, trained at the Academia de San Fernando in',
    'Madrid, and fell in with the Surrealists in Paris in the 1930s. When war and',
    'fascism closed Europe she fled, like so many others, to Mexico City, and it was',
    'there, safe at last and in her forties, that she painted the pictures she is',
    'remembered for.</p>',
    '<p>What strikes you first is the CRAFT. Varo painted small, on panel and',
    'masonite, in fine glazes, with the patience of a medieval miniaturist. Nothing',
    'is loose or accidental. Her interiors are meticulous and dreamlike at once:',
    'towers and cells and workshops, spidery machines, women with heart-shaped faces',
    'spinning cloth or coaxing music or growing wings, half science and half magic.</p>',
    '',
    '<p>My two chosen works for this essay:</p>',
    '<p>1. <i>Bordando el Manto Terrestre</i> (Embroidering the Earth&rsquo;s Mantle),',
    '1961. Pale girls in a high tower embroider a cloth that spills from the windows',
    'and becomes the whole world outside, the land and the sea and the houses, all',
    'stitched into being by their captive labour. It is a picture about making the',
    'world and not being allowed to leave the room where you make it.</p>',
    '<p>2. <i>La Creacion de las Aves</i> (Creation of the Birds), 1957. An owl-woman',
    'at a desk draws birds that lift off the page and fly, using light caught through',
    'a lens and pigment fed from a still on the wall. Part alchemist, part engineer,',
    'part artist. It is basically a self-portrait of what she thought painting was.</p>',
    '<blockquote><p>&ldquo;I do not know anything about painting, or life, but I paint',
    'what I see inside.&rdquo;<br>— attributed to Remedios Varo</p></blockquote>',
    '<p>You cannot write about Varo without her best friend Leonora Carrington. In',
    'Mexico City the two of them were inseparable, cooking up recipes that were half',
    'spells, sharing an occult and comic private world that fed straight into the',
    'work of both. Varo died suddenly of a heart attack in 1963, at only',
    'fifty-four, just as Mexico had begun to love her. Her first big show had sold',
    'out on the opening day.</p>',
    '<p><b>Bibliography (as best i can do it):</b><br>',
    'Kaplan, Janet. <i>Unexpected Journeys: The Art and Life of Remedios Varo</i>.',
    '1988ish?<br>',
    'Chadwick, Whitney. <i>Women Artists and the Surrealist Movement</i>. 1985.<br>',
    'gallery handout from the Mexico City retrospective (no date on it, sorry).</p>',
    '<hr>',
    '<p>ring links for marking: <a href="leonora-carrington.geocities.ws">Leonora',
    'Carrington</a>, the friend, and <a href="alice-neel.geocities.ws">Alice Neel</a>,',
    'another woman the art world kept waiting far too long.</p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
    '<p><small>counter: 00415 · best viewed at 800x600 · grade pending, wish me luck ·',
    'last updated 11 May · — d.f.</small></p>',
  ]);

// ---- Alice Neel: the private collector --------------------------------------

const NEEL = P('alice-neel.geocities.ws', 'ALICE NEEL',
  'Alice Neel // from a private collection', [
    '<!--bg:art-women-->',
    '<h1>Alice Neel</h1>',
    '<p><small>notes on the Neels in my own collection, and on the painter herself,',
    'set down for the friends who ask about them when they come to dinner. not for',
    'sale, before you ask.</small></p>',
    '<hr>',
    '<p>Alice Neel (1900&ndash;1984) called herself a collector of souls, and that is',
    'exactly what her portraits are. For most of a long American century she painted',
    'the people around her, lovers, neighbours, labour organisers, art critics,',
    'pregnant women, her own family, the poor of Spanish Harlem where she chose to',
    'live for decades, and she painted them without flattery and without cruelty,',
    'which is much harder than either.</p>',
    '<p>Her line is fast and sure and a little raw. She leaves canvas bare at the',
    'edges, lets a blue outline show through, exaggerates a hand or a stare, and',
    'somehow the sitter is more present for it, not less. She painted the pregnant',
    'nude when almost no one would, and she painted the old and the ill and the',
    'anxious with the same steady, unsparing attention she gave the famous.</p>',
    '<p class="fs-aside"><b>On the two in the hall.</b> Both my Neels are oil on',
    'canvas from the 1960s, and both show her method plainly: a thin turpentine',
    'wash to place the figure, a cobalt-blue drawing line laid straight onto the',
    'weave, and then only as much colour as the face and hands demand, the rest of',
    'the canvas left to breathe. Stand close and you can read the order she worked in.</p>',
    '<img class="indie-pic" src="assets/media/web/art/neel-01.jpg" alt=""><span class="indie-cap">Alice Neel, Mother and Child, 1927 (public domain)</span>',
    '<blockquote><p>&ldquo;Whether I am painting or not, I have this overweening',
    'interest in humanity. Even if I am not working, I am still analysing',
    'people.&rdquo;<br>— Alice Neel</p></blockquote>',
    '<p>The recognition came late and almost too slowly to matter. For decades she',
    'was out of step, a figurative painter of people in the years when abstraction',
    'ruled and a portraitist was thought quaint. She raised her children in hardship',
    'and kept painting through it. Only in the 1970s did the tide turn, with a',
    'retrospective at the Whitney in 1974 and a late, deserved fame. She kept working',
    'to the end, and her last self-portrait, painted naked in a chair at eighty, is',
    'one of the bravest pictures of old age anyone has made.</p>',
    '<p>Her portrait of Andy Warhol from 1970, the shot body scarred and trussed',
    'after he had been shot, eyes closed, is in the Whitney now and is worth the',
    'trip on its own. She saw straight through the silver wig to the frightened',
    'mortal underneath.</p>',
    '<hr>',
    '<p>The ring runs on from here to <a href="vigee-le-brun.geocities.ws">Vigee Le',
    'Brun</a>, a portraitist of two centuries before who also made her sitters',
    'live; and to <a href="remedios-varo.geocities.ws">Remedios Varo</a>, another',
    'woman the museums came round to slowly.</p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
    '<p><small>visitors: 00647 · best viewed at 800x600 · a private collection, shown',
    'for the pleasure of it · last updated 19 Jan</small></p>',
  ]);

export const ART_C = [VIGEE, PAULA, HILMA, CARRINGTON, VARO, NEEL];
