// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH D: aesthetics, music, and the Western-Marxist root.
//
// Fan pages, kept on a free host, each ABOUT a thinker or a book and never in
// the thinker’s own voice. A reading group working through Adorno’s last,
// unfinished book on art; a devotee’s shrine to Adorno the composer and music
// critic, jazz essays and all; a clean academic summary of Lukács and the word
// reification; and a student’s late coursework on Korsch, the other 1923 book.
// The authors, titles and dates are real; the opinions are the fans’.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Adorno, Aesthetic Theory: the reading-group notes ----------------------

const AESTHETIC = P('adorno-aesthetic.geocities.ws', 'AESTHETIC THEORY',
  'AESTHETIC THEORY // reading notes on Adorno’s last book', [
    '<!--bg:messianic-->',
    '<img class="indie-pic" src="assets/media/web/fs/adorno-01.jpg" alt=""><span class="indie-cap">Theodor W. Adorno (photo: Jeremy J. Shapiro, CC BY-SA)</span>',
    '<h1>AESTHETIC THEORY</h1>',
    '<p><small>notes from the Thursday reading group, kept by whoever remembers to',
    'type them up (mostly me). we are going slowly through <i>Aesthetic Theory</i>',
    'because you cannot go fast, the book will not let you. six of us, one pot of',
    'coffee, a lot of arguing. these are the notes, warts and all.</small></p>',
    '<hr>',
    '<p class="fs-epi">“It is self-evident that nothing concerning art is',
    'self-evident any more.” — the first line of the book</p>',
    '<p>That is where Adorno starts, and it is a warning. He wrote',
    '<i>Aesthetic Theory</i> in his last years and it was still unfinished when he',
    'died in 1969; it came out in 1970, edited from the manuscript by Gretel Adorno',
    'and Rolf Tiedemann. There are no chapters really, no tidy staircase of an',
    'argument. It circles. Every paragraph seems to take back half of what the last',
    'one gave you. We found the shape maddening for about three weeks and then',
    'started to see that the shape IS the argument.</p>',
    '<hr>',
    '<h2>The one idea, if you make us pick one</h2>',
    '<p>Art is autonomous, it stands apart from the world of getting and spending,',
    'and BECAUSE it stands apart it can tell the truth about that world. A real',
    'artwork is not a pretty thing and it is not a message. It is a closed object',
    'that will not be useful, and its refusal to be useful is exactly its knowledge',
    'of a false society. He calls this the truth-content of the work. Not what the',
    'artist meant, not the mood it puts you in, but the truth the finished thing',
    'holds without saying.</p>',
    '<blockquote class="fs-quote"><p>“Art is the social antithesis of society.”</p></blockquote>',
    '<p>We spent a whole evening on that sentence. The point, as far as we got: art',
    'does its social work by NOT joining in, by keeping a distance the market would',
    'like to close. The moment art rolls up its sleeves and delivers a slogan it',
    'stops being the thing that could stand against the slogans.</p>',
    '<hr>',
    '<h2>What we argued about: autonomy versus commitment</h2>',
    '<p>This is the fight in the book, and it is a real fight Adorno had. Against',
    'him stand the writers who said art must commit, must take a side, must serve',
    'the struggle plainly. Brecht above all, and behind Brecht the older quarrel',
    'with Lukács, who wanted art to give a realist picture of the whole society.',
    'Adorno says no: committed art flatters the audience into thinking the problem',
    'is understood and half solved, and it borrows the very language of the',
    'administered world it means to attack. Better the difficult, closed, autonomous',
    'work that refuses to be consumed. Half of us think he is right. Half of us',
    'think this is a comfortable position for a man with a piano and a pension. The',
    'group did not settle it. Adorno did not settle it either, which is honestly a',
    'relief.</p>',
    '<div class="fs-aside"><p>Aside, for the record. Someone asked whether Adorno',
    'actually LIKED anything. He did. Beckett, above all, whom this book was going',
    'to be dedicated to; Kafka; the Schoenberg school. His taste was narrow and',
    'ferocious. He did not hand out praise and when he did it counted.</p></div>',
    '<hr>',
    '<h2>The natural-beauty detour, and the promise</h2>',
    '<p>The strangest and best stretch, we thought, is on natural beauty, which the',
    'whole tradition after Hegel had thrown out. Adorno picks it back up. A',
    'landscape that moves you is not just scenery, it is a glimpse of something not',
    'yet ruined, a hint of what reconciliation between people and nature might feel',
    'like. Art carries that same promise, folded up and unpaid. He never lets the',
    'promise come true on the page, because in a false world it cannot. It stays a',
    'promise. That reaching-toward, without arrival, is why this page sits where it',
    'does in the ring, next to the hopeful ones.</p>',
    '<p class="fs-pull">The artwork keeps a promise the world has broken, by',
    'refusing to pretend it has been kept.</p>',
    '<hr>',
    '<h2>Questions we left open</h2>',
    '<p>ONE. If autonomous art is the only honest art, what happens when the museum',
    'and the record label swallow the autonomous work whole and sell it back as a',
    'luxury? Adorno saw that coming; see the culture-industry argument he made with',
    'Horkheimer at <a href="cultureindustry.geocities.ws">cultureindustry</a>. Does',
    'autonomy survive being catalogued?</p>',
    '<p>TWO. Is the difficulty of the difficult work a real defence, or just a wall',
    'that keeps most people out? We could not agree.</p>',
    '<p>THREE. The book is unfinished. How much of the circling is method and how',
    'much is a manuscript he never got to cut? Honest answer: we do not know, and',
    'neither did the editors.</p>',
    '<hr>',
    '<p><b>Where this sits in Adorno</b></p>',
    '<p>Read it after the philosophy, not before. The negative dialectic that says',
    'no synthesis, no reconciliation, is the engine here too; the shrine to that is',
    'at <a href="adorno-negative-dialectics.geocities.ws">adorno-negative-dialectics</a>.',
    'And the deepest worked example of everything in this book is the music writing,',
    'because music was where Adorno actually knew the material from the inside; that',
    'is over at <a href="adorno-music.geocities.ws">adorno-music</a>. Benjamin',
    'stands behind the whole thing, the artwork essay especially, at',
    '<a href="aura.geocities.ws">aura</a>.</p>',
    '<hr>',
    '<p><small>counter: 00512 · best viewed at 800x600 · under construction, chapter',
    'notes still going up as we finish them · last updated 14 Mar</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a reading-group member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Adorno on music: the devotee’s shrine ----------------------------------

const MUSIC = P('adorno-music.geocities.ws', 'ADORNO ON MUSIC',
  'ADORNO ON MUSIC // Schoenberg, and the jazz problem', [
    '<!--bg:messianic-->',
    '<img class="indie-pic" src="assets/media/web/fs/gramophone-01.jpg" alt=""><span class="indie-cap">an Edison phonograph (public domain)</span>',
    '<h1>ADORNO ON MUSIC</h1>',
    '<p><small>a shrine kept by someone who came to Adorno through the SCORES, not',
    'the seminars. i play a bit, badly, and this man taught me to hear differently,',
    'so i forgive him a great deal. not everything. read on. — R.</small></p>',
    '<hr>',
    '<p>People forget that before he was the philosopher he was a MUSICIAN. Theodor',
    'W. Adorno went to Vienna in the 1920s and studied composition with Alban Berg,',
    'and he moved inside the Schoenberg circle, the second Viennese school, the',
    'people who broke tonality open. He composed. He knew the material from the',
    'keyboard and the manuscript paper, not from a lecture, and it shows in every',
    'line he wrote about music. That is why he is worth reading on this even when he',
    'is being impossible.</p>',
    '<hr>',
    '<h2>Philosophy of New Music (1949)</h2>',
    '<p>The central book, and the one to start with. <i>Philosophy of New Music</i>',
    'is built as a face-off between two composers who stand for two paths. Schoenberg',
    'is PROGRESS: the twelve-tone method follows the material where it wants to go,',
    'even into the harsh and the unwelcoming, refusing to soothe. Stravinsky is',
    'RESTORATION: the borrowed old forms, the mask, the ritual, the giving of comfort',
    'the age has not earned. Adorno backs Schoenberg without blinking. The book is',
    'not fair to Stravinsky and it does not try to be. It is a thesis with a villain.</p>',
    '<blockquote class="fs-quote"><p>“The new art is as abstract as social relations',
    'have in truth become.”</p></blockquote>',
    '<p>That is the nerve of it. The difficulty of the new music is not the composer',
    'being awkward for the sake of it. The music has gone abstract and cold because',
    'the society has, and honest music registers the fact instead of papering over',
    'it with a tune you can hum on the way out.</p>',
    '<hr>',
    '<h2>The regression of listening</h2>',
    '<p>His other great theme, and the one that stings, is what he called the',
    'regression of listening. As music becomes a product, the ear gets lazy and',
    'childish; we stop following a piece as an argument that unfolds in time and',
    'start collecting hit moments, the big tune, the drop, the bit for the advert.',
    'We recognise instead of understanding. This is the culture industry heard from',
    'the inside, and it links straight to the argument he and Horkheimer made at',
    '<a href="cultureindustry.geocities.ws">cultureindustry</a>. Marcuse’s',
    'flattened, one-dimensional mind at',
    '<a href="one-dimensional.geocities.ws">one-dimensional</a> is the same patient',
    'seen by a different doctor.</p>',
    '<div class="fs-aside"><p>Fair warning to new readers. Adorno on music will',
    'make you self-conscious about everything you enjoy, for about a year. Push',
    'through it. He is not telling you to stop listening. He is telling you to',
    'listen as if it mattered, because he thought it did.</p></div>',
    '<hr>',
    '<h2>Controversy</h2>',
    '<p>Now the part his admirers have to say out loud instead of hiding. Adorno',
    'wrote a series of essays attacking jazz, from the 1930s onward, and they have',
    'not aged well. Plainly, they are the worst thing he did. He heard jazz as a',
    'standardised commodity, a false rebellion that actually drilled the listener',
    'into obedience, its spontaneity fake and its freedom staged. He wrote this',
    'about a living Black American music he barely knew from the inside, mostly',
    'from what washed up in Europe, and he never revised the view when he could',
    'have learned better. The judgement is wrong on the musicology and it is worse',
    'on everything around the musicology. You can hold on to the man on Schoenberg',
    'and on the regression of listening and still say, without wriggling, that the',
    'jazz essays are a failure, blind where he was usually sharp. Both things are',
    'true. This shrine is not going to pretend otherwise.</p>',
    '<p class="fs-pull">Right about the regression of the ear; badly, lastingly',
    'wrong about the music that was doing the opposite under his nose.</p>',
    '<hr>',
    '<p><b>Why keep the shrine, then</b></p>',
    '<p>Because when Adorno is inside music he actually knows, he hears more than',
    'anyone, and he gives you the equipment to hear it too. The theory of it all,',
    'the truth-content of the autonomous work, is worked out next door at',
    '<a href="adorno-aesthetic.geocities.ws">adorno-aesthetic</a>, and the',
    'philosophy underneath both is at',
    '<a href="adorno-negative-dialectics.geocities.ws">adorno-negative-dialectics</a>.',
    'Start with the music. It is where the whole apparatus was tuned.</p>',
    '<hr>',
    '<p><small>counter: 00337 · best heard on real speakers, viewed at 800x600 ·',
    'this page under slow construction · last updated 22 Feb</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a devotee, with reservations. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Lukács: the clean academic summary -------------------------------------

const LUKACS = P('lukacs-reification.geocities.ws', 'GEORG LUKÁCS',
  'GEORG LUKÁCS // reification, and the 1923 book', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/weimar-01.jpg" alt=""><span class="indie-cap">(photo: Sludge G, CC BY-SA)</span>',
    '<h1>GEORG LUKÁCS</h1>',
    '<p><small>a summary page maintained for a graduate seminar. aim: get the core',
    'claims of <i>History and Class Consciousness</i> straight, with the right',
    'dates, before anyone argues about them. corrections welcome by post.</small></p>',
    '<hr>',
    '<p>Georg Lukács (1885–1971), Hungarian philosopher and critic, is the',
    'grandfather of what later got called Western Marxism. His <i>History and Class',
    'Consciousness</i> (1923) is one of the two founding texts of that tradition,',
    'the other being Korsch’s book of the very same year, over at',
    '<a href="korsch-marxism.geocities.ws">korsch-marxism</a>. The Frankfurt School',
    'used him constantly and kept him at arm’s length, for reasons this page will',
    'get to.</p>',
    '<hr>',
    '<h2>The central concept: reification</h2>',
    '<p>The German is <i>Verdinglichung</i>, thing-ification, the turning of a',
    'relation between people into the semblance of a relation between things. Lukács',
    'takes Marx on the fetishism of commodities and Weber on rationalisation and',
    'welds them into one idea. Under capitalism, he argues, the commodity form is',
    'not one economic fact among others. It is the universal form of the whole',
    'society, and it spreads.</p>',
    '<blockquote class="fs-quote"><p>“The problem of commodities … the central,',
    'structural problem of capitalist society in all its aspects.”</p></blockquote>',
    '<p>His move, the one that mattered for everything after, is that reification',
    'does not stop at the factory gate or the market stall. It gets INTO',
    'consciousness. We come to see the social world as a set of fixed, law-governed',
    'things we can only observe and calculate, never change, because the commodity',
    'form has taught us to. The contemplative attitude of the scientist and the',
    'clerk is reification in the head. That is the claim the later critical',
    'theorists could not do without.</p>',
    '<hr>',
    '<h2>The identical subject-object</h2>',
    '<p>Lukács needed a way out of the frozen world he had just described, and here',
    'is where he is boldest and most disputed. The proletariat, he says, is the',
    'identical subject-object of history. When workers come to know their own',
    'situation, they are not looking at an outside thing; they ARE the commodity',
    '(labour power) looking at itself. So their self-knowledge is at the same time',
    'knowledge of the whole, and potentially the act that changes it. Class',
    'consciousness is the point where the object of history wakes up as its subject.',
    'It is a magnificent argument and, most readers since have felt, too neat by',
    'half.</p>',
    '<div class="fs-aside"><p>Note on the author against himself. Lukács later',
    'disowned much of this book under political pressure, calling it idealist,',
    'over-Hegelian, a deviation. Read the 1967 preface he attached to it and you',
    'watch a man arguing with his younger and more brilliant self. Read the 1923',
    'text first, then the preface, and make up your own mind about who won.</p></div>',
    '<hr>',
    '<h2>A short critical note</h2>',
    '<p>The trouble is the identical subject-object. It asks one class to be the',
    'hinge of all of history, the guaranteed agent that turns theory into',
    'liberation, and the twentieth century did not oblige. Adorno took the concept',
    'of reification and threw away the guarantee, which is a large part of what',
    'negative dialectics is; see',
    '<a href="adorno-negative-dialectics.geocities.ws">adorno-negative-dialectics</a>',
    'if that is your next stop, though it lives in a different corner of the ring.',
    'The concept outlived the philosophy of history that carried it in.</p>',
    '<hr>',
    '<h2>Afterlife</h2>',
    '<p>Reification did not stay buried. Axel Honneth returned to it directly in a',
    '2005 book, rereading it through recognition rather than through the philosophy',
    'of history; his shrine is at',
    '<a href="honneth-recognition.geocities.ws">honneth-recognition</a>. So the word',
    'Lukács coined in 1923 is still in service, doing work he would not entirely',
    'recognise.</p>',
    '<hr>',
    '<p><b>Key works</b></p>',
    '<p><i>History and Class Consciousness</i> (1923); the long central essay is',
    '“Reification and the Consciousness of the Proletariat”. Earlier, before the',
    'Marxism, <i>The Theory of the Novel</i> (1916). The 1967 self-critical preface',
    'travels with the later editions.</p>',
    '<hr>',
    '<p><small>hits: 00648 · best viewed at 800x600 · maintained for seminar use ·',
    'last updated 9 Jan</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a seminar page in the ring. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Korsch: the student’s late coursework ----------------------------------

const KORSCH = P('korsch-marxism.geocities.ws', 'KARL KORSCH',
  'KARL KORSCH // Marxism and Philosophy (coursework)', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/books-01.jpg" alt=""><span class="indie-cap">(photo: Furkan Akkurt, CC BY-SA)</span>',
    '<h1>KARL KORSCH</h1>',
    '<p><small>for HIST-311, Western Marxism, essay 2. handed in late, sorry Dr M.',
    'the library copy went missing so some of this is from my notes. put it online',
    'because a mate asked. — posted 4 Nov</small></p>',
    '<hr>',
    '<p>Everybody who does this module reads Lukács and stops. This essay is about',
    'the OTHER 1923 book, the one that came out the same year and got its author',
    'into just as much trouble: Karl Korsch, <i>Marxism and Philosophy</i>. Korsch',
    '(1886–1961) was a German, a lawyer by training, briefly a minister in a',
    'short-lived left government in Thuringia, and for a while in the early orbit of',
    'the Frankfurt Institut before he drifted out to the edges. Lukács has the',
    'reputation. Korsch has, i think, the sharper single point.</p>',
    '<hr>',
    '<p><b>the one point</b></p>',
    '<p>Korsch attacks the idea that Marxism is a NEUTRAL SCIENCE, a body of correct',
    'results you could learn the way you learn chemistry, sitting outside history',
    'and just describing it. He says that picture is itself unMarxist. Marxism is a',
    'form of consciousness that belongs to a moment and a struggle; theory and',
    'practice are not two separate departments where the professors do one and the',
    'workers do the other. They are one thing, and when you split them you have',
    'already lost what made Marx Marx.</p>',
    '<blockquote class="fs-quote"><p>Marxism and philosophy stand or fall together:',
    'you cannot abolish philosophy without realising it.</p></blockquote>',
    '<p>(that is me summarising his line off Marx, not a direct quote, so dont put',
    'it in speech marks in YOUR essay.) the point is that the “orthodox” Marxists of',
    'the Second International had quietly turned Marx into a neutral social science',
    'and thrown the philosophy out as old Hegel baggage. Korsch says the philosophy',
    'was never baggage. it was the part that knew theory had to become practice or',
    'be nothing.</p>',
    '<hr>',
    '<p><b>why he and Lukács belong together</b></p>',
    '<p>Same year, 1923, same enemy (a Marxism gone stiff and scientistic), same',
    'return to Hegel to loosen it. This is why the histories treat the two books as',
    'the twin start of Western Marxism. Lukács has reification, the big machine of a',
    'concept, over at',
    '<a href="lukacs-reification.geocities.ws">lukacs-reification</a>. Korsch has',
    'the method point, cleaner and with less scaffolding. read them as a pair.</p>',
    '<div class="fs-aside"><p>side note that i could not fit in the essay proper.',
    'both books got officially condemned at the Comintern in 1924, in the same',
    'breath, by name. getting attacked from Moscow was basically the birth',
    'certificate of Western Marxism. Korsch never made his peace with the party the',
    'way Lukács kept trying to; he was expelled and stayed out and got more',
    'heterodox, later hanging around with Brecht.</p></div>',
    '<hr>',
    '<p><b>the Institut connection</b></p>',
    '<p>Korsch was around the Frankfurt Institut in its early years before Horkheimer',
    'gave it its later shape; for what the Institut was and became see',
    '<a href="institut-fur-sozialforschung.geocities.ws">institut-fur-sozialforschung</a>.',
    'he was more of a fellow traveller than an insider, and the more the Institut',
    'moved toward big interdisciplinary research the further out Korsch sat. worth',
    'knowing he was there at the edge though.</p>',
    '<hr>',
    '<p><b>so what</b></p>',
    '<p>Dr M said end on why it matters, so: Korsch’s warning is against turning a',
    'critical theory into a neutral toolkit that describes the world and quietly',
    'gives up on changing it. that warning did not expire in 1923. anytime a',
    'radical idea gets tidied into a method you can teach without any risk to',
    'anybody, Korsch is the person who already told you what happened.</p>',
    '<hr>',
    '<p><b>Bibliography (rough, will fix)</b></p>',
    '<p>Korsch, Karl. <i>Marxism and Philosophy</i>. 1923. (NLB edn, trans. Fred',
    'Halliday, the one the library HAD.)<br>',
    'Korsch, Karl. <i>Karl Marx</i>. 1938.<br>',
    'Lukács, <i>History and Class Consciousness</i>, 1923, obviously.<br>',
    'lecture notes wk 5 &amp; 6.</p>',
    '<hr>',
    '<p><small>counter: 00193 · best viewed at 640x480 · under construction (need to',
    'fix the biblio) · last updated 4 Nov</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a student page in the ring. « prev · random · next »',
    '</small></p>',
  ]);

export const FS_D = [AESTHETIC, MUSIC, LUKACS, KORSCH];
