// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// The label's own paperwork, and the licensing argument around it.
//
// locarecords.com already exists and states that everything went out under
// copyleft. What it never showed was the licence, and the licence is where the
// interesting failure lives: nobody could say what the SOURCE of a song is, and
// the label shipped anyway and wrote down that it did not know.
//
// The free-software pages are here because the label's decision is unreadable
// without them, and because a cached web from this period without the GNU
// Manifesto on it would be missing the document half of it was arguing with.

export const LABEL_SITES = [
  {
    domain: 'locarecords.com/licence',
    name: 'THE LICENCE',
    title: 'Loca Records — the licence, and the question we could not answer',
    body: [
      '<!--bg:locaweb-->',
      '<h1>The licence</h1>',
      '<p><small>What it says, why we chose it, and the part we got wrong.</small></p>',
      '<hr>',
      '<p>Every release on this label is licensed so that you may copy it, perform',
      'it, broadcast it, remix it, sell what you make, and pass it on, provided',
      'that what you make carries the same terms forward.</p>',
      '<p>That last clause is the whole thing. It is not a permission, it is an',
      'obligation, and it is what stops the licence being a gift to whoever is',
      'largest.</p>',
      '<h2>The three we have used</h2>',
      '<pre class="jb-list">',
      '  1999   GNU General Public License',
      '         written for software. we applied it to music because',
      '         there was nothing else and waiting was not a plan',
      '',
      '  2001   Open Audio License (EFF)',
      '         written for this, at last, by people who had been',
      '         asked the same questions we had',
      '',
      '  2003   Creative Commons Attribution-ShareAlike',
      '         the one that stuck, and the one everybody now',
      '         assumes was always there',
      '</pre>',
      '<h2>The question we could not answer</h2>',
      '<p>The GPL turns on the difference between a program and its source code.',
      'You must ship the source, meaning the preferred form for making changes.',
      'That sentence does the entire work of the licence.</p>',
      '<p>So: what is the source code of a song?</p>',
      '<p>We were asked this within a fortnight of the first release and we have',
      'never had a clean answer. The candidates, in the order we argued about',
      'them:</p>',
      '<pre class="jb-list">',
      '  the finished stereo file   too late. you cannot change anything',
      '  the multitrack             warmer. but the parts are already',
      '                             committed and a bounced part is cooked',
      '  the session                machine-specific, needs the same',
      '                             software, dies with the software',
      '  the sequencer patterns     closest to "the preferred form for',
      '                             making changes", and unreadable to',
      '                             anybody without the same box',
      '  the notation               there is none, and there never was',
      '</pre>',
      '<p>We shipped the finished audio and said so, which is the equivalent of',
      'shipping a binary and calling it source, and we knew it at the time.</p>',
      '<h2>Why we did it anyway</h2>',
      '<p>Because the alternative was to wait for a licence that fit, and the',
      'people who wait for the right instrument are still waiting, and the records',
      'went out and were copied and cut up and sold on by other people, which is',
      'what the licence was for.</p>',
      '<p>The purist objection is correct and the purist objection would have',
      'produced nothing.</p>',
      '<hr>',
      '<p><small>Full texts: <a href="gnu.org">gnu.org</a>,',
      '<a href="openaudio.eff.org">openaudio.eff.org</a>,',
      '<a href="creativecommons.org">creativecommons.org</a>. Questions people',
      'actually sent us: <a href="copyleft-faq.geocities.ws">the FAQ</a>.</small></p>',
    ],
  },
  {
    domain: 'copyleft-faq.geocities.ws',
    name: 'COPYLEFT FAQ',
    title: 'Copyleft music — the questions people actually asked',
    body: [
      '<!--bg:grey-->',
      '<h1>Copyleft music: the actual questions</h1>',
      '<p><small>Collected off a mailing list and two labels’ postbags. Not the',
      'questions the licences answer. The ones people ask.</small></p>',
      '<hr>',
      '<p><b>Can I sample it?</b><br>Yes. That is the point. What you make carries',
      'the same licence.</p>',
      '<p><b>Can I sell what I make?</b><br>Yes. Free does not mean unpaid, it',
      'means the terms travel with it. You may charge whatever anybody will pay.</p>',
      '<p><b>Can I put it in an advert?</b><br>Yes, and this is where everybody',
      'stops being pleased. The licence does not have a clause about whether you',
      'approve of the buyer. If you wanted one you wanted a different licence.</p>',
      '<p><b>What about the performing rights society?</b><br>The hard one. If you',
      'are a member, your works are assigned, and you may not be free to license',
      'them like this at all. Several people found this out afterwards. Check',
      'before, not after.</p>',
      '<p><b>What is the source code of a song?</b><br>Nobody knows. See',
      '<a href="locarecords.com/licence">the label’s own admission</a>.</p>',
      '<p><b>Does this mean anybody can claim they wrote it?</b><br>No.',
      'Attribution is required and is the one thing every version of these',
      'licences agrees on.</p>',
      '<p><b>What happens if somebody breaks the terms?</b><br>Realistically:',
      'nothing. Enforcement means a lawyer and a small label does not have one.',
      'The licence works because most people are decent and because being caught',
      'is embarrassing, and anybody who tells you otherwise is selling you',
      'something.</p>',
      '<hr>',
      '<p><small>Compiled by somebody on the list who got tired of typing the',
      'same six replies.</small></p>',
    ],
  },
  {
    domain: 'gnu.org',
    name: 'GNU',
    title: 'The GNU Project',
    body: [
      '<!--bg:black-->',
      '<h1>The GNU Project</h1>',
      '<p><small>GNU’s Not Unix. Announced 1983. Still not finished, on',
      'purpose.</small></p>',
      '<hr>',
      '<p>The plan: write a complete operating system, compatible with Unix,',
      'entirely from free software, so that nobody has to agree to a licence',
      'forbidding them from sharing it with a friend.</p>',
      '<h2>Free as in</h2>',
      '<p>The confusion is in English rather than in the idea. Free speech, not',
      'free beer. Four freedoms, numbered from zero because the man who wrote them',
      'is a programmer:</p>',
      '<pre class="jb-list">',
      '  0   to run the program, for any purpose',
      '  1   to study how it works, and change it.',
      '      access to the source is a precondition',
      '  2   to redistribute copies',
      '  3   to distribute your changed versions',
      '</pre>',
      '<h2>The trick</h2>',
      '<p>Copyleft. Rather than putting the work in the public domain, where',
      'anybody may take it and close it, the licence uses copyright against itself:',
      'you may do all of the above, and anything you distribute that is derived',
      'from it must carry the same permission.</p>',
      '<p>A legal device that turns the mechanism of enclosure into the mechanism',
      'of the commons. Whatever you think of the politics, that is an elegant piece',
      'of work.</p>',
      '<h2>The manifesto</h2>',
      '<p>Written to explain why anybody would do this, and the argument in it is',
      'not primarily economic. It is that a program you may not change is a program',
      'you do not own, and that a community in which people may not help each other',
      'has been made worse in order to be made profitable.</p>',
      '<p>Read it. It is short, it is thirty years old, and it is about a situation',
      'people describe as new.</p>',
      '<hr>',
      '<p><small>Cached 01:12. A record label applied this to music:',
      '<a href="locarecords.com/licence">how that went</a>.</small></p>',
    ],
  },
  {
    domain: 'openaudio.eff.org',
    name: 'OPEN AUDIO LICENSE',
    title: 'The Open Audio License — EFF',
    body: [
      '<!--bg:navy-->',
      '<h1>Open Audio License</h1>',
      '<p><small>Electronic Frontier Foundation. The middle step nobody',
      'remembers.</small></p>',
      '<hr>',
      '<p>Between applying a software licence to music because there was nothing',
      'better, and the arrival of a general set of licences for creative work,',
      'there was this: a licence written specifically for recordings, by lawyers',
      'who had been asked the awkward questions by musicians.</p>',
      '<h2>What it did differently</h2>',
      '<p>It stopped pretending that a recording has source code. Instead of',
      'requiring the preferred form for modification, it grants the right to copy,',
      'perform, and make derived works of what you actually have, and requires',
      'attribution and the same terms onward.</p>',
      '<p>That is a smaller promise than the GPL makes and an honest one. You are',
      'not given the multitrack. You are given permission.</p>',
      '<h2>Why nobody remembers it</h2>',
      '<p>Because Creative Commons arrived shortly after with a family of licences,',
      'a name people could say, and a graphic. Better marketing beat an earlier and',
      'more carefully scoped instrument, which happens constantly and is nobody’s',
      'fault.</p>',
      '<p>Several labels moved across. The recordings released under this remain',
      'under it, so it is still doing its job on a few hundred records in the',
      'world, quietly, with nobody maintaining the page.</p>',
      '<hr>',
      '<p><small>Cached 02:44. Superseded, not revoked. There is a difference and',
      'it matters to anybody holding one of those records.</small></p>',
      '<p><small>What replaced it: <a href="creativecommons.org">Creative Commons</a>.</small></p>',
    ],
  },
  {
    domain: 'creativecommons.org',
    name: 'CREATIVE COMMONS',
    title: 'Creative Commons',
    body: [
      '<!--bg:locaweb-->',
      '<h1>Creative Commons</h1>',
      '<p><small>Some rights reserved.</small></p>',
      '<hr>',
      '<p>A set of licences you can put on anything you have made, in three layers:',
      'the legal text, a plain-English summary anybody can read, and a machine',
      'readable version so that a search engine can find work you are allowed to',
      'use.</p>',
      '<p>That third layer is the innovation and it is the one nobody talks about.',
      'A licence a machine can read turns permission into something searchable.</p>',
      '<h2>The pieces</h2>',
      '<pre class="jb-list">',
      '  BY    credit the author. on everything, always',
      '  SA    share alike. derivatives carry the same terms',
      '  NC    non-commercial only',
      '  ND    no derivatives',
      '</pre>',
      '<p>Combine them and you have the family. BY-SA is the copyleft one and the',
      'one compatible in spirit with what the free software people were doing.</p>',
      '<h2>The argument inside it</h2>',
      '<p>NC is the contested clause and the argument has never settled. It feels',
      'protective and it is a trap: nobody can tell you where commercial begins. A',
      'blog with an advert on it? A charity that charges for a room? A teacher',
      'selling a photocopied handout at cost?</p>',
      '<p>The share-alike people argue you should drop NC entirely and rely on the',
      'obligation to pass the terms on, because that is enforceable and',
      '"commercial" is not. That is the position the copyleft labels took.</p>',
      '<hr>',
      '<p><small>Cached 03:50. There were labels doing this three years before',
      'this site existed and nobody asked them: see',
      '<a href="locarecords.com/licence">one of them</a>.</small></p>',
    ],
  },
  {
    domain: 'codeislaw.geocities.ws',
    name: 'CODE IS LAW',
    title: 'Code is law — notes',
    body: [
      '<!--bg:parch-->',
      '<h1>Code is law</h1>',
      '<p><small>Notes on Lessig, for a reading group that spent two evenings',
      'arguing about the title alone.</small></p>',
      '<hr>',
      '<p>The claim is not that code should be law or that programmers are',
      'legislators. It is that in a built environment, the architecture regulates',
      'you as effectively as a statute does, and more quietly.</p>',
      '<h2>The four</h2>',
      '<pre class="jb-list">',
      '  law           says do not, and punishes you after',
      '  norms         other people look at you',
      '  the market    price puts it out of reach',
      '  architecture  it simply cannot be done',
      '</pre>',
      '<p>All four regulate. Only the first is voted on. And the fourth is the',
      'strongest, because there is no moment of decision in which you might have',
      'chosen otherwise: a door that does not open is not a rule you broke.</p>',
      '<h2>Why this landed when it did</h2>',
      '<p>Because the early web was described everywhere as a place beyond',
      'regulation, and the argument here is that this is exactly backwards. A',
      'space made entirely of code is the most regulable space ever built, because',
      'its architecture can be changed by whoever owns it, overnight, without',
      'telling you, and the change is not experienced as a rule at all.</p>',
      '<p>The group’s objection, which I record because it is good: this makes',
      'everything architecture and therefore explains nothing in particular. My',
      'answer was that it explains why you cannot appeal.</p>',
      '<hr>',
      '<p><small>See also <a href="gnu.org">the licences</a>, which are an attempt',
      'to use law to hold architecture open.</small></p>',
    ],
  },
  {
    domain: 'napsterpanic.geocities.ws',
    name: 'THE PANIC',
    title: 'Watching the majors panic, from a very small label',
    body: [
      '<!--bg:grey-->',
      '<h1>The panic, from down here</h1>',
      '<p><small>Written by somebody who puts out four hundred records at a time',
      'and has been reading the trade press with a straight face.</small></p>',
      '<hr>',
      '<p>Everybody is copying everything and the industry has decided the answer',
      'is lawyers.</p>',
      '<p>I want to record the view from a label that has nothing to lose, because',
      'in twenty years the only accounts of this will be by people who had',
      'something to lose.</p>',
      '<h2>What it looks like from here</h2>',
      '<p>Our records are already licensed so you may copy them. So the thing that',
      'is presented as an existential threat is, for us, the distribution we could',
      'never afford. Somebody in a country we have never shipped to has our record.',
      'Good.</p>',
      '<p>We were never going to sell them a copy. There is no lost sale. The lost',
      'sale is an accounting entry invented by people who assume every copy',
      'displaces a purchase, and the arithmetic only works if you believe everybody',
      'has infinite money.</p>',
      '<h2>Where I think they are right</h2>',
      '<p>Not about the copying. About the middle. What is actually being destroyed',
      'is the shop, the distributor and the rep, and those are people with jobs who',
      'have done nothing wrong, and the labels suing students are not going to save',
      'any of them, and nothing else will either.</p>',
      '<p>I have a distributor. He is decent, he is owed money by everybody, and I',
      'do not know what he does next. That is the part of this nobody is writing',
      'about because it does not fit either side’s press release.</p>',
      '<hr>',
      '<p><small>See <a href="shellshock-distribution.co.uk">how the middle',
      'worked</a> while it worked.</small></p>',
      '<p><small>What people did before any of it: <a href="tapesfortrade.geocities.ws">tapes for trade</a>.</small></p>',
    ],
  },
  {
    domain: 'shellshock-distribution.co.uk',
    name: 'DISTRIBUTION',
    title: 'How a record actually got into a shop',
    body: [
      '<!--bg:grey-->',
      '<h1>How a record got into a shop</h1>',
      '<p><small>Independent distribution, explained by somebody who did it for',
      'eleven years and is now doing something else.</small></p>',
      '<hr>',
      '<p>You have five hundred records in your hall. Between them and a shop in',
      'Leeds there is an entire trade that nobody outside it has ever heard of.</p>',
      '<h2>The chain</h2>',
      '<pre class="jb-list">',
      '  label        makes it. has no vehicle and no phone list',
      '  distributor  warehouses it, carries it in a catalogue,',
      '               sells it to shops, and gets paid last',
      '  rep          drives to the shops with a boot full of',
      '               samples and an opinion',
      '  shop         takes some. on sale or return',
      '</pre>',
      '<h2>Sale or return</h2>',
      '<p>The clause that decides everything. The shop does not buy your record. It',
      'takes it, and if it does not sell, it sends it back, and you are paid for',
      'nothing and you have handled it three times.</p>',
      '<p>Which means a distributor’s real product is judgement about how many a',
      'shop can actually shift, and a good one will take fewer than you want them',
      'to, and is doing you a favour that will not feel like one.</p>',
      '<h2>The money</h2>',
      '<p>Sixty days if you are lucky, ninety if you are not, from the date the',
      'shop settles, which is itself sixty days from a sale. So a record that sells',
      'in March may be paid for in August, and the pressing plant wanted paying in',
      'January.</p>',
      '<p>Every small label that died in this period died of that gap and not of',
      'anybody’s taste.</p>',
      '<hr>',
      '<p><small>See <a href="pressingplant.co.uk">the other end of the same',
      'problem</a> and <a href="napsterpanic.geocities.ws">what happened',
      'next</a>.</small></p>',
    ],
  },
  {
    domain: 'pressingplant.co.uk',
    name: 'PRESSING PLANT',
    title: 'Vinyl pressing — order form and notes',
    body: [
      '<!--bg:parch-->',
      '<h1>Vinyl pressing</h1>',
      '<p><small>Order form, lead times, and the things people get wrong on their',
      'first record.</small></p>',
      '<hr>',
      '<pre class="jb-list">',
      '  ORDER FORM                          minimum   lead time',
      '',
      '  7" black, plain sleeve                 500      5 weeks',
      '  7" black, printed sleeve               500      6 weeks',
      '  7" coloured vinyl                      500      7 weeks',
      '  12" black, printed sleeve              500      6 weeks',
      '  LP, printed inner and outer            500      8 weeks',
      '',
      '  lacquer cutting                per side      included',
      '  test pressings                 5 copies      included',
      '  centre labels                  2 colours     included',
      '  extra colours                  each          + £45',
      '  metalwork storage              per year      £30',
      '</pre>',
      '<h2>The order of operations</h2>',
      '<p>Your tape is cut to a lacquer. The lacquer is plated to make a metal',
      'master, from which come mothers, from which come stampers, and the stampers',
      'are what actually presses the record. Every one of those is a generation and',
      'every generation is a chance to lose something.</p>',
      '<p>This is why the minimum is five hundred. The cost is nearly all in',
      'getting to the stampers. Once you are there, records are cheap. Below about',
      'that number you are paying setup and nothing else.</p>',
      '<h2>Test pressings</h2>',
      '<p>Play them. All five, both sides, on a system you know. People sign off',
      'test pressings without listening because they are excited and in a hurry,',
      'and then five hundred copies of a fault arrive in a van.</p>',
      '<h2>Things that go wrong</h2>',
      '<pre class="jb-list">',
      '  too long a side     level has to come down. it will sound thin',
      '                      and you will blame us',
      '  heavy bass out of   the needle will jump. we will tell you.',
      '  phase               please listen when we do',
      '  off-centre hole     ours. we will re-press. it happens',
      '  warp                the van, the weather, or your hall',
      '</pre>',
      '<h2>The one nobody expects</h2>',
      '<p>Loud and long are the same problem. A groove that swings wider needs more',
      'room, so a twenty-two minute side cannot be as loud as a fifteen minute one.',
      'It is physics and not an opinion, and every first-time customer argues about',
      'it, and we have never once won that argument before the test pressing and',
      'never once lost it afterwards.</p>',
      '<hr>',
      '<p><small>Lathe cuts are a different trade and we do not do them. See the',
      '<a href="ward.fanpages.org.uk">page about VAN 64</a>, which explains it',
      'properly.</small></p>',
      '<p><small>The rest of the paperwork, and the arithmetic: <a href="howtorunalabel.geocities.ws">how to run a label</a>. A review of one of them: <a href="overloadmedia.co.uk">Overload</a>.</small></p>',
    ],
  },
  {
    domain: 'howtorunalabel.geocities.ws',
    name: 'HOW TO RUN A LABEL',
    title: 'How to run a label, and lose money doing it',
    body: [
      '<!--bg:grey-->',
      '<h1>How to run a label</h1>',
      '<p><small>Everything I wish somebody had told me. You will do it',
      'anyway.</small></p>',
      '<hr>',
      '<h2>What it actually is</h2>',
      '<p>Not taste. Admin. You will spend one evening a month on music and every',
      'other evening on envelopes, invoices, forms, and finding out who has not',
      'paid you.</p>',
      '<h2>The list of things nobody mentions</h2>',
      '<pre class="jb-list">',
      '  catalogue number    invent one. any format. be consistent',
      '  barcode             you need one per release to be in a shop.',
      '                      they are bought in blocks and they are dull',
      '  MCPS                mechanical royalties. there is a form.',
      '                      it must be filed BEFORE the pressing',
      '  PRS                 performance. different body, different form',
      '  the P line           (P) year, name. it is not decoration,',
      '                      it is the claim',
      '  ISRC                per track. free. almost nobody bothers and',
      '                      then cannot be paid by radio',
      '</pre>',
      '<h2>The money, honestly</h2>',
      '<pre class="jb-list">',
      '  500 seven inches, printed sleeves        £780',
      '  mastering                                £150',
      '  artwork                                  a favour',
      '  MCPS                                      £60',
      '  promos, 60 copies posted                 £110',
      '  ---------------------------------------------',
      '  out                                     £1100',
      '',
      '  sold through distribution, 340 @ £1.70    £578',
      '  sold direct, 90 @ £3.50                   £315',
      '  ---------------------------------------------',
      '  in                                       £893',
      '</pre>',
      '<p>That is a good outcome. That is a record that did well.</p>',
      '<h2>So why</h2>',
      '<p>Because the alternative is that it does not exist. Somebody has to be',
      'the person who says yes and takes the cheques, and the reason there are so',
      'few records is that being that person is boring.</p>',
      '<hr>',
      '<p><small>Somebody who ran one has said the same thing better:',
      '<a href="homepage.mac.com/mirrordisc/about">Joe’s page</a>.</small></p>',
    ],
  },
  {
    domain: 'kinematic.fanpages.org.uk',
    name: 'KINEMATIC',
    title: 'Kinematic — LOCA001',
    body: [
      '<!--bg:loca-->',
      '<h1>Kinematic</h1>',
      '<p><small>LOCA001. 1999. I bought it not knowing what the sticker on the',
      'back meant.</small></p>',
      '<hr>',
      '<p>The first thing the label put out, and the first record I owned that',
      'came with a licence on it instead of a warning.</p>',
      '<p>Everything else I had ever bought said the same thing on the back: all',
      'rights reserved, unauthorised copying prohibited, a list of the things I was',
      'not allowed to do with the object in my hand. This one said the opposite,',
      'in about the same number of words, and I read it four times on the bus.</p>',
      '<h2>The record</h2>',
      '<p>Electronica, patient, more space in it than was fashionable that year.',
      'Nothing on it is trying to be a single. It rewards being played twice and',
      'that is not a criticism, it is a description of how it is built.</p>',
      '<h2>What I did with the permission</h2>',
      '<p>Nothing, for two years. Then a friend wanted something under a short film',
      'and I remembered that I was allowed, and we used four minutes of it, and I',
      'wrote to the label to say so out of politeness rather than obligation.</p>',
      '<p>They wrote back. That is the whole story and it is why I still have the',
      'record. The permission was real. Somebody had thought about it, put it on a',
      'sleeve, and meant it.</p>',
      '<hr>',
      '<p><small>The label: <a href="locarecords.com">locarecords.com</a>. The',
      'licence: <a href="locarecords.com/licence">what it says</a>.</small></p>',
      '<p><small>The one after it: <a href="mandibles.geocities.ws">LOCA002</a>.</small></p>',
    ],
  },
  {
    domain: 'mandibles.geocities.ws',
    name: 'MANDIBLES EP',
    title: 'The Mandibles EP — LOCA002',
    body: [
      '<!--bg:loca-->',
      '<h1>Mandibles EP</h1>',
      '<p><small>LOCA002, 1999, and a sleeve with two hundred words of legal text',
      'on the back of it.</small></p>',
      '<hr>',
      '<p>Second release. Same terms as the first, and by now somebody at the',
      'label had realised that a licence nobody can read is not a licence anybody',
      'will use.</p>',
      '<p>So the back of this one carries a plain summary above the formal text:',
      'what you may do, in four lines, in English, before the paragraph that a',
      'lawyer would want. Everybody does that now. In 1999 on a record sleeve it',
      'was an oddity worth remarking on and I am remarking on it.</p>',
      '<h2>The music</h2>',
      '<p>Four tracks, harder edged than LOCA001, and the second one is the reason',
      'people looked for this label at all. It has been used by other people since,',
      'legitimately, which is the licence doing exactly what it was for.</p>',
      '<h2>Small collector note</h2>',
      '<p>The first run has the summary set in a lighter weight than the run after',
      'it, because somebody could not read it in a shop and said so. A typographic',
      'correction to a legal notice on a record sleeve. I have both.</p>',
      '<hr>',
      '<p><small>See also <a href="kinematic.fanpages.org.uk">LOCA001</a>.</small></p>',
    ],
  },
  {
    domain: 'tapesfortrade.geocities.ws',
    name: 'TAPES FOR TRADE',
    title: 'Tapes for trade — my list',
    body: [
      '<!--bg:lace-->',
      '<h1>Tapes for trade</h1>',
      '<p><small>Updated when I remember. SAE and a blank, or a tape of your own.',
      'No money, I am not a shop.</small></p>',
      '<hr>',
      '<p>How this works, for anybody new. You write to me. You send a stamped',
      'addressed envelope and a blank C90, or a tape of something I have not got.',
      'I copy the thing you asked for and send it back. Nobody profits and',
      'everybody ends up with more music.</p>',
      '<h2>The etiquette</h2>',
      '<pre class="jb-list">',
      '  label the tape properly. artist, title, date, source',
      '  say what generation it is. 2nd, 3rd, off vinyl, off FM',
      '  do not trade something you were given as a favour',
      '  do not sell any of it. this stops the moment money appears',
      '  send it back within a fortnight or say why',
      '</pre>',
      '<p>The generation rule is the one people ignore and it matters. A fourth',
      'generation cassette off an FM broadcast is a document of a thing having',
      'existed and it is not a recording, and telling somebody otherwise wastes',
      'their postage.</p>',
      '<h2>The J-card</h2>',
      '<p>The bit of card that folds into the case. Done properly on a photocopier,',
      'with the tracklist typed, and the spine actually legible so it can be read',
      'on a shelf. It takes twenty minutes and it is the difference between a tape',
      'somebody keeps and a tape with biro on it.</p>',
      '<hr>',
      '<p><small>Currently after: anything off Loca I have not got, and the',
      'Farringdon set somebody mentioned on the board. See',
      '<a href="loca-tapes.org.uk">loca-tapes.org.uk</a>.</small></p>',
    ],
  },
  {
    domain: 'radio4a.geocities.ws',
    name: 'RADIO 4A',
    title: 'Radio 4A — Brighton pirate radio',
    body: [
      '<!--bg:black-->',
      '<h1>Radio 4A</h1>',
      '<p><small>Somewhere on the FM dial, weekends, when the transmitter was up.</small></p>',
      '<hr>',
      '<p>A pirate station in a town with a hill in the middle of it, which is the',
      'only geography that matters: get the aerial high and you cover Brighton, and',
      'the hill is also how you get found.</p>',
      '<h2>How it worked</h2>',
      '<p>The transmitter and the aerial in one place, on a roof or in a stairwell,',
      'and the studio somewhere else entirely with a link between them. That',
      'separation is the whole operational design. The transmitter is the part that',
      'gets confiscated, so it must be the part with nobody standing next to it and',
      'nothing in it worth having.</p>',
      '<p>The rig was expected to be lost. You built it cheap, you built two, and',
      'the second one was in somebody’s mum’s garage in Portslade.</p>',
      '<h2>What it was for</h2>',
      '<p>Everything the legal stations would not touch, which in this town meant',
      'dance music, and party information, and a phone number that people rang to',
      'find out where things were happening. That last function is why the',
      'authorities cared: it was not the records, it was the address of the',
      'party.</p>',
      '<p>Which puts a station like this in the same paragraph as everything else',
      'that got legislated at in this period. See',
      '<a href="soundsystem.geocities.ws">the sound system page</a> and',
      '<a href="schnews.org.uk">the free sheet</a>.</p>',
      '<hr>',
      '<p><small>Off the air. The aerial was up there for years afterwards and',
      'may still be.</small></p>',
    ],
  },
  {
    domain: 'soundsystem.geocities.ws',
    name: 'THE RIG',
    title: 'The rig — a sound system page',
    body: [
      '<!--bg:black-->',
      '<h1>The rig</h1>',
      '<p><small>What it is made of, what it weighs, and the law that was written',
      'about it by name.</small></p>',
      '<hr>',
      '<h2>What a rig is</h2>',
      '<pre class="jb-list">',
      '  bass bins      the heavy ones. two people each. the reason',
      '                 you need a van and friends',
      '  mid tops       on stands or on the bins',
      '  amps           in a rack, in a flight case, and the rack is',
      '                 the most expensive thing you own',
      '  crossover      splits the signal by frequency to the right',
      '                 amp. get this wrong and you cook a driver',
      '  generator      diesel, borrowed, and the actual limit on',
      '                 how long the night lasts',
      '</pre>',
      '<p>All of it built rather than bought. Plywood, a router, and somebody’s',
      'dad’s workshop. The plans went round on photocopies.</p>',
      '<h2>The law</h2>',
      '<p>Section 63 of the Criminal Justice and Public Order Act 1994 gives a',
      'police officer the power to direct people to leave land where amplified',
      'music is being played at night, and the Act defines the music it means:</p>',
      '<pre class="jb-list">',
      '  "music" includes sounds wholly or predominantly',
      '  characterised by the emission of a succession of',
      '  repetitive beats',
      '</pre>',
      '<p>That is real statute. Parliament wrote a definition of a genre into an',
      'Act of Parliament, and it is still the single strangest sentence in British',
      'law, and everybody who was there can quote it.</p>',
      '<p>Section 61 handles the vehicles, which is how you actually get moved on,',
      'because the rig has to be in something.</p>',
      '<hr>',
      '<p><small>The week by week account of what that Act did is at',
      '<a href="schnews.org.uk">schnews.org.uk</a>. The band whose audience it was',
      'written at: <a href="levellers.fanpages.org.uk">the Levellers</a>.</small></p>',
      '<p><small>Where the party information came from: <a href="radio4a.geocities.ws">Radio 4A</a>.</small></p>',
    ],
  },
  {
    domain: 'zapclub.geocities.ws',
    name: 'THE ZAP',
    title: 'The Zap Club — under the arches',
    body: [
      '<!--bg:loca-->',
      '<h1>The Zap</h1>',
      '<p><small>Kings Road Arches, Brighton. Below the promenade, in the',
      'seafront wall.</small></p>',
      '<hr>',
      '<p>Brick arches under the road, facing the beach, with the sea about forty',
      'feet from the door. Low curved ceilings, so the sound goes round rather than',
      'up, and condensation off the brick by midnight.</p>',
      '<h2>What it was</h2>',
      '<p>Not only a club. Performance, cabaret, comedy, art events, and then club',
      'nights, in the same rooms in the same week, run by people who did not think',
      'those were separate businesses.</p>',
      '<p>Which is why the bill on any given month reads oddly now: a performance',
      'artist, a band nobody has heard of who became enormous, and a club night,',
      'all in seven days.</p>',
      '<h2>The floor</h2>',
      '<p>Sloped, slightly, towards the sea, because it is built into a sea wall',
      'and the sea wall has a job. You noticed it at the end of the night.</p>',
      '<h2>Getting out</h2>',
      '<p>Up the steps onto the prom at two in the morning with the tide in, which',
      'is the specific Brighton experience that people who did not live there do',
      'not have. Everybody stopped at the railing. Everybody.</p>',
      '<hr>',
      '<p><small>See also <a href="northlaine.geocities.ws">the other end of',
      'town</a> and <a href="theheartandhand.geocities.ws">where people went',
      'first</a>.</small></p>',
    ],
  },
  {
    domain: 'overloadmedia.co.uk',
    name: 'OVERLOAD',
    title: 'Overload Media — reviews',
    body: [
      '<!--bg:grey-->',
      '<h1>Overload</h1>',
      '<p><small>Reviews. Irregular. Nobody is paid.</small></p>',
      '<hr>',
      '<h2>meme &amp; tome — <i>Invisible</i></h2>',
      '<p><small>Mirrordisc, md lp 000. Vinyl, 500 copies.</small></p>',
      '<p>Nine tracks and thirty-nine minutes, and it takes about half of that',
      'before you work out what it is doing.</p>',
      '<p>The credits tell you more than most sleeves do. Four of the nine are one',
      'person working alone and the rest are both of them with somebody else in the',
      'room, and the solo ones are longer and end less tidily. You can hear the',
      'difference without being told which is which, and then you check the label',
      'and you were right, which is a rare and slightly unsettling experience.</p>',
      '<p>Best of it: <i>aufheben</i>, which is three minutes twenty, the shortest',
      'thing here, the only one in a language other than English, and the only one',
      'they never put up for download. Make of that what you like.</p>',
      '<p>Worst of it: nothing, but <i>whatever you say</i> has singing on it and',
      'the singing pulls the record towards being a song, and the record is better',
      'when it is not one.</p>',
      '<p><b>Verdict.</b> Buy it from the box number. It will cost you a stamp and',
      'a cheque and the trouble is part of the point.</p>',
      '<hr>',
      '<p><small>The label: <a href="homepage.mac.com/mirrordisc">Mirrordisc',
      'Productions</a>, Brighton. Longer reading of the same record:',
      '<a href="loca-tapes.org.uk">Steve S.</a></small></p>',
    ],
  },
];
