// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH D — decolonisation & independence, the founders of new states.
//
// Pages a history student, a party branch, and a couple of enthusiasts made
// about the leaders who took their countries out of empire and into statehood:
// a long walk fan shrine for Mandela; reading notes on Nehru's prison book;
// an academic crib on Sukarno; a coursework sheet on Ataturk; a write-up of
// Ben-Gurion at the microphone; and a sober summary of de Valera. The dates,
// offices and quotations are real; the darker parts are named where they belong.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Mandela: the long-walk fan shrine (SHOWPIECE) --------------------------

const MANDELA = P('nelson-mandela.geocities.ws', 'MANDELA',
  'THE LONG WALK — a Nelson Mandela shrine', [
    '<!--bg:pol-independence-->',
    '<h1>THE LONG WALK</h1>',
    '<p><small>a shrine to Nelson Rolihlahla Mandela (born 1918), made by a sixth-',
    'form history club that adopted him as our man the year he walked out of prison.',
    'we watched it live in the common room and nobody said anything for a bit. these',
    'pages are ours, corrections welcome. — the club, Leeds</small></p>',
    '<hr>',
    '<p class="fs-epi">"It always seems impossible until it is done."</p>',
    '<p>He trained as a lawyer and in 1952 opened, with Oliver Tambo, the first',
    'black law firm in South Africa. He joined the African National Congress and',
    'helped build its Youth League, and when the National Party brought in apartheid',
    'after 1948 he was in the thick of the campaigns against it: the Defiance',
    'Campaign of 1952, the Freedom Charter of 1955, the treason trial that dragged on',
    'for years and collapsed.</p>',
    '<div class="fs-aside"><b>What apartheid was.</b> A legal system, built from',
    '1948, that sorted every person by race and handed power, land, the vote and the',
    'good jobs to the white minority. Pass laws controlled where black South',
    'Africans could live and work. It was not an accident or a mood; it was written',
    'into statute, and the ANC set out to break it.</div>',
    '<p>After the Sharpeville massacre in 1960, when police shot dead sixty-nine',
    'people at a pass-law protest, the ANC was banned and the road of peaceful',
    'protest was closed. Mandela helped found and lead Umkhonto we Sizwe, "the Spear',
    'of the Nation", the armed wing, and turned to sabotage against state targets.',
    'He was clear about why: fifty years of non-violence had won the movement',
    'nothing but more repression. He went underground, slipped abroad for training,',
    'and was caught in 1962.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/mandela-01.jpg" alt=""><span class="indie-cap">Nelson Mandela (photo: Kingkongphoto, CC BY-SA 2.0)</span>',
    '<h2>The Rivonia Trial</h2>',
    '<p>In 1963 the police raided a farm at Rivonia and rounded up the leadership.',
    'Mandela and his co-accused faced the death penalty for sabotage. From the dock',
    'in 1964 he gave the speech that made his name across the world, four hours of',
    'it, ending on the lines that were read out again and again for the next',
    'twenty-seven years:</p>',
    '<blockquote class="fs-quote"><p>"I have cherished the ideal of a democratic and',
    'free society in which all persons live together in harmony and with equal',
    'opportunities. It is an ideal which I hope to live for and to achieve. But if',
    'needs be, it is an ideal for which I am prepared to die."</p>',
    '<p><small>— Nelson Mandela, statement from the dock, Pretoria, 20 April 1964</small></p></blockquote>',
    '<p>They were spared the rope and given life. Mandela went to Robben Island, the',
    'prison on a rock off Cape Town, to break limestone in a quarry that ruined his',
    'eyes. He was prisoner 466/64. He stayed a prisoner, on the island and later on',
    'the mainland, for twenty-seven years, and the state offered him freedom more',
    'than once if he would renounce the armed struggle. He refused every time.</p>',
    '<pre>',
    '   A LONG WALK, IN DATES',
    '   1918  born in the Transkei',
    '   1944  joins the ANC, helps found the Youth League',
    '   1952  the Defiance Campaign; opens a law firm with Tambo',
    '   1960  Sharpeville; the ANC is banned',
    '   1962  arrested; 1964 sentenced to life at the Rivonia Trial',
    '   1964  Robben Island begins',
    '   1990  released on 11 February; the ANC unbanned',
    '   1993  Nobel Peace Prize, shared with F. W. de Klerk',
    '   1994  elected president in the first free election',
    '</pre>',
    '<p class="fs-pull">On 11 February 1990 he walked out of the gates a free man,',
    'and raised his fist, and the club watched it live and went very quiet.</p>',
    '<p>What came next was harder than a speech. He and F. W. de Klerk, the last',
    'apartheid president, negotiated the end of the system through years of talks',
    'that more than once nearly broke down in violence. They shared the 1993 Nobel',
    'Peace Prize for it. In 1994, in the first election in which every adult could',
    'vote, the ANC won and Mandela became the first black president of South Africa.',
    'He set up the Truth and Reconciliation Commission under Archbishop Desmond Tutu',
    'to face what had been done rather than bury it, and he served ONE term and',
    'stepped down, which for a liberation leader is its own kind of statement.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/nehru-01.jpg" alt=""><span class="indie-cap">Jawaharlal Nehru (photo: Abbie Rowe, public domain)</span>',
    '<div class="fs-aside"><b>Not a saint, and he said so.</b> He always defended the',
    'turn to armed struggle as a last resort forced on the movement, not a first',
    'choice. His long first marriage broke under the years in prison; his second, to',
    'Winnie Madikizela-Mandela, a serious figure in the struggle in her own right,',
    'ended in a bitter separation amid controversy about her later conduct. He asked',
    'to be read as a man who did difficult things, not as a plaster figure.</div>',
    '<p>Read him next to the other founders. Nehru at',
    '<a href="jawaharlal-nehru.geocities.ws">jawaharlal-nehru</a> wrote his best book',
    'in a colonial prison too, and led the other giant of the non-aligned world; and',
    'Ben-Gurion at <a href="david-ben-gurion.geocities.ws">david-ben-gurion</a>',
    'founded a state the same decade, by a very different and far more contested',
    'road. Mahatma Gandhi, who armed nobody, is the shadow behind all of them, and',
    'has no page in our ring yet.</p>',
    '<hr>',
    '<p><small>counter: 04664 · best viewed at 800x600 · under construction, the',
    'presidency section still to come · last updated 18 Jul · ~ the history club, Leeds ~</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Nehru: reading notes on a prison book ----------------------------------

const NEHRU = P('jawaharlal-nehru.geocities.ws', 'NEHRU',
  'READING NOTES: The Discovery of India (Nehru)', [
    '<!--bg:pol-independence-->',
    '<h1>READING NOTES: The Discovery of India</h1>',
    '<p><small>notes kept as i read, on Jawaharlal Nehru (1889–1964) and the book he',
    'wrote in Ahmadnagar Fort prison. i am doing this the slow way, a chapter a week,',
    'and typing up what stuck. not a review, just the notes. — R.</small></p>',
    '<hr>',
    '<p><b>Who he was, before the book.</b> Nehru was Cambridge-educated, a barrister,',
    'the son of a wealthy lawyer, and he gave it up for the Indian National Congress',
    'and the independence movement. Gandhi was his mentor and, in a way, his opposite:',
    'Gandhi the ascetic of the village, Nehru the modern socialist who wanted dams',
    'and steel and science. He went to prison again and again under British rule,',
    'nine times, nearly nine years in all. He came out in 1947 as the first prime',
    'minister of independent India, and held the office until he died in 1964.</p>',
    '<div class="fs-aside"><b>The book itself.</b> <i>The Discovery of India</i> was',
    'written in 1944 while he was locked up in Ahmadnagar Fort, one of the long',
    'wartime imprisonments. It is a whole civilisation seen from a cell: a sweep',
    'through thousands of years of Indian history, written by a man forbidden to take',
    'part in the present, working out what the country he could not walk in actually',
    'was. That is the thing that stays with you, the address of it.</div>',
    '<p><b>Chapter notes, the bits I marked.</b> His famous line is not from the book,',
    'it is the speech at midnight on 14–15 August 1947 when power passed:</p>',
    '<blockquote class="fs-quote"><p>"At the stroke of the midnight hour, when the',
    'world sleeps, India will awake to life and freedom."</p>',
    '<p><small>— Jawaharlal Nehru, "Tryst with Destiny", 14 August 1947</small></p></blockquote>',
    '<p>The freedom came cut in two. Partition split British India into India and',
    'Pakistan, and the migrations and massacres that followed killed hundreds of',
    'thousands and uprooted millions. Nehru wanted a united, secular India and got',
    'independence and division in the same night. The notes do not let you skip that.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/nehru-01.jpg" alt=""><span class="indie-cap">Jawaharlal Nehru (photo: Abbie Rowe, public domain)</span>',
    '<p><b>What he built, the Nehruvian state.</b> At home he set the pattern that',
    'lasted a generation: a secular constitution in a country of many faiths, a',
    'planned mixed economy with the state building the heavy industry, universal',
    'adult suffrage from the start, and a drive for science and technology. He called',
    'the big dams and steel plants and research institutes:</p>',
    '<p class="fs-pull">"the temples of modern India" — the phrase he used at the',
    'opening of the Bhakra-Nangal dam, and it stuck to the whole project.</p>',
    '<p><b>Abroad, non-alignment.</b> This is the part I understood least before and',
    'best now. With the world splitting into an American bloc and a Soviet bloc,',
    'Nehru refused to pick a side and made a virtue and a movement of the refusal.',
    'With Nasser of Egypt and Tito of Yugoslavia he built the Non-Aligned Movement,',
    'a bloc of the newly free countries that would not be anyone\'s client. The idea',
    'ran straight out of the Bandung Conference, which Sukarno hosted; see',
    '<a href="sukarno.geocities.ws">sukarno</a> for that end of it.</p>',
    '<div class="fs-aside"><b>Where the notes turn critical.</b> Non-alignment did',
    'not stop a war. In 1962 the border dispute with China broke into a short, sharp',
    'conflict that India lost badly, and it wounded Nehru and the whole idea that',
    'the new bloc could stand outside power politics. And his socialist planning,',
    'the "licence raj" it grew into, is blamed by many later writers for slow growth.',
    'The book does not answer these; they came after it.</div>',
    '<img class="indie-pic" src="assets/media/web/pol/sukarno-01.jpg" alt=""><span class="indie-cap">Sukarno (public domain)</span>',
    '<p><b>The one to read him next to</b> is Mandela at',
    '<a href="nelson-mandela.geocities.ws">nelson-mandela</a>, another lawyer who',
    'wrote his best pages in a colonial jail and led the other half of the free',
    'world\'s imagination. His daughter Indira Gandhi later held the same office, by',
    'a harder and more divisive road, but that is a different page.</p>',
    '<hr>',
    '<p><small>counter: 01947 · best viewed at 800x600 · notes typed on a borrowed',
    'machine · last updated 22 Aug · still three chapters to go</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Sukarno: the academic crib ---------------------------------------------

const SUKARNO = P('sukarno.geocities.ws', 'SUKARNO',
  'Sukarno and the founding of Indonesia — a summary', [
    '<!--bg:pol-independence-->',
    '<h1>Sukarno (1901–1970)</h1>',
    '<p><small>A summary page maintained for a comparative-politics reading group.',
    'Aim: the founding of Indonesia and the non-aligned world, in brief, with the',
    'main sources at the foot. Additions by email to the group secretary.</small></p>',
    '<hr>',
    '<p>Sukarno was the founding president of the Republic of Indonesia and the',
    'leading figure of its national awakening. Trained as an engineer in Bandung, he',
    'came to politics young, founded the Indonesian National Party in 1927, and spent',
    'years in Dutch prison and internal exile for it. He was a spellbinding orator',
    'who could hold a crowd of hundreds of thousands, and he built his authority on',
    'the voice as much as on the office.</p>',
    '<h2>The Proclamation of 1945</h2>',
    '<p>The turning point came at the close of the Second World War. Japan had',
    'occupied the Dutch East Indies; as it surrendered, and before the Dutch could',
    'return, Sukarno and Mohammad Hatta proclaimed independence on 17 August 1945,',
    'in a text of two spare sentences read out in a Jakarta front garden. What',
    'followed was four years of revolution and war against the returning Dutch, who',
    'did not concede sovereignty until 1949, under heavy international pressure.</p>',
    '<div class="fs-aside"><b>Pancasila.</b> In June 1945 Sukarno set out the "five',
    'principles" meant to hold a vast, plural archipelago together: belief in one',
    'God, a just and civilised humanity, the unity of Indonesia, democracy by',
    'consensus, and social justice. Pancasila remained the official state philosophy',
    'long after him, precisely because it tried to include the religious and the',
    'secular, the many islands and the one nation, in a single frame.</div>',
    '<p>Consider the scale of the founding. Indonesia is thousands of islands,',
    'hundreds of languages, the largest Muslim population in the world alongside',
    'large Christian, Hindu and other communities. To make one nation of it at all',
    'was the achievement, and Pancasila was the instrument.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/sukarno-01.jpg" alt=""><span class="indie-cap">Sukarno (public domain)</span>',
    '<h2>Bandung and non-alignment</h2>',
    '<p>In 1955 Sukarno hosted the Asian-African Conference at Bandung, which',
    'gathered the leaders of twenty-nine newly independent or emerging states and',
    'gave the decolonising world a sense of itself as a third force between the two',
    'Cold War blocs. Bandung fed directly into the Non-Aligned Movement that Nehru,',
    'Nasser and Tito would formalise; the Nehru end of that story is at',
    '<a href="jawaharlal-nehru.geocities.ws">jawaharlal-nehru</a>.</p>',
    '<h2>Guided Democracy, and the fall</h2>',
    '<p>From 1959 Sukarno set aside parliamentary government for what he called',
    '"Guided Democracy", concentrating power in himself and balancing the army',
    'against the very large Indonesian Communist Party. The balancing act ended in',
    'catastrophe. After a murky attempted coup in 1965, the army under Suharto',
    'unleashed anti-communist massacres in which several hundred thousand people were',
    'killed, and pushed Sukarno aside. He was stripped of power by 1967 and died',
    'under house arrest in 1970. The founding orator ended silenced.</p>',
    '<p>For a founder who reshaped his state as thoroughly, though along a secular',
    'and republican line of his own, see Ataturk at',
    '<a href="kemal-ataturk.geocities.ws">kemal-ataturk</a>. Hatta, the co-signatory',
    'of the proclamation, has no page here.</p>',
    '<hr>',
    '<p><small>Selected reading: Legge, <i>Sukarno: A Political Biography</i> (1972);',
    'Kahin, <i>Nationalism and Revolution in Indonesia</i> (1952); the Bandung',
    'communiqué. counter: 00901 · best viewed at 800x600 · reading group, page tended',
    'quarterly · last updated 4 Mar</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Ataturk: the coursework sheet ------------------------------------------

const ATATURK = P('kemal-ataturk.geocities.ws', 'ATATURK',
  'HIST2214 coursework: Ataturk & the Turkish Republic', [
    '<!--bg:pol-independence-->',
    '<h1>Ataturk and the making of modern Turkey</h1>',
    '<p><small>HIST2214 Nations and Nationalism · assessed web project (worth 30%) ·',
    'submitted by student no. 9930471 · "produce a web resource on a C20th nation-',
    'founder." this is mine. please do not mark down for the counter, the brief said',
    'make it look like a real page.</small></p>',
    '<hr>',
    '<p><b>1. Who.</b> Mustafa Kemal (1881–1938), from 1934 called Ataturk, "Father',
    'of the Turks", was the founder and first president of the Republic of Turkey. He',
    'rose as an army officer in the dying Ottoman Empire and made his name in the',
    'First World War at Gallipoli in 1915, where the Ottoman defence held off the',
    'Allied landings.</p>',
    '<p><b>2. The war of independence.</b> After 1918 the Ottoman Empire was defeated',
    'and its territory carved up by the victorious powers under the Treaty of Sevres.',
    'Kemal led a national resistance from Anatolia against the partition and the',
    'occupying and invading forces, above all the Greek army in the west. The',
    'Turkish national movement won, the sultanate was abolished, and a new settlement,',
    'the Treaty of Lausanne of 1923, recognised the borders of a sovereign Turkish',
    'state. The Republic was proclaimed on 29 October 1923 with Kemal as president.</p>',
    '<div class="fs-aside"><b>Note for the marker: the population exchange.</b> The',
    'Lausanne settlement included a compulsory exchange of populations with Greece,',
    'in which roughly 1.5 million Orthodox Christians and around half a million',
    'Muslims were uprooted and moved by treaty. It followed years of war in which',
    'communities on all sides suffered atrocities. A founding is not only speeches;',
    'this belongs in the account.</div>',
    '<p><b>3. The reforms.</b> This is the part the module is really about. Ataturk',
    'drove a top-down transformation, fast and by law, to make Turkey secular and',
    'Western-facing:</p>',
    '<pre>',
    '   THE KEMALIST REFORMS (selected)',
    '   1924  the caliphate abolished; religious courts closed',
    '   1925  the fez banned; the "hat law" and dress reform',
    '   1925  the Western (Gregorian) calendar adopted',
    '   1928  the Arabic script replaced by a new Latin alphabet',
    '   1928  the clause naming Islam the state religion removed',
    '   1930s surnames required by law; Kemal takes "Ataturk"',
    '   1934  votes for women in national elections',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/pol/ataturk-01.jpg" alt=""><span class="indie-cap">Mustafa Kemal Ataturk (public domain)</span>',
    '<p>The alphabet change is the one that stops you. Overnight the written language',
    'was cut from its Ottoman and Arabic past, and Ataturk himself toured with a',
    'blackboard teaching the new letters. It opened literacy to millions and severed',
    'a link to the old learning at the same time; the module wants us to hold both.</p>',
    '<p><b>4. The cult and the criticism.</b> The reforms were imposed, not debated.',
    'Turkey under Ataturk was effectively a one-party state; opposition was',
    'suppressed, and Kurdish revolts were put down hard. A powerful personality cult',
    'grew and long outlived him, protected by law. His own summary of the doctrine',
    'was blunt:</p>',
    '<blockquote class="fs-quote"><p>"Peace at home, peace in the world."</p>',
    '<p><small>— Mustafa Kemal Ataturk, 1931</small></p></blockquote>',
    '<p><b>5. Compare.</b> Set him beside two other founders of new states: Ben-Gurion',
    'at <a href="david-ben-gurion.geocities.ws">david-ben-gurion</a>, and Sukarno at',
    '<a href="sukarno.geocities.ws">sukarno</a>, who tried to hold a plural nation',
    'together by inclusion where Ataturk drove a single secular model from the top.</p>',
    '<hr>',
    '<p><small>Bibliography (as required): Mango, <i>Ataturk</i> (1999); Zurcher,',
    '<i>Turkey: A Modern History</i> (1993); lecture notes wk 6–7; the Nutuk (Kemal\'s',
    'own 1927 Speech), extracts only. hits: 02923 · best viewed at 800x600 · last',
    'updated 30 Nov, the night before the deadline</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Ben-Gurion: the speech write-up ----------------------------------------

const BENGURION = P('david-ben-gurion.geocities.ws', 'BEN-GURION',
  'AT THE MICROPHONE: Ben-Gurion declares a state', [
    '<!--bg:pol-independence-->',
    '<h1>AT THE MICROPHONE, 14 MAY 1948</h1>',
    '<p><small>a write-up of the declaration and the man who read it, David',
    'Ben-Gurion (1886–1973), put together from the recordings and the accounts. i',
    'wanted the scene in the room, not just the dates. — a listener</small></p>',
    '<hr>',
    '<p>Picture the Tel Aviv Museum hall, late on a Friday afternoon, the British',
    'Mandate hours from ending, war already at the door. David Ben-Gurion, short and',
    'white-haired and blunt, stood and read out the Declaration of the Establishment',
    'of the State of Israel. He had been the leader of the Jewish community in',
    'Palestine for years, head of the Jewish Agency, the organiser more than the',
    'orator, and now he read the state into being in a few minutes and banged a',
    'gavel. The recording is thin and crackling and the room sings Hatikvah at the',
    'end.</p>',
    '<blockquote class="fs-quote"><p>"We hereby declare the establishment of a Jewish',
    'state in Eretz-Israel, to be known as the State of Israel."</p>',
    '<p><small>— David Ben-Gurion, reading the Declaration, Tel Aviv, 14 May 1948</small></p></blockquote>',
    '<p>He became the first prime minister and defence minister. Within a day the',
    'new state was at war with the neighbouring Arab states, the war Israelis call',
    'the War of Independence.</p>',
    '<div class="fs-aside"><b>The contested history, stated plainly.</b> The same',
    'events are named differently on the two sides, and both names are true to those',
    'who use them. In the 1948 war and the months around it, well over 700,000',
    'Palestinian Arabs fled or were expelled from their homes and were not allowed',
    'to return; Palestinians call this the Nakba, the catastrophe. The war followed',
    'the United Nations partition plan of 1947, which the Jewish leadership accepted',
    'and the Arab states and Palestinian leadership rejected. A page about the',
    'founding that left this out would not be telling the history.</div>',
    '<p>What he built afterwards was the machinery of a state under siege: he merged',
    'the underground militias into one national army and forced the others to',
    'disband, absorbed a huge wave of Jewish immigration, including refugees from',
    'Europe and from Arab lands, and set the young country\'s institutions. He was',
    'decisive to the point of high-handedness, and he made enemies on his own side',
    'doing it.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/ben-gurion-01.jpg" alt=""><span class="indie-cap">David Ben-Gurion (photo: Fritz Cohen, public domain)</span>',
    '<p><b>The desert, and the retirement.</b> Ben-Gurion had a conviction that the',
    'future of the country lay in the empty south, the Negev, and he meant it',
    'personally. He resigned, returned, and finally in the 1960s and 70s withdrew to',
    'a kibbutz in the desert, Sde Boker, to live the thing he preached. There is a',
    'photograph of the old founder in work clothes among the sheds that did as much',
    'for his legend as any speech.</p>',
    '<p class="fs-pull">He read a state into existence on a Friday afternoon and',
    'spent the rest of his life arguing about what it should become.</p>',
    '<p>Read him next to two other founders on this ring. De Valera at',
    '<a href="eamon-de-valera.geocities.ws">eamon-de-valera</a> also wrote a',
    'constitution for a contested new state; and Mandela at',
    '<a href="nelson-mandela.geocities.ws">nelson-mandela</a> founded a democracy',
    'by trying to reconcile the enemies of the old order rather than to sort them.</p>',
    '<hr>',
    '<p><small>counter: 01948 · best viewed at 800x600 · assembled from the archive',
    'recordings · under construction, sound clip to be added when i can encode it ·',
    'last updated 9 May</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- de Valera: the sober summary -------------------------------------------

const DEVALERA = P('eamon-de-valera.geocities.ws', 'DE VALERA',
  'Eamon de Valera and the Irish state — a summary', [
    '<!--bg:pol-independence-->',
    '<h1>Eamon de Valera (1882–1975)</h1>',
    '<p><small>A summary page for a local history circle. Aim: the long shadow de',
    'Valera cast over Irish politics, set out plainly, the Treaty split included.',
    'Notes and corrections welcome at the usual address.</small></p>',
    '<hr>',
    '<p>Eamon de Valera was the dominant figure in independent Ireland for half a',
    'century, as revolutionary, as head of government, and finally as president. He',
    'was American-born, which more than once kept him alive, and he came to Irish',
    'politics through the language movement and the Irish Volunteers.</p>',
    '<h2>The Easter Rising</h2>',
    '<p>He commanded a battalion in the Easter Rising of 1916, the rebellion in',
    'Dublin against British rule that was crushed in a week. The leaders were',
    'executed by firing squad; de Valera, a battalion commandant, was sentenced to',
    'death but not shot, his American birth and the political cost of more executions',
    'both cited as reasons. He came out of prison a national figure and became',
    'president of Sinn Fein and of the revolutionary Dail.</p>',
    '<div class="fs-aside"><b>The Treaty split.</b> The Anglo-Irish Treaty of 1921',
    'ended the War of Independence but gave not a republic but a Free State inside',
    'the British Empire, with an oath to the Crown and the partition of the north.',
    'De Valera rejected it and led the anti-Treaty side. The disagreement became the',
    'Irish Civil War of 1922–23, fought between former comrades, shorter than the war',
    'against Britain and in some ways more bitter. The anti-Treaty side lost. The',
    'wound ran through Irish politics for generations.</div>',
    '<p>What sets de Valera apart from many who lose a civil war is what he did next.',
    'He did not stay outside the state he had fought. In 1926 he broke from the',
    'irreconcilables and founded a new party, Fianna Fail, took his seat in the Free',
    'State parliament, and in 1932 won power by the ballot and held it, on and off,',
    'for most of the next thirty years.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/de-valera-01.jpg" alt=""><span class="indie-cap">Eamon de Valera (public domain)</span>',
    '<h2>The 1937 Constitution</h2>',
    '<p>His central monument is Bunreacht na hEireann, the Constitution of 1937,',
    'which he largely drafted. It replaced the Free State framework, removed most',
    'traces of the Crown, renamed the state Ireland, and asserted a claim over the',
    'whole island. It gave the Catholic Church a "special position", since removed,',
    'and wrote a conservative social vision, including on the place of women, into',
    'the fundamental law. It remains, much amended, the constitution of Ireland',
    'today.</p>',
    '<pre>',
    '   OFFICES HELD (selected)',
    '   1917       president of Sinn Fein',
    '   1919-22    president of the revolutionary Dail',
    '   1926       founds Fianna Fail',
    '   1932-48    head of government (Taoiseach from 1937)',
    '   1937       the new Constitution enacted',
    '   1951-54, 1957-59   again head of government',
    '   1959-73    president of Ireland',
    '</pre>',
    '<p>In the Second World War his government kept the state neutral, a policy known',
    'in Ireland as the Emergency, and he defended it as the proof and the price of',
    'the sovereignty he had spent his life pursuing. He ended as president, the',
    'ceremonial head of state, into his nineties, nearly blind, the last living',
    'commandant of 1916.</p>',
    '<p>For founders who also wrote constitutions for contested new states, see',
    'Ataturk at <a href="kemal-ataturk.geocities.ws">kemal-ataturk</a> and, at the',
    'other end of the archipelago world, Sukarno at',
    '<a href="sukarno.geocities.ws">sukarno</a>. His great Treaty rival Michael',
    'Collins, killed in the Civil War, has no page in this ring.</p>',
    '<hr>',
    '<p><small>Selected reading: Coogan, <i>De Valera: Long Fellow, Long Shadow</i>',
    '(1993); Ferriter, <i>Judging Dev</i> (2007); the text of Bunreacht na hEireann.',
    'visitors: 01916 · best viewed at 800x600 · local history circle · last updated',
    '2 Feb</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

export const POL_D = [MANDELA, NEHRU, SUKARNO, ATATURK, BENGURION, DEVALERA];
