// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH AA_E — East Asian philosophy (1900–1990).
//
// Cached fan and student pages ABOUT the thinkers, never in their voice. A
// departmental seminar summary of Nishida and the Kyoto School; a devotee's
// shrine to D. T. Suzuki; reading-group minutes on Watsuji's ethics of
// betweenness; book-reading notes on Lu Xun's A Madman's Diary; a student's
// coursework on Feng Youlan; a talk write-up on Kang Youwei. The people,
// titles, dates and books are real; the framing and the enthusiasm are the
// admirers'. Names are given family-name-first where that is the custom, and
// said so on the page.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Nishida Kitaro: the seminar summary (SHOWPIECE) ------------------------

const NISHIDA = P('nishida-kitaro.geocities.ws', 'NISHIDA',
  'NISHIDA KITARO // pure experience & the logic of place', [
    '<!--bg:aa-eastasia-->',
    '<h1>NISHIDA KITARO and the Logic of Place</h1>',
    '<p><small>summary pages kept for the East Asian philosophy reading seminar. we',
    'meet fortnightly and one of us writes up the thinker we read. this term:',
    'Nishida. a note on the name, the Japanese custom is family name first, so it is',
    'Nishida (family) Kitaro (given), and we keep that order here. corrections',
    'welcome. — kept by the seminar</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>&ldquo;To experience means to know facts just as they',
    'are, to know in accordance with facts by completely relinquishing one&rsquo;s',
    'own fabrications.&rdquo;</p><p>&mdash; Nishida Kitaro, <i>An Inquiry into the',
    'Good</i> (1911)</p></div>',
    '<p>Nishida Kitaro (1870&ndash;1945) was the first modern Japanese philosopher',
    'of the front rank, and the founder of what came to be called the Kyoto School.',
    'He taught for most of his life at Kyoto Imperial University. He had trained in',
    'Zen practice as a young man, and he had read the German philosophers closely,',
    'and his whole work is the attempt to think those two inheritances together',
    'without letting either dissolve the other. He did not want a Japanese footnote',
    'to European philosophy, and he did not want a mysticism that refused to argue.',
    'He wanted a philosophy that could hold its ground in the seminar room and still',
    'begin from the place where Zen begins.</p>',
    '<h2>pure experience</h2>',
    '<p>His first book, <i>An Inquiry into the Good</i> (Zen no kenkyu, 1911),',
    'starts from what he calls PURE EXPERIENCE (junsui keiken). The idea is that',
    'before we split the world into a knowing subject over here and a known object',
    'over there, there is simply experience happening. The moment of hearing a',
    'sound, before the thought &ldquo;I am hearing a sound made by something out',
    'there&rdquo;, is one undivided event. Subject and object are not the starting',
    'point, they are a division made afterwards, inside an experience that was whole',
    'first.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Over time, pure experience widens and',
    'deepens, and the distinction of subject and object arises within it, not before',
    'it.&rdquo;</p><p><small>a gloss on the argument of <i>An Inquiry into the',
    'Good</i></small></p></blockquote>',
    '<p>This was a bold place to begin. Most European theories of knowledge take the',
    'gap between subject and object as the given problem. Nishida takes the gap as',
    'something that HAPPENS, a fold inside a prior unity, and asks what that unity',
    'is. The rest of his life is the working out of that question.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/nishida-01.jpg" alt=""><span class="indie-cap">Nishida Kitaro (public domain)</span>',
    '<h2>the logic of basho (place)</h2>',
    '<p>By the middle of the 1920s he had a new tool for it, the LOGIC OF BASHO, of',
    'place. It first appears in the long essay &ldquo;Basho&rdquo; (1926). The move',
    'is to stop asking only WHAT a thing is and to ask WHERE it is, in what field it',
    'stands. Every judgement, &ldquo;S is P&rdquo;, places an individual subject',
    'within a predicate. Push that placing to its limit and you look for the final',
    'field, the place that holds everything and can never itself be turned into an',
    'object placed in some further field. That final place Nishida calls ABSOLUTE',
    'NOTHINGNESS (zettai mu).</p>',
    '<p class="fs-pull">Absolute nothingness is not a blank and not a void of',
    'despair. It is the ground in which every being stands, the place that can hold',
    'and never be held.</p>',
    '<p>The word nothingness misleads a Western reader who expects nihilism.',
    'Nishida&rsquo;s absolute nothingness is closer to the Buddhist mu, the emptiness',
    'that is fullness, the open field in which things come to be at all. It is not a',
    'thing that is missing. It is the placing itself, the ground that gives every',
    'object its room and withdraws behind them.</p>',
    '<pre>',
    'THE LOGIC OF BASHO (place)',
    '--------------------------',
    'the judgement   "S is P"',
    '    the individual (the grammatical subject) is grasped',
    '    by being PLACED within a predicate-field',
    '',
    'three enfolding places',
    '    1. basho of being ............ the field of objects,',
    '                                    the things that are',
    '    2. basho of relative ......... the field of consciousness,',
    '       (oppositional) nothingness  the "I" set over its object',
    '    3. basho of absolute ......... the ground that can never',
    '       nothingness                 itself be made an object;',
    '                                    it holds all and is held',
    '                                    by nothing',
    '',
    'the true self is found not as a subject that has the world',
    'in front of it, but as the PLACE in which subject and',
    'object both arise',
    '</pre>',
    '<div class="fs-aside"><p><b>The Kyoto School.</b> Nishida did not work alone.',
    'Around him and after him gathered the philosophers now called the Kyoto School,',
    'among them Tanabe Hajime and, later, Nishitani Keiji. It was a genuine school,',
    'with a shared vocabulary of nothingness and place. It also carried a shadow.',
    'During the war years some of its members took part in the debates on',
    '&ldquo;overcoming modernity&rdquo; and on Japan&rsquo;s role, and the political',
    'record of the school in those years is still argued over and should be. Reading',
    'Nishida honestly means reading that context too, not around it.</p></div>',
    '<p>His late work turned the logic of place toward the world itself, in the',
    'difficult formula of the SELF-IDENTITY OF ABSOLUTE CONTRADICTORIES (zettai',
    'mujunteki jiko doitsu), the idea that the real is held together precisely as a',
    'unity of what contradicts itself, the one and the many, the made and the',
    'making. He was still revising it when he died in June 1945, a few weeks before',
    'the war ended.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/suzuki-01.jpg" alt=""><span class="indie-cap">D. T. Suzuki (public domain)</span>',
    '<hr>',
    '<p>Two of the seminar&rsquo;s other pages sit close to this one. Nishida&rsquo;s',
    'lifelong friend from Kanazawa, the Zen scholar who carried these questions to',
    'the West, has a shrine at',
    '<a href="dt-suzuki.geocities.ws">dt-suzuki.geocities.ws</a>. And the philosopher',
    'who took the ethics of the person in a direction Nishida did not, toward',
    'betweenness and climate, is written up at',
    '<a href="watsuji-tetsuro.geocities.ws">watsuji-tetsuro.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>counter: 00512 · best viewed at 800x600 · this summary is part of an',
    'ongoing seminar and may be revised · last updated 14 Oct</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp;',
    'Postcolonial Ring</a> ]</small></p>',
  ]);

// ---- D. T. Suzuki: the devotee's shrine -------------------------------------

const SUZUKI = P('dt-suzuki.geocities.ws', 'D.T. SUZUKI',
  'D. T. SUZUKI // the man who carried Zen west', [
    '<!--bg:aa-eastasia-->',
    '<h1>D. T. SUZUKI</h1>',
    '<p><small>a shrine to Daisetz Teitaro Suzuki, put up by someone who found a',
    'battered copy of the Essays in a second-hand shop and never got over it. in the',
    'West he signed himself D. T. Suzuki, in Japan the name runs family-first,',
    'Suzuki Daisetz. either way, the man who opened a door. — kept by a grateful',
    'reader</small></p>',
    '<hr>',
    '<p>Daisetz Teitaro Suzuki (1870&ndash;1966) is very nearly the reason the word',
    'ZEN means anything in English at all. He was born the same year as his lifelong',
    'friend the philosopher Nishida Kitaro, in the same part of Japan, and the two',
    'of them talked and wrote to one another across their whole lives. Where Nishida',
    'built the philosophy, Suzuki became the great translator and interpreter, the',
    'one who carried Zen Buddhism out into the Western world and made it possible for',
    'people who knew no Japanese to begin to hear it.</p>',
    '<p>As a young man he trained in Zen under the master Soyen Shaku, and it was',
    'Soyen Shaku who gave him the Buddhist name Daisetz, which is usually rendered',
    '&ldquo;Great Humility&rdquo;. He spent years in the United States working for',
    'the Open Court publishing house in La Salle, Illinois, learning the trade of',
    'carrying one world&rsquo;s thought into another&rsquo;s language.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/suzuki-01.jpg" alt=""><span class="indie-cap">D. T. Suzuki (public domain)</span>',
    '<h2>the Essays, and satori</h2>',
    '<p>The books that did the work were the <i>Essays in Zen Buddhism</i>, three',
    'series of them (1927, 1933 and 1934), and the earlier <i>Introduction to Zen',
    'Buddhism</i>. In them he tried to convey SATORI, the sudden awakening, the',
    'flash in which the ordinary dualistic mind drops away and things are seen',
    'directly. He was honest that satori cannot really be handed over in a sentence,',
    'that it is not a doctrine to be agreed with but an event to be undergone, and',
    'yet he wrote about it with such patience and such stories from the old masters',
    'that readers felt they had at least been shown the door, even if only they',
    'could walk through it.</p>',
    '<div class="fs-aside"><p><b>His correspondents.</b> Suzuki&rsquo;s reach ran',
    'through some remarkable friendships. The psychologist Carl Jung wrote a foreword',
    'to his <i>Introduction to Zen Buddhism</i>. Late in his long life he exchanged',
    'letters and met with the Trappist monk Thomas Merton, a Christian contemplative',
    'who found in Zen a mirror for his own tradition. Suzuki treated all of it as',
    'conversation, never conquest.</p></div>',
    '<p>He lived to be ninety-five, working almost to the end, and by then he had',
    'become something like a bridge with people walking both ways across it. It is',
    'fair to say he simplified at times, and later scholars have argued that the Zen',
    'he presented was shaped for its Western audience more than he let on. That is a',
    'real debate and worth having. But the debt is real too. A great many readers in',
    'English first met Buddhism through his patient, generous prose.</p>',
    '<hr>',
    '<p>For the philosophy that grew alongside his friendship, see the seminar page',
    'on Nishida at',
    '<a href="nishida-kitaro.geocities.ws">nishida-kitaro.geocities.ws</a>. And for',
    'the Chinese philosopher who tried the same bridging work in the other tradition,',
    'carrying Chinese thought to the West and Western thought home, there is',
    '<a href="feng-youlan.geocities.ws">feng-youlan.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01890 · best viewed at 800x600 · this page under gentle',
    'construction, more of the Essays to come · last updated 2 Nov · sat quietly',
    'before posting · — a grateful reader</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp;',
    'Postcolonial Ring</a> ]</small></p>',
  ]);

// ---- Watsuji Tetsuro: reading-group minutes ---------------------------------

const WATSUJI = P('watsuji-tetsuro.geocities.ws', 'WATSUJI',
  'WATSUJI TETSURO // ningen, betweenness & climate', [
    '<!--bg:aa-eastasia-->',
    '<h1>Reading Group: Watsuji Tetsuro</h1>',
    '<p><small>minutes of the third meeting. present: six of us and a flask of',
    'green tea someone brought. text under discussion: Watsuji&rsquo;s ethics, with',
    'a look at <i>Fudo</i>. family name first, so Watsuji (family) Tetsuro (given).',
    'minutes taken by whoever lost the toss.</small></p>',
    '<hr>',
    '<p><b>Opening.</b> We agreed a one-line placing before we started. Watsuji',
    'Tetsuro (1889&ndash;1960) was a Japanese moral philosopher and historian of',
    'culture whose great argument is that Western ethics has been quietly wrong to',
    'start from the lone individual. His whole ethics starts somewhere else, from the',
    'space BETWEEN people.</p>',
    '<p><b>The word we kept coming back to: ningen.</b> Watsuji builds everything on',
    'the Japanese word for a human being, NINGEN. He points out that the two',
    'characters in it mean, roughly, &ldquo;person&rdquo; and &ldquo;between&rdquo;.',
    'A human being is not first a private self who then, secondly, bumps into other',
    'selves. To be human is already to be between, in relations, in the web of',
    'family and neighbour and stranger. He has a name for that between-ness,',
    'AIDAGARA, the betweenness that we always already stand in. Ethics for Watsuji is',
    'the study of ningen, of the person as betweenness, not the study of a solitary',
    'conscience.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;The individual and the whole are not two',
    'facts to be added together. Each is real only through the other.&rdquo;</p>',
    '<p><small>the group&rsquo;s summary of the argument of the <i>Rinrigaku</i></small></p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/aa/watsuji-01.jpg" alt=""><span class="indie-cap">Watsuji Tetsuro (public domain)</span>',
    '<p><b>Where the argument aims.</b> Someone raised the obvious worry, that this',
    'could dissolve the person into the group and leave no ground to stand on against',
    'a crowd or a state. We thought this was the strongest objection and we did not',
    'settle it. Watsuji insists the movement goes both ways, the individual negating',
    'the whole and the whole negating the individual, neither swallowing the other.',
    'Whether that holds under pressure, especially given the Japan he wrote in, we',
    'left open and want to come back to.</p>',
    '<p><b>Fudo, on climate.</b> We spent the last half hour on <i>Fudo</i> (1935),',
    'usually given in English as <i>Climate and Culture</i>. Watsuji had read',
    'Heidegger and felt that all that emphasis on TIME had left out SPACE, the actual',
    'land and weather a people lives in. Fudo is his word for climate in a broad',
    'sense, the whole lived environment. He argues that a monsoon climate, a desert,',
    'a meadow each grow a different way of being human, a different temper of feeling',
    'and community. We noted the risk here, that this can slide toward crude',
    'national character, and Watsuji does not always avoid it. But the core thought,',
    'that human existence is placed, bodily and geographical and not floating in pure',
    'time, we found genuinely useful.</p>',
    '<p><b>Actions.</b> Next time we read the chapter on the monsoon more slowly.',
    'Someone to bring the objection about the state written up properly.</p>',
    '<hr>',
    '<p>Cross-reading. The philosopher whose logic of place stands behind a lot of',
    'this, and whom Watsuji knew, is at',
    '<a href="nishida-kitaro.geocities.ws">nishida-kitaro.geocities.ws</a>. And for a',
    'writer working the same years in China, turning a cold eye on what a culture',
    'does to the people inside it, the group recommends',
    '<a href="lu-xun.geocities.ws">lu-xun.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>counter: 00343 · best viewed at 800x600 · reading group meets',
    'fortnightly, newcomers welcome · minutes posted 9 Sep</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp;',
    'Postcolonial Ring</a> ]</small></p>',
  ]);

// ---- Lu Xun: book-reading notes on A Madman's Diary -------------------------

const LUXUN = P('lu-xun.geocities.ws', 'LU XUN',
  'LU XUN // reading notes on A Madman’s Diary', [
    '<!--bg:aa-eastasia-->',
    '<h1>Reading Notes: Lu Xun, <i>A Madman&rsquo;s Diary</i></h1>',
    '<p><small>my notes on one story, kept as I read. Lu Xun is a pen name, the',
    'writer&rsquo;s own name was Zhou Shuren; in Chinese the family name comes first.',
    'I am reading the Yang Xianyi and Gladys Yang translation. not a scholar, just a',
    'reader keeping track. — kept by a reader in the north</small></p>',
    '<hr>',
    '<p><b>The writer.</b> Lu Xun (1881&ndash;1936) is usually called the father of',
    'modern Chinese literature, and the phrase is not an exaggeration. He went to',
    'Japan as a young man to study medicine. The famous turning point came in Sendai,',
    'when he saw a lantern slide of Chinese people standing by, dull-faced, while one',
    'of their countrymen was executed. He decided that a nation&rsquo;s sickness of',
    'spirit could not be cured with medicine, and that what was needed was to change',
    'minds. So he abandoned medicine for writing. It is one of the great swerves in',
    'a literary life.</p>',
    '<p><b>The New Culture Movement.</b> He wrote into the ferment of the New Culture',
    'Movement and what became the May Fourth generation, young intellectuals arguing',
    'that the old order, Confucian hierarchy and the classical written language and',
    'all, was strangling the country. Lu Xun&rsquo;s answer was to write in the',
    'living vernacular, the way people actually spoke, and to write without mercy',
    'about what he saw.</p>',
    '<div class="fs-aside"><p><b>Note to self, on the title.</b> The story appeared',
    'in the magazine <i>New Youth</i> (Xin Qingnian) in 1918. It is often called the',
    'first modern short story written in vernacular Chinese. That is a lot of weight',
    'for thirteen short diary entries to carry, and yet it does.</p></div>',
    '<p><b>The story itself.</b> A man keeps a diary. He has become convinced that',
    'the people around him, his neighbours, his own elder brother, are cannibals,',
    'that they mean to eat him. As his notes go on he reads through the old Confucian',
    'histories, the ones full of &ldquo;virtue and morality&rdquo;, and between the',
    'lines, everywhere, he finds two words written over and over: EAT PEOPLE.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/luxun-01.jpg" alt=""><span class="indie-cap">Lu Xun (public domain)</span>',
    '<p><b>What I think it is doing.</b> The madness is the point. Only the man',
    'everyone calls mad can see the truth of the society plainly, that a whole',
    'tradition dressed up as virtue has been consuming its own people for thousands',
    'of years. The cannibalism is not literal, or not only. It is Lu Xun&rsquo;s',
    'image for a culture that devours the human beings inside it and calls the eating',
    'righteousness. The last line turns to the children. SAVE THE CHILDREN, the',
    'madman writes, the ones who have not yet eaten anyone. It is the smallest',
    'possible hope and he does not oversell it.</p>',
    '<p><b>To read next.</b> Everyone says the other one to read is <i>The True Story',
    'of Ah Q</i> (1921&ndash;22), the portrait of a low, self-deceiving man who turns',
    'every humiliation into an imaginary victory, and who was meant, I gather, as a',
    'mirror held up to a whole national habit of mind. It is in the collection',
    '<i>Call to Arms</i>. That is my next stop.</p>',
    '<hr>',
    '<p>Around the ring. For the philosopher who tried to build a modern Chinese',
    'thought that could stand beside the West, see',
    '<a href="feng-youlan.geocities.ws">feng-youlan.geocities.ws</a>. For the',
    'reformer of the generation before, who wanted to save the old order by remaking',
    'it rather than tearing it down, see',
    '<a href="kang-youwei.geocities.ws">kang-youwei.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>counter: 00707 · best viewed at 800x600 · reading in progress, notes',
    'added as I go · last updated 21 Aug · — a reader in the north</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp;',
    'Postcolonial Ring</a> ]</small></p>',
  ]);

// ---- Feng Youlan: student coursework ----------------------------------------

const FENG = P('feng-youlan.geocities.ws', 'FENG YOULAN',
  'FENG YOULAN // coursework: a modern neo-Confucian', [
    '<!--bg:aa-eastasia-->',
    '<h1>PHIL 214 Coursework: Feng Youlan</h1>',
    '<p><small>submitted for PHIL 214, Modern Asian Thought, semester two. name',
    'withheld until marked. topic: assess Feng Youlan&rsquo;s contribution. word',
    'count over, sorry. Chinese order, family name first, so Feng (family) Youlan',
    '(given). — put online after it was handed back, minus the red ink</small></p>',
    '<hr>',
    '<p><b>Introduction.</b> Feng Youlan (1895&ndash;1990) was one of the most',
    'important Chinese philosophers of the twentieth century, known for two things',
    'above all: a great history of Chinese philosophy that taught the subject to a',
    'generation, and an attempt to build a new Confucian philosophy for the modern',
    'age. He also lived through enough upheaval for three lifetimes, and the record',
    'of how his thought bent under political pressure is part of the story and cannot',
    'be left out.</p>',
    '<p><b>The History.</b> His <i>History of Chinese Philosophy</i> (two volumes,',
    'published in the early 1930s) was the work that made his name. For many readers,',
    'in China and then in English through the translation by Derk Bodde, it was the',
    'first orderly account of the whole tradition from the ancient masters onward. He',
    'had studied in the United States under John Dewey at Columbia, and he brought',
    'back a training in Western method that he turned on his own inheritance, without',
    'flattening it into Western shapes.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/fengyoulan-01.jpg" alt=""><span class="indie-cap">Feng Youlan (public domain)</span>',
    '<p><b>The new neo-Confucianism.</b> In the 1930s and 1940s Feng did not only',
    'write history, he tried to do philosophy of his own. He called it the NEW',
    'RATIONAL PHILOSOPHY (Xin Lixue), a modern revival of the rationalist wing of',
    'Song-dynasty neo-Confucianism, the school of Cheng Yi and Zhu Xi. He took their',
    'old idea of LI, principle or pattern, and reworked it with the tools of Western',
    'logic into something he hoped could stand as philosophy anywhere. The ambition',
    'was a bridge between Chinese and Western thought on which the traffic ran both',
    'ways.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I am not writing a history of Chinese',
    'philosophy in order to bury it, but so that it may live and grow.&rdquo;</p>',
    '<p><small>the essay&rsquo;s paraphrase of Feng&rsquo;s stated aim</small></p></blockquote>',
    '<p><b>The later self-criticism.</b> After 1949, under the new political order,',
    'Feng repeatedly criticised his own earlier work, sometimes harshly, and revised',
    'his positions to fit the times, especially during the Cultural Revolution. It is',
    'easy to judge from a comfortable distance. My tutor said, and I agree, that the',
    'honest thing is to record it plainly: a first-rate mind put under enormous',
    'pressure, who bent, and who kept working into great old age, publishing a last',
    'multi-volume history of Chinese philosophy in his nineties. Both facts are true',
    'and both belong in the picture.</p>',
    '<p><b>Conclusion.</b> Feng Youlan matters as the philosopher who tried hardest',
    'to make the Chinese tradition speak in the modern philosophical world as an',
    'equal, and who left both a history the whole field still uses and a life that',
    'shows what the century did to those who lived through it.</p>',
    '<p><b>Bibliography</b> (as handed in, tutor says fix the dates):<br>',
    'Feng Youlan, <i>A History of Chinese Philosophy</i>, trans. D. Bodde, 2 vols.<br>',
    'Feng Youlan, <i>A Short History of Chinese Philosophy</i>.<br>',
    'lecture notes, wk 6 &amp; 7 (the neo-Confucian revival).<br>',
    'that photocopied chapter nobody could find the source of.</p>',
    '<hr>',
    '<p>Ring links used for this essay. On the writer who thought the old tradition',
    'was eating its own people, not to be revived, see',
    '<a href="lu-xun.geocities.ws">lu-xun.geocities.ws</a>. On the reformer who first',
    'tried to modernise Confucianism from within, a generation earlier, see',
    '<a href="kang-youwei.geocities.ws">kang-youwei.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>hits: 00268 · best viewed at 800x600 · page still under construction,',
    'will add the marked feedback if I am brave · last updated 30 Jun</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp;',
    'Postcolonial Ring</a> ]</small></p>',
  ]);

// ---- Kang Youwei: talk write-up ---------------------------------------------

const KANG = P('kang-youwei.geocities.ws', 'KANG YOUWEI',
  'KANG YOUWEI // talk write-up: the reformer & the Great Unity', [
    '<!--bg:aa-eastasia-->',
    '<h1>Talk write-up: Kang Youwei and the Book of the Great Unity</h1>',
    '<p><small>notes from the evening lecture in the society&rsquo;s spring series,',
    'written up from what I scribbled. the speaker was good, any mistakes are mine,',
    'not hers. Chinese name order, family first, so Kang (family) Youwei (given).',
    '— written up by whoever sat at the front</small></p>',
    '<hr>',
    '<p><b>Who he was.</b> The talk opened by placing him. Kang Youwei',
    '(1858&ndash;1927) was a Confucian scholar and the leading reformer of the last',
    'years of imperial China. His great conviction was that China had to modernise or',
    'be carved up, and that the way to do it was not to throw Confucius away but to',
    'reinterpret him. He argued, controversially, that Confucius had himself been a',
    'reformer, a maker of new institutions, and that the tradition rightly read was a',
    'charter for change rather than a dead weight against it.</p>',
    '<p><b>The Hundred Days.</b> The heart of the talk was 1898. For a hundred or so',
    'days that summer the young Guangxu Emperor, taking Kang&rsquo;s advice and that',
    'of his brilliant pupil Liang Qichao, issued a torrent of reforming edicts, on',
    'the schools, the examinations, the army, the administration. The speaker called',
    'it a genuine attempt to remake the state from the top in a single season. Then',
    'the conservative court, led by the Empress Dowager Cixi, struck back. The',
    'reforms were reversed, several of the reformers were executed, and Kang barely',
    'escaped into exile abroad. She reminded us that Kang spent much of the rest of',
    'his life outside China, still arguing, by then overtaken by more radical men.</p>',
    '<div class="fs-aside"><p><b>An aside the speaker made.</b> It is tempting to',
    'file Kang as a failure because the Hundred Days collapsed. She pushed back on',
    'that. The ideas he put into the air, that the state could be deliberately',
    'redesigned, that Confucianism could be modern, did not die when the edicts were',
    'torn up. They shaped the argument every Chinese thinker after him had to have.</p></div>',
    '<img class="indie-pic" src="assets/media/web/aa/kangyouwei-01.jpg" alt=""><span class="indie-cap">Kang Youwei (public domain)</span>',
    '<p><b>The Book of the Great Unity.</b> The strangest and most moving part came',
    'last. Kang wrote, and mostly kept private in his lifetime, a book called the',
    '<i>Datong Shu</i>, the <i>Book of the Great Unity</i>, sometimes given as the',
    'Great Harmony. It draws on an old Confucian idea of the age of Great Unity and',
    'turns it into a full utopia. In it Kang imagines a future world that has done',
    'away with the boundaries that divide humankind: the boundaries of nation, of',
    'class, of race, of sex, and even, he wrote, of the family itself, which he',
    'thought bred as much selfishness as love. A world without states, held in',
    'common, its children raised in common. The speaker was careful to say how',
    'radical this was for a Confucian scholar of his day, and how far ahead of the',
    'reforms he actually fought for.</p>',
    '<p><b>Discussion.</b> In the questions someone asked whether the utopia and the',
    'cautious reformer could really be the same man. The answer that stuck with me',
    'was that Kang thought the Great Unity was where history was going in the very',
    'long run, but that you could not leap there, you had to reform the world you',
    'actually had, step by step, first. The dream and the edicts were two ends of one',
    'road.</p>',
    '<hr>',
    '<p>Society links. For the philosopher a generation later who tried to build a',
    'modern Confucian system for the classroom, see',
    '<a href="feng-youlan.geocities.ws">feng-youlan.geocities.ws</a>. For the writer',
    'who lost all patience with saving the old order and turned his pen against it,',
    'see <a href="lu-xun.geocities.ws">lu-xun.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>counter: 00195 · best viewed at 800x600 · spring lecture series, more',
    'write-ups to follow · posted 4 May</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp;',
    'Postcolonial Ring</a> ]</small></p>',
  ]);

export const AA_E = [NISHIDA, SUZUKI, WATSUJI, LUXUN, FENG, KANG];
