// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH AA_F — postcolonial theory and the bridge.
//
// Pages made in the 1990s by students, reading groups and admirers about the
// thinkers who taught them to read empire in the archive: Said on Orientalism,
// Guha and the Subaltern Studies project, Spivak's hard question, Bhabha's
// third space, Nandy's intimate enemy, and Shariati's red Shiism. The books,
// dates and politics are real; the framing and the affection are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Said: book-reading notes on Orientalism (SHOWPIECE) --------------------

const SAID = P('edward-said.geocities.ws', 'EDWARD SAID',
  'ORIENTALISM — a reader’s notebook // Edward Said', [
    '<!--bg:aa-postcolonial-->',
    '<h1>ORIENTALISM: a reader’s notebook</h1>',
    '<p><small>notes made reading Edward Said (1935–2003) over one long term.',
    'i kept a notebook because the book is dense and i wanted to be able to argue',
    'with it later. these are the pages, tidied up. corrections welcome. — N.H.</small></p>',
    '<hr>',
    '<p class="fs-epi">“The Orient was almost a European invention.”<br>',
    '— Edward Said, <i>Orientalism</i> (1978), opening page</p>',
    '<p>Said was born in Jerusalem in 1935, schooled in Cairo, and spent his',
    'working life at Columbia in New York. A Palestinian in the American academy,',
    'a literary critic who also played the piano seriously, he wrote the book that',
    'gave a whole field its name. <i>Orientalism</i> is not a book about the East.',
    'It is a book about how the West wrote the East into being as something it',
    'could study, picture and rule.</p>',
    '<blockquote class="fs-quote"><p>“Orientalism [is] a Western style for',
    'dominating, restructuring, and having authority over the Orient.”</p>',
    '<p><small>— <i>Orientalism</i>, Introduction</small></p></blockquote>',
    '<p>His method he took in part from Michel Foucault: the Orient is a',
    '<i>discourse</i>, a body of writing and images that produces its object',
    'rather than merely describing it. He took as much again from Antonio Gramsci,',
    'on how a culture makes its own authority feel like plain common sense. The',
    'scholars, the travel writers and the colonial administrators all drew on one',
    'archive and cited one another until the picture closed on itself.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/said-01.jpg" alt=""><span class="indie-cap">Edward Said (Barenboim-Said Akademie, CC0)</span>',
    '<div class="fs-aside"><p><b>the three Orientalisms.</b> Said says the word',
    'carries three senses at once. An academic discipline, with chairs and',
    'journals. A style of imagination that splits the world into East and West. And',
    'a corporate institution for dealing with the Orient, that is, an arm of',
    'government and empire. His argument is that the three cannot be pulled apart.</p></div>',
    '<p>The evidence is a long reading of the archive. Silvestre de Sacy and Ernest',
    'Renan building the discipline; Edward Lane living in Cairo to describe the',
    'Egyptians; Flaubert meeting the courtesan Kuchuk Hanem and speaking for her',
    'because she could not speak for herself; Lord Cromer governing Egypt with the',
    'textbook in his hand. One archive, quoted forward for a century, and the',
    'living people underneath it fixed as a type: timeless, sensual, despotic,',
    'incapable of representing themselves.</p>',
    '<pre>THE ARGUMENT OF ORIENTALISM, IN STEPS\n'
    + '  1. There is no neutral “Orient” waiting to be found.\n'
    + '     The Orient is made, produced as an object of\n'
    + '     European knowledge.\n'
    + '  2. That knowledge and the empire grow together. To\n'
    + '     know the East in this way was already to hold\n'
    + '     authority over it.\n'
    + '  3. Scholar, novelist and colonial officer draw on one\n'
    + '     archive. Renan, Lane, Flaubert, Cromer, each citing\n'
    + '     the others into a closed and self-confirming system.\n'
    + '  4. The Oriental is frozen into a type, sensual and\n'
    + '     despotic and mute, a figure who by definition\n'
    + '     cannot speak for himself.\n'
    + '  5. The discourse outlives the empires that built it and\n'
    + '     runs on now in the fluent language of area experts\n'
    + '     and television pundits.</pre>',
    '<p><b>Culture and Imperialism (1993).</b> The sequel widens the lens from the',
    'Middle East to empire as such, and turns to the novel. Said reads Jane',
    'Austen’s <i>Mansfield Park</i> and finds the sugar of Antigua paying for the',
    'calm of the English house; he reads Conrad, Kipling and Verdi’s <i>Aida</i>',
    'the same way. His name for the method is <i>contrapuntal reading</i>, borrowed',
    'from music. You hold two lines together, the metropolitan story and the',
    'colony it depends on and will not mention, and you listen to them at once.</p>',
    '<p class="fs-pull">“Exile is strangely compelling to think about but terrible',
    'to experience.” — Reflections on Exile</p>',
    '<p>Behind the scholarship there was a life in politics. Said wrote for the',
    'Palestinian cause for decades, sat on the Palestinian National Council, and',
    'then broke publicly with the Oslo accords because he thought they sold the',
    'refugees short. He prized the figure of the amateur, the intellectual who',
    'speaks outside the guild and refuses to be a specialist for hire, and he',
    'prized the exile’s double vision, at home nowhere and therefore able to see',
    'two worlds where the settled person sees one.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/spivak-01.jpg" alt=""><span class="indie-cap">Gayatri Spivak (photo: Rosa Luxemburg-Stiftung, CC BY 2.0)</span>',
    '<p>Where to read next in this ring. Gayatri Spivak takes the mute figure of',
    'step four and asks the harder question, whether the subaltern can speak at',
    'all: <a href="gayatri-spivak.geocities.ws">gayatri-spivak</a>. Homi Bhabha',
    'takes Said’s fixed colonial type and shows it wobbling, never quite as sure',
    'of itself as it sounds: <a href="homi-bhabha.geocities.ws">homi-bhabha</a>.',
    'The teacher Said learned close reading from, Erich Auerbach, who wrote',
    '<i>Mimesis</i> in exile in Istanbul, has no page here, but he is all over',
    'this book.</p>',
    '<hr>',
    '<p><small>counter: 03571 · best viewed at 800x600 · typed up on the library',
    'machine · last updated 14 Oct 98</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp; Postcolonial Ring</a> ]</small></p>',
    '<p><small>« prev · random · next »</small></p>',
  ]);

// ---- Guha: academic summary -------------------------------------------------

const GUHA = P('ranajit-guha.geocities.ws', 'RANAJIT GUHA',
  'Ranajit Guha &amp; Subaltern Studies // a summary', [
    '<!--bg:aa-postcolonial-->',
    '<h1>Ranajit Guha and the Subaltern Studies project</h1>',
    '<p><small>a summary page prepared for a postgraduate seminar. it aims to be',
    'accurate and short. sources listed at the foot.</small></p>',
    '<hr>',
    '<p>Ranajit Guha, born in Bengal in 1923, is the historian who founded',
    'Subaltern Studies and gave Indian historiography a new object: the politics',
    'of the people who do not appear in the official record. His early book',
    '<i>A Rule of Property for Bengal</i> (1963) examined the Permanent Settlement',
    'and the making of colonial land law. The project that made his name began two',
    'decades later.</p>',
    '<p>In 1982 Guha and a group of younger scholars launched the series',
    '<i>Subaltern Studies</i>. The word <i>subaltern</i> they took from Gramsci,',
    'where it names the subordinate groups excluded from power. The collective’s',
    'argument was that both schools of existing history, the colonialist and the',
    'bourgeois nationalist, told the story of the nation from above, as the work',
    'of elites, and so wrote the peasant and the labourer out of their own',
    'insurgencies. Against this the collective claimed an autonomous domain of',
    'subaltern politics, one that did not simply follow the lead of the Congress',
    'or the Raj.</p>',
    '<blockquote class="fs-quote"><p>“The historiography of Indian nationalism has',
    'for a long time been dominated by elitism.”</p><p><small>— Ranajit Guha,',
    'opening of the Subaltern Studies manifesto, 1982</small></p></blockquote>',
    '',
    '<p>His central book is <i>Elementary Aspects of Peasant Insurgency in Colonial',
    'India</i> (1983). Working from the records of revolts across the nineteenth',
    'century, Guha tried to reconstruct the peasant rebel as a conscious political',
    'subject, reading negation, ambiguity, solidarity and rumour as the grammar of',
    'insurgent action rather than as blind riot. The methodological companion',
    'piece, the essay “The Prose of Counter-Insurgency” (in <i>Subaltern Studies',
    'II</i>, 1983), showed how the colonial document itself is written from the',
    'side of order. The archive records the rebel only as a problem for the state,',
    'so the historian who wants the rebel’s own consciousness has to read that',
    'prose against its grain.</p>',
    '<p>The collective grew and changed, and later took a more textual and',
    'theoretical turn under the influence of, among others, Gayatri Spivak, who',
    'edited a selection with Guha and pressed the question of who speaks for the',
    'subaltern. Ashis Nandy, working nearby at the Centre for the Study of',
    'Developing Societies in Delhi, shared the wider suspicion of the modern state',
    'even while arguing from a different ground. Partha Chatterjee, a member of the',
    'collective, carried the work into the study of nationalism and the politics of',
    'the governed.</p>',
    '<p>Read next. Gayatri Spivak’s intervention in the project is at',
    '<a href="gayatri-spivak.geocities.ws">gayatri-spivak</a>, and Ashis Nandy’s',
    'parallel critique of the modern nation-state is at',
    '<a href="ashis-nandy.geocities.ws">ashis-nandy</a>.</p>',
    '<hr>',
    '<p><small>Selected reading: Guha, <i>Elementary Aspects of Peasant Insurgency',
    'in Colonial India</i> (1983); Guha (ed.), <i>Subaltern Studies</i> I–VI',
    '(1982–); Guha and Spivak (eds.), <i>Selected Subaltern Studies</i> (1988).</small></p>',
    '<p><small>visitors: 01192 · best viewed at 800x600 · last updated 3 Mar 99</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp; Postcolonial Ring</a> ]</small></p>',
    '<p><small>« prev · random · next »</small></p>',
  ]);

// ---- Spivak: reading-group minutes ------------------------------------------

const SPIVAK = P('gayatri-spivak.geocities.ws', 'G. C. SPIVAK',
  'MINUTES: “Can the Subaltern Speak?” (Spivak)', [
    '<!--bg:aa-postcolonial-->',
    '<h1>Reading group minutes: “Can the Subaltern Speak?”</h1>',
    '<p><small>the Thursday theory group, upstairs room. present: eight of us this',
    'week. text: Gayatri Chakravorty Spivak, “Can the Subaltern Speak?” (1988).',
    'minutes taken by whoever had the clearest handwriting, that is me. — R.</small></p>',
    '<hr>',
    '<p><b>1. Who she is.</b> We started with the biography because half the room',
    'only knew her from the essay. Born in Calcutta in 1942. She made her name in',
    '1976 by translating Jacques Derrida’s <i>Of Grammatology</i> into English and',
    'writing a long preface that taught a generation what deconstruction was. So',
    'she comes to the colonial question already armed with the tools for taking a',
    'text apart, and she never lets the reader forget who is doing the reading.</p>',
    '<p><b>2. The famous question.</b> Long argument about what the title even',
    'means. Agreed in the end: the subaltern here is not just “the poor”. It is',
    'the position so far outside the lines of power that when such a person tries',
    'to speak, the speech cannot be heard <i>as</i> political speech. The channels',
    'that would carry it, the archive, the law, even the sympathetic scholar,',
    'reshape it on the way. So the question is not whether they have a voice. It is',
    'whether the structure lets that voice arrive.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/spivak-01.jpg" alt=""><span class="indie-cap">Gayatri Spivak (photo: Rosa Luxemburg-Stiftung, CC BY 2.0)</span>',
    '<p><b>3. The example that stopped us.</b> Spivak’s case is <i>sati</i>, widow',
    'immolation, and the British ban on it. Her line about how the colonial rescue',
    'was described:</p>',
    '<p class="fs-pull">“White men are saving brown women from brown men.”</p>',
    '<p>Between the British claim to be protecting the woman and the nativist claim',
    'that she chose the fire freely, the woman’s own construction of her act',
    'disappears. Both sides speak for her; neither lets her speak. Spivak follows',
    'the archive of a young woman, Bhubaneswari Bhaduri, whose suicide was framed',
    'and reframed by everyone but herself. We found this genuinely upsetting and',
    'sat with it for a while.</p>',
    '<p><b>4. Strategic essentialism.</b> Someone raised the phrase she is known',
    'for. The idea that a subordinated group may, for a political moment, act',
    '<i>as if</i> it had one fixed shared essence, in order to be able to act at',
    'all, while knowing the essence is a fiction. We noted that Spivak herself grew',
    'wary of the phrase later, because people kept quoting the essentialism and',
    'dropping the strategic. Also discussed: <i>worlding</i>, her term for the way',
    'imperialism writes the colony into being as part of the world it then claims',
    'to have discovered.</p>',
    '<p><b>5. Where it connects.</b> This is Said’s mute Oriental',
    '(<a href="edward-said.geocities.ws">edward-said</a>) taken one turn further,',
    'and it argues at points with Bhabha’s more hopeful reading of colonial speech',
    '(<a href="homi-bhabha.geocities.ws">homi-bhabha</a>). Her debt to Derrida ran',
    'all through the evening. Next week: a chapter of <i>A Critique of Postcolonial',
    'Reason</i>, if anyone can find a copy.</p>',
    '<hr>',
    '<p><small>counter: 00908 · best viewed at 800x600 · the Thursday group, since',
    'Sept 96 · minutes last posted 19 Feb 99</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp; Postcolonial Ring</a> ]</small></p>',
    '<p><small>« prev · random · next »</small></p>',
  ]);

// ---- Bhabha: talk write-up --------------------------------------------------

const BHABHA = P('homi-bhabha.geocities.ws', 'HOMI BHABHA',
  'LECTURE NOTES: hybridity &amp; the third space (Bhabha)', [
    '<!--bg:aa-postcolonial-->',
    '<h1>Lecture notes: Homi Bhabha on the location of culture</h1>',
    '<p><small>write-up of a public lecture i went to, plus what i could piece',
    'together afterwards from <i>The Location of Culture</i>. any errors are mine,',
    'not the speaker’s. he talks fast and the ideas are slippery on purpose.</small></p>',
    '<hr>',
    '<p>Homi K. Bhabha, born in Bombay in 1949 into the city’s Parsi community,',
    'was introduced as one of the three names, with Said and Spivak, that founded',
    'postcolonial theory as a field. His book <i>The Location of Culture</i> (1994)',
    'gathers the essays the talk drew on. The prose is famously hard. The speaker',
    'said, disarmingly, that the difficulty is part of the argument, because the',
    'colonial encounter is not clean and a clean theory would falsify it.</p>',
    '<p><b>Hybridity.</b> His first move against the old picture. Colonised and',
    'coloniser do not meet as two sealed cultures, one then swallowing the other.',
    'What the encounter actually produces is something mixed, a hybrid that belongs',
    'wholly to neither side and unsettles both. Purity is the colonial fantasy;',
    'hybridity is the fact on the ground.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/bhabha-01.jpg" alt=""><span class="indie-cap">Homi Bhabha (photo: jeanbaptisteparis, CC BY-SA 2.0)</span>',
    '<p><b>The third space.</b> The place where that mixing happens. Bhabha calls',
    'it the space of <i>enunciation</i>, the in-between where meaning is negotiated',
    'rather than handed down. Because every utterance passes through it, no',
    'cultural authority arrives at the other side quite intact. This was the part',
    'the audience questions circled back to most.</p>',
    '<p><b>Mimicry and ambivalence.</b> The sharpest section. Empire tells the',
    'colonised to become like the coloniser, to be reformed and Anglicised, but',
    'never actually to be equal. So it demands a copy that must stay a copy. Bhabha’s',
    'phrase for the reformed colonial subject:</p>',
    '<blockquote class="fs-quote"><p>“almost the same, but not quite”</p>',
    '<p><small>— Homi Bhabha, “Of Mimicry and Man”, in <i>The Location of',
    'Culture</i></small></p></blockquote>',
    '<p>and, more bluntly, almost the same but not white. The catch is that the',
    'near-copy is also a threat. It mocks the original just by resembling it, and',
    'it shows that the supposedly natural authority of the coloniser can be worn',
    'like a costume. So colonial discourse is <i>ambivalent</i>: it both wants the',
    'mimic and is menaced by him. The power is never as whole as it pretends.</p>',
    '<p>Where it sits. This is the optimistic wing of the field, set against Said’s',
    'heavier account of a discourse that holds firm',
    '(<a href="edward-said.geocities.ws">edward-said</a>). It also rhymes, though',
    'from a different tradition, with Ashis Nandy’s idea that coloniser and',
    'colonised are bound together in one damaged psychology',
    '(<a href="ashis-nandy.geocities.ws">ashis-nandy</a>). Frantz Fanon ran all',
    'through the talk, as the writer Bhabha reads and rereads.</p>',
    '<hr>',
    '<p><small>counter: 01044 · best viewed at 800x600 · written up the same night',
    'while it was fresh · last updated 7 Dec 98</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp; Postcolonial Ring</a> ]</small></p>',
    '<p><small>« prev · random · next »</small></p>',
  ]);

// ---- Nandy: student coursework ----------------------------------------------

const NANDY = P('ashis-nandy.geocities.ws', 'ASHIS NANDY',
  'PPE 314 essay page: Ashis Nandy, The Intimate Enemy', [
    '<!--bg:aa-postcolonial-->',
    '<h1>The Intimate Enemy: coursework notes on Ashis Nandy</h1>',
    '<p><small>PPE 314 Politics of Colonialism, term paper prep. putting my notes',
    'up in case anyone else in the seminar is stuck. do NOT copy this, cite it, the',
    'marker reads these pages too apparently. — posted by dev_k</small></p>',
    '<hr>',
    '<p>Ashis Nandy, born 1937, is a political psychologist and social theorist at',
    'the Centre for the Study of Developing Societies in Delhi. He is the awkward',
    'one in the postcolonial field, an ironist who distrusts the modern state as',
    'much as he distrusts the empire it replaced. The set text for us is <i>The',
    'Intimate Enemy: Loss and Recovery of Self Under Colonialism</i> (1983).</p>',
    '<p><b>The main argument (this is the bit for the essay).</b> Nandy says the',
    'deepest damage of colonialism was not out there in the economy and the army',
    'but inside, in the mind, and on both sides. Colonialism installed a psychology',
    'that wounded the colonised and the coloniser together. It prized a hard,',
    'competitive, hyper-masculine idea of the adult Western man and taught everyone',
    'to despise what it coded as feminine, childlike or weak, including much of',
    'what Indian culture had valued. The enemy is intimate because it got inside.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/nandy-01.jpg" alt=""><span class="indie-cap">Ashis Nandy (photo: Mohan Trivedi, CC BY-SA 3.0)</span>',
    '<p><b>Why he is hard to place.</b> He does not want the mirror-image answer, a',
    'proud aggressive nationalism that beats the West at its own game, because that',
    'just keeps the same psychology and swaps the flag. He reaches instead for the',
    'figures the modern story calls losers, the saint, the woman, the child, even',
    'a Gandhi read against the grain, as holding a saner idea of the self. In class',
    'we argued about whether this is profound or whether it romanticises.</p>',
    '<p><b>The state and secularism.</b> His other famous line, from essays like',
    '“The Politics of Secularism and the Recovery of Religious Tolerance”, is that',
    'the modern secular nation-state is not the neutral referee it claims to be. He',
    'argues that older, lived, plural forms of religious tolerance often kept the',
    'peace better than the official secularism that replaced them. This one is',
    'controversial and the seminar split down the middle over it.</p>',
    '<blockquote class="fs-quote"><p>“Colonialism is first of all a matter of',
    'consciousness and needs to be defeated ultimately in the minds of men.”</p>',
    '<p><small>— Ashis Nandy, <i>The Intimate Enemy</i></small></p></blockquote>',
    '<p><b>WONKY BIBLIOGRAPHY (still checking these, some page numbers missing).</b><br>',
    'Nandy, A. (1983) <i>The Intimate Enemy</i>. Delhi: Oxford Univ. Press.<br>',
    'Nandy, A. (1980) <i>At the Edge of Psychology</i>. OUP (i think? the library',
    'copy has no date page).<br>',
    'Nandy, A. (1995) <i>The Savage Freud and Other Essays</i>. Princeton.<br>',
    'Nandy on secularism — it is in an edited collection, need to find the editor.</p>',
    '<p>See also, for the wider argument about the colonial archive, Ranajit Guha at',
    '<a href="ranajit-guha.geocities.ws">ranajit-guha</a>, and for a very different',
    'religious answer to the same modern predicament, Ali Shariati at',
    '<a href="ali-shariati.geocities.ws">ali-shariati</a>. Nandy reads Gandhi and',
    'Tagore closely; neither is in this corner of the ring.</p>',
    '<hr>',
    '<p><small>hit counter: 00623 · best viewed at 800x600 · UNDER CONSTRUCTION',
    '(adding the essay plan once i have a mark back) · last updated 22 Nov 98 ·',
    'dev_k</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp; Postcolonial Ring</a> ]</small></p>',
    '<p><small>« prev · random · next »</small></p>',
  ]);

// ---- Shariati: personal fan shrine ------------------------------------------

const SHARIATI = P('ali-shariati.geocities.ws', 'ALI SHARIATI',
  'a shrine to Ali Shariati // red Shiism', [
    '<!--bg:aa-postcolonial-->',
    '<h1>ALI SHARIATI: teacher of the revolution</h1>',
    '<p><small>a page for Dr Ali Shariati (1933–1977), kept by an admirer who read',
    'the English translations and could not put them down. i am no scholar of Iran,',
    'i am a reader who was moved. corrections gratefully received. — s.a.</small></p>',
    '<hr>',
    '<p class="fs-epi">“Every day is Ashura, every place is Karbala.”<br>',
    '— an old Shia saying that Shariati made a call to action</p>',
    '<p>Ali Shariati was an Iranian sociologist of religion, and to many the',
    'intellectual who did most to give the 1979 revolution its language. He was',
    'born near Mashhad in 1933, the son of a reformist religious teacher. In Paris',
    'in the early 1960s he read Marxism and existentialism, worked on the journal',
    'of the Algerian resistance, and came under the spell of Frantz Fanon, whom he',
    'translated into Persian. He took from Fanon the idea that a colonised people',
    'must recover itself, and he asked what, for Iran, that self was.</p>',
    '<p><b>Return to the self.</b> His answer was <i>bazgasht be khishtan</i>, the',
    'return to the self. Not the borrowed self of the Westernised elite, and not a',
    'museum-piece tradition either, but a living Shia Islam turned into a force for',
    'justice here and now. He gave his most famous lectures at the Hosseiniye',
    'Ershad in Tehran, and the young came in their thousands, until the Shah’s',
    'police closed it and imprisoned him.</p>',
    '<img class="indie-pic" src="assets/media/web/aa/shariati-01.jpg" alt=""><span class="indie-cap">Ali Shariati (public domain)</span>',
    '<p><b>Red Shiism and black Shiism.</b> This is the idea people remember, and',
    'the reason for the title of this page. Shariati split the tradition in two.</p>',
    '<blockquote class="fs-quote"><p>“Red Shiism [is] the religion of martyrdom,',
    'black Shiism the religion of mourning.”</p><p><small>— Ali Shariati, from the',
    'essay published in English as <i>Red Shi’ism vs Black Shi’ism</i></small></p></blockquote>',
    '<p>Red Shiism is the faith of Ali and of Husayn at Karbala, a religion of',
    'protest, of standing against the tyrant even unto death. Black Shiism is the',
    'faith the Safavid state and a quietist clergy made of it, all mourning and',
    'ritual and waiting, a religion that keeps the people’s heads down. Shariati',
    'wanted the red against the black. Martyrdom, for him, was not passive',
    'suffering; it was a witness that indicts the unjust ruler in front of history.</p>',
    '<p><b>His death.</b> The regime hounded him. Released from prison and allowed',
    'to leave Iran, he reached England in 1977 and died there in June, in',
    'Southampton, at the age of forty-three. The official cause was a heart attack.',
    'Many of his readers have always believed the Shah’s secret police, the SAVAK,',
    'had a hand in it. He died in exile, as so many in this ring did, and did not',
    'live to see the revolution his words had helped to shape.</p>',
    '<p>He does not fit the neat categories. He argued with the traditional clergy',
    'and with the secular left at once, and after 1979 the state that quoted him',
    'was not always the one he had imagined. Read alongside Ashis Nandy on the',
    'wounds of the modern state (<a href="ashis-nandy.geocities.ws">ashis-nandy</a>)',
    'and Homi Bhabha on the mixed and unfinished colonial self',
    '(<a href="homi-bhabha.geocities.ws">homi-bhabha</a>). His teacher in Paris,',
    'the scholar of Islam Louis Massignon, and his hero Fanon, both belong beside',
    'him in any full account.</p>',
    '<hr>',
    '<p><small>counter: 00777 · best viewed at 800x600 · this page made with love',
    'and a borrowed scanner · last updated 5 Jun 99 · s.a.</small></p>',
    '<p><small>[ <a href="anticolonial-ring.geocities.ws">Anticolonial &amp; Postcolonial Ring</a> ]</small></p>',
    '<p><small>« prev · random · next »</small></p>',
  ]);

export const AA_F = [SAID, GUHA, SPIVAK, BHABHA, NANDY, SHARIATI];
