// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — fantasy and the epic.
//
// The fanzine writer, the paperback collector and the convention-goer, each
// keeping a shrine to a corner of fantasy. A full Tolkien author-shrine with a
// reading order and a Middle-earth timeline; a single-novel guide to The Lord
// of the Rings; an Earthsea reading guide that quietly puts Le Guin against the
// epic; a Conan and sword-and-sorcery profile of Howard; a close reading of
// Dunsany's invented pantheon; and a Gormenghast page on the gothic without
// magic. Authors, titles and dates are real; the enthusiasms are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Tolkien: the author shrine (SHOWPIECE) ---------------------------------

const TOLKIEN = P('j-r-r-tolkien.geocities.ws', 'TOLKIEN',
  'THE PROFESSOR // a J.R.R. Tolkien shrine', [
    '<!--bg:sff-fantasy-->',
    '<h1>THE PROFESSOR</h1>',
    '<p><small>a shrine to John Ronald Reuel Tolkien (1892-1973), kept by a reader',
    'who came for the dragons and stayed for the languages. i have read the trilogy',
    'eleven times and i am not embarrassed. corrections and pedantry welcome, i',
    'will lose to you gladly. — Elanor, fanzine editor of <i>Mathom</i></small></p>',
    '<hr>',
    '<p class="fs-epi">"All that is gold does not glitter, / Not all those who',
    'wander are lost."<br>— J.R.R. Tolkien, <i>The Fellowship of the Ring</i>, 1954</p>',
    '<p>Before he was the man who invented modern epic fantasy, Tolkien was a',
    'philologist, a professor of Anglo-Saxon and then of English at Oxford, a man',
    'who loved dead languages the way other people love music. That is the key to',
    'the whole thing, so hold on to it. He did not build a world and then bolt on',
    'some languages to decorate it. He built the languages first, Quenya and',
    'Sindarin, the two Elvish tongues, and then reasoned that a language needs a',
    'people to speak it, and a people needs a history, and a history needs a world.',
    'Middle-earth grew downward from its words.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/tolkien-01.jpg" alt=""><span class="indie-cap">J. R. R. Tolkien, c.1925 (public domain)</span>',
    '<p>It began, so the story goes, with a sentence he scribbled on a blank page',
    'while marking exam papers: "In a hole in the ground there lived a hobbit." He',
    'did not know what a hobbit was. He had to find out. <i>The Hobbit</i> (1937)',
    'was the finding out, a children’s book, a there-and-back-again adventure',
    'with a dragon called Smaug and a riddle game in the dark. It sold, and the',
    'publisher wanted more hobbits, and the more he gave them turned into something',
    'no publisher had asked for.</p>',
    '<p class="fs-aside"><b>Did you know?</b> The word "sub-creation" is Tolkien’s',
    'own. In his lecture and essay <i>On Fairy-Stories</i> (given 1939, printed',
    '1947) he argued that the maker of a fantasy world is a sub-creator: God makes',
    'the Primary World, and the storyteller makes a Secondary World that the mind',
    'can enter and believe while inside it. The test is not escapism, he said, but',
    'the "inner consistency of reality". A good invented world obeys its own laws.</p>',
    '<p>That essay is the nearest thing fantasy has to a manifesto, and it is worth',
    'reading straight. Tolkien defends the fairy-story against the charge that it',
    'is childish and dishonest. Fantasy, he says, does not deny reason, it depends',
    'on it: you have to know that grass is green before the green sun of a made',
    'world can astonish you. And he names three gifts the good fairy-story gives:',
    'Recovery, a clean re-seeing of ordinary things; Escape, which he defends as',
    'the escape of the prisoner and not the flight of the deserter; and Consolation,',
    'the sudden joyous turn he called the eucatastrophe, the happy ending that comes',
    'against all hope.</p>',
    '<p class="fs-pull">"The Lord of the Rings is one of those things: if you like',
    'it you do, if you don’t, you boo." — W.H. Auden, reviewing it in 1956, and',
    'getting the fandom exactly right forty years early.</p>',
    '<p><i>The Lord of the Rings</i> came out in three volumes across 1954 and 1955,',
    'and it has its own page, so i will not spoil it here beyond saying it is not a',
    'trilogy. Tolkien wrote one very long novel and the publisher split it in three',
    'to spread the risk of the paper cost. Read it as one book. There is a fuller',
    'guide at <a href="the-lord-of-the-rings.geocities.ws">the-lord-of-the-rings</a>.</p>',
    '<p>And then there is the deep book, the one he worked at his whole life and',
    'never finished, the legendarium behind everything. <i>The Silmarillion</i> was',
    'edited together by his son Christopher and published in 1977, four years after',
    'his death. It is the Bible of Middle-earth, the older and sadder mythology, the',
    'creation by music, the fall of the elves, the wars over the Silmarils, the',
    'drowning of Numenor. It is not a novel and it will break the reader who comes',
    'to it expecting hobbits. Come to it expecting Genesis and you will do better.</p>',
    '<h2>where to start (a reading order)</h2>',
    '<pre>',
    'IF YOU HAVE NEVER READ HIM',
    '  1. The Hobbit (1937) ......... the way in. a children’s book. read it first.',
    '  2. The Fellowship of the Ring (1954)',
    '  3. The Two Towers (1954)',
    '  4. The Return of the King (1955) .. and READ THE APPENDICES. they are the point.',
    '',
    'IF YOU WANT THE DEEP LORE',
    '  5. The Silmarillion (1977, ed. C. Tolkien) .. the elder days. hard. worth it.',
    '  6. Unfinished Tales (1980) ....... the workshop, the offcuts, the extra light.',
    '',
    'FOR THE TRULY LOST (i am here)',
    '  7. The History of Middle-earth, 12 vols (1983-96, ed. C. Tolkien)',
    '     the whole compost heap of drafts. do not start here. arrive here.',
    '',
    'THE ESSAY EVERYONE SHOULD READ',
    '  *  On Fairy-Stories (1947) .. the theory of the whole thing, in 60 pages.',
    '</pre>',
    '<p class="fs-quote">"I cordially dislike allegory in all its manifestations,',
    'and always have done so since I grew old and wary enough to detect its',
    'presence."<br>— Tolkien, in the foreword to the second edition, swatting away',
    'the readers who wanted the Ring to be the atom bomb. It is not. He hated that',
    'reading. The tale grew in the telling, he said, and meant it.</p>',
    '<h2>the shape of the ages</h2>',
    '<pre>',
    'A ROUGH MIDDLE-EARTH TIMELINE (do not @ me, the dates are Tolkien’s own)',
    '',
    '  Before time .. the Music of the Ainur. the world sung into being.',
    '  Years of the Lamps / of the Trees .. the elder light, before sun and moon.',
    '  First Age .... the Silmarils, Morgoth, Beren and Luthien, the fall of the elves.',
    '  Second Age ... Numenor rises and drowns. the Rings of Power are forged.',
    '               .. the One Ring made in secret. the Last Alliance. Sauron thrown down.',
    '  Third Age .... the Ring lost, found by Gollum, found by Bilbo. THE HOBBIT.',
    '               .. and at its very end, THE LORD OF THE RINGS. the Ring unmade.',
    '  Fourth Age ... the Dominion of Men. the elves depart over Sea. the tale closes.',
    '</pre>',
    '<p>Why does a dead Oxford professor matter now, with the machines gone quiet',
    'and the shelves the only thing still lit? Because he built a thing that holds',
    'together without a single circuit, a world made entirely of words and belief,',
    'consistent enough to walk around in and love. Sub-creation needs no power',
    'supply. Open the book and Middle-earth is simply there, exactly as complete as',
    'the day he closed it.</p>',
    '<p>For the older, stranger fantasy that fed him, especially the invented',
    'pantheons, follow the trail back to Lord Dunsany at',
    '<a href="lord-dunsany.geocities.ws">lord-dunsany</a>. Tolkien read him young.</p>',
    '<hr>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
    '<p><small>hit counter: 08127 · best viewed in Netscape at 800x600 · this shrine',
    'is under eternal construction, like the Silmarillion was · a proud member of the',
    'fantasy webring for readers who own more maps than furniture · last updated 22',
    'March · — Elanor</small></p>',
  ]);

// ---- The Lord of the Rings: single-novel reading guide ----------------------

const LOTR = P('the-lord-of-the-rings.geocities.ws', 'LOTR',
  'THE LORD OF THE RINGS // a reading guide', [
    '<!--bg:sff-fantasy-->',
    '<h1>THE LORD OF THE RINGS</h1>',
    '<p><small>a reading guide to the one book, kept by a collector who owns four',
    'editions and is hunting a fifth. this page has NO film spoilers because when i',
    'built it there were no films worth the name. it is about the BOOK. — Barliman</small></p>',
    '<hr>',
    '<p class="fs-epi">"One Ring to rule them all, One Ring to find them, / One Ring',
    'to bring them all, and in the darkness bind them."<br>— the ring-verse,',
    '<i>The Lord of the Rings</i>, 1954</p>',
    '<p>First, the pedantry, because it matters. This is not a trilogy. Tolkien',
    'wrote one novel and his publisher, Allen &amp; Unwin, split it into three',
    'volumes across 1954 and 1955 to keep the price of paper down in a lean',
    'post-war market. <i>The Fellowship of the Ring</i> and <i>The Two Towers</i>',
    'came in 1954, <i>The Return of the King</i> in 1955, held back partly because',
    'Tolkien was still fighting with the index. Six books, three bindings, one',
    'story. Shelve it as one.</p>',
    '<p>The shape is a quest in reverse. Most quests go out to fetch a treasure. This',
    'one goes out to destroy one. Frodo Baggins inherits a magic ring from his uncle',
    'Bilbo and learns from the wizard Gandalf that it is the One Ring, the master',
    'ring the Dark Lord Sauron forged to control all the others and poured his own',
    'malice into. It cannot be used against him, because using it makes you into',
    'him. It cannot be hidden, because he will find it. It can only be unmade, and',
    'only in the fire where it was made, Mount Doom, in the heart of his own land.</p>',
    '<p class="fs-aside"><b>Did you know?</b> The Fellowship is nine, set against the',
    'nine Ringwraiths: four hobbits (Frodo, Sam, Merry, Pippin), two men (Aragorn',
    'and Boromir), the wizard Gandalf, the elf Legolas and the dwarf Gimli. Nine',
    'walkers against nine riders. Tolkien counted these things carefully.</p>',
    '<p>What lifts it above adventure is that the Ring works on everyone who carries',
    'it, and the closer you are to being able to do good with power, the more it',
    'wants you. Gandalf refuses to touch it. Galadriel is tempted and passes the',
    'test. Boromir, who only wants to save his city, falls. And the one who carries',
    'it to the end, Frodo, fails at the last step, claims it, and is saved only by',
    'Gollum and by an earlier act of pity. The Ring is not destroyed by strength. It',
    'is destroyed by mercy, almost by accident. That is not how adventure stories',
    'usually end, and it is why this one lasts.</p>',
    '',
    '<p class="fs-pull">Do not skip the appendices. The romance of Aragorn and',
    'Arwen, the only version of their whole love story, is hidden back there in',
    'Appendix A, where most readers never look.</p>',
    '<p>The appendices are the secret heart of the object. Sixty-odd pages at the',
    'back: the timelines, the family trees, the calendars, the writing systems, a',
    'primer on the pronunciation of Elvish, the tale of the years. They are the',
    'philologist showing his working. And the maps, drawn by Tolkien and his son',
    'Christopher, are not decoration, they are load-bearing, because the story is',
    'measured in real days of walking and you are meant to be able to trace it.</p>',
    '<pre>',
    'THE THREE VOLUMES, THE SIX BOOKS',
    '',
    '  THE FELLOWSHIP OF THE RING (1954)',
    '     Book I  .. the Shire, the road, the Black Riders, Rivendell.',
    '     Book II .. the Council, Moria, Lothlorien, the breaking of the Fellowship.',
    '  THE TWO TOWERS (1954)',
    '     Book III .. Rohan, the Ents, Helm’s Deep, the war in the north.',
    '     Book IV  .. Frodo, Sam and Gollum toward Mordor. the stairs of Cirith Ungol.',
    '  THE RETURN OF THE KING (1955)',
    '     Book V  .. Gondor, the siege, the Pelennor Fields, the last debate.',
    '     Book VI .. Mount Doom, the crowning, and the long road home to a spoiled Shire.',
    '     + THE APPENDICES. read them.',
    '</pre>',
    '<p>A word on the ending most readers forget. The hobbits come home to find the',
    'Shire itself has been industrialised and enslaved in their absence, and they',
    'have to clean it out themselves. Tolkien insisted this was not an allegory of',
    'anything, but the Scouring of the Shire is the quiet argument of the whole',
    'book: that the small and the local are worth defending, and that the ones who',
    'saved the world do not come back unchanged. Frodo is too wounded to stay. He',
    'goes over Sea. Sam plants the gardens and stays. That is the true ending.</p>',
    '<p>Where to go next. Back to the man himself and the deeper mythology at',
    '<a href="j-r-r-tolkien.geocities.ws">j-r-r-tolkien</a>. And if you want to see',
    'what fantasy looks like when a very different writer answers the epic in a',
    'quieter key, go straight to <a href="the-earthsea.geocities.ws">the-earthsea</a>',
    'and read Le Guin. She is not writing against Tolkien exactly, but she is asking',
    'what the balance costs.</p>',
    '<hr>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
    '<p><small>counter: 05540 · best viewed in Netscape at 800x600 · under',
    'construction (adding the Ballantine cover scans) · member, the fantasy webring',
    'for readers with too many editions · last updated 9 February · — Barliman</small></p>',
  ]);

// ---- Earthsea: single-novel reading guide (Le Guin, full seriousness) -------

const EARTHSEA = P('the-earthsea.geocities.ws', 'EARTHSEA',
  'EARTHSEA // the true name and the balance (Le Guin)', [
    '<!--bg:sff-fantasy-->',
    '<h1>EARTHSEA</h1>',
    '<p><small>a reading guide to Ursula K. Le Guin’s Earthsea, kept by a reader',
    'who thinks it is the best fantasy anyone has written and is prepared to argue',
    'the point at length and without raising her voice. — Tenar</small></p>',
    '<hr>',
    '<p class="fs-epi">"To light a candle is to cast a shadow."<br>— Ursula K. Le',
    'Guin, <i>A Wizard of Earthsea</i>, 1968</p>',
    '<p>Earthsea is an archipelago, a whole world of islands in a wide sea, and its',
    'magic runs on one clear law: to work magic on a thing you must know its true',
    'name, its name in the Old Speech, the language the world was made in. Names are',
    'power, and because they are power they are dangerous, and the wise use them',
    'sparingly. Le Guin began the sequence in 1968 with <i>A Wizard of Earthsea</i>,',
    'and it is, on the surface, the story every fantasy reader now knows by heart:',
    'a gifted boy goes to a school for wizards on the island of Roke and learns his',
    'craft. She wrote that plot a full generation before it became a franchise, and',
    'she did something with it that the imitators mostly missed.</p>',
    '<p>The boy is called Ged, though his true name is Sparrowhawk, and he is proud',
    'and impatient and hungry to be great. To show off, and in anger, he uses a',
    'spell beyond his strength and tears a hole in the world, and out of it comes a',
    'shadow, a nameless thing that hunts him across the whole archipelago. The book',
    'is the story of the chase, and its turn is one of the quiet masterstrokes of',
    'the genre: Ged stops running, turns, and pursues the shadow instead, and when',
    'he finally corners it at the edge of the world he names it with his own name.',
    'The shadow was himself, the death and cruelty in him, and to be whole he has to',
    'own it rather than defeat it.</p>',
    '',
    '<p class="fs-aside"><b>Worth saying plainly.</b> Le Guin made Ged and most of',
    'the people of Earthsea red-brown and black-skinned, and the villains of the',
    'first book white, in 1968, on purpose, and quietly, without a speech about it.',
    'Illustrators and film-makers whitewashed him for decades and she never stopped',
    'being angry about it. Read the books. She tells you what he looks like.</p>',
    '<p>What sets Earthsea against the epic is the idea of the Balance, the',
    'Equilibrium. Power in this world is not there to be maximised. The wise wizard',
    'is the one who knows when NOT to act, because every act of magic pulls on the',
    'whole, and to change one thing is to unbalance another. This is the opposite of',
    'the quest for the mighty artefact. Le Guin, whose father was the anthropologist',
    'Alfred Kroeber and who read Taoism all her life, built a fantasy where wisdom',
    'looks like restraint, and where the hero’s growth is a growth in humility.</p>',
    '<p class="fs-quote">"The wise needn’t ever know what the fool must learn: that',
    'when you seek power, you must first master yourself."<br>— the argument of the',
    'whole first book, in a line.</p>',
    '<pre>',
    'THE EARTHSEA BOOKS',
    '',
    '  A Wizard of Earthsea ...... 1968 .. Ged, Roke, the shadow. start here.',
    '  The Tombs of Atuan ........ 1971 .. Tenar, the dark labyrinth, a woman’s book.',
    '  The Farthest Shore ........ 1972 .. Ged old, a hole in the world, death.',
    '  ---- a long pause, and a rethinking ----',
    '  Tehanu .................... 1990 .. the same world after the epic. domestic. furious.',
    '  Tales from Earthsea ....... 2001 .. the stories the earlier books left out.',
    '  The Other Wind ............ 2001 .. the last one. the wall between living and dead.',
    '</pre>',
    '<p>Do not stop at the first three. When Le Guin came back to Earthsea in 1990',
    'with <i>Tehanu</i>, she turned the whole thing over and looked at who the first',
    'trilogy had left out: the women, the ordinary, the ones with no wizard-power',
    'and no place on Roke. It is a harder, angrier, more grown-up book, and it makes',
    'the early ones deeper in retrospect rather than smaller. She was interrogating',
    'her own younger work in public, which very few writers have the nerve to do.</p>',
    '<p>Le Guin was, and this is not a fan’s exaggeration, one of the major American',
    'writers of the century, in or out of the genre. She is the quiet counter to the',
    'epic: the world saved not by a great war but by a hard-won balance, by naming',
    'rather than conquering. For the great war itself, read Tolkien at',
    '<a href="j-r-r-tolkien.geocities.ws">j-r-r-tolkien</a>. For fantasy in a wholly',
    'different, gothic key, the crumbling castle and the ritual, go to',
    '<a href="mervyn-peake.geocities.ws">mervyn-peake</a>.</p>',
    '<hr>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
    '<p><small>counter: 04102 · best viewed at 800x600 · this page is not under',
    'construction, it is finished, like a good spell knows when to stop · a member',
    'of the fantasy webring · last updated 30 January · — Tenar</small></p>',
  ]);

// ---- Robert E. Howard: author profile (sword-and-sorcery) -------------------

const HOWARD = P('robert-e-howard.geocities.ws', 'HOWARD',
  'CONAN’S MAKER // Robert E. Howard', [
    '<!--bg:sff-fantasy-->',
    '<h1>CONAN’S MAKER</h1>',
    '<p><small>a profile of Robert Ervin Howard (1906-1936), kept by a pulp',
    'collector who will fight you about the difference between what Howard wrote and',
    'what other hands did to Conan after he died. these are Howard’s Conan. accept',
    'no pastiche. — Crom’s own, editor of the fanzine <i>Hyborian Age</i></small></p>',
    '<hr>',
    '<p class="fs-epi">"Let me live deep while I live; let me know the rich juices',
    'of red meat and stinging wine on my palate."<br>— Conan, in <i>Queen of the',
    'Black Coast</i>, 1934</p>',
    '<p>Robert E. Howard invented sword-and-sorcery, or near enough that the credit',
    'is his by right. A young Texan, largely self-taught, writing at a furious pace',
    'from the small town of Cross Plains to sell to the pulp magazines and support',
    'his household, he poured out boxers and cowboys and pirates and Crusaders, and',
    'in 1932 he created the one who outlived all the rest: Conan the Cimmerian, the',
    'barbarian. Conan first stalked into print in <i>Weird Tales</i> in December',
    '1932, in a story called "The Phoenix on the Sword", and the genre of the lone',
    'sword against the dark sorcerer started there.</p>',
    '<p>The setting is the Hyborian Age, a made-up slice of prehistory that Howard',
    'invented and back-dated between the sinking of Atlantis and the beginnings of',
    'recorded history, so that his imagined kingdoms could be as brutal and as free',
    'as he liked without answering to any real map. He even wrote a mock-scholarly',
    'essay, "The Hyborian Age", laying out its nations and migrations, the',
    'philologist’s trick turned to pulp ends. Aquilonia, Cimmeria, Stygia,',
    'Zamora: kingdoms with the gloss of history on them and none of the record.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/howard-01.jpg" alt=""><span class="indie-cap">Robert E. Howard (public domain)</span>',
    '<p class="fs-aside"><b>Did you know?</b> Howard and H.P. Lovecraft were long',
    'correspondents and friends who never met in person, arguing barbarism against',
    'civilisation across years of letters. Both wrote for <i>Weird Tales</i>. Their',
    'circle, Howard, Lovecraft and Clark Ashton Smith, were the three that magazine',
    'is remembered for.</p>',
    '<p>What people miss, dismissing Conan as muscle, is the temperature of the',
    'prose. Howard wrote at a headlong pace with a real ear, a driving rhythm and a',
    'melancholy under the violence. His theme, argued out in those letters with',
    'Lovecraft, was that civilisation is a thin and treacherous crust over barbarism,',
    'and that the barbarian, for all his savagery, is more honest and more alive',
    'than the decadent city he plunders. It is a bleak romanticism, and it is felt',
    'on every page, not bolted on.</p>',
    '<p class="fs-pull">"Barbarism is the natural state of mankind. Civilization is',
    'unnatural. It is a whim of circumstance. And barbarism must always ultimately',
    'triumph." — Howard, in a 1935 letter to Lovecraft. He believed it.</p>',
    '<pre>',
    'THE ESSENTIAL HOWARD (start with the real thing)',
    '',
    '  CONAN, the original stories (Weird Tales, 1932-36):',
    '    The Phoenix on the Sword ...... 1932 .. the first Conan.',
    '    The Tower of the Elephant ..... 1933 .. the one everyone names as best.',
    '    Queen of the Black Coast ...... 1934 .. Conan and Belit. the great one.',
    '    Beyond the Black River ........ 1935 .. the frontier one. civilisation vs. the wild.',
    '    The People of the Black Circle  1934 .. sorcery and the mountains.',
    '',
    '  BEYOND CONAN',
    '    Kull of Atlantis .............. the earlier brooding king. tried Conan’s throne first.',
    '    Solomon Kane .................. the grim Puritan avenger. sword AND scripture.',
    '    Bran Mak Morn ................. the last king of the Picts.',
    '',
    '  A NOTE: read the Howard originals, not the later "completions". accept no pastiche.',
    '</pre>',
    '<p>He died young and by his own hand in 1936, at thirty, on the morning his',
    'mother lay dying. He left a body of work written in barely a decade. Conan',
    'went on without him, in comics and paperbacks and film, much of it not his and',
    'not as good, which is why every Howard reader learns to check the byline.</p>',
    '<p>The line runs backward from Howard to the older invented mythologies. For',
    'the prose fantasy and the made pantheons that fed this whole tradition, and',
    'that Lovecraft loved too, read Lord Dunsany at',
    '<a href="lord-dunsany.geocities.ws">lord-dunsany</a>. And for the epic that grew',
    'up alongside the pulp and eventually eclipsed it in the shops, see',
    '<a href="the-lord-of-the-rings.geocities.ws">the-lord-of-the-rings</a>.</p>',
    '<hr>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
    '<p><small>counter: 03318 · best viewed in Netscape at 800x600 · under',
    'construction (scanning the Margaret Brundage covers) · a member of the fantasy',
    'webring, sword-and-sorcery division · last updated 14 March · By Crom · — the',
    'editor</small></p>',
  ]);

// ---- Lord Dunsany: close reading of one idea (the invented pantheon) --------

const DUNSANY = P('lord-dunsany.geocities.ws', 'DUNSANY',
  'THE GODS OF PEGANA // Dunsany’s invented pantheon', [
    '<!--bg:sff-fantasy-->',
    '<h1>THE GODS OF PEGANA</h1>',
    '<p><small>a close reading of one idea, the MADE pantheon, kept by a reader who',
    'thinks Dunsany is the most quietly influential fantasist nobody has read, and',
    'means to fix at least the second half of that. — a keeper of the older',
    'shrines</small></p>',
    '<hr>',
    '<p class="fs-epi">"Before there stood gods upon Olympus, or ever Allah was',
    'Allah, had wrought and rested MANA-YOOD-SUSHAI."<br>— Lord Dunsany, the opening',
    'of <i>The Gods of Pegana</i>, 1905</p>',
    '<p>Here is the idea, and it is a large one hidden in a small strange book.',
    'Before Dunsany, if you wanted gods in a story you borrowed them: the Greek',
    'pantheon, the Norse, the Christian scheme, whatever your reader already',
    'believed or half-believed. In 1905 Edward Plunkett, the eighteenth Baron',
    'Dunsany, an Irish peer with a castle and a great deal of time, published',
    '<i>The Gods of Pegana</i> and did something almost nobody had done in prose',
    'before: he invented an entire pantheon out of nothing, gods and priests and a',
    'cosmology and a mythology with no root in any real religion, and wrote it in',
    'the cadences of scripture so that it read as though it had always been holy.</p>',
    '<p>That is the whole seed of secondary-world fantasy. A made mythology,',
    'presented as if remembered rather than composed. In Pegana the little gods do',
    'the work of the world while the great god MANA-YOOD-SUSHAI sleeps, and the',
    'drummer Skarl beats a drum to keep him sleeping, because when the drumming',
    'stops and MANA wakes, the gods and the worlds are ended. It is a cosmology',
    'built on a held breath. No one had made a whole religion for the pleasure of',
    'the making before, and read it aloud: the whole apparatus of invented myth that',
    'the genre now runs on starts in that quiet, deliberately biblical prose.</p>',
    '<img class="indie-pic" src="assets/media/web/sff/dunsany-01.jpg" alt=""><span class="indie-cap">Lord Dunsany (Morrall-Hoole Studios, public domain)</span>',
    '<p class="fs-aside"><b>Did you know?</b> Dunsany wrote fast and, famously, with',
    'a quill pen, and rarely revised. He was for a while one of the most produced',
    'playwrights in the English-speaking world. The fantasy came in the early',
    'books: <i>Time and the Gods</i> (1906), <i>The Sword of Welleran</i> (1908),',
    'and the dream-land tales collected in <i>A Dreamer’s Tales</i> (1910).</p>',
    '<p>The influence runs in two directions and both of them matter to this ring.',
    'H.P. Lovecraft read Dunsany in 1919 and was, by his own account, knocked',
    'sideways: a whole run of Lovecraft’s early dream-cycle stories are frank',
    'Dunsany imitations, and the idea of invented, indifferent gods with unpronounce-',
    'able names owes Pegana a direct debt. And the young Tolkien read him too, and',
    'the notion that a fantasy could carry its own deep, self-consistent mythology,',
    'presented as ancient scripture, is in the air Tolkien breathed before <i>The',
    'Silmarillion</i>.</p>',
    '<p class="fs-pull">"I know that I shall never be as the gods that sit in Pegana."',
    'Read a page of Dunsany aloud and you can hear the King James Bible under it, put',
    'to the service of gods that never were.</p>',
    '<pre>',
    'A WAY IN TO DUNSANY (he is thin on the ground, hunt the second-hand shops)',
    '',
    '  The Gods of Pegana ......... 1905 .. the invented pantheon. start here.',
    '  Time and the Gods ......... 1906 .. more of Pegana. the same holy cadence.',
    '  The Sword of Welleran ..... 1908 .. heroes and cities that never were.',
    '  A Dreamer’s Tales ......... 1910 .. the dream-lands. the Lovecraft trigger.',
    '  The King of Elfland’s Daughter  1924 .. his one great fantasy NOVEL. luminous.',
    '',
    '  THE ONE TO READ IF YOU READ ONE NOVEL: The King of Elfland’s Daughter.',
    '</pre>',
    '<p>His later masterwork, <i>The King of Elfland’s Daughter</i> (1924), is the',
    'novel-length proof of the method: a village that wishes to be ruled by a magic',
    'lord, and gets its wish, and learns what it costs when the timeless world of',
    'Elfland leans into our own. It is one of the loveliest fantasy novels in the',
    'language and it goes in and out of print like a tide.</p>',
    '<p>Follow the pantheon forward to where Lovecraft’s friend took it into pulp,',
    'the Hyborian Age and Conan, at <a href="robert-e-howard.geocities.ws">',
    'robert-e-howard</a>. And for the gothic strand of fantasy, the ritual and the',
    'decay rather than the made gods, go to <a href="mervyn-peake.geocities.ws">',
    'mervyn-peake</a>.</p>',
    '<hr>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
    '<p><small>counter: 01890 · best viewed at 800x600 · under construction until',
    'MANA-YOOD-SUSHAI wakes · a member of the fantasy webring, the old-and-obscure',
    'shelf · last updated 5 December</small></p>',
  ]);

// ---- Mervyn Peake: author profile (the gothic fantasy without magic) --------

const PEAKE = P('mervyn-peake.geocities.ws', 'PEAKE',
  'GORMENGHAST // Mervyn Peake and the gothic without magic', [
    '<!--bg:sff-fantasy-->',
    '<h1>GORMENGHAST</h1>',
    '<p><small>a profile of Mervyn Peake (1911-1968), poet, illustrator, novelist,',
    'kept by a reader who wants you to understand that this is fantasy with not one',
    'wizard, not one spell, not one dragon, and it is still the strangest castle in',
    'the genre. — the under-gardener</small></p>',
    '<hr>',
    '<p class="fs-epi">"Titus is seven. His confines, Gormenghast."<br>— Mervyn',
    'Peake, the opening of <i>Titus Groan</i>, 1946</p>',
    '<p>Set one thing straight first, because it is the whole point of the page.',
    'There is no magic in Gormenghast. No wizards, no spells, no invented pantheon,',
    'no ring, no quest. And yet Peake’s books are shelved with the fantasists and',
    'belong there, because the castle itself is the fantastical thing: a vast,',
    'crumbling, half-ruined pile so old and so enormous that nobody has seen all of',
    'it, ruled not by a king’s power but by RITUAL, an endless choking round of',
    'ceremonies whose meaning was lost centuries ago and which must be performed',
    'exactly anyway. The fantasy is a world governed entirely by dead custom.</p>',
    '<p>Peake began <i>Titus Groan</i> (1946) and <i>Gormenghast</i> (1950), the two',
    'great volumes, and the fragmentary <i>Titus Alone</i> (1959) came later, written',
    'as the illness that would kill him was already taking his hand and his mind. He',
    'was first and always an illustrator, one of the finest of his age, and it shows',
    'in the prose: every character is drawn before he is described, grotesque and',
    'exact, and the sentences pile up detail the way a pen builds a face in',
    'cross-hatching. The books are slow, dense, gorgeous, and unlike anything else.</p>',
    '',
    '<p class="fs-aside"><b>Did you know?</b> Peake was an official war artist and',
    'was among those who drew Belsen shortly after its liberation. The horror he',
    'saw there is often read into the darkening of the later books. He also',
    'illustrated <i>Treasure Island</i> and <i>The Ancient Mariner</i>, and wrote',
    'genuinely good nonsense verse for children.</p>',
    '<p>The engine of the story is a single dangerous idea: rebellion against the',
    'ritual. Steerpike, a kitchen boy with a cold clever brain and no scruple at',
    'all, climbs out of the sculleries by murder and manipulation, exploiting the',
    'castle’s frozen customs against the family that keeps them. He is one of the',
    'great villains in English fiction, a self-made man in a world with no room for',
    'self-making, and Peake makes you half-admire him even as he grows monstrous.',
    'Against him is Titus, the seventy-seventh Earl, born in the first pages, a boy',
    'who wants only to be free of the whole machine of custom that made him.</p>',
    '<p class="fs-pull">The theme, if you want it bare: what does ritual do to the',
    'people who serve it, and what will a clever man without conscience do to a world',
    'that runs on forms it no longer understands.</p>',
    '<pre>',
    'THE GORMENGHAST BOOKS',
    '',
    '  Titus Groan .... 1946 .. the birth of Titus. the rise of Steerpike begins.',
    '  Gormenghast .... 1950 .. Titus a boy and youth. the reckoning with Steerpike.',
    '  Titus Alone .... 1959 .. Titus leaves the castle. unfinished, strange, damaged.',
    '',
    '  (a fourth, Titus Awakes, was reconstructed later from notes by his widow.)',
    '  READ THE FIRST TWO. they are the achievement. the third is for the devoted.',
    '</pre>',
    '<p>Peake is the proof that fantasy does not need a system of magic to be',
    'fantasy. It needs a world that runs on its own strange, complete, internal',
    'logic, and Gormenghast runs on ritual and decay the way Middle-earth runs on',
    'history and Earthsea on the balance. It is the gothic wing of the house.</p>',
    '<p>For fantasy that IS built on a made mythology and invented gods, go back to',
    '<a href="lord-dunsany.geocities.ws">lord-dunsany</a>. And for the fantasy that',
    'answers the epic with restraint rather than ruin, the true names and the',
    'balance, read Le Guin at <a href="the-earthsea.geocities.ws">the-earthsea</a>.</p>',
    '<hr>',
    '<p><small>[ <a href="sff-ring.geocities.ws">SF &amp; Fantasy Ring</a> ]</small></p>',
    '<p><small>counter: 02245 · best viewed in Netscape at 800x600 · this page is',
    'under construction and will be forever, as is only proper for Gormenghast · a',
    'member of the fantasy webring, gothic wing · last updated 18 November · — the',
    'under-gardener</small></p>',
  ]);

export const SFF_E = [TOLKIEN, LOTR, EARTHSEA, HOWARD, DUNSANY, PEAKE];
