// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH PHIL_B — Hellenistic to the medieval opening.
//
// Pages a 1990s reading group or student might have kept about the school and
// the thinkers they were working through: a sober class handout on the Stoics;
// a devotee's shrine to Plotinus; a set of book-reading notes on Augustine; the
// minutes of a Tuesday meeting on Boethius; a clean summary of Avicenna; and a
// handed-in undergraduate essay on Averroes. The works, dates and doctrines are
// real; the voices and the enthusiasms are the pages' own.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- The Stoics: the school handout (SHOWPIECE) -----------------------------

const STOICS = P('the-stoics.geocities.ws', 'THE STOICS',
  'THE STOICS // living according to nature', [
    '<!--bg:antiquity-->',
    '<h1>THE STOICS</h1>',
    '<p class="fs-epi">"Some things are up to us and some are not up to us." — Epictetus, Enchiridion I</p>',
    '<p><small>A handout for the Wednesday reading circle. This one is not about a',
    'single man. Stoicism is a SCHOOL, running some five hundred years, and to',
    'read it you have to hold three very different people in your head at once.',
    'Keep this sheet by you. — the convenor</small></p>',
    '<hr>',
    '<p>The school takes its name from a porch. Around 300 BC a merchant named',
    'Zeno of Citium, shipwrecked and washed up in Athens, began teaching under a',
    'painted colonnade, the <i>Stoa Poikile</i>, and his followers were called',
    'the people of the porch, the Stoics. What Zeno founded, Cleanthes and',
    'Chrysippus built into a whole system, three parts locked together: logic,',
    'physics and ethics. You do not get the famous calm without the physics that',
    'holds it up.</p>',
    '<p>The physics first, because everything hangs on it. The Stoics held that',
    'the cosmos is a single living body ordered through and through by reason.',
    'They called that ordering reason the LOGOS, a divine fire running through all',
    'things, and nothing falls outside it. What looks like chance is only cause we',
    'cannot yet see. To live well, then, is to live in agreement with this order,',
    'to live, in their phrase, ACCORDING TO NATURE, which means according to',
    'reason, both the reason in you and the reason in the whole.</p>',
    '<div class="fs-aside"><p>A word that trips people up: <i>apatheia</i>. It does',
    'NOT mean apathy, a dead numbness. It means freedom from the <i>pathe</i>, the',
    'passions that come from false judgements about what is good and bad. A Stoic',
    'sage still feels the first involuntary jolt, what they called a first',
    'movement. He simply does not consent to it and let it grow into grief or',
    'rage. Calm is a verdict, not a mood.</p></div>',
    '<p>From the physics comes the one idea everybody remembers, the heart of the',
    'whole practical teaching, set out most sharply by Epictetus, a freed slave',
    'who taught at Nicopolis and never wrote a line himself. His pupil Arrian took',
    'the notes we now read as the <i>Discourses</i> and the little handbook, the',
    '<i>Enchiridion</i>. Here is the division on which the rest turns.</p>',
    '<pre>',
    'THE DICHOTOMY OF CONTROL',
    '',
    '  UP TO US                         NOT UP TO US',
    '  (eph\' hemin)                     (ouk eph\' hemin)',
    '  --------------------------       --------------------------',
    '  our judgements                   our body',
    '  our impulses                     our reputation',
    '  our desires and aversions        our property',
    '  what we choose to pursue         office, station, the deeds',
    '  or avoid                         of other people',
    '',
    '  These are our own work,          These are not our work.',
    '  free, unhindered.                Fortune governs them.',
    '',
    '  RULE: place the good only in the first column.',
    '  Want the second column to be otherwise than it is,',
    '  and you have handed Fortune the keys to your peace.',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/phil/marcus-aurelius-01.jpg" alt=""><span class="indie-cap">Marcus Aurelius (photo: Daniel Martin, CC BY-SA 4.0)</span>',
    '<p>The mistake we make, on this account, is to invest our happiness in the',
    'second column, in the things Fortune lends and reclaims at will. The Stoic',
    'discipline is to draw the good back into the first column, into the use we',
    'make of our impressions, which is the one province truly our own. You cannot',
    'stop the storm. You can decline to let the storm decide whether you are well.</p>',
    '<blockquote class="fs-quote"><p>"You have power over your mind, not outside',
    'events. Realise this, and you will find strength."</p>',
    '<p><small>— Marcus Aurelius, Meditations</small></p></blockquote>',
    '<p>Which brings us to the third of our three men, and the strangest case in',
    'the history of philosophy: an emperor who kept a private notebook of Stoic',
    'exercises and never meant us to read it. Marcus Aurelius ruled Rome from AD',
    '161 to 180, fought long wars on the Danube, and in his tent at night wrote',
    'reminders to himself, in Greek, on how to meet the day. We call the notebook',
    'the <i>Meditations</i>. It is not a treatise. It is a man talking himself',
    'back into the doctrine, over and over, because he found it hard, as we do.</p>',
    '<div class="fs-aside"><p>Note the social sweep. Because one logos runs through',
    'all rational beings, the Stoics reached a bold conclusion for their day: every',
    'human being, slave or emperor, Greek or foreigner, shares in reason and so',
    'belongs to one community. This is the root of COSMOPOLITANISM, the idea that',
    'the city you truly belong to is the world.</p></div>',
    '<p class="fs-pull">The one thing Fortune cannot touch is the use you make of',
    'what Fortune sends.</p>',
    '<p><b>The quarrel with the Garden.</b> Just up the road, and just about the',
    'same age, sat the rival school of the Epicureans. Both promised peace of',
    'mind, and there the agreement ends. Epicurus taught that the gods are',
    'unconcerned and the universe is atoms falling and swerving in the void, with',
    'no providence steering it, so seek a quiet pleasure and be untroubled. The',
    'Stoics found this unbearable: for them the universe is exactly NOT indifferent,',
    'it is shot through with reason, and virtue, not pleasure, is the only good.',
    'You can read the other porch, the Garden, at',
    '<a href="epicurus.geocities.ws">epicurus.geocities.ws</a>, and it is worth',
    'doing, because the two schools are best understood against each other.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/epicurus-01.jpg" alt=""><span class="indie-cap">Epicurus, whose Garden the Porch argued against (public domain)</span>',
    '<p>Where did it go. Roman Stoicism gave way, in the centuries after Marcus,',
    'to a very different current, the Neoplatonism of Plotinus, who kept the idea',
    'of a divine order but turned it upward and inward toward a single source',
    'beyond being. If the porch has cooled and you want to see where the ancient',
    'world went next, the Enneads are waiting at',
    '<a href="plotinus.geocities.ws">plotinus.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>Under construction: a page on Seneca is promised for the spring.',
    'You are visitor 00312 · best viewed in Netscape at 800x600 · handout last',
    'revised 14 Mar</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Plotinus: the devotee's shrine -----------------------------------------

const PLOTINUS = P('plotinus.geocities.ws', 'PLOTINUS',
  'PLOTINUS // the flight of the alone to the Alone', [
    '<!--bg:antiquity-->',
    '<h1>PLOTINUS</h1>',
    '<p class="fs-epi">"The flight of the alone to the Alone." — Plotinus, Enneads VI.9</p>',
    '<p><small>my page for Plotinus (about AD 204 to 270), the last great pagan',
    'philosopher and the one who changed how I read everything. I came for the',
    'logic and I stayed for the ascent. if this page is a little rapturous, that',
    'is because he is. — Cassia</small></p>',
    '<hr>',
    '<p>Start with the problem he inherited and would not let go. If there is many,',
    'and clearly there is, a whole teeming world of separate things, then the many',
    'must come from a one, because to be anything at all is to be one thing, a',
    'unity, before it is anything else. Plotinus followed that thread all the way',
    'up, past being itself, to a source he simply calls THE ONE, or sometimes the',
    'Good. And here is the vertigo of it: the One is beyond being, beyond thought,',
    'beyond even the name he gives it. You cannot say what it IS. You can only say',
    'what it is not, and point.</p>',
    '<p>How does the many come from the One? Not by making, not by choosing, not by',
    'any act at all, because act would divide the One and it cannot be divided. It',
    'comes by EMANATION. Think of the sun, which does not decide to shine and loses',
    'nothing by shining. The One overflows out of its own fullness, and from that',
    'overflow proceeds the first radiance, NOUS, divine Intellect, in which all the',
    'Forms are thought together in one eternal act. From Nous in turn flows SOUL,',
    'which looks up to Intellect and down to the world, and gives life and order to',
    'the whole of nature. Three levels, three <i>hypostases</i>: the One, Intellect,',
    'Soul. Everything that exists is somewhere on that ladder of light, dimmer the',
    'further down it falls.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/plotinus-01.jpg" alt=""><span class="indie-cap">A bust thought to be Plotinus (public domain)</span>',
    '<p>And here is why he is not just a cosmologist but a guide. You and I are',
    'soul, and the soul remembers, faintly, where it came from. The whole of life',
    'rightly lived is a RETURN, a turning back up the ladder we came down, from the',
    'scattered world to Soul, from Soul to Intellect, and at the very summit, in a',
    'moment his student described him reaching only a handful of times, to union',
    'with the One itself. Not knowledge OF it, which would still be two things, a',
    'knower and a known, but a simple being-one-with, past all seeing. That is the',
    'line at the top of this page. The alone in you flies to the Alone.</p>',
    '<blockquote class="fs-quote"><p>"Withdraw into yourself and look. And if you do',
    'not find yourself beautiful yet, act as does the sculptor of a statue that is',
    'to be made beautiful: he cuts away here, he smooths there, until he has shown a',
    'lovely face upon his statue."</p>',
    '<p><small>— Plotinus, Enneads I.6</small></p></blockquote>',
    '<p>We have any of this only because of one devoted man. Plotinus taught in',
    'Rome and could barely be bothered to write, and when he did his handwriting',
    'and his eyesight were both failing. His pupil PORPHYRY gathered the essays',
    'after his death, arranged them into six groups of nine, and it is from the',
    'Greek for nine, <i>ennea</i>, that we have the title: the ENNEADS. Porphyry',
    'also wrote a life of his teacher, and it is where we get the famous detail',
    'that Plotinus seemed ashamed to be in a body at all.</p>',
    '<p>What he founded we now call NEOPLATONISM, though he would only have said he',
    'was reading Plato rightly. It became the great reservoir the next age drank',
    'from. The porch he learned his discipline from is at',
    '<a href="the-stoics.geocities.ws">the-stoics.geocities.ws</a>, and the reader',
    'who carried the One into the Christian world, weeping over these very books',
    'before his conversion, is at',
    '<a href="augustine.geocities.ws">augustine.geocities.ws</a>. Follow the light',
    'downstream and it runs for a thousand years.</p>',
    '<hr>',
    '<p><small>this page best viewed by candlelight, or failing that at 800x600 in',
    'Netscape · you are soul number 00188 to visit · last updated 2 Feb · a shrine,',
    'and I am not sorry</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Augustine: book-reading notes ------------------------------------------

const AUGUSTINE = P('augustine.geocities.ws', 'AUGUSTINE',
  'AUGUSTINE // reading notes: Confessions & City of God', [
    '<!--bg:scholastic-->',
    '<h1>AUGUSTINE OF HIPPO</h1>',
    '<p><small>Reading notes kept as I work through two of the books. These are',
    'MY notes on what Augustine (354 to 430) actually says, chapter by chapter,',
    'not a summary lifted from somewhere. Page references are to the Penguin',
    'editions on my shelf. Corrections welcome.</small></p>',
    '<hr>',
    '<p><b>BOOK ONE OF TWO: the Confessions (c. 397)</b></p>',
    '<p>First thing to unlearn: this is not a memoir in our sense. It is a prayer.',
    'The whole thing is addressed to God, in the second person, throughout, which',
    'is why it can be so raw. He is not telling US about the stolen pears or the',
    'years with his mistress or the long resistance to belief. He is telling God,',
    'and letting us listen. The famous restless line comes right at the start and',
    'sets the key for everything after it.</p>',
    '<blockquote class="fs-quote"><p>"You have made us for yourself, and our heart',
    'is restless until it rests in you."</p>',
    '<p><small>— Confessions I.1</small></p></blockquote>',
    '<p><u>Books X and XI, the ones the philosophers care about.</u> Having told',
    'the story, he stops and asks two hard questions. First, MEMORY. In Book X he',
    'goes wandering through it and is frightened by its size, the vast halls where',
    'the past is stored, present images of absent things. Where is the self, if the',
    'self is this? Second, and this is the passage I keep rereading, TIME. In Book',
    'XI he asks what time even is.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/augustine-01.jpg" alt=""><span class="indie-cap">Augustine of Hippo, by Philippe de Champaigne (public domain)</span>',
    '<p>His answer is dizzying and modern. The past is not, because it has gone.',
    'The future is not, because it has not come. The present has no length, for if',
    'it did you could divide it into a bit of past and a bit of future. So how can',
    'we measure time, which seems to be made of two nothings and a knife-edge?',
    'Because, he says, time is a stretching of the SOUL, a <i>distentio animi</i>.',
    'We hold the past as memory, the future as expectation, the present as',
    'attention, and the measuring happens in the mind, not out there in the world.',
    'His summary of the puzzle is the honest heart of the book:</p>',
    '<blockquote class="fs-quote"><p>"What then is time? If no one asks me, I know.',
    'If I wish to explain it to one who asks, I know not."</p>',
    '<p><small>— Confessions XI.14</small></p></blockquote>',
    '<div class="fs-aside"><p>Doctrine to keep straight while reading: ORIGINAL SIN.',
    'For Augustine the will is not neutral. Since Adam, human nature is disordered,',
    'turned in on itself, and cannot heal itself by effort alone. What saves is',
    'GRACE, given freely, not earned. This is the hinge of his long fight with',
    'Pelagius, who thought we could climb by our own strength. Augustine said no,',
    'and the Western church went with Augustine.</p></div>',
    '<p><b>BOOK TWO OF TWO: the City of God (413 to 426)</b></p>',
    '<p>Written after Rome was sacked in 410, when pagans were saying the city fell',
    'because it had abandoned the old gods for the Christians. Augustine answers on',
    'a scale that leaves the immediate quarrel far below. He divides all of human',
    'history between TWO CITIES, not two places but two loves. The earthly city is',
    'built on love of self reaching to contempt of God. The heavenly city is built',
    'on love of God reaching to contempt of self. The two are mixed together in',
    'this world, wheat and weeds in one field, and only sorted at the end. No',
    'earthly empire, Rome included, is the City of God, and none is meant to last.</p>',
    '<p><u>Where these ideas come from.</u> You can hear the Neoplatonist in him on',
    'every page, the ascent of the restless soul to a good beyond the world. He',
    'read Plotinus before he read deeply in scripture, and it broke his',
    'materialism open. That inheritance is at',
    '<a href="plotinus.geocities.ws">plotinus.geocities.ws</a>. And the man who',
    'took Augustine\'s problem of time and providence and turned it toward the',
    'question of whether God\'s foreknowledge leaves us free is at',
    '<a href="boethius.geocities.ws">boethius.geocities.ws</a>. Read them in that',
    'order and the thread holds.</p>',
    '<hr>',
    '<p><small>notes still growing, Book XIX not yet typed up · counter reads 00204',
    '· best viewed at 800x600 · last updated 9 Apr</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Boethius: the reading-group minutes ------------------------------------

const BOETHIUS = P('boethius.geocities.ws', 'BOETHIUS',
  'BOETHIUS // minutes: the Consolation, Tuesday', [
    '<!--bg:scholastic-->',
    '<h1>BOETHIUS &mdash; reading group minutes</h1>',
    '<p><small>Minutes of the Tuesday group. Present: seven of us. Text: the',
    '<i>Consolation of Philosophy</i>. Tea provided. These minutes taken by the',
    'secretary; blame me for any mangling of the argument.</small></p>',
    '<hr>',
    '<p><b>1. The situation of the book.</b> We spent the first twenty minutes on',
    'the setting, because it is unbearable and you cannot read the book without it.',
    'Boethius (about 477 to 524) was a Roman aristocrat, consul, the most learned',
    'man of his day, who set himself the task of translating all of Aristotle and',
    'Plato into Latin. He fell from favour under the Ostrogothic king Theodoric,',
    'was accused of treason, and wrote this book IN PRISON, awaiting an execution',
    'that duly came, at Pavia, by a particularly nasty method. So the calm of the',
    'book is hard-won. He is talking himself down from despair, with the clock',
    'running.</p>',
    '<p><b>2. Who is the lady?</b> Agreed quickly. Philosophy appears to him in his',
    'cell as a woman of changing height, her dress torn where squabbling schools',
    'have ripped off scraps, and she takes the role a doctor takes with a fevered',
    'patient. The whole book is a dialogue between the prisoner and her, moving',
    'from complaint up toward understanding, prose alternating with verse. R.',
    'pointed out this form has a name, <i>prosimetrum</i>, and we all wrote it down',
    'to sound clever later.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/boethius-01.jpg" alt=""><span class="indie-cap">Boethius (public domain)</span>',
    '<p><b>3. Fortune and her wheel.</b> The famous image, and the one everyone',
    'came knowing. Philosophy makes Fortune speak in her own defence. Fortune says,',
    'in effect: inconstancy is my whole nature, I never promised to stay, the wheel',
    'turns and that is the one thing about me you can rely on. What you are',
    'mourning was never yours, only lent. The group split on whether this is',
    'consoling or just a landlord\'s excuse. K. said it only bites if you already',
    'accept the next step, that the real good is not on the wheel at all.</p>',
    '<blockquote class="fs-quote"><p>"I turn the wheel that spins. I delight to see',
    'the high come down and the low ascend."</p>',
    '<p><small>— Fortune, in the Consolation, Book II</small></p></blockquote>',
    '<p><b>4. The hard part, and where we spent the rest of the evening: FORE-',
    'KNOWLEDGE and FREE WILL.</b> This is Book V and it is why philosophers still',
    'read the book. The problem, stated plainly by J.:</p>',
    '<pre>',
    '  THE WORRY',
    '  1. God knows today everything that will happen tomorrow.',
    '  2. If God knows today that I will do X tomorrow,',
    '     then it is already fixed that I will do X.',
    '  3. If it is already fixed, I am not free to do otherwise.',
    '  4. Therefore God\'s foreknowledge destroys my freedom.',
    '</pre>',
    '<p><b>5. Boethius\' answer.</b> This took real work and we are not sure we have',
    'it right. His move is to deny that God knows things in TIME at all. God does',
    'not sit in the past foreseeing a future not yet arrived. God is ETERNAL, and',
    'eternity, in his careful definition, is not endless time but the whole of life',
    'possessed at once, complete, all at a single stroke. So God does not FORE-see',
    'tomorrow. God simply SEES it, the way you see something happening in front of',
    'you now, present to your gaze. And seeing me choose freely does not make the',
    'choice unfree, any more than your watching me lift the teapot forces my hand.',
    'His slogan for the divine standpoint:</p>',
    '<blockquote class="fs-quote"><p>Eternity is "the whole, simultaneous and',
    'perfect possession of unending life."</p>',
    '<p><small>— Consolation, Book V, prose 6</small></p></blockquote>',
    '<p><b>6. Did it satisfy us?</b> Roughly half. M. objected that shifting God',
    'out of time relabels the problem rather than dissolving it, since if the',
    'eternal seeing is fixed then so is what is seen. The other half thought the',
    'distinction between a fact being certain and a fact being necessary does real',
    'work, and that Boethius saw it first. We did not settle it. We rarely do.</p>',
    '<p><b>7. Next week and links.</b> The problem of time here leans straight back',
    'on Augustine, whom several of us want to reread first, at',
    '<a href="augustine.geocities.ws">augustine.geocities.ws</a>. And the whole',
    'medieval habit of putting Aristotle to Christian use, which Boethius began by',
    'translating the logic, comes to its summit in Aquinas, at',
    '<a href="aquinas.geocities.ws">aquinas.geocities.ws</a>, which is where the',
    'group turns next month. Meeting closed 9pm.</p>',
    '<hr>',
    '<p><small>minutes filed · visitor 00151 · best viewed at 800x600 · this page',
    'last updated 21 May · new members welcome, second Tuesday</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Avicenna: the academic summary -----------------------------------------

const AVICENNA = P('avicenna.geocities.ws', 'AVICENNA',
  'AVICENNA // Ibn Sina, essence and existence', [
    '<!--bg:scholastic-->',
    '<h1>AVICENNA (IBN SINA)</h1>',
    '<p><small>A short, sober account of Ibn Sina (about 980 to 1037), the greatest',
    'philosopher of the Islamic golden age and, through his Latin translators, one',
    'of the makers of the medieval West. Third person throughout; sources at the',
    'foot.</small></p>',
    '<hr>',
    '<p>Abu Ali al-Husayn ibn Sina, Latinised as Avicenna, was born near Bukhara in',
    'Central Asia and was, by any measure, a prodigy. He tells us he had mastered',
    'the sciences of his day, medicine included, before he was eighteen, and that',
    'he read Aristotle\'s <i>Metaphysics</i> forty times without grasping it until a',
    'chance commentary by al-Farabi unlocked it. He wrote in Arabic and in Persian,',
    'through a restless life spent between courts, and left two works that shaped',
    'centuries.</p>',
    '<p>The first is the <i>Canon of Medicine</i> (<i>al-Qanun fi al-Tibb</i>), a',
    'systematic ordering of the whole medical knowledge of the age, which became',
    'the standard textbook in the universities of Europe as well as the Islamic',
    'world and was still being printed as a teaching text five hundred years on.',
    'The second, the properly philosophical one, is the vast <i>Book of Healing</i>',
    '(<i>al-Shifa</i>), a healing not of the body but of the soul\'s ignorance,',
    'covering logic, natural science, mathematics and metaphysics.</p>',
    '<p>His central metaphysical claim is a distinction that the Latin schoolmen',
    'took over wholesale: the distinction between ESSENCE and EXISTENCE. Consider',
    'what a thing IS, its essence, a horse, a triangle. The essence of a triangle',
    'tells you nothing about whether any triangle exists. Essence and existence are',
    'therefore really distinct: in every created thing, to be what it is and to be',
    'at all are two facts, not one. Existence is something ADDED to an essence that',
    'does not of itself contain it.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/avicenna-01.jpg" alt=""><span class="indie-cap">Avicenna, Ibn Sina (public domain)</span>',
    '<p>From this a proof of God follows. Everything whose essence does not include',
    'its own existence is merely POSSIBLE in itself; it need not be, and if it is,',
    'something else must account for its being. Trace the chain of such borrowed',
    'existence and it cannot run back for ever without explaining nothing. There',
    'must be one being whose very essence IS to exist, that borrows from nothing,',
    'the Necessary Existent, <i>wajib al-wujud</i>. That, for Avicenna, is God: not',
    'a first thing in a series but the being in whom the distinction between essence',
    'and existence collapses.</p>',
    '<div class="fs-aside"><p>The thought experiment he is remembered for, the',
    'FLYING MAN. Imagine a man created in an instant, full grown, suspended in',
    'empty air, in the dark, his limbs held apart so they touch nothing, with no',
    'memory and no sensation of any kind. Would he affirm anything? Avicenna says',
    'he would still affirm that HE IS, that his self exists, though he is aware of',
    'no body at all. The self is therefore known directly, prior to and apart from',
    'the body, which Avicenna takes as evidence that the soul is not identical with',
    'the flesh. Readers have argued ever since about how much the argument proves;',
    'few have been able to leave it alone.</p></div>',
    '<p>His influence ran two ways. Westward, through Latin translation at Toledo,',
    'his essence-existence distinction became a working part of scholastic',
    'metaphysics; Aquinas builds on it directly, at',
    '<a href="aquinas.geocities.ws">aquinas.geocities.ws</a>. Within the Islamic',
    'world his confident marriage of Aristotle with revelation drew a sharp reply',
    'from al-Ghazali, and it was left to the philosophers of the far West, above',
    'all Ibn Rushd of Cordoba, to answer that reply and defend philosophy again;',
    'see <a href="averroes.geocities.ws">averroes.geocities.ws</a>.</p>',
    '<hr>',
    '<p><small>Sources: Gutas, Avicenna and the Aristotelian Tradition; the Shifa',
    'in the McGinnis translation. · visitor 00137 · best viewed at 800x600 · page',
    'last updated 3 Jun</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Averroes: the handed-in undergraduate essay ----------------------------

const AVERROES = P('averroes.geocities.ws', 'AVERROES',
  'AVERROES // essay: the Commentator (Ibn Rushd)', [
    '<!--bg:scholastic-->',
    '<h1>AVERROES: THE COMMENTATOR</h1>',
    '<p><small>PHIL 214 &mdash; Medieval Philosophy &mdash; Essay 2. Student no.',
    '9930471. Word count 1,190. "Assess the claim that Ibn Rushd was the truest',
    'Aristotelian of the Middle Ages." I have put this up on my web space so my',
    'study group can read it. Grade pending.</small></p>',
    '<hr>',
    '<p>Abu al-Walid Muhammad ibn Rushd (1126 to 1198), known to the Latin West as',
    'Averroes, was born at Cordoba in Muslim Spain, served as a judge and court',
    'physician, and devoted his working life to a single scholarly project of',
    'extraordinary ambition: to recover the real Aristotle from centuries of',
    'Neoplatonist overlay and to explain him, book by book, to his own age. He',
    'wrote commentaries at three levels of depth, the short, the middle and the',
    'long, on nearly the whole Aristotelian corpus. To the Latins who read him in',
    'translation he was known by one title only, THE COMMENTATOR, as Aristotle was',
    'THE PHILOSOPHER. Dante puts him among the virtuous pagans of Limbo, apart, in',
    'a place of honour.</p>',
    '<p>His first target was a fellow Muslim. Al-Ghazali had written <i>The',
    'Incoherence of the Philosophers</i>, attacking the Aristotelian school (and',
    'Avicenna in particular, at',
    '<a href="avicenna.geocities.ws">avicenna.geocities.ws</a>) as unbelievers on',
    'points such as the eternity of the world. Averroes answered, blow for blow,',
    'in a book titled <i>The Incoherence of the Incoherence</i>, defending reason\'s',
    'right to its own conclusions. His considered view on the wider question is set',
    'out in the <i>Decisive Treatise</i>.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/averroes-01.jpg" alt=""><span class="indie-cap">Averroes, Ibn Rushd (photo: Sailko, CC BY 3.0)</span>',
    '<p>On FAITH and REASON his position is subtle and often flattened by his',
    'enemies. He did not hold, as the Latin caricature had it, that a thing could',
    'be true in philosophy and false in religion at the same time, the so-called',
    'double truth. His actual claim is that there is ONE truth reached by two',
    'roads. Scripture speaks to everyone, in images and persuasion; demonstration',
    'speaks to the trained few, in proof. Where the plain sense of scripture seems',
    'to contradict a proven conclusion, the scripture is to be read allegorically,',
    'because God, the author of both roads, cannot contradict himself. Philosophy',
    'and revelation are, in his image, "milk-sisters", nursed from one source.</p>',
    '<p>His most notorious doctrine concerns the INTELLECT, and here I think the',
    'essay title\'s claim starts to strain. Reading Aristotle\'s difficult remarks',
    'on the intellect in <i>De Anima</i>, Averroes concluded that the material',
    'intellect, the power by which we grasp universal truths, is ONE and the same,',
    'a single shared intellect, for the whole human race, not multiplied one to a',
    'person. Individuals think by being joined to it temporarily; what is immortal',
    'is the one intellect, not your private mind. The unity of the intellect is a',
    'bold reading, and it carried a heavy cost, since it seems to leave no personal',
    'immortality at all.</p>',
    '<div class="fs-aside"><p>Aftermath in the West. Latin translators carried',
    'Averroes into the universities, where a party of arts masters at Paris,',
    'Siger of Brabant among them, embraced the harder theses. This LATIN',
    'AVERROISM was condemned in 1277, and Aquinas wrote a whole treatise, <i>On',
    'the Unity of the Intellect against the Averroists</i>, to refute the shared-',
    'intellect doctrine. The quarrel is at',
    '<a href="aquinas.geocities.ws">aquinas.geocities.ws</a>.</p></div>',
    '<p>So, to the question set. Averroes was the most faithful EXPOSITOR of',
    'Aristotle the Middle Ages produced, and no medieval reader knew the texts more',
    'closely. But faithful exposition and true doctrine are not the same test, and',
    'on the intellect his fidelity to a hard Aristotelian reading led him where',
    'most of the tradition, Muslim, Jewish and Christian alike, would not follow.',
    'He recovered the Philosopher and he paid for it.</p>',
    '<hr>',
    '<p><small>Bibliography (as handed in): Averroes, <i>Decisive Treatise</i>,',
    'trans. Hourani; Leaman, <i>Averroes and His Philosophy</i>; lecture notes',
    'wk 6. · visitor 00121 · best viewed at 800x600 · uploaded 30 Jun</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

export const PHIL_B = [STOICS, PLOTINUS, AUGUSTINE, BOETHIUS, AVICENNA, AVERROES];
