// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — the scene & industry.
//
// Fan pages kept on a free host by a games obsessive: the arcade as a place,
// the games press, the cheat code, id Software, the shareware model, and the
// MUD. ORG/scene/document/studio pages, not first-person voices. The people,
// studios, dates and games are real; the enthusiasm and the grudges are the
// fan's.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- the arcade: the showpiece scene page -----------------------------------

const THE_ARCADE = P('the-arcade.geocities.ws', 'THE ARCADE',
  'THE ARCADE // insert coin to continue', [
    '<!--bg:games-culture-->',
    '<h1>THE ARCADE</h1>',
    '<p><small>a shrine to the coin-op arcade, the dark room that smelled of',
    'carpet and solder and forty machines all running their attract loops at',
    'once. i grew up in one of these. it is mostly a phone shop now. — Coop</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>INSERT COIN</p><p><small>— every machine, forever</small></p></div>',
    '<p>The arcade was a place before it was a nostalgia. You walked in with a',
    'pocket of change, the machines stood in rows with their marquees lit above',
    'the glass, and each one ran its ATTRACT MODE, a little unattended demo of',
    'itself, showing off the high scores and daring you to do better. You put a',
    'coin in the slot, or a token you had bought at the change booth, and the',
    'machine woke up and belonged to you until you died.</p>',
    '<div class="fs-aside"><p><b>DID YOU KNOW.</b> Many cabinets took tokens, not',
    'coins, so your money could not leave the building once you had changed it.',
    'The token was the arcade telling you, kindly, that you were staying.</p></div>',
    '<p>The controls were part of it. The joystick and the buttons were bolted to',
    'a steel panel built to survive a decade of angry teenagers, and every game',
    'felt different in the hand: the spinner on <i>Tempest</i>, the trackball on',
    '<i>Missile Command</i>, the yoke on a flying game, the twin sticks on',
    '<i>Robotron</i>. You did not own the game. You rented three minutes of it and',
    'you played as if the three minutes mattered, because they cost you.</p>',
    '<img class="indie-pic" src="assets/media/web/games/arcade-cabinet-01.jpg" alt=""><span class="indie-cap">An arcade cabinet (photo: Halcyanide, CC BY-SA 4.0)</span>',
    '<h2>THE HIGH SCORE</h2>',
    '<p>When you did well the machine asked for your INITIALS, three letters,',
    'because three letters was all the memory it could spare. You entered them by',
    'rolling a stick up and down through the alphabet, and then your AAA or ASS or',
    'your actual initials sat on the board in the attract loop for everyone who',
    'came after, until the power went off at closing and the volatile memory',
    'forgot you. The next morning the board was factory defaults again and you had',
    'to earn your place back.</p>',
    '<pre>',
    '     TODAY&apos;S BEST  --  ASTEROIDS DELUXE',
    '   ------------------------------------------',
    '     1ST    99850    AAA',
    '     2ND    74210    COO',
    '     3RD    68300    DAZ',
    '     4TH    51120    ???',
    '     5TH    44900    PAT',
    '   ------------------------------------------',
    '        HIGH SCORE RESETS AT POWER OFF',
    '</pre>',
    '<div class="fs-quote"><blockquote><p>"You had to be there when the board was',
    'live. A photograph of a high score proves nothing. The machine had to be on."',
    '</p></blockquote></div>',
    '<h2>THE UNWRITTEN RULES</h2>',
    '<p>Nobody printed these. Everybody knew them. Break one and the room let you',
    'know.</p>',
    '<pre>',
    '   1. A COIN ON THE GLASS MEANS &quot;I HAVE NEXT&quot;. DO NOT MOVE IT.',
    '   2. WINNER STAYS ON. LOSER PUTS ANOTHER COIN UP OR STEPS BACK.',
    '   3. NO NUDGING THE CABINET. TILT IS FOR PINBALL AND IT IS WATCHING.',
    '   4. DO NOT WATCH OVER A STRANGER&apos;S SHOULDER AND BREATHE.',
    '   5. IF YOU GET THE KILL SCREEN, YOU TELL EVERYONE. THAT IS THE LAW.',
    '   6. THE CHANGE BOOTH IS NOT A BANK. BRING YOUR OWN NOTES.',
    '</pre>',
    '<div class="fs-pull"><p>Winner stays on. Loser puts another coin up. The whole',
    'social order of the room, in six words.</p></div>',
    '<img class="indie-pic" src="assets/media/web/games/arcade-hall-01.jpg" alt=""><span class="indie-cap">An arcade floor (photo: Funspotarcade, CC BY-SA 4.0)</span>',
    '<h2>THE DECLINE</h2>',
    '<p>What killed the arcade was the living room. Through the 1980s the home',
    'consoles caught up, and by the 1990s the port on your Mega Drive or your SNES',
    'was close enough to the cabinet that the trip into town stopped being worth',
    'it. Why pay a coin a go when the cartridge sat in the machine at home and',
    'never asked for another coin. The arcades held on with the things a console',
    'could not do, the big fighting cabinets and the light-gun rigs and the sit-in',
    'racers, and then those faded too. The room went quiet one machine at a time.</p>',
    '<p>For the tricks that beat the machines, the level warps and the button',
    'sequences whispered across the floor, see <a href="the-cheat-code.geocities.ws">',
    'the-cheat-code</a>. For the magazines that carried the arcade home in print,',
    'the reviews and the tip lines, see <a href="the-games-magazine.geocities.ws">',
    'the-games-magazine</a>.</p>',
    '<hr>',
    '<p><small>UNDER CONSTRUCTION. more cabinets to add. counter: 08192 · best',
    'viewed in Netscape at 800x600 · a webring-for-gamers page · last updated 2 Aug',
    '</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- the games magazine: the games press ------------------------------------

const THE_GAMES_MAGAZINE = P('the-games-magazine.geocities.ws', 'GAMES MAG',
  'THE GAMES MAGAZINE // reviewed out of 100', [
    '<!--bg:games-culture-->',
    '<h1>THE GAMES MAGAZINE</h1>',
    '<p><small>before the web this is how you knew what was good. a stack of these',
    'under the bed, the covers falling off, the cover tape long lost. — Coop</small></p>',
    '<hr>',
    '<p>The games magazine was the trade paper of a hobby that the papers of record',
    'ignored. It reviewed the games, it printed the news, it ran the tip lines and',
    'the pen-pal columns, and on the good ones it came with a COVER TAPE or a cover',
    'disk stuck to the front, a cassette or a floppy carrying demos and a type-in',
    'or two. You bought it for the tape and stayed for the reviews.</p>',
    '<h2>THE SCORE OUT OF 100</h2>',
    '<p>The British magazines reviewed out of 100 and argued about it forever. A',
    'game in the nineties was a classic, a game in the fifties was for the bargain',
    'bin, and the magazines that gave a big number a Gold or a Sizzler or a Crash',
    'Smash sold you the badge as much as the review. The number was a fight every',
    'month between the writers who loved the game and the ones who did not.</p>',
    '<div class="fs-aside"><p><b>THE TITLES.</b> <i>Zzap!64</i> for the Commodore',
    '64, <i>Crash</i> for the Spectrum, both out of Ludlow from Newsfield.',
    '<i>Computer and Video Games</i>, the CVG, one of the first and the broadest.',
    'And across the Atlantic <i>Nintendo Power</i>, the house magazine that mailed',
    'the maps and the counsellor tips straight from Nintendo.</p></div>',
    '<h2>THE TYPE-IN LISTING</h2>',
    '<p>The pages carried PROGRAM LISTINGS, whole games printed as BASIC you keyed',
    'in yourself, line by line, checksum column down the side so you could find the',
    'line you had fat-fingered. An afternoon of typing and a saved cassette and you',
    'had a game the shops never sold, written by a reader, printed for free.</p>',
    '<pre>',
    '   10 REM *** LISTING OF THE MONTH ***',
    '   20 PRINT &quot;PRESS ANY KEY TO PLAY&quot;',
    '   30 GET A$: IF A$=&quot;&quot; THEN 30',
    '   40 GOSUB 1000 : REM SET UP SCREEN',
    '   50 GOTO 200  : REM MAIN LOOP',
    '   .. keep going, the checksum is in the margin ..',
    '</pre>',
    '',
    '<h2>THE TIP LINE</h2>',
    '<p>At the back sat the tips pages, the readers writing in with the POKE that',
    'gave infinite lives and the sequence that skipped a level, and a premium-rate',
    'phone line you were told not to call without asking whoever paid the bill.',
    'This is where a cheat travelled from one bedroom to the whole country, and',
    'the magazine was the post office. The codes themselves live at',
    '<a href="the-cheat-code.geocities.ws">the-cheat-code</a>.</p>',
    '<blockquote><p>"We are the readers writing to the readers. The publisher just',
    'owns the staples." — a letters page, more or less</p></blockquote>',
    '<p>The magazine also sent you back into town with a shopping list, because the',
    'reviews were of the machines you fed with coins. For the room those machines',
    'stood in, see <a href="the-arcade.geocities.ws">the-arcade</a>.</p>',
    '<hr>',
    '<p><small>counter: 03571 · best viewed in Netscape at 800x600 · SPOILERS in the',
    'tips section below the fold, you were warned · last updated 21 Jul</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- the cheat code: the document page --------------------------------------

const THE_CHEAT_CODE = P('the-cheat-code.geocities.ws', 'CHEAT CODE',
  'THE CHEAT CODE // up up down down left right left right B A', [
    '<!--bg:games-culture-->',
    '<h1>THE CHEAT CODE</h1>',
    '<p><small>a document. everything the playground knew and half of it was even',
    'true. WALKTHROUGH AND CHEATS BELOW, spoilers throughout, do not scroll if you',
    'want the game clean. — Coop</small></p>',
    '<hr>',
    '<p>A cheat code is a way in that the game left open, sometimes on purpose so',
    'the testers could reach the late levels without playing the early ones, and',
    'sometimes an accident that a player found and passed on. It travelled by word',
    'of mouth in the playground, by letter in the magazine tip lines, and by the',
    'crack screen on a copied tape, and by the time it reached you nobody knew who',
    'found it first.</p>',
    '<h2>THE KONAMI CODE</h2>',
    '<p>The most famous of them all, put into Konami games by the developers and',
    'first widely known from <i>Gradius</i> and then <i>Contra</i> on the NES,',
    'where it handed you a full stock of lives and made the game survivable. Enter',
    'it at the title screen.</p>',
    '<pre>',
    '   UP  UP  DOWN  DOWN  LEFT  RIGHT  LEFT  RIGHT  B  A',
    '   ( on Contra, then START, and you begin with 30 lives )',
    '</pre>',
    '<div class="fs-aside"><p><b>NOTE.</b> On some later versions people added',
    'SELECT and pressed it for two players. The core ten inputs are the ones that',
    'stuck, and a generation can still key them in without thinking.</p></div>',
    '<h2>THE KINDS OF CHEAT</h2>',
    '<p>They were not all the same thing, and the arguments about which counted as',
    '"cheating" and which was just clever went on for years.</p>',
    '<pre>',
    '   LEVEL SELECT  --  a hidden menu, warp straight to any stage',
    '   INFINITE LIVES --  the death counter never goes down',
    '   INVULNERABILITY -- nothing can touch you, sometimes typed &quot;IDDQD&quot;',
    '   MAP / WARP ZONE -- a pipe or a door that skips whole worlds',
    '   DEBUG MODE    --  the developers&apos; own tools, left switched on',
    '</pre>',
    '',
    '<h2>THE POKE AND THE CRACKED LOADER</h2>',
    '<p>On the home micros the cheat went deeper than a code typed at the title',
    'screen. A POKE wrote a value straight into a memory address while the game',
    'ran, so POKE the address that held your lives with 255 and you had all the',
    'lives the byte could count. The magazines printed columns of POKEs for every',
    'game. To use them you often loaded the game, broke in, and poked before you',
    'let it go.</p>',
    '<pre>',
    '   LOAD &quot;&quot;',
    '   ( wait for the loading screech to finish )',
    '   POKE 35899,255 : REM MINER WILLY NEVER RUNS OUT',
    '   RUN',
    '</pre>',
    '<p>On the cracked copies the crackers went one better and built the cheats',
    'into the CRACKED LOADER itself, a menu that came up before the game with the',
    'trainer options already there, toggle infinite lives, toggle infinite time,',
    'and their greetings scrolling past underneath. The loader was where the crack',
    'group signed its work. That whole distribution grew its own economy; see',
    '<a href="the-shareware-model.geocities.ws">the-shareware-model</a> for the',
    'legitimate cousin, try-before-you-buy over the same phone lines and disks.</p>',
    '<blockquote><p>"Everyone at school knew the code. Nobody at school knew where',
    'it came from. That is a cheat code." — a lunch queue, 1991</p></blockquote>',
    '<p>Many of these codes reached you folded inside a magazine, on the tips',
    'pages, next to the reviews. See <a href="the-games-magazine.geocities.ws">',
    'the-games-magazine</a> for the post office they travelled through.</p>',
    '<hr>',
    '<p><small>counter: 05040 · best viewed in Netscape at 800x600 · corrections to',
    'the handle above, i will fight you about the SELECT button · last updated 9 Aug',
    '</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- id Software: the studio page -------------------------------------------

const ID_SOFTWARE = P('id-software.geocities.ws', 'ID SOFTWARE',
  'id Software // shareware, engines, and the mod', [
    '<!--bg:games-culture-->',
    '<h1>id Software</h1>',
    '<p><small>the studio that took the shareware disk and the PC and built the',
    'first-person shooter on top of them. lower-case id, as in the Freud, and they',
    'will tell you it rhymes with "did". — Coop</small></p>',
    '<hr>',
    '<p>id Software formed in 1991 out of a group of programmers and artists who',
    'had been making games for a magazine disk and decided to make them for',
    'themselves. The core was John Carmack on the engine, John Romero on the design',
    'and the level building, Adrian Carmack (no relation) on the art, and Tom Hall',
    'on the design and the writing. A small room, a lot of pizza, and a run of',
    'games that changed what the PC was for.</p>',
    '<h2>THE RUN</h2>',
    '<p>They announced themselves with <i>Commander Keen</i> in 1990, a side-scroller',
    'on the PC that scrolled as smoothly as a console when everyone said the PC',
    'could not, because Carmack had worked out how. Then the shift to the first',
    'person: <i>Wolfenstein 3D</i> in 1992, the Nazi-shooting maze that made the',
    'genre; <i>Doom</i> in 1993, which made it a phenomenon; and <i>Quake</i> in',
    '1996, true 3D and true multiplayer over the network.</p>',
    '<pre>',
    '   1990   Commander Keen        the smooth-scrolling PC platformer',
    '   1992   Wolfenstein 3D        the first-person shooter takes shape',
    '   1993   Doom                  shareware, deathmatch, the phenomenon',
    '   1996   Quake                 real 3D, real network multiplayer',
    '</pre>',
    '<div class="fs-aside"><p><b>THE ENGINE.</b> Carmack built a new engine for each',
    'game and treated the technology as the real product, then licensed the engine',
    'to other studios. The idea that an engine was a thing you could sell, apart',
    'from the game on top of it, is partly his.</p></div>',
    '<img class="indie-pic" src="assets/media/web/games/romero-01.jpg" alt=""><span class="indie-cap">John Romero of id (photo: Official GDC, CC BY 2.0)</span>',
    '<h2>THE MOD</h2>',
    '<p>The thing that made id different was that they let you take it apart.',
    '<i>Doom</i> kept its levels and art in a separate file, the WAD, and players',
    'worked out how to build their own, so within a year there were thousands of',
    'homemade levels passed around the bulletin boards. Then id did the thing',
    'almost no one did: they RELEASED THE SOURCE CODE, <i>Doom</i> in 1997 and',
    'later <i>Quake</i>, under a free licence, so the engines outlived the company',
    'that shipped them and run on every machine anyone has ported them to since.</p>',
    '<blockquote><p>"In the information age, the barriers just aren\'t there. The',
    'barriers are self-imposed." — John Carmack</p></blockquote>',
    '<p>id built its business on giving the first slice away. The full story of',
    'that, the free episode and the cheque in the post, is at',
    '<a href="the-shareware-model.geocities.ws">the-shareware-model</a>. And the',
    'game that carried it furthest has its own shrine at',
    '<a href="doom.geocities.ws">doom</a>.</p>',
    '<hr>',
    '<p><small>counter: 06660 · best viewed in Netscape at 800x600 · greets to',
    'everyone still making WADs · last updated 14 Aug</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- the shareware model: the document page ---------------------------------

const THE_SHAREWARE_MODEL = P('the-shareware-model.geocities.ws', 'SHAREWARE',
  'THE SHAREWARE MODEL // episode one is free', [
    '<!--bg:games-culture-->',
    '<h1>THE SHAREWARE MODEL</h1>',
    '<p><small>a document on how a bedroom studio sold a game before the shops would',
    'stock it. try before you buy, and mostly you did not buy, but enough people',
    'did. — Coop</small></p>',
    '<hr>',
    '<p>Shareware was a way of selling that gave you the software first and asked',
    'for the money second, on trust. You got the program free, from a friend, off',
    'a bulletin board, on a cover disk, from a catalogue of disks a company mailed',
    'you for the price of the postage, and if you liked it and kept using it you',
    'were asked to send the author a cheque and register. No shop, no distributor,',
    'no shelf. The copying that publishers feared was the whole delivery system.</p>',
    '<h2>EPISODE ONE FREE</h2>',
    '<p>For games the master stroke came from Apogee, Scott Miller\'s company, and',
    'it is sometimes called the Apogee model. You split the game into EPISODES.',
    'Episode one you gave away complete and free, a real game with a real ending,',
    'good enough that people copied it far and wide for you. Episodes two and three',
    'you sold, and you could only get them from the author, by post, with a cheque.',
    'id Software used exactly this for <i>Wolfenstein 3D</i> and <i>Doom</i>; see',
    '<a href="id-software.geocities.ws">id-software</a>.</p>',
    '<pre>',
    '   HOW IT WORKED',
    '   -----------------------------------------------',
    '   1. EPISODE ONE spreads for free. costs you nothing.',
    '   2. PLAYER FINISHES IT, wants more, no shop sells it.',
    '   3. PLAYER MAILS A CHEQUE to the address in the game.',
    '   4. EPISODES TWO AND THREE arrive on a disk by post.',
    '   -----------------------------------------------',
    '   the free copy is the advert AND the product',
    '</pre>',
    '<div class="fs-aside"><p><b>REGISTER, PLEASE.</b> Games nagged gently. A screen',
    'at the end of the free episode gave the address and the price and told you',
    'that the people who wrote this ate food. The honour system did the rest.</p></div>',
    '<img class="indie-pic" src="assets/media/web/games/floppy-disk-01.jpg" alt=""><span class="indie-cap">A 5.25-inch floppy disk (photo: Muralikrishna M, CC BY-SA 4.0)</span>',
    '<h2>THE BBS AND THE DISK CATALOGUE</h2>',
    '<p>The plumbing under all of it was the BULLETIN BOARD SYSTEM, a computer in',
    'somebody\'s spare room with a modem and a phone line, that you dialled up',
    'directly to download files and leave messages. Shareware moved across the',
    'BBSes, and it moved by post through the shareware libraries, companies that',
    'sold disks of collected shareware for a small fee, the fee being for the disk',
    'and the mailing and not for the programs, which were free to pass on. A lot of',
    'shovelware rode along on those disks, but so did the real thing.</p>',
    '<blockquote><p>"The idea was simple. Let people play the game, and if they like',
    'it, they will pay for it." — the shareware pitch, in a hundred readme files</p>',
    '</blockquote>',
    '<p>The same disks and boards carried the cracked and the trained copies too,',
    'the ones with the cheats built in; the difference was whether the cheque ever',
    'went in the post. For the codes and the trainers, see',
    '<a href="the-mud.geocities.ws">the-mud</a> for where the dial-up crowd hung',
    'their text worlds off the same modems.</p>',
    '<hr>',
    '<p><small>counter: 04096 · best viewed in Netscape at 800x600 · UNDER',
    'CONSTRUCTION, a page on the BBS door games is coming · last updated 16 Aug',
    '</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- the MUD: the scene page ------------------------------------------------

const THE_MUD = P('the-mud.geocities.ws', 'THE MUD',
  'THE MUD // a world made of words', [
    '<!--bg:games-culture-->',
    '<h1>THE MUD</h1>',
    '<p><small>the Multi-User Dungeon, the online game before anyone drew a picture',
    'of one. all text, all imagination, and a phone bill to make your parents cry.',
    '— Coop</small></p>',
    '<hr>',
    '<p>A MUD is a shared world made of words. You dial in, or you log on across the',
    'university network, and the machine tells you where you are in prose, and you',
    'type what you want to do, and it tells you what happens, and so does everyone',
    'else who is logged in at the same time. It is a text adventure that other',
    'people are inside with you, wandering the same rooms, talking, fighting,',
    'helping and robbing each other, all at once, in real time.</p>',
    '<h2>ESSEX, 1978</h2>',
    '<p>It started at the University of Essex in 1978. Roy Trubshaw wrote the first',
    'version on the university\'s DEC mainframe, and Richard Bartle took it on and',
    'built it out into the game that gave the whole form its name, MUD1. When the',
    'university opened its machine to the outside network at night, players dialled',
    'in from everywhere the phone reached, and a genre was born on a computer that',
    'was meant to be doing sums.</p>',
    '<pre>',
    '   You are in a dimly lit hall. Passages lead north',
    '   and east. A brass lantern rests on the flagstones.',
    '   A WIZARD is here.',
    '   &gt; get lantern',
    '   Taken.',
    '   &gt; north',
    '</pre>',
    '<div class="fs-aside"><p><b>THE WORD.</b> Bartle and Trubshaw. Essex. 1978.',
    'People argue about a great deal in this hobby, but the MUD has a birthplace and',
    'two names on the paperwork, and they are those.</p></div>',
    '<img class="indie-pic" src="assets/media/web/games/bartle-01.jpg" alt=""><span class="indie-cap">Richard Bartle, co-author of MUD (photo: J. G. Bartle, CC BY-SA 3.0)</span>',
    '<h2>PLAYERS AND WIZARDS</h2>',
    '<p>You started as a lowly player and you worked your way up by playing, and if',
    'you reached the top you became a WIZARD (or a witch), which was the game\'s way',
    'of turning its best players into its staff. Wizards had powers over the world',
    'and duties in it, they ran events and settled fights and built new rooms, and',
    'the social order of the MUD, who could do what to whom, was a real thing people',
    'took seriously. Bartle later sorted the players into four types, the achievers',
    'and the explorers and the socialisers and the killers, and that map of who',
    'wants what from a game outlived the text worlds it was drawn from.</p>',
    '<blockquote><p>"You haven\'t truly played a MUD until you have been a wizard, and',
    'you haven\'t truly been a wizard until you have made a room." — a MUD admin, on',
    'a mailing list</p></blockquote>',
    '<p>The MUD grew straight out of the single-player text adventure, the parser',
    'and the room descriptions and the grue in the dark; for the ancestor, see',
    '<a href="zork.geocities.ws">zork</a>. And it hung off the same modems and',
    'bulletin boards that carried the free games around; for that plumbing, see',
    '<a href="the-shareware-model.geocities.ws">the-shareware-model</a>.</p>',
    '<hr>',
    '<p><small>counter: 01978 · best viewed in Netscape at 800x600 · a',
    'webring-for-gamers member · mind the phone bill · last updated 18 Aug</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

export const GAME_F = [
  THE_ARCADE,
  THE_GAMES_MAGAZINE,
  THE_CHEAT_CODE,
  ID_SOFTWARE,
  THE_SHAREWARE_MODEL,
  THE_MUD,
];
