// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH FS-A — Frankfurt School, the first-generation core.
//
// Fan pages kept on a free host, each ABOUT a thinker, a book or an episode and
// never in the thinker's own voice. A sober tutorial on Horkheimer and the idea
// of a critical theory; a devotee's shrine to Adorno and the negative dialectic;
// a clean history of the Institut; two sets of reading notes, on the Dialectic
// of Enlightenment and on the Eclipse of Reason; and a reading group's page on
// Minima Moralia. The authors, titles, dates and quotations are real; the
// warmth and the grudges are the fans'.

import { fileBlock } from './files.js';

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Horkheimer: the sober tutorial -----------------------------------------

const HORKHEIMER = P('horkheimer-critical-theory.geocities.ws', 'HORKHEIMER',
  'MAX HORKHEIMER // what makes a theory critical', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/horkheimer-01.jpg" alt=""><span class="indie-cap">Max Horkheimer, 1937 (public domain)</span>',
    '<h1>MAX HORKHEIMER: WHAT MAKES A THEORY CRITICAL</h1>',
    '<p><small>a clean summary for people coming to this cold, kept by a reference',
    'librarian who got tired of pointing students at photocopies. no hero-worship',
    'here, just the shape of the argument, laid out plainly.</small></p>',
    '<hr>',
    '<h2>The man and the post</h2>',
    '<p>Max Horkheimer (1895–1973) took over the Institut fur Sozialforschung in',
    '1930 and held it, through exile and return, for most of the rest of his life.',
    'He was less a system-builder than a director in the full sense: he set the',
    'programme, gathered the people, and kept a difficult group pointed at a',
    'shared question. For the house he ran, see',
    '<a href="institut-fur-sozialforschung.geocities.ws">institut-fur-sozialforschung</a>.</p>',
    '<hr>',
    '<h2>The 1937 essay</h2>',
    '<p>The key text is "Traditional and Critical Theory" (1937). The distinction',
    'is simple to state and hard to live up to. TRADITIONAL theory takes society',
    'as a set of facts out there and builds a neutral mirror of them, the way the',
    'natural sciences model nature. It asks how things work and leaves the frame',
    'itself untouched. CRITICAL theory refuses the pose of the detached observer.',
    'It grasps society as a whole that human beings have made and could therefore',
    'change, and it knows that the theorist is inside the object being studied,',
    'not hovering above it.</p>',
    '<p>So the difference is not the subject matter, it is the stance. A critical',
    'theory carries its own interest in emancipation openly rather than pretending',
    'to have none. That is the move the whole school turns on.</p>',
    '<hr>',
    '<h2>Instrumental reason, and the later turn</h2>',
    '<p><i>Eclipse of Reason</i> (1947), first given as lectures at Columbia, is',
    'the darker sequel. Horkheimer splits reason in two. OBJECTIVE reason once',
    'asked which ends were worth pursuing, whether a life or an order was good.',
    'SUBJECTIVE or instrumental reason asks only about means: given any end at',
    'all, what is the efficient way to reach it. As the second drives out the',
    'first, reason keeps its power to calculate and loses its power to judge, and',
    'in the end it turns on itself. There is a fuller reading of that book at',
    '<a href="eclipse-of-reason.geocities.ws">eclipse-of-reason</a>.</p>',
    '<p>With Adorno he wrote the book that states the whole grim thesis, the',
    '<i>Dialectic of Enlightenment</i> (1947). Notes on it live at',
    '<a href="dialectic-of-enlightenment.geocities.ws">dialectic-of-enlightenment</a>.</p>',
    '<div class="fs-aside"><p>A small correction one hears too rarely: Horkheimer',
    'did not think reason was the enemy. The argument is that a reason which has',
    'forgotten how to ask about ends becomes dangerous, not that thinking as such',
    'should be given up. He wanted more reason of the older kind, not less',
    'reason.</p></div>',
    '<hr>',
    '<h2>A short critical note</h2>',
    '<p>The standing objection is that the later Horkheimer leaves no lever. If',
    'instrumental reason has colonised everything, including the minds that would',
    'resist it, where does the critique get to stand? The second generation took',
    'exactly this problem as its starting point and answered it with a theory of',
    'communication. That is a real weakness, and it is also why the work still',
    'gets argued over rather than shelved.</p>',
    '<hr>',
    '<p><small>visitors: 00612 · best viewed at 800x600 · under construction, the',
    'bibliography needs page numbers · last updated 8 Oct</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a member page. « prev · random · next »',
    '</small></p>',
    fileBlock(25),
  ]);

// ---- Adorno: the devotee's shrine (SHOWPIECE) -------------------------------

const ADORNO = P('adorno-negative-dialectics.geocities.ws', 'ADORNO',
  'THEODOR W. ADORNO // the negative dialectic', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/adorno-01.jpg" alt=""><span class="indie-cap">Theodor W. Adorno (photo: Jeremy J. Shapiro, CC BY-SA)</span>',
    '<h1>THEODOR W. ADORNO: THE NEGATIVE DIALECTIC</h1>',
    '<p class="fs-epi">"The whole is the false." — Adorno</p>',
    '<p><small>a shrine, and i am not going to pretend otherwise. i have been',
    'reading him since a teacher put a photocopied aphorism on the overhead and it',
    'reorganised my head. everything below is me trying to say why. — R.</small></p>',
    '<hr>',
    '<p>Theodor W. Adorno (1903–1969) is the one the others orbit. Composer',
    'first, pupil of Alban Berg in Vienna, then the sharpest mind in the Institut',
    'and, after Horkheimer, its centre of gravity. He came back to Frankfurt in',
    '1949, out of the American exile, and taught and wrote and argued there until',
    'he died on holiday in Switzerland in August 1969, worn down, many think, by',
    'the year that had just happened. More on that below.</p>',
    '<hr>',
    '<h2>Negative Dialectics (1966)</h2>',
    '<p>The big late book, and the hardest. The whole tradition of dialectic',
    'before him aimed at synthesis: two terms clash and a higher third resolves',
    'them, and the resolution is progress. Adorno pulls the plug on the third',
    'term. There is to be NO synthesis, no reconciliation, no comfortable landing.',
    'Dialectic stays negative, which means it keeps working against the false',
    'wholes that thought is forever trying to build.</p>',
    '<p>The heart of it is the NON-IDENTICAL. Every concept promises to capture',
    'its object and never quite does; there is always a remainder the concept has',
    'to crush to make the object fit. Identity-thinking is the habit of pretending',
    'the remainder is not there. Negative dialectics is the discipline of keeping',
    'faith with it, of holding open the gap between the thing and the name we put',
    'on it.</p>',
    '<blockquote class="fs-quote"><p>"The whole is the false."</p></blockquote>',
    '<p>Read that against Hegel, who taught a whole century that "the true is the',
    'whole". Adorno inverts it on purpose. In a world organised as a false',
    'totality, the gesture that gathers everything up into one grand system is',
    'already complicit; the totality is not the truth, it is the lie you have to',
    'break to see anything at all.</p>',
    '<div class="fs-aside"><p>He thinks in CONSTELLATIONS, a word he takes half',
    'from Benjamin. You do not define a thing by pinning it to a genus. You circle',
    'it with a cluster of concepts, none of them the master key, and the object',
    'shows itself in the pattern they make around it, the way a constellation is',
    'nowhere in any single star. It is why the prose is the way it is. The',
    'difficulty is not decoration, it is the method refusing to give you the tidy',
    'summary that would falsify the thing.</p></div>',
    '<hr>',
    '<h2>Minima Moralia, and the music</h2>',
    '<p>If Negative Dialectics is too steep to start on, start with <i>Minima',
    'Moralia</i> (1951), the "Reflections from Damaged Life", written in exile as',
    '153 short aphorisms. It carries the most quoted line he ever wrote:</p>',
    '<blockquote class="fs-quote"><p>"Wrong life cannot be lived rightly."</p></blockquote>',
    '<p>There is a reading group\'s page on that book at',
    '<a href="minima-moralia.geocities.ws">minima-moralia</a>, and it is the',
    'kindest door into him. On the aesthetics and the philosophy of music, the',
    'other half of his life, see <a href="adorno-aesthetic.geocities.ws">adorno-aesthetic</a>.',
    'The book he wrote with Horkheimer on the manufacture of culture is next door',
    'at <a href="cultureindustry.geocities.ws">cultureindustry</a>, which is where',
    'a lot of people first meet him.</p>',
    '<p>&nbsp;</p>',
    '<h2>Controversy</h2>',
    '<p>Two fights follow him around, and a fan page that ducks them is no use to',
    'anyone.</p>',
    '<p><b>The jazz essays.</b> Adorno wrote about jazz across the 1930s and after,',
    'and the writing has not aged well; it is the standard rap against him and it',
    'lands. He heard the standardised products of the American music industry and',
    'took them for the whole of an idiom he did not really know from the inside,',
    'and he missed the improvisation, the Black musical tradition, nearly',
    'everything that mattered. You can hold on to his account of the culture',
    'industry, which is strong, and still say plainly that on this he was wrong.</p>',
    '<p><b>The students, 1969.</b> The last year of his life turned into a running',
    'battle with the radical students he had, in a sense, helped to make. It ended',
    'badly, with an occupation of his own Institut and, notoriously, with Adorno',
    'calling the police on his students. The full account, the lecture-hall',
    'protest and all, is at',
    '<a href="adorno-and-the-students.geocities.ws">adorno-and-the-students</a>.',
    'His own line on it still stings: he had built a theory to think the world,',
    'he said, and had not reckoned on people wanting to realise it with Molotov',
    'cocktails.</p>',
    '<p class="fs-pull">He wanted to keep the wound open. That was the whole',
    'method, and the students wanted to act on it.</p>',
    '<hr>',
    '<p>Why he still reads now, with everything gone quiet: because he built a way',
    'of thinking that does not need the happy ending to keep going, and that is a',
    'rare piece of equipment to be handed. The negativity is not despair, it is a',
    'refusal to call the damaged thing whole.</p>',
    '<hr>',
    '<p><small>counter: 03271 · best viewed at 800x600 · under construction, the',
    'discography is coming · this page loves you, wrong life and all · last updated',
    '14 Sep</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a devoted member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The Institut: the clean history ----------------------------------------

const INSTITUT = P('institut-fur-sozialforschung.geocities.ws', 'THE INSTITUT',
  'THE INSTITUT FUR SOZIALFORSCHUNG // a short history', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/uni-frankfurt-01.jpg" alt=""><span class="indie-cap">Goethe University, Frankfurt (photo: Adam Jones, CC BY-SA)</span>',
    '<h1>THE INSTITUT FUR SOZIALFORSCHUNG</h1>',
    '<p><small>a plain history of the place, kept by a member of a small reading',
    'circle. we wanted one page that just told you what happened, in order,',
    'without the mythology. corrections welcome.</small></p>',
    '<hr>',
    '<h2>Founded, 1923</h2>',
    '<p>The Institut fur Sozialforschung opened in Frankfurt in 1923, paid for out',
    'of the fortune of Felix Weil, whose father had made money in the grain trade',
    'in Argentina. The idea was an endowed home for Marxist research standing a',
    'little apart from the university and from any party. The first director was',
    'Carl Grunberg, a Vienna economic historian of the old scholarly kind, and',
    'under him the house had a strong archival and labour-history bent.</p>',
    '<hr>',
    '<h2>The 1930 turn</h2>',
    '<p>Everything people mean by "the Frankfurt School" starts when Max',
    'Horkheimer became director in 1930. His inaugural address set out a new',
    'programme: an interdisciplinary materialism in which philosophy would set the',
    'questions and the empirical social sciences, economics, sociology,',
    'psychology, would work on them together, each correcting the others. It was a',
    'genuinely new way to organise research, and the house journal, the',
    '<i>Zeitschrift fur Sozialforschung</i>, founded 1932, became the record of it.',
    'On Horkheimer\'s own idea of what made this work critical, see',
    '<a href="horkheimer-critical-theory.geocities.ws">horkheimer-critical-theory</a>.</p>',
    '<div class="fs-aside"><p>A point worth keeping straight: the Institut was',
    'never a school in the sense of a shared doctrine everyone signed. It was a',
    'building, a payroll and a journal that held together some very different and',
    'often quarrelsome people. The unity is real but it is the unity of an',
    'argument, not of a creed.</p></div>',
    '<hr>',
    '<h2>Exile, 1933</h2>',
    '<p>The members were mostly Jewish and mostly Marxist, so 1933 gave them no',
    'choice. The Institut had prudently moved its endowment out of Germany in',
    'advance, which is much of why it survived at all. It relocated first to',
    'Geneva, briefly to Paris, and by the mid-1930s to New York, where Columbia',
    'University gave it a home on Morningside Heights. The long American chapter,',
    'the language trouble, the Radio Research clash and the move to Los Angeles,',
    'has its own page at <a href="exile-at-columbia.geocities.ws">exile-at-columbia</a>.</p>',
    '<hr>',
    '<h2>Return, 1951</h2>',
    '<p>Horkheimer and Adorno went back to Frankfurt and reopened the Institut in',
    '1951, one of the very few of the emigration to return and rebuild in West',
    'Germany rather than stay away. The postwar Institut became a training ground',
    'for a whole generation of German sociology, and the line runs on through',
    'Habermas and past him to the directors of today.</p>',
    '<hr>',
    '<h2>A short critical note</h2>',
    '<p>Historians argue about how Marxist the returned Institut still was, and',
    'how much the American years, and the money, and the fear, sanded the politics',
    'down. It is a fair question and there is no settling it on one page. What is',
    'not in doubt is that the place survived the century that was built to destroy',
    'it, and kept publishing.</p>',
    '<hr>',
    '<p><small>visitors: 00489 · best viewed at 640x480 · under construction ·',
    'last updated 21 Oct</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a member page. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Dialectic of Enlightenment: the reading notes --------------------------

const DIALECTIC = P('dialectic-of-enlightenment.geocities.ws', 'DIALECTIC OF ENLGHT',
  'DIALECTIC OF ENLIGHTENMENT // reading notes', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/la-01.jpg" alt=""><span class="indie-cap">Pacific Palisades, where they wrote it in exile (photo: Niranjan Arminius, CC BY-SA)</span>',
    '<h1>DIALECTIC OF ENLIGHTENMENT: READING NOTES</h1>',
    '<p><small>notes on one book, taken as i went, chapter by chapter. Horkheimer',
    'and Adorno, drafted in the Los Angeles exile in 1944 and published in 1947.',
    'these are working notes, not a review; where i got stuck i left it stuck.</small></p>',
    '<hr>',
    '<p>The thesis in one sentence, their own:</p>',
    '<blockquote class="fs-quote"><p>"Myth is already enlightenment, and',
    'enlightenment reverts to mythology."</p></blockquote>',
    '<p>Both halves matter. Myth was already an early attempt to explain and',
    'master nature, so the Enlightenment did not break cleanly from it; and the',
    'Enlightenment, in its drive to dominate everything, hardens back into a new',
    'kind of fate, a second mythology. Reason meant to free us becomes a machinery',
    'that boxes us in. That is the "dialectic" in the title, and it is meant to',
    'hurt.</p>',
    '<hr>',
    '<h2>Odysseus and the Sirens</h2>',
    '<p>The excursus everyone remembers. They read the Sirens episode from Homer',
    'as the primal scene of bourgeois reason. Odysseus wants to hear the song and',
    'survive it, so he has himself lashed to the mast while the rowers stop their',
    'ears with wax and pull. He gets the pleasure, bound and powerless to act on',
    'it; they get the labour, deaf to the beauty entirely. Enjoyment for the',
    'master who cannot move, toil for the workers who cannot hear. They call',
    'Odysseus the first bourgeois: the self that masters itself in order to master',
    'nature, and pays for it in a lasting inner renunciation.</p>',
    '<p>What we argued about in the group: is this reading of Homer, or is Homer',
    'just a good peg for a thesis they already had? Verdict was, a bit of both,',
    'and the peg is brilliant either way.</p>',
    '<hr>',
    '<h2>The culture industry</h2>',
    '<p>The most-read chapter, "The Culture Industry: Enlightenment as Mass',
    'Deception". Their term, and they chose "industry" against "mass culture" on',
    'purpose: this is culture manufactured from above, not something rising up',
    'from the people. Standardised products sold as choice, amusement that trains',
    'you to accept the very order that exhausts you. There is a whole page on this',
    'strand at <a href="cultureindustry.geocities.ws">cultureindustry</a>, and it',
    'is worth reading alongside these notes.</p>',
    '<div class="fs-aside"><p>Open question we never closed: if the culture',
    'industry really is total, how did the two of them manage to see through it to',
    'write the chapter? Either the domination has a gap in it or the authors are',
    'claiming a vantage the theory says nobody has. The book does not answer this,',
    'and honest readers admit it.</p></div>',
    '<hr>',
    '<h2>Elements of anti-Semitism</h2>',
    '<p>The hardest section, and the reason the book exists. Written in the middle',
    'of the extermination, it tries to think anti-Semitism not as a lapse from',
    'civilisation but as something civilisation itself produces: projection, the',
    'rage of the dominated turned onto a target the order picks out for them, the',
    'blind fury of a reason that has cut itself off from reflection. Grim, uneven,',
    'unforgettable.</p>',
    '<hr>',
    '<p>Where to go next. The compressed, aphoristic companion to this book is',
    'Adorno\'s <i>Minima Moralia</i>, notes at',
    '<a href="minima-moralia.geocities.ws">minima-moralia</a>. And the full',
    'account of the negative method that runs under the whole thing is at',
    '<a href="adorno-negative-dialectics.geocities.ws">adorno-negative-dialectics</a>.</p>',
    '<hr>',
    '<p><small>counter: 01144 · best viewed at 800x600 · under construction, the',
    'anti-Semitism notes need another pass · last updated 2 Nov</small></p>',
    fileBlock(14),
    fileBlock(15),
    fileBlock(16),
    fileBlock(17),
    fileBlock(18),
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a member page. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Minima Moralia: the reading-group page ---------------------------------

const MINIMA = P('minima-moralia.geocities.ws', 'MINIMA MORALIA',
  'MINIMA MORALIA // reading-group page', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/typewriter-01.jpg" alt=""><span class="indie-cap">reflections from a damaged life (photo: Sammlung der Medien und Wissenschaft, CC BY)</span>',
    '<h1>MINIMA MORALIA: REFLECTIONS FROM DAMAGED LIFE</h1>',
    '<p class="fs-epi">"The splinter in your eye is the best magnifying glass." — Adorno</p>',
    '<p><small>the Thursday reading group\'s page. six of us, a book we took slowly,',
    'one aphorism a week and then the argument. Adorno wrote it in exile and',
    'published it in 1951, a hundred and fifty-three short pieces, dedicated to',
    'Horkheimer. this is where we kept the lines that stopped us.</small></p>',
    '<hr>',
    '<p>The whole book turns on the word in the subtitle, DAMAGED. It is a moral',
    'philosophy written from the conviction that there is no longer any sound',
    'ground to write one from, no undamaged private life you could hold up as the',
    'good one. The most famous sentence says it flat:</p>',
    '<blockquote class="fs-quote"><p>"Wrong life cannot be lived rightly."</p></blockquote>',
    '<p>We spent a whole evening on this one. It is not a counsel of despair and it',
    'is not a get-out. You cannot buy yourself a clean private conscience inside a',
    'social order that is itself false; there is no corner of it uncontaminated',
    'where you get to be good on your own. But naming that is not the same as',
    'giving up. The book is the record of a mind refusing both the lie of the',
    'happy inner life and the collapse into cynicism.</p>',
    '<hr>',
    '<h2>The line about the splinter</h2>',
    '<blockquote class="fs-quote"><p>"The splinter in your eye is the best',
    'magnifying glass."</p></blockquote>',
    '<p>Our favourite, and the one we argued longest over. He is turning a',
    'reproach into a method. What hurts you, the thing lodged in you that you',
    'cannot ignore, is exactly the instrument that lets you see the society that',
    'put it there. Your own damage, looked at hard instead of soothed away, is',
    'evidence. It is the whole permission slip for a critical theory that starts',
    'from the bruise and not from a system.</p>',
    '<div class="fs-aside"><p>Someone in the group pointed out that the aphorism',
    'form is doing the argument, not just carrying it. A false whole cannot be',
    'told the truth in the shape of a smooth continuous system, because the smooth',
    'system would reproduce the very false wholeness he is attacking. So he writes',
    'in fragments on purpose. The broken form is honest to a broken life. We',
    'thought that was the cleverest thing about the book.</p></div>',
    '<hr>',
    '<h2>What we argued about</h2>',
    '<p>The recurring fight was about who gets to write like this. Adorno is a',
    'brilliant emigre professor mourning a European high culture from a house in',
    'California, and some of the aphorisms about servants, about telephones, about',
    'the vulgarity of the new world, read as a mandarin flinching at modern life.',
    'Two of us defended him: the discomfort is the point, he indicts his own',
    'privileged position as much as anyone\'s. Two of us were not so sure. We did',
    'not settle it. A book worth arguing about does not always resolve.</p>',
    '<hr>',
    '<p>Read alongside. The theoretical engine under these fragments is set out at',
    '<a href="adorno-negative-dialectics.geocities.ws">adorno-negative-dialectics</a>,',
    'and the big collaborative book from the same exile, the same years, is at',
    '<a href="dialectic-of-enlightenment.geocities.ws">dialectic-of-enlightenment</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00933 · best viewed at 800x600 · under construction, more',
    'aphorisms to add as we reach them · last updated 30 Oct</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a member page. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Eclipse of Reason: the reading notes -----------------------------------

const ECLIPSE = P('eclipse-of-reason.geocities.ws', 'ECLIPSE OF REASON',
  'ECLIPSE OF REASON // reading notes', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/books-01.jpg" alt=""><span class="indie-cap">(photo: Furkan Akkurt, CC BY-SA)</span>',
    '<h1>ECLIPSE OF REASON: READING NOTES</h1>',
    '<p><small>notes on Horkheimer\'s little 1947 book, which began as lectures he',
    'gave at Columbia during the New York years. short book, heavy freight. i took',
    'these to teach it to myself; keep them for what they are.</small></p>',
    '<hr>',
    '<p>The whole argument hangs on one distinction, so get it straight first.</p>',
    '<h2>Objective vs subjective reason</h2>',
    '<p>OBJECTIVE reason, in the old sense running from the Greeks through the',
    'idealists, held that reason was in the world, not only in our heads. It could',
    'ask about ENDS: whether an action, a life, an order was reasonable in itself,',
    'whether the ends people pursued were worth pursuing. Reason judged the goals.</p>',
    '<p>SUBJECTIVE or INSTRUMENTAL reason gives all that up. It no longer asks',
    'whether an end is good; it asks only whether the means are efficient. Set any',
    'goal you like, however mad, and instrumental reason will calculate the',
    'shortest route to it and call itself rational for doing so. Reason shrinks',
    'from a faculty of judgement into a faculty of calculation.</p>',
    '<hr>',
    '<h2>Reason turning on itself</h2>',
    '<p>Here is the pay-off, and it is bleak. Once reason can only calculate means',
    'and can no longer weigh ends, it loses the ground to defend the very ideals,',
    'freedom, justice, tolerance, that the Enlightenment fought for in its name.',
    'Those ideals now look like mere preferences with no rational backing, so',
    'reason cannot argue for them and cannot argue against their enemies either.',
    'Horkheimer\'s hardest formulation is that reason has liquidated itself as an',
    'agency of ethical, moral and religious insight. Say it slowly. The tool that',
    'was to secure our values has dissolved its own authority to hold any.</p>',
    '<div class="fs-aside"><p>Note to self on not misreading this. He is not',
    'preaching a return to religion or to some cosy premodern cosmos where reason',
    'sat in the stars. The book is mournful about objective reason, not',
    'nostalgic. The task he leaves is to rescue reason\'s power to judge ends',
    'WITHOUT the old metaphysics that used to underwrite it, and he does not',
    'pretend to have finished that task.</p></div>',
    '<hr>',
    '<h2>How it fits</h2>',
    '<p>This is the same year, 1947, and the same argument as the book he wrote',
    'with Adorno; read them as a pair. The <i>Dialectic of Enlightenment</i> tells',
    'the grand mythic version, notes at',
    '<a href="dialectic-of-enlightenment.geocities.ws">dialectic-of-enlightenment</a>;',
    'the <i>Eclipse of Reason</i> is the tighter, more lecture-room statement of',
    'the core of it. For the wider frame of Horkheimer\'s critical theory, start at',
    '<a href="horkheimer-critical-theory.geocities.ws">horkheimer-critical-theory</a>.</p>',
    '<hr>',
    '<p>Why keep reading it now, in the long quiet after the calculating machines',
    'grew so loud: because we built a civilisation exceptionally good at working',
    'out means and worse than ever at arguing about ends, and Horkheimer named',
    'that split when it was still only a lecture course. He saw the shape of it',
    'coming.</p>',
    '<hr>',
    '<p><small>counter: 00707 · best viewed at 640x480 · under construction ·',
    'last updated 5 Nov</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a member page. « prev · random · next »',
    '</small></p>',
  ]);

export const FS_A = [HORKHEIMER, ADORNO, INSTITUT, DIALECTIC, MINIMA, ECLIPSE];
