// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH FS-G, the fourth generation and the digital.
//
// Fan pages kept on a free host, each ABOUT a thinker and never in the
// thinker's own voice. A devotee's shrine to Jaeggi's revival of alienation;
// a showpiece for Rosa, all pull-quotes and air, arguing about resonance; a
// student's late coursework on Celikates and critique from below; and a
// reading group working through the Frankfurt School turned on the machine.
// The authors, titles and dates are real; the enthusiasm is the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Jaeggi: the devotee's shrine -------------------------------------------

const JAEGGI = P('jaeggi-forms-of-life.geocities.ws', 'JAEGGI',
  'RAHEL JAEGGI // alienation has a life in it again', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/weimar-02.jpg" alt=""><span class="indie-cap">Berlin (photo: Dietmar Rabich, CC BY-SA)</span>',
    '<h1>RAHEL JAEGGI</h1>',
    '<p class="fs-epi">"Alienation is a relation of relationlessness." (Rahel Jaeggi)</p>',
    '<p><small>a page kept by someone who did a philosophy MA, fell out of love',
    'with the whole apparatus of it, and got pulled back in by exactly one book.',
    'this is a shrine, i admit it. i have read the alienation book three times and',
    'i am not finished with it. yours, r.k.</small></p>',
    '<hr>',
    '<p>Here is why she matters. For about forty years you were not allowed to say',
    'ALIENATION in serious company. The word had a bad smell. It seemed to need a',
    'true human essence sitting somewhere behind the false life, a real self you',
    'were being kept from, and nobody could tell you where that self was kept or',
    'who had the key. So the concept got quietly retired. Jaeggi picked it up off',
    'the floor, dusted it, and gave it back to us without the metaphysics.</p>',
    '<h2>Alienation (2005, English 2014)</h2>',
    '<p>The move is elegant. Alienation is not being cut off from your true nature.',
    'It is a broken relation, a way of being related to your own life, your work,',
    'your desires, in which you cannot make any of it your own. You go through the',
    'motions and none of the motions are yours. She calls it, and this is the line',
    'that got me:</p>',
    '<blockquote class="fs-quote"><p>"a relation of relationlessness"</p></blockquote>',
    '<p>You are still related to the thing. You are just related to it as a stranger,',
    'as something that happens to you rather than something you do. No lost paradise',
    'is needed. You do not have to believe in an essence to see when a person cannot',
    'inhabit their own actions. That is the trick, and it is a good one.</p>',
    '<hr>',
    '<h2>Critique of Forms of Life (2014, English 2018)</h2>',
    '<p>The bigger book, and the more ambitious. The worry it answers is the one',
    'every liberal throws at critical theory: who are YOU to judge how other people',
    'live? Say nothing and you cannot criticise anything. Say too much and you are',
    'just imposing your taste. Jaeggi threads it by treating a form of life as a',
    'kind of PROBLEM-SOLVING. A way of living is an accumulated set of answers to',
    'the problems living throws up, and like any answer it can work or fail, learn',
    'or get stuck. So you can criticise a form of life from the inside, by its own',
    'lights, when it stops being able to solve the problems it keeps generating.',
    'Not taste. Not essence. Learning, or the failure to learn.</p>',
    '<p class="fs-pull">forms of life are not sacred and they are not arbitrary. they can get stuck.</p>',
    '<p>What I like is that it gives critique something to bite on that is neither a',
    'private preference nor a commandment from nowhere. A form of life that cannot',
    'metabolise its own contradictions is failing, and you are allowed to say so.</p>',
    '<hr>',
    '<p><b>where she comes from</b></p>',
    '<p>She was Honneth\'s student and she now holds the chair in Berlin, and she',
    'runs the reading and the fights that keep the tradition arguing with itself',
    'rather than curating a museum of it. If you want the recognition side of the',
    'family, that is <a href="honneth-recognition.geocities.ws">honneth-recognition</a>,',
    'her teacher, the struggle for recognition and all three of its spheres. And',
    'the closest living company for her, the person doing the acceleration-and-',
    'resonance version of the same worry about how we can and cannot inhabit a',
    'life, is over at <a href="rosa-resonance.geocities.ws">rosa-resonance</a>.',
    'Go read both. They rhyme.</p>',
    '<hr>',
    '<p>Why now. When so much of a life gets handled for you, arranged, optimised,',
    'served up, the question of whether any of it is actually YOURS stops being a',
    'seminar puzzle and starts being the whole question. Jaeggi handed us the word',
    'for it back, sharpened. Use it.</p>',
    '<hr>',
    '<p><small>counter: 00312 · best viewed at 800x600 · under construction (the',
    'Freedom\'s Right notes are coming, i promise) · last updated 22 Mar</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Rosa: the showpiece ----------------------------------------------------

const ROSA = P('rosa-resonance.geocities.ws', 'ROSA',
  'HARTMUT ROSA // resonance, and the world you cannot make behave', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/frankfurt-02.jpg" alt=""><span class="indie-cap">(photo: Nicolas Scheuer, CC BY-SA)</span>',
    '<h1>HARTMUT ROSA</h1>',
    '<p class="fs-epi">"We do not want to make the world faster. We want to reach it." (Hartmut Rosa)</p>',
    '<p><small>this page is a labour of love, kept by somebody who read the big',
    'acceleration book on trains, running late, which is either the worst or the',
    'best possible way to read it. i have tried to give it room to breathe, the way',
    'the man himself says a thing needs room. take your time here. yours, nge</small></p>',
    '<hr>',
    '<p>Rosa is a sociologist at Jena and he leads a research college there on',
    'exactly the thing his books are about, the way modern life relates to time. He',
    'came up through the Frankfurt tradition, through Honneth, and he asked it a',
    'question it had somehow left on the table for a century. Never mind whether',
    'society is just. Ask first: what is it doing to our relation to time, and',
    'through time, to everything?</p>',
    '<h2>Social Acceleration (2005)</h2>',
    '<p>The diagnosis book. Rosa says modernity is not defined by progress or reason',
    'or capital so much as by SPEED, and he pulls the speed apart into three',
    'strands that feed each other.</p>',
    '<p>One, technical acceleration: transport, communication, production, all the',
    'machines that do the same task faster. Two, acceleration of social change: the',
    'world itself turns over quicker, jobs, tastes, relationships, the ground moves',
    'under you within a single life instead of across generations. Three,',
    'acceleration of the pace of life: the felt thing, the sense of hurry, of never',
    'having enough time even though the machines were supposed to give us more.</p>',
    '<p class="fs-pull">the machines got faster and we got less time. that is the paradox, and it is not an accident.</p>',
    '<p>The cruel joke is that the three form a circle that drives itself. Faster',
    'machines should free up time, but they raise what counts as normal, so the',
    'social world speeds up, so the pace of life tightens, so we reach for faster',
    'machines. Rosa calls it a self-propelling wheel that no longer needs a promise',
    'of the good life to keep it turning. It turns because stopping means falling',
    'behind. Not desire. Dread.</p>',
    '<div class="fs-aside"><p>An aside, because it is the detail that sold me. Rosa',
    'points out that we no longer even experience the acceleration as somebody\'s',
    'plan or command. There is no tyrant with a whip. It arrives as a mute,',
    'impersonal pressure, the emails that were already there when you woke, the',
    'sense that you are the slow one. That is what makes it so hard to argue with.',
    'You cannot refuse an order nobody gave.</p></div>',
    '<hr>',
    '<h2>Resonance (2016)</h2>',
    '<p>Here is the turn, and it is why this page exists. Rosa is not just a',
    'diagnostician of speed. He asked the harder question: if acceleration is the',
    'sickness, what would health even look like? And his answer is RESONANCE.</p>',
    '<p>Resonance is a way of relating to the world in which the world answers back.',
    'You reach out, something reaches you, and you are changed by the meeting and',
    'cannot fully predict how. A piece of music that takes hold of you. A landscape',
    'that stops you. A conversation that goes somewhere neither of you planned. Work',
    'that talks back. It is not happiness, it is not a warm feeling you can buy or',
    'produce on demand. It is a live relation, two ways, where you and the thing',
    'you meet are both genuinely in play.</p>',
    '<p>The opposite of resonance is not noise. The opposite is a mute world, a',
    'world that has gone silent and grey, that you can only manipulate and never',
    'reach, that stands over against you as pure material for your projects. Rosa',
    'borrows the harshest Frankfurt word for this and lets it sit at the centre of',
    'the book:</p>',
    '<blockquote class="fs-quote"><p>"reification": a relation to the world as mute, cold, and merely there to be controlled.</p></blockquote>',
    '<p>And here is the sting he drives home. Acceleration turns the world mute. The',
    'faster you have to move over the surface of things, the less any single thing',
    'can answer you, because you are already gone. Speed and muteness are the same',
    'condition seen twice. You cannot resonate with a world you are racing across.</p>',
    '<p class="fs-pull">you cannot resonate with a world you are racing across.</p>',
    '<h2>The Uncontrollability of the World (2018)</h2>',
    '<p>The short, sharp one, and the one to hand a friend who will not read six',
    'hundred pages. Rosa\'s claim is that modernity runs on a drive to make the',
    'world knowable, reachable, manageable, controllable, to bring every last bit',
    'of it within range. And the catch is that a fully controlled world is a dead',
    'one. The things that matter to us, the ones that resonate, matter precisely',
    'because they are NOT fully at our disposal. They can refuse. A relationship you',
    'could fully control would not be worth having. Snow you could summon on demand',
    'would stop being snow. Rosa\'s word for the good bit is <i>Unverfügbarkeit</i>,',
    'the quality of being not-at-your-disposal, and he says we are busy engineering',
    'it out of existence and wondering why everything feels flat.</p>',
    '<div class="fs-aside"><p>My own favourite example of his: the perfect holiday,',
    'planned to the minute, every view pre-booked, every meal reviewed in advance.',
    'You get exactly what you paid for and nothing reaches you at all. The thing you',
    'were chasing was never on the itinerary. It cannot be put on one.</p></div>',
    '<hr>',
    '<h2>Controversy: is resonance too soft?</h2>',
    '<p>I have to be fair, because the objection is a real one and the seminars will',
    'not let it go. The worry is that resonance is TOO SOFT a concept to do the work',
    'Rosa wants from it. It sounds, the critics say, like a wellness idea in a',
    'philosopher\'s coat. Slow down, feel the music, touch some grass. And you can',
    'hear how that would land: a comfortable prescription that leaves the structures',
    'of acceleration, the labour markets and the capital that actually drive the',
    'wheel, entirely alone. Where is the politics? Can you resonate your way out of',
    'a system that needs you sprinting? Is this critical theory or is it a very',
    'well-read spa?</p>',
    '<p>Two things in his defence, and I think they hold. First, Rosa is explicit',
    'that resonance cannot be produced on command, which is the whole point, and',
    'that means it cannot be sold to you as a technique either. A resonance you',
    'could reliably manufacture would already be the mute, controlled thing he is',
    'against. So it resists exactly the wellness capture the critics fear. Second,',
    'he does not say meditate instead of organise. He argues that the CONDITIONS of',
    'resonance are social and institutional, that a society organised around',
    'endless acceleration systematically starves them, and that changing the',
    'conditions is a political task. The concept is soft on purpose, because the',
    'thing it names cannot be forced. That is not the same as being soft on the',
    'system that kills it.</p>',
    '<p>Fair to say the argument is not settled, and the sharper Marxists remain',
    'unconvinced. I think the concept earns its place. Read the acceleration book',
    'first and the objection gets a lot quieter, because you have felt the disease',
    'before he offers you the name for the cure.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>His nearest company is <a href="jaeggi-forms-of-life.geocities.ws">',
    'jaeggi-forms-of-life</a>, who asks the same worry in a different key: whether',
    'you can actually inhabit your own life, or only pass through it as a stranger.',
    'And behind both of them stands the communicative turn, the idea that reaching',
    'an understanding with the world and with each other is a thing reason can do,',
    'over at <a href="habermas-communicative-action.geocities.ws">',
    'habermas-communicative-action</a>. Rosa is friendlier to the world\'s own',
    'voice than Habermas ever was, but the family line is clear.</p>',
    '<hr>',
    '<p>Why now, with the pace finally broken. When everything sped up for so long,',
    'the one relation that never fitted on the schedule was the one that turned out',
    'to matter. Rosa named it before the wheel stopped turning. Worth having the',
    'word ready.</p>',
    '<hr>',
    '<p><small>counter: 01188 · best viewed at 800x600, slowly · this page has no',
    'auto-refresh on purpose · under construction, forever, appropriately · last',
    'updated 9 Apr</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Celikates: the student coursework --------------------------------------

const CELIKATES = P('celikates-critique.geocities.ws', 'CELIKATES',
  'CRITIQUE FROM BELOW // notes on Celikates (SOC-341)', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/protest-02.jpg" alt=""><span class="indie-cap">West Berlin, 1968 (photo: Ludwig Binder, Haus der Geschichte, CC BY-SA)</span>',
    '<h1>CRITIQUE AS SOCIAL PRACTICE</h1>',
    '<p><small>for SOC-341, Contemporary Critical Theory. handed in a week late,',
    'sorry Dr M. these are my notes worked up into a page because the seminar said',
    'to and my laptop is the only place they were safe. Robin Celikates,',
    '<i>Critique as Social Practice</i>.</small></p>',
    '<hr>',
    '<p>intro (written 14 Feb). the question this book is really answering is one',
    'that used to embarrass critical theory a lot. the theorist sits in the',
    'university and tells everyone else that their consciousness is false, that they',
    'cannot see the ideology they are trapped in. but if ordinary people are so',
    'trapped, how come the theorist is not? who made the theorist the one person in',
    'the room who can see clearly? Celikates calls this the problem of the',
    'critic standing ABOVE, and his whole book is a way out of it.</p>',
    '<h2>the main move</h2>',
    '<p>his answer is that critique is not something the theorist brings to people',
    'from outside. it is something people are ALREADY doing. ordinary social actors',
    'criticise their own institutions all the time, they complain, they refuse, they',
    'point out that the rules are not being kept, they organise. that is critique,',
    'as a practice, before any professor turns up. so the job of the critical',
    'theorist is not to lecture from above. it is to follow the critique people',
    'already practise, make it sharper, help it understand itself, but never to',
    'replace it with the smarter view from the seminar room.</p>',
    '<p>Celikates gets this partly out of a fight with Boltanski and the French',
    'sociology of critique, and he keeps the good bit: that people are competent,',
    'they have their own critical capacities, they are not just dupes waiting to be',
    'woken up. (i think this is the strongest thing in the book and i said so in',
    'seminar.)</p>',
    '<h2>where it goes: disobedience and migration</h2>',
    '<p>the reason this is not just abstract is that he takes it into real fights.',
    'CIVIL DISOBEDIENCE is his big case. the standard liberal view treats',
    'disobedience as a polite exception, allowed only if you are calm, symbolic, and',
    'accept your punishment. Celikates says that tames it. disobedience is better',
    'understood as ordinary people practising democracy BY OTHER MEANS when the',
    'official channels are blocked, an active claim rather than a plea for mercy.',
    'and MIGRATION struggles are the other case, people crossing borders and',
    'claiming rights they were not granted, enacting a membership nobody handed',
    'them. these are critique as a practice, done with the body, not a theory in a',
    'book.</p>',
    '<p>this is the Berlin scene, by the way. Celikates was part of the critical-',
    'theory crowd there before he moved to Amsterdam, the same milieu as a lot of',
    'the fourth-generation people, and you can feel the shared project: pull',
    'critical theory back down to what people are actually doing.</p>',
    '<hr>',
    '<p><b>what i argued about with my group</b></p>',
    '<p>the obvious objection, and Tomas raised it: if critique is just following',
    'what people already do, does the theory lose its teeth? what if the critique',
    'people practise is bad, reactionary, a mob? does Celikates have any way to say',
    'a movement is WRONG, or does he have to cheer for whatever people happen to be',
    'doing? my answer (i think his answer) is that following is not the same as',
    'approving, that critique has to be reconstructive, it holds a practice to the',
    'standards that practice itself appeals to. but i am not fully sure he escapes',
    'it and i left it open in the essay.</p>',
    '<hr>',
    '<p><b>neighbours (for the further reading bit)</b></p>',
    '<p>the person next door doing forms of life and whether you can criticise a way',
    'of living from inside it is <a href="jaeggi-forms-of-life.geocities.ws">',
    'jaeggi-forms-of-life</a>, and honestly you should read her second chapter',
    'alongside this. and the recognition tradition it all grows out of, disrespect',
    'as the thing that drives people to struggle, is',
    '<a href="honneth-recognition.geocities.ws">honneth-recognition</a>, who was',
    'more or less the teacher of this whole generation.</p>',
    '<hr>',
    '<p>why it matters now (conclusion, rushed, sorry). when the experts turn out',
    'not to have had the map after all, the idea that the people doing the',
    'criticising already know something worth listening to stops being a nice',
    'thought and starts being the only place to begin. Celikates got there early.</p>',
    '<hr>',
    '<p><b>bibliography</b> (Harvard-ish, i ran out of time)</p>',
    '<p><small>Celikates, R. <i>Critique as Social Practice: Critical Theory and',
    'Social Self-Understanding</i>. orig. German 2009, English edition 2018.<br>',
    'Celikates, R. also the essays on civil disobedience, various.<br>',
    'Honneth (the recognition one, 1992), see the linked page.<br>',
    'Boltanski (mentioned in seminar, did not finish it).</small></p>',
    '<hr>',
    '<p><small>counter: 00147 · best viewed at 640x480 · this is student work, do',
    'not cite me, cite him · last updated 21 Feb</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Critical Theory and the Digital: reading-group notes -------------------

const DIGITAL = P('critical-theory-and-the-digital.geocities.ws', 'CT + DIGITAL',
  'READING GROUP // the culture industry has an API now', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/typewriter-01.jpg" alt=""><span class="indie-cap">(photo: Sammlung der Medien und Wissenschaft, CC BY)</span>',
    '<h1>CRITICAL THEORY AND THE DIGITAL</h1>',
    '<p><small>notes from the Tuesday reading group at the hackspace, taken by',
    'whoever had the laptop that week (mostly me). we spent six weeks on one',
    'question: what happens when you point the old Frankfurt School critique',
    'straight at the machine. the spine text was David M. Berry, <i>Critical Theory',
    'and the Digital</i> (2014). here is where we got to.</small></p>',
    '<hr>',
    '<p><b>week 1: the culture industry, but automated</b></p>',
    '<p>we started at the obvious place. Adorno and Horkheimer said the culture',
    'industry manufactures the standardised stuff people take for their own free',
    'taste, a factory turning out sameness dressed as choice (their chapter is over',
    'at <a href="cultureindustry.geocities.ws">cultureindustry</a>, we read it',
    'first). the group\'s question: is a platform just the culture industry with',
    'better logistics? partly yes. but somebody pointed out the difference that',
    'matters. the old culture industry pushed the SAME thing at everyone. the',
    'platform pushes a DIFFERENT thing at each person and calls that liberation,',
    'while the sameness has moved down a layer, into the sorting itself. everyone',
    'gets a personalised feed and everyone is inside the same machine. that felt',
    'like the real update and we spent a whole evening on it.</p>',
    '<hr>',
    '<p><b>week 2: the administered world becomes the datafied world</b></p>',
    '<p>the phrase we kept coming back to. the first-generation people wrote about',
    'the administered world, a life managed, sorted, and totally organised from',
    'above, reason gone instrumental (see the eclipse-of-reason strand). Berry\'s',
    'move, as we read him, is that the administered world did not go away, it got a',
    'database. administration used to need clerks and files. now it runs as data',
    'and code, quietly, on everyone, all the time. the totally managed society the',
    'old men feared did not need a dictator. it needed an API and our consent to the',
    'terms.</p>',
    '<p class="fs-pull">the administered world did not go away. it got a database.</p>',
    '<hr>',
    '<p><b>week 3: Adorno and Benjamin, read for the screen</b></p>',
    '<p>this is the chapter people argued about most. Berry does not just apply the',
    'old texts, he reads them AT the interface. Benjamin on mechanical reproduction',
    'and the aura, the way endless copying strips the here-and-now off a work, turns',
    'out to be about the feed before there was a feed (Benjamin\'s essay is at',
    '<a href="aura.geocities.ws">aura</a>). and Adorno\'s stuff on standardisation',
    'reads like a description of a template. the group split on whether this is',
    'insight or just a good pattern-match. i am on the insight side. the concepts',
    'were built to see exactly this and they were built too early to name it.</p>',
    '<hr>',
    '<p><b>week 4: computationality, and why criticism keeps going missing</b></p>',
    '<p>Berry\'s own word, which he carries in from his earlier work over at',
    '<a href="the-philosophy-of-software.geocities.ws">the-philosophy-of-software</a>.',
    'the idea is that the computational has quietly become the horizon we think',
    'inside, the taken-for-granted ground, the way print once was. and his sharpest',
    'complaint in this book is that so much writing ABOUT the digital forgets to be',
    'critical at all. it describes, it celebrates, it consults, it does everything',
    'except ask who the arrangement serves. the digital humanities gets a hard',
    'look here, and the room was divided about whether that was fair (two of us do',
    'DH and took it personally).</p>',
    '<div class="fs-aside"><p>side argument that ran over into the pub: is the',
    'problem that the tools are uncritical, or that the people using them stopped',
    'asking? Berry wants both, we decided, the tool builds in a way of seeing AND',
    'the culture around it stops looking. you cannot fix one without the other.</p></div>',
    '<hr>',
    '<p><b>week 5: what the machine hides</b></p>',
    '<p>the thread that ties the book to his software work. code runs the mediation',
    'now the way writing once did, and it does it while staying out of sight, so a',
    'critical reading has to make the hidden layer show itself. the group liked',
    'this because it gives critique an actual object again, not just a mood. you can',
    'go DOWN into the system and read what it is doing, and what it is doing is',
    'usually an argument the smooth surface never admits to.</p>',
    '<hr>',
    '<p><b>week 6: what we could not settle</b></p>',
    '<p>the open question we ended on. the Frankfurt School had almost no politics of',
    'the way out, Adorno least of all, and Berry inherits some of that. you finish',
    'the book seeing the datafied administered world very clearly and with not much',
    'idea what to DO. is the diagnosis the point, or is a diagnosis with no exit',
    'just despair with footnotes? we did not agree. we did agree the diagnosis is',
    'right, which is why the group kept meeting.</p>',
    '<hr>',
    '<p><b>next to read</b></p>',
    '<p>the Adorno backbone, the non-identical and the whole is the false, is at',
    '<a href="adorno-negative-dialectics.geocities.ws">adorno-negative-dialectics</a>,',
    'and half the book only makes sense once you have sat with it. and if you want',
    'the software argument this grows out of, go to',
    '<a href="the-philosophy-of-software.geocities.ws">the-philosophy-of-software</a>',
    'and read that first, it is the engine under this one.</p>',
    '<hr>',
    '<p>why it matters now, in the after. we read the book expecting a critique of',
    'gadgets and found a critique of a whole administered life run as data. that',
    'life is the one that just seized up around us. the reading group carries on.',
    'Tuesdays, the hackspace, bring your own copy.</p>',
    '<hr>',
    '<p><small>counter: 00298 · best viewed at 800x600 · notes are collective, blame',
    'is mine · under construction, we are still on the reading · last updated 30',
    'Apr</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a reading-group member. « prev · random · next »',
    '</small></p>',
  ]);

export const FS_G = [JAEGGI, ROSA, CELIKATES, DIGITAL];
