// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — the industry & culture. Six fan pages ABOUT the comics business and
// the scene, never in a house voice: a document page on the Comics Code and the
// 1954 panic; a shop regular's love letter to the direct market and Wednesday;
// an anthology tribute to 2000 AD and Tharg; a publisher shrine to Gaines's EC;
// a con-goer's field notes from San Diego; and a close-reading essay on the
// superhero form itself. The publishers, dates and works are real; the passion
// and the grudges belong to the fans.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- the Comics Code: the document page (SHOWPIECE) -------------------------

const COMICS_CODE = P('the-comics-code.geocities.ws', 'COMICS CODE',
  'THE COMICS CODE AUTHORITY 1954 — the seal that ate an industry', [
    '<!--bg:comics-culture-->',
    '<h1>THE COMICS CODE AUTHORITY</h1>',
    '<p><small>a document page kept by someone who collects pre-Code horror and',
    'will not shut up about what was taken away. everything here is checked',
    'against the actual 1954 Code text. spoilers below only in the sense that i',
    'tell you how the industry nearly died. — the archivist</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>“You mean I can be prosecuted for publishing pictures',
    'like these?”<br>— the tone of a bad year, 1954</p></div>',
    '<p>In 1954 the American comic-book industry, frightened for its life, wrote',
    'itself a set of rules and hung a little stamp in the top corner of every',
    'approved cover. The stamp said <b>APPROVED BY THE COMICS CODE AUTHORITY</b>.',
    'For nearly forty years a comic without that seal could not get on most',
    'newsstands, and so the seal decided what a whole medium was allowed to be.</p>',
    '<h2>how the panic started</h2>',
    '<p>The spark was a book. Fredric Wertham, a psychiatrist, published',
    '<i>Seduction of the Innocent</i> in 1954, arguing that crime and horror',
    'comics were schooling children in delinquency and worse. It was bad science',
    'dressed as concern, but it landed. That same year the US Senate Subcommittee',
    'on Juvenile Delinquency held televised hearings, and the cameras went to the',
    'publisher least willing to grovel.</p>',
    '<img class="indie-pic" src="assets/media/web/comics/early-comic-01.jpg" alt=""><span class="indie-cap">The Yellow Kid by R. F. Outcault (public domain)</span>',
    '<div class="fs-quote"><blockquote><p>“A cover in bad taste, possibly, but not',
    'a bad cover.”<br>— William M. Gaines, before the Senate subcommittee, 21',
    'April 1954, defending an EC cover of a severed head</p></blockquote></div>',
    '<p>Gaines walked into that room to defend the medium and, tired and unwell,',
    'handed the reformers their best afternoon. The exchange over the severed head',
    'ran in every paper. Within months the publishers formed the Comics Magazine',
    'Association of America and adopted the Code, and the man who had defended them',
    'was the man the Code was built to destroy. His shop is at',
    '<a href="ec-comics.geocities.ws">ec-comics</a>, and it is the saddest link on',
    'this page.</p>',
    '<h2>a few of the rules</h2>',
    '<pre>',
    'FROM THE CODE OF THE COMICS MAGAZINE ASSOCIATION OF AMERICA, 1954',
    '(General Standards, paraphrased close to the wording)',
    '',
    '  * "Crimes shall never be presented in such a way as to create',
    '     sympathy for the criminal."',
    '  * "In every instance good shall triumph over evil and the criminal',
    '     punished for his misdeeds."',
    '  * "No comic magazine shall use the words horror or terror in its title."',
    '  * "All scenes of horror, excessive bloodshed, gory or gruesome crimes,',
    '     depravity, lust, sadism, masochism shall not be permitted."',
    '  * "Scenes dealing with, or instruments associated with walking dead,',
    '     torture, vampires and vampirism, ghouls, cannibalism, and',
    '     werewolfism are prohibited."',
    '  * "Respect for parents, the moral code, and for honorable behavior',
    '     shall be fostered."',
    '</pre>',
    '<p>Read the fourth and fifth of those together and you have the death warrant',
    'for an entire genre. You cannot publish <i>Tales from the Crypt</i> under a',
    'rule that bans the walking dead by name. That was not an accident of drafting.',
    'The horror and crime comics were the target, and the target was hit.</p>',
    '<div class="fs-aside"><p><b>TRIVIA BOX.</b> The word "terror" being banned',
    'from titles is why a good run of magazines were renamed overnight. Two of',
    'EC\'s titles were literally outlawed by their own names. Gaines killed the',
    'whole horror and crime line in 1954 and 1955 and kept exactly one thing that',
    'the Code could not touch, because it was a magazine and not a comic book:',
    '<i>Mad</i>.</p></div>',
    '<h2>the long slow death of the seal</h2>',
    '<pre>',
    'A ROUGH TIMELINE',
    '',
    '  1954   Wertham, SEDUCTION OF THE INNOCENT. Senate hearings.',
    '  1954   CMAA formed; the Comics Code adopted.',
    '  1955   EC folds its comic line; MAD survives as a magazine.',
    '  1971   Marvel prints a Spider-Man drugs story WITHOUT the seal',
    '         (at the request of the US government, no less); the Code',
    '         is revised soon after.',
    '  1989   Another revision loosens the grip.',
    '  2001   Marvel abandons the Code entirely.',
    '  2011   The last holdouts drop it; the Authority is finished.',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/comics/speech-bubble-01.jpg" alt=""><span class="indie-cap">A comic speech balloon (photo: Henry Söderlund, CC BY 2.0)</span>',
    '<div class="fs-pull"><p>“The seal did not protect children. It protected',
    'distribution.”</p></div>',
    '<p>What the Code really policed was the newsstand. A frightened industry made',
    'itself respectable so the wholesalers would keep carrying it, and the price',
    'was horror, crime, ambiguity, and most of what made the medium interesting to',
    'an adult. The superhero survived because the superhero was already clean, or',
    'could be made clean, which is a story told over at',
    '<a href="the-superhero.geocities.ws">the-superhero</a>.</p>',
    '<p>The thing that finally broke the Code was not a court. It was the',
    'direct-market comic shop, which sold to collectors who did not need the',
    'newsstand or its seal, and which is why the shop people speak of Wednesday',
    'the way churchgoers speak of Sunday. That started somewhere, and the somewhere',
    'has its own history worth reading.</p>',
    '<p><small>[ <a href="comics-ring.geocities.ws">Comics Ring</a> ]</small></p>',
    '<p><small>counter: 01954 · best viewed in Netscape at 800x600 · this page is',
    'PERMANENTLY under construction because i keep finding banned issues ·',
    'collectors\' webring welcome · last updated 14 Oct</small></p>',
    '<p><small>« a proud member of the ring · random · next »</small></p>',
  ]);

// ---- the comic shop: the scene page -----------------------------------------

const COMIC_SHOP = P('the-comic-shop.geocities.ws', 'COMIC SHOP',
  'THE DIRECT MARKET // Wednesday is the holy day', [
    '<!--bg:comics-culture-->',
    '<h1>THE COMIC SHOP</h1>',
    '<p><small>notes from behind the counter and in front of it, by someone who',
    'has smelled a lot of newsprint. this is about the SHOP as an institution, not',
    'any one shop. mine closed. they mostly do. i still go Wednesdays. — the',
    'saturday kid, now the tuesday adult</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>“New books are in.”<br>— the three best words in the',
    'week</p></div>',
    '<p>Before the specialist shop, comics were sold on a spinner rack next to the',
    'gum, on sale-or-return, and the shopkeeper did not care and could not order',
    'what he wanted. Then in the 1970s a man named Phil Seuling worked out a',
    'different deal with the publishers: buy the books outright, non-returnable, at',
    'a bigger discount, and in exchange get exactly the titles and the numbers you',
    'ask for. That is the DIRECT MARKET, and it built the shop you are picturing.</p>',
    '<div class="fs-aside"><p><b>WHY IT MATTERED.</b> Non-returnable meant the',
    'publisher no longer carried the risk of unsold copies, so it became safe to',
    'print odd, niche, adult, unseal-able things for a known audience of',
    'collectors. The shop is the reason the Comics Code could finally be ignored.',
    'See how that ended at <a href="the-comics-code.geocities.ws">the-comics-code',
    '</a>.</p></div>',
    '<h2>the furniture of the faith</h2>',
    '<pre>',
    'A FIELD GUIDE TO THE SHOP',
    '',
    '  THE WALL          the expensive new books and the key back issues,',
    '                    bagged and boarded, priced in pencil, do not touch',
    '  THE LONG BOXES    the fifty-cent and dollar bins, alphabetical if',
    '                    you are lucky, archaeology if you are not',
    '  BAGS AND BOARDS   polypropylene sleeve, acid-free backing board,',
    '                    the liturgy of preservation',
    '  THE PULL LIST     your standing order, your name on a box behind',
    '                    the counter, the closest thing to being known',
    '  THE GUIDE         the Overstreet Price Guide, the argument-settler,',
    '                    "near mint" versus "very fine" versus your dreams',
    '</pre>',
    '<p>Bag and board is not fussiness. Newsprint from before the 1980s was acid',
    'paper and it browns and it crumbles, and a bad crease or a spine roll drops a',
    'book two grades and half its value. Collectors learned conservation the hard',
    'way, one foxed cover at a time.</p>',
    '<img class="indie-pic" src="assets/media/web/comics/comic-shop-01.jpg" alt=""><span class="indie-cap">A comic-book shop interior (photo: Allan Ferguson, CC BY 2.0)</span>',
    '<div class="fs-pull"><p>“You do not have a comic collection. You have a',
    'humidity problem you are managing.”</p></div>',
    '<h2>Wednesday</h2>',
    '<p>New comics ship to shops on a Wednesday in the United States, and the word',
    'for the people who are there when the door opens is exactly what you think it',
    'is. The shop is a clubhouse as much as a shop. It is where you found out what',
    'was good before the internet would tell you, where somebody older pressed the',
    'right issue into your hands, where the argument about who could beat whom went',
    'on for years and hurt nobody. When you outgrow one thing you find the next in',
    'the long boxes, on your knees, sneezing.</p>',
    '<p>The natural next stop up from the shop is the convention, where every shop',
    'in the country empties its best stock onto one enormous floor. That has its',
    'own page at <a href="the-comic-con.geocities.ws">the-comic-con</a>, and you',
    'should take cash and comfortable shoes.</p>',
    '<p><small>[ <a href="comics-ring.geocities.ws">Comics Ring</a> ]</small></p>',
    '<p><small>hit counter: 00733 · best viewed at 800x600 in Netscape ·',
    'UNDER CONSTRUCTION (the back-issue database, forever) · last updated 2 Sep',
    '</small></p>',
    '<p><small>« ring member · random · next »</small></p>',
  ]);

// ---- 2000 AD: the anthology page --------------------------------------------

const TWOK_AD = P('2000ad.geocities.ws', '2000 AD',
  '2000 AD // Tharg\'s Thrill-Power since 1977', [
    '<!--bg:comics-culture-->',
    '<h1>2000 AD</h1>',
    '<p><small>a shrine to the Galaxy\'s Greatest Comic, kept by an earthlet who',
    'has bought it most weeks since the Betelgeuse days. Splundig vur thrigg, as',
    'the big green editor says. — a devoted squaxx dek Thargo</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>“Borag Thungg, Earthlets!”<br>— Tharg the Mighty, alien',
    'editor, most Progs</p></div>',
    '<p>On 26 February 1977 the first Prog of <i>2000 AD</i> went on sale in',
    'Britain, a weekly science-fiction anthology aimed at kids and fronted by a',
    'fictional green-skinned alien editor called Tharg the Mighty, who beamed the',
    'stories in from Betelgeuse as pure THRILL-POWER. It is still going. Nothing',
    'else from British comics of that era survived, and this one did it by being',
    'faster, nastier and cleverer than it was ever supposed to be.</p>',
    '<h2>the shape of a Prog</h2>',
    '<p>An anthology, so five or six short serial episodes an issue, six pages',
    'each, cliffhanger to cliffhanger. The masterstroke was the second issue, which',
    'introduced a lawman of the future in a fascist megacity, and he took over the',
    'whole comic and never gave it back.</p>',
    '<div class="fs-aside"><p><b>JUDGE DREDD.</b> Created by writer John Wagner and',
    'artist Carlos Ezquerra in 1977, Dredd is judge, jury and executioner in',
    'Mega-City One. The joke that runs underneath is that he is the hero and he is',
    'also a jackbooted authoritarian, and the strip has never once let you forget',
    'the second half. It is satire wearing a helmet you never see under.</p></div>',
    '',
    '<div class="fs-quote"><blockquote><p>“I am the Law!”<br>— Judge Dredd,',
    'repeatedly, and he is not kidding</p></blockquote></div>',
    '<h2>the school</h2>',
    '<p>Here is the thing history remembers <i>2000 AD</i> for. It was the finest',
    'training ground British comics ever had, and in the 1980s the American',
    'publishers came shopping and took the lot. If you have read the graphic-novel',
    'canon, you have read <i>2000 AD</i> graduates.</p>',
    '<pre>',
    'WHERE THEY LEARNED IT (a partial staff list)',
    '',
    '  Alan Moore ......... Skizz, D.R. & Quinch, Future Shocks, then away',
    '                       to Watchmen and the rest of the Earth',
    '  Grant Morrison ..... Zenith with Steve Yeowell, then the DC years',
    '  Pat Mills .......... founding editor, Nemesis the Warlock, Sláine,',
    '                       the angriest man in the building and its engine',
    '  John Wagner ........ Judge Dredd, Strontium Dog, the house voice',
    '  Alan Grant ......... Dredd and Strontium Dog with Wagner',
    '  and the artists: Bolland, Ezquerra, McMahon, Gibbons, ONeill ...',
    '</pre>',
    '<p>Moore and Morrison both did their apprenticeship here on the short',
    '"Future Shock", a twist-ending one-off that taught you to build a whole world',
    'and knock it down in four pages. You can see the discipline in everything they',
    'wrote afterwards. The horror and crime that the American Comics Code',
    'strangled in 1954 came back into comics partly through this British side door,',
    'and the older American shock it echoes lived at',
    '<a href="ec-comics.geocities.ws">ec-comics</a>.</p>',
    '<div class="fs-pull"><p>“Thrill-power is a measurable quantity and Tharg is',
    'watching the dials.”</p></div>',
    '<p>You bought it off the newsagent\'s shelf, not from a specialist',
    '<a href="the-comic-shop.geocities.ws">comic shop</a>, because Britain never',
    'had much of a direct market. It came folded in a satchel,',
    'read to bits by Monday, swapped in the playground. That is a different economy',
    'of comics entirely from the American one, and it is why a British reader and',
    'an American reader of the same age grew up with almost no titles in common.</p>',
    '<p><small>[ <a href="comics-ring.geocities.ws">Comics Ring</a> ]</small></p>',
    '<p><small>counter: 02000 · best viewed in Netscape at 800x600 · this site is',
    'Tharg-approved and 100% thrill-powered · last updated 26 Feb</small></p>',
    '<p><small>« squaxx ring member · random · next »</small></p>',
  ]);

// ---- EC Comics: the publisher page ------------------------------------------

const EC_COMICS = P('ec-comics.geocities.ws', 'EC COMICS',
  'EC COMICS // Gaines, the Crypt, and the best two years in comics', [
    '<!--bg:comics-culture-->',
    '<h1>EC COMICS</h1>',
    '<p><small>a publisher shrine to Entertaining Comics, the company that was too',
    'good to be allowed to live, kept by a pre-Code obsessive. everything the Code',
    'was built to kill, EC did first and best. — the crypt-keeper\'s apprentice',
    '</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>“Good evening, boils and ghouls.”<br>— the Crypt-Keeper,',
    'your host, Tales from the Crypt</p></div>',
    '<p>Entertaining Comics was a small New York publisher that, for a few years in',
    'the early 1950s, produced the sharpest, best-drawn, most grown-up comic books',
    'anyone had made. Then it was legislated out of existence. The story of EC and',
    'the story of the Comics Code are the same story told from opposite ends.</p>',
    '<h2>the man</h2>',
    '<p>William M. Gaines inherited the company from his father Max in 1947 and did',
    'not much want it. Then he found the horror line and the right editors and',
    'artists, and for a short while EC was the place where the talent wanted to be.',
    'Gaines is the man who sat before the Senate in 1954 and defended the medium,',
    'the afternoon that ended the New Trend line and, in the end, the whole',
    'business.</p>',
    '<pre>',
    'THE NEW TREND LINE (the great years, roughly 1950 to 1954)',
    '',
    '  TALES FROM THE CRYPT ....... horror, the Crypt-Keeper hosting',
    '  THE VAULT OF HORROR ........ horror, the Vault-Keeper hosting',
    '  THE HAUNT OF FEAR .......... horror, the Old Witch hosting',
    '  WEIRD SCIENCE .............. science fiction, Feldstein & Kurtzman',
    '  WEIRD FANTASY .............. science fiction, the Bradbury adaptations',
    '  CRIME SUSPENSTORIES ........ crime, the cover that hanged them',
    '  SHOCK SUSPENSTORIES ........ social horror: racism, lynching, bigotry',
    '  MAD ........................ Kurtzman, 1952, the one that got away',
    '</pre>',
    '',
    '<p>Look at that list. Three of them are horror titles hosting their stories',
    'through a ghoulish narrator, a format the whole medium copied. <i>Weird',
    'Science</i> and <i>Weird Fantasy</i> ran adaptations of a young Ray Bradbury,',
    'after Bradbury politely pointed out they had adapted him without asking and',
    'Gaines, to his credit, started paying him. <i>Shock SuspenStories</i> ran',
    'stories about racism and mob violence that were braver than most of what the',
    '"respectable" press would print.</p>',
    '<div class="fs-aside"><p><b>THE ARTISTS.</b> EC ran a stable most publishers',
    'would kill for: Jack Davis, Graham Ingels on the horror, Wally Wood and Al',
    'Williamson on the science fiction, Johnny Craig, Bernard Krigstein whose',
    '"Master Race" (1955) is one of the finest short comics ever drawn, and Harvey',
    'Kurtzman running the war titles and then <i>Mad</i>. The war books, <i>Frontline',
    'Combat</i> and <i>Two-Fisted Tales</i>, were anti-war at the height of Korea.',
    '</p></div>',
    '<div class="fs-quote"><blockquote><p>“Are you making a horror comic that we',
    'should be worried about, Mr Gaines?”<br>— the sense of the 1954 hearings, in',
    'a sentence</p></blockquote></div>',
    '<h2>the kill and the survivor</h2>',
    '<p>The Code of 1954 banned the words horror and terror in titles, banned the',
    'walking dead and the vampire and the ghoul by name, and required that crime',
    'never be shown with sympathy and that good always visibly win. Every one of',
    'those rules was aimed at what EC did every month. Gaines shut the New Trend',
    'line down in 1955. He kept <i>Mad</i>, converted it from a colour comic into a',
    'black-and-white magazine so it fell outside the Code entirely, and <i>Mad</i>',
    'went on to shape American satire for forty years. The company that the Code',
    'destroyed left behind the one title the Code could not touch.</p>',
    '<div class="fs-pull"><p>“They took the horror line. They did not get Alfred E.',
    'Neuman.”</p></div>',
    '<p>EC\'s influence never died. The horror-host format, the twist ending, the',
    'anthology of nasty little moral tales, all of it came back through British',
    'weeklies and through 1980s creators who had grown up on smuggled copies. The',
    'British inheritor of the anthology-of-shocks idea is at',
    '<a href="2000ad.geocities.ws">2000ad</a>, and the form EC spent its war titles',
    'quietly criticising, the man in the costume, is examined at',
    '<a href="the-superhero.geocities.ws">the-superhero</a>.</p>',
    '<p><small>[ <a href="comics-ring.geocities.ws">Comics Ring</a> ]</small></p>',
    '<p><small>counter: 01950 · best viewed at 800x600 · SPOILERS BELOW for stories',
    'older than your grandparents · a member of the pre-Code collectors\' webring ·',
    'last updated 31 Oct</small></p>',
    '<p><small>« ring member, boils and ghouls · random · next »</small></p>',
  ]);

// ---- the comic con: the scene page ------------------------------------------

const COMIC_CON = P('the-comic-con.geocities.ws', 'COMIC CON',
  'THE COMIC CONVENTION // the fandom made flesh', [
    '<!--bg:comics-culture-->',
    '<h1>THE COMIC CONVENTION</h1>',
    '<p><small>field notes from the convention floor, kept by someone who has slept',
    'on more hotel-room floors than she will admit and queued for things she can no',
    'longer remember wanting. take water. take cash. — con-goer, badge number',
    'long since laminated</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>“I came for the back issues and stayed for the people.”',
    '<br>— every con-goer, eventually</p></div>',
    '<p>A comic convention is what happens when the clubhouse gets too big for one',
    'shop and rents a hall. Dealers bring their long boxes and their wall books,',
    'creators sit at tables and sign and sketch, the fans come in costume, and for',
    'a weekend the thing you were slightly embarrassed to love in your town is the',
    'only thing anyone in the building cares about.</p>',
    '<h2>San Diego, and how it grew</h2>',
    '<p>The big one started small. In 1970 a group of San Diego fans ran a modest',
    'convention, a few hundred people, dealers and a couple of guest creators, and',
    'it grew, and grew, until San Diego Comic-Con became a phenomenon that fills a',
    'convention centre and half a city and that Hollywood now treats as a launch',
    'pad. It was fans, not an industry, who built it. That order matters.</p>',
    '<div class="fs-aside"><p><b>A NOTE ON THE WORD FAN.</b> Comics fandom is older',
    'than the conventions. It ran on mimeographed fanzines and letters columns and',
    'the postal service for decades before anyone met in a hall. The con did not',
    'invent the community. It gave a community that already existed a room, and a',
    'weekend, and a way to see each other\'s faces.</p></div>',
    '<pre>',
    'THE FLOOR (a rough map of any con)',
    '',
    '  DEALERS ALLEY ...... the long boxes, the wall of keys, the haggle',
    '  ARTISTS ALLEY ...... creators at tables, prints, commissions, the',
    '                       nervous first-timer next to the legend',
    '  PANELS ............. announcements, retrospectives, "an hour with",',
    '                       the queue that starts three panels early',
    '  COSPLAY ............ the costumes, the photo scrums, the craft that',
    '                       took six months of evenings',
    '  THE QUEUE .......... a place, a culture, and a test of character',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/comics/comic-con-01.jpg" alt=""><span class="indie-cap">The Comic-Con hall (photo: William Tung, CC BY-SA 2.0)</span>',
    '<div class="fs-pull"><p>“The con is the one place the pull list becomes a',
    'crowd.”</p></div>',
    '<p>The trade side is real. A convention is the biggest back-issue shop in the',
    'world for one weekend, and the grading arguments and the bag-and-board rituals',
    'you know from the shop are all here at scale. If the specialist shop is your',
    'parish, the con is the pilgrimage, and both are described from the counter side',
    'at <a href="the-comic-shop.geocities.ws">the-comic-shop</a>.</p>',
    '<p>There is a shadow to the growth, and honest fans say it out loud. The bigger',
    'a con gets, the more it becomes a marketing event for films and games with the',
    'comics pushed to the back tables, and the harder it gets for the small-press',
    'creator to afford a place on the floor. The convention that fans built for',
    'comics can end up being a place where comics are the least of it. Where the',
    'medium itself came under a different kind of pressure, from the censors rather',
    'than the marketers, is the story at',
    '<a href="the-comics-code.geocities.ws">the-comics-code</a>.</p>',
    '<p><small>[ <a href="comics-ring.geocities.ws">Comics Ring</a> ]</small></p>',
    '<p><small>hit counter: 01970 · best viewed in Netscape at 800x600 · this page',
    'UNDER CONSTRUCTION until i scan my badge collection · con-goers\' webring ·',
    'last updated 20 Jul</small></p>',
    '<p><small>« ring member · random · next »</small></p>',
  ]);

// ---- the superhero: the close-reading essay page ----------------------------

const SUPERHERO = P('the-superhero.geocities.ws', 'SUPERHERO',
  'THE SUPERHERO // a close reading of the form', [
    '<!--bg:comics-culture-->',
    '<h1>THE SUPERHERO</h1>',
    '<p><small>an essay page, not a fan shrine, though i am a fan. i want to read',
    'the FORM: the costume, the double life, the origin, and the argument about',
    'what it all means. citations are to real issues. corrections welcome. — a',
    'reader who thinks about this too much</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>“Look! Up in the sky!”<br>— the crowd, forever</p></div>',
    '<p>In June 1938 a man in a blue suit and a red cape lifted a car over his head',
    'on the cover of <i>Action Comics</i> No. 1, and a form was born. Superman,',
    'created by Jerry Siegel and Joe Shuster, two young men from Cleveland who sold',
    'the rights for a pittance and spent their lives regretting it, set almost every',
    'convention of the genre in a single figure. Read the form and you read a strange',
    'modern folklore.</p>',
    '<h2>the three parts</h2>',
    '<p>Strip a superhero down and you find three things doing the work, and they',
    'are worth taking one at a time.</p>',
    '<pre>',
    'THE GRAMMAR OF THE FORM',
    '',
    '  THE COSTUME .......... a heraldic device worn on the body. It is not',
    '                         a disguise so much as a FLAG. Bright, simple,',
    '                         readable at a glance, a walking logo.',
    '  THE SECRET IDENTITY .. the double life. Clark Kent and Superman,',
    '                         Bruce Wayne and Batman. The mask is not only',
    '                         hiding the hero. It is hiding the ordinary',
    '                         person the hero cannot afford to be.',
    '  THE ORIGIN ........... the wound that makes the mission. The dead',
    '                         parents, the doomed planet, the radioactive',
    '                         accident. Retold endlessly because it is the',
    '                         moral engine, not just the backstory.',
    '</pre>',
    '<p>Take the secret identity first, because it is the part that carries the',
    'most weight. The double life stages a wish and a fear at once. The wish: that',
    'the ordinary clerk, the ignored teenager, is secretly the most important person',
    'alive. The fear: that to be powerful you must hide who you really are, and can',
    'never be fully known. Siegel and Shuster, two Jewish kids in Depression',
    'Cleveland, wrote an immigrant who passes as mild-mannered and is secretly a god.',
    'The form has never quite stopped being about who gets to belong.</p>',
    '<img class="indie-pic" src="assets/media/web/comics/early-comic-01.jpg" alt=""><span class="indie-cap">The Yellow Kid by R. F. Outcault (public domain)</span>',
    '<div class="fs-quote"><blockquote><p>“This looks like a job for Superman.”<br>',
    '— Clark Kent, stepping into the phone booth, the double life in one line',
    '</p></blockquote></div>',
    '<h2>the ages</h2>',
    '<p>Fandom sorts the history into ages, and the scheme is rough but useful. It',
    'is a way of saying the form kept renegotiating its relationship to its own',
    'innocence.</p>',
    '<pre>',
    'THE AGES (fan periodisation, contested at the edges)',
    '',
    '  GOLDEN  1938 on ... Superman, Batman, Wonder Woman, Captain America.',
    '                      The form invented, the war fought in four colours.',
    '  SILVER  1956 on ... the Flash rebooted, the Marvel explosion (Lee,',
    '                      Kirby, Ditko), heroes with problems and rent.',
    '  BRONZE  1970 on ... the drug issues, relevance, the first cracks,',
    '                      the Code loosened, death allowed back in.',
    '  DARK    1986 on ... Watchmen and The Dark Knight Returns. The form',
    '                      turns and reads ITSELF. Nothing quite innocent after.',
    '</pre>',
    '<p>The line between the Silver and the Dark ages runs straight through 1986,',
    'the year the superhero was taken apart from the inside by two books. If you',
    'want the close reading of that turn, it is at',
    '<a href="2000ad.geocities.ws">2000ad</a> that a generation of the writers who',
    'did the taking-apart learned their trade first.</p>',
    '<div class="fs-aside"><p><b>THE ARGUMENT ABOUT IT.</b> The critics have never',
    'agreed what the superhero is FOR. Umberto Eco, in a famous 1962 essay on',
    'Superman, argued the hero is trapped in a mythic present where nothing can',
    'permanently change, which is why the status quo always resets. Others read the',
    'form as American power fantasy, a fascination with the strong man that deserves',
    'suspicion, and the darker 1980s books took that suspicion and made it the',
    'subject. Both readings are in the room whenever a hero puts on a mask.',
    '</p></div>',
    '<div class="fs-pull"><p>“A costume is an argument about who gets to be seen and',
    'who has to hide.”</p></div>',
    '<p>There is a case for the defence and it is not naive. The superhero is a',
    'modern mythology, a shared body of stories a whole culture can retell and',
    'argue with, and the best of them ask real questions about power and',
    'responsibility inside a form aimed at children. There is a case for the',
    'prosecution too, that a fantasy of a strong figure who solves by force what',
    'politics cannot is a fantasy worth being wary of, and the form is honest',
    'enough to have staged that very worry in its own pages. The version of the',
    'medium that once tried to do without the costume, the horror and crime line',
    'the censors then destroyed, is the counter-history at',
    '<a href="ec-comics.geocities.ws">ec-comics</a>.</p>',
    '<p><small>[ <a href="comics-ring.geocities.ws">Comics Ring</a> ]</small></p>',
    '<p><small>counter: 01938 · best viewed at 800x600 · this essay is a work in',
    'progress and always will be · corrections and citations welcome · last updated',
    '9 Aug</small></p>',
    '<p><small>« ring member · random · next »</small></p>',
  ]);

export const COMX_F = [COMICS_CODE, COMIC_SHOP, TWOK_AD, EC_COMICS, COMIC_CON, SUPERHERO];
