// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — the world & the vernacular.
//
// The architecture web of a student who went looking past the usual masters:
// tropical modernism in Sri Lanka, mud brick in Egypt, the humane modern in
// India, concrete and light in Japan, colour and water in Mexico, and the
// anonymous building the moderns had to relearn. Pages ABOUT the architects,
// never in their voice. Buildings, dates and ideas are real; the enthusiasm,
// the coursework and the webring furniture belong to the fans.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Geoffrey Bawa: the showpiece shrine ------------------------------------

const BAWA = P('geoffrey-bawa.geocities.ws', 'GEOFFREY BAWA',
  'GEOFFREY BAWA // tropical modernism & the walk', [
    '<!--bg:arch-world-->',
    '<h1>GEOFFREY BAWA</h1>',
    '<p><small>a shrine to Geoffrey Bawa (1919&ndash;2003), the architect of',
    'tropical modernism, kept by an architecture student who spent a whole',
    'monsoon at Lunuganga and came back changed. everything here i checked twice.',
    'corrections welcome. &mdash; Priya</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;One cannot really explain a Bawa building. One has',
    'to experience it, to walk through it.&rdquo; &mdash; a line remembered from',
    'the studio, on why the plans never tell you enough</p>',
    '<p>Bawa came to architecture late, and by the long way round. He read',
    'English at Cambridge, qualified as a barrister at the Middle Temple, and only',
    'in his thirties turned to building, training at the Architectural Association',
    'in London and qualifying around 1957. He was almost forty when he began the',
    'work that made him. That late start matters, because he never designed like a',
    'man in a hurry to prove a theory.</p>',
    '<p>What he built was a modern architecture that belonged to the tropics and',
    'to Sri Lanka. Not the white box shipped out from Europe and left to bake, but',
    'a modern that opened itself to the monsoon and the heat: deep verandahs, open',
    'courtyards, roofs that reach out for shade, walls that stop being walls so the',
    'garden can walk indoors. He took the courtyard house of the region and the',
    'plan of the modern movement and would not choose between them.</p>',
    '<p class="fs-pull">The building is not an object you look at. It is a walk',
    'you take, and the view is rationed to you one frame at a time.</p>',
    '<p>The idea people reach for is THE WALK. A Bawa building is arranged as a',
    'sequence, a route through shade and light and courtyard and sudden view. You',
    'do not see the whole thing at once. You are led, turned, held at a threshold,',
    'and then the landscape is handed to you through a precise opening, and then',
    'taken away again. The section does as much work as the plan.</p>',
    '',
    '<p><b>Lunuganga</b></p>',
    '<p>He bought a rubber estate at Bentota in 1948 and spent the rest of his',
    'life turning it into a garden, Lunuganga, moving hills and framing views of',
    'the lake for decades. It was his laboratory. Whatever he learned about siting',
    'a building in a landscape, about the borrowed view and the long axis, he',
    'learned there first and carried into the commissions. His brother Bevis kept',
    'a garden of his own nearby at Brief, so the whole thing rather ran in the',
    'family.</p>',
    '<p><b>The Kandalama hotel</b></p>',
    '<p>The building everyone means is the Kandalama, near Dambulla, finished in',
    'the early 1990s. Bawa laid it along a rock face above the Kandalama reservoir,',
    'and rather than clear the site he let the building grow into the rock. The',
    'stone of the hillside runs straight through the corridors. The concrete is',
    'meant to disappear under climbing plants, so from across the water you see a',
    'green cliff and only slowly notice the storeys in it. From inside, the view',
    'reaches all the way to the rock of Sigiriya. It is the clearest thing he ever',
    'built about how a large modern building can sit lightly on a place instead of',
    'flattening it.</p>',
    '<div class="fs-aside"><b>did you know?</b> The new Sri Lankan Parliament at',
    'Sri Jayawardenepura Kotte (1979&ndash;1982) is Bawa&rsquo;s too. He set the',
    'assembly on an island in an artificial lake, a cluster of pavilions under',
    'wide copper roofs, so the seat of government reads as a Kandyan pavilion',
    'grown to national scale rather than a borrowed European dome.</div>',
    '<blockquote class="fs-quote"><p>&ldquo;I have never been able to',
    'think about architecture in an abstract way. The building comes from the',
    'place.&rdquo; &mdash; the sense of Bawa, as his students report it</p></blockquote>',
    '<p>His own house grew down a lane in Colombo, number 33, four small houses',
    'knocked slowly into one over the years, a maze of courtyards and light-wells',
    'in the middle of the city. If you want to understand the walk, people say,',
    'start there and not at the famous hotel.</p>',
    '',
    '<p>The essential Bawa, for the notebook:</p>',
    '<pre>',
    ' BUILDING                         PLACE              c.',
    ' -------------------------------  -----------------  -------',
    ' Lunuganga (garden estate)        Bentota            1948-',
    ' Bentota Beach Hotel              Bentota            1968',
    ' Bawa house, 33rd Lane            Colombo            1960s-',
    ' Sri Lankan Parliament            Kotte              1979-82',
    ' University of Ruhuna             Matara             1980s',
    ' Kandalama Hotel                  nr Dambulla        1991-94',
    ' Blue Water Hotel                 Wadduwa            1998',
    ' -------------------------------  -----------------  -------',
    ' the thread through all of it: the courtyard, the framed',
    ' view, the roof reaching for shade, the walk</pre>',
    '<p>Two neighbours on this ring worth the trip. Hassan Fathy at',
    '<a href="hassan-fathy.geocities.ws">hassan-fathy</a> was doing the same',
    'listening to place and climate a continent away, in mud brick, for the poor.',
    'And Tadao Ando at <a href="tadao-ando.geocities.ws">tadao-ando</a> is the',
    'opposite material, smooth concrete against Bawa&rsquo;s rough plaster, but the',
    'same conviction that light and route are the real building. Corbusier and',
    'Kahn stand behind a lot of this too, though neither has a page in our ring.</p>',
    '<hr>',
    '<p><small>counter: 01977 · best viewed in Netscape at 800x600 · this corner',
    'still under construction, the Lunuganga photos are coming · last updated 4',
    'Aug</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
  ]);

// ---- Hassan Fathy: a single-building close reading of New Gourna ------------

const FATHY = P('hassan-fathy.geocities.ws', 'HASSAN FATHY',
  'NEW GOURNA // architecture for the poor (Fathy)', [
    '<!--bg:arch-world-->',
    '<h1>NEW GOURNA</h1>',
    '<p><small>a close reading of one village, and of the man who built it:',
    'Hassan Fathy (1900&ndash;1989). notes for ARCH 214, the vernacular seminar.',
    'kept up by a conservation volunteer who has actually stood in the mosque',
    'there. &mdash; Tom</small></p>',
    '<hr>',
    '<p>Between 1946 and roughly 1952, the Egyptian architect Hassan Fathy built a',
    'whole village near Luxor. New Gourna was meant to rehouse the people of Old',
    'Gourna, who lived on the hillside directly over the tombs of the Theban',
    'nobles and were, the authorities said, making a living from what lay beneath',
    'their floors. The state wanted them moved. Fathy was given the job of building',
    'somewhere for them to go.</p>',
    '<p>What makes it a landmark is that he refused the obvious answer. He did not',
    'reach for concrete and imported steel and the cheapest modern shed. He built',
    'in mud brick, the material of the place, made from the earth of the site by',
    'the people who would live there.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Architecture for the poor&rdquo; is',
    'the phrase that stuck, from the title of his 1973 book. He first told the',
    'story as <i>Gourna: A Tale of Two Villages</i>.</p></blockquote>',
    '<p><b>The Nubian vault</b></p>',
    '<p>The technical heart of it is the roof. Mud brick will make a wall easily',
    'enough, but roofing a room is the hard part, and timber was scarce and',
    'expensive. Fathy went to Aswan and found Nubian masons who still knew how to',
    'raise a vault in mud brick with no timber centring at all, leaning each course',
    'of bricks back against the last at an angle so the arch builds itself in the',
    'air as it goes. He learned the craft from them and made it the signature of',
    'New Gourna: the vault and the dome over every room, and no forest felled to',
    'hold them up while they set.</p>',
    '',
    '<p><b>Building for the climate</b></p>',
    '<p>Every move answers the heat of Upper Egypt without a watt of power. The',
    'courtyard at the centre of the house holds cool night air. The <i>malqaf</i>,',
    'the wind-catch, rises above the roof to scoop the prevailing breeze and pour',
    'it down through the rooms. Thick mud walls lag the day&rsquo;s heat so it',
    'arrives after dark when it is wanted. The high domed ceiling lets the hot air',
    'rise off the sleepers below. None of it was invented by Fathy. All of it was',
    'the accumulated wisdom of the region, which the concrete box had thrown away.</p>',
    '<div class="fs-aside"><b>a hard honesty about it:</b> New Gourna was not a',
    'simple success. Many of the Gourna families did not want to leave the tombs',
    'and the tourist trade, drainage and a rising water table damaged the fabric,',
    'and much of the village was never occupied as planned. Fathy wrote the failure',
    'into the book himself. The IDEA outran the one village, and that is why the',
    'one village still gets taught.</div>',
    '<p>Read Fathy next to Balkrishna Doshi at',
    '<a href="balkrishna-doshi.geocities.ws">balkrishna-doshi</a>, who took the',
    'same question, decent housing for people without money, into India and modern',
    'materials. And the whole argument sits inside the case Geoffrey Bawa makes at',
    '<a href="geoffrey-bawa.geocities.ws">geoffrey-bawa</a>, that a serious modern',
    'architecture answers its own climate and place before it answers a magazine.</p>',
    '<hr>',
    '<p><small>hits: 00842 · best viewed at 800x600 · a member of the buildings',
    'webring · seminar notes, do not cite without the book · last updated 22',
    'Jan</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
  ]);

// ---- Balkrishna Doshi: an architect profile ---------------------------------

const DOSHI = P('balkrishna-doshi.geocities.ws', 'B.V. DOSHI',
  'BALKRISHNA DOSHI // the humane modern (Pritzker 2018)', [
    '<!--bg:arch-world-->',
    '<h1>BALKRISHNA DOSHI</h1>',
    '<p><small>a tribute page to B. V. Doshi (1927&ndash;2023), the architect who',
    'made the modern movement live in India, put up the week he won the Pritzker.',
    'i am an ordinary fan with a library card, not an expert. &mdash; Anand</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;An environment is not a building. It is what happens',
    'between buildings, where life is lived.&rdquo; &mdash; the spirit of Doshi,',
    'as his lectures are remembered</p>',
    '<p>Doshi is the bridge. He worked for four years in Paris in the early 1950s',
    'in the atelier of Le Corbusier, then went home to Ahmedabad to supervise',
    'Corbusier&rsquo;s Indian buildings on the ground. A little later he worked',
    'alongside Louis Kahn on the Indian Institute of Management at Ahmedabad. So he',
    'carried the two great masters of concrete inside him, and then spent fifty',
    'years arguing gently with both, softening their grandeur into something a',
    'hot, crowded, low-budget country could actually use and love.</p>',
    '<p><b>Sangath</b></p>',
    '<p>His own studio in Ahmedabad, Sangath, finished in 1980, is the clearest',
    'statement of who he became. Low vaults half-buried in the earth, their curved',
    'roofs clad in broken white china mosaic to throw off the sun, water channels',
    'and grass between them. You go DOWN into it, out of the heat. The name means',
    '&ldquo;moving together&rdquo;. It is a modern building that behaves like a',
    'shaded garden.</p>',
    '',
    '<p class="fs-pull">He asked what the modern movement would look like if it',
    'had grown up in the Indian heat, on an Indian budget, and had been made to be',
    'kind.</p>',
    '<p><b>Aranya</b></p>',
    '<p>The work that shows his conscience is Aranya, a low-cost housing scheme at',
    'Indore from the late 1980s, planned for something like eighty thousand people,',
    'most of them poor. Doshi did not hand down finished flats. He laid out the',
    'streets, the drains, the courtyards and a core house, a room and a service',
    'plinth, and left the families to build and grow their own homes upward and',
    'outward as they could afford to. The plan gave dignity and left room for life',
    'to fill it in. It won the Aga Khan Award for Architecture.</p>',
    '<div class="fs-aside"><b>did you know?</b> Doshi founded the school now',
    'called CEPT University in Ahmedabad, and with the painter M. F. Husain made',
    'Amdavad ni Gufa, an underground gallery of connected domes like a cave. In',
    '2018 he became the first architect from India to win the Pritzker Prize.</div>',
    '<p>His near neighbours on this ring: Hassan Fathy at',
    '<a href="hassan-fathy.geocities.ws">hassan-fathy</a>, who took the same care',
    'for the poor into mud brick in Egypt, and Tadao Ando at',
    '<a href="tadao-ando.geocities.ws">tadao-ando</a>, the other great inheritor of',
    'Kahn&rsquo;s concrete, though Ando polishes where Doshi shades and buries.</p>',
    '<hr>',
    '<p><small>counter: 00518 · best in Netscape 800x600 · proud building-spotter,',
    'ring member · last updated 9 Mar</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
  ]);

// ---- Tadao Ando: a single-building close reading -----------------------------

const ANDO = P('tadao-ando.geocities.ws', 'TADAO ANDO',
  'THE CHURCH OF THE LIGHT // concrete & light (Ando)', [
    '<!--bg:arch-world-->',
    '<h1>THE CHURCH OF THE LIGHT</h1>',
    '<p><small>a close reading of one small building by Tadao Ando (b. 1941), the',
    'self-taught master. written for the ARCH 301 seminar and never handed back, so',
    'i am putting it here. &mdash; K.</small></p>',
    '<hr>',
    '<p>Ando is the architect nobody taught. He never went to architecture school.',
    'He was a boxer, then he travelled and looked hard at buildings, from Kyoto to',
    'the Pantheon to the work of Le Corbusier, and he taught himself by drawing',
    'them. What came out of that is one of the most disciplined bodies of work of',
    'the century, and it is built from almost nothing: smooth grey concrete,',
    'daylight, water, and a very few clean geometric shapes.</p>',
    '<p>The concrete is the first thing people notice. Ando&rsquo;s formwork is so',
    'exact that the finished wall is silky, almost like stone or skin, with the',
    'little tie-holes left in a calm regular grid across it. The surface is the',
    'decoration, because there is no other decoration. Nothing is applied. The wall',
    'is simply, exactly, itself.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I create enclosed spaces mainly by',
    'means of thick concrete walls. The primary reason is to create a place for the',
    'individual, a zone for oneself.&rdquo; &mdash; the sense of Ando</p></blockquote>',
    '<p><b>The building itself</b></p>',
    '<p>The Church of the Light, at Ibaraki near Osaka, was finished in 1989. It',
    'is a plain concrete box. In the wall behind the altar Ando cut a cross, a',
    'vertical slit and a horizontal slit meeting, straight through the concrete, so',
    'that the only real ornament in the room is the sunlight itself, pouring',
    'through the gap in the shape of a cross and moving across the dark interior as',
    'the day turns. The floor and pews step down toward it. The light does what a',
    'stained-glass window costing a hundred times more would try to do, with a saw',
    'cut and the sun.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/church-of-the-light-01.jpg" alt=""><span class="indie-cap">The Church of the Light by Tadao Ando (photo: Bujatt, CC BY-SA 2.5)</span>',
    '<p>The section is the whole idea:</p>',
    '<pre>',
    '   outside            inside the box',
    '   sunlight  ->  |####|        |',
    '                 |###+|........ altar wall',
    '                 |####|        |   with the cut cross:',
    '                 |####|        |',
    '                 |###-+-###|   |        |',
    '                 |####|        |   -----+-----',
    '                 |####|        |        |',
    '   a slot in the concrete, and the sun does the rest</pre>',
    '<p><b>The Row House</b></p>',
    '<p>The building that made his name was smaller still. The Row House at',
    'Sumiyoshi in Osaka, the Azuma House of 1976, is a narrow concrete home',
    'squeezed into a terrace, and Ando put an open courtyard straight through its',
    'middle. To cross from the bedroom to the kitchen you step outside, under the',
    'sky, in the rain if it is raining. He gave the family light and air and a',
    'piece of the weather, and in exchange asked them to feel the seasons every',
    'day. That bargain, comfort traded for intensity, is the whole of his',
    'architecture in one small house.</p>',
    '<p>For the material opposite of all this rough-cast against smooth, walk over',
    'to Luis Barrag&aacute;n at',
    '<a href="luis-barragan.geocities.ws">luis-barragan</a>, who works light and',
    'water like Ando but in hot colour instead of grey. And Balkrishna Doshi at',
    '<a href="balkrishna-doshi.geocities.ws">balkrishna-doshi</a> is the other heir',
    'of Louis Kahn, warming the same concrete for the Indian sun.</p>',
    '<hr>',
    '<p><small>hits: 00951 · best viewed at 800x600 · viewed best on a decent',
    'monitor, the concrete needs the greys · webring for buildings, member · last',
    'updated 30 Nov</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
  ]);

// ---- Luis Barragán: an architect profile ------------------------------------

const BARRAGAN = P('luis-barragan.geocities.ws', 'LUIS BARRAGAN',
  'LUIS BARRAGAN // colour, water, wall (Pritzker 1980)', [
    '<!--bg:arch-world-->',
    '<h1>LUIS BARRAG&Aacute;N</h1>',
    '<p><small>a page for Luis Barrag&aacute;n (1902&ndash;1988), the Mexican',
    'master of colour and water and wall. kept by someone who saved for two years',
    'to go and stand in the courtyard of the Casa Barrag&aacute;n and would do it',
    'again tomorrow. &mdash; Sofia</small></p>',
    '<hr>',
    '<p>Barrag&aacute;n trained as an engineer in Guadalajara and might have stayed',
    'a competent modernist among many. What changed him was looking backward and',
    'sideways: the walled gardens of the Mediterranean and Morocco, the writings of',
    'Ferdinand Bac, the plain lime-washed walls and quiet water of the Mexican',
    'hacienda and convent. He put all of that through the discipline of the modern',
    'plan and arrived somewhere no one else was.</p>',
    '<p>His materials are almost embarrassingly simple. A tall plane of wall,',
    'rendered and painted a single strong colour, pink or ochre or a deep',
    'purple-blue, taken from the market stalls and the folk houses of Mexico. A',
    'still sheet or a running channel of water. A shaft of daylight let in high and',
    'sideways. Space you cannot see all of at once. Out of those he made rooms and',
    'courtyards that stop people in their tracks and, quite often, make them cry,',
    'which is exactly what he was after.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I believe in an emotional',
    'architecture. It is very important for humankind that architecture should move',
    'by its beauty.&rdquo; &mdash; Luis Barrag&aacute;n</p></blockquote>',
    '<p><b>The two you must know</b></p>',
    '<p>The Casa Barrag&aacute;n in Mexico City, his own house and studio from',
    '1948, looks shut and ordinary from the street and opens inside into a sequence',
    'of tall, calm, colour-washed rooms and a wild roof terrace closed off with',
    'coloured walls so that all you see is the sky. It is now protected as a World',
    'Heritage site, one of very few single houses to be listed for what it does to',
    'the person standing in it.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/casa-barragan-01.jpg" alt=""><span class="indie-cap">Cuadra San Cristóbal by Luis Barragán (photo: Anna Bertho, CC BY-SA 4.0)</span>',
    '<p>And the Cuadra San Crist&oacute;bal, at Los Clubes outside the city, from',
    'the late 1960s, an estate built around horses. A great pink wall with a',
    'square opening, a wide pink plane spilling a sheet of water into a pool where',
    'the horses drink, the animals and their riders crossing the frame. It is the',
    'clearest thing he made about wall, water, colour and the living body moving',
    'through them.</p>',
    '<p class="fs-epi">&ldquo;Beauty, inspiration, magic, enchantment, serenity,',
    'silence, intimacy and amazement.&rdquo; &mdash; the words Barrag&aacute;n',
    'used for what architecture had forgotten</p>',
    '<p>In 1980 he became only the second person to win the Pritzker Prize, which',
    'brought the wider world to a body of work that is, in the end, quite small and',
    'almost entirely in and around one city.</p>',
    '<p>Where to go next on the ring. The wider tradition Barrag&aacute;n drank',
    'from, the anonymous walled house of a hot country, is set out at',
    '<a href="the-vernacular.geocities.ws">the-vernacular</a>. And Tadao Ando at',
    '<a href="tadao-ando.geocities.ws">tadao-ando</a> is the cool northern cousin,',
    'the same love of a plain wall and controlled light, in grey concrete rather',
    'than hot lime-wash.</p>',
    '<hr>',
    '<p><small>counter: 00733 · best viewed in Netscape at 800x600 · the colour',
    'photos never look right on a monitor, go and see it · ring member · last',
    'updated 17 Apr</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
  ]);

// ---- The Vernacular: a movement / idea page ---------------------------------

const VERNACULAR = P('the-vernacular.geocities.ws', 'THE VERNACULAR',
  'THE VERNACULAR // architecture without architects', [
    '<!--bg:arch-world-->',
    '<h1>THE VERNACULAR</h1>',
    '<p><small>an idea page on vernacular architecture, the building that no famous',
    'name designed. kept by a conservation volunteer who got tired of every history',
    'starting with a genius and a drawing board. &mdash; the barn-and-courtyard',
    'appreciation society (membership: me)</small></p>',
    '<hr>',
    '<p>Vernacular architecture is the ordinary building of a place: the farmhouse,',
    'the barn, the courtyard house, the hill village, the market, the shrine, made',
    'over centuries by the people who used them, out of what the ground gave, to',
    'answer the weather they actually had. No architect signed it. No style was',
    'declared. And yet it is often wiser about heat and cold and rain than the',
    'clever building next door.</p>',
    '<p class="fs-pull">Nobody designed it and everybody did. It is the slow',
    'answer a whole society worked out to the question of how to live in one',
    'particular climate.</p>',
    '<p><b>Architecture without architects</b></p>',
    '<p>The phrase belongs to Bernard Rudofsky, who in 1964 mounted an exhibition',
    'at the Museum of Modern Art in New York and a small book to go with it, both',
    'called <i>Architecture Without Architects</i>. He filled the walls with',
    'photographs of anonymous building from all over the world, the cliff',
    'dwellings, the whitewashed hill towns, the granaries and the arcades, and',
    'argued that this &ldquo;non-pedigreed&rdquo; architecture had more to teach',
    'than most of what the profession was putting up. It changed how a generation',
    'looked.</p>',
    '',
    '<p><b>The wisdom in it</b></p>',
    '<p>What the anonymous builders knew, without a word of physics, was how to',
    'stay comfortable for free. A short list of the tricks that come up again and',
    'again, from very different places:</p>',
    '<pre>',
    ' MOVE           WHAT IT DOES                 SEEN IN',
    ' -------------  ---------------------------  -----------------',
    ' courtyard      cool air pool, private sky   Rome to Beijing',
    ' thick wall     lag the day&rsquo;s heat        adobe, stone, cob',
    ' wind-catch     scoop the breeze down         Egypt, Iran, Sind',
    ' deep verandah  shade the wall, sit outside   the wet tropics',
    ' high ceiling   let the hot air rise off you  the hot dry lands',
    ' small windows  keep the sun out              the desert house',
    ' steep roof     shed the snow or the rain     the mountain, the north',
    ' -------------  ---------------------------  -----------------</pre>',
    '<p><b>The lesson the moderns relearned</b></p>',
    '<p>The first modern movement threw much of this away. The same flat-roofed',
    'glass box went up in Helsinki and in Baghdad, and in the hot places it cooked,',
    'and the answer offered was to bolt on air-conditioning and burn power to fix',
    'what the design had broken. The best of the later architects went back to',
    'school with the anonymous builders. Hassan Fathy at',
    '<a href="hassan-fathy.geocities.ws">hassan-fathy</a> rebuilt the mud-brick',
    'vault and the wind-catch for the villages of Egypt. Luis Barrag&aacute;n at',
    '<a href="luis-barragan.geocities.ws">luis-barragan</a> took the walled patio',
    'and the still water of the hacienda into modern rooms. Geoffrey Bawa did it',
    'for the tropics and Balkrishna Doshi for the Indian city, though their pages',
    'sit elsewhere on the ring.</p>',
    '<hr>',
    '<p><small>visitors: 00629 · best viewed at 800x600 · a proud member of the',
    'buildings webring · under construction, more courtyards to come · last updated',
    '11 Feb</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
  ]);

export const ARCH_E = [BAWA, FATHY, DOSHI, ANDO, BARRAGAN, VERNACULAR];
