// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH POL_B — nineteenth-century statecraft.
//
// Cached pages a history student, a party enthusiast and a couple of amateur
// societies made about the statecraft of the long nineteenth century: an
// academic-style summary of Bismarck, reading notes on a Metternich biography,
// a short scholarly page on Talleyrand, a Gladstone fan shrine, a write-up of a
// Disraeli speech, and an event page for the Congress of Vienna. The dates,
// offices and quotations are real; the framing and the enthusiasms are the
// pages' makers'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Bismarck: the academic summary (SHOWPIECE) -----------------------------

const BISMARCK = P('otto-von-bismarck.geocities.ws', 'BISMARCK',
  'Otto von Bismarck // the Iron Chancellor', [
    '<!--bg:pol-statecraft-->',
    '<h1>Otto von Bismarck (1815&ndash;1898)</h1>',
    '<p class="fs-epi"><i>&ldquo;Politics is the art of the possible.&rdquo;</i></p>',
    '<p><small>A summary page prepared for a first-year survey in modern European',
    'history. Reading notes, dates and a short bibliography below. Corrections',
    'welcome by email to the seminar list.</small></p>',
    '<hr>',
    '<p>Otto von Bismarck was the Prussian statesman who unified Germany under',
    'Prussian leadership and served as the first Chancellor of the German Empire',
    'from 1871 to 1890. A Junker landowner by birth and temperament, he entered',
    'Prussian politics as a hard conservative and was appointed Minister President',
    'of Prussia by King Wilhelm I in 1862, during a constitutional crisis over the',
    'army budget. He governed for years without a legally approved budget, a fact',
    'worth keeping in view: the unifier of Germany began by overriding his own',
    'parliament.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/bismarck-01.jpg" alt=""><span class="indie-cap">Otto von Bismarck (public domain)</span>',
    '<p class="fs-quote"><blockquote>&ldquo;The great questions of the day will not',
    'be settled by speeches and majority decisions &mdash; that was the great',
    'mistake of 1848 and 1849 &mdash; but by iron and blood.&rdquo;<br>',
    '<span>&mdash; Bismarck to the Prussian budget committee, 30 September 1862</span>',
    '</blockquote></p>',
    '<p>The phrase is usually remembered as &ldquo;blood and iron&rdquo;, and it',
    'names his method. <b>Realpolitik</b>: politics conducted from a cold reading',
    'of interest and power rather than from principle or sentiment. Bismarck did',
    'not unify Germany out of nationalist feeling, which he distrusted, but because',
    'a Prussian-led Germany served Prussian power. He was willing to borrow',
    'liberal and nationalist causes when they were useful and to drop them when',
    'they were not.</p>',
    '<hr>',
    '<p><b>The three wars of unification</b></p>',
    '<p>Bismarck built the Empire through three short, deliberate wars, each ending',
    'before it could widen into a general European conflict.</p>',
    '<pre>',
    '  1864   War against Denmark (with Austria) over Schleswig and Holstein.',
    '  1866   The Austro-Prussian War. Seven weeks; Prussia defeats Austria at',
    '         Koeniggraetz and excludes Austria from German affairs.',
    '  1867   The North German Confederation, under Prussian leadership.',
    '  1870   The Ems Dispatch, edited by Bismarck to provoke France.',
    '  1870-71 The Franco-Prussian War. France defeated; Napoleon III captured',
    '         at Sedan.',
    '  1871   The German Empire proclaimed in the Hall of Mirrors at Versailles.',
    '         Wilhelm I is Emperor; Bismarck is Chancellor.',
    '</pre>',
    '<p>The choice of Versailles for the proclamation, on French soil after a',
    'French defeat, and the annexation of Alsace-Lorraine that followed, left a',
    'grievance that shaped the next fifty years of European politics.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/metternich-01.jpg" alt=""><span class="indie-cap">Klemens von Metternich, by Thomas Lawrence (public domain)</span>',
    '<p><b>The alliance system</b></p>',
    '<p>Having made the Empire by war, Bismarck spent his years as Chancellor',
    'trying to keep the peace that preserved it, chiefly by keeping France isolated',
    'and by managing the rivalry between Austria-Hungary and Russia in the Balkans.',
    'The instruments were a web of treaties: the Three Emperors&rsquo; League, the',
    'Dual Alliance with Austria-Hungary in 1879, the Triple Alliance of 1882, and',
    'the secret Reinsurance Treaty with Russia in 1887. He presided over the',
    'Congress of Berlin in 1878 as, in his own phrase, an &ldquo;honest',
    'broker&rdquo;. The system was intricate and depended on one man holding all',
    'its threads at once.</p>',
    '<p class="fs-pull">He built the welfare state not out of sympathy for the',
    'workers but to draw them away from the socialists.</p>',
    '<p><b>Kulturkampf and the welfare state</b></p>',
    '<p>At home Bismarck fought two long internal campaigns. The <i>Kulturkampf</i>',
    'of the 1870s was a struggle against the political influence of the Catholic',
    'Church, which largely failed and was quietly wound down. Against the growing',
    'Social Democrats he combined repression with concession: the Anti-Socialist',
    'Laws of 1878 banned the party&rsquo;s organisation, while in the 1880s he',
    'introduced health insurance, accident insurance and old-age pensions, the',
    'first modern social insurance system in the world. The aim was candidly',
    'stated. He hoped a worker with a pension to lose would be a worker less drawn',
    'to revolution.</p>',
    '<hr>',
    '<p><b>The fall</b></p>',
    '<p>The old Emperor died in 1888. After a brief reign by Friedrich III, the',
    'throne passed to the young and headstrong Wilhelm II, who wanted to rule as',
    'well as reign and had no intention of being managed. In 1890 he forced',
    'Bismarck&rsquo;s resignation. The Reinsurance Treaty with Russia was allowed',
    'to lapse soon after, and Russia drifted toward France, the very outcome',
    'Bismarck had spent twenty years preventing. He retired to his estate and',
    'died in 1898, writing memoirs that settled scores.</p>',
    '<p>Bismarck is not a comfortable figure. He was an authoritarian who despised',
    'parliaments, provoked wars for calculated ends, and persecuted Catholics and',
    'socialists. He was also, by common agreement, the most skilful practitioner',
    'of statecraft of his century, and the diplomatic order he built kept the great',
    'powers from general war while he held office. Both things are true and a fair',
    'account has to carry them together.</p>',
    '<p class="fs-aside"><b>Compare and contrast (for the essay):</b> Bismarck the',
    'conservative revolutionary against the older conservatism of',
    '<a href="klemens-von-metternich.geocities.ws">Metternich</a>, who tried to',
    'freeze Europe against change; and the domestic reformer against his liberal',
    'contemporary <a href="william-gladstone.geocities.ws">Gladstone</a> in Britain,',
    'who arrived at social reform from the opposite direction.</p>',
    '<hr>',
    '<p><small>SELECT BIBLIOGRAPHY (as handed out; check editions yourselves):<br>',
    'Taylor, A. J. P. <i>Bismarck: The Man and the Statesman</i>. 1955.<br>',
    'Pflanze, Otto. <i>Bismarck and the Development of Germany</i>. Princeton.<br>',
    'Gall, Lothar. <i>Bismarck: The White Revolutionary</i>. 2 vols.<br>',
    'Bismarck&rsquo;s own <i>Gedanken und Erinnerungen</i> (Reflections and',
    'Reminiscences) &mdash; useful but self-serving, read with care.</small></p>',
    '<p><small>hit counter: 03571 &middot; best viewed at 800x600 &middot; this page',
    'is UNDER CONSTRUCTION (footnotes still to add) &middot; last updated 14 Oct</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Metternich: reading notes on a biography (2 images) --------------------

const METTERNICH = P('klemens-von-metternich.geocities.ws', 'METTERNICH',
  'Reading notes: a life of Metternich', [
    '<!--bg:pol-statecraft-->',
    '<h1>Reading notes: Metternich</h1>',
    '<p><small>Notes I made working through a biography of Klemens von Metternich',
    '(1773&ndash;1859) over the vac. Page references are to the paperback I had;',
    'yours may differ. Kept here so I do not lose the notebook again. &mdash; R.H.</small></p>',
    '<hr>',
    '<p>Metternich was the Austrian foreign minister from 1809 and State',
    'Chancellor from 1821 until 1848. For the better part of forty years he was the',
    'presiding figure of European diplomacy, so much so that historians call the',
    'period the Age of Metternich. He was Rhineland-born, married into the',
    'Austrian nobility, and rose through the diplomatic service at the moment',
    'Napoleon was remaking the continent.</p>',
    '<p><b>Ch. 1&ndash;3, the making of a conservative.</b> The key to him is that',
    'he lived through the French Revolution as a young man and drew from it a',
    'single lifelong lesson: revolution is chaos, and the first duty of a statesman',
    'is order. He was not a reactionary romantic. He was a rationalist of order,',
    'cool, vain, endlessly patient, who thought societies were fragile machines',
    'that revolution wrecked.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/metternich-01.jpg" alt=""><span class="indie-cap">Klemens von Metternich, by Thomas Lawrence (public domain)</span>',
    '<p class="fs-quote"><blockquote>&ldquo;When France sneezes, Europe catches',
    'cold.&rdquo;<br><span>&mdash; attributed to Metternich</span></blockquote></p>',
    '<p><b>Ch. 4&ndash;6, Vienna and the balance of power.</b> His monument is the',
    '<a href="the-congress-of-vienna.geocities.ws">Congress of Vienna</a> of',
    '1814&ndash;15, which he hosted and largely steered. The principle was the',
    'balance of power: arrange the great states so that none can dominate and each',
    'checks the others, and you buy peace. Out of it came the <b>Concert of',
    'Europe</b>, a habit of the great powers meeting to manage crises together',
    'rather than settling them only by war. Whatever else one thinks of him, no',
    'general war engulfed Europe between 1815 and 1914, and the Concert was part of',
    'the reason.</p>',
    '<p class="fs-pull">His system rested on treating the desire for national and',
    'liberal freedom as a disease to be contained.</p>',
    '<p><b>Ch. 7&ndash;9, the machinery of repression.</b> This is the darker half',
    'and the notes should say so plainly. To hold the settlement in place Metternich',
    'built a system of censorship, secret police and surveillance across Austria and',
    'the German states. The Carlsbad Decrees of 1819 muzzled the universities and',
    'the press. Nationalist and liberal movements, in the German lands, in Italy, in',
    'the empire&rsquo;s many peoples, were monitored, banned and broken up. The',
    'stability he prized was paid for by keeping the lid clamped down hard.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/congress-vienna-01.jpg" alt=""><span class="indie-cap">The Congress of Vienna, after Isabey (CC BY-SA 3.0)</span>',
    '<p><b>Ch. 10, the year it broke.</b> In 1848 revolution swept the European',
    'capitals and reached Vienna itself. The crowds turned on the old Chancellor as',
    'the symbol of the whole system, and in March 1848 Metternich resigned and fled,',
    'in the end to England. The order he had defended for a generation cracked',
    'open in a matter of weeks. It was patched back together in part afterwards, but',
    'the Age of Metternich was over, and he lived his last decade as a spectator.</p>',
    '<hr>',
    '<p><b>What I took from it.</b> Metternich is the great conservative statesman',
    'of the century, the mirror image of the men who came after. Where',
    '<a href="otto-von-bismarck.geocities.ws">Bismarck</a> would harness',
    'nationalism to build a new state, Metternich spent his career trying to hold',
    'nationalism down to preserve an old empire of many peoples. He kept the peace',
    'and he stopped the clock, and eventually the clock started again without him.</p>',
    '<p><small>notebook page &middot; counter: 01204 &middot; best viewed at 800x600',
    '&middot; last updated 2 Sep</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Talleyrand: a short academic page --------------------------------------

const TALLEYRAND = P('talleyrand.geocities.ws', 'TALLEYRAND',
  'Talleyrand // the survivor', [
    '<!--bg:pol-statecraft-->',
    '<h1>Charles-Maurice de Talleyrand (1754&ndash;1838)</h1>',
    '<p><small>A short scholarly note. Talleyrand is a byword for diplomatic',
    'cunning and for political survival, and the two are the same story.</small></p>',
    '<hr>',
    '<p>Charles-Maurice de Talleyrand-Perigord served, in turn, the monarchy of the',
    'old regime, the Revolution, the Directory, Napoleon, the restored Bourbons and',
    'the July Monarchy. He held high office under governments that spent much of',
    'their energy destroying one another, and he outlasted almost all of them. To',
    'his enemies this made him the model of the man without principle; to his',
    'admirers it made him the servant not of any regime but of France itself.</p>',
    '<p>Born to an aristocratic family and lamed in childhood, he was steered into',
    'the Church against his inclination and rose to become Bishop of Autun. In the',
    'Revolution he abandoned the clerical career, supported the seizure of Church',
    'lands, and was excommunicated. He had found his real vocation, which was',
    'diplomacy.</p>',
    '<p class="fs-aside"><b>The turned coat, or the constant aim?</b> Talleyrand',
    'insisted he had never betrayed a government that had not already, in his view,',
    'abandoned France&rsquo;s interests first. It is the defence of every survivor,',
    'and readers have argued about it for two centuries. The record allows both',
    'readings and does not settle between them.</p>',
    '<p>As Napoleon&rsquo;s foreign minister he helped negotiate the settlements',
    'that followed French victories, then turned against the Emperor as he judged',
    'the wars were leading France to ruin, intriguing with foreign powers while',
    'still in office. When Napoleon fell, Talleyrand was ready.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/talleyrand-01.jpg" alt=""><span class="indie-cap">Talleyrand, by Francois Gerard (public domain)</span>',
    '<p>His masterpiece was the <a href="the-congress-of-vienna.geocities.ws">',
    'Congress of Vienna</a> of 1814&ndash;15. France was the defeated aggressor and',
    'should have sat at the edge of the room. Talleyrand, representing the restored',
    'Bourbons, used the principle of <i>legitimacy</i> and the divisions among the',
    'victors to work France back to the centre of the negotiations, so that the',
    'defeated power helped shape the peace. It is remembered as one of the great',
    'feats of diplomacy performed from a position of weakness.</p>',
    '<p class="fs-quote"><blockquote>&ldquo;They have learned nothing and forgotten',
    'nothing.&rdquo;<br><span>&mdash; a remark on the returning Bourbons, commonly',
    'attributed to Talleyrand</span></blockquote></p>',
    '<p>The wit is real and much of it is probably genuine, though like all famous',
    'talkers he has been credited with lines he never spoke. What is not in doubt is',
    'the skill. In the same generation of statecraft he is the necessary companion',
    'to <a href="klemens-von-metternich.geocities.ws">Metternich</a>, his opposite',
    'number at Vienna, and his gift for reading power without illusion looks forward',
    'to the later realists. Among nineteenth-century figures the wit and the',
    'calculation are matched later in Britain by',
    '<a href="benjamin-disraeli.geocities.ws">Disraeli</a>, though Disraeli served',
    'one crown and Talleyrand served six.</p>',
    '<hr>',
    '<p><small>References: Duff Cooper, <i>Talleyrand</i> (1932); Lawday, <i>Napoleon&rsquo;s',
    'Master</i>. Page maintained for a reading group on the diplomacy of the',
    'Napoleonic settlement.</small></p>',
    '<p><small>counter: 00688 &middot; best viewed at 800x600 &middot; last updated',
    '19 Aug</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Gladstone: the personal fan shrine -------------------------------------

const GLADSTONE = P('william-gladstone.geocities.ws', 'GLADSTONE',
  'THE GRAND OLD MAN // a Gladstone shrine', [
    '<!--bg:pol-statecraft-->',
    '<h1>THE GRAND OLD MAN</h1>',
    '<p><small>a page for William Ewart Gladstone (1809&ndash;1898), kept by a',
    'Liberal to the bone who thinks the G.O.M. was the greatest of all the prime',
    'ministers and is happy to argue about it. rosette below. &mdash; a member of',
    'the local Liberal club</small></p>',
    '<pre>',
    '        (@)   VOTE   (@)',
    '       ~~~~ GLADSTONE ~~~~',
    '</pre>',
    '<hr>',
    '<p>Four times Prime Minister. Nobody else has managed that. William Gladstone',
    'led Liberal governments in 1868&ndash;74, 1880&ndash;85, 1886, and',
    '1892&ndash;94, and he was still forming a ministry in his eighties. They',
    'called him the Grand Old Man, the G.O.M., and his enemies said it stood for',
    'God&rsquo;s Only Mistake, which only proves he mattered enough to be hated',
    'properly.</p>',
    '<p>He began life a High Tory, the young man Macaulay called the rising hope of',
    'the stern unbending Tories, and he crossed the floor over the course of a',
    'career to become the great tribune of Victorian Liberalism. As Chancellor of',
    'the Exchequer he made the Budget a moral instrument, cutting duties, trusting',
    'free trade, and preaching thrift in the public finances as if it were a',
    'sermon, which for him it half was.</p>',
    '<p class="fs-pull">He would take his axe into the woods at Hawarden and fell',
    'trees for relaxation. Even his hobbies were strenuous.</p>',
    '<p><b>THE MIDLOTHIAN CAMPAIGN</b></p>',
    '<p>This is the bit I love. In 1879 Gladstone went up to the Scottish',
    'constituency of Midlothian and campaigned by railway, speaking to enormous',
    'crowds at every station, denouncing the foreign policy of',
    '<a href="benjamin-disraeli.geocities.ws">Disraeli</a>&rsquo;s government and',
    'the cruelties it tolerated abroad. It is often called the first modern',
    'political campaign, taking the argument straight to the mass of voters instead',
    'of leaving it in the House. It worked. The Liberals won and Gladstone was back',
    'in Downing Street in 1880.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/gladstone-01.jpg" alt=""><span class="indie-cap">William Gladstone (public domain)</span>',
    '<p><b>IRELAND, and why he lost</b></p>',
    '<p>The cause that consumed his last years, and I will not pretend it did not',
    'cost him, was Home Rule for Ireland: self-government for Ireland within the',
    'Union. He came to believe it was simple justice. It split his own party. The',
    'first Home Rule Bill was defeated in the Commons in 1886 when the Liberal',
    'Unionists broke away, and the second passed the Commons in 1893 only to be',
    'thrown out by the House of Lords. He did not live to see it, and neither, in',
    'the form he wanted, did anyone. He thought it the great unfinished business',
    'and he was right to.</p>',
    '<p class="fs-quote"><blockquote>&ldquo;My mission is to pacify Ireland.&rdquo;<br>',
    '<span>&mdash; Gladstone, on forming his first government, 1868</span></blockquote></p>',
    '<p><b>THE RIVALRY</b></p>',
    '<p>You cannot talk about Gladstone without Disraeli. They loathed each other,',
    'the earnest moralist and the glittering cynic, and between them they made the',
    'two-party politics of the age. Gladstone was the conscience, the account',
    'books, the felled trees and the enormous speeches. Read his rival&rsquo;s page',
    'and then come back and tell me who was the better man. I already know.</p>',
    '<p>And for the other kind of statesman entirely, look at',
    '<a href="otto-von-bismarck.geocities.ws">Bismarck</a> in Germany, doing by',
    'iron and calculation what Gladstone tried to do by argument and conscience.',
    'Gladstone thought Bismarck&rsquo;s methods a moral catastrophe. I think he had',
    'a point.</p>',
    '<hr>',
    '<p><small>counter: 02106 &middot; best viewed at 800x600 &middot; a proud',
    'Gladstonian since before it was unfashionable &middot; last updated 5 Nov',
    '&middot; UNDER CONSTRUCTION: a page on the Bulgarian agitation to come</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Disraeli: the speech write-up ------------------------------------------

const DISRAELI = P('benjamin-disraeli.geocities.ws', 'DISRAELI',
  'Disraeli at the Crystal Palace // a speech write-up', [
    '<!--bg:pol-statecraft-->',
    '<h1>Disraeli at the Crystal Palace, 1872</h1>',
    '<p><small>A write-up of one famous speech, with notes on the man who gave it.',
    'Benjamin Disraeli, Earl of Beaconsfield (1804&ndash;1881), novelist and twice',
    'Conservative Prime Minister. Prepared for a talk to the debating society.</small></p>',
    '<hr>',
    '<p>On 24 June 1872, at the Crystal Palace in Sydenham, the leader of the',
    'Conservative opposition rose to give a speech that set out what his party was',
    'for. He named three great objects: to maintain the institutions of the',
    'country, to uphold the Empire, and to elevate the condition of the people. In',
    'a few sentences Disraeli had drawn the map his party would follow for the next',
    'half century.</p>',
    '<p class="fs-quote"><blockquote>&ldquo;The palace is not safe when the cottage',
    'is not happy.&rdquo;<br><span>&mdash; Disraeli, on the condition of the',
    'people</span></blockquote></p>',
    '<p><b>Who was speaking.</b> Disraeli was unlike anyone else at the top of',
    'Victorian politics. He was a novelist first, the author of <i>Coningsby</i>',
    'and <i>Sybil</i>, the latter subtitled <i>The Two Nations</i>, the rich and',
    'the poor who lived as if on different planets. He was of Jewish descent, in a',
    'parliament and a party not built to welcome him, and he arrived at the',
    'leadership by sheer wit, nerve and persistence, having been laughed at in his',
    'maiden speech and promising the House that the time would come when they would',
    'hear him. It did.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/disraeli-01.jpg" alt=""><span class="indie-cap">Benjamin Disraeli (public domain)</span>',
    '<p><b>The Reform Act of 1867.</b> The paradox of his career is that the',
    'Conservative extended the vote further than the Liberals had dared. The Second',
    'Reform Act of 1867, which Disraeli steered through as Chancellor of the',
    'Exchequer under Lord Derby, roughly doubled the electorate and gave the vote',
    'to many urban working men. His critics called it a leap in the dark and',
    'accused him of dishing the Whigs, taking their own cause out of their hands',
    'for party advantage. He believed, or said he believed, that the working man',
    'was a natural Conservative if only the party would trust him.</p>',
    '<p class="fs-aside"><b>One-nation Toryism.</b> Out of the <i>Sybil</i> theme',
    'and the Crystal Palace speech comes the tradition later called one-nation',
    'Conservatism: the claim that the party of order should also be the party of',
    'social reform, binding the two nations into one so that the whole is not torn',
    'apart. His second ministry passed real measures on public health, housing and',
    'the legal rights of trade unions to back the words with law.</p>',
    '<p><b>The Empire and the Queen.</b> Disraeli made the Empire a Conservative',
    'cause and made himself the favourite minister of Queen Victoria, who had',
    'little warmth for his rival. In 1875 he bought Britain a controlling interest',
    'in the Suez Canal, and in 1876 he had Parliament proclaim Victoria Empress of',
    'India, a title she delighted in. At the Congress of Berlin in 1878 he returned',
    'claiming &ldquo;peace with honour&rdquo;. The imperial turn had its costs, in',
    'the wars in Afghanistan and Zululand that shadowed his last ministry, and his',
    'Liberal opponent hammered him for them.</p>',
    '<p><b>The rivalry.</b> That opponent was',
    '<a href="william-gladstone.geocities.ws">Gladstone</a>, and the antagonism',
    'between the two defined the era. Disraeli had the wit, the novels, the',
    'flattery of the Queen and the flair for the grand gesture; his rival had the',
    'conscience and the account books. For an earlier master of the same arts of',
    'charm and calculation in politics, the comparison often drawn is with',
    '<a href="talleyrand.geocities.ws">Talleyrand</a> in France, though Disraeli',
    'kept his faith with one party where Talleyrand kept faith with none.</p>',
    '<hr>',
    '<p><small>hit counter: 01490 &middot; best viewed at 800x600 &middot; speech',
    'text checked against Hansard where possible &middot; last updated 21 Sep</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- The Congress of Vienna: the ORG / event page ---------------------------

const CONGRESS_VIENNA = P('the-congress-of-vienna.geocities.ws', 'VIENNA 1815',
  'The Congress of Vienna 1814&ndash;15 // an event page', [
    '<!--bg:pol-statecraft-->',
    '<h1>The Congress of Vienna, 1814&ndash;1815</h1>',
    '<p><small>An event page: what the Congress was, who was there, what it settled,',
    'and why it is argued about. Maintained as part of a diplomacy-history web',
    'project. Sources at the foot.</small></p>',
    '<hr>',
    '<p>The Congress of Vienna was the conference of European powers, held in the',
    'Austrian capital from September 1814 to June 1815, that redrew the map of',
    'Europe after the defeat of Napoleon. It was the largest gathering of its kind',
    'the continent had seen, and the settlement it produced held, in its main',
    'lines, for the better part of a century.</p>',
    '<p><b>Who ran it.</b> Four great victorious powers dominated the proceedings,',
    'with a fifth soon working its way in.</p>',
    '<pre>',
    '  AUSTRIA   Prince Metternich, the host, chairing and steering.',
    '  BRITAIN   Lord Castlereagh, then the Duke of Wellington.',
    '  RUSSIA    Tsar Alexander I, in person and unpredictable.',
    '  PRUSSIA   Prince Hardenberg.',
    '  FRANCE    Talleyrand, the defeated power, talking his way back in.',
    '</pre>',
    '<p>The presiding figure was',
    '<a href="klemens-von-metternich.geocities.ws">Metternich</a>, whose page',
    'covers his conservative system at greater length. The most admired manoeuvre',
    'was that of <a href="talleyrand.geocities.ws">Talleyrand</a>, who represented',
    'defeated France and, by invoking the principle of legitimacy and exploiting the',
    'quarrels among the victors, brought France back from the dock to the top',
    'table.</p>',
    '<p class="fs-aside"><b>&ldquo;The Congress dances but does not advance.&rdquo;</b>',
    'The remark, ascribed to the Prince de Ligne, caught the endless round of balls,',
    'banquets and entertainments that ran alongside the negotiations. It is why the',
    'gathering is sometimes remembered as the dancing congress. The serious business',
    'went on behind the dancing, much of it in private among the four, later five.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/congress-vienna-01.jpg" alt=""><span class="indie-cap">The Congress of Vienna, after Isabey (CC BY-SA 3.0)</span>',
    '<p><b>What it settled.</b> The guiding aims were a balance of power so that no',
    'single state could dominate as France had, and, where possible, the',
    'restoration of legitimate ruling houses. In outline:</p>',
    '<pre>',
    '  * A ring of strengthened states around France to contain her: an enlarged',
    '    Kingdom of the Netherlands, a strong Prussia on the Rhine, Piedmont-Sardinia.',
    '  * Restoration of the Bourbons in France and of old ruling houses elsewhere.',
    '  * A German Confederation of 39 states replacing the old Holy Roman Empire,',
    '    with Austria presiding.',
    '  * Russia gaining most of Poland; Prussia gaining much of Saxony and the',
    '    Rhineland; Austria compensated in northern Italy.',
    '  * Britain keeping key naval and colonial gains and a formal condemnation of',
    '    the slave trade written into the final act.',
    '</pre>',
    '<p><b>The verdict, both ways.</b> For a long time the Congress was blamed as a',
    'reactionary bargain, a conspiracy of monarchs and ministers to hold down the',
    'national and liberal aspirations that the French Revolution had awoken, and it',
    'was that: the settlement moved peoples between crowns without asking them, and',
    'it set the frame for the repression of the following decades. It was also,',
    'measured differently, a remarkable success at its own stated task. No general',
    'war engulfed the great powers of Europe between 1815 and 1914, and the habit of',
    'the powers conferring together, the Concert of Europe, began here. The two',
    'judgements are not really rivals. The order kept the peace of the powers and',
    'it did so by sitting on the peoples, and an honest event page has to record',
    'both sides of the account.</p>',
    '<p>The work was nearly complete when Napoleon returned from Elba in March 1815,',
    'the Hundred Days that ended at Waterloo that June. The Final Act was signed on',
    '9 June 1815, days before the battle. The century of relative great-power peace',
    'that historians associate with the settlement began in earnest afterwards.</p>',
    '<hr>',
    '<p><small>Sources: Kissinger, <i>A World Restored</i> (1957); Zamoyski,',
    '<i>Rites of Peace</i>; Nicolson, <i>The Congress of Vienna</i>. Part of a',
    'diplomacy-history web project; corrections to the project list.</small></p>',
    '<p><small>visitors: 00933 &middot; best viewed at 800x600 &middot; page last',
    'tended 30 Oct &middot; more maps to come, UNDER CONSTRUCTION</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

export const POL_B = [BISMARCK, METTERNICH, TALLEYRAND, GLADSTONE, DISRAELI, CONGRESS_VIENNA];
