// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// CACHED WEB, INDIE BATCH F: the bridge out of the guitars.
//
// Four pages from the same collector's site, the stretch where the indie
// shelf stops being a guitar shelf. Stereolab bolt a Moog and a motorik pulse
// to the indie band; Spiritualized issue a record as a course of medication;
// Bristol slows the beat down over a sampler; and a rock band in a church
// decides it no longer wants to rock and the word "post-rock" gets coined to
// name it. The keeper writes ABOUT the bands, never in their voice, and points
// at the electronic end of the collection every chance he gets. Labels and
// years are real; catalogue detail is what he can vouch for. Dated by day and
// month, never year.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Stereolab --------------------------------------------------------------

const STEREOLAB = P('stereolab.geocities.ws', 'STEREOLAB',
  'Stereolab: krautrock, lounge and a Marxist Moog', [
    '<!--bg:indie-->',
    '<img class="indie-pic" src="assets/media/web/indie/moog-01.jpg" alt=""><span class="indie-cap">a modular synth</span>',
    '<p><small>a page about Stereolab, kept by the same collector who keeps the',
    'rest of this shelf. this is where the guitars start letting the machines in.',
    'last updated 14 Feb. best viewed at 640x480.</small></p>',
    '<h1>KRAUTROCK, LOUNGE, AND A MARXIST MOOG</h1>',
    '<p><small>You are visitor 000714. the counter has been stuck on a Farfisa',
    'chord since Tuesday.</small></p>',
    '<hr>',
    '<h2>The band that plugged indie into the mains</h2>',
    '<p>I file Stereolab at the exact point on my shelf where the indie years',
    'stop being about a bloke and a distortion pedal. Tim Gane came out of',
    'McCarthy, a proper jangly left-wing indie band, and instead of writing more',
    'jangle he went and bolted a vintage organ, a Moog and a drum pattern that',
    'never resolves onto the front of it. Laetitia Sadier sings over the top in',
    'French and English, flat and lovely, like a newsreader who has read Marx.',
    'They put it out themselves on Duophonic, the D-UHF catalogue, seven-inches',
    'and albums both, so the means of production were theirs too, which they',
    'would want you to notice.</p>',
    '<h2>The records I reach for</h2>',
    '<p>Transient Random-Noise Bursts with Announcements (1993) is the one that',
    'first told me a guitar band could drone for eighteen minutes and mean it;',
    'Mars Audiac Quintet (1994) has "Ping Pong", a bright pop tune whose words',
    'are a lecture on the boom-and-bust of capital, sung like an advert. Then the',
    'two that matter most to this shelf: Emperor Tomato Ketchup (1996) and Dots',
    'and Loops (1997), both on Duophonic through Elektra. Dots and Loops was cut',
    'partly with Tortoise and the German producer Jan St. Werner, and you can',
    'hear the guitars quietly handing the record over to programming.</p>',
    '<h2>Motorik: the second instrument</h2>',
    '<p>The thing I go on about to anyone who will sit still: the real player in',
    'this band is the beat itself. That flat, forward, unhurried pulse is the',
    'motorik, the one Neu! and Can and Kraftwerk built, a rhythm that does not',
    'swing and does not stop, it just travels. Once you hear the loop as an',
    'instrument rather than a backing, half of what happens after on this shelf',
    'makes sense. So it is no accident I keep the <a href="kraftwerk.geocities.ws">Kraftwerk',
    'page</a> open in the next window; Stereolab are the indie kids reading the',
    'German manual and doing the exercises.</p>',
    '<h2>A groove, or an argument?</h2>',
    '<p>Here is my pet question. When they repeat a bar forty times, is that a',
    'groove to nod to or a point being made? I think both, and I think that is the',
    'joke. Repetition in a pop song is pleasure; repetition on a production line',
    'is the thing the sleeve-notes are complaining about. They give you the',
    'pleasure and the critique in the same loop and let you sort it out. It is the',
    'first door on this shelf that opens onto the electronic room, and the label',
    'they helped make possible for a certain kind of head is at the end of the',
    'corridor: see the <a href="warp-records.geocities.ws">Warp Records page</a>,',
    'where listening music gets made to sit down to.</p>',
    '<p><small>Why they matter now, with the shops shut: they are the proof that a',
    'guitar band could think its way toward the machine without losing its nerve.',
    'The loop was there to be used, and they used it. Kept here since the',
    'McCarthy days.</small></p>',
    '<hr>',
    '<p><small>under construction (the discography table keeps eating the Farfisa',
    'symbol). sign the guestbook, it is nearly full.</small></p>',
    '<hr>',
    '<p><small>',
    '[ <a href="electronic-tape-ring.geocities.ws">Electronic &amp; Tape Music</a> ]',
    '[ <a href="studio-as-instrument-ring.geocities.ws">The Studio as Instrument</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    '[ prev | post-rock ring | next ]',
    '</small></p>',
  ]);

// ---- Spiritualized ----------------------------------------------------------

const SPIRITUALIZED = P('spiritualized.geocities.ws', 'SPIRITUALIZED',
  'Spiritualized: Ladies and Gentlemen We Are Floating in Space', [
    '<!--bg:indie-->',
    '<img class="indie-pic" src="assets/media/web/indie/console-01.jpg" alt=""><span class="indie-cap">a mixing desk</span>',
    '<p><small>a page for the 1997 record on Dedicated, kept by someone who owns',
    'the blister-pack copy and refuses to open the foil. last updated 9 Feb. best',
    'viewed at 640x480.</small></p>',
    '<h1>LADIES AND GENTLEMEN WE ARE FLOATING IN SPACE</h1>',
    '<p><small>You are visitor 000531. take one on rising, one at night.</small></p>',
    '<hr>',
    '<h2>The medium is the message, printed on the box</h2>',
    '<p>You have to start with the object, because the band did. When Dedicated',
    'issued Ladies and Gentlemen We Are Floating in Space in 1997, the CD came',
    'boxed as a pharmaceutical, a foil blister pack, the disc pressed like a pill',
    'and the liner written as a dosage. I have never seen a record put its whole',
    'argument on the packaging so plainly. The music is about love as an illness',
    'you are being treated for, so the sleeve makes you the patient before a note',
    'plays. That is not a gimmick to me. It is the record telling you how to',
    'take it.</p>',
    '<h2>Where it comes from</h2>',
    '<p>Jason Pierce, who signs himself J. Spaceman, came out of Spacemen 3, the',
    'Rugby band he ran with Sonic Boom until they stopped speaking. Spacemen 3',
    'were two chords and a lot of drone; Spiritualized kept the drone and added',
    'everything. On this album that means the London Community Gospel Choir, a',
    'string section, brass, and Pierce, small and deadpan in the middle of it, as',
    'if a garage band had been handed a cathedral. Lazer Guided Melodies (1992)',
    'and Pure Phase (1995) got him here; this is the one where the door opens all',
    'the way.</p>',
    '<h2>The drone, held over from the guitars</h2>',
    '<p>What ties it to my shoegaze shelf is the drone. Where Kevin Shields bent a',
    'chord until it would not sit still, Pierce holds a chord until it turns into',
    'a room you are standing in. If you have the <a href="my-bloody-valentine-loveless.geocities.ws">Loveless',
    'page</a> open you already know the trick; this is the gospel-and-strings',
    'version of it, the same refusal to let a note simply end. The title track',
    'floats on a single held figure for the length of a hymn, and "Broken Heart"',
    'just sits in its grief with the strings and lets you sit there too.</p>',
    '<h2>Does the packaging complete the record, or comment on it?</h2>',
    '<p>My question, and I go back and forth. Some days the blister pack feels like',
    'the last piece, the record only finished once you are holding it as a course',
    'of treatment. Other days it feels like a wink, the band standing outside the',
    'sad songs pointing at them. I have decided I do not need to settle it. A pop',
    'record that makes you argue with its box is doing more than most, and it',
    'belongs on this shelf because it is one more step off the guitar and toward',
    'sound as pure atmosphere, which is the direction the whole collection is',
    'walking.</p>',
    '<p><small>Why it matters now: it is the record I put on when I want to be',
    'reminded that a sleeve is part of the music, not a wrapper for it. Keep the',
    'foil sealed; buy a second one to play. Kept in the medicine cabinet.</small></p>',
    '<hr>',
    '<p><small>this page is under construction and probably always will be. the',
    'guestbook is full again, drop me a line instead.</small></p>',
    '<hr>',
    '<p><small>',
    '[ <a href="studio-as-instrument-ring.geocities.ws">The Studio as Instrument</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    '[ prev | post-rock ring | next ]',
    '</small></p>',
  ]);

// ---- Massive Attack & Portishead --------------------------------------------

const MASSIVE_ATTACK_PORTISHEAD = P('massive-attack-portishead.geocities.ws',
  'MASSIVE ATTACK &amp; PORTISHEAD',
  'Bristol, trip-hop and the slowed beat', [
    '<!--bg:hauntology-->',
    '<img class="indie-pic" src="assets/media/web/indie/bristol-01.jpg" alt=""><span class="indie-cap">Bristol</span>',
    '<p><small>a page on the two Bristol records that turned the sampler into an',
    'instrument, kept by a collector who came to them sideways off the indie',
    'shelf. last updated 6 Feb. best viewed at 640x480.</small></p>',
    '<h1>BRISTOL, THE SAMPLER, AND THE SLOWED BEAT</h1>',
    '<p><small>You are visitor 000889. the counter runs at 90 beats per minute,',
    'like everything else on this page.</small></p>',
    '<hr>',
    '<h2>Blue Lines (1991)</h2>',
    '<p>Massive Attack came out of the Wild Bunch, a Bristol sound system, so their',
    'first record was made by people who thought like DJs, not like a band. Blue',
    'Lines (Wild Bunch through Circa and Virgin, 1991) is built out of records',
    'other people made, samples slowed right down and laid under Shara Nelson,',
    'Horace Andy and a very young Tricky. "Unfinished Sympathy" is the one',
    'everybody knows, strings over a broken beat; "Safe from Harm" walks in on a',
    'sample and never speeds up. The dub is in the low end and the patience, the',
    'sound-system habit of letting a bassline do the work. If you want that',
    'lineage properly, the <a href="king-tubby.geocities.ws">King Tubby page</a>',
    'and the <a href="dub-ring.geocities.ws">Dub Ring</a> are where it starts.</p>',
    '<h2>Dummy (1994)</h2>',
    '<p>Portishead took the same city and made it colder. Dummy (Go! Beat, 1994)',
    'is Beth Gibbons singing like a torch singer over Geoff Barrow and Adrian',
    'Utley, "Glory Box", "Sour Times", "Numb". The detail I never get over is the',
    'crackle. Barrow did not just sample old records; the story is he cut his own',
    'playing to acetate, scuffed it, and sampled that back in, so the surface noise',
    'is deliberate, manufactured, a new record wearing an old one’s coat. It is a',
    'made thing pretending to be a found thing.</p>',
    '<h2>The sampler as indie’s second instrument</h2>',
    '<p>This is the page where I say it straight. On this shelf the sampler does',
    'the job the guitar used to do. It is the instrument you build a track on, and',
    'the tune is what you choose to steal and how you slow it. The people who',
    'taught everyone that a sampler is a compositional tool and not a toy are on',
    'the <a href="public-enemy-bomb-squad.geocities.ws">Bomb Squad page</a>;',
    'Bristol took their method and dropped the tempo through the floor. Same',
    'instrument, opposite mood.</p>',
    '<h2>Is the crackle nostalgia, or method?</h2>',
    '<p>My question, and it is the one that sends me to the end of the shelf. That',
    'manufactured hiss on Dummy is doing something I only fully understood once I',
    'reached <a href="boards-of-canada.geocities.ws">Boards of Canada</a>, where',
    'the decayed tape and the false memory become the whole point of the record.',
    'Portishead get there first, almost by accident: they wanted an atmosphere and',
    'built one out of fake age. So is the crackle a longing for a past, or just a',
    'good trick with a sampler? I think, on this record, longing is the trick, and',
    'that is the door out of trip-hop and into the hauntology at the far end of',
    'the collection.</p>',
    '<p><small>Why they matter now: they proved you could make a heartbreak record',
    'entirely out of other people’s records, and make it sound like it had always',
    'existed. The shops are shut; the samples are all we have.</small></p>',
    '<hr>',
    '<p><small>guestbook’s broken again, sorry. page under construction, the Dummy',
    'section keeps de-syncing. Filed under Bristol.</small></p>',
    '<hr>',
    '<p><small>',
    '[ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="dub-ring.geocities.ws">The Dub Ring</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    '[ prev | post-rock ring | next ]',
    '</small></p>',
  ]);

// ---- Bark Psychosis & post-rock ---------------------------------------------

const BARK_PSYCHOSIS_POSTROCK = P('bark-psychosis-postrock.geocities.ws',
  'BARK PSYCHOSIS &amp; THE WORD POST-ROCK',
  'Hex, and where the guitar stops being the point', [
    '<!--bg:hauntology-->',
    '<img class="indie-pic" src="assets/media/web/indie/reel-02.jpg" alt=""><span class="indie-cap">reel-to-reel tape</span>',
    '<p><small>a page about Hex (1994) and the label somebody stuck on it, kept by',
    'the collector who taped the Peel sessions and reads the reviews too closely.',
    'last updated 3 Feb. best viewed at 640x480.</small></p>',
    '<h1>HEX, AND THE WORD THEY INVENTED FOR IT</h1>',
    '<p><small>You are visitor 000402. the counter has stopped, which suits the',
    'record.</small></p>',
    '<hr>',
    '<h2>Hex (1994)</h2>',
    '<p>Bark Psychosis were Graham Sutton’s band, and Hex (Circa through Virgin,',
    '1994) is the record I keep for the exact moment a rock group stops wanting to',
    'be one. Parts of it were recorded in a church in east London, and it sounds',
    'like it, all space and decay, guitars that ring and then get out of the way',
    'for a bassline, a bit of tape, a held silence. The guitar is still there; it',
    'is just no longer the point. It has become one texture among several, which',
    'is a very different job from playing the riff.</p>',
    '<h2>The word</h2>',
    '<p>This is the page where a critic gets a credit. Simon Reynolds reviewed Hex',
    'and reached for "post-rock", using rock instruments for things rock was not',
    'built to do, guitars as a source of tone and colour rather than of riffs. The',
    'name stuck, spread, and got hung on a hundred bands who never asked for it.',
    'I have a soft spot for the fact that a whole genre got its name from one',
    'review of one record most people had not heard. The label came before the',
    'thing it labelled had really arrived.</p>',
    '<h2>Where it comes from, where it goes</h2>',
    '<p>The ancestor everyone names is Talk Talk, who went from a synth-pop band to',
    'making Spirit of Eden (1988) and Laughing Stock (1991), Mark Hollis building',
    'records out of quiet and refusing to tour them. Bark Psychosis are the indie',
    'children of that nerve. And the two bands I file next to them show the road',
    'out: Disco Inferno, whose D.I. Go Pop (Rough Trade, 1994) wired every guitar',
    'string and drum to a sampler so a strummed chord might trigger a breaking',
    'wave; and Seefeel, who started on Too Pure making guitar-drone and then',
    'signed to Warp, which is the literal door from this shelf to the electronic',
    'one. When a guitar band walks onto <a href="warp-records.geocities.ws">Warp</a>',
    'the argument of this whole collection is basically over.</p>',
    '<h2>What is a rock band that has stopped wanting to rock?</h2>',
    '<p>My question, and Hex is my answer to it. It is a band using the loop and',
    'the sampler and the studio as its instruments while still, technically,',
    'holding guitars. It is guitars discovering they were only ever one way of',
    'moving air. Follow the thread to the end and you arrive where I always end',
    'up, at <a href="boards-of-canada.geocities.ws">Boards of Canada</a>, all',
    'decayed tape and half-remembered warmth, no guitars needed. Hex is the last',
    'record on this shelf that still bothers to pick one up.</p>',
    '<p><small>Why it matters now: it is the sound of an instrument admitting it is',
    'not the only tool in the room, made in a church while the shops outside were',
    'already starting to close. Play it low, all the way through.</small></p>',
    '<hr>',
    '<p><small>under construction. the guestbook took one entry in four years and it',
    'was somebody asking what post-rock means. i still do not have a short answer.</small></p>',
    '<hr>',
    '<p><small>',
    '[ <a href="electronic-tape-ring.geocities.ws">Electronic &amp; Tape Music</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    '[ prev | post-rock ring | next ]',
    '</small></p>',
  ]);

export const INDIE_F = [
  STEREOLAB,
  SPIRITUALIZED,
  MASSIVE_ATTACK_PORTISHEAD,
  BARK_PSYCHOSIS_POSTROCK,
];
