// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH PHIL_A — the Greeks, Heraclitus to Epicurus.
//
// Pages a 1990s enthusiast, student or reading group might have kept about the
// philosopher they loved. A fan shrine to the obscure one of Ephesus; a sober
// summary of Parmenides; the minutes of a reading group arguing over Socrates;
// a handed-in essay on Plato; a summary of Aristotle; and a write-up of a talk
// on Epicurus. The names, dates, works and doctrines are real; the framing,
// the counters and the enthusiasms are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Heraclitus: the personal fan shrine (SHOWPIECE) ------------------------

const HERACLITUS = P('heraclitus.geocities.ws', 'HERACLITUS',
  'THE RIVER PAGE // Heraclitus of Ephesus', [
    '<!--bg:antiquity-->',
    '<h1>THE RIVER PAGE</h1>',
    '<p><small>a shrine to Heraclitus of Ephesus (c. 535 to c. 475 BC), the one',
    'they called the Obscure and also the Weeping Philosopher. i met him in a',
    'second-hand copy of the fragments with half the spine gone and i have not',
    'been the same since. everything on this page i had to dig out of other',
    'writers, because he left one book and it is lost. — riverwatcher</small></p>',
    '<hr>',
    '<div class="fs-epi">Nature loves to hide. &mdash; Heraclitus, fragment 123</div>',
    '<p>Here is the thing you already half-know, the one line that got out of the',
    'ancient world and never stopped travelling. He looked at a river and saw the',
    'whole of reality in it.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Upon those who step into the same rivers,',
    'different and again different waters flow.&rdquo;</p><p><small>Heraclitus,',
    'fragment 12, as preserved by Arius Didymus</small></p></blockquote>',
    '<p>The river keeps its name and its banks, so it looks like the same river,',
    'but the water is never the water you touched a moment ago. You are like that.',
    'The world is like that. This is FLUX, in Greek the sense caught later in the',
    'tag <i>panta rhei</i>, all things flow. Nothing stands still, nothing simply',
    'stays. To be is to be in change.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/heraclitus-01.jpg" alt=""><span class="indie-cap">Heraclitus (photo: RoyFokker, CC BY-SA 4.0)</span>',
    '<p>His chosen element was FIRE. Where an earlier thinker had picked water or',
    'air as the <i>arche</i>, the first stuff of the world, Heraclitus picked the',
    'one that is never a thing but always a process. Fire only exists by burning.',
    'It keeps its shape by changing its fuel. That is the whole cosmos in a candle:',
    'steady on the surface, feeding and dying underneath.</p>',
    '<div class="fs-pull">All things flow, and the fire keeps the measure.</div>',
    '<div class="fs-aside"><b>What is the logos?</b> This is the hard word. It',
    'means the account, the word, the ratio, the measure. For Heraclitus the flux',
    'is not chaos: under the endless change runs one common <i>logos</i>, a lawful',
    'proportion that holds the changing world together and that a wise person can',
    'come to hear. He complains that most people live as if asleep, each in a',
    'private world, deaf to the common thing. Centuries later the word gets picked',
    'up by the Stoics, and later still by the opening of John\'s Gospel, but it',
    'starts here, with him, meaning the hidden order in the burning.</div>',
    '<p>He also loved the way opposites turn out to be one. The road up the hill',
    'and the road down the hill are the same road. Disease makes health sweet,',
    'hunger makes fullness good. Strife, he says, is justice, because the tension',
    'between opposites is exactly what holds a thing in being, the way the tension',
    'in a bowstring or a lyre-string is what makes it work. Here is the shape of',
    'the doctrine set out plainly:</p>',
    '<pre>',
    'THE ARGUMENT OF THE RIVER',
    '  1. Everything is always changing; nothing simply stays.',
    '  2. Yet the change is not random: it keeps a measure.',
    '  3. That measure is the logos, common to all, the same for all.',
    '  4. Fire is its emblem: ever-living, kindled and quenched in measures.',
    '  5. Opposites are one: up and down, war and peace, the way there',
    '     and the way back are a single road.',
    '  6. Most people sleep through this. The wise listen to the logos,',
    '     not to me.',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/phil/parmenides-01.jpg" alt=""><span class="indie-cap">Parmenides, who denied all change (photo: Sergio Spolti, CC BY-SA 4.0)</span>',
    '<p><b>The quarrel that made European philosophy</b></p>',
    '<p>You cannot understand what came next without the fight. Over in Elea,',
    'Parmenides argued the exact opposite: that change is an illusion and only',
    'unchanging Being is real. Heraclitus says reality IS change; Parmenides says',
    'reality cannot change at all. That standoff is the engine room of everything',
    'after. Plato spent his life trying to have it both ways, an unchanging world',
    'of Forms above a flowing world of things, and you can read the whole of',
    '<a href="plato.geocities.ws">Plato</a> as an answer to both men at once. Go',
    'and hear the other side of it from <a href="parmenides.geocities.ws">',
    'Parmenides</a> and make up your own mind. i know whose river i am standing in.</p>',
    '<hr>',
    '<p><small>under eternal construction (fitting, for a flux page) &middot;',
    'you are visitor 00292 &middot; best viewed in Netscape at 800x600 &middot;',
    'last updated 21 Aug</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Parmenides: the academic summary ---------------------------------------

const PARMENIDES = P('parmenides.geocities.ws', 'PARMENIDES',
  'Parmenides of Elea // a short account', [
    '<!--bg:antiquity-->',
    '<h1>Parmenides of Elea</h1>',
    '<p><small>A short and sober account, kept for students who have to read the',
    'poem and would like to know what it is doing before they start. Third person',
    'throughout. Corrections welcome.</small></p>',
    '<hr>',
    '<p>Parmenides (born c. 515 BC) came from Elea, a Greek colony in southern',
    'Italy, and he is the founder of what later writers call the Eleatic school.',
    'His pupil Zeno defended him with the famous paradoxes of motion. He wrote a',
    'single philosophical poem, conventionally titled <i>On Nature</i>, of which',
    'substantial fragments survive, chiefly through Simplicius. It is the earliest',
    'sustained piece of deductive metaphysics in the Western tradition.</p>',
    '<p>The poem opens with a chariot journey in which the narrator is carried up',
    'to a goddess, who promises to teach him two things: the unshakeable heart of',
    'well-rounded truth, and the opinions of mortals, in which there is no true',
    'trust. This gives the work its two parts.</p>',
    '<p><b>The Way of Truth.</b> The core is a single, austere claim: <i>it is,</i>',
    'and <i>it is not possible for it not to be.</i> One can think and speak only of',
    'what is; what is not cannot even be thought, for there is nothing there to',
    'think about. From this Parmenides deduces the properties of Being. Since what',
    'is not is nothing, Being cannot have come from it, so Being is ungenerated. It',
    'cannot pass into nothing, so it is imperishable. It cannot have gaps of',
    'not-being within it, so it is continuous and one. It cannot change, for change',
    'would require it to become what it is not. Being is therefore ungenerated,',
    'indestructible, whole, unique, unmoving and complete.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/parmenides-01.jpg" alt=""><span class="indie-cap">Parmenides (photo: Sergio Spolti, CC BY-SA 4.0)</span>',
    '<p><b>The Way of Opinion.</b> The goddess then gives an account of the world',
    'as mortals take it to be, a cosmos of light and night, of many things coming',
    'to be and passing away. She flags it in advance as deceptive. Scholars still',
    'argue why a philosopher who has just proved that change is impossible would',
    'go on to give a detailed cosmology of a changing world. The usual reading is',
    'that it is the best account possible of the world of appearances, offered so',
    'that no rival can catch the student out, but known to be second-best.</p>',
    '<p><b>Why he matters.</b> Parmenides set the problem that the next two',
    'centuries had to solve. If reason proves that Being is one and unchanging, yet',
    'the senses show a many that changes, which do we trust? He stands as the exact',
    'opposite pole to <a href="heraclitus.geocities.ws">Heraclitus</a>, for whom',
    'reality simply is change. The pluralists after him, the atomists and the',
    'rest, were trying to save the appearances without breaking his logic. Above',
    'all his shadow falls across <a href="plato.geocities.ws">Plato</a>, whose',
    'Forms are unchanging and known by reason exactly as Parmenidean Being is, and',
    'who honoured the old man by naming a difficult late dialogue after him.</p>',
    '<hr>',
    '<p><small>a plain-text page, no apologies &middot; visitor 00518 &middot;',
    'best viewed at 800x600 &middot; last updated 4 Mar</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Socrates: the reading-group minutes ------------------------------------

const SOCRATES = P('socrates.geocities.ws', 'SOCRATES',
  'MINUTES: the Tuesday reading group does Socrates', [
    '<!--bg:antiquity-->',
    '<h1>MINUTES: Socrates</h1>',
    '<p><small>Minutes of the Tuesday evening reading group, upstairs at the',
    'Feathers. Present: seven of us. Apologies: two. We had said we would read the',
    '<i>Apology</i> and we mostly had. Minutes taken by whoever lost the toss.</small></p>',
    '<hr>',
    '<p>We started, as ever, by trying to agree what we were even talking about,',
    'which felt appropriate. Socrates (469 to 399 BC), Athenian, wrote NOTHING. We',
    'kept coming back to this. Everything we have is second-hand: the dialogues of',
    'his pupil <a href="plato.geocities.ws">Plato</a>, the memoirs of Xenophon, a',
    'cruel turn in a comedy by Aristophanes, and remarks by his intellectual',
    'grandson <a href="aristotle.geocities.ws">Aristotle</a>. So the man and the',
    'character are hard to pull apart. This is now called the Socratic problem and',
    'we did not solve it before the first round.</p>',
    '<p><b>The method.</b> General agreement that the heart of it is the ELENCHUS,',
    'the cross-examination. Socrates claims to know nothing and asks someone who',
    'claims to know, say, what courage is, or piety, or justice. He draws out a',
    'definition, then shows by questions that it contradicts things the person also',
    'believes. The definition collapses. Everyone leaves knowing less than they',
    'thought, which Socrates counts as progress.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I am wiser than this man; it is likely',
    'that neither of us knows anything worthwhile, but he thinks he knows something',
    'when he does not, whereas I do not know and do not think I do.&rdquo;</p>',
    '<p><small>Socrates in Plato, <i>Apology</i> 21d</small></p></blockquote>',
    '<p>This is where the famous tag comes from, usually shortened to &ldquo;I know',
    'that I know nothing.&rdquo; M. pointed out, rightly, that he never quite says',
    'it that neatly, but the sense is his. His wisdom is knowing the size of his',
    'own ignorance.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/socrates-01.jpg" alt=""><span class="indie-cap">Socrates, Roman bust (public domain)</span>',
    '<p><b>The daimonion.</b> A tangent that took twenty minutes. Socrates spoke of',
    'a <i>daimonion</i>, a divine sign or inner voice, which never told him what to',
    'do but sometimes stopped him doing something. Not a conscience exactly, not a',
    'god exactly. We did not agree on what it was and neither did the ancients.</p>',
    '<p><b>The trial.</b> This is where the room went quiet. In 399 BC he was tried',
    'before an Athenian jury on charges of impiety and corrupting the young. The',
    'city had lost a long war and wanted someone to blame, and Socrates had spent',
    'decades making powerful men look foolish in public. He was found guilty by a',
    'narrow margin, then, refusing to grovel or to propose exile, was condemned to',
    'death. He drank the hemlock. Plato\'s <i>Phaedo</i> gives the death scene and',
    'D. read the last page aloud and we let it sit.</p>',
    '<p>Next Tuesday: Plato, the <i>Meno</i>, the bit where the slave boy does',
    'geometry. Bring the Penguin if you have it. We adjourned owing the Feathers',
    'for the crisps.</p>',
    '<hr>',
    '<p><small>hit counter: 00147 &middot; best viewed at 800x600 &middot; the',
    'Tuesday group, meeting since Sept &middot; page last updated 6 Nov</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Plato: the student coursework essay ------------------------------------

const PLATO = P('plato.geocities.ws', 'PLATO',
  'Plato and the Forms // coursework, PHIL-102', [
    '<!--bg:antiquity-->',
    '<h1>Plato and the Theory of Forms</h1>',
    '<p><small>PHIL-102 Introduction to Ancient Philosophy &middot; Essay 2 &middot;',
    'word count 1,480 &middot; submitted late, sorry Dr. Okafor, the printer at the',
    'hall was out of toner AGAIN. Grade and comments came back, see foot of page. i',
    'put it online because a mate asked for it.</small></p>',
    '<hr>',
    '<p><b>Question: Explain Plato\'s Theory of Forms and its role in the</b>',
    '<b><i>Republic</i>.</b></p>',
    '<p>Plato (c. 428 to c. 348 BC) was an Athenian aristocrat, a pupil of',
    '<a href="socrates.geocities.ws">Socrates</a>, and the founder of the Academy,',
    'the school that gives us the word &ldquo;academic&rdquo; and that ran, in some',
    'form, for nearly nine centuries. His most famous pupil was',
    '<a href="aristotle.geocities.ws">Aristotle</a>. He wrote in dialogues, mostly',
    'with Socrates as the speaker, so it is never quite simple to say which view is',
    'Plato\'s own. The Theory of Forms is the view most people mean by',
    '&ldquo;Platonism&rdquo; and it runs right through the <i>Republic</i>.</p>',
    '<p>The basic idea. The things we see and touch are always imperfect and always',
    'changing. No drawn triangle is perfectly a triangle; no just act is justice',
    'itself. Yet we understand them by a standard they never quite meet. Plato',
    'argues that the standard is real: there exists a Form of Triangle, of Justice,',
    'of Beauty, of the Good, unchanging, perfect, grasped by the mind and not the',
    'eye. Particular things are what they are by &ldquo;participating&rdquo; in the',
    'Forms. The Forms are more real than the things, because they do not change,',
    'which is Plato taking a side in the old fight between the philosophers of',
    'flux and the philosophers of being.</p>',
    '<p><b>The Divided Line.</b> In Book VI Plato draws a line cut into four to',
    'grade knowledge. Lowest is <i>eikasia</i>, guessing from images and shadows;',
    'then <i>pistis</i>, belief about ordinary visible things; then',
    '<i>dianoia</i>, the reasoning of the mathematician who still leans on',
    'diagrams; and highest <i>noesis</i>, pure understanding of the Forms',
    'themselves, crowned by the Form of the Good, which he compares to the sun',
    'because it is what makes the other Forms knowable at all.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/plato-01.jpg" alt=""><span class="indie-cap">Plato, Roman bust (photo: Marie-Lan Nguyen, public domain)</span>',
    '<p><b>The Cave.</b> In Book VII comes the allegory everyone remembers.',
    'Prisoners are chained facing a wall, and take the shadows cast on it for the',
    'whole of reality. One is freed, turns, is dazzled by the fire, and is dragged',
    'up out of the cave into the sunlight, where at last he sees real things and',
    'finally the sun itself, which stands for the Good. The point is education as',
    'turning the soul around, and it maps straight onto the divided line. When he',
    'goes back down to tell the others, they think he has ruined his eyes and would',
    'kill him if they could, which any reader in PHIL-102 can see is Plato thinking',
    'about what Athens did to Socrates.</p>',
    '<p><b>The tripartite soul and the city.</b> The <i>Republic</i> is really',
    'about justice. Plato says the soul has three parts: reason, spirit (the',
    'high-hearted part that feels anger and honour), and appetite. Justice in the',
    'soul is each part doing its own job under the rule of reason. He builds a',
    'city on the same plan, with rulers, guardians and producers, so that the ideal',
    'state is the soul written large, and the philosopher, who alone knows the',
    'Forms, is the one fit to rule.</p>',
    '<p><b>Conclusion.</b> The Forms give Plato a fixed world for knowledge to be',
    'about, a standard for value, and a reason to put philosophers in charge. Even',
    'Aristotle, who rejected the whole theory, spent his life arguing with it,',
    'which tells you how much work it does.</p>',
    '<hr>',
    '<p><small><b>Bibliography</b> (as handed in, formatting as-is)<br>',
    'Plato, <i>The Republic</i>, trans. Desmond Lee, Penguin, 1974.<br>',
    'Plato, <i>The Last Days of Socrates</i>, Penguin (the one with the green',
    'cover).<br>',
    'Annas, J. <i>An Introduction to Plato\'s Republic</i>, Oxford, 1981.<br>',
    'lecture handout wk 3 &ldquo;Forms and Participation&rdquo; (Dr. Okafor).</small></p>',
    '<p><small><b>Marker\'s comment:</b> B+. Clear on the Line and the Cave. You',
    'assert &ldquo;more real&rdquo; without unpacking degrees of reality; and the',
    'bibliography is not a valid style. See me. Good work though. &mdash; A.O.</small></p>',
    '<hr>',
    '<p><small>visitor 00363 &middot; best viewed at 800x600 &middot; last updated',
    '2 Dec, the day i got it back</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Aristotle: the academic summary ----------------------------------------

const ARISTOTLE = P('aristotle.geocities.ws', 'ARISTOTLE',
  'Aristotle of Stagira // a short account', [
    '<!--bg:antiquity-->',
    '<h1>Aristotle of Stagira</h1>',
    '<p><small>A sober summary for readers who want the shape of the system before',
    'they open the texts. Third person, no frills. If you find an error, say so.</small></p>',
    '<hr>',
    '<p>Aristotle (384 to 322 BC) was born at Stagira in the north of Greece, came',
    'to Athens at seventeen and studied for twenty years in',
    '<a href="plato.geocities.ws">Plato\'s</a> Academy. He later tutored the young',
    'Alexander of Macedon, the one the world would call the Great, and then founded',
    'his own school in Athens, the Lyceum, whose members were called Peripatetics',
    'from the covered walk where they taught. He wrote across almost everything:',
    'logic, physics, biology, astronomy, metaphysics, ethics, politics, rhetoric',
    'and poetics. Much of what survives reads like lecture notes rather than',
    'finished books.</p>',
    '<p><b>Logic.</b> Aristotle effectively invented formal logic. His treatises,',
    'later collected as the <i>Organon</i>, set out the theory of the syllogism, a',
    'form of argument in which a conclusion follows of necessity from two premises.',
    'The stock example is not his own words but catches it: all men are mortal,',
    'Socrates is a man, therefore Socrates is mortal. This framework stood as the',
    'whole of logic for two thousand years.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/aristotle-01.jpg" alt=""><span class="indie-cap">Aristotle, after Lysippos (public domain)</span>',
    '<p><b>The four causes.</b> To explain why anything is as it is, Aristotle says',
    'we must give four kinds of answer. The material cause is what a thing is made',
    'of (the bronze of a statue). The formal cause is the shape or definition that',
    'makes it that kind of thing (the figure the statue takes). The efficient cause',
    'is what brought it about (the sculptor and the chisel). The final cause is',
    'what it is for, its end or <i>telos</i> (to honour a god, to adorn the',
    'temple). Nature, for Aristotle, is full of final causes: things have ends',
    'built into what they are, and an acorn is directed towards the oak.</p>',
    '<p><b>Substance, potentiality, actuality.</b> Against his teacher, Aristotle',
    'put the real firmly back into individual things. A particular horse or man is',
    'a <i>substance</i>, a this-here, a union of matter and form, and the universal',
    'exists in such things rather than in a separate heaven of Forms. Change he',
    'explains as the passage from potentiality to actuality: the acorn is',
    'potentially an oak and becomes one actually; the bronze is potentially a',
    'statue. This pair let him describe growth and change without falling into',
    'either Heraclitus\' pure flux or Parmenides\' frozen Being.</p>',
    '<p><b>The golden mean.</b> His ethics is set out chiefly in the',
    '<i>Nicomachean Ethics</i>, named for his son. The good for a human being is',
    '<i>eudaimonia</i>, flourishing, the activity of the soul in accordance with',
    'virtue across a whole life. Moral virtue is a settled disposition to feel and',
    'act rightly, and it lies as a mean between two vices, one of excess and one of',
    'deficiency. Courage sits between rashness and cowardice; generosity between',
    'waste and meanness. The mean is not a fixed midpoint but is relative to the',
    'person and the situation, and finding it is the work of practical wisdom.</p>',
    '<p><b>Afterlife of the system.</b> The schools that came after took what they',
    'needed and quarrelled with the rest. The <a href="the-stoics.geocities.ws">',
    'Stoics</a> built a rival account of nature and the good life, and much later',
    'Aristotle would be absorbed, argued over and half-swallowed by medieval',
    'philosophy, so that for centuries he was known simply as the Philosopher.</p>',
    '<hr>',
    '<p><small>visitor 00405 &middot; best viewed at 800x600 &middot; under',
    'construction in the Politics section &middot; last updated 18 Jan</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- Epicurus: the talk write-up --------------------------------------------

const EPICURUS = P('epicurus.geocities.ws', 'EPICURUS',
  'Notes from a talk on Epicurus // the Garden', [
    '<!--bg:antiquity-->',
    '<h1>Notes from a talk on Epicurus</h1>',
    '<p><small>I went along on Thursday to a talk at the adult education centre,',
    '&ldquo;Epicurus and the Art of Being Untroubled&rdquo;, given by a visiting',
    'lecturer whose name I did not catch properly. These are my notes, tidied up on',
    'the bus home and after. Any mistakes are mine, not the speaker\'s.</small></p>',
    '<hr>',
    '<p>She started by clearing up the insult. In everyday English an',
    '&ldquo;epicure&rdquo; is a person devoted to fine food and luxury, and this,',
    'she said, is almost the reverse of what Epicurus taught. Epicurus (341 to 270',
    'BC) was born on Samos and settled in Athens, where about 307 BC he bought a',
    'house with a garden and taught there. The school was simply called the Garden.',
    'Unusually for the time it admitted women and enslaved people as members, which',
    'scandalised the neighbours.</p>',
    '<p><b>The physics.</b> Epicurus took over the atomism of Democritus. Nothing',
    'exists but atoms and the void; the atoms are eternal, fall through the void,',
    'and combine to make everything, including us. To this he added one famous',
    'wrinkle, the SWERVE: now and then an atom veers a tiny amount from its',
    'straight fall, with no cause. Without the swerve, atoms would rain down in',
    'parallel forever and nothing would ever collide or combine, and there would be',
    'no room for free will. The speaker said the swerve is Epicurus\' way of keeping',
    'the universe from being a rigid machine.</p>',
    '<img class="indie-pic" src="assets/media/web/phil/epicurus-01.jpg" alt=""><span class="indie-cap">Epicurus, Roman bust (public domain)</span>',
    '<p><b>The point of it all: ataraxia.</b> The physics is in service of a goal.',
    'Epicurus is a hedonist, yes, but pleasure for him is chiefly the ABSENCE of',
    'pain and trouble, a settled calm he calls <i>ataraxia</i>, freedom from',
    'disturbance in the mind. The pleasures to chase are simple and easy to get,',
    'bread and water and friendship and thought, not the endless craving that only',
    'breeds anxiety. He rated friendship above almost everything.</p>',
    '<p><b>Death is nothing to us.</b> This was the part the room leaned into. Most',
    'of our misery, Epicurus argues, comes from two fears: fear of the gods and',
    'fear of death. The gods, if they exist, are blissful and take no interest in',
    'us, so there is nothing to dread there. And death is simply the end of',
    'sensation. His argument, from the <i>Letter to Menoeceus</i>, runs: while we',
    'exist, death is not here; when death is here, we do not exist; so death is',
    'nothing to the one who dies, and there is no one left for it to harm. The',
    'speaker put his four-part cure on the board, the TETRAPHARMAKOS:</p>',
    '<pre>',
    'THE FOURFOLD REMEDY (tetrapharmakos)',
    '  1. Do not fear god.',
    '  2. Do not worry about death.',
    '  3. What is good is easy to get.',
    '  4. What is terrible is easy to endure.',
    '</pre>',
    '<p>She closed by noting that we have almost none of Epicurus\' own many books.',
    'A few letters and collections of sayings survive, and the fullest statement of',
    'the whole system is a Latin poem by his Roman follower Lucretius,',
    '<i>De Rerum Natura</i>, written two centuries later. For the rival school of',
    'the day, the tougher and more famous one, she pointed us to the',
    '<a href="the-stoics.geocities.ws">Stoics</a>, who agreed with almost none of',
    'the physics and shared a good deal of the aim. And for the Democritus and',
    'four-causes background she said to read some',
    '<a href="aristotle.geocities.ws">Aristotle</a> first, which I have not done',
    'yet but mean to.</p>',
    '<p><small>someone has set the whole of Lucretius in ML:',
    '<a href="de-rerum-natura-ml.geocities.ws">de rerum natura</a></small></p>',
    '<hr>',
    '<p><small>my notes, put up for the others who were there &middot; visitor',
    '00188 &middot; best viewed in Netscape at 800x600 &middot; last updated the',
    'Sunday after, 9 Feb</small></p>',
    '<p><small>[ <a href="philosophy-ring.geocities.ws">Philosophy Ring</a> ]</small></p>',
  ]);

// ---- De rerum natura, set in ML -----------------------------------------------
// The program is held line by line and printed on the page; pagefile: in main.js
// saves exactly the text of the <pre> to the NostBook.
export const DRN_ML = [
  "(* DE RERVM NATVRA                                                       *)",
  "(* On the Nature of Things, in six books, after Titus Lucretius Carus,  *)",
  "(* who wrote it in Latin hexameters for Gaius Memmius and did not live  *)",
  "(* to finish it. Set again here in ML, which has no hexameters, and     *)",
  "(* run on whatever machine will take it.                                *)",
  "(*                                                                      *)",
  "(*   ml de_rerum_natura.ml                                              *)",
  "",
  "let",
  "",
  "  (* ================================================================== *)",
  "  (* LIBER PRIMVS                                                       *)",
  "  (* ================================================================== *)",
  "",
  "  (* Aeneadum genetrix, mother of Aeneas and his people,               *)",
  "  (* pleasure of men and of gods, kind Venus, who under the sliding    *)",
  "  (* signs of the sky fill the sea that carries ships and the earth    *)",
  "  (* that carries crops, since through you every kind of living thing  *)",
  "  (* is conceived, and rises, and looks upon the light of the sun:     *)",
  "  (* the winds run from you, goddess, and the clouds of heaven, and    *)",
  "  (* the earth, the clever maker, sends up sweet flowers for you, and  *)",
  "  (* the levels of the ocean laugh, and the calmed sky shines with     *)",
  "  (* light poured out. Be with me while I write these verses on the    *)",
  "  (* nature of things for my Memmius, and give the Romans quiet,       *)",
  "  (* because while the country is in trouble I cannot work with an    *)",
  "  (* untroubled mind, and he cannot, in times like these, be spared    *)",
  "  (* from the common good.                                             *)",
  "",
  "  val genetrix = \"Aeneadum genetrix\"",
  "  val memmius = \"Memmius\"",
  "  val quies = 0                     (* the peace she is asked for *)",
  "",
  "  (* When human life lay foul upon the ground for all to see,          *)",
  "  (* crushed under the weight of religion, which showed its head from  *)",
  "  (* the regions of the sky and stood over mortals with a horrible    *)",
  "  (* face, a man of Greece first dared to lift his mortal eyes against *)",
  "  (* it and first to stand against it. Neither the stories of the     *)",
  "  (* gods nor thunderbolts nor the sky with its threatening roar held  *)",
  "  (* him back. They drove the keen courage of his mind the harder, so  *)",
  "  (* that he longed to be the first to break the close bolts of the   *)",
  "  (* gates of nature. And so the living force of his mind won, and he *)",
  "  (* went far beyond the flaming walls of the world, and crossed the   *)",
  "  (* whole unmeasured universe in mind and spirit, and came back, a    *)",
  "  (* victor, to tell us what can come to be and what cannot.          *)",
  "",
  "  val graius_homo = \"Epicurus\"",
  "  fun moenia_mundi walls = walls    (* the flaming walls, which a mind may pass *)",
  "",
  "  (* The first principle: nothing is ever made out of nothing by the   *)",
  "  (* power of the gods. Nil posse creari de nilo. If things came from  *)",
  "  (* nothing, any kind could be born from anything, and nothing would  *)",
  "  (* need a seed. Men could rise out of the sea, the scaly tribe out   *)",
  "  (* of the earth, and birds could hatch from the sky. Trees would not *)",
  "  (* keep to their fruit; every tree could bear everything.            *)",
  "",
  "  fun create from = from            (* what is made, is made of what was there *)",
  "  val nihil = nil",
  "  val ex_nihilo = create nihil      (* and from nothing, nothing *)",
  "",
  "  (* The second: nature resolves each thing back into its bodies and   *)",
  "  (* does not destroy anything into nothing. If time, which takes      *)",
  "  (* things away with age, consumed the whole of their matter, from    *)",
  "  (* where would Venus lead back the races of living things, each in   *)",
  "  (* its kind, into the light of life?                                  *)",
  "",
  "  fun conserve things = things      (* what goes, goes back into the store *)",
  "",
  "  (* So there are bodies we cannot see. The wind that whips the sea    *)",
  "  (* and wrecks great ships is made of bodies, though no one has seen  *)",
  "  (* them. Clothes hung on a shore that breaks with waves grow damp,  *)",
  "  (* and spread out in the sun they dry, though no one has seen the    *)",
  "  (* water arrive or leave. A ring on a finger thins with the years;  *)",
  "  (* the iron of the plough wears in the furrow; the bronze hands of   *)",
  "  (* statues by the city gates are rubbed thin by the greetings of     *)",
  "  (* people passing. We see that they are less, and we never see the  *)",
  "  (* bodies go.                                                         *)",
  "",
  "  fun len nil = 0",
  "    | len (_ :: rest) = 1 + len rest",
  "",
  "  fun sum nil = 0",
  "    | sum (n :: rest) = n + sum rest",
  "",
  "  (* And there is void, the empty place, inane. If there were none,     *)",
  "  (* nothing could move, since body would stand against body           *)",
  "  (* everywhere and nothing could give way. Water seeps through rock;  *)",
  "  (* food spreads through the limbs; sound passes through walls; cold *)",
  "  (* reaches the bone. None of this happens unless there is somewhere *)",
  "  (* empty for it to go.                                               *)",
  "",
  "  val inane = 0                     (* the void, which weighs nothing and stops nothing *)",
  "",
  "  (* So all of nature, as it is in itself, consists of two things:     *)",
  "  (* bodies, and the void in which they are placed and through which   *)",
  "  (* they move. Anything else you might name is a property of these   *)",
  "  (* two, or something that happens to them. Slavery and poverty and *)",
  "  (* wealth, liberty, war and concord are events: they come and go    *)",
  "  (* and the nature of things stays as it was. Time itself is nothing *)",
  "  (* by itself. It is only our sense of what has passed and what is    *)",
  "  (* happening now and what is to come.                                *)",
  "",
  "  fun eventum (corpus, locus) = (corpus, locus)",
  "",
  "  (* The first bodies are solid and single and cannot be broken.        *)",
  "  (* There is a least part, and it does not divide. If there were no    *)",
  "  (* least, the smallest thing would hold as many parts as the whole   *)",
  "  (* universe, both being endless, and that cannot be. These are the   *)",
  "  (* primordia, the first-beginnings, the seeds of things, the         *)",
  "  (* genital bodies, the elements: I give them many names because our *)",
  "  (* language is poor and the matter is new.                           *)",
  "",
  "  val primordia = [(0, 24), (1, 24), (2, 24), (3, 24),",
  "                   (4, 24), (5, 24), (6, 24), (7, 24)]",
  "",
  "  val summa_rerum = len primordia   (* the sum of things, which does not change *)",
  "",
  "  (* And the universe has no edge. Suppose there were one, and a man   *)",
  "  (* ran to the last limit and threw a spear. Either something stops  *)",
  "  (* the spear, and then there is something beyond the limit, or       *)",
  "  (* nothing stops it, and then the limit was not the limit. Wherever *)",
  "  (* you set the end, I will ask you where the spear goes.             *)",
  "",
  "  fun telum where = where + 1        (* wherever it lands, there is a further place *)",
  "",
  "  (* I am going through places of the Muses that no one has walked     *)",
  "  (* before. I like to come to untouched springs and drink there, and  *)",
  "  (* to pick new flowers. Like a doctor who rims the cup of bitter     *)",
  "  (* wormwood with honey for a child, I have put this hard teaching    *)",
  "  (* into sweet-spoken song.                                           *)",
  "",
  "  val absinthia = \"the teaching\"",
  "  val mel = \"the verse\"",
  "  fun poculum (bitter, honey) = honey ^ \" round the rim of \" ^ bitter",
  "  val potio = poculum (absinthia, mel)",
  "",
  "  (* ================================================================== *)",
  "  (* LIBER SECVNDVS                                                     *)",
  "  (* ================================================================== *)",
  "",
  "  (* Suave, mari magno. It is pleasant, when winds churn the waters on  *)",
  "  (* the great sea, to watch from land another's great trouble: not     *)",
  "  (* because anyone's distress is a joy, but because it is sweet to    *)",
  "  (* see what evils you yourself are free of. Sweeter still to hold   *)",
  "  (* the high calm places built by the teaching of the wise, and look *)",
  "  (* down from there on others wandering everywhere, looking for the  *)",
  "  (* road of life, contending with their talents, fighting over       *)",
  "  (* birth, working night and day to rise to the top of wealth and to  *)",
  "  (* be masters of things.                                             *)",
  "",
  "  val templa_serena = \"the calm places\"",
  "",
  "  (* The first bodies are always moving. Look when the sun's rays are  *)",
  "  (* let into a dark room: you will see many tiny bodies mingling in    *)",
  "  (* many ways through the empty space, in the light of the rays, as  *)",
  "  (* if in eternal war, fighting in squadrons, never resting, driven  *)",
  "  (* together and apart. From this you can guess what it is for the    *)",
  "  (* first beginnings to be tossed for ever in the great void.         *)",
  "",
  "  fun radius motes = motes          (* what the sunbeam shows, it does not change *)",
  "",
  "  (* In the void nothing holds anything back, so all the first bodies  *)",
  "  (* fall at an equal speed, heavy and light alike, straight down by  *)",
  "  (* their own weight, like drops of rain.                             *)",
  "",
  "  fun step nil = nil",
  "    | step ((x, y) :: rest) = (x, y - 1) :: step rest",
  "",
  "  fun fall 0 atoms = atoms",
  "    | fall k atoms = fall (k - 1) (step atoms)",
  "",
  "  fun same (x, y) (a, b) = x = a andalso y = b",
  "",
  "  fun meets atom nil = false",
  "    | meets atom (other :: rest) = same atom other orelse meets atom rest",
  "",
  "  fun collisions nil = 0",
  "    | collisions (atom :: rest) = (if meets atom rest then 1 else 0) + collisions rest",
  "",
  "  (* And here is a thing I want you to know. When the bodies are being  *)",
  "  (* carried straight down through the void by their own weight, at    *)",
  "  (* times quite uncertain and in uncertain places they swerve a       *)",
  "  (* little from their course, just so much that you could call it a   *)",
  "  (* change of motion. Incerto tempore ferme incertisque locis. If     *)",
  "  (* they did not swerve, they would all fall downwards like drops of  *)",
  "  (* rain through the deep void, and no collision would be born, and   *)",
  "  (* no blow would be struck among the first beginnings: and so nature *)",
  "  (* would never have made anything.                                   *)",
  "",
  "  fun incertus seed = (seed * 75 + 74) mod 65537",
  "",
  "  val tempus = incertus 1417 mod 24        (* incerto tempore *)",
  "  val locus = incertus tempus mod 7        (* incertisque locis *)",
  "",
  "  (* No more than the least. Nec plus quam minimum. Not so much that    *)",
  "  (* they seem to move aslant, which the facts would refute; only that *)",
  "  (* much.                                                             *)",
  "",
  "  fun paulum (x, y) = (x + 1, y)",
  "",
  "  fun clinamen when where now i nil = nil",
  "    | clinamen when where now i (atom :: rest) =",
  "        (if now = when andalso i = where then paulum atom else atom)",
  "          :: clinamen when where now (i + 1) rest",
  "",
  "  fun imber k limit swerving atoms seen =",
  "    if k = limit then seen",
  "    else imber (k + 1) limit swerving",
  "           (step (if swerving then clinamen tempus locus k 0 atoms else atoms))",
  "           (seen + collisions (step (if swerving then clinamen tempus locus k 0 atoms else atoms)))",
  "",
  "  val sine_clinamine = imber 0 24 false primordia 0   (* rain, and nothing comes of it *)",
  "  val cum_clinamine = imber 0 24 true primordia 0     (* the first blow is struck *)",
  "",
  "  (* And if every motion were always linked to another, and the new     *)",
  "  (* arose from the old in fixed order, and the first bodies never made *)",
  "  (* by swerving some beginning of motion that breaks the bonds of     *)",
  "  (* fate, so that cause does not follow cause from infinity, where    *)",
  "  (* would this free will come from, for living things all over the    *)",
  "  (* earth, this will wrested from the fates, fatis avolsa voluntas, by *)",
  "  (* which we go where pleasure leads each of us?                      *)",
  "",
  "  fun voluntas will = will",
  "",
  "  (* The bodies have no colour. Colour comes and goes with light, and  *)",
  "  (* the neck of a dove looks now red, now green, now blue, as the sun  *)",
  "  (* moves. Nor do they feel. Living things that feel are made of what *)",
  "  (* does not feel, as worms are born from dung when the earth is wet *)",
  "  (* with rain.                                                        *)",
  "",
  "  fun color _ = \"\"                  (* none *)",
  "  fun sensus _ = false              (* none either *)",
  "",
  "  (* And there are other worlds, many of them, in other parts of the   *)",
  "  (* void, with other races of men and other kinds of wild beasts.     *)",
  "  (* Nothing in the universe is the only one of its kind.              *)",
  "",
  "  val alii_mundi = [primordia, primordia, primordia]",
  "",
  "  (* ================================================================== *)",
  "  (* LIBER TERTIVS                                                      *)",
  "  (* ================================================================== *)",
  "",
  "  (* E tenebris tantis. You who out of such darkness were the first to *)",
  "  (* lift so bright a light, showing us the goods of life, I follow    *)",
  "  (* you, glory of the Greek people, and set my feet firmly in the      *)",
  "  (* prints you left: not as a rival but from love, because I want to *)",
  "  (* copy you. How could a swallow compete with swans?                 *)",
  "",
  "  fun vestigia steps = steps",
  "",
  "  (* The mind, animus, and the spirit, anima, are made of bodies like   *)",
  "  (* everything else: very small, very smooth and very round, so that  *)",
  "  (* they move at the slightest touch. When the spirit leaves, the     *)",
  "  (* body weighs no less, as the scent of wine leaves the wine and the *)",
  "  (* perfume leaves the ointment and nothing appears to be missing.     *)",
  "",
  "  val animus = primordia",
  "  val anima = primordia",
  "",
  "  fun dissolve nil = nil",
  "    | dissolve (_ :: rest) = dissolve rest",
  "",
  "  val post_mortem = dissolve anima",
  "",
  "  (* Nil igitur mors est ad nos. Death, then, is nothing to us and      *)",
  "  (* matters nothing, since the nature of the mind is mortal. As in the *)",
  "  (* time gone by we felt no distress, when the Carthaginians came from *)",
  "  (* every side to fight, when the whole world shook under the trumpet *)",
  "  (* of war and it was not known under whose rule all men would fall, *)",
  "  (* so, when we are no longer, when body and spirit are parted, there *)",
  "  (* will be no one for anything to happen to, and nothing will move  *)",
  "  (* our senses, not if earth were mixed with sea and sea with sky.     *)",
  "",
  "  fun ad_nos _ = ()",
  "",
  "  val ante_natum = len nihil",
  "  val post_obitum = len post_mortem",
  "  val speculum = ante_natum = post_obitum    (* the time before us, held up as a mirror *)",
  "",
  "  (* And if nature herself suddenly spoke and rebuked one of us: what  *)",
  "  (* is it, mortal, that you grieve so much? If the life you had was   *)",
  "  (* pleasant, why not leave like a guest who has had enough, and take *)",
  "  (* untroubled rest? If it was not, why ask for more of it, to waste *)",
  "  (* that too? I can devise nothing more to please you. Everything is *)",
  "  (* always the same.                                                  *)",
  "",
  "  fun eadem omnia sunt = sunt",
  "",
  "  (* ================================================================== *)",
  "  (* LIBER QVARTVS                                                      *)",
  "  (* ================================================================== *)",
  "",
  "  (* From the surface of things, thin films are always peeling off and *)",
  "  (* flying through the air, simulacra, images, like the skin a snake  *)",
  "  (* leaves on a thorn, like the membrane calves shed at birth, and it *)",
  "  (* is these that strike our eyes and wake us to see, and frighten us *)",
  "  (* in our sleep, so that we think we see the dead.                   *)",
  "",
  "  fun simulacrum (x, y) = (x, y)",
  "",
  "  fun peel nil = nil",
  "    | peel (atom :: rest) = simulacrum atom :: peel rest",
  "",
  "  val visa = peel primordia",
  "",
  "  (* And do not think that eyes were made so that we could see. Nothing *)",
  "  (* is born in the body so that we can use it. What is born makes its *)",
  "  (* use.                                                               *)",
  "",
  "  fun usus organ = organ",
  "",
  "  (* This is Venus for us. From her the first drop of sweetness fell   *)",
  "  (* into the heart, and cold care followed. The lovers press close and *)",
  "  (* hurt each other, and get nothing out of it, since nothing can     *)",
  "  (* pass from one body into the other.                               *)",
  "",
  "  fun amor (a, b) = len a + len b - len (a @ b)    (* nothing passes *)",
  "",
  "  (* ================================================================== *)",
  "  (* LIBER QVINTVS                                                      *)",
  "  (* ================================================================== *)",
  "",
  "  (* The world is not divine and not eternal. It had a birth and will  *)",
  "  (* have a death. One day will bring it down, and the great mass and  *)",
  "  (* machinery of the world, held up for so many years, will fall.     *)",
  "  (* Machina mundi.                                                    *)",
  "",
  "  fun mundus 0 = nil",
  "    | mundus n = n :: mundus (n - 1)",
  "",
  "  val natus = mundus 7",
  "  val moriturus = dissolve natus",
  "",
  "  (* The young earth sent up grass and shrubs first, then living things *)",
  "  (* of many kinds, out of the warm and the wet; and the earth has      *)",
  "  (* rightly been given the name of mother, since all came from her.   *)",
  "  (* Many monsters were born that could not feed or breed, and they    *)",
  "  (* died out. Those that are left had cunning or courage or speed.     *)",
  "",
  "  val tellus = \"mater\"",
  "  fun keep p nil = nil",
  "    | keep p (x :: rest) = if p x then x :: keep p rest else keep p rest",
  "  fun can_live n = n mod 3 = 0",
  "  val superstites = keep can_live (mundus 21)",
  "",
  "  (* The first people lived like beasts, and lightning brought fire,   *)",
  "  (* or two branches rubbed in the wind; then huts, and skins, and      *)",
  "  (* speech, which nature drove them to, and need gave names to things. *)",
  "  (* Then towns, and property, and gold, and kings, and laws. Then      *)",
  "  (* bronze, and iron, and war.                                         *)",
  "",
  "  fun ignis branches = branches + 1",
  "  val lingua = \"names\"",
  "",
  "  (* ================================================================== *)",
  "  (* LIBER SEXTVS                                                       *)",
  "  (* ================================================================== *)",
  "",
  "  (* Thunder is clouds colliding high up, as the wind meets them;      *)",
  "  (* lightning is fire struck out of them. It is not the gods. If Jove *)",
  "  (* threw it, why does he strike his own temples, and waste it on the *)",
  "  (* empty sea, and on the mountains where no one is?                  *)",
  "",
  "  fun fulmen _ = \"clouds\"",
  "",
  "  (* The stone the Greeks call magnet, from the Magnesians, draws iron, *)",
  "  (* and the iron rings hang from one another in a chain, five and     *)",
  "  (* more, swaying in the wind, held by the stone's force passing       *)",
  "  (* through them.                                                      *)",
  "",
  "  fun catena 0 = nil",
  "    | catena n = \"anulus\" :: catena (n - 1)",
  "",
  "  val anuli = catena 5",
  "",
  "  (* And there was a plague once in Athens, which came out of Egypt.    *)",
  "  (* It filled the roads with the dead and the temples with the dead.   *)",
  "  (* People fought each other over pyres that were not theirs, setting *)",
  "  (* their own on top of others with great shouting, and would rather  *)",
  "  (* shed blood than leave the bodies.                                 *)",
  "",
  "  val pestis = dissolve primordia",
  "",
  "  (* The poem stops here. Whether he meant it to, no one knows.         *)",
  "",
  "in",
  "  echo (if sine_clinamine = 0",
  "           andalso cum_clinamine > 0",
  "           andalso len ex_nihilo = 0",
  "           andalso summa_rerum = 8",
  "           andalso speculum",
  "        then \"Swerve\"",
  "        else \"\")",
  "end",
].join('\n') + '\n';
const escDrn = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const DRN = P('de-rerum-natura-ml.geocities.ws', 'DE RERUM NATURA',
  'De rerum natura // set in ML', [
    '<!--bg:antiquity-->',
    '<h1>DE RERVM NATVRA</h1>',
    '<p><small>Lucretius, all six books, set in ML by a Latin teacher who learnt the',
    'language one winter to have something to do in the evenings. it runs. it is',
    'long. the Latin is his and the English is mine.</small></p>',
    '<hr>',
    '<p>The verse is in the comments, in my own plain English with the Latin',
    'where I could not leave it out. The program is in the rest. It wants a',
    'machine that runs ML; it was written on a NostBook and runs there.</p>',
    '<p><a href="pagefile:de_rerum_natura.ml">de_rerum_natura.ml</a> &middot; save it,',
    'then <code>ml download/de_rerum_natura.ml</code></p>',
    '<pre data-file="de_rerum_natura.ml">' + escDrn(DRN_ML) + '</pre>',
    '<hr>',
    '<p><small>for the sixth form &middot; see also the Thursday notes on',
    '<a href="epicurus.geocities.ws">Epicurus</a> &middot; last updated 1 Mar</small></p>',
  ]);

export const PHIL_A = [HERACLITUS, PARMENIDES, SOCRATES, PLATO, ARISTOTLE, EPICURUS, DRN];
