// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// DUB &amp; REGGAE: THE MIXING DESK AS INSTRUMENT.
//
// Three pages kept by people who chase the version, not the vocal. A
// sound-system veteran who stood in front of the speaker boxes in Waterhouse; a
// crate-digger who treats the Black Ark like a lost civilisation; a melodica
// devotee who plays every Far East record until the family complains. What binds
// them is a claim about the machine: in Jamaica the mixing board stopped being
// where you tidied a recording and became the thing you played, live, with your
// hands, dropping the drum and bass in and out, slamming the reverb tank,
// feeding the echo back on itself. The facts under the enthusiasm are real. The
// remix, as all three keep insisting to each other across the ring, begins here.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- King Tubby: the sound-system veteran ------------------------------------

const KING_TUBBY = P('king-tubby.geocities.ws', 'KING TUBBY',
  'KING TUBBY — the man at the controls', [
    '<!--bg:dub-->',
    '<h1>KING TUBBY &#9835; at the controls</h1>',
    '<p><small>kept by a man who stood in front of the boxes at the Waterhouse',
    'dances and never got the ringing out of his ears. maintained since 8 Feb.',
    '“best played LOUD, the way it was cut.”</small></p>',
    '<hr>',
    '<p>His name was Osbourne Ruddock and he fixed radios and wound transformers',
    'in Kingston before he ran a sound system, Tubby&#8217;s Home Town Hi-Fi. That',
    'is the order that matters. The man was an <b>electronics engineer</b> first,',
    'and dub is what happens when an engineer stops serving the song and starts',
    'playing the equipment.</p>',
    '<p>Here is what he actually did, because people romance it and get it wrong.',
    'He took the multitrack tape of a finished tune and mixed it AGAIN, live, at',
    'the board. He pulled the vocal clean off. He dropped the drum and bass in and',
    'out so the rhythm keeps falling away under you and slamming back. He rode the',
    'faders like a keyboard. He ran the whole thing through <b>spring reverb</b> so',
    'the snare would explode and hang, and through a <b>tape echo</b> unit that he',
    'would feed back on itself till it howled. There is a famous move where he',
    'thumps the reverb tank so it crashes like thunder. The desk is the',
    'instrument. He is performing.</p>',
    '<p>The board itself was a home-made thing, an old broadcast mixer he rebuilt,',
    'with a high-pass filter he wired in so he could sweep the bass away and bring',
    'it back like a wave. None of it was designed for this. He made it do this.</p>',
    '<hr>',
    '<p><b>THE DUBPLATE.</b> Understand the dubplate and you understand the whole',
    'economy. A dubplate is a one-off acetate cut for a single sound system, an',
    'exclusive, a version nobody else has. Tubby cut specials so his sound had',
    'weapons no rival could answer at the dance. That is the point of origin. A',
    'recording that exists to be unique, to be played out once and murder the',
    'competition, is already a different idea of music from the record you buy in',
    'a shop.</p>',
    '<p>He worked the vocal cuts of other producers&#8217; tunes, which is why you',
    'have to follow the ring to <a href="lee-scratch-perry-black-ark.geocities.ws">',
    'Lee Perry and the Black Ark</a> and to <a href="augustus-pablo.geocities.ws">',
    'Augustus Pablo</a>. Tubby did not make the songs. He UNMADE them, and the',
    'unmaking is the art. Pablo brought him the melodica rhythms and Tubby',
    'versioned them. Perry sent tapes across town. Dub is a conversation between',
    'the man who builds the track and the man at the desk who takes it apart.</p>',
    '<p>My one argument with the Pablo people: they credit Pablo with',
    '&#8220;King Tubbys Meets Rockers Uptown&#8221; (1976) as if it is a Pablo',
    'album, and it is a great record, but the reason it is a landmark is the mix.',
    'The title tells you whose room it is. It is Tubby&#8217;s uptown, at the',
    'controls.</p>',
    '<hr>',
    '<p>They shot him dead outside his house in 1989. Robbery, they said. By then',
    'half his apprentices had gone on to run Jamaica, Scientist and Prince Jammy',
    'and the rest, all trained at his board. Every producer who has ever pulled a',
    'vocal out to make a version, every remix on a twelve inch, every dance record',
    'that is really just the drum and the bass and a ghost of the tune, is working',
    'in a form this radio repairman invented in a little room in Waterhouse.</p>',
    '<p>People say sampling started the remix. It did not. The remix started here,',
    'with a man and a set of faders, deciding the recording was raw material.</p>',
    '<hr>',
    '<p><small>Rings: <a href="dub-ring.geocities.ws">&#171; The Dub Ring &#187;</a>',
    ' &middot; <a href="studio-as-instrument-ring.geocities.ws">&#171; The Studio as',
    ' Instrument &#187;</a></small></p>',
    '<p><small><a href="techsociety-webring.geocities.ws">&#171; Technology &amp;',
    ' Society Webring &#187;</a></small></p>',
    '<!-- also see the versions cut by Scientist and Prince Jammy, Tubby men both -->',
  ]);

// ---- Lee Scratch Perry / the Black Ark: the crate-digger obsessive -----------

const BLACK_ARK = P('lee-scratch-perry-black-ark.geocities.ws', 'BLACK ARK',
  'The Black Ark — what a 4-track can do', [
    '<!--bg:dub-->',
    '<h1>THE BLACK ARK</h1>',
    '<p><small>a page by someone who has spent too much rent money chasing',
    'original Black Ark pressings. corrections welcome, lies are not. updated',
    '19 Jan.</small></p>',
    '<hr>',
    '<p>Everybody quotes the mad-genius stuff first, the smoke and the buried mics,',
    'so let me get it out of the way and then tell you why it is not the point.',
    'Lee &#8220;Scratch&#8221; Perry built a studio behind his house in Washington',
    'Gardens, Kingston, and called it the <b>Black Ark</b>. Yes he blew ganja',
    'smoke onto the tapes. Yes he is said to have buried a microphone under a palm',
    'tree to get a particular thud, and sprayed things with blood and whisky, and',
    'painted the walls with symbols. All apparently true. All beside the point.</p>',
    '<p>Here is the point, and it is a <b>materiality</b> point. The Black Ark was',
    'built around a <b>TEAC 4-track</b> reel-to-reel. FOUR tracks. A little',
    'semi-pro machine you could put in a bedroom. Out of that four-track came',
    'records that sound like they have twenty things happening at once, oceans of',
    'depth, a swamp you can fall into. How? By <b>bouncing</b>. You fill the four',
    'tracks, mix them down to one or two, free up the others, pile more on, and',
    'every bounce is another layer of tape hiss and saturation and the sound of',
    'the machine straining. The murk is not a limitation he suffered. It is the',
    'sound. He made a small machine hallucinate that it was an orchestra.</p>',
    '<p>And like <a href="king-tubby.geocities.ws">Tubby</a> he mixed with his',
    'whole body. Spring reverb everywhere, tape delay fed back, the faders worked',
    'live so instruments surface and drown. Tubby&#8217;s dub is clean and violent,',
    'space and shock. Perry&#8217;s is the opposite texture, wet, overgrown,',
    'everything smeared into everything. Two answers to the same question: what is',
    'the mixing desk FOR. Both answer, it is an instrument. That is why I keep',
    'sending people down the ring between them.</p>',
    '<hr>',
    '<p><b>THE RECORDS.</b> The one to own, if the gods let you, is the Congos&#8217;',
    '<i>Heart of the Congos</i> (1977). Cedric Myton&#8217;s falsetto floating over',
    'that thick Ark bottom-end, cattle lowing somewhere in the mix. Perry produced',
    'it and it is the studio at its absolute peak. Then <i>Super Ape</i> (1976),',
    'credited to the Upsetters, which is Perry in full dub-architect mode. If you',
    'only know him from the singles he cut with Bob Marley and the Wailers in the',
    'early seventies, go deeper. The Ark years are where he becomes a composer of',
    '<i>sound</i> rather than songs.</p>',
    '<p>Around 1979 he burned the Black Ark down. Or it burned. Accounts differ and',
    'he told it different ways himself. Either way the room that made those records',
    'was gone, and nothing he cut afterward in anyone else&#8217;s clean studio',
    'ever sounded the same, which tells you the room was part of the instrument',
    'too.</p>',
    '<p>For the melodica end of this world, and another regular at Tubby&#8217;s',
    'board, see <a href="augustus-pablo.geocities.ws">Augustus Pablo</a>. Different',
    'temperament, same conviction: the record is not finished when the take is',
    'finished. That is where the version, and everything downstream of it, begins.</p>',
    '<hr>',
    '<p><small>discography note: original Ark pressings often have hand-scratched',
    'run-out matrices and no two labels agree. do not trust a clean reissue to tell',
    'you what the tape actually sounded like in that room.</small></p>',
    '<hr>',
    '<p><small>Rings: <a href="dub-ring.geocities.ws">&#171; The Dub Ring &#187;</a>',
    ' &middot; <a href="studio-as-instrument-ring.geocities.ws">&#171; The Studio as',
    ' Instrument &#187;</a></small></p>',
    '<p><small><a href="techsociety-webring.geocities.ws">&#171; Technology &amp;',
    ' Society Webring &#187;</a></small></p>',
  ]);

// ---- Augustus Pablo: the melodica devotee ------------------------------------

const AUGUSTUS_PABLO = P('augustus-pablo.geocities.ws', 'AUGUSTUS PABLO',
  'Augustus Pablo &amp; the Far East sound', [
    '<!--bg:dub-->',
    '<h1>Augustus Pablo &#9835; the Far East sound</h1>',
    '<p><small>maintained by someone who has played the melodica badly for eleven',
    'years and will not stop. this page is a love letter, be warned. last touched',
    '3 Feb.</small></p>',
    '<hr>',
    '<p>His name was Horace Swaby and his instrument was a <b>melodica</b> &#8212;',
    'a plastic toy, a mouth-organ with a little keyboard, the thing they hand',
    'children in primary school. Nobody had made it a lead instrument. He picked',
    'one up in a music shop, and out of that reedy, breathy, slightly out-of-tune',
    'toy he built a whole world of sound he called <b>Far East</b>: minor-key,',
    'meditative, more like something heard from a hillside than a dancehall.</p>',
    '<p>I love this because it is the melodica that makes the case. A cheap object',
    'nobody respects, played with total seriousness, becomes unmistakable. You',
    'know a Pablo record in two bars. The material humility of the thing is the',
    'whole charm. He did the same to the studio that the sound-system men did to',
    'the mixing desk: took the equipment everyone underrated and treated it as an',
    'instrument worthy of a lifetime.</p>',
    '<hr>',
    '<p><b>THE RECORD.</b> <i>King Tubbys Meets Rockers Uptown</i> (1976). If you',
    'own one dub album, own this one. Pablo built the rhythms, on his Rockers',
    'productions, and <a href="king-tubby.geocities.ws">King Tubby</a> mixed them',
    'to pieces at his board in Waterhouse &#8212; dropping the drum and bass out',
    'from under the melodica, drowning the whole thing in reverb, riding the',
    'faders so the tune keeps disappearing and coming back. The melodica sounds',
    'lonelier for all that space around it. The title track is one of the great',
    'recordings, dub or otherwise, and it is a duet: the man who plays the toy and',
    'the man who plays the desk.</p>',
    '<p>Before that, <i>This Is Augustus Pablo</i> (1974) collects the early Far',
    'East sides and shows the sound arriving fully formed. But <i>Rockers Uptown</i>',
    'is where the two halves of this little corner of the ring meet on one slab of',
    'vinyl, which is why I send everyone there.</p>',
    '<hr>',
    '<p>A word on the neighbours. The <a href="lee-scratch-perry-black-ark.geocities.ws">',
    'Black Ark</a> people and I agree on the important thing and argue about',
    'everything else. Perry&#8217;s records are dense, humid, overgrown; you sink',
    'into them. Pablo&#8217;s are spare and cold and clear, all air and distance.',
    'One fills the room, the other empties it. Both decided the recording is raw',
    'material to be worked after the fact. If you want the engineer&#8217;s side of',
    'that argument, follow the ring to Tubby, whose desk turned Horace',
    'Swaby&#8217;s toy into a landmark.</p>',
    '<p>He was shot and survived it once, and died of illness in 1999, still young.',
    'The Far East sound has no real successor because nobody else heard a melodica',
    'the way he did. That is the whole reason to keep this page up.</p>',
    '<hr>',
    '<p><small>Rings: <a href="dub-ring.geocities.ws">&#171; The Dub Ring &#187;</a>',
    ' &middot; <a href="studio-as-instrument-ring.geocities.ws">&#171; The Studio as',
    ' Instrument &#187;</a></small></p>',
    '<p><small><a href="techsociety-webring.geocities.ws">&#171; Technology &amp;',
    ' Society Webring &#187;</a></small></p>',
    '<p><small>best viewed at 800x600. melodica in D, if you were going to ask.',
    '</small></p>',
  ]);

export const MUSIC_E = [KING_TUBBY, BLACK_ARK, AUGUSTUS_PABLO];
