// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH H — the reception, the quarrels, the 1960s.
//
// Fan pages, kept on a free host, each ABOUT a Frankfurt School figure or
// episode and never in that figure’s own voice. A devotee’s shrine to Marcuse
// and his Freud; a write-up of a talk on Angela Davis’s Frankfurt years, with
// an aside and a row about patience; an account of the 1969 clash between
// Adorno and his own students; a sober summary of the positivism dispute; and
// a student’s messy where-to-start guide with a bibliography that never quite
// settles. The authors, titles and dates are real; the fandom and the grudges
// are the fans’.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Marcuse: the devotee’s shrine to Eros ----------------------------------

const MARCUSE_EROS = P('marcuse-eros.geocities.ws', 'MARCUSE / EROS',
  'EROS AND CIVILIZATION // the Freud the New Left actually read', [
    '<!--bg:exile-->',
    '<img class="indie-pic" src="assets/media/web/fs/marcuse-01.jpg" alt=""><span class="indie-cap">Herbert Marcuse, 1955 (photo: Marcuse family, CC BY-SA)</span>',
    '<h1>EROS AND CIVILIZATION</h1>',
    '<p class="fs-epi">“Under the rule of the performance principle, body and',
    'mind are made into instruments of alienated labor.” — Herbert Marcuse</p>',
    '<p><small>a shrine to Herbert Marcuse, kept by someone who read this book on',
    'a night shift and could not sleep after. i am not a philosopher. i just',
    'think he was right and hardly anyone says so any more. — R.</small></p>',
    '<hr>',
    '<p>Everyone reaches for the angry late Marcuse, the one who says the whole',
    'society has gone flat. That is the other book, <i>One-Dimensional Man</i>,',
    'and it has its own shrine over at <a href="one-dimensional.geocities.ws">',
    'one-dimensional</a>. Go there for the diagnosis. Come HERE for the cure, or',
    'at least for the argument that a cure is thinkable at all.</p>',
    '<p><i>Eros and Civilization</i> (1955) is Marcuse reading Freud AGAINST the',
    'grain and coming out hopeful, which nobody expected. Freud said civilisation',
    'costs us our instincts: to live together and work, we repress the drives, and',
    'that repression is the price of the whole thing and there is no refund.',
    'Marcuse takes the bargain seriously and then asks a sharp question of it.</p>',
    '<h2>The bit that changed my mind</h2>',
    '<p>How much of the repression is really needed for civilisation, and how much',
    'is just needed for THIS civilisation, the one built on scarcity and command',
    'and getting people to work jobs they hate? Marcuse splits them. There is',
    'basic repression, the minimum any shared life would ask. And then there is',
    'what he calls SURPLUS REPRESSION, the extra load piled on to keep a',
    'particular order of domination running. The surplus is not nature. It is',
    'history, and history can be undone.</p>',
    '<p class="fs-pull">The chains are real. Some of them are also optional.</p>',
    '<p>The engine of the surplus he names the PERFORMANCE PRINCIPLE: Freud’s',
    'reality principle in its modern, competitive, clock-punching form, the one',
    'that turns the body into a tool for labour and reserves pleasure for the',
    'leftover hours. Lift the performance principle, and you do not get chaos. You',
    'get the chance of what he calls NON-REPRESSIVE SUBLIMATION, work and culture',
    'that run on Eros instead of against it, play that is not the opposite of',
    'seriousness. A liberated society would not abolish reason. It would stop',
    'making reason the jailer.</p>',
    '<blockquote class="fs-quote"><p>“the Great Refusal”</p></blockquote>',
    '<p>His phrase for the No that art and desire keep saying to the given world,',
    'the refusal to accept that what is, is all there could be. The New Left took',
    'it off the page and into the street. Of all the Institut, Marcuse is the one',
    'the movement actually read, carried, argued over. The others were admired at a',
    'distance. He got quoted on placards.</p>',
    '<hr>',
    '<h2>Controversy</h2>',
    '<p>He did not win this Freud for free. Erich Fromm had spent years softening',
    'psychoanalysis into something warmer and more social, playing down the drives,',
    'the death instinct, the whole biological machinery. Marcuse went at him hard.',
    'His charge was that the friendly, revisionist Freud gave up exactly the part',
    'that had teeth, the theory of the instincts, and without the teeth you lose',
    'the measure of how much this order costs us. Keep the pessimism, Marcuse said,',
    'because only the dark Freud can show you the size of the possible liberation.',
    'The row ran cold for years and never really thawed.</p>',
    '<hr>',
    '<p><b>Neighbours worth a visit.</b> Read the darker companion at',
    '<a href="one-dimensional.geocities.ws">one-dimensional</a>, where the refusal',
    'has gone quiet and the society has closed over. And if you want to see what',
    'happened when a student took the Great Refusal literally and walked out of the',
    'seminar into a movement, there is a whole page on Angela Davis at',
    '<a href="angela-davis-frankfurt.geocities.ws">angela-davis-frankfurt</a>.</p>',
    '<p>&nbsp;</p>',
    '<p><small>visitors: 00612 · best viewed at 800x600 · this corner is STILL under',
    'construction, i keep finding better passages · last updated 22 Mar</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Angela Davis: the talk write-up (SHOWPIECE) ----------------------------

const ANGELA_DAVIS = P('angela-davis-frankfurt.geocities.ws', 'A. DAVIS / FRANKFURT',
  'I went to hear a talk on Angela Davis’s Frankfurt years', [
    '<!--bg:exile-->',
    '<img class="indie-pic" src="assets/media/web/fs/davis-01.jpg" alt=""><span class="indie-cap">Angela Davis (photo: Bernard Gotfryd, public domain)</span>',
    '<h1>ANGELA DAVIS IN FRANKFURT</h1>',
    '<p><small>notes i typed up after a public lecture at the university last week,',
    '“The Frankfurt School Goes to California and Comes Back Political”. the room',
    'was full, people sitting on the steps. i have tidied my scribbles but the',
    'mistakes are mine, not the speaker’s. — posted by len</small></p>',
    '<hr>',
    '<p>The speaker started with a fact that made half the room sit up. Before she',
    'was the woman on the poster, before the trial and the prison writing, Angela',
    'Davis was a philosophy student, and her teachers were the Frankfurt School.',
    'Not at a distance, not from books alone. In person, in seminars, on two',
    'continents.</p>',
    '<h2>The route</h2>',
    '<p>She found Marcuse first, at Brandeis, and he became the teacher who mattered',
    'most to her. Then, on his advice, she went to the source. From 1965 to 1967',
    'she studied in Frankfurt, in the seminars of Adorno and the rest of the',
    'Institut circle, reading Kant and Hegel and Marx in the German the way they',
    'read it. Then home to California, and graduate work with Marcuse again at San',
    'Diego. So she had the whole line: the exile generation in Frankfurt, and its',
    'most political member on the American coast.</p>',
    '<div class="fs-aside"><p>An aside the speaker made and then let sit. Picture',
    'the seminar room in Frankfurt in 1966. Adorno at the front, the most refined',
    'critical mind in Europe, taking apart a sentence of Hegel’s for an hour. And',
    'in the seats, a young American who is reading the newspapers from home, where',
    'cities are burning and people her age are being beaten on bridges. The theory',
    'was true. It was also very far from the street. She felt both at once, the',
    'speaker said, the truth of the theory and the distance of the street.</p></div>',
    '<p>Because at some point the news from home stopped being background. The',
    'movement was happening NOW, and she wanted to be in it, not writing about it',
    'from a seminar in another country. So she made the decision the talk was',
    'really about. She came back, and she gave herself to the Black liberation',
    'movement, the work of it, the organising and the risk.</p>',
    '<img class="indie-pic" src="assets/media/web/fs/protest-01.jpg" alt=""><span class="indie-cap">1968 (photo: Ludwig Binder, Haus der Geschichte, CC BY-SA)</span>',
    '<h2>Controversy</h2>',
    '<p>Here is where the room got quiet, because the speaker did not make it a',
    'simple hero story. When Davis told her Frankfurt teachers that she wanted to',
    'leave the seminar and throw herself into the movement, the response she',
    'remembers, above all from Adorno, was to counsel patience. The theory needed',
    'her. The moment was not ripe. There was a suggestion, as she tells it, that a',
    'scholar plunging straight into activism was a little like a trained thinker',
    'deciding to go and work as a technician, using a fraction of what she knew.</p>',
    '<p class="fs-pull">Adorno counselled patience. She had run out of it.</p>',
    '<p>Marcuse, the speaker was careful to say, was different, closer to her, more',
    'willing to follow the argument out of the room and into the world. But the',
    'Adorno moment is the one that stings, and the one people remember, because it',
    'shows the exile generation at the limit of its own courage. They had theorised',
    'refusal for thirty years. When a student went to actually refuse, in her body,',
    'in her country, the counsel was to wait. The speaker did not gloat about this.',
    'She reported it plainly and moved on to the next slide.</p>',
    '<hr>',
    '<p>What Davis carried out of Frankfurt, the talk argued, was not the patience.',
    'It was the method. The habit of grasping a whole system rather than a single',
    'grievance, of reading the prison and the market and the culture as one',
    'structure. That is the Frankfurt inheritance, turned from contemplation into',
    'organising. Their theory got an American political afterlife it had not quite',
    'dared to want.</p>',
    '<p>In the questions afterward someone asked whether the teachers were simply',
    'wrong to counsel patience. The speaker would not settle it. She said the whole',
    'quarrel between thinking and acting lives inside that one exchange, and that',
    'the school has been arguing with itself about it ever since. If you want the',
    'seminar side of that same fight, on home ground, go and read what happened',
    'when Adorno’s OWN students lost patience two years later, over at',
    '<a href="adorno-and-the-students.geocities.ws">adorno-and-the-students</a>.',
    'And if you want the theory of refusal she carried out the door, it is at',
    '<a href="marcuse-eros.geocities.ws">marcuse-eros</a>.</p>',
    '<p>&nbsp;</p>',
    '<p><small>counter: 01488 · best viewed at 800x600 · these are MY notes, quote',
    'the speaker not me · guestbook is open · page put up 4 May</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Adorno and the students, 1969: the account of the clash ----------------

const ADORNO_STUDENTS = P('adorno-and-the-students.geocities.ws', 'ADORNO / 1969',
  'ADORNO AND THE STUDENTS, 1969 — how it actually went', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/protest-02.jpg" alt=""><span class="indie-cap">West Berlin students, 1968 (photo: Ludwig Binder, Haus der Geschichte, CC BY-SA)</span>',
    '<h1>ADORNO AND THE STUDENTS, 1969</h1>',
    '<p><small>i sat in on a seminar session where a lecturer walked us through the',
    'last year of Adorno’s life, the year it all came apart with his own students.',
    'this is my write-up of what she laid out. it is not a comfortable story and',
    'she did not make it one. — typed up by C.</small></p>',
    '<hr>',
    '<p>Set the scene. By 1969 the German student movement, the SDS, had read its',
    'way through the Frankfurt School and taken it at its word. If the whole',
    'society was a false one, if reason had become mere administration, then what',
    'was there to do but ACT. And the theorists who had taught them to think that',
    'were right there in Frankfurt, running an institute. The students turned to',
    'the teachers and said, in effect: you showed us the trap, now help us break',
    'it. And the teachers, Adorno above all, would not go where the students wanted',
    'to go.</p>',
    '<h2>The occupation</h2>',
    '<p>It came to a head at the Institut for Social Research itself. Students',
    'occupied the building. For Adorno this was close to unbearable, because the',
    'Institut was not an abstraction to him, it was the thing that had survived',
    'exile and come home, the fragile place where the work happened. He wanted the',
    'theory radical and the seminar room orderly, and the students no longer',
    'believed you could have both.</p>',
    '<h2>The Busenaktion</h2>',
    '<p>Then the famous scene, in a lecture. A group of students, in what became',
    'known as the “Busenaktion”, interrupted Adorno at the lectern, some of them',
    'baring their breasts, showering him with flower petals, mocking the old man’s',
    'decorum to his face. It was theatre, and it was cruel, and it was aimed',
    'exactly at the gap between his sublime prose and his very proper person. He',
    'left the hall. The image went round the world and has followed his name ever',
    'since.</p>',
    '<hr>',
    '<h2>Controversy</h2>',
    '<p>Here is the part that still divides people, and the lecturer did not spare',
    'him. Faced with the occupation, Adorno called the police. On his own',
    'students. The man who had written the century’s deepest indictment of the',
    'administered world, of the state that manages and contains, picked up the',
    'telephone and asked the administered world to come and clear his building. To',
    'the students it was the ultimate betrayal, proof that the radical theory had a',
    'timid liberal underneath. To Adorno it was the defence of the one small space',
    'where thinking could still happen. Both readings had hold of something real.</p>',
    '<p>He tried to explain himself, most sharply in a line that has become the',
    'motto of the whole disaster:</p>',
    '<blockquote class="fs-quote"><p>“I established a theoretical model of thought.',
    'But how could I have suspected that people would want to realise it with',
    'Molotov cocktails?” — Adorno</p></blockquote>',
    '<p>Read it slowly, because it is the fault line of critical theory in one',
    'sentence. He genuinely believed his work was a way of THINKING, a stubborn',
    'refusal to make peace with the false whole, and not a set of marching orders.',
    'The students heard a thinker who had taught them the house was on fire and',
    'then forbade them to run for the door. Whether theory owes action anything, or',
    'whether keeping the thought uncorrupted IS the action, is the argument he left',
    'unfinished.</p>',
    '<hr>',
    '<p>He did not get to finish it. Worn down by the year, Adorno went to',
    'Switzerland for the summer, and in August 1969 he died of a heart attack in',
    'the mountains. The students who had tormented him were, many of them,',
    'devastated. The quarrel had no ending, only a death in the middle of it.</p>',
    '<p>For the sublime prose that the flower petals were mocking, go and read the',
    'shrine to <a href="adorno-negative-dialectics.geocities.ws">',
    'adorno-negative-dialectics</a>. And for the other side of the fight, the',
    'teacher who was more willing to march, see',
    '<a href="marcuse-eros.geocities.ws">marcuse-eros</a>. Marcuse and Adorno wrote',
    'to each other about exactly this in 1969, two old friends on opposite sides of',
    'the barricade, and stayed friends.</p>',
    '<p>&nbsp;</p>',
    '<p><small>counter: 00969 · best viewed at 640x480 · under construction, i am',
    'still tracking down the dates · last updated 18 Aug</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The Positivism Dispute: the sober summary ------------------------------

const POSITIVISM_DISPUTE = P('the-positivism-dispute.geocities.ws', 'POSITIVISMUSSTREIT',
  'THE POSITIVISM DISPUTE // a plain summary', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/uni-frankfurt-01.jpg" alt=""><span class="indie-cap">Goethe University, Frankfurt (photo: Adam Jones, CC BY-SA)</span>',
    '<h1>THE POSITIVISM DISPUTE</h1>',
    '<p><small>a clean summary page, no fireworks, kept by a sociology tutor who',
    'got tired of pointing students at photocopies. corrections welcome, i want',
    'this to be reliable. — the tutor</small></p>',
    '<hr>',
    '<p>The Positivismusstreit, the “positivism dispute”, was a long argument about',
    'METHOD in the social sciences that ran through German thought from 1961',
    'onward. On one side, the critical theorists of the Frankfurt School, Theodor',
    'Adorno and, in the next round, the younger Jürgen Habermas. On the other, the',
    'critical rationalists, Karl Popper and, more combatively, Hans Albert. It',
    'began at a conference of the German Sociological Association and spilled into',
    'essays and replies for years.</p>',
    '<h2>What they were actually fighting about</h2>',
    '<p>Not whether to be rigorous. Both sides wanted rigour. The quarrel was over',
    'what rigour in the study of society could even mean.</p>',
    '<p>Popper’s position, roughly. Science, including social science, proceeds by',
    'proposing hypotheses and trying hard to refute them. You cannot verify a',
    'theory once and for all, you can only fail to falsify it so far. So the honest',
    'method is piecemeal: state a clear conjecture, test it against the facts, throw',
    'it out if it breaks. Grand claims about “society as a whole” are not testable',
    'and so are not knowledge. Keep it modest, keep it checkable, reform in small',
    'steps.</p>',
    '<p>Adorno’s answer. Society is not a heap of separate facts you can test one at',
    'a time, because the facts are already shaped by the whole they belong to. The',
    '“data” a positivist treats as neutral are products of a particular social',
    'order, and to take them at face value is quietly to endorse that order. Critical',
    'theory insists on grasping the TOTALITY, the system that makes the individual',
    'facts what they are, even though the totality is never a thing you can point at',
    'and measure. Method that refuses the whole ends up describing the surface and',
    'calling it the world.</p>',
    '<h2>Value-freedom</h2>',
    '<p>Under this sat the older question of value-freedom, inherited from Max',
    'Weber. Popper and Albert held that science should separate factual claims from',
    'value judgements as cleanly as it can. Adorno held that the separation is',
    'itself a value, and a convenient one, because a social science that brackets',
    'all judgement about whether the arrangement is just quietly accepts that it is.',
    'You cannot study a false society from nowhere. The choice is only whether your',
    'values are examined or hidden.</p>',
    '<hr>',
    '<h2>Controversy</h2>',
    '<p>Part of the heat came from the word “positivism” itself. Popper did not',
    'think he was a positivist at all. He had spent his career ATTACKING the',
    'logical positivists, and here were the Frankfurt people filing him under the',
    'very label he had fought. He found that maddening, and said so. From the',
    'critical-theory side the point was that critical rationalism still shared the',
    'deep habit it objected to, treating knowledge of society as the piecemeal',
    'testing of isolated claims, and that habit is what they meant by positivism in',
    'the broad sense. So a good deal of the dispute was two camps disagreeing about',
    'what the fight was even called.</p>',
    '<p>The second-generation phase belonged to Habermas, who turned the exchange',
    'toward the interests that guide knowledge and, later, toward language and',
    'communication as the ground a social science could stand on. That is a whole',
    'further story, and the beginnings of it sit on the page for',
    '<a href="habermas-public-sphere.geocities.ws">habermas-public-sphere</a>.</p>',
    '<hr>',
    '<p>Why it still matters. Every argument now about whether you can model a',
    'society, whether the numbers speak for themselves, whether a metric is neutral',
    'or already loaded, is this dispute again in new clothes. Adorno’s side is at',
    'its fullest in <a href="adorno-negative-dialectics.geocities.ws">',
    'adorno-negative-dialectics</a>, where the refusal of the false whole is worked',
    'out as a way of thinking and not just a slogan.</p>',
    '<p><small>visitors: 00337 · best viewed at 800x600 · last updated 9 Feb ·',
    'this page is stable, i am not adding graphics</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Reading the Frankfurt School: the student where-to-start ---------------

const READING_FS = P('reading-the-frankfurt-school.geocities.ws', 'WHERE TO START',
  'READING THE FRANKFURT SCHOOL // where to start (notes)', [
    '<!--bg:critical-->',
    '<img class="indie-pic" src="assets/media/web/fs/books-01.jpg" alt=""><span class="indie-cap">(photo: Furkan Akkurt, CC BY-SA)</span>',
    '<h1>READING THE FRANKFURT SCHOOL</h1>',
    '<p><small>for SOC-311, the annotated reading list i wish someone had handed ME',
    'in first year. handed in a bit late, sorry. everything here is stuff i',
    'actually read, or at least started. — bex, posted 3 October</small></p>',
    '<hr>',
    '<p>Okay. The Frankfurt School scares people off because there is SO much of it',
    'and it all seems to assume you have read the other bits first. You have not.',
    'Nobody has. Here is an order that worked for me, generation by generation, plus',
    'the two history books that hold the whole thing together.</p>',
    '<h2>First: get a map</h2>',
    '<p>Do not start with Adorno. Start with a history, so you know who is who.',
    'There are two big ones and you only need one to begin. Martin Jay, <i>The',
    'Dialectical Imagination</i> (1973), is the classic first history in English,',
    'warm and readable, takes you up to 1950. Rolf Wiggershaus, <i>The Frankfurt',
    'School</i> (1986), is the huge thorough one, more people, more detail, better',
    'if you want the whole cast. I read Jay first and Wiggershaus when i got',
    'obsessed.</p>',
    '<h2>Then: start here, then this</h2>',
    '<p><b>The first generation.</b> Begin with the short sharp one, Adorno’s',
    '<i>Minima Moralia</i> (1951), because it is aphorisms, so you can read three',
    'pages and stop and it still lands. THEN the hard famous one he wrote with',
    'Horkheimer, <i>Dialectic of Enlightenment</i> (drafted 1944, published 1947),',
    'which is where “myth is already enlightenment” comes from. For the theory',
    'behind all of it, Horkheimer’s essay “Traditional and Critical Theory”',
    '(1937). The place it all ran from is the institute itself, and there is a',
    'clear page on it at <a href="institut-fur-sozialforschung.geocities.ws">',
    'institut-fur-sozialforschung</a>.</p>',
    '<p><b>The exile.</b> None of this happened in a calm library. They were',
    'refugees. The best single page on what that did to the work, the New York',
    'years, the clash with American empirical research, the German colony in Los',
    'Angeles, is the talk write-up at',
    '<a href="exile-at-columbia.geocities.ws">exile-at-columbia</a>. Read it before',
    'the heavy books and they make more sense.</p>',
    '<p><b>The culture stuff</b>, which is really why most of us are here. The',
    'culture-industry argument, that mass culture is a factory turning out',
    'sameness and calling it choice, has its own page at',
    '<a href="cultureindustry.geocities.ws">cultureindustry</a>. Pair it with',
    'Marcuse for the politics, <i>Eros and Civilization</i> (1955) for the hope and',
    '<i>One-Dimensional Man</i> for the despair, the latter at',
    '<a href="one-dimensional.geocities.ws">one-dimensional</a>. And Walter',
    'Benjamin on art and reproduction is the one everyone half-knows, done properly',
    'at <a href="aura.geocities.ws">aura</a>.</p>',
    '<p><b>The second generation.</b> Habermas is the big turn, from despair to',
    'communication. Start with <i>The Structural Transformation of the Public',
    'Sphere</i> (1962), it is basically a history of the coffee house and it reads',
    'like one.</p>',
    '<div class="fs-aside"><p>Warning from experience. Do NOT open <i>Negative',
    'Dialectics</i> (1966) as your first Adorno. I did. I cried. Come back to it in',
    'third year when you have the muscles. Same goes for the <i>Aesthetic Theory</i>.',
    'They are worth it, just not FIRST.</p></div>',
    '<p><b>Where the school touches now.</b> If you want to see the whole tradition',
    'aimed at computers and data instead of radio and film, the useful bridge is',
    'David M. Berry, whose page is at',
    '<a href="the-philosophy-of-software.geocities.ws">the-philosophy-of-software</a>.',
    'He runs Adorno and Benjamin straight at the machine. Marx’s own note on',
    'machines, the one they all secretly build on, is at',
    '<a href="fragment-on-machines.geocities.ws">fragment-on-machines</a>, and for',
    'the later story about how systems come to steer us there is',
    '<a href="societies-of-control.geocities.ws">societies-of-control</a>.</p>',
    '<hr>',
    '<p><b>Bibliography</b> (the ones i actually used, roughly in the order i grabbed',
    'them off the shelf, my referencing is a work in progress):</p>',
    '<p><small>',
    'Adorno, T. W. <i>Minima Moralia</i>. 1951.<br>',
    'Horkheimer, Max and Adorno. <i>Dialectic of Enlightenment</i>. wrote it 1944,',
    'came out 1947.<br>',
    'Horkheimer, M., “Traditional and Critical Theory”, essay, 1937.<br>',
    'Adorno, <i>Negative Dialectics</i>, 1966 (do not start here, see above).<br>',
    'Marcuse, Herbert. <i>Eros and Civilization</i>, 1955.<br>',
    'Habermas, J. <i>The Structural Transformation of the Public Sphere</i> (1962).<br>',
    'JAY, Martin. <i>The Dialectical Imagination</i>. 1973. [the readable history]<br>',
    'Wiggershaus, Rolf, <i>The Frankfurt School</i>, 1986, the big one, 700-odd pages,',
    'i did not read all of it, be realistic about it.<br>',
    '(sorry the formatting is all over the place, i will fix it before the final',
    'version, prof said footnotes next time)</small></p>',
    '<hr>',
    '<p><small>counter: 02051 · best viewed at 800x600 · PERMANENTLY under',
    'construction, this list keeps growing · last updated 3 Oct · sign the',
    'guestbook if it helped</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const FS_H = [
  MARCUSE_EROS,
  ANGELA_DAVIS,
  ADORNO_STUDENTS,
  POSITIVISM_DISPUTE,
  READING_FS,
];
