// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// DES_B — interiors & decorating, the decorators from de Wolfe to Castaing.
//
// Cached pages an enthusiast made about the rooms she loved: a fan shrine to
// the first decorator; a collector cataloguing the all-white years; a write-up
// of an evening talk on baroque modern; an academic note on spare Parisian
// luxury; a student's wonky coursework on the 1960s; and a collector on the
// eccentric French antiquaire. The names, dates and pieces are real; the
// enthusiasms are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Elsie de Wolfe: the fan shrine (SHOWPIECE) -----------------------------

const DE_WOLFE = P('elsie-de-wolfe.geocities.ws', 'DE WOLFE',
  'ELSIE DE WOLFE — the first decorator', [
    '<!--bg:des-interiors-->',
    '<h1>ELSIE DE WOLFE</h1>',
    '<p><small>a shrine to the woman who invented the job. i keep this page',
    'because every glossy magazine that tells you to paint a dark room white and',
    'let the light in is quoting her and does not know it. i know it. — Prue</small></p>',
    '<p class="fs-epi">"I am going to make everything around me beautiful. That',
    'will be my life." — Elsie de Wolfe</p>',
    '<hr>',
    '<p>Before Elsie de Wolfe (1865 to 1950) there were upholsterers and there',
    'were architects and there was no such person as the interior decorator you',
    'could hire by name. She made the job up and then made it respectable. She',
    'had been an actress, known more for her frocks than her lines, and when the',
    'stage was done she turned the eye she had for a costume onto whole rooms.</p>',
    '<p class="fs-pull">She threw out the brown and let the light in.</p>',
    '<p>The Victorian interior she inherited was a dim and crowded thing: heavy',
    'plush, dark varnish, tassels on everything, a clutter of ornament that hid',
    'the room inside it. De Wolfe cleared it out. Light walls, chintz, plenty of',
    'mirror to bounce what daylight there was, painted furniture, comfortable',
    'chairs you could actually sit in. It reads as obvious now, which is the mark',
    'of how completely she won.</p>',
    '<img class="indie-pic" src="assets/media/web/des/dewolfe-01.jpg" alt=""><span class="indie-cap">Elsie de Wolfe (Bain News Service, public domain)</span>',
    '<p><b>The Colony Club</b></p>',
    '<p>Her first real commission, around 1905, was the Colony Club in New York,',
    'the first social club for women in the city, and the architect Stanford',
    'White handed her the inside of it. She gave it trellis and light and glazed',
    'chintz, garden-room ease indoors, nothing like the panelled gloom of a',
    'gentlemen’s club. It made her name overnight and the commissions',
    'followed.</p>',
    '<blockquote class="fs-quote"><p>"It is the personality of the mistress that',
    'the home expresses. Men are forever guests in our homes, no matter how much',
    'happiness they may find there." — Elsie de Wolfe, <i>The House in Good',
    'Taste</i></p></blockquote>',
    '<p><b>The House in Good Taste (1913)</b></p>',
    '<p>The book made her a movement. Part manifesto, part manual, it told the',
    'ordinary reader that good taste could be learned and that the first rules',
    'were suitability, simplicity and proportion. Much of the actual prose was',
    'ghosted by a magazine writer, Ruby Ross Goodnow, who went on to be a fine',
    'decorator in her own right under the name Ruby Ross Wood, but the eye and',
    'the argument are de Wolfe’s throughout.</p>',
    '<div class="fs-aside"><p><b>A note on glazed chintz.</b> Chintz is a printed',
    'and glazed cotton, the glaze a starch or wax finish that gives it that faint',
    'sheen and helps it shed dust. De Wolfe loved it for exactly the reasons the',
    'heavy decorators distrusted it: it was light, it was cheap enough to renew,',
    'and the flowers on it brought a garden into a dark town room. Her fondness',
    'for it earned her the nickname the Chintz Lady.</p></div>',
    '<pre>',
    'A DE WOLFE ROOM, THE PARTS OF IT',
    '  walls .......... pale, painted, often off-white or grey',
    '  light .......... maximised; mirror set to double the windows',
    '  textile ........ glazed chintz, plenty of it, renewed often',
    '  furniture ...... eighteenth-century French, or painted to suit',
    '  floor .......... light rugs, nothing muddy underfoot',
    '  clutter ........ banished; every object made to earn its place',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/des/maugham-01.jpg" alt=""><span class="indie-cap">Syrie Maugham (Wellcome, CC BY 4.0)</span>',
    '<p>She lived the part. With Elisabeth Marbury she kept a famous salon, first',
    'in New York and then at the Villa Trianon at Versailles, and she was one of',
    'the first women photographed with a face lift and blue-rinsed hair, forever',
    'exercising and standing on her head into old age. The persona was part of',
    'the product. If you were buying taste, it helped to buy it from someone who',
    'so plainly had it.</p>',
    '<p>Why she matters, now the rooms are quiet and we are all deciding again',
    'what to keep and what to clear out: she was the one who said a room is for',
    'the person who lives in it, that comfort and light are not the enemies of',
    'beauty but its condition. Two who carried the argument on are worth a visit,',
    'Syrie Maugham at <a href="syrie-maugham.geocities.ws">syrie-maugham</a>, who',
    'took the light walls all the way to white, and Dorothy Draper at',
    '<a href="dorothy-draper.geocities.ws">dorothy-draper</a>, who kept the',
    'boldness and threw the good taste happily out of the window.</p>',
    '<hr>',
    '<p><small>counter: 03318 · best viewed at 800x600 · this page is under',
    'construction, more photographs when i can scan them · last updated 24 Mar',
    '</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Syrie Maugham: the collector's page ------------------------------------

const MAUGHAM = P('syrie-maugham.geocities.ws', 'MAUGHAM',
  'Syrie Maugham // the all-white room (a collector’s notes)', [
    '<!--bg:des-interiors-->',
    '<h1>Syrie Maugham</h1>',
    '<p><small>catalogue notes kept by a collector of 1930s interiors. prices',
    'where i have them, condition where it matters, and a standing want-list at',
    'the foot. corrections welcome.</small></p>',
    '<hr>',
    '<p>Syrie Maugham (1879 to 1955) gave the 1930s its most famous single room',
    'and one of the most copied interiors of the century. She was the daughter of',
    'Thomas Barnardo, the founder of the children’s homes, and for a time',
    'the wife of the writer Somerset Maugham, but the decorating was entirely her',
    'own doing and she built a business on both sides of the Atlantic on the',
    'strength of it.</p>',
    '<p><b>The all-white room</b></p>',
    '<p>The room the whole trade remembers is the white drawing room of her house',
    'in the King’s Road, Chelsea, unveiled about 1927 and endlessly',
    'photographed after. White walls, white satin and velvet, white lilies, a',
    'white sofa, beige and oyster and cream carpeting, mirror and shell and',
    'lightly bleached wood. It was not literally one colour, it was a whole scale',
    'of off-whites played against one another, and it looked like nothing else in',
    'London at the time.</p>',
    '<img class="indie-pic" src="assets/media/web/des/maugham-01.jpg" alt=""><span class="indie-cap">Syrie Maugham (Wellcome, CC BY 4.0)</span>',
    '<blockquote class="fs-quote"><p>"Colour comes and goes but white always',
    'remains." The line is passed around with her name on it; whether or not she',
    'said it exactly, the room argued it plainly enough.</p></blockquote>',
    '<p><b>Pickled and bleached furniture</b></p>',
    '<p>Her signature technique, and the one collectors hunt for, is the',
    '"pickled" finish. She would strip an old piece of oak or walnut back to the',
    'bare wood, then lime or bleach it so the grain went pale and chalky and the',
    'dark colour of the antique disappeared. A good Georgian commode, in her',
    'hands, came out looking like driftwood. Purists were appalled that she was',
    'stripping fine old patina off good brown furniture; her clients did not',
    'care, and neither, mostly, do I.</p>',
    '<div class="fs-aside"><p><b>A note on pickling.</b> To "pickle" wood is to',
    'lighten it without paint: the surface is stripped, then a white or grey wash,',
    'liming paste or bleach is worked into the open grain and wiped back, leaving',
    'the pale pigment in the pores while the wood still reads as wood. On oak,',
    'with its coarse grain, the effect is strongest. Beware modern fakes done in',
    'white emulsion; the real thing shows the grain, not a coat over it.</p></div>',
    '<p><b>The interiors, London and Le Touquet</b></p>',
    '<p>Beyond the Chelsea house there were the rooms at Le Touquet on the French',
    'coast and a long list of London commissions through the late 1920s and',
    '1930s. The look was consistent: stripped and painted surfaces, mirrored',
    'screens, plaster and shell motifs, a palette drained of strong colour so the',
    'shapes and the light did the work. She also dealt in furniture through her',
    'shop, so a piece with a Maugham provenance may have passed through her hands',
    'as stock rather than been made for her.</p>',
    '<img class="indie-pic" src="assets/media/web/des/frank-01.jpg" alt=""><span class="indie-cap">A Jean-Michel Frank club chair (photo: Tim Evanson, CC BY-SA 2.0)</span>',
    '<pre>',
    'STANDING WANT-LIST',
    '  - pickled oak side table, limed grain, honest wear ..... seeking',
    '  - mirrored screen, three fold, 1930s .................. seeking',
    '  - plaster wall bracket, shell form, chalk-white ....... seeking',
    '  - documented Chelsea-period provenance ................ dreaming',
    '</pre>',
    '<p>Her line runs on either side. The spare Parisian rooms of Jean-Michel',
    'Frank at <a href="jean-michel-frank.geocities.ws">jean-michel-frank</a> share',
    'her taste for a drained palette and a fine plain surface, and behind them',
    'both stands the first decorator, Elsie de Wolfe at',
    '<a href="elsie-de-wolfe.geocities.ws">elsie-de-wolfe</a>, who had begun the',
    'business of clearing the colour out a generation before.</p>',
    '<hr>',
    '<p><small>hits: 01192 · best viewed at 800x600 · catalogue last revised 8 Feb',
    '</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Dorothy Draper: the talk write-up --------------------------------------

const DRAPER = P('dorothy-draper.geocities.ws', 'DRAPER',
  'Dorothy Draper: baroque modern (a talk, written up)', [
    '<!--bg:des-interiors-->',
    '<h1>Dorothy Draper, baroque modern</h1>',
    '<p><small>notes from an evening lecture at the decorative arts society,',
    'written up for the newsletter by a member who took too few notes and had too',
    'much of the wine. any errors are mine, not the speaker’s.</small></p>',
    '<hr>',
    '<p>The speaker began where you would expect, with the fact that Dorothy',
    'Draper (1889 to 1969) was the opposite of everything the good-taste',
    'decorators stood for, and proud of it. Where Syrie Maugham drained the',
    'colour out, Draper turned it all the way up. Her style, which she cheerfully',
    'called "modern baroque", was big, loud and theatrical: enormous cabbage-rose',
    'chintzes, plaster scrollwork, stark black-and-white chequerboard floors,',
    'shocking splashes of aubergine and turquoise, scale pushed past the point of',
    'good manners.</p>',
    '<p>She was, the speaker stressed, the first American to industrialise the',
    'trade. Draper ran a proper company, Dorothy Draper and Company, founded',
    'around 1925, and took on things no individual decorator had touched: whole',
    'hotels, restaurants, department stores, an aeroplane cabin, a car interior.',
    'She decorated the public’s daylight, not just its drawing rooms.</p>',
    '<img class="indie-pic" src="assets/media/web/des/draper-01.jpg" alt=""><span class="indie-cap">A Dorothy Draper interior at the Greenbrier (photo: Valereee, CC0)</span>',
    '<p><b>The Greenbrier</b></p>',
    '<p>The set-piece of the evening was the Greenbrier hotel in West Virginia,',
    'which Draper redid after the war, around 1946 and 1948. She let loose there:',
    'the famous cabbage-rose chintz, rooms in cabbage green and rhododendron red,',
    'the black-and-white marble floors, a romantic Southern extravagance on a',
    'scale that would have given a Parisian minimalist a seizure. The speaker',
    'showed a slide of the main corridor and let it sit there without comment,',
    'which was the right thing to do.</p>',
    '<blockquote class="fs-quote"><p>"I believe in doing the thing you feel is',
    'right. If it looks right, it is right." — Dorothy Draper, roughly, from',
    '<i>Decorating is Fun!</i></p></blockquote>',
    '<p><b>Decorating is Fun! (1939)</b></p>',
    '<p>Her book, the speaker said, is the anti-manual. Where the good-taste',
    'writers laid down laws, Draper told the ordinary reader to be brave, to use',
    'strong colour without fear, to stop being intimidated by the experts and',
    'enjoy herself. It democratised nerve rather than taste. She followed it with',
    'a syndicated column and became, for a while, the decorating voice most',
    'American women actually heard.</p>',
    '<p>In the questions afterwards someone asked whether the boldness was just',
    'vulgarity with confidence, and the speaker allowed that the line was thin and',
    'that Draper walked it on purpose. Big scale against good taste was the whole',
    'game, and she knew exactly which side she was playing for.</p>',
    '<p>The evening placed her between two others on this ring. Behind her, the',
    'first decorator, Elsie de Wolfe at',
    '<a href="elsie-de-wolfe.geocities.ws">elsie-de-wolfe</a>, from whom she took',
    'the boldness and dropped the restraint; and ahead of her the 1960s eye of',
    'David Hicks at <a href="david-hicks.geocities.ws">david-hicks</a>, who',
    'shared her nerve for a colour clash but drilled it into geometry.</p>',
    '<hr>',
    '<p><small>society newsletter · visitors 00648 · best viewed at 800x600 ·',
    'written up 15 Nov</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Jean-Michel Frank: the academic summary --------------------------------

const FRANK = P('jean-michel-frank.geocities.ws', 'FRANK',
  'Jean-Michel Frank // spare Parisian luxury', [
    '<!--bg:des-interiors-->',
    '<h1>Jean-Michel Frank</h1>',
    '<p><small>a summary page, written for a design-history reading group. sources',
    'at the foot as best i can give them.</small></p>',
    '<hr>',
    '<p>Jean-Michel Frank (1895 to 1941) practised a kind of luxury that looked,',
    'at first glance, like poverty. His Paris interiors of the late 1920s and',
    '1930s were nearly empty by the standards of the day: plain walls, a few large',
    'simple forms, almost no ornament, a palette of beige and ivory and pale grey.',
    'The trick, and the reason his clients were among the richest in Europe, was',
    'that the plainness was achieved with the most extravagant materials and the',
    'most exacting craft available.</p>',
    '<p><b>Spare, but never cheap</b></p>',
    '<p>A Frank wall might be panelled entirely in squares of parchment or vellum,',
    'or in straw marquetry, thousands of splints of dyed straw laid by hand to',
    'catch the light like watered silk. A table might be topped in shagreen, the',
    'rubbed skin of a ray or shark, or in mica, or in bronze. The forms were',
    'severe and the surfaces were priceless. This is the paradox that historians',
    'keep returning to: a reductive, almost monastic manner underwritten by',
    'boundless expense.</p>',
    '<div class="fs-aside"><p><b>A note on shagreen.</b> Shagreen is the tanned',
    'skin of a ray or a small shark, its surface a field of tiny round nodules',
    'that, ground flat and dyed (often the characteristic pale green), gives a',
    'granular sheen unlike any leather. Costly, laborious to work, and quietly',
    'unmistakable, it was one of Frank’s signatures and a marker of the',
    'French luxury trade between the wars.</p></div>',
    '<p><b>The Parsons table</b></p>',
    '<p>His best-known single object is not a rare material at all but a shape: a',
    'table with a square-section leg flush to the edge of a top of the same',
    'thickness, so that the whole thing reads as four planes and nothing else. It',
    'came out of his teaching connection with the Paris studio of the Parsons',
    'School of Design and carries that name to this day. It is about as close to',
    'a diagram of a table as a table can get, and it went on to be made in every',
    'material and every price bracket for the rest of the century.</p>',
    '<img class="indie-pic" src="assets/media/web/des/frank-01.jpg" alt=""><span class="indie-cap">A Jean-Michel Frank club chair (photo: Tim Evanson, CC BY-SA 2.0)</span>',
    '<p><b>The Noailles and the milieu</b></p>',
    '<p>His patrons were the Vicomte and Vicomtesse de Noailles, for whom he did',
    'the celebrated rooms on the Place des États-Unis, and his circle ran',
    'through the Paris avant-garde, including work alongside the Giacometti',
    'brothers, who made lamps and plaster objects for his interiors. He took his',
    'own life in New York in 1941, having fled the war. The label "minimal before',
    'minimalism" is often hung on him, and while it is anachronistic it points at',
    'something real: he arrived at reduction decades before it became a doctrine,',
    'and by an opposite route, through luxury rather than against it.</p>',
    '<p>Two neighbours on this ring set him off well. The eccentric, layered,',
    'colour-drunk rooms of Madeleine Castaing at',
    '<a href="madeleine-castaing.geocities.ws">madeleine-castaing</a> are his',
    'temperamental opposite and worked the same Paris; and the drained palette and',
    'stripped surfaces of Syrie Maugham at',
    '<a href="syrie-maugham.geocities.ws">syrie-maugham</a> reach for a similar',
    'quiet from the English side.</p>',
    '<hr>',
    '<p><small>reading-group page · counter 00507 · best viewed at 800x600 ·',
    'last updated 2 Apr</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- David Hicks: the student coursework ------------------------------------

const HICKS = P('david-hicks.geocities.ws', 'HICKS',
  'DAVID HICKS — geometry and the tablescape (coursework)', [
    '<!--bg:des-interiors-->',
    '<h1>David Hicks: geometry and the tablescape</h1>',
    '<p><small>coursework for DES2104 History of the Interior, semester two. word',
    'count 1,050. please do not mark me down for the hit counter, i like it. — Jo',
    'K.</small></p>',
    '<hr>',
    '<p>David Hicks (1929 to 1998) was the British decorator who defined the look',
    'of the 1960s and 70s smart interior. My argument in this essay is that his',
    'contribution was to take the bold colour of the earlier decorators and',
    'discipline it with geometry, so that where Dorothy Draper was baroque and',
    'loose, Hicks was bold and tight.</p>',
    '<p><b>1. The geometric carpet</b></p>',
    '<p>Hicks is best remembered for his carpets. He designed strong, small-scale',
    'geometric patterns, hexagons, octagons, interlocking shapes, often in unusual',
    'and clashing colours, and had them made up as fitted carpets and rugs. The',
    '"Hicks hexagon" became so widely copied that people forget it had an author.',
    'The point of the geometry, as I read it, was to give a busy pattern a rigid',
    'order, so the eye reads energy and control at the same time.</p>',
    '',
    '<p><b>2. The tablescape</b></p>',
    '<p>His other lasting word is "tablescape", which he coined for the composed',
    'arrangement of objects on a table top. Instead of scattering ornaments about',
    'a room, Hicks grouped them, obelisks, boxes, books, a plant, a piece of coral,',
    'objects of different heights and materials, into a deliberate still life to be',
    'looked at as a whole. He treated the table top as a small stage. I think this',
    'is his most useful idea for an ordinary room because it costs nothing and',
    'anyone can try it.</p>',
    '<blockquote class="fs-quote"><p>"I think the most important thing about',
    'decoration is that a room should be liveable." — David Hicks (quoted in his',
    '<i>Living with Design</i>, near enough)</p></blockquote>',
    '<p><b>3. The colour clash and the eye for scale</b></p>',
    '<p>Hicks was famous for putting colours together that were not supposed to',
    'go, aubergine with orange, scarlet with pink, and making them work through',
    'confidence and proportion. He had a sharp eye for scale, mixing a very large',
    'object with small ones, an antique with something modern, so that no room was',
    'ever bland. He married into the royal circle (his wife was Lady Pamela',
    'Mountbatten) which helped the fashionable commissions along, but the eye was',
    'real and was his own.</p>',
    '<pre>',
    'HOW TO BUILD A TABLESCAPE (from my notes)',
    '  1. pick one surface and clear it completely',
    '  2. vary the HEIGHTS: an obelisk, a low box, a stack of books',
    '  3. vary the MATERIAL: stone, lacquer, brass, a living plant',
    '  4. group tight; leave the rest of the table bare',
    '  5. look at it as a picture, not as objects',
    '</pre>',
    '<p><b>Conclusion</b></p>',
    '<p>Hicks connects backwards and forwards. He inherits the nerve for strong',
    'colour from Dorothy Draper at',
    '<a href="dorothy-draper.geocities.ws">dorothy-draper</a>, whose boldness he',
    'admired and tidied, and he sits alongside the layered, personal interiors of',
    'Madeleine Castaing at',
    '<a href="madeleine-castaing.geocities.ws">madeleine-castaing</a>, another',
    'decorator who made a room feel composed rather than decorated. For my next',
    'essay I want to look properly at the tablescape idea and whether it is really',
    'just a still life moved off the wall.</p>',
    '<p><b>Bibliography (as required)</b></p>',
    '<pre>',
    'Hicks, David. David Hicks on Decoration. 1966. (in the library, oversize)',
    'Hicks, David. Living with Design. 1979.',
    'lecture notes, DES2104 week 6, "the sixties interior"',
    'that documentary the tutor showed, name in my other file, sorry',
    '</pre>',
    '<hr>',
    '<p><small>hits: 00231 · best viewed at 800x600 · under construction (adding',
    'the pictures once i get the scanner working) · last updated 19 May · handle:',
    'jo_k</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Madeleine Castaing: the collector's page -------------------------------

const CASTAING = P('madeleine-castaing.geocities.ws', 'CASTAING',
  'Madeleine Castaing // the antiquaire of the rue Bonaparte', [
    '<!--bg:des-interiors-->',
    '<h1>Madeleine Castaing</h1>',
    '<p><small>a collector’s page for the most eccentric decorator France',
    'produced. i buy in her taste when i can afford it, which is not often. notes',
    'and provenance below.</small></p>',
    '<hr>',
    '<p>Madeleine Castaing (1894 to 1992) was an antique dealer and decorator who',
    'ran, for decades, a small crowded shop at the corner of the rue Bonaparte and',
    'the rue Jacob in Paris, and who built from it one of the most personal and',
    'imitated styles of the century. She sat in the window in a wig held on with a',
    'ribbon under the chin, refused to sell to people she did not like, and priced',
    'by mood. The trade adored and feared her.</p>',
    '<p><b>The look</b></p>',
    '<p>Her interiors were layered, romantic and slightly mad. She favoured a',
    'particular blue-green, an emerald or "Castaing green", used it on walls and',
    'woodwork, and set it against leopard-print carpet, small-scale wallpapers,',
    'ebonised Napoleon III furniture, buttoned upholstery, fringed lamps and',
    'plants. Nothing matched in the ordinary sense; everything was composed. She',
    'made a room feel as though it had grown, layer on layer, over a long and',
    'eccentric life, which in her own case it more or less had.</p>',
    '<div class="fs-aside"><p><b>A note on the leopard carpet.</b> The',
    'leopard-spotted stair and floor carpet is the Castaing signature most often',
    'copied. It was machine-woven wool, a printed or woven spot on a pale ground,',
    'and she ran it up staircases and across whole floors where a plainer decorator',
    'would have laid something quiet. Watch, on the market, for later reproductions;',
    'the period examples have a softer, less regular spot.</p></div>',
    '<p><b>Lèves and the personal interior</b></p>',
    '<p>Her country house at Lèves, near Chartres, was the fullest statement of the',
    'style and a place of pilgrimage for the decorators who came after. She had a',
    'long association with the painter Chaïm Soutine, whom she and her husband',
    'Marcellin championed and collected, and the mix of high art and shabby',
    'romantic comfort in her rooms owes something to that world. The interiors were',
    'never fashionable in the streamlined sense; they were personal, and that was',
    'the point of them.</p>',
    '<img class="indie-pic" src="assets/media/web/des/castaing-01.jpg" alt=""><span class="indie-cap">Madeleine Castaing, by Soutine (photo: Yair Haklai, CC BY-SA 4.0)</span>',
    '<pre>',
    'CASTAING, WHAT TO LOOK FOR',
    '  colour ......... the blue-green; leopard spot; small florals',
    '  furniture ...... ebonised Napoleon III, buttoned, fringed',
    '  provenance ..... anything from the rue Bonaparte shop, if papered',
    '  beware ......... bright modern leopard repros; regular machine spot',
    '</pre>',
    '<p>She worked the same Paris as the spare modernists and could not have been',
    'more different from them. For the opposite temperament, all reduction and fine',
    'plain surface, see Jean-Michel Frank at',
    '<a href="jean-michel-frank.geocities.ws">jean-michel-frank</a>; and for a',
    'later decorator who shared her instinct for a room composed rather than merely',
    'furnished, the geometric eye of David Hicks at',
    '<a href="david-hicks.geocities.ws">david-hicks</a>.</p>',
    '<hr>',
    '<p><small>hits: 00893 · best viewed at 800x600 · collection notes last revised',
    '11 Jan</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

export const DES_B = [DE_WOLFE, MAUGHAM, DRAPER, FRANK, HICKS, CASTAING];
