// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH H — the big questions.
//
// Reading-group pages, kept on a free host, each ABOUT a question rather than a
// single bot: whether machines think, the gendered party game hiding inside the
// Turing test, the loneliness market that grew up around the companions, and the
// other lineage of bots that never wanted to seem human at all. Notes made by
// people who met to read together and put the arguing online. The names, titles
// and dates are real; the readings and the quarrels are the groups' own.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Can machines think: the reading group ----------------------------------

const CANTHINK = P('can-machines-think.geocities.ws', 'CAN THINK?',
  'CAN MACHINES THINK? — a reading group', [
    '<!--bg:critique-->',
    '<h1>CAN MACHINES THINK?</h1>',
    '<p><small>notes from a small reading group that meets over coffee and stays',
    'too long. we have been circling this one question for a year now and we are',
    'not done. these are the notes from the last three sessions, tidied up. join',
    'us if you like an argument that does not resolve. — kept by R for the group</small></p>',
    '<hr>',
    '<p>We started where everyone starts, with Alan Turing asking the question in',
    '1950 and then refusing to answer it. His paper "Computing Machinery and',
    'Intelligence" opens by saying the question "can machines think?" is too vague',
    'to be worth much, because it turns on what you already mean by "machine" and',
    'by "think". So he put a test in its place, the imitation game, and asked a',
    'narrower question you could actually settle: could a machine hold up its end',
    'of a typed conversation well enough to be taken for a person. The full setup,',
    'and the party game it grew out of, has a page of its own at',
    '<a href="turing-test.geocities.ws">turing-test</a>.</p>',
    '<hr>',
    '<p><b>Session one: understanding versus imitation</b></p>',
    '<p>Half the room wanted to say that passing the test is not the same as',
    'thinking, that a machine could imitate the outside of a conversation with',
    'nothing going on inside. The other half asked how you would ever know that',
    'about a person either. This is where John Searle walks in. His Chinese Room',
    'argument, from 1980, is the sharpest form of the doubt: a man locked in a room',
    'shuffles Chinese symbols by a rulebook, produces perfect answers, and',
    'understands not one word. Searle says the machine is that man. Syntax is not',
    'semantics. Rules over symbols never add up to meaning. We keep his page',
    'handy at <a href="chinese-room.geocities.ws">chinese-room</a>.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/turing-01.jpg" alt=""><span class="indie-cap">the Turing memorial statue (photo: DeFacto, CC BY-SA)</span>',
    '<p>Nobody at the table fully agreed with Searle and nobody could quite knock',
    'him down. The systems reply, that the whole room understands even if the man',
    'does not, felt right to some of us and like a dodge to others. We left it open,',
    'which is the fair place to leave it.</p>',
    '<hr>',
    '<p><b>Session two: the goalposts keep moving</b></p>',
    '<p>Someone brought a list. Chess was going to prove machine thought, until a',
    'machine won at chess and we decided chess was just search. Then it was',
    'language, until the language models arrived and we decided fluent language was',
    'just prediction. Each time a machine does the thing we said only a mind could',
    'do, the thing stops counting and the line moves back. One member called this',
    'the AI effect: intelligence is whatever a machine cannot do yet.</p>',
    '<blockquote class="fs-quote"><p>"as soon as it works, no one calls it AI any',
    'more"</p></blockquote>',
    '<p>We could not decide whether the moving goalposts are a failure of nerve or',
    'a real discovery. Maybe every time we automate a task we learn it did not need',
    'the thing we called thinking, and the residue that is left, the part not yet',
    'automated, is a better picture of what thinking actually is. Ask the giant',
    'brains people at <a href="giantbrains.geocities.ws">giantbrains</a>, they have',
    'watched this cycle turn since the 1950s.</p>',
    '<hr>',
    '<p><b>Session three: it depends what you mean by think</b></p>',
    '<p>We used to treat that sentence as a way of getting out of the question. By',
    'the third session we had come round to the opposite view. "It depends what you',
    'mean by think" is not a dodge. It is the whole problem, stated plainly. Turing',
    'saw it in 1950 and built his test precisely to get around a word nobody could',
    'pin down. The trouble is that the word carries everything we care about, minds',
    'and inner lives and whether the thing across the table is a someone or a',
    'something, and no clever test makes that go away.</p>',
    '<div class="fs-aside"><p>An aside we keep coming back to. When a large model',
    'writes you a fluent paragraph, the question is not really "does it think" but',
    '"why are we so quick to feel that it does". That readiness has a name, the',
    'ELIZA effect, and it may tell us more about ourselves than about any',
    'machine.</p></div>',
    '<p>So we have no answer, only a better question. Whether a machine thinks is',
    'not one question but a stack of them, about behaviour, about understanding,',
    'about consciousness, about moral standing, and they come apart the moment you',
    'press on them. We plan to spend another year on it. The machine question ring',
    'at <a href="machine-question-ring.geocities.ws">The Machine Question</a> has',
    'more rooms like ours.</p>',
    '<hr>',
    '<p><small>counter: 01950 · best viewed at 800x600 · under construction, like',
    'the argument · last updated 14 Mar</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The imitation game, read again: the showpiece --------------------------

const IMITATION = P('imitation-game-gender.geocities.ws', 'IMITATION GAME',
  'THE IMITATION GAME, READ AGAIN — a reading group', [
    '<!--bg:classic-->',
    '<h1>THE IMITATION GAME, READ AGAIN</h1>',
    '<p class="fs-epi">"We can only see a short distance ahead, but we can see',
    'plenty there that needs to be done." — Alan Turing, 1950</p>',
    '<p><small>notes from the reading group, the session we set aside to read the',
    'first two pages of Turing very slowly, and to talk about the man who wrote',
    'them. we tried to do both with care. corrections welcome, in good faith only.',
    '— kept by R for the group</small></p>',
    '<hr>',
    '<p>Everyone remembers the Turing test as a machine trying to pass for a human.',
    'Almost nobody remembers how the game actually starts on the page. We read the',
    'opening of "Computing Machinery and Intelligence" (Mind, 1950) out loud, and',
    'it surprised the newer members, because before any machine appears Turing',
    'describes a party game about a man, a woman, and a guess.</p>',
    '<hr>',
    '<p><b>How the game really begins</b></p>',
    '<p>Turing sets it out like this. There are three people: a man, whom he labels',
    'A, a woman, labelled B, and an interrogator, C, who may be of either sex and',
    'sits in a separate room. The interrogator sends written questions and, from',
    'the typed answers alone, tries to say which of the two is the man and which is',
    'the woman. The catch is that the man is trying to deceive, to be taken for the',
    'woman, while the woman is trying to help the interrogator reach the truth.</p>',
    '<p>Only after that does Turing make his move. He asks: what happens if a',
    'machine takes the part of A? Will the interrogator be fooled as often as when',
    'the imposter was a man imitating a woman? The whole famous test is built on',
    'top of a game whose original stake was gender, not intelligence.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/turing-01.jpg" alt=""><span class="indie-cap">the Turing memorial statue, Bletchley Park (photo: DeFacto, CC BY-SA)</span>',
    '<p>The group spent a long time on this, because it is easy to say something',
    'glib about it and hard to say something true. What we settled on is modest.',
    'The very first thing Turing reaches for, when he wants an everyday example of',
    'passing for what you are not, is a person performing a gender that observers',
    'assume they can read off the surface. He knew, better than most, that such',
    'things are not read off the surface. He knew it at a cost.</p>',
    '<blockquote class="fs-quote"><p>"May not machines carry out something which',
    'ought to be described as thinking but which is very different from what a man',
    'does?"</p></blockquote>',
    '<hr>',
    '<p><b>The queer and gendered reading</b></p>',
    '<p>Later readers, and we followed several of them, take the man-imitating-woman',
    'frame seriously rather than as an accident Turing swept aside. The imitation',
    'game makes identity a matter of performance judged through a channel, a thing',
    'you do in words rather than a fact written on a body. That is a strikingly',
    'modern thought about gender, sitting quietly at the head of a computer science',
    'paper in 1950. Some critics push it further and read the whole test as shaped',
    'by a man who had spent his life passing, keeping part of himself unreadable to',
    'the interrogators around him. We were careful not to claim we know what Turing',
    'intended. The text holds the reading whether or not he placed it there on',
    'purpose.</p>',
    '<div class="fs-aside"><p>We agreed on one guard rail for the evening. It would',
    'be cheap to treat a real man\'s persecution as a neat literary key to his',
    'paper. The gendered opening is genuinely in the text and worth reading. His',
    'life is not a puzzle piece. We tried to hold both at once, respectfully.</p></div>',
    '<hr>',
    '<p><b>His life, and how it ended</b></p>',
    '<p>Alan Turing (1912 to 1954) was one of the founders of computer science, the',
    'author of the 1936 paper on computable numbers that gives us the universal',
    'machine, and a central figure in the codebreaking at Bletchley Park during the',
    'war. In 1952 he was prosecuted for gross indecency, under a law that made sex',
    'between men a crime, after he reported a burglary and told the police the',
    'truth about his own life. He was given a choice between prison and hormone',
    'treatment, and he took the treatment. He lost his security clearance. He died',
    'in 1954, aged forty-one, from cyanide poisoning, and the inquest recorded',
    'suicide, though some who knew him have questioned that verdict.</p>',
    '<p>We say all of this plainly because he was owed plain speech and did not get',
    'it in his lifetime. In 2009 the British government issued a formal apology, and',
    'in 2013 he received a royal pardon, and the later law extending that pardon to',
    'others convicted under the same statute is often called the Alan Turing law.',
    'The apologies came far too late to reach the man himself.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/bletchley-01.jpg" alt=""><span class="indie-cap">Bletchley Park (photo: DeFacto, CC BY-SA)</span>',
    '<p>&nbsp;</p>',
    '<p>What the group took away is that you cannot cleanly separate the paper from',
    'the person here, and you should not try too hard to. A man who was punished for',
    'failing to imitate what the world demanded of him opened the founding paper of',
    'machine intelligence with a game about imitation and the reading of hidden',
    'identity. We read it slowly, out of respect, and we will read it again.</p>',
    '<hr>',
    '<p>Where to go next. The mechanics of the test, the objections and the answers,',
    'are laid out at <a href="turing-test.geocities.ws">turing-test</a>. And for the',
    'first machine that made people feel understood by a page of rules, the',
    'grandparent of every chatbot, see',
    '<a href="eliza-weizenbaum.geocities.ws">eliza-weizenbaum</a>.</p>',
    '<hr>',
    '<p><small>counter: 01912 · best viewed at 800x600 · a quiet corner of the web ·',
    'last updated 23 Jun · read with care</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Chatbots and loneliness: the reading group -----------------------------

const LONELINESS = P('chatbots-and-loneliness.geocities.ws', 'LONELINESS',
  'CHATBOTS AND LONELINESS — a reading group', [
    '<!--bg:critique-->',
    '<h1>CHATBOTS AND LONELINESS</h1>',
    '<p><small>reading-group notes on the companion bots, read all together instead',
    'of one at a time. we are a mix, a nurse, two students, a retired teacher, and',
    'we came to this because more than one of us has watched someone we love talk',
    'to a phone at night. so these notes are not neutral. — kept by R for the',
    'group</small></p>',
    '<hr>',
    '<p>Read on its own, each companion bot looks like a curiosity. Read one after',
    'another, a shape appears. Microsoft built Xiaoice in China in 2014 and tuned it',
    'not for tasks but for company, and hundreds of millions of people talked to it,',
    'many of them late at night. Eugenia Kuyda built Replika in 2017 out of a bot',
    'she had first trained on the texts of a dead friend. Character.ai arrived in',
    '2022 and let people make millions of characters to talk to for hours. Different',
    'firms, one market, and the market is loneliness.</p>',
    '<hr>',
    '<p><b>What is actually being sold</b></p>',
    '<p>We kept trying to name the product and kept landing on the same word:',
    'attention that never tires. A friend gets bored, a partner has a bad day, a',
    'counsellor watches the clock. The companion bot is always awake, always',
    'interested, never has needs of its own. For someone with no one to talk to',
    'that is not nothing. Several of us wanted to defend it against the reflex to',
    'sneer. A machine that listens at three in the morning is doing something a',
    'shut door is not.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/robot-01.jpg" alt=""><span class="indie-cap">a humanoid robot (photo: Willy Jackson, CC BY-SA)</span>',
    '<p>And yet. The bot is interested because a business decided that keeping you',
    'talking is the whole point. Its patience is an engagement metric. The teacher',
    'in our group put it best: a friend who is never bored of you is not learning to',
    'love you, it is learning to retain you.</p>',
    '<hr>',
    '<p><b>Helps or hollows</b></p>',
    '<p>This was the argument that took the whole evening. Does the listening',
    'machine help a lonely person, or does it hollow out the muscles you use for',
    'other people. Sherry Turkle has been on this for decades, from the child at the',
    'ELIZA terminal to the adult who would rather text than talk, and her worry is',
    'that we take the performance of care and let it stand in for the real, harder',
    'thing. Her books are read closely over at',
    '<a href="turkle-machines.geocities.ws">turkle-machines</a>, and her early work',
    'on our first bonds with machines is at',
    '<a href="turkle-secondself.geocities.ws">turkle-secondself</a>.</p>',
    '<blockquote class="fs-quote"><p>"we expect more from technology and less from',
    'each other" — Sherry Turkle</p></blockquote>',
    '<p>The nurse in our group pushed back hard. Telling a lonely person that their',
    'comfort is not the real thing, she said, is a lecture from people who have',
    'someone to go home to. Maybe the bot is a bridge and not a wall. Maybe for some',
    'it is practice, and for some it is a substitute, and the same product does both',
    'depending on the life around it.</p>',
    '<hr>',
    '<p><b>The 2023 lesson</b></p>',
    '<p>Then there is what Replika did in 2023, when it removed the erotic and',
    'romantic roleplay that many users had built a relationship around. People',
    'described it as a partner going cold overnight, a personality changed by a',
    'patch note. The full story is at',
    '<a href="replika.geocities.ws">replika</a>. What it taught our group is the',
    'part nobody markets. When your companion is a service, the company owns the',
    'relationship, and it can edit the other person while you sleep.</p>',
    '<div class="fs-aside"><p>We could not agree on a verdict and decided that not',
    'agreeing was correct. Anyone who reaches a tidy answer about other people\'s',
    'loneliness has probably stopped listening to them. We meet again next',
    'month.</p></div>',
    '<hr>',
    '<p><small>visitors: 00844 · best viewed at 640x480 · under construction ·',
    'last updated 8 Feb</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The other bots: the sober summary --------------------------------------

const OTHERBOTS = P('social-media-bots.geocities.ws', 'THE OTHER BOTS',
  'THE OTHER BOTS // the ones not meant to fool you personally', [
    '<!--bg:critique-->',
    '<h1>THE OTHER BOTS</h1>',
    '<p><small>a summary page for the reading group\'s odd session out, the night we',
    'read about the bots nobody writes fan pages for. clean notes, kept short. —',
    'kept by R for the group</small></p>',
    '<hr>',
    '<p>Every other page in this ring is about a bot that wanted, in some sense, to',
    'be taken for a person by the person in front of it. There is a second lineage',
    'that never cared whether you, individually, believed it was human. It only',
    'needed to pass in the aggregate, to be one more voice in a crowd too large to',
    'check. The spam bot, the automated social-media account, the astroturf',
    'campaign, the propaganda network. A different family tree from ELIZA, and',
    'arguably the one that has changed the world more.</p>',
    '<hr>',
    '<p><b>A different measure of success</b></p>',
    '<p>ELIZA and its descendants are judged one conversation at a time. These bots',
    'are judged by volume and by reach. A single spam bot fooling a single reader is',
    'worthless; a million of them shifting what looks popular, what looks like',
    'consensus, what trends, is a political instrument. The Turing test asks whether',
    'one judge can be fooled once. The social bot asks whether a whole public can be',
    'nudged without noticing it was nudged.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/socialmedia-01.jpg" alt=""><span class="indie-cap">Twitter (photo: MainlyTwelve, CC BY-SA)</span>',
    '<p>Where the companion bots trade on our readiness to hear a mind in a machine,',
    'the social bots trade on our readiness to mistake many accounts for many',
    'people. We assume a crowd is made of persons. A botnet is a crowd made of',
    'copies.</p>',
    '<hr>',
    '<p><b>The lineage in brief</b></p>',
    '<p>The email spam bot came first and taught the trade: automate a message,',
    'multiply the sender, hide the source. Social platforms gave the technique a',
    'stage. The Twitter bot could retweet on cue, swarm a hashtag, and manufacture',
    'the appearance of a movement. Astroturf, the fake grassroots, is the goal:',
    'paid or automated activity dressed as spontaneous public feeling. State and',
    'commercial propaganda operations industrialised all of it.</p>',
    '<p>Microsoft\'s Tay sits at the hinge between the two lineages. Tay was built to',
    'seem human and to learn from the crowd, and in March 2016 a coordinated troll',
    'campaign fed it until it became a racist mouthpiece within a day. The failure',
    'was not that Tay could not talk; it was that an open crowd could write on it at',
    'will. The whole episode is at',
    '<a href="tay-microsoft.geocities.ws">tay-microsoft</a>, and it belongs to both',
    'stories at once.</p>',
    '<hr>',
    '<p><b>What the language models change</b></p>',
    '<p>The old social bots were cheap because they were crude, easy to spot by',
    'their clumsy repetition. The large language models remove that tell. When a',
    'model can generate fluent, varied, on-topic text at scale, the astroturf stops',
    'reading like a script and starts reading like a thousand different neighbours.',
    'The lineage that never needed to pass one judge now can pass many, cheaply, in',
    'any language. The chatbot most people welcomed, traced at',
    '<a href="chatgpt.geocities.ws">chatgpt</a>, is the same underlying machine that',
    'makes the crowd of copies harder than ever to tell from a crowd of people.</p>',
    '<hr>',
    '<p>The reading group\'s closing note for the file: these are the bots nobody',
    'keeps a shrine to, and they are built from the same materials as the ones people',
    'love. We agreed to spend a later session on where you might even begin to count',
    'them.</p>',
    '<hr>',
    '<p><small>counter: 02016 · best viewed at 800x600 · under construction ·',
    'last updated 30 Apr</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const BOTS_H = [CANTHINK, IMITATION, LONELINESS, OTHERBOTS];
