// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — the underplayed women (all bg:comp-women).
//
// Pages a concert-goer, a student, and an enthusiast kept about the women the
// programme books skip: Farrenc who fought the Conservatoire for equal pay,
// Lili Boulanger who took the Prix de Rome and died at twenty-four, Florence
// Price whose manuscripts turned up in a derelict house, Bacewicz the
// violinist with the string quartets, Ustvolskaya with her hammer, and Smyth
// who conducted The March of the Women from a prison window. The works, dates
// and premieres are real; the admiration is the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Farrenc: the concert write-up (SHOWPIECE) ------------------------------

const FARRENC = P('louise-farrenc.geocities.ws', 'FARRENC',
  'LOUISE FARRENC // a concert of the Third Symphony', [
    '<!--bg:comp-women-->',
    '<h1>LOUISE FARRENC</h1>',
    '<p class="fs-epi"><i>A write-up of the Farrenc evening at the Conservatoire',
    'chamber hall, given by the college orchestra and a visiting society. Notes',
    'taken from the third row, tidied up the week after.</i></p>',
    '<hr>',
    '<p>The programme opened with the Third Symphony in G minor (Op. 36, 1847),',
    'and by the end of the first movement the question the evening was built to',
    'ask had answered itself: why is this woman not played? Jeanne-Louise Farrenc',
    '(1804 to 1875) wrote three symphonies, a nonet, two piano quintets, chamber',
    'music of real weight, and a shelf of piano studies that pianists still work',
    'through. In her own century she was admired by Schumann and by Berlioz, and',
    'then the concert hall let her go.</p>',
    '<p class="fs-pull">Three symphonies, a nonet, the quintets, and a silence of a',
    'hundred years.</p>',
    '<p>She was the only woman to hold a permanent chair at the Paris',
    'Conservatoire in the whole of the nineteenth century, appointed Professor of',
    'Piano in 1842, and she held it for thirty years. She trained a generation of',
    'women pianists who went on to careers of their own.</p>',
    '<div class="fs-aside"><b>On the nonet.</b> The Nonet in E flat (Op. 38, 1849)',
    'is the work that broke her neglect open in her own lifetime. The young Joseph',
    'Joachim played the violin in its first performance, and the success of it gave',
    'her the standing to press the case she had been making for years about her',
    'salary. Nine instruments, winds and strings together, and a lightness that',
    'never turns thin.</div>',
    '<img class="indie-pic" src="assets/media/web/comp/farrenc-01.jpg" alt=""><span class="indie-cap">Louise Farrenc (public domain)</span>',
    '<p><b>The fight for equal pay.</b> For nearly a decade the Conservatoire paid',
    'her less than the men who held the same rank. After the triumph of the Nonet',
    'she wrote to the director, Daniel Auber, and demanded parity. She got it. It',
    'is a small administrative fact and it is also the reason her name still means',
    'something beyond the scores: she would not be paid as a lesser thing for the',
    'same work.</p>',
    '<blockquote class="fs-quote"><p>"She had earned by her talent and her',
    'labours the right to be treated on the same footing as her colleagues."</p>',
    '<p><small>— the case her husband Aristide made on her behalf, paraphrased in',
    'the college records</small></p></blockquote>',
    '<p>The second half gave us the Piano Quintet No. 1 in A minor (Op. 30), with',
    'the double bass in the texture where a cello would usually sit, a colour she',
    'liked and used more than once. The playing was warm and a little under-',
    'rehearsed, which suited a composer nobody grows up hearing.</p>',
    '<pre>',
    'FARRENC — a short works-list',
    '  Op. 30   Piano Quintet No. 1 in A minor',
    '  Op. 32   Symphony No. 1 in C minor',
    '  Op. 35   Symphony No. 2 in D major',
    '  Op. 36   Symphony No. 3 in G minor      (1847)',
    '  Op. 38   Nonet in E flat major          (1849)',
    '  Op. 40   Trio in E minor (fl or vn, vc, pf)',
    '           Le Tresor des Pianistes (with A. Farrenc, an edition',
    '           of three centuries of keyboard music)',
    '</pre>',
    '<p>Her last large project was not a composition at all. With her husband she',
    'edited <i>Le Tresor des Pianistes</i>, an enormous anthology of early keyboard',
    'music gathered from the sources, a work of scholarship that historians of the',
    'piano still draw on. She finished it alone after he died.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/lili-boulanger-01.jpg" alt=""><span class="indie-cap">Lili Boulanger (public domain)</span>',
    '<p>The revival is recent and it is real. Recordings of the symphonies have',
    'begun to appear, the Nonet turns up in chamber programmes, and orchestras',
    'that would once have filled the slot with a minor overture now reach for the',
    'G minor. If you can hear the Third live, go. For a composer who took the same',
    'prize barrier from the other side, the Prix de Rome, see',
    '<a href="lili-boulanger.geocities.ws">lili-boulanger</a>, and for an',
    'Englishwoman who fought the same institutions with more noise, see',
    '<a href="ethel-smyth.geocities.ws">ethel-smyth</a>.</p>',
    '<hr>',
    '<p><small>counter: 00612 · best viewed at 800x600 · under construction:',
    'a page on the Second Symphony is coming · concert notes, last updated 8 Mar',
    '</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Lili Boulanger: the academic summary -----------------------------------

const LILI = P('lili-boulanger.geocities.ws', 'LILI BOULANGER',
  'Lili Boulanger (1893-1918) — a study note', [
    '<!--bg:comp-women-->',
    '<h1>Lili Boulanger</h1>',
    '<p><small>A summary prepared for a seminar on French music before the Great',
    'War. Dates and prize records checked against the Conservatoire archives.',
    'Corrections welcome.</small></p>',
    '<hr>',
    '<p>Marie-Juliette Olga Boulanger, known as Lili, was born in Paris in 1893',
    'and died there in 1918 at the age of twenty-four. In the small span of a',
    'working life she became, in 1913, the first woman to win the Premier Grand',
    'Prix de Rome for composition, the most coveted prize in French music, with',
    'her cantata <i>Faust et Helene</i>. She was nineteen.</p>',
    '<p>The prize had been closed to women in practice for its whole history. She',
    'took it not as a gesture but on the merit of a taut, dramatic setting that',
    'the jury could not set aside. Her elder sister Nadia had competed for the',
    'same prize and reached only second place; it was the younger sister who',
    'carried it, and it was Nadia who then spent a long life teaching much of the',
    'century how to compose.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/lili-boulanger-01.jpg" alt=""><span class="indie-cap">Lili Boulanger (public domain)</span>',
    '<p><b>The music.</b> The mature works are sombre, modal, harmonically rich,',
    'and unmistakably her own. The three psalm settings are the centre of it. The',
    'setting of Psalm 130, <i>Du fond de l\'abime</i> ("Out of the depths"), for',
    'soloists, chorus, organ and orchestra, is a work of grief and grandeur that',
    'sounds like nothing else of its moment. Psalm 24 is bright and processional;',
    'Psalm 129 is bitter and short.</p>',
    '<p>She wrote knowing her time was short. She had been ill since childhood,',
    'with what was probably intestinal tuberculosis, and much of her music was',
    'composed against pain and exhaustion. Her last work, the <i>Pie Jesu</i>,',
    'she dictated to Nadia when she was too weak to write the notes herself.</p>',
    '<blockquote><p>"I have a great desire to work, because I feel that my time',
    'may be short."</p><p><small>— attributed to Lili Boulanger by her sister',
    'Nadia in later interviews</small></p></blockquote>',
    '<p>The larger project she did not finish was an opera on Maurice',
    'Maeterlinck\'s <i>La Princesse Maleine</i>, left in sketches at her death. What',
    'survives complete is enough to place her among the finest French composers of',
    'the generation, and the neglect that followed had more to do with the',
    'brevity of the life and the sex of the composer than with the quality of the',
    'pages.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/florence-price-01.jpg" alt=""><span class="indie-cap">Florence Price (public domain)</span>',
    '<p>For the American composer who broke a different barrier two decades later,',
    'the first Black woman to have a symphony played by a major orchestra, see',
    '<a href="florence-price.geocities.ws">florence-price</a>. For the',
    'nineteenth-century Frenchwoman who fought the same Conservatoire from a chair',
    'inside it, see <a href="louise-farrenc.geocities.ws">louise-farrenc</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00388 · best viewed at 800x600 · MIDI of the Pie Jesu',
    'withheld out of respect; some things want a real organ · page last revised',
    '14 Jan</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Florence Price: the personal fan shrine --------------------------------

const PRICE = P('florence-price.geocities.ws', 'FLORENCE PRICE',
  'FLORENCE PRICE // the symphony they nearly lost', [
    '<!--bg:comp-women-->',
    '<h1>FLORENCE PRICE</h1>',
    '<p><small>my shrine to Florence Beatrice Price (1887 to 1953), because a',
    'house nearly ate her music and i cannot stop thinking about it. i am not a',
    'musicologist, i am just a fan with a stack of records. — Nettie</small></p>',
    '<hr>',
    '<p>Here is the fact i lead with every time. On 15 June 1933 the Chicago',
    'Symphony Orchestra, under Frederick Stock, played her Symphony No. 1 in E',
    'minor, and Florence Price became the first Black American woman to have a',
    'symphony performed by a major American orchestra. She was born in Little',
    'Rock, Arkansas, trained at the New England Conservatory, and had to give her',
    'birthplace as Mexico on the forms to get around the colour line. Read that',
    'again.</p>',
    '<p>She wrote four symphonies, concertos for piano and for violin, art songs,',
    'and hundreds of pieces, and she made her living partly by writing music for',
    'radio jingles and teaching, because the concert world would only open so',
    'far. Marian Anderson closed her famous 1939 concert at the Lincoln Memorial',
    'with Price\'s arrangement of <i>My Soul\'s Been Anchored in the Lord</i>, in',
    'front of seventy-five thousand people.</p>',
    '<p><b>the sound.</b> She takes the European symphony and grows the',
    'spiritual and the dance up through it. In place of the usual third-movement',
    'scherzo she often writes a JUBA, the syncopated plantation dance, so the',
    'symphony gets up and moves in a way Brahms never does. The melodies lean on',
    'the pentatonic and the bent note of the spiritual without ever quoting a',
    'real one; they are hers, built in that idiom.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/florence-price-01.jpg" alt=""><span class="indie-cap">Florence Price (public domain)</span>',
    '<p><b>the part that breaks my heart.</b> After she died her music slid out of',
    'the repertoire almost completely. Then in 2009 a couple renovating a derelict',
    'house south of Chicago, a place she had used as a summer home, found stacks of',
    'her manuscripts and papers abandoned inside, including works thought lost',
    'altogether, among them the Fourth Symphony and the Violin Concertos. A whole',
    'shelf of a composer, sitting in a rotting house for half a century.</p>',
    '<blockquote><p>"I have two handicaps, those of sex and race. I am a woman,',
    'and I have some Negro blood in my veins."</p><p><small>— Florence Price, in a',
    '1943 letter to the conductor Serge Koussevitzky, asking him to look at her',
    'scores</small></p></blockquote>',
    '<p>Koussevitzky, as far as anyone can tell, never wrote back. That letter is',
    'the whole thing in a paragraph: a first-rank composer having to introduce',
    'herself, twice, and getting silence. The recordings coming out now, the',
    'orchestras finally programming the E minor and the rediscovered Fourth, are',
    'sixty years late and very welcome.</p>',
    '<p>If you love her you should meet the Polish violinist-composer at',
    '<a href="grazyna-bacewicz.geocities.ws">grazyna-bacewicz</a>, another double',
    'career run against the grain, and the Frenchwoman who died young with the',
    'Prix de Rome in her hand at <a href="lili-boulanger.geocities.ws">',
    'lili-boulanger</a>.</p>',
    '<hr>',
    '<p><small>counter: 01047 · best viewed at 800x600 · this page will grow as i',
    'get more of the records · signed, Nettie · last updated 22 Feb</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Bacewicz: the student coursework ---------------------------------------

const BACEWICZ = P('grazyna-bacewicz.geocities.ws', 'BACEWICZ',
  'Grazyna Bacewicz — coursework (MUS 214)', [
    '<!--bg:comp-women-->',
    '<h1>Grazyna Bacewicz: the double career</h1>',
    '<p><small>MUS 214, Twentieth-Century Music, essay 2. Topic set: "a',
    'neoclassical composer outside the main centres". Word count a bit over. i',
    'have a rehearsal so the bibliography is rough, sorry. — student no. 4471',
    '</small></p>',
    '<hr>',
    '<p>Grazyna Bacewicz (1909 to 1969) was a Polish composer and a concert',
    'violinist at the same time, and for a good stretch of her life she was better',
    'known as the player. She studied in Warsaw and then in Paris with Nadia',
    'Boulanger, the sister of the composer, which is where the neoclassical',
    'discipline in her writing comes from: clean lines, motor rhythms, tight',
    'forms, the influence of Stravinsky held together with a real melodic gift.</p>',
    '<p>The core of her output is the chamber music, and inside that the SEVEN',
    'STRING QUARTETS, which run right across her career and are the best single',
    'way into her. The Fourth (1951) is the one that gets played and it won a',
    'prize at Liege. There are also seven violin sonatas and several violin',
    'concertos, no surprise from someone who could premiere them herself.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/bacewicz-01.jpg" alt=""><span class="indie-cap">Grazyna Bacewicz (CC BY-SA 3.0)</span>',
    '<p>She survived the war in occupied Poland, gave secret concerts, and kept',
    'writing. After a car accident in 1954 she gradually gave up performing and',
    'composed full time, and the late music (the Music for Strings, Trumpets and',
    'Percussion, 1958; the fourth and later quartets) moves toward a freer, more',
    'dissonant idiom without ever throwing away the craft. Poland treated her',
    'better than most countries treated their women composers, which is a low bar,',
    'but she was genuinely central at home.</p>',
    '<blockquote><p>"I possess a little machine which allows me to switch off my',
    'private life when I am writing music."</p><p><small>— Grazyna Bacewicz, as',
    'quoted in a Polish radio interview</small></p></blockquote>',
    '<p>Why she matters for this course: she shows that the neoclassical line ran',
    'strong outside Paris and outside the men, that a first-rate performer could',
    'also be a first-rate composer, and that a national school can carry a woman',
    'to its centre when it decides to. She is where i would send anyone who thinks',
    'the mid-century belonged to the twelve-tone people alone.</p>',
    '<p>see also, for this essay\'s neighbours in the "women the programmes skip"',
    'file: the Soviet extremist at <a href="galina-ustvolskaya.geocities.ws">',
    'galina-ustvolskaya</a>, and the American whose manuscripts turned up in a',
    'derelict house at <a href="florence-price.geocities.ws">florence-price</a>.</p>',
    '<p><small>Bibliography (rough): sleeve notes to the Chandos quartets set;',
    'Grove entry, "Bacewicz"; lecture 9 handout; a documentary i half-watched.',
    '</small></p>',
    '<hr>',
    '<p><small>hits: 00233 · best viewed at 800x600 · MIDI of the Fourth Quartet',
    'here, but honestly it sounds like a kettle, hear it live · handed in 3 Dec',
    '</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Ustvolskaya: the listening notes ---------------------------------------

const USTVOLSKAYA = P('galina-ustvolskaya.geocities.ws', 'USTVOLSKAYA',
  'listening notes: the Sixth Piano Sonata (Ustvolskaya)', [
    '<!--bg:comp-women-->',
    '<h1>Listening notes: Ustvolskaya, Piano Sonata No. 6</h1>',
    '<p><small>Notes made while sitting with one work on repeat: the Sixth Piano',
    'Sonata (1988) of Galina Ustvolskaya (1919 to 2006). Written for me, put here',
    'in case they help someone else who finds this music frightening.</small></p>',
    '<hr>',
    '<p>Play it once and you understand the nickname the critics gave her: "the',
    'lady with the hammer". The Sixth Sonata is ten minutes of tone clusters',
    'struck with the flat of the hand and the fist, marked at the loudest',
    'dynamics the page will hold, ffff and beyond. It does not develop the way a',
    'sonata is meant to. It repeats, it pounds, it stops.</p>',
    '<p>Track the dynamics and you hear the plan. The clusters are not noise for',
    'its own sake; they are placed, spaced by silence, and the silences are as',
    'loaded as the blows. She asks the pianist to hit chromatic clusters that no',
    'single hand can voice, so the sound is a mass rather than a harmony. It is',
    'closer to ritual than to the recital.</p>',
    '<p><b>who she was.</b> She studied with Shostakovich in Leningrad, and he',
    'thought her the real thing; he quoted a theme of hers in two of his own works',
    'and said in private that it was she who would be remembered. She rejected the',
    'debt in public and went somewhere he never dared. She wrote very little, and',
    'destroyed more, and refused almost all the labels put on her, including',
    '"religious", though the late works carry titles like <i>Symphony No. 2, True',
    'and Eternal Bliss</i> and read like prayer under torture.</p>',
    '',
    '<p>The catalogue is tiny and deliberate: six piano sonatas, five symphonies,',
    'a handful of compositions she was willing to let stand, everything else',
    'suppressed. The instrumentation is strange on purpose, a symphony for',
    'reciting voice with piccolo, tuba, and percussion, nothing that sounds like',
    'the orchestra you expect. She lived out of the Soviet public eye and outlived',
    'the whole system that had ignored her.</p>',
    '<blockquote><p>"There is no link whatsoever between my music and that of any',
    'other composer, living or dead."</p><p><small>— Galina Ustvolskaya, in the',
    'few words she gave to interviewers</small></p></blockquote>',
    '<p>Listening advice, having done it: do not put it on as background, it will',
    'not allow that. Sit down, one work, from the first blow to the last silence.',
    'Then, when your ears have come back, hear it against the Englishwoman who',
    'made a different kind of noise at <a href="ethel-smyth.geocities.ws">',
    'ethel-smyth</a>, or against the tighter, cleaner Polish rigour at',
    '<a href="grazyna-bacewicz.geocities.ws">grazyna-bacewicz</a>.</p>',
    '<hr>',
    '<p><small>counter: 00159 · best viewed at 800x600 · no MIDI, a soundcard',
    'cannot survive this piece · notes last updated 30 Apr</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

// ---- Ethel Smyth: the lecture write-up --------------------------------------

const SMYTH = P('ethel-smyth.geocities.ws', 'ETHEL SMYTH',
  'Dame Ethel Smyth — a lecture write-up', [
    '<!--bg:comp-women-->',
    '<h1>Dame Ethel Smyth: composer and suffragette</h1>',
    '<p><small>Notes written up from a public lecture given at the town hall,',
    '"Music and the Vote", the speaker a retired professor of music. Any errors',
    'in transcription are mine, not the lecturer\'s.</small></p>',
    '<hr>',
    '<p>The lecturer began where everyone begins, with the toothbrush, and then',
    'made us earn the rest. Ethel Smyth (1858 to 1944) was a serious composer',
    'first, an English one who forced her way to Leipzig against her father\'s',
    'flat refusal, studied there, and came back with a technique the German world',
    'had taken seriously when the English one would not.</p>',
    '<p>The two works to know, we were told, are the <i>Mass in D</i> (1891), a',
    'large sacred work of real ambition that got a hearing at the Royal Albert',
    'Hall and then, being by a woman, largely vanished; and the opera <i>The',
    'Wreckers</i> (1906), set among the Cornish coast communities who lured ships',
    'onto the rocks, which the lecturer called the strongest English opera between',
    'Purcell and Britten. She wrote six operas in all and fought for every',
    'staging.</p>',
    '<img class="indie-pic" src="assets/media/web/comp/smyth-01.jpg" alt=""><span class="indie-cap">Ethel Smyth (public domain)</span>',
    '<p><b>The suffrage years.</b> Around 1910 she gave two years wholly to the',
    'Women\'s Social and Political Union, put her craft at its service, and wrote',
    '<i>The March of the Women</i> (1911), which became the anthem of the movement.',
    'Arrested for breaking a window during a WSPU campaign, she was held in',
    'Holloway prison, and the conductor Thomas Beecham, visiting, found her at the',
    'window of her cell conducting the other suffragettes in the exercise yard as',
    'they sang her march, beating time with a toothbrush.</p>',
    '<blockquote><p>"I feel I must fight for [my music], because I want women to',
    'turn their minds to big and difficult jobs."</p><p><small>— Ethel Smyth,',
    'quoted by the lecturer from her memoirs</small></p></blockquote>',
    '<p>The lecturer\'s real point was about the price. Smyth spent a fortune of',
    'energy on getting heard that a man of her gifts would have spent on the next',
    'score, and she said so, loudly, in ten volumes of memoirs that are half',
    'music history and half a long complaint that reads brilliantly. In later',
    'life she went deaf, could no longer hear her own new work, and turned more',
    'and more to the writing. She was made a Dame in 1922, the first female',
    'composer so honoured.</p>',
    '<p>The talk closed by placing her among the others in this fight: the',
    'Frenchwoman who held her Conservatoire chair and won her equal pay at',
    '<a href="louise-farrenc.geocities.ws">louise-farrenc</a>, and, for a very',
    'different century and temperament, the Soviet composer who made a music of',
    'pure force at <a href="galina-ustvolskaya.geocities.ws">galina-ustvolskaya</a>.</p>',
    '<hr>',
    '<p><small>counter: 00427 · best viewed at 800x600 · under construction:',
    'the lecturer promised handouts on the Mass in D, will add them · written up',
    '19 May</small></p>',
    '<p><small>[ <a href="composers-ring.geocities.ws">Composers Ring</a> ]</small></p>',
  ]);

export const COMP_E = [FARRENC, LILI, PRICE, BACEWICZ, USTVOLSKAYA, SMYTH];
