// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// TAPE, THE STUDIO AND THE PEOPLE WHO BUILT THE MACHINES.
//
// A cluster of amateur pages about musique concrete, the electronic studio and
// the synthesiser, each kept by a different obsessive: a tape purist with a
// razor blade and a chinagraph pencil, a Radiophonic devotee, a Moog collector
// with the patch chart pinned over his desk. None of them is a musician. Each
// writes ABOUT the artist or the machine, quotes titles and dates that are real
// and checkable, and has a view of their own. Half the batch is about the women
// who built the instruments and were left off the plate, and those pages argue
// with the theory web across the ring.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Schaeffer: musique concrete, the cut and the locked groove -------------

const SCHAEFFER = P('pierre-schaeffer-grm.geocities.ws', 'SCHAEFFER',
  'Pierre Schaeffer &amp; musique concrete', [
    '<!--bg:radiophonic-->',
    '<h1>Pierre Schaeffer</h1>',
    '<p><small>musique concrete, the GRM, and the day the train came off the',
    'rails and into the music. kept by a man with a splicing block. — J.R.</small></p>',
    '<hr>',
    '<p>In 1948 an engineer at the Radiodiffusion-Television Francaise in Paris',
    'took a set of disc recordings of steam locomotives, played them on turntables,',
    'looped a groove so it repeated forever, and made a piece of music out of the',
    'noise. That piece is the “Etude aux chemins de fer”, the railway study, and',
    'it is the first thing in the folder marked <i>musique concrete</i>. There are',
    'five of them together, the “Cinq etudes de bruits”, and they are made of',
    'trains, saucepans, spinning tops and a man playing the piano who is not the',
    'point.</p>',
    '<p>Concrete because you start from the concrete sound, the recorded thing,',
    'and work backwards to the composition, instead of starting from a note on',
    'paper and working forwards to a performance. That is the whole idea and it is',
    'still the most radical one on this page. Schaeffer was not a composer. He was',
    'a radio engineer, which is exactly why it occurred to him and had not occurred',
    'to the composers.</p>',
    '<h2>The locked groove and the blade</h2>',
    '<p>People forget the first tools were not tape. The railway study was made on',
    'shellac and lacquer discs with a locked groove, a groove cut so the needle',
    'never travelled inward, so the same fraction of a second came round again and',
    'again. A loop before there was anything to loop with. When tape arrived the',
    'work moved to the blade: you cut the brown tape at an angle on a splicing',
    'block, you turned a sound round so it ran backwards, you took the attack off',
    'the front of a note so nobody could tell it had ever been a piano. Materiality',
    'is not a theory here, it is a box of razor blades and a bin full of offcuts.</p>',
    '<h2>The objet sonore</h2>',
    '<p>His one big idea, and the one I keep coming back to, is the “objet sonore”,',
    'the sound object: a sound listened to for itself, cut off from whatever made',
    'it, so you no longer hear “a train” but a shape with a grain and a weight.',
    'He called the listening that goes with it “reduced listening”, from the',
    'phenomenologists, and if that sounds like homework it is, he wrote a very fat',
    'book about it (the “Traite des objets musicaux”, 1966) that I have carried',
    'around for years and finished once.</p>',
    '<p>Pierre Henry is the other name you need. Henry was the trained musician',
    'Schaeffer worked with, and their “Symphonie pour un homme seul” (1950) is the',
    'one to play someone who thinks this is all trains and academics. The studio',
    'became the GRM, the Groupe de Recherches Musicales, and it is still going,',
    'which is more than most of the places on this ring can say.</p>',
    '<h2>Where it goes</h2>',
    '<p>Cologne heard about Paris and did the opposite on purpose, so read the',
    '<a href="stockhausen.geocities.ws">Stockhausen</a> page next for the fight',
    'about whether you build sound from recordings or from pure tones. And the tape',
    'blade travels: the woman who drew sound instead of cutting it is on the',
    '<a href="daphne-oram-oramics.geocities.ws">Daphne Oram</a> page, and she got',
    'to it from the same place Schaeffer did, the radio engineering room rather',
    'than the conservatoire.</p>',
    '<hr>',
    '<p><small>Play the railway study loud on a proper system. It was cut for',
    'loudspeakers, not headphones, and it knows it. — J.R., keeps a splicing block',
    'on the desk “for morale”. last updated 2 Feb.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="studio-as-instrument-ring.geocities.ws">« The',
    'Studio as Instrument »</a></small></p>',
  ]);

// ---- Stockhausen: Cologne, pure tones, and the cult ------------------------

const STOCKHAUSEN = P('stockhausen.geocities.ws', 'STOCKHAUSEN',
  'Karlheinz Stockhausen — the Cologne studio', [
    '<!--bg:radiophonic-->',
    '<h1>Karlheinz Stockhausen</h1>',
    '<p><small>a page for the WDR studio, the tape works, and against the last',
    'thirty years of him. maintained since 4 Jan.</small></p>',
    '<hr>',
    '<p>Paris built music out of recorded noise. Cologne thought that was cheating.',
    'At the WDR studio the idea was <i>elektronische Musik</i>, electronic music in',
    'the strict German sense: you build every sound yourself out of pure tones from',
    'oscillators, sine waves stacked up by hand, so nothing in the piece was ever a',
    'thing in the world. It is the opposite of Schaeffer and the two studios argued',
    'about it for years. See the <a href="pierre-schaeffer-grm.geocities.ws">',
    'Schaeffer</a> page for the other half of the row.</p>',
    '<p>Then Stockhausen went and settled the argument by ignoring it. In “Gesang',
    'der Junglinge” (1956) he put a boy’s recorded voice in among the electronic',
    'tones and blurred the line the whole quarrel was about. It is still the piece',
    'I would save. A voice singing scripture, chopped and scattered around the room',
    'on five loudspeakers, in and out of sounds that were never anybody’s voice.</p>',
    '<h2>The tape works</h2>',
    '<p>“Kontakte” (1958 to 1960) is the other one, the contact between electronic',
    'and instrumental sound, and there is a version with a pianist and a percussionist',
    'playing against the tape. “Hymnen” (1966 to 1967) takes the national anthems',
    'of the world and runs them through everything until they come apart. All of it',
    'is scissors and splicing tape and patience, months of it, for minutes of sound.',
    'The materiality is time: the reason these pieces sound the way they do is that',
    'a man stood at a machine cutting quarter-inch tape for the better part of a',
    'year.</p>',
    '<h2>The bit I will not defend</h2>',
    '<p>I am a fan and I am going to be honest about the back half. Somewhere after',
    'the sixties he decided he was a channel for higher forces, wrote an opera cycle',
    'meant to run seven evenings (“Licht”, one for each day of the week), scored a',
    'string quartet with a helicopter for each player, and said a thing about a',
    'terrible day in New York in 2001 that I am not going to repeat on a tribute',
    'page because it does not deserve the traffic. The cult of himself got in front',
    'of the work. It happens. Play the fifties tape pieces and leave the robes in',
    'the cupboard.</p>',
    '<hr>',
    '<p><small>The Beatles put him on the Sgt Pepper sleeve, which is how half of',
    'my generation heard the name. Fair enough. Start at “Gesang”, not at the',
    'helicopters. — kept by someone who queued for a WDR reissue in the rain.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="studio-as-instrument-ring.geocities.ws">« The',
    'Studio as Instrument »</a></small></p>',
  ]);

// ---- Daphne Oram: drawing sound onto film, and written out -------------------

const ORAM = P('daphne-oram-oramics.geocities.ws', 'ORAM',
  'Daphne Oram &amp; Oramics', [
    '<!--bg:radiophonic-->',
    '<h1>Daphne Oram</h1>',
    '<p><small>who co-founded the BBC Radiophonic Workshop, walked out inside a',
    'year, and built an instrument you drew with. an appreciation, and a',
    'complaint.</small></p>',
    '<hr>',
    '<p>Two things everybody ought to know and mostly does not. First: the BBC',
    'Radiophonic Workshop, that everyone rightly loves, was set up in 1958 and',
    'Daphne Oram co-founded it. Second: she left it inside a year, because a BBC',
    'department that gave you a room, a handful of tape machines and a strict brief',
    'to make sound effects for radio drama was not the same thing as being allowed',
    'to compose, and she wanted to compose.</p>',
    '<p>So she left and built her own instrument in a converted oast house in Kent,',
    'on her own money, and called it Oramics.</p>',
    '<h2>Drawing the sound</h2>',
    '<p>This is the part that stops people. On Oramics you did not play a keyboard',
    'and you did not splice tape. You <i>drew</i>. You painted shapes, curves and',
    'blocks, in black onto strips of clear 35mm film, ran the film past a bank of',
    'photocells, and the shape you had drawn became the sound: the wave, the',
    'volume, the vibrato, all of it under your pencil. The gesture of your hand on',
    'the film was the note. I have never got over it. It is the most direct thing',
    'anybody built in this whole story, drawing straight onto the tone, and a woman',
    'built it in a barn while the men got the BBC department with the nameplate.</p>',
    '<p>She wrote it up in a book, “An Individual Note” (1972), which is half',
    'manual, half philosophy, and worth hunting down. She is the reason I get',
    'irritable when people say the women were “also there”. She was not also there.',
    'She built the instrument.</p>',
    '<h2>Read across, because this is the argument</h2>',
    '<p>The theory people have finally caught up and there are pages worth your',
    'time. The <a href="penelope.geocities.ws">penelope</a> page argues that women',
    'and machines go back to the loom and the switchboard, not to the synth ad in',
    'the eighties, and Oram is exactly their case. <a href="zerosandones.geocities.ws">',
    'zeros and ones</a> (that is Sadie Plant’s book) says the digital was women’s',
    'work from the start and got told it was men’s, which is the Oram story in one',
    'line. Both of those sit inside the <a href="cyberfeminist-ring.geocities.ws">',
    'cyberfeminist ring</a>, which is where I send anyone who thinks this page is',
    'just nostalgia for a barn.</p>',
    '<p>And one I half-agree with. The Kittler crowd at',
    '<a href="theres-no-software.geocities.ws">there’s no software</a> say there is',
    'no software, only the physics of the hardware doing the work, and that all the',
    'talk of programs hides the machine. Oramics is their dream exhibit, a “program”',
    'you can see because it is a line drawn on a piece of film. Where I part company',
    'is that they make it sound like nobody chose anything, and Oram chose every',
    'curve. The film did what her hand told it. That is not the machine writing',
    'itself.</p>',
    '<p>Then read the <a href="delia-derbyshire.geocities.ws">Delia Derbyshire</a>',
    'page, because the other one who got written out was down the corridor at the',
    'Workshop Oram had just left.</p>',
    '<hr>',
    '<p><small>The Oramics machine survives in a museum now, which is the correct',
    'outcome and was by no means the likely one. — kept by A.M., who has stood in',
    'front of it and can confirm it is enormous.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="british-radiophonic-ring.geocities.ws">« British',
    'Radiophonic »</a> &middot; <a href="cyberfeminist-ring.geocities.ws">« Cyberfeminist',
    'Ring »</a></small></p>',
  ]);

// ---- Delia Derbyshire: the Doctor Who theme, spliced note by note -----------

const DERBYSHIRE = P('delia-derbyshire.geocities.ws', 'DERBYSHIRE',
  'Delia Derbyshire — the theme, note by note', [
    '<!--bg:radiophonic-->',
    '<h1>Delia Derbyshire</h1>',
    '<p><small>the woman who made the most famous piece of electronic music in',
    'Britain out of a wobbly oscillator and a razor blade, and did not get her name',
    'on it. by someone who has counted the splices.</small></p>',
    '<hr>',
    '<p>1963. Ron Grainer writes a tune for a new BBC science-fiction serial, a',
    'melody and some words like “wind bubble and wow” on a sheet of paper, and hands',
    'it to the Radiophonic Workshop. Delia Derbyshire realises it. There are no',
    'synthesisers yet, none, so here is how the Doctor Who theme was actually made,',
    'and it is the best story on this whole ring.</p>',
    '<h2>How it was actually built</h2>',
    '<p>Every sound is a test-tone oscillator, the kind you find in a lab, plus',
    'white noise for the swoops and the hisses. There is no keyboard to play a',
    'tune on. So she tuned an oscillator to a pitch, recorded a bit of it onto',
    'tape, measured off a length of that tape with a ruler to get the right',
    'duration, cut it, and spliced it to the next one. Every note in the bassline',
    'is a physical piece of tape cut to length and joined to the one before it, by',
    'hand, and then the whole line is a loop hung round the room. The melody, the',
    'bassline, the hisses: separate reels, run at once and mixed, in a building',
    'that did not have a multitrack machine.</p>',
    '<p>People say “she programmed it”. Nobody programmed anything. She spliced it.',
    'The story is that Grainer heard it back and asked “did I write that?”, and she',
    'is supposed to have said “most of it”. He wanted to get her a co-credit and the',
    'BBC would not let a Workshop staffer be named. So the most-heard piece of',
    'electronic music in the country went out anonymous, and everybody knows the',
    'tune and almost nobody knew the woman until she was nearly gone.</p>',
    '<h2>White Noise, and Decca</h2>',
    '<p>She was not only the theme. “An Electric Storm” (1969), by White Noise, the',
    'group she made with David Vorhaus and Brian Hodgson, is a proper album and',
    'still sounds like it arrived from somewhere else. And the detail I cannot let',
    'go of: before the BBC, she went to Decca looking for work and was told the',
    'company did not employ women in the recording studio. Decca. The label that',
    'turned down the Beatles was also busy turning down her.</p>',
    '<h2>Why this page is angry</h2>',
    '<p>Read the <a href="daphne-oram-oramics.geocities.ws">Daphne Oram</a> page',
    'and you get the pattern: two women, the same Workshop, both doing the founding',
    'work, both left off the plate. That is why I send people to',
    '<a href="cyberfeminist-ring.geocities.ws">the cyberfeminist ring</a> and to',
    'the Kittler page at <a href="theres-no-software.geocities.ws">there’s no',
    'software</a>. Kittler’s crowd like her because the theme really is just the',
    'hardware, oscillators and tape and scissors, with no “program” anywhere, and',
    'they are right about that. What their page never quite says, and what Oram’s',
    'keeper says better, is that a person decided every cut. The tape did not tune',
    'itself.</p>',
    '<hr>',
    '<p><small>Next time it comes round on the telly, listen to the bassline and',
    'remember it is a row of hand-cut splices from 1963. Nobody has improved on it.',
    '— D.H., has tried to make one loop the old way and gave up at the fourth cut.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="british-radiophonic-ring.geocities.ws">« British',
    'Radiophonic »</a> &middot; <a href="cyberfeminist-ring.geocities.ws">« Cyberfeminist',
    'Ring »</a></small></p>',
  ]);

// ---- Wendy Carlos: Switched-On Bach, one line at a time ---------------------

const CARLOS = P('wendy-carlos-moog.geocities.ws', 'CARLOS',
  'Wendy Carlos &amp; Switched-On Bach', [
    '<!--bg:radiophonic-->',
    '<h1>Wendy Carlos</h1>',
    '<p><small>the record that made a room full of engineers realise the Moog was',
    'a musical instrument. and the patience it took. kept with respect.</small></p>',
    '<hr>',
    '<p>“Switched-On Bach” came out in 1968 and it did the thing no demo record had',
    'managed: it took the Moog seriously as music, not as a novelty that goes',
    'boop. Bach realised on a synthesiser, the Brandenburgs and the inventions and',
    'the rest, and it sold like nothing electronic had, and it is the reason your',
    'local shop had a synth in the window by 1972.</p>',
    '<h2>Why it was so hard</h2>',
    '<p>Here is what people miss. The Moog she used was monophonic. One note at a',
    'time. So a piece of Bach with three or four voices moving at once had to be',
    'built one line at a time, each voice played and recorded on its own and layered',
    'up on tape, and every single line had to be tuned by hand because the',
    'oscillators drifted with the heat of the room. Get to the end of a long take',
    'and find the pitch had wandered and you did it again. Then you did the next',
    'voice. It took months. This is not a man sitting down and playing Bach on a',
    'keyboard. It is closer to what Delia Derbyshire was doing with the blade, the',
    'patient layering of single lines, and I put the two records next to each other',
    'on purpose. See <a href="delia-derbyshire.geocities.ws">Derbyshire</a>.</p>',
    '<p>She engineered it with Rachel Elkind, and she was as much the engineer as',
    'the player, working with Bob Moog directly on what the instrument even needed',
    'to do. Read <a href="bob-moog-synth.geocities.ws">the Bob Moog page</a> for the',
    'machine itself, the patch cords and all.</p>',
    '<h2>The films, and the person</h2>',
    '<p>After the Bach records she scored “A Clockwork Orange” (1971) and later',
    '“Tron” (1982), so a lot of people have heard her work without knowing it. And',
    'the plain fact, because she has been open about it for decades and it is part',
    'of who built this music: Wendy Carlos is a trans woman, and transitioned in the',
    'early 1970s, around the years those first records were changing what a studio',
    'could be. The theory web has people who write about exactly this, and the one',
    'worth reading is <a href="sandystone-virtual.geocities.ws">Sandy Stone’s page</a>,',
    'who was herself a recording engineer before she was a theorist and does not',
    'treat any of it as a curiosity. Her page and the',
    '<a href="cyberfeminist-ring.geocities.ws">cyberfeminist ring</a> are where this',
    'belongs, alongside Oram and Derbyshire: the people who built the machines and',
    'kept getting described as standing next to them.</p>',
    '<hr>',
    '<p><small>Play the 1968 record and then try to imagine tuning every note of it',
    'by hand in a warm room. That is the whole review. — kept by someone who has one',
    'oscillator and a great deal of sympathy.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="cyberfeminist-ring.geocities.ws">« Cyberfeminist',
    'Ring »</a></small></p>',
  ]);

// ---- Bob Moog: the machine, the patch cords, the Minimoog -------------------

const MOOG = P('bob-moog-synth.geocities.ws', 'MOOG',
  'Bob Moog &amp; the synthesizer', [
    '<!--bg:radiophonic-->',
    '<h1>Bob Moog</h1>',
    '<p><small>the man who built the thing everybody else on this ring is playing.',
    'a collector’s page, with the patch chart pinned over the desk.</small></p>',
    '<hr>',
    '<p>Everybody argues about the players. This page is for the engineer, because',
    'without him half the other pages on this ring are blank. Bob Moog (rhymes with',
    'vogue, and he minded about that) started out building theremins from a kit in',
    'the family home, which is the right origin for him: he was a maker of',
    'instruments before he was anything else, and he never really stopped being',
    'that.</p>',
    '<h2>Voltage control, in plain words</h2>',
    '<p>His idea, the one everything hangs on, is voltage control. You make a',
    'circuit whose pitch, or loudness, or brightness, is set by an electrical',
    'voltage, and then you can have one part of the machine send a voltage to',
    'another part and control it automatically. A keyboard is just a device for',
    'sending out a different voltage per key. Once pitch is a voltage, you can',
    'sweep it, wobble it, or let one oscillator steer another. That is the modular',
    'synth, and it is why the thing is a wall of separate boxes rather than a piano.</p>',
    '<h2>The patch cords, which are the whole point</h2>',
    '<p>The Moog modular is a wall of knobs and sockets, and you make a sound by',
    'connecting the boxes together with patch cords, physical leads you plug from',
    'one module’s output to another’s input. The sound does not exist until you have',
    'wired it. There is no memory. When you find a good one you write the settings',
    'down on a chart or you draw the patch, because when you pull the leads out it is',
    'gone. That is the materiality people go on about: a Moog patch is a diagram you',
    'built with your hands and it lives on a bit of paper. This is exactly what the',
    'engineers mean over on <a href="silicon-ring.geocities.ws">the silicon ring</a>,',
    'where they read the machine as hardware first and the “settings” as a fiction',
    'laid over a physical circuit. On a modular Moog they are plainly right, because',
    'the setting <i>is</i> a handful of cables.</p>',
    '<h2>The Minimoog</h2>',
    '<p>Then in 1970 the Minimoog, and this is the one that changed who got to play.',
    'They took the modular idea, chose the connections that mattered, wired them',
    'inside the box so you no longer needed the cords, and bolted it to a keyboard',
    'in a road case a band could carry to a gig. No patching, still fat. You could',
    'sling it on top of an organ and take it on tour. Half the basslines of the',
    'seventies come out of that decision. The wall of cables became a thing with a',
    'pitch wheel that one person could throw in the back of a van.</p>',
    '<p>For the man who tuned the same oscillators note by note before the Minimoog',
    'made it easier, see <a href="wendy-carlos-moog.geocities.ws">Wendy Carlos</a>,',
    'who worked with Bob directly. And for the West-coast machine that went the',
    'other way and refused the keyboard on purpose, the',
    '<a href="suzanne-ciani.geocities.ws">Suzanne Ciani</a> page and her Buchla.</p>',
    '<hr>',
    '<p><small>If you ever get to patch a real modular, do the boring thing first:',
    'one oscillator, one filter, one envelope, and listen to what each cable does',
    'before you make a cathedral of it. — B.T., owns more cables than sense.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="machines-beat-ring.geocities.ws">« Machines That',
    'Made the Beat »</a></small></p>',
  ]);

// ---- Suzanne Ciani: the Buchla, the West coast, a living on the machines -----

const CIANI = P('suzanne-ciani.geocities.ws', 'CIANI',
  'Suzanne Ciani &amp; the Buchla', [
    '<!--bg:radiophonic-->',
    '<h1>Suzanne Ciani</h1>',
    '<p><small>the other coast, the other machine, no keyboard, and a woman who',
    'actually paid the rent with it when almost nobody could. by a Buchla',
    'evangelist.</small></p>',
    '<hr>',
    '<p>East coast, Bob Moog gives you a keyboard, because he wanted the thing to',
    'be an instrument a musician recognised. West coast, Don Buchla refuses the',
    'keyboard on purpose, because he thought a row of black-and-white keys drags all',
    'your old habits into a machine that could do something new. The Buchla has',
    'touch plates instead, metal pads you press that read how hard and where, and',
    'sequencers, and it steers you toward texture and pulse rather than tunes. If',
    'the <a href="bob-moog-synth.geocities.ws">Moog</a> is a synth that wants to be',
    'a band, the Buchla is a synth that wants to be weather. Suzanne Ciani is the',
    'person who made me hear the difference.</p>',
    '<h2>The pop and the pour</h2>',
    '<p>Here is the fact that delights everyone I tell it to. That “pop and pour”',
    'sound in the old Coca-Cola adverts, the bottle opening and the liquid going',
    'into the glass, is a Buchla. She made it. She spent years doing sound design',
    'and logos for advertising, on synthesisers, because that was where a person',
    'could earn a living on the machines in the seventies, and she was one of the',
    'very few doing it and getting paid. Play someone the Coke pour and then tell',
    'them there is no Coke, it is a woman and a modular synth in New York, and watch',
    'their face.</p>',
    '<h2>Seven Waves</h2>',
    '<p>Then the records under her own name, and “Seven Waves” (1982) is the one to',
    'start on: the Buchla’s pulse and her own playing, water as the whole idea of',
    'the record. She kept performing live on the thing, quadraphonic, no laptop,',
    'building it in the room, decades before that became a fashionable thing to do.</p>',
    '<h2>Why she is on this ring with the others</h2>',
    '<p>She belongs on the same shelf as <a href="daphne-oram-oramics.geocities.ws">',
    'Oram</a>, <a href="delia-derbyshire.geocities.ws">Derbyshire</a> and',
    '<a href="wendy-carlos-moog.geocities.ws">Carlos</a>, and for once it is not a',
    'story about being written out, it is a story about making it work. She built a',
    'business on the machines. That is why I send her to',
    '<a href="cyberfeminist-ring.geocities.ws">the cyberfeminist ring</a> as well:',
    'not as another woman done down by the men, but as one who got the invoice paid.</p>',
    '<hr>',
    '<p><small>Best viewed at 800x600. If the Buchla samples below do not load your',
    'browser is too old, email me. — kept by someone who will bore you about touch',
    'plates given half a chance. last updated 9 Feb.</small></p>',
    '<p><small>rings: <a href="electronic-tape-ring.geocities.ws">« Electronic &amp;',
    'Tape Music »</a> &middot; <a href="studio-as-instrument-ring.geocities.ws">« The',
    'Studio as Instrument »</a> &middot; <a href="cyberfeminist-ring.geocities.ws">«',
    'Cyberfeminist Ring »</a></small></p>',
  ]);

export const MUSIC_C = [
  SCHAEFFER,
  STOCKHAUSEN,
  ORAM,
  DERBYSHIRE,
  CARLOS,
  MOOG,
  CIANI,
];
