// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH A — the video-store cult canon.
//
// Six fan pages a film-obsessed kid kept on a free host in 1998, each ABOUT a
// cult film and never in the film's own voice. A video-store staff pick with
// the full kit (Blade Runner); a zine review of the year's new Coen picture
// (Lebowski); a fan shrine to a punk science-fiction favourite (Repo Man); a
// film-studies coursework page (Brazil); a top-ten quotable page (Withnail);
// and a staff pick written the week Fincher's new one landed (Fight Club). The
// directors, years and casts are real; the star ratings and the grudges are
// the fan's.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Blade Runner: the video-store staff pick (SHOWPIECE) -------------------

const BLADE_RUNNER = P('blade-runner.geocities.ws', 'BLADE RUNNER',
  'BLADE RUNNER // staff pick of the month (Ridley Scott, 1982)', [
    '<!--bg:genx-cult-->',
    '<h1>BLADE RUNNER</h1>',
    '<p><small>STAFF PICK OF THE MONTH, pulled off the shelf and pressed into',
    'your hands by the clerk who will not shut up about it. i have rented this to',
    'the same three regulars eleven times between us. if you have only seen it',
    'once you have not seen it. — Cass, back counter, Tuesdays and Thursdays</small></p>',
    '<hr>',
    '<p class="fs-epi">"I\'ve seen things you people wouldn\'t believe." — Roy Batty</p>',
    '<p>Ridley Scott, 1982, from Philip K. Dick\'s novel <i>Do Androids Dream of',
    'Electric Sheep?</i> Harrison Ford is Deckard, a burnt-out cop dragged back',
    'to hunt down four replicants, bio-engineered people so like us that you need',
    'a machine and a long interview to tell the difference. It is set in a Los',
    'Angeles of 2019 that never stops raining, all neon and steam and giant',
    'advertising, and it more or less invented what everyone now means by the',
    'look of the future. Neo-noir with flying cars. The private eye, the femme',
    'fatale, the rain on the window, only the case is: what is a person.</p>',
    '<pre>',
    '  +--------------------------------------------------+',
    '  |  BLADE RUNNER            [ SCI-FI / NOIR ]        |',
    '  |--------------------------------------------------|',
    '  |  YEAR .... 1982                                  |',
    '  |  DIRECTOR. Ridley Scott                          |',
    '  |  RUNTIME . 117 min (theatrical) / 116 (DC)       |',
    '  |  STARS ... Harrison Ford, Rutger Hauer,          |',
    '  |            Sean Young, Edward James Olmos,        |',
    '  |            Daryl Hannah, M. Emmet Walsh           |',
    '  |  FORMAT .. VHS, letterbox if you can find it      |',
    '  |  RATING .. * * * * *  (five of five, no notes)   |',
    '  +--------------------------------------------------+',
    '</pre>',
    '<p><b>MIND THE CUT YOU RENT.</b> This is the whole reason for the card. There',
    'is more than one Blade Runner and they are not the same film.</p>',
    '<p>The 1982 THEATRICAL cut has Deckard talking over the top of everything in',
    'a flat voice-over the studio bolted on because they thought audiences would',
    'be lost, and it has a tacked-on happy ending with sunny scenery that was cut',
    'in from another production entirely. A lot of us grew up on that one because',
    'it was the only tape going. Then in 1992 came the DIRECTOR\'S CUT: no',
    'voice-over, no sunny ending, and one small strange addition, a daydream of a',
    'unicorn that changes what you think about Deckard himself. That is the war in',
    'a sentence. The voice-over war split fandom down the middle and it is still',
    'the argument you will have at the counter.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/vhs-01.jpg" alt=""><span class="indie-cap">A VHS cassette, the format it came on (photo: LoMit, CC BY-SA 4.0)</span>',
    '<p class="fs-aside"><b>DID YOU KNOW.</b> The film opened to soft business in',
    '1982, buried the same summer as a friendly alien and a certain space saga,',
    'and a fair few reviewers shrugged. It found its people on video and on late',
    'television across the decade, one curious renter at a time, until it turned',
    'from a flop into the most argued-over science-fiction film there is. This is',
    'the whole reason a video store exists.</p>',
    '<p><b>IS DECKARD ONE OF THEM.</b> The big one. The Director\'s Cut plants that',
    'unicorn daydream, and then another character leaves a folded paper unicorn',
    'where Deckard will find it, as if to say: i know what you dream. Read it one',
    'way and the hunter is the hunted, a replicant who does not know it. Read it',
    'the other way and he is just a tired man. Ridley Scott has hinted; Harrison',
    'Ford has said the opposite. i will not tell you what i think because arguing',
    'about it is half the fun and i want you to come back and argue.</p>',
    '<p class="fs-pull">The chase is not the point. The four replicants only want',
    'what anyone wants, which is more time, and the film knows it.</p>',
    '<p>And that is why the ending lands the way it does. Rutger Hauer as Roy',
    'Batty, the leader of the four, at the end of his own short built-in lifespan,',
    'sitting in the rain, delivers the speech everyone means when they say the',
    'film is beautiful. Hauer trimmed it himself the night before. The last line,',
    'about moments lost "like tears in rain", is the most quoted thing in the',
    'picture and it earns every bit of it.</p>',
    '<blockquote><p>"All those moments will be lost in time, like tears in rain.',
    'Time to die." — Roy Batty</p></blockquote>',
    '<pre>',
    '  IF YOU LIKED THIS, RENT THESE',
    '  ----------------------------------',
    '  > Alien (Scott, 1979) — same director, the horror one',
    '  > The Terminator (Cameron, 1984)',
    '  > Brazil (Gilliam, 1985) — see our page, the OTHER',
    '      broken future, funnier and sadder',
    '  > Akira (Otomo, 1988) — the neon city, animated',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/genx/video-store-01.jpg" alt=""><span class="indie-cap">The shelves of an independent video store (photo: Mojmir Churavy, CC0)</span>',
    '<p>Where to go from here on this ring. If you want the other great',
    'retro-future that fights its own studio over the ending, we did a whole',
    'coursework page on <a href="brazil.geocities.ws">brazil</a>. And if you want',
    'to see what happens when a genius director is let off the leash to be funny,',
    'the newest thing on the shelf is the Coens picture over at',
    '<a href="the-big-lebowski.geocities.ws">the-big-lebowski</a>. Rent wide.</p>',
    '<hr>',
    '<p><small>UNDER CONSTRUCTION. adding frame grabs as i can borrow a capture',
    'card. best viewed in Netscape at 800x600. counter: 03812 rentals and',
    'climbing. last updated 14 Oct 1998. flame gif goes here when i work out how',
    'to make it not crash the page.</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- The Big Lebowski: the zine review --------------------------------------

const THE_BIG_LEBOWSKI = P('the-big-lebowski.geocities.ws', 'BIG LEBOWSKI',
  'THE BIG LEBOWSKI // zine review, issue 6 (Coens, 1998)', [
    '<!--bg:genx-cult-->',
    '<h1>THE BIG LEBOWSKI</h1>',
    '<p><small>reprinted from XEROX FLOWER zine, issue six, the one i photocopied',
    'at work when the manager was on lunch. cut and paste and staple, same as',
    'ever. this is the review, typed up for the web because people kept asking to',
    'read it. — the editor (me)</small></p>',
    '<hr>',
    '<p class="fs-epi">"The Dude abides." — The Dude</p>',
    '<p>New this year, 1998, from Joel and Ethan Coen, the pair who did',
    '<i>Fargo</i> two years back. This is the loose one, the shaggy one, and i',
    'think it is going to be the one people keep. Jeff Bridges plays Jeffrey',
    'Lebowski, who answers only to "the Dude", an ageing slacker in a dressing',
    'gown who wants nothing from life but a clean rug and a game of bowls. Two',
    'goons rough him up over a debt and ruin the rug, because they have him',
    'confused with a different, richer Lebowski. The rug, he keeps saying, really',
    'tied the room together. So off he goes to get compensated, and the whole',
    'daft plot unrolls from there.</p>',
    '<p>It is a mistaken-identity comedy wearing the coat of a Raymond Chandler',
    'mystery, a kidnapping and a ransom and a briefcase, except our detective is',
    'stoned and mostly wants his rug back. The plot honestly does not matter and',
    'the Coens know it does not matter. What matters is the hang, the talk, the',
    'people.</p>',
    '<p class="fs-pull">A private-eye plot handed to a man who cannot be bothered',
    'to solve it. That is the joke, and it is a rich one.</p>',
    '<p>John Goodman is Walter, the Dude\'s bowling partner, a Vietnam veteran who',
    'brings a firearm and his own rage to every single situation including a',
    'friendly frame of tenpin. Steve Buscemi is poor Donny, who never follows the',
    'conversation and gets told to shut up every time he tries. The bowling alley',
    'is the still centre the film keeps coming home to, all that green baize light',
    'and the balls rolling. There are dream sequences, a bowling musical number',
    'in the Dude\'s head, a nihilist gang, a severed toe, and a rug that will not',
    'stay tied.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/coens-01.jpg" alt=""><span class="indie-cap">The Coen brothers, who wrote and directed it (photo: Georges Biard, CC BY-SA 3.0)</span>',
    '<p class="fs-aside"><b>MARK MY WORDS.</b> This one is going to grow legs.',
    'The lines are already going round the store like a virus, people answering',
    'the phone as the Dude, ordering White Russians they do not even like. Give',
    'it a couple of years and somebody somewhere throws a proper convention for',
    'it, matching shirts, quote contests, the works. You read it here in a',
    'stapled zine first.</p>',
    '<p>VERDICT: four cans of half-and-half out of five. It rambles, it does not',
    'care about its own story, and that is exactly the point of it. Put it on with',
    'friends and a jug of something and let it wash over you. The Dude abides, and',
    'so, i suspect, will this film.</p>',
    '<p>On this ring: if you want more slacker heroes who solve nothing, our fan',
    'over at <a href="repo-man.geocities.ws">repo-man</a> makes the case for the',
    'punk cousin of this thing. And for the other side of the coin, a stone-cold',
    'sci-fi classic done straight, see the staff pick at',
    '<a href="blade-runner.geocities.ws">blade-runner</a>.</p>',
    '<hr>',
    '<p><small>counter: 00967. best viewed in Netscape at 800x600. this page is',
    'still UNDER CONSTRUCTION, scans of the original zine spread to follow. last',
    'updated 30 Nov 1998. member of the VHS collectors\' webring, ask me about',
    'trades. — ed.</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Repo Man: the personal fan shrine --------------------------------------

const REPO_MAN = P('repo-man.geocities.ws', 'REPO MAN',
  'REPO MAN // my favourite film ever, a shrine (Alex Cox, 1984)', [
    '<!--bg:genx-cult-->',
    '<h1>*** REPO MAN ***</h1>',
    '<p><small>welcome to my shrine to the greatest film nobody i know has seen.',
    'i have worn out two rental tapes and bought the ex-rental of a third. if you',
    'came here from the ring, sit down, this is going to take a while. — spikeball,',
    'age 19, on the family computer, keep out MUM</small></p>',
    '<hr>',
    '<p class="fs-epi">"The life of a repo man is always intense." — Bud</p>',
    '<p>Alex Cox, 1984. Otto (Emilio Estevez) is a bored punk who loses his',
    'supermarket job and falls in with Bud (Harry Dean Stanton), who repossesses',
    'cars for a living and treats it like a philosophy and a religion. That is the',
    'street level of the film. Above the street there is a 1964 Chevy Malibu',
    'driving around Los Angeles with something in the boot so hot that it glows,',
    'and whoever opens it up gets more than they bargained for, and there is a',
    'huge bounty on the car, and government agents and UFO obsessives are all',
    'chasing it. Punk comedy meets science-fiction satire and neither one blinks.</p>',
    '<p>i cannot explain to you how much this film means to me. It is funny about',
    'being broke and bored and young in a way almost nothing is. Bud\'s speeches',
    'about the repo code are the closest thing i have to a creed. Harry Dean',
    'Stanton is the best thing in it and he is the best thing in everything, and',
    'if you do not know the name yet you will, there is a whole page for the man',
    'on this very ring at <a href="harry-dean-stanton.geocities.ws">',
    'harry-dean-stanton</a> and you should go and pay respect.</p>',
    '<p class="fs-pull">"Ordinary people, i hate \'em." Bud again. i have this',
    'written inside my school folder.</p>',
    '<p><b>THE SOUNDTRACK.</b> Half the reason to own this. Iggy Pop did the theme',
    'song. The rest is a blast of early-80s Los Angeles punk and hardcore, Black',
    'Flag, Circle Jerks, Suicidal Tendencies, the Plugz doing the incidental',
    'music. There is a scene where the Circle Jerks turn up as a lounge act',
    'playing one of their own hard songs slow, and it is the single funniest',
    'sight gag about selling out i have ever seen. The tape of the soundtrack is',
    'the other thing i wore out.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/stanton-01.jpg" alt=""><span class="indie-cap">Harry Dean Stanton, who stars (photo: DeanoJD, CC BY-SA 4.0)</span>',
    '<p class="fs-aside"><b>THE GENERIC JOKE.</b> Everything in Otto\'s world comes',
    'in plain white packaging with black lettering: a tin that just says FOOD, a',
    'can that just says DRINK, cigarettes that say CIGARETTES. It is the whole',
    'punk sneer at consumer life done as set dressing and nobody points at it. It',
    'is just there in the background making the point.</p>',
    '<p>WHY IT IS A CULT FILM. It flopped in cinemas, obviously, because of course',
    'it did, and then a song from it got on the radio and the studio had to sort',
    'of un-cancel the film and put it back out, and it found everybody like me on',
    'video and at midnight showings. That is how these things always go.</p>',
    '<p>Neighbour on the ring: the newer slacker comedy everyone is quoting this',
    'year, the bowling one, gets a proper review from a friend at',
    '<a href="the-big-lebowski.geocities.ws">the-big-lebowski</a>. Same spirit,',
    'gentler drugs.</p>',
    '<hr>',
    '<p><small>counter: 00538. best viewed in Netscape at 800x600, i built this in',
    'Notepad. UNDER CONSTRUCTION 4 EVER. animated flaming skull goes RIGHT HERE',
    'once i find one that loads. last updated 2 Sep 1998. plate o\' shrimp.</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Brazil: the film-studies coursework ------------------------------------

const BRAZIL = P('brazil.geocities.ws', 'BRAZIL',
  'BRAZIL // FILM 214 coursework essay (Terry Gilliam, 1985)', [
    '<!--bg:genx-cult-->',
    '<h1>BRAZIL (1985): dystopia as farce</h1>',
    '<p><small>FILM 214, Introduction to Science-Fiction Cinema, seminar essay,',
    'submitted for assessment. i got a 2:1 for this and the tutor wrote "trim the',
    'plot summary" so please do not tell her i put the whole thing on the web.',
    '— K. (student number withheld)</small></p>',
    '<hr>',
    '<p class="fs-epi">"We\'re all in it together." — Ministry slogan, Brazil</p>',
    '<p><b>Introduction.</b> Terry Gilliam\'s <i>Brazil</i> (1985) is a satire set',
    'in a retro-future that never quite arrived: a world of the mid-twentieth',
    'century imagined forward with no digital anything, only vast clattering',
    'machines, endless paper forms, and ducts. Ducts everywhere, pipes and',
    'ductwork crawling across every wall, the plumbing of a state that has',
    'plumbed itself into paralysis. It is often read alongside Orwell, and Gilliam',
    'has said the working title was "1984 and a half", but the temperature is',
    'completely different. Where Orwell is cold, Gilliam is a farce.</p>',
    '<p><b>Plot, briefly (tutor: i know).</b> Sam Lowry (Jonathan Pryce) is a',
    'minor clerk in the Ministry of Information who is content to be nobody and',
    'escapes into daydreams of flying to rescue a woman. A literal bug, a squashed',
    'fly, drops into a printer and turns the name Tuttle into Buttle on a warrant,',
    'and the wrong man is arrested by mistake. Sam is sent to smooth over the',
    'clerical error and in doing so meets the woman from his dreams and falls',
    'foul of the whole apparatus. Robert De Niro appears as Tuttle, a renegade',
    'heating engineer who fixes ducts without the paperwork, which in this world',
    'makes him a wanted terrorist.</p>',
    '<img class="indie-pic" src="assets/media/web/genx/video-store-01.jpg" alt=""><span class="indie-cap">The shelves of an independent video store (photo: Mojmir Churavy, CC0)</span>',
    '<p><b>Argument.</b> The film\'s target is not a dictator but bureaucracy',
    'itself, the machinery of forms and departments and receipts that grinds on',
    'with nobody in charge and nobody to blame. Terror here is administrative. The',
    'state tortures people and then bills them for the service. Read this way',
    '<i>Brazil</i> belongs beside the other great broken-future films of the',
    'period, and i would put it directly next to the neon dystopia of',
    '<a href="blade-runner.geocities.ws">blade-runner</a> on this ring: two',
    'visions of tomorrow, one wet and corporate, one dusty and clerical, both',
    'refusing the clean chrome future the genre used to sell.</p>',
    '<p class="fs-quote"><blockquote><p>The comedy is the argument. A world this',
    'absurd cannot be argued with, only laughed at, and the laughter is what the',
    'apparatus cannot process on its forms.</p></blockquote></p>',
    '<p><b>The ending and the studio.</b> The single most important thing to know',
    'about <i>Brazil</i> is that there are two endings, and the fight over them is',
    'part of the text now. Gilliam\'s ending is bleak: Sam escapes only inside his',
    'own broken mind while his body sits captured. The American studio, Universal,',
    'thought this unreleasable and cut its own shorter, sweeter version with a',
    'happy escape, which fans call the "Love Conquers All" cut. Gilliam fought',
    'them in public, took out a trade advert asking when they would release his',
    'film, and arranged private screenings for critics until a critics\' award',
    'forced the studio\'s hand. The director\'s version is the one that survived. It',
    'is a rare case of the artist winning and it is why we can study the real film',
    'at all.</p>',
    '<p><b>Conclusion.</b> <i>Brazil</i> matters because it makes the machinery',
    'funny without making it safe. You laugh, and then you notice you are laughing',
    'at your own week at the bank or the benefits office, and the laugh goes cold.</p>',
    '<pre>',
    '  BIBLIOGRAPHY (as required)',
    '  --------------------------------',
    '  Gilliam, T. (dir.) BRAZIL. Universal, 1985.',
    '  Orwell, G. Nineteen Eighty-Four. (the obvious one)',
    '  the making-of documentary on the laserdisc, which',
    '     the library HAS, ask at the desk',
    '  a magazine article about the studio fight that i',
    '     photocopied and then lost the cover of, sorry',
    '</pre>',
    '<p>Neighbour on the ring: for another beloved cult film from these same',
    'islands, drunk and quotable instead of dystopian, see the top-ten over at',
    '<a href="withnail-and-i.geocities.ws">withnail-and-i</a>.</p>',
    '<hr>',
    '<p><small>counter: 00291. best viewed in Netscape at 800x600. this page is',
    'coursework and UNDER CONSTRUCTION until i get the mark back and stop being',
    'nervous. last updated 21 Jan 1999.</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Withnail and I: the top-ten / quotable page ----------------------------

const WITHNAIL_AND_I = P('withnail-and-i.geocities.ws', 'WITHNAIL',
  'WITHNAIL AND I // the ten most quotable lines (Robinson, 1987)', [
    '<!--bg:genx-cult-->',
    '<h1>WITHNAIL AND I: THE TOP TEN LINES</h1>',
    '<p><small>the definitive countdown, argued over with my flatmates until three',
    'in the morning and more than one slammed door. do not write in to complain',
    'about the order, the order is CORRECT. — Boozy, keeper of this page and the',
    'flat\'s only working kettle</small></p>',
    '<hr>',
    '<p class="fs-epi">"We want the finest wines available to humanity." — Withnail</p>',
    '<p>Bruce Robinson, 1987. Two out-of-work actors share a filthy flat in',
    'Camden at the fag-end of the 1960s. Withnail (Richard E. Grant) is grand,',
    'furious, permanently drunk and magnificent. "I" (Paul McGann), who is barely',
    'named in the whole film, is the nervier one who narrates. Broke and cold and',
    'sick of it, they cadge a country cottage off Withnail\'s outrageous Uncle',
    'Monty and go "on holiday by mistake", where they discover they have no idea',
    'how the countryside works, cannot light a fire, cannot catch a meal, and are',
    'quite possibly going to freeze. That is nearly the entire plot. The film runs',
    'on dialogue, and what dialogue.</p>',
    '<p>It is the most quotable British film there is, and it has become a drinking',
    'game, where you are meant to match the pair drink for drink through the film,',
    'which is a genuinely terrible idea because Withnail puts away a frightening',
    'amount including, at one grim point, lighter fluid. Please do not actually do',
    'the lighter fluid. Do the countdown instead.</p>',
    '<pre>',
    '  THE TOP TEN, DEFINITIVE, NO APPEALS',
    '  --------------------------------------',
    '  10. "I have some extremely distressing news."',
    '   9. "We\'ve gone on holiday by mistake."',
    '   8. "I feel like a pig shat in my head."',
    '   7. "Scrubbers! Scrubbers!"',
    '   6. "Monty, you terrible c... " (you know the one)',
    '   5. "We want the finest wines available to humanity."',
    '   4. "I demand to have some booze."',
    '   3. "Even a stopped clock tells the right time twice',
    '        a day."',
    '   2. "chin chin"',
    '   1. "I have of late, but wherefore I know not, lost',
    '        all my mirth."   (the closing Hamlet, alone,',
    '        in the rain, to the wolves. gets me every time.)',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/genx/vhs-01.jpg" alt=""><span class="indie-cap">A VHS cassette, the format it came on (photo: LoMit, CC BY-SA 4.0)</span>',
    '<p class="fs-aside"><b>DID YOU KNOW.</b> Bruce Robinson based Withnail on a',
    'real flatmate from his own hungry acting years, and wrote it as a novel',
    'first. Richard E. Grant, who plays the great drunk, barely drinks in real',
    'life and had to be talked into getting properly drunk once so he would know',
    'what he was portraying. Every so often the least likely person is perfect',
    'for the part.</p>',
    '<p>Why it lasts. Because it is really about the end of a friendship and the',
    'end of an era, both at once, and the funniest film about failure ever made',
    'earns the sadness of its last scene the hard way, line by brilliant line. You',
    'laugh the whole way and then Withnail is alone at the zoo in the rain doing',
    'Hamlet to nobody, and that is the film.</p>',
    '<p>On the ring: for the newest cult thing on the shelf, all soap and bruises',
    'and a nasty clever twist, the staff have written up',
    '<a href="fight-club.geocities.ws">fight-club</a>, which came out this very',
    'year. And for the other British masterpiece of the ductwork-and-despair',
    'school, the coursework page on <a href="brazil.geocities.ws">brazil</a> is',
    'worth your time.</p>',
    '<hr>',
    '<p><small>counter: 00612. best viewed in Netscape at 800x600. UNDER',
    'CONSTRUCTION, adding the full quote list when the flat stops arguing about',
    'it, so, never. last updated 8 Dec 1998. chin chin.</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

// ---- Fight Club: the video-store staff pick, hot off the projector ----------

const FIGHT_CLUB = P('fight-club.geocities.ws', 'FIGHT CLUB',
  'FIGHT CLUB // staff pick, brand new this week (Fincher, 1999)', [
    '<!--bg:genx-cult-->',
    '<h1>FIGHT CLUB</h1>',
    '<p><small>STAFF PICK, and this one is a gamble because the film only just',
    'opened and half the reviews hate it. i saw it twice opening weekend. i think',
    'the reviews are wrong and i think in five years this is a cult film, so i am',
    'planting the flag now, on the internet, where flags are cheap. — Cass, back',
    'counter (yes, the Blade Runner one)</small></p>',
    '<hr>',
    '<p class="fs-epi">"The first rule of Fight Club is: you do not talk about',
    'Fight Club." — Tyler Durden</p>',
    '<p>David Fincher, 1999, from the novel by Chuck Palahniuk. Edward Norton',
    'plays an unnamed narrator, an office drone with insomnia and a flat full of',
    'catalogue furniture, so numb he can only feel anything at support groups for',
    'illnesses he does not have. Then he meets Tyler Durden (Brad Pitt), a soap',
    'salesman and free radical who says everything the narrator cannot, and the',
    'two of them start a bare-knuckle club in the basement of a bar where men go',
    'to feel something the modern world has sanded off them. That is the setup.',
    'It grows into something much bigger and stranger, and there is a twist near',
    'the end that reframes the entire film, which i will not spoil.</p>',
    '<p>Underneath the bruises it is a satire of consumer life, of the idea that',
    'you are what you own, that a man can be talked into buying an identity from a',
    'furniture catalogue. Tyler\'s answer to that is destruction, and the film is',
    'clever enough to make Tyler thrilling and then to make you nervous about how',
    'thrilling you found him. It does not hand you the moral. It hands you the',
    'problem.</p>',
    '<p class="fs-pull">A film about men who own too much and feel too little, and',
    'the dangerous fun of throwing it all on a bonfire.</p>',
    '<pre>',
    '  STAFF PICK CARD                    [ NEW RELEASE ]',
    '  ------------------------------------------------',
    '  FIGHT CLUB (1999)   dir. David Fincher',
    '  from the novel by Chuck Palahniuk (1996)',
    '  with: Edward Norton, Brad Pitt, Helena',
    '        Bonham Carter, Meat Loaf',
    '  the clerk says: * * * * (four of five, ask',
    '        me again in a year, i bet it goes to five)',
    '  WARNING: not a date film. or maybe the best',
    '        date film. depends entirely on the date.',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/genx/video-store-01.jpg" alt=""><span class="indie-cap">The shelves of an independent video store (photo: Mojmir Churavy, CC0)</span>',
    '<p class="fs-aside"><b>THE SOAP.</b> Tyler makes and sells fancy soap, and',
    'there is a running joke about what the fat for the soap is rendered from and',
    'who it gets sold back to. It is the whole consumer-culture argument folded',
    'into a bar of soap you can buy at a nice shop. Fincher shoots the film grimy',
    'and green and brilliant, and there are little visual tricks buried in it that',
    'reward a second rental, which is exactly what a video store wants to hear.</p>',
    '<p>The reception, as of this week, is a proper fight of its own. Some critics',
    'are appalled, some are calling it the film of the year, and audiences are',
    'walking out arguing. My money says the arguing is the point and my money says',
    'it wins in the end, the way <a href="blade-runner.geocities.ws">blade-runner',
    '</a> won after everyone wrote it off. Ask the shelf. The shelf remembers.</p>',
    '<p>On the ring: for the friendlier end of the slacker-satire family, the new',
    'Coens comedy over at <a href="the-big-lebowski.geocities.ws">the-big-lebowski',
    '</a>, and for the punk grandfather of all of this, the shrine at',
    '<a href="repo-man.geocities.ws">repo-man</a>.</p>',
    '<hr>',
    '<p><small>counter: 00147 and it only went up today. best viewed in Netscape',
    'at 800x600. UNDER CONSTRUCTION, this page written in a hurry the night the',
    'film opened. last updated 16 Oct 1999. do not talk about it. tell everyone.</small></p>',
    '<p><small>[ <a href="genx-screen-ring.geocities.ws">Gen X Screen Ring</a> ]</small></p>',
  ]);

export const GENX_A = [BLADE_RUNNER, THE_BIG_LEBOWSKI, REPO_MAN, BRAZIL, WITHNAIL_AND_I, FIGHT_CLUB];
