// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// SOC_C — anarchism & libertarian socialism.
//
// Pages a reading group, a student, a branch and an old militant kept about the
// anarchist tradition: a fan shrine to Bakunin, reading notes on Kropotkin's
// Mutual Aid, an academic summary of Proudhon, a rally write-up for Emma
// Goldman, a branch's minutes on Malatesta, and the homepage of the IWW. The
// names, titles, dates and quarrels are real; the framing is the 1990s web.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Bakunin: the personal fan shrine (SHOWPIECE) ---------------------------

const BAKUNIN = P('mikhail-bakunin.geocities.ws', 'BAKUNIN',
  'THE URGE TO DESTROY — a Bakunin shrine', [
    '<!--bg:soc-anarchist-->',
    '<h1>THE URGE TO DESTROY</h1>',
    '<p class="fs-epi">"The passion for destruction is also a creative passion." — M. Bakunin, 1842</p>',
    '<p><small>a shrine to Mikhail Bakunin (1814&ndash;1876), the giant of',
    'collectivist anarchism, kept by someone who read him at nineteen and never',
    'got over it. i am not neutral about this man. read on and you will not be',
    'either. raised fist to all who visit. \\o/ &mdash; Nadia</small></p>',
    '<hr>',
    '<p>He was a Russian nobleman who gave up the whole comfortable life to spend',
    'thirty years plotting revolution across Europe. Dresden, Prague, Paris, the',
    'barricades of 1848 and 1849. Arrested, handed to the Tsar, chained in the',
    'Peter and Paul Fortress, then Siberia, then an escape right across the',
    'Pacific and back to Europe to start again. You do not invent a life like',
    'that. He lived it.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/bakunin-01.jpg" alt=""><span class="indie-cap">Mikhail Bakunin, by Nadar (public domain)</span>',
    '<h2>collectivist anarchism</h2>',
    '<p>His answer to the social question was collectivism. The land and the',
    'workshops belong to the associated workers who use them, not to the state',
    'and not to the private owner. Bakunin wanted the means of production held in',
    'common, run from below through federations of free communes and unions, with',
    'the reward still tied to labour rather than to need. That last point is what',
    'later separated him from the anarcho-communists like Kropotkin, who wanted',
    'distribution by need. Between them they map most of the anarchist argument,',
    'and you can visit Kropotkin at',
    '<a href="peter-kropotkin.geocities.ws">peter-kropotkin</a>.</p>',
    '<blockquote class="fs-quote"><p>"Liberty without socialism is privilege and',
    'injustice; socialism without liberty is slavery and brutality."</p></blockquote>',
    '<p>That sentence is the whole quarrel of the century in one line. He would',
    'not choose between freedom and equality. He wanted both or neither.</p>',
    '<hr>',
    '<h2>the split with Marx</h2>',
    '<p>This is the part people fight about, so here it is plainly. Bakunin and',
    'Karl Marx were both in the First International, the International Working',
    "Men's Association, and they could not share a house. Marx wanted the workers",
    'to take the state and use it, a workers\u2019 government, the dictatorship of',
    'the proletariat as a stage on the road. Bakunin said any state you build,',
    'even a workers\u2019 one, grows its own governing class and turns on the people',
    'it claims to serve. Give the revolution a state and you have made new',
    'masters. He predicted, decades early, that a "red bureaucracy" would be the',
    'cruellest tyranny of all.</p>',
    '<div class="fs-aside"><p><b>The Hague, 1872.</b> The feud ended in a rigged',
    'congress. Marx and his allies expelled Bakunin from the International and,',
    'to keep it out of anarchist hands, moved the whole General Council to New',
    'York, where it quietly died. Marx won the vote and lost the argument: the',
    'anarchists carried on without him. For the organisation itself see',
    '<a href="the-first-international.geocities.ws">the-first-international</a>.</p></div>',
    '<p class="fs-pull">"They maintain that only a dictatorship can create the',
    "people's will; we reply that no dictatorship can have any other aim than to",
    'perpetuate itself."</p>',
    '<img class="indie-pic" src="assets/media/web/soc/kropotkin-01.jpg" alt=""><span class="indie-cap">Peter Kropotkin, by Nadar (public domain)</span>',
    '<h2>God and the State</h2>',
    '<p>His most read book was never finished. <i>God and the State</i> is a',
    'fragment, written around 1871, published after his death by his comrades',
    'Cafiero and Reclus, who found it among his papers. It is a furious assault',
    'on religion and on all authority that claims a higher sanction. The famous',
    'passage turns the idea of rebellion into the very thing that makes us human:</p>',
    '<pre>',
    '  He alone wills and disposes who governs himself.',
    '',
    '  Man, like all the rest of nature, is entirely the',
    '  product of natural forces. Three elements, or three',
    '  fundamental principles, constitute the essential',
    '  conditions of all human development:',
    '',
    '    (1) human animality;',
    '    (2) thought; and',
    '    (3) rebellion.',
    '',
    '  To the first, properly speaking, corresponds social',
    '  and private economy; to the second, science; to the',
    '  third, liberty.',
    '',
    '        — from God and the State (posth. 1882)',
    '</pre>',
    '<hr>',
    '<h2>the secret brotherhoods</h2>',
    '<p>Now the awkward bit, because a shrine that hides the awkward bit is worth',
    'nothing. For a man who preached freedom from above, Bakunin loved a secret',
    'society. The Alliance of Social Democracy, the International Brotherhood, ranks',
    'and oaths and an invisible directorate steering the open movement. Marx used',
    'this against him, and not unfairly. And there was Nechaev, the cold young',
    'fanatic Bakunin fell in with, whose <i>Catechism of a Revolutionary</i> made',
    'the cause an excuse for anything. Bakunin broke with him in horror in the end,',
    'but the association clings to his name. A great libertarian with a weakness',
    'for the conspiratorial. Both are true.</p>',
    '<hr>',
    '<p>Why he matters now, with the old machines gone quiet, is that he asked the',
    'question no revolution has answered. Who guards the guards. Who governs the',
    'ones who govern in your name. He trusted no answer that began by concentrating',
    'power, and history has been unkind to those who told him he was naive.</p>',
    '<hr>',
    '<p><small>counter: 01814 · best viewed at 800x600 · this page is under',
    'perpetual construction, like the revolution · last updated 30 May</small></p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
  ]);

// ---- Kropotkin: book-reading notes on Mutual Aid ----------------------------

const KROPOTKIN = P('peter-kropotkin.geocities.ws', 'KROPOTKIN',
  'Reading notes: Mutual Aid (Kropotkin)', [
    '<!--bg:soc-anarchist-->',
    '<h1>Reading notes: Mutual Aid</h1>',
    '<p><small>notes taken for the Tuesday reading circle on Peter Kropotkin',
    '(1842&ndash;1921), <i>Mutual Aid: A Factor of Evolution</i> (1902). page refs',
    'are to the old Heinemann edition, sorry if yours differ. these are notes, not',
    'gospel, correct me at the meeting.</small></p>',
    '<hr>',
    '<p><b>who he was.</b> A Russian prince, a geographer, a real one, who mapped',
    'the mountains of Siberia and then gave up the title and the career for',
    'anarchism. "The prince who gave it up", people call him. Warm where Bakunin',
    'was stormy. He turned collectivist anarchism into anarcho-communism, and you',
    'can see the difference against <a href="mikhail-bakunin.geocities.ws">',
    'mikhail-bakunin</a>: Bakunin kept reward tied to labour, Kropotkin said take',
    'according to need and let the storehouse be open.</p>',
    '<hr>',
    '<p><b>the main argument of the book.</b> Kropotkin read the Social Darwinists,',
    'the Huxley crowd, who made nature a gladiator show, every beast for itself,',
    'and used it to justify the market red in tooth and claw. He answered from the',
    'field. As a naturalist in Siberia he had looked for the war of each against',
    'all and mostly found the opposite: animals of a species cooperating, sharing,',
    'defending one another, because the ones that cooperate survive. Mutual aid is',
    'not soft, it is a hard fact of evolution, as real a factor as competition and',
    'often the stronger one.</p>',
    '<blockquote class="fs-quote"><p>"Don\u2019t compete! ... that is the watchword',
    'which comes to us from the bush, the forest, the river, the ocean."</p></blockquote>',
    '<p><b>the human chapters.</b> He runs the same argument up through history:',
    'the tribe, the village commune, the free medieval city, the guild, right up',
    'to the friendly societies and unions of his own day. Everywhere, under the',
    'state and against it, ordinary people build webs of mutual support. The state',
    "did not invent cooperation, he says. It absorbed it, taxed it, and took the",
    'credit.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/kropotkin-01.jpg" alt=""><span class="indie-cap">Peter Kropotkin, by Nadar (public domain)</span>',
    '<p><b>the other book to read first, honestly.</b> <i>The Conquest of Bread</i>',
    '(1892) is the practical one, the picture of how an anarcho-communist society',
    'might feed and house itself by expropriation and free distribution. Mutual',
    'Aid gives you the evidence that people are made for it. Bread gives you the',
    'plan. Read Bread when you are angry and Mutual Aid when you need convincing',
    'that the anger has a foundation.</p>',
    '<hr>',
    '<p><b>where the circle got stuck.</b> Is he too optimistic about human',
    'nature? Errico Malatesta, who knew him and loved him, thought so, and said',
    'Kropotkin let a hopeful biology do the work that only struggle and',
    'organisation can do. Worth arguing next week. Malatesta is at',
    '<a href="errico-malatesta.geocities.ws">errico-malatesta</a> if you want to',
    'read the friendly quarrel from the other side.</p>',
    '<hr>',
    '<p><small>counter: 00892 · best viewed at 800x600 · Tuesday reading circle ·',
    'notes last tidied 14 Apr</small></p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
  ]);

// ---- Proudhon: academic summary ---------------------------------------------

const PROUDHON = P('pierre-joseph-proudhon.geocities.ws', 'PROUDHON',
  'Pierre-Joseph Proudhon: a summary', [
    '<!--bg:soc-anarchist-->',
    '<h1>Pierre-Joseph Proudhon</h1>',
    '<p><small>a summary page maintained for students of nineteenth-century',
    'political thought. Pierre-Joseph Proudhon (1809&ndash;1865). references at the',
    'foot. compiled from standard sources; report errors to the address',
    'below.</small></p>',
    '<hr>',
    '<p>Proudhon was a self-taught printer from Besan&ccedil;on and the first',
    'person to call himself an anarchist and mean it as a compliment. In 1840,',
    'in <i>What is Property?</i>, he asked his own title and gave the answer that',
    'made him notorious across Europe.</p>',
    '<blockquote class="fs-quote"><p>"Property is theft."</p></blockquote>',
    '<p>The slogan is more careful than it sounds. Proudhon did not condemn all',
    'possession. He distinguished property, meaning the absentee owner\u2019s claim',
    'to rent, interest and profit drawn from the labour of others, from possession,',
    'meaning the workshop, the tools and the home actually used by the person who',
    'holds them. The first he attacked as theft. The second he defended. This',
    'distinction runs through everything he wrote.</p>',
    '<hr>',
    '<p><b>Mutualism.</b> His positive doctrine was mutualism: a society of',
    'independent producers, artisans and peasant proprietors and workers\u2019',
    'associations, exchanging goods at their cost in labour, bound by free contract',
    'rather than by the state. Not communism, which he distrusted as much as',
    'capitalism, and not the free market of the economists either, but a third',
    'thing, an economy of equals trading fairly without a master over them.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/proudhon-01.jpg" alt=""><span class="indie-cap">Pierre-Joseph Proudhon, by Gustave Courbet (public domain)</span>',
    '<p><b>The People\u2019s Bank.</b> In 1849 he tried to build it. The Banque du',
    'Peuple was to offer producers free credit, interest-free, so that workers',
    'could fund their own enterprises without the usurer. It enrolled thousands',
    'before his imprisonment for offending the President killed it in weeks. The',
    'idea outlived the institution and fed straight into the credit-union and',
    'cooperative movements that followed.</p>',
    '<div class="fs-aside"><p><b>The quarrel with Marx.</b> The two men corresponded',
    'warmly at first. Then Proudhon published <i>The Philosophy of Poverty</i>',
    '(1846) and Marx answered with <i>The Poverty of Philosophy</i> (1847), a book',
    'whose title is a sneer and whose contents are a demolition. Marx accused',
    'Proudhon of dressing up petty-bourgeois nostalgia as economics. Proudhon',
    'thought Marx a would-be dictator of the movement. The mutualist tradition and',
    'the Marxist one have argued ever since.</p></div>',
    '<p>His influence ran two ways. Through Bakunin at',
    '<a href="mikhail-bakunin.geocities.ws">mikhail-bakunin</a> it fed the',
    'collectivist and later anarchist current of the First International. And in',
    'Britain his praise of skilled craft and honest making chimed with William',
    'Morris at <a href="william-morris.geocities.ws">william-morris</a> and the',
    'guild-socialist idea of the worker as maker rather than hand.</p>',
    '<hr>',
    '<p><b>Select references.</b> Proudhon, <i>What is Property?</i> (1840);',
    '<i>System of Economic Contradictions</i> (1846); <i>General Idea of the',
    'Revolution in the Nineteenth Century</i> (1851). G. Woodcock, <i>Pierre-Joseph',
    'Proudhon</i> (1956). K. Steven Vincent, <i>Proudhon and the Rise of French',
    'Republican Socialism</i> (1984).</p>',
    '<hr>',
    '<p><small>hits: 00517 · best viewed at 800x600 · a student resource · last',
    'updated 2 Mar</small></p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
  ]);

// ---- Emma Goldman: rally / talk write-up ------------------------------------

const GOLDMAN = P('emma-goldman.geocities.ws', 'GOLDMAN',
  'Red Emma: notes from the talk', [
    '<!--bg:soc-anarchist-->',
    '<h1>Red Emma: notes from the talk</h1>',
    '<p><small>a write-up of the evening talk "Emma Goldman and the Unruly Life",',
    'given at the social centre last Thursday to a packed and rowdy room. i took',
    'notes so the people who could not squeeze in would not miss it. all mistakes',
    'mine. raised fist. &mdash; from the back row</small></p>',
    '<hr>',
    '<p>The speaker opened with the line everyone waits for, and then spent the',
    'evening earning it back. Emma Goldman (1869&ndash;1940), "Red Emma", born in',
    'Lithuania under the Tsar, arrived in America at sixteen, radicalised by the',
    'hanging of the Haymarket anarchists in Chicago. From there, a life on the',
    'platform and in the cells.</p>',
    '<blockquote class="fs-quote"><p>"If I can\u2019t dance, I don\u2019t want to be',
    'part of your revolution." (as remembered, and as she would have',
    'wished)</p></blockquote>',
    '<p>The speaker was honest that Goldman never wrote those exact words. What she',
    'wrote was a refusal to have her joy disciplined out of her by a cause that',
    'took itself too grimly. A comrade told her to stop dancing, it did not befit',
    'an agitator, and she rounded on him. The tidy slogan came later. The spirit is',
    'hers.</p>',
    '<img class="indie-pic" src="assets/media/web/soc/goldman-01.jpg" alt=""><span class="indie-cap">Emma Goldman (public domain)</span>',
    '<p><b>anarchist feminism.</b> This was the heart of the talk. Goldman went',
    'further than the vote. She attacked marriage as an economic arrangement that',
    'sold women a lifetime of dependence, defended free love and birth control when',
    'both could get you arrested, and insisted that a woman\u2019s emancipation had to',
    'begin inside her own soul, not only in the statute book. She quarrelled with',
    'the respectable suffragists as often as with the state. The room loved this',
    'part.</p>',
    '<p><b>Mother Earth.</b> From 1906 she published the magazine <i>Mother Earth</i>,',
    'anarchist politics bound together with modern drama, poetry and the new',
    'ideas, for over ten years. It was her megaphone and her school. Alexander',
    'Berkman, her lifelong comrade, helped run it.</p>',
    '<div class="fs-aside"><p><b>The deportation.</b> In 1917 Goldman and Berkman',
    'were jailed for agitating against conscription. In 1919, at the height of the',
    'first Red Scare, a young J. Edgar Hoover built the case to expel her, and on',
    'the "Soviet Ark", the <i>Buford</i>, she and hundreds of others were shipped',
    'to Russia. She went hopeful. She left disillusioned, and wrote',
    '<i>My Disillusionment in Russia</i> (1923) against the Bolshevik state, which',
    'cost her friends on the left who were not ready to hear it.</p></div>',
    '<p>The speaker closed by pointing us to her comrades. Errico Malatesta, whom',
    'she met on the international circuit, at',
    '<a href="errico-malatesta.geocities.ws">errico-malatesta</a>, and the',
    'American labour anarchism of the Wobblies at',
    '<a href="the-iww.geocities.ws">the-iww</a>, whose free-speech fights she threw',
    'herself into.</p>',
    '<hr>',
    '<p><small>attendance about ninety · counter: 00648 · best viewed at 800x600 ·',
    'the social centre, upstairs · written up 9 Jun</small></p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
  ]);

// ---- Malatesta: branch / reading-group minutes ------------------------------

const MALATESTA = P('errico-malatesta.geocities.ws', 'MALATESTA',
  'Branch minutes: reading Malatesta', [
    '<!--bg:soc-anarchist-->',
    '<h1>Branch minutes: reading Malatesta</h1>',
    '<p><small>minutes of the branch meeting, second Wednesday. present: nine',
    'members and two visitors. item three on the agenda was our reading of Errico',
    'Malatesta (1853&ndash;1932). minuted by the secretary; corrections to be tabled',
    'next meeting.</small></p>',
    '<hr>',
    '<p><b>3.1</b> The secretary gave the life. An Italian from Campania, medical',
    'student turned electrician turned lifelong agitator, a comrade of Bakunin\u2019s',
    'in the First International as a very young man and later close to Kropotkin,',
    'though he argued with both. Sixty years of insurrections, arrests and exile,',
    'from Argentina to London to Buenos Aires and back. He mended machines for a',
    'living wherever he landed. The room noted he is the anarchist who actually',
    'held down a job.</p>',
    '<hr>',
    '<p><b>3.2</b> On the propaganda of the deed. The branch discussed Malatesta\u2019s',
    'long argument with the tactic of the heroic assassination and the bomb. He had',
    'flirted with insurrection as a young man, but he came to reject terror as',
    'self-defeating: it frightened the very workers it meant to inspire and handed',
    'the state its excuse for repression. A member read the line the branch liked',
    'best.</p>',
    '<blockquote class="fs-quote"><p>"Let us do all we can to hasten the revolution;',
    'but let it be the work of all, and not of a few."</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/soc/malatesta-01.jpg" alt=""><span class="indie-cap">Errico Malatesta (public domain)</span>',
    '<p><b>3.3</b> On organisation. This was where Malatesta parted from the',
    'purists. Against those who thought any permanent organisation a betrayal of',
    'anarchist spontaneity, he argued that anarchists must organise, patiently and',
    'openly, in unions and federations and papers, or leave the field to those who',
    'do. Freedom is not the absence of structure, he said, but structure freely',
    'made and freely unmade. A visitor asked how this differed from Kropotkin\u2019s',
    'view. The secretary noted Malatesta thought Kropotkin too trusting of a',
    'benign nature, and steered the room to',
    '<a href="peter-kropotkin.geocities.ws">peter-kropotkin</a> for the other',
    'side.</p>',
    '<p><b>3.4</b> On <i>Umanit&agrave; Nova</i>, the daily paper he founded in 1920',
    'in the ferment of the Italian <i>biennio rosso</i>, the two red years of',
    'factory occupations. When Mussolini came, Malatesta spent his last years under',
    'house arrest and surveillance in Rome, still writing, watched to the end. The',
    'branch observed that he outlived almost every comrade and was buried with the',
    'fascists standing guard over the grave.</p>',
    '<hr>',
    '<p><b>3.5</b> Action agreed. We will read Emma Goldman next, who knew him on',
    'the international circuit, over at',
    '<a href="emma-goldman.geocities.ws">emma-goldman</a>. Meeting closed 9.20pm.</p>',
    '<hr>',
    '<p><small>counter: 00381 · best viewed at 800x600 · the branch, meeting since',
    "'94 · minutes posted 12 Feb</small></p>",
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
  ]);

// ---- The IWW: the ORG / union homepage --------------------------------------

const IWW = P('the-iww.geocities.ws', 'THE IWW',
  'Industrial Workers of the World — One Big Union', [
    '<!--bg:soc-anarchist-->',
    '<h1>Industrial Workers of the World</h1>',
    '<p><small>an information page on the Industrial Workers of the World, the',
    'IWW, the Wobblies. founded 1905, still carrying the red card. this page kept',
    'by fellow workers for anyone who wants to know what the union stands for.',
    'solidarity.</small></p>',
    '<hr>',
    '<p>The IWW was founded in Chicago in June 1905 by socialists, anarchists and',
    'militant unionists who were sick of the craft unions that split workers by',
    'trade and shut out the unskilled, the migrant, the black worker and the',
    'woman. Big Bill Haywood chaired the founding convention. Eugene Debs and',
    "Mother Jones were in the hall, and the veteran Lucy Parsons, widow of a",
    'Haymarket martyr. Their idea was simple and enormous.</p>',
    '<blockquote class="fs-quote"><p>"An injury to one is an injury to all."</p></blockquote>',
    '<p><b>One Big Union.</b> Not a union for printers and another for miners, but',
    'one union for the entire working class, organised by industry, strong enough',
    'to stop the whole economy at once. The Preamble to their constitution put it',
    'without apology.</p>',
    '<pre>',
    '  The working class and the employing class have',
    '  nothing in common.',
    '',
    '  Between these two classes a struggle must go on',
    '  until the workers of the world organize as a class,',
    '  take possession of the means of production, abolish',
    '  the wage system, and live in harmony with the earth.',
    '',
    '  Instead of the conservative motto, "A fair day\'s wage',
    '  for a fair day\'s work," we must inscribe on our banner',
    '  the revolutionary watchword, "Abolition of the wage',
    '  system."',
    '',
    '        — Preamble to the IWW Constitution (1905)',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/soc/iww-01.jpg" alt=""><span class="indie-cap">An IWW poster (public domain)</span>',
    '<p><b>The Little Red Songbook.</b> The Wobblies sang. Their pocket songbook,',
    '<i>Songs to Fan the Flames of Discontent</i>, put class struggle to tunes',
    'everyone knew so a picket line could hold together in the cold. Its greatest',
    'author was Joe Hill, the Swedish-born songwriter who gave the movement "The',
    'Preacher and the Slave" and its mockery of "pie in the sky". Framed for murder',
    'on thin evidence and shot by a Utah firing squad in 1915, Hill sent his last',
    'word to Haywood.</p>',
    '<blockquote class="fs-quote"><p>"Don\u2019t waste any time mourning. Organize!"',
    '&mdash; Joe Hill, 1915</p></blockquote>',
    '<p><b>Free speech and the strikes.</b> The IWW fought the great free-speech',
    'battles in the western towns, filling the jails until the authorities gave',
    'way, and led the huge textile strikes at Lawrence in 1912, remembered as the',
    '"Bread and Roses" strike, and at Paterson in 1913. Emma Goldman stood with',
    'them in the free-speech fights; you can read her at',
    '<a href="emma-goldman.geocities.ws">emma-goldman</a>. And the union\u2019s first',
    'great public voice was Eugene Debs, whose road ran on from here into the',
    'Socialist Party ballot, at <a href="eugene-debs.geocities.ws">eugene-debs</a>.</p>',
    '<p>The war years and the Red Scare brought raids, mass trials and',
    'deportations that broke the union\u2019s strength, but it never dissolved. The',
    'red card is still printed. Fellow workers still sign it.</p>',
    '<hr>',
    '<p><small>counter: 01905 · best viewed at 800x600 · under construction, like',
    'the One Big Union · page last updated 1 May</small></p>',
    '<p><small>[ <a href="socialism-ring.geocities.ws">Socialism Ring</a> ]</small></p>',
  ]);

export const SOC_C = [BAKUNIN, KROPOTKIN, PROUDHON, GOLDMAN, MALATESTA, IWW];
