// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH LIT_F — gothic, romance & the wide world.
//
// Pages a reader or a book-group made about the novelists they loved: a
// note-taker's reading of Frankenstein; a three-sisters shrine to the Brontes;
// a tidy academic summary of Hugo; the minutes of a book-club night on Zola; a
// student's coursework on Hardy; and a write-up of a talk on Wilde. The
// novels, the dates and the lines are real; the handwriting in the margins is
// the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Mary Shelley: book-reading notes on Frankenstein (SHOWPIECE) -----------

const MARY_SHELLEY = P('mary-shelley.geocities.ws', 'MARY SHELLEY',
  'READING NOTES // Frankenstein (1818)', [
    '<!--bg:lit-gothic-->',
    '<h1>Frankenstein; or, The Modern Prometheus</h1>',
    '<p><small>reading notes kept as i go, chapter by chapter, for the Tuesday',
    'book circle. edition on my desk is the 1818 text, not the tidied-up 1831',
    'one. all mistakes mine. — wintermute_reads</small></p>',
    '<hr>',
    '<p class="fs-epi">“Did I request thee, Maker, from my clay<br>',
    'To mould me man? Did I solicit thee<br>',
    'From darkness to promote me?”<br>',
    '<span class="fs-epi-src">— Milton, Paradise Lost; the epigraph Shelley set on her title page</span></p>',
    '<p>First thing the notes have to get right, because everyone gets it wrong at',
    'the pub: FRANKENSTEIN IS THE MAKER, NOT THE MADE. Victor Frankenstein is the',
    'student who builds the thing. The thing he builds has no name. Shelley calls',
    'it the creature, the being, the wretch, the daemon, never the doctor and',
    'never Frankenstein. Two hundred years of posters got the name onto the wrong',
    'body. Hold the line on this.</p>',
    '<p>Mary was eighteen when she began it. She published it anonymously in 1818,',
    'and a good many early readers took it for her husband Percy Shelley’s work,',
    'or for her father William Godwin’s, because the preface was Percy’s and the',
    'dedication was to Godwin. Her name went on the title page in 1831. Keep the',
    '1818 and the 1831 apart when we talk on Tuesday; they are different books in',
    'small important ways.</p>',
    '<div class="fs-aside"><b>How it started: the wet summer of 1816</b><br>',
    'The famous origin. In the summer of 1816, the “Year Without a Summer” after',
    'a volcano the far side of the world darkened the skies, Mary and Percy',
    'Shelley were staying near Lord Byron at the Villa Diodati on Lake Geneva.',
    'The weather kept them indoors reading German ghost stories, and Byron set a',
    'contest: each of them to write a ghost story of their own. Byron’s doctor,',
    'John Polidori, got <i>The Vampyre</i> out of it. Mary, after some nights with',
    'nothing, had the waking dream that became this book. She was the one who',
    'actually finished the assignment.</div>',
    '<img class="indie-pic" src="assets/media/web/lit/mary-shelley-01.jpg" alt=""><span class="indie-cap">Mary Shelley, by Richard Rothwell (public domain)</span>',
    '<p>The shape of the telling is the part i keep having to draw for people, so',
    'here it is as a diagram. It is a story inside a story inside a story, letters',
    'on the outside and a monster’s confession at the very centre:</p>',
    '<pre>',
    '  Robert Walton  --- writes letters home from the Arctic ice',
    '      to his sister, Mrs Margaret Saville (England)',
    '   |',
    '   |  picks up a dying man from the floes, who tells his life:',
    '   v',
    '    Victor Frankenstein  --- narrates his tale to Walton',
    '     |',
    '     |  meets his creature on the glacier, who tells ITS life:',
    '     v',
    '      The Creature  --- narrates its tale to Victor',
    '       |',
    '       |  watches a family through a chink in the wall:',
    '       v',
    '        the De Lacey cottagers  --- the story the Creature learns speech and grief from',
    '</pre>',
    '<p>Everything the Creature knows about being human it learns by spying on the',
    'De Laceys and by reading three books it finds in a bag: Milton’s <i>Paradise',
    'Lost</i>, Plutarch’s <i>Lives</i>, and Goethe’s <i>Sorrows of Young Werther</i>.',
    'It reads <i>Paradise Lost</i> as true history and asks the obvious question:',
    'am I Adam or am I the fallen angel. The epigraph up top is the Creature’s',
    'whole grievance in three lines of Milton.</p>',
    '<blockquote class="fs-quote"><p>“I ought to be thy Adam, but I am rather the',
    'fallen angel, whom thou drivest from joy for no misdeed.”</p>',
    '<p class="fs-quote-src">— the creature to Victor, on the sea of ice</p></blockquote>',
    '<p>The reading the circle should argue about: this is not a book about a',
    'monster who is evil by nature. The creature is born gentle and is made',
    'murderous by being cast out, feared, and refused a companion. The horror is',
    'the abandonment. Victor’s sin is not making life, it is making a life and',
    'then running from it in disgust the moment it opens its eyes. Every death in',
    'the book follows from that flinch.</p>',
    '<p class="fs-pull">“Beware; for I am fearless, and therefore powerful.”</p>',
    '<img class="indie-pic" src="assets/media/web/lit/frankenstein-01.jpg" alt=""><span class="indie-cap">The 1818 title page of Frankenstein (public domain)</span>',
    '<p>So the Modern Prometheus of the subtitle is Victor, who steals a fire he',
    'cannot control, though Shelley leaves it teasingly open whether the theft is',
    'the crime or the cowardice after it is the crime. Science and hubris, yes,',
    'but read it and the hubris is a father’s, not a chemist’s. Questions to',
    'bring Tuesday: is Walton warned off his own polar obsession in time? does the',
    'creature really mean to die at the end, or is that Walton’s guess? and why',
    'does Shelley give the monster the best prose in the book.</p>',
    '<hr>',
    '<p>If you liked this, the circle also did the moor-and-madwoman gothic of the',
    'Brontes, notes at <a href="the-brontes.geocities.ws">the-brontes</a>, and the',
    'other end of the century, the cool aesthetes and the picture that ages instead',
    'of the man, is over at <a href="oscar-wilde.geocities.ws">oscar-wilde</a>.</p>',
    '<hr>',
    '<p><small>counter: 01818 · best viewed at 800x600 · this page is under',
    'construction, more chapters as i read them · last updated 31 Oct</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- The Brontes: personal fan shrine ---------------------------------------

const THE_BRONTES = P('the-brontes.geocities.ws', 'THE BRONTES',
  'THREE SISTERS, ONE PARSONAGE // a Bronte shrine', [
    '<!--bg:lit-gothic-->',
    '<h1>Three sisters, one parsonage</h1>',
    '<p><small>i have loved these three since i was fifteen and read Jane Eyre',
    'under the desk in a maths lesson. this is my shrine to them. yes i have been',
    'to Haworth. yes i cried on the moor. i am not ashamed. — cathy_on_the_moor</small></p>',
    '<hr>',
    '<p>Charlotte, Emily and Anne Bronte grew up in the parsonage at Haworth, up',
    'on the West Yorkshire moors, with their brother Branwell and a father who was',
    'the curate. Their mother died early, two elder sisters died in childhood, and',
    'the three who were left made whole imaginary kingdoms together, Angria and',
    'Gondal, scribbled in tiny handwriting in tiny books. The moor is not a',
    'backdrop in the novels, it is a character, and it is a real place you can',
    'still walk out into and freeze on.</p>',
    '<p>In 1846 they published a book of poems as <b>Currer, Ellis and Acton',
    'Bell</b>. They kept their own initials but hid the fact they were women,',
    'because, as Charlotte put it later, they had a vague notion that authoresses',
    'were looked on with prejudice. The book sold two copies. TWO. Do not let this',
    'discourage you about anything you are making.</p>',
    '<hr>',
    '<p><b>JANE EYRE (1847), by Currer = Charlotte</b></p>',
    '<p>My first and forever favourite. Plain, poor, orphaned Jane goes to be a',
    'governess at Thornfield, falls for her brooding employer Mr Rochester, and',
    'gets to the altar before she learns what is locked on the third floor:',
    'Bertha Mason, Rochester’s living wife, the madwoman in the attic who has been',
    'setting those fires. Jane walks away rather than be a mistress, half starves',
    'on the moor, and comes back only when she can come back free. The line',
    'everyone knows, and it earns it:</p>',
    '<blockquote class="fs-quote"><p>“Reader, I married him.”</p>',
    '<p class="fs-quote-src">— Jane Eyre, opening the last chapter</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/lit/brontes-01.jpg" alt=""><span class="indie-cap">The Bronte sisters, by Branwell Bronte (public domain)</span>',
    '<p><b>WUTHERING HEIGHTS (1847), by Ellis = Emily</b></p>',
    '<p>Not a love story. People call it a love story and then read it and go very',
    'quiet. Heathcliff, brought home a foundling, and Catherine Earnshaw ruin each',
    'other and half the next generation with a passion that is closer to weather',
    'than to tenderness. Catherine’s “I am Heathcliff” is not romantic, it is',
    'frightening. The whole thing is told at two removes, by the housekeeper Nelly',
    'Dean to the tenant Mr Lockwood, so you never quite get to stand in the room.',
    'Emily wrote one novel and it is a thunderclap.</p>',
    '<p><b>THE TENANT OF WILDFELL HALL (1848), by Acton = Anne</b></p>',
    '<p>The one people skip, and they are wrong to. Anne is the clear-eyed one.',
    'Her Helen leaves a drunk and abusive husband and supports herself by painting,',
    'which in 1848 was close to scandalous, and Anne meant it to be. <i>Agnes Grey</i>',
    'is the quieter governess book. Do not believe anyone who tells you Anne is the',
    'lesser sister; she is just the least gothic and the most honest about how bad',
    'a bad marriage actually is.</p>',
    '<hr>',
    '<p>And then it fell apart fast. Branwell went first, then Emily caught cold at',
    'his funeral and would not see a doctor and was dead by Christmas 1848, then',
    'Anne the next spring. Charlotte outlived them all, wrote <i>Villette</i> and',
    '<i>Shirley</i> alone in the emptied house, married at last, and died in 1855.',
    'When you stand in the parsonage you are standing in a house that buried nearly',
    'everyone in it inside a decade.</p>',
    '<p>Where next: for the book that half-invented this whole moor-and-dread mood',
    'a generation before, see the Frankenstein notes at',
    '<a href="mary-shelley.geocities.ws">mary-shelley</a>. And for the same wild',
    'English country turned bleak and modern and doomed, the Hardy page at',
    '<a href="thomas-hardy.geocities.ws">thomas-hardy</a> is the sad next stop.</p>',
    '<hr>',
    '<p><small>visitors: 02310 · best viewed at 800x600 · signed in the guestbook',
    'by every Bronte pilgrim who found me · last updated 14 Feb</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Victor Hugo: academic summary ------------------------------------------

const VICTOR_HUGO = P('victor-hugo.geocities.ws', 'VICTOR HUGO',
  'Victor Hugo (1802-1885) // a summary', [
    '<!--bg:lit-gothic-->',
    '<h1>Victor Hugo: the Romantic conscience</h1>',
    '<p><small>a plain summary page, kept for students and reading groups who want',
    'the shape of Hugo before they open the big books. compiled from the standard',
    'lives; corrections welcome.</small></p>',
    '<hr>',
    '<p>Victor Hugo (1802–1885) was the towering figure of French Romanticism:',
    'poet, novelist, dramatist, and by the end a political conscience for a whole',
    'nation. His preface to the play <i>Cromwell</i> (1827) is often taken as the',
    'manifesto of the movement, arguing that art should hold the grotesque and the',
    'sublime together rather than keep to the polite proportions of the classical',
    'stage. He wrote for six decades and buried the classical rules while doing it.</p>',
    '<p><b>Notre-Dame de Paris (1831).</b> Known in English as <i>The Hunchback of',
    'Notre-Dame</i>, though the French title puts the cathedral first, and that is',
    'the point: the building is the protagonist. Quasimodo the bell-ringer,',
    'Esmeralda the dancer, and the archdeacon Frollo move through a medieval Paris',
    'Hugo reconstructs stone by stone. The novel was partly written to shame his',
    'contemporaries into preserving Gothic architecture they were letting fall',
    'down, and it worked.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/hugo-01.jpg" alt=""><span class="indie-cap">Victor Hugo (photo: Etienne Carjat, public domain)</span>',
    '<p><b>Les Miserables (1862).</b> The vast one. Jean Valjean, imprisoned',
    'nineteen years for stealing a loaf, is shown mercy by a bishop, breaks parole,',
    'remakes himself as an honest man, and is hunted across the decades by the',
    'policeman Javert, for whom the law and justice are the same thing until the',
    'day they are not. Around them Hugo builds the doomed girl Fantine, her',
    'daughter Cosette, the street boy Gavroche, and the students at the barricade',
    'in the June Rebellion of 1832. The famous digressions, on the Battle of',
    'Waterloo, on the argot of thieves, and the long descent into the sewers of',
    'Paris where Valjean carries a wounded man through the filth, are not padding;',
    'Hugo means the book to hold a whole society, the low places included.</p>',
    '<div class="fs-aside"><b>The exile</b><br>',
    'When Louis-Napoleon seized power and made himself Emperor in 1851, Hugo, a',
    'deputy who opposed him, fled France and settled in the Channel Islands,',
    'mostly on Guernsey at Hauteville House. He stayed away nearly twenty years, on',
    'principle, refusing an amnesty, and wrote much of his greatest work in exile,',
    'including <i>Les Miserables</i>. He returned only when the Empire fell in 1870.',
    'When he died in 1885 two million people followed the coffin and he was laid in',
    'the Pantheon.</div>',
    '<p>The verse should not be forgotten behind the novels. <i>Les Contemplations</i>',
    '(1856), the grief-struck poems after his daughter Leopoldine drowned, and the',
    'epic <i>La Legende des siecles</i> are central to why the French rank him',
    'first of all as a poet. English readers, who mostly meet him through the',
    'novels and the musical, tend to miss this.</p>',
    '<p>Related pages in the ring: Hugo’s younger countryman turned the Romantic',
    'sympathy for the poor into a colder, more clinical naturalism, summarised at',
    '<a href="emile-zola.geocities.ws">emile-zola</a>. And for the gothic strain',
    'that runs alongside French Romanticism, the Frankenstein notes are at',
    '<a href="mary-shelley.geocities.ws">mary-shelley</a>.</p>',
    '<hr>',
    '<p><small>counter: 01802 · best viewed at 800x600 · last updated 9 Mar</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Emile Zola: reading-group minutes --------------------------------------

const EMILE_ZOLA = P('emile-zola.geocities.ws', 'EMILE ZOLA',
  'Book Club minutes // Germinal (Zola)', [
    '<!--bg:lit-gothic-->',
    '<h1>Thursday Book Club: minutes</h1>',
    '<p><small>the Thursday club, upstairs room, eleven present, two apologies.',
    'book of the month: <i>Germinal</i> (1885) by Emile Zola. minute-taker: R.',
    'biscuits: P. next month’s book decided at the end, see below.</small></p>',
    '<hr>',
    '<p><b>1. Opening.</b> We agreed to start with the book and save the wine for',
    'after, which lasted about ten minutes. Germinal, everyone concurred, is the',
    'one that actually hurts to read, in a good way. It follows Etienne Lantier,',
    'an out-of-work mechanic, who takes a job at the Le Voreux pit in the coal',
    'country of northern France and is pulled into a miners’ strike that starves',
    'and breaks the very people it was meant to save.</p>',
    '<p><b>2. The mine as a monster.</b> M. pointed out that Zola writes the pit',
    'like a living beast that eats men, “crouching” and swallowing its workers down',
    'each morning. Le Voreux even sounds like <i>le vorace</i>, the devourer. We',
    'talked about the scene where the flooded mine collapses and traps Etienne and',
    'Catherine underground, which two members admitted they had to put down and',
    'come back to.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/zola-01.jpg" alt=""><span class="indie-cap">Emile Zola (Nadar studio, public domain)</span>',
    '<p><b>3. Where it sits in the big scheme.</b> S. reminded us that Germinal is',
    'one novel of twenty in the <b>Rougon-Macquart cycle</b>, which Zola subtitled',
    'the “Natural and Social History of a Family under the Second Empire”. The plan',
    'was scientific in ambition: follow one bloodline down two branches, the',
    'respectable Rougons and the ruined Macquarts, across French society, and show',
    'heredity and environment working on them like laws. Etienne is a Macquart, and',
    'the drink and the violence in the blood is meant to be part of why the ending',
    'goes as it does. Other novels of the cycle came up: <i>L’Assommoir</i> on',
    'drink and the slums, <i>Nana</i> on the courtesan, and <i>La Bete humaine</i>',
    'on the railways and murder.</p>',
    '<p><b>4. Naturalism, and did we buy it.</b> A real argument here. Zola called',
    'his method naturalism and even wrote an essay, <i>Le Roman experimental</i>,',
    'claiming the novelist should work like a scientist running an experiment on',
    'his characters. J. thought this was a bit much and that the great scenes are',
    'great because Zola is a poet of crowds, not because his heredity theory is',
    'sound. R. defended the method as at least honest about wanting to put the',
    'working poor on the page as they actually lived, which the polite novel had',
    'not done. We did not settle it. Minute-taker notes that we rarely do.</p>',
    '<div class="fs-aside"><b>5. The other Zola: J’accuse.</b><br>',
    'P. insisted we spend ten minutes on it and was right to. In 1898, at the',
    'height of the Dreyfus affair, Zola published an open letter, <i>J’accuse…!</i>,',
    'on the front page of the newspaper <i>L’Aurore</i>, accusing the French army',
    'of framing Captain Alfred Dreyfus and covering it up because Dreyfus was a',
    'Jew. Zola was convicted of libel for it and fled to England for a year to',
    'avoid prison. The club agreed this is of a piece with the novels: the same',
    'man who put the miners on the page put his own liberty on the line for a',
    'wronged stranger.</div>',
    '<p><b>6. Any other business.</b> Next month, to stay in the same wild English',
    'landscape as our earlier read, we chose Hardy; notes and edition details are',
    'on the student page at <a href="thomas-hardy.geocities.ws">thomas-hardy</a>.',
    'For the grand Romantic ancestor of the French social novel, several of us',
    'want to revisit Hugo at <a href="victor-hugo.geocities.ws">victor-hugo</a>',
    'before the summer. Meeting closed 9.40pm.</p>',
    '<hr>',
    '<p><small>counter: 00885 · best viewed at 800x600 · minutes kept since the',
    'club began · page last updated 22 Apr</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Thomas Hardy: student coursework ---------------------------------------

const THOMAS_HARDY = P('thomas-hardy.geocities.ws', 'THOMAS HARDY',
  'ENG240 coursework // Hardy and the indifferent universe', [
    '<!--bg:lit-gothic-->',
    '<h1>Hardy and the indifferent universe</h1>',
    '<p><small>ENG240 The Victorian Novel, essay 2, submitted work put up on my own',
    'page because i was quite pleased with the mark. do not copy it, tutors read',
    'these too. — s.p., second year</small></p>',
    '<hr>',
    '<p>This essay argues that the central figure in Thomas Hardy (1840–1928) is',
    'not a person but a universe that does not care. Where the earlier Victorians',
    'let Providence tidy up the plot, Hardy hands the plot to chance, coincidence',
    'and bad timing, and lets it crush people who did nothing to deserve it. His',
    'novels are mostly set in <b>Wessex</b>, a half-imaginary version of the real',
    'south-west of England, Dorset above all, with Dorchester renamed Casterbridge',
    'and the old heaths and hills given new names. Wessex feels solid because Hardy',
    'built it from a countryside he actually knew.</p>',
    '<p><b>Tess of the d’Urbervilles (1891).</b> Hardy gave it the subtitle “A',
    'Pure Woman Faithfully Presented” and knew exactly how much trouble the word',
    'pure would cause. Tess Durbeyfield, a poor country girl, is seduced or',
    'assaulted (Hardy keeps it deliberately unclear) by Alec d’Urberville, loses',
    'the resulting child, finds a purer love with Angel Clare, and is abandoned by',
    'him on their wedding night when she confesses the past he had just confessed a',
    'worse version of. The book ends at Stonehenge and the gallows. Hardy’s most',
    'quoted, most bitter sentence closes it:</p>',
    '<blockquote class="fs-quote"><p>“the President of the Immortals, in Aeschylean',
    'phrase, had ended his sport with Tess.”</p>',
    '<p class="fs-quote-src">— Tess of the d’Urbervilles, final chapter</p></blockquote>',
    '<p>The gods, if there are any, are playing, and we are the toys. That is the',
    'whole Hardy universe in one line, and it is why he unsettled his first readers',
    'so badly. Providence has left the building.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/hardy-01.jpg" alt=""><span class="indie-cap">Thomas Hardy (public domain)</span>',
    '<p><b>Jude the Obscure (1895).</b> The last and darkest novel. Jude Fawley, a',
    'poor stonemason, dreams of the university at Christminster (Oxford) and is',
    'shut out by class; he loves his cousin Sue Bridehead, they live together',
    'unmarried against the whole weight of the age, and the book grinds them down',
    'to one of the most harrowing scenes in English fiction. The critics were',
    'savage, some calling it “Jude the Obscene” and one bishop reportedly burning',
    'the book. Hardy, wounded by the outcry, gave up the novel altogether.</p>',
    '<p><b>The turn to poetry.</b> After Jude, Hardy wrote no more novels and spent',
    'the last thirty years of his life as a poet, publishing <i>Wessex Poems</i>',
    '(1898) and much more. Many now think the poetry is his finest work, plain and',
    'clear-eyed and haunted by his dead first wife. The move is telling: the man',
    'who could not soften his vision for the novel-reading public turned to the',
    'form where he answered to no one.</p>',
    '<p><b>Wonky bibliography</b> (as submitted, tutor said tidy this up):</p>',
    '<pre>',
    '  Hardy, T. -- Far from the Madding Crowd, 1874',
    '  Hardy, T. -- The Return of the Native, 1878 (Egdon Heath!)',
    '  Hardy, T. -- The Mayor of Casterbridge, 1886',
    '  Hardy, T. -- Tess of the durbervilles, 1891   [check the apostrophe]',
    '  Hardy, T. -- Jude the Obscure, 1895',
    '  Hardy, T. -- Wessex Poems, 1898',
    '  + lecture notes, wk 6, on chance & coincidence in H.',
    '</pre>',
    '<p>Cross-reading for the module: the Bronte moors are the Romantic version of',
    'this same wild country, see <a href="the-brontes.geocities.ws">the-brontes</a>,',
    'and for the continental naturalism that Hardy is sometimes bracketed with, the',
    'book-club notes on Zola are at <a href="emile-zola.geocities.ws">emile-zola</a>.</p>',
    '<hr>',
    '<p><small>counter: 00240 · best viewed at 800x600 · under construction, essay 3',
    'on the poetry to follow · last updated 5 May</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Oscar Wilde: talk write-up ---------------------------------------------

const OSCAR_WILDE = P('oscar-wilde.geocities.ws', 'OSCAR WILDE',
  'Talk write-up // Wilde: the wit and the gaol', [
    '<!--bg:lit-gothic-->',
    '<h1>Wilde: the wit and the gaol</h1>',
    '<p><small>notes from a public talk given at the local literary society last',
    'week, “Oscar Wilde: the wit and the gaol”, speaker was a retired lecturer.',
    'i wrote it up from my scribbles for those who missed it. any errors are in my',
    'notes, not the talk.</small></p>',
    '<hr>',
    '<p>The speaker began where everyone begins, with the epigrams, the polished',
    'one-liners Wilde (1854–1900) dropped into every play and drawing room. She',
    'read us a handful and let them land before saying anything clever herself:</p>',
    '<blockquote class="fs-quote"><p>“I can resist everything except temptation.”</p>',
    '<p class="fs-quote-src">— Lord Darlington, Lady Windermere’s Fan</p></blockquote>',
    '<p>Her point was that the epigram is not just decoration. It is Wilde’s whole',
    'method: take a piety the Victorians held dear, turn it exactly upside down, and',
    'watch it still ring true the other way up. The wit is a way of thinking, not a',
    'garnish on it.</p>',
    '<p><b>The aesthete.</b> She set Wilde inside aestheticism, art for art’s sake,',
    'the idea that beauty needs no moral excuse and that art should not be made to',
    'teach us to be good. His preface to <i>The Picture of Dorian Gray</i> ends',
    'flatly, “All art is quite useless”, and he meant it as a defence, not a',
    'confession. Beauty owes us nothing, which in a preachy age was close to a',
    'provocation.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/wilde-01.jpg" alt=""><span class="indie-cap">Oscar Wilde (photo: Napoleon Sarony, public domain)</span>',
    '<p><b>The Picture of Dorian Gray (1890, expanded 1891).</b> His only novel and',
    'the hinge of the talk. Dorian, painted in his beauty by Basil Hallward and',
    'schooled in pleasure by the languid Lord Henry Wotton, wishes the portrait',
    'would age in his place. It does. He stays young and unmarked while the picture,',
    'hidden in the attic, takes on every cruelty and corruption, growing hideous in',
    'his stead. The speaker drew the obvious and correct line to the trials to come:',
    'here is a book about a beautiful life with a horror locked upstairs, written by',
    'a man who was about to be dragged through the same doubling in a courtroom.</p>',
    '<p><b>The plays.</b> She reminded us that at the very height of his fame, in the',
    'mid-1890s, Wilde had the comedies running to packed houses: <i>Lady',
    'Windermere’s Fan</i>, <i>An Ideal Husband</i>, and the perfect one, <i>The',
    'Importance of Being Earnest</i> (1895), which she called a play about nothing,',
    'built entirely out of wit, and none the worse for it. He was, for one season,',
    'the most successful playwright in London.</p>',
    '<div class="fs-aside"><b>The trial and Reading Gaol</b><br>',
    'Then the fall, told plainly and without relish, which the speaker said the',
    'story does not need. In 1895 Wilde sued the father of his lover Lord Alfred',
    'Douglas for criminal libel, lost, and was himself prosecuted and convicted of',
    '“gross indecency” under the law of the day. He was sentenced to two years’',
    'hard labour and served most of it in Reading Gaol. Out of that came the long',
    'letter <i>De Profundis</i> and, after his release, <i>The Ballad of Reading',
    'Gaol</i> (1898), on a hanging he witnessed there. Broken and bankrupt, he',
    'died in a Paris hotel in 1900, aged forty-six.</div>',
    '<p>She closed on the double life the work now reads by, the surface all wit and',
    'the underside all cost, and took questions. Two threads for further reading',
    'she named: for the gothic bargain of a portrait that carries the sin, the',
    'grandparent is the Frankenstein tradition at',
    '<a href="mary-shelley.geocities.ws">mary-shelley</a>; and for the grand',
    'continental Romantic against whom the English aesthetes were a cooler, later',
    'reaction, see <a href="victor-hugo.geocities.ws">victor-hugo</a>.</p>',
    '<hr>',
    '<p><small>counter: 01854 · best viewed at 800x600 · write-up of the 3rd Nov',
    'talk · page last updated 8 Nov</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

export const LIT_F = [MARY_SHELLEY, THE_BRONTES, VICTOR_HUGO, EMILE_ZOLA, THOMAS_HARDY, OSCAR_WILDE];
