// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — the institutions of film.
//
// The repertory-house end of the cineaste web: a movement, a cinematheque, a
// festival, two techniques and the critic. Pages made by a film society, a
// preservation-minded programmer and a couple of cinema-studies students, all
// canon-minded and reverent about the image. The directors, films, dates and
// techniques are real; the hit counters, the handles and the reverence are the
// fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Italian neorealism: the movement primer (SHOWPIECE) --------------------

const NEOREALISM = P('italian-neorealism.geocities.ws', 'NEOREALISM',
  'ITALIAN NEOREALISM // cinema in the rubble', [
    '<!--bg:cine-institution-->',
    '<h1>ITALIAN NEOREALISM</h1>',
    '<p><small>the primer page of the Wednesday Film Society, kept so we do not',
    'have to explain it again at the door. cinema went out into the street and',
    'came back changed. everything below is on the study sheet. — the programmer</small></p>',
    '<p class="fs-epi">"You do not make a film to say something, you make a film',
    'because you have seen something." — attributed in the society to Cesare Zavattini</p>',
    '<hr>',
    '<p>Neorealism is the Italian cinema of the late 1940s that put down the',
    'studio and the star and walked out into the bombed streets. The war had',
    'wrecked Cinecitta, the money was gone, and a handful of film-makers turned',
    'the poverty into a method. Real locations. Available light. Ordinary people',
    'in front of the camera instead of professional actors. Stories about work,',
    'hunger, rent and the day after the liberation. The screen learnt to look at',
    'the poor without arranging them into a moral.</p>',
    '<p>The usual first date is 1945, when Roberto Rossellini shot <i>Rome, Open',
    'City</i> (<i>Roma citta aperta</i>) partly on the street while the Germans',
    'had barely left, on whatever stock he could buy, and the roughness became',
    'the truth of it. Anna Magnani running after the truck is one of the images',
    'the century keeps. Rossellini followed it with <i>Paisan</i> (1946) and',
    '<i>Germany Year Zero</i> (1948), the war trilogy that took the method up',
    'through Italy and into the ruins of Berlin.</p>',
    '<p class="fs-pull">The camera left the studio and did not want to go back.</p>',
    '<p>The film most people mean when they say neorealism is Vittorio De Sica\'s',
    '<i>Bicycle Thieves</i> (<i>Ladri di biciclette</i>, 1948), written with',
    'Cesare Zavattini, who was the theorist of the group as much as its writer.',
    'A man in postwar Rome gets a job that needs a bicycle, the bicycle is',
    'stolen, and he walks the city with his small son looking for it. That is the',
    'whole plot, and that is the point. Zavattini wanted cinema to follow a man',
    'for the ninety minutes in which nothing "happens", because in those minutes',
    'a whole society is visible. De Sica cast a factory worker, Lamberto',
    'Maggiorani, in the lead, and the boy, Enzo Staiola, he found on the street.</p>',
    '<blockquote class="fs-quote"><p>"My films are a struggle against the absence',
    'of human solidarity. In <i>Bicycle Thieves</i> everyone is responsible."</p>',
    '<p><small>— Vittorio De Sica, as the society has it on the study sheet</small></p></blockquote>',
    '<p>De Sica had done it a year before the war ended in feeling with <i>The',
    'Children Are Watching Us</i> (1943), and would go on to <i>Umberto D.</i>',
    '(1952), the old pensioner and his dog, which Zavattini thought the purest',
    'thing they ever managed. Around them Luchino Visconti made <i>Ossessione</i>',
    '(1943), often called the first stirring, and <i>La Terra Trema</i> (1948),',
    'shot in Sicily with the fishermen playing themselves and speaking their own',
    'dialect. Giuseppe De Santis brought a rougher, more popular edge with',
    '<i>Bitter Rice</i> (1949).</p>',
    '<img class="indie-pic" src="assets/media/web/cine/film-reel-01.jpg" alt=""><span class="indie-cap">Rolls of celluloid film (photo: Marcel Oosterwijk, CC BY-SA 2.0)</span>',
    '<p class="fs-aside"><b>Did you know.</b> There was almost no such thing as a',
    'neorealist "script" in the studio sense. Zavattini argued for the',
    '<i>pedinamento</i>, the shadowing, the idea that the camera should simply',
    'follow a real person through real time. The dream, which he never quite got',
    'to make, was ninety minutes in the life of a man to whom nothing at all',
    'happens. He thought that would be the truest film ever shot.</p>',
    '<p>Why it mattered beyond Italy is simple. Every new wave that followed took',
    'something from it. The French critics at <i>Cahiers</i> built half their',
    'theory on Rossellini. Satyajit Ray saw <i>Bicycle Thieves</i> in London and',
    'went home to make the Apu Trilogy on location in Bengal. The method,',
    'location, non-actors, small lives filmed with respect, travelled everywhere',
    'a young cinema wanted to break from the studio. The rubble was Italian, the',
    'lesson was portable.</p>',
    '<pre>',
    'A ROUGH TIMELINE (society study sheet)',
    '  1943  Visconti, Ossessione            first stirrings',
    '  1943  De Sica, The Children Are Watching Us',
    '  1945  Rossellini, Rome Open City      the opening shot of it all',
    '  1946  Rossellini, Paisan',
    '  1948  De Sica, Bicycle Thieves        the one everybody names',
    '  1948  Visconti, La Terra Trema        the fishermen, their own dialect',
    '  1948  Rossellini, Germany Year Zero   the method taken to Berlin',
    '  1949  De Santis, Bitter Rice          the popular, rougher edge',
    '  1952  De Sica, Umberto D.             Zavattini thought it the purest',
    '  1954  Fellini, La Strada              the movement passing into something else',
    '</pre>',
    '<pre>',
    'THE ESSENTIAL TEN (start here, in this order)',
    '   1. Rome, Open City            Rossellini   1945',
    '   2. Bicycle Thieves            De Sica      1948',
    '   3. Umberto D.                 De Sica      1952',
    '   4. La Terra Trema             Visconti     1948',
    '   5. Paisan                     Rossellini   1946',
    '   6. Germany Year Zero          Rossellini   1948',
    '   7. Shoeshine                  De Sica      1946',
    '   8. Ossessione                 Visconti     1943',
    '   9. Bitter Rice                De Santis    1949',
    '  10. Europe \'51                 Rossellini   1952',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/cine/film-projector-01.jpg" alt=""><span class="indie-cap">A 1930s 35mm film projector (photo: YellowFratello, CC BY-SA 4.0)</span>',
    '<p>Where the argument about it is kept, and where it was preserved.',
    'The critics who first defended it, Andre Bazin above all, are gathered at',
    '<a href="the-film-critic.geocities.ws">the-film-critic</a>, and Bazin loved',
    'these films for exactly the reason some found them dull, that they refused to',
    'cut the world into a lesson. The prints themselves survived because',
    'institutions chose to keep them, which is the story told at',
    '<a href="the-cinematheque.geocities.ws">the-cinematheque</a>. In plain text',
    'for the newcomers, because they are off our little ring: read Zavattini\'s',
    '"Some Ideas on the Cinema" (1953), and if you want the American translation',
    'of the enthusiasm, Pauline Kael wrote well about De Sica.</p>',
    '<hr>',
    '<p><small>you are visitor 03612 · best viewed in Netscape at 800x600 ·',
    'the Wednesday Film Society, upstairs at the Roxy · last updated 14 Oct ·',
    'a cineaste webring page, members welcome</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- The Cinematheque: an ORG / place page ----------------------------------

const CINEMATHEQUE = P('the-cinematheque.geocities.ws', 'CINEMATHEQUE',
  'THE CINEMATHEQUE // Langlois kept the reels', [
    '<!--bg:cine-institution-->',
    '<h1>THE CINEMATHEQUE</h1>',
    '<p><small>notes for the preservation table at our society, on the place that',
    'taught us why a print is worth saving even before anyone can say why. kept',
    'by the member who does the film-can inventory. — R.T.</small></p>',
    '<hr>',
    '<p>A cinematheque is a film archive with a screen attached. It keeps prints,',
    'it repairs them, and it shows them, and that last part is the argument. The',
    'model for all of them is the Cinematheque Francaise in Paris, and the model',
    'for how to run one, and how to fight for one, is Henri Langlois.</p>',
    '<p>Langlois (1914 to 1977) co-founded the Cinematheque in 1936 with Georges',
    'Franju. His method was not tidy. Where the tidy archivists of the day argued',
    'about which films were worth keeping, Langlois kept everything, on the sound',
    'principle that you cannot know now what a later century will need. During the',
    'occupation he and his circle hid reels from the Germans, who were happy to',
    'let nitrate film "disappear". A great deal of early cinema exists at all',
    'because one obsessive would not throw the cans away.</p>',
    '<p class="fs-pull">He kept everything, on the principle that you cannot yet',
    'know what the future will want to watch.</p>',
    '<p>Then he showed it, cheaply, constantly, in no respectable order. A silent',
    'comedy next to a new American thriller next to a German expressionist',
    'nightmare. Young Parisians in the 1950s more or less lived in his seats, and',
    'those young people were Francois Truffaut, Jean-Luc Godard, Jacques Rivette,',
    'Claude Chabrol, Eric Rohmer. They watched more cinema, and more different',
    'cinema, than any generation before them, and then they went and made the',
    'French New Wave. The screen was their university.</p>',
    '',
    '<p class="fs-aside"><b>The 1968 affair.</b> In February 1968 the government,',
    'through the culture ministry, moved to remove Langlois from the Cinematheque',
    'he had built. The film world detonated. Directors from around the world,',
    'Chaplin, Kurosawa, Welles among them, withdrew the rights to show their films',
    'in protest. There were demonstrations in the street and police outside the',
    'building. Within weeks Langlois was reinstated. Some read the Langlois affair',
    'as a rehearsal for the larger upheaval of May 1968 that shut the country down',
    'a few months later.</p>',
    '<p>What the Cinematheque stands for, and what every cinematheque since has',
    'inherited, is a claim that runs against the market. A film is not only a',
    'product that earns its keep in its opening fortnight and then goes dark. It',
    'is a work that a culture should be able to see again, in a cinema, on a print,',
    'for as long as the culture lasts. Preservation is not nostalgia. It is the',
    'decision to keep the past watchable.</p>',
    '<p>Where the movement they preserved is set out, see',
    '<a href="italian-neorealism.geocities.ws">italian-neorealism</a>, whose',
    'prints survived because places like this refused to let them rot. And for the',
    'other great public institution of film, the one that makes reputations rather',
    'than keeping them, see <a href="the-film-festival.geocities.ws">the-film-festival</a>.',
    'Off our ring, in plain text: Iris Barry did the same founding work at the',
    'film library of the Museum of Modern Art in New York, and deserves the credit',
    'as much as Langlois does.</p>',
    '<hr>',
    '<p><small>counter 01188 · best viewed at 800x600 · handle the reels with',
    'cotton gloves · page last tended 22 Sep · a member of the cineaste webring</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- The Film Festival: an ORG / scene page ---------------------------------

const FESTIVAL = P('the-film-festival.geocities.ws', 'FILM FESTIVAL',
  'THE FILM FESTIVAL // Cannes, Venice, the red carpet', [
    '<!--bg:cine-institution-->',
    '<h1>THE FILM FESTIVAL</h1>',
    '<p><small>a field guide for society members going to their first festival, so',
    'they do not stand in the wrong queue. what the prizes mean and where they come',
    'from. — the festival correspondent (one trip to Venice, never shuts up about it)</small></p>',
    '<hr>',
    '<p>A film festival is where a film is born in public. It premieres, a jury',
    'weighs it, critics file overnight, buyers make offers in the corridors, and a',
    'reputation is made or missed in a week. Three festivals sit above the rest,',
    'and it helps to know what each one is.</p>',
    '<p><b>Venice</b> is the oldest, founded in 1932 as part of the Biennale, which',
    'makes it the senior festival of the world. Its top prize is the Golden Lion',
    '(<i>Leone d\'Oro</i>). It has the grand setting, the Lido, the long history and,',
    'in its earliest years, a compromised one, since it began under the Fascist',
    'regime before the war remade it.</p>',
    '<p><b>Cannes</b> was conceived in the late 1930s partly in reaction to that',
    'politicised Venice, and after the war it opened properly in 1946 and became the',
    'centre of gravity of world cinema. Its top prize was called the Grand Prix for',
    'years and then, from 1955, the Palme d\'Or, the golden palm, which is now the',
    'single most coveted award a film can win outside the Oscars, and to many',
    'serious viewers more coveted than those. Cannes is also the largest film market',
    'on earth, so the art and the money stand in the same room and pretend not to',
    'notice each other.</p>',
    '<p class="fs-pull">A festival is two things at once, a temple and a trade fair,',
    'and it never decides which.</p>',
    '<p><b>Berlin</b>, the Berlinale, started in 1951 in a divided city, on the',
    'Cold War fault line, and it has always carried a more political charge. Its',
    'prize is the Golden Bear (<i>Goldener Bar</i>). Between them, Venice in',
    'late summer, Cannes in May, Berlin in February, the three set the calendar of',
    'the art-cinema year.</p>',
    '<img class="indie-pic" src="assets/media/web/cine/cinema-facade-01.jpg" alt=""><span class="indie-cap">A cinema facade and marquee (photo: PortlandAppraisalBlog, CC BY-SA 4.0)</span>',
    '<p class="fs-aside"><b>What a jury actually does.</b> A festival jury is a',
    'small panel, often chaired by a famous director or actor, that watches the',
    'films in competition and awards the prizes. It is not a vote of critics and it',
    'is not the box office. It is a handful of people in a room, which is why the',
    'results can be perverse, inspired, or a scandal, sometimes in the same year. A',
    'Palme d\'Or can make a small film from an unknown country into a world event',
    'overnight, and has, many times.</p>',
    '<p>The festival matters because it is one of the few places where a difficult',
    'film from a small cinema can be seen before the market has decided whether it',
    'is allowed to exist. A premiere at Cannes or Venice buys a film attention that',
    'no advertising could, and for a first-time director from far outside Hollywood',
    'it can be the whole difference. The red carpet is the part on television. The',
    'part that counts is the screening the morning after, half empty, where the',
    'critics decide what the film is.</p>',
    '<p>For the archive that keeps films watchable long after their festival week is',
    'over, see <a href="the-cinematheque.geocities.ws">the-cinematheque</a>. For the',
    'writers who file those overnight verdicts and turn them into lasting judgement,',
    'see <a href="the-film-critic.geocities.ws">the-film-critic</a>. Off the ring, in',
    'plain text: Sundance and Toronto matter enormously too, the first for American',
    'independents, the second as the launch pad into the awards season.</p>',
    '<hr>',
    '<p><small>you are guest 00947 · best viewed in Netscape at 800x600 · bring',
    'comfortable shoes and a raincoat · updated 3 Nov · cineaste webring member</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- The Montage: a technique page ------------------------------------------

const MONTAGE = P('the-montage.geocities.ws', 'MONTAGE',
  'THE MONTAGE // the cut is the meaning', [
    '<!--bg:cine-institution-->',
    '<h1>THE MONTAGE</h1>',
    '<p><small>CIN 210, Film Form and Technique, my own revision notes on editing,',
    'shared because a coursemate asked and it saves me writing it twice. corrections',
    'welcome, i am only a second-year. — study handle: splice_girl</small></p>',
    '<hr>',
    '<p>Montage is the French word for editing, the joining of shots. In film',
    'theory it means something stronger than "cutting the boring bits out". It',
    'means that meaning is made at the join, in the collision of one shot against',
    'the next, and that the cut is not a break in the film but the place where the',
    'film thinks.</p>',
    '<p><b>The Kuleshov effect.</b> The founding experiment. Around 1918 the Soviet',
    'film-maker Lev Kuleshov took a single neutral shot of an actor\'s face and',
    'intercut it, so the story goes, with a bowl of soup, then a coffin, then a',
    'child. Audiences praised the actor for showing hunger, then grief, then',
    'tenderness. The face never changed. The meaning came entirely from the shot',
    'next to it. Editing, Kuleshov showed, is where cinema makes emotion, out of',
    'pieces that do not contain it on their own.</p>',
    '<blockquote class="fs-quote"><p>"The foundation of film art is editing."</p>',
    '<p><small>— Lev Kuleshov, as our lecturer quotes him</small></p></blockquote>',
    '<p><b>Eisenstein and the collision.</b> Sergei Eisenstein took the discovery',
    'and made a whole theory of it. For him the cut was not a smooth link but a',
    'collision, a shock, two images striking each other to throw off a third idea',
    'that is in neither of them. He called it intellectual montage, or the montage',
    'of attractions. The Odessa Steps sequence in <i>Battleship Potemkin</i> (1925)',
    'is the demonstration everyone studies: the pram, the boot, the rifles, the',
    'faces, cut so that the meaning is built by the editing rather than filmed by',
    'the camera.</p>',
    '<img class="indie-pic" src="assets/media/web/cine/film-reel-01.jpg" alt=""><span class="indie-cap">Rolls of celluloid film (photo: Marcel Oosterwijk, CC BY-SA 2.0)</span>',
    '<p class="fs-aside"><b>Two opposed schools, worth keeping straight for the',
    'exam.</b> CONTINUITY editing, the Hollywood default, wants the cuts to',
    'disappear, so the join is invisible and you forget you are watching edited',
    'film at all. INTELLECTUAL montage wants the cut to show, to jolt, to make you',
    'notice the join and think. One hides the seam to tell a story smoothly, the',
    'other exposes it to make an argument. Both are montage. They just disagree',
    'about whether you should see the edit working.</p>',
    '<p>So a shot is a unit of meaning, and montage is the grammar that puts the',
    'units together. Change the order or the length or the neighbour of a shot and',
    'you change what it says, even though the footage inside it has not moved a',
    'frame. That is the whole discovery of the Soviet school, and it is why editing',
    'is treated as an art and not a chore.</p>',
    '<p>The technique that stands opposed to the cut, the shot held unbroken so that',
    'no montage is needed, is set out at <a href="the-long-take.geocities.ws">',
    'the-long-take</a>, and the argument between the two runs through the whole',
    'history of criticism, gathered at <a href="the-film-critic.geocities.ws">',
    'the-film-critic</a>, where Andre Bazin made the case for the long take against',
    'exactly this. Off the ring, in plain text: Vsevolod Pudovkin was the third of',
    'the great Soviet theorists, gentler than Eisenstein, who thought of montage as',
    'linkage rather than collision.</p>',
    '<hr>',
    '<p><small>hits 00512 · best viewed at 800x600 · these are STUDENT notes, cite',
    'the actual reading · last updated 9 Mar · a cineaste webring page</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- The Long Take: a technique page ----------------------------------------

const LONGTAKE = P('the-long-take.geocities.ws', 'LONG TAKE',
  'THE LONG TAKE // the shot that will not cut', [
    '<!--bg:cine-institution-->',
    '<h1>THE LONG TAKE</h1>',
    '<p><small>a page for the shot that refuses to cut, kept by a programmer who',
    'once ran the opening of Touch of Evil three times in a row for a stubborn',
    'audience and lost two of them. worth it. — the late-show programmer</small></p>',
    '<hr>',
    '<p>A long take is a shot held for an unusual length of time without a cut. The',
    'French call it the <i>plan-sequence</i>, a sequence carried in a single shot,',
    'and when a whole scene plays out in one unbroken run of film the camera stops',
    'being an editor and becomes a witness. It is the deliberate opposite of the',
    'cut, and the standing rival to montage.</p>',
    '<p>The reference example, the one every student is shown, is the opening of',
    'Orson Welles\'s <i>Touch of Evil</i> (1958). A bomb is placed in the boot of a',
    'car, and the camera then follows that car, and a strolling couple, through the',
    'streets of a border town for over three minutes in a single crane shot, so',
    'that the whole time you know the bomb is there and the people do not. The',
    'suspense is built by refusing to cut. The take ends, and only then does the',
    'film explode.</p>',
    '<p class="fs-pull">One shot, no cut, and the whole world has to be true at',
    'once because there is nowhere to hide a join.</p>',
    '<p>The long take runs back through the history of the moving camera. Max Ophuls',
    'built whole films out of gliding, unbroken shots, the camera waltzing through',
    '<i>La Ronde</i> (1950) and <i>Lola Montes</i> (1955). Kenji Mizoguchi in Japan',
    'held long, distant takes that let a scene keep its own time. And Andrei',
    'Tarkovsky made the long take almost a spiritual practice, holding a shot until',
    'ordinary duration turned strange, in <i>Andrei Rublev</i> (1966) and',
    '<i>Stalker</i> (1979). He called what he was after "sculpting in time", and the',
    'long take was his chisel.</p>',
    '<img class="indie-pic" src="assets/media/web/cine/movie-camera-01.jpg" alt=""><span class="indie-cap">A Bolex H16 movie camera (photo: Sean P. Anderson, CC BY 2.0)</span>',
    '<p class="fs-aside"><b>Why the theorists cared.</b> Andre Bazin argued that the',
    'long take, especially married to deep focus so that near and far are both',
    'sharp, is truer to reality than montage, because it does not chop the',
    'world into pieces and reassemble it into a lesson. It leaves space and time',
    'whole and lets the viewer\'s eye do the choosing. Where the montage theorist',
    'builds meaning at the cut, the long-take director trusts the unbroken world in',
    'front of the lens. Both are making the same choice from opposite ends: what to',
    'do about the cut.</p>',
    '<p>Real time is the extreme case. Hold the take long enough, or chain enough of',
    'them, and screen time equals lived time, the ten minutes on screen are ten',
    'minutes in the room. Alfred Hitchcock played the whole trick as a stunt in',
    '<i>Rope</i> (1948), cutting only where he had to hide the reel change, so the',
    'film pretends to be one continuous shot from end to end.</p>',
    '<p>The opposite principle, the cut and the collision, is set out at',
    '<a href="the-montage.geocities.ws">the-montage</a>, and reading the two pages',
    'together is the fastest way to understand editing at all. For the premieres',
    'where these long-take showpieces first stunned an audience, see',
    '<a href="the-film-festival.geocities.ws">the-film-festival</a>. Off the ring,',
    'in plain text: later directors ran the idea to its limit, the Hungarian Bela',
    'Tarr built entire films from takes many minutes long.</p>',
    '<hr>',
    '<p><small>counter 00688 · best viewed at 800x600 · do not talk during the take',
    '· page last updated 28 Aug · a proud cineaste webring member</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- The Film Critic: an ORG / idea page ------------------------------------

const CRITIC = P('the-film-critic.geocities.ws', 'FILM CRITIC',
  'THE FILM CRITIC // Bazin, Cahiers, Kael', [
    '<!--bg:cine-institution-->',
    '<h1>THE FILM CRITIC</h1>',
    '<p><small>the reading-room page of the society, on the writers who taught us',
    'how to watch. we argue about them more than about the films. kept by whoever',
    'is on the newsletter that term. — the reading circle</small></p>',
    '<p class="fs-epi">"The cinema substitutes for our gaze a world more in harmony',
    'with our desires." — Andre Bazin, roughly, as we quote him</p>',
    '<hr>',
    '<p>Film criticism is the argument that runs alongside the films and, now and',
    'then, changes them. A critic is not only a consumer guide printing stars. At',
    'its height, criticism is a way of teaching a whole culture how to look, and',
    'twice in the last century it did exactly that.</p>',
    '<p><b>Andre Bazin.</b> The great theorist-critic, and for many the most',
    'important writer cinema has had. In 1951 he co-founded <i>Cahiers du Cinema</i>,',
    'the French magazine that became the most influential film journal in the world.',
    'Bazin argued for realism, for deep focus and the long take over aggressive',
    'montage, for a cinema that keeps the world whole rather than cutting it into an',
    'argument. He loved the Italian neorealists for exactly that. His collected',
    'essays, gathered as <i>What Is Cinema?</i> (<i>Qu\'est-ce que le cinema?</i>),',
    'are still the book. He died in 1958, at forty, on the eve of the New Wave that',
    'his own magazine had raised.</p>',
    '<p class="fs-pull">He did not just review the films. He taught a generation',
    'how to see them, and then they picked up cameras.</p>',
    '<p><b>Cahiers and the young critics.</b> Around Bazin gathered a group of',
    'ferocious young writers, Francois Truffaut, Jean-Luc Godard, Eric Rohmer,',
    'Jacques Rivette, Claude Chabrol. In 1954 Truffaut published the essay that lit',
    'the fuse, attacking the polite literary "tradition of quality" in French',
    'cinema and calling instead for the director as the true author of a film. That',
    'idea, the <i>politique des auteurs</i>, became auteur theory, and the critics',
    'who wrote it then went out and became the directors of the French New Wave.',
    'The criticism and the film-making were the same act.</p>',
    '',
    '<p class="fs-aside"><b>The American argument.</b> When the auteur idea crossed',
    'the Atlantic it started a fight. Andrew Sarris translated it into a ranking of',
    'directors, his "pantheon". Pauline Kael, writing for the <i>New Yorker</i>,',
    'attacked the whole system in her essay "Circles and Squares" (1963), distrusting',
    'any theory that decided a film was good before you had watched it. Kael wrote',
    'from the gut, from pleasure, in a voice all her own, and taught American',
    'readers that criticism could be as alive as the movies. Sarris the systematiser,',
    'Kael the sensualist, and a whole generation of American critics grew up in the',
    'space between them.</p>',
    '<p>Under all of it is the figure of the cinephile, the one who loves cinema',
    'past all reason, who sees everything, who keeps lists and revisits and argues.',
    'The critic is the cinephile who writes it down. That love is not a soft thing.',
    'It is what makes a person sit through the difficult film twice and come out',
    'able to say why it matters, which is the work criticism is for.</p>',
    '<p>The magazine and the archive that fed these critics is set out at',
    '<a href="the-cinematheque.geocities.ws">the-cinematheque</a>, where the young',
    '<i>Cahiers</i> writers did their real education in the dark. And the technique',
    'Bazin championed against the Soviets is at <a href="the-montage.geocities.ws">',
    'the-montage</a>, which is the other half of the same quarrel. Off the ring, in',
    'plain text: read Bazin\'s "The Evolution of the Language of Cinema", and if you',
    'want the British corner, Penelope Houston edited <i>Sight and Sound</i> for',
    'decades and kept the serious argument going in English.</p>',
    '<hr>',
    '<p><small>reading-room counter 00773 · best viewed in Netscape at 800x600 ·',
    'the society newsletter, back numbers on request · last updated 17 Nov ·',
    'a cineaste webring page</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

export const CINE_F = [NEOREALISM, CINEMATHEQUE, FESTIVAL, MONTAGE, LONGTAKE, CRITIC];
