// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — the Americas & Oceania.
//
// Fan pages kept on a free host by mythology enthusiasts: a devotional shrine
// to the feathered serpent (the showpiece); a textual walk through the Popol
// Vuh; a careful, respectful primer on the Aboriginal Dreaming; a page on the
// Pacific voyaging traditions and Maui; an Andean primer on Viracocha and Inti;
// and a respectful profile of Coyote across the Native nations. The peoples,
// the deities and the texts are real; the enthusiasm is the pages' own. The
// living traditions are treated as living belief and cultural heritage.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Quetzalcoatl: the showpiece shrine -------------------------------------

const QUETZALCOATL = P('quetzalcoatl.geocities.ws', 'QUETZALCOATL',
  'QUETZALCOATL — the Feathered Serpent // a shrine', [
    '<!--bg:myth-americas-->',
    '<h1>QUETZALCOATL</h1>',
    '<p><small>a shrine to the Feathered Serpent of Mesoamerica, kept by a',
    'second-year who wandered into an Aztec-history module and never quite came',
    'back out. corrections welcome, i am still learning the Nahuatl. — Marisol</small></p>',
    '<div class="fs-epi"><p>“He was the wind, he was the guide and road-sweeper of',
    'the rain-gods.” — from a Nahuatl account gathered in the sixteenth century</p></div>',
    '<hr>',
    '<p>His name in Nahuatl is <i>Quetzalcōātl</i>, and it is a compound you can',
    'pull apart with your hands: <i>quetzalli</i>, the long green tail-feather of',
    'the quetzal bird, and <i>cōātl</i>, serpent. A snake dressed in the feathers',
    'of a bird, earth and sky in one body. He is the god of wind, of learning and',
    'the priesthood, of the calendar and the arts of writing, and he is the',
    'morning star, the planet Venus going up ahead of the sun. Under the wind',
    'aspect he is called Ehecatl, and his temples were built round so the wind',
    'could turn about them and find no corner to catch on.</p>',
    '<div class="fs-aside"><p><b>Did you know?</b> Round temples in the Aztec',
    'cities were dedicated to Quetzalcoatl in his wind form, Ehecatl. The idea was',
    'that the wind should meet no sharp edges, so the shrine of the wind-god was',
    'built without corners. You can still see the circular base of one in the',
    'centre of Mexico City.</p></div>',
    '<p>He belongs to more than one people and more than one age. The Feathered',
    'Serpent is very old in Mesoamerica, worshipped at Teotihuacan long before the',
    'Aztecs, carried on by the Toltecs at Tula, and taken up by the Mexica (the',
    'Aztecs) who inherited so much of the older Toltec prestige. Among the Maya to',
    'the south the same power appears as Kukulkan and, in the K’iche’',
    'account, as Gucumatz. One serpent, many tongues.</p>',
    '<img class="indie-pic" src="assets/media/web/myth/quetzalcoatl-01.jpg" alt=""><span class="indie-cap">Quetzalcoatl, from the Codex Borgia (public domain)</span>',
    '<h2>the maker of people</h2>',
    '<p>In the tradition, after an earlier world had ended Quetzalcoatl went down',
    'into Mictlan, the land of the dead, to fetch the bones of the people who had',
    'lived before. Mictlantecuhtli, the lord of the dead, set him tricks and traps,',
    'and Quetzalcoatl stumbled and the bones broke, which the storytellers say is',
    'why people come in different sizes. He carried the broken bones up all the',
    'same and let his own blood fall on them, and from that the present people were',
    'made. The story goes that he also gave them maize, carrying it out from inside',
    'a mountain in the shape of an ant. What the god does, in tale after tale, is',
    'fetch and give: bones, blood, grain, the calendar, the crafts.</p>',
    '<div class="fs-quote"><blockquote><p>The lord of the dead said: what do you',
    'want here? And the Feathered Serpent said: I have come for the precious bones',
    'that you keep.</p></blockquote><p><small>— retold from the Nahuatl</small></p></div>',
    '<h2>the god and the king</h2>',
    '<p>Here is the knot every enthusiast has to learn to untie. There is',
    'Quetzalcoatl the god, and there is Topiltzin Ce Acatl Quetzalcoatl, a',
    'ruler-priest of Tula who took the god’s name as a title, as priests did.',
    'The chronicles tell of this human Quetzalcoatl as a wise and gentle king who',
    'forbade human sacrifice and taught the arts, until he was shamed or tricked',
    'by the sorcery of Tezcatlipoca, his great rival, and left Tula in disgrace.',
    'He went east toward the sea, and in one telling set himself alight and rose',
    'as the morning star, and in another sailed away on a raft of serpents',
    'promising to come back. Do not fuse the two into one person. The god is the',
    'god; the king is a man who wore the god’s name and whose story got braided',
    'into the god’s.</p>',
    '<div class="fs-pull"><p>The god is the god. The king is a man who wore the',
    'god’s name.</p></div>',
    '<img class="indie-pic" src="assets/media/web/myth/maya-01.jpg" alt=""><span class="indie-cap">A detail of the Maya Dresden Codex (photo: Lacambalam, CC BY-SA 4.0)</span>',
    '<h2>the myth of the return</h2>',
    '<p>Because the king sailed east and said he would return, and because his',
    'name-year in the calendar was One Reed, later chroniclers wrote that the',
    'Aztecs took the arrival of the Spanish in a One Reed year for the promised',
    'return. Historians now treat that neat fit with a good deal of suspicion,',
    'since much of it was written down after the conquest and reads like a story',
    'told backwards to explain a defeat. Note it, weigh it, and do not repeat it as',
    'settled fact.</p>',
    '<h2>a note on the Aztec pantheon, and a rough chronology</h2>',
    '<pre>',
    'THE COMPANY HE KEEPS (Aztec names)',
    '  Ometeotl .......... the dual lord, being above being',
    '  Tezcatlipoca ...... "smoking mirror", night, fate, his rival',
    '  Quetzalcoatl ...... feathered serpent: wind, learning, Venus',
    '  Huitzilopochtli ... the sun and war, patron of the Mexica',
    '  Tlaloc ............ the rain, the mountains, the storm',
    '  Mictlantecuhtli ... lord of Mictlan, the land of the dead',
    '',
    'THE FEATHERED SERPENT THROUGH TIME (rough)',
    '  c. 100-550 CE  Teotihuacan raises the Feathered Serpent pyramid',
    '  c. 900-1150   Tula (Tollan) of the Toltecs; Topiltzin the priest-king',
    '  c. 1325       the Mexica found Tenochtitlan; inherit the old cult',
    '  1519          One Reed year; the Spanish land on the coast',
    '</pre>',
    '<hr>',
    '<p>Where to go next. For the Feathered Serpent among the Maya and the great',
    'creation book of the highlands, see <a href="the-maya-myths.geocities.ws">',
    'the-maya-myths</a>. For the other high civilisation of the Americas and its',
    'creator Viracocha, cross the isthmus to <a href="the-inca-myths.geocities.ws">',
    'the-inca-myths</a>. On the human king I lean on the old accounts gathered by',
    'the friar Bernardino de Sahagún and on later historians of the Nahua; those',
    'are books, not pages in this ring.</p>',
    '<p><small>hit counter: 03571 · best viewed in Netscape at 800x600 · this',
    'shrine is under eternal construction, like the round temple · last updated 14',
    'Sep · a member of the webring for myth</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
  ]);

// ---- The Maya myths: a text profile of the Popol Vuh ------------------------

const THE_MAYA_MYTHS = P('the-maya-myths.geocities.ws', 'THE MAYA MYTHS',
  'THE POPOL VUH // the book of the K’iche’ Maya', [
    '<!--bg:myth-americas-->',
    '<h1>THE MAYA MYTHS: reading the Popol Vuh</h1>',
    '<p><small>a page about one book, because one book is enough for a lifetime.',
    'kept by a member of the folklore reading circle who did the Tedlock',
    'translation cover to cover twice. — R. Okonkwo</small></p>',
    '<hr>',
    '<p>The <i>Popol Vuh</i> is the great surviving creation narrative of the',
    'K’iche’ Maya of the Guatemalan highlands, and it is a living text of a',
    'living people; the K’iche’ are here now, some hundreds of thousands of',
    'them, speaking the language the book is written in. The title means something',
    'like the Book of the Community or the Book of Counsel. What we read comes from',
    'a manuscript written down in the K’iche’ language in the Roman alphabet',
    'in the middle of the sixteenth century, later copied by the friar Francisco',
    'Ximénez with a Spanish version beside it. Behind that alphabetic text stands',
    'an older painted book and a much older oral telling.</p>',
    '<div class="fs-quote"><blockquote><p>This is the account of how all was in',
    'suspense, all calm, in silence; all motionless, still, and the expanse of the',
    'sky was empty.</p></blockquote><p><small>— the Popol Vuh, opening, in the',
    'tradition of the standard English renderings</small></p></div>',
    '<h2>the creation, in three tries</h2>',
    '<p>In the tradition, the makers are Tepeu and Gucumatz, the Sovereign and the',
    'Feathered Serpent, together with Huracan, the Heart of Sky. They speak the',
    'world into shape, raising the mountains out of the water. Then they want',
    'beings who will speak back to them and keep the days, and here the story is',
    'honest about failure. They make the animals first, but the animals only',
    'squawk and cannot pray, so the animals are set to be eaten. They try people of',
    'mud, who slump and dissolve. They try people of wood, who walk and talk but',
    'have no hearts and no memory of their makers, and these are wiped away in a',
    'flood, and the storytellers say the monkeys in the forest are what is left of',
    'them.</p>',
    '<img class="indie-pic" src="assets/media/web/myth/maya-01.jpg" alt=""><span class="indie-cap">A detail of the Maya Dresden Codex (photo: Lacambalam, CC BY-SA 4.0)</span>',
    '<h2>the hero twins</h2>',
    '<p>The long middle of the book follows Hunahpu and Xbalanque, the hero twins.',
    'Their father and uncle, ballplayers both, had been summoned down to Xibalba,',
    'the underworld, by its lords One Death and Seven Death, and beaten and killed',
    'there. The twins are conceived when the severed head of their father, hung in',
    'a tree, spits into the hand of a maiden of Xibalba. Grown, they too are called',
    'down to the underworld, and they too must play the great ballgame against the',
    'lords of death.</p>',
    '<p>What follows is a run of tests in the houses of Xibalba, the Dark House and',
    'the Razor House and the Bat House and the rest, and the twins pass them by',
    'wit and by trickery rather than by strength. They let themselves be killed and',
    'come back; disguised as wandering performers they promise the lords a trick,',
    'the sacrifice and revival of a living thing, and the lords, greedy for the',
    'marvel, ask to be killed and revived themselves. The twins kill them and do',
    'not bring them back. Death is put in its place, below. The twins rise into the',
    'sky as the sun and the moon.</p>',
    '<div class="fs-aside"><p><b>A note on the ballgame.</b> The Mesoamerican',
    'ballgame was real and ancient, played with a heavy rubber ball on a stone',
    'court shaped like a capital I, the ball kept moving with the hip. In the Popol',
    'Vuh it is the hinge of the whole story, the game the fathers lose and the sons',
    'win, life and death played out on the court.</p></div>',
    '<h2>people of maize</h2>',
    '<p>Only after the twins have dealt with death do the makers succeed with',
    'humanity, and the material is the point: they grind yellow maize and white',
    'maize and from the dough they form the first true people, who can speak and',
    'remember and give thanks. A people who live by maize tell a story in which',
    'people are made of maize. That is the note the book closes its creation on,',
    'and it is worth sitting with.</p>',
    '<pre>',
    'THE MAKING OF PEOPLE, in order',
    '  1. the animals ....... can cry out, cannot pray        (kept, to be eaten)',
    '  2. the mud people .... shapeless, dissolve in water     (unmade)',
    '  3. the wood people ... move and speak, no heart, no memory (flooded away)',
    '  4. the maize people .. speak, remember, give thanks      (the present kind)',
    '</pre>',
    '<hr>',
    '<p>Neighbours in the ring. The Feathered Serpent who helps make this world is',
    'the same power honoured to the north; see the shrine at',
    '<a href="quetzalcoatl.geocities.ws">quetzalcoatl</a>. For the Andean creation',
    'and the other great American tradition, see',
    '<a href="the-inca-myths.geocities.ws">the-inca-myths</a>. For English I would',
    'send you to the translations by Dennis Tedlock and by Allen Christenson; those',
    'are books, not pages here.</p>',
    '<p><small>counter: 01984 · best viewed at 800x600 · under construction (the',
    'Xibalba section keeps growing) · last updated 2 Aug</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
  ]);

// ---- The Dreamtime: a respectful primer -------------------------------------

const THE_DREAMTIME = P('the-dreamtime.geocities.ws', 'THE DREAMTIME',
  'THE DREAMING // a respectful primer', [
    '<!--bg:myth-americas-->',
    '<h1>THE DREAMING</h1>',
    '<p><small>a primer written with care, because this is not a dead mythology',
    'but the living belief and law of the Aboriginal peoples of Australia. i am an',
    'outsider and a folklore-society member; i have tried to say only what is said',
    'openly and to point you to Aboriginal writers for the rest. — the compiler</small></p>',
    '<hr>',
    '<p>First, a caution that belongs at the top. There is no single "Aboriginal',
    'mythology", because there is no single Aboriginal people. Aboriginal Australia',
    'is made of many distinct nations, each with its own country, its own law and',
    'its own languages, hundreds of languages across the continent. What follows is',
    'general and partial, offered with respect, and it cannot stand in for any',
    'particular people’s own account of themselves. Much knowledge is held',
    'properly within communities and is not mine or yours to take.</p>',
    '<p>"The Dreamtime", or better "the Dreaming", is the usual English for a set',
    'of ideas that each language names in its own word: <i>Tjukurrpa</i> among the',
    'Anangu of the Western Desert, <i>Altjira</i> among the Arrernte of the centre,',
    'and many others. It is not a long-ago time in the way English "once upon a',
    'time" is long ago. It is the enduring ground of things, the creation that is',
    'also still present, the pattern that holds the world and the law together now.</p>',
    '<div class="fs-quote"><blockquote><p>The Dreaming is not a dream, and it is',
    'not the past. It is the Law, and it is now.</p></blockquote><p><small>— a',
    'sense often given by Aboriginal teachers to outsiders</small></p></div>',
    '<h2>the ancestral beings</h2>',
    '<p>In the many traditions, ancestral beings moved across a formless country in',
    'the creation and shaped it: they are the makers of the hills, the waterholes,',
    'the rivers and the living things, and often they became those features',
    'themselves, so that a particular rock or reach of water is an ancestor, not',
    'merely a place an ancestor once was. Among the best known widely is the',
    'Rainbow Serpent, associated with water and the creation of the land across',
    'many northern and other traditions, though the being takes different names and',
    'different stories from nation to nation.</p>',
    '<img class="indie-pic" src="assets/media/web/myth/oceania-artefact-01.jpg" alt=""><span class="indie-cap">A Torres Strait turtle-shell ancestor mask (museum object, CC0)</span>',
    '<h2>songlines</h2>',
    '<p>The paths the ancestral beings walked are remembered as songlines, also',
    'called dreaming tracks. A songline is at once a route across real country and',
    'a sung sequence that records it, so that the song and the land carry each',
    'other. To know the song is to know the way, the water along it and the law',
    'that holds for that country. These tracks can run for great distances and',
    'cross the lands of several peoples, and the knowledge of them is a serious',
    'responsibility, held and passed on under law.</p>',
    '<div class="fs-aside"><p><b>A word on words.</b> "Dreamtime" was coined by',
    'early English writers and many Aboriginal people prefer "the Dreaming", or the',
    'word from their own language. Follow the lead of the people whose belief it',
    'is. If you write about a particular nation’s tradition, use their name for',
    'it and their account, not this general sketch.</p></div>',
    '<h2>the law and the living belief</h2>',
    '<p>The Dreaming is not only a set of stories about how things began. It is the',
    'source of the Law: how people should live, marry, care for country and for one',
    'another, and what responsibilities each person carries for particular places',
    'and particular knowledge. It is taught through ceremony, through art, through',
    'song and dance and the care of country, and it is alive today, held by',
    'communities who have kept it through invasion, dispossession and every effort',
    'to break it. Treat it as you would any people’s living faith and law, with',
    'respect and without helping yourself to what is not offered.</p>',
    '<hr>',
    '<p>Neighbours in the ring, across the water. For the seafaring traditions of',
    'the Pacific and the demigod Maui, see',
    '<a href="the-polynesian-myths.geocities.ws">the-polynesian-myths</a>. For the',
    'Feathered Serpent and the Mesoamerican world, see',
    '<a href="quetzalcoatl.geocities.ws">quetzalcoatl</a>. For the rest, and this',
    'is the important pointer, read Aboriginal writers and community sources',
    'directly, and organisations such as AIATSIS; those are off this little ring,',
    'named here in plain text and worth far more than my summary.</p>',
    '<p><small>visitors: 00930 · best viewed at 800x600 · this page respects the',
    'traditional owners of the lands it describes · last tended 9 May</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
  ]);

// ---- The Polynesian myths: voyaging and Maui --------------------------------

const THE_POLYNESIAN_MYTHS = P('the-polynesian-myths.geocities.ws', 'POLYNESIAN MYTHS',
  'THE PACIFIC // Maui, Tangaroa and the wayfinders', [
    '<!--bg:myth-americas-->',
    '<h1>THE POLYNESIAN MYTHS</h1>',
    '<p><small>a primer on the myths of the great ocean, kept by an armchair',
    'navigator who has never sailed further than the Isle of Wight but reads',
    'everything about those who sailed everywhere. — the compiler</small></p>',
    '<hr>',
    '<p>Polynesia is the vast triangle of the Pacific whose points are roughly',
    'Hawai’i in the north, Aotearoa (New Zealand) in the south-west and Rapa Nui',
    '(Easter Island) in the east, with Samoa, Tonga, Tahiti and many islands',
    'between. The peoples of these islands are distinct, the Māori and the',
    'Hawaiians and the Samoans and the rest, each with their own telling, yet they',
    'share a family of languages and a family of gods and heroes, because they came',
    'from common voyaging ancestors. In the traditions the great gods include',
    'Tangaroa of the sea, Tane of the forest, Rongo of cultivated food and Tu of',
    'war, with the sky father Rangi and the earth mother Papa parted at the',
    'beginning so that light could come between them.</p>',
    '<div class="fs-quote"><blockquote><p>Tangaroa, Tangaroa the vast, Tangaroa of',
    'the ocean, the sea is his skin and the fish are his children.</p></blockquote>',
    '<p><small>— in the tradition of the island tellings</small></p></div>',
    '<h2>Maui, the demigod</h2>',
    '<p>The best loved hero across the islands is Maui, a demigod and a trickster,',
    'small and clever and always going one step too far. The stories vary from',
    'island to island, and in the tradition they include these. Maui fished up',
    'islands from the sea floor with a magic hook baited, in some tellings, with',
    'his own blood; Aotearoa’s North Island is called Te Ika-a-Māui, the fish',
    'of Maui, to this day. Maui snared the sun with ropes and beat it until it',
    'agreed to cross the sky more slowly, so that the days would be long enough to',
    'work and to fish. Maui brought fire up from the underworld, coaxing it from',
    'his ancestress Mahuika. In some tellings his last daring, the attempt to win',
    'immortality for people by passing through the body of the goddess of death,',
    'is the one trick that kills him, which is why people still die.</p>',
    '<div class="fs-pull"><p>Maui fished up islands, snared the sun and stole',
    'fire, and the one trick that killed him was the one meant to save us from',
    'dying.</p></div>',
    '<img class="indie-pic" src="assets/media/web/myth/polynesian-01.jpg" alt=""><span class="indie-cap">A Marquesan tiki ancestor figure (Louvre; photo Jastrow, public domain)</span>',
    '<h2>the voyaging and the wayfinding</h2>',
    '<p>Behind the myths lies one of the real wonders of human history. The',
    'ancestors of the Polynesians settled the largest ocean on Earth in',
    'double-hulled voyaging canoes, deliberately, generations before the European',
    'age of sail. They found their way without compass or chart by wayfinding: by',
    'the rising and setting points of the stars, by the direction and feel of the',
    'ocean swells, by the flight of birds, the shapes of clouds and the drift of',
    'debris. This knowledge was carried in the memory and the training of master',
    'navigators, and in the later twentieth century it was revived, most famously',
    'when the canoe Hōkūle’a sailed from Hawai’i to Tahiti by traditional',
    'wayfinding alone.</p>',
    '<pre>',
    'READING THE OCEAN WITHOUT INSTRUMENTS (a wayfinder’s toolkit)',
    '  the star compass ... rising/setting points of known stars as headings',
    '  the swells ........ steady ocean swells felt through the hull',
    '  the birds ......... landfinding birds that fly out and back to shore',
    '  the clouds ........ still cloud that stacks above an unseen island',
    '  the drift ......... floating wood, land birds, a green tint under cloud',
    '</pre>',
    '<hr>',
    '<p>Neighbours in the ring. Across to the Australian mainland and the living',
    'Dreaming of its many nations, see',
    '<a href="the-dreamtime.geocities.ws">the-dreamtime</a>. For a trickster of a',
    'very different ocean of land, the North American Coyote, see',
    '<a href="coyote-the-trickster.geocities.ws">coyote-the-trickster</a>. For the',
    'Māori tellings in depth I lean on collections such as those gathered by',
    'Māori scholars and elders; those are books and community sources, not pages',
    'in this ring.</p>',
    '<p><small>counter: 01221 · best viewed at 800x600 · this page navigates by',
    'the stars and a 56k modem · last updated 30 Jun</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
  ]);

// ---- The Inca myths: an Andean primer ---------------------------------------

const THE_INCA_MYTHS = P('the-inca-myths.geocities.ws', 'THE INCA MYTHS',
  'THE ANDES // Viracocha, Inti and the founding of Cusco', [
    '<!--bg:myth-americas-->',
    '<h1>THE INCA MYTHS</h1>',
    '<p><small>a primer on the Andean traditions, kept by a classics student who',
    'took a wrong turn out of Greece and ended up very happily in the mountains.',
    'the Quechua spellings vary; i have done my best. — Marisol</small></p>',
    '<hr>',
    '<p>The Inca ruled a great Andean empire from Cusco in the fifteenth and early',
    'sixteenth centuries, and they inherited and gathered up much older Andean',
    'belief. The myths reach us mostly through Spanish chroniclers and through',
    'Andean writers of the colonial period, so they come to us at a slant, written',
    'down by outsiders or by the newly converted. Behind them are peoples, many of',
    'them speaking Quechua and Aymara today, whose religion was woven into the land',
    'itself.</p>',
    '<h2>Viracocha, the creator</h2>',
    '<p>In the tradition Viracocha (Wiraqucha) is the great creator, who rose from',
    'Lake Titicaca in the darkness and made the sun, the moon and the stars, and',
    'then made people, in some tellings twice, destroying a first race and shaping',
    'the present one from clay or from stone at Tiwanaku and sending them out to',
    'people the land. When his work was done he walked north-west across the',
    'mountains teaching as he went, and at last walked out across the sea. He is a',
    'creator who withdraws, leaving the world in the keeping of the gods he set in',
    'the sky.</p>',
    '<div class="fs-quote"><blockquote><p>He came from the great lake in the time',
    'of darkness, and he commanded the sun to rise.</p></blockquote><p><small>— in',
    'the tradition of the Andean creation accounts</small></p></div>',
    '<h2>Inti and the Sapa Inca</h2>',
    '<p>Chief among the gods Viracocha set in the sky is Inti, the sun, from whom',
    'the ruling Inca claimed descent. The Sapa Inca, the sole ruler, was honoured',
    'as the son of the Sun, and the great festival of Inti Raymi marked the sun’s',
    'turn at the southern winter solstice with feasting and offering. Beside Inti',
    'stood Mama Killa the moon, Illapa the thunder and weather, and everywhere',
    'Pachamama, the earth mother, to whom the first of the drink and the first of',
    'the planting were given back.</p>',
    '<img class="indie-pic" src="assets/media/web/myth/inca-01.jpg" alt=""><span class="indie-cap">An Inca gold llama figurine (British Museum; photo: BabelStone, CC BY-SA 3.0)</span>',
    '<h2>the founding of Cusco</h2>',
    '<p>The story goes that the first Inca, Manco Cápac, and his sister and wife',
    'Mama Ocllo were sent by the Sun to bring order to the people. In one telling',
    'they emerged from Lake Titicaca, in another from caves at Pacaritambo, the',
    'place of dawn. They carried a golden staff and were told to settle where it',
    'sank into the ground, and it sank at Cusco, and there they founded the city',
    'that became the navel of the empire and taught the people to farm and to',
    'weave.</p>',
    '<div class="fs-aside"><p><b>Huacas.</b> All across the Andes the sacred was',
    'anchored in the land as <i>huacas</i>: holy places, stones, springs, mountains,',
    'ancestor-mummies and objects that held power. Lines called <i>ceques</i> ran',
    'out from the great temple in Cusco to link the huacas around it, ordering the',
    'sacred landscape and the calendar together. The holiness was in the country,',
    'not only in a temple.</p></div>',
    '<pre>',
    'THE ANDEAN SKY AND EARTH (Inca names)',
    '  Viracocha ...... Wiraqucha, the creator who withdrew',
    '  Inti ........... the sun, father of the Sapa Inca',
    '  Mama Killa ..... the moon, wife of the sun',
    '  Illapa ......... thunder, lightning and the rain',
    '  Pachamama ...... the earth mother, of the planting and the harvest',
    '  the huacas ..... the sacred places and things of the land',
    '</pre>',
    '<hr>',
    '<p>Neighbours in the ring. For the other great imperial tradition of the',
    'Americas and its book of creation, see',
    '<a href="the-maya-myths.geocities.ws">the-maya-myths</a>. For the Feathered',
    'Serpent of Mesoamerica, see',
    '<a href="quetzalcoatl.geocities.ws">quetzalcoatl</a>. On the Andes I lean on',
    'the colonial chroniclers and on modern Andean scholarship; those are books,',
    'named here in plain text, not pages in this ring.</p>',
    '<p><small>hit counter: 00887 · best viewed at 800x600 · page under',
    'construction at 3,400 metres · last updated 21 Apr</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
  ]);

// ---- Coyote: a respectful trickster profile ---------------------------------

const COYOTE_THE_TRICKSTER = P('coyote-the-trickster.geocities.ws', 'COYOTE',
  'COYOTE // trickster, maker, fool (a respectful page)', [
    '<!--bg:myth-americas-->',
    '<h1>COYOTE</h1>',
    '<p><small>a page for Coyote, written with care, because these are the living',
    'oral traditions of many distinct Native North American nations, not old',
    'superstitions to be smiled at. i am an outsider and a folklore reader; i point',
    'you to the nations’ own tellers wherever i can. — R. Okonkwo</small></p>',
    '<hr>',
    '<p>The first thing to say, and to keep saying, is that there is no single',
    '"Coyote". Coyote figures in the stories of many Native nations across western',
    'North America, the Diné (Navajo), the Nez Perce, the Crow, the Maidu, the',
    'Karuk, the Nch’i-Wana peoples of the Columbia and a great many more, and each',
    'nation has its own Coyote, its own language, its own stories and its own laws',
    'about how and when they may be told. What follows is a general outline offered',
    'with respect. It cannot stand in for any nation’s own account, and some',
    'stories are seasonal or sacred and not for casual retelling.</p>',
    '<div class="fs-quote"><blockquote><p>Coyote was going along. That is how so',
    'many of the stories begin, and it is a whole way of seeing the',
    'world.</p></blockquote><p><small>— a very common opening in the',
    'traditions</small></p></div>',
    '<h2>maker and fool at once</h2>',
    '<p>What makes Coyote so alive as a figure is that he is two things at the same',
    'time and the stories never resolve it. He is a maker and helper, who in many',
    'traditions has a hand in shaping the present world, arranging the land and the',
    'rivers and the ways of the people. And he is a fool and a glutton, greedy,',
    'boastful, driven by his appetites, forever overreaching and coming to grief.',
    'The same figure who helps set the world in order is the one who cannot keep',
    'his own hunger in check. The stories hold both without flinching.</p>',
    '',
    '<h2>the bringer of fire, and of death</h2>',
    '<p>In many traditions Coyote is a bringer of fire. The story goes that fire',
    'was kept by beings who would not share it, and Coyote, with the help of other',
    'animals in a relay, stole a burning brand and carried it to the people, or',
    'placed it in the trees so that it could be drawn out again by rubbing wood.',
    'And in a number of traditions it is Coyote who brings death into the world:',
    'when it is debated whether people who die should return, Coyote argues, often',
    'for a hard practical reason, that they should not, and then his own child dies',
    'and he learns too late what he has done. The law he made cannot be unmade,',
    'even for him.</p>',
    '<div class="fs-aside"><p><b>Why the stories are told.</b> In many nations the',
    'Coyote stories are teaching stories, told in particular seasons, often in the',
    'winter. Coyote does the foolish, greedy, forbidden thing so that the listener,',
    'especially the young listener, need not; the lesson is carried by his',
    'mistakes rather than by a lecture. To hear the story rightly is to be taught',
    'by it.</p></div>',
    '<h2>a living heritage</h2>',
    '<p>These are not stories from a closed past. They are told now, by living',
    'peoples, in languages many of which are being carried on and taught to new',
    'generations against long odds. When you read a Coyote story, read whose story',
    'it is: which nation, told by whom, gathered how. A story told by a member of a',
    'nation carries an authority that no outsider’s summary, including this one,',
    'can borrow. Prefer the nations’ own storytellers and publications, and',
    'respect that some tellings are not offered to everyone.</p>',
    '<hr>',
    '<p>Neighbours in the ring. For a trickster demigod of the Pacific and the',
    'traditions of wayfinding, see',
    '<a href="the-polynesian-myths.geocities.ws">the-polynesian-myths</a>. For the',
    'living Dreaming of the many nations of Aboriginal Australia, kept with the',
    'same care, see <a href="the-dreamtime.geocities.ws">the-dreamtime</a>. For the',
    'nations’ own tellings I point you to tribal publishers and to storytellers',
    'named by their nations; those are off this ring, in plain text, and they come',
    'first.</p>',
    '<p><small>visitors: 00742 · best viewed in Netscape at 800x600 · a member of',
    'the webring for myth · this page respects the nations whose stories it names ·',
    'last tended 17 Mar</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
  ]);

export const MYTH_E = [
  QUETZALCOATL,
  THE_MAYA_MYTHS,
  THE_DREAMTIME,
  THE_POLYNESIAN_MYTHS,
  THE_INCA_MYTHS,
  COYOTE_THE_TRICKSTER,
];
