// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// ARCH B — the pioneers. Sullivan and the tall office building, Gaudí and the
// unfinished cathedral, the skyscraper and the steel frame, the Crystal Palace
// and the Eiffel Tower, and the Arts and Crafts reaction to the machine. Pages
// an architecture enthusiast kept on a free host in the late 1990s: student
// coursework, a shrine, close readings, an idea page and a style primer. The
// buildings, architects and dates are real; the enthusiasm is the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Louis Sullivan: the shrine (showpiece) ---------------------------------

const SULLIVAN = P('louis-sullivan.geocities.ws', 'SULLIVAN',
  'LOUIS SULLIVAN — form ever follows function', [
    '<!--bg:arch-pioneers-->',
    '<h1>LOUIS SULLIVAN</h1>',
    '<p><small>a shrine to Louis Henry Sullivan (1856–1924), the father of the',
    'tall office building and, to my mind, the first architect to look a steel',
    'frame in the eye and ask what it wanted to be. kept by a third-year',
    'architecture student who should be working on studio. — R.T.</small></p>',
    '<hr>',
    '<p class="fs-epi">“Form ever follows function.”<br>',
    '<span>— Louis Sullivan, “The Tall Office Building Artistically Considered”, 1896</span></p>',
    '<p>Everyone shortens it to “form follows function” and drops the <i>ever</i>,',
    'which is a shame, because the <i>ever</i> is the whole music of the line. He',
    'did not mean strip a building bare. He meant that the shape of a living thing',
    'expresses what it does, and a building should do the same, honestly, from the',
    'inside out. Read the essay and you find him reaching for the oak and the',
    'apple-blossom, not for a machine.</p>',
    '',
    '<p>He came up in Chicago after the fire of 1871, when a whole city had to be',
    'rebuilt at once and the ground was ready for a new kind of building. With his',
    'partner Dankmar Adler he took the new steel skeleton and the safety lift and',
    'worked out how a very tall commercial building should actually look. Not a',
    'stone box pretending to be Greek, and not an engineer’s afterthought, but a',
    'thing with a base you walk into, a long shaft of repeated offices, and a',
    'crowning cornice at the top. Base, shaft, capital, like a column, read up the',
    'height of the street.</p>',
    '<blockquote class="fs-quote"><p>“It must be tall, every inch of it tall. The',
    'force and power of altitude must be in it, the glory and pride of exaltation',
    'must be in it.”</p><p><span>— Sullivan, on the tall office building</span></p></blockquote>',
    '<p>The two buildings you must know are the Wainwright Building in St. Louis',
    '(1891) and the Guaranty Building in Buffalo (1896). The Wainwright is the one',
    'where he first got the whole idea to hold together, the brick piers running',
    'unbroken up the shaft so your eye is pulled skyward. The Guaranty is the',
    'Wainwright perfected, sheathed in terracotta and covered, every inch, in his',
    'ornament.</p>',
    '<h2>the ornament</h2>',
    '<p>Do not skip the ornament as some Victorian leftover. It is the strangest',
    'and most personal thing he did. Sullivan grew his decoration like foliage,',
    'tight geometric seed-shapes bursting into leaf and vine, cast in terracotta',
    'and iron. He wrote a whole book of it late in life, <i>A System of',
    'Architectural Ornament</i> (1924), drawing the growth of form out of the seed.',
    'The moderns who came after him threw the ornament away and kept the frame. He',
    'would have thought them half-dressed.</p>',
    '',
    '<p class="fs-pull">“An architect who took the raw new frame and gave it a',
    'grammar.”</p>',
    '<pre>',
    '  SULLIVAN & ADLER — buildings to know',
    '  ---------------------------------------------',
    '  1889  Auditorium Building, Chicago (with Adler)',
    '  1891  Wainwright Building, St. Louis',
    '  1893  Transportation Building, World’s Fair',
    '  1896  Guaranty (Prudential) Building, Buffalo',
    '  1899  Carson Pirie Scott store, Chicago',
    '  1908  National Farmers’ Bank, Owatonna',
    '        ("a jewel box on the prairie")',
    '  ---------------------------------------------',
    '  the "jewel box" banks are late, small and superb',
    '</pre>',
    '<div class="fs-aside"><p><b>Did you know?</b> A young draughtsman named Frank',
    'Lloyd Wright worked for Sullivan in the Adler & Sullivan office through the',
    'early 1890s and always called him <i>Lieber Meister</i>, the beloved master.',
    'Wright carried the idea of an organic architecture out of that office and made',
    'it his own. Sullivan’s later years were lean and lonely; Wright never quite',
    'stopped paying the debt in print.</p></div>',
    '<p>He belongs to the Chicago School, the loose group of architects and',
    'engineers who, in the 1880s and 1890s, worked out the commercial high-rise on',
    'a steel frame with the wide "Chicago window". For the building type itself,',
    'and how the frame and the lift made it possible, see',
    '<a href="the-skyscraper.geocities.ws">the-skyscraper</a>. For the dictum and',
    'its long, argued afterlife, the page to read is',
    '<a href="form-follows-function.geocities.ws">form-follows-function</a>, which',
    'is fairer to it than the slogan ever is.</p>',
    '<hr>',
    '<p><small>counter: 03120 · best viewed in Netscape at 800x600 · this shrine is',
    'under eternal construction, like a certain cathedral · last updated 14 Oct',
    '</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a proud stop on the buildings webring. « prev · random · next »</small></p>',
  ]);

// ---- Antoni Gaudí: a single-building close reading --------------------------

const GAUDI = P('antoni-gaudi.geocities.ws', 'GAUDI',
  'ANTONI GAUDI // the Sagrada Familia up close', [
    '<!--bg:arch-pioneers-->',
    '<h1>ANTONI GAUDÍ and the SAGRADA FAMÍLIA</h1>',
    '<p><small>one building, read slowly. notes by a volunteer with the local',
    'conservation society who spent a fortnight in Barcelona with a sketchbook and',
    'came home changed. — pages for anyone who will listen.</small></p>',
    '<hr>',
    '<p>Antoni Gaudí (1852–1926) was the great one-off of Catalan',
    '<i>modernisme</i>, that Barcelona flowering of the turn of the century that',
    'ran parallel to Art Nouveau but grew its own stranger flowers. He gave the',
    'city Park Güell with its serpentine tiled bench and its columned market hall,',
    'and Casa Batlló with its bone-like balconies and its scaled roof, and the',
    'Casa Milà (La Pedrera) that seems quarried rather than built. But the work of',
    'his life, the one he died inside, is the Basílica de la Sagrada Família.</p>',
    '<p>He took over the project in 1883, a year after it began, and spent the',
    'rest of his life on it, the last years living on the site like a hermit. He',
    'knew he would never see it finished. He is supposed to have said that his',
    'client, meaning God, was in no hurry.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/sagrada-familia-01.jpg" alt=""><span class="indie-cap">The Sagrada Família by Gaudí (photo: Reda Kerbush, CC BY-SA 4.0)</span>',
    '<p><b>the catenary arch.</b> Here is the thing to understand, the thing that',
    'makes him an engineer and not just a dreamer. Gaudí hated the flying buttress.',
    'He called the Gothic cathedral a crippled thing that needed crutches to stand.',
    'So he found a way to build without them. He hung little weighted strings',
    'upside down to model his structures, chains and shot-bags, and a hanging chain',
    'falls into a curve called a catenary, which is the perfect line of pure',
    'tension. Turn that hanging curve upside down and you get the perfect line of',
    'pure compression, an arch that stands with no sideways push, no buttress',
    'needed. His famous upside-down string model in the crypt at Colònia Güell is',
    'the whole secret in one dusty object.</p>',
    '<p><b>trencadís.</b> The other signature is the broken-tile mosaic, the',
    '<i>trencadís</i>, made of smashed ceramic and glass pressed into mortar so a',
    'curved surface can be clad in colour that a flat tile never could. It is',
    'thrift and glory at once, the rubbish of the tile works turned into the skin',
    'of a dragon.</p>',
    '<p>He drew almost nothing flat. He worked in plaster models and hanging',
    'chains and his own eye, which is exactly why finishing the building after his',
    'death has been so slow and so argued-over. The reaction to the machine and the',
    'return to the honest handmade that runs through his whole generation is set',
    'out at <a href="arts-and-crafts.geocities.ws">arts-and-crafts</a>, and though',
    'they never met he is a cousin of that movement. For the American who was',
    'asking the same question about honest structure at the very same moment, in a',
    'wholly different key, see <a href="louis-sullivan.geocities.ws">',
    'louis-sullivan</a>.</p>',
    '<p>He was run over by a tram in 1926 and, dressed shabbily as always, was',
    'taken for a pauper. The city buried him in the crypt of his own unfinished',
    'church. William Morris he was not, but the love of the made thing was the',
    'same fire.</p>',
    '<hr>',
    '<p><small>hits: 01888 · best viewed at 800x600 · a Catalan-modernisme',
    'appreciation page · last updated 2 Sep · corrections welcome, i am only a',
    'volunteer</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>member of the buildings webring. « prev · random · next »</small></p>',
  ]);

// ---- The skyscraper: an ORG / idea page -------------------------------------

const SKYSCRAPER = P('the-skyscraper.geocities.ws', 'SKYSCRAPER',
  'THE SKYSCRAPER // steel, the lift, and the race for the sky', [
    '<!--bg:arch-pioneers-->',
    '<h1>THE SKYSCRAPER</h1>',
    '<p><small>an idea page, not a person page. how the tall building became',
    'possible and then became a race. kept as a reference for anyone who keeps',
    'losing the dates in a pub argument. — the building-spotter.</small></p>',
    '<hr>',
    '<p>A skyscraper is not just a tall building, it is a tall building made',
    'possible by two inventions arriving together in the second half of the',
    'nineteenth century. Take either one away and the whole thing falls down, in',
    'one case literally.</p>',
    '<p><b>The steel frame.</b> The first is the metal skeleton. In a traditional',
    'building the outer walls hold the whole weight, so the taller you go the',
    'thicker the base must be, until the ground floor is nearly solid masonry and',
    'you can go no higher. The Monadnock Building in Chicago (1891) is the famous',
    'last gasp of that method, load-bearing brick walls almost two metres thick at',
    'the bottom. The answer was to hang the building on an inner cage of iron and',
    'then steel, so the frame carries the load and the wall becomes a thin skin, a',
    'curtain, that only has to keep the weather out. William Le Baron Jenney’s',
    'Home Insurance Building in Chicago (1885) is usually called the first of the',
    'true skeleton-frame towers.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/seagram-01.jpg" alt=""><span class="indie-cap">The Seagram Building by Mies van der Rohe (photo: Epicgenius, CC BY-SA 4.0)</span>',
    '<p><b>The safety lift.</b> The second is the one people forget. A tall',
    'building is no use if nobody will climb the stairs to the top of it. Elisha',
    'Otis showed his safety lift at the New York Crystal Palace exhibition in 1854',
    'by having the hoisting rope cut while he stood on the platform; a spring-loaded',
    'catch gripped the guide rails and held him. It was theatre, and it sold the',
    'idea that a lift would not drop you. Once people would ride upward the upper',
    'floors became the desirable ones, and rent turned the frame’s new height into',
    'money.</p>',
    '<p>After that it was a race, first in Chicago and then, harder and taller, in',
    'New York. The Woolworth Building (1913), Cass Gilbert’s Gothic tower, was',
    'called the Cathedral of Commerce and held the height record for a while. Then',
    'came the sprint of the early 1930s, the Chrysler Building (1930) with its',
    'stainless steel crown, quickly beaten by the Empire State Building (1931),',
    'which went up in a bit over a year and held the record for four decades. The',
    'race for the sky was on.</p>',
    '<pre>',
    '  A SHORT LADDER OF FIRSTS AND TALLESTS',
    '  -----------------------------------------',
    '  1854  Otis demonstrates the safety lift',
    '  1885  Home Insurance Bldg, Chicago (skeleton frame)',
    '  1891  Wainwright, St. Louis / Monadnock (last of brick)',
    '  1913  Woolworth Building, New York',
    '  1930  Chrysler Building, New York',
    '  1931  Empire State Building, New York',
    '  -----------------------------------------',
    '</pre>',
    '<p>The architect who first gave this new type a proper face, rather than just',
    'stacking storeys, was Louis Sullivan; the base, shaft and cornice he worked',
    'out is at <a href="louis-sullivan.geocities.ws">louis-sullivan</a>. And for',
    'the other great iron structure of the age, the one that went up not for rent',
    'but for a world’s fair and outdid every tower on earth, see',
    '<a href="the-eiffel-tower.geocities.ws">the-eiffel-tower</a>.</p>',
    '<hr>',
    '<p><small>visitors: 02044 · best viewed at 800x600 · a buildings reference',
    'page, corrections gratefully received · last updated 21 Aug</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a node on the buildings webring. « prev · random · next »</small></p>',
  ]);

// ---- The Crystal Palace: a single-building close reading --------------------

const CRYSTAL_PALACE = P('the-crystal-palace.geocities.ws', 'CRYSTAL PALACE',
  'THE CRYSTAL PALACE // Paxton, 1851, iron and glass', [
    '<!--bg:arch-pioneers-->',
    '<h1>THE CRYSTAL PALACE</h1>',
    '<p><small>ARCH 214, History of Building Technology, coursework essay (the',
    'good copy, marked 72). building study: the Crystal Palace, Hyde Park, 1851.',
    'i have kept the wonky bibliography at the bottom, tutor said fix the',
    'referencing. — a second-year, filing it here so i stop losing it.</small></p>',
    '<hr>',
    '<p>The Crystal Palace was the building put up in Hyde Park to house the Great',
    'Exhibition of the Works of Industry of All Nations in 1851. It was designed',
    'not by an architect at all but by Joseph Paxton, a gardener, the head gardener',
    'to the Duke of Devonshire at Chatsworth, who had built enormous glasshouses',
    'and knew exactly how to roof a vast space in iron and glass.</p>',
    '<p>The committee had been floundering. They had a design for a heavy brick',
    'building with a dome that nobody liked and that could never be finished in',
    'time. Paxton, the story goes, sketched his glasshouse idea on a piece of',
    'blotting paper during a railway meeting. It won because it could be built',
    'fast, cheaply, and taken down again afterwards.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/crystal-palace-01.jpg" alt=""><span class="indie-cap">The Crystal Palace, 1851 (Dickinson Brothers, public domain)</span>',
    '<p><b>Why it matters as building.</b> This is one of the first great works of',
    'prefabrication. Nothing on the site was carved or cast to fit in place.',
    'Instead the whole thing was a kit, made of a small number of standard parts',
    'repeated thousands of times, iron columns and girders and a standard pane of',
    'glass, all sized to a single module of 24 feet. The parts were made in',
    'factories in the Midlands, brought by the new railways, and bolted together on',
    'site by a small army of workers in a matter of months. A modern glazing wagon',
    'ran along the roof gutters so the glaziers could fit pane after pane at speed.</p>',
    '<p>It enclosed a huge volume, over 90,000 square metres of floor, and it kept',
    'the full-grown elm trees of the park inside it, under glass, which is where',
    '<i>Punch</i> gave it the mocking name that stuck, the Crystal Palace. Light',
    'poured through it in a way no masonry building could manage. It was the',
    'greenhouse made monumental, a whole architecture of iron and glass that the',
    'railway stations and market halls of the century would take up.</p>',
    '<p>After the exhibition it was dismantled and re-erected, larger, at Sydenham',
    'in south London, where it stood until fire destroyed it in 1936. The building',
    'that most obviously carries its lesson forward, iron structure raised for a',
    'world’s fair and higher than anything before it, is at',
    '<a href="the-eiffel-tower.geocities.ws">the-eiffel-tower</a>, and the everyday',
    'child of the same structural revolution, the tall commercial building on a',
    'metal frame, is set out at <a href="the-skyscraper.geocities.ws">',
    'the-skyscraper</a>.</p>',
    '<pre>',
    '  BIBLIOGRAPHY (tutor: FIX THE FORMAT)',
    '  - Chadwick, G. The Works of Sir Joseph Paxton',
    '  - Hix, J. The Glass House (on glasshouses generally)',
    '  - the big Pevsner history of building types, ch. on',
    '    exhibition buildings, ref TBC',
    '  - "the blotting-paper sketch" story, need a proper source',
    '</pre>',
    '<hr>',
    '<p><small>counter: 00934 · best viewed at 800x600 · a coursework page, please',
    'do not cite my essay in yours · last updated 4 Mar</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>on the buildings webring. « prev · random · next »</small></p>',
  ]);

// ---- The Eiffel Tower: a single-building close reading ----------------------

const EIFFEL = P('the-eiffel-tower.geocities.ws', 'EIFFEL TOWER',
  'THE EIFFEL TOWER // wrought iron, 1889, and the protest', [
    '<!--bg:arch-pioneers-->',
    '<h1>THE EIFFEL TOWER</h1>',
    '<p><small>one structure, read closely. kept by a bridge-and-ironwork',
    'enthusiast who thinks the tower is really a piece of engineering that Paris',
    'learned to love by accident. — the spotter, again.</small></p>',
    '<hr>',
    '<p>The Eiffel Tower was built for the Exposition Universelle of 1889, the',
    'world’s fair held in Paris to mark the centenary of the French Revolution. It',
    'was meant to be temporary, a spectacular gateway to the fair, and it was for',
    'four decades the tallest man-made structure on earth, a shade over 300 metres,',
    'nearly double the height of the Washington Monument that had held the record',
    'before it.</p>',
    '<p>The name belongs to Gustave Eiffel, the engineer whose firm built it,',
    'though the design was worked up by two engineers in his company, Maurice',
    'Koechlin and Émile Nouguier, with the architect Stephen Sauvestre added to',
    'dress the base with arches and make it more palatable. Eiffel was already the',
    'master of the great wrought-iron viaduct and had engineered the internal',
    'skeleton of the Statue of Liberty. The tower is his kind of thing, a bridge',
    'stood on its end.</p>',
    '<img class="indie-pic" src="assets/media/web/arch/eiffel-tower-01.jpg" alt=""><span class="indie-cap">The Eiffel Tower (photo: Mark.thurman92, CC BY-SA 3.0)</span>',
    '<p><b>The lattice.</b> The tower is not solid, it is a lattice, an open',
    'web of wrought-iron members riveted together, and that openness is the point.',
    'A solid tower that tall would catch the wind like a sail and be torn down. The',
    'lattice lets the wind pass through, and the whole flared shape, wide feet',
    'curving up to a narrow top, is calculated so that the pressure of the wind is',
    'carried down the legs to the ground. Eiffel worked the curve out from the wind',
    'load. It is a mathematical shape wearing a decorative face. Some two and a half',
    'million rivets hold it, every one hammered in by hand.</p>',
    '<blockquote class="fs-quote"><p>“We, writers, painters, sculptors, architects,',
    'lovers of the beauty of Paris... protest with all our strength... against the',
    'erection... of the useless and monstrous Eiffel Tower.”</p>',
    '<p><span>— from the artists’ protest published in <i>Le Temps</i>, 1887</span></p></blockquote>',
    '<p>That protest was signed by a crowd of the eminent, Charles Garnier who',
    'built the Opéra among them, and by the writer Guy de Maupassant, who is said',
    'to have taken to eating lunch in the tower’s restaurant on the grounds that it',
    'was the one spot in Paris from which he could not see the thing. The city was',
    'supposed to pull it down after twenty years. It was saved because the tall',
    'iron mast turned out to be perfect for the new wireless telegraphy, and the',
    'antennas kept it standing until Paris had quietly fallen in love with it.</p>',
    '<p>It belongs with the other great iron-and-glass statement of the century,',
    'the prefabricated exhibition hall at <a href="the-crystal-palace.geocities.ws">',
    'the-crystal-palace</a>, and the same revolution in metal structure that let it',
    'rise let the tall commercial building rise too, which is the story at',
    '<a href="the-skyscraper.geocities.ws">the-skyscraper</a>.</p>',
    '<hr>',
    '<p><small>hits: 01502 · best viewed in Netscape at 800x600 · an ironwork',
    'appreciation page · last updated 30 Jul · this page is under construction, the',
    'rivet count needs a proper citation</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a member of the buildings webring. « prev · random · next »</small></p>',
  ]);

// ---- Arts and Crafts: a movement / style primer -----------------------------

const ARTS_AND_CRAFTS = P('arts-and-crafts.geocities.ws', 'ARTS & CRAFTS',
  'ARTS AND CRAFTS // Morris, the Red House, the guilds', [
    '<!--bg:arch-pioneers-->',
    '<h1>THE ARTS AND CRAFTS MOVEMENT</h1>',
    '<p><small>a primer on the movement, kept by someone who joined the local',
    'building-conservation society to save a threatened Voysey house and got',
    'thoroughly converted along the way. — a conservation volunteer.</small></p>',
    '<hr>',
    '<p>Arts and Crafts was the reaction, in Britain from the 1860s onward, against',
    'the cheap and ugly machine-made goods of the industrial age. Its argument, in',
    'a sentence, was that the factory had split the worker from the joy of making,',
    'turned the craftsman into a hand tending a machine, and that you could see the',
    'misery of it in the shoddy objects that resulted. The cure was a return to the',
    'honest handmade, to the workshop, to the dignity of the maker.</p>',
    '<p>The great voice was William Morris (1834–1896), the designer, poet and',
    'socialist, who took the ideas of the critic John Ruskin and made them into a',
    'working practice and a firm. Ruskin had argued in <i>The Stones of Venice</i>',
    'that Gothic building was great precisely because it let the mason think and',
    'carve freely, roughness and all, where the machine demanded a dead perfection.',
    'Morris believed it and lived it.</p>',
    '<div class="fs-aside"><p><b>The building to know: the Red House.</b> In 1859',
    'the young Morris had Philip Webb design him a home at Bexleyheath in Kent. The',
    'Red House is plain red brick where fashion wanted stucco, built around the way',
    'the family actually lived rather than around a symmetrical front, with a well',
    'and a steep roof and honest materials shown as themselves. It is often called',
    'the first Arts and Crafts building, and the making of it, friends painting the',
    'furniture and the walls together, led straight to the founding of Morris’s',
    'design firm in 1861.</p></div>',
    '',
    '<p>After Morris the movement spread into a whole generation of architect-',
    'designers. Charles Voysey built long, low, white-rendered houses with sloping',
    'buttresses and simple bands of windows, and designed everything down to the',
    'door hinges and the wallpaper. The idea of the <b>guild</b> came back, groups',
    'of makers working together, such as C. R. Ashbee’s Guild of Handicraft, and',
    'the country was dotted with workshops turning out furniture and metalwork and',
    'books made with care.</p>',
    '<p>There is a real tension inside the movement, and it is worth naming',
    'plainly. Handmade goods made by well-paid craftsmen cost money, so the honest',
    'furniture that was meant for everyone tended to end up in the houses of the',
    'wealthy. Morris the socialist felt the contradiction keenly. The movement',
    'never solved it.</p>',
    '<p>Its influence ran far. It fed into Art Nouveau on the continent and the',
    'work of a figure like <a href="antoni-gaudi.geocities.ws">antoni-gaudi</a>,',
    'who shared the love of the handmade and the honest material even without the',
    'English connection, and it crossed the Atlantic into the American Craftsman',
    'style and the Prairie School. The insistence that a building show its',
    'structure and its materials honestly is a thread that runs on into the',
    'modern creed argued out at <a href="louis-sullivan.geocities.ws">',
    'louis-sullivan</a>, though Morris would have had strong words about the steel',
    'frame.</p>',
    '<hr>',
    '<p><small>counter: 01276 · best viewed at 800x600 · a movement primer for the',
    'conservation-minded · last updated 9 May · long may the guilds be',
    'remembered</small></p>',
    '<p><small>[ <a href="architecture-ring.geocities.ws">Architecture Ring</a> ]</small></p>',
    '<p><small>a member of the buildings webring. « prev · random · next »</small></p>',
  ]);

export const ARCH_B = [SULLIVAN, GAUDI, SKYSCRAPER, CRYSTAL_PALACE, EIFFEL, ARTS_AND_CRAFTS];
