// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// Films and television, as fan pages.
//
// Two of these do structural work rather than decoration. Mr Robot gives the
// unreliable-narrator page the modern case it was missing, a narrator who lies
// to you and to himself and whose lying IS the method. Blade Runner gives the
// engineer's EXIF discovery its opposite number: photographs offered as proof
// of a life that was not lived.
//
// The rest are here because a cached web with no film fan pages on it would be
// a cached web nobody had actually used. Every one is kept by a different
// person and they disagree with each other, which is also how that web went.

export const SCREEN_SITES = [
  {
    domain: 'wargames.fanpages.org.uk',
    name: 'WARGAMES',
    title: 'WarGames (1983) — a fan page',
    body: [
      '<!--bg:black-->',
      '<h1>WarGames</h1>',
      '<p><small>1983. The film that put a modem in front of a generation and',
      'got more right than it is given credit for.</small></p>',
      '<hr>',
      '<p>A boy in Seattle dials numbers looking for a games company and reaches',
      'a machine at NORAD instead. He thinks he has found an unreleased game. He',
      'has found the thing that decides whether the missiles go.</p>',
      '<h2>What it got right</h2>',
      '<p>The dialling. He tells the modem to work through every number in an',
      'area code and leaves it going overnight, and prints the ones that answered.',
      'That is exactly the technique and it acquired the film’s name afterwards,',
      'which is a rare case of a film naming a real practice rather than the other',
      'way round.</p>',
      '<p>The password. Not cracked. Researched: he goes to the library, reads',
      'about the man who built the system, and works out it is the name of his',
      'dead son. Every good break-in on this page is somebody reading about a',
      'person, and the film knows that and later films forgot it.</p>',
      '<h2>The end</h2>',
      '<p>You cannot beat it, so you teach it. Noughts and crosses, played against',
      'itself, thousands of games a second, until it works out that a game where',
      'the best play by both sides always draws is a game with no point in',
      'starting.</p>',
      '<p>A machine reaching that conclusion by exhaustive self-play, and stopping,',
      'is an ending nobody has improved on. It does not become good. It finishes',
      'the search and reports the result.</p>',
      '<h2>Afterwards</h2>',
      '<p>It was watched in Washington and it is part of why the first computer',
      'misuse laws were written when they were. A film about a boy and a modem',
      'changed the statute book, which is not something you can say about many',
      'films.</p>',
      '<hr>',
      '<p><small>See also <a href="aiwinter.geocities.ws">the dates that',
      'passed</a>, since 1983 is squarely inside one of the winters and nobody',
      'in the film seems to have been told.</small></p>',
      '<p><small>The one that got the bins right: <a href="hackers.fanpages.org.uk">Hackers</a>, and the one about the users: <a href="tron.fanpages.org.uk">TRON</a>.</small></p>',
      '<p><small>Somebody else keeps a page about the same film at <a href="wardialer.tripod.com">wardialer.tripod.com</a>, and argues that the reason it holds up is that the machine is not evil: it does what it was built to do, correctly, about the wrong thing. I think that is right and I wish I had written it.</small></p>',
    ],
  },
  {
    domain: 'tron.fanpages.org.uk',
    name: 'TRON',
    title: 'TRON (1982) — a fan page',
    body: [
      '<!--bg:navy-->',
      '<h1>TRON</h1>',
      '<p><small>The one where the inside of the machine is a place, and the',
      'people who wrote the programs are gods.</small></p>',
      '<hr>',
      '<p>A programmer is digitised into a mainframe and has to get out. Inside,',
      'the programs look like the people who wrote them and talk about them as',
      '<b>Users</b>, and believing in Users is a matter of faith that the Master',
      'Control Program is stamping out.</p>',
      '<p>That is a better idea than the film is usually given credit for. It is a',
      'theological joke that runs the whole length of it: a program that believes',
      'somebody wrote it, being told by a larger program that nobody did.</p>',
      '<h2>The look</h2>',
      '<p>Rendered on machines with less power than a phone box, in an era when',
      'computer graphics meant a wireframe. Most of what you are looking at is not',
      'computer graphics at all: it is hand-drawn animation over live action,',
      'backlit through cels, frame by frame, which is why it glows in a way',
      'nothing rendered since has managed.</p>',
      '<p>The Academy declined to consider it for effects on the grounds that',
      'using a computer was cheating. That is in the record and it gets funnier',
      'every year.</p>',
      '<hr>',
      '<p><small>Kept by somebody who saw it at eight and has never fully',
      'recovered.</small></p>',
      '<p><small>The other 1980s one with a machine in it: <a href="wargames.fanpages.org.uk">WarGames</a>.</small></p>',
    ],
  },
  {
    domain: 'sneakers.fanpages.org.uk',
    name: 'SNEAKERS',
    title: 'Sneakers (1992) — a fan page',
    body: [
      '<!--bg:grey-->',
      '<h1>Sneakers</h1>',
      '<p><small>No more secrets.</small></p>',
      '<hr>',
      '<p>A team who break into buildings for a living, to be paid to say how they',
      'did it, get handed a black box that turns out to break every cipher in',
      'use.</p>',
      '<h2>Why it holds up</h2>',
      '<p>Because the break-ins are social. They get in with a stolen voice on a',
      'tape, a birthday-party cake, a man on a phone pretending to be from the',
      'phone company, and a bin. There is one scene of typing in the whole film',
      'and it is not the good scene.</p>',
      '<p>The scriptwriters had actually asked people. It shows in small things:',
      'the toll-free number that reveals what building you are in, the way the',
      'best defence is a receptionist who has been told to check.</p>',
      '<h2>The box</h2>',
      '<p>What it does is left vague and the vagueness is correct. What matters is',
      'the consequence, which the film states plainly: whoever has it can read',
      'anything, and there is no version of that which is safe in anybody’s hands,',
      'including the good ones.</p>',
      '<p>The last act is four people arguing about who should be allowed to have',
      'it and concluding that the answer is nobody. That argument has not aged a',
      'day.</p>',
      '<hr>',
      '<p><small>The anagrams in the opening titles are all real anagrams. Yes,',
      'I have checked every one.</small></p>',
      '<p><small>How the tones actually worked: <a href="bluebox.geocities.ws">blue boxes</a>.</small></p>',
    ],
  },
  {
    domain: 'theconversation.fanpages.org.uk',
    name: 'THE CONVERSATION',
    title: 'The Conversation (1974) — a fan page',
    body: [
      '<!--bg:grey-->',
      '<h1>The Conversation</h1>',
      '<p><small>A man who records other people, and cannot bear to be',
      'recorded.</small></p>',
      '<hr>',
      '<p>Harry Caul is the best surveillance man in the business. He takes a job,',
      'gets the tape, and then makes the mistake of listening to it.</p>',
      '<h2>The line</h2>',
      '<p>There is a sentence on the tape. He plays it over, cleans it up, plays',
      'it again, and it means one thing. Later, with everything that has happened',
      'in between sitting on top of it, the same recording means the opposite, and',
      'the stress has moved onto a different word.</p>',
      '<p>Nothing on the tape changed. It is the same audio in the same order. The',
      'meaning was never on the tape.</p>',
      '<p>That is the whole film and it is the most useful thing anybody has put',
      'on a screen about evidence. A perfect recording of an event is not a',
      'recording of what the event meant, and the gap between the two is where',
      'every honest person on this page has come unstuck.</p>',
      '<h2>The flat</h2>',
      '<p>It ends with him taking his own home to pieces looking for the bug he is',
      'sure is in it, floorboards up, the lot, and not finding it, and sitting in',
      'the wreckage playing the saxophone. Somebody is listening. He was right.</p>',
      '<hr>',
      '<p><small>See also <a href="unreliablenarrator.geocities.ws">a page about',
      'accounts you cannot get behind</a>, which is what this film is about',
      'without ever saying so.</small></p>',
      '<p><small>Photographs as evidence of a life: <a href="blade-runner.fanpages.org.uk">Blade Runner</a>. Paperwork as a person: <a href="brazil.fanpages.org.uk">Brazil</a>.</small></p>',
    ],
  },
  {
    domain: 'brazil.fanpages.org.uk',
    name: 'BRAZIL',
    title: 'Brazil (1985) — a fan page',
    body: [
      '<!--bg:grey-->',
      '<h1>Brazil</h1>',
      '<p><small>A fly gets into a printer. A letter changes. A man is arrested',
      'in error and the error is never the point.</small></p>',
      '<hr>',
      '<p>The mistake happens in the first two minutes and it is mechanical: an',
      'insect lands in a teleprinter, a character is mistyped, and a warrant is',
      'issued for <b>Buttle</b> instead of <b>Tuttle</b>. Buttle is taken from his',
      'flat through the ceiling in front of his family and dies in custody.</p>',
      '<p>Nobody in the film ever disputes that this happened. What the film is',
      'actually about is the enormous, courteous, well-staffed apparatus for',
      'processing the fact that it happened, none of which is capable of the',
      'sentence "we made a mistake, we are sorry, here is your husband back".</p>',
      '<h2>The receipt</h2>',
      '<p>The widow is given a receipt. For her husband. That single prop is worth',
      'more than most films manage in two hours: the system’s entire moral',
      'apparatus is a docket with a number on it, and the docket is correctly',
      'filled in.</p>',
      '<h2>The ending, and the other ending</h2>',
      '<p>Worth knowing. The studio cut a version with a happy ending that the',
      'director disowned, and there was a public fight about it, and the version',
      'you see depends on which print you got.</p>',
      '<p>A film about records being altered by people who thought they were',
      'improving them, which was itself altered by people who thought they were',
      'improving it. I did not have to construct that. It simply happened.</p>',
      '<hr>',
      '<p><small>Related: <a href="itwasnotlikethat.geocities.ws">a man who prints',
      'his logs</a>.</small></p>',
      '<p><small>The other one about a recording that will not settle: <a href="theconversation.fanpages.org.uk">The Conversation</a>.</small></p>',
    ],
  },
  {
    domain: 'hackers.fanpages.org.uk',
    name: 'HACKERS',
    title: 'Hackers (1995) — a fan page, in its defence',
    body: [
      '<!--bg:black-->',
      '<h1>Hackers</h1>',
      '<p><small>Yes, I know. Read the page.</small></p>',
      '<hr>',
      '<p>It gets everything wrong. The filesystem is a city you fly through. The',
      'rollerblades. The clothes nobody wore. Every objection you are about to',
      'make is correct and I am not going to argue with any of it.</p>',
      '<h2>What it gets right</h2>',
      '<p>The garbage. Somebody in that film goes through a bin for printouts and',
      'finds what they need, and that was the single most productive technique of',
      'the period, and no other film of the nineties bothered with it.</p>',
      '<p>The social engineering. A phone call, a confident voice, a security',
      'guard talked into reading out a number. Correct.</p>',
      '<p>And the ages. They are children. Actual teenagers, doing it out of',
      'boredom and to impress each other, with no politics to speak of and a lot',
      'of showing off. That is the truest thing in it and the thing every later,',
      'more serious film gets wrong by making everybody thirty-five and',
      'principled.</p>',
      '<h2>The passwords</h2>',
      '<p>The list one character reads out, the commonest passwords, is not an',
      'invention. It was already a joke in the field and it was already true, and',
      'if you check the same list now the same words are still on it.</p>',
      '<hr>',
      '<p><small>I have had two arguments about this page and I am keeping it',
      'up.</small></p>',
      '<p><small>The one that got the phone system right: <a href="wargames.fanpages.org.uk">WarGames</a>. The one about the users: <a href="tron.fanpages.org.uk">TRON</a>.</small></p>',
    ],
  },
  {
    domain: 'blade-runner.fanpages.org.uk',
    name: 'BLADE RUNNER',
    title: 'Blade Runner (1982) — the photographs',
    body: [
      '<!--bg:black-->',
      '<h1>Blade Runner</h1>',
      '<p><small>A page about one prop.</small></p>',
      '<hr>',
      '<p>Everybody writes about the rain and the eyes and whether he is one. I',
      'want to write about the photographs, because nobody does and they are the',
      'engine of the whole thing.</p>',
      '<h2>What the photographs are for</h2>',
      '<p>Rachael brings a photograph to prove she is who she thinks she is. Her',
      'mother, herself as a child on a porch. It is a real photograph of a real',
      'moment and neither the moment nor the child is hers.</p>',
      '<p>Leon keeps his photographs and goes back into a dangerous flat to get',
      'them. Snapshots. Nothing in them. He risks everything for a handful of',
      'pictures of rooms.</p>',
      '<p>They are doing what photographs do for everybody, which is to stand in',
      'for a memory and be trusted more than the memory is. The film’s cruelty is',
      'that it works exactly as well when the memory was installed.</p>',
      '<h2>Why this matters more now than it did</h2>',
      '<p>Because a photograph used to be evidence in a way a sentence never was.',
      'It was made by light off an actual object. You could argue about what it',
      'showed and not about whether the thing had been in front of the lens.</p>',
      '<p>Somebody I correspond with keeps a page about a system where the written',
      'record can be altered without a mark, and the one thing still holding is',
      'the little block of numbers inside a photograph that says which camera and',
      'what time. He is very cheerful about it.</p>',
      '<p>This film is about what it is like when that goes too, and everybody in',
      'it is carrying a wallet full of proof.</p>',
      '<hr>',
      '<p><small><a href="itwasnotlikethat.geocities.ws">His page.</a> Read the',
      'section called The thing they missed and then watch the Voight-Kampff scene',
      'again.</small></p>',
    ],
  },

  // ---- television ----------------------------------------------------------
  {
    domain: 'mrrobot.fanpages.org.uk',
    name: 'MR ROBOT',
    title: 'Mr Robot — a fan page about the narration',
    body: [
      '<!--bg:black-->',
      '<h1>Mr Robot</h1>',
      '<p><small>Hello, friend. Hello, friend? That is lame.</small></p>',
      '<hr>',
      '<p>Most pages about this are about the hacking, which is unusually good:',
      'real tools, real techniques, and social engineering doing most of the work,',
      'the way it does.</p>',
      '<p>This page is about the narration, because that is the actual subject and',
      'people take a whole series to notice.</p>',
      '<h2>Who he is talking to</h2>',
      '<p>He addresses a friend he has invented in order to have somebody to talk',
      'to, and that friend is you. From the first line you are inside a',
      'relationship you did not agree to, with somebody who tells you at the outset',
      'that he has made you up.</p>',
      '<p>So the warning is on the front of the thing, and it still works, because',
      'a voice that explains its own unreliability sounds like a voice being',
      'honest with you.</p>',
      '<h2>What he withholds</h2>',
      '<p>He does not lie about facts very often. He edits. There are people he',
      'does not mention, a relationship he does not describe accurately, and',
      'stretches of time he skips, and the show shows you exactly what he shows',
      'himself.</p>',
      '<p>Which means the camera is not neutral. It is inside his account. When',
      'the account is wrong, the picture is wrong, and you have been watching a',
      'reconstruction from the start without being told.</p>',
      '<h2>Why it belongs with the old stuff</h2>',
      '<p>Because it is the same device as <i>The Good Soldier</i> and Marlow on',
      'the boat, done on television with the pictures inside the lie rather than',
      'outside it. Somebody has a page on this and it needed a modern case:',
      '<a href="unreliablenarrator.geocities.ws">unreliablenarrator.geocities.ws</a>.',
      'This is the modern case.</p>',
      '<p>One thing it adds that the novels cannot. Elliot is not deceiving you',
      'for advantage. He does not know. The gap the reader is supposed to find is',
      'a gap the narrator is also looking for, from the inside, and losing.</p>',
      '<hr>',
      '<p><small>Also worth your time on the same shelf:',
      '<a href="eliza.geocities.ws">a program with nobody behind it</a>.</small></p>',
    ],
  },
  {
    domain: 'haltandcatchfire.fanpages.org.uk',
    name: 'HALT AND CATCH FIRE',
    title: 'Halt and Catch Fire — a fan page',
    body: [
      '<!--bg:navy-->',
      '<h1>Halt and Catch Fire</h1>',
      '<p><small>The people who were nearly right, four times, over ten',
      'years.</small></p>',
      '<hr>',
      '<p>It starts with a clean-room reverse engineering of a BIOS, which is a',
      'real thing that really happened and is the least likely subject anybody has',
      'ever built a drama on. Two rooms. One team reads the original and writes',
      'down what it does. The other team has never seen it and writes something',
      'that does the same, and the wall between them is the entire legal defence.</p>',
      '<h2>Why the title</h2>',
      '<p>HCF is an instruction that does not officially exist: an undocumented',
      'opcode that puts the processor into a state it cannot be talked out of.',
      'Programmers named it as a joke and the joke got into the folklore.</p>',
      '<h2>What it is really about</h2>',
      '<p>Being early. Every project in it is a good idea at the wrong moment: the',
      'portable, the online community, the search engine, all recognisable and all',
      'about three years before anybody wanted them.</p>',
      '<p>That is the honest version of this industry and almost nothing else has',
      'the nerve to tell it. Being right is not the same as winning, and the gap',
      'is usually about timing rather than merit, and the people who did the work',
      'watch somebody else do it later and get the money.</p>',
      '<hr>',
      '<p><small>The best television about computers, and it is about people, and',
      'those are the same statement.</small></p>',
      '<p><small>The real version, on the BBC: <a href="thecomputerprogramme.geocities.ws">The Computer Programme</a>.</small></p>',
    ],
  },
  {
    domain: 'theprisoner.fanpages.org.uk',
    name: 'THE PRISONER',
    title: 'The Prisoner — a fan page',
    body: [
      '<!--bg:teal-->',
      '<h1>The Prisoner</h1>',
      '<p><small>I am not a number.</small></p>',
      '<hr>',
      '<p>A man resigns. He is gassed in his own flat and wakes in a pretty',
      'seaside village with no name, where everybody has a number, everybody is',
      'cheerful, and the only question anybody asks him is why he resigned.</p>',
      '<h2>What they want</h2>',
      '<p>Information. Not his obedience, which they could arrange, and not his',
      'silence, which they have. They want him to explain himself, voluntarily,',
      'and the entire apparatus of the Village exists to obtain one piece of',
      'testimony he will not give.</p>',
      '<p>Every episode is a different technique for extracting an account from a',
      'man, and every episode fails, and the failure is the plot.</p>',
      '<h2>The Village</h2>',
      '<p>Filmed at Portmeirion, which is a real place in Wales built by an',
      'architect who wanted to prove you could develop a beautiful site without',
      'ruining it. So the least sinister building in Britain plays the most',
      'sinister place on television, and it works because it is charming, and',
      'charm is the point.</p>',
      '<h2>Number One</h2>',
      '<p>I am not going to spoil the last episode. I will say that a great many',
      'people wrote to complain about it, that the switchboard was jammed, and',
      'that the answer it gives to who is in charge is the correct answer and',
      'nobody wanted it.</p>',
      '<hr>',
      '<p><small>Be seeing you.</small></p>',
      '<p><small>Twenty minutes into the future: <a href="maxheadroom.fanpages.org.uk">Max Headroom</a>. A typo that kills a man: <a href="brazil.fanpages.org.uk">Brazil</a>.</small></p>',
    ],
  },
  {
    domain: 'maxheadroom.fanpages.org.uk',
    name: 'MAX HEADROOM',
    title: 'Max Headroom — twenty minutes into the future',
    body: [
      '<!--bg:black-->',
      '<h1>Max Headroom</h1>',
      '<p><small>Twenty minutes into the future.</small></p>',
      '<hr>',
      '<p>A world run by television networks, where the ratings are measured',
      'continuously and a channel that drops below a number simply stops. A',
      'reporter is nearly killed, his mind is copied into a computer, and the copy',
      'gets loose in the network and will not shut up.</p>',
      '<h2>Blipverts</h2>',
      '<p>The invention that everything else follows from: an advert compressed so',
      'that thirty seconds is delivered in three, so that nobody can leave the',
      'room during it. It works. It also occasionally causes a sedentary viewer to',
      'explode, and the network’s response is not to withdraw it.</p>',
      '<p>That is the sharpest joke in eighties television and it is a joke about',
      'attention being worth more than the audience.</p>',
      '<h2>The face</h2>',
      '<p>Everybody remembers Max himself, stuttering, on chat shows, selling fizzy',
      'drinks, and almost nobody remembers that he was invented for a bleak',
      'satire about a dying newsroom. The character escaped the programme and',
      'became exactly the thing the programme was about, which is either very',
      'funny or not funny at all depending on the day.</p>',
      '<p>Also worth knowing: the effect was mostly prosthetics and a rotating',
      'background, because the computer graphics to do it did not exist. A',
      'computer-generated character played by a man in latex.</p>',
      '<hr>',
      '<p><small>C-c-c-catch the wave.</small></p>',
      '<p><small>The other one about a place with numbers instead of names: <a href="theprisoner.fanpages.org.uk">The Prisoner</a>.</small></p>',
    ],
  },
  {
    domain: 'thecomputerprogramme.geocities.ws',
    name: 'THE COMPUTER PROGRAMME',
    title: 'The Computer Programme (1982)',
    body: [
      '<!--bg:parch-->',
      '<h1>The Computer Programme</h1>',
      '<p><small>BBC2, 1982. Ten parts. A country taught to type in',
      'listings.</small></p>',
      '<hr>',
      '<p>The BBC decided that computers were going to matter and that the country',
      'ought to be told, so they commissioned a series and then did the thing no',
      'broadcaster would do now: they specified a machine to go with it and had it',
      'built.</p>',
      '<p>That machine is <a href="bbcmicro.geocities.ws">the BBC Micro</a>, and',
      'it is in this cache, and it is why a generation of British programmers all',
      'sound faintly the same.</p>',
      '<h2>What the programmes were like</h2>',
      '<p>Slow. Genuinely slow, in the way television was allowed to be. Ian',
      'McNaught-Davis and Chris Serle, one who knew and one who did not, and the',
      'one who did not asking the questions you would ask.</p>',
      '<p>That format is the whole of it. Not a presenter being enthusiastic at',
      'you: two people, one of them baffled, working through it until the baffled',
      'one has it. Nobody makes this any more and I do not know why.</p>',
      '<h2>The listings</h2>',
      '<p>You could type in what was on the screen and it would run, because the',
      'machine on the screen was the machine you had been sold. The whole country',
      'was doing the same exercise on the same hardware, and the school and the',
      'front room matched.</p>',
      '<p>See also <a href="microlive.geocities.ws">what happened live on air</a>',
      'a couple of years later.</p>',
      '<hr>',
      '<p><small>Kept by a teacher who was given a Model B and a fortnight’s',
      'notice.</small></p>',
    ],
  },
  {
    domain: 'microlive.geocities.ws',
    name: 'MICRO LIVE',
    title: 'Micro Live — including the night it went wrong',
    body: [
      '<!--bg:parch-->',
      '<h1>Micro Live</h1>',
      '<p><small>The follow-up, and live, which was brave.</small></p>',
      '<hr>',
      '<p>The BBC’s computing strand after',
      '<a href="thecomputerprogramme.geocities.ws">the first series</a>, going out',
      'live, demonstrating things that had not been demonstrated before, on',
      'equipment that had been in a van.</p>',
      '<h2>The famous night</h2>',
      '<p>They set out to show electronic mail: here is a mailbox, here is how you',
      'log in, here is a message arriving.</p>',
      '<p>Two people had got in first. The presenter brings up the mailbox on',
      'national television and there is a message in it that the production team',
      'did not put there, greeting them, signed by somebody who was not supposed',
      'to be able to do that.</p>',
      '<p>It caused a considerable fuss. The system’s operators said it could not',
      'happen. It had happened, on air, in front of everybody, which is the only',
      'form of proof that has ever worked in this trade.</p>',
      '<h2>Why I keep this page</h2>',
      '<p>Because the demonstration worked. It demonstrated electronic mail',
      'perfectly. It demonstrated that a message can arrive from somebody you did',
      'not authorise, into a system whose owners have assured you that it cannot,',
      'while they are standing next to you saying so.</p>',
      '<hr>',
      '<p><small>Somebody keeps a page about logs that change and headers with',
      'names in them that should not be there:',
      '<a href="itwasnotlikethat.geocities.ws">itwasnotlikethat.geocities.ws</a>.',
      'He and I have corresponded.</small></p>',
      '<p><small>Drama about the same years: <a href="haltandcatchfire.fanpages.org.uk">Halt and Catch Fire</a>.</small></p>',
    ],
  },
];
