// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH PARA-A — UFOs & aliens.
//
// Cached true-believer pages from the late 1990s: a Roswell case-file shrine,
// an Area 51 dossier, a close-up on the Greys, a crop-circle "how to spot a
// hoax" guide, an abduction chronology, and a Project Blue Book document page.
// The dates, places and names are the real record; the breathless certainty is
// the webmaster's. Claims are attributed; the mundane explanation is always in
// the room. No supernatural fact asserted in the narration.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Roswell: the case-file shrine (SHOWPIECE) ------------------------------

const ROSWELL = P('roswell.geocities.ws', 'ROSWELL',
  'ROSWELL 1947 // the case they buried // case file', [
    '<!--bg:para-ufo-->',
    '<h1>ROSWELL, JULY 1947</h1>',
    '<p class="fs-epi"><small>&ldquo;RAAF Captures Flying Saucer On Ranch in Roswell Region&rdquo;',
    ' — Roswell Daily Record, 8 July 1947</small></p>',
    '<p>Welcome to the case file. If you read one page on this whole ring, read',
    'this one. What follows is what the newspapers printed, what the Air Force',
    'said, and what the believers say happened. I have tried to keep the three',
    'apart so you can make up your OWN mind. The truth they do not want you to',
    'know is in the gaps between the columns.</p>',
    '<div class="fs-aside"><b>SIGHTINGS HOTLINE</b><br>',
    'Saw something over the New Mexico desert? Grandparent worked the base in',
    "'47? I want the story. SIGHTINGS WELCOME, e-mail me. All accounts kept in",
    'confidence unless you say otherwise. — the webmaster</div>',
    '<p>The story goes like this. In early July 1947 a rancher, W. W. &ldquo;Mac&rdquo;',
    'Brazel, found a scatter of debris on the Foster ranch near Corona, some',
    'seventy-odd miles from Roswell. Foil, sticks, rubber, tape with a queer',
    'pattern on it. He took some to the sheriff, the sheriff called the Roswell',
    'Army Air Field, and on 8 July the base press officer put out a release',
    'saying the 509th had recovered a &ldquo;flying disc&rdquo;. It went out on the wire.',
    'Then, within hours, General Ramey at Fort Worth stood the story down and',
    'showed the press a torn weather balloon and a radar reflector.</p>',
    '<img class="indie-pic" src="assets/media/web/para/roswell-sign-01.jpg" alt=""><span class="indie-cap">The International UFO Museum sign, Roswell (photo: Myotus, CC BY 4.0)</span>',
    '<h2>WHAT THEY SAID vs WHAT BELIEVERS SAY</h2>',
    '<pre>',
    '  THE OFFICIAL LINE          |  WHAT BELIEVERS SAY',
    '  ---------------------------+----------------------------',
    '  a weather balloon (1947)   |  the balloon was the cover',
    '  Project Mogul, a secret    |  the foil "read like metal',
    '    array of balloons and    |    but sprang back", no',
    '    sensors to listen for    |    ordinary balloon (Marcel)',
    '    Soviet atom tests (USAF  |',
    '    report, 1994)            |  a craft came down, not a',
    '  no bodies; test dummies    |    balloon',
    '    dropped in the 1950s     |  bodies were recovered and',
    '    (USAF report, 1997)      |    taken to a base',
    '  case closed                |  case never closed',
    '</pre>',
    '<p>The believers lean hardest on Major Jesse Marcel, the 509th intelligence',
    'officer who handled the debris. Years later he told the researcher Stanton',
    'Friedman that the material was not from any balloon he knew, and that the',
    'wreckage in the Fort Worth photograph was not the wreckage he had brought in.',
    'Friedman, with Charles Berlitz and William Moore, put the crashed-saucer',
    'account into print in 1980 with <i>The Roswell Incident</i>, and the case,',
    'quiet for thirty years, came roaring back.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;It was nothing that came from earth. I was',
    'convinced of that at the time and I am convinced of it now.&rdquo;</p>',
    '<p><small>— Jesse Marcel, as quoted by the researchers, recalling 1947</small></p>',
    '</blockquote>',
    '<h2>A CASE CHRONOLOGY</h2>',
    '<pre>',
    '  14 Jun 1947  Brazel finds the debris on the Foster ranch',
    '  08 Jul 1947  RAAF press release: a "flying disc" recovered',
    '  08 Jul 1947  Gen. Ramey retracts it: a weather balloon',
    '  09 Jul 1947  Brazel re-interviewed; the story goes cold',
    '  1978-80      Marcel speaks; Friedman investigates',
    '  1980         "The Roswell Incident" published',
    '  1994         USAF: the debris was Project Mogul',
    '  1995         the "alien autopsy" film airs on TV',
    '  1997         USAF "Case Closed": the "bodies" were dummies',
    '</pre>',
    '<p>Then there is the film. In 1995 the London-based producer Ray Santilli',
    'released grainy black-and-white footage said to show the autopsy of a',
    'recovered alien, and it screened around the world. Sceptics called it a hoax',
    'from the start, and years later Santilli described it as a &ldquo;reconstruction&rdquo;',
    'of footage he said he had once seen. Believers split over it. Whatever else',
    'it did, it lit the fuse under the whole 1990s revival, and it is the reason',
    'half of you have heard the word Roswell at all.</p>',
    '<p class="fs-pull">&ldquo;A weather balloon does not need forty years of denials.&rdquo;',
    ' — what they say in town</p>',
    '<img class="indie-pic" src="assets/media/web/para/flying-saucer-model-01.jpg" alt=""><span class="indie-cap">A 1929 pulp saucer, Science Wonder Stories (Frank R. Paul, public domain)</span>',
    '<p>The town itself made its peace with the story. The International UFO',
    'Museum and Research Center opened on Main Street in 1992, the festival fills',
    'the motels every July, and a place that the Air Force wanted forgotten now',
    'puts the saucer on the lamp-posts. Go in summer. Ask the old-timers. Some of',
    'them were children in 1947 and they remember the trucks.</p>',
    '<p>Where to go next on this ring. The men who ran the secret programmes kept',
    'their real work at <a href="area-51.geocities.ws">area-51</a>, out at Groom',
    'Lake, and the Air Force study that logged the sightings and then closed the',
    'file is written up at',
    '<a href="project-blue-book.geocities.ws">project-blue-book</a>. Read all',
    'three and see if the balloon still floats.</p>',
    '<p><small>counter: 07477 · best viewed in Netscape at 800x600 · THE TRUTH IS',
    'HERE · this site is under eternal construction · last updated 2 Jul</small></p>',
    '<p><small>[ <a href="paranormal-ring.geocities.ws">Paranormal Ring</a> ]</small></p>',
  ]);

// ---- Area 51: the dossier ---------------------------------------------------

const AREA51 = P('area-51.geocities.ws', 'AREA 51',
  'AREA 51 // Groom Lake // what is behind the fence', [
    '<!--bg:para-ufo-->',
    '<h1>AREA 51: THE BOX THEY WON&rsquo;T ADMIT TO</h1>',
    '<p>For years the government would not even say it EXISTED. A base the size of',
    'a town, out on the dry bed of Groom Lake in the Nevada desert, and no line',
    'on any public map. They call it Area 51, or Dreamland, or Homey Airport, or',
    'Watertown, and the name keeps changing because a name you can say is a name',
    'you can ask questions about.</p>',
    '<div class="fs-aside"><b>DID YOU KNOW?</b><br>',
    'The mundane story is real and it is still a cover for secrecy: Groom Lake is',
    'where the U-2 spy plane was tested from 1955, and later the A-12 / SR-71 and',
    'the F-117 stealth fighter. Black aircraft, not black triangles. Sceptics say',
    'that is ALL of it. Believers say a real secret is exactly what you hide a',
    'bigger one behind.</div>',
    '<p>So let us be fair to the boring explanation, because the boring',
    'explanation is documented. The strange lights over Nevada in the 1950s and',
    "'60s line up rather well with test flights of aircraft that flew higher and",
    'faster than anything the public knew about. A U-2 at seventy thousand feet,',
    'catching the sun after dusk, will light up an airline pilot&rsquo;s report as',
    'surely as any saucer. The CIA itself later said its own planes explained a',
    'good share of the Cold War sightings. That is not nothing.</p>',
    '<img class="indie-pic" src="assets/media/web/para/area-51-sign-01.jpg" alt=""><span class="indie-cap">The Extraterrestrial Highway sign, Nevada (photo: Astronautilus, CC BY 2.0)</span>',
    '<p>But then there is Bob Lazar. In 1989, on Las Vegas television, a man',
    'calling himself Bob Lazar said he had been hired to work at a site he called',
    'S-4, near Papoose Lake just south of Groom, reverse-engineering the',
    'propulsion of recovered alien craft powered by an element he called 115.',
    'His account is unproven, parts of his CV could not be confirmed, and',
    'sceptics have picked it apart for years. Believers point out that element',
    '115 was later actually synthesised (and named moscovium), which proves',
    'nothing about saucers but is a strange thing to have guessed. Make of it',
    'what you will. I only report what he claimed.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;We drove out to the black mailbox on the',
    'Groom Road, killed the engine, and waited. About nine the light came up over',
    'the ridge and it did not move like a plane.&rdquo;</p>',
    '<p><small>— a sky-watcher&rsquo;s account, Rachel, Nevada, posted to the list</small></p>',
    '</blockquote>',
    '<p>The perimeter is where the strange meets the solid. There is no fence you',
    'can see for miles, but there are the signs (USE OF DEADLY FORCE AUTHORIZED),',
    'the motion sensors buried in the scrub, the white Jeep Cherokees on the',
    'ridgeline that the watchers call the &ldquo;cammo dudes&rdquo;, and yes, the',
    'low black helicopters people report when they get too close. That part is',
    'not folklore. Approach the line and someone is there before you are.</p>',
    '<p>Two doors off this page. The debris that started all the talk of recovered',
    'craft came down near <a href="roswell.geocities.ws">roswell</a> in 1947, and',
    'the beings the abductees describe from these programmes are the subject of',
    '<a href="the-grays.geocities.ws">the-grays</a>. Follow the money and the',
    'secrecy and see where it leads.</p>',
    '<p><small>counter: 05151 · best viewed in Netscape at 800x600 · they know you',
    'read this · site under construction, like the base · last updated 19 May</small></p>',
    '<p><small>[ <a href="paranormal-ring.geocities.ws">Paranormal Ring</a> ]</small></p>',
  ]);

// ---- The Greys: the close-up ------------------------------------------------

const GRAYS = P('the-grays.geocities.ws', 'THE GRAYS',
  'THE GRAYS // the face at the end of the bed', [
    '<!--bg:para-ufo-->',
    '<h1>THE GRAYS</h1>',
    '<p class="fs-epi"><small>&ldquo;They looked at me and I could not move.&rdquo;',
    ' — the account that repeats, told a thousand times over</small></p>',
    '<p>You already know the face. The smooth grey skin, the small body, the',
    'enormous black almond eyes with no white in them. It is on the book covers',
    'and the T-shirts now, but it did not always look like this, and how it came',
    'to look like this is the real story on this page.</p>',
    '<p>Believers say the Greys are the beings behind the abduction accounts: the',
    'ones who take people from their bedrooms and their cars, run the',
    'examinations, and return them with the hours missing. Whether they are real',
    'visitors or a shape our own minds keep reaching for, one thing is plain from',
    'the record. The image spread, and it spread through the culture in a way we',
    'can almost date.</p>',
    '<pre>',
    '  HOW THE FACE TOOK OVER (as the accounts run)',
    '  1961  the Hill case: "greyish" beings, wraparound eyes',
    '  1987  Whitley Strieber, COMMUNION: the cover face',
    '  1980s the "grey" becomes the default in the reports',
    '  1990s the face is everywhere; other "types" fade',
    '</pre>',
    '<p>The turning point most people point to is 1987, when the writer Whitley',
    'Strieber published <i>Communion</i>, his account of what he said happened to',
    'him at a cabin, and put a painting of a huge-eyed grey being on the cover.',
    'The book was a bestseller. After it, sceptics note, the &ldquo;grey&rdquo; became the',
    'dominant type in new accounts, where before the reports had described all',
    'sorts of beings, tall, hairy, robotic, human. That is either the witnesses',
    'converging on the truth, or the culture handing everyone the same picture.',
    'The story goes both ways depending on who is telling it.</p>',
    '',
    '<p>And there is the missing time. The pattern in the accounts is not usually',
    'a memory of the beings at all. It is a gap. A drive that took two hours too',
    'long, a jump of the clock, an unease that will not lift, and only later,',
    'often under hypnosis, the rest is said to come. Sceptics have a great deal to',
    'say about what hypnosis does to memory, and the abduction page takes that up',
    'directly.</p>',
    '<p class="fs-pull">&ldquo;The eyes are the whole thing. Everything else you might',
    'forget. Not the eyes.&rdquo; — a letter to this page</p>',
    '<p>Read on. The full narrative, from the Hills onward, is set out at',
    '<a href="the-abduction.geocities.ws">the-abduction</a>, and the secret desert',
    'programmes the Greys are tied to in the lore are at',
    '<a href="area-51.geocities.ws">area-51</a>. I make no claim I cannot',
    'attribute. I only keep the file.</p>',
    '<p><small>counter: 04240 · best viewed in Netscape at 800x600 · a believers&rsquo;',
    'webring page · e-mail me your account · last updated 8 Aug</small></p>',
    '<p><small>[ <a href="paranormal-ring.geocities.ws">Paranormal Ring</a> ]</small></p>',
  ]);

// ---- Crop circles: the how-to guide -----------------------------------------

const CROPCIRCLES = P('crop-circles.geocities.ws', 'CROP CIRCLES',
  'CROP CIRCLES // spot a hoax vs the real thing // a guide', [
    '<!--bg:para-ufo-->',
    '<h1>CROP CIRCLES: HOAX OR THE REAL THING?</h1>',
    '<p>Every summer the patterns come back to the English fields, above all',
    'around the old chalk country of Wiltshire, under the shadow of the barrows',
    'and Silbury Hill. They started as simple circles in the late 1970s and grew,',
    'through the 1980s and 1990s, into vast and elaborate pictograms, spirals and',
    'fractals a quarter of a mile across, laid down overnight. This page is a',
    'field guide. Here is how the two sides tell them apart.</p>',
    '<pre>',
    '  THE HOAXERS LEAVE            |  BELIEVERS LOOK FOR',
    '  --------------------------- + --------------------------',
    '  stalks snapped at the base  |  stalks bent, not broken,',
    '  post-holes for the plank    |    at a node, "as if steamed"',
    '  a survey pole centre-mark   |  no footprints coming in',
    '  daylight tells; it is rough |  laid down in a single night',
    '  string-and-board geometry   |  "expulsion cavities" in nodes',
    '</pre>',
    '<div class="fs-aside"><b>THE CONFESSION YOU MUST KNOW ABOUT</b><br>',
    'In 1991 two men from Southampton, Doug Bower and Dave Chorley, told the press',
    'they had been making crop circles since 1978 for a laugh, using a plank, a',
    'length of rope and a wire sight on a cap. They demonstrated it. Many circles',
    'ARE hoaxes; this is not in doubt. The honest question is only whether every',
    'single one is, and the believers say Doug and Dave could not have been in',
    'two counties at once.</div>',
    '<p>So let us be straight, the way a good field guide has to be. Doug and Dave',
    'were real, their plank was real, and after them a whole culture of circle',
    'makers grew up who treat the fields as an art form and sign their work in',
    'private. A great many of the famous formations have known makers. That is the',
    'ground truth, and anyone selling you mystery who does not tell you about 1991',
    'is selling you short.</p>',
    '<img class="indie-pic" src="assets/media/web/para/crop-circle-01.jpg" alt=""><span class="indie-cap">An aerial crop circle, Switzerland 2009 (photo: Kecko, CC BY 2.0)</span>',
    '<p>What the believers hold onto, once you grant all that, is the residue: the',
    'formations that appeared where no track led in, the bent rather than broken',
    'stalks that some researchers (the ones they call cereologists) say they',
    'cannot reproduce with a plank, the accounts of glows and hums in the fields',
    'at night. Sceptics answer that a determined team works in the dark and leaves',
    'less than you think, and that wanting it to be strange is doing a lot of the',
    'work. I lay out both. You walk the field yourself.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;We got tired of people saying it must be',
    'flying saucers, so we thought we would give them something to look at.&rdquo;</p>',
    '<p><small>— Doug Bower, on why they started, as told to the papers in 1991</small></p>',
    '</blockquote>',
    '<p>Next on the ring. The Air Force study that catalogued the wider mystery is',
    'at <a href="project-blue-book.geocities.ws">project-blue-book</a>, and the',
    'case that started England talking about things in the sky is over at',
    '<a href="roswell.geocities.ws">roswell</a>. Take a torch and go careful in',
    'the wheat; the farmers are within their rights and the plank leaves marks.</p>',
    '<p><small>counter: 03660 · best viewed in Netscape at 800x600 · made in a',
    'Wiltshire bedroom, this page anyway · under construction · last updated 3 Aug</small></p>',
    '<p><small>[ <a href="paranormal-ring.geocities.ws">Paranormal Ring</a> ]</small></p>',
  ]);

// ---- The abduction: the chronology ------------------------------------------

const ABDUCTION = P('the-abduction.geocities.ws', 'THE ABDUCTION',
  'THE ABDUCTION // from the Hills onward // a chronology', [
    '<!--bg:para-ufo-->',
    '<h1>THE ABDUCTION NARRATIVE</h1>',
    '<p>It has a shape now, told over and over: the light, the paralysis, the',
    'small grey figures, the table, the examination, the missing hours, and later',
    'the slow return of it all under hypnosis. This page follows how that shape',
    'was built, case by case, from the one that started it.</p>',
    '<pre>',
    '  A CHRONOLOGY OF THE NARRATIVE',
    '  1961  Betty & Barney Hill, New Hampshire: missing time,',
    '          later recovered under hypnosis; the "star map"',
    '  1966  "The Interrupted Journey" tells the Hill case',
    '  1975  the TV film brings it to millions',
    '  1981  Budd Hopkins, MISSING TIME: the pattern named',
    '  1987  Hopkins INTRUDERS; Strieber COMMUNION',
    '  1992  the abduction study conference at MIT',
    '</pre>',
    '<p>The founding case is Betty and Barney Hill. Driving home through the White',
    'Mountains of New Hampshire one night in September 1961, the Hills saw a light',
    'that seemed to follow them, arrived home with two hours they could not',
    'account for, and were later, under hypnosis with a Boston psychiatrist,',
    'recorded describing an encounter with small beings aboard a craft. Betty',
    'said she had been shown a &ldquo;star map&rdquo;. It is the first widely reported',
    'abduction of its kind, and almost every element that became standard is',
    'already there in it.</p>',
    '<img class="indie-pic" src="assets/media/web/para/telescope-night-sky-01.jpg" alt=""><span class="indie-cap">The night sky (NASA/JPL-Caltech/UCLA, public domain)</span>',
    '<p>Through the 1980s the artist and researcher Budd Hopkins gathered many',
    'more accounts and argued that a great wave of people had been taken, often',
    'repeatedly, often since childhood, and mostly without conscious memory of it.',
    'His books <i>Missing Time</i> (1981) and <i>Intruders</i> (1987) gave the',
    'phenomenon its name and its method, and the hypnosis sessions were central to',
    'both. Believers say he uncovered a hidden epidemic. That is the believers&rsquo;',
    'reading, and I give it to you as theirs.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;I came back to the car and I did not know how',
    'long I had been gone. My watch said one thing and the sky said another.&rdquo;</p>',
    '<p><small>— an experiencer&rsquo;s account, read into the record at a support group</small></p>',
    '</blockquote>',
    '<div class="fs-aside"><b>THE SCEPTIC&rsquo;S READING — in fairness</b><br>',
    'Sceptics point to two things. First, SLEEP PARALYSIS: on waking or falling',
    'asleep the body stays frozen while the mind is alert, and people in this',
    'state commonly report a presence in the room, pressure on the chest, lights',
    'and figures and terror. Second, HYPNOSIS does not recover memory like a tape;',
    'it can plant and reshape it, and a leading question becomes a remembered',
    'fact. Neither settles the matter. Both belong on the page.</div>',
    '<p>Follow it on. The beings at the centre of these accounts have their own',
    'file at <a href="the-grays.geocities.ws">the-grays</a>, and the official',
    'study that logged the sightings before it shut its doors is at',
    '<a href="project-blue-book.geocities.ws">project-blue-book</a>.</p>',
    '<p><small>counter: 04961 · best viewed in Netscape at 800x600 · a support',
    'page, not a diagnosis · your account is safe with me · last updated 20 Jun</small></p>',
    '<p><small>[ <a href="paranormal-ring.geocities.ws">Paranormal Ring</a> ]</small></p>',
  ]);

// ---- Project Blue Book: the document page -----------------------------------

const BLUEBOOK = P('project-blue-book.geocities.ws', 'BLUE BOOK',
  'PROJECT BLUE BOOK // the file the Air Force closed', [
    '<!--bg:para-ufo-->',
    '<h1>PROJECT BLUE BOOK</h1>',
    '<p>This is the paperwork. For seventeen years the United States Air Force ran',
    'an official study of unidentified flying objects, collected the reports,',
    'filed them, explained most of them, could not explain some of them, and then',
    'in 1969 closed the whole thing down. It is the nearest we have to a public',
    'record, and this page is a plain guide to what it was.</p>',
    '<pre>',
    '  THE OFFICIAL STUDIES, IN ORDER',
    '  1948-49  Project SIGN     first USAF study',
    '  1949-52  Project GRUDGE   the debunking years',
    '  1952-69  Project BLUE BOOK  the long one',
    '           ~12,000 cases logged in all',
    '           ~700 left "unidentified"',
    '  1966-68  the Condon Committee at Colorado',
    '  1969     Condon Report; Blue Book closed',
    '</pre>',
    '<p>Blue Book ran from 1952 and gathered something like twelve thousand cases',
    'before the end. The great majority it put down to aircraft, balloons, stars',
    'and planets (Venus low on the horizon is the classic), weather and plain',
    'mistakes. A residue, several hundred, it marked &ldquo;unidentified&rdquo;, which the',
    'Air Force was always careful to say meant only that the data were too thin to',
    'classify, not that anything unearthly had called. Believers read that',
    'residue very differently, and there the argument sits to this day.</p>',
    '',
    '<p>The man to know is Dr J. Allen Hynek, the astronomer the Air Force hired',
    'as its scientific consultant. He began, by his own account, a sceptic, the',
    'man who explained sightings away as Venus and swamp gas. Over the years, he',
    'said, a hard core of cases wore his scepticism down, and he ended as the',
    'founder of a serious civilian study group. It is Hynek who gave us the',
    'classification everyone borrowed:</p>',
    '<pre>',
    '  HYNEK&rsquo;S CLOSE ENCOUNTERS',
    '  CE-1  a UFO seen close, under ~150m, no interaction',
    '  CE-2  a physical trace: marks, heat, stalled engines',
    '  CE-3  an occupant or being observed',
    '  ( CE-4, abduction, was added by others later )',
    '</pre>',
    '<div class="fs-aside"><b>WHY IT SHUT</b><br>',
    'The Air Force commissioned an outside study at the University of Colorado',
    'under the physicist Edward Condon. Its 1968 report concluded that further',
    'study of UFOs was unlikely to advance science, and on the back of it Blue',
    'Book was closed in 1969. Believers say the conclusion was written before the',
    'work; the report&rsquo;s own case-by-case sections are still argued over.</div>',
    '<blockquote class="fs-quote"><p>&ldquo;I began as a scoffer. I could not stay one.',
    'The whole subject deserved better than ridicule.&rdquo;</p>',
    '<p><small>— the sense of Hynek&rsquo;s later position, as his readers report it</small></p>',
    '</blockquote>',
    '<p>Cross-refer. The case that predates the whole file, and haunts it, is at',
    '<a href="roswell.geocities.ws">roswell</a>, and for a mystery Blue Book never',
    'had to rule on, the English fields, see',
    '<a href="crop-circles.geocities.ws">crop-circles</a>. Read the file before',
    'you believe anyone who tells you what is in it.</p>',
    '<p><small>counter: 03212 · best viewed in Netscape at 800x600 · a document',
    'page for researchers · corrections welcome · last updated 14 Apr</small></p>',
    '<p><small>[ <a href="paranormal-ring.geocities.ws">Paranormal Ring</a> ]</small></p>',
  ]);

export const PARA_A = [ROSWELL, AREA51, GRAYS, CROPCIRCLES, ABDUCTION, BLUEBOOK];
