// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH D — Japanese & Asian cinema.
//
// The film-society corner of the cached web that kept the Eastern canon:
// a Kurosawa shrine with a full filmography; a quiet appreciation of Ozu
// and the tatami shot; a Satyajit Ray tribute; a close reading of Tokyo
// Story; and two national-cinema primers, Japanese and Indian. The
// directors, films and dates are real; the reverence is the cineastes'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Kurosawa: the shrine (SHOWPIECE) ---------------------------------------

const KUROSAWA = P('akira-kurosawa.geocities.ws', 'KUROSAWA',
  'AKIRA KUROSAWA // the emperor // a shrine', [
    '<!--bg:cine-asia-->',
    '<h1>AKIRA KUROSAWA</h1>',
    '<p><small>a shrine to Akira Kurosawa (1910&ndash;1998), kept by the',
    'programmer of a small repertory season that ran his films two winters ago and',
    'never quite stopped. they called him the emperor on set and it stuck. still',
    'the best door into world cinema i know. &mdash; the season programmer</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;In a mad world, only the mad are sane.&rdquo;',
    '<br>&mdash; Akira Kurosawa</p>',
    '<p>Start where everyone starts, with <i>Seven Samurai</i> (1954). A village',
    'of farmers hires seven masterless swordsmen to defend the harvest against',
    'bandits, and out of that simple line Kurosawa built three and a half hours',
    'that never sag. He shot the final battle in the rain and the mud with several',
    'cameras running at once, cut on movement, and used the long lens to flatten',
    'the chaos into something you could read. Hollywood remade it as a Western,',
    '<i>The Magnificent Seven</i>, which tells you where a good deal of the',
    'Western learned its manners.</p>',
    '<img class="indie-pic" src="assets/media/web/cine/kurosawa-01.jpg" alt=""><span class="indie-cap">Akira Kurosawa (public domain)</span>',
    '<p><i>Rashomon</i> (1950) is the one that changed what a film could do with',
    'the truth. A killing in a forest is told four times, by the bandit, the wife,',
    'the dead man through a medium, and a woodcutter who watched, and the four',
    'accounts do not agree. Kurosawa does not tell you which witness to believe.',
    'The unreliable narrator was old in fiction, but seeing it staged four ways on',
    'a screen, each version shot as if it were the truth, was new. People still',
    'say &ldquo;a Rashomon situation&rdquo; and mean exactly this. It took the',
    'Golden Lion at Venice in 1951 and opened the West to Japanese cinema.</p>',
    '<blockquote class="fs-quote"><p>The camera goes into the forest and the sun',
    'comes through the leaves in flecks. Kurosawa pointed the lens up into the',
    'trees toward the light, which the manuals told you never to do, and got one',
    'of the most copied images in the medium.</p></blockquote>',
    '<p>Two habits of his eye are worth naming. The WIPE, where one shot slides',
    'the next in across the frame like a page turning, he used it as punctuation,',
    'a cut with a flourish, and it became a signature. And the TELEPHOTO lens,',
    'the long focal length that compresses distance and lets him pull a face out',
    'of a crowd or hold three planes of a battle in one plane of focus. He liked',
    'to shoot with several cameras at once so the actors never knew which was on',
    'them, which kept the playing raw.</p>',
    '<p class="fs-pull">&ldquo;I like hot summers, cold winters, heavy rain and',
    'snow, and I think most of my pictures have something to do with that.&rdquo;</p>',
    '<p>Late Kurosawa turned to colour and to scale. <i>Kagemusha</i> (1980), the',
    'story of a thief who doubles for a dying warlord, and then <i>Ran</i> (1985),',
    'his <i>King Lear</i> moved to feudal Japan, an old lord who divides his lands',
    'among three sons and is destroyed by the giving. <i>Ran</i> is the summit of',
    'his colour work, whole armies dressed in single blocks of red, yellow and',
    'blue so you can read a battle by its palette. He was going blind when he',
    'painted the storyboards; they hang in galleries now.</p>',
    '<div class="fs-aside"><p><b>Did you know?</b> When funds dried up at home, it',
    'was admirers abroad who kept him working. George Lucas and Francis Ford',
    'Coppola helped bring <i>Kagemusha</i> to the screen, and later George Lucas',
    'has said the two droids in <i>Star Wars</i> owe something to the two',
    'bickering peasants who open <i>The Hidden Fortress</i> (1958).</p></div>',
    '<p>The filmography is long and there is not a decade in it without a landmark.</p>',
    '<pre>',
    'AKIRA KUROSAWA — selected films',
    '  1948  Drunken Angel        first film with Toshiro Mifune',
    '  1950  Rashomon             Golden Lion, Venice 1951',
    '  1952  Ikiru                a dying clerk builds a playground',
    '  1954  Seven Samurai        the one they all remake',
    '  1957  Throne of Blood      Macbeth as Noh theatre',
    '  1957  The Lower Depths     after Gorky',
    '  1958  The Hidden Fortress  the two peasants',
    '  1961  Yojimbo              remade as A Fistful of Dollars',
    '  1963  High and Low         a kidnapping, colour in one shot',
    '  1965  Red Beard            last film with Mifune',
    '  1975  Dersu Uzala          shot in the USSR, an Oscar',
    '  1980  Kagemusha            the shadow warrior',
    '  1985  Ran                  King Lear in feudal Japan',
    '  1990  Dreams               eight short dreams in colour',
    '</pre>',
    '<p>If you have an evening and not a week, here is where to spend it.</p>',
    '<pre>',
    'THE ESSENTIAL FIVE — a first Kurosawa season',
    '  1.  Seven Samurai (1954)     .... the whole cinema in one film',
    '  2.  Rashomon (1950)          .... four truths, no verdict',
    '  3.  Ikiru (1952)             .... the quietest and the saddest',
    '  4.  Ran (1985)               .... the colour and the ruin',
    '  5.  Yojimbo (1961)           .... the one that made a genre',
    '</pre>',
    '',
    '<p>Where to go next in this ring. Kurosawa is the loud door into Japanese',
    'cinema, so try the quiet one after him: Ozu at',
    '<a href="yasujiro-ozu.geocities.ws">yasujiro-ozu</a>, who never moved the',
    'camera if he could help it and broke your heart anyway. And the film most',
    'often set against <i>Seven Samurai</i> as its opposite pole is <i>Tokyo',
    'Story</i>, close-read at <a href="tokyo-story.geocities.ws">tokyo-story</a>.',
    'Mizoguchi and Naruse, the other two of the great postwar trio, are named on',
    'the primer pages if you follow the ring round.</p>',
    '<hr>',
    '<p><small>you are visitor 03412 &middot; best viewed in Netscape at 800x600',
    '&middot; this shrine is under permanent construction, there is always another',
    'film &middot; last updated 8 Dec</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- Ozu: the quiet appreciation --------------------------------------------

const OZU = P('yasujiro-ozu.geocities.ws', 'OZU',
  'YASUJIRO OZU // the tatami eye', [
    '<!--bg:cine-asia-->',
    '<h1>YASUJIRO OZU</h1>',
    '<p><small>an appreciation of Yasujiro Ozu (1903&ndash;1963), by a member of',
    'the film society who came for Kurosawa and stayed, in the end, for Ozu. it',
    'takes a few films. then it takes you over. &mdash; H.T., society treasurer</small></p>',
    '<hr>',
    '<p>Ozu made roughly one kind of film, the family drama, over and over, and',
    'got deeper into it every time. Parents and grown children, a marriage to',
    'arrange, a house that will soon be emptier, the ordinary passage of a family',
    'through time. Almost nothing &ldquo;happens&rdquo; in the loud sense. A',
    'daughter agrees to marry and leave her widowed father. An old couple visit',
    'the city. That is a plot, for Ozu, and it is enough for the deepest picture',
    'in the cinema of how families come apart gently, by nobody&rsquo;s fault.</p>',
    '<div class="fs-aside"><p><b>The tatami shot.</b> Ozu set the camera about a',
    'metre off the floor, at the eye level of a person kneeling on a tatami mat,',
    'and left it there. Low, still, looking slightly up. It is the posture of a',
    'guest in a Japanese room, and it puts you at the family&rsquo;s own height',
    'rather than standing over them. Once you have noticed it you cannot unsee',
    'it.</p></div>',
    '<p>Two more habits define him. The PILLOW SHOT, a name critics borrowed from',
    'the &ldquo;pillow word&rdquo; of Japanese verse: a cutaway to an empty',
    'corridor, a hanging kettle, rooftops, a passing train, held for a few',
    'seconds with no people in it. It is not establishing anything and it is not',
    'symbolic exactly. It is a rest, a breath between scenes, a place to let the',
    'feeling settle before the next room. And the famous refusal of the',
    'convention that actors should not look down the lens: Ozu&rsquo;s people',
    'address the camera almost head on when they talk, so you are seated at the',
    'table, spoken to, not spying.</p>',
    '<blockquote class="fs-quote"><p>He would not cut on movement and he would not',
    'follow a moving figure with a pan. He said he had no use for the crane or the',
    'dolly. What looks like poverty of technique is a whole grammar built by',
    'subtraction.</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/cine/ozu-01.jpg" alt=""><span class="indie-cap">Yasujirō Ozu (public domain)</span>',
    '<p>Film scholars talk about Ozu&rsquo;s &ldquo;360-degree space&rdquo;. The',
    'old Hollywood rule keeps the camera on one side of an imaginary line between',
    'two people talking so that left stays left. Ozu ignored it. He placed the',
    'camera anywhere in the full circle of the room, so two people conversing may',
    'both seem to face the same way. It should be confusing and it never is; he',
    'built his own consistent geometry and trusts you to live inside it.</p>',
    '<p><i>Late Spring</i> (1949) is the place to start, and the template for much',
    'that followed. A widowed professor and his devoted grown daughter keep house',
    'together, content; everyone agrees she must marry before it is too late, and',
    'so the father pretends he intends to remarry to free her to go. The last',
    'shot, the father alone peeling an apple in the emptied house, is one of the',
    'quietest devastations on film. Setsuko Hara plays the daughter, smiling',
    'through the whole picture, and the smile is the tragedy.</p>',
    '<p class="fs-pull">&ldquo;I am like a tofu-maker. All I make is tofu.&rdquo;',
    '<br>&mdash; Yasujiro Ozu, on making the same film again and again</p>',
    '<p>Where to go next. The masterpiece most people reach for is <i>Tokyo',
    'Story</i>, and it has its own close reading at',
    '<a href="tokyo-story.geocities.ws">tokyo-story</a>. For a very different',
    'sensibility built on the same humanist patience, cross the water to India',
    'and Satyajit Ray at <a href="satyajit-ray.geocities.ws">satyajit-ray</a>,',
    'who admired this kind of attention to the everyday and returned it in his own',
    'key.</p>',
    '<hr>',
    '<p><small>counter 01188 &middot; best viewed at 800x600 &middot; a proud page',
    'of the cineaste webring &middot; last tended 21 Nov</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- Ray: the tribute -------------------------------------------------------

const RAY = P('satyajit-ray.geocities.ws', 'RAY',
  'SATYAJIT RAY // the humanist eye', [
    '<!--bg:cine-asia-->',
    '<h1>SATYAJIT RAY</h1>',
    '<p><small>a tribute page for Satyajit Ray (1921&ndash;1992), kept by a',
    'student in the film-studies society who thinks he is the most underrated of',
    'the great directors in the West and will argue it with anyone. &mdash; R.,',
    'second year</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;The only solutions that are ever worth anything are',
    'the solutions that people find themselves.&rdquo; &mdash; Satyajit Ray</p>',
    '<p>Ray came to film from graphic design and illustration in Calcutta, taught',
    'himself by watching everything the city&rsquo;s film society could screen,',
    'and was pushed over the edge by two encounters: seeing De Sica&rsquo;s',
    '<i>Bicycle Thieves</i> in London, and meeting Jean Renoir when Renoir came to',
    'Bengal to shoot <i>The River</i>. Italian neorealism taught him you could',
    'make a great film in the street with non-actors and almost no money; Renoir',
    'taught him to watch people without judging them. Both lessons are in every',
    'frame he shot.</p>',
    '<p>His monument is the APU TRILOGY, three films following one boy from a',
    'Bengal village to manhood in the city. <i>Pather Panchali</i> (1955), the',
    'first, was made on weekends over years as the money came and went, partly',
    'funded in the end by the state government of West Bengal. It follows a poor',
    'Brahmin family, the boy Apu and his sister Durga, through hunger, small joys,',
    'a monsoon, and a death, with a patience that has no hurry in it at all. The',
    'children see a train for the first time across a field of white kaash grass,',
    'and the image became the emblem of a whole national cinema.</p>',
    '<img class="indie-pic" src="assets/media/web/cine/ray-01.jpg" alt=""><span class="indie-cap">Satyajit Ray (photo: Dinu Alam, CC BY-SA 4.0)</span>',
    '<p>The trilogy continues with <i>Aparajito</i> (1956) and closes with',
    '<i>Apur Sansar</i> (1959), the boy now a man, married almost by accident,',
    'and then a father. Ravi Shankar wrote the music for the first film in a',
    'single long night, the sitar under the rain, and the sound of it is half the',
    'reason people weep. Ray went on to a long career of quiet range, from the',
    'costume drama <i>The Music Room</i> (1958) to the sharp Calcutta films of the',
    'nineteen-seventies, but the trilogy is where a newcomer should begin.</p>',
    '<blockquote class="fs-quote"><p>He did his own thing at every station of the',
    'craft. He wrote the scripts, drew the storyboards, chose the shots, and from',
    'the nineteen-sixties on composed his own scores. Few directors have held so',
    'many of the reins at once and pulled so gently.</p></blockquote>',
    '<p>What people mean by his HUMANIST EYE is a refusal to make anyone a',
    'villain. The camera stays with a face a beat longer than the plot needs, and',
    'in that beat you are asked to understand rather than to judge. He filmed the',
    'everyday, a meal, a walk to fetch water, a letter read aloud, as though the',
    'everyday were where the whole meaning of a life is kept.</p>',
    '<p>Where to go next. For the wider field Ray came out of and towered over,',
    'the parallel cinema of Ghatak and Sen and the Bengali renaissance, see the',
    'primer at <a href="indian-cinema.geocities.ws">indian-cinema</a>. And the',
    'director most often named in the same breath as Ray for sheer stature is',
    'Kurosawa, the shrine at',
    '<a href="akira-kurosawa.geocities.ws">akira-kurosawa</a>; the two of them',
    'admired each other warmly across the years.</p>',
    '<hr>',
    '<p><small>hits: 00967 &middot; best viewed in Netscape at 800x600 &middot;',
    'this page is a member of the cineaste webring &middot; last updated 14 Oct',
    '</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- Tokyo Story: the close reading -----------------------------------------

const TOKYO_STORY = P('tokyo-story.geocities.ws', 'TOKYO STORY',
  'TOKYO STORY (1953) // a close reading', [
    '<!--bg:cine-asia-->',
    '<h1>TOKYO STORY &mdash; a close reading</h1>',
    '<p><small>coursework kept online for the reading group. FS3021 World Cinema,',
    'single-film study. all page references are to the film itself, timings from',
    'the print we screened. corrections welcome. &mdash; posted by the module',
    'convenor</small></p>',
    '<hr>',
    '<p><b>The film in one line.</b> An elderly couple travel from their small',
    'town to Tokyo to visit their grown children, find the children too busy and',
    'too small-hearted to have time for them, and go home; on the way back the',
    'mother falls ill and dies. Ozu, 1953. That is the whole plot, and it is one',
    'of the two or three films that turn up on every serious list of the greatest',
    'ever made.</p>',
    '<div class="fs-aside"><p><b>Note on the poll.</b> In the once-a-decade critics',
    'poll that the film world treats as its census, <i>Tokyo Story</i> has sat near',
    'the very top for years, and in the poll of directors it has more than once',
    'been voted the single greatest film. Take polls for what they are, but the',
    'company is not accidental.</p></div>',
    '<p><b>The old couple.</b> Chishu Ryu and Chieko Higashiyama play the parents',
    'with an unforced patience; they never complain, and their courtesy is what',
    'makes the children&rsquo;s neglect land so hard. The one person who is kind',
    'to them is Noriko, the widow of their son killed in the war, played by',
    'Setsuko Hara, who owes them nothing by blood and gives them everything by',
    'grace. Ozu sets the true daughter&rsquo;s coldness against the',
    'daughter-in-law&rsquo;s warmth and never once underlines it.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Isn&rsquo;t life disappointing?&rdquo;',
    'says the youngest daughter near the end. &ldquo;Yes, it is,&rdquo; Noriko',
    'answers, and smiles. The film&rsquo;s whole sorrow and its whole consolation',
    'are in that exchange.</p></blockquote>',
    '',
    '<p><b>The low camera and the transitions.</b> Everything said on the Ozu',
    'page about the tatami-level camera is here at its most disciplined: the shot',
    'height barely changes for two hours, so that when the mother is dying the',
    'stillness of the frame does the grieving the characters are too composed to',
    'do. Between scenes Ozu cuts to his pillow shots, a harbour, a passing train,',
    'washing on a line, smoke from a chimney, each a held breath. The transitions',
    'are not decoration; they are the film&rsquo;s sense of time passing over a',
    'family that cannot hold itself together.</p>',
    '<pre>',
    'FS3021 — points to bring to the reading group',
    '  1.  Count the pillow shots. What is each one doing?',
    '  2.  Noriko has no duty to be kind. Why is she the moral centre?',
    '  3.  The father drinks with old friends and admits his',
    '      children disappointed him. Is this the emotional pivot?',
    '  4.  The camera almost never moves. Track the exceptions.',
    '  5.  Compare the smile of Setsuko Hara here with Late Spring.',
    '</pre>',
    '<p><b>Wonky bibliography</b> (as handed round, verify before citing):</p>',
    '<pre>',
    '  Richie, D. — Ozu (Univ. of California Press), the standard book',
    '  Bordwell, D. — Ozu and the Poetics of Cinema',
    '  Desser, D. (ed.) — Ozu&#39;s Tokyo Story, a casebook',
    '  [someone had &quot;Sight &amp; Sound poll&quot; scrawled here, no year]',
    '</pre>',
    '<p>Where to go next. Read this against the director&rsquo;s wider method at',
    '<a href="yasujiro-ozu.geocities.ws">yasujiro-ozu</a>, and set it in the',
    'national story at <a href="japanese-cinema.geocities.ws">japanese-cinema</a>,',
    'where the postwar golden age that produced it is laid out.</p>',
    '<hr>',
    '<p><small>viewed 00742 times &middot; best at 800x600 &middot; kept for the',
    'FS3021 reading group &middot; last updated 2 Mar</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- Japanese cinema: the national primer -----------------------------------

const JAPANESE_CINEMA = P('japanese-cinema.geocities.ws', 'JAPAN',
  'JAPANESE CINEMA // a national primer', [
    '<!--bg:cine-asia-->',
    '<h1>JAPANESE CINEMA &mdash; a primer</h1>',
    '<p><small>a primer for newcomers, written up by the programmer of a Japanese',
    'season so people would stop asking &ldquo;is it all samurai?&rdquo; at the',
    'interval. it is not all samurai. read on. &mdash; the season desk</small></p>',
    '<hr>',
    '<p>Japan had one of the great studio cinemas long before the West noticed,',
    'and a vocabulary worth learning at the door. Films divide, roughly, into',
    'JIDAIGEKI, the period drama set before the modern era, swords and castles and',
    'the samurai code, and GENDAIGEKI, the contemporary drama of families, offices',
    'and small towns. Kurosawa worked both; Ozu worked almost only the second. The',
    'division is not a wall, but it is the first map.</p>',
    '<div class="fs-aside"><p><b>The great trio.</b> Say &ldquo;Japanese cinema&rdquo;',
    'to a programmer and three names come back: Kurosawa, Ozu and Kenji Mizoguchi.',
    'Add Mikio Naruse and you have the four corners of the classical era. Kurosawa',
    'is the West&rsquo;s door; the other three are the reward for staying.</p></div>',
    '<p>Kenji Mizoguchi (1898&ndash;1956) is the master of the long take and the',
    'moving camera, the &ldquo;one scene, one shot&rdquo; that lets a whole',
    'unhappiness unfold without a cut to relieve it. <i>Ugetsu</i> (1953) and',
    '<i>Sansho the Bailiff</i> (1954) are the entries; both are ghost-haunted,',
    'both centre on women broken by a men&rsquo;s world, and both move the camera',
    'like a slow tide. Critics speak of his frame as a scroll unrolling, the eye',
    'carried sideways across a painted world.</p>',
    '',
    '<p>Mikio Naruse (1905&ndash;1969) is the quietest and the hardest to find,',
    'the poet of ordinary disappointment, of women getting by in a Tokyo that',
    'gives them no room. <i>When a Woman Ascends the Stairs</i> (1960) is the way',
    'in. If Ozu is resignation with a smile, Naruse is resignation without one.</p>',
    '<p>The POSTWAR GOLDEN AGE, roughly the late nineteen-forties into the',
    'nineteen-sixties, is when all of this reached the West at once. <i>Rashomon</i>',
    'winning at Venice in 1951 opened the gate; within a few years the festivals',
    'and the art houses of Europe and America were full of Japanese films, and the',
    'canon we now teach was largely set. The studios were factories, turning out',
    'genre pictures by the hundred, and the masters worked inside that system, not',
    'outside it.</p>',
    '<pre>',
    'A FIRST JAPANESE SEASON — six to start with',
    '  Rashomon (Kurosawa, 1950)          the door',
    '  Tokyo Story (Ozu, 1953)            the summit of the home drama',
    '  Ugetsu (Mizoguchi, 1953)           the ghost story as tragedy',
    '  Seven Samurai (Kurosawa, 1954)     the jidaigeki at full stretch',
    '  Sansho the Bailiff (Mizoguchi, 1954)  the long take that hurts',
    '  When a Woman Ascends the Stairs (Naruse, 1960)',
    '</pre>',
    '<p>Where to go next. The obvious first stop is the Kurosawa shrine at',
    '<a href="akira-kurosawa.geocities.ws">akira-kurosawa</a>. For the other great',
    'national cinema of the region and its parallel-cinema movement, cross to',
    '<a href="indian-cinema.geocities.ws">indian-cinema</a>. Ozu and Tokyo Story',
    'have their own pages if you follow the ring round.</p>',
    '<hr>',
    '<p><small>counter 01044 &middot; best viewed in Netscape at 800x600 &middot;',
    'a cineaste webring page, under construction (always) &middot; last updated 30',
    'Sep</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

// ---- Indian cinema: the national primer -------------------------------------

const INDIAN_CINEMA = P('indian-cinema.geocities.ws', 'INDIA',
  'INDIAN CINEMA // the parallel and the popular', [
    '<!--bg:cine-asia-->',
    '<h1>INDIAN CINEMA &mdash; a primer</h1>',
    '<p><small>a primer kept by a member of the film society who got tired of',
    'people saying &ldquo;Indian film&rdquo; and meaning only the song-and-dance',
    'blockbuster. there is a whole other tradition. this page is about that one.',
    '&mdash; posted by the society librarian</small></p>',
    '<hr>',
    '<p>India makes more films than any country on earth, and most people abroad',
    'know only the popular cinema, the big song-and-dance melodrama of the Bombay',
    'and southern studios, which is a real and vast art in its own right. But',
    'running alongside it from the nineteen-fifties on there was a second',
    'tradition, the PARALLEL CINEMA, serious, low-budget, socially engaged, closer',
    'to Italian neorealism than to the box office. This page is a door into that.</p>',
    '<p>Its centre of gravity was Bengal, and the moment is often called the',
    'BENGALI RENAISSANCE of film. Three names hold it up. Satyajit Ray, the',
    'humanist and the internationalist, whose Apu Trilogy carried Indian cinema to',
    'the world&rsquo;s festivals and who has his own page at',
    '<a href="satyajit-ray.geocities.ws">satyajit-ray</a>. Ritwik Ghatak, fiercer',
    'and more operatic, marked all his life by the Partition of Bengal, whose',
    '<i>Meghe Dhaka Tara</i> (1960) is the essential entry. And Mrinal Sen, the',
    'political modernist, restless in form, whose <i>Bhuvan Shome</i> (1969) is',
    'often taken as the shot that started the New Indian Cinema of the',
    'nineteen-seventies.</p>',
    '<div class="fs-aside"><p><b>Ray, Ghatak, Sen.</b> A useful shorthand: Ray',
    'looks at the human being with compassion, Ghatak looks at history with grief,',
    'and Sen looks at society with an argument. Three temperaments, one renaissance,',
    'often at odds with one another, which is how you know it was alive.</p></div>',
    '',
    '<p>The parallel cinema drew state support through the Film Finance',
    'Corporation, took its bearings from neorealism and the European art film, and',
    'set itself deliberately against the conventions of the popular product, the',
    'star, the interval, the half-dozen songs. It did not despise the popular',
    'cinema so much as want to do something the popular cinema had no room for: to',
    'look steadily at poverty, caste, the countryside and the city without turning',
    'them into spectacle.</p>',
    '<blockquote class="fs-quote"><p>The song and the melodrama, which the parallel',
    'film set itself against, are not a failing of the popular cinema but its',
    'genius, a form with its own long roots in Indian theatre and music. The two',
    'traditions are best understood together, as an argument rather than a',
    'hierarchy.</p></blockquote>',
    '<pre>',
    'PARALLEL CINEMA — a first shelf',
    '  Pather Panchali (Ray, 1955)          the film that opened the door',
    '  Meghe Dhaka Tara (Ghatak, 1960)      Partition and a sister&#39;s ruin',
    '  Bhuvan Shome (Sen, 1969)             the New Indian Cinema begins',
    '  The Music Room (Ray, 1958)           the decaying aristocrat',
    '  Ankur (Benegal, 1974)                the movement widens beyond Bengal',
    '</pre>',
    '<p>Where to go next. The deepest single body of work in this tradition is',
    'Ray&rsquo;s, at <a href="satyajit-ray.geocities.ws">satyajit-ray</a>. For the',
    'other great Asian national cinema in this ring, its studios, its masters and',
    'its golden age, cross to',
    '<a href="japanese-cinema.geocities.ws">japanese-cinema</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00688 &middot; best viewed at 800x600 &middot; a member',
    'page of the cineaste webring &middot; last updated 7 Jan</small></p>',
    '<p><small>[ <a href="world-cinema-ring.geocities.ws">World Cinema Ring</a> ]</small></p>',
  ]);

export const CINE_D = [KUROSAWA, OZU, RAY, TOKYO_STORY, JAPANESE_CINEMA, INDIAN_CINEMA];
