// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// FILE C — modernism. Six pages a reader kept about the great modernists: a
// book-group’s reading notes on Ulysses (the showpiece), a tidy academic
// summary of Woolf, the minutes of a Proust evening, a Kafka fan shrine, a
// student’s Faulkner coursework, and the write-up of a Mann lecture. The
// novels, dates and quotations are real; the enthusiasms are the pages' own.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Joyce: the book-group reading notes on Ulysses (SHOWPIECE) -------------

const JOYCE = P('james-joyce.geocities.ws', 'JAMES JOYCE',
  'READING ULYSSES // notes for the group // James Joyce', [
    '<!--bg:lit-modernism-->',
    '<h1>READING ULYSSES</h1>',
    '<p><small>working notes kept for the Thursday reading group as we go through',
    '<i>Ulysses</i> (1922) a few episodes at a time. not a summary, a set of',
    'handrails, so nobody drops out around Oxen of the Sun. corrections welcome.',
    '— kept by the note-taker</small></p>',
    '<hr>',
    '<p class="fs-epi">“Stately, plump Buck Mulligan came from the stairhead,',
    'bearing a bowl of lather on which a mirror and a razor lay crossed.”<br>',
    '— the first sentence, <i>Ulysses</i></p>',
    '<p>One day in one city. The whole book takes place in Dublin on 16 June 1904,',
    'a Thursday, from morning to the small hours of the next day. Readers now keep',
    'that date every year and call it BLOOMSDAY, after Leopold Bloom, the',
    'advertising canvasser whose ordinary wanderings across the city carry the',
    'book. Stephen Dedalus, the young man from Joyce’s earlier <i>A Portrait of',
    'the Artist as a Young Man</i> (1916), is the other centre. Bloom is the',
    'father he does not know he is looking for.</p>',
    '<p><b>The Homeric parallel.</b> Joyce laid Homer’s <i>Odyssey</i> under the',
    'day like a template. Bloom is Odysseus (Ulysses is the Latin name), his wife',
    'Molly is a Penelope who does not wait, Stephen is Telemachus the son. Each of',
    'the eighteen episodes answers to an adventure from the poem. Joyce gave the',
    'episodes those Homeric names privately, in a schema he passed to friends;',
    'they are not printed in the book, which is why we list them below.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/joyce-01.jpg" alt=""><span class="indie-cap">James Joyce (photo: Alex Ehrenzweig, public domain)</span>',
    '<pre>',
    'THE EIGHTEEN EPISODES (Joyce’s Homeric titles)',
    '',
    '  I. THE TELEMACHIAD',
    '     1  Telemachus',
    '     2  Nestor',
    '     3  Proteus',
    '',
    ' II. THE ODYSSEY',
    '     4  Calypso',
    '     5  Lotus Eaters',
    '     6  Hades',
    '     7  Aeolus',
    '     8  Lestrygonians',
    '     9  Scylla and Charybdis',
    '    10  Wandering Rocks',
    '    11  Sirens',
    '    12  Cyclops',
    '    13  Nausicaa',
    '    14  Oxen of the Sun',
    '    15  Circe',
    '',
    'III. THE NOSTOS (the homecoming)',
    '    16  Eumaeus',
    '    17  Ithaca',
    '    18  Penelope',
    '</pre>',
    '<p><b>Stream of consciousness.</b> The technique everyone means when they say',
    '"difficult". Joyce writes thought as it actually runs: half-finished, jumping,',
    'private, without stopping to explain itself to us. We are inside Bloom’s head',
    'and Stephen’s, and by the end inside Molly’s, and the prose changes its whole',
    'manner from episode to episode. Aeolus is set out like a newspaper with',
    'headlines. Sirens is arranged like music. Oxen of the Sun runs through the',
    'history of English prose style from Anglo-Saxon forward, which is the one the',
    'group always dreads, so take it slowly and do not try to catch every echo.</p>',
    '<div class="fs-aside"><b>How to read it without giving up</b><br>',
    'Read it aloud when it stops making sense on the page; a lot of it is sound',
    'before it is meaning. Keep a Dublin map to hand for Wandering Rocks. Do not',
    'look every allusion up on the first pass. Getting the drift of a page beats',
    'decoding one line and losing the hour.</div>',
    '<p>The last episode, Penelope, is Molly Bloom in bed, eight enormous',
    'unpunctuated sentences of drifting thought that close the book on a rising',
    'note of assent:</p>',
    '<blockquote class="fs-quote"><p>“yes I said yes I will Yes.”</p>',
    '<p>— Molly Bloom, the final words of <i>Ulysses</i></p></blockquote>',
    '<p class="fs-pull">One ordinary man, one ordinary day, written as if it held',
    'the whole of the Odyssey and the whole of the English language.</p>',
    '<p><b>Where it comes from.</b> Before the big books there is <i>Dubliners</i>',
    '(1914), fifteen short stories of the city that repay reading first. They turn',
    'on what Joyce called the EPIPHANY: a small ordinary moment in which something',
    'shows its true nature and a life stands suddenly revealed. The last and',
    'greatest, "The Dead", closes on snow falling over all of Ireland:</p>',
    '<img class="indie-pic" src="assets/media/web/lit/woolf-01.jpg" alt=""><span class="indie-cap">Virginia Woolf, by G. C. Beresford (public domain)</span>',
    '<blockquote class="fs-quote"><p>“His soul swooned slowly as he heard the snow',
    'falling faintly through the universe and faintly falling, like the descent of',
    'their last end, upon all the living and the dead.”</p>',
    '<p>— "The Dead", <i>Dubliners</i></p></blockquote>',
    '<p><b>The far shore.</b> After <i>Ulysses</i> Joyce spent seventeen years on',
    '<i>Finnegans Wake</i> (1939), a book written in a dream-language of puns and',
    'folded tongues that even devoted readers treat as a country you visit rather',
    'than cross. The group has agreed we are not going there this year. One',
    'homecoming at a time.</p>',
    '<hr>',
    '<p>If <i>Ulysses</i> takes, the two neighbours to read next are Virginia',
    'Woolf, who was working the single day and the inner voice in England at the',
    'very same time, over at',
    '<a href="virginia-woolf.geocities.ws">virginia-woolf</a>, and Franz Kafka,',
    'the other pole of the modern novel, dread where Joyce is delight, at',
    '<a href="franz-kafka.geocities.ws">franz-kafka</a>. Ezra Pound and T. S.',
    'Eliot championed Joyce early; Sylvia Beach published the book from her Paris',
    'bookshop when nobody in the English-speaking world would touch it.</p>',
    '<p><small>counter: 01922 · best viewed at 800x600 · this page under',
    'construction until we reach Ithaca · last updated 16 Jun</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Woolf: the academic summary --------------------------------------------

const WOOLF = P('virginia-woolf.geocities.ws', 'VIRGINIA WOOLF',
  'Virginia Woolf: a summary // modernism', [
    '<!--bg:lit-modernism-->',
    '<h1>Virginia Woolf (1882–1941)</h1>',
    '<p><small>a short summary page for students meeting Woolf for the first time.',
    'dates and titles checked; read the novels, not just this.</small></p>',
    '<hr>',
    '<p>Virginia Woolf stands with Joyce at the centre of English modernism, and',
    'like him she moved the novel inward, away from the machinery of plot and',
    'towards the flow of consciousness and the texture of a mind meeting the',
    'world. Where the Victorians told you what happened, Woolf shows you what it',
    'felt like to be alive inside a single passing moment.</p>',
    '<p><b>Mrs Dalloway (1925).</b> A whole novel in one June day in London.',
    'Clarissa Dalloway prepares to give a party; across the city the shell-shocked',
    'veteran Septimus Warren Smith moves towards his death; their days never quite',
    'touch and yet answer one another. The narration slides from mind to mind',
    'without warning, and the striking of Big Ben stitches the separate',
    'consciousnesses to the same hour. It is the clearest place to begin.</p>',
    '<p><b>To the Lighthouse (1927).</b> Often called her finest. The Ramsay',
    'family and their guests at a house in the Hebrides, in three movements. The',
    'long middle section, "Time Passes", empties the house of people and lets ten',
    'years and a war run through it in a few pages, which is one of the boldest',
    'things in the modern novel.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/woolf-01.jpg" alt=""><span class="indie-cap">Virginia Woolf, by G. C. Beresford (public domain)</span>',
    '<p><b>A Room of One’s Own (1929).</b> Not a novel but a long essay, grown out',
    'of lectures on women and fiction, and the source of the sentence everyone',
    'knows:</p>',
    '<blockquote class="fs-quote"><p>“A woman must have money and a room of her own',
    'if she is to write fiction.”</p>',
    '<p>— <i>A Room of One’s Own</i></p></blockquote>',
    '<p>The argument is material before it is anything else: the reason the shelves',
    'held so few women was not want of genius but want of the money, the privacy',
    'and the education that men had kept for themselves. Her invented figure of',
    'Shakespeare’s equally gifted sister, who had no such room and so wrote',
    'nothing, has done more than any statistic to make the point stick.</p>',
    '<p><b>The moment of being.</b> Woolf’s own name for those sudden flashes when',
    'the cotton-wool of ordinary daily life parts and something real shows',
    'through. Her fiction is built to catch them. The novels care less for the',
    'events of a life than for these lit instants, which is why so little seems to',
    '"happen" and so much is felt.</p>',
    '<p><b>The Hogarth Press.</b> In 1917 Woolf and her husband Leonard founded',
    'their own press, at first hand-setting the type themselves. It freed her to',
    'publish her most experimental work without asking anyone’s leave, and it gave',
    'the English reader the first translations of Freud and, for a time, the early',
    'poems of T. S. Eliot. Being her own publisher was part of how Woolf became',
    'so free a writer. She belonged to the Bloomsbury group of writers and',
    'artists, though the work is hers alone.</p>',
    '<hr>',
    '<p>Read alongside her: Joyce, the other master of the single day and the',
    'inner voice, at <a href="james-joyce.geocities.ws">james-joyce</a>, and',
    'Proust, whose vast novel of memory was appearing in Paris across the same',
    'years, at <a href="marcel-proust.geocities.ws">marcel-proust</a>.</p>',
    '<p><small>hits: 00884 · best viewed at 800x600 · last updated 25 Mar</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Proust: the reading-group minutes --------------------------------------

const PROUST = P('marcel-proust.geocities.ws', 'MARCEL PROUST',
  'Proust evening // minutes // In Search of Lost Time', [
    '<!--bg:lit-modernism-->',
    '<h1>Minutes: the Proust evening</h1>',
    '<p><small>minutes of the reading circle, the evening we gave over to Marcel',
    'Proust. present: nine members and a guest. tea, and someone brought the',
    'little cakes on purpose. — minuted by the secretary</small></p>',
    '<hr>',
    '<p><b>1. The book itself.</b> We agreed to call it <i>In Search of Lost',
    'Time</i>, though older members knew it as <i>Remembrance of Things Past</i>,',
    'and in French <i>À la recherche du temps perdu</i>. One novel in seven parts,',
    'begun with <i>Swann’s Way</i> (1913) and finished only after Proust’s death',
    'in 1922. Well over three thousand pages. Nobody present claimed to have',
    'reached the end, and we resolved not to pretend.</p>',
    '<p><b>2. The madeleine.</b> The passage the whole evening kept returning to.',
    'The narrator, grown and unhappy, tastes a spoonful of tea in which he has',
    'soaked a morsel of a little shell-shaped cake, a madeleine, and the taste',
    'brings his whole lost childhood at Combray flooding back, complete, unbidden.',
    'This is INVOLUNTARY MEMORY: the past recovered not by trying to remember but',
    'by an accident of the senses, a taste, a smell, an uneven paving stone. The',
    'guest made the point that willed memory gives us only facts about the past,',
    'while the involuntary kind gives the past back alive. Carried without',
    'objection.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/proust-01.jpg" alt=""><span class="indie-cap">Marcel Proust (photo: Otto Wegener, public domain)</span>',
    '<p class="fs-pull">The past is not behind us waiting to be summoned. It is',
    'hidden in some object we never think to look inside, and it ambushes us.</p>',
    '<p><b>3. The people.</b> We tried to keep the cast straight. Combray, the',
    'village of the childhood. Swann, the cultivated man of the world whose',
    'jealous love for Odette fills much of the first volume and rehearses the',
    'narrator’s own. The Guermantes, the aristocratic family whose name glows with',
    'glamour from far off and dims the closer the narrator is admitted to it.',
    'Charlus, Albertine. We gave up on a full family tree and agreed the book is',
    'about how these names change their meaning as a life goes on.</p>',
    '<p><b>4. The cork-lined room.</b> A member reminded us that Proust, asthmatic',
    'and increasingly a recluse, wrote much of the novel in a bedroom lined with',
    'cork to keep out the noise of Paris, working through the night and sleeping',
    'by day. The image pleased everyone: the whole vast social world of the book',
    'reconstructed from memory by a sick man in a silent sealed room.</p>',
    '<p><b>5. Any other business.</b> Two members admitted defeat at the length.',
    'The chair proposed we read only <i>Swann’s Way</i> for next time rather than',
    'the whole, and take the famous overture and the Combray section slowly.',
    'Agreed. Meeting closed at half past nine.</p>',
    '<hr>',
    '<p>Suggested neighbours for members who want more: Kafka, the other great',
    'European novelist of these years, at',
    '<a href="franz-kafka.geocities.ws">franz-kafka</a>, and Woolf, who was doing',
    'her own work on memory and the moment in English, at',
    '<a href="virginia-woolf.geocities.ws">virginia-woolf</a>. The English',
    'translation we mostly used is the old Scott Moncrieff.</p>',
    '<p><small>visitors: 00623 · best viewed at 800x600 · the reading circle,',
    'minutes archived · last updated 4 Feb</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Kafka: the personal fan shrine -----------------------------------------

const KAFKA = P('franz-kafka.geocities.ws', 'FRANZ KAFKA',
  'THE BURROW // a Kafka shrine // Franz Kafka', [
    '<!--bg:lit-modernism-->',
    '<h1>THE BURROW: a Kafka shrine</h1>',
    '<p><small>i have read these books more times than is healthy and i keep this',
    'page for the others who feel the same. Franz Kafka (1883–1924), Prague, dead',
    'at forty of tuberculosis, barely published in his life, now the adjective for',
    'the whole modern situation. — kept by a devotee</small></p>',
    '<hr>',
    '<p>Start where everyone starts, with the sentence that is the best opening in',
    'the language:</p>',
    '<blockquote class="fs-quote"><p>“As Gregor Samsa awoke one morning from',
    'uneasy dreams he found himself transformed in his bed into a gigantic',
    'insect.”</p><p>— <i>The Metamorphosis</i> (1915)</p></blockquote>',
    '<p>And then, and this is the whole of Kafka, nobody in the story finds it',
    'strange enough. Gregor’s first worry is that he will miss his train to work.',
    'His family’s first worry is money. The horror is not the insect, the horror',
    'is how quickly a life folds the monstrous into the ordinary and carries on.',
    'That is the trick he plays in everything: the impossible is admitted without',
    'comment, and the dread comes from the calm.</p>',
    '<p><b>The Trial (1925).</b> Josef K. is arrested one morning and never told',
    'the charge. He is not imprisoned; he is left free to go on with his life while',
    'the incomprehensible case grinds forward through offices in attics, past',
    'lawyers who explain nothing, towards an end he cannot appeal because he cannot',
    'find the court. Everyone who has ever been ground small by an institution that',
    'will not say what it wants recognises this book on sight.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/kafka-01.jpg" alt=""><span class="indie-cap">Franz Kafka (photo: Atelier Jacobi, public domain)</span>',
    '<p><b>The Castle (1926).</b> The mirror of it. Here K. wants IN and cannot get',
    'in. He arrives as a land surveyor summoned to a village ruled by a castle on',
    'the hill, and spends the whole unfinished book trying to reach an authority',
    'that acknowledges him only through messengers and lost letters. The Trial:',
    'shut out of your own defence. The Castle: shut out of the thing you were',
    'called to serve. Between them they map the modern feeling of the closed door.</p>',
    '<p><b>The letter to his father.</b> In 1919 Kafka wrote his father a letter',
    'of some fifty pages, an account of a lifetime of feeling small and judged',
    'before a large confident man. He gave it to his mother to pass on. She never',
    'delivered it. Read it and the fathers and faceless authorities all through',
    'the fiction stop being abstract.</p>',
    '<p><b>The instruction to burn it.</b> Here is the fact that should stop your',
    'heart. Kafka told his friend Max Brod to burn all of it, unread, when he',
    'died. The novels, the diaries, the letters, everything. Brod refused. He',
    'edited <i>The Trial</i>, <i>The Castle</i> and <i>Amerika</i> out of the',
    'papers and published them in the years after 1924, and that disobedience is',
    'the only reason any of this exists. We owe the whole of Kafka to a friend who',
    'would not do as he was asked.</p>',
    '<hr>',
    '<p>Where to go from the burrow: Proust, the other pole of the European novel',
    'in these years, patient and luminous where Kafka is spare and dark, at',
    '<a href="marcel-proust.geocities.ws">marcel-proust</a>, and Faulkner, the',
    'American who took the same modern dread into the deep South, at',
    '<a href="william-faulkner.geocities.ws">william-faulkner</a>. The old Muir',
    'translations are the ones most of us grew up on.</p>',
    '<p><small>counter: 00483 · best viewed at 800x600 · this page will not tell',
    'you what it wants · last updated 3 Jun</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Faulkner: the student coursework ---------------------------------------

const FAULKNER = P('william-faulkner.geocities.ws', 'WILLIAM FAULKNER',
  'ENGL 214 coursework // Faulkner // William Faulkner', [
    '<!--bg:lit-modernism-->',
    '<h1>Faulkner and the long sentence</h1>',
    '<p><small>ENGL 214: The Modern Novel. coursework essay, term 2. topic set:',
    '"difficulty and form in Faulkner". word count a bit over, sorry. — student',
    'submission</small></p>',
    '<hr>',
    '<p>William Faulkner (1897–1962) took the modernist methods that Joyce and',
    'Woolf were using on London and Dublin and turned them on the American South,',
    'on a single imagined county in Mississippi that he populated across novel',
    'after novel. He called it YOKNAPATAWPHA COUNTY, invented the name and even',
    'drew the map, and made it, in his own phrase, his "own little postage stamp',
    'of native soil". The families recur, the same land is fought over across',
    'generations, and the history of the South, slavery and its long aftermath,',
    'is the ground everything grows in.</p>',
    '<p><b>The Sound and the Fury (1929).</b> The hard one and the great one. Four',
    'sections, four ways of telling the fall of the Compson family. The first is',
    'narrated by BENJY, a man with the mind of a small child who has no sense of',
    'time, so his section slides between decades without warning inside a single',
    'paragraph, a smell or a word tipping him from now into thirty years ago. It',
    'is baffling on the first read and it is meant to be; you are inside a',
    'consciousness that cannot order its own past. The title comes from Macbeth:',
    'life as "a tale told by an idiot, full of sound and fury, signifying',
    'nothing".</p>',
    '<p><b>The long sentence.</b> Faulkner’s sentences can run for a page and',
    'more, piling clause on clause, doubling back, refusing to close, because the',
    'past for him is never finished and a sentence that stopped cleanly would be',
    'telling a lie about time. His most quoted line puts it plainly:</p>',
    '<blockquote class="fs-quote"><p>“The past is never dead. It’s not even',
    'past.”</p><p>— <i>Requiem for a Nun</i> (1951)</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/lit/faulkner-01.jpg" alt=""><span class="indie-cap">William Faulkner (photo: Carl Van Vechten, public domain)</span>',
    '<p><b>As I Lay Dying (1930).</b> The one i would start with. The Bundren',
    'family carry their mother’s coffin across the county to bury her, and the',
    'whole novel is told in short first-person bursts by fifteen different',
    'characters, the living and, once, the dead woman herself. Shorter than <i>The',
    'Sound and the Fury</i> and easier to hold, but doing the same thing: a single',
    'event assembled out of many partial minds, no one of them the whole truth.</p>',
    '<p>My argument, briefly, is that the difficulty is not decoration. Faulkner',
    'makes us do the work of assembling the story because that is what memory and',
    'history actually are, a jumble we piece together and never quite finish. The',
    'form is the meaning. He was given the Nobel Prize in 1949.</p>',
    '<hr>',
    '<p><b>Bibliography (works cited)</b></p>',
    '<pre>',
    'Faulkner, W. The Sound and the Fury. 1929.',
    'Faulkner, W. As I Lay Dying. 1930.',
    'Faulkner, W. Absalom, Absalom! 1936.',
    'Faulkner, W. Requiem for a Nun. 1951. [the "past" quote]',
    '   -- and the Nobel banquet speech, 1950, which we did in class',
    '</pre>',
    '<p>Cross-reading for the essay: Mann, the European master of the same big',
    'ambitious modern novel, at <a href="thomas-mann.geocities.ws">thomas-mann</a>,',
    'and Joyce, whose stream of consciousness Faulkner clearly learned from, at',
    '<a href="james-joyce.geocities.ws">james-joyce</a>.</p>',
    '<p><small>counter: 00318 · best viewed at 800x600 · handed in one day late ·',
    'last updated 12 May</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

// ---- Mann: the lecture write-up ---------------------------------------------

const MANN = P('thomas-mann.geocities.ws', 'THOMAS MANN',
  'Notes on a Thomas Mann lecture // modernism', [
    '<!--bg:lit-modernism-->',
    '<h1>"Irony and the German soul": a Mann lecture, written up</h1>',
    '<p><small>notes taken at an evening lecture on Thomas Mann given at the',
    'literary society, written up afterwards for members who could not attend.',
    'any errors are mine, not the speaker’s. — a member</small></p>',
    '<hr>',
    '<p>The speaker began by placing Thomas Mann (1875–1955) as the great German',
    'novelist of the age, the man who carried the long, patient, deeply serious',
    'European novel into the twentieth century and won the Nobel Prize for it in',
    '1929. Where the other modernists broke the sentence, she said, Mann kept it',
    'whole and made his newness out of IRONY: a narrator who holds his characters',
    'and their ideas at a faint, affectionate, examining distance, never quite',
    'letting us or himself settle.</p>',
    '<p><b>Buddenbrooks (1901).</b> His first novel, written when he was in his',
    'twenties, and the book the Nobel citation named. It follows a prosperous',
    'merchant family in the northern town of Lübeck across four generations as',
    'their commercial vigour slowly gives way to sensitivity, art and illness. The',
    'speaker’s point: as the family grows more refined it grows less fit to',
    'survive, and Mann watches that decline with a cool tenderness that is the',
    'whole tone of his work.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/mann-01.jpg" alt=""><span class="indie-cap">Thomas Mann (photo: Carl Van Vechten, public domain)</span>',
    '<p><b>Death in Venice (1912).</b> The famous novella. Gustav von Aschenbach,',
    'a disciplined ageing writer, travels to Venice, becomes fixated on the beauty',
    'of a Polish boy, Tadzio, and stays on as cholera spreads through the city',
    'until it kills him. The lecture read it as the collapse of a life built',
    'wholly on discipline and form the moment beauty and desire are let in. Order',
    'and its undoing, she said, is Mann’s lifelong subject.</p>',
    '<p><b>The Magic Mountain (1924).</b> The centre of the evening. A young',
    'engineer, Hans Castorp, goes up to a tuberculosis sanatorium in the Swiss',
    'Alps at Davos to visit his cousin for three weeks, and stays for seven years.',
    'Time itself dilates on the mountain, and Castorp is fought over by two',
    'tutors, the humanist Settembrini and the radical Naphta, whose long debates',
    'carry the argument of a whole European civilisation on the edge of the First',
    'World War. The speaker called it a novel that swallows a continent’s ideas',
    'and never stops being a story.</p>',
    '<p class="fs-pull">On the mountain three weeks become seven years, and a young',
    'man’s ordinary education becomes the education of an age.</p>',
    '<p>She closed by noting that Mann later left Germany when the Nazis came to',
    'power and spoke against them from exile, so that the ironist turned out to',
    'have a firm centre after all. Questions ran on past the hour.</p>',
    '<hr>',
    '<p>The speaker recommended reading Mann next to Faulkner, the American at',
    'work on the same scale of ambitious modern novel, at',
    '<a href="william-faulkner.geocities.ws">william-faulkner</a>, and Proust,',
    'his true European companion in the long novel of a whole society, at',
    '<a href="marcel-proust.geocities.ws">marcel-proust</a>. The Lowe-Porter',
    'translations are the ones most in the room had read.</p>',
    '<p><small>attendance: 00247 · best viewed at 800x600 · the literary society,',
    'lecture notes · last updated 18 Nov</small></p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
  ]);

export const LIT_C = [JOYCE, WOOLF, PROUST, KAFKA, FAULKNER, MANN];
