// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH B — the systems languages.
//
// Fan pages kept on a free host, each ABOUT a language or its designer and
// never in the designer’s own voice. A C devotee who keeps a battered copy of
// K&R by the keyboard; a C++ shrine that spends half its length defending the
// language from the people who use it; an affectionate Pascal page that will
// not hear a word against Wirth; a page for the typeless ancestors B and BCPL;
// a page for Ada and its committee; and Modula-2 and Oberon, each smaller than
// the last. The names, titles and dates are real; the loyalties are the fans’.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- C: the K&R devotee -----------------------------------------------------

const C_RITCHIE = P('c-ritchie.geocities.ws', 'C / RITCHIE',
  'DENNIS RITCHIE // C, and the book on the shelf', [
    '<!--bg:systems-->',
    '<h1>DENNIS RITCHIE AND C</h1>',
    '<p><small>a page for Dennis Ritchie (1941–2011) and the language i actually',
    'earned my living in. i learned it from one thin book and a lot of segfaults.',
    'keeper of this page: a night-shift sysadmin who still writes his tools in C. — greg</small></p>',
    '<hr>',
    '<h2>Bell Labs, 1972</h2>',
    '<p>Ritchie built C at Bell Labs around 1972, growing it alongside Unix so the',
    'two came up together. Unix had started in assembler on a small machine, and',
    'the point of C was to write the operating system itself in something higher',
    'than raw instructions and still keep it close enough to the metal to be fast.',
    'That is the whole trick of the language. It sits one short step above the',
    'hardware and pretends to be nothing more.</p>',
    '<p>Because Unix could be rewritten in C, Unix could be MOVED. Port the compiler',
    'and the system followed. That portability is why so much of what you are using',
    'right now, underneath everything, is still C or a descendant of it.</p>',
    '<h2>The thinnest famous book</h2>',
    '<p>The manual is <i>The C Programming Language</i> (1978), Brian Kernighan and',
    'Dennis Ritchie, which everyone just calls K&amp;R. It is astonishingly short',
    'for a book that taught a generation, and the first program in it is the reason',
    'every language since prints the same two words to say hello:</p>',
    '<pre>main()\n{\n    printf("hello, world\\n");\n}</pre>',
    '<img class="indie-pic" src="assets/media/web/lang/ritchie-01.jpg" alt=""><span class="indie-cap">Dennis Ritchie (photo: Denise Panyik-Dale, CC BY)</span>',
    '<p>Kernighan wrote the prose and the examples, Ritchie designed the language;',
    'the second edition (1988) is the one for ANSI C, and it is the one to buy if',
    'you are buying. Keep it by the keyboard. You will open it more than you think.</p>',
    '<h2>Sharp on purpose</h2>',
    '<p>C hands you the pointer and trusts you not to cut yourself, and of course',
    'you do. Undefined behaviour, the off-by-one, the buffer you overran, all of it',
    'is the price of a language that refuses to stand between you and the address',
    'space. Ritchie knew the bargain. He gave you the power and the rope.</p>',
    '<div class="fs-aside">Ritchie also gets too little credit for Unix itself; he',
    'and Ken Thompson shared the 1983 Turing Award for it. The language usually',
    'grabs the spotlight, but the system came in the same pair of hands.</div>',
    '<h2>Neighbours</h2>',
    '<p>C did not come from nowhere. It grew straight out of the typeless machine',
    'languages B and BCPL, and that story is worth its own page over at',
    '<a href="unix-b-bcpl.geocities.ws">unix-b-bcpl</a>. And when people wanted',
    'objects bolted on top without losing the speed, they got',
    '<a href="cpp-stroustrup.geocities.ws">cpp-stroustrup</a>, which is either the',
    'best or the worst thing that ever happened to C depending on who you ask.</p>',
    '<hr>',
    '<p><small>counter: 03271 · best viewed at 800x600 · this site hand-written in a',
    'text editor, obviously · under construction (the pointers section) · last',
    'updated 14 Oct</small></p>',
    '<p><small>',
    '[ <a href="programming-languages-ring.geocities.ws">Programming Languages Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- C++: the showpiece shrine ----------------------------------------------

const CPP_STROUSTRUP = P('cpp-stroustrup.geocities.ws', 'C++ / STROUSTRUP',
  'BJARNE STROUSTRUP // C++, and the people who complain about it', [
    '<!--bg:systems-->',
    '<h1>BJARNE STROUSTRUP AND C++</h1>',
    '<p><small>a shrine to the most complained-about language on Earth, kept by',
    'someone who ships game engines in it and is TIRED of the sneering. yes it is',
    'big. yes i love it. read on before you mail me. — the maintainer</small></p>',
    '<hr>',
    '<h2>C with Classes</h2>',
    '<p>Bjarne Stroustrup started it at Bell Labs in 1979 under the name “C with',
    'Classes”. He had used Simula for his doctoral work in Cambridge and loved how',
    'it let you model a problem with classes and objects, and he had used C and',
    'loved how fast and close to the machine it was, and he wanted both at once',
    'without paying for either. That is the founding wish of the whole language:',
    'the abstraction of Simula at the speed of C.</p>',
    '<p>By 1983 it had the name C++, coined by Rick Mascitti, the increment operator',
    'made into a pun. The reference book, <i>The C++ Programming Language</i>, came',
    'in 1985 and that is the year most people date the language proper.</p>',
    '<img class="indie-pic" src="assets/media/web/lang/stroustrup-01.jpg" alt=""><span class="indie-cap">Bjarne Stroustrup (photo: ICPCNews, CC BY)</span>',
    '<h2>Zero-overhead, or it is not C++</h2>',
    '<p>The rule Stroustrup keeps coming back to is the zero-overhead principle:',
    'what you do not use, you do not pay for, and what you do use you could not',
    'reasonably have hand-coded any faster. That is the promise that lets you write',
    'a class, a template, an abstraction, and still get code as tight as the C you',
    'would have written by hand. When it holds it is the finest thing in systems',
    'programming. Nobody pretends it always holds.</p>',
    '<p>Then came the Standard Template Library, Alexander Stepanov’s design, folded',
    'into the standard in the 1990s: containers, iterators and algorithms fitted',
    'together by templates so a sort worked on anything you could iterate. It is',
    'generic programming done properly, and it is also where the error messages',
    'start to read like a ransom note. Both things are true.</p>',
    '<h2>Controversy</h2>',
    '<p>Here is the argument that never stops. C++ is TOO BIG. It is too many',
    'features layered over too many years, several ways to do everything, a spec',
    'the length of a phone book, corners even the committee cannot hold in their',
    'heads. Every serious programmer has a list of the parts they wish were not',
    'there. Stroustrup has heard all of it, for forty years, and his answer is the',
    'line the whole language lives under:</p>',
    '<blockquote class="fs-quote">“There are only two kinds of languages: the ones',
    'people complain about and the ones nobody uses.”</blockquote>',
    '<p>Which is not a dodge. A language people ship real, large, load-bearing',
    'systems in gets pushed into every awkward corner of the world, and it grows',
    'scar tissue and warts because it is being USED. The tidy language with no',
    'complaints is tidy because nobody has stress-tested it against a shipping',
    'deadline. He also likes to say there is a smaller, cleaner language struggling',
    'to get out of C++, but he will not tell you which subset it is, because your',
    'subset and mine are different, and that is the real problem in one sentence.</p>',
    '<img class="indie-pic" src="assets/media/web/lang/bell-labs-01.jpg" alt=""><span class="indie-cap">Bell Labs (photo: Carlo Nardone, CC BY-SA)</span>',
    '<div class="fs-aside">His own preferred defence: C++ is not a language you learn',
    'all of, it is a language you learn a working dialect of and stay inside. The',
    'people who hate it hardest are often the ones who tried to swallow the whole',
    'thing at once. Do not do that.</div>',
    '<h2>Neighbours</h2>',
    '<p>The two parents both have pages. C is next door at',
    '<a href="c-ritchie.geocities.ws">c-ritchie</a>, the speed and the metal that',
    'C++ refused to give up. And Simula, the language that gave Stroustrup classes',
    'and objects in the first place, is over at',
    '<a href="simula-nygaard.geocities.ws">simula-nygaard</a>. Read both and the',
    'whole design suddenly makes sense: he was trying to marry them.</p>',
    '<hr>',
    '<p><small>counter: 05128 · best viewed at 800x600 · compiled with more warnings',
    'than you · greets to everyone still waiting on their build · last updated 2 Nov</small></p>',
    '<p><small>',
    '[ <a href="programming-languages-ring.geocities.ws">Programming Languages Ring</a> ]<br>',
    'ring member and unrepentant. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Pascal: the affectionate page ------------------------------------------

const PASCAL_WIRTH = P('pascal-wirth.geocities.ws', 'PASCAL / WIRTH',
  'NIKLAUS WIRTH // Pascal, and the art of leaving things out', [
    '<!--bg:systems-->',
    '<h1>NIKLAUS WIRTH AND PASCAL</h1>',
    '<p><small>the page for the man who taught half of us to program properly. i',
    'met Pascal on a school machine in the eighties and it fixed my habits for life.',
    'i will not hear a word against him. — a grateful ex-student, now a teacher myself</small></p>',
    '<hr>',
    '<h2>Pascal, 1970</h2>',
    '<p>Niklaus Wirth (1934–2024) built Pascal around 1970 to teach structured',
    'programming, and it did the job so well it became the language a generation',
    'first thought clearly in. Strong typing that catches your mistake before the',
    'machine does. Clean control structures so you never reach for a GOTO. Records',
    'and pointers introduced gently, in the right order. It reads like a language',
    'that was DESIGNED, because it was, by one person with taste, and that is rarer',
    'than it should be.</p>',
    '<p>Here is the shape of it, and notice how little you have to know to read it:</p>',
    '<pre>function fact(n: integer): integer;\nbegin\n  if n = 0 then\n    fact := 1\n  else\n    fact := n * fact(n - 1)\nend;</pre>',
    '<p>No ceremony you do not need, no cleverness for its own sake. A beginner can',
    'read that on the first day and know exactly what it does. That was the point.</p>',
    '<h2>A whole life of subtraction</h2>',
    '<p>Pascal is only the middle of the story. Wirth’s run is the most disciplined',
    'in the whole field: Algol-W first (1966), a tidied Algol; then Pascal (1970);',
    'then Modula-2 (1978) with real modules; then Oberon (1987), a language and an',
    'entire operating system, each design SMALLER than the last. Where everyone',
    'else added, Wirth took away, and kept taking away, until only the parts that',
    'earned their place were left. That is the whole shelf at',
    '<a href="modula-oberon.geocities.ws">modula-oberon</a>.</p>',
    '<img class="indie-pic" src="assets/media/web/lang/wirth-01.jpg" alt=""><span class="indie-cap">Niklaus Wirth (Wikimedia Commons, CC BY-SA)</span>',
    '<div class="fs-aside">The name. He liked to point out that you can call him by',
    'name or call him by value: by name it is “Veert”, by value it is “Worth”. A',
    'compiler-writer’s joke about his own surname, and he told it happily for',
    'decades. He won the Turing Award in 1984, and he had earned it several times',
    'over by then.</div>',
    '<h2>Wirth’s law</h2>',
    '<p>His sharpest line is the one they named after him: software gets slower',
    'faster than hardware gets faster. Every gain the chip people hand us, the',
    'software people spend twice over on bloat, so the machine on your desk feels no',
    'quicker than the one you replaced. He said it plainly in 1995 and it has only',
    'got truer. A man who spent his life making things smaller was entitled to the',
    'observation.</p>',
    '<h2>Neighbours</h2>',
    '<p>Pascal came out of the Algol tradition, and the committee that made Algol 60',
    'has a page at <a href="algol-committee.geocities.ws">algol-committee</a>; Wirth',
    'sat inside that world and then walked his own way out of it. For what he did',
    'next, follow the subtraction to <a href="modula-oberon.geocities.ws">',
    'modula-oberon</a>. And if you want the deepest archive of the language itself,',
    'the Pascal history site kept off the free hosts is the real treasure at',
    '<a href="pascal.hansotten.com">pascal.hansotten.com</a>.</p>',
    '<hr>',
    '<p><small>counter: 02640 · best viewed at 640x480 (the resolution i learned him',
    'at) · under construction: the Modula-2 examples · last updated 9 Sep</small></p>',
    '<p><small>',
    '[ <a href="programming-languages-ring.geocities.ws">Programming Languages Ring</a> ]<br>',
    'a devoted member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- B and BCPL: the ancestors ----------------------------------------------

const UNIX_B_BCPL = P('unix-b-bcpl.geocities.ws', 'B & BCPL',
  'B, BCPL // the typeless roots of C', [
    '<!--bg:systems-->',
    '<h1>B, BCPL AND THE ROOTS OF C</h1>',
    '<p><small>a page for the ancestors nobody remembers, kept by an old hand who',
    'used a machine where a word was just a word and you dealt with it. this is',
    'where C came from, so pay attention. — d.r. (not that one)</small></p>',
    '<hr>',
    '<h2>Before the types</h2>',
    '<p>C did not spring up finished. Behind it stand two languages almost nobody',
    'runs any more, and they explain why C is shaped the way it is. Both were',
    'TYPELESS in the modern sense: there was really one kind of thing, the machine',
    'word, and it was up to you whether a given word was a number, a character or',
    'an address. Fast, close to the hardware, and entirely willing to let you make',
    'a fool of yourself.</p>',
    '<h2>BCPL</h2>',
    '<p>Martin Richards designed BCPL around 1967, at Cambridge and then at MIT. It',
    'was built to be portable and to bootstrap itself onto new machines with very',
    'little effort, which for the era was a real achievement. Everything was the',
    'word. Its curly braces and its way of thinking passed almost intact down the',
    'line, and if you have ever wondered why C looks like C, a good part of the',
    'answer is BCPL.</p>',
    '<img class="indie-pic" src="assets/media/web/lang/bell-labs-01.jpg" alt=""><span class="indie-cap">Bell Labs (photo: Carlo Nardone, CC BY-SA)</span>',
    '<h2>B</h2>',
    '<p>Then Ken Thompson wrote B around 1969 at Bell Labs, a stripped-down BCPL cut',
    'to fit the tiny machine Unix was starting on. Still typeless, still the word as',
    'the only real currency. Dennis Ritchie worked on it too, and when the hardware',
    'grew and B needed a notion of the byte and of different sizes of data, Ritchie',
    'added types and the thing that came out the other side was C. The letter after',
    'B, which is the whole joke in the naming.</p>',
    '<div class="fs-aside">The famous origin trivia: some say C is named for the next',
    'letter after B, others that B itself was short for BCPL. Both stories get told.',
    'Either way the line runs BCPL, then B, then C, each one a little less spare than',
    'the last.</div>',
    '<h2>Neighbours</h2>',
    '<p>The obvious place to go from here is forward, to what B and BCPL turned into:',
    '<a href="c-ritchie.geocities.ws">c-ritchie</a>. And for the wider world these',
    'machines lived in, the first high-level language of all is at',
    '<a href="fortran-backus.geocities.ws">fortran-backus</a>, which was solving the',
    'same problem from the numerical end while Richards and Thompson solved it from',
    'the systems end.</p>',
    '<hr>',
    '<p><small>counter: 00913 · best viewed at 800x600 · this page runs on nostalgia',
    'and a very old server · last updated 22 Aug</small></p>',
    '<p><small>',
    '[ <a href="programming-languages-ring.geocities.ws">Programming Languages Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Ada: the committee and the mandate -------------------------------------

const ADA_LANGUAGE = P('ada-language.geocities.ws', 'ADA',
  'ADA // big, careful, and named for the right person', [
    '<!--bg:systems-->',
    '<h1>ADA</h1>',
    '<p><small>a page for the language that flies aircraft and does not crash, kept',
    'by an engineer who worked on avionics and trusts almost nothing else. people',
    'laugh at Ada until their code has to not kill anyone. — a safety-critical lifer</small></p>',
    '<hr>',
    '<h2>The Department of Defense wanted one language</h2>',
    '<p>By the late 1970s the United States military was drowning in programming',
    'languages, hundreds of them across its systems, and it wanted ONE, designed on',
    'purpose, for embedded and real-time work. It ran a competition. The winning',
    'design, team Green, came from Jean Ichbiah and his group at CII Honeywell Bull',
    'in France, and the language was settled around 1980. It was named Ada, for Ada',
    'Lovelace, who wrote what many count as the first program a century before there',
    'was a machine to run it. For once the name honours the right person.</p>',
    '<img class="indie-pic" src="assets/media/web/lang/mainframe-02.jpg" alt=""><span class="indie-cap">IBM System/360 controls (public domain, John Sauter)</span>',
    '<h2>What it is for</h2>',
    '<p>Ada is big and it is careful, and both are the point. Strong typing pushed',
    'about as far as it will go, so a great many mistakes cannot even be compiled.',
    'Tasking built into the language itself, so concurrency and real-time deadlines',
    'are first-class rather than bolted on. Packages for structuring large systems',
    'that dozens of people work on for decades. This is not a language for a quick',
    'script. It is a language for the flight-control computer, the railway signal,',
    'the thing that must not fail.</p>',
    '<div class="fs-aside">The military standard that defined it carried the number',
    'MIL-STD-1815, and the 1815 is not an accident: it is the year Ada Lovelace was',
    'born. Someone on that committee had a sense of history.</div>',
    '<h2>Mandated, and resented for it</h2>',
    '<p>For a while the Department of Defense actually required Ada for its projects,',
    'and nothing makes programmers love a language less than being ordered to use',
    'it. It got a reputation as heavy and bureaucratic, the committee language you',
    'were forced into. The mandate is long gone now, but Ada quietly stayed exactly',
    'where it always earned its keep: aerospace, rail, defence, the places where a',
    'compiler that nags you today beats a bug that surfaces at ten thousand feet.</p>',
    '<h2>Neighbours</h2>',
    '<p>For the discipline of strong typing done at teaching scale rather than',
    'military scale, see <a href="pascal-wirth.geocities.ws">pascal-wirth</a>; Ada',
    'and Pascal share the same conviction that the compiler should catch you early.',
    'And the block-structured tradition both descend from is at',
    '<a href="algol-committee.geocities.ws">algol-committee</a>, the grandparent of',
    'the careful languages.</p>',
    '<hr>',
    '<p><small>counter: 01185 · best viewed at 800x600 · this page validated more',
    'carefully than your firmware · last updated 30 Sep</small></p>',
    '<p><small>',
    '[ <a href="programming-languages-ring.geocities.ws">Programming Languages Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Modula-2 and Oberon: the subtraction continues -------------------------

const MODULA_OBERON = P('modula-oberon.geocities.ws', 'MODULA & OBERON',
  'MODULA-2 & OBERON // Wirth keeps taking things away', [
    '<!--bg:systems-->',
    '<h1>MODULA-2 AND OBERON</h1>',
    '<p><small>a page for what Wirth did after Pascal, kept by someone who ran an',
    'actual Oberon system on an actual workstation and misses it. cleaner than',
    'anything you are using now, i promise you. — an ETH admirer</small></p>',
    '<hr>',
    '<h2>Modula-2: the module arrives</h2>',
    '<p>After Pascal, Niklaus Wirth wanted a way to build big programs out of parts',
    'that could be compiled and reasoned about separately, and around 1978 he',
    'produced Modula-2. The headline feature is right there in the name: the MODULE,',
    'a unit with a clean interface and a hidden implementation, so you could split a',
    'system into pieces that only knew about each other through what they promised,',
    'not how they worked. That idea is everywhere now. Modula-2 made it plain.</p>',
    '<p>It ran on the Lilith, a workstation Wirth’s group designed and built at ETH',
    'Zürich around 1980, hardware and software from the same hands, the whole thing',
    'written in Modula-2 down to the bare metal. Very few people have ever designed',
    'both the machine and the language it speaks. Wirth did it more than once.</p>',
    '<img class="indie-pic" src="assets/media/web/lang/terminal-01.jpg" alt=""><span class="indie-cap">a DEC VT100 (photo: Jason Scott, CC BY)</span>',
    '<h2>Oberon: smaller still</h2>',
    '<p>Then he did the thing that tells you everything about him. With Jürg',
    'Gutknecht he built Oberon (1987), and it is SMALLER than Modula-2, not larger.',
    'A language pared back to almost nothing, and on top of it a complete operating',
    'system, also called Oberon, also tiny, that a couple of people could hold',
    'entirely in their heads. No bloat, no dead features, no cleverness left in that',
    'did not pay rent. Here is a whole module, and that is genuinely most of what',
    'you need to know to read the language:</p>',
    '<pre>MODULE Hello;\n  IMPORT Out;\nBEGIN\n  Out.String("Hello"); Out.Ln\nEND Hello.</pre>',
    '<p>Where the rest of the industry answered every problem by adding, Wirth kept',
    'answering by removing, and the astonishing part is that the removed version',
    'usually did the job. Read his law about software bloat over at',
    '<a href="pascal-wirth.geocities.ws">pascal-wirth</a> and you will see Oberon is',
    'that law turned into an operating system.</p>',
    '<div class="fs-aside">There is a real principle underneath it, sometimes called',
    'Wirth’s: a designer knows a thing is finished not when there is nothing left to',
    'add, but when there is nothing left to take away. Oberon is what that looks like',
    'when someone actually means it.</div>',
    '<h2>Neighbours</h2>',
    '<p>The obvious neighbour is the man himself and the language that started the',
    'run, at <a href="pascal-wirth.geocities.ws">pascal-wirth</a>. And for the',
    'systems-language world Oberon quietly argued with, the one that won by being',
    'everywhere, see <a href="c-ritchie.geocities.ws">c-ritchie</a>; put Oberon and',
    'C side by side and you are looking at two completely different answers to the',
    'same question about how close to the metal a language should sit.</p>',
    '<hr>',
    '<p><small>counter: 00727 · best viewed at 800x600 · powered by a Lilith in my',
    'memory and a beige box in the loft · under construction: the Oberon screenshots',
    '· last updated 5 Oct</small></p>',
    '<p><small>',
    '[ <a href="programming-languages-ring.geocities.ws">Programming Languages Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const LANG_B = [C_RITCHIE, CPP_STROUSTRUP, PASCAL_WIRTH, UNIX_B_BCPL, ADA_LANGUAGE, MODULA_OBERON];
