// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — punk & post-punk. Fan pages kept on a free host, each ABOUT a
// SCENE and never a single band: the year-zero of 1976, the art-school turn
// that followed, the American hardcore circuit, the riot grrrl movement given
// its full weight, the industrial workshop and the brief total burn of no
// wave. Scenes, places, years and labels are real; the crate-digger opinions
// and the fanzine grudges belong to the fans who typed them.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- punk: the showpiece scene primer ---------------------------------------

const PUNK = P('punk.geocities.ws', 'PUNK 76',
  'YEAR ZERO // a punk primer, 1976-77', [
    '<!--bg:music-punk-->',
    '<h1>YEAR ZERO</h1>',
    '<p><small>a primer on punk, the scene not the fashion, kept by someone who',
    'was too young for it and has been making up for that ever since. tape',
    'traders welcome, corrections welcomer. — Col</small></p>',
    '<p class="fs-epi"><i>“This is a chord. This is another. This is a third. Now',
    'form a band.”</i><br>— the caption to a diagram in a fanzine, 1977</p>',
    '<hr>',
    '<p>Two cities, one year, and a door kicked open. Punk did not fall out of the',
    'sky in 1976, it had been gathering since the garage bands of the 1960s and',
    'the loud short songs of the Stooges and the MC5 in Detroit and the New York',
    'Dolls after them. But 1976 to 1977 is when it took a name and a scene and a',
    'set of rules, most of which were about having no rules. The music was fast,',
    'the songs were short, the recording was cheap and rough on purpose, and the',
    'whole point was that you did not need permission, a conservatoire or a fortune',
    'in gear. You needed three chords and the nerve to stand up.</p>',
    '<h2>New York: CBGB and the Bowery</h2>',
    '<p>The American end grew in a narrow bar on the Bowery called CBGB, which stood',
    'for Country, Bluegrass and Blues and never booked much of any of them. From',
    '1974 on it gave a stage to the Ramones, whose songs barely cleared two minutes',
    'and who counted themselves in and did not stop; to Television, arty and',
    'guitar-clever, with Tom Verlaine winding long lines out of a cheap sound; to',
    'Blondie, who carried a pop instinct through the noise; to Patti Smith, who',
    'brought poetry to it; and to the Talking Heads, nervy and clever and new. It',
    'was a smaller, artier, more literary thing than the London version, and it',
    'came first.</p>',
    '<p class="fs-pull">Three chords and the nerve to stand up. That was the whole',
    'entry fee, and it was meant to be.</p>',
    '<h2>London: the 100 Club and the Roxy</h2>',
    '<img class="indie-pic" src="assets/media/web/music-scenes/cbgb-01.jpg" alt=""><span class="indie-cap">The CBGB awning, New York (photo: Alkivar, CC BY-SA 2.5)</span>',
    '<p>The London end was angrier and more political and better at headlines. The',
    'Sex Pistols, managed and provoked by Malcolm McLaren out of his and Vivienne',
    'Westwood’s shop on the King’s Road, made themselves a national scandal',
    'and a genuinely fierce band underneath the scandal. The Clash carried the',
    'politics and the reach, opening the music out toward reggae and beyond. The',
    'Damned got there first on record and played faster than anyone. The 100 Club',
    'on Oxford Street held the punk festival of September 1976 that gathered the',
    'scene in one room, and the Roxy in Covent Garden ran for a hundred nights as',
    'its early home. Buzzcocks up in Manchester pressed <i>Spiral Scratch</i> in',
    '1977 on their own New Hormones label and showed the rest of the country you',
    'could just do it yourself.</p>',
    '<p class="fs-quote"><i>“Punk rock was about change, about creating new',
    'possibilities.”</i> People said versions of this at the time and meant the',
    'access more than the anger: the stage stopped being a place you had to be',
    'anointed to reach.</p>',
    '<h2>The fanzine</h2>',
    '<p>The scene wrote itself up as it happened. Mark Perry started <i>Sniffin’',
    'Glue</i> in London in 1976, photocopied, hand-lettered, misspelled and',
    'furious, and it became the model for a thousand zines after it. The fanzine',
    'was punk’s own theory of itself: cheap, fast, made by a fan with no',
    'training, passed hand to hand. The do-it-yourself press and the do-it-yourself',
    'record were the same idea in two media.</p>',
    '<div class="fs-aside"><b>did you know</b><br>The name argued with itself from',
    'the start. In New York it pointed back to a 1970s rock-writer’s word for',
    'garage bands; in London it read as an insult reclaimed, the word for a nobody,',
    'worn on purpose. Same four letters, two different chips on two different',
    'shoulders.</div>',
    '<p>Here is a rough gig-and-record diary of the year it turned, and the',
    'family-tree of what you actually had to learn to join in.</p>',
    '<pre>',
    'YEAR ZERO — a short diary, 1976-77',
    '  Jul 1976  Ramones tour Britain, light a fuse under London',
    '  Sep 1976  the 100 Club Punk Festival, Oxford Street',
    '  Nov 1976  Sex Pistols, "Anarchy in the U.K." (single)',
    '  Dec 1976  the televised swearing; the tabloids do the promotion',
    '  Jan 1977  Buzzcocks, "Spiral Scratch" EP (New Hormones, own label)',
    '  Feb 1977  the Damned, "Damned Damned Damned" (first UK punk LP)',
    '  Apr 1977  the Clash, "The Clash" (debut LP)',
    '  Oct 1977  Sex Pistols, "Never Mind the Bollocks" (LP)',
    '',
    'LEARN THREE CHORDS (the whole syllabus)',
    '  E  --  A  --  B        <- turn it up, count it in, do not stop',
    '   |      |      |',
    '  form a band -> press a single -> photocopy a zine -> next town</pre>',
    '<img class="indie-pic" src="assets/media/web/music-scenes/electric-guitar-01.jpg" alt=""><span class="indie-cap">A 1980s electric guitar (photo: Elmschrat, CC BY-SA 4.0)</span>',
    '<p>Where it went next is two doors. The art-school wing slowed down, spread',
    'out and turned strange, which became post-punk, and you can read that at',
    '<a href="post-punk.geocities.ws">post-punk</a>. The other wing sped up, got',
    'shorter and harder and crossed the Atlantic into the American underground,',
    'which became <a href="hardcore.geocities.ws">hardcore</a>. Off the roster but',
    'owed a mention: Iggy and the Stooges, the New York Dolls and the Velvet',
    'Underground before them, without whom none of this stands up.</p>',
    '<hr>',
    '<p><small>hit counter: 03177 · best viewed in Netscape at 800x600 · this page',
    'is under construction and always will be · now playing: something loud and',
    'two minutes long · last updated 14 Aug</small></p>',
    '<p><small>[ <a href="music-scenes-ring.geocities.ws">Music Scenes Ring</a> ]</small></p>',
  ]);

// ---- post-punk: scene primer ------------------------------------------------

const POSTPUNK = P('post-punk.geocities.ws', 'POST-PUNK',
  'AFTER THE YEAR ZERO // post-punk 1978-82', [
    '<!--bg:music-punk-->',
    '<h1>AFTER THE YEAR ZERO</h1>',
    '<p><small>notes on post-punk, roughly 1978 to 1982, by someone who thinks the',
    'interesting part started when the shouting stopped. — R.</small></p>',
    '<p class="fs-epi"><i>“He used to work in a factory, now he plays guitar in a',
    'band.”</i> The scene was full of people who had jumped exactly that gap and',
    'wanted the music to sound like the jump.</p>',
    '<hr>',
    '<p>Punk cleared the ground and said anyone can do this. Post-punk took the',
    'permission and asked a harder question: now that anyone can, what should we',
    'make? The answer was not faster and louder, it was stranger. The three chords',
    'opened out into angles and space and rhythm. Art-school ideas came back in,',
    'this time without apology. The records got dubby, funky, cold, clever and odd,',
    'and the four-year window from about 1978 to 1982 holds more genuinely new',
    'sounds than almost any stretch before or since.</p>',
    '<p>Manchester had Joy Division, whose bass carried the tune while the guitar',
    'scraped the edges, all of it built in the studio by the producer Martin',
    'Hannett into something that sounded like the empty city at night. Their two',
    'albums came out on Factory, and after the death of Ian Curtis in 1980 the',
    'surviving members became New Order and walked the scene toward the dancefloor.',
    'London had Wire, who wrote songs that stopped the instant they had said their',
    'piece, and Public Image Ltd, John Lydon’s band after the Sex Pistols,',
    'built on Jah Wobble’s dub bass and Keith Levene’s glassy guitar.</p>',
    '',
    '<p>Leeds had Gang of Four, who put a hard funk rhythm section under lyrics',
    'about how ordinary life gets bought and sold, the danceable and the political',
    'locked together on purpose. Manchester also kept the Fall, Mark E. Smith’s',
    'long war of a band, repetitive and contrary and unlike anyone. Around them the',
    'Raincoats, the Slits and Siouxsie and the Banshees pulled the sound further',
    'out again. What tied it together was less a style than a stance: use the',
    'studio, borrow from dub and funk and the avant-garde, refuse the easy return',
    'to rock and roll.</p>',
    '<p class="fs-pull">Punk asked who is allowed to play. Post-punk asked what is',
    'left to play once everyone is allowed.</p>',
    '<p>The labels mattered as much as the bands. Factory in Manchester, run by',
    'Tony Wilson with Peter Saville’s austere sleeves, and Rough Trade in',
    'London, shop and label and the distribution network under half the scene, gave',
    'the records a way to reach people without a major. From here two doors again.',
    'One wing pushed the coldness and the tape machine all the way into the',
    'workshop of <a href="industrial.geocities.ws">industrial</a>. And the whole',
    'thing owes its ground zero to <a href="punk.geocities.ws">punk</a>, the year',
    'that made the space. Off the roster but next in the family: the synth-pop that',
    'grew straight out of this, from the Human League to Depeche Mode.</p>',
    '<hr>',
    '<p><small>counter: 01642 · best viewed at 800x600 · under construction ·',
    'tape traders welcome · last updated 30 Jul</small></p>',
    '<p><small>[ <a href="music-scenes-ring.geocities.ws">Music Scenes Ring</a> ]</small></p>',
  ]);

// ---- hardcore: ORG/scene page -----------------------------------------------

const HARDCORE = P('hardcore.geocities.ws', 'HARDCORE',
  'FASTER AND SHORTER // American hardcore, from 1980', [
    '<!--bg:music-punk-->',
    '<h1>FASTER AND SHORTER</h1>',
    '<p><small>a scene page for American hardcore, from about 1980 on. built and',
    'maintained by the van, for the van. list your local matinee show below, i',
    'check the guestbook. — deej</small></p>',
    '<hr>',
    '<p>When punk crossed to the American suburbs it did not slow down, it sped up.',
    'Hardcore is what happened when kids too young and too far from any scene took',
    'the fastest, shortest, angriest end of punk and stripped even that back.',
    'Songs dropped under a minute. Tempos doubled. The singing became shouting.',
    'And because there was no industry anywhere near it, the scene built its own',
    'everything: its own labels, its own venues in rented halls and church',
    'basements, its own touring circuit stitched together by phone numbers passed',
    'hand to hand.</p>',
    '<p>Los Angeles and its suburbs gave it Black Flag, whose relentless touring in',
    'a battered van more or less invented the American underground road map, and',
    'the Dead Kennedys up in San Francisco, sharp and satirical under Jello',
    'Biafra. Washington DC gave it Bad Brains, an all-Black band of astonishing',
    'speed and precision who could turn on a coin into reggae, and Minor Threat,',
    'Ian MacKaye’s band, short-lived and enormous in influence. New York, Boston',
    'and Minneapolis each grew a scene of their own, and the whole thing ran on the',
    'seven-inch single and the photocopied flyer.</p>',
    '<div class="fs-aside"><b>did you know</b><br>The words STRAIGHT EDGE come from',
    'a Minor Threat song. Ian MacKaye meant it as a personal note, no drink, no',
    'drugs, a clear head in a scene that was wrecking itself. Some fans hardened it',
    'into a movement and a lifestyle he never quite asked for, which is what tends',
    'to happen to a good line.</div>',
    '',
    '<p>The label that carried the West Coast was SST, run by Black Flag’s Greg',
    'Ginn, and Dischord in DC, run by MacKaye and Jeff Nelson, which put out the',
    'city’s whole scene on principle and kept the prices low on principle too.',
    'The ethic was the point as much as the music: do it yourself, keep it cheap,',
    'answer your own mail, sleep on floors, and never wait for a company to say',
    'yes. Hardcore came straight out of <a href="punk.geocities.ws">punk</a> and',
    'took the DIY promise literally. And the same underground network, the same',
    'floors and zines and seven-inches, carried the feminist movement that',
    'answered it a decade on at <a href="riot-grrrl.geocities.ws">riot-grrrl</a>.',
    'Off the roster: Hüsker Dü and the Minutemen, who came up through this and then',
    'burst its bounds.</p>',
    '<hr>',
    '<p><small>counter: 00913 · best viewed at 800x600 · this site is under',
    'construction, like the scene · all ages / all welcome · last updated 22 Jun',
    '</small></p>',
    '<p><small>[ <a href="music-scenes-ring.geocities.ws">Music Scenes Ring</a> ]</small></p>',
  ]);

// ---- riot-grrrl: ORG/scene page (foregrounded, full seriousness) ------------

const RIOTGRRRL = P('riot-grrrl.geocities.ws', 'RIOT GRRRL',
  'GIRLS TO THE FRONT // riot grrrl, Olympia & DC', [
    '<!--bg:music-punk-->',
    '<h1>GIRLS TO THE FRONT</h1>',
    '<p><small>a page for the riot grrrl movement, Olympia and Washington DC,',
    'early 1990s. put up by someone it reached late and changed anyway. this is a',
    'movement, not a genre, and i have tried to write it as one. — Steph</small></p>',
    '<p class="fs-epi"><i>“Girls to the front.”</i><br>— the call from the stage,',
    'clearing a space at the front of the room for the women in the crowd</p>',
    '<hr>',
    '<p>Riot grrrl began where two small scenes met: Olympia, Washington, a college',
    'town with the Evergreen State College, the K Records label and the',
    'International Pop Underground, and Washington DC, with its long hardcore',
    'history and its own restless conscience. At the start of the 1990s a group of',
    'women there looked at the punk underground they loved and named what was',
    'wrong with it. The shows were a wall of men at the front. The scene talked',
    'about liberation and left the women holding the coats. So they made a movement',
    'to change it from inside, and they refused to treat that as a side issue to',
    'the music.</p>',
    '<p>Bikini Kill were the band at the centre of it, Kathleen Hanna singing,',
    'Tobi Vail on drums, Kathi Wilcox on bass and Billy Karren on guitar. Their',
    'shows were confrontations and invitations at once: Hanna would call the women',
    'to the front of the room, hand the microphone to anyone with something to say',
    'about being hurt, and turn the gig into a meeting. Bratmobile, Molly Neuman',
    'and Allison Wolfe and Erin Smith, were the other founding band, and Heavens to',
    'Betsy brought Corin Tucker, later of Sleater-Kinney. Around them Huggy Bear in',
    'Britain carried the movement across the Atlantic.</p>',
    '<p class="fs-pull">This was never only a sound. It was a way of running a room,',
    'a press and a politics, with the band as one part of it.</p>',
    '',
    '<p>The zine was as important as the record. The movement even took its name',
    'from one: <i>Riot Grrrl</i>, the fanzine Hanna and Vail and others made, and',
    'the tripled r was the point, a growl put into the word "girl" to take it back.',
    'The zines were cut-and-paste, handwritten, passed at shows and posted between',
    'towns, and they carried the arguments, the reading lists, the confessions and',
    'the manifestos. Hanna’s <i>Riot Grrrl Manifesto</i>, printed in the',
    '<i>Bikini Kill</i> zine in 1991, set it out in a hammering list of "because"',
    'lines: because a girl in a band is still treated as a novelty, because the',
    'mainstream press will not tell our stories, because we are angry at a society',
    'that tells us Girl = Dumb, Girl = Bad, Girl = Weak. It read as a call to build',
    'the culture yourself rather than beg for a place in the one that shut you out.</p>',
    '<p>The movement paid for its visibility. When the mainstream press discovered',
    'it around 1992 and 1993 the coverage was mocking or prurient, so the network',
    'called a media blackout and spoke through its own zines instead, which is one',
    'of the more clear-eyed things any scene has done about the press. Riot grrrl',
    'did not last long as an organised thing, but its insistence that the',
    'underground answer for its own sexism, and its faith in the zine and the',
    'meeting and the self-run label, ran straight on into feminist music and',
    'organising after it.</p>',
    '<p>It grew directly out of the DIY underground of',
    '<a href="hardcore.geocities.ws">hardcore</a>, whose floors and seven-inches',
    'and touring circuit it used and turned to its own ends. And it shares an',
    'ancestor with the art-refusal of <a href="no-wave.geocities.ws">no-wave</a>,',
    'where women like Lydia Lunch had already put a woman’s fury at the front of',
    'the noise. Off the roster but owed the name: the Olympia label K Records and',
    'the queercore scene alongside which riot grrrl grew.</p>',
    '<hr>',
    '<p><small>counter: 02551 · best viewed at 800x600 · this page is under',
    'construction and run by a girl · zines traded gladly, write to me · last',
    'updated 3 Aug</small></p>',
    '<p><small>[ <a href="music-scenes-ring.geocities.ws">Music Scenes Ring</a> ]</small></p>',
  ]);

// ---- industrial: close-listening page ---------------------------------------

const INDUSTRIAL = P('industrial.geocities.ws', 'INDUSTRIAL',
  'MUSIC FROM THE WORKSHOP // industrial, a close listen', [
    '<!--bg:music-punk-->',
    '<h1>MUSIC FROM THE WORKSHOP</h1>',
    '<p><small>a close-listening page for the first wave of industrial music. put',
    'up by someone who thinks you have to sit with these records, not just survive',
    'them. headphones, lights low, no skipping. — V.</small></p>',
    '<p class="fs-epi"><i>“industrial music for industrial people”</i><br>— the',
    'slogan Industrial Records printed on itself, half a joke and wholly a',
    'programme</p>',
    '<hr>',
    '<p>Industrial did not start as a genre, it started as a label and a slogan.',
    'Throbbing Gristle, who came out of the performance-art group COUM',
    'Transmissions, founded Industrial Records in London in 1976, and their name',
    'for what they made is the name we still use. The idea was to treat sound the',
    'way an artist treats any material: tape loops, found noise, cheap electronics,',
    'the hum and clang of the machine age turned into music, made to unsettle',
    'rather than to please. Genesis P-Orridge, Cosey Fanni Tutti, Peter',
    'Christopherson and Chris Carter built it in a studio they called the Death',
    'Factory, and the point was to confront, to document the bleak and the taboo,',
    'and to refuse the comforts of the pop song.</p>',
    '<p>Listen to a Throbbing Gristle track and notice what is not there: no verse',
    'and chorus, no warm production, no invitation to sing along. What is there is',
    'texture and repetition and dread, a rhythm that feels mechanical rather than',
    'human, a voice used as another source of noise. In Sheffield, Cabaret Voltaire',
    'took a warmer, funkier route to the same territory, splicing tape cut-ups and',
    'dance rhythm and dub space, more groove and less assault but the same faith in',
    'the tape machine as an instrument. Their name they lifted from the Dada',
    'nightclub in Zurich, which tells you where their heads were.</p>',
    '<div class="fs-aside"><b>a listening note</b><br>The transgression can date',
    'faster than the sound. Strip the shock away and the records still hold up as',
    'sound design, as a way of making rhythm and texture out of noise. Start there',
    'and the difficulty stops being a wall.</div>',
    '',
    '<p>Around the core were SPK from Australia and Clock DVA and, harsher still,',
    'the Whitehouse end that pushed volume and provocation to the limit. What they',
    'shared was method more than sound: the studio as a place to build music out of',
    'the noise of industry itself, and a stance that took its cues from the',
    'avant-garde, from Dada and William Burroughs and the tape cut-up, as much as',
    'from rock. It carried the coldness and the tape experiments of',
    '<a href="post-punk.geocities.ws">post-punk</a> all the way into the workshop.',
    'And it shares a founding nerve with <a href="no-wave.geocities.ws">no-wave</a>,',
    'the same refusal of the well-made song at the same moment. Off the roster but',
    'downstream: everything the word "industrial" came to mean in the 1980s and',
    'after, from Einstürzende Neubauten to the dancefloor versions.</p>',
    '<hr>',
    '<p><small>counter: 00688 · best viewed at 800x600 · under construction ·',
    'now playing: a tape loop, forever · last updated 9 Jul</small></p>',
    '<p><small>[ <a href="music-scenes-ring.geocities.ws">Music Scenes Ring</a> ]</small></p>',
  ]);

// ---- no-wave: ORG/scene page ------------------------------------------------

const NOWAVE = P('no-wave.geocities.ws', 'NO WAVE',
  'NO NEW YORK // no wave, 1978', [
    '<!--bg:music-punk-->',
    '<h1>NO NEW YORK</h1>',
    '<p><small>a page for no wave, downtown New York, around 1978. the scene that',
    'was over almost before it was named. kept by a completist who will trade you',
    'a dub of the compilation. — A.</small></p>',
    '<hr>',
    '<p>No wave was a refusal with a pun for a name. Punk had become "new wave" as',
    'the industry tidied it up for radio, so a handful of downtown New York bands',
    'called what they did "no wave", no to the new wave, no to the returning song,',
    'no to the whole idea of getting good and getting signed. It ran for a few',
    'years around 1978 in the lofts and clubs of Lower Manhattan, and it was as',
    'much a part of the downtown art world, the film-makers and the performance',
    'artists, as of music.</p>',
    '<p>The document that fixed it is a compilation. In 1978 Brian Eno recorded',
    'four of the bands and released them as <i>No New York</i>, and that record is',
    'the scene in a sleeve: the Contortions, James Chance’s band, welding a',
    'skronking free-jazz saxophone to a broken funk; Teenage Jesus and the Jerks,',
    'Lydia Lunch’s band, slow and scraping and brutal; Mars and DNA, both of',
    'them taking the guitar somewhere atonal and jagged and short. DNA had Arto',
    'Lindsay playing a guitar he had never learned to play in the ordinary sense,',
    'which was exactly the point.</p>',
    '<p class="fs-pull">No to the new wave, no to the well-made song, no to getting',
    'good and getting signed. A scene named for what it would not do.</p>',
    '',
    '<p>The music was atonal, abrasive, rhythmically stiff and deliberately',
    'unschooled, and it did not want to be liked. Where punk still kept the shape',
    'of a rock song, no wave threw the shape out. It burned fast and left few',
    'records, which is part of why it stayed a legend, but its nerve ran on into a',
    'lot of what came after, from Sonic Youth’s early noise to the whole idea',
    'that not knowing how to play could be a starting point rather than a lack. It',
    'shares that founding refusal with <a href="industrial.geocities.ws">',
    'industrial</a>, the same year’s war on the well-made song from a different',
    'city. And Lydia Lunch’s fury at the front of it is one of the ancestors of',
    'the movement at <a href="riot-grrrl.geocities.ws">riot-grrrl</a>. Off the',
    'roster: the downtown loft scene around Glenn Branca and the young Sonic Youth',
    'who picked it all up.</p>',
    '<hr>',
    '<p><small>counter: 00479 · best viewed in Netscape at 800x600 · perpetually',
    'under construction · a webring for diggers, join it · last updated 18 May',
    '</small></p>',
    '<p><small>[ <a href="music-scenes-ring.geocities.ws">Music Scenes Ring</a> ]</small></p>',
  ]);

export const MSCN_C = [PUNK, POSTPUNK, HARDCORE, RIOTGRRRL, INDUSTRIAL, NOWAVE];
