// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH D — hashing & integrity.
//
// The corner of the crypto web that worries not about secrecy but about
// whether a thing arrived unchanged. A how-it-works showpiece on the one-way
// hash; a worked page on the humble checksum; a history of the attacks on MD5
// and SHA; a close reading of the keyed hash; a close reading of the collision
// and the birthday attack; and a worked page on the fingerprint you read down
// the telephone. Every example digest is invented and harmless.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- the hash function: the showpiece ---------------------------------------

const HASH_FUNCTION = P('the-hash-function.geocities.ws', 'HASH FUNCTION',
  'THE HASH FUNCTION // one way in, no way back', [
    '<!--bg:cryp-integrity-->',
    '<h1>THE HASH FUNCTION</h1>',
    '<p><small>how it works, written up for the newcomers who keep asking on the',
    'group. if you have read Schneier you know all this already, go and read',
    'something harder. everyone else, sit down. — merkle_fan (not that Merkle,',
    'i wish)</small></p>',
    '<div class="fs-epi"><p>&ldquo;A good hash is a meat grinder. Sausage from a',
    'pig is easy. A pig from sausage is the trick.&rdquo; &mdash; a line off',
    'sci.crypt, author long since forgotten</p></div>',
    '<hr>',
    '<p>A hash function takes an input of ANY length, a byte or a gigabyte, and',
    'returns a short string of fixed length called the digest, or the hash, or',
    'the message digest. Feed it the whole of <i>War and Peace</i> and you get',
    '128 bits back. Feed it the single letter A and you get 128 bits back. The',
    'output is always the same size, and for a given input it is always the same',
    'value. That is the whole of the interface. Everything interesting is in what',
    'the function refuses to let you do.</p>',
    '<p><b>THREE PROPERTIES, and learn the names, because people muddle them.</b></p>',
    '<p>PRE-IMAGE RESISTANCE. Given a digest, you cannot find an input that hashes',
    'to it. The function runs one way only. Forward is a moment; backward is a',
    'search through every possible message, which for a decent hash is a search',
    'you do not finish before the sun goes out.</p>',
    '<p>SECOND PRE-IMAGE RESISTANCE. Given one message, you cannot find a',
    'DIFFERENT message with the same digest. Handed the contract, you cannot forge',
    'a second contract that hashes identically and swap it in.</p>',
    '<p>COLLISION RESISTANCE. You cannot find ANY two messages that share a',
    'digest, even if you get to pick both. This is the hardest to promise and the',
    'first to fall, and it has a page of its own at',
    '<a href="the-collision.geocities.ws">the-collision</a>.</p>',
    '<div class="fs-aside"><p><b>DID YOU KNOW.</b> The three properties are not',
    'the same strength. Collision resistance is the demanding one, because the',
    'birthday attack lets an opponent choose both sides at once. A hash can hold',
    'the first two and lose the third, and plenty have.</p></div>',
    '<img class="indie-pic" src="assets/media/web/cryp/shannon-01.jpg" alt=""><span class="indie-cap">Claude Shannon, who founded information theory (public domain)</span>',
    '<p><b>THE AVALANCHE EFFECT.</b> Change one bit of the input and roughly half',
    'the bits of the output flip. There is no smooth relation between input and',
    'output, no neighbourhood you can climb. A comma added to a letter gives a',
    'digest with no visible relation to the first. That is the property that',
    'makes the hash useful as a detector: any change, however small, shows.</p>',
    '<pre>',
    'PROPERTIES OF A GOOD CRYPTOGRAPHIC HASH',
    '  fixed output size    any input -> n bits, always n bits',
    '  deterministic        same input -> same digest, every time',
    '  fast to compute      forward is cheap',
    '  pre-image resistant  digest -> input is infeasible',
    '  2nd pre-image res.   given m, another m\' with H(m)=H(m\') is infeasible',
    '  collision resistant  ANY m, m\' with H(m)=H(m\') is infeasible',
    '  avalanche            flip one input bit, ~half the output bits flip',
    '</pre>',
    '<p>An invented digest, so you can see the shape of the thing (this is not the',
    'hash of anything real, it is here to look at):</p>',
    '<pre>',
    '  message : "the quick brown fox"',
    '  digest  : 7f3a c19e 44d0 8b62 e1a7 90fc 2d55 6b0e',
    '',
    '  message : "the quick brown fix"      (one letter changed)',
    '  digest  : b204 6e8d f1a3 0c97 55ba 27e4 90d1 3f8c',
    '</pre>',
    '<div class="fs-pull"><p>A hash proves a file is unchanged. It does not keep a',
    'secret, and on its own it does not prove WHO sent the file.</p></div>',
    '<p><b>WHAT A HASH IS FOR.</b> Integrity. You publish the digest of a file',
    'through one channel and the file through another, and a reader who computes',
    'the digest and matches it knows the file arrived whole. It is the fingerprint',
    'of a file, a short unforgeable stand-in you can compare when comparing the',
    'whole thing is awkward. Passwords are stored as hashes so the store can check',
    'you without holding the secret. Signatures sign the hash, not the document,',
    'because the hash is short and the document is long.</p>',
    '',
    '<p><b>WHAT A HASH IS NOT FOR.</b> It is not encryption; there is no key and',
    'nothing comes back out. It is not a secret; anyone can compute it. And a',
    'plain hash by itself does not authenticate, because anyone who can change the',
    'file can recompute the digest to match. To bind a hash to a sender you need a',
    'key, and that is the keyed hash at',
    '<a href="md5-and-sha.geocities.ws">md5-and-sha</a> and the MAC one ring over.',
    'The named hashes of the decade, MD5 and the SHA family, live at',
    '<a href="md5-and-sha.geocities.ws">md5-and-sha</a>.</p>',
    '<hr>',
    '<p><small>counter: 03106 · best viewed in Netscape at 800x600 · under',
    'construction, the diagrams are coming · PGP key fingerprint',
    '4A1F 88C0 D3E2 7B65 90AA 12FD 6C34 E0B9 (invented, do not trust) · last',
    'updated 14 Aug</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the checksum: a worked example page ------------------------------------

const CHECKSUM = P('the-checksum.geocities.ws', 'CHECKSUM',
  'THE CHECKSUM // catches the slip, not the lie', [
    '<!--bg:cryp-integrity-->',
    '<h1>THE CHECKSUM</h1>',
    '<p><small>a worked page, because people keep calling a checksum a hash and',
    'they are cousins, not twins. worked examples below, do them with a pencil.',
    '— the parity kid</small></p>',
    '<hr>',
    '<p>A checksum is a small value computed from data so that a later reader can',
    'tell whether the data changed by accident. It is built to catch the slip: the',
    'flipped bit on a noisy line, the digit fat-fingered into a form, the block',
    'that came off the tape wrong. It is fast, it is cheap, and it is NOT',
    'cryptographic. Hold that last part; it is the whole reason for this page.</p>',
    '<p><b>THE PARITY BIT.</b> The smallest checksum there is. Count the 1-bits in',
    'a byte and add one more bit to make the total even (even parity). If a single',
    'bit flips in transit the count goes odd and the receiver knows something',
    'broke. Worked example, even parity:</p>',
    '<pre>',
    '  data 1011001  -> four 1-bits, already even -> parity 0 -> send 10110010',
    '  data 1110001  -> four 1-bits, already even -> parity 0 -> send 11100010',
    '  data 1010001  -> three 1-bits, make even   -> parity 1 -> send 10100011',
    '</pre>',
    '<p>One flipped bit and the parity fails. But flip TWO bits and the count is',
    'even again and the error sails through. Parity catches an odd number of',
    'errors and misses an even number. It is honest work and it is very cheap.</p>',
    '<div class="fs-aside"><p><b>THE CRC.</b> The cyclic redundancy check treats',
    'your data as one enormous binary number and divides it by a fixed polynomial;',
    'the remainder is the check value. It is the workhorse behind Ethernet frames,',
    'ZIP archives and disk sectors, and it catches burst errors that parity would',
    'wave through. Clever, standard, everywhere. Still not cryptographic.</p></div>',
    '',
    '<p><b>THE LUHN CHECK.</b> The formula on the end of a payment card number,',
    'from Hans Peter Luhn at IBM. The last digit is a check digit chosen so the',
    'following sum comes out to a multiple of ten. Walking from the right, double',
    'every second digit; if a doubled value passes nine, subtract nine; add the',
    'lot up. A made-up number that passes, so you can trace the steps:</p>',
    '<pre>',
    '  card    4 9 2 7  6 1 8 3  0 0 4 2  1 2 3 7   (invented, not a real card)',
    '  double  8 9 4 7 12 1 16 3 0 0 8 2 2 2 6 7   (every 2nd from the right)',
    '  cast 9  8 9 4 7  3 1  7 3 0 0 8 2 2 2 6 7   (12->3, 16->7)',
    '  sum     = 70   -> ends in 0 -> passes the Luhn test',
    '</pre>',
    '<p>It catches almost every single mistyped digit and most swaps of adjacent',
    'digits. It does nothing against a person who WANTS a valid-looking number,',
    'because the rule is public and anyone can make a fresh one pass.</p>',
    '<div class="fs-pull"><p>A checksum answers &ldquo;did this change by',
    'accident?&rdquo; It cannot answer &ldquo;did someone change this on',
    'purpose?&rdquo;</p></div>',
    '<p><b>WHY IT IS NOT CRYPTOGRAPHIC.</b> Every one of these is public and',
    'reversible in the sense that matters to an attacker: knowing the rule, you',
    'can change the data AND fix the check so it still passes. An adversary who',
    'edits your file recomputes the CRC and moves on. To resist a deliberate',
    'change you need the one-way hash at',
    '<a href="the-hash-function.geocities.ws">the-hash-function</a>, where fixing',
    'the digest to match a forged message is the thing you cannot do. And when you',
    'read a check value aloud to a human, you have crossed into the territory of',
    '<a href="the-fingerprint.geocities.ws">the-fingerprint</a>.</p>',
    '<hr>',
    '<p><small>counter: 01844 · best viewed at 800x600 · a cypherpunk keeps this',
    'corner tidy · last updated 2 Jul</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- MD5 and SHA: a history of the attack -----------------------------------

const MD5_AND_SHA = P('md5-and-sha.geocities.ws', 'MD5 AND SHA',
  'MD5 AND SHA // the hashes everyone runs, and the cracks in them', [
    '<!--bg:cryp-integrity-->',
    '<h1>MD5 AND SHA</h1>',
    '<p><small>a history-of-the-attack page. i am not saying stop using them',
    'tomorrow. i am saying read the warnings, because the people who write the',
    'attacks are not bluffing and they never have been. — a worried sysadmin</small></p>',
    '<div class="fs-epi"><p>&ldquo;Attacks always get better; they never get',
    'worse.&rdquo; &mdash; a maxim repeated at every crypto conference</p></div>',
    '<hr>',
    '<p><b>MD5.</b> Ronald Rivest of MIT, the R of RSA, designed a family of',
    'message digests. MD4 came in 1990 and fell fast. MD5 followed in 1991,',
    'strengthened, and became the hash the decade actually ran on: file integrity,',
    'password stores, the checksums under half the software you downloaded. It',
    'produces a 128-bit digest. Small, fast, everywhere.</p>',
    '<p><b>SHA.</b> The Secure Hash Algorithm came out of the NSA and was',
    'published by NIST as a federal standard. The first, in 1993 and now called',
    'SHA-0, was withdrawn almost at once. SHA-1 replaced it in 1995 with a tiny',
    'design change the agency would not fully explain, and produces a 160-bit',
    'digest. The extra 32 bits over MD5 matter more than they look, because the',
    'birthday attack works on half the bit-length; see',
    '<a href="the-collision.geocities.ws">the-collision</a> for why.</p>',
    '<pre>',
    '  hash     year   digest bits   birthday bound (approx work)',
    '  MD4      1990   128           2^64      (broken)',
    '  MD5      1991   128           2^64',
    '  SHA-0    1993   160           2^80      (withdrawn)',
    '  SHA-1    1995   160           2^80',
    '</pre>',
    '',
    '<p><b>THE FIRST CRACKS.</b> The warnings did not wait long. In 1993 den',
    'Boer and Bosselaers found a &ldquo;pseudo-collision&rdquo; in MD5&rsquo;s',
    'compression function. In 1996 Hans Dobbertin pushed that to a real collision',
    'in the compression function and said in print what the cautious had begun to',
    'suspect: MD5 should not be trusted where collision resistance is required,',
    'and a better hash should be chosen for new work. The full function had not',
    'been broken end to end, but the floor was creaking and everyone in the room',
    'could hear it.</p>',
    '<div class="fs-aside"><p><b>WHY 128 BITS STOPPED FEELING LIKE ENOUGH.</b> A',
    '128-bit hash offers only 64 bits of resistance against a collision, because',
    'the birthday attack halves the exponent. Sixty-four bits looked comfortable',
    'in 1991 and looks a good deal less so once you price a decade of Moore&rsquo;s',
    'law into the machine doing the searching.</p></div>',
    '<p>The pattern is the one at the top of this page. Nobody wakes up to a hash',
    'that broke overnight; the distance from &ldquo;a weakness in the compression',
    'function&rdquo; to &ldquo;here are two files with the same digest&rdquo;',
    'closes year by year, and the sensible reader migrates while the migrating is',
    'still calm. For what a hash is meant to do in the first place, go back to',
    '<a href="the-hash-function.geocities.ws">the-hash-function</a>.</p>',
    '<hr>',
    '<p><small>counter: 02571 · best viewed in Netscape at 800x600 · this page',
    'updated whenever the news is bad · PGP fingerprint 91C7 4E20 0B8A 5D13 66F1',
    '9A44 2E70 C085 (invented) · last updated 9 May</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the message authentication code: a close reading -----------------------

const MAC = P('the-message-authentication-code.geocities.ws', 'MAC',
  'THE MESSAGE AUTHENTICATION CODE // the hash that knows who you are', [
    '<!--bg:cryp-integrity-->',
    '<h1>THE MESSAGE AUTHENTICATION CODE</h1>',
    '<p><small>a close reading of one idea, the keyed hash. short page, one point,',
    'made properly. — a reader of the group</small></p>',
    '<hr>',
    '<p>A plain hash proves a message is whole. It cannot prove who sent it,',
    'because the hash is public and anyone who alters the message can recompute the',
    'digest to match. The message authentication code closes that gap by folding a',
    'shared secret key into the hash. The sender computes a tag from the message',
    'AND the key; the receiver, who holds the same key, recomputes it and checks.',
    'A match means two things at once: the message is unaltered, and it came from',
    'someone who knows the key.</p>',
    '<div class="fs-quote"><p>Integrity asks whether the message changed.',
    'Authenticity asks who sent it. A MAC is the one short tag that answers',
    'both.</p></div>',
    '<p><b>WHY NOT JUST HASH THE KEY WITH THE MESSAGE.</b> The obvious move, tag =',
    'H(key followed by message), leaks. With the hash constructions of the day an',
    'attacker who has one valid tag can extend the message and produce a new valid',
    'tag without knowing the key at all, the length-extension trick. The naive',
    'keyed hash is weaker than it looks, and that is exactly the sort of thing this',
    'corner of the web exists to warn about.</p>',
    '',
    '<p><b>HMAC.</b> Bellare, Canetti and Krawczyk set the construction right in',
    '1996. HMAC wraps the hash twice with the key mixed in through two different',
    'pads, an inner and an outer round, which closes the extension hole and comes',
    'with a proof that the whole stands as long as the underlying hash behaves.',
    'The shape, in words rather than secrets:</p>',
    '<pre>',
    '  HMAC(K, m) = H( (K XOR opad) followed by H( (K XOR ipad) followed by m ) )',
    '',
    '    K     the shared secret key',
    '    ipad  the inner pad, the byte 0x36 repeated',
    '    opad  the outer pad, the byte 0x5c repeated',
    '    H     any decent hash (see md5-and-sha)',
    '</pre>',
    '<p>It takes whatever hash you trust and turns it into a keyed tag without',
    'trusting the hash to do more than it promised. The hash it wraps is the',
    'business of <a href="md5-and-sha.geocities.ws">md5-and-sha</a>.</p>',
    '<p><b>NOT A SIGNATURE.</b> A MAC uses ONE key that both sides hold, so either',
    'side could have made any tag. That is fine between two parties who trust each',
    'other and useless as proof to a third, because you cannot show a judge which',
    'of you wrote it. A digital signature uses a private key only the signer holds',
    'and gives non-repudiation; a MAC gives shared assurance and nothing you can',
    'take to court. And when a human reads a short value aloud to check a key by',
    'ear, that is the fingerprint at',
    '<a href="the-fingerprint.geocities.ws">the-fingerprint</a>, a different job',
    'again.</p>',
    '<hr>',
    '<p><small>counter: 00937 · best viewed at 800x600 · kept by a sci.crypt',
    'regular · last updated 21 Mar</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the collision: a close reading -----------------------------------------

const COLLISION = P('the-collision.geocities.ws', 'COLLISION',
  'THE COLLISION // two doors, one key, and the birthday trick', [
    '<!--bg:cryp-integrity-->',
    '<h1>THE COLLISION</h1>',
    '<p><small>a close reading of the one thing that breaks a hash. the maths is',
    'small and the consequence is large. bring the pigeons. — a puzzle-setter</small></p>',
    '<div class="fs-epi"><p>&ldquo;There are more messages than there are',
    'digests. The rest is only arithmetic.&rdquo; &mdash; scrawled in a margin</p></div>',
    '<hr>',
    '<p>A collision is two different inputs with the same digest. That collisions',
    'EXIST is not a flaw and not in doubt. A hash maps inputs of every length onto',
    'a fixed number of outputs, so there are vastly more possible messages than',
    'possible digests, and by the pigeonhole principle some digests must be shared.',
    'If you have more pigeons than holes, one hole holds two birds. There is no',
    'argument to be had with it.</p>',
    '<div class="fs-aside"><p><b>THE PIGEONHOLE, PLAINLY.</b> A 128-bit hash has',
    'about 3.4 x 10^38 possible outputs. The number of possible inputs has no',
    'upper bound at all. Collisions are therefore a certainty. The security',
    'question was never whether they exist; it is whether anyone can FIND one.</p></div>',
    '<p><b>THE BIRTHDAY ATTACK.</b> Here is the unpleasant part. You might think',
    'finding a collision in an n-bit hash takes about 2^n tries. It does not. It',
    'takes about 2^(n/2), the square root, and the reason is the birthday paradox.',
    'In a room of just twenty-three people the odds are better than even that two',
    'share a birthday, because you are not matching one fixed date, you are',
    'matching ANY pair, and the pairs multiply far faster than the people.</p>',
    '',
    '<p>Apply that to hashes. To collide with ONE specific digest (a pre-image)',
    'you really do face the full 2^n. But to find ANY two inputs that agree, an',
    'attacker generates a pile of messages, hashes them, and waits for two to',
    'match, and by the birthday count the pile only needs to be about 2^(n/2)',
    'deep. The effective strength is HALVED.</p>',
    '<pre>',
    '  hash bits n     pre-image work 2^n     collision work 2^(n/2)',
    '  64              2^64                    2^32   (trivial today)',
    '  128             2^128                   2^64',
    '  160             2^160                   2^80',
    '</pre>',
    '<p>That halving is why a 128-bit hash is treated as a 64-bit promise and why',
    'the field kept reaching for more bits. The numbers behind MD5&rsquo;s 128 and',
    'SHA&rsquo;s 160 are read out at',
    '<a href="md5-and-sha.geocities.ws">md5-and-sha</a>.</p>',
    '<div class="fs-pull"><p>Find one pair of documents with the same digest and',
    'every signature over that digest signs both.</p></div>',
    '<p><b>WHY A COLLISION BREAKS A SIGNATURE.</b> A signature signs a hash, not a',
    'document. Suppose an attacker prepares two messages that collide, an innocent',
    'one and a hostile one, and gets you to sign the innocent one. Your signature',
    'is over the shared digest, so it validates the hostile message just as well.',
    'You signed a benign letter; the same signature now vouches for a contract you',
    'never saw. Collision resistance is the property that stops this, and it is',
    'the property the birthday attack comes for first. The whole edifice it',
    'protects is set out at',
    '<a href="the-hash-function.geocities.ws">the-hash-function</a>.</p>',
    '<hr>',
    '<p><small>counter: 01508 · best viewed in Netscape at 800x600 · a webring for',
    'crypto keeps the lights on · last updated 30 Apr</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the fingerprint: a worked example page ---------------------------------

const FINGERPRINT = P('the-fingerprint.geocities.ws', 'FINGERPRINT',
  'THE FINGERPRINT // the hash you say out loud', [
    '<!--bg:cryp-integrity-->',
    '<h1>THE FINGERPRINT</h1>',
    '<p><small>a worked page on the human end of integrity. the maths ends at your',
    'mouth. read one to a friend down the phone and you will remember this better',
    'than any diagram. — a PGP evangelist, key below</small></p>',
    '<hr>',
    '<p>A public key is a long ugly number. Comparing two of them by eye, digit by',
    'digit, is how mistakes get made, and a swapped key is how a man in the middle',
    'gets in. The fingerprint is the fix: hash the key down to a short string and',
    'compare the string instead. If the fingerprints match, the keys match, because',
    'a hash that resists second pre-images will not let a different key wear the',
    'same fingerprint. You have shrunk an impossible comparison to a possible one.</p>',
    '<p><b>WORKED, WITH AN INVENTED KEY.</b> A fingerprint is usually shown as hex',
    'in spaced groups so a human can keep their place while reading it aloud. This',
    'is not anyone&rsquo;s real key; it is here to be read:</p>',
    '<pre>',
    '  Key fingerprint = 2E9F  A1C4  70DB  5638  11A0',
    '                    8FD2  4B67  C309  E5A1  7C40',
    '</pre>',
    '<div class="fs-aside"><p><b>THE PGP WORD LIST.</b> Hex read down a crackly',
    'phone line is a trap: &ldquo;C&rdquo; and &ldquo;D&rdquo; and &ldquo;E&rdquo;',
    'blur, and &ldquo;fifty&rdquo; and &ldquo;fifteen&rdquo; wreck a whole line.',
    'PGP maps each byte to a distinct English word, two lists that alternate for',
    'odd and even positions so a dropped word is caught. You read words, not',
    'letters, and the ear does the checking.</p></div>',
    '',
    '<p>The same invented fingerprint, spoken as words instead of hex, so you can',
    'hear the difference:</p>',
    '<pre>',
    '  hex   :  2E   9F   A1   C4   70   DB',
    '  spoken:  frighten  hamlet  reindeer  sardonic  bottomless  concurrent',
    '           (illustrative words only, not the real PGP list mapping)',
    '</pre>',
    '<div class="fs-pull"><p>You never send the key down the phone. You send the',
    'fingerprint, and the fingerprint is small enough to trust your own ears.</p></div>',
    '<p><b>COMPARING OVER THE PHONE.</b> The ritual, and it is a ritual worth',
    'keeping. You get someone&rsquo;s key by whatever grubby channel, email or a',
    'keyserver or a floppy at a party. Then you ring them, a voice you recognise,',
    'and you read the fingerprint to each other. Match, and you know the key is',
    'theirs and nobody swapped it on the way. It is the point where the cold',
    'mathematics of the hash comes to rest on a warm thing, a familiar voice',
    'confirming a short string.</p>',
    '<p>The short value is only as trustworthy as the hash under it, so a',
    'fingerprint inherits every worry about collisions and about which hash was',
    'used; that keyed-and-secret cousin, the tag two parties share, is the MAC at',
    '<a href="the-message-authentication-code.geocities.ws">the-message-authentication-code</a>.',
    'And the plain error-catching check, the non-cryptographic one you compute for',
    'a noisy line rather than an enemy, is the checksum at',
    '<a href="the-checksum.geocities.ws">the-checksum</a>.</p>',
    '<hr>',
    '<p><small>counter: 02233 · best viewed at 800x600 · sign my key at the next',
    'meet · PGP fingerprint 2E9F A1C4 70DB 5638 11A0 8FD2 4B67 C309 E5A1 7C40',
    '(invented, matches the example above) · last updated 18 Jun</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

export const CRYP_D = [HASH_FUNCTION, CHECKSUM, MD5_AND_SHA, MAC, COLLISION, FINGERPRINT];
