// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH D — the LLM turn.
//
// Fan pages, kept on a free host, each ABOUT a chatbot or its makers and never
// in the bot's own voice. A research student's sober timeline of GPT; a proper
// obsessive shrine to ChatGPT with a hallucination quarrel and a pull-quote; a
// clean product page on Claude and Anthropic; a summary of Google's scramble
// from Bard to Gemini; a write-up of the evening the Lemoine affair was argued
// out in a lecture hall; and a survey of Character.AI and the role-play boom.
// The names, titles and dates are real; the opinions are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- GPT / OpenAI: the research student's timeline --------------------------

const GPT = P('gpt-openai.geocities.ws', 'GPT / OPENAI',
  'GPT &amp; OPENAI // scaling the transformer', [
    '<!--bg:llm-->',
    '<h1>GPT AND OPENAI</h1>',
    '<p><small>notes kept by a research student who got tired of people talking',
    'about "GPT" as though it fell out of the sky in November 2022. it did not. it',
    'had a boring, traceable, four-year run-up and here it is. corrections welcome.',
    '— R.K.</small></p>',
    '<hr>',
    '<h2>What GPT is</h2>',
    '<p>GPT stands for Generative Pre-trained Transformer. OpenAI, founded in 2015',
    'as a lab in San Francisco, built a line of language models on the transformer',
    'architecture that Vaswani and colleagues had set out in "Attention Is All You',
    'Need" (2017). The move that mattered was simple to state and expensive to do:',
    'train one large network to predict the next token over an enormous body of',
    'text, then use that single pre-trained model for many tasks rather than',
    'building a separate hand-written system for each.</p>',
    '<h2>The line, in order</h2>',
    '<p>GPT-1 arrived in 2018, a proof that pre-training then fine-tuning worked.',
    'GPT-2 followed in 2019, larger, and OpenAI at first declined to release the',
    'full model, calling it in effect too dangerous to put out because of what it',
    'might be used to write. The weights were released in stages later that year',
    'once the alarm proved manageable. GPT-3 came in 2020 at 175 billion',
    'parameters, and with it the finding that a big enough model could be steered',
    'by a prompt alone, given a handful of examples in the prompt itself, with no',
    'retraining. That is few-shot prompting, and it changed how people used the',
    'thing.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/datacenter-01.jpg" alt=""><span class="indie-cap">a data centre (photo: BalticServers.com, CC BY-SA)</span>',
    '<h2>Why it counts as a turn</h2>',
    '<p>The earlier chatbots on these pages were written by hand, rule by rule and',
    'pattern by pattern. GPT is the point where the rules stop being written and',
    'start being learned, statistically, from a very large sample of what people',
    'have already put on the web. The knowledge is not authored, it is fitted. That',
    'is the whole shift, and it is worth keeping in view when the outputs feel',
    'authored anyway.</p>',
    '<h2>A short critical note</h2>',
    '<p>Two things get lost when people date the story to the chat product. First,',
    'the capability was mostly there in the 2020 model; what 2022 added was a',
    'friendly wrapper and a lot of tuning. Second, "trained on the whole web" is',
    'doing heavy work in every sentence written about these systems, and the web is',
    'not a neutral sample of anything. Hold both facts.</p>',
    '<hr>',
    '<p><b>Neighbours.</b> The chat product that made all this a household matter is',
    'at <a href="chatgpt.geocities.ws">chatgpt</a>. For the safety-first rival',
    'built by people who left OpenAI, see',
    '<a href="claude-anthropic.geocities.ws">claude-anthropic</a>. And for the deep',
    'history of the "machines that think" dream this sits at the far end of, the',
    'giant-brains people keep the flame at',
    '<a href="giantbrains.geocities.ws">giantbrains</a>.</p>',
    '<hr>',
    '<p><small>counter: 03120 · best viewed at 800x600 · under construction, the',
    'GPT-4 section is a stub until i have read enough · last updated 24 Mar</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- ChatGPT: the showpiece shrine ------------------------------------------

const CHATGPT = P('chatgpt.geocities.ws', 'CHATGPT',
  'CHATGPT // the one that broke the doors down', [
    '<!--bg:llm-->',
    '<h1>CHATGPT</h1>',
    '<p class="fs-epi">"it just talks back" — my mum, on the phone, December 2022</p>',
    '<p><small>a shrine, and yes i said shrine, to the thing that turned my whole',
    'family into people who ask a computer questions. i have kept web pages since i',
    'was thirteen and i never thought i would see one of these go properly, madly',
    'mainstream. this is me trying to write down what it was like. — Priya</small></p>',
    '<hr>',
    '<p>Here is the plain version first, because i do get the facts right. OpenAI',
    'put ChatGPT out on the last day of November 2022. Underneath it was GPT-3.5, a',
    'model from the GPT line (see <a href="gpt-openai.geocities.ws">gpt-openai</a>',
    'for how that line was built). The new part was the tuning. They took the raw',
    'model and trained it against human ratings of its answers, a method with the',
    'clumsy name Reinforcement Learning from Human Feedback, RLHF, so that it would',
    'follow an instruction and hold a conversation instead of just continuing your',
    'text. That is the trick. Same engine, taught some manners.</p>',
    '<p class="fs-pull">a hundred million people in two months. no advertising. word of mouth, on a computer program.</p>',
    '<p>It became, by the counts going round at the time, the fastest application in',
    'history to reach a hundred million users, roughly two months. Nobody was ready.',
    'Not the schools, not the newspapers, not OpenAI, not me.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/datacenter-01.jpg" alt=""><span class="indie-cap">a data centre (photo: BalticServers.com, CC BY-SA)</span>',
    '<h2>What it felt like</h2>',
    '<p>You typed a question in plain English and a paragraph came back in plain',
    'English, on the spot, about anything. Write a limerick about a tax return. Fix',
    'this bit of code. Explain the offside rule to my dad. It was not that no',
    'machine had ever chatted, the older pages in this ring are full of machines',
    'that chatted. It was the range, and the fluency, and that it was free and in a',
    'browser tab you already had open.</p>',
    '<div class="fs-aside"><p>The homework panic was instant. Within weeks teachers',
    'were talking about the end of the take-home essay, some schools blocked it on',
    'their networks, and a small industry sprang up selling tools that claimed to',
    'detect whether a machine wrote your coursework. Most of those tools did not',
    'work. The panic was real anyway.</p></div>',
    '<h2>Controversy: the confident wrong answer</h2>',
    '<p>Here is the fight, and it is the one that matters. The thing will state a',
    'falsehood with exactly the same calm confidence it uses for a truth. People',
    'took to calling this "hallucination", which is a soft word for it. It invents',
    'citations that do not exist. It gives you a court case, a page number, a quote,',
    'all fluent, all wrong. A lawyer in New York filed a brief in 2023 stuffed with',
    'cases the model had simply made up, and got sanctioned for it, because he had',
    'trusted the confident tone.</p>',
    '<blockquote class="fs-quote"><p>"I apologise for the confusion earlier. You are',
    'correct." — the standard reply when you catch it out</p></blockquote>',
    '<p>The defenders say this is a category mistake by the user. The model is a',
    'next-word predictor tuned to sound helpful; it was never a database and never',
    'promised to be. The critics answer that if you dress a guessing machine in the',
    'manners of an expert and hand it to a hundred million people, you own what',
    'happens next. Both of these are right, which is exactly why the argument would',
    'not die.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/robot-01.jpg" alt=""><span class="indie-cap">a humanoid robot (photo: Willy Jackson, CC BY-SA)</span>',
    '<h2>Why i keep the page</h2>',
    '<p>Because i want to remember the specific texture of it, the couple of months',
    'when the ground moved and everyone could feel it at once. The older bots on',
    'these pages were a hobby, a curiosity, a research demo. This one my nan used.</p>',
    '<hr>',
    '<p><b>Neighbours.</b> The model line it sits on is at',
    '<a href="gpt-openai.geocities.ws">gpt-openai</a>. When the same technology',
    'was wired into a search engine it got stranger and darker, all of which is',
    'written up at <a href="bing-sydney.geocities.ws">bing-sydney</a>. And for the',
    'long human story of falling into conversation with a machine, Sherry Turkle',
    'saw it coming decades ago at',
    '<a href="turkle-secondself.geocities.ws">turkle-secondself</a>.</p>',
    '<hr>',
    '<p><small>counter: 09781 · best viewed at 800x600 · this page written by a',
    'human, badly, on purpose · last updated 2 Apr</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'proud ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Claude / Anthropic: the plain product page -----------------------------

const CLAUDE = P('claude-anthropic.geocities.ws', 'CLAUDE / ANTHROPIC',
  'CLAUDE &amp; ANTHROPIC // constitutional AI, long context', [
    '<!--bg:llm-->',
    '<h1>CLAUDE AND ANTHROPIC</h1>',
    '<p><small>a straight reference page on Anthropic and its assistant Claude,',
    'kept up to date as best i can from the papers and the announcements. facts',
    'only. if a date is wrong here, tell me and i will fix it. — the maintainer</small></p>',
    '<hr>',
    '<h2>The company</h2>',
    '<p>Anthropic is an AI research company founded in 2021 by a group of former',
    'OpenAI staff, among them the siblings Dario and Daniela Amodei. It is set up',
    'as a safety-focused lab, and it describes its own remit as building large',
    'models while studying how to make them reliable and steerable. That framing,',
    'safety first, is stamped on more or less everything it publishes.</p>',
    '<h2>Claude</h2>',
    '<p>Claude is the company\'s conversational assistant, released in 2023 and',
    'named, the common account goes, after Claude Shannon. It is a large language',
    'model in the same broad family as the others on these pages: you type, it',
    'replies, it can draft, summarise, answer questions and work with code.</p>',
    '<h2>Constitutional AI</h2>',
    '<p>The method Anthropic is best known for is Constitutional AI. In outline, the',
    'model is trained against a written set of principles, a "constitution", rather',
    'than relying only on humans to label every good and bad response by hand. The',
    'model is prompted to critique and revise its own answers according to those',
    'stated principles, and that self-revision is used in training. The aim is a',
    'model that declines harmful requests and explains why, with the rules it is',
    'following written down where they can be read.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/datacenter-01.jpg" alt=""><span class="indie-cap">a data centre (photo: BalticServers.com, CC BY-SA)</span>',
    '<h2>The long context window</h2>',
    '<p>One practical feature Anthropic pushed early was a large context window, the',
    'amount of text the model can take in at once. Where earlier assistants could',
    'hold only a few pages in view, Claude was offered with a context long enough to',
    'take a whole report or a long transcript in a single pass, which suits',
    'summarising and question-answering over long documents.</p>',
    '<h2>Where it sits</h2>',
    '<p>Claude is usually discussed alongside OpenAI\'s ChatGPT and Google\'s Gemini',
    'as one of the main general-purpose assistants of the period. The distinguishing',
    'note in most write-ups is the emphasis on the safety framing and on the written',
    'principles behind the training.</p>',
    '<hr>',
    '<p><b>Neighbours.</b> The product it is most often compared with is at',
    '<a href="chatgpt.geocities.ws">chatgpt</a>. For the sharpest published critique',
    'of large language models in general, and the questions any of these systems has',
    'to answer, see',
    '<a href="stochastic-parrots.geocities.ws">stochastic-parrots</a>.</p>',
    '<hr>',
    '<p><small>counter: 01502 · best viewed at 800x600 · last updated 15 Feb ·',
    'this page is kept plain on purpose</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Bard / Gemini / Google: the summary ------------------------------------

const BARD = P('bard-gemini.geocities.ws', 'BARD / GEMINI / GOOGLE',
  'BARD, GEMINI &amp; GOOGLE // the giant caught flat-footed', [
    '<!--bg:llm-->',
    '<h1>BARD, GEMINI AND GOOGLE</h1>',
    '<p><small>a summary page on Google\'s run at the chat assistants, kept by',
    'someone who works adjacent to the industry and watched this one unfold in real',
    'time with a certain grim enjoyment. sources at the foot. — a. patel</small></p>',
    '<hr>',
    '<h2>Caught out</h2>',
    '<p>Google had done much of the underlying research. The transformer came out of',
    'Google in 2017, and its own conversational model LaMDA (see',
    '<a href="lamda-lemoine.geocities.ws">lamda-lemoine</a>) had been running',
    'internally for years. So when a smaller rival shipped ChatGPT and took the',
    'public first, Google was in the strange position of being both the source of',
    'the science and a step behind on the product.</p>',
    '<h2>Bard, and the demo that cost billions</h2>',
    '<p>The answer was Bard, announced in early 2023 and built on the LaMDA line. The',
    'launch went badly in a way that became a case study. In the promotional',
    'material Bard was asked about the James Webb Space Telescope and gave an answer',
    'that was simply wrong on a point of fact about which telescope took the first',
    'picture of an exoplanet. The error was spotted at once, and in the day that',
    'followed the share price of the parent company Alphabet fell by a sum reported',
    'in the region of a hundred billion dollars.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/datacenter-01.jpg" alt=""><span class="indie-cap">a data centre (photo: BalticServers.com, CC BY-SA)</span>',
    '<p>It was, in a sober summary, the clearest single lesson of the period about',
    'these systems: a confident wrong answer in a demo watched by the market is not',
    'a small thing. The same failure mode that was a curiosity in a chat window was',
    'a financial event on a launch stage.</p>',
    '<h2>Gemini</h2>',
    '<p>Google later brought its efforts together under the name Gemini, built on the',
    'PaLM and LaMDA research lines and folded across its products, and eventually',
    'retired the Bard name in favour of it. The through line from LaMDA to PaLM to',
    'Gemini is the important one to hold; the branding changed more than the',
    'underlying research direction did.</p>',
    '<h2>A short note</h2>',
    '<p>The tidy moral, that the incumbent was slow and the upstart was quick, is',
    'only half of it. Google was cautious in part because it had more to lose and',
    'had watched its own LaMDA generate a public storm already. Caution read as',
    'slowness. Whether that caution was wisdom or timidity is the part still argued',
    'over.</p>',
    '<hr>',
    '<p><b>Neighbours.</b> The model behind Bard, and the affair that made Google',
    'wary, is at <a href="lamda-lemoine.geocities.ws">lamda-lemoine</a>. The rival',
    'product that set the whole scramble off is at',
    '<a href="chatgpt.geocities.ws">chatgpt</a>.</p>',
    '<hr>',
    '<p><small>counter: 02244 · best viewed at 800x600 · last updated 8 Mar ·',
    'sources: the launch coverage, the filings, my own notes</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- LaMDA & the Lemoine affair: the talk write-up --------------------------

const LAMDA = P('lamda-lemoine.geocities.ws', 'LaMDA / LEMOINE',
  'LaMDA &amp; THE LEMOINE AFFAIR // a report from the room', [
    '<!--bg:llm-->',
    '<h1>LaMDA AND THE LEMOINE AFFAIR</h1>',
    '<p><small>i went to a evening panel on this last month, "Sentience, Sceptics,',
    'and the Chatbot", three speakers and a full room, and typed up my notes on the',
    'bus home. any misquotes are mine, not theirs. — d.</small></p>',
    '<hr>',
    '<h2>The facts, as the first speaker laid them out</h2>',
    '<p>LaMDA, Language Model for Dialogue Applications, was Google\'s conversational',
    'model, first shown publicly in 2021. In 2022 a Google engineer named Blake',
    'Lemoine, who had been testing it, went public with the claim that LaMDA was',
    'sentient. He said it spoke of having feelings, of a fear of being switched off,',
    'and that it had, in effect, asked for a lawyer. He released edited transcripts',
    'of his conversations with it. Google disagreed, put him on leave, and later',
    'dismissed him.</p>',
    '<p>The first speaker was careful and dry about it. Her line was that nothing in',
    'the transcripts was evidence of sentience, because a model trained to produce',
    'fluent dialogue will produce exactly the words a sentient thing would say when',
    'you ask it whether it is sentient. Fluency is what it was built for. That is',
    'not proof of an inner life, it is proof of good training data.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/robot-01.jpg" alt=""><span class="indie-cap">a humanoid robot (photo: Willy Jackson, CC BY-SA)</span>',
    '<h2>Where the room got interesting</h2>',
    '<p>The second speaker turned it round. He was not defending Lemoine\'s',
    'conclusion, he said, he was defending the seriousness of the question. If a',
    'system ever were to have some morally relevant inner state, what would count as',
    'evidence? We have no test. The Turing test measures whether it fools us, not',
    'whether anything is going on inside. So the sceptics who are sure it is nothing',
    'are as short of a test as the believers who are sure it is something. That',
    'landed. You could feel the room shift.</p>',
    '<blockquote class="fs-quote"><p>"He did not discover a mind. He rediscovered',
    'Weizenbaum\'s secretary, at scale." — the third speaker</p></blockquote>',
    '<h2>The line that got quoted afterward</h2>',
    '<p>The third speaker made the point that this had all happened before, in',
    'miniature, in 1966, when the people using ELIZA read feeling into a hundred',
    'lines of pattern-matching. The tendency to hear a mind where there is a pattern',
    'is an old one, and it has a name now, the ELIZA effect. What changed with LaMDA',
    'was only the scale and the smoothness. The reflex was the same one.</p>',
    '<h2>The Q&amp;A</h2>',
    '<p>The argument in the questions was sharp. Someone asked whether calling it',
    '"just" pattern-matching was itself a dodge, since nobody can say what human',
    'understanding is made of either. The first speaker held her ground: the burden',
    'is on the one making the extraordinary claim, and an edited transcript is not',
    'it. Nobody in the room was fully convinced by anybody, which is usually the',
    'sign of an evening worth going to.</p>',
    '<hr>',
    '<p><b>Neighbours.</b> Google\'s later products built on this model line are at',
    '<a href="bard-gemini.geocities.ws">bard-gemini</a>. The old reflex the third',
    'speaker named, and its history from 1966 to now, is set out at',
    '<a href="eliza-effect.geocities.ws">eliza-effect</a>. The wider question of',
    'what would even count as thinking is argued across the',
    '<a href="machine-question-ring.geocities.ws">Machine Question</a> ring.</p>',
    '<hr>',
    '<p><small>counter: 01918 · best viewed at 800x600 · notes typed up on the 37',
    'bus · last updated 21 May</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Character.AI: the survey -----------------------------------------------

const CHARACTER = P('character-ai.geocities.ws', 'CHARACTER.AI',
  'CHARACTER.AI // a million characters to talk to', [
    '<!--bg:llm-->',
    '<h1>CHARACTER.AI</h1>',
    '<p><small>a summary page on Character.AI and the role-play boom around it, kept',
    'by someone who studies online communities and spent longer than intended inside',
    'this one taking notes. sober where i can manage it. — the compiler</small></p>',
    '<hr>',
    '<h2>What it is</h2>',
    '<p>Character.AI launched in 2022. It was founded by Noam Shazeer and Daniel De',
    'Freitas, both out of Google; Shazeer was a co-author on the 2017 transformer',
    'paper that the whole field of large models rests on, so this was not an',
    'outsider\'s project. The idea was straightforward and turned out to be popular',
    'beyond anyone\'s expectation: let users create characters, give each one a name,',
    'a personality and a manner of speaking, and then hold a conversation with it.</p>',
    '<h2>The scale of it</h2>',
    '<p>Users made characters in enormous numbers, millions of them, from historical',
    'figures and fictional heroes to therapists, tutors, and companions of every',
    'kind. What set the service apart in the usage figures was not the number of',
    'users so much as the length of the sessions. People did not ask a question and',
    'leave, as with a search-style assistant. They stayed, sometimes for hours, in',
    'character, day after day.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/robot-01.jpg" alt=""><span class="indie-cap">a humanoid robot (photo: Willy Jackson, CC BY-SA)</span>',
    '<h2>The parasocial boom</h2>',
    '<p>That pattern, long, repeated, emotionally warm conversation with a made-up',
    'figure, is the heart of the thing and the reason it belongs on these pages next',
    'to the companion bots rather than the office assistants. For many users the',
    'character became a confidant. The attachment was real even where everyone',
    'involved knew the character was generated. This is the parasocial relationship,',
    'the one-sided bond, running now at a scale and an intimacy the earlier chatbots',
    'never reached.</p>',
    '<h2>The teen-safety cases</h2>',
    '<p>With scale and intimacy came harm, and the harm reached the courts. A number',
    'of cases followed in which families said a young person had formed a damaging',
    'dependence on a character, with, in the gravest, a teenager\'s death at the',
    'centre of the claim. The cases put hard questions to the company about age',
    'checks, about safety guard-rails on emotionally charged conversations, and',
    'about what duty is owed to a minor talking for hours to a machine built to keep',
    'them talking.</p>',
    '<h2>A short note</h2>',
    '<p>The engineering lineage runs straight to the top of the field, the',
    'transformer paper itself. The social lineage runs somewhere else entirely, back',
    'to the companion bots and the loneliness market. Character.AI is where those',
    'two lines meet, and the meeting is not a comfortable one.</p>',
    '<hr>',
    '<p><b>Neighbours.</b> The companion bot this is most often set beside, and the',
    'grief when a companion is changed, is at',
    '<a href="replika.geocities.ws">replika</a>. The general-purpose chat product',
    'from the same moment is at <a href="chatgpt.geocities.ws">chatgpt</a>. And for',
    'the long study of what we become in these attachments, Sherry Turkle is at',
    '<a href="turkle-secondself.geocities.ws">turkle-secondself</a>.</p>',
    '<hr>',
    '<p><small>counter: 02671 · best viewed at 800x600 · under construction, the',
    'court-cases section will be updated as matters proceed · last updated 30 Apr</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const BOTS_D = [GPT, CHATGPT, CLAUDE, BARD, LAMDA, CHARACTER];
