// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — schools, movements & the makers.
//
// The design web at its most argumentative: the pages where enthusiasts fight
// about what design is FOR. A school's own prospectus kept alive by an admirer
// (the Bauhaus); a movement page that will not stop quoting Ruskin and Morris
// (Arts and Crafts); a tidy academic summary of the Vienna Workshops; a
// collector besotted with a Victorian who thought like an engineer (Dresser);
// a fan righting an old wrong (Eileen Gray); and a design student's coursework
// on the woman who refused the word decorator (Florence Knoll). Names, dates
// and pieces are real; the devotions and the grudges are the pages' own.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- the Bauhaus: the school's own prospectus, kept by an admirer -----------

const BAUHAUS = P('the-bauhaus.geocities.ws', 'THE BAUHAUS',
  'THE BAUHAUS // art and craft, one thing (1919-1933)', [
    '<!--bg:des-movements-->',
    '<h1>THE BAUHAUS</h1>',
    '<p class="fs-epi">"The ultimate aim of all art is the building." <br>— Walter Gropius, Bauhaus Manifesto, 1919</p>',
    '<p><small>A page for the Staatliches Bauhaus, the school that ran from 1919 to',
    '1933 and changed what a chair, a lamp and a wall were allowed to be. Kept by',
    'an admirer who has read the manifesto more times than is healthy.</small></p>',
    '<hr>',
    '<p>Walter Gropius opened the Bauhaus in Weimar in 1919 by folding the old art',
    'academy into the old crafts school and refusing to let them be two things. The',
    'manifesto put a cathedral on the cover, a woodcut by Lyonel Feininger, and',
    'argued that painter, sculptor and architect must come back down to the crafts',
    'and build together. There was to be no snobbery of the fine artist over the',
    'maker. Everyone passed first through the <i>Vorkurs</i>, the preliminary',
    'course, run first by Johannes Itten and then by Laszlo Moholy-Nagy, where you',
    'unlearned your habits and handled materials with your own eyes and hands.</p>',
    '<p>The teaching happened in workshops, not lecture halls, and each workshop',
    'was led by two people: a <i>Formmeister</i>, a master of form, and a',
    '<i>Werkmeister</i>, a master of craft. Metal, cabinet-making, weaving,',
    'pottery, wall-painting, printing, stage. The idea was that a young designer',
    'learned the hand and the head at once, so that a teapot or a cradle came out',
    'of real knowledge of the material and not out of a drawing done in ignorance.</p>',
    '<p class="fs-aside"><b>A note on the tubular steel.</b> The Wassily chair (1925)',
    'came out of the Dessau metal workshop under Marcel Breuer, who is said to have',
    'taken the idea from the handlebars of his Adler bicycle. Seamless bent steel',
    'tube, taut canvas or leather straps for the seat and back, the whole heavy',
    'upholstered armchair reduced to a line drawn in the air. Cheap in principle,',
    'reproducible, and unmistakably a thing that could only have been made once the',
    'bicycle factory existed.</p>',
    '<img class="indie-pic" src="assets/media/web/des/bauhaus-01.jpg" alt=""><span class="indie-cap">The Bauhaus building at Dessau (photo: JensKunstfreund, CC BY-SA 4.0)</span>',
    '<p>In 1925 the city of Weimar turned hostile and cut the money, and the school',
    'moved to Dessau, into the building everyone pictures when they hear the word:',
    'Gropius own glass-curtained workshop block, the bridge of offices, the studio',
    'tower with its little balconies. This is where the Bauhaus became the Bauhaus',
    'of the posters and the postcards. The masters lived in white flat-roofed',
    'houses at the edge of a pine wood, and taught a second generation who had',
    'themselves been students, so that the method began to feed itself.</p>',
    '<p>The painters are the part people remember, and no wonder. Paul Klee and',
    'Wassily Kandinsky both taught form here, Klee with his notebooks on the moving',
    'line and Kandinsky with his stubborn theory that a triangle wants to be',
    'yellow. Moholy-Nagy brought photography, film and the machine aesthetic and',
    'edited the Bauhaus books. Oskar Schlemmer ran the stage and made the Triadic',
    'Ballet, dancers turned into walking sculpture. It was a strange and glorious',
    'staff for a small provincial school to have gathered.</p>',
    '<p class="fs-pull">Art and craft were never to be two things. That is the',
    'whole of the manifesto, and everything the school made was an argument for it.</p>',
    '<p>Two people are usually left out of the postcard version and should not be.',
    'Gunta Stolzl ran the weaving workshop and became the only woman appointed a',
    'full master, and the weaving workshop was where a great deal of the school',
    'actual income came from. Anni Albers learned and then taught there before',
    'carrying the loom to America. The school preached equality and then quietly',
    'steered many of its women into the weaving workshop, which is a tension worth',
    'stating plainly rather than smoothing over.</p>',
    '<p><b>The three cities, in order.</b></p>',
    '<pre>',
    '1919-1925  WEIMAR   Gropius. The manifesto, the Vorkurs, Itten.',
    '                    Expressionist heat cooling into method.',
    '1925-1932  DESSAU   Gropius, then Hannes Meyer (1928), then',
    '                    Mies van der Rohe (1930). The glass building.',
    '                    Tubular steel, the Bauhaus books, the peak.',
    '1932-1933  BERLIN   Mies. A private institute in a disused',
    '                    telephone factory. Shut within the year.',
    '</pre>',
    '<p>The politics closed it. Hannes Meyer, who followed Gropius as director in',
    '1928, turned the school hard toward social use and the left, was pushed out in',
    '1930, and Mies van der Rohe took over to try to steer it out of trouble. It',
    'did not work. When the National Socialists took Dessau they cut the funding,',
    'and Mies reopened the school as a private venture in a derelict factory in',
    'Berlin. In 1933 the Gestapo closed it, and the staff voted to dissolve it',
    'themselves rather than accept the conditions offered.</p>',
    '<img class="indie-pic" src="assets/media/web/des/arts-crafts-01.jpg" alt=""><span class="indie-cap">Red House, Bexleyheath (photo: Velela, public domain)</span>',
    '<p>What looks like an ending was really a scattering. Gropius and Breuer went',
    'to Harvard, Mies to Chicago and the tower blocks, Moholy-Nagy founded the New',
    'Bauhaus there, Albers to Black Mountain College. The school lasted fourteen',
    'years and taught perhaps twelve hundred students, and its idea of the workshop,',
    'of the preliminary course, of the designer who knows the material, is now the',
    'water that every art and design school swims in without noticing.</p>',
    '<p>The movement it grew out of is at',
    '<a href="the-arts-and-crafts-movement.geocities.ws">the-arts-and-crafts-movement</a>,',
    'and it is worth reading the two together, because the Bauhaus took the Arts and',
    'Crafts love of the honest workshop and then made its peace with the machine',
    'that Morris could not abide. Its nearer cousin in time and temper is the Vienna',
    'workshop at',
    '<a href="the-wiener-werkstatte.geocities.ws">the-wiener-werkstatte</a>, luxury',
    'craft where the Bauhaus wanted mass production, but sharing the dream of the',
    'total designed world.</p>',
    '<hr>',
    '<p><small>hits: 03119 · best viewed at 800x600 · this page is under',
    'construction, the Berlin year needs more · last updated 14 Mar</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Arts and Crafts: the movement page that keeps quoting Ruskin -----------

const ARTSANDCRAFTS = P('the-arts-and-crafts-movement.geocities.ws', 'ARTS & CRAFTS',
  'THE ARTS AND CRAFTS MOVEMENT // the revolt of the craftsman', [
    '<!--bg:des-movements-->',
    '<h1>THE ARTS AND CRAFTS MOVEMENT</h1>',
    '<p><small>A page kept for the movement that looked at the Victorian machine,',
    'looked at what it was doing to the people who fed it, and said no. Roughly',
    '1880 to 1920 in Britain, then everywhere. We quote Ruskin and Morris a great',
    'deal here and make no apology for it.</small></p>',
    '<hr>',
    '<p>It began as an argument about work. John Ruskin, in the chapter called',
    '"The Nature of Gothic" in <i>The Stones of Venice</i> (1853), asked his',
    'readers to look at a rough medieval carving and to see in its very roughness',
    'the mark of a free man who had thought while he worked. The perfect machined',
    'ornament of the modern factory, he argued, was bought at the price of turning',
    'the worker into a tool. You cannot have both the finish and the freedom.</p>',
    '<p class="fs-quote"><blockquote>"You must either make a tool of the creature,',
    'or a man of him. You cannot make both."<br>— John Ruskin, The Stones of Venice,',
    '1853</blockquote></p>',
    '<p>William Morris took that sentence and spent his life acting on it. He hated',
    'what the factory made and hated more what it did to the maker, and he set out',
    'to prove that goods could be made well, by hand, by people who took pleasure',
    'in the making. From 1861 the firm (later Morris and Company) produced wallpaper,',
    'printed and woven textiles, stained glass, furniture and tiles. He revived',
    'vegetable dyes and hand-block printing when it would have been far cheaper to',
    'do neither. His famous rule for the home has never been bettered as advice.</p>',
    '<img class="indie-pic" src="assets/media/web/des/arts-crafts-01.jpg" alt=""><span class="indie-cap">Red House, Bexleyheath (photo: Velela, public domain)</span>',
    '<p class="fs-pull">Have nothing in your houses that you do not know to be',
    'useful, or believe to be beautiful. — William Morris, 1880</p>',
    '<p>There was a contradiction at the heart of it, and the movement knew, and it',
    'is fairer to name it than to hide it. Handwork is slow, and slow work is dear,',
    'so the honest hand-made table cost more than most of the people Morris cared',
    'about could ever pay. A socialist who could sell only to the rich. Morris felt',
    'this keenly and turned to political organising in his last years, lecturing on',
    'art and labour, because he had come to think the problem could not be solved',
    'one workshop at a time while the whole system stood.</p>',
    '<p class="fs-aside"><b>A note on the guild.</b> The movement organised itself',
    'into guilds and workshops on a half-remembered medieval model: the Century',
    'Guild (1882), the Art Workers Guild (1884), and C. R. Ashbee Guild of Handicraft',
    '(1888), which he moved from the East End of London out to Chipping Campden in',
    'the Cotswolds in 1902, taking the workmen and their families to make silver and',
    'furniture in the country. The Cotswold experiment is where the movement produced',
    'some of its purest furniture, under Ernest Gimson and the Barnsley brothers.</p>',
    '<img class="indie-pic" src="assets/media/web/des/dresser-01.jpg" alt=""><span class="indie-cap">A Christopher Dresser teapot (photo: Daderot, public domain)</span>',
    '<p>The word came late. "Arts and Crafts" was coined in 1887 for the Arts and',
    'Crafts Exhibition Society, which held the shows that gave the loose movement a',
    'name and a shop window. By then it had a shape: honesty to materials, so that',
    'oak looked and behaved like oak; construction shown rather than hidden, the',
    'joint left proud, the hinge on the outside of the door; truth to the making,',
    'so that a thing carried the evidence of the hand that made it.</p>',
    '<p><b>What it turned into.</b> The movement crossed the sea and the North Sea',
    'and changed as it went. In Vienna the impulse hardened into the geometric luxury',
    'of the Wiener Werkstatte. In Germany it fed, by a long and quarrelsome route,',
    'into the Bauhaus, which kept the love of the workshop and dropped the hatred of',
    'the machine. Read the school it fathered at',
    '<a href="the-bauhaus.geocities.ws">the-bauhaus</a>. One awkward relative belongs',
    'in the same conversation and is filed here as a provocation: Christopher Dresser,',
    'who admired the machine that Morris loathed and designed for it happily. He is at',
    '<a href="christopher-dresser.geocities.ws">christopher-dresser</a>, and he makes',
    'the movement define itself by contrast.</p>',
    '<p>Two names to hold in mind beyond the British story: Gustav Stickley, who',
    'carried the plain oak Craftsman furniture across the United States, and Elbert',
    'Hubbard of the Roycrofters, who did the same with more showmanship. Neither has',
    'a page in this ring, but both belong to the movement.</p>',
    '<hr>',
    '<p><small>counter: 01894 · best viewed at 800x600 · a hand-built page, joints',
    'showing · last updated 2 Feb</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- the Wiener Werkstatte: the tidy academic summary -----------------------

const WERKSTATTE = P('the-wiener-werkstatte.geocities.ws', 'WIENER WERKSTATTE',
  'The Wiener Werkstatte, 1903-1932 // a summary', [
    '<!--bg:des-movements-->',
    '<h1>The Wiener Werkstatte (1903-1932)</h1>',
    '<p><small>A short academic summary of the Vienna Workshops, compiled from the',
    'standard literature for anyone who needs the facts in order. Corrections by',
    'email if you have the Schweiger catalogue to hand.</small></p>',
    '<hr>',
    '<p>The Wiener Werkstatte, the Vienna Workshops, was a production co-operative of',
    'designers and craftsmen founded in 1903 by the architect Josef Hoffmann and the',
    'designer Koloman Moser, with financial backing from the industrialist and',
    'collector Fritz Waerndorfer. It grew out of the Vienna Secession, the group of',
    'artists who had broken from the academy in 1897, and it carried the Secession',
    'idea of a modern total art into the making of actual objects.</p>',
    '<p>The governing ambition was the <i>Gesamtkunstwerk</i>, the total work of',
    'art: a building and everything in it designed as one coherent thing, down to',
    'the cutlery, the light switches and the dress the client wore at dinner.',
    'Hoffmann and Moser wanted the whole visible world of a commission to speak in a',
    'single vocabulary, and that vocabulary was, above all, the grid. The square,',
    'repeated, pierced, laid over black and white, became so much the house signature',
    'that Hoffmann earned the nickname Quadratl-Hoffmann, little-square Hoffmann.</p>',
    '<p>The workshops issued a manifesto, the <i>Arbeitsprogramm</i>, in 1905, which',
    'set out the terms: good material and good work were worth more than showy',
    'decoration, the maker was to be named and valued, and the divide between the',
    'designer and the executing craftsman was to be closed. The debt to the British',
    'Arts and Crafts movement, and to Ashbee Guild of Handicraft in particular, was',
    'open and acknowledged; the difference was that Vienna embraced luxury and the',
    'metropolitan client where the British movement kept dreaming of the common good.</p>',
    '<img class="indie-pic" src="assets/media/web/des/wiener-werkstatte-01.jpg" alt=""><span class="indie-cap">The Palais Stoclet, Vienna Workshops (CC BY-SA 3.0)</span>',
    '<p>The great commission, and the surviving proof of the whole idea, is the',
    'Palais Stoclet in Brussels (1905 to 1911), built for the banker Adolphe Stoclet.',
    'Hoffmann designed the house and the workshops made everything inside it, and',
    'Gustav Klimt supplied the mosaic frieze for the dining room, the Tree of Life',
    'with the embracing figures. It is one of the few places where the total work of',
    'art was actually completed and paid for and still stands, and it is now a World',
    'Heritage site.</p>',
    '<p>The economics were always precarious. Hand-made luxury for a small clientele',
    'could not easily cover the wages of a large workshop, and the enterprise moved',
    'from crisis to crisis. Moser left in 1907. Waerndorfer was ruined and emigrated',
    'in 1914. The fashion and textile departments, and a lively line in postcards and',
    'the Kunstschau exhibitions, kept it visible through the 1910s and 1920s, and a',
    'new generation including Dagobert Peche brought a looser, more decorative manner',
    'after the First World War. The workshops finally closed in 1932, undone by the',
    'Depression.</p>',
    '<p><b>Legacy.</b> The Werkstatte stands between the Arts and Crafts workshop and',
    'the industrial designer of the twentieth century, sharing the first affection',
    'for craft and the second appetite for the modern city. Its clean geometry fed',
    'directly into what came after, and the reader who wants the school that pushed',
    'the same total-design dream toward the machine and mass production should go to',
    '<a href="the-bauhaus.geocities.ws">the-bauhaus</a>. A near contemporary who',
    'worked the same ground of modern craft, quite separately and to her own ends,',
    'is Eileen Gray at <a href="eileen-gray.geocities.ws">eileen-gray</a>.</p>',
    '<p>Select bibliography (as far as this compiler could check it): Werner J.',
    'Schweiger, <i>Wiener Werkstatte: Design in Vienna 1903-1932</i>; the standard',
    'exhibition catalogues; and the Secession literature on Hoffmann and Moser. Dates',
    'here follow those sources.</p>',
    '<hr>',
    '<p><small>hits: 00932 · best viewed at 800x600 · monochrome by design ·',
    'last updated 9 Dec</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Christopher Dresser: the collector's catalogue page --------------------

const DRESSER = P('christopher-dresser.geocities.ws', 'C. DRESSER',
  "Christopher Dresser // a collector's page (1834-1904)", [
    '<!--bg:des-movements-->',
    '<h1>Christopher Dresser</h1>',
    '<p><small>The pieces and the papers of Christopher Dresser (1834-1904), set out',
    'by a collector who has spent years and more than he should admit chasing his',
    'metalwork. If you own a marked Dresser piece and want it identified, write.</small></p>',
    '<hr>',
    '<p>The claim, and the collector will defend it, is that Christopher Dresser was',
    'the first independent industrial designer: the first man to make his living',
    'designing goods for factories to manufacture, signing them, and selling the',
    'design as the thing of value rather than the handwork. Where William Morris',
    'fought the machine, Dresser walked into the factory and asked what it could do',
    'that the hand could not, and then designed for that. He is the road not taken by',
    'the Arts and Crafts movement, filed here so the two can be read against each',
    'other. That movement is at',
    '<a href="the-arts-and-crafts-movement.geocities.ws">the-arts-and-crafts-movement</a>.</p>',
    '<p>He came to design through botany. Dresser trained and lectured as a botanist,',
    'good enough to be considered for a chair in the subject, and he wrote <i>The Art',
    'of Decorative Design</i> (1862) and <i>Principles of Decorative Design</i> (1873)',
    'out of a botanist idea of structure: that a plant is beautiful because it is',
    'built to work, growth and function showing in the form. He carried that eye into',
    'the design of everything, looking for the underlying structure and the fitness',
    'of a thing to its use, decades before Louis Sullivan gave the idea its slogan.</p>',
    '<p class="fs-aside"><b>A note on the metal.</b> The pieces the collector prizes',
    'are the electroplate and silver he designed in the late 1870s, above all for',
    'James Dixon and Sons of Sheffield and for Hukin and Heath. A Dresser toast rack',
    'or claret jug or teapot from these years is a shock: bare geometric bodies,',
    'legs like a drawing compass, ebonised wooden handles set at a clean angle,',
    'rivets left showing as honest fixings. They look as though they were designed in',
    'the 1930s. They were designed before 1880, for the machine, on purpose.</p>',
    '<img class="indie-pic" src="assets/media/web/des/dresser-01.jpg" alt=""><span class="indie-cap">A Christopher Dresser teapot (photo: Daderot, public domain)</span>',
    '<p>Japan is the other key. Dresser was among the very first European designers to',
    'go there, travelling through the country in 1876 as a guest of the government,',
    'and he wrote it up in <i>Japan: Its Architecture, Art and Art Manufactures</i>',
    '(1882). He did not want the picturesque surface of things that other Europeans',
    'copied. He wanted the Japanese principle: the beauty that comes from restraint,',
    'from a few well-chosen means, from leaving out. That principle is visible in his',
    'own severe metalwork long before anyone else in Britain was thinking that way.</p>',
    '<p><b>A short catalogue of what to look for.</b></p>',
    '<pre>',
    '  MAKERS      James Dixon & Sons; Hukin & Heath; Elkington;',
    '              Linthorpe Art Pottery (he was art director).',
    '  MATERIALS   electroplated nickel silver; sterling; ebonised',
    '              wood; cast iron; glass; pottery in strong glazes.',
    '  TELLS       geometric bodies, spider legs, exposed rivets,',
    '              angled handles, almost no ornament, a facsimile',
    '              signature "Chr. Dresser" on the better pieces.',
    '  DATES       the radical metalwork clusters 1878-1882.',
    '</pre>',
    '<p>He was busy to the point of disappearing behind his own output. Dresser ran a',
    'design studio that supplied patterns for wallpaper, carpets, textiles, ceramics,',
    'cast iron and glass to dozens of manufacturers, so that a great deal of ordinary',
    'high-Victorian material culture passed through his office unsigned. For a long',
    'time this hid him. The severe metal was ahead of its buyers, sold modestly, and',
    'his reputation faded after his death until the design historians of the later',
    'twentieth century recognised what those teapots were.</p>',
    '<p>The nearest heir in this ring, oddly, is not a Victorian at all but Florence',
    'Knoll, who also insisted that a good object was an argument about use and not a',
    'piece of decoration. See <a href="florence-knoll.geocities.ws">florence-knoll</a>.',
    'A useful monograph for the collector is Widar Halen, <i>Christopher Dresser</i>',
    '(1990), and the older Pevsner essays that first put him back on the map.</p>',
    '<hr>',
    '<p><small>counter: 00688 · best viewed at 800x600 · no frames, no nonsense ·',
    'last updated 21 Jan</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Eileen Gray: the fan shrine that rights an old wrong --------------------

const GRAY = P('eileen-gray.geocities.ws', 'EILEEN GRAY',
  'EILEEN GRAY // they forgot her and then they remembered', [
    '<!--bg:des-movements-->',
    '<h1>EILEEN GRAY</h1>',
    '<p><small>a fan page for Eileen Gray (1878-1976), Irish, brilliant, and left',
    'out of the story for far too long. kept by me because the first time i learned',
    'what happened at her own house i was actually angry. — niamh</small></p>',
    '<hr>',
    '<p>She was born Kathleen Eileen Moray Gray in Ireland in 1878, studied at the',
    'Slade in London, and moved to Paris, where she found the thing that would make',
    'her name: lacquer. She learned the craft properly, apprenticed to the Japanese',
    'master Seizo Sugawara, and it is brutal, painstaking work, coat after coat, the',
    'fumes bad enough to give her the lacquer disease on her hands. She did it anyway',
    'for years until she was one of the finest lacquer artists in Europe.</p>',
    '<p>Her screens are the early glory. The Brick Screen and the black lacquer panel',
    'screens are made of small blocks or panels that pivot, so the screen is never',
    'quite a wall and never quite open, a thing that changes as you move past it. The',
    'grand decorator Jacques Doucet bought her work, and in 1922 she opened her own',
    'shop in Paris, Galerie Jean Desert, to sell her lacquer, her rugs and her',
    'furniture. She was a maker and a shopkeeper and a designer all at once, and',
    'entirely her own.</p>',
    '<img class="indie-pic" src="assets/media/web/des/eileen-gray-01.jpg" alt=""><span class="indie-cap">The E-1027 adjustable table, by Eileen Gray (photo: 14GTR, CC0)</span>',
    '<p class="fs-pull">She built the house, she designed everything in it, and for',
    'fifty years the world gave the credit to a man who painted on its walls.</p>',
    '<p>Then the building. Between 1926 and 1929, with the architect Jean Badovici,',
    'Gray designed and built a small white modernist villa above the sea at',
    'Roquebrune on the Cote d Azur, and gave it the cryptic name E-1027. It is a code',
    'for their two names entwined: E for Eileen, 10 for J the tenth letter, 2 for B,',
    '7 for G. She designed the house AND everything in it, and this is where the',
    'furniture everyone knows was born, made for actual rooms and actual use.</p>',
    '<p class="fs-aside"><b>A note on the adjustable table.</b> The piece called E-1027,',
    'after the house, is the famous one: a circular glass top on a tubular steel frame,',
    'the column off-centre so the disc can reach out over a bed or a low chair, and the',
    'whole top slides up and down so you can raise it to eat or lower it to rest a cup.',
    'The story is that she made it so her sister could take breakfast in bed without',
    'crumbs in the sheets. Function first, and the elegance falls out of the function.</p>',
    '<p>The other pieces from these years are just as good. The Bibendum chair, two',
    'fat rolled leather arcs on a steel frame, named for the Michelin man because that',
    'is exactly what it looks like, and comfortable in a way modernist chairs usually',
    'refuse to be. The Transat chair, a folding sling like a deck chair rethought for',
    'a modern terrace. The lacquer, the rugs, the lot, all thought through together.</p>',
    '<p><b>Now the wrong.</b> Le Corbusier was a friend of Badovici and a visitor to',
    'E-1027, and he loved the house, and in 1938 and 1939 he painted a series of large',
    'coloured murals directly on to its white walls, without Gray consent. She was',
    'appalled. She had designed the walls to be bare, part of the architecture, and he',
    'had signed himself across them. For decades afterward the house was widely',
    'assumed to be his work, or Badovici, and Gray own authorship was quietly lost.',
    'It is one of the uglier acts in modern design and it is worth knowing who did it.</p>',
    '<p>The rediscovery came late and she lived to see a little of it. In 1972 a',
    'lacquer screen of hers sold at auction for a startling sum, the design world woke',
    'up, and Gray, by then in her nineties and nearly blind, was suddenly recognised',
    'as a pioneer of the modern interior. She died in 1976. The reproductions of the',
    'E-1027 table and the Bibendum chair are everywhere now, which is a kind of',
    'justice, though the house itself took much longer to be saved and set right.</p>',
    '<p>If you want the near neighbours: the woman who ran the American corporate',
    'interior with the same refusal to be called a mere decorator is at',
    '<a href="florence-knoll.geocities.ws">florence-knoll</a>, and the Vienna workshop',
    'where modern craft first went luxurious is at',
    '<a href="the-wiener-werkstatte.geocities.ws">the-wiener-werkstatte</a>. Read',
    'Peter Adam biography of Gray if you want the whole life.</p>',
    '<hr>',
    '<p><small>counter: 02007 · best viewed at 800x600 · this page will never be',
    'under construction on the Corbusier question · last updated 5 May · sign the',
    'guestbook, tell me you knew her name</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

// ---- Florence Knoll: the student coursework ---------------------------------

const KNOLL = P('florence-knoll.geocities.ws', 'FLORENCE KNOLL',
  'Florence Knoll // DES 214 coursework', [
    '<!--bg:des-movements-->',
    '<h1>Florence Knoll and the Knoll Look</h1>',
    '<p><small>DES 214, History of Modern Design, essay 3. "Account for the',
    'influence of a twentieth-century designer on the everyday environment." Student',
    'no. 9930418. Please excuse the under-construction bits, I ran out of time on the',
    'bibliography. — R.T.</small></p>',
    '<hr>',
    '<p>Florence Knoll (1917-2019), born Florence Schust and known to everyone as',
    'Shu, is the designer responsible for the way a modern office actually looks and',
    'feels, and yet most people have never heard her name. In this essay I will argue',
    'that her importance is exactly of the kind that gets overlooked, because she',
    'designed the background: the boardrooms, the reception areas and the open plans',
    'that a whole postwar corporate world took for granted.</p>',
    '<p>She trained as an architect, and this is the key to everything. She studied at',
    'the Cranbrook Academy of Art, where she became close to the Saarinen family and',
    'a friend of Charles and Ray Eames, and then at the Illinois Institute of',
    'Technology under Ludwig Mies van der Rohe. So she came out of the same Bauhaus',
    'line that ended up in America, the Bauhaus by way of Mies, and she brought an',
    'architect training to a furniture firm.</p>',
    '<p class="fs-quote"><blockquote>"I am not a decorator. The only place I decorate',
    'is my own house."<br>— Florence Knoll</blockquote></p>',
    '<p>She married Hans Knoll and together they built the Knoll company into the',
    'great American purveyor of modern furniture. Her genius move was the Knoll',
    'Planning Unit, which she ran from 1943: an in-house design service that would',
    'plan a client whole interior, space, layout, colour, textile and furniture',
    'together, as one architectural problem. A company did not just buy chairs from',
    'Knoll, it bought a designed environment. This is why the postwar corporate',
    'interior looks the way it does.</p>',
    '<img class="indie-pic" src="assets/media/web/des/knoll-01.jpg" alt=""><span class="indie-cap">Florence Knoll (photo: Governor Tom Wolf, CC BY 2.0)</span>',
    '<p>The "Knoll look" is the result: clean, rational, rectilinear, warmed by good',
    'materials and by carefully chosen colour and texture, usually with the strong',
    'sculptural chair of a colleague as the one soft or curved note in a room of',
    'right angles. Which brings me to the point my tutor said I always miss, so I',
    'will make it clearly this time.</p>',
    '<p class="fs-aside"><b>Note on how she used other people chairs.</b> Knoll put',
    'the great sculptural seats of her friends into production and then set them',
    'inside her own rational rooms as contrast: Eero Saarinen Womb chair (1948) and',
    'his Tulip pedestal chairs and tables, Harry Bertoia wire Diamond chair (1952),',
    'and Mies own Barcelona chair. Her own designs she once described, with dry',
    'modesty, as the "fill-in pieces that nobody else wants to do": the sofas, the',
    'benches, the tables, the storage. Someone had to design the sensible things.</p>',
    '<p>And the credenza is the best of those sensible things. The Knoll credenza is',
    'the long, low storage cabinet on slim legs that sits under the window in every',
    'well-run office of the period, holding the files and hiding the clutter, wood or',
    'lacquer above, a base of thin steel below. It is not glamorous and it was never',
    'meant to be. It is the piece that makes the rational room possible by giving the',
    'mess somewhere to go, and it is pure Florence Knoll: an ordinary need, solved',
    'with total seriousness.</p>',
    '<p>Her method was famous. She worked with "paste-ups", small collages of the',
    'actual wood veneers, the fabric swatches, the metal and the colour, pinned',
    'together to a plan, so a client could see and feel the whole room before a stick',
    'of it was built. It was a way of designing the atmosphere of a space and not',
    'only its objects, and it came straight out of her architectural training.</p>',
    '<p>In conclusion, Florence Knoll influence is everywhere and invisible, which is',
    'the hardest kind to see and to grade. She retired from the company in 1965. To',
    'compare her refusal of the word decorator with an earlier designer who insisted',
    'on structure over ornament, see the Victorian industrial designer Christopher',
    'Dresser at <a href="christopher-dresser.geocities.ws">christopher-dresser</a>,',
    'and for the modernist who also built the room and everything in it, see',
    '<a href="eileen-gray.geocities.ws">eileen-gray</a>.</p>',
    '<p><b>Bibliography</b> (UNDER CONSTRUCTION, will fix refs before hand-in):</p>',
    '<pre>',
    '  - the big Knoll company book, cant find my note of the author',
    '  - Bassett & Kirkham, something on women designers (check title)',
    '  - the Bertoia and Saarinen dates are off the Knoll catalogue',
    '  - ask tutor if Wikipedia counts, probably not',
    '</pre>',
    '<hr>',
    '<p><small>hits: 00251 · best viewed at 800x600 · made for DES 214 · GET OFF MY',
    'PAGE if you are the marker and it is still under construction · last updated',
    '28 Apr</small></p>',
    '<p><small>[ <a href="design-ring.geocities.ws">Design Ring</a> ]</small></p>',
  ]);

export const DES_F = [BAUHAUS, ARTSANDCRAFTS, WERKSTATTE, DRESSER, GRAY, KNOLL];
