// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH HOME_H — the survey, the wars, the end.
//
// Fan pages, kept on a free host, each ABOUT a home computer or an episode in
// home computing and never in a maker's own voice. A student's late survey of
// the whole twenty years (the Altair to Windows 95); a reading group's notes on
// the 1983 price war; a reading group on the shakeout that followed; a collector's
// love letter to keeping dead machines alive; and a sober account of the Cambridge
// rivalry between Sinclair and Acorn. The machines, dates and specs are real; the
// affection and the grudges are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- A history of the home computer: the student survey (showpiece) ---------

const HISTORY = P('a-history-of-home-computers.geocities.ws', 'A HISTORY',
  'A HISTORY OF THE HOME COMPUTER // Altair to Windows 95', [
    '<!--bg:kit-->',
    '<h1>A HISTORY OF THE HOME COMPUTER</h1>',
    '<p><small>coursework for HIST-238, Technology &amp; Society. handed in late,',
    'sorry Dr Okonkwo. i have put it on my geocities so the seminar can read it,',
    'and honestly because the footnotes would not fit on the paper copy. — Priya,',
    '4 March</small></p>',
    '<p class="fs-epi">"There is no reason for any individual to have a computer in',
    'their home." — attributed to Ken Olsen of DEC, 1977. he later said he was',
    'misquoted. he was still wrong.</p>',
    '<hr>',
    '<p>This is the short version of a twenty-year story: from a kit you soldered on',
    'the kitchen table to a beige box your parents bought at Dixons with Windows 95',
    'already on it. I have split it into eras. Most of them have a fuller page',
    'somewhere on this ring if you want the detail, and I have linked the two I lean',
    'on hardest.</p>',
    '<h2>1. The kit era (1975 to 1977)</h2>',
    '<p>It starts with the ALTAIR 8800, on the cover of <i>Popular Electronics</i> in',
    'January 1975. MITS in Albuquerque, Ed Roberts, an Intel 8080 running at 2MHz,',
    'and 256 bytes of memory. No screen, no keyboard: you set the program with',
    'toggle switches on the front and read the answer off a row of red lights. It',
    'cost 439 dollars as a kit and it sold out. Two young men called Gates and Allen',
    'wrote a BASIC for it and founded a company on the proceeds. The full story is',
    'at <a href="altair-8800.geocities.ws">altair-8800.geocities.ws</a>, which is',
    'better than my paragraph.</p>',
    '<img class="indie-pic" src="assets/media/web/home/altair-01.jpg" alt=""><span class="indie-cap">Where it began, the Altair 8800 (photo: Tim Colegrove, CC BY-SA 4.0)</span>',
    '<p>The point of the kit era is that a computer was a thing hobbyists BUILT and',
    'shared, passed round a club, argued over. It was not yet a product you bought',
    'finished. That was about to change.</p>',
    '<h2>2. The 1977 trinity</h2>',
    '<p>Three machines arrived in one year that you could take home and switch on:',
    'the Apple II, the Commodore PET, and the Tandy TRS-80. The Apple II was the',
    'clever one, a 6502 at 1MHz, colour graphics from a trick of Wozniak’s, and',
    'in 1979 it got VisiCalc, the spreadsheet that made businesses buy it. The PET',
    'had a horrible little chiclet keyboard and a monitor built in. The TRS-80, a',
    'Z80, sold in every Radio Shack in America and got called the "Trash-80" by',
    'people who owned the other two.</p>',
    '<div class="fs-aside"><p>A note on the 6502. It was a 25-dollar chip when its',
    'rivals cost six times that, and it ended up inside the Apple II, the PET, the',
    'Atari machines, the BBC Micro, the Commodore 64 and the Nintendo. Half this',
    'essay runs on one cheap processor designed by Chuck Peddle. Cheapness is a',
    'design decision, and it decided a lot.</p></div>',
    '<h2>3. The 8-bit boom (1981 to 1985)</h2>',
    '<p>This is the big one, the years when the machine came into ordinary houses. In',
    'Britain the ZX Spectrum (Sinclair, 1982, a Z80 at 3.5MHz, 48K, a rubber',
    'keyboard that felt like dead skin) went to war with the BBC Micro (Acorn, in',
    'every school) and later the Amstrad CPC. In America the Commodore 64 (1982, the',
    'SID sound chip, 64K) outsold everything ever made. You loaded games off cassette',
    'and waited, and waited. A tiny sample of what a session looked like:</p>',
    '<pre>LOAD ""\nPress PLAY on tape\n... (four minutes of screeching) ...\nR: Tape loading error</pre>',
    '<p>Everyone my mum’s age who owned one remembers that last line.</p>',
    '<h2>4. The 16-bit machines (1984 to 1990)</h2>',
    '<p>Then the Motorola 68000 arrived and everything got a mouse. The Macintosh',
    '(1984, 128K, too little of it) sold the graphical interface to the public. The',
    'Commodore Amiga (1985) had custom chips called Agnus, Denise and Paula and could',
    'do things with sound and video that looked like the future. The Atari ST had',
    'MIDI ports and moved into recording studios. People argued about Amiga versus ST',
    'for years, mostly on playgrounds.</p>',
    '<img class="indie-pic" src="assets/media/web/home/ibmpc-01.jpg" alt=""><span class="indie-cap">Where it settled, the IBM PC (photo: Rama and Musee Bolo, CC BY-SA 2.0 FR)</span>',
    '<h2>5. The beige box wins (1981 to 1995)</h2>',
    '<p>Quietly, off to one side, IBM had shipped the PC in 1981: an Intel 8088, an',
    'open design built from parts anyone could buy, and DOS licensed from Microsoft',
    'in a deal that let Microsoft sell it to everyone else too. Compaq copied the',
    'one secret part in a clean room, the clones flooded in, and the ugly cloneable',
    'committee-built machine ate the market the elegant closed machines thought they',
    'owned. By 1995, with Windows 95 and a CD-ROM drive, the beige box had taken the',
    'home as well. The uncomfortable version of that argument is laid out at',
    '<a href="the-beige-box.geocities.ws">the-beige-box.geocities.ws</a>, and it is',
    'worth reading even if you do not want it to be true.</p>',
    '<hr>',
    '<p>What I take from all this, for the essay: the machine that won was rarely the',
    'best one. It was the cheapest, or the most open, or the one with the killer app,',
    'or the one your school happened to buy. If you want to see the craft that the',
    'winners left behind, the demoscene is still writing new work for these old chips',
    'at <a href="demoscene.geocities.ws">demoscene.geocities.ws</a>, and the bedroom',
    'coders who started it kept a ring going at',
    '<a href="bedroom-coders-ring.geocities.ws">bedroom-coders-ring</a>.</p>',
    '<p>&nbsp;</p>',
    '<h2>Bibliography (rough, will tidy for the final)</h2>',
    '<p><small>Campbell-Kelly, M. and Aspray, W. <i>Computer: A History of the',
    'Information Machine</i>, 1996. the sober one.<br>',
    'Freiberger, P. and Swaine, M. <i>Fire in the Valley</i>, 1984. all the',
    'personalities, a bit gossipy, i liked it.<br>',
    'Tomczyk, M. <i>The Home Computer Wars</i>, 1984 (i think). Commodore from the',
    'inside, cited more properly on the wars page.<br>',
    'Veit, S. <i>Stan Veit’s History of the Personal Computer</i>, 1993.<br>',
    'the Popular Electronics Jan 1975 cover (from a scan, so no page no.).<br>',
    'Ceruzzi, P. <i>A History of Modern Computing</i>. note to self, GET THE',
    'YEAR, library copy was out.</small></p>',
    '<hr>',
    '<p><small>counter: 00147 · best viewed at 800x600 · under construction, the',
    '16-bit bit needs more · last updated 4 March</small></p>',
    '<p><small>',
    '[ <a href="home-computers-ring.geocities.ws">Home Computers Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The home computer wars: reading-group notes ----------------------------

const WARS = P('the-home-computer-wars.geocities.ws', 'THE WARS',
  'THE HOME COMPUTER WARS // reading-group notes (the 1983 crash)', [
    '<!--bg:eightbit-->',
    '<h1>THE HOME COMPUTER WARS</h1>',
    '<p><small>notes from the Tuesday reading group at the hackspace. this month we',
    'read Michael Tomczyk’s <i>The Home Computer Wars</i> (1984), his insider',
    'account of Commodore, alongside whatever we could find on the 1983 crash. six of',
    'us, two pizzas, one argument that ran to closing. — kept by the note-taker</small></p>',
    '<hr>',
    '<p>The short story the book tells: between roughly 1982 and 1984 the American',
    'home computer makers cut their prices until most of them bled to death. The man',
    'holding the knife was Jack Tramiel of Commodore, whose motto was "business is',
    'war" and who meant it. His page is at',
    '<a href="jack-tramiel.geocities.ws">jack-tramiel.geocities.ws</a> and it does not',
    'soften him.</p>',
    '<h2>What the group agreed on</h2>',
    '<p>Commodore owned its own chip factory. It had bought MOS Technology, the people',
    'who made the 6502, so when everyone else was paying for their processors',
    'Commodore was paying itself. That is how the VIC-20 and then the Commodore 64',
    'could keep dropping in price while still turning a profit. The 64 started around',
    '595 dollars and was under 200 within about two years. Tramiel could sell at a',
    'price that would ruin anyone who had to buy their chips on the open market.</p>',
    '',
    '<p>Texas Instruments tried to fight him with the TI-99/4A and got it wrong. TI',
    'made chips too, so it thought it could win a price war, but its machine was',
    'awkwardly built and TI ended up selling it below cost to keep pace. It lost',
    'about a hundred dollars on many machines and pulled out of the market in 1983,',
    'having lost a fortune. The book is not kind about the management there.</p>',
    '<h2>The British front</h2>',
    '<p>Over here the war had a different shape but the same casualties. Sinclair kept',
    'cutting corners to hit a price, which is a milder version of the same strategy,',
    'and it worked until it did not. His page is at',
    '<a href="sir-clive-sinclair.geocities.ws">sir-clive-sinclair.geocities.ws</a>. The',
    'also-rans, the Dragon 32 and the Oric and the Jupiter Ace, mostly drowned. When',
    'the American market crashed in 1983, it took the video game business down with',
    'it and spooked everyone, and the shops that had stacked machines to the ceiling',
    'suddenly could not shift them.</p>',
    '<h2>What we argued about</h2>',
    '<p>Half the room said the price war was good for buyers, because it put a real',
    'computer in a working family’s house for the first time, and that this was',
    'worth the wreckage. The other half said the wreckage WAS the point, that killing',
    'your rivals below cost is not competition, it is a rich company burning money to',
    'clear the field, and buyers only win until one firm is left standing. Nobody',
    'moved anybody. We left it there.</p>',
    '<blockquote class="fs-quote"><p>"Business is war. I don’t believe in',
    'compromising, I believe in winning." — Jack Tramiel, quoted more than once that',
    'evening</p></blockquote>',
    '<p>One open question for next time. Tramiel won the war and then, within months,',
    'was forced out of his own company in 1984. He went and bought Atari and started',
    'a fresh fight with the Amiga people. So did winning the price war actually win',
    'him anything he kept. We ran out of pizza before we settled it.</p>',
    '<hr>',
    '<p><small>counter: 00512 · best viewed at 800x600 · under construction, adding',
    'the crash figures when someone checks them · notes last typed up 9 Oct</small></p>',
    '<p><small>',
    '[ <a href="home-computers-ring.geocities.ws">Home Computers Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- What happened to the machines: reading-group notes ---------------------

const WHATHAPPENED = P('what-happened-to-them.geocities.ws', 'WHAT HAPPENED',
  'WHAT HAPPENED TO THE MACHINES // the shakeout, theme by theme', [
    '<!--bg:pc-->',
    '<h1>WHAT HAPPENED TO THE MACHINES</h1>',
    '<p><small>reading-group notes, second session on the survey. last time we read',
    'the rise, this time we tried to work out why only two of these families were',
    'still selling by the middle of the nineties. arranged by theme rather than by',
    'company, because the companies blur together once they start dying. — the',
    'note-taker again</small></p>',
    '<hr>',
    '<p>The bald fact we started from: of the dozens of incompatible home machines of',
    'the early eighties, by about 1995 the market was the IBM-compatible PC and, in a',
    'much smaller corner, the Apple Macintosh. Everything else had become a hobby.',
    'The argument for why the beige box won is at',
    '<a href="the-beige-box.geocities.ws">the-beige-box.geocities.ws</a>; here we',
    'just wanted to track the bodies.</p>',
    '<h2>Theme one: incompatibility killed them</h2>',
    '<p>Every 8-bit machine spoke its own language. A program for the Spectrum did not',
    'run on the Commodore 64, which did not run on the Amstrad. Software houses had to',
    'pick which machines to support and re-write everything for each. The PC clones,',
    'for all their ugliness, ALL ran the same DOS, so a program written once ran',
    'everywhere, and that pile of software got deeper every year until it was too deep',
    'to leave.</p>',
    '',
    '<h2>Theme two: the 16-bit machines were beaten by the boring one</h2>',
    '<p>The Amiga and the Atari ST were technically ahead of the PC for years. It did',
    'not save them. Commodore, still living off the 64, mismanaged the Amiga, could',
    'not decide whether it was a games machine or a workstation, and went bankrupt in',
    '1994. Atari faded out around the same time and ended up making a games console,',
    'the Jaguar, that did not sell. The better machine kept losing to the machine',
    'with the deeper software shelf and the business buyers behind it.</p>',
    '<h2>Theme three: the buyouts and the bankruptcies</h2>',
    '<p>We tried to make a rough list and it got grim quickly. Commodore, bankrupt',
    '1994, its brands sold on and passed around like a parcel. Atari, absorbed and',
    'renamed until nothing was left. Acorn, brilliant, British, and squeezed out of',
    'the general market, though it left behind the ARM processor that is now in every',
    'phone alive, so in a way Acorn won by dying. Sinclair sold his computer business',
    'to Amstrad in 1986 and that was that. Tandy stopped making its own line. Even IBM',
    'lost control of the standard it had created, because the clones did not need IBM',
    'any more.</p>',
    '<blockquote class="fs-quote"><p>"The machines did not so much fail as get',
    'outlived by a format." — one of us, trying to sum it up, and the rest more or',
    'less nodded</p></blockquote>',
    '<h2>Where they went instead</h2>',
    '<p>They did not vanish, they moved rooms. The dead machines became the',
    'retrocomputing hobby, kept running by people who love them, and that is a happier',
    'page than this one: see <a href="retro-hobby.geocities.ws">retro-hobby.geocities.ws</a>.',
    'A machine with no shops and no software house behind it can still be the most',
    'alive thing in someone’s spare room.</p>',
    '<h2>What we argued about</h2>',
    '<p>Whether "best" ever mattered at all, or whether it was always going to be',
    'about compatibility and money and nothing else. The romantics in the group hated',
    'that idea. The engineers in the group had watched it happen at work and were not',
    'surprised. We agreed to disagree and to read the retro page for next week.</p>',
    '<hr>',
    '<p><small>counter: 00330 · best viewed at 800x600 · under construction, the',
    'bankruptcy dates need a proper check · notes last typed up 23 Oct</small></p>',
    '<p><small>',
    '[ <a href="home-computers-ring.geocities.ws">Home Computers Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The retrocomputing hobby: a love letter (personal fan) -----------------

const RETRO = P('retro-hobby.geocities.ws', 'RETRO HOBBY',
  'THE RETROCOMPUTING HOBBY // keeping the dead machines running', [
    '<!--bg:people-->',
    '<h1>THE RETROCOMPUTING HOBBY</h1>',
    '<p><small>a love letter, kept by someone with four working machines older than',
    'they are and a soldering iron that is always warm. this is not nostalgia,',
    'exactly. it is closer to keeping an old car on the road because you like the way',
    'it drives. — Col</small></p>',
    '<hr>',
    '<p>People ask why. The machines are slow, the games are simple, the whole lot',
    'fits in an emulator on a phone. Why keep the actual plastic and silicon alive.',
    'Here is the real answer: because the thing in front of you is the thing itself,',
    'not a picture of it, and there is a pleasure in a 6502 at 1MHz doing exactly what',
    'it did in 1982 and not one instruction more.</p>',
    '<h2>Recapping, the first rite</h2>',
    '<p>The commonest job is recapping. The electrolytic capacitors in these machines',
    'are forty years old and they leak, and the leak eats the circuit board underneath.',
    'You desolder the old ones, clean the mess, and fit fresh capacitors, and a',
    'machine that was dead comes back. There is a particular smell to an Amiga power',
    'supply that has been left too long, and a particular joy in hearing the disk',
    'drive knock and the screen come up after you have fixed it.</p>',
    '',
    '<h2>Emulation, and the argument about it</h2>',
    '<p>Emulators are wonderful and I will not hear otherwise. A modern PC can pretend',
    'to be a Spectrum, a C64, an Amiga, all of them, cycle for cycle. It saves the',
    'software from rotting on cassettes that no longer read. But the purists say the',
    'feel is gone: the rubber keys under your fingers, the CRT glow, the loading',
    'stripes, the weight of the thing. Both sides are right. I run emulators to play',
    'and keep the real machines to love, and I do not think that is a contradiction.</p>',
    '<blockquote class="fs-quote"><p>"An emulator preserves the software. A collector',
    'preserves the machine. You need both, and neither will admit it." — overheard at',
    'a swap meet, written on the back of my hand</p></blockquote>',
    '<h2>The people who still write new code</h2>',
    '<p>Here is the part that surprises outsiders. People are still writing NEW',
    'programs for these computers. New games come out for the Commodore 64 every year,',
    'on cartridge and cassette, made with more skill than the old ones because the',
    'coders have decades of practice now. And the demoscene never left: coders still',
    'fight the SID chip and the Amiga’s Agnus and Denise to pull off effects the',
    'machines were never meant to do, and release them at parties. Start at',
    '<a href="demoscene-home.geocities.ws">demoscene-home.geocities.ws</a> if you have',
    'never seen a modern C64 demo, and clear your evening.</p>',
    '<h2>The collectors</h2>',
    '<p>We are a soft-hearted lot. We rescue machines from skips and lofts and house',
    'clearances, we photograph the serial numbers, we hunt the one missing key for a',
    'Spectrum, we pay too much for a boxed one and pretend to our partners that we did',
    'not. If you want to know how the whole story fits together, the survey is at',
    '<a href="a-history-of-home-computers.geocities.ws">a-history-of-home-computers.geocities.ws</a>,',
    'and it is better organised than my shelves.</p>',
    '<p>&nbsp;</p>',
    '<p>Why does it matter now, with newer machines going dark around us. Because a',
    'machine you can open, understand, and repair on your own kitchen table is a rare',
    'thing to hold on to, and we intend to hold on to these. Come and solder',
    'something.</p>',
    '<hr>',
    '<p><small>counter: 00688 · best viewed at 800x600 · under construction forever,',
    'like the machines · last updated 15 Nov</small></p>',
    '<p><small>',
    '[ <a href="home-computers-ring.geocities.ws">Home Computers Ring</a> ]<br>',
    'ring member, and proud. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Sinclair vs Acorn: academic summary ------------------------------------

const SINCLAIRACORN = P('sinclair-vs-acorn.geocities.ws', 'SINCLAIR v ACORN',
  'SINCLAIR vs ACORN // the Cambridge rivalry', [
    '<!--bg:people-->',
    '<h1>SINCLAIR vs ACORN</h1>',
    '<p><small>a clean summary of the Cambridge rivalry for anyone coming to it fresh.',
    'no hero-worship, both firms did remarkable and foolish things. kept as a',
    'reference page.</small></p>',
    '<hr>',
    '<p>Two companies, a mile apart in Cambridge, defined British home computing in the',
    'early 1980s, and they defined it by opposing philosophies. Sinclair Research cut',
    'every corner to hit the lowest possible price. Acorn Computers over-engineered,',
    'built to last, and charged accordingly. The rivalry was personal: Acorn was',
    'founded in 1978 by Chris Curry and Hermann Hauser, and Curry had previously',
    'worked for Clive Sinclair.</p>',
    '<h2>The two philosophies in hardware</h2>',
    '<p>The Sinclair approach is the ZX Spectrum (1982): a Z80 at 3.5MHz, 16K or 48K,',
    'a one-piece rubber keyboard, colour with the notorious attribute clash, cassette',
    'loading, and a price of 125 pounds for the 16K model that undercut everything.',
    'Clever, cheap, and fragile. His page is at',
    '<a href="sir-clive-sinclair.geocities.ws">sir-clive-sinclair.geocities.ws</a>.</p>',
    '<img class="indie-pic" src="assets/media/web/home/sinclair-01.jpg" alt=""><span class="indie-cap">Sir Clive Sinclair (photo: public domain)</span>',
    '<p>The Acorn approach is the BBC Micro (1981): also a 6502-based machine, but',
    'built like a tank, with a proper keyboard, generous expansion, and the finest',
    'BASIC of the era, BBC BASIC, which included an inline assembler so a schoolchild',
    'could drop from BASIC into 6502 machine code and back. It cost far more, around',
    '335 pounds for the Model B, and it was worth it.</p>',
    '<h2>The BBC contract, the turning point</h2>',
    '<p>In 1981 the BBC launched a Computer Literacy Project and needed a machine to',
    'carry its name into every school. Both firms wanted the contract. Acorn won it,',
    'to a tight and famous deadline, and the "BBC Micro" went into British classrooms',
    'for a decade. Sinclair lost it, and never forgave it, and sold to the schools’',
    'poorer cousins, the homes, in far greater numbers but at far lower margins.</p>',
    '<h2>The two roads out</h2>',
    '<p>The rivalry produced two very different legacies. Sinclair spent his profits on',
    'the flat-screen pocket television and then the C5, an electric trike that became a',
    'national joke in 1985 and badly damaged his reputation. Acorn, needing a faster',
    'processor and finding nothing on the market it liked, designed its own: the Acorn',
    'RISC Machine, first shipped in the Archimedes in 1987. That processor, later',
    'renamed and spun out as ARM, is now in almost every mobile phone on the planet.',
    'The engineer chiefly behind it, Sophie Wilson, who had also written BBC BASIC, has',
    'a page at <a href="sophie-wilson.geocities.ws">sophie-wilson.geocities.ws</a>.</p>',
    '<h2>A short critical note</h2>',
    '<p>It is tempting to read this as a simple morality tale, the corner-cutter',
    'punished and the careful engineer rewarded. That is too neat. Sinclair’s',
    'cheapness put a computer into hundreds of thousands of ordinary British homes that',
    'could never have afforded a BBC Micro, and much of the British games industry grew',
    'out of those bedrooms. Acorn’s over-engineering nearly priced it out of',
    'existence more than once and it survived on the school contract and a lucky bet on',
    'a processor. Each firm’s vice was the flip side of its virtue.</p>',
    '<hr>',
    '<p><small>counter: 00274 · best viewed at 640x480 · a reference page, corrections',
    'welcome · last updated 2 Dec</small></p>',
    '<p><small>',
    '[ <a href="home-computers-ring.geocities.ws">Home Computers Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const HOME_H = [HISTORY, WARS, WHATHAPPENED, RETRO, SINCLAIRACORN];
