// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// LIT_B — the Russian novel.
//
// Pages a reader made about the Russians: book-reading notes on The Brothers
// Karamazov (the showpiece); an academic summary of Tolstoy; a book-club's
// minutes on Chekhov; a fan shrine to Gogol; a student's coursework on
// Turgenev; and a write-up of a talk on Pushkin. The novels, characters, dates
// and techniques are real; the enthusiasms and the marginal notes are the
// readers' own.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Dostoevsky: book-reading notes on The Brothers Karamazov (SHOWPIECE) ---

const DOSTOEVSKY = P('dostoevsky.geocities.ws', 'DOSTOEVSKY',
  'READING THE BROTHERS KARAMAZOV // notes as I go', [
    '<!--bg:lit-russia-->',
    '<h1>Reading The Brothers Karamazov</h1>',
    '<p><small>notes kept while working through the Garnett translation over a',
    'winter, a chapter or two a night, written up the next morning before the',
    'thread of it went. not a review. more a logbook. — kept by a reader in the',
    'north</small></p>',
    '<p class="fs-epi">Verily, verily, I say unto you, Except a corn of wheat fall',
    'into the ground and die, it abideth alone: but if it die, it bringeth forth',
    'much fruit.<br>— the epigraph Dostoevsky set at the front, John 12:24</p>',
    '<hr>',
    '<p>The last novel, published in 1880, serialised across two years in <i>The',
    'Russian Messenger</i> before it was a book, and he died a few months after he',
    'finished it. It is the biggest thing he made and it holds everything he had',
    'been circling for thirty years: the murder, the faith, the doubt, the courtroom,',
    'the children. A father killed and four sons who each in a different way wanted',
    'him dead. Start with the family, because the whole novel is the family.</p>',
    '<pre>',
    'THE KARAMAZOVS',
    '',
    'Fyodor Pavlovich Karamazov  (the father, a buffoon and a sensualist)',
    '   |',
    '   +-- by Adelaida Ivanovna (first wife) ....... DMITRI  "Mitya"',
    '   |        the soldier, all passion and honour, ruined by money and Grushenka',
    '   |',
    '   +-- by Sofya Ivanovna (second wife) ......... IVAN',
    '   |        the intellectual, "everything is permitted", the Grand Inquisitor',
    '   |    ..................................... ALEXEI  "Alyosha"',
    '   |        the novice, the heart of the book, Zosima\'s boy',
    '   |',
    '   +-- (reputed, unacknowledged) ............... SMERDYAKOV',
    '            son of "stinking Lizaveta", the servant, the lackey with the falling',
    '            sickness, the one who actually does it',
    '',
    'Around them: Grushenka and Katerina Ivanovna (the two women), the elder',
    'Zosima (Alyosha\'s teacher), and the boys of the town led by Kolya Krasotkin.',
    '</pre>',
    '<p>Four sons and a fifth who is not counted, and the book asks over and over',
    'who is guilty. The law says Dmitri. The truth is Smerdyakov did the deed. But',
    'the deeper charge lands on Ivan, whose clever talk gave the servant permission,',
    'and by the end nobody in the book is quite innocent of the wish. Dostoevsky',
    'wanted exactly that spread of guilt.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/dostoevsky-01.jpg" alt=""><span class="indie-cap">Fyodor Dostoevsky, by Vasily Perov (public domain)</span>',
    '<p class="fs-pull">If there is no God, then everything is permitted.</p>',
    '<p>That line is the engine. It is Ivan\'s idea, carried out the window by',
    'Smerdyakov, who took the clever man at his word and did the thing the clever',
    'man only thought. Ivan never says the sentence quite so neatly in the text,',
    'and I keep having to remind myself of that, but it is the whole argument of',
    'him in a breath, and the novel spends its length testing it to destruction.</p>',
    '<hr>',
    '<p><b>The Grand Inquisitor</b></p>',
    '<p>The centre of the book, and the thing people read even when they read',
    'nothing else. Ivan tells Alyosha a poem he has made up. Christ comes back to',
    'earth in Seville during the Inquisition, and the old Cardinal has him arrested',
    'and comes to his cell at night to explain why he must be burned. The charge is',
    'astonishing: you gave men freedom, and freedom is more than they can bear, so',
    'we have taken it back from them and given them bread and mystery and someone to',
    'obey, and they are happier. Christ says nothing the whole time. At the end he',
    'kisses the old man. It is the most powerful case against faith ever written,',
    'and it was written by a believer, on purpose, to be that strong. He said in a',
    'letter he was afraid he had made the atheism too convincing.</p>',
    '<p class="fs-quote">"Each of us is guilty before everyone for everyone, and I',
    'more than any." <br>— the elder Zosima, giving back the answer the Inquisitor',
    'never gets</p>',
    '<p>Zosima is the reply to Ivan, and he is a quieter voice, which is the risk',
    'Dostoevsky took. Against the brilliant argument for despair he set an old monk',
    'saying love people, take the guilt of the world on yourself, water the earth',
    'with your tears. Whether it holds up against the Inquisitor is the question you',
    'carry out of the book. He knew a shout does not beat an argument. He wrote it',
    'anyway.</p>',
    '<hr>',
    '<p><b>POLYPHONY — why nobody in here sounds like the author</b></p>',
    '<p>The Russian critic Mikhail Bakhtin gave this the name that stuck, in',
    '<i>Problems of Dostoevsky\'s Poetics</i>. He called the novels POLYPHONIC, many',
    'voiced, like a piece of music with several independent lines that do not',
    'resolve into one tune. In an ordinary novel the characters serve the author\'s',
    'single view of the world. In Dostoevsky, Bakhtin argued, the characters are',
    'free consciousnesses who really do disagree with their maker, and he does not',
    'settle the argument over their heads. Ivan gets the best lines against God and',
    'the author does not lean in to correct him. The atheist is allowed to win the',
    'round. That is the polyphony: a book that is an unfinished conversation, not a',
    'lecture with quotations.</p>',
    '<p class="fs-aside"><b>A note on the word.</b> Bakhtin also gave us',
    '<i>dialogism</i> and the idea that a self only exists in answering another',
    'self, and <i>unfinalisability</i>, the refusal to sum a person up and close the',
    'file on them. Handy words for a reading group. The short form: in these books a',
    'person is never finished, and neither is the argument.</p>',
    '<hr>',
    '<p><b>Where he came from — you cannot read the novels without this</b></p>',
    '<p>In 1849 Dostoevsky was arrested for belonging to the Petrashevsky Circle, a',
    'group of young men who met to read banned socialist books aloud. He was',
    'sentenced to death. They were taken to Semyonovsky Square, stood up in the',
    'cold in their shirts, the first three tied to the posts, and the order to aim',
    'given. Then a rider came with the reprieve that had been arranged all along.',
    'The whole execution was staged by the state to teach them a lesson. One of the',
    'condemned went mad on the spot. Dostoevsky went instead to four years of hard',
    'labour in Omsk, in Siberia, in chains, with a New Testament the only book he',
    'was allowed. He came out changed, and everything after carries the mark of a',
    'man who stood in front of the rifles and was given his life back as if by a',
    'trick.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/tolstoy-01.jpg" alt=""><span class="indie-cap">Leo Tolstoy (photo: Prokudin-Gorskii, public domain)</span>',
    '<p><b>The others, briefly, because they lead here</b></p>',
    '<p><i>Crime and Punishment</i> (1866) is the one to read first. Raskolnikov, a',
    'poor student in Petersburg, works out a theory that extraordinary men are',
    'permitted to step over the law for a higher end, and to test it on himself he',
    'takes an axe to a pawnbroker and her sister. The rest of the book is the theory',
    'meeting the fact of what he has done. It is Ivan\'s idea acted out by one man a',
    'decade before Ivan, and Raskolnikov cannot carry it, and confesses, and is',
    'sent to Siberia, where the last page begins to turn him back toward the living.</p>',
    '<p><i>Notes from Underground</i> (1864) is the short bitter one, the underground',
    'man talking straight at you from his hole, spiteful, sick, contradicting himself',
    'on purpose to prove a man is not a piano key that reason can play, that he will',
    'choose his own ruin just to show he is free. Modern in a way that is almost',
    'unfair. Read it and you see where the twentieth century got half its voice.</p>',
    '<p>Then <i>The Idiot</i> (1869) with Prince Myshkin, the good man loose in a bad',
    'world, and <i>Demons</i> (1872) on the revolutionaries and where their logic',
    'ends. But Karamazov gathers them all up. Finish here and go back to the others',
    'and they read like studies for it.</p>',
    '<hr>',
    '<p>Neighbours worth a click. Tolstoy, the other giant, the one they always set',
    'against him, is at <a href="tolstoy.geocities.ws">tolstoy.geocities.ws</a>, and',
    'the two of them never met, which still seems impossible. And the writer they',
    'both came out of, in the line Dostoevsky himself is supposed to have said, is',
    'kept at <a href="gogol.geocities.ws">gogol.geocities.ws</a>. Belinsky championed',
    'him early and Nabokov could not stand him late, and both are worth knowing, but',
    'those are arguments for another page.</p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
    '<p><small>counter: 03219 · best viewed at 800x600 · this corner is under',
    'construction, the Demons notes are still coming · last updated 14 Dec · logged',
    'by a reader who should have been asleep</small></p>',
  ]);

// ---- Tolstoy: academic summary ----------------------------------------------

const TOLSTOY = P('tolstoy.geocities.ws', 'TOLSTOY',
  'Leo Tolstoy: an overview // the two great novels and after', [
    '<!--bg:lit-russia-->',
    '<h1>Leo Tolstoy: an overview</h1>',
    '<p><small>a summary page, compiled for a survey course and left up afterwards.',
    'corrections welcome to the address at the foot. sources listed where I could',
    'find them.</small></p>',
    '<hr>',
    '<p>Lev Nikolayevich Tolstoy (1828&ndash;1910) is, with Dostoevsky, one of the',
    'two names the nineteenth-century Russian novel is usually reduced to, and the',
    'contrast between them is a critical commonplace worth stating once and then',
    'setting aside. Where Dostoevsky works by fever, crisis and the confessional',
    'voice, Tolstoy works by breadth, daylight and an apparently godlike calm, a',
    'narrator who seems to see everything at once and to weigh it fairly. The two',
    'never met. Tolstoy was born to the old landed aristocracy at Yasnaya Polyana,',
    'the estate he lived and wrote and is buried on, and the land is never far from',
    'the work.</p>',
    '<p class="fs-quote">"All happy families are alike; each unhappy family is',
    'unhappy in its own way." <br>— the opening sentence of Anna Karenina</p>',
    '<hr>',
    '<p><b>War and Peace (1869)</b></p>',
    '<p>The book people mean when they mean a long book. It follows several noble',
    'families, the Bolkonskys, the Rostovs, the Bezukhovs, through the Napoleonic',
    'wars and the French invasion of 1812, and its true subject is how the huge',
    'public event and the small private life run through each other. Pierre Bezukhov',
    'blunders toward meaning, Prince Andrei looks for glory and finds the sky over',
    'Austerlitz instead, Natasha Rostova grows up across the length of it. Tolstoy',
    'refused to call it a novel. He was right that it is not quite one.</p>',
    '<p>Threaded through the story is a THEORY OF HISTORY, argued openly in the',
    'digressions and hammered home in a second epilogue that many readers skip.',
    'Tolstoy attacks the great-man account of events. Napoleon does not move history,',
    'he is carried by it, a figure who imagines he steers while the real motion is',
    'the sum of countless small actions by people who cannot see the whole. History',
    'is made by everyone and commanded by no one. It is the most argued-over part of',
    'the book, and the part most like the later Tolstoy pushing through.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/tolstoy-01.jpg" alt=""><span class="indie-cap">Leo Tolstoy (photo: Prokudin-Gorskii, public domain)</span>',
    '<p><b>Anna Karenina (1878)</b></p>',
    '<p>Serialised through the mid 1870s and the more shapely of the two. It runs on',
    'two tracks that barely touch. Anna, married to the cold official Karenin, falls',
    'for the officer Vronsky, leaves husband and standing for him, and is destroyed',
    'by a society that will forgive the affair but not the honesty, until the train',
    'at the end. Against her runs Konstantin Levin, the landowner who works his own',
    'fields, courts and wins Kitty, and gropes his way toward a faith he can live',
    'by. Levin is Tolstoy in all but name, down to the estate and the doubt, and the',
    'novel gives him the quiet ending it takes from Anna.</p>',
    '<hr>',
    '<p><b>The late conversion</b></p>',
    '<p>Around 1880, at the height of his fame, Tolstoy fell into the spiritual',
    'crisis he set down in <i>A Confession</i> (1882): a rich, celebrated, healthy',
    'man who could not answer why he should not kill himself, and who climbed out by',
    'way of a stripped-down Christianity of his own making. What followed was decades',
    'of a different Tolstoy, the moralist and reformer, who preached non-resistance',
    'to evil, renounced private property and rank, and in <i>What Is Art?</i> (1897)',
    'came close to disowning his own two masterpieces as the amusements of the idle',
    'rich. He kept writing fiction, the terrible clear late stories like <i>The Death',
    'of Ivan Ilyich</i> and <i>Hadji Murat</i>, but under protest against himself. He',
    'died in 1910 at a remote railway station, having fled his home and his marriage',
    'at eighty-two, and the running away was the last argument of his life.</p>',
    '<p>His non-resistance passed directly to Gandhi, who corresponded with him, and',
    'through Gandhi to a century of non-violent resistance, so the reformer\'s reach',
    'in the end outran the novelist\'s. That is a debt usually left out of the',
    'literary summary and it should not be.</p>',
    '<hr>',
    '<p>See also the other giant, at',
    '<a href="dostoevsky.geocities.ws">dostoevsky.geocities.ws</a>, who is everything',
    'Tolstoy is not, and the doctor with the lighter touch and the shorter form at',
    '<a href="chekhov.geocities.ws">chekhov.geocities.ws</a>, who admired Tolstoy',
    'this side of idolatry and still went his own quiet way.</p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
    '<p><small>hits: 01704 · best viewed at 800x600 · compiled for a second-year',
    'survey · last updated 2 Nov</small></p>',
  ]);

// ---- Chekhov: reading-group minutes -----------------------------------------

const CHEKHOV = P('chekhov.geocities.ws', 'CHEKHOV',
  'The Tuesday Group reads Chekhov // minutes', [
    '<!--bg:lit-russia-->',
    '<h1>The Tuesday Reading Group: Chekhov</h1>',
    '<p><small>minutes of three meetings, kept by whoever had the biro. we read the',
    'stories one month and the plays the next and then had an argument about the gun,',
    'which is minuted below. eight of us, plus the two who only came for the wine.</small></p>',
    '<hr>',
    '<p><b>Meeting one: the short stories.</b> We agreed to start with the stories',
    'because they are where he is himself and where he changed the form for everyone',
    'after. Anton Chekhov (1860&ndash;1904) wrote hundreds of them, first for money',
    'and fast, then slower and deeper. We read <i>The Lady with the Little Dog</i>,',
    '<i>Ward No. 6</i>, <i>Gooseberries</i> and <i>The Bishop</i>. What everyone kept',
    'saying: nothing happens, and everything happens. He leaves out the big scene you',
    'expect, the confession or the death or the reconciliation, and gives you the',
    'ordinary evening on either side of it, and somehow the missing scene is louder',
    'for being missing. Marjorie called it the art of what gets left out. We let that',
    'stand.</p>',
    '<p>The other thing: no verdict. He does not tell you who is right. He shows the',
    'schoolteacher and the drunk and the bishop each from inside, with sympathy, and',
    'then steps back. Somebody quoted his own line, that the writer\'s job is to state',
    'the question correctly, not to answer it. Which annoyed Peter, who wanted an',
    'answer. Noted for the record that Peter always wants an answer.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/chekhov-01.jpg" alt=""><span class="indie-cap">Anton Chekhov (public domain)</span>',
    '<p><b>Meeting two: the plays.</b> We did <i>The Seagull</i> (1896), <i>Uncle',
    'Vanya</i>, <i>Three Sisters</i> and <i>The Cherry Orchard</i> (1904, the last',
    'thing he finished). Same method as the stories, up on the stage. People do not',
    'have big scenes, they miss trains, drink tea, fail to say the thing, and the',
    'orchard gets sold while everyone talks about something else. The famous story:',
    '<i>The Seagull</i> was booed off on its first night in Petersburg and Chekhov',
    'swore off the theatre, and then Stanislavsky staged it again two years later at',
    'the new Moscow Art Theatre and it was a triumph, and the seagull became the',
    'company\'s emblem, which it still is. He kept insisting the plays were comedies.',
    'Stanislavsky kept staging them as tragedies. The group split four to four on who',
    'was right and moved to the pub.</p>',
    '<hr>',
    '<p><b>Meeting three: the argument about the gun.</b> This took the whole',
    'evening so it gets its own heading. The principle everyone half-remembers, now',
    'called CHEKHOV\'S GUN, comes from his letters and his advice to younger writers,',
    'and the cleanest version is roughly this:</p>',
    '<p class="fs-quote">"If in the first act you have hung a pistol on the wall,',
    'then in the following one it should be fired. Otherwise do not put it there." <br>',
    '— Chekhov, in a much-repeated piece of advice to a young playwright</p>',
    '<p>Everything on the stage must earn its place and pay off later. Nothing',
    'decorative, nothing that does not fire. Then Sandra pointed out the twist that',
    'makes it interesting, that Chekhov himself keeps hanging up guns that never go',
    'off, whole lives that never fire, and that the disappointment IS the effect. So',
    'the rule and the practice pull against each other, and we decided that the rule',
    'is for the machinery and the sadness is for the people, and left it there',
    'because it was late.</p>',
    '<hr>',
    '<p><b>The other thing to know.</b> He was a doctor all along. Qualified in',
    'medicine, treated the poor for nothing, ran clinics through the cholera, and',
    'made the brutal census journey to the penal colony on Sakhalin Island and wrote',
    'the survey up as an indictment. His own line, that medicine was his lawful wife',
    'and literature his mistress, gets quoted to death, but it is true, and the',
    'clinician\'s eye, cool, exact, unsentimental about the body, is all over the',
    'writing. He died of the tuberculosis he had diagnosed in himself years before,',
    'at forty-four, in a German spa, and the famous detail is that he died calmly,',
    'having asked for a glass of champagne.</p>',
    '<hr>',
    '<p>Next month we cross back a generation to',
    '<a href="turgenev.geocities.ws">turgenev.geocities.ws</a>, the elder Chekhov',
    'quietly learned restraint from, and someone wants us to reread',
    '<a href="tolstoy.geocities.ws">tolstoy.geocities.ws</a> because Chekhov worshipped',
    'the man and argued with the preacher, and both should be on the table.</p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
    '<p><small>visitors: 00942 · best viewed at 800x600 · the Tuesday Group, meeting',
    'upstairs since \'96 · minutes last typed up 9 Oct</small></p>',
  ]);

// ---- Gogol: personal fan shrine ---------------------------------------------

const GOGOL = P('gogol.geocities.ws', 'GOGOL',
  'GOGOL!! the strangest of them all // a shrine', [
    '<!--bg:lit-russia-->',
    '<h1>GOGOL!!</h1>',
    '<p><small>my shrine to Nikolai Gogol, the funniest and the most frightening',
    'writer I have ever read, and I will not hear a word against him except the words',
    'he would have laughed at. put together over about a year of not being able to',
    'shut up about him. — Vera K.</small></p>',
    '<hr>',
    '<p>I came to Gogol (1809&ndash;1852) sideways, through a line everyone quotes',
    'and half misattributes, and I have never got over him. He is the one the whole',
    'Russian tradition points back to. There is a saying, usually put in Dostoevsky\'s',
    'mouth though nobody can quite pin it down, that the vicomte de Vogüé may have',
    'coined:</p>',
    '<p class="fs-pull">We have all come out of Gogol\'s Overcoat.</p>',
    '<p>And it is TRUE, that is the maddening thing. The pity for the small crushed',
    'clerk, the grotesque that tips into horror, the laughter that leaves a chill,',
    'all of it starts here. Let me tell you why he is the best.</p>',
    '<hr>',
    '<p><b>THE OVERCOAT (1842)</b> is where I would send anyone first. Akaky',
    'Akakievich is a copying clerk, the lowest of the low, a man who loves nothing in',
    'the world but the letters he transcribes. He saves and starves to buy a new',
    'overcoat, the one beautiful thing he will ever own, and on the first night he',
    'wears it out it is stolen, and nobody in the whole machine of the city will help',
    'him, and he dies of it. And THEN, and this is the Gogol turn, he comes back as a',
    'ghost stealing overcoats off the shoulders of the important. You laugh and then',
    'you are ashamed you laughed. I have read it maybe ten times.</p>',
    '<p><b>DEAD SOULS (1842)</b> is the big one, the one he thought would be his',
    'masterpiece. The scheme is perfect and horrible: Chichikov, a smooth swindler,',
    'travels the provinces BUYING DEAD SERFS. Serfs were counted as "souls" and taxed',
    'on the last census until the next, so a landowner still paid on peasants who had',
    'died. Chichikov offers to take these dead souls, these names, off their books,',
    'and quietly builds a fortune of people who do not exist, mortgaging phantoms.',
    'Every landowner he visits is a different portrait of the rot, the miser, the',
    'bully, the sugary bore, the sentimental fraud. It is a whole dead country drawn',
    'in ghosts.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/gogol-01.jpg" alt=""><span class="indie-cap">Nikolai Gogol (public domain)</span>',
    '<p><b>THE NOSE (1836)</b> because I have to. A man wakes up and his nose is',
    'gone, and then he meets it walking round Petersburg in a uniform higher-ranking',
    'than his own, and it will not admit it is a nose. That is the story. It is not',
    'explained and it is not a dream and Gogol does not care that you want it to make',
    'sense. Nobody wrote anything that strange again for a hundred years.</p>',
    '<hr>',
    '<p><b>THE PART THAT BREAKS MY HEART</b></p>',
    '<p>Gogol meant <i>Dead Souls</i> to be three parts, a Russian comedy in the old',
    'sense, going from the hell of part one up toward redemption. He wrote the second',
    'part. And then, under the sway of a harsh confessor and a religious dread that',
    'ate the last years of him, he decided the work was sinful, and he BURNED the',
    'manuscript of the second volume, days before he died in 1852. He was starving',
    'himself by then, in a kind of holy despair. A few charred chapters survived. We',
    'will never have the rest. The greatest of all the burned books, and he lit it',
    'himself.</p>',
    '<p class="fs-aside"><b>Do not forget the play.</b> <i>The Government Inspector</i>',
    '(1836) is the other masterpiece, a whole corrupt town mistaking a penniless',
    'nobody for the dreaded inspector from the capital and falling over themselves to',
    'bribe him. It is the funniest thing about fear and guilt ever staged, and',
    'apparently the Tsar himself watched it and said everyone had got what was coming,',
    'himself included.</p>',
    '<hr>',
    '<p>If you love him, go and see the two he fathered. The whole line of pity and',
    'crisis runs on to <a href="dostoevsky.geocities.ws">dostoevsky.geocities.ws</a>,',
    'who took the crushed clerk and gave him a soul that argues back. And the',
    'fountainhead, the one Gogol himself looked up to, the man who handed him the plot',
    'of both <i>Dead Souls</i> and <i>The Government Inspector</i>, is at',
    '<a href="pushkin.geocities.ws">pushkin.geocities.ws</a>. Yes, Pushkin gave Gogol',
    'the ideas. Go and thank him.</p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
    '<p><small>counter: 01288 · best viewed at 800x600 · under construction, the',
    'Petersburg Tales are getting their own page soon · last updated 21 Nov · made',
    'with love and dread by Vera K.</small></p>',
  ]);

// ---- Turgenev: student coursework -------------------------------------------

const TURGENEV = P('turgenev.geocities.ws', 'TURGENEV',
  'RUSS 214 essay // Turgenev and the nihilist', [
    '<!--bg:lit-russia-->',
    '<h1>Fathers and Sons: Bazarov and the Word Nihilist</h1>',
    '<p><small>RUSS 214, The Nineteenth-Century Russian Novel. essay 2 of 3. I am',
    'putting my coursework up in case it helps anyone else in the seminar, do not',
    'copy it, the marker knows this page exists. bibliography at the bottom, such as',
    'it is. — d.p., second year</small></p>',
    '<hr>',
    '<p>Ivan Turgenev (1818&ndash;1883) is the third name in the usual trio and the',
    'odd one out, the Westerniser, the one who lived half his life abroad, wrote a',
    'clean and elegant Russian, and looked at his own country with the eye of a man',
    'who had stood outside it. This essay is on his best-known novel, <i>Fathers and',
    'Sons</i> (1862), and on the word it launched.</p>',
    '<p><b>The argument.</b> Turgenev built the whole novel on the gap of one',
    'generation, the gentle idealistic fathers of the 1840s against the hard',
    'scientific sons of the 1860s, and put the whole quarrel into one character,',
    'Yevgeny Bazarov. Bazarov is a young medical man who believes only in what he can',
    'dissect. He calls himself a NIHILIST, a man who bows to no authority, takes no',
    'principle on trust, respects nothing that cannot be proved. He would rather know',
    'how a frog works than read a line of Pushkin. Turgenev did not invent the word',
    'but he made it burn, and after the novel it was everywhere, thrown at a whole',
    'generation of young Russian radicals, who then, in a twist Turgenev did not',
    'plan, adopted it and wore it with pride.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/turgenev-01.jpg" alt=""><span class="indie-cap">Ivan Turgenev, by Ilya Repin (public domain)</span>',
    '<p><b>Why it is a real novel and not a pamphlet.</b> The clever thing is that',
    'Turgenev does not let Bazarov win or lose cleanly. He gives him all the force,',
    'all the future, and then he does the cruel honest thing: he lets Bazarov fall in',
    'love, against his own creed, with a woman who will not have him, and the great',
    'scientific denier is left shaken by the one thing his theory has no room for. And',
    'then he dies, stupidly, of an infection caught cutting up a corpse, and dies',
    'bravely, and the novel closes on his old parents weeping at the country grave.',
    'Nobody came away satisfied. The radicals thought he had mocked the young; the',
    'reactionaries thought he had glorified them. Getting attacked from both sides is,',
    'I would argue, the proof he had drawn it fairly.</p>',
    '<p class="fs-epi">"We sit in the mud, my friend, and reach for the stars." <br>',
    '— a line often given to Turgenev, on the mixed business of being human</p>',
    '<p><b>The wider work.</b> Before the novels came <i>A Sportsman\'s Sketches</i>',
    '(1852), a set of quiet linked stories told by a gentleman out shooting who keeps',
    'meeting the serfs on the land, drawn as full human beings, and the book is',
    'credited with helping turn educated opinion against serfdom itself. It is said',
    'the future Tsar Alexander II read it and it moved him toward the emancipation of',
    '1861. A book of hunting sketches that helped free the serfs. That is a fact worth',
    'the whole essay.</p>',
    '<p>Turgenev spent his later decades in the West, in Baden-Baden and Paris, close',
    'to the singer Pauline Viardot for most of his life, friends with Flaubert and the',
    'French novelists, the great Russian abroad. He quarrelled bitterly with',
    'Dostoevsky, who put a cruel parody of him into <i>Demons</i>, the two men',
    'standing for the two directions Russia could face, out to Europe or back into',
    'itself. Turgenev faced out. It cost him at home and it is part of why he reads so',
    'clear.</p>',
    '<hr>',
    '<p><b>Bibliography (in progress, will fix the format before I submit)</b></p>',
    '<pre>',
    'Turgenev, I. - Fathers and Sons (1862) [the Norton, ed. w/ the essays]',
    'Turgenev, I. - A Sportsman\'s Sketches (1852)',
    'Berlin, I. - "Fathers and Children" (the lecture, in Russian Thinkers) <-- READ THIS',
    'seminar handout wk 4, "nihilism before the nihilists"',
    'that book by Frank on Dostoevsky, the chapter on the quarrel  [get full ref]',
    '</pre>',
    '<hr>',
    '<p>Cross-links for the seminar: the doctor-writer a generation on who learned',
    'Turgenev\'s restraint and out-wrote him in the short form is at',
    '<a href="chekhov.geocities.ws">chekhov.geocities.ws</a>, and the man he feuded',
    'with, his opposite in every way, is at',
    '<a href="dostoevsky.geocities.ws">dostoevsky.geocities.ws</a>.</p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
    '<p><small>hits: 00517 · best viewed at 800x600 · a student page, marks pending ·',
    'last updated 4 Mar · this site is under construction FOREVER apparently</small></p>',
  ]);

// ---- Pushkin: talk write-up -------------------------------------------------

const PUSHKIN = P('pushkin.geocities.ws', 'PUSHKIN',
  'Notes from the Pushkin talk // the fountainhead', [
    '<!--bg:lit-russia-->',
    '<h1>"The Sun of Russian Poetry": notes from Thursday\'s talk</h1>',
    '<p><small>write-up of the evening lecture at the literary society, given by a',
    'visiting translator whose name I did not catch clearly and will not risk',
    'spelling wrong. any errors below are mine, from scribbled notes at the back with',
    'a bad pen.</small></p>',
    '<hr>',
    '<p>The speaker began where every Russian begins, with the claim that Alexander',
    'Pushkin (1799&ndash;1837) is the fountainhead, the one from whom the whole',
    'literature flows, and that the loss for us who read him in translation is real,',
    'because more than any of the novelists he lives in the sound of the language,',
    'and the sound is the part that does not cross over. He is loved in Russia the way',
    'no writer is loved anywhere else, learned by heart, quoted in the street. The',
    'phrase used at his death, she said, was that the sun of Russian poetry had set.</p>',
    '<p><b>The novel in verse.</b> The talk centred on <i>Eugene Onegin</i>, written',
    'across the 1820s and finished in 1833, which is a full novel told entirely in',
    'rhymed verse. The bored young dandy Onegin, sick of the city, comes to the',
    'country; the shy, bookish Tatyana falls for him and writes him a letter pouring',
    'out her heart; he lectures her coldly and turns her down. Then out of boredom and',
    'spite he flirts with his friend Lensky\'s fiancee, Lensky challenges him, and in a',
    'duel Onegin kills the friend he never meant to harm. Years later he meets Tatyana',
    'again, now married and grand, and now HE is the one who loves and writes the',
    'letter, and now SHE, still loving him, refuses, because she will not betray her',
    'husband. The whole thing turns on that mirror, and it is heartbreaking, and the',
    'speaker said the ending is the most quietly moral in Russian literature.</p>',
    '<img class="indie-pic" src="assets/media/web/lit/pushkin-01.jpg" alt=""><span class="indie-cap">Alexander Pushkin, by Orest Kiprensky (public domain)</span>',
    '<p><b>The stanza.</b> The part I most wanted to get down. Pushkin built a',
    'special verse form for the book and used it almost all the way through, and it is',
    'now called the ONEGIN STANZA or the Pushkin sonnet. She put the shape on the',
    'board and I copied it:</p>',
    '<pre>',
    'THE ONEGIN STANZA',
    '',
    '14 lines, iambic tetrameter (four beats a line)',
    'rhyme scheme:   A b A b  C C d d  E f f E  g g',
    '',
    '  capitals = feminine rhyme (stress on the next-to-last syllable)',
    '  lower    = masculine rhyme (stress on the last)',
    '',
    'a quatrain (crossed), a quatrain (paired), a quatrain (enclosed),',
    'and a closing couplet that snaps it shut, often with a joke.',
    '</pre>',
    '<p>The speaker said the miracle is that it never feels like a cage. The verse',
    'runs as light and quick as talk, jumps from a broken heart to a shopping list to',
    'a swipe at a critic and back, and the form just carries it. She read a stanza in',
    'Russian first and you could hear the click of the final couplet even without the',
    'words. Vladimir Nabokov spent years translating it and arguing that it could not',
    'be truly translated, and produced a famously literal English version plus a',
    'commentary longer than the poem, which tells you something about the problem.</p>',
    '<p class="fs-quote">"I write to you. What more is there to say? / What more is',
    'there that I can add?" <br>— the opening of Tatyana\'s letter, in one of the',
    'English versions the speaker quoted</p>',
    '<hr>',
    '<p><b>The duel.</b> The talk ended, as it had to, on the terrible echo. Pushkin',
    'wrote a fatal duel into <i>Onegin</i>, and then in 1837 died in one himself. A',
    'campaign of poison-pen letters and court gossip about his wife drove him to',
    'challenge Georges d\'Anthes, a French officer in Russian service. They met by the',
    'Black River outside Petersburg in the January snow. Pushkin was shot in the',
    'stomach and died two days later in agony, at thirty-seven. The speaker\'s point',
    'was that he had rehearsed it on the page and walked into it anyway, and that the',
    'nation went into a mourning the authorities were frightened of. She said the',
    'other novels we read all stand on ground Pushkin cleared, and that he also wrote',
    'the drama <i>Boris Godunov</i>, the tales, and <i>The Bronze Horseman</i>, and',
    'that we should not let the verse novel eat the rest of him.</p>',
    '<hr>',
    '<p>She sent us onward to two who owe him directly. Gogol, whom Pushkin handed the',
    'plots of his two greatest works, is at',
    '<a href="gogol.geocities.ws">gogol.geocities.ws</a>, and the tradition of the big',
    'novel that grows from the ground Pushkin broke runs on to',
    '<a href="tolstoy.geocities.ws">tolstoy.geocities.ws</a>.</p>',
    '<p><small>[ <a href="literature-ring.geocities.ws">Literature Ring</a> ]</small></p>',
    '<p><small>counter: 00688 · best viewed at 800x600 · notes from the literary',
    'society, Thursday evenings, newcomers welcome · written up 17 Feb</small></p>',
  ]);

export const LIT_B = [DOSTOEVSKY, TOLSTOY, CHEKHOV, GOGOL, TURGENEV, PUSHKIN];
