// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH B — the calculus. Pages a student, a maths society and a couple of
// enthusiasts kept about the men who invented the calculus and the century that
// followed: Newton and the Principia, Leibniz and the notation that won, Euler
// the inexhaustible, Fermat in his margin, the quarrelsome Bernoullis, and
// Lagrange with his diagram-free mechanics. Dates, works and quarrels are real;
// the fandom is the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Newton: book-reading notes on the Principia (SHOWPIECE) ----------------

const NEWTON = P('isaac-newton.geocities.ws', 'NEWTON',
  'READING THE PRINCIPIA // fluxions, gravity, the quarrel', [
    '<!--bg:math-analysis-->',
    '<h1>Reading the Principia</h1>',
    '<p class="fs-epi"><small>"I do not know what I may appear to the world, but to',
    'myself I seem to have been only like a boy playing on the sea-shore."<br>',
    '— Isaac Newton</small></p>',
    '<p><small>notes kept while reading my way through the <i>Principia</i> a few',
    'pages a week, with the Motte translation open on one knee and Chandrasekhar',
    'on the other. this is a reading diary, not a lecture. corrections welcome.',
    '— a slow reader in the maths library</small></p>',
    '<hr>',
    '<p>The full title is <i>Philosophiae Naturalis Principia Mathematica</i>, the',
    'Mathematical Principles of Natural Philosophy, published in 1687 with Edmond',
    'Halley paying the printer out of his own pocket. Three books. The first two',
    'set out the motion of bodies, the third, the <i>System of the World</i>, turns',
    'the machinery on the heavens and gets the planets, the Moon, the tides and the',
    'comets out of a single law. Newton (1642&ndash;1727) had most of it worked out',
    'twenty years earlier, in the plague years of 1665 and 1666, the stretch he',
    'later called his <i>annus mirabilis</i>, when Cambridge shut and he went home',
    'to Woolsthorpe and did the calculus, the optics and the gravitation more or',
    'less at once.</p>',
    '<blockquote class="fs-quote"><p>"Every body continues in its state of rest, or',
    'of uniform motion in a right line, unless it is compelled to change that state',
    'by forces impressed upon it."</p><p><small>— the First Law, in Motte\'s',
    'translation</small></p></blockquote>',
    '<p>What surprised me first is how little of the book looks like the calculus.',
    'Newton found his results with what he called the method of FLUXIONS, his own',
    'calculus of quantities that flow, but he set the proofs out in the old',
    'language of Greek geometry, ratios and limits of vanishing arcs. He trusted',
    'the geometry to convince, and he may have wanted to keep the new method to',
    'himself a while longer. So the reader gets the classical dress and has to feel',
    'the calculus moving underneath it.</p>',
    '<img class="indie-pic" src="assets/media/web/math/newton-01.jpg" alt=""><span class="indie-cap">Isaac Newton, after Godfrey Kneller (public domain)</span>',
    '<p><b>Fluxions, and the notation nobody uses now</b></p>',
    '<p>A fluxion is a rate of change. If a quantity <i>x</i> flows in time, Newton',
    'writes its fluxion (what we would call the derivative with respect to time)',
    'with a dot above the letter, and the fluxion of that with two dots. The flowing',
    'quantity itself he called the fluent. The inverse operation, our integral, he',
    'handled through fluents and, in print, through a little prime mark. Leibniz,',
    'working independently over in Germany, chose the notation that actually',
    'survived. Here they are side by side, the same two ideas in two hands.</p>',
    '<pre>',
    '  idea                Newton (fluxions)      Leibniz (differentials)',
    '  ------------------  ---------------------  ------------------------',
    '  the quantity        x   (a fluent)         x',
    '  its rate of change  x&#775;   (a fluxion)         dx/dt',
    '  second rate         x&#776;                     d&sup2;x/dt&sup2;',
    '  the accumulation    x&#697;  (a fluent of x)     &#8747; x dt',
    '',
    '  "velocity is the fluxion of position; position is the fluent of velocity"',
    '        x&#775; = d x / d t              &#8747; x&#775; dt = x',
    '</pre>',
    '<p>Leibniz\'s dx and the long S of the integral read like an algebra you can',
    'push around on the page, and that is why the Continent, running with Leibniz,',
    'raced ahead through the eighteenth century while England, loyal to the dots,',
    'fell behind for the better part of a hundred years. The dot notation still',
    'lives in a corner of mechanics, where an overdot means "rate of change in',
    'time", but the daily calculus everyone learns is Leibniz\'s.</p>',
    '<p class="fs-pull">The apple is not a fairy tale, but it is not a bump on the',
    'head either. The idea was that the SAME force pulling the apple down keeps the',
    'Moon in its orbit.</p>',
    '<p><b>Universal gravitation</b></p>',
    '<p>The heart of Book III is one law that does not care whether it is looking at',
    'a falling apple or a falling Moon. Every two bodies pull on each other with a',
    'force along the line between them, proportional to each mass and falling off',
    'with the square of the distance.</p>',
    '<pre>',
    '        G m&#8321; m&#8322;',
    '  F  =  ---------            (an inverse-square law: double the distance,',
    '          r&sup2;               quarter the force)',
    '</pre>',
    '<p>From that plus the three laws of motion Newton derives Kepler\'s ellipses,',
    'the equal-areas rule, the 3/2 power law of the periods, the flattening of the',
    'Earth at the poles, the precession of the equinoxes and the tides. One page',
    'of the book was worth a working life to the man who wrote it and it does the',
    'work of a whole observatory.</p>',
    '<div class="fs-aside"><p><b>The quarrel with Leibniz.</b> Who invented the',
    'calculus? Newton had his fluxions by the mid 1660s but published late. Leibniz',
    'developed his differential calculus in the 1670s and published first, in 1684.',
    'For years it was cordial enough. Then the accusations of plagiarism began, the',
    'national presses took sides, and in 1712 the Royal Society convened a committee',
    'to judge the matter. The committee found for Newton. Newton was President of',
    'the Royal Society at the time, and it later emerged that he had drafted much of',
    'the supposedly impartial report himself. The modern verdict is the fair one:',
    'they invented it independently, Newton earlier, Leibniz better dressed. The',
    'bitterness poisoned the last years of both.</p></div>',
    '<img class="indie-pic" src="assets/media/web/math/leibniz-01.jpg" alt=""><span class="indie-cap">Gottfried Leibniz, by C. B. Francke (public domain)</span>',
    '<p><b>The other lives</b></p>',
    '<p>He held the Lucasian Chair at Cambridge, the professorship later associated',
    'with a great many famous names, from 1669. He poured years into alchemy and',
    'into unorthodox theology that he kept carefully hidden. And in 1696 he left',
    'Cambridge for London to become Warden, then Master, of the Royal Mint, where',
    'he ran the great recoinage and pursued clippers and counterfeiters with a',
    'prosecutor\'s zeal, sending several to the gallows. The man who weighed the',
    'planets spent his second career weighing coins.</p>',
    '<p>Where to go next in the ring. The other half of the quarrel is set out',
    'sympathetically at <a href="leibniz-calculus.geocities.ws">leibniz-calculus</a>,',
    'and the man who took the new calculus and did more with it than anyone,',
    'Leonhard Euler, is over at <a href="leonhard-euler.geocities.ws">leonhard-euler</a>.',
    'Halley, Hooke and Flamsteed turn up all through the story but have no page here',
    'yet.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01687 · best viewed at 800x600 · this reading diary is',
    'under construction, more chapters as i get to them · last updated 24 Mar</small></p>',
  ]);

// ---- Leibniz: academic summary ----------------------------------------------

const LEIBNIZ = P('leibniz-calculus.geocities.ws', 'LEIBNIZ',
  'Gottfried Wilhelm Leibniz and the calculus // a summary', [
    '<!--bg:math-analysis-->',
    '<h1>Leibniz and the Calculus</h1>',
    '<p><small>A short reference summary maintained for the reading ring. Neutral',
    'in tone, kept up to date, no fan mail. Sources on request.</small></p>',
    '<hr>',
    '<p>Gottfried Wilhelm Leibniz (1646&ndash;1716) was a lawyer, diplomat,',
    'librarian, philosopher and mathematician, born in Leipzig and for most of his',
    'career in the service of the House of Hanover. In mathematics he is remembered',
    'above all for the differential and integral calculus, developed in the 1670s',
    'and first published in 1684 in the journal <i>Acta Eruditorum</i>, in a paper',
    'whose Latin title is mercifully abbreviated to the <i>Nova Methodus</i>.</p>',
    '<p><b>The notation that won.</b> Leibniz thought hard about signs. He held that',
    'a well-chosen notation does part of the reasoning for you, and his calculus',
    'notation is the proof of it. He wrote the differential of a quantity as',
    '<i>dx</i>, the derivative as the quotient <i>dy/dx</i>, and the integral with',
    'an elongated S, from the Latin <i>summa</i>, standing for a sum of infinitely',
    'many infinitely thin strips.</p>',
    '<pre>',
    '   dy',
    '   --  = the ratio of two differentials   (a slope, a rate)',
    '   dx',
    '',
    '   &#8747; y dx = the sum of the strips y wide dx      (an area)',
    '',
    '   and the two are inverse:  d ( &#8747; y dx ) = y dx',
    '</pre>',
    '<p>This is essentially the notation a student learns today. Its virtue is that',
    'the symbols can be manipulated almost as if the differentials were ordinary',
    'quantities, so that the fundamental theorem of the calculus, that',
    'differentiation and integration undo one another, reads straight off the page.</p>',
    '<img class="indie-pic" src="assets/media/web/math/leibniz-01.jpg" alt=""><span class="indie-cap">Gottfried Leibniz, by C. B. Francke (public domain)</span>',
    '<p><b>Infinitesimals.</b> Leibniz reasoned with infinitely small quantities,',
    'the differentials, treated as smaller than any assignable magnitude yet not',
    'zero. Contemporaries, and later Bishop Berkeley in his sharp pamphlet <i>The',
    'Analyst</i>, mocked these as the "ghosts of departed quantities". The',
    'infinitesimal was not put on a rigorous footing until the nineteenth century',
    'reworked the calculus in terms of limits, and it was rehabilitated in its own',
    'right only in the twentieth, in Abraham Robinson\'s non-standard analysis.',
    'Leibniz used it with great success long before anyone could justify it.</p>',
    '<p><b>The priority dispute.</b> Leibniz and Isaac Newton arrived at the',
    'calculus independently, Newton earlier but publishing later, Leibniz publishing',
    'first and with the superior notation. The two camps fell into a bitter quarrel',
    'over precedence, in which a Royal Society committee found against Leibniz in',
    '1712. The consensus now credits both. The fuller account from the Newton side',
    'is set out at <a href="isaac-newton.geocities.ws">isaac-newton</a>.</p>',
    '<p><b>The universal characteristic.</b> Beyond the calculus, Leibniz dreamed of',
    'a <i>characteristica universalis</i>, a formal language in which every concept',
    'would be written in exact symbols, joined to a <i>calculus ratiocinator</i>, a',
    'method of computing with those symbols so that disputes could be settled by',
    'reckoning. "Let us calculate," he imagined two reasoners saying, and pick up',
    'their pens. It was a foreshadowing of formal logic and, some argue, of the',
    'idea of computation itself. His work on binary arithmetic and his stepped',
    'reckoning machine belong to the same ambition.</p>',
    '<p>The Bernoulli brothers of Basel were the first to seize on the Leibnizian',
    'calculus and drive it forward; see <a href="the-bernoullis.geocities.ws">the-bernoullis</a>.',
    'Newton is the natural companion page above.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hits: 00846 · best viewed at 800x600 · maintained for the',
    'Mathematicians Ring · last revised 8 Feb</small></p>',
  ]);

// ---- Euler: personal fan shrine ---------------------------------------------

const EULER = P('leonhard-euler.geocities.ws', 'EULER',
  'EULER!! the most prolific mathematician EVER', [
    '<!--bg:math-analysis-->',
    '<h1>Leonhard Euler!!</h1>',
    '<p><small>a shrine to the greatest and busiest mathematician who ever lived,',
    'by someone who has been slowly copying out the Basel problem proof by hand',
    'because it is that beautiful. read the whole page, there is a payoff. — v.</small></p>',
    '<hr>',
    '<p>Leonhard Euler (1707&ndash;1783), born in Basel, worked in St Petersburg and',
    'Berlin and then St Petersburg again, and produced so much mathematics that the',
    'complete edition of his works, the <i>Opera Omnia</i>, is still not finished',
    'after more than a century of editing. He wrote something like 850 books and',
    'papers. He gave us so much of the notation we use without thinking: the letter',
    '<i>e</i> for the base of the natural logarithm, <i>i</i> for the square root of',
    'minus one, the sigma for a sum, <i>f(x)</i> for a function, and a great deal of',
    'the modern shape of trigonometry.</p>',
    '<p><b>The most beautiful equation.</b> Everyone\'s favourite, and mine. Start',
    'from Euler\'s formula, which ties the exponential to the circle:</p>',
    '<pre>',
    '   e^(ix) = cos x + i sin x',
    '',
    '   put x = &pi;  (half a turn around the circle):',
    '',
    '   e^(i&pi;) = cos &pi; + i sin &pi; = -1 + 0 = -1',
    '',
    '   and so        e^(i&pi;) + 1 = 0',
    '</pre>',
    '<p>Five constants, e, i, pi, 1 and 0, and the three operations of addition,',
    'multiplication and exponentiation, all bound into one short true sentence. If',
    'you are not a little stunned the first time, read it again.</p>',
    '<img class="indie-pic" src="assets/media/web/math/euler-01.jpg" alt=""><span class="indie-cap">Leonhard Euler, by Jakob Handmann (public domain)</span>',
    '<p><b>The Basel problem.</b> The question that made his name in 1735: what is',
    'the exact sum of the reciprocals of the squares? Everyone knew it converged to',
    'something near 1.645, nobody could say what. Euler found it, and the answer has',
    'a pi in it, which is outrageous, because there is not a circle in sight.</p>',
    '<pre>',
    '    1     1     1     1              &pi;&sup2;',
    '   --- + --- + --- + --- + ...  =  ------',
    '   1&sup2;    2&sup2;    3&sup2;    4&sup2;               6',
    '</pre>',
    '<p><b>The Seven Bridges of Konigsberg.</b> In 1736 the good people of',
    'Konigsberg wondered whether you could stroll the town crossing each of its',
    'seven bridges exactly once and come home. Euler proved you cannot, and in doing',
    'so he threw away the map. What matters, he saw, is not distance or shape but',
    'how the land masses connect, so he replaced each patch of land with a dot and',
    'each bridge with a line, and asked about the dots and lines alone. A walk that',
    'uses every edge once exists only if the number of dots with an odd count of',
    'lines is nought or two. Konigsberg had four. No walk. That little argument is',
    'the seed of graph theory and of topology, whole fields grown from a Sunday',
    'stroll.</p>',
    '<p class="fs-pull">He lost the sight of one eye in his thirties and both by his',
    'sixties, said he would have fewer distractions, and produced nearly half his',
    'work totally blind, dictating it to his sons and students.</p>',
    '<p>Blind, he computed with a memory that beggars belief, running long numerical',
    'series in his head and calling out the results. He died in 1783 in the middle',
    'of a calculation, over tea, working on the orbit of the newly found Uranus. The',
    'mathematician Condorcet said that he "ceased to calculate and to live".</p>',
    '<p>My neighbours in the ring: Euler adored the number theory of Pierre de',
    'Fermat and proved a good deal that Fermat had only claimed, so go and read',
    '<a href="pierre-fermat.geocities.ws">pierre-fermat</a>. And the man who took up',
    'the analytical tradition after him, and admired him this side of idolatry, is',
    'Lagrange at <a href="joseph-lagrange.geocities.ws">joseph-lagrange</a>.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01707 · best viewed at 800x600 · under construction, still',
    'copying out the Konigsberg proof properly · signed, v. · last updated 30 Apr</small></p>',
  ]);

// ---- Fermat: maths-society minutes ------------------------------------------

const FERMAT = P('pierre-fermat.geocities.ws', 'FERMAT',
  'Society minutes: an evening on Pierre de Fermat', [
    '<!--bg:math-analysis-->',
    '<h1>Minutes: Fermat evening</h1>',
    '<p><small>Minutes of the ordinary meeting of the Recreational Number Theory',
    'Society, taken by the secretary. Present: eleven members and two guests. Tea',
    'and biscuits provided by the treasurer. These minutes are circulated to the',
    'ring for anyone who missed the evening.</small></p>',
    '<hr>',
    '<p><b>1. Welcome and apologies.</b> The chair opened the meeting and reminded',
    'members that Pierre de Fermat (1601&ndash;1665) was by trade a lawyer and',
    'magistrate at Toulouse, and did his mathematics as an amateur, in the true',
    'sense, for the love of it. He published almost nothing in his lifetime. Most',
    'of what we have comes from his letters and from notes scribbled in the margins',
    'of his books, gathered and printed by his son after his death.</p>',
    '<p><b>2. The little theorem.</b> The member for combinatorics presented',
    'Fermat\'s little theorem, agreed to be one of the pillars of number theory and',
    'the workhorse behind a great deal of modern cryptography, though of course',
    'Fermat could not have known that.</p>',
    '<pre>',
    '   If p is prime and a is not divisible by p, then',
    '',
    '        a^(p-1) &equiv; 1   (mod p)',
    '',
    '   e.g.  p = 5, a = 3 :   3^4 = 81 = 16&times;5 + 1  &equiv; 1 (mod 5)',
    '</pre>',
    '<p>A short discussion followed on the name. It is called "little" only to',
    'distinguish it from the famous "last" theorem, not because it is a small',
    'matter. The member for combinatorics noted that Euler was the first to publish',
    'a proof, and generalised it; members were referred to the Euler page in the',
    'ring.</p>',
    '<img class="indie-pic" src="assets/media/web/math/fermat-01.jpg" alt=""><span class="indie-cap">Pierre de Fermat (public domain)</span>',
    '<p><b>3. The last theorem and the margin.</b> The chair then turned to the',
    'notorious marginal note. Reading his copy of the <i>Arithmetica</i> of',
    'Diophantus, at the problem of splitting a square into two squares, Fermat wrote',
    'in the margin that the same cannot be done for any higher power.</p>',
    '<blockquote class="fs-quote"><p>"It is impossible to separate a cube into two',
    'cubes, or a fourth power into two fourth powers, or in general any power higher',
    'than the second into two like powers. I have discovered a truly marvellous',
    'proof of this, which this margin is too narrow to contain."</p></blockquote>',
    '<p>That is to say, the equation below has no solution in positive whole numbers',
    'for any exponent n greater than two, even though for n equal to two there are',
    'endlessly many, the Pythagorean triples such as 3, 4, 5.</p>',
    '<pre>',
    '   x&#8319; + y&#8319; = z&#8319;      has no positive integer solutions for n > 2',
    '</pre>',
    '<p>The secretary records that the room was united in doubting that Fermat',
    'really had a proof, since the theorem resisted the greatest mathematicians for',
    'more than three centuries and was settled, by Andrew Wiles, only very recently',
    'and by machinery from far beyond anything available in 1637. But nobody has',
    'ever found him wrong about a claim, which keeps the doubt polite.</p>',
    '<p><b>4. Any other business: the dice.</b> The treasurer reminded members that',
    'in 1654 Fermat and Blaise Pascal, in an exchange of letters about a gambler\'s',
    'problem of how to divide the stakes of an unfinished game, between them laid',
    'the foundations of the mathematical theory of probability. A whole science out',
    'of a quarrel over dice.</p>',
    '<p><b>5. Close.</b> The chair thanked the speakers and noted that the next',
    'meeting continues the analytic geometry that Fermat developed alongside',
    'Descartes. Members wishing to read ahead were directed to Euler at',
    '<a href="leonhard-euler.geocities.ws">leonhard-euler</a>, who cleared up so',
    'much that Fermat left dangling, and to Gauss at',
    '<a href="carl-gauss.geocities.ws">carl-gauss</a>, in whom number theory finally',
    'became a discipline. Meeting closed at nine. Diophantus was mentioned but has',
    'no page in our ring.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>visitors: 00337 · best viewed at 800x600 · Recreational Number',
    'Theory Society, minutes secretary · page last updated 14 Mar</small></p>',
  ]);

// ---- The Bernoullis: student coursework -------------------------------------

const BERNOULLIS = P('the-bernoullis.geocities.ws', 'BERNOULLIS',
  'MATH 214 coursework: the Bernoulli family', [
    '<!--bg:math-analysis-->',
    '<h1>The Bernoulli Family of Basel</h1>',
    '<p><small>MATH 214 History of Mathematics · essay 3 of 4 · student number',
    'withheld · "discuss the contribution of a single family to the early calculus".',
    'submitted late, sorry. please ignore the coffee ring on page 2.</small></p>',
    '<hr>',
    '<p>No family has ever produced so many mathematicians as the Bernoullis of',
    'Basel. Across three generations they gave Europe at least eight, and the first',
    'two, the brothers Jakob and Johann, were among the very first anywhere to grasp',
    'the new Leibnizian calculus and turn it into a working tool. They also fought',
    'like cats, which is half the fun of the story.</p>',
    '<p><b>The main characters (so you can keep them straight).</b></p>',
    '<pre>',
    '   Jakob  (1655-1705)  the elder brother. Bernoulli numbers, the',
    '                       "law of large numbers", loved the logarithmic spiral.',
    '   Johann (1667-1748)  younger brother, pupil then rival of Jakob. Set the',
    '                       brachistochrone challenge. Taught the Marquis de',
    '                       l\'Hopital (whose famous rule is really Johann\'s).',
    '   Daniel (1700-1782)  Johann\'s son. Fluid dynamics: Bernoulli\'s principle.',
    '                       His own father is said to have plagiarised him.',
    '</pre>',
    '<p><b>The brachistochrone.</b> In 1696 Johann Bernoulli threw down a public',
    'challenge to the mathematicians of Europe. Given two points at different',
    'heights, not one above the other, what is the shape of the wire down which a',
    'bead will slide, under gravity alone, in the shortest time? Not the straight',
    'line, as it turns out. The answer is an arc of a cycloid, the curve traced by',
    'a point on a rolling wheel.</p>',
    '<img class="indie-pic" src="assets/media/web/math/bernoulli-01.jpg" alt=""><span class="indie-cap">Jakob Bernoulli (public domain)</span>',
    '<p>The story goes that Newton, sent the problem, solved it in a single evening',
    'after a day at the Mint and sent in the answer anonymously, and that Johann,',
    'recognising the hand, said he "knew the lion by his claw". Whether the tale is',
    'exact or not, the solutions that came in, from Johann, from his brother Jakob,',
    'from Leibniz, from Newton and from l\'Hopital, opened a whole new subject.</p>',
    '<p><b>The calculus of variations.</b> That subject is the calculus of',
    'variations: not finding the value of x that makes a quantity largest or',
    'smallest, but finding the whole FUNCTION, the entire curve, that makes some',
    'total quantity a minimum or maximum. The brachistochrone minimises time; a',
    'hanging chain minimises energy and gives the catenary; light takes the path of',
    'least time. Jakob\'s response to his brother\'s challenge, in particular, pushed',
    'toward the general method, later completed by Euler and by Lagrange.</p>',
    '<p><b>Bernoulli numbers.</b> Jakob, working on sums of the powers of the whole',
    'numbers, ran into a single sequence of rational numbers that keeps the',
    'bookkeeping straight, now called the Bernoulli numbers. They turn up again and',
    'again, in the values of the zeta function, in the expansions of the tangent',
    'and in analysis generally, far from where he first met them.</p>',
    '<p><b>Fluid dynamics.</b> Daniel, in his <i>Hydrodynamica</i> of 1738, gave the',
    'principle that bears his name: in a moving fluid, where the speed is greater',
    'the pressure is lower. It is the reason, roughly, that aeroplanes fly and that',
    'a shower curtain sucks inward. His father Johann promptly published a competing',
    'book, backdated to appear the earlier, one of the meaner acts in the family',
    'record.</p>',
    '<p><b>Conclusion.</b> The Bernoullis show the early calculus becoming a craft',
    'passed down and quarrelled over within one household. They stood on Leibniz,',
    'whose notation they championed; see <a href="leibniz-calculus.geocities.ws">',
    'leibniz-calculus</a>. And their greatest pupil, at Basel, was the young',
    'Leonhard Euler, over at <a href="leonhard-euler.geocities.ws">leonhard-euler</a>,',
    'whom Johann coached and came to call the prince of mathematicians.</p>',
    '<p><b>Bibliography.</b> Boyer, <i>A History of Mathematics</i> (the library',
    'copy, edition unclear, cover missing). Bell, <i>Men of Mathematics</i> (out on',
    'loan, quoted from memory). the Encyclopaedia in the reading room, article',
    '"Bernoulli". a website i cannot find again. NB to self: get real page numbers',
    'before the resubmit.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 00214 · best viewed at 800x600 · made for MATH 214 · this',
    'page under construction until i get my mark back · last updated 2 May</small></p>',
  ]);

// ---- Lagrange: talk write-up ------------------------------------------------

const LAGRANGE = P('joseph-lagrange.geocities.ws', 'LAGRANGE',
  'Talk write-up: "Lagrange and the mechanics without pictures"', [
    '<!--bg:math-analysis-->',
    '<h1>"Mechanics Without Pictures": a Lagrange talk</h1>',
    '<p><small>my notes on the departmental history-of-maths seminar last Thursday,',
    'speaker\'s name in my notebook somewhere, tidied up for the ring. any errors',
    'are mine, not the speaker\'s. tea was weak, talk was strong.</small></p>',
    '<hr>',
    '<p>The speaker opened with a boast that Joseph-Louis Lagrange (1736&ndash;1813)',
    'made in the preface to his masterwork, and that has delighted mathematicians',
    'ever since. Of the <i>Mecanique analytique</i>, published in Paris in 1788, he',
    'wrote that the reader will find no diagrams in the whole book.</p>',
    '<blockquote class="fs-quote"><p>"No diagrams will be found in this work. The',
    'methods that I set forth require neither constructions nor geometrical or',
    'mechanical arguments, but only algebraic operations."</p><p><small>— Lagrange,',
    'preface to the <i>Mecanique analytique</i></small></p></blockquote>',
    '<p>The whole of mechanics, the speaker explained, Lagrange rebuilt as algebra',
    'and analysis, with not a single picture to lean on. Where Newton drew triangles',
    'and swept out areas, Lagrange wrote down functions and differentiated them. It',
    'is the moment mechanics stops being geometry and becomes calculus through and',
    'through.</p>',
    '<p><b>The Lagrangian.</b> The trick, the speaker said, is to stop tracking',
    'forces and start tracking energy. Form a single quantity, the Lagrangian, the',
    'kinetic energy minus the potential energy, and the true motion of the system',
    'is the one that makes a certain total, the action, stationary. Out of that one',
    'principle drop the equations of motion for any system at all, in whatever',
    'coordinates suit it, pendulums, planets, spinning tops.</p>',
    '<pre>',
    '   L  =  T - V            (kinetic energy minus potential energy)',
    '',
    '    d ( &part;L )     &part;L',
    '   --- ( --- )  -  ---  =  0        the Euler-Lagrange equation,',
    '    dt ( &part;q&#775; )     &part;q          one for each coordinate q',
    '</pre>',
    '<p>A member of the audience pointed out that this grew directly from the',
    'calculus of variations Euler and Lagrange had built together, and the speaker',
    'agreed: the machinery that finds the best curve is turned here on nature',
    'itself, which behaves, in a precise sense, as economically as it can.</p>',
    '<img class="indie-pic" src="assets/media/web/math/lagrange-01.jpg" alt=""><span class="indie-cap">Joseph-Louis Lagrange (public domain)</span>',
    '<p><b>The Lagrange points.</b> The part that woke the back row. In studying the',
    'three-body problem, the Sun, a planet and a small body, Lagrange found five',
    'special points where the gravity of the two large bodies and the motion of the',
    'system balance so that a small body can sit still relative to the other two.',
    'These are the Lagrange points, and they are not a curiosity: spacecraft are',
    'parked at them to this day, and clouds of asteroids, the Trojans, sit in two of',
    'the Sun and Jupiter points. Mathematics from 1772 giving real addresses in',
    'space.</p>',
    '<p><b>Number theory.</b> The speaker did not want to leave the impression that',
    'Lagrange was all mechanics. He proved the four-square theorem, that every whole',
    'number is the sum of at most four perfect squares, and did deep work on',
    'continued fractions and on the theory of equations that fed straight into the',
    'group theory to come.</p>',
    '<p class="fs-pull">Born in Turin, made his name in Berlin at the court of',
    'Frederick the Great, and ended in Paris, where he survived the Revolution that',
    'sent his friend the chemist Lavoisier to the guillotine.</p>',
    '<p>The speaker closed by placing him in the line. Lagrange took up the analysis',
    'of Euler, over at <a href="leonhard-euler.geocities.ws">leonhard-euler</a>, and',
    'carried it toward the rigorous nineteenth century, where Cauchy at',
    '<a href="augustin-cauchy.geocities.ws">augustin-cauchy</a> would insist on',
    'proving carefully what the eighteenth century had used so boldly. Laplace and',
    'Lavoisier were named in passing and have no page in our ring.</p>',
    '<p><small>[ <a href="mathematicians-ring.geocities.ws">Mathematicians Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01788 · best viewed at 800x600 · seminar notes, tidied ·',
    'last updated 19 May</small></p>',
  ]);

export const MATH_B = [NEWTON, LEIBNIZ, EULER, FERMAT, BERNOULLIS, LAGRANGE];
