// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// THREE PAGES ABOUT THE OBJECT, NOT THE MUSIC.
//
// Written by people who love the carrier more than they can quite justify: a
// format obsessive with a timeline he keeps updating, a mixtape romantic who
// still has the C90s, and a hi-fi bore who reads the dead wax the way other
// people read tea leaves. The history is real — Columbia's LP in 1948, the
// Philips cassette in 1963, the CD in 1982 — and the fixations are theirs. The
// subject is always the shellac, the vinyl, the tape, the aluminium: how long a
// thought it let you have, and how you held it.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- the format itself ------------------------------------------------------

const FORMAT = P('the-format-page.geocities.ws', 'THE PHYSICAL RECORD',
  'the physical record — a format page', [
    '<!--bg:vinyl-->',
    '<h1>The Physical Record</h1>',
    '<p><small>A page about the carrier, not the songs. I keep meaning to split',
    'it in two and I never do. If a date here is wrong tell me and I will fix it,',
    'I care about this more than is healthy. — Aldous, keeper of the shelf.</small></p>',
    '<hr>',
    '<p>Every format decided two things before a note was played: how long a',
    'thought could be, and how you held it in your hand. The rest of this page is',
    'me going through them one at a time.</p>',
    '<p>Start with <b>shellac</b>. The 78 was a heavy, brittle disc pressed from a',
    'resin the lac insect makes, ten inches across, and it gave you about three',
    'minutes a side. Three minutes. That is why so much of the early music we love',
    'is three minutes long — not because the feeling was three minutes long, but',
    'because the shellac was. Drop one and it goes like a plate. We only still',
    'have Robert Johnson because a few of those 78s did not get dropped; see the',
    'page a friend keeps at',
    '<a href="robert-johnson.geocities.ws">robert-johnson.geocities.ws</a>. No',
    'surviving shellac, no surviving voice.</p>',
    '<p>Then <b>vinyl</b>, and everything changes. Columbia brought out the',
    'long-playing microgroove disc in 1948 — 33⅓ rpm, a finer groove packed',
    'tighter, twelve inches, better than twenty minutes a side. Suddenly a side',
    'could be a suite, an argument, a whole mood, instead of a single. The album',
    'as we mean it is a physical fact of 1948 before it is an artistic one. RCA',
    'answered the next year, 1949, with the little <b>7-inch 45</b>, the fat',
    'spindle hole and the single in its own body. For a while the two firms',
    'fought a daft speed war and we ended up keeping both, the LP for the statement',
    'and the 45 for the hit.</p>',
    '<table class="jb-table" border="1" cellpadding="3">',
    '<tr><th>format</th><th>came in</th><th>the material</th><th>a side holds</th><th>how you held it</th></tr>',
    '<tr><td>shellac 78</td><td>from the 1900s</td><td>shellac, brittle</td><td>~3 min</td><td>two hands, carefully</td></tr>',
    '<tr><td>vinyl LP</td><td>Columbia, 1948</td><td>vinyl, microgroove, 33⅓</td><td>20+ min</td><td>by the edges, like a photo</td></tr>',
    '<tr><td>7-inch 45</td><td>RCA, 1949</td><td>vinyl, big hole</td><td>~4 min</td><td>a stack on the spindle</td></tr>',
    '<tr><td>compact cassette</td><td>Philips, 1963</td><td>magnetic tape in a shell</td><td>up to 45 min</td><td>in your pocket</td></tr>',
    '<tr><td>compact disc</td><td>1982</td><td>aluminium under plastic</td><td>~74 min</td><td>by the hole and the rim</td></tr>',
    '</table>',
    '<p>The <b>compact cassette</b> is the one people underrate. Philips put it out',
    'in 1963 and it was never meant to be hi-fi, it was meant to be small and',
    'cheap and yours. And that is exactly why it mattered: it was the first format',
    'you could <i>write on</i>. You could record onto it at your kitchen table.',
    'The whole culture of the home-made tape comes out of that shell, which is why',
    'I sent the compilation stuff off to its own page —',
    '<a href="the-mixtape.geocities.ws">the-mixtape.geocities.ws</a> — because it',
    'deserves more than a paragraph.</p>',
    '<p>Then the <b>compact disc</b>, 1982, sold to us as “perfect sound forever”.',
    'No surface noise, no wear, aluminium sealed under lacquer, held by the hole',
    'and the rim so your fingers never touched the data. I am not going to sneer at',
    'it the way some of my ring do; it was a marvel. But “perfect” did something',
    'to how records got made, and a bloke down the ring has a whole page about',
    'that at',
    '<a href="loudness-and-mastering.geocities.ws">loudness-and-mastering.geocities.ws</a>,',
    'go and read it, he is right even when he is insufferable.</p>',
    '<p>For the physics of all this — why the tape holds a signal at all, what a',
    'stamper is doing to the vinyl, how the pits on a CD become sound — the',
    'engineers keep a proper media page and I defer to them:',
    '<a href="tape-and-cassette.geocities.ws">tape-and-cassette.geocities.ws</a>.',
    'They can tell you the coercivity of a chrome tape. I can only tell you it',
    'sounded brighter and hissed less.</p>',
    '<p>Last thing. The <b>sampler</b> — the Fairlight in 1979 and the boxes that',
    'followed — did something none of the others did: it turned all of the above',
    'back into raw material. A shellac 78, an LP, a 45, all of it became something',
    'you could lift a second out of and build a new record from. The format stopped',
    'being the final object and became a supply of sound. That is where this page',
    'runs out, because after that the carrier is not the point any more, and this',
    'is a page for people who still think it is.</p>',
    '<hr>',
    '<p><small>best viewed at 800x600. under construction, the cylinder section is',
    'coming (Edison, Berliner, the disc that beat the wax roll). last updated',
    '11 Feb. you are visitor 004182.</small></p>',
    '<p><small><a href="vinyl-collectors-ring.geocities.ws">« Vinyl Collectors Ring »</a></small></p>',
    '<p><small><a href="techsociety-webring.geocities.ws">« Technology &amp; Society Webring »</a></small></p>',
  ]);

// ---- the mixtape ------------------------------------------------------------

const MIXTAPE = P('the-mixtape.geocities.ws', 'THE MIXTAPE',
  'the mixtape — a page for the C90', [
    '<!--bg:vinyl-->',
    '<h1>The Mixtape</h1>',
    '<p><small>A page for anyone who ever spent a whole evening making one tape for',
    'one person. If that is you, you already understand this page. — R., who still',
    'has the box.</small></p>',
    '<hr>',
    '<p>A mixtape is a C90 and an evening you are not getting back. Ninety minutes,',
    'forty-five a side, and you recorded it in real time, which means you sat there',
    'and <i>listened to the whole thing</i> as you made it, start to finish, no',
    'skipping. You could not drag and drop a feeling. You had to live through it in',
    'order, and so did they.</p>',
    '<p>The tape came out of Philips in 1963 (the format history is on the',
    '<a href="the-format-page.geocities.ws">format page</a> if you want the dates',
    'done properly). What the industry never understood is that the writeable part',
    'was the whole point. The blank C90 was not a threat. It was a love letter with',
    'a running order.</p>',
    '<p>The suits did think it was a threat, mind. In 1981 the BPI ran the',
    '“Home Taping Is Killing Music” campaign — the little skull made out of a',
    'cassette and two crossbones underneath, and the small print, “Home Taping Is',
    'Killing Music. And It’s Illegal.” We used to iron the logo onto things. They',
    'meant it as a warning and we took it as a badge, which tells you everything',
    'about who was right.</p>',
    '<p>Here is what they missed. The <b>track order is an argument</b>. You open',
    'with something to make them stay. You put the one that actually says the thing',
    'four tracks in, where they are not braced for it. You never, ever end side one',
    'on a fade if you can help it, because the click of the machine stopping should',
    'land on a downbeat. You leave a few seconds of silence in the right place',
    'because silence is a track too. Nobody taught me this. The format taught me',
    'this, because you had to fill exactly forty-five minutes and the last song had',
    'to fit or you started the side again.</p>',
    '<p>And the <b>inlay card</b>. Hand-written, always. Biro on the little folded',
    'card, and if you ran out of room on a title you just kept going smaller and',
    'squeezed it up the side. The handwriting was the point. A printed tracklist',
    'would have missed it entirely. You were meant to hold the card and read the',
    'names in the order you chose them, in your own bad handwriting, and know that',
    'someone sat there for ninety minutes plus the evening it took to decide.</p>',
    '<p>People go on about vinyl now, the ritual, the sleeve, and fair enough. But',
    'vinyl you buy. A mixtape you <i>make</i>, and you make it for one person, and',
    'there is only one, and it is not for sale. That is the record I would save',
    'from the fire.</p>',
    '<hr>',
    '<p><small>this page is a permanent work in progress, like the tapes. mail me',
    'your best opening track. last updated 6 Feb.</small></p>',
    '<p><small><a href="vinyl-collectors-ring.geocities.ws">« Vinyl Collectors Ring »</a> ·',
    '<a href="vinyl-collectors-ring.geocities.ws">« Cassette Culture / DIY Tapes Ring »</a></small></p>',
    '<p><small><a href="techsociety-webring.geocities.ws">« Technology &amp; Society Webring »</a></small></p>',
  ]);

// ---- the pressing (a hi-fi bore) --------------------------------------------

const PRESSING = P('loudness-and-mastering.geocities.ws', 'THE PRESSING',
  'the pressing — reading the dead wax', [
    '<!--bg:vinyl-->',
    '<h1>The Pressing (and how to read it)</h1>',
    '<p><small>Yes, I am the person at the fair holding two copies of the same',
    'album up to the light. No, they are not the same. If that annoys you this page',
    'will annoy you. — D.W., pressing matters.</small></p>',
    '<hr>',
    '<p>Two people own “the same” record and they are not listening to the same',
    'thing. The music is identical. The <b>pressing</b> is not, and the pressing is',
    'what reaches your ears. The general format story is on the',
    '<a href="the-format-page.geocities.ws">format page</a>; this page is about the',
    'individual object, the one specific disc, and where its secrets are written.</p>',
    '<p>They are written in the <b>dead wax</b> — the run-out groove, that smooth',
    'ring between the last track and the label. Tilt it under a lamp and you will',
    'find scratched or stamped codes. This is the matrix, and it is not decoration.',
    'Here is how I read it:</p>',
    '<pre class="jb-list">',
    'MATRIX / CATALOGUE  the master this side was cut from',
    'STAMPER MARK        which stamper pressed this copy (early = fewer copies before it)',
    'A / B  or  -1 -2    the cut; a lower number is usually the earlier cut',
    'CUTTING HOUSE       initials of the engineer or room (Sterling, etc.)',
    'THE HAND            sometimes a signature, e.g. “A PORKY PRIME CUT” (George Peckham)',
    '</pre>',
    '<p>Why does anyone care. Because a <b>first pressing</b> was cut from a fresh',
    'master by the cutting engineer, often supervised, and pressed while the',
    'stampers were still crisp. A later reissue may be cut from a copy of a copy, or',
    'from a tape a generation down, on tired stampers, into thinner vinyl. Same',
    'catalogue number on the sleeve, a different record in the groove. The dead wax',
    'is where you tell them apart, and it is the one part of the record that does',
    'not lie to you.</p>',
    '<p>If you want the good version, look for a <b>half-speed master</b>. The',
    'lacquer is cut with the tape running at half speed and the lathe turning at',
    'half speed, which gives the cutter head twice as long to trace every detail,',
    'so the high end and the transients come out cleaner. Mobile Fidelity built a',
    'reputation on this, “Original Master Recording”, and the old CBS Mastersound',
    'half-speeds are worth having too. They cost more and they are worth it, and I',
    'will not be arguing about that today.</p>',
    '<p>Now the thing that actually keeps me up. The <b>loudness war</b>. When the',
    'CD arrived in 1982 it had far more dynamic range than vinyl could dream of —',
    'the quiet could be truly quiet and the loud genuinely loud. And then, through',
    'the 1990s, the industry started throwing that gift away. Master it louder than',
    'the last one so it jumps out of the radio, squash the peaks flat with a',
    'limiter, and the whole record sits at the top with nowhere left to go. New',
    'CDs came out louder and more tiring every year. Turn one up and there is no',
    'lift in it, because the loud and the quiet have been pushed into the same',
    'thin band at the top of the scale.</p>',
    '<p>So my advice, for whatever an obsessive is worth: read the dead wax, buy',
    'the earlier cut, keep the half-speeds, and be suspicious of anything sold to',
    'you as louder. Then go and make someone a tape and stop measuring things —',
    'the people over at <a href="the-mixtape.geocities.ws">the-mixtape.geocities.ws</a>',
    'have the right idea and I say that as the least romantic man on the ring.</p>',
    '<hr>',
    '<p><small>corrections welcome, especially on stamper codes, I am always',
    'learning. best viewed at 800x600. last updated 14 Feb. visitor 000937.</small></p>',
    '<p><small><a href="vinyl-collectors-ring.geocities.ws">« Vinyl Collectors Ring »</a></small></p>',
    '<p><small><a href="techsociety-webring.geocities.ws">« Technology &amp; Society Webring »</a></small></p>',
  ]);

export const MUSIC_H = [FORMAT, MIXTAPE, PRESSING];
