// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F: the third generation and the politics of recognition.
//
// Fan pages, kept on a free host, each ABOUT a thinker and never in the
// thinker's own voice. A devotee's shrine to Honneth and the struggle for
// recognition; a clean summary of Fraser with the famous quarrel written up;
// two student coursework pages (Benhabib handed in late, Wellmer holding the
// line for modernism); and a sober account of Menke, art and law held
// together. The authors, titles and dates are real; the enthusiasms are the
// fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Honneth: the devotee's shrine ------------------------------------------

const HONNETH = P('honneth-recognition.geocities.ws', 'HONNETH',
  'THE STRUGGLE FOR RECOGNITION // an Axel Honneth shrine', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/uni-frankfurt-01.jpg" alt=""><span class="indie-cap">Goethe University, Frankfurt (photo: Adam Jones, CC BY-SA)</span>',
    '<h1>THE STRUGGLE FOR RECOGNITION</h1>',
    '<p><small>a shrine to Axel Honneth, kept by a philosophy postgrad who read',
    'the recognition book in one sitting on a night train and has not been quite',
    'the same since. i keep this page because nobody in my department takes him',
    'seriously enough. they will. (R.)</small></p>',
    '<p class="fs-epi">"the struggle for recognition" — Axel Honneth</p>',
    '<hr>',
    '<p>Here is the whole idea, and it is beautiful. People do not fight only over',
    'bread and money. They fight to be SEEN. Social conflict, right down at its',
    'root, is a struggle to be recognised as somebody who counts, and the fuel of',
    'it is the burning experience of being denied that, of being humiliated,',
    'insulted, passed over, treated as nothing. Honneth took that feeling, the one',
    'everybody knows in their body, and built a whole social theory on it.</p>',
    '<h2>The book</h2>',
    '<p><i>The Struggle for Recognition</i> (1992) is the one you must read. He',
    'argues there are three spheres in which a person needs to be recognised, and',
    'each has its own injury when it fails:</p>',
    '<blockquote class="fs-quote"><p>love · rights · solidarity</p></blockquote>',
    '<p>LOVE, the sphere of close relationships, where you learn basic self-',
    'confidence, and whose injury is abuse and neglect. RIGHTS, where you are',
    'recognised as a legal person equal to everyone else, and whose injury is being',
    'denied rights, being excluded. And SOLIDARITY, the wider community of value',
    'where what you do and who you are is esteemed, and whose injury is having your',
    'way of life held in contempt. Deny a person in any of the three and you get',
    'not just sadness but a MOTIVE, a reason to struggle.</p>',
    '<div class="fs-aside"><p>He gets the bones of this from the young Hegel, the',
    'Jena writings on recognition, and then he does something clever: he runs it',
    'through social psychology so it is not just a story about Spirit, it is about',
    'actual wounded people. Hegel with a clinic attached.</p></div>',
    '<h2>Disrespect</h2>',
    '<p>The word to carry away is DISRESPECT (in the German, <i>Missachtung</i>).',
    'It is the negative that drives the whole engine. You do not need a theorist to',
    'tell you what justice looks like if you can name precisely what an insult',
    'does to a person. That is his method, really: read the moral grammar of',
    'society off its injuries.</p>',
    '<h2>The rest of the shelf</h2>',
    '<p><i>Reification</i> (2005), where he takes Lukacs’s old idea, treating',
    'people and things as mere objects, and rebuilds it as a forgetting of prior',
    'recognition. And <i>Freedom’s Right</i> (2011), the big late one, a whole',
    'theory of justice worked out through the institutions where freedom actually',
    'lives, family, market, democratic public. He does not float above society and',
    'hand down principles. He digs the norms out of the practices we already have.</p>',
    '<p>&nbsp;</p>',
    '<p>And the fact i am most proud to know: he became director of the Institut',
    'für Sozialforschung in Frankfurt in 2001, the same chair Horkheimer and',
    'Adorno held. The line runs unbroken. He carries Habermas’s turn forward,',
    'from communication to recognition, and you can hear the argument continuing at',
    '<a href="habermas-communicative-action.geocities.ws">habermas-communicative-action</a>.</p>',
    '<hr>',
    '<p>Why he matters now, when so much feels cold and administered: he gives you',
    'a way to hear political anger as a demand and not just as noise. Every',
    'movement that says we will not be treated as nothing is speaking his',
    'language, whether it has read him or not.</p>',
    '<p>Neighbours worth your time. The communicative turn he inherits and then',
    'bends toward recognition is next door at',
    '<a href="habermas-communicative-action.geocities.ws">habermas-communicative-action</a>.',
    'And his student Rahel Jaeggi is carrying the whole programme into the present',
    'at <a href="jaeggi-forms-of-life.geocities.ws">jaeggi-forms-of-life</a>.</p>',
    '<hr>',
    '<p><small>counter: 01992 · best viewed at 800x600 · under construction, more',
    'on Freedom’s Right when i have finished it · last updated 8 Mar</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Fraser: the clean summary, with the quarrel written up -----------------

const FRASER = P('fraser-redistribution.geocities.ws', 'FRASER',
  'NANCY FRASER // redistribution AND recognition', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/newyork-01.jpg" alt=""><span class="indie-cap">New York (photo: William P. Gottlieb, public domain)</span>',
    '<h1>NANCY FRASER: REDISTRIBUTION AND RECOGNITION</h1>',
    '<p><small>a summary page maintained for a reading circle. i try to keep it',
    'sober and accurate. corrections welcome. this is the page i wish i had had',
    'when i started.</small></p>',
    '<hr>',
    '<p>Nancy Fraser is a critical theorist in the Frankfurt School line who works',
    'in New York. Her long argument is that a theory of justice has to hold two',
    'things at once, and that the fashion for choosing between them has done real',
    'damage.</p>',
    '<h2>The core claim</h2>',
    '<p>There are two kinds of injustice, and they are not the same thing.',
    'REDISTRIBUTION answers economic injustice, the unfair division of wealth,',
    'labour and resources. RECOGNITION answers cultural injustice, the disrespect',
    'and misrecognition of people for who they are. Fraser insists you need BOTH',
    'axes, and that many real harms, gender and race above all, sit across the two',
    'at once, so a politics that fixes only one leaves the other standing.</p>',
    '<p>Her word for the second kind, and this is where she splits from Honneth,',
    'is that recognition should be treated as a matter of STATUS, not of',
    'psychology. The question is not whether people feel esteemed. The question is',
    'whether they can take part in social life as full peers. She calls that',
    'principle PARITY OF PARTICIPATION, and it is the test she runs everything',
    'through.</p>',
    '<h2>Controversy: the quarrel with Honneth</h2>',
    '<p>This is the famous one, and it is worth getting right because people garble',
    'it. In 2003 Fraser and Axel Honneth published a book together,',
    '<i>Redistribution or Recognition? A Political-Philosophical Exchange</i>. It',
    'is one book, two authors, arguing. Read it beside the Honneth shrine at',
    '<a href="honneth-recognition.geocities.ws">honneth-recognition</a> and you',
    'get both sides in their own words.</p>',
    '<p>The split, as cleanly as i can put it. HONNETH wants recognition to be the',
    'single, deep category. For him even economic injustice is at bottom a form of',
    'misrecognition, a denial of the esteem that labour is owed, so recognition',
    'goes all the way down and redistribution is one of its provinces. FRASER says',
    'no. Fold economics into recognition and you lose the hard, structural,',
    'impersonal grip of the market, the way capitalism wrongs people whatever',
    'anybody feels about them. She keeps the two axes side by side and refuses to',
    'let either swallow the other. She also mistrusts building the theory on',
    'psychology, on injury and self-realisation, because it makes justice hang on',
    'states of feeling. Hence the status model, and parity of participation as a',
    'test you can apply from the outside.</p>',
    '<p class="fs-pull">not redistribution OR recognition. redistribution AND recognition.</p>',
    '<h2>Where it went</h2>',
    '<p>Fraser did not stay in the seminar room with this. She went after her own',
    'side. Her essay on PROGRESSIVE NEOLIBERALISM is the sharp one: the charge that',
    'a certain liberal politics married the language of recognition, diversity and',
    'representation, to a hollowed-out economics, so you got the symbols of',
    'inclusion bolted onto Wall Street, and the redistribution half of the promise',
    'quietly dropped. A lot of people found that essay very uncomfortable, which is',
    'usually a sign the diagnosis landed.</p>',
    '<p>Lately she has widened the lens all the way out. <i>Cannibal Capitalism</i>',
    '(2022) argues that capitalism does not just exploit wage labour, it feeds on',
    'the things it refuses to pay for and pretends are free: care work, nature, the',
    'public powers of the state, the unpaid labour that holds everything up. An',
    'economy eating its own conditions of existence.</p>',
    '<div class="fs-aside"><p>Do not forget the early Fraser. Her 1990 critique of',
    'Habermas’s public sphere is a landmark: the single bourgeois public was',
    'never as open as it claimed, it ran on exclusions, and there were always',
    'counter-publics kept outside the door. It set up a lot of what came after.</p></div>',
    '<hr>',
    '<p>Neighbours. The other half of the great debate lives at',
    '<a href="honneth-recognition.geocities.ws">honneth-recognition</a>. And the',
    'feminist reworking of discourse ethics, the concrete other, sits with Seyla',
    'Benhabib at',
    '<a href="benhabib-situating.geocities.ws">benhabib-situating</a>, who is',
    'arguing the neighbouring question about who counts as a member at all.</p>',
    '<hr>',
    '<p><small>visitors: 01147 · best viewed at 800x600 · reading-circle page,',
    'kept current · last updated 14 Feb</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Benhabib: student coursework, handed in late ---------------------------

const BENHABIB = P('benhabib-situating.geocities.ws', 'BENHABIB',
  'Situating the Self // notes for SOC-311 (Benhabib)', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/books-01.jpg" alt=""><span class="indie-cap">(photo: Furkan Akkurt, CC BY-SA)</span>',
    '<h1>SITUATING THE SELF: NOTES ON SEYLA BENHABIB</h1>',
    '<p><small>for SOC-311, Contemporary Critical Theory. handed in late, sorry',
    'Prof. putting the good version online because it took me ages and someone may',
    'as well get the use of it. started these 3 November.</small></p>',
    '<hr>',
    '<p>Seyla Benhabib is the one who took Habermas and discourse ethics and asked',
    'the awkward feminist questions, then kept going until she was asking who gets',
    'to be inside the moral community in the first place. two big moves, so i will',
    'do them one at a time.</p>',
    '<h2>1. the generalised and the concrete other</h2>',
    '<p>This is from <i>Situating the Self</i> (1992) and it is the bit i actually',
    'understood. Standard moral theory, Kant and then Rawls and then Habermas,',
    'treats the other person as a GENERALISED OTHER: a rational agent just like me,',
    'stripped of everything particular, so we can work out fair rules behind a kind',
    'of veil. Benhabib says fine, but that abstraction quietly writes the actual',
    'person out. It forgets the CONCRETE OTHER, this specific person with a history,',
    'a body, needs, a situation. A morality that only knows generalised others can',
    'be fair and still blind. You need both standpoints.</p>',
    '<p>Her point is not to bin universalism. it is to make it INTERACTIVE, worked',
    'out between real situated people in actual conversation, not deduced by one',
    'philosopher in an armchair. she calls this holding on to universalism while',
    'situating the self. hence the title, which i only got about halfway through,',
    'oops.</p>',
    '<div class="fs-aside"><p>the earlier book is <i>Critique, Norm, and Utopia</i>',
    '(1986), her big study of the critical-theory tradition from Hegel and Marx',
    'down to the Frankfurt School. it is where she works out the two strands she',
    'thinks critical theory has always had, a backward-looking critique and a',
    'future-looking one. dense. i only read the intro properly, being honest.</p></div>',
    '<h2>2. the rights of others</h2>',
    '<p>The later Benhabib turns to migration, which is what makes her feel current.',
    'In <i>The Rights of Others</i> she takes the cosmopolitan question head on:',
    'what do we owe to people who are not members, the migrant, the refugee, the',
    'stranger at the border? There is a tension she names between universal human',
    'rights, which are meant to belong to everyone, and the sovereignty of a people',
    'to decide who joins it. She does not pretend it dissolves.</p>',
    '<p>her word for the way out is DEMOCRATIC ITERATIONS: the idea that a political',
    'community keeps re-enacting and re-interpreting its founding norms, and each',
    'time it can widen the circle of who counts. rights are not fixed once, they',
    'get argued forward. i think this is the most hopeful thing on the whole',
    'reading list tbh.</p>',
    '<p class="fs-pull">who counts as one of us is not settled once. it gets re-argued.</p>',
    '<hr>',
    '<p>links for the marker. the discourse-ethics parent she is reworking is at',
    '<a href="habermas-communicative-action.geocities.ws">habermas-communicative-action</a>.',
    'and she shares the wider argument about redistribution and recognition with',
    'Nancy Fraser at',
    '<a href="fraser-redistribution.geocities.ws">fraser-redistribution</a>, though',
    'they come at membership from different ends.</p>',
    '<hr>',
    '<p><b>bibliography</b> (i think this is right, Prof, please dont mark me down',
    'on the formatting)</p>',
    '<p><small>Benhabib, S. <i>Critique, Norm, and Utopia</i>, 1986.<br>',
    'Benhabib, S. <i>Situating the Self</i>, 1992. THE main one.<br>',
    'Benhabib, S. <i>The Rights of Others</i> (on cosmopolitanism and migration).<br>',
    '+ lecture notes wk 6 and wk 7, and the Fraser page linked above which honestly',
    'helped a lot.</small></p>',
    '<hr>',
    '<p><small>counter: 00308 · best viewed at 800x600 · a student page, be kind ·',
    'last updated 3 Nov</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Wellmer: student coursework, holding the line for modernism ------------

const WELLMER = P('wellmer-modernism.geocities.ws', 'WELLMER',
  'The Persistence of Modernity // essay notes (Wellmer)', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/frankfurt-01.jpg" alt=""><span class="indie-cap">Frankfurt am Main (photo: Christian Wolf, CC BY-SA)</span>',
    '<h1>THE PERSISTENCE OF MODERNITY: ON ALBRECHT WELLMER</h1>',
    '<p><small>essay working-notes for the aesthetics module. putting them up',
    'because Wellmer has almost nothing about him online and finding my way in took',
    'weeks. begun 20 January. rough in places, sorry.</small></p>',
    '<hr>',
    '<p>Albrecht Wellmer is the one who stands exactly between the two big Frankfurt',
    'positions and refuses to jump to either side. Picture it as a room with Adorno',
    'at one end and Habermas at the other, and Wellmer standing in the middle',
    'saying you are both half right, let me hold the door open.</p>',
    '<h2>the problem he is stuck on</h2>',
    '<p>On one side, ADORNO. Modern art is precious because it is NEGATIVE, because',
    'it refuses to be reconciled with a false world, and its whole truth is in that',
    'refusal (there is a good summary of the aesthetics at',
    '<a href="adorno-aesthetic.geocities.ws">adorno-aesthetic</a>). trouble is,',
    'Adorno paints himself into a corner where nothing good can ever be said',
    'positively and every hope looks like a sell-out.</p>',
    '<p>On the other side, HABERMAS. reason can be rescued, we reach understanding',
    'through language, there is a rational way forward. trouble is, once you go all',
    'in on communicative rationality the dark, difficult, negative side of modern',
    'art starts to look like a problem to be tidied away rather than something',
    'that KNOWS things.</p>',
    '<h2>what Wellmer does with it</h2>',
    '<p>The book is <i>The Persistence of Modernity</i> (1985). the argument, near',
    'as i can get it: do not choose. hold on to aesthetic modernity, Adorno’s',
    'difficult negative art, WITHOUT giving up on Habermas’s idea that reason',
    'and communication can actually get somewhere. Wellmer thinks the negativity of',
    'the artwork is itself a kind of communication, it says something true about',
    'damaged life, and it can be taken up into a rational public conversation',
    'without being flattened. so the promise of reconciliation that Adorno keeps',
    'pushing off into the impossible distance, Wellmer tries to bring a bit closer',
    'and make speakable.</p>',
    '<blockquote class="fs-quote"><p>modernity persists. it is not over, and it is',
    'not to be escaped into something called the postmodern.</p></blockquote>',
    '<p>(that is me paraphrasing the drift of the title, not a direct quote, dont',
    'cite it as one.) the point of the word PERSISTENCE is that he is pushing back',
    'on the 1980s fashion for declaring modernity finished. he thinks the modern',
    'project, the difficult one, is still running and still ours.</p>',
    '<p>my one line for the exam: Wellmer keeps Adorno’s ear and Habermas’s',
    'nerve, and will not let go of either.</p>',
    '<hr>',
    '<p>links. the two poles he is steering between are Adorno at',
    '<a href="adorno-aesthetic.geocities.ws">adorno-aesthetic</a> and Habermas at',
    '<a href="habermas-communicative-action.geocities.ws">habermas-communicative-action</a>.',
    'read those two first, then Wellmer makes way more sense, which is the order i',
    'wish i had done it in.</p>',
    '<hr>',
    '<p><b>refs used</b><br>',
    '<small>Wellmer, A., <i>The Persistence of Modernity</i>, 1985 (essays on',
    'aesthetics, ethics and the postmodern).<br>',
    'module reader, weeks 4 and 5.<br>',
    'the two geocities pages linked above, which i am counting as legit because',
    'they cite the actual books.</small></p>',
    '<hr>',
    '<p><small>counter: 00196 · best viewed at 800x600 · a student page under slow',
    'construction · last updated 20 Jan</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Menke: the sober summary, art and law held together --------------------

const MENKE = P('menke-force.geocities.ws', 'MENKE',
  'CHRISTOPH MENKE // aesthetic negativity and the law', [
    '<!--bg:recognition-->',
    '<img class="indie-pic" src="assets/media/web/fs/weimar-02.jpg" alt=""><span class="indie-cap">(photo: Dietmar Rabich, CC BY-SA)</span>',
    '<h1>CHRISTOPH MENKE: FORCE, ART AND THE LAW</h1>',
    '<p><small>a summary page kept by a reader who thinks Menke is the most',
    'interesting of the current Frankfurt lot and is annoyed that so little of him',
    'is discussed in English. i have tried to keep this accurate and short.</small></p>',
    '<hr>',
    '<p>Christoph Menke works in Frankfurt in the recognition generation, but his',
    'question is his own. He wants to hold two things together that most people',
    'keep in separate buildings: the AESTHETIC, the theory of art, and the',
    'JURIDICAL, the theory of rights and law. His wager is that the same problem',
    'runs through both, the problem of what he calls negativity or force, and that',
    'you cannot understand either one properly on its own.</p>',
    '<h2>Aesthetic negativity</h2>',
    '<p>The early book is <i>The Sovereignty of Art</i>, a study of aesthetic',
    'negativity read through Adorno and Derrida together. The claim, roughly: the',
    'power of art is that it interrupts and unsettles the ordinary orders of',
    'meaning rather than simply adding to them. Art is sovereign because it can',
    'suspend the rules the rest of life runs on. Menke takes Adorno’s account',
    'of the difficult, negative artwork (summarised at',
    '<a href="adorno-aesthetic.geocities.ws">adorno-aesthetic</a>) and pushes it',
    'through French deconstruction, which is not a marriage everyone would have',
    'attempted.</p>',
    '<h2>Force</h2>',
    '<p>The pivotal book is <i>Force</i> (2013), which he subtitles an aesthetic',
    'anthropology. Here the argument goes underneath both art and reason to a',
    'darker layer: a FORCE in the human being that is pre-rational, obscure,',
    'expressive, the thing that stirs before it is shaped into a faculty or a rule.',
    'Aesthetics, on this reading, is the discipline that keeps faith with that',
    'force instead of tidying it away. It is a deliberately unsettling book,',
    'because it plants something unruly at the root of the human.</p>',
    '<h2>The critique of rights</h2>',
    '<p>Then he carries the same nerve into law. <i>Critique of Rights</i> (2015)',
    'turns on modern subjective rights, the rights each individual is said to',
    'hold, and argues that their form is not innocent. In granting the individual a',
    'private domain of entitlement, the modern legal form also naturalises the',
    'self-interested individual it claims merely to protect, and so reproduces the',
    'very domination it promises to limit. Menke is not calling for the abolition of',
    'rights. He is asking for a different, self-critical form of them.</p>',
    '<div class="fs-aside"><p>What ties the three books together is a single',
    'suspicion: that our highest achievements, autonomous art and equal rights',
    'alike, carry a hidden cost in what they have to exclude or repress to work.',
    'Read one book and it looks like aesthetics. Read all three and it is a theory',
    'of the modern subject.</p></div>',
    '<hr>',
    '<p>Neighbours. His Adorno inheritance sits with',
    '<a href="adorno-aesthetic.geocities.ws">adorno-aesthetic</a>. And the nearest',
    'living argument, over whether to steer between Adorno and Habermas or to go',
    'under both, is with Albrecht Wellmer at',
    '<a href="wellmer-modernism.geocities.ws">wellmer-modernism</a>. Put the two',
    'pages together and you have the current quarrel about what is left of',
    'aesthetic modernity.</p>',
    '<hr>',
    '<p><small>visitors: 00512 · best viewed at 800x600 · corrections welcome, i am',
    'only a reader · last updated 26 Apr</small></p>',
    '<p><small>',
    '[ <a href="frankfurt-school-ring.geocities.ws">Frankfurt School Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const FS_F = [HONNETH, FRASER, BENHABIB, WELLMER, MENKE];
