// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH CRYP_B — stream & symmetric ciphers.
//
// Cached pages from a late-1990s crypto enthusiast: the RC4 how-it-works
// showpiece, the stream cipher and the keystream read closely, the repeating-
// key XOR worked out, Enigma broken at Bletchley, and DES with its short key.
// sci.crypt voice, worked examples on harmless demo text, a keen sense that
// the maths had just gone political. No game secret ever appears in a <pre>.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- RC4: the showpiece how-it-works ----------------------------------------

const RC4 = P('rc4.geocities.ws', 'RC4',
  'RC4 // the little cipher that ran the web', [
    '<!--bg:cryp-symmetric-->',
    '<h1>RC4</h1>',
    '<p class="fs-epi">“It is a very simple algorithm. You can hold it in your',
    'head.” — a sci.crypt regular, on why arcfour spread so fast</p>',
    '<p><small>a how-it-works page for RC4, the stream cipher that quietly',
    'encrypted half the web in the 1990s. kept by a reader of sci.crypt who has',
    'typed the twenty lines out from memory more times than is healthy.',
    '— rc4fan</small></p>',
    '<hr>',
    '<p>Ron Rivest designed RC4 in 1987 at RSA Data Security. The name stands for',
    '“Rivest Cipher 4”. For seven years it was a TRADE SECRET, licensed but never',
    'published, and you were supposed to take the box on trust. Then in September',
    '1994 someone posted the algorithm, reverse-engineered, to the Cypherpunks',
    'mailing list, and from there to sci.crypt. Because “RC4” was a trademark the',
    'free version got called ARCFOUR (“alleged RC4”), and that is the name you',
    'will still see in a lot of code. The cat was out of the bag and it was never',
    'going back in.</p>',
    '<blockquote class="fs-quote"><p>Once the source was on the list, RC4 was',
    'everyone’s. You cannot un-publish twenty lines of C.</p></blockquote>',
    '<p>What made it spread was the SIZE of it. Most ciphers are a slab of tables',
    'and rounds. RC4 is a byte array and two counters, and it is fast, and you',
    'can carry the whole thing in your head. It went into SSL, into WEP, into',
    'Lotus Notes, into more places than anyone kept track of.</p>',
    '<hr>',
    '<p><b>How it works, in two halves.</b> RC4 keeps a STATE: an array S of 256',
    'bytes, holding a permutation of the numbers 0 to 255. Every value from 0 to',
    '255 appears exactly once. There are two stages. First the key-scheduling',
    'algorithm (KSA) stirs the key into that array. Then the pseudo-random',
    'generation algorithm (PRGA) pulls a keystream out of it, one byte at a time,',
    'each byte produced by SWAPPING two entries and reading a third.</p>',
    '<img class="indie-pic" src="assets/media/web/cryp/rivest-01.jpg" alt=""><span class="indie-cap">Ron Rivest, who designed RC4 (photo: Ronald L. Rivest, CC BY-SA 4.0)</span>',
    '<p>The heart of both halves is the same move: pick two positions, swap the',
    'bytes that sit there, and let the array drift further from where it started.',
    'The KSA does 256 swaps to set up. The PRGA does one swap per output byte,',
    'for as long as you keep asking.</p>',
    '<pre>',
    'KSA — key-scheduling algorithm (set up the state)',
    '------------------------------------------------',
    '  for i in 0..255:  S[i] = i          # start with the identity',
    '  j = 0',
    '  for i in 0..255:',
    '      j = (j + S[i] + key[i mod keylen]) mod 256',
    '      swap S[i], S[j]                 # 256 swaps, keyed',
    '',
    'PRGA — pseudo-random generation (make the keystream)',
    '---------------------------------------------------',
    '  i = 0 ;  j = 0',
    '  loop, once per output byte:',
    '      i = (i + 1) mod 256',
    '      j = (j + S[i]) mod 256',
    '      swap S[i], S[j]',
    '      k = S[ (S[i] + S[j]) mod 256 ]  # the keystream byte',
    '      output k',
    '',
    'encrypt:  cipher_byte = plain_byte XOR k',
    'decrypt:  plain_byte  = cipher_byte XOR k   # same keystream, same XOR',
    '</pre>',
    '<p>The keystream byte k has nothing to do with the message. You generate the',
    'stream from the key alone, then XOR it against the plaintext. To decrypt you',
    'regenerate the identical stream and XOR again, because XOR is its own',
    'inverse. RC4 is a STREAM CIPHER end to end; the block cipher works another',
    'way entirely (see <a href="the-stream-cipher.geocities.ws">the-stream-cipher</a>',
    'for the contrast). The stream it makes is the whole game, and there is a',
    'close reading of that at <a href="the-keystream.geocities.ws">the-keystream</a>.</p>',
    '<hr>',
    '<div class="fs-aside"><p><b>Did you know:</b> the first bytes of an RC4',
    'keystream are BIASED. The second byte is twice as likely to be zero as it',
    'should be, and there are other leaks near the start. The state has not been',
    'stirred enough yet. The standard fix is to generate and THROW AWAY the first',
    '256 (or more) bytes before you use any. A cipher that starts predictable is',
    'no cipher for that stretch.</p></div>',
    '<p>That bias is not a footnote. It is how RC4 was eventually broken in the',
    'wild: WEP, the old wireless standard, used a fresh short key for every packet',
    'and did not discard the leaky opening bytes, and Fluhrer, Mantin and Shamir',
    'showed in 2001 that you could recover the key by collecting enough of those',
    'weak openings. The algorithm did not change. The way it was USED handed the',
    'attacker the early bytes on a plate.</p>',
    '<p class="fs-pull">Strong enough to look like privacy, weak enough to be no',
    'obstacle to the people who set the rules.</p>',
    '<p><b>The forty-bit key.</b> RC4 will take a key of almost any length. That',
    'flexibility is exactly what let the export regime bend it. Through the 1990s',
    'a government permitted “export-grade” crypto to leave the country only if the',
    'key was cut to FORTY BITS, and a great deal of exported software shipped RC4',
    'at forty bits. The algorithm was untouched; the keyspace was throttled.',
    'Forty bits is about a million million keys, which sounds enormous and is',
    'nothing: a single well-funded machine, or a room full of ordinary ones,',
    'walks the entire space by brute force in a matter of days, and the answer',
    'gets cheaper every year. Forty bits was never meant to stop a serious',
    'adversary. It was meant to look like a lock.</p>',
    '<pre>',
    'How much does the key length buy you?',
    '-------------------------------------',
    '  key bits     distinct keys        rough character',
    '  --------     -------------        ---------------',
    '    40         ~1.1 x 10^12         export-grade; falls in days',
    '    56         ~7.2 x 10^16         old DES; falls to a built machine',
    '    64         ~1.8 x 10^19         a serious effort',
    '   128         ~3.4 x 10^38         out of reach by brute force',
    '',
    '(each added bit DOUBLES the work. forty to fifty-six is not a little',
    ' stronger, it is about sixty-five thousand times the work.)',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/cryp/padlock-01.jpg" alt=""><span class="indie-cap">A padlock (photo: Tomasz Sienicki, CC BY-SA 3.0)</span>',
    '<p>So the shape of RC4 is a permutation of 256 bytes, a swap, and an XOR. The',
    'shape of the POLITICS around it is a knob on the key length and a promise',
    'that forty turns was plenty. Both are worth understanding, and they are not',
    'the same subject.</p>',
    '<hr>',
    '<p><small>counter: 02561 · best viewed in Netscape at 800x600 ·',
    'under construction (adding the WEP attack writeup) · last updated 14 Dec</small></p>',
    '<p><small>key fingerprint (do not trust, obviously invented):',
    'C0FF EE00 1987 4ARC F0UR 5EED BABE 1234 5678 9ABC — rc4fan @ sci.crypt</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the stream cipher: a close reading of one idea -------------------------

const STREAM_CIPHER = P('the-stream-cipher.geocities.ws', 'STREAM CIPHER',
  'the stream cipher // one idea, read closely', [
    '<!--bg:cryp-symmetric-->',
    '<h1>the stream cipher</h1>',
    '<p><small>one page, one idea, read slowly. what a stream cipher IS, and how',
    'it differs from the block cipher it is always set against. — a keeper of the',
    'crypto ring</small></p>',
    '<hr>',
    '<p>A stream cipher does one thing. It manufactures a long ribbon of',
    'pseudo-random bytes from the key, the KEYSTREAM, and it combines that ribbon',
    'with the message by XOR, one byte against one byte, for as long as the',
    'message runs. That is the entire idea. Everything else is engineering to make',
    'the ribbon good.</p>',
    '<blockquote class="fs-quote"><p>A stream cipher is a machine for imitating a',
    'one-time pad you do not have to carry.</p></blockquote>',
    '<p>The one-time pad is the ancestor here. The pad XORs your message against a',
    'truly random key as long as the message, and it is unbreakable, and it is',
    'unusable because you must somehow share that mountain of key. A stream cipher',
    'cheats: it takes a short key and STRETCHES it, with an algorithm, into a',
    'ribbon that only LOOKS random. It is not perfectly secret the way the pad is.',
    'It is secret as long as an attacker cannot predict the ribbon.</p>',
    '<hr>',
    '<p><b>Against the block cipher.</b> The other family works in slabs. A block',
    'cipher (DES, later AES) takes a fixed lump of bits, say 64 or 128, and',
    'scrambles the whole lump at once through several rounds, key mixed in at',
    'every round. It does not make a keystream; it transforms the block itself.',
    'The contrast is worth holding in one place.</p>',
    '<img class="indie-pic" src="assets/media/web/cryp/enigma-rotors-01.jpg" alt=""><span class="indie-cap">Enigma rotors, which stepped the substitution (photo: TedColes, CC0)</span>',
    '<pre>',
    '  STREAM cipher                    BLOCK cipher',
    '  -------------                    ------------',
    '  makes a keystream, XORs it       transforms a fixed-size block',
    '  one byte (or bit) at a time      64 or 128 bits at a go',
    '  no padding needed                message padded up to a block',
    '  fast, tiny state (RC4)           heavier, table-driven (DES)',
    '  error stays local               error can spoil a whole block',
    '  MUST NOT reuse the keystream     mode of operation matters',
    '</pre>',
    '<p>The last line in the stream column is the one that kills people. Because a',
    'stream cipher is just message-XOR-keystream, the keystream must never be used',
    'twice. Reuse it across two messages and the two ciphertexts XOR together to',
    'give you the two plaintexts XOR’d against each other, with the keystream',
    'gone entirely. From there a reader with patience pulls both messages apart.',
    'The same trap as reusing a pad, dressed in faster clothes. The reason why',
    'lives at <a href="the-keystream.geocities.ws">the-keystream</a>, and the',
    'cipher that made this family famous is at <a href="rc4.geocities.ws">rc4</a>.</p>',
    '<div class="fs-aside"><p><b>Two flavours.</b> A SYNCHRONOUS stream cipher',
    'makes its keystream from the key alone, independent of the message; sender',
    'and receiver must stay in step, and a dropped byte throws the rest into',
    'nonsense. A SELF-SYNCHRONISING (asynchronous) stream cipher feeds recent',
    'ciphertext back into the generator, so after a slip it finds its feet again',
    'within a few bytes. RC4 is the synchronous kind.</p></div>',
    '<p class="fs-pull">Two ciphertexts under one keystream are two windows into',
    'the same room.</p>',
    '<p>The appeal of the stream cipher is speed and smallness. No padding, almost',
    'no state, encrypt as the bytes arrive off the wire. That is why it went into',
    'the protocols that had to run everywhere on modest hardware. The price is',
    'discipline: get the keystream right, never repeat it, and throw away the',
    'weak opening if your generator has one.</p>',
    '<hr>',
    '<p><small>counter: 01120 · best viewed at 800x600 · a crypto-webring page ·',
    'last updated 2 Nov</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- XOR and the repeating key: a worked-example page -----------------------

const XOR_REPEATING = P('xor-and-the-repeating-key.geocities.ws', 'XOR KEY',
  'XOR and the repeating key // worked by hand', [
    '<!--bg:cryp-symmetric-->',
    '<h1>XOR and the repeating key</h1>',
    '<p><small>a worked-example page. the simplest cipher there is, why it is',
    'genuinely unbreakable in one form and genuinely feeble in another, all done',
    'on harmless demo text you can check with a pencil. — the ring keeper</small></p>',
    '<hr>',
    '<p>XOR, the exclusive-or, is the smallest cipher operation there is. Two',
    'bits: output 1 if they differ, 0 if they match. Its one magic property is',
    'that it is ITS OWN INVERSE. XOR a byte with a key byte to encrypt; XOR the',
    'result with the SAME key byte and the original comes straight back.</p>',
    '<pre>',
    '  p XOR k = c      (encrypt)',
    '  c XOR k = p      (decrypt, because k XOR k = 0)',
    '',
    '  truth table          worked on one letter (demo only)',
    '  a b | a^b            plaintext  H  = 0100 1000',
    '  0 0 |  0             key byte   K  = 0010 1011',
    '  0 1 |  1             --------------------------- XOR',
    '  1 0 |  1             cipher        = 0110 0011',
    '  1 1 |  0             back: 0110 0011 XOR 0010 1011 = 0100 1000 = H',
    '</pre>',
    '<p>If the key is truly random, as long as the message, and used only once,',
    'this XOR IS the one-time pad and it cannot be broken. Perfect secrecy, no',
    'catch, no cleverness recovers the message. The trouble begins the moment you',
    'try to make a long message secret with a SHORT key.</p>',
    '<hr>',
    '<p><b>The repeating key.</b> You have five bytes of key and five hundred bytes',
    'of message, so you repeat the key over and over, wrapping round, until it',
    'covers the message. This is easy to code and it is fatally weak. Watch what',
    'the repeat does on a harmless sentence.</p>',
    '',
    '<pre>',
    '  plaintext:  A T T A C K A T D A W N',
    '  key (len3): K E Y K E Y K E Y K E Y     <- three bytes, repeated',
    '  ------------------------------------',
    '  position:   0 1 2 0 1 2 0 1 2 0 1 2     <- same key byte every 3rd column',
    '',
    '  every 3rd letter is enciphered with the SAME key byte.',
    '  columns {0,3,6,9...} share a key byte; so do {1,4,7...}; so do {2,5,8...}.',
    '</pre>',
    '<p>That regularity is the whole weakness. A repeating-key XOR is really just',
    'several Caesar-style shifts interleaved, one per key position. Break the',
    'message into those columns and each column was encrypted with a single',
    'fixed byte, which is trivial to attack.</p>',
    '<div class="fs-aside"><p><b>How a repeated key is found and stripped.</b>',
    'First find the key LENGTH. Where the same plaintext meets the same key byte,',
    'identical ciphertext stretches appear; the gaps between such repeats tend to',
    'be multiples of the key length (this is Kasiski’s method, borrowed from',
    'the Vigenere break). A count called the index of coincidence sharpens the',
    'guess. Once you know the length, say five, you sort the ciphertext into five',
    'piles by position. Each pile met ONE key byte, so each pile is a simple',
    'single-byte XOR, and single-byte XOR falls instantly: try all 256 bytes and',
    'keep whichever makes that pile look like real text. Solve the piles, and the',
    'key falls out one byte at a time.</p></div>',
    '<p class="fs-pull">A short key repeated over a long message is a promise the',
    'message keeps breaking.</p>',
    '<p><b>The difference from a true one-time pad.</b> The pad never repeats,',
    'because the key is as long as the message and thrown away after. There are no',
    'columns to sort, because no key byte is ever reused, so there is nothing to',
    'line up and nothing to strip. Repeat the key even once and you have surrendered',
    'the only thing that made the pad perfect. The XOR is identical in both cases;',
    'the security lives entirely in whether the key repeats.</p>',
    '<p>For what the keystream has to be so this never happens by accident, see',
    '<a href="the-keystream.geocities.ws">the-keystream</a>. For the heavyweight',
    'cousin that scrambles whole blocks instead of XOR-ing a stream, see',
    '<a href="des-and-the-block-cipher.geocities.ws">des-and-the-block-cipher</a>.</p>',
    '<hr>',
    '<p><small>counter: 00947 · best viewed at 800x600 · pencil and paper',
    'friendly · last updated 21 Oct</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the Enigma machine: a history-of-the-attack page -----------------------

const ENIGMA = P('the-enigma-machine.geocities.ws', 'ENIGMA',
  'the Enigma machine // how it fell', [
    '<!--bg:cryp-symmetric-->',
    '<h1>the Enigma machine</h1>',
    '<p class="fs-epi">“It was thanks to Ultra that we won the war.” — Winston',
    'Churchill, as quoted by his cryptanalysts</p>',
    '<p><small>a history-of-the-attack page. not how Enigma worked so much as how',
    'it was BROKEN, twice, first by Poland and then at Bletchley. — the ring',
    'keeper</small></p>',
    '<hr>',
    '<p>Enigma was a German electro-mechanical cipher machine, a typewriter with',
    'rotors. Press a key and a current runs through a set of rotating wheels, each',
    'rewiring the letter, then bounces off a reflector and back through the rotors',
    'by a different path, lighting a lamp for the enciphered letter. The rotors',
    'STEP after each keypress, like an odometer, so the same plaintext letter',
    'comes out different almost every time. In front of the rotors sat a',
    'PLUGBOARD (Steckerbrett) that swapped pairs of letters before and after,',
    'multiplying the settings enormously.</p>',
    '<p>The security was in the DAILY KEY: which rotors, in which order, their',
    'starting positions, and the plugboard pairings, all changed every day by a',
    'printed sheet. The number of possible settings ran to astronomical figures,',
    'and the Germans trusted it completely. That trust was the mistake.</p>',
    '<hr>',
    '<div class="fs-aside"><p><b>The flaw at the centre.</b> The reflector that',
    'made Enigma so tidy also gave it one fatal property: NO LETTER COULD EVER',
    'ENCIPHER TO ITSELF. An A never came out as A. That sounds harmless. It is a',
    'gift to the attacker: line a suspected word (a “crib”) against the',
    'ciphertext, and any position where a letter sits above itself is impossible,',
    'so you slide the crib along and throw out every clashing placement for free.',
    'A cipher that can never leave a letter unchanged has told you where the',
    'plaintext is NOT.</p></div>',
    '<p><b>Poland first.</b> The break did not begin at Bletchley. In the early',
    '1930s the Polish Cipher Bureau, and above all the mathematician Marian',
    'Rejewski, worked out the internal wiring of Enigma from traffic and a little',
    'espionage, treating the machine as a problem in the theory of permutations.',
    'Rejewski and his colleagues Jerzy Różycki and Henryk Zygalski built',
    'methods and machines (the “bomba”) to recover daily keys. In July 1939, with',
    'invasion weeks away, Poland handed everything it knew to Britain and France.',
    'The Allied break stood on Polish foundations.</p>',
    '<img class="indie-pic" src="assets/media/web/cryp/enigma-01.jpg" alt=""><span class="indie-cap">An Enigma machine (NSA, public domain)</span>',
    '<p><b>Then Bletchley.</b> At Bletchley Park, Alan Turing and Gordon Welchman',
    'took the idea further and designed the BOMBE, an electromechanical machine',
    'that tested Enigma settings at speed. The Bombe did not try every setting',
    'blindly. It ran on cribs, likely stretches of plaintext such as a weather',
    'report or a stock phrase, and used the CONTRADICTIONS (helped by that',
    '“no letter maps to itself” rule, and by Welchman’s diagonal board) to',
    'discard impossible rotor settings wholesale, leaving a short list a human',
    'could check. Bletchley’s output was code-named ULTRA, and historians',
    'reckon it shortened the war in Europe by a year or more.</p>',
    '<p class="fs-pull">The machine was strong. The way it was USED, and the one',
    'letter it could never be, let the mathematicians in.</p>',
    '<p>Enigma is a rotor machine, not a modern symmetric cipher, but it belongs',
    'in this family: a shared secret key, changed daily, scrambling letters. Its',
    'descendants traded rotors for arithmetic. The Data Encryption Standard put',
    'the same idea (a fixed secret key, a heavy scramble) into electronics and',
    'S-boxes; see <a href="des-and-the-block-cipher.geocities.ws">des-and-the-block-cipher</a>.',
    'And the stream cipher that grew up to run the web is at',
    '<a href="rc4.geocities.ws">rc4</a>.</p>',
    '<hr>',
    '<p><small>counter: 01944 · best viewed in Netscape at 800x600 · with thanks',
    'to the Poles · last updated 9 Sep</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- DES and the block cipher: a cipher explainer ---------------------------

const DES = P('des-and-the-block-cipher.geocities.ws', 'DES',
  'DES and the block cipher // 56 bits was never enough', [
    '<!--bg:cryp-symmetric-->',
    '<h1>DES and the block cipher</h1>',
    '<p><small>a cipher explainer. the Data Encryption Standard, the block-cipher',
    'idea it carried, and the argument about its key length that ran for twenty',
    'years and turned out to be right. — the ring keeper</small></p>',
    '<hr>',
    '<p>The Data Encryption Standard was adopted as a US federal standard in 1977,',
    'developed from an IBM design (Lucifer) with the involvement of the National',
    'Security Agency. It was the first serious cipher published as an open',
    'standard for everyone to use, and for two decades it was the workhorse of',
    'commercial cryptography.</p>',
    '<p>DES is a BLOCK cipher. It does not make a keystream and XOR it, the way a',
    'stream cipher does (contrast at <a href="the-stream-cipher.geocities.ws">',
    'the-stream-cipher</a>). It takes the message a slab at a time: a 64-BIT',
    'block in, a 64-bit block out, scrambled as one lump under the key. Longer',
    'messages are cut into blocks and fed through one after another.</p>',
    '<hr>',
    '<p><b>Inside: a Feistel network.</b> DES is built as a FEISTEL network, a',
    'design with one elegant trick. Split the block in two halves. Each round',
    'runs one half through a function mixed with a round key, XORs the result into',
    'the other half, and swaps the halves. Do this sixteen times.</p>',
    '<pre>',
    'One Feistel round (L = left half, R = right half, K = round key)',
    '---------------------------------------------------------------',
    '  L(next) = R',
    '  R(next) = L  XOR  f(R, K)',
    '',
    '  16 rounds, a different round key each time.',
    '  the beauty: decryption is the SAME circuit with the round keys',
    '  applied in reverse order. f never has to be inverted.',
    '</pre>',
    '',
    '<p>The scramble function f leans on the S-BOXES, eight little lookup tables',
    'that substitute bits for other bits in a deliberately non-linear way. The',
    'S-boxes are where a block cipher gets its muscle: they stop the whole thing',
    'collapsing into linear algebra an attacker could just solve. The NSA had a',
    'hand in choosing them, which fed years of suspicion of a hidden back door.',
    'The twist in the tale: when DIFFERENTIAL CRYPTANALYSIS became public',
    'knowledge in the late 1980s, the S-boxes turned out to be unusually STRONG',
    'against exactly that attack, as though the designers had known about it and',
    'kept quiet. The NSA’s hand, on that point, had strengthened the cipher.</p>',
    '<div class="fs-aside"><p><b>Did you know:</b> IBM’s Lucifer used a key of',
    '112 bits or more. The standardised DES shipped with a key of just 56 bits',
    '(64, less 8 parity bits). Whitfield Diffie and Martin Hellman argued in 1977',
    'that 56 bits was too short and would fall to a purpose-built brute-force',
    'machine. They were told it was fine. They were right.</p></div>',
    '<p><b>The key was too short, and it fell.</b> Fifty-six bits is about',
    'seventy-two thousand million million keys. In 1997 and 1998 that stopped',
    'being safe. A distributed internet effort cracked a DES challenge, and then',
    'the Electronic Frontier Foundation built a purpose-made machine, DEEP CRACK,',
    'for a few hundred thousand dollars, that found a DES key by brute force in',
    'well under a week. The cipher was not broken by clever mathematics. It was',
    'walked, key by key, exactly as Diffie and Hellman had warned twenty years',
    'earlier.</p>',
    '<p class="fs-pull">The algorithm held. The keyspace ran out.</p>',
    '<p>The fix came in two steps. TRIPLE-DES ran the cipher three times with two',
    'or three keys, buying an effective key length long enough to be safe again,',
    'at three times the cost. Then a public competition chose a fresh design, and',
    'in 2001 the Advanced Encryption Standard (AES, the Rijndael cipher) replaced',
    'DES outright with 128-bit blocks and keys of 128, 192 or 256 bits. On the',
    'short-key argument in general, and how long a brute force really takes, the',
    'repeating-key page has the arithmetic in miniature at',
    '<a href="xor-and-the-repeating-key.geocities.ws">xor-and-the-repeating-key</a>.',
    'The rotor-machine grandparent of the shared-key idea is at',
    '<a href="the-enigma-machine.geocities.ws">the-enigma-machine</a>.</p>',
    '<hr>',
    '<p><small>counter: 01677 · best viewed at 800x600 · under construction',
    '(triple-DES modes coming) · last updated 30 Nov</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

// ---- the keystream: a close reading of one idea -----------------------------

const KEYSTREAM = P('the-keystream.geocities.ws', 'KEYSTREAM',
  'the keystream // the ribbon everything hangs on', [
    '<!--bg:cryp-symmetric-->',
    '<h1>the keystream</h1>',
    '<p class="fs-epi">“The security of a stream cipher is the security of its',
    'keystream, and nothing else.” — a sci.crypt truism</p>',
    '<p><small>one idea, read closely. the stream of bytes a stream cipher makes,',
    'and the two rules it must never break. — a keeper of the crypto ring</small></p>',
    '<hr>',
    '<p>The keystream is the ribbon of pseudo-random bytes a stream cipher',
    'generates from the key. It is not the message and it is not the key; it is',
    'what the key is STRETCHED into, and the whole cipher is nothing more than',
    'message XOR keystream. So everything the cipher promises rests on this one',
    'stream being good. Two rules, and both are absolute.</p>',
    '<p><b>Rule one: it must be unpredictable.</b> An attacker who can guess the',
    'next byte of the keystream can strip it off the ciphertext and read the',
    'message. Pseudo-random is not enough on its own; it must be',
    'CRYPTOGRAPHICALLY pseudo-random, meaning that even after seeing a long',
    'stretch of output you cannot predict the next byte any better than chance.',
    'A generator that merely looks random to the eye, but whose internal state a',
    'clever observer can reconstruct, is no keystream at all.</p>',
    '<img class="indie-pic" src="assets/media/web/cryp/turing-01.jpg" alt=""><span class="indie-cap">Alan Turing, who broke the Enigma keys (public domain)</span>',
    '<div class="fs-aside"><p><b>The classic that is NOT enough on its own: the',
    'LFSR.</b> A linear feedback shift register is a beautiful little hardware',
    'generator: a row of bits, tapped and XOR-ed and shifted, spilling out a long',
    'stream that passes every simple randomness test. It is fast and cheap and it',
    'was everywhere. It is also LINEAR, and linear means solvable: observe a',
    'handful of output bits (about twice the register length) and you can solve',
    'for the whole internal state and predict the rest forever. A bare LFSR makes',
    'a predictable keystream. Real designs combine several non-linearly, or add a',
    'non-linear step, precisely to break that linearity.</p></div>',
    '<p><b>Rule two: it must never be reused.</b> This is the harder discipline.',
    'Use the same keystream on two messages and the XOR of the two ciphertexts',
    'equals the XOR of the two plaintexts, the keystream cancelled clean out of',
    'the sum.</p>',
    '<pre>',
    '  c1 = m1 XOR ks',
    '  c2 = m2 XOR ks',
    '  ------------------------------',
    '  c1 XOR c2 = m1 XOR m2       <- the keystream is GONE',
    '',
    '  the attacker now has m1 XOR m2 and, with a little knowledge of what',
    '  the plaintexts might be, pulls the two messages apart. this is the',
    '  “two-time pad”, and it has sunk real systems.',
    '</pre>',
    '<p>That is why RC4 and its kin derive a fresh keystream for every message,',
    'usually by mixing a per-message nonce into the key, and why reusing a nonce',
    'is a cardinal sin. The mechanism that makes RC4’s stream is set out at',
    '<a href="rc4.geocities.ws">rc4</a>; the family it belongs to, and why the',
    'keystream must not repeat, is read more widely at',
    '<a href="the-stream-cipher.geocities.ws">the-stream-cipher</a>.</p>',
    '<p class="fs-pull">A predictable keystream is a lock whose key you left in',
    'the door.</p>',
    '<p>The modern generator has moved on from the bare shift register to designs',
    'built to resist prediction even by an adversary who has watched a great deal',
    'of output. The requirement never changed: unpredictable, and used exactly',
    'once. Meet both and the stream cipher is sound. Fail either and the elegant',
    'XOR hands the message straight back.</p>',
    '<hr>',
    '<p><small>counter: 00838 · best viewed at 800x600 · a crypto-webring page ·',
    'last updated 17 Dec</small></p>',
    '<p><small>[ <a href="cryptography-ring.geocities.ws">Cryptography Ring</a> ]</small></p>',
  ]);

export const CRYP_B = [RC4, STREAM_CIPHER, XOR_REPEATING, ENIGMA, DES, KEYSTREAM];
