// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// PUBLIC SERVICE BROADCASTING — batch B, before and after the institution.
//
// Marconi, because the whole archive had not one page on him and broadcasting
// has to start somewhere; and the Computer Literacy Project, because the `home`
// web already has the BBC Micro as a MACHINE and nobody had it as a POLICY.
// The machine page belongs with the Spectrum and the Amstrad. This one belongs
// next to the licence fee, which is what paid for it.
//
// Images: assets/media/web/psb, all PD or CC BY-SA, see PROVENANCE.md there.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Marconi ---------------------------------------------------------------

const MARCONI = P('marconi.geocities.ws', 'MARCONI',
  'MARCONI // the signal that should not have arrived', [
    '<!--bg:proto-->',
    '<h1>MARCONI</h1>',
    '<p><small>somebody on the ring pointed out we had four pages on what',
    'broadcasting was FOR and none on how the signal got out of the room. so.',
    '— posted by A. Whitlock</small></p>',
    '<img class="indie-pic" src="assets/media/web/psb/marconi.jpg" alt=""><span class="indie-cap">Guglielmo Marconi (photo: Pach Brothers, public domain)</span>',
    '<hr>',
    '<p>Guglielmo Marconi did not discover radio waves. Hertz had done that,',
    'and Maxwell had predicted them before Hertz found them. What Marconi did,',
    'from about 1894, was refuse to treat them as a laboratory curiosity. He was',
    'twenty, he was working in his father’s attic at Pontecchio, and the thing',
    'he had that the physicists did not was an interest in distance.</p>',
    '<p>He took the apparatus outdoors and made it go further, and then further,',
    'and the whole subsequent history of the twentieth century is downstream of',
    'that stubbornness.</p>',
    '<h2>Poldhu, December 1901</h2>',
    '<img class="indie-pic" src="assets/media/web/psb/poldhu.jpg" alt=""><span class="indie-cap">The transmitting station at Poldhu, Cornwall, 1900 (photo: John Ambrose Fleming, public domain)</span>',
    '<p>The station at Poldhu in Cornwall sent the letter S, three dots, and',
    'Marconi reported hearing it at St John’s, Newfoundland, on 12 December',
    '1901. Across the Atlantic.</p>',
    '<p>It should not have worked. The physics of the day said radio waves',
    'travelled in straight lines, and the Earth is not straight; the signal',
    'ought to have gone off into space somewhere over the middle of the ocean.',
    'People said so at the time, and some of them said Marconi had heard',
    'atmospheric noise and wanted it to be an S.</p>',
    '<p>They were right about the physics and wrong about the result. What',
    'nobody knew in 1901 was that there is a layer of charged particles high in',
    'the atmosphere that bounces the signal back down. Kennelly and Heaviside',
    'proposed it the next year and it took until the 1920s to be settled. The',
    'transmission worked because of a piece of the world nobody had discovered',
    'yet.</p>',
    '<p>Whether that particular S was really heard is still argued over. I have',
    'read both sides and I do not know. What is not argued over is that within a',
    'few years the thing was routine.</p>',
    '<h2>What he actually built</h2>',
    '<p>Not a broadcaster. That is the thing to hold on to. Marconi built',
    '<i>wireless telegraphy</i>: point to point, one station to one station,',
    'ships to shore, the same messages the cables carried but without the cable.',
    'A private channel that happened to have no wire in it.</p>',
    '<p>The fact that anyone with a receiver could hear it was a problem to be',
    'solved, not a feature. He spent years trying to make transmissions',
    'selective, so that only the intended station could pick them up.</p>',
    '<p>Broadcasting, meaning deliberately transmitting to whoever happens to be',
    'listening, arrives later and arrives as an accident of that failure. The',
    'medium turned out to be one-to-many and the industry spent two decades',
    'working out that this was the point rather than the flaw. Everything on the',
    'rest of this ring, the charters and the fees and the committees, is people',
    'trying to decide what to do about a channel that reaches everybody, which',
    'is a problem nobody had before Marconi could not stop it happening.</p>',
    '<h2>The Titanic, and what followed</h2>',
    '<p>In April 1912 the wireless operators aboard the Titanic were Marconi',
    'employees. The distress calls were heard, the Carpathia turned, and around',
    'seven hundred people were taken off. Marconi was called before the inquiry',
    'and treated as a hero, and the regulations that followed required ships to',
    'keep a listening watch around the clock.</p>',
    '<p>The other half of that story is the part about interference: amateur',
    'transmissions clogging the band, false reports circulating, no agreement',
    'about who had the right to use which frequency. The Radio Act of 1912 in',
    'the United States followed within months. Licensing arrives with the first',
    'disaster, which is roughly when it always arrives.</p>',
    '<hr>',
    '<p>See also <a href="founding-of-the-bbc.geocities.ws">the founding of the',
    'BBC</a>, which is what the manufacturers did with the medium once they had',
    'it.</p>',
    '<hr>',
    '<p><small>counter: 00156 · best viewed at 800x600</small></p>',
    '<p><small>',
    '[ <a href="public-service-ring.geocities.ws">Public Service Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- the Computer Literacy Project -----------------------------------------

const CLP = P('computer-literacy-project.geocities.ws', 'COMPUTER LITERACY PROJECT',
  'COMPUTER LITERACY PROJECT // a broadcaster commissions a computer', [
    '<!--bg:proto-->',
    '<h1>COMPUTER LITERACY PROJECT</h1>',
    '<p><small>there is a good page on the <a href="bbc-micro.geocities.ws">BBC',
    'Micro</a> over on the home computing ring and i am not going to repeat it.',
    'that page is about the machine. this one is about why a television company',
    'was commissioning hardware at all, which nobody seems to write about and',
    'which is the strange part.</small></p>',
    '<img class="indie-pic" src="assets/media/web/psb/bbcmicro.jpg" alt=""><span class="indie-cap">The BBC Microcomputer (photo: Stuart Brady / Ubcule, public domain)</span>',
    '<hr>',
    '<h2>The odd thing</h2>',
    '<p>Around 1980 the BBC decided the country was going to need to understand',
    'computers, and that it should do something about it. Fine. A broadcaster',
    'makes a television series about computing. That is an ordinary thing for a',
    'broadcaster to do.</p>',
    '<p>What is not ordinary is the next step. They concluded that a series',
    'would be useless unless viewers could do the things on screen themselves,',
    'that the machines then on sale were incompatible with each other, and that',
    'therefore they had better specify a machine. They wrote a specification,',
    'put it out to tender, and Acorn in Cambridge built it.</p>',
    '<p>Read that again, because it is genuinely peculiar. A public broadcaster',
    'defined a computer architecture, put its own name on the case, and sold it',
    'into schools, as an educational intervention, funded by a licence fee.</p>',
    '<h2>The series and the machine together</h2>',
    '<p>The point was that the two were one thing. The programme showed a line',
    'of BASIC and you typed the same line into the same machine and got the same',
    'result. There was no gap between watching and doing, and no translation',
    'layer where your computer was not the one on the television.</p>',
    '<p>The machine went into schools in enormous numbers. A generation of',
    'people in this country learned what a computer was on one, which is why the',
    'nostalgia is so thick and why it is worth being careful about the',
    'nostalgia.</p>',
    '<h2>What it assumed</h2>',
    '<p>That literacy means writing and not only reading. The whole design took',
    'for granted that a person who is going to live among computers should be',
    'able to make one do something, and that this was a public matter, like',
    'being able to read a timetable.</p>',
    '<p>The machine boots into a language. Not into a desktop, not into a store,',
    'into a prompt where the expected next thing is that you type an',
    'instruction. Whatever else that is, it is a claim about what the person in',
    'front of it is for.</p>',
    '<p>I do not want to overdo this. It was also an expensive machine, sold',
    'largely into schools, in a country that had just decided to close a lot of',
    'other things; and Acorn made a great deal of money; and plenty of children',
    'used it to play Elite and learned nothing whatever about computing, which',
    'is their right.</p>',
    '<p>But the assumption is there in the hardware and it is not there in',
    'anything I have bought since. Every machine I own now boots into a place',
    'where things are chosen rather than written.</p>',
    '<h2>The tail</h2>',
    '<p>Acorn went on from the BBC Micro to design its own processor, because',
    'the parts available were not good enough for what it wanted to do next.',
    'That processor is the one now in a very large proportion of the phones on',
    'earth. There is a page about that on <a href="arm-story.geocities.ws">the',
    'home computing ring</a> and it is a better page than mine.</p>',
    '<p>So the sequence is: a licence fee paid a broadcaster, which specified a',
    'teaching machine, whose maker built a processor, which ended up in almost',
    'every pocket. Nobody planned that and nobody could have.</p>',
    '<hr>',
    '<p>See also <a href="ceefax.geocities.ws">Ceefax</a>, the other thing the',
    'BBC built that was not television.</p>',
    '<hr>',
    '<p><small>counter: 00174 · under construction · i want to add the',
    'specification document if anyone has a scan</small></p>',
    '<p><small>',
    '[ <a href="public-service-ring.geocities.ws">Public Service Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const PSB_B = [MARCONI, CLP];
