// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH D. The deep-learning explosion.
//
// Fan pages, kept on a free host, each ABOUT a figure, dataset, system or
// episode and never in the subject's own voice. A devotee's shrine to Fei-Fei
// Li and ImageNet; a breathless write-up of the 2012 night the field turned
// over (the showpiece, with a pull-quote and two pictures); a fan's page for
// Hinton that will not duck the row over his warnings; a sober summary of
// LeCun and Bengio; a talk write-up of AlphaGo and Move 37; and clean notes on
// reinforcement learning. The names, papers and dates are real; the awe and the
// opinions are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Fei-Fei Li & ImageNet: the devotee's shrine ----------------------------

const IMAGENET = P('imagenet-fei-fei.geocities.ws', 'IMAGENET',
  'FEI-FEI LI & IMAGENET // data was the missing thing', [
    '<!--bg:deeplearning-->',
    '<h1>FEI-FEI LI &amp; IMAGENET</h1>',
    '<p><small>a shrine, kept by a lab assistant who spent one whole summer',
    'drawing boxes round cats for a labelling job and came out the other side a',
    'believer. everyone worships the algorithms. i am here for the DATA and the',
    'woman who saw it first. R.</small></p>',
    '<p class="fs-epi">"If you want to teach a machine to see, you first have to',
    'give it something to look at." That is the argument, more or less.</p>',
    '<hr>',
    '<p>Here is the thing the textbooks skate over. For years the whole field',
    'chased cleverer and cleverer algorithms and got almost nowhere on real',
    'pictures, and the reason was not the algorithms. It was that the machines had',
    'never SEEN enough. A child sees millions of things before it can name a dog.',
    'Fei-Fei Li took that seriously when almost nobody else did.</p>',
    '<p>She was born in Beijing in 1976, came to the United States as a teenager,',
    'ran a dry-cleaning shop with her family while she studied, and ended up doing',
    'computer vision at Princeton and then Stanford. Around 2006 she started on an',
    'idea that colleagues thought was, to be polite, a waste of a young careers.',
    'Not a new model. A DATASET. An enormous one.</p>',
    '<h2>the build</h2>',
    '<p>ImageNet was mapped onto WordNet, the big tree of English nouns, so every',
    'category sat in a proper hierarchy: animal, then mammal, then dog, then the',
    'breeds. Then the pictures had to be found and, harder, LABELLED, and there',
    'were meant to be millions. No lab could pay for that by hand. The answer was',
    'Amazon Mechanical Turk, thousands of workers across the world tagging images',
    'a fraction of a penny at a time. That labour is the hidden foundation of the',
    'whole modern boom, and it is worth saying so out loud.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/feifei-01.jpg" alt=""><span class="indie-cap">Fei-Fei Li (photo: ITU Pictures, CC BY)</span>',
    '<p>By 2009 there were around fourteen million labelled images across some',
    'twenty-two thousand categories, and the paper "ImageNet: A Large-Scale',
    'Hierarchical Image Database" (Deng, Dong, Socher, Li, Li and Fei-Fei Li,',
    'CVPR 2009) put it in front of the field. It was given away free.</p>',
    '<h2>the challenge</h2>',
    '<p>From 2010 there was an annual contest, the ImageNet Large Scale Visual',
    'Recognition Challenge, where teams competed to classify a slice of the set',
    'and the error rates were posted for all to see. For two years the numbers',
    'crept down slowly. Then in 2012 something walked in and knocked the error',
    'nearly in half in a single go, and the whole discipline changed its mind in',
    'an afternoon. That story has its own page, and you should go and read it: the',
    'night is written up at',
    '<a href="alexnet-2012.geocities.ws">alexnet-2012</a>.</p>',
    '<blockquote class="fs-quote"><p>The algorithms did not suddenly get clever.',
    'They finally got fed.</p></blockquote>',
    '<p>The deeper argument, and the one i keep pressing on people, is that the',
    'statistical turn had prepared the ground (all that is set out over at',
    '<a href="statistical-ml.geocities.ws">statistical-ml</a>), but it took a',
    'dataset of this size to show what those methods could really do. Data was not',
    'the boring part. Data was the missing ingredient.</p>',
    '<div class="fs-aside"><p>She did not stop. Later she pushed "human-centred"',
    'AI at Stanford, co-founded the outreach effort AI4ALL to widen who gets into',
    'the field, and did a stint as chief scientist for AI at Google Cloud. Her',
    'memoir, <i>The Worlds I See</i> (2023), tells the ImageNet story from the',
    'inside, dry-cleaning shop and all.</p></div>',
    '<hr>',
    '<p>Why it matters now, with the machines gone quiet: everyone remembers the',
    'models and forgets that a model is only ever as good as what it was shown,',
    'and who was paid what to show it. Keep an eye on the dataset. That is the',
    'lesson she taught the field whether the field thanks her for it or not.</p>',
    '<hr>',
    '<p>Neighbours. The night it all paid off is at',
    '<a href="alexnet-2012.geocities.ws">alexnet-2012</a>, and the run-up in',
    'method is at <a href="statistical-ml.geocities.ws">statistical-ml</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01209 · best viewed at 800x600 · labelled by hand, mostly',
    '· under construction, more on AI4ALL soon · last updated 8 Mar</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a proud member. &laquo; prev · random · next &raquo;',
    '</small></p>',
  ]);

// ---- AlexNet 2012: the showpiece talk write-up ------------------------------

const ALEXNET = P('alexnet-2012.geocities.ws', 'ALEXNET 2012',
  'ALEXNET, 2012 // the night the field turned over', [
    '<!--bg:deeplearning-->',
    '<h1>ALEXNET, 2012</h1>',
    '<p><small>i went to a retrospective panel where three people who were in the',
    'room in 2012 told the story again, and i came home and typed it up before i',
    'lost it. corrections welcome, i was scribbling in the dark. a grad student',
    'who now knows exactly where he was.</small></p>',
    '<hr>',
    '<p>Set the scene. It is autumn 2012. Computer vision is a respectable, patient',
    'field where progress on the ImageNet challenge comes a percentage point at a',
    'time and everyone hand-crafts their features. The best systems the year before',
    'were sitting around a twenty-six per cent top-five error. That is the world',
    'that walked into the room. It is not the world that walked out.</p>',
    '<p>Three people from Geoffrey Hinton\'s group in Toronto entered the challenge:',
    'Alex Krizhevsky, who did the heroic engineering and whose name the thing now',
    'carries; Ilya Sutskever; and Hinton himself. They ran a deep convolutional',
    'neural network, eight layers, sixty million parameters, the kind of thing that',
    'had been written off as a dead end for twenty years.</p>',
    '<p class="fs-pull">Fifteen per cent. The runner-up was on twenty-six. Nobody',
    'in the room had ever seen a jump like it.</p>',
    '<p>The top-five error came in around fifteen point three per cent against the',
    'next team\'s twenty-six point two. In a field that measured its life in',
    'fractions of a point, that was not an improvement. That was a different',
    'century arriving early.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/gpu-01.jpg" alt=""><span class="indie-cap">a modern GPU (photo: Geekerwan, CC BY)</span>',
    '<h2>how they did it</h2>',
    '<p>The panel was good on the three things that mattered, so here they are.</p>',
    '<p>ONE, the hardware. They trained the thing on two consumer NVIDIA GTX 580',
    'graphics cards, gaming GPUs, in a bedroom more or less, not on some national',
    'supercomputer. The network was split across the two cards because that was all',
    'the memory there was. The speaker made the point that the whole revolution',
    'rode in on the back of the games industry, which had spent a decade building',
    'cheap parallel silicon to draw explosions.</p>',
    '<p>TWO, the tricks that made a deep net actually train. They used ReLU units,',
    'which learn far faster than the old smooth activation functions, and they used',
    'a brand-new regularisation trick called dropout, from the Toronto group, that',
    'randomly switches off half the neurons during training so the net cannot lean',
    'on any one path. Together these stopped a deep network from stalling or',
    'over-fitting the way everyone expected it to.</p>',
    '<p>THREE, and this is the bit the ImageNet people never let you forget, the',
    'DATA. None of it works without the million-plus labelled pictures Fei-Fei Li\'s',
    'team had spent years assembling. The engine and the fuel arrived at the same',
    'time. Read the fuel\'s story at',
    '<a href="imagenet-fei-fei.geocities.ws">imagenet-fei-fei</a>.</p>',
    '<blockquote class="fs-quote"><p>"ImageNet Classification with Deep',
    'Convolutional Neural Networks", Krizhevsky, Sutskever and Hinton, presented',
    'at NIPS, December 2012. Ten pages. It has been cited more times than anyone',
    'can now count.</p></blockquote>',
    '<p>&nbsp;</p>',
    '<h2>what the room did</h2>',
    '<p>The story everyone tells is of the session where the result was shown. The',
    'panellist said you could feel the mood change. Half the audience understood at',
    'once that the ground had shifted and their careers with it, and the other half',
    'spent the coffee break arguing that it was a fluke, that convolutional nets',
    'were a toy, that it would not generalise. Within about a year almost every',
    'serious vision group had thrown out its hand-crafted pipeline and gone deep.',
    'The venture money noticed a beat later. Google bought Hinton\'s tiny company',
    'not long after.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/neuralnet-01.jpg" alt=""><span class="indie-cap">a convolutional network (Cecbur, CC BY-SA)</span>',
    '<div class="fs-aside"><p>None of the three ideas was truly new that night.',
    'Convolutional nets went back to LeCun in the 1980s and 1990s (see',
    '<a href="hinton-deep.geocities.ws">hinton-deep</a> for the man who supervised',
    'the winning team). What was new was that all the pieces, the method, the',
    'hardware and the data, were finally in the same place at the same time. That',
    'is usually how these things go.</p></div>',
    '<hr>',
    '<p>Why it matters now, with the boom long crested: this is the hinge. Before',
    'it, artificial intelligence mostly meant rules and search and careful',
    'engineering. After it, for better and worse, it meant deep networks trained on',
    'oceans of data, and everything that followed, the whole roaring decade, ran',
    'through this one result. If you want to understand how the field got where it',
    'got, you start in this room.</p>',
    '<hr>',
    '<p>Neighbours. The dataset that made it possible is at',
    '<a href="imagenet-fei-fei.geocities.ws">imagenet-fei-fei</a>, and the man who',
    'was the third name on the paper is at',
    '<a href="hinton-deep.geocities.ws">hinton-deep</a>.</p>',
    '<hr>',
    '<p><small>counter: 03370 · best viewed at 800x600 · typed up from bad notes ·',
    'this page will be revised when i stop being excited about it · last updated',
    '14 Dec</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a proud member. &laquo; prev · random · next &raquo;',
    '</small></p>',
  ]);

// ---- Geoffrey Hinton: the fan who will not duck the row ---------------------

const HINTON = P('hinton-deep.geocities.ws', 'HINTON',
  'GEOFFREY HINTON // the godfather, and the warning', [
    '<!--bg:deeplearning-->',
    '<h1>GEOFFREY HINTON</h1>',
    '<p><small>a fan page, kept by someone who read the 1986 backprop paper as an',
    'undergraduate and has followed him ever since, through the wilderness years',
    'when nobody would fund a neural net and everyone said he was wasting his',
    'life. he was not. d.</small></p>',
    '<hr>',
    '<p>They call him the godfather of deep learning and for once the nickname is',
    'earned. Geoffrey Hinton, born in London in 1947, great-great-grandson of the',
    'logician George Boole as it happens, spent decades insisting that the way to',
    'build a mind was to train networks that learn their own features, at a time',
    'when the whole field had decided that was a dead end.</p>',
    '<h2>the work</h2>',
    '<p>The greatest hits, roughly in order. In 1986, with David Rumelhart and',
    'Ronald Williams, the paper that made backpropagation famous and gave',
    'multi-layer networks a way to actually learn. Through the',
    '1980s, with Terry Sejnowski, the Boltzmann machine. In 2006, the work on',
    'deep belief networks that got the word "deep" back into circulation. And in',
    '2012, dropout, and the supervision of the ImageNet-winning team that turned',
    'the whole field over in one night (that night is at',
    '<a href="alexnet-2012.geocities.ws">alexnet-2012</a>).</p>',
    '<img class="indie-pic" src="assets/media/web/ai/hinton-01.jpg" alt=""><span class="indie-cap">Geoffrey Hinton, 2024 (photo: Arthur Petron, CC BY-SA)</span>',
    '<p>In 2018 he shared the Turing Award, computing\'s top prize, with Yann LeCun',
    'and Yoshua Bengio, the other two of the trio who kept the faith through the',
    'lean years (they have their own page at',
    '<a href="lecun-bengio.geocities.ws">lecun-bengio</a>). Then in 2024, the one',
    'nobody predicted, a share of the Nobel Prize in Physics with John Hopfield,',
    'for the foundational work on learning in neural networks. A Nobel. In physics.',
    'For a man who spent years unable to get a grant.</p>',
    '<blockquote class="fs-quote"><p>"I have always been convinced that the only way',
    'to get artificial intelligence to work is to do the computation in a way',
    'similar to the human brain."</p></blockquote>',
    '<h2>Controversy: the warning</h2>',
    '<p>Here is where a fan has to be honest, because this is the loud part now. In',
    'the spring of 2023 Hinton resigned from Google, where he had worked for a',
    'decade, specifically so that he could speak freely about the dangers of the',
    'systems he had helped create. He said he had changed his mind about how close',
    'these machines were, and that a part of him regretted his life\'s work.</p>',
    '<p>He started warning, in plain language, that models might get smarter than',
    'us sooner than anyone expected, that they could be used by bad actors, and',
    'that we did not know how to keep control of something more capable than',
    'ourselves. He put real numbers, uncomfortable ones, on the chance of things',
    'going badly wrong.</p>',
    '<p>And the field split, in public, hard. His old Turing co-winner Yann LeCun',
    'took almost the opposite view, arguing that the doom talk was overblown, that',
    'current models are nowhere near that dangerous, and that fear would hand the',
    'whole field to a few big companies under the banner of safety. Yoshua Bengio,',
    'the third of the trio, came down closer to Hinton and turned much of his own',
    'work toward safety. So the three godfathers who spent thirty years agreeing',
    'that neural nets would work now cannot agree at all on what to do about the',
    'fact that they did.</p>',
    '<div class="fs-aside"><p>My own two cents, for what a fan\'s cents are worth.',
    'You do not have to think Hinton is right about the timelines to think it',
    'matters that the man who built the thing is the one pulling the alarm. He has',
    'nothing left to prove and no product to sell. When someone walks away from a',
    'salary like that to be free to worry in public, the worry is at least worth',
    'hearing out.</p></div>',
    '<hr>',
    '<p>Why he matters now, in the hush after the loud years: the same stubbornness',
    'that made him keep building networks when everyone said stop is the',
    'stubbornness that now makes him say stop when everyone wants to keep building.',
    'It is the same man. He followed the argument where it went both times.</p>',
    '<hr>',
    '<p>Neighbours. The night his students proved him right is at',
    '<a href="alexnet-2012.geocities.ws">alexnet-2012</a>, and the two colleagues',
    'he shared the prize and now the quarrel with are at',
    '<a href="lecun-bengio.geocities.ws">lecun-bengio</a>. The bigger fight over',
    'whether any of these systems really think is running over on the chatbots',
    'web at <a href="can-machines-think.geocities.ws">can-machines-think</a>.</p>',
    '<hr>',
    '<p><small>counter: 02611 · best viewed at 800x600 · kept by a believer, not a',
    'neutral · last updated 21 Oct</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'a proud member. &laquo; prev · random · next &raquo;',
    '</small></p>',
  ]);

// ---- LeCun & Bengio: the sober academic summary -----------------------------

const LECUN_BENGIO = P('lecun-bengio.geocities.ws', 'LECUN & BENGIO',
  'LeCUN & BENGIO // the other two of the trio', [
    '<!--bg:deeplearning-->',
    '<h1>LeCUN &amp; BENGIO</h1>',
    '<p><small>a plain summary, kept up to date as best i can. the third of the',
    '2018 Turing trio, Geoffrey Hinton, has his own page next door. this one is',
    'for the other two. Maintained for a study group.</small></p>',
    '<hr>',
    '<p>The 2018 Turing Award went jointly to three people for making deep learning',
    'work: Geoffrey Hinton (see <a href="hinton-deep.geocities.ws">hinton-deep</a>),',
    'Yann LeCun and Yoshua Bengio. This page covers the latter two. They agreed for',
    'thirty years on the science and, lately, have come apart in public over what',
    'it means, which is a story in itself.</p>',
    '<h2>Yann LeCun</h2>',
    '<p>Born in France in 1960. In the late 1980s and through the 1990s, first at',
    'Bell Labs, LeCun built the convolutional neural network into a working tool.',
    'His LeNet, developed roughly from 1989 to 1998, took the idea of local',
    'receptive fields and weight-sharing, trained it with backpropagation, and read',
    'handwritten digits well enough that it went into real service reading the',
    'numbers on bank cheques. That was deep learning doing a paying job years',
    'before the word was fashionable.</p>',
    '<p>The key paper, "Gradient-Based Learning Applied to Document Recognition"',
    '(LeCun, Bottou, Bengio and Haffner, 1998), is one of the foundations, and the',
    'MNIST digit dataset that came out of that world is still the first thing every',
    'student trains a net on. The architecture he pioneered is exactly the kind',
    'that won ImageNet in 2012.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/lecun-01.jpg" alt=""><span class="indie-cap">Yann LeCun (photo: Jeremy Barande, CC BY-SA)</span>',
    '<p>Later LeCun became chief AI scientist at Meta and, notably, a sceptic about',
    'the current large language models. His argument is that predicting the next',
    'word off a mountain of text is not the road to real understanding, that these',
    'systems have no world model and no grounding, and that the field is over-',
    'invested in one trick. He has been pushing his own alternative, built around',
    'models that learn how the world works rather than just how text reads. On the',
    'question of danger he is the field\'s leading optimist, which puts him squarely',
    'against Hinton.</p>',
    '<h2>Yoshua Bengio</h2>',
    '<p>Born in France in 1964, based for his whole career in Montreal, where he',
    'built one of the great deep-learning labs. Bengio\'s contributions run through',
    'the theory: early work on training deep networks, on learning word',
    'representations, and, importantly, on the attention mechanism. The paper by',
    'Bahdanau, Cho and Bengio (2014) introduced attention for machine translation,',
    'and attention is the idea the transformer would later build an entire',
    'architecture around (that story is at',
    '<a href="transformers-2017.geocities.ws">transformers-2017</a>).</p>',
    '<p>In recent years Bengio has turned much of his attention to safety. He has',
    'led international assessments of the risks, signed and helped write the open',
    'letters, and argued that the field needs guard-rails before capability runs',
    'ahead of understanding. On the danger question he sits close to Hinton and',
    'well away from LeCun, which means the 2018 trio now holds two of the three',
    'main positions in the argument between them.</p>',
    '<h2>a short critical note</h2>',
    '<p>It is worth noticing that the same three people who were told for decades',
    'that neural networks would never amount to anything now disagree profoundly',
    'about what those networks amount to. The science united them. The consequences',
    'did not. That disagreement is not a weakness in the field, it is the field',
    'doing its arguing where everyone can see it.</p>',
    '<hr>',
    '<p>Neighbours. The third of the trio and the fight over the warnings is at',
    '<a href="hinton-deep.geocities.ws">hinton-deep</a>, and the architecture',
    'Bengio\'s attention work led to is at',
    '<a href="transformers-2017.geocities.ws">transformers-2017</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01488 · best viewed at 800x600 · corrections to the study',
    'group · last updated 2 Sep</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a member. &laquo; prev · random · next &raquo;',
    '</small></p>',
  ]);

// ---- AlphaGo & DeepMind: the talk write-up ----------------------------------

const ALPHAGO = P('alphago-2016.geocities.ws', 'ALPHAGO',
  'ALPHAGO / DEEPMIND // Move 37 and what came after', [
    '<!--bg:deeplearning-->',
    '<h1>ALPHAGO / DEEPMIND</h1>',
    '<p><small>i went to hear a DeepMind researcher give an evening lecture on the',
    'Go match and everything that grew out of it, and these are my notes, tidied.',
    'the room was full of people who play Go and people who write code and not',
    'many who do both. a note-taker in the third row.</small></p>',
    '<hr>',
    '<p>The speaker started with the problem, because you have to understand the',
    'problem to feel the result. Go is not chess. The board is nineteen by',
    'nineteen, the number of possible positions is larger than the atoms in the',
    'observable universe, and you cannot win by brute-force search the way Deep',
    'Blue beat Kasparov in 1997. For decades Go was the standing proof that there',
    'was something machines could not do. The best programs played like a keen',
    'amateur and no better.</p>',
    '<p>DeepMind, the London lab founded in 2010 by Demis Hassabis, Shane Legg and',
    'Mustafa Suleyman, and bought by Google in 2014, set out to break it. Hassabis',
    'is a former chess prodigy and games designer, which the speaker clearly',
    'thought was the whole point: this is a person who thinks in games.</p>',
    '<h2>the match</h2>',
    '<p>In March 2016, in Seoul, their program AlphaGo played Lee Sedol, one of the',
    'greatest players alive, over five games, and won four to one. It was watched',
    'live by tens of millions. AlphaGo combined a deep neural network that had',
    'learned from human games and from playing itself with a tree search guided by',
    'that network, so it had both intuition and calculation.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/goboard-01.jpg" alt=""><span class="indie-cap">a Go board (photo: Culture Japon, CC BY-SA)</span>',
    '<p>Then the speaker got to Move 37, and the room went quiet, because half of',
    'them had watched it live. In the second game AlphaGo played a move on the',
    'fifth line that no professional would have chosen, that looked like a mistake,',
    'that one commentator said must be an error. It was not an error. It was deep,',
    'and it won, and Lee Sedol left the room to compose himself. The speaker\'s',
    'phrase for it stuck with me: the machine had played something no human had',
    'taught it and no human would have dared.</p>',
    '<blockquote class="fs-quote"><p>"It\'s not a human move. I\'ve never seen a human',
    'play this move," said a commentator on Move 37.</p></blockquote>',
    '<p>He was fair, though, and mentioned that Lee Sedol won game four with a',
    'brilliant move of his own, sometimes called the divine move, that AlphaGo had',
    'no answer to. The machine was not perfect. It was just, on the whole, better.</p>',
    '<h2>what came after</h2>',
    '<p>The second half of the talk was about how fast it moved on. In 2017 came',
    'AlphaGo Zero, and then AlphaZero, which threw away the human games entirely',
    'and learned Go, chess and shogi from nothing but the rules and millions of',
    'games against itself, in a matter of hours, and beat everything that came',
    'before it. Learning purely by self-play and reward, which is the engine',
    'described over at',
    '<a href="reinforcement-learning.geocities.ws">reinforcement-learning</a>.</p>',
    '<p>And then the turn that the speaker plainly cared about most. DeepMind',
    'pointed the same kind of method at a real scientific problem, and in 2020',
    'AlphaFold cracked the prediction of protein structures at the CASP contest,',
    'solving a problem biologists had chewed on for fifty years. In 2024 Hassabis',
    'and John Jumper shared the Nobel Prize in Chemistry for it. A games company',
    'won a chemistry Nobel. The room, mostly, understood why that was the real',
    'headline.</p>',
    '<hr>',
    '<p>Why it matters now, looking back on it: the Go match was the moment the',
    'public felt the thing move, the way the field had felt it move in 2012 (that',
    'earlier hinge is at <a href="imagenet-fei-fei.geocities.ws">imagenet-fei-fei</a>).',
    'A machine did something graceful and strange in a game we thought was ours,',
    'and then the same trick started reading the shape of proteins. It was never',
    'only about the game.</p>',
    '<hr>',
    '<p>Neighbours. The learning-by-reward engine underneath it is at',
    '<a href="reinforcement-learning.geocities.ws">reinforcement-learning</a>, and',
    'the dataset moment that opened the whole decade is at',
    '<a href="imagenet-fei-fei.geocities.ws">imagenet-fei-fei</a>.</p>',
    '<hr>',
    '<p><small>counter: 02047 · best viewed at 800x600 · notes from row three, any',
    'errors are mine not the speaker\'s · last updated 30 Apr</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a proud member. &laquo; prev · random · next &raquo;',
    '</small></p>',
  ]);

// ---- Reinforcement learning: clean academic summary -------------------------

const REINFORCEMENT = P('reinforcement-learning.geocities.ws', 'RL',
  'REINFORCEMENT LEARNING // learning by reward', [
    '<!--bg:deeplearning-->',
    '<h1>REINFORCEMENT LEARNING</h1>',
    '<p><small>a summary page, kept clean on purpose. this is the branch of machine',
    'learning about agents, actions and rewards, and it turns up under a',
    'surprising amount of what made the news. for anyone starting out.</small></p>',
    '<hr>',
    '<p>Most machine learning is about labels: here is a picture, here is the word',
    '"cat", learn the mapping. Reinforcement learning is a different shape',
    'entirely. There is an agent in an environment. It takes an action, the world',
    'changes, and now and then it gets a reward or a penalty. It is never told the',
    'right answer directly. It has to work out, from the rewards alone, which',
    'actions were worth taking, sometimes long after the fact.</p>',
    '<h2>the core idea</h2>',
    '<p>The founding text is Richard Sutton and Andrew Barto,',
    '<i>Reinforcement Learning: An Introduction</i> (first edition 1998, a much',
    'expanded second edition in 2018). It is still the book people learn from. At',
    'its heart is the reward hypothesis: the claim that everything we mean by goals',
    'and purposes can be framed as the maximising of expected cumulative reward.',
    'Bold, and arguable, and the whole field is built on it.</p>',
    '<p>The hard part is credit assignment. If you win a game of chess, which of',
    'your forty moves deserves the credit? The trick that cracked this is',
    'temporal-difference learning, Sutton\'s contribution, where the agent learns',
    'to predict future reward and nudges its predictions toward what actually',
    'happens, step by step, without waiting for the final score.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/sutton-01.jpg" alt=""><span class="indie-cap">Richard Sutton (photo: Steve Jurvetson, CC BY)</span>',
    '<p>The best-known method is Q-learning (Chris Watkins, 1989), where the agent',
    'learns a value for each action in each state, the long-run reward it can',
    'expect if it acts well from there on. Learn those values accurately and good',
    'behaviour falls out of always choosing the highest. Much of the mathematics',
    'goes back to Richard Bellman and dynamic programming in the 1950s, which is',
    'where the equations come from.</p>',
    '<h2>where it shows up</h2>',
    '<p>Two places make the point. First, self-play. AlphaGo and then AlphaZero',
    'learned superhuman play by reinforcement, taking the win or loss as the reward',
    'and improving over millions of games against themselves (the match is written',
    'up at <a href="alphago-2016.geocities.ws">alphago-2016</a>). The board game',
    'was the perfect testbed: a clear reward, at the end, win or lose.</p>',
    '<p>Second, and less obvious, the chat models. When a large language model is',
    'tuned to be helpful and to follow instructions, a big part of that is done',
    'with reinforcement learning from human feedback, where human preferences',
    'become the reward signal that shapes the model\'s behaviour. The same engine',
    'that taught a machine to play Go is part of what taught the chat systems their',
    'manners (the product side of that is on the chatbots web at',
    '<a href="chatgpt.geocities.ws">chatgpt</a>).</p>',
    '<h2>a short critical note</h2>',
    '<p>The catch is baked into the reward hypothesis. An agent maximises exactly',
    'what you reward it for, not what you meant, and specifying a reward that',
    'captures what you actually want turns out to be extremely hard. Agents find',
    'loopholes, game the score, and satisfy the letter of the reward while missing',
    'the point of it. That gap is a large part of what the safety people worry',
    'about, and it is not a detail, it is central.</p>',
    '<hr>',
    '<p>Neighbours. The self-play systems that showed what it could do are at',
    '<a href="alphago-2016.geocities.ws">alphago-2016</a>, and the architecture',
    'the tuned chat models are built on is at',
    '<a href="transformers-2017.geocities.ws">transformers-2017</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00933 · best viewed at 640x480 · kept deliberately plain ·',
    'last updated 17 Jun</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a member. &laquo; prev · random · next &raquo;',
    '</small></p>',
  ]);

export const AIH_D = [IMAGENET, ALEXNET, HINTON, LECUN_BENGIO, ALPHAGO, REINFORCEMENT];
