// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — motor & endurance.
//
// The pages a motorsport and cycling obsessive kept on a free host in the late
// 1990s: a shrine to Fangio, a sober retelling of Senna's last day, a profile of
// Merckx the Cannibal, a tribute to the Tour de France, a retelling of Le Mans,
// and an explainer of the Grand Prix. The register is the fan, the statistician
// and the amateur historian. Records, results and greatest-ever arguments. The
// drivers, dates and results are real; the enthusiasm is the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Fangio: the shrine (SHOWPIECE) -----------------------------------------

const FANGIO = P('juan-manuel-fangio.geocities.ws', 'FANGIO',
  'EL MAESTRO // a shrine to Juan Manuel Fangio', [
    '<!--bg:sport-motor-->',
    '<h1>EL MAESTRO</h1>',
    '<p><small>a shrine to Juan Manuel Fangio (1911&ndash;1995), kept by a man who',
    'has never driven anything faster than a Cortina but who knows greatness when',
    'he reads about it. corrections welcome, worship encouraged. &mdash; Trevor,',
    'club statistician</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;You must always believe you will become the best, but',
    'you must never believe you have done so.&rdquo; &mdash; Juan Manuel Fangio</p>',
    '<p>He came from Balcarce, a country town in the province of Buenos Aires, the',
    'son of an Italian immigrant plasterer. He was a mechanic before he was a',
    'racer, and he learned his craft on the brutal open-road races of South',
    'America, thousands of miles across the Andes on dirt and gravel, the sort of',
    'event that killed people every year. He did not reach the European',
    'championship until he was already in his late thirties, an age when most',
    'drivers are finished. It did not matter. He remains, for many who saw him and',
    'many more who only read the numbers, the greatest of them all.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/fangio-01.jpg" alt=""><span class="indie-cap">Juan Manuel Fangio (Museo Fangio, public domain)</span>',
    '<h2>Five titles, four marques</h2>',
    '<p>Between 1951 and 1957 Fangio won the Formula One World Championship five',
    'times, and he did it with four different manufacturers, which no one else has',
    'ever managed. Alfa Romeo, then Mercedes-Benz, then Ferrari, then Maserati. He',
    'did not sit in the best car and wait. He went where the best car was, and',
    'where it was not the best he made it look as though it were.</p>',
    '<pre>',
    'JUAN MANUEL FANGIO — WORLD CHAMPIONSHIPS',
    '=======================================',
    ' YEAR   MARQUE            NOTE',
    ' 1951   Alfa Romeo        his first title, the Alfetta 159',
    ' 1954   Maserati/Mercedes won for two teams in one season',
    ' 1955   Mercedes-Benz     the W196, dominant',
    ' 1956   Ferrari           the Lancia-Ferrari D50',
    ' 1957   Maserati          the 250F, and the greatest drive',
    '',
    ' 24 wins from 52 championship starts. 29 pole positions.',
    ' Five titles in seven seasons. Retired 1958.',
    '</pre>',
    '<p class="fs-pull">A win rate of nearly one race in two. No one before or since',
    'has come close to it over a career.</p>',
    '<h2>The N&uuml;rburgring, 1957</h2>',
    '<p>The drive people mean when they say he was the best came at the German',
    'Grand Prix of 1957, on the old N&uuml;rburgring, all fourteen miles and more',
    'than a hundred and seventy corners of it. Fangio gambled on a mid-race pit',
    'stop for fuel and tyres and came out far behind the two Ferraris of Hawthorn',
    'and Collins. What followed was a pursuit that has never been bettered. He broke',
    'the lap record again and again, by whole seconds, lapping a circuit that',
    'terrified everyone who drove it, and caught and passed both cars in the last',
    'laps to win. He was forty-six years old. He said afterwards that he had',
    'frightened himself, that he had done things that day he had never done before',
    'and would never do again.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/racing-car-01.jpg" alt=""><span class="indie-cap">A 1907 Grand Prix Brasier (L’Auto, public domain)</span>',
    '<p class="fs-aside"><b>DID YOU KNOW?</b> In February 1958, before a race in',
    'Havana, Fangio was kidnapped at gunpoint by rebels of Fidel Castro&rsquo;s',
    '26th of July Movement, who wanted the publicity. He was held for about a day',
    'and released unharmed. He spoke warmly of his captors afterwards and stayed in',
    'touch with one of them for years. He called it, with a shrug, one of the',
    'adventures of his life.</p>',
    '<h2>The grace of the man</h2>',
    '<p>What the records cannot show is the smoothness. Men who raced against him',
    'said he seemed never to hurry, that the car under him was never fighting,',
    'that he found a line and a rhythm the rest could only chase. Stirling Moss,',
    'who drove alongside him at Mercedes and rated himself second to no one, called',
    'Fangio the greatest he ever saw and counted it an honour to have finished',
    'behind him. He raced in the deadliest era the sport has known, when a season',
    'could take the lives of several of your friends, and he came through it, and',
    'he retired in one piece, and he went home to Balcarce.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;To race is to live. But those who died',
    'while racing knew, perhaps, how to live more than all the others.&rdquo;',
    '<br>&mdash; Fangio</p></blockquote>',
    '<hr>',
    '<p>If you want the machinery he mastered, read the <a href="the-grand-prix.geocities.ws">Grand',
    'Prix</a> page in this ring. And if you want to argue about who was the',
    'greatest of the modern age, you cannot avoid <a href="ayrton-senna.geocities.ws">Ayrton',
    'Senna</a>. Some of us think the two of them stand alone. Others put Jim Clark or',
    'Michael Schumacher up there too; that argument never ends, which is half the',
    'fun of it.</p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hit counter: 03571 · best viewed in Netscape at 800x600 · a proud',
    'member of the greatest-drivers webring · this shrine last updated 9 Nov · dedicated',
    'to my late father, who saw the 250F at Aintree</small></p>',
  ]);

// ---- Senna: the famous-event retelling --------------------------------------

const SENNA = P('ayrton-senna.geocities.ws', 'SENNA',
  'Imola, 1 May 1994 — remembering Ayrton Senna', [
    '<!--bg:sport-motor-->',
    '<h1>Imola, 1 May 1994</h1>',
    '<p><small>a page in memory of Ayrton Senna da Silva (1960&ndash;1994). i have',
    'tried to set down that weekend plainly and with respect. if you knew him only',
    'as a name, i hope this tells you why so many of us grieved. &mdash; Paulo</small></p>',
    '<hr>',
    '<p>He was Brazilian, from S&atilde;o Paulo, and he won the Formula One World',
    'Championship three times, in 1988, 1990 and 1991. The bare figures do not',
    'reach what he was. He drove as though the car were an argument he was winning,',
    'and in the wet, when grip vanished and other men slowed, he seemed to be on a',
    'dry road of his own. His pole lap at Monaco in 1988 is still spoken of as a',
    'thing not quite of this world; he said later he had gone into a kind of trance',
    'and had frightened himself, and had eased off. He won at Monaco six times, more',
    'than anyone.</p>',
    '<h2>The rivalry</h2>',
    '<p>For years his measure was Alain Prost, the calculating Frenchman they called',
    'the Professor. They were team-mates at McLaren and then enemies, and they',
    'collided, deliberately by most accounts, at Suzuka in 1989 and again in 1990,',
    'each collision settling a championship. It was the great feud of the age, the',
    'cool tactician against the driver of pure will. In time it cooled, and Prost,',
    'by then retired, was among the first he spoke of returning to when the new',
    'season began.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/senna-01.jpg" alt=""><span class="indie-cap">Ayrton Senna (Wikimedia Commons, freely licensed)</span>',
    '<h2>The weekend</h2>',
    '<p>The San Marino Grand Prix at Imola in 1994 was overshadowed before the race',
    'even began. On the Friday Rubens Barrichello had a heavy crash and was lucky to',
    'survive. On the Saturday the young Austrian Roland Ratzenberger was killed in',
    'qualifying, the first driver to die at a Grand Prix meeting in twelve years.',
    'Senna, who led the drivers on matters of safety, was shaken badly. Those close',
    'to him said he did not want to race.</p>',
    '<p>He started from pole. On the seventh lap, leading, his car left the road at',
    'the fast Tamburello corner and struck the concrete wall. He was airlifted to',
    'hospital in Bologna and died that evening, the first of May 1994. He was',
    'thirty-four.</p>',
    '<p class="fs-aside"><b>WHAT CAME AFTER.</b> Brazil held three days of national',
    'mourning and something like a million people lined the streets of S&atilde;o',
    'Paulo for the funeral. His death, with Ratzenberger&rsquo;s the day before,',
    'forced a thorough overhaul of safety in the sport, changes that have saved many',
    'lives since. It emerged that he had carried a furled Austrian flag in his car,',
    'to raise for Ratzenberger had he won.</p>',
    '<h2>What he left</h2>',
    '<p>He had faith, and he had a fierce sense that his gift was not only his. The',
    'Ayrton Senna Institute, founded by his sister with the fortune he left, has',
    'schooled millions of Brazilian children. In his own country he is not only a',
    'sportsman remembered but something closer to a patron of the poor. On the track',
    'he is the standard by which the fast are still measured.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;If you no longer go for a gap that exists,',
    'you are no longer a racing driver.&rdquo;<br>&mdash; Ayrton Senna, 1990</p></blockquote>',
    '<hr>',
    '<p>Older readers will want the other maestro of this ring, <a href="juan-manuel-fangio.geocities.ws">Juan',
    'Manuel Fangio</a>, who won five titles in the fifties; when Senna equalled one of',
    'Fangio&rsquo;s records the old man was there to shake his hand. For the machinery',
    'and the championship itself, see <a href="the-grand-prix.geocities.ws">the Grand',
    'Prix</a>.</p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>visitors: 02140 · best viewed at 800x600 · under construction, i keep',
    'adding to it · last updated 1 May, the anniversary · obrigado, Ayrton</small></p>',
  ]);

// ---- Merckx: the athlete profile --------------------------------------------

const MERCKX = P('eddy-merckx.geocities.ws', 'MERCKX',
  'THE CANNIBAL // Eddy Merckx, the greatest cyclist', [
    '<!--bg:sport-motor-->',
    '<h1>THE CANNIBAL</h1>',
    '<p><small>a tribute to Eddy Merckx (born 1945) by the secretary of a small',
    'cycling club who has bored every new member with these facts for twenty years.',
    'you are next. &mdash; Ken, hon. sec.</small></p>',
    '<hr>',
    '<p>They called him the Cannibal because he ate everything. Other riders would',
    'be grateful for a stage win, a day in front; Merckx wanted the stage and the',
    'next one and the mountains prize and the points and the whole race, and he',
    'wanted them all at once, and he took them. He is, by the ordinary reckoning of',
    'wins and titles, the greatest cyclist who ever rode a bicycle, and it is not a',
    'close argument.</p>',
    '<h2>What he won</h2>',
    '<p>Five Tours de France (1969, 1970, 1971, 1972 and 1974). Five Giri d&rsquo;Italia.',
    'A Vuelta a Espa&ntilde;a. Three World Championships on the road. And the',
    'one-day Monuments, the hardest single races there are, again and again: seven',
    'Milan&ndash;San Remos, five Li&egrave;ge&ndash;Bastogne&ndash;Li&egrave;ges,',
    'the Tour of Flanders, Paris&ndash;Roubaix. In his first Tour, in 1969, he won',
    'the overall race, the points jersey and the mountains classification all',
    'together, something no one had done and no one has done since.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/merckx-01.jpg" alt=""><span class="indie-cap">Eddy Merckx (photo: Foto43, CC BY 2.0)</span>',
    '<p class="fs-pull">He won roughly 525 races in his career. In the 1971 season',
    'alone he won 54 times.</p>',
    '<h2>The hour</h2>',
    '<p>In October 1972, in Mexico City, at altitude, Merckx set the Hour Record,',
    'the purest test in cycling: one rider, one track, sixty minutes, alone against',
    'the clock. He rode 49.431 kilometres. He said afterwards it was the hardest',
    'thing he had ever done and that he would never attempt it again, and he never',
    'did. The record stood for twelve years, and the manner of it, a man riding',
    'himself very nearly into the ground, became part of the legend.</p>',
    '<p>He was not loved everywhere. In France there was a feeling that he left',
    'nothing for anyone else, that a race needs a contest and Merckx would not',
    'grant one. At the 1975 Tour a spectator punched him in the liver on the climb',
    'of the Puy de D&ocirc;me; he rode on, in pain, and lost the race narrowly, and',
    'raced the next year regardless. He did not know another way to ride.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;Ride as much or as little, as long or as',
    'short as you feel. But ride.&rdquo;<br>&mdash; a line long attributed to',
    'Merckx</p></blockquote>',
    '<hr>',
    '<p>To understand the race he conquered, read <a href="the-tour-de-france.geocities.ws">the Tour',
    'de France</a> in this ring. And for the other great endurance test, the one on',
    'four wheels rather than two, see <a href="le-mans.geocities.ws">Le Mans</a>. If',
    'you want a modern rival for the greatest-ever crown, people will say Bernard',
    'Hinault or Lance Armstrong; the older heads in the clubhouse just smile and',
    'point at the palmar&egrave;s above.</p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01669 · best viewed at 800x600 · a member of the two-wheels',
    'webring · last updated 17 Jul · keep the rubber side down</small></p>',
  ]);

// ---- The Tour de France: the ORG/tournament page -----------------------------

const TOUR = P('the-tour-de-france.geocities.ws', 'TOUR DE FRANCE',
  'LE TOUR // the great race, since 1903', [
    '<!--bg:sport-motor-->',
    '<h1>LE TOUR</h1>',
    '<p><small>an enthusiast&rsquo;s guide to the Tour de France, maintained by a',
    'schoolteacher who plans the summer around three weeks of afternoon television.',
    '&mdash; Miss Hartley, Geography</small></p>',
    '<hr>',
    '<p>The Tour de France is the greatest endurance event in sport. Three weeks,',
    'more than three thousand kilometres, across the flat north and up over the',
    'Alps and the Pyrenees and home to Paris. It was founded in 1903 by the',
    'newspaper <i>L&rsquo;Auto</i>, whose editor Henri Desgrange dreamed up a race',
    'so hard it would sell papers by the terror of it. The first winner was Maurice',
    'Garin. It has run every year since except through the two world wars.</p>',
    '<h2>The jerseys</h2>',
    '<p>The leader of the whole race wears the yellow jersey, the <i>maillot',
    'jaune</i>, said to be yellow because the pages of <i>L&rsquo;Auto</i> were',
    'printed on yellow paper. To wear it into Paris is the ambition of every rider',
    'who ever turned a pedal in anger.</p>',
    '<pre>',
    'THE JERSEYS OF THE TOUR',
    '=======================',
    ' YELLOW    maillot jaune     the overall race leader, on time',
    ' GREEN     maillot vert      the points leader, the sprinters',
    ' POLKA-DOT à pois rouges     the King of the Mountains',
    ' WHITE     maillot blanc     the best young rider',
    '</pre>',
    '',
    '<h2>The mountains</h2>',
    '<p>The Tour is won and lost in the high mountains. The names are a litany to',
    'anyone who follows it: the Col du Tourmalet, the Galibier, Alpe d&rsquo;Huez',
    'with its twenty-one hairpin bends, the Mont Ventoux standing bald and white',
    'above Provence. On these climbs the race splits apart, the pretenders fall',
    'away, and the contenders are left alone to settle it between them.</p>',
    '<p class="fs-aside"><b>THE PELOTON.</b> Most of the race is ridden in the great',
    'bunch called the peloton, where riders shelter from the wind behind one another',
    'and save their strength. A rider or a small group who escapes off the front is',
    'the breakaway, and the daily drama is whether the breakaway can stay away or',
    'whether the peloton, working together, will reel it back before the line.</p>',
    '<h2>The champions</h2>',
    '<p>Five men have won it five times: Jacques Anquetil, Eddy Merckx, Bernard',
    'Hinault, Miguel Indurain and, later and under a shadow, Lance Armstrong. Of',
    'them the club argues loudest about Merckx, who won his first Tour and took the',
    'yellow, green and mountains prizes all in one year. Fausto Coppi and Gino',
    'Bartali carried the race through the hard Italian years either side of the war,',
    'their rivalry dividing a nation.</p>',
    '<hr>',
    '<p>For the greatest of the Tour&rsquo;s champions, read <a href="eddy-merckx.geocities.ws">Eddy',
    'Merckx</a>, the Cannibal, here in the ring. And for the endurance test on four',
    'wheels, the twenty-four hours of <a href="le-mans.geocities.ws">Le Mans</a>.</p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hit counter: 02255 · best viewed in Netscape at 800x600 · allez allez',
    'allez · page last updated 24 Jul, in Tour week · this site is a member of the',
    'cyclosport webring</small></p>',
  ]);

// ---- Le Mans: the famous-event retelling ------------------------------------

const LEMANS = P('le-mans.geocities.ws', 'LE MANS',
  'THE 24 HOURS // the Circuit de la Sarthe', [
    '<!--bg:sport-motor-->',
    '<h1>THE 24 HOURS</h1>',
    '<p><small>everything a newcomer needs to know about the 24 Hours of Le Mans,',
    'set down by someone who has sat up all night by the radio more times than his',
    'wife thinks reasonable. &mdash; Big Dave, Endurance Racing Club</small></p>',
    '<hr>',
    '<p>The 24 Hours of Le Mans has been run, near enough every year since 1923, on',
    'the Circuit de la Sarthe near the city of Le Mans in western France. It is not',
    'a sprint. It is a full day and a full night of racing, and the winner is',
    'simply the car that covers the greatest distance in twenty-four hours. Part of',
    'the course is closed public road. It tests the machine as hard as the men who',
    'drive it, and for most of its history it has been as much a contest of',
    'engineering and reliability as of speed.</p>',
    '<h2>1955</h2>',
    '<p>The race carries a shadow. In 1955 a Mercedes driven by Pierre Levegh struck',
    'a slower car, launched into the air and disintegrated against the barrier by',
    'the packed main grandstand. Levegh and more than eighty spectators were killed',
    'and many more injured, the worst disaster in the history of motorsport. The',
    'race was not stopped, a decision debated ever since, so that the crowds leaving',
    'would not block the roads for the ambulances. Mercedes withdrew from racing',
    'altogether at the end of that season and did not return for decades. The',
    'catastrophe forced a reckoning with safety across the whole sport.</p>',
    '<img class="indie-pic" src="assets/media/web/sport/racing-car-01.jpg" alt=""><span class="indie-cap">A 1907 Grand Prix Brasier (L’Auto, public domain)</span>',
    '<h2>Ford against Ferrari</h2>',
    '<p>The most famous rivalry the race has known came in the 1960s. Ferrari had',
    'dominated Le Mans through the decade. Henry Ford II, after a soured attempt to',
    'buy the Italian firm, resolved to beat it on the track, and poured a fortune',
    'into the Ford GT40. Ferrari held them off at first. Then, in 1966, the Fords',
    'came good and swept the podium, the American company&rsquo;s answer delivered',
    'at last, and they went on to win the race four years running.</p>',
    '<pre>',
    'LE MANS — A FEW MARQUES BY OUTRIGHT WINS',
    '========================================',
    ' Porsche    the record holder, wins across many decades',
    ' Ferrari    the dominant name of the late 1950s and early 60s',
    ' Jaguar     the C-type and D-type of the 1950s',
    ' Ford       the GT40, four in a row from 1966',
    ' Bentley    the "Bentley Boys" of the 1920s',
    '</pre>',
    '<p class="fs-aside"><b>THE START.</b> For decades the race began with the',
    'famous Le Mans start: the drivers sprinted across the track to their cars,',
    'jumped in and roared off. It made for a thrilling sight and it cost lives,',
    'because men drove off without fastening their belts to save seconds. Jacky',
    'Ickx protested by walking, calmly, to his car in 1969, and won. The running',
    'start was abolished soon after.</p>',
    '<hr>',
    '<p>For the sprint championship that is the other pole of motorsport, read <a href="the-grand-prix.geocities.ws">the',
    'Grand Prix</a>. And for the endurance test on two wheels, the three weeks of',
    '<a href="eddy-merckx.geocities.ws">Eddy Merckx</a>&rsquo;s Tour, see his page in',
    'the ring.</p>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>counter: 01488 · best viewed at 800x600 · brew the coffee, it is a',
    'long night · last updated 14 Jun, race weekend · Endurance Racing Club webring</small></p>',
  ]);

// ---- The Grand Prix: the ORG/idea page --------------------------------------

const GRANDPRIX = P('the-grand-prix.geocities.ws', 'GRAND PRIX',
  'FORMULA ONE // the world championship, since 1950', [
    '<!--bg:sport-motor-->',
    '<h1>THE GRAND PRIX</h1>',
    '<p><small>a plain guide to Formula One and the Grand Prix, written for a friend',
    'who asked what all the fuss was, and then left up in case it helps you too.',
    '&mdash; R. Coates</small></p>',
    '<hr>',
    '<p>A Grand Prix is a motor race, and Formula One is the class of car and the',
    'championship at the summit of the sport. The Formula One World Championship',
    'began in 1950, its first race at Silverstone in England, and it has run every',
    'year since. Over a season the drivers race at circuits around the world and',
    'score points, and the one with the most at the end is the world champion.',
    'There is a second title, for the constructors, the firms that build the cars,',
    'and the two are chased at once.</p>',
    '<h2>The circuits</h2>',
    '<p>The calendar is a tour of famous places. Monaco, run through the streets of',
    'Monte Carlo past the harbour and the casino, slow and unforgiving and the one',
    'every driver most wants to win. Monza, the fast old royal park near Milan, the',
    'temple of speed. Spa-Francorchamps in the Belgian forest, with its plunging',
    'Eau Rouge. Silverstone, the British home of the sport. Each has its own',
    'character, and the great drivers are the ones who master all of them.</p>',
    '<pre>',
    'HOW THE CHAMPIONSHIP WORKS',
    '==========================',
    ' A season   many races (Grands Prix) around the world',
    ' Qualifying decides the starting order; pole is fastest',
    ' The race   points to the finishers, most to the winner',
    ' Two titles the Drivers\' and the Constructors\'',
    ' Champion   the driver with the most points at year end',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/sport/racing-car-01.jpg" alt=""><span class="indie-cap">A 1907 Grand Prix Brasier (L’Auto, public domain)</span>',
    '<h2>The danger</h2>',
    '<p>For most of its history the sport was appallingly dangerous. In the 1950s',
    'and 1960s a driver who raced a full career could expect to see several of his',
    'friends killed, and had a real chance of dying himself. Jim Clark, thought by',
    'many the most naturally gifted of all, was killed in 1968. The drivers',
    'themselves, led by men such as Jackie Stewart, fought hard and against',
    'resistance for better barriers, better medical cover and better cars. The sport',
    'is far safer now than it was, though it has never been made safe.</p>',
    '<p class="fs-aside"><b>THE GLAMOUR.</b> Alongside the danger runs the glamour,',
    'the reason the sport draws the crowds it does: the wealth, the beautiful',
    'machinery, the yachts in the harbour at Monaco, the champagne on the podium.',
    'It has always been both things at once, the risk and the show, and the tension',
    'between them is a good part of the fascination.</p>',
    '<h2>The greats</h2>',
    '<p>Whom you name as the greatest tells the world your age. The old hands say',
    '<a href="juan-manuel-fangio.geocities.ws">Juan Manuel Fangio</a>, five titles in',
    'the 1950s against the odds and the deaths. A younger crowd says <a href="ayrton-senna.geocities.ws">Ayrton',
    'Senna</a>, three titles and a genius in the wet, lost at Imola in 1994. Between',
    'them, and after them, come Jim Clark, Alain Prost, Michael Schumacher and more.',
    'The argument is part of loving the sport.</p>',
    '<hr>',
    '<p><small>[ <a href="sport-ring.geocities.ws">Sport Ring</a> ]</small></p>',
    '<hr>',
    '<p><small>hit counter: 02796 · best viewed in Netscape at 800x600 · lights out',
    'and away we go · last updated 21 Aug · a member of the motorsport webring</small></p>',
  ]);

export const SPRT_E = [FANGIO, SENNA, MERCKX, TOUR, LEMANS, GRANDPRIX];
