// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH E — American painting and the overlooked mid-century.
//
// Cached pages a gallery, a museum, a private collector, a fan, a student and a
// lecture-goer made about the painters they loved: Pollock's drip shown by a
// downtown dealer; a museum wall-labelling Rothko; a collector who bought Norman
// Lewis when nobody else would; a shrine to Alma Thomas; a coursework-ish
// summary of Hopper; and a write-up of a Burchfield show. Titles, dates, media
// and collections are real; the enthusiasm and the handles are the pages'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Pollock: the downtown gallery showpiece --------------------------------

const POLLOCK = P('jackson-pollock.geocities.ws', 'POLLOCK',
  'JACKSON POLLOCK // the drip and the all-over canvas', [
    '<!--bg:art-american-->',
    '<h1>JACKSON POLLOCK</h1>',
    '<p><small>a selling and viewing page kept by a downtown dealer’s room. we',
    'have shown American work since the lofts were cheap. no photography in the',
    'room, but we keep good plates here for study. enquiries welcome. — the gallery</small></p>',
    '<hr>',
    '<p class="fs-epi"><i>“When I am in my painting, I am not aware of what I am',
    'doing.”</i><br>— Jackson Pollock, 1947</p>',
    '<p>Paul Jackson Pollock (1912–1956) is the painter who took the picture off',
    'the easel and put it on the floor. He tacked raw unstretched canvas to the',
    'boards of a barn on Long Island, walked around all four sides of it, and let',
    'the paint fall from a stick or a hardened brush or a can with a hole in it. He',
    'called it neither dripping nor accident. He said he could control the flow,',
    'and that there was no accident just as there was no beginning and no end. What',
    'came out is the ALL-OVER canvas, a surface with no centre and no top, woven',
    'edge to edge, that you read the way you read weather rather than the way you',
    'read a window.</p>',
    '<img class="indie-pic" src="assets/media/web/art/pollock-01.jpg" alt=""><span class="indie-cap">Jackson Pollock (public domain)</span>',
    '<p>This is the heart of what got called ABSTRACT EXPRESSIONISM, the first',
    'American movement the rest of the world had to follow rather than lead. The',
    'critics split him from the field: some read the poured skeins as pure',
    'painterly energy, action laid down in real time; others read them as vast',
    'fields of contemplation. Both were looking at the same webs of enamel',
    'house-paint, which is the ordinary industrial stuff he used, not artists’',
    'oils, poured in silver and black and white and rust across canvases too big',
    'to take in from one spot.</p>',
    '<p class="fs-aside"><b>A note on the medium.</b> The drip pictures are mostly',
    'commercial enamel and aluminium paint, the kind you would buy for a radiator,',
    'on unprimed cotton duck. That is part of why they are fragile and why the',
    'conservators worry: the paint sits ON the cloth rather than soaking into a',
    'ground, and it has its own life as it ages.</p>',
    '<p>The great year was 1950. In one stretch he made <i>One: Number 31, 1950</i>,',
    '<i>Autumn Rhythm (Number 30)</i> and <i>Number 32, 1950</i>, the three that',
    'still stop people in the room. Then, almost at the height of it, he pulled',
    'back from pouring and returned to black and to the figure, and the work grew',
    'harder and darker. He drank, badly and for years. On an August night in 1956',
    'he crashed his car a few miles from the house on Long Island and was killed,',
    'aged forty-four. One of his passengers died with him; the other lived.</p>',
    '<p class="fs-pull">He is the reason a generation of painters believed New York',
    'had taken the argument away from Paris.</p>',
    '<p>His wife was the painter Lee Krasner, herself a serious artist long before',
    'she met him and for the thirty years after, who managed the estate and kept',
    'the barn and the reputation. The photographer Hans Namuth filmed him working',
    'in 1950, and those reels, of a man walking round a canvas on the ground,',
    'flinging line, did as much to fix the legend as any single picture.</p>',
    '<img class="indie-pic" src="assets/media/web/art/rothko-01.jpg" alt=""><span class="indie-cap">Mark Rothko, c.1949 (photo: Consuelo Kanaga)</span>',
    '<p>A wall-label list, for study:</p>',
    '<pre>',
    'Mural                          1943   oil/casein on canvas   U. of Iowa',
    'Full Fathom Five               1947   oil w/ nails, tacks    MoMA, NY',
    'Number 1, 1948 (Anatomy)       1948   oil & enamel           MoMA, NY',
    'Number 1A, 1948                1948   oil & enamel           MoMA, NY',
    'Autumn Rhythm (Number 30)      1950   enamel on canvas       Met, NY',
    'One: Number 31, 1950           1950   oil & enamel           MoMA, NY',
    'Blue Poles (Number 11, 1952)   1952   enamel, alu., glass    NGA Australia',
    '</pre>',
    '<p>If Pollock is the poured line, the other pole of the movement is the poured',
    'colour: see Mark Rothko’s fields at',
    '<a href="mark-rothko.geocities.ws">mark-rothko</a>, whose quiet is the exact',
    'opposite of this noise. And for the America that stayed still and figurative',
    'while all this broke loose, the diners and the empty rooms of Edward Hopper',
    'are at <a href="edward-hopper.geocities.ws">edward-hopper</a>.</p>',
    '<hr>',
    '<p><small>counter: 03271 · best viewed at 800x600 · under construction, more',
    'plates to come · last updated 14 Mar</small></p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
  ]);

// ---- Rothko: the museum wall-label ------------------------------------------

const ROTHKO = P('mark-rothko.geocities.ws', 'ROTHKO',
  'MARK ROTHKO // the colour-field and the floating rectangles', [
    '<!--bg:art-american-->',
    '<h1>MARK ROTHKO</h1>',
    '<p><small>gallery notes and wall-labels from the modern collection. reproduced',
    'here for visitors who cannot make the trip. the works are not to scale on your',
    'screen; they are meant to tower over you.</small></p>',
    '<hr>',
    '<p>Mark Rothko (1903–1970), born Marcus Rothkowitz in Dvinsk in the Russian',
    'Empire, brought to Oregon as a child, is the painter of the large soft',
    'rectangle of colour that hangs in a field of another colour and seems to',
    'breathe. He arrived at the form slowly, through myth and Surrealist stains in',
    'the 1940s, and by about 1949 had cleared everything else away. What remained',
    'were two or three blurred blocks stacked on a ground, edges feathered so they',
    'neither sit flat nor float free.</p>',
    '<img class="indie-pic" src="assets/media/web/art/rothko-01.jpg" alt=""><span class="indie-cap">Mark Rothko, c.1949 (photo: Consuelo Kanaga)</span>',
    '<p>He resisted the label COLOUR-FIELD and resisted the word abstract even more.',
    'He said he was not interested in the relationships of colour or form, and that',
    'if you were moved only by those you missed the point. He was after the big',
    'human things, tragedy, ecstasy, doom, and he wanted the paintings hung low and',
    'close and lit dimly so that you stood inside them rather than in front of',
    'them.</p>',
    '<p class="fs-quote"><i>“The people who weep before my pictures are having the',
    'same religious experience I had when I painted them.”</i> — Mark Rothko</p>',
    '<p>Two commissions tell the second half of the story. In 1958 he was paid',
    'handsomely to paint a series of murals for the Four Seasons restaurant in the',
    'new Seagram Building in New York. He worked on them in a dark red and brown',
    'key, then, after eating in the finished restaurant, decided he would not let',
    'his work hang where the rich came to dine, returned the fee and kept the',
    'pictures. A large group of the SEAGRAM MURALS came to the Tate in London on',
    'the day he died.</p>',
    '<p class="fs-aside"><b>Wall-label.</b><br>Mark Rothko, <i>Black on Maroon</i>,',
    '1958. Oil, acrylic, glue tempera and pigment on canvas. One of the Seagram',
    'mural group. Tate, London.</p>',
    '<p>The second is the octagonal chapel in Houston, commissioned by the de',
    'Menil family, for which he made fourteen very dark canvases, near-black',
    'purples and browns that only give up their differences to a patient eye. It',
    'opened in 1971 as a non-denominational space for contemplation. He did not',
    'live to see it. In February 1970 he took his own life in his New York studio.</p>',
    '<img class="indie-pic" src="assets/media/web/art/alma-thomas-01.jpg" alt=""><span class="indie-cap">Alma Thomas (public domain)</span>',
    '<p>His fields are usually set against Pollock’s poured line as the two poles',
    'of the New York School; that argument, from the other side, is at',
    '<a href="jackson-pollock.geocities.ws">jackson-pollock</a>. And for a painter',
    'the same downtown world walked straight past, the collector’s page for',
    'Norman Lewis is at <a href="norman-lewis.geocities.ws">norman-lewis</a>.</p>',
    '<hr>',
    '<p><small>visitors: 02140 · best viewed at 800x600 · modern collection notes ·',
    'page last tended 22 Jan</small></p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
  ]);

// ---- Norman Lewis: the private collector ------------------------------------

const LEWIS = P('norman-lewis.geocities.ws', 'NORMAN LEWIS',
  'NORMAN LEWIS // the Abstract Expressionist the histories left out', [
    '<!--bg:art-american-->',
    '<h1>NORMAN LEWIS</h1>',
    '<p><small>from a private collection, put online so the work is at least seen.',
    'i began buying him when the prices said nobody was looking, which tells you',
    'more about the market than about the painting. holdings and notes below.</small></p>',
    '<hr>',
    '<p>Norman Lewis (1909–1979) was a first-rank Abstract Expressionist and for',
    'most of the century the histories left him out, because he was Black and the',
    'story the movement told about itself did not have room for that. He was in the',
    'room. He took part in the famous “Studio 35” sessions with the others in',
    '1950 and was in the circle around Willem de Kooning and the rest, and his',
    'painting stands with theirs without apology.</p>',
    '<p>He came up through the Harlem of the 1930s, taught in the WPA years, and',
    'moved from an early social realism to abstraction in the 1940s without ever',
    'quite letting go of the human crowd inside the mark. That is the thing to see',
    'in him: the abstraction keeps turning back into a PROCESSION. Small ragged',
    'shapes gather along a horizontal, and you read a march, a congregation, a',
    'streetful of people, in what is still, strictly, an abstract band of black on',
    'a pale ground.</p>',
    '',
    '<p class="fs-aside"><b>From the collection.</b><br>Norman Lewis, <i>Migrating',
    'Birds</i>, 1954, oil on canvas. It won a prize at the Carnegie International in',
    'Pittsburgh in 1955, the sort of recognition that should have opened every door',
    'and did not.</p>',
    '<p>Two threads run through the mature work. One is JAZZ: he loved the music and',
    'painted its scatter and its swing, letting the marks improvise across the',
    'surface the way a soloist runs across the bar. The other is the movement of',
    'his own people, the migration of black and white shapes read as the migration',
    'of a population, and later a direct reckoning with the times, a series on the',
    'civil-rights years in which the massed white marks turn menacing, the hoods of',
    'a Klan crowd read in the same abstract language he used for a congregation.</p>',
    '<p>In 1963 he helped found SPIRAL, the group of Black artists in New York, with',
    'Romare Bearden and Hale Woodruff and others, who met to ask what, if anything,',
    'their art owed to the struggle then at its height. Lewis kept painting',
    'abstractly and kept arguing that the freedom to do so was itself part of the',
    'point.</p>',
    '<p>Set him beside Alma Thomas, the other great Black abstractionist this web',
    'keeps, whose shrine is at <a href="alma-thomas.geocities.ws">alma-thomas</a>;',
    'and beside Rothko at <a href="mark-rothko.geocities.ws">mark-rothko</a>, whose',
    'fame is the exact measure of what Lewis was denied.</p>',
    '<hr>',
    '<p><small>counter: 01188 · best viewed at 800x600 · a private holding, not for',
    'sale · last updated 9 Feb</small></p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
  ]);

// ---- Alma Thomas: the fan shrine --------------------------------------------

const THOMAS = P('alma-thomas.geocities.ws', 'ALMA THOMAS',
  'ALMA THOMAS // the mosaic of colour, found in her seventies', [
    '<!--bg:art-american-->',
    '<h1>ALMA THOMAS</h1>',
    '<p><small>a shrine, kept by someone who saw one painting in a museum and had to',
    'go and find out who she was. i have been reading about her ever since. if this',
    'page makes one more person look her up it has done its job. — Ren</small></p>',
    '<hr>',
    '<p class="fs-epi"><i>“A world without colour would seem dead. Colour is',
    'life.”</i><br>— Alma Thomas</p>',
    '<p>Alma Woodsey Thomas (1891–1978) spent nearly her whole working life as a',
    'schoolteacher in Washington, teaching art to children at Shaw Junior High for',
    'thirty-five years, and only after she retired, in her seventies, did she paint',
    'the work that made her name. Think about that for a moment. The paintings',
    'everyone loves her for were made by a woman in her late seventies and',
    'eighties, with arthritis in her hands, who had waited that long for the time.</p>',
    '<img class="indie-pic" src="assets/media/web/art/alma-thomas-01.jpg" alt=""><span class="indie-cap">Alma Thomas (public domain)</span>',
    '<p>Her signature is the dab. Short broken strokes of pure colour, set side by',
    'side with little rivers of bare canvas showing between them, so the whole',
    'surface reads like a MOSAIC or like a garden bed seen from above, or like',
    'light coming through leaves. She said her azaleas and her holly tree, seen',
    'through the window of her Washington house, first taught her to break colour',
    'up that way. The bands curve and circle; the eye keeps moving; nothing sits',
    'still.</p>',
    '<p class="fs-pull">She waited until her seventies, and then she was one of the',
    'freshest colourists in the country.</p>',
    '<p>Then came the SPACE paintings. She followed the Apollo flights and the first',
    'photographs of the earth from orbit with real excitement, and made a run of',
    'pictures with titles like <i>Blast Off</i> and <i>The Eclipse</i> and <i>Snoopy',
    'Sees Earth Wrapped in Sunset</i>, the concentric dabs turning into orbits and',
    'launches and the curve of a planet. In 1972 she became the first Black woman',
    'to have a solo exhibition at the Whitney Museum in New York, at the age of',
    'eighty.</p>',
    '<p class="fs-aside"><b>A favourite.</b> <i>Resurrection</i>, 1966, acrylic on',
    'canvas, is a wheel of blues and greens and reds. It later hung in the White',
    'House, the first work by a Black woman to enter its collection. She would have',
    'enjoyed the thought that the schoolteacher got there in the end.</p>',
    '<p>She belongs beside Norman Lewis, the other Black abstractionist this ring',
    'keeps, whose page is at <a href="norman-lewis.geocities.ws">norman-lewis</a>;',
    'and it is worth setting her joy against the stillness of Edward Hopper over at',
    '<a href="edward-hopper.geocities.ws">edward-hopper</a>, two Americas painted',
    'in the same years.</p>',
    '<hr>',
    '<p><small>counter: 01542 · best viewed at 800x600 · this page is a work of',
    'love and always under construction · last updated 30 Apr · signed, Ren</small></p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
  ]);

// ---- Hopper: the academic summary -------------------------------------------

const HOPPER = P('edward-hopper.geocities.ws', 'HOPPER',
  'EDWARD HOPPER // American light and American solitude', [
    '<!--bg:art-american-->',
    '<h1>EDWARD HOPPER</h1>',
    '<p><small>a summary page maintained for a course reading list. references at the',
    'foot. corrections gratefully received.</small></p>',
    '<hr>',
    '<p>Edward Hopper (1882–1967) is the painter of American solitude and of the',
    'particular quality of American light. He trained in New York, spent time in',
    'Paris in the years the moderns were breaking everything open, and took almost',
    'none of it, choosing instead a plain, hard realism that he then made strange',
    'by what he did with light and with empty space.</p>',
    '<p>The subject, again and again, is a person or two held inside a shaft of',
    'light and surrounded by silence: a woman alone at a table, an usherette',
    'against a wall, a couple in a diner who are not speaking. Even the pictures',
    'with nobody in them, a gas station at dusk, a row of shopfronts, a sunlit room',
    'with an open door, feel as though someone has just left or is about to be',
    'lonely there. He gives you the architecture of loneliness, the geometry of the',
    'wall and the window and the fall of the sun across the floor.</p>',
    '<img class="indie-pic" src="assets/media/web/art/hopper-01.jpg" alt=""><span class="indie-cap">Hopper, House by the Railroad, 1925 (public domain)</span>',
    '<p>The famous one is <i>Nighthawks</i> (1942, Art Institute of Chicago): three',
    'customers and a server in the acid-green light of an all-night diner, seen',
    'through a great curved sheet of glass, on a street with no door back out onto',
    'it. It has become the standard image of the modern city at night, endlessly',
    'reproduced and parodied, though the parody never quite kills the ache in the',
    'original.</p>',
    '<p>Others belong on the same shelf: <i>Early Sunday Morning</i> (1930, Whitney,',
    'New York), a row of red shopfronts and a barber’s pole in raking morning',
    'light with not a soul in sight; <i>Automat</i> (1927); <i>Gas</i> (1940, MoMA);',
    'and <i>Office at Night</i> (1940). His wife, the painter Josephine Nivison',
    'Hopper, modelled for nearly every woman in the mature work and kept the',
    'ledgers that record them.</p>',
    '<p class="fs-quote"><i>“Maybe I am slightly inhuman... All I ever wanted to do',
    'was to paint sunlight on the side of a house.”</i> — Edward Hopper</p>',
    '<p>For a very different American vision of the same small towns and the same',
    'weather, see the visionary watercolours of Charles Burchfield at',
    '<a href="charles-burchfield.geocities.ws">charles-burchfield</a>; and for the',
    'colour and the joy that Hopper’s stillness refuses, Alma Thomas is at',
    '<a href="alma-thomas.geocities.ws">alma-thomas</a>.</p>',
    '<hr>',
    '<p><b>References</b></p>',
    '<pre>',
    'Levin, G. (1995) Edward Hopper: An Intimate Biography. New York: Knopf.',
    'Goodrich, L. (1971) Edward Hopper. New York: Abrams.',
    'Whitney Museum of American Art (Hopper bequest), New York.',
    'Art Institute of Chicago, wall text for Nighthawks (1942).',
    '</pre>',
    '<p><small>counter: 00996 · best viewed at 800x600 · for the seminar, week 8 ·',
    'last updated 5 Feb</small></p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
  ]);

// ---- Burchfield: the exhibition write-up ------------------------------------

const BURCHFIELD = P('charles-burchfield.geocities.ws', 'BURCHFIELD',
  'CHARLES BURCHFIELD // the sound of nature made visible', [
    '<!--bg:art-american-->',
    '<h1>CHARLES BURCHFIELD</h1>',
    '<p><small>notes written up after the touring exhibition came through, for',
    'anyone who missed it. the paintings are watercolours and much bigger than that',
    'word usually promises. — written up by a visitor</small></p>',
    '<hr>',
    '<p>Charles Burchfield (1893–1967) was a visionary American watercolourist, a',
    'painter who worked almost entirely in a medium the academies treat as minor',
    'and made it carry visions. He lived his whole quiet life in Ohio and then near',
    'Buffalo in western New York, a commercial artist and a family man who painted',
    'the seasons and the small towns and the weeds at the edge of the yard as',
    'though they were haunted, which, in his seeing, they were.</p>',
    '<p>The exhibition made the shape of a career clear. The early work, around',
    '1917, the year he called his “golden year”, is small and strange and',
    'ecstatic, full of what he called his “conventions for abstract thoughts”,',
    'little repeated signs for fear and for melancholy and for the drone of insects',
    'on a hot afternoon. A long middle period turns sober and documentary, the',
    'ordinary main streets and railway yards and Victorian HOUSES of a declining',
    'industrial region, gaunt and staring, so that a plain house looks out at you',
    'like a face.</p>',
    '<img class="indie-pic" src="assets/media/web/art/burchfield-01.jpg" alt=""><span class="indie-cap">Burchfield, Twilight Moon, 1916 (public domain)</span>',
    '<p>Then, from about the mid-1940s, he opened the early ecstatic vision back up',
    'and painted the very biggest and strangest work of his life. This is where he',
    'tries to make SOUND VISIBLE: the throb of cicadas, the ringing of heat, the',
    'wind and the church bells and the coming of spring, all pushed into the paint',
    'as radiating lines and haloes and pulsing edges around the trees and the sky.',
    'He would sometimes cut and add strips of paper to enlarge a picture years',
    'after starting it, so a work grew outward as the vision grew.</p>',
    '<p class="fs-aside"><b>Seen in the show.</b><br><i>The Insect Chorus</i>, 1917,',
    'opaque and transparent watercolour. <i>Song of the Telegraph</i> and the late',
    'expanding works from the 1950s. <i>An April Mood</i>, 1946–55. Many lent by',
    'the Burchfield Penney Art Center in Buffalo, which keeps his archive.</p>',
    '<p>He was championed early, shown at the new Museum of Modern Art in its very',
    'first season, then somewhat set aside as abstraction took the century, which',
    'is part of why a fresh look mattered. He fits no school. The nearest company',
    'on this ring is Edward Hopper, who painted the same American small town from',
    'the far side of the mood, at <a href="edward-hopper.geocities.ws">edward-hopper</a>;',
    'and for the poured energy Burchfield reached for in paint and Pollock reached',
    'for in enamel, see <a href="jackson-pollock.geocities.ws">jackson-pollock</a>.</p>',
    '<hr>',
    '<p><small>counter: 00637 · best viewed at 800x600 · exhibition notes, written',
    'up after the fact · last updated 18 Mar</small></p>',
    '<p><small>[ <a href="painters-ring.geocities.ws">Painters Ring</a> ]</small></p>',
  ]);

export const ART_E = [POLLOCK, ROTHKO, LEWIS, THOMAS, HOPPER, BURCHFIELD];
