// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH MT-B: German media theory and media archaeology.
//
// Fan pages, kept on a free host, each ABOUT a thinker and never in the
// thinker’s own voice. A night-shift sysadmin who watches timestamps scroll
// (Ernst); a zine-maker who collects pictures of marvellous dead machines
// (Zielinski); a librarian in love with the go-between (Krämer); and a
// lapsed romantic who followed Debray from the jungle to the seminar room
// (Debray). The authors, titles and dates are real; the enthusiasms are the
// fans’.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Ernst: the night-shift sysadmin ----------------------------------------

const ERNST = P('chronopoetics.geocities.ws', 'CHRONOPOETICS',
  'CHRONOPOETICS // the machine keeps the time (Ernst)', [
    '<!--bg:mediatheory-->',
    '<h1>CHRONOPOETICS</h1>',
    '<p><small>a fan page for Wolfgang Ernst (b. 1959), kept by someone who runs',
    'the machines all night and watches the timestamps go by. i found him because',
    'i wanted a theory that cared about the CLOCK and not the content, and here he',
    'is. greetings from the server room. signed, nightwatch</small></p>',
    '<hr>',
    '<p>Ernst holds the media studies chair in Berlin and comes out of the German',
    'line that Kittler opened, but he pushes it somewhere colder and more precise.',
    'His question is not what a medium MEANS. His question is what a medium DOES,',
    'physically, in time, while it is running. He is a media archaeologist, which',
    'for him is a real practice and not a metaphor: you get the old apparatus, you',
    'switch it on if you can, and you listen to what it is actually doing.</p>',
    '<hr>',
    '<p><b>the archive is a machine, not a memory</b></p>',
    '<p>His first big idea in English is in <i>Digital Memory and the Archive</i>',
    '(2013). We are used to the archive as a poetic word, a great hall of cultural',
    'memory, dust and parchment. Ernst says drop that. In a computer the archive is',
    'an OPERATION. It is address, storage, retrieval, refresh. It is not brooding',
    'over the past, it is doing work in the present, right now, at clock speed. The',
    'romantic archive is a story we tell; the technical archive is a circuit that',
    'reads and writes.</p>',
    '<hr>',
    '<p><b>time-critical media</b></p>',
    '<p>The word to take away is TIME-CRITICAL. Some things a machine does only',
    'make sense at the scale of the microsecond, in the timing itself, below where',
    'a human can follow. A signal has to arrive in the right window or the whole',
    'process fails. Ernst says that is where the real being of technical media',
    'lives, in the operative present of the apparatus, the tiny now in which it',
    'measures and acts. He lays this out fully in <i>Chronopoetics: The Temporal',
    'Being and Operativity of Technological Media</i> (2016), which is where this',
    'page gets its name.</p>',
    '<p>Chronopoetics means, roughly, the time-making of the machine. Media do not',
    'just sit inside our time. They MEASURE time, they generate time, they cut it',
    'into slices we could never feel. The clock in the chip is not reading the hour,',
    'it is producing the beat that everything else marches to.</p>',
    '<hr>',
    '<p>A dry note from the night shift. When you have watched a log file long',
    'enough you stop reading the messages and start reading the intervals between',
    'them. That is Ernst’s whole move, made into a job. The content of the line',
    'tells you almost nothing; the timing tells you the machine is alive.</p>',
    '<hr>',
    '<p><b>neighbours worth a visit</b></p>',
    '<p>Kittler is the grandfather of this room, over at',
    '<a href="theres-no-software.geocities.ws">theres-no-software</a>, and Ernst is',
    'the student who took the hardware nerve and turned it toward TIME. For the',
    'longer view, Zielinski at',
    '<a href="deep-time-of-media.geocities.ws">deep-time-of-media</a> goes digging',
    'through the deep time of dead machines, and Parikka at',
    '<a href="geology-of-media.geocities.ws">geology-of-media</a> takes the deep',
    'time all the way down into the rock the machines are made of.</p>',
    '<hr>',
    '<p>Why he matters now, with the old certainties running down: the people who',
    'kept a real ear on what the apparatus was doing, second by second, are the',
    'ones who can still hear when it starts to fail. Ernst taught that listening.</p>',
    '<hr>',
    '<p><small>counter: 00512 · best viewed at 800x600 · this corner still under',
    'construction, a page on his sound work is coming · last updated 8 Oct</small></p>',
    '<p><small>',
    '[ <a href="mediatheory-ring.geocities.ws">Media Theory Ring</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Zielinski: the zine-maker and machine-collector ------------------------

const ZIELINSKI = P('deep-time-of-media.geocities.ws', 'DEEP TIME',
  'DEEP TIME OF THE MEDIA // dig, don’t march (Zielinski)', [
    '<!--bg:mediatheory-->',
    '<h1>DEEP TIME OF THE MEDIA</h1>',
    '<p><small>kept by someone who makes a photocopied zine about beautiful dead',
    'machines and needed a patron saint for it. Siegfried Zielinski (b. 1951) is',
    'him. this is my favourite book on the shelf and i will fight for it. signed,',
    'cut &amp;',
    'paste, literally</small></p>',
    '<hr>',
    '<p>Everyone tells the story of media the same way: a straight line of progress,',
    'one clever thing after another, each better than the last, arriving right on',
    'time at us, the point of it all. Zielinski cannot stand that story. He calls',
    'his alternative an AN-ARCHAEOLOGY, an archaeology with no clean origin and no',
    'tidy order, and the book is <i>Deep Time of the Media: Toward an Archaeology of',
    'Hearing and Seeing by Technical Means</i> (2006).</p>',
    '<hr>',
    '<p><b>deep time</b></p>',
    '<p>He borrows the phrase from geology, where deep time is the vast slow time of',
    'rock and fossil, far bigger than any human calendar. Turned on media it means:',
    'stop looking at the last twenty years. Go back centuries. Go and find the',
    'strange machines and the strange thinkers who dreamed of hearing and seeing by',
    'technical means long before the industry existed. There is more imagination in',
    'the dead ends than in the whole official line of winners.</p>',
    '<hr>',
    '<p><b>the marvellous machines</b></p>',
    '<p>His heroes are the curious ones. Athanasius Kircher, the seventeenth-century',
    'Jesuit with his magic lanterns and speaking statues and cabinets of wonders,',
    'gets pride of place. Zielinski loves the figures who tried something gorgeous',
    'and impractical and got left out of the textbook. He is not being nostalgic. He',
    'is after the possibilities that were open once and got closed off when the',
    'industry picked its few winners.</p>',
    '<hr>',
    '<p><b>variantology</b></p>',
    '<p>The programme has a name: VARIANTOLOGY. Instead of one grand history of THE',
    'media, you look for the variety, the branchings, the roads not taken, across',
    'many cultures and many centuries. His rule of thumb, and it is the best',
    'sentence in the book, runs like this: do not seek the old in the new, seek the',
    'new in the old. The fresh idea is hiding back there in the archive of failures,',
    'waiting for someone to notice it.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>Ernst at <a href="chronopoetics.geocities.ws">chronopoetics</a> is the',
    'closest company, digging the same ground with a sharper eye for the clock, and',
    'Parikka at <a href="geology-of-media.geocities.ws">geology-of-media</a> takes',
    'deep time literally, right down into the minerals. If you like this page you',
    'will like both of those.</p>',
    '<hr>',
    '<p>Why now, with so much lying broken and half-remembered: the person who knows',
    'the deep time, who has walked the graveyard of clever machines, is the one who',
    'can see that none of this was inevitable and that other paths were always open.',
    'Zielinski keeps that graveyard, and he keeps it as a workshop.</p>',
    '<hr>',
    '<p><small>counter: 00343 · best viewed at 640x480 like it is meant to be ·',
    'under construction forever, that is the point · last updated 21 Sep</small></p>',
    '<p><small>',
    '[ <a href="mediatheory-ring.geocities.ws">Media Theory Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Krämer: the librarian in love with the go-between -----------------------

const KRAMER = P('messenger.geocities.ws', 'MESSENGER',
  'THE MESSENGER // the medium that adds nothing (Krämer)', [
    '<!--bg:mediatheory-->',
    '<h1>THE MESSENGER</h1>',
    '<p><small>a page for Sybille Krämer (b. 1951), German media philosopher, kept',
    'by a reference librarian who spends all day carrying things between people who',
    'never meet. when i read her i finally had a word for the job. signed, the',
    'desk</small></p>',
    '<hr>',
    '<p>Most media theory is loud. The medium bends the message, the medium adds',
    'itself, the medium is the message, and so on. Krämer goes the other way and',
    'looks at the humble case that all the loud theories skip past: the medium that',
    'is trying NOT to add itself. The go-between. The one whose whole success is to',
    'disappear so that what passes through arrives clean. Her book in English is',
    '<i>Medium, Messenger, Transmission: An Approach to Media Philosophy</i> (2015).</p>',
    '<hr>',
    '<p><b>the messenger model</b></p>',
    '<p>Her figure for the medium is the MESSENGER. Think of the herald, the courier,',
    'the angel in the old paintings, the postman. A good messenger is a nobody on',
    'purpose. He is not the author of the message and he is not its audience. He',
    'stands in the third place, the between, and he does his job best when you forget',
    'he was ever there. Transmission, not expression. The point is not what the',
    'messenger has to say, because he has nothing to say. The point is that he',
    'carries.</p>',
    '<p>This flips the usual heroism of media theory. We love to say the medium',
    'shapes everything, and often it does. Krämer asks us to take seriously the ideal',
    'the medium is measured against, which is self-effacement, the flat clean channel',
    'that lets the other two ends meet. The messenger who added his own opinion would',
    'be a bad messenger.</p>',
    '<hr>',
    '<p><b>the diagram and operative writing</b></p>',
    '<p>Her other long love is what she calls OPERATIVE WRITING, and the diagram is',
    'her best example. A map, a table, a line of algebra, a family tree. These are',
    'not pictures of the world and they are not sentences about it. They are marks',
    'on a flat surface that you can WORK with, move around, compute on, read in more',
    'than one direction. Writing that does something, not writing that says',
    'something. She takes the humble flat surface, the page and the diagram, more',
    'seriously than almost anyone.</p>',
    '<hr>',
    '<p>A dry observation. Librarians and messengers get thanked last, if at all,',
    'exactly because they did the job well and vanished into it. Krämer is the',
    'first philosopher i have read who treats that vanishing as the interesting',
    'part rather than an embarrassment.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>Flusser at <a href="technical-image.geocities.ws">technical-image</a> is a',
    'good pairing, since he too worries about surfaces and what a technical mark',
    'really is, and Ernst at',
    '<a href="chronopoetics.geocities.ws">chronopoetics</a> shares her taste for the',
    'operation over the meaning. For the deep history of transmission as such, go to',
    'Debray at <a href="mediology.geocities.ws">mediology</a>, who asks how a message',
    'gets carried not across a room but across the centuries.</p>',
    '<hr>',
    '<p>Why she matters now, when so many channels have gone quiet: we only learn',
    'what the go-between was doing once it stops carrying. Krämer wrote the theory of',
    'the messenger while the messengers were still running. Read her now and you',
    'notice every silent link that used to hold.</p>',
    '<hr>',
    '<p><small>visitors: 00298 · best viewed at 800x600 · a page on her work on',
    'writing systems is under construction · last updated 14 Oct</small></p>',
    '<p><small>',
    '[ <a href="mediatheory-ring.geocities.ws">Media Theory Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Debray: the lapsed romantic --------------------------------------------

const DEBRAY = P('mediology.geocities.ws', 'MEDIOLOGY',
  'MEDIOLOGY // how ideas outlive us (Debray)', [
    '<!--bg:mediatheory-->',
    '<h1>MEDIOLOGY</h1>',
    '<p><small>a page for Régis Debray (b. 1940), kept by someone who came for the',
    'life story and stayed for the theory. do not skip the theory. signed, the reader in',
    'the back row</small></p>',
    '<hr>',
    '<p>Debray had a life before he had a discipline. As a young man he went to Latin',
    'America and carried a gun with Che Guevara’s circle, was captured in Bolivia and',
    'spent years in prison. He came out of all that and spent the rest of his life on',
    'a quieter and stranger question: how does a word outlive the body that spoke it?',
    'How does an idea travel across centuries when every person who held it is dead?',
    'That question became a whole field, and he named it MEDIOLOGY.</p>',
    '<hr>',
    '<p><b>transmission, not communication</b></p>',
    '<p>Here is the distinction the whole thing turns on. COMMUNICATION is moving a',
    'message across SPACE, from me to you, now. TRANSMISSION is moving it across',
    'TIME, from the dead to the unborn, down the generations. Media studies, he says,',
    'is obsessed with communication and forgets transmission, and transmission is the',
    'deeper mystery. A tweet is communication. A religion that lasts two thousand',
    'years is transmission. Mediology studies the second one.</p>',
    '<p>And ideas do not travel on their own. They need carriers, material and',
    'institutional both: a book, a church, a school, a monument, an archive, an',
    'order of monks copying by hand. Debray keeps insisting that a belief with no',
    'body to carry it simply dies, however true it is. The high idea rides on the low',
    'freight. That is the mediologist’s favourite scandal.</p>',
    '<hr>',
    '<p><b>the mediaspheres</b></p>',
    '<p>He cuts the long history of transmission into three MEDIASPHERES, named for',
    'the ruling medium of each. The LOGOSPHERE, the age of speech and the written',
    'word, where authority rests on the sacred text. The GRAPHOSPHERE, the age of',
    'print, of the book and the nation and the reading public. The VIDEOSPHERE, the',
    'age of the screen and the image, where the visible rules. Each sphere carries',
    'ideas in its own way and stamps them with its own kind of power.</p>',
    '<hr>',
    '<p><b>the shelf in English</b></p>',
    '<p>Start with <i>Media Manifestos</i> (1994), which is where he sets out the',
    'programme and picks the fight with plain communication theory. Then',
    '<i>Transmitting Culture</i> (2000), the fuller statement of how culture gets',
    'handed on. Both are short and sharp and a little grand, which suits him.</p>',
    '<hr>',
    '<p>A dry note. It is a strange arc, from the rifle to the reading list, and',
    'Debray knows it is strange, and he made the strangeness into his subject. The',
    'guerrilla learned the hard way that the deed dies with the body and only the',
    'word gets carried on. So he went and studied the carrying.</p>',
    '<hr>',
    '<p><b>neighbours</b></p>',
    '<p>McLuhan at <a href="the-medium-is.geocities.ws">the-medium-is</a> is the one',
    'he argues with, since McLuhan reads the medium off its form while Debray insists',
    'you follow the institutions and the freight that actually carry it. And Krämer',
    'at <a href="messenger.geocities.ws">messenger</a> is the natural partner: she',
    'has the philosophy of the go-between, he has the long history of what the',
    'go-between hands down the generations.</p>',
    '<hr>',
    '<p>Why now, with the network fraying and so much at risk of simply not being',
    'passed on: transmission is never automatic, it is work, and a culture that stops',
    'doing the work loses the thread within a generation. Debray spent a lifetime on',
    'how the thread gets held. Good moment to ask who is holding it.</p>',
    '<hr>',
    '<p><small>counter: 00456 · best viewed at 800x600 · a page on his later work is',
    'under construction · last updated 2 Nov</small></p>',
    '<p><small>',
    '[ <a href="mediatheory-ring.geocities.ws">Media Theory Ring</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

export const MT_B = [ERNST, ZIELINSKI, KRAMER, DEBRAY];
