// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// HISTORY OF AI, BATCH A — prehistory & cybernetics (bg:proto).
//
// Fan pages, kept on a free host, each ABOUT a figure or idea in the deep roots
// of the field and never in that figure's own voice. Mostly sober academic
// summaries kept by students and librarians; the Wiener page is a devotee's
// shrine that breaks the mould. Names, titles and dates are real; the warmth and
// the opinions are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Boole: the clean academic summary --------------------------------------

const BOOLE = P('boolean-logic.geocities.ws', 'BOOLEAN LOGIC',
  'GEORGE BOOLE // the laws of thought', [
    '<!--bg:proto-->',
    '<h1>GEORGE BOOLE AND THE LAWS OF THOUGHT</h1>',
    '<p><small>a summary page kept by a maths postgrad who got tired of people',
    'saying "boolean" without knowing there was a Boole. corrections welcome, i',
    'have checked the dates twice.</small></p>',
    '<hr>',
    '<h2>Who he was</h2>',
    '<p>George Boole (1815 to 1864) was a largely self-taught English mathematician',
    'who ended up professor at Queen\'s College, Cork. His great idea was simple to',
    'state and enormous in its reach: that the rules of reasoning could be written',
    'as algebra, the same way the rules of number are.</p>',
    '<h2>The two books</h2>',
    '<p>He set it out first in a short work, <i>The Mathematical Analysis of Logic</i>',
    '(1847), and then properly in <i>An Investigation of the Laws of Thought</i>',
    '(1854). The second title is the one to remember. In it he treats logical',
    'classes with an algebra where a symbol stands for "all the things that are X",',
    'and where multiplication means "and", addition means "or", and the whole thing',
    'runs on just two values.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/ibm704-01.jpg" alt=""><span class="indie-cap">an IBM 704 (NASA, public domain)</span>',
    '<h2>The central move: true and false as 1 and 0</h2>',
    '<p>This is the part every computer person should know. Boole let his symbols',
    'take only two values, 1 and 0, standing for the whole universe and for nothing,',
    'or read another way, for true and for false. An expression like x(1 minus x)',
    'always comes out to 0, which is his algebra saying that nothing can both be a',
    'thing and not be that thing. The law of non-contradiction, written as sums.</p>',
    '<blockquote class="fs-quote"><p>"the respective interpretation of the symbols',
    '0 and 1 in the system of logic are Nothing and Universe."</p></blockquote>',
    '<p>Two values, closed rules, no appeal to intuition. Reasoning made mechanical,',
    'on paper, decades before there was a machine to run it on.</p>',
    '<h2>Why it is the ground floor</h2>',
    '<p>For most of a century this sat in logic and philosophy. Then in 1937 a',
    'young engineer named Claude Shannon noticed that a network of electrical relays,',
    'each either open or shut, obeys exactly Boole\'s two-valued algebra, and that',
    'you could therefore design and simplify switching circuits by doing logic. That',
    'thesis is where Boole\'s algebra becomes the wiring of every digital machine.',
    'The and-gate, the or-gate, the not-gate on any chip are Boole in silicon.</p>',
    '<div class="fs-aside"><p>Small correction i keep having to make: Boole did not',
    'build a computer and never imagined one. He was doing logic. The engineering',
    'came later, from other people. Give him the algebra, not the hardware.</p></div>',
    '<h2>Neighbours</h2>',
    '<p>The algebra runs forward two ways. Into the theory of what a machine can',
    'compute at all, over at <a href="turing-machine.geocities.ws">turing-machine</a>,',
    'and into the measure of the message itself, at',
    '<a href="shannon-information.geocities.ws">shannon-information</a>, where the',
    'same Shannon who wired up Boole\'s logic later worked out how much a signal',
    'can carry.</p>',
    '<hr>',
    '<p><small>visitors: 01120 · best viewed at 800x600 · under construction, the',
    'bibliography needs tidying · last updated 8 Mar</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Turing: the clean academic summary -------------------------------------

const TURING = P('turing-machine.geocities.ws', 'TURING MACHINE',
  'TURING & COMPUTABILITY // On Computable Numbers', [
    '<!--bg:proto-->',
    '<h1>TURING AND COMPUTABILITY</h1>',
    '<p><small>notes kept by a computer-science librarian. this page is about the',
    '1936 paper and the theory of computation, not the codebreaking and not the',
    'later imitation game, though both get a pointer at the foot.</small></p>',
    '<hr>',
    '<h2>The paper</h2>',
    '<p>Alan Turing (1912 to 1954) published "On Computable Numbers, with an',
    'Application to the Entscheidungsproblem" in 1936, when he was twenty-three. It',
    'was an answer to a question David Hilbert had posed: is there a mechanical',
    'procedure that can decide, for any statement in a formal system, whether it is',
    'provable? To answer it Turing had first to say precisely what "a mechanical',
    'procedure" even means, and that definition is the lasting gift.</p>',
    '<h2>The machine</h2>',
    '<p>He imagined the plainest device that could still count as computing: a',
    'strip of tape divided into squares, a head that reads and writes one symbol at',
    'a time, and a small table of rules telling it what to do next given its state',
    'and the symbol it sees. That is the whole apparatus. No arithmetic unit, no',
    'memory hierarchy, just read, write, move, change state. Anything an algorithm',
    'can do, one of these can do.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/turing-01.jpg" alt=""><span class="indie-cap">the Alan Turing statue by Stephen Kettle (photo: DeFacto, CC BY-SA)</span>',
    '<h2>The universal machine</h2>',
    '<p>Then the decisive step. Turing described a single machine that takes, as',
    'part of its input, the description of any other machine, and then behaves',
    'exactly like it. One machine that can imitate all the others by reading their',
    'rules as data. This is the idea of the stored program and of general-purpose',
    'computing, worked out in mathematics a decade before anyone built the hardware.',
    'Every computer you have used is a rough physical approximation of it.</p>',
    '<h2>The halting problem</h2>',
    '<p>The sting in the paper is a limit. Turing showed there can be no general',
    'procedure that decides, for every machine and every input, whether that machine',
    'will eventually stop or run forever. Suppose there were such a decider; you can',
    'build a machine that asks the decider about itself and then does the opposite,',
    'and the contradiction sinks the whole idea. So some questions are not just',
    'hard, they are formally undecidable. Hilbert\'s dream of a decision procedure',
    'was answered, and the answer was no.</p>',
    '<h2>The Church-Turing thesis</h2>',
    '<p>Alonzo Church reached the same undecidability result in the same period by a',
    'different road, his lambda calculus, and the two constructions turned out to',
    'define the same class of computable functions. The claim that this shared class',
    'captures everything we would ever be willing to call "effectively calculable"',
    'is the Church-Turing thesis. It is not a theorem you can prove, it is a',
    'boundary the field has agreed to stand behind.</p>',
    '<div class="fs-aside"><p>A thing worth saying plainly: none of this 1936 work',
    'is about thinking machines. It is about the limits of formal calculation. The',
    'question of whether a machine could think came later, in 1950, and it is a',
    'separate argument even though the same man asked both.</p></div>',
    '<h2>Neighbours</h2>',
    '<p>The algebra underneath all this two-valued logic is set out at',
    '<a href="boolean-logic.geocities.ws">boolean-logic</a>, and the man who turned',
    'Turing\'s abstract machine into an actual architecture of stored programs is at',
    '<a href="von-neumann.geocities.ws">von-neumann</a>. For the 1950 imitation game,',
    'which is a different paper and a different question, the chatbots people keep a',
    'good page at <a href="turing-test.geocities.ws">turing-test</a>.</p>',
    '<hr>',
    '<p><small>counter: 02044 · best viewed at 800x600 · last updated 21 Apr ·',
    'under construction, adding a note on Church</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- McCulloch & Pitts: the clean academic summary --------------------------

const MCP = P('mcculloch-pitts.geocities.ws', 'McCULLOCH-PITTS',
  'McCULLOCH & PITTS // the artificial neuron', [
    '<!--bg:proto-->',
    '<h1>McCULLOCH, PITTS AND THE ARTIFICIAL NEURON</h1>',
    '<p><small>a summary page for a reading list in cognitive science. the paper is',
    'hard going and the notation has dated badly, so this is the plain-English',
    'version of what it claimed and why it mattered.</small></p>',
    '<hr>',
    '<h2>The paper</h2>',
    '<p>Warren McCulloch (1898 to 1969), a neurophysiologist, and Walter Pitts (1923',
    'to 1969), a self-taught logician still in his teens when they met, published',
    '"A Logical Calculus of the Ideas Immanent in Nervous Activity" in 1943, in the',
    '<i>Bulletin of Mathematical Biophysics</i>. It is one of the founding documents',
    'of the whole idea that thinking might be computation.</p>',
    '<h2>The model</h2>',
    '<p>They stripped the biological neuron down to a logic device. Their neuron is',
    'all-or-none: it receives inputs from other neurons, each either firing or not,',
    'and it fires itself only if enough of its excitatory inputs are active and none',
    'of its inhibitory inputs veto it. A threshold, a sum, a yes or a no. Time moves',
    'in discrete ticks. There is no in-between, no biochemistry, no gradient.</p>',
    '<blockquote class="fs-quote"><p>"for every net behaving under one assumption,',
    'there exists another net which behaves under the other and gives the same',
    'results."</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/ai/neuralnet-01.jpg" alt=""><span class="indie-cap">an artificial neural network (Cecbur, CC BY-SA)</span>',
    '<h2>The claim that made it famous</h2>',
    '<p>Because each neuron is really a little logic gate, a network of them can be',
    'wired to compute any logical proposition you like. And-relations, or-relations,',
    'negation, memory loops that hold a state: all buildable from these on-or-off',
    'units. The nervous system, on this picture, is not merely like a logical',
    'machine, it can be described as one. Mind becomes, in principle, a matter of',
    'connection and threshold.</p>',
    '<h2>What it seeded</h2>',
    '<p>Two big things grew from this root. First, it fed directly into John von',
    'Neumann\'s thinking about computing machines; he cited it, and the abstraction of',
    'the neuron as a switching element shaped how people talked about both brains and',
    'computers for a generation. Second, and more lastingly, it is the ancestor of',
    'the artificial neural network. Every unit in every net that followed is a',
    'descendant of this 1943 threshold neuron, made continuous and trainable.</p>',
    '<div class="fs-aside"><p>The trainable part is what these two did not have. Their',
    'neurons were hand-wired to a fixed logic; nothing learned. Making the connection',
    'strengths adjustable, so a net could be taught rather than built, was the next',
    'move, and it belongs to the people down the ring, not to 1943.</p></div>',
    '<h2>A word on Pitts</h2>',
    '<p>Walter Pitts was a prodigy who had taught himself logic from Russell and',
    'Whitehead as a boy. He fell into Wiener\'s circle at MIT and then, after a',
    'painful falling-out, into drink and obscurity; he died the same year as',
    'McCulloch, in 1969. The most original mind in the story left almost nothing',
    'under his own name. The 1943 paper carries most of what survives of it.</p>',
    '<h2>Neighbours</h2>',
    '<p>The line forward, to the first neuron that could actually learn, runs to',
    '<a href="perceptron-rosenblatt.geocities.ws">perceptron-rosenblatt</a>. The',
    'wider circle these two moved in, the feedback science that tried to put animal',
    'and machine in one frame, is at',
    '<a href="cybernetics-wiener.geocities.ws">cybernetics-wiener</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00893 · best viewed at 640x480 · last updated 2 Feb ·',
    'this page is part of a cog-sci reading list</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Wiener: the SHOWPIECE devotee's shrine ---------------------------------

const WIENER = P('cybernetics-wiener.geocities.ws', 'CYBERNETICS',
  'NORBERT WIENER // the science of steering', [
    '<!--bg:proto-->',
    '<h1>NORBERT WIENER AND CYBERNETICS</h1>',
    '<p><small>a shrine, i will not pretend otherwise, kept by someone who read',
    '<i>The Human Use of Human Beings</i> at the wrong age and never got over it. i',
    'have tried to keep the facts straight and let the feeling show at the edges.',
    'greetings to anyone else who loves this difficult, decent man. — R.</small></p>',
    '<p class="fs-epi">"We are not stuff that abides, but patterns that perpetuate',
    'themselves." — Norbert Wiener</p>',
    '<hr>',
    '<h2>The prodigy who became a conscience</h2>',
    '<p>Norbert Wiener (1894 to 1964) could read by three and took his doctorate at',
    'Harvard at eighteen, pushed hard and early by a demanding father. He spent his',
    'career at MIT. The child prodigy is the part people repeat; the part i care',
    'about is that he grew into one of the very few scientists of his century who',
    'stopped, in public, to ask what his own work would do to people.</p>',
    '<h2>Where the word comes from</h2>',
    '<p>In 1948 he published <i>Cybernetics: Or Control and Communication in the',
    'Animal and the Machine</i> and gave a science its name. He took the word from',
    'the Greek <i>kybernetes</i>, the steersman at the tiller, the same root that',
    'gives us "governor". The choice is the argument in miniature: this is the',
    'science of steering, of holding a course against whatever the sea does to you.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/wiener-01.jpg" alt=""><span class="indie-cap">Norbert Wiener (photo: Konrad Jacobs, CC BY-SA)</span>',
    '<h2>Feedback, the engine of the whole thing</h2>',
    '<p>The idea under everything is FEEDBACK. A system senses the gap between where',
    'it is and where it should be, acts to close that gap, then senses again, around',
    'and around. The thermostat, the ship\'s steering engine, a hand reaching for a',
    'cup and correcting as it goes, the body holding its own temperature: Wiener saw',
    'one pattern under all of them.</p>',
    '<blockquote class="fs-quote"><p>"the animal and the machine" was not a figure',
    'of speech for him. It was the claim that the same mathematics of control and',
    'communication describes both, for the first time in one language.</p></blockquote>',
    '<p>The war had set him on it. Working on a predictor for anti-aircraft fire,',
    'with Julian Bigelow, he had to model a gunner and a fleeing pilot as parts of a',
    'single feedback loop, and out of that came a 1943 paper with Arturo Rosenblueth,',
    '"Behavior, Purpose and Teleology", which dared to put purpose back into the',
    'description of a machine. Homeostasis, the body holding itself steady, sits in',
    'the same family. Control and communication, animal and machine, one science.</p>',
    '<h2>The Macy Conferences</h2>',
    '<p>Cybernetics was not a solo performance. From 1946 to 1953 a remarkable set of',
    'people gathered at the Macy Conferences in New York to argue it into being:',
    'Wiener, John von Neumann, Warren McCulloch and Walter Pitts, Margaret Mead and',
    'Gregory Bateson, Claude Shannon among them. Mathematicians, neurophysiologists,',
    'anthropologists in one room, which is why cybernetics never sat quietly in a',
    'single department. It was built to cross the lines.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/ibm704-01.jpg" alt=""><span class="indie-cap">an early computer (NASA, public domain)</span>',
    '<h2>The book i take my handle from</h2>',
    '<p>In 1950 he wrote <i>The Human Use of Human Beings</i>, the same ideas turned',
    'toward society, and it is the one to start with. Wiener was clear-eyed and, for',
    '1950, remarkably early. He warned that the automatic factory would concentrate',
    'power in very few hands and could throw the market value of ordinary human',
    'labour down toward nothing, the way the first industrial revolution once threw',
    'down the value of the arm.</p>',
    '<p class="fs-pull">The title is a warning folded into a pun: use human beings',
    'humanely, do not use them as spare machine parts.</p>',
    '<p>He did not say do not build it. He said know what you are building, and whose',
    'hands will hold it. A cybernetic society could go either way, and he could see',
    'which way the money pushed. The fuller social argument, and it is his best, is',
    'the one the folk over at <a href="human-use.geocities.ws">human-use</a> take',
    'their name from; go and read them, they are a good crowd.</p>',
    '<div class="fs-aside"><p>The fact i mention every time. After the war Wiener',
    'refused to do further military research and said so in print, in a 1947 piece,',
    'a scientist declining to hand his results to people who might use them to harm.',
    'It was not a fashionable thing to do in those years. It is, to me, the most',
    'important thing about him.</p></div>',
    '<h2>Why he matters now</h2>',
    '<p>Cybernetics is the science of steering, and a society that forgets it is',
    'steering gets steered by whoever holds the tiller. Wiener asked us to keep a',
    'hand on it, and to remember that the loop always runs back through a human',
    'body somewhere. That is the part later enthusiasts dropped, and it is the part',
    'worth keeping.</p>',
    '<h2>Neighbours</h2>',
    '<p>The logical neuron that fed straight into this circle is at',
    '<a href="mcculloch-pitts.geocities.ws">mcculloch-pitts</a>, and the man who was',
    'circling the same year from the side of the message, measuring information',
    'itself, is at <a href="shannon-information.geocities.ws">shannon-information</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01894 · best viewed at 800x600 · a shrine, kept with care ·',
    'under construction, forever · last updated 12 Oct</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Shannon: the clean academic summary ------------------------------------

const SHANNON = P('shannon-information.geocities.ws', 'SHANNON',
  'CLAUDE SHANNON // a mathematical theory', [
    '<!--bg:proto-->',
    '<h1>CLAUDE SHANNON AND INFORMATION THEORY</h1>',
    '<p><small>summary notes kept by an electrical-engineering student. i have tried',
    'to keep the maths light and the claims accurate. the toys at the end are real,',
    'i promise.</small></p>',
    '<hr>',
    '<h2>Two theses, both foundational</h2>',
    '<p>Claude Shannon (1916 to 2001) worked at Bell Labs and did two separate things',
    'that each would make a career. The first, his 1937 master\'s thesis, showed that',
    'Boole\'s two-valued algebra describes networks of electrical relays, so that you',
    'could design and simplify switching circuits by doing logic. That is the theory',
    'that made digital circuit design possible; the algebra behind it is over at',
    '<a href="boolean-logic.geocities.ws">boolean-logic</a>.</p>',
    '<h2>The 1948 paper</h2>',
    '<p>The second thing is the one this page is for. "A Mathematical Theory of',
    'Communication", published in the <i>Bell System Technical Journal</i> in 1948,',
    'founded information theory more or less complete in a single stroke. It asks a',
    'plain engineering question, how much can you reliably push down a noisy channel,',
    'and answers it with a whole new set of concepts.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/shannon-01.jpg" alt=""><span class="indie-cap">Claude Shannon (photo: Konrad Jacobs, CC BY-SA)</span>',
    '<h2>The bit</h2>',
    '<p>Shannon\'s decisive move was to separate the amount of information from its',
    'meaning entirely. Information, for him, is the reduction of uncertainty,',
    'measured in binary digits, and it was in this paper that the word "bit" first',
    'appeared in print. A message that could have been any of two equally likely',
    'things carries one bit when it arrives. He did not care in the least what the',
    'message said; he cared how surprised you should be to receive it.</p>',
    '<blockquote class="fs-quote"><p>"The fundamental problem of communication is',
    'that of reproducing at one point either exactly or approximately a message',
    'selected at another point."</p></blockquote>',
    '<h2>Channel capacity and the noisy-channel theorem</h2>',
    '<p>The result that stunned engineers was this. Every channel has a capacity, a',
    'ceiling in bits per second set by its bandwidth and its noise. Shannon proved',
    'that as long as you send below that ceiling, you can drive the error rate as',
    'close to zero as you like, with clever enough coding, and that above it you',
    'cannot. Nobody had thought reliable communication over an unreliable channel',
    'was even possible in principle. He showed exactly where the line falls.</p>',
    '<div class="fs-aside"><p>Note that Wiener was working the same territory in the',
    'same year, from the side of control and prediction. The two of them are the',
    'twin roots: Shannon measuring the message, Wiener steering the system. Neither',
    'reduces to the other, but they were reading each other closely.</p></div>',
    '<h2>The chess paper and the mouse</h2>',
    '<p>Shannon also had a playful streak that pointed straight at what became AI. In',
    '1950 he wrote "Programming a Computer for Playing Chess", the first serious',
    'account of how a machine might search a game tree and evaluate positions, and',
    'it set the terms for decades of computer chess. In the same period he built',
    'Theseus, a mechanical mouse that could learn its way through a maze and',
    'remember the route, one of the earliest demonstrations of a machine that',
    'learns from experience.</p>',
    '<h2>Neighbours</h2>',
    '<p>The two-valued algebra his first thesis rests on is at',
    '<a href="boolean-logic.geocities.ws">boolean-logic</a>. The theory of what a',
    'machine can compute at all, worked out the same decade, is at',
    '<a href="turing-machine.geocities.ws">turing-machine</a>.</p>',
    '<hr>',
    '<p><small>counter: 01502 · best viewed at 800x600 · last updated 30 Jan ·',
    'under construction</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Von Neumann: the clean academic summary --------------------------------

const VONNEUMANN = P('von-neumann.geocities.ws', 'VON NEUMANN',
  'JOHN VON NEUMANN // the architecture', [
    '<!--bg:proto-->',
    '<h1>JOHN VON NEUMANN</h1>',
    '<p><small>a summary page, kept by a history-of-computing enthusiast. the man did',
    'so many things that any one page is a scandal of omission, so this sticks to the',
    'four that touch the history of thinking machines.</small></p>',
    '<hr>',
    '<h2>The man</h2>',
    '<p>John von Neumann (1903 to 1957), born in Budapest, was one of the last people',
    'who could be first-rate across mathematics, physics, economics and computing at',
    'once. He worked at the Institute for Advanced Study in Princeton and on the',
    'Manhattan Project. This page leaves the bomb aside and takes the four',
    'contributions that bear on the history of AI.</p>',
    '<h2>One. The stored-program architecture</h2>',
    '<p>In 1945 he wrote the "First Draft of a Report on the EDVAC", which laid out a',
    'computer as a small set of parts, a memory holding both data and instructions, a',
    'processing unit, a control unit, and paths between them. The decisive idea is',
    'that the program lives in the same memory as the data, so a machine can treat',
    'its own instructions as things to be read and changed. This is the "von Neumann',
    'architecture", and near enough every computer since is built on it.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/vonneumann-01.jpg" alt=""><span class="indie-cap">John von Neumann (Wikimedia Commons, CC BY-SA)</span>',
    '<div class="fs-aside"><p>A fairness note. The draft circulated with only von',
    'Neumann\'s name on it, and the engineers who built the ENIAC and conceived much',
    'of the design, J. Presper Eckert and John Mauchly, never quite got their due',
    'for it. The idea was in the air at Penn, not his alone. He wrote it down',
    'clearly, which is its own kind of contribution, but he did not invent it in a',
    'vacuum.</p></div>',
    '<h2>Two. Self-reproducing automata</h2>',
    '<p>Von Neumann asked whether a machine could build a copy of itself, and',
    'answered it in the abstract, years before the structure of DNA was known. He',
    'designed, on paper, a cellular automaton, a grid of simple cells each following',
    'the same local rule, in which a configuration could read its own description and',
    'construct a working duplicate. The work was unfinished at his death and edited',
    'into print by Arthur Burks as <i>Theory of Self-Reproducing Automata</i> (1966).',
    'It is the deep root of artificial life.</p>',
    '<h2>Three. Game theory</h2>',
    '<p>With the economist Oskar Morgenstern he wrote <i>Theory of Games and Economic',
    'Behavior</i> (1944), founding game theory as a discipline: a mathematics of',
    'decision when other decision-makers are also choosing, each anticipating the',
    'rest. It runs under economics, strategy and, later, the reasoning of any agent',
    'that has to act against an opponent.</p>',
    '<h2>Four. The Computer and the Brain</h2>',
    '<p>At the end of his life, dying of cancer, he was writing the Silliman Lectures',
    'as a book comparing the two, <i>The Computer and the Brain</i>, published',
    'unfinished in 1958. It is careful and undogmatic. He notes that the brain works',
    'in a language unlike our arithmetic, more statistical, more analog than digital,',
    'and warns against assuming the machine and the brain compute the same way. A',
    'sober last word from a man who had every reason to overclaim.</p>',
    '<blockquote class="fs-quote"><p>"The language of the brain is not the language',
    'of mathematics."</p></blockquote>',
    '<h2>Neighbours</h2>',
    '<p>The theory of computation his architecture makes physical is at',
    '<a href="turing-machine.geocities.ws">turing-machine</a>; the two men knew and',
    'read each other. And the 1956 summer meeting where the name "artificial',
    'intelligence" was coined, which Shannon helped convene and which stands at the',
    'head of the field proper, is at <a href="dartmouth-1956.geocities.ws">',
    'dartmouth-1956</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01310 · best viewed at 800x600 · last updated 17 May ·',
    'under construction, the game-theory section wants expanding</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const AIH_A = [BOOLE, TURING, MCP, WIENER, SHANNON, VONNEUMANN];
