// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH HOME_I — the Acorn machines from the inside.
//
// The corpus had the hardware and the story and none of the USE. Four pages on
// what it was actually like: the language, the operating system underneath it,
// the noise the drives made, and the failure.
//
// THE STAR COMMANDS PAGE IS THE ONE THAT MATTERS to everything else in this
// archive. A star command is a line handed to the machine's own command
// interpreter, and any ROM in the machine may claim one, which means the
// operating system is extensible by anybody who can burn an EPROM. A player who
// has been typing at an ML prompt on an island runs into a 1981 home computer
// whose command line was designed to be extended by strangers, and nothing on
// the page points that out.
//
// Facts checked: BBC BASIC by Sophie Wilson; PROC/FN, REPEAT/UNTIL and the
// inline 6502 assembler in square brackets; resident integer variables A% to Z%;
// MODE 7 teletext at 1K against 20K for the high-resolution modes; DFS with a
// 31-file catalogue and no hierarchy; ADFS bringing directories; unrecognised
// star commands offered round the sideways ROMs.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

const RING = [
  '<hr>',
  '<p><small>',
  '[ <a href="home-computers-ring.geocities.ws">Home Computers Ring</a> ]<br>',
  'ring member. « prev · random · next »',
  '</small></p>',
];

// ---- BBC BASIC ---------------------------------------------------------------

const BASIC = P('bbc-basic.geocities.ws', 'BBC BASIC',
  'Programming in BBC BASIC', [
    '<!--bg:eightbit-->',
    '<h1>BBC BASIC</h1>',
    '<p><small>Why the people who learned on this one are insufferable about',
    'it.</small></p>',
    '<img class="indie-pic" src="assets/media/web/home/bbcmicro-01.jpg" alt=""><span class="indie-cap">The machine. The BASIC was in ROM and came up in about a second (photo via Wikimedia)</span>',
    '<hr>',
    '<p>Every home computer of the period came with a BASIC and most of them were',
    'bad. Line numbers, GOTO, two-letter variable names, and no way to organise',
    'anything, so a program of any size became a swamp.</p>',
    '<p>Sophie Wilson wrote the one in the BBC Micro and it is a different',
    'language wearing the same name.</p>',
    '<h2>Procedures and functions with names</h2>',
    '<p>This is the whole thing. You could write:</p>',
    '<pre>',
    '   10 REM shields',
    '   20 PROCdraw_ship(x%, y%)',
    '   30 IF hit% THEN PROCexplode ELSE PROCscan',
    '   40 END',
    '   50 :',
    '   60 DEF PROCdraw_ship(px%, py%)',
    '   70   MOVE px%, py% : DRAW px%+40, py%+20',
    '   80 ENDPROC',
    '</pre>',
    '<p>A named procedure, with parameters, and LOCAL variables inside it. On a',
    'machine where the competition was still doing GOSUB 2400 and hoping.</p>',
    '<p>So a fourteen-year-old writing on a Beeb was writing structured code',
    'without being told that was what it was called, and a fourteen-year-old on',
    'most other machines was not, and you can hear the difference twenty years',
    'later in how they talk about programs.</p>',
    '<h2>Proper loops</h2>',
    '<pre>',
    '   REPEAT',
    '     PROCread_keys',
    '     PROCmove_everything',
    '     PROCdraw',
    '   UNTIL fired% OR lives% = 0',
    '</pre>',
    '<p>REPEAT ... UNTIL, and FOR ... NEXT, and IF ... THEN ... ELSE on one line.',
    'You could go a long way without a single GOTO and most people did.</p>',
    '<h2>The integer variables</h2>',
    '<p>A percent sign makes a variable an integer, and <b>A% to Z%</b> are',
    'special: they live at fixed addresses, they are not cleared by RUN, and they',
    'are fast. Everybody used them for the inner loops.</p>',
    '<p>This is the first piece of performance thinking most of us ever did and',
    'nobody explained it, we just noticed that the version with the percent signs',
    'was quicker.</p>',
    '<h2>The assembler is in the language</h2>',
    '<p>Now the part that makes people go quiet.</p>',
    '<pre>',
    '   DIM code% 200',
    '   FOR pass% = 0 TO 2 STEP 2',
    '     P% = code%',
    '     [ OPT pass%',
    '       LDA #65',
    '       JSR &amp;FFEE      \\\\ OSWRCH: print it',
    '       RTS',
    '     ]',
    '   NEXT',
    '   CALL code%',
    '</pre>',
    '<p>Square brackets, and inside them you are writing <b>6502 assembly</b>, in',
    'the same program, assembled by the BASIC, with BASIC variables usable as',
    'labels and addresses. Two passes because the first one does not know where',
    'the forward references land.</p>',
    '<p>No other home BASIC did this. It meant the step from BASIC to machine',
    'code was not a step: you wrote the slow bit in BASIC, found the part that',
    'was too slow, and put brackets round it.</p>',
    '<h2>Graphics and sound</h2>',
    '<pre class="jb-list">',
    '  MODE 0-7    screen modes. MODE 7 is teletext and',
    '              costs 1K; MODE 0 is 640x256 and costs',
    '              20K, on a machine with 32K',
    '  PLOT/DRAW   proper line drawing, and triangle fill',
    '  VDU         send codes straight at the screen driver',
    '  SOUND       channel, amplitude, pitch, duration',
    '  ENVELOPE    fourteen numbers describing how a note',
    '              changes over time, and nobody has ever',
    '              understood all fourteen',
    '</pre>',
    '<p>The memory arithmetic is the thing that shaped what got written. Choosing',
    'MODE 0 spent two thirds of the machine on the screen. Most games are in',
    'MODE 1, 2 or 5 for exactly that reason, and MODE 7 exists so that a text',
    'program can have twenty-nine of the thirty-two kilobytes.</p>',
    '<hr>',
    '<p>See also <a href="star-commands.geocities.ws">the star commands</a>,',
    'which is the machine underneath this, and',
    '<a href="type-in-listings.geocities.ws">the listings</a>.</p>',
    ...RING,
  ]);

// ---- star commands -----------------------------------------------------------

const STAR = P('star-commands.geocities.ws', 'STAR COMMANDS',
  'The star commands, and the machine underneath BASIC', [
    '<!--bg:eightbit-->',
    '<h1>*</h1>',
    '<p><small>What the asterisk does, and why it is the cleverest thing in the',
    'machine.</small></p>',
    '<hr>',
    '<p>Type a line beginning with a star and BASIC does not look at it. It hands',
    'the rest of the line straight to the <b>Machine Operating System</b>, which',
    'is a separate thing living in its own ROM underneath.</p>',
    '<p>So the prompt you are sitting at is two command lines at once: a language',
    'above, an operating system below, and one character to choose.</p>',
    '<h2>The ones everybody knew</h2>',
    '<pre class="jb-list">',
    '  *CAT          catalogue the disc. Say "cat"',
    '  *.            the same thing, and what people',
    '                actually typed',
    '  *RUN prog     load and run a machine-code file',
    '  */prog        the same, shorter',
    '  *LOAD, *SAVE  bytes to and from an address',
    '  *HELP         ask every ROM in the machine what it',
    '                answers to, and they all reply',
    '  *TAPE         use the cassette',
    '  *DISC         use the disc',
    '  *SPOOL out    copy everything printed from here on',
    '                into a file',
    '  *EXEC in      feed a file to the keyboard as if it',
    '                were being typed',
    '  *KEY 0 text|M  program the red function keys',
    '  *OPT 1,2      turn on the filing-system messages',
    '  *TV 255,1     shift the picture up, fix the wobble',
    '</pre>',
    '<p><b>*SPOOL and *EXEC together are a shell script</b>, in 1981, on a school',
    'computer. Spool a session to a file, edit it, exec it back, and the machine',
    'types it to itself.</p>',
    '<h2>*FX</h2>',
    '<p>The general-purpose one. <code>*FX a,b,c</code> calls the OSBYTE routine',
    'with three numbers, and the numbers do everything the operating system can',
    'do that has no nicer name.</p>',
    '<pre class="jb-list">',
    '  *FX 4,1       cursor keys become ordinary keys',
    '  *FX 12,0      keyboard auto-repeat back to normal',
    '  *FX 15,1      throw away anything typed ahead',
    '  *FX 21,0      flush the keyboard buffer',
    '  *FX 200,3     disable ESCAPE and clear memory on',
    '                BREAK, which is how you stopped',
    '                somebody listing your program',
    '  *FX 210,1     silence',
    '</pre>',
    '<p>Nobody remembered these. Everybody had them written on the back of an',
    'exercise book, copied off somebody else, and the good numbers travelled',
    'round a school like folklore.</p>',
    '<h2>The part that is genuinely elegant</h2>',
    '<p>The MOS does not know most of these commands.</p>',
    '<p>When it gets a star command it does not recognise, it offers it round',
    '<b>every ROM in the machine</b> in turn, and each one gets a chance to say',
    'that is mine, and handle it. The filing system is a ROM. The word processor',
    'is a ROM. A ROM you burned yourself and pushed into a spare socket is a ROM.</p>',
    '<p>Which means the operating system&rsquo;s command set is <b>extensible by',
    'strangers</b>. Buy a chip, put it in the machine, and the machine has new',
    'commands, and *HELP will list them, and nothing had to be recompiled and',
    'nobody had to ask Acorn.</p>',
    '<p>People paid for sideways ROM boards with sixteen sockets on them so they',
    'could have more of this.</p>',
    '<hr>',
    '<p>See also <a href="bbc-basic.geocities.ws">BBC BASIC</a> and',
    '<a href="the-disc-drive.geocities.ws">the drives</a>.</p>',
    ...RING,
  ]);

// ---- the drives --------------------------------------------------------------

const DISC = P('the-disc-drive.geocities.ws', 'THE DISC DRIVE',
  'The noises, and the filing systems that made them', [
    '<!--bg:eightbit-->',
    '<h1>The drive</h1>',
    '<p><small>On the sound, which everybody who used one can still do out loud,',
    'and why it was information and not decoration.</small></p>',
    '<img class="indie-pic" src="assets/media/web/home/floppy-01.jpg" alt=""><span class="indie-cap">Five and a quarter inches, genuinely floppy, in a paper sleeve (photo via Wikimedia)</span>',
    '<hr>',
    '<h2>The sound</h2>',
    '<p>Type <code>*CAT</code> and the drive answers before the screen does.</p>',
    '<p>A single hard <b>clack</b> as the head loads. Then the seek: a fast dry',
    'rattle as the stepper drags the head across the surface, one track at a time,',
    'and you can hear the individual steps. Then it settles into a rhythm, and',
    'the rhythm is the file being read.</p>',
    '<p>You learned it without deciding to. A short trip meant the file was near',
    'the middle. A long clattering run out and back meant the disc was fragmented',
    'and this was going to take a moment. A repeated identical rattle, over and',
    'over, in the same place, meant a bad sector and the drive retrying, and your',
    'stomach dropped before the error came up.</p>',
    '<p>That is the point worth making. The noise was <b>a progress bar with',
    'error reporting</b>, and it was free, and it was accurate, and nobody',
    'designed it. Modern storage is silent and tells you nothing.</p>',
    '<h2>And the tape, which was worse and better</h2>',
    '<img class="indie-pic" src="assets/media/web/home/datasette-01.jpg" alt=""><span class="indie-cap">The other way in. Four minutes if it worked (photo via Wikimedia)</span>',
    '<p>Before the drive, cassette. Press play, press RETURN, and listen.</p>',
    '<p>A steady tone: that is the leader, the machine is finding its footing.',
    'Then the data, which is a harsh two-tone screech at about twelve hundred',
    'baud, and on the screen the block numbers going up in hex.</p>',
    '<p>You could hear a failure coming. The tone wavering meant the azimuth was',
    'off or the tape had stretched, and you would reach for the head-alignment',
    'screw with a jeweller&rsquo;s screwdriver while it was still playing,',
    'because you could tune it by ear, live, and people got extremely good at',
    'this.</p>',
    '<p>And then <code>Data?</code> at block 3B of 5F and you rewound and did the',
    'whole four minutes again.</p>',
    '<h2>DFS</h2>',
    '<p>The Disc Filing System. What most Beebs had.</p>',
    '<pre class="jb-list">',
    '  100K   single sided, 40 track',
    '  200K   80 track, and the drives that could do',
    '         both had a switch on the front',
    '  31     files in the catalogue. Thirty-one. Full',
    '         is full whatever the free space says',
    '  7      characters in a filename',
    '  $      the directory. There are others, one',
    '         letter each, and they are not folders,',
    '         they are a letter in front of the name',
    '</pre>',
    '<p>No hierarchy at all. Thirty-one files, flat, and when you filled it you',
    'got another disc, which is why everybody had a box of them with the labels',
    'written over three times.</p>',
    '<h2>ADFS</h2>',
    '<p>The Advanced Disc Filing System, which arrived with the later machines',
    'and brought the thing DFS did not have: <b>real directories</b>, nested, with',
    'a proper path.</p>',
    '<pre class="jb-list">',
    '  *DIR games      go into a directory',
    '  *DIR ^          go back up one',
    '  *CDIR work      make one',
    '  $.games.elite   a path, from the root',
    '</pre>',
    '<p>And 640K on a disc instead of 200K, and a bigger catalogue, and it was',
    'slower on floppy and everybody said so, and it was the right thing anyway.</p>',
    '<p>The argument about whether ADFS was worth it went on for years in the',
    'magazines and split almost exactly along the line of whether you had more',
    'than thirty-one files.</p>',
    '<hr>',
    '<p>See also <a href="star-commands.geocities.ws">*CAT and the rest</a>.</p>',
    ...RING,
  ]);

// ---- why it failed -----------------------------------------------------------

const WHYFAILED = P('why-the-archimedes-failed.geocities.ws', 'WHY IT FAILED',
  'Why the Archimedes failed', [
    '<!--bg:eightbit-->',
    '<h1>Why the Archimedes failed</h1>',
    '<p><small>Asked in the pub about once a year and never answered properly,',
    'so here it is at length. It is not one reason.</small></p>',
    '<img class="indie-pic" src="assets/media/web/home/archimedes-01.jpg" alt=""><span class="indie-cap">The A3000. Faster than anything you could buy and almost nobody bought it (photo via Wikimedia)</span>',
    '<hr>',
    '<p>1987. A machine with a processor Acorn had designed themselves, that',
    'outran everything on the market, in a case that cost less to make than the',
    'competition, running a windowing system that was quick.</p>',
    '<p>It should have won. Here is what actually happened, and the order matters,',
    'because the reasons compound.</p>',
    '<h2>1. It was late to a question already settled</h2>',
    '<p>By 1987 the business world had answered the compatibility question and',
    'the answer was the IBM PC. Not because the PC was good. Because everybody',
    'else had one, and the files opened, and the person who bought it did not get',
    'sacked for it.</p>',
    '<p>Speed does not beat that. Nothing beats that. The Archimedes was fast at',
    'a moment when nobody senior was asking how fast.</p>',
    '<h2>2. No software, and the reason is circular</h2>',
    '<p>Developers write for the machines people have. People buy the machines',
    'with software. Neither side moves first, and a new architecture has to break',
    'the loop with money, and Acorn did not have that money.</p>',
    '<p>So it had a good word processor, a superb art package, some genuinely',
    'excellent games, and none of the things a business had standardised on.</p>',
    '<h2>3. Education was a trap as well as a market</h2>',
    '<p>Acorn owned the British classroom, and that kept the company alive and',
    'shaped everything.</p>',
    '<p>But a schools supplier sells to committees, on contracts, in a market',
    'that is protected and therefore not competitive. It builds no consumer',
    'brand and no retail presence. And when the schools decided they had better',
    'teach the machines children would meet at work, the whole market went at',
    'once, and there was nothing else underneath it.</p>',
    '<h2>4. It was a British company and stayed one</h2>',
    '<p>Almost no presence in America, which is where the volume was, where the',
    'software houses were, and where the press that mattered was.</p>',
    '<p>A machine that is unknown in the United States in the late eighties is a',
    'regional machine whatever it can do.</p>',
    '<h2>5. The price war it could not fight</h2>',
    '<p>PC clones from a dozen makers, all compatible, all undercutting each',
    'other, all commodity. Acorn had one machine, made by one company, and could',
    'not get into that fight because there was no second source and nobody',
    'cloning it. The thing that made it theirs is the thing that kept it',
    'expensive.</p>',
    '<h2>6. Nobody was told</h2>',
    '<p>The marketing was poor and everybody who was there says so. A machine',
    'whose entire case is that it is faster than you think has to be demonstrated,',
    'and it mostly was not, outside education and the enthusiast magazines.</p>',
    '<h2>And the answer nobody wants</h2>',
    '<p>It did not fail.</p>',
    '<p>Acorn built that processor because they needed one and could not buy what',
    'they wanted, and the design was small, cheap to make and used almost no',
    'power, because it had to run in a home computer without a fan.</p>',
    '<p>Those three properties are exactly what a battery-powered device needs.',
    'The processor was spun out, and licensed rather than sold, and it is now in',
    'a very large proportion of the objects in your house.</p>',
    '<p>The company went. The machine went. The part they made because they had',
    'no other option is the most widely manufactured processor design in history,',
    'and it came out of a small firm in Cambridge that mostly sold to schools.</p>',
    '<hr>',
    '<p>See also <a href="acorn-archimedes.geocities.ws">the machine</a> and',
    '<a href="arm-story.geocities.ws">what happened to the chip</a>.</p>',
    ...RING,
  ]);


// ---- STOS --------------------------------------------------------------------
//
// The other side of the same coin as the BBC BASIC page: a language sold to
// people who wanted to make a game rather than learn to program, and which
// therefore put sprites, scrolling and music in as verbs. Its author went on to
// do it again on the Amiga.
//
// Checked: Jawx, being François Lionet and Constantin Sotiropoulos; Mandarin
// Software, 1988, Atari ST, after an earlier French release; 2.3 shipping with
// Orbit, Zoltar and Bullet Train; the compiler arriving after the interpreter;
// AMOS in 1990 dropping line numbers; the source released via Clickteam around
// 2001.

const STOS = P('stos-basic.geocities.ws', 'STOS',
  'STOS BASIC — the game creator', [
    '<!--bg:eightbit-->',
    '<h1>STOS</h1>',
    '<p><small>Atari ST, 1988. A BASIC with sprites in the language, sold to',
    'people who wanted to finish something.</small></p>',
    '<hr>',
    '<p>Written by <b>Jawx</b>, which is François Lionet and Constantin',
    'Sotiropoulos, published in Britain by Mandarin Software in 1988 after a',
    'French release, and subtitled <i>The Game Creator</i>, which is an honest',
    'description of what it was for.</p>',
    '<h2>What was different about it</h2>',
    '<p>Every other BASIC treated graphics as something you did to a screen',
    'a pixel at a time. STOS put the things a game is made of into the language',
    'itself, as commands, with the hard parts already done.</p>',
    '<pre class="jb-list">',
    '  sprites      a real sprite system: define, move,',
    '               animate, and collision detection you',
    '               did not have to write',
    '  screens      several of them, swapped and copied',
    '  scrolling    as a command, not as an exercise',
    '  music        composed in an editor and played from',
    '               the program',
    '</pre>',
    '<p>Which means a fifteen-year-old could have something moving about the',
    'screen and colliding with something else on the first evening, on a machine',
    'where doing that properly otherwise meant knowing the ST&rsquo;s insides.</p>',
    '<h2>What was in the box</h2>',
    '<p>Version 2.3 came with three finished games, Orbit, Zoltar and Bullet',
    'Train, and the point of them was not that they were good. It was that they',
    'were <b>written in STOS and you had the source</b>, so you could open one,',
    'see how it worked, and take it apart.</p>',
    '<p>And a sprite editor, and a music editor, and the accessory disc.</p>',
    '<h2>The extensions</h2>',
    '<p>It was extensible and a small industry grew round that: <b>Maestro</b>',
    'for sampled sound, a 3D extension, an STE extension for the later machines,',
    'Control, Extra, Ninja Tracker. Some official, some not.</p>',
    '<p>And a <b>compiler</b>, which arrived after the interpreter and mattered',
    'enormously, because the standard complaint about STOS was that it was slow',
    'once you stepped outside the high-level commands.</p>',
    '<h2>The fair criticisms</h2>',
    '<p>Two, and both are true.</p>',
    '<p>It was slow when you were not using the commands it was built around.',
    'The sprite routines are quick because somebody wrote them in assembler; your',
    'own loop is a BASIC loop.</p>',
    '<p>And it encouraged bad structure. Line numbers, GOTO, and no real',
    'procedures, so a STOS program that got past a certain size became the same',
    'swamp as every other BASIC. It gave you the graphics of a modern language',
    'and the shape of an old one.</p>',
    '<h2>AMOS</h2>',
    '<p>Lionet did it again on the Amiga, in 1990, and the two years in between',
    'were spent well: <b>AMOS</b> dropped line numbers and had proper structured',
    'constructs, and is the better language, and is the one people who had both',
    'machines remember with real affection.</p>',
    '<p>The source of STOS was released around 2001, through Clickteam, which is',
    'the company Lionet ended up at, still making tools for people who want to',
    'produce something without first becoming programmers. That is one straight',
    'line from 1988 to now.</p>',
    '<hr>',
    '<p>See also <a href="bbc-basic.geocities.ws">BBC BASIC</a>, which is the',
    'opposite argument: a language that taught structure and made you do the',
    'graphics yourself.</p>',
    ...RING,
  ]);

export const HOME_I = [BASIC, STAR, DISC, WHYFAILED, STOS];
