// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// GAME A — the arcade golden age.
//
// Fan pages kept on a free host by an arcade regular, a high-score obsessive
// who logs patterns, cheats and cabinet lore the way other people keep a
// diary. A Pac-Man walkthrough shrine with the ghost table and the kill
// screen; a close reading of Space Invaders; a Donkey Kong how-to; a Defender
// best-of; a Tempest fan shrine; a Robotron design appreciation. The people,
// studios and years are real; the bragging and the grudges are the fan's.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Pac-Man: the walkthrough / high-score shrine (SHOWPIECE) ---------------

const PACMAN = P('pac-man-patterns.geocities.ws', 'PAC-MAN',
  'PAC-MAN // patterns, ghosts and the kill screen', [
    '<!--bg:games-arcade-->',
    '<h1>PAC-MAN</h1>',
    '<p><small>the maze i have played more than any other, kept by someone who',
    'still has the callus. Toru Iwatani, Namco, 1980. i learnt the patterns off a',
    'photocopied sheet a bloke in the arcade sold me for a pound and i have been',
    'refining them for years. corrections welcome, brag posts welcome. — coinop_col</small></p>',
    '<hr>',
    '<div class="fs-epi"><p>PAC-MAN. Namco. 1980. INSERT COIN.</p>',
    '<p><small>— attract mode, every arcade i ever stood in</small></p></div>',
    '<p>Iwatani has said he wanted a game that was not about shooting, one that',
    'would pull women and couples into an arcade full of blokes hammering',
    'Space Invaders. He landed on eating. The story he tells is that the shape of',
    'the hero came from a pizza with a slice taken out, and whether that is',
    'polished up for the telling or not, the character reads instantly, which is',
    'the whole trick. You are a mouth in a maze and you are hungry.</p>',
    '<div class="fs-aside"><p><b>DID YOU KNOW.</b> The original Japanese release',
    'was <i>Puck Man</i>. It was changed to Pac-Man for the West so that people',
    'could not scratch the P on the cabinet into something ruder. The maze, the',
    'dots, the four ghosts and the four power pellets were there from the start.</p></div>',
    '<h2>the four ghosts, and why they are not random</h2>',
    '<p>This is the thing people never quite believe until you show them. The four',
    'ghosts do not chase you at random. Each one runs its own logic, and once you',
    'read the logic the maze stops being frightening and starts being solvable.</p>',
    '<pre>',
    'GHOST     JAPANESE   PERSONALITY (how it hunts)',
    '-------   --------   -------------------------------------------',
    'BLINKY    the red    direct pursuit. aims at your tile. speeds',
    '                     up when the dots run low ("Cruise Elroy").',
    'PINKY     the pink   ambush. aims four tiles AHEAD of your nose,',
    '                     so it tries to cut you off, not follow.',
    'INKY      the cyan   the awkward one. uses Blinky\'s position',
    '                     AND yours to pick a square. hard to read.',
    'CLYDE     the orange   chases when far, runs for his corner when',
    '                     close. the coward. the one you exploit.',
    '</pre>',
    '<p>Because the behaviour is fixed, the whole board is fixed. The same inputs',
    'from the same start give the same result every time, and that is what a',
    'pattern IS. You are not reacting to the ghosts, you are running a route you',
    'already know is safe and letting their fixed logic slide past you.</p>',
    '<img class="indie-pic" src="assets/media/web/games/iwatani-01.jpg" alt=""><span class="indie-cap">Toru Iwatani, who designed it (photo: Official GDC, CC BY 2.0)</span>',
    '<div class="fs-quote"><blockquote><p>"The ghosts had to have their own',
    'characters. If they all did the same thing it would have been boring."</p>',
    '<p><small>— Toru Iwatani, on the four personalities</small></p></blockquote></div>',
    '<h2>power pellets and the eyes</h2>',
    '<p>Eat a power pellet and the ghosts turn blue and flee, and now you hunt',
    'them. Four in a row is 200, 400, 800, 1600, so the greedy play is to herd',
    'them together and take all four off one pellet. Eat a ghost and only the eyes',
    'go scuttling back to the box in the middle to be reborn. Later in the game the',
    'blue time shrinks, then it stops happening at all, and by then you had better',
    'be living on patterns because fear will not save you.</p>',
    '<div class="fs-pull"><p>learn one pattern per board and you will out-live every',
    'button-masher in the room. it is not reflexes. it is homework.</p></div>',
    '<h2>the kill screen: level 256</h2>',
    '<p>Here is the famous one. Reach level 256 and the right-hand half of the',
    'maze dissolves into a mess of garbled letters and numbers. The board is',
    'unplayable. It is not a designed ending, it is a BUG. The level counter is',
    'held in a single byte, which can only count from 0 to 255. On the 256th board',
    'the routine that draws the fruit at the bottom tries to draw 256 pieces of',
    'fruit, the counter rolls over, and the drawing runs off the end and vomits',
    'over half the screen. The game did not plan to end. It ran out of number.</p>',
    '<div class="fs-aside"><p><b>THE PERFECT GAME.</b> A perfect Pac-Man is every',
    'dot, every pellet, every ghost on every pellet, and every fruit, all the way',
    'to the kill screen, for the maximum 3,333,360 points with not one point',
    'missed. Billy Mitchell was reported as the first to do it, in 1999. The',
    'record scene has argued about Mitchell for years since; whatever you make of',
    'that, the perfect score itself is a fixed mathematical ceiling and the number',
    'does not move.</p></div>',
    '<h2>my board</h2>',
    '<pre>',
    'RANK  NAME  SCORE      NOTE',
    '----  ----  ---------  ----------------------------',
    '  1   COL   3,333,360  the perfect run. one time. never again.',
    '  2   COL   2,150,900  clean to 173, choked on a Pinky ambush.',
    '  3   DEK   1,904,220  local rival. claims a witness. no photo.',
    '  4   COL     998,760  the first time i ever cleared board 100.',
    '  5   ???     900,000  someone put initials  ASS. very funny.',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/games/joystick-01.jpg" alt=""><span class="indie-cap">An Atari joystick (photo: Evan-Amos, public domain)</span>',
    '<h2>where to go next</h2>',
    '<p>If you like the fixed-pattern thing, the other 1981 giant to study is',
    '<a href="donkey-kong-screens.geocities.ws">Donkey Kong</a>, where the barrels also',
    'run rules you can learn. And you cannot understand why Pac-Man mattered',
    'without the game it was reacting against, so go and read',
    '<a href="space-invaders-descent.geocities.ws">Space Invaders</a>, the one that',
    'filled the arcades with shooting before Iwatani filled them with eating.</p>',
    '<hr>',
    '<p><small><b>SPOILER WARNING:</b> yes this whole page spoils the kill screen',
    'and the ghost logic. that is the point of a walkthrough. if you wanted to',
    'find it out yourself you should not have scrolled this far.</small></p>',
    '<p><small>hits: 25,600 · best viewed in Netscape at 800x600 · this page under',
    'eternal construction · last updated 4 Aug · a proud stop on the gamers webring</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- Space Invaders: the ORG / close-reading page ---------------------------

const SPACEINVADERS = P('space-invaders-descent.geocities.ws', 'SPACE INVADERS',
  'SPACE INVADERS // reading the descent (Nishikado)', [
    '<!--bg:games-arcade-->',
    '<h1>SPACE INVADERS</h1>',
    '<p><small>a close reading of the game that started it, by someone who thinks',
    'you can read a game the way you read anything else. Tomohiro Nishikado,',
    'Taito, 1978. no high scores on this page, just argument. — the archivist</small></p>',
    '<hr>',
    '<p>Nishikado built almost all of it himself, hardware and software both, and',
    'he has said the machine he had was not fast enough to draw everything he',
    'wanted. That limit is the reason the game feels the way it feels, and this is',
    'the bit worth reading closely.</p>',
    '<h2>the speed-up is an accident that became the whole game</h2>',
    '<p>Watch a row of invaders at the top of the screen. They shuffle slowly.',
    'Now clear most of them and watch the last few. They move fast, and faster,',
    'until the final alien is skittering across the line like something panicked.',
    'Players read this as the aliens getting braver as their numbers thin, a nerve',
    'that grips you as the board empties. It was not designed as drama. The',
    'processor could only redraw so many sprites per frame. With forty invaders on',
    'screen it was slow, so they crawled. With one invader left the processor had',
    'almost nothing to draw, so it ran quick. The acceleration is the hardware',
    'showing through. Nishikado noticed it made the game better and kept it.</p>',
    '<div class="fs-quote"><blockquote><p>"When there were fewer invaders the',
    'program had less to process, so they moved faster. I decided to leave it in',
    'because it made the game more exciting."</p>',
    '<p><small>— Tomohiro Nishikado, on the speed-up</small></p></blockquote></div>',
    '<p>So the tension you feel is a limit of 1978 silicon, kept because a good',
    'designer knew a gift when he saw one. The medium is not hiding under the game.',
    'The medium is right there on the screen, quickening.</p>',
    '<img class="indie-pic" src="assets/media/web/games/arcade-cabinet-01.jpg" alt=""><span class="indie-cap">An arcade cabinet (photo: Halcyanide, CC BY-SA 4.0)</span>',
    '<h2>the template it laid down</h2>',
    '<p>Almost everything the shoot-em-up would do for the next decade is here in',
    'the first one. You have a fixed gun at the bottom that slides left and right.',
    'You have waves that descend, drop a row, reverse, and descend again, so the',
    'threat gets closer with every pass. You have four bunkers you shelter behind,',
    'which erode as they take fire from both sides until there is nowhere left to',
    'hide. And you have a score that the machine remembers, the high score sitting',
    'at the top of the screen as a thing to beat. That last one changed arcades.',
    'A number to chase is a reason to put another coin in.</p>',
    '<h2>the coin shortage, and whether to believe it</h2>',
    '<p>The famous story is that Space Invaders was so popular in Japan that it',
    'caused a national shortage of 100-yen coins. It is repeated everywhere. The',
    'sober version is that this is very likely a legend, or at least badly',
    'exaggerated, since the mint simply made more coins and the demand was regional',
    'and seasonal. What is not a legend is the scale. Taito filled entire parlours',
    'with nothing but these cabinets, and the game is fairly credited with kicking',
    'off the golden age of the arcade outright.</p>',
    '<div class="fs-aside"><p><b>TRIVIA.</b> The invaders were not always aliens.',
    'Nishikado first thought of soldiers, tanks and planes, and backed off human',
    'targets as too grim. He looked to <i>The War of the Worlds</i> and the',
    'octopus-like Martian for the shape, which is why the top-row invader reads a',
    'little like a squid.</p></div>',
    '<h2>where to go next</h2>',
    '<p>The game that answered this one by refusing to be about shooting is',
    '<a href="pac-man-patterns.geocities.ws">Pac-Man</a>, and you should read the two',
    'together. For where the shoot-em-up went once designers stopped keeping you',
    'still, go and stand in front of <a href="defender.geocities.ws">Defender</a>,',
    'which unlocked the screen and let it scroll, and nearly broke everyone\'s',
    'hands doing it.</p>',
    '<hr>',
    '<p><small>visitors: 08,142 · best viewed in Netscape at 800x600 · under',
    'construction, more sections to come · last updated 21 Jul · member of the',
    'gamers webring</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- Donkey Kong: the walkthrough -------------------------------------------

const DONKEYKONG = P('donkey-kong-screens.geocities.ws', 'DONKEY KONG',
  'DONKEY KONG // how to clear all four screens', [
    '<!--bg:games-arcade-->',
    '<h1>DONKEY KONG</h1>',
    '<p><small>the how-to for the four screens, kept by someone who has run the',
    'board so many times he counts the barrels in his sleep. Shigeru Miyamoto,',
    'Nintendo, 1981. spoilers all the way down, obviously. — hammer_time</small></p>',
    '<hr>',
    '<p>The story of this one is famous. Nintendo had a flop on their hands, a lot',
    'of unsold cabinets of a game called Radar Scope, and they handed a young',
    'staff designer named Shigeru Miyamoto the job of turning them into something',
    'people would play. He was not a hardware engineer, he was the man who could',
    'draw and who thought about story, and what he made was the first true',
    'platform game. A carpenter has to climb a building to rescue a woman from a',
    'big ape who keeps throwing things at him. That is a scenario, not just a',
    'target, and games were not usually built out of scenarios yet.</p>',
    '<div class="fs-aside"><p><b>NAMES.</b> The hero was called Jumpman on the',
    'cabinet. He became Mario later. The captured woman is Pauline. Donkey Kong is',
    'the ape, and yes the name is meant to read as "stubborn gorilla", Miyamoto',
    'reaching for English out of a dictionary. Jumpman jumps because that is the',
    'one verb the game gives you, and the whole design is built on that one verb.</p></div>',
    '<h2>the four screens</h2>',
    '<p>People forget there are four boards, because the first one is the icon.',
    'Here is the run.</p>',
    '<pre>',
    'SCREEN 1  THE RAMPS. sloped girders, barrels rolling down, the',
    '          hammer power-up. climb without getting flattened.',
    'SCREEN 2  THE RIVETS / CEMENT FACTORY. moving lifts and bouncing',
    '          springs come off the right edge. timing, not nerve.',
    'SCREEN 3  THE ELEVATORS. ride the platforms up, dodge the',
    '          fireballs, mind the gap you fall through.',
    'SCREEN 4  THE RIVETS FINALE. pull out all eight rivets and the',
    '          structure collapses, Kong falls, you get Pauline.',
    '</pre>',
    '<p>Clear the fourth and it loops back harder. The barrels on screen one are',
    'the thing everyone dies to, so learn them. A barrel will usually roll down a',
    'ramp and take the ladder down to the next, but sometimes it carries straight',
    'on past the ladder, and reading which is which is the skill. Grab the hammer',
    'and for a few seconds you can smash barrels for points, but you cannot climb',
    'or jump while you swing it, so a greedy hammer run gets you cornered.</p>',
    '',
    '<div class="fs-pull"><p>the barrels are not random. they favour the ladders.',
    'stand one tile clear of a ladder top and most of them commit before they',
    'reach you.</p></div>',
    '<h2>why it matters</h2>',
    '<p>This was Nintendo\'s arcade breakthrough in the West, the game that made',
    'the company money in America and set up everything after. More than that, it',
    'is where the platform game is born, the whole idea of climbing a structure of',
    'ledges and ladders with one jump button and a hazard you have to time. Every',
    'jump-and-climb game owes this board. And it is where Miyamoto starts, the man',
    'who would go on to Mario and Zelda from this one flop-rescue job.</p>',
    '<h2>where to go next</h2>',
    '<p>For the other fixed-pattern classic of this exact era, the maze that',
    'rewards homework over reflexes, read <a href="pac-man-patterns.geocities.ws">Pac-Man</a>.',
    'And if you want to see what an arcade screen could do when it stopped being a',
    'flat cartoon and became pure glowing line, go to',
    '<a href="tempest.geocities.ws">Tempest</a> and look down the tube.</p>',
    '<hr>',
    '<p><small>counter: 06,027 · best viewed in Netscape at 800x600 · this shrine',
    'is under construction forever · last updated 30 Jun · gamers webring member</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- Defender: the best-of / fan site ---------------------------------------

const DEFENDER = P('defender.geocities.ws', 'DEFENDER',
  'DEFENDER // the hardest game in the arcade (Jarvis)', [
    '<!--bg:games-arcade-->',
    '<h1>DEFENDER</h1>',
    '<p><small>a shrine to the cabinet that beat me for a whole summer before it',
    'let me in. Eugene Jarvis, Williams, 1981. this page argues Defender is the',
    'greatest arcade game ever made and i will not be softening that. — nightingale</small></p>',
    '<hr>',
    '<p>Everybody who walked up to a Defender cabinet in 1981 put their coin in,',
    'died in about eight seconds, and walked off calling it unfair. It looked like',
    'chaos. Five buttons and a two-way stick and a screen full of stuff moving in',
    'every direction at once. Jarvis has cheerfully admitted it was probably too',
    'hard, and it did badly on first location test before it became one of the',
    'biggest earners of the era. The people who stayed found the best game on the',
    'floor. Here is my case, as a list, because that is what a fan page is for.</p>',
    '<h2>why Defender is the greatest, an ordered list</h2>',
    '<pre>',
    '1. THE MINIMAP. a scanner strip across the top showing the whole',
    '   planet at once. you fly your bit of the world and read the',
    '   rest on radar. arcade games did not do this. Defender did.',
    '2. THE HORIZONTAL SCROLL. the world is wider than the screen and',
    '   wraps around. you choose which way to fly. a game about a',
    '   place, not a screen.',
    '3. THE HUMANS. ten little people on the surface. the landers try',
    '   to abduct them, lift them to the top, and mutate them into',
    '   fast killers. you can catch a falling human and set them down.',
    '4. THE PANEL. thrust, reverse, fire, smart bomb, hyperspace, on a',
    '   five-button hand that nobody could work at first. once it is in',
    '   the fingers it feels like flying a real thing.',
    '5. THE STAKES. let all ten humans die and the planet explodes and',
    '   the whole world turns to a hellscape of mutants. you are not',
    '   playing for score alone, you are keeping a world alive.',
    '</pre>',
    '<div class="fs-aside"><p><b>THE SMART BOMB AND HYPERSPACE.</b> The smart bomb',
    'clears the screen, and you get very few, so hoard them for the moment the',
    'scanner fills with red. Hyperspace jumps you to a random spot and might drop',
    'you straight onto an enemy or blow you up outright. It is the button you',
    'press when you have already decided you are dead anyway.</p></div>',
    '',
    '<div class="fs-quote"><blockquote><p>"I wanted the feeling of being',
    'overwhelmed, of defending something you were probably going to lose."</p>',
    '<p><small>— Eugene Jarvis, on the design</small></p></blockquote></div>',
    '<p>That losing feeling is the point. Most arcade games put you on the attack.',
    'Defender puts you on defence, outnumbered, over a planet you cannot quite',
    'save, and asks how long you can hold. The name is not decoration.</p>',
    '<h2>where to go next</h2>',
    '<p>Jarvis took the twin-stick idea further the very next year, stripped out',
    'the scroll and boiled the intensity down to one screen, and made',
    '<a href="robotron-2084.geocities.ws">Robotron: 2084</a>. If you love Defender',
    'you owe Robotron an afternoon. And for where the whole shooting arcade began,',
    'the game Defender is descended from, go back to',
    '<a href="space-invaders-descent.geocities.ws">Space Invaders</a> and see how far four',
    'years took it.</p>',
    '<hr>',
    '<p><small>hits: 04,410 · best viewed in Netscape at 800x600 · perpetually',
    'under construction · last updated 12 Aug · a member of the gamers webring</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- Tempest: the personal fan shrine ---------------------------------------

const TEMPEST = P('tempest.geocities.ws', 'TEMPEST',
  'TEMPEST // down the tube (Theurer, Atari)', [
    '<!--bg:games-arcade-->',
    '<h1>TEMPEST</h1>',
    '<p><small>my favourite cabinet in the whole world, and this page is a love',
    'letter to it, nothing more clever than that. Dave Theurer, Atari, 1981. i',
    'was the kid who fed it fifty-pence pieces until they threw me out at closing.',
    ' — spinner</small></p>',
    '<hr>',
    '<p>You do not so much look at Tempest as look DOWN it. The playfield is a',
    'tube coming out of the screen towards you, drawn in glowing vector lines, and',
    'you sit on the near rim and the enemies climb up the walls at you from the',
    'far end. It runs on Atari\'s colour vector hardware, so the lines are not',
    'painted on a normal screen, they are drawn by the beam itself, which is why',
    'the colours have that hot electric glow that a photo never quite catches.</p>',
    '<div class="fs-epi"><p>SUPERZAPPER RECHARGE.</p>',
    '<p><small>— the two words every Tempest player loves to see</small></p></div>',
    '<p>Theurer has said the idea came partly out of a nightmare about monsters',
    'crawling out of a hole in the ground, and once you know that you cannot',
    'unsee it. The whole game is a hole in the ground with things coming out.</p>',
    '<h2>the things that climb the tube</h2>',
    '<pre>',
    'FLIPPER   the basic enemy. flips along the rim towards your lane.',
    '          get it before it reaches the top or it eats you.',
    'SPIKER    crawls up a lane laying a SPIKE behind it. fly into a',
    '          spike at the round\'s end and you die. shoot them down.',
    'TANKER    a carrier. shoot it and it splits into two of whatever',
    '          it was carrying. more targets, not fewer.',
    'PULSAR    electrifies its whole lane. do not be sitting in a lane',
    '          that lights up.',
    'FUSEBALL  bounces between lanes, awkward, drifts up at you sideways.',
    '</pre>',
    '',
    '<p>You have the SUPERZAPPER, which clears the tube, but you only get to fire',
    'it fully once per level. The second press in a level barely does anything, so',
    'the discipline is to save the good one for the moment the rim fills with',
    'flippers and you are about to be swarmed. At the end of each level you fly',
    'DOWN the tube into the next one, through the field of spikes you did or did',
    'not clear, and that little descent is the best three seconds in the arcade.</p>',
    '<div class="fs-pull"><p>i will never be able to explain the colour to anyone',
    'who only saw it in a photo. you had to stand in front of the glass in a dark',
    'arcade. it glowed like nothing else on the floor.</p></div>',
    '<div class="fs-aside"><p><b>TRIVIA.</b> Tempest was one of the first games to',
    'let you pick your starting level, so a good player could skip ahead to a',
    'harder tube and rack up a bigger score faster. The spinner controller, a dial',
    'you whip round the rim with, is part of why it feels so good and why nothing',
    'quite plays like it on a joystick.</p></div>',
    '<h2>where to go next</h2>',
    '<p>For the other great fixed board of 1981, the one built on climbing and one',
    'jump button, go to <a href="donkey-kong-screens.geocities.ws">Donkey Kong</a>. And',
    'for the game that took pure arcade intensity to its absolute limit a year',
    'later, no scroll, no tube, just a screen and a swarm, read',
    '<a href="robotron-2084.geocities.ws">Robotron: 2084</a>.</p>',
    '<hr>',
    '<p><small>counter: 02,084 · best viewed in Netscape at 800x600 · this shrine',
    'is under construction and always will be · last updated 8 Aug · gamers',
    'webring, come find the rest of us</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

// ---- Robotron: 2084: the design-appreciation page ---------------------------

const ROBOTRON = P('robotron-2084.geocities.ws', 'ROBOTRON',
  'ROBOTRON: 2084 // the perfect arcade machine (Jarvis, DeMar)', [
    '<!--bg:games-arcade-->',
    '<h1>ROBOTRON: 2084</h1>',
    '<p><small>an appreciation of a design that i think is as close to perfect as',
    'the arcade ever got. Eugene Jarvis and Larry DeMar, Williams, 1982. this is',
    'not a walkthrough, there is no trick to it, there is only the thing itself.',
    ' — the design desk</small></p>',
    '<hr>',
    '<p>Jarvis had made <a href="defender.geocities.ws">Defender</a> the year',
    'before, a game people called too complicated, five buttons and a scanner and',
    'a scrolling world. With Robotron he did the opposite. He threw away the scroll,',
    'threw away the buttons, and asked what is the smallest, purest arcade game you',
    'can build. The answer is a single screen, a swarm, and two joysticks.</p>',
    '<h2>the twin-stick idea</h2>',
    '<p>There is no fire button on a Robotron cabinet. There are two sticks. The',
    'left stick moves you. The right stick shoots, in whichever of the eight',
    'directions you push it. That one decision is the whole game. It means you can',
    'run one way and fire the other, backpedalling while you rake a line of fire',
    'across the enemies chasing you, and it means your hands are doing two',
    'completely separate jobs at once with no time to think about either. The',
    'controls are the design. Nothing about the story could carry a game this fast.</p>',
    '<div class="fs-quote"><blockquote><p>"There is no end. You cannot win. You',
    'just play until you die. It is about survival."</p>',
    '<p><small>— Eugene Jarvis, on Robotron</small></p></blockquote></div>',
    '',
    '<p>The setup, such as it is: it is the year 2084, the Robotrons have turned on',
    'their makers, and you are a lone mutant defending the last human family. The',
    'family run about the screen as Mommy, Daddy and Mikey, and you save them by',
    'touching them, for points and for the small human reason that they are the',
    'last ones left. You cannot save them all. The screen fills faster than you',
    'can clear it, wave after wave, and the difficulty curve only ever goes up.</p>',
    '<div class="fs-aside"><p><b>THE ENEMIES.</b> The Grunts walk straight at you',
    'and speed up as the wave thins. The Hulks cannot be killed and only shoved,',
    'so they herd you into corners. The Brains reprogram the humans into Progs that',
    'hunt you. The Enforcers and the spinning Electrodes fill the gaps. Every enemy',
    'is a different kind of pressure and they all arrive at once.</p></div>',
    '<h2>why it is the pure case</h2>',
    '<p>Robotron does not have a level you are working towards or a boss you are',
    'building up to beat. It has no win condition at all. It is the arcade',
    'proposition stated with nothing left out and nothing to hide behind. Put a',
    'coin in, survive as long as your hands can, watch the number climb, and when',
    'you die the machine asks for another coin. Jarvis stripped the form down to',
    'its bones and the bones turned out to be enough.</p>',
    '<pre>',
    'CONTROL   LEFT STICK move (8 way) · RIGHT STICK fire (8 way)',
    'GOAL      survive waves · rescue the human family for points',
    'ENEMIES   Grunts, Hulks (unkillable), Brains, Progs, Enforcers',
    'END       there is none. you play until you die.',
    '</pre>',
    '<h2>where to go next</h2>',
    '<p>Read this alongside its older, wider sibling',
    '<a href="defender.geocities.ws">Defender</a>, and you can watch one designer',
    'ask the same question two ways. And for the other 1981 machine that chased',
    'pure sensation over story, the glowing vector tube, go to',
    '<a href="tempest.geocities.ws">Tempest</a>.</p>',
    '<hr>',
    '<p><small>hits: 02,084 · best viewed in Netscape at 800x600 · under',
    'construction · last updated 15 Aug · listed on the gamers webring</small></p>',
    '<p><small>[ <a href="games-ring.geocities.ws">Games Ring</a> ]</small></p>',
  ]);

export const GAME_A = [PACMAN, SPACEINVADERS, DONKEYKONG, DEFENDER, TEMPEST, ROBOTRON];
