// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// THE MACHINES BATCH: HIP-HOP, THE SAMPLER, HOUSE, TECHNO.
//
// Six cached pages about the boxes that were meant for something else. The
// turntable was a playback device and somebody made it an instrument. The
// TR-808 and the TB-303 were commercial flops, dumped cheap into the second-hand
// shops, and a generation who could not afford anything better built three
// musics out of them. The sampler turned every record ever pressed into raw
// material, and then the law caught up and shut the door.
//
// Each page is by a fan, never in the artist's voice: a battle DJ who diagrams
// the crossfader, an electro crate-digger, a beatmaker still furious about
// sample-clearance, a gear collector with the serial numbers written down, a
// Chicago clubber, and a Detroit head who reads Toffler. The scholarship under
// them is real: the records, the machines, the dates, the court case. Where the
// author is going on memory or riding a hobby-horse, it shows, because that is
// what these pages were.
//
// FOLDED people, named in prose or in a source-comment so nobody is missed:
// DJ Kool Herc and Grand Wizzard Theodore (who invented the scratch), Arthur
// Baker and John Robie (who built Planet Rock in the studio), DJ Pierre and
// Phuture (who found the acid in the 303), Ron Hardy and Larry Sherman of Trax,
// Alvin Toffler and Rick Davis behind the word techno.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- 1. Grandmaster Flash: the turntable as an instrument -------------------

const GRANDMASTER_FLASH = P('grandmaster-flash.geocities.ws', 'GRANDMASTER FLASH',
  'GRANDMASTER FLASH · the science of the wheels of steel', [
    '<!--bg:rave-->',
    '<h1>GRANDMASTER FLASH</h1>',
    '<p><small>a turntablist’s page. no mixing tips for sale, i worked mine out',
    'the way he did, off the record and off the label. — DJ Halftime</small></p>',
    '<hr>',
    '<p>Everybody who tells the story starts it in the wrong place. It does not',
    'start with a rapper. It starts with a man treating two Technics and a mixer',
    'as one instrument with six moving parts, and the instrument is the point.</p>',
    '<p>Before Flash there was <b>DJ Kool Herc</b>, who worked out that the best',
    'four bars of a record are the break, the bit where the band drops out and',
    'the drummer carries it, and that with two copies of the same record you can',
    'keep the break going by cutting from one to the other. Herc called it the',
    'merry-go-round. It was a huge idea and it was rough as anything, because',
    'Herc did it by eye and by luck and it drifted.</p>',
    '<h2>Quick mix theory</h2>',
    '<p>What Joseph Saddler did, and he is precise about this, was turn Herc’s',
    'trick into a method you could hit every single time. He called it the',
    '<b>quick mix theory</b>. You mark the record. You find the front of the',
    'break, and you look at the label as a clock face, so a certain groove is',
    'always at, say, the ten o’clock, and you crayon a line there. Now you can',
    'spin the record back to the exact top of the break with your hand while the',
    'other deck plays out, and drop it in on the one. Round and round, no drift,',
    'a four-bar loop made of two records and two hands. That is the',
    '<b>clock theory</b> underneath it, and it is the most practical piece of',
    'thinking in the whole of this music.</p>',
    '<p>Then the crossfader. Flash rebuilt his mixer so he could cue one deck in',
    'the headphones while the room heard the other, which sounds obvious and was',
    'not, and it is the thing that makes the cut invisible. His young friend',
    '<b>Grand Wizzard Theodore</b> is the one who then found the scratch, moving',
    'the record back and forth under the needle as a sound in itself, more or',
    'less by accident with his mum shouting at him to turn it down. Between the',
    'two of them the deck stopped being a thing that plays records and became a',
    'thing you play.</p>',
    '<pre class="jb-list">',
    '  the rig, as i run mine',
    '  ----------------------',
    '  deck L  ──┐',
    '            ├─►  mixer, crossfader in the middle, cue in the phones',
    '  deck R  ──┘',
    '  two copies of the same record on both. crayon on the label.',
    '  left hand backspins, right hand rides the fader. that is the instrument.',
    '</pre>',
    '<h2>A record made of records</h2>',
    '<p>The proof is on wax. <i>The Adventures of Grandmaster Flash on the Wheels',
    'of Steel</i>, 1981, Sugar Hill. Seven inches, and there is no band on it.',
    'It is Flash, live, cutting between Chic’s “Good Times”, Blondie’s “Rapture”,',
    'Queen, the Furious Five’s own stuff, a spoken-word record, all of it done in',
    'one take on the decks and pressed as it happened. A record composed entirely',
    'of other records, played by hand. People argue about the first this and the',
    'first that; nobody has shown me an earlier one that actually is this.</p>',
    '<p>My view, and i will defend it: the turntable is the first great',
    'instrument built out of a machine that was designed only to play back. That',
    'is why this page is filed with the drum machines and the samplers and not',
    'with the bands. The idea that you take a consumer object and misuse it into',
    'an instrument runs straight from Flash’s crossfader to the sampler two',
    'streets over, and the man who ran with it hardest was',
    '<a href="afrika-bambaataa-planet-rock.geocities.ws">Bambaataa</a>, who put',
    'the same cut-and-loop mind onto a drum machine and made the record that',
    'split hip-hop off into electro.</p>',
    '<p>And the argument about whose records they are, and whether you are allowed',
    'to build a new one out of them, is exactly the fight the',
    '<a href="public-enemy-bomb-squad.geocities.ws">Bomb Squad</a> walked into a',
    'few years later. Flash could cut “Good Times” up live in a park and nobody',
    'sent a lawyer. Put the same thing on a sampler and press ten thousand of it',
    'and you find out fast whose it is. Read their page, it goes into the law.</p>',
    '<hr>',
    '<p><small>best viewed at 800x600 with the bass turned up. this page is',
    'always under construction because i am always finding out i had a date',
    'wrong. last updated 9 Feb.</small></p>',
    '<p><small>you are visitor 004417.</small></p>',
    '<p><small>rings: [ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="studio-as-instrument-ring.geocities.ws">The Studio as Instrument</a> ]<br>',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]</small></p>',
  ]);

// ---- 2. Afrika Bambaataa / Planet Rock: the 808 and the Kraftwerk lift ------

const PLANET_ROCK = P('afrika-bambaataa-planet-rock.geocities.ws', 'PLANET ROCK',
  'PLANET ROCK · where hip-hop met the machine', [
    '<!--bg:rave-->',
    '<h1>Afrika Bambaataa &amp; the Soulsonic Force — “Planet Rock”</h1>',
    '<p><small>an electro page, kept by a crate-digger who will bore you about the',
    'exact records this one is welded together from. — Rockers Delight (the b-boy',
    'not the label)</small></p>',
    '<hr>',
    '<p>1982, Tommy Boy. If Flash’s <i>Wheels of Steel</i> is the last word of',
    'hip-hop made from other people’s bands, “Planet Rock” is the first word of',
    'hip-hop made from a machine, and you can hear the join because the machine',
    'is a <b>Roland TR-808</b> and nothing else on earth sounds like an 808.</p>',
    '<h2>What it is built from</h2>',
    '<p>Two Kraftwerk records, mainly, and this is not a rumour, it is right there',
    'in your ears. The melody — that cold, marching, unforgettable line — is',
    '“Trans-Europe Express” (1977). The rhythm and the feel are lifted off',
    '“Numbers”, from <i>Computer World</i> (1981). Bambaataa loved Kraftwerk, put',
    'them on in the Bronx next to James Brown and did not think that was a strange',
    'thing to do, and out of that came the whole of electro. There is a',
    'page on <a href="kraftwerk.geocities.ws">kraftwerk.geocities.ws</a> that',
    'goes at the Dusseldorf end of it properly; i am at the Bronx end. Between',
    'us that one record is the hinge.</p>',
    '<p>Over the top of the 808 it was Bambaataa with <b>Arthur Baker</b> and the',
    'keyboard player <b>John Robie</b> in the studio actually assembling it, and',
    'credit where it is due, because “Planet Rock” is as much a production as it',
    'is a DJ record. But the sound people went home humming is the drum machine',
    'and the Kraftwerk line, and both of those are somebody taking a European',
    'electronic record and a Japanese box and making something neither was for.</p>',
    '<h2>The box</h2>',
    '<p>That 808 is the same discontinued flop the house and techno people were',
    'about to build on, and it is worth its own page, which it has:',
    '<a href="roland-808-303.geocities.ws">the Roland 808 &amp; 303</a>. Short',
    'version: Roland could not sell them, dumped them cheap, and “Planet Rock”',
    'is the record that told everyone with two hundred dollars what the thing was',
    'actually for. The booming kick that goes on too long, the cowbell, the',
    'handclap. Once this record was out, that kick was the sound of the future',
    'for about ten years.</p>',
    '<p>My own view is that “Planet Rock” matters more than the records',
    'everyone calls more important, because it is the fork in the road. Down one',
    'branch, hip-hop stays with the breakbeat and the sampler and gets to the',
    '<a href="public-enemy-bomb-squad.geocities.ws">Bomb Squad</a>. Down the',
    'other, this exact drum machine goes to Detroit and Chicago and comes back as',
    'techno and house. It all runs through <a href="grandmaster-flash.geocities.ws">Flash’s</a>',
    'basic idea — take the machine you were sold and use it wrong — but this is',
    'the day it stopped being turntables and started being circuits.</p>',
    '<p>The Zulu Nation politics behind Bambaataa i will leave to people who were',
    'in it. Peace, unity, and having a better record collection than you: that is',
    'as far as i am qualified to go.</p>',
    '<hr>',
    '<p><small>corrections to the sample list especially welcome, i have been',
    'wrong before. best played loud. last updated 21 Jan.</small></p>',
    '<p><small>rings: [ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="electronic-tape-ring.geocities.ws">Electronic &amp; Tape Music</a> ]<br>',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]</small></p>',
  ]);

// ---- 3. Public Enemy / the Bomb Squad: the sampler and the law --------------

const BOMB_SQUAD = P('public-enemy-bomb-squad.geocities.ws', 'BOMB SQUAD',
  'THE BOMB SQUAD · a record the law made illegal to make again', [
    '<!--bg:rave-->',
    '<h1>PUBLIC ENEMY / THE BOMB SQUAD</h1>',
    '<p><small>written by somebody who makes beats on an SP and is STILL ANGRY',
    'about this. read to the bottom, it turns into a copyright argument and i am',
    'not sorry. — T. on the MPC</small></p>',
    '<hr>',
    '<p><i>It Takes a Nation of Millions to Hold Us Back</i>, 1988, Def Jam. The',
    'loudest, densest, most crowded record anybody had made out of other records,',
    'and the reason it exists at all is a three-year window that slammed shut',
    'right after, and has never opened again.</p>',
    '<h2>How dense</h2>',
    '<p>The <b>Bomb Squad</b> — Hank Shocklee, his brother Keith, Eric “Vietnam”',
    'Sadler, and Chuck D having the ideas — did not build a beat around one',
    'sample the way people do now. They layered dozens. A single track like',
    '“Rebel Without a Pause” or “Bring the Noise” has a horn stab off one record,',
    'a drum off another, a squeal off a third, a siren, a bit of a speech, all',
    'stacked and fighting, and the fighting is the sound. That saxophone shriek on',
    '“Rebel” is the JBs’ “The Grunt”, pitched up until it is a weapon.</p>',
    '<p>The tools were an <b>E-mu SP-1200</b> and the SP-12 before it, and the',
    'E-mu Emulator. Twelve-bit samplers with a few seconds of memory, so you had',
    'to be brutal about what you kept, and the crunch the SP put on everything is',
    'half the character. Same family of idea as',
    '<a href="grandmaster-flash.geocities.ws">Flash</a> cutting two copies of a',
    'break by hand — take the good four seconds off somebody else’s record — only',
    'now the good four seconds are captured, chopped and rebuilt into something',
    'the original band would not recognise.</p>',
    '<h2>Then the door shut</h2>',
    '<p>Here is the part that keeps me up. Hank Shocklee has said, plainly, that',
    'they could not make <i>Nation of Millions</i> today, because you cannot',
    'clear that many samples and you cannot afford them if you could. And he is',
    'right, and here is why.</p>',
    '<p>In 1991 a court ruled against Biz Markie for sampling without a licence',
    '— the “Alone Again” case, <i>Grand Upright v. Warner</i> — and after that',
    'every sample had to be cleared and paid for before the record came out.',
    'Reasonable if you think a sample is theft. But look at what it did: it made',
    'the Bomb Squad’s method economically impossible. A record built from forty',
    'sources needs forty licences, forty lawyers, forty payments, and no label',
    'will fund that, so the music that came after got thinner. The law did not',
    'ban a style. It priced it out, which comes to the same thing.</p>',
    '<p>This is the same argument the code people are having, and they have said',
    'it better than i can. <a href="critical-code.geocities.ws">critical-code.geocities.ws</a>',
    'is worth reading on who owns a thing that is made out of copies, and',
    '<a href="decss.geocities.ws">decss.geocities.ws</a> is the sharpest case of',
    'the lot — a few lines that a court tried to make illegal to publish. A',
    'sampler is a copy machine you play like an instrument, and the question the',
    'law keeps asking it is the question it asked DeCSS: when does copying become',
    'making. The Bomb Squad answered it on a record in 1988 and the courts have',
    'been disagreeing ever since.</p>',
    '<p>My conclusion is simple and it is not neutral. The best sample record ever',
    'made is also an argument, and it won the argument on the turntable and lost',
    'it in the courtroom, and we have been living in the losing side of that for',
    'thirty years.</p>',
    '<hr>',
    '<p><small>THIS PAGE IS NOT FINISHED and never will be, there is always',
    'another source to add. mail me your isolated breaks. last updated 3 Mar.',
    '</small></p>',
    '<p><small>rings: [ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="studio-as-instrument-ring.geocities.ws">The Studio as Instrument</a> ]<br>',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]</small></p>',
  ]);

// ---- 4. Roland TR-808 & TB-303: two flops that built three musics -----------

const ROLAND_808_303 = P('roland-808-303.geocities.ws', 'ROLAND 808 &amp; 303',
  'ROLAND TR-808 &amp; TB-303 · the machines nobody wanted', [
    '<!--bg:rave-->',
    '<h1>ROLAND TR-808 &amp; TB-303</h1>',
    '<p><small>a collector’s page. i have the serials written down. i am the',
    'person who tells you the “wrong” sounds are the whole point, at parties,',
    'until you leave. — the Machine Room (Coventry)</small></p>',
    '<hr>',
    '<p>Two boxes. Both sold badly. Both discontinued and forgotten. Both then',
    'dug back out of the second-hand shops by people who could not afford a real',
    'drummer or a real bass player, and turned into the foundation of hip-hop,',
    'house, techno and acid. If you want the argument of this whole corner of my',
    'site in two objects, it is these.</p>',
    '<h2>TR-808 Rhythm Composer, 1980</h2>',
    '<p>Roland wanted a drum machine that sounded like drums. The 808 does not',
    'sound like drums. It uses analogue circuits, not samples, so the kick is a',
    'tuned boom you can stretch out forever, the snare is a papery snap, the',
    'hi-hats are a hiss and there is that cowbell. In 1980 that counted as',
    '<i>wrong</i>, and the LinnDrum came along using real recorded drums and ate',
    'Roland’s lunch, so the 808 was dropped around 1983 after something like',
    'twelve thousand of them. Twelve thousand. Then it turned up cheap, and',
    '<a href="afrika-bambaataa-planet-rock.geocities.ws">“Planet Rock”</a> told',
    'everyone what the boom was for, and Marvin Gaye put it under “Sexual',
    'Healing”, and Miami built a whole scene on that kick. The thing failed for',
    'exactly the reason it then won: it does not sound real, it sounds like a',
    'machine, and a generation decided that was the sound they wanted.</p>',
    '<h2>TB-303 Bass Line, 1981</h2>',
    '<p>Sadder story, better ending. The 303 was sold to guitarists as a practice',
    'gadget: program a bassline into it, play your guitar over the top, pretend',
    'you have a band. It was fiddly to program, it did not sound like a bass',
    'guitar, and it sold so badly Roland killed it in 1984 after about ten',
    'thousand. Then somebody in Chicago — the record is Phuture’s “Acid Tracks”',
    'and the man usually credited is <b>DJ Pierre</b> — twisted the knobs while',
    'it was running, in real time, and got that squelching, sliding, liquid',
    'scream nobody had asked it for. That is acid. A bass machine that could not',
    'do a bass, misused into a sound with its own genre named after it.</p>',
    '<pre class="jb-list">',
    '  what i can tell you off the serials',
    '  -----------------------------------',
    '  TR-808   1980, analogue voices, no samples   dropped ~1983',
    '  TB-303   1981, one oscillator, a filter,     dropped ~1984',
    '           a resonance knob that is the        both bought cheap,',
    '           whole of acid house                 both irreplaceable now',
    '</pre>',
    '<p>How they work as objects is the engineers’ department, and they do it',
    'properly over at <a href="silicon-ring.geocities.ws">the silicon ring</a> —',
    'the chips, the filter circuit, why a bit of analogue drift is a feature and',
    'not a fault. I am a listener with a screwdriver, not a designer, and i send',
    'the circuit questions their way.</p>',
    '<p>Where these two go next is the two rooms next door. The 808 and a',
    'reel-to-reel and a disco record become house with',
    '<a href="frankie-knuckles-house.geocities.ws">Frankie Knuckles</a> in',
    'Chicago. The same machines in the hands of three kids outside Detroit become',
    '<a href="detroit-techno.geocities.ws">techno</a>. Neither city could have',
    'afforded to do it with anything that had been designed properly and sold',
    'well. The failure is not a footnote to the story. The failure is why there',
    'was anything cheap enough to start the story with.</p>',
    '<hr>',
    '<p><small>if you are selling a working 303 do not tell me the price, tell me',
    'the story, i cannot afford either. best viewed at 800x600. last updated',
    '17 Feb.</small></p>',
    '<p><small>you are visitor 002980.</small></p>',
    '<p><small>rings: [ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="silicon-ring.geocities.ws">The Silicon Ring</a> ]<br>',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]</small></p>',
  ]);

// ---- 5. Frankie Knuckles / Chicago house: the edit and the terrible vinyl ---

const FRANKIE_KNUCKLES = P('frankie-knuckles-house.geocities.ws', 'FRANKIE KNUCKLES',
  'FRANKIE KNUCKLES · house, and the pressings that crackled', [
    '<!--bg:rave-->',
    '<h1>FRANKIE KNUCKLES / CHICAGO HOUSE</h1>',
    '<p><small>kept by somebody who was too young for the Warehouse and has spent',
    'years making up for it. the crackle on my Trax records is not on yours',
    'differently, it is on everyone’s. — Marshall, still up</small></p>',
    '<hr>',
    '<p>The word “house” comes off a building. The <b>Warehouse</b> in Chicago,',
    'where Frankie Knuckles was the resident from 1977, and “house music” started',
    'as shorthand in the record shops for the kind of thing they played at the',
    'Warehouse. That is the whole etymology and people still get it wrong, so:',
    'a room, a DJ, a name that stuck.</p>',
    '<h2>The edit</h2>',
    '<p>Knuckles did not have techno to play, because it did not exist yet. He had',
    'disco, and disco was dying and getting three minutes a side, and the crowd',
    'wanted the good part to last. So he made it last. Reel-to-reel tape, a razor',
    'blade, splice the break of a disco record back onto itself so it runs for',
    'eight minutes instead of one, and then — this is the move — put a drum',
    'machine underneath it to drive it and cover the joins. A Roland box, the',
    'same cheap discontinued family i go on about on the',
    '<a href="roland-808-303.geocities.ws">808 and 303 page</a>, thumping away',
    'under an old disco record you have surgically extended. That is house,',
    'before anybody made a house record. It is an editing technique first and a',
    'genre second.</p>',
    '<p>Ron Hardy over at the Music Box was doing his own harder, wilder version',
    'of the same thing at the same time, and the two rooms fed each other. I am',
    'not going to pretend i can settle who did what first; people who were there',
    'cannot either.</p>',
    '<h2>The pressings</h2>',
    '<p>And now the bit that makes me laugh and cry. When Chicago started pressing',
    'its own house records, the main label was <b>Trax</b>, run by Larry Sherman,',
    'and Trax records sound <i>terrible</i>. Not the music. The vinyl. Sherman',
    'had a pressing plant and, the story goes, pressed new records on recycled',
    'vinyl — melted-down returns and old stock — so the pressings came out grey,',
    'thin, warped and crackling before you had even played them. Records that',
    'were noisy in the shrink-wrap.</p>',
    '<p>Here is my actual view, and it is not the romantic one you expect. That',
    'terrible vinyl is part of the sound of house whether we like it or not,',
    'because for years the only copy anyone had of the foundational records was a',
    'crackling Trax pressing, and that surface noise got into people’s ears as',
    'part of the thing. But do not tell me the crackle is beautiful. It is a man',
    'saving money on your favourite record. The music survived the pressing; it',
    'was not improved by it.</p>',
    '<p>Where it goes from here is up the interstate. The same machines, a',
    'different city, a colder idea: <a href="detroit-techno.geocities.ws">Detroit',
    'techno</a>. House warms the machine up and keeps it dancing; Detroit lets',
    'it stay a machine. Read them next.</p>',
    '<hr>',
    '<p><small>this page best viewed loud and late. if you have a first-press',
    'Trax that does NOT crackle, you have a fake, sorry. last updated 28 Jan.',
    '</small></p>',
    '<p><small>you are dancer number 006120.</small></p>',
    '<p><small>rings: [ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="studio-as-instrument-ring.geocities.ws">The Studio as Instrument</a> ]<br>',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]</small></p>',
  ]);

// ---- 6. Detroit techno: the Belleville Three and the machine question -------

const DETROIT_TECHNO = P('detroit-techno.geocities.ws', 'DETROIT TECHNO',
  'DETROIT TECHNO · the Belleville Three and the future they built', [
    '<!--bg:rave-->',
    '<h1>DETROIT TECHNO</h1>',
    '<p><small>Juan Atkins · Derrick May · Kevin Saunderson. kept by somebody who',
    'thinks this is the most serious music of the century and will argue it sober.',
    '— K., after the last train</small></p>',
    '<hr>',
    '<p>Three kids who met at Belleville High School outside Detroit — Juan',
    'Atkins, Derrick May, Kevin Saunderson, the <b>Belleville Three</b> — took',
    'the same cheap machines Chicago was dancing to and pointed them at the',
    'future instead of the floor. House is a party. Techno is a thought about',
    'what a city is for after the factories close.</p>',
    '<h2>The records</h2>',
    '<p>Atkins first, as Cybotron with Rick Davis: “Clear” (1983), robotic,',
    'stripped, already the whole idea in one track. Then Atkins alone as',
    '<b>Model 500</b>, “No UFO’s” (1985). Then Derrick May as Rhythim Is Rhythim,',
    'and “Strings of Life” (1987), which is the one that converted the rest of',
    'the world — a piano riff and a rush and no bassline to speak of, on the',
    'Transmat label. Saunderson took it closest to a pop song, as Inner City and',
    'as Reese. Different temperaments, one machine shelf.</p>',
    '<h2>Kraftwerk and Parliament in a lift</h2>',
    '<p>Derrick May had the best line anybody has ever had about a genre. He',
    'described the music as George Clinton and Kraftwerk “stuck in an elevator”',
    'with only a drum machine — the European machine-precision of',
    '<a href="kraftwerk.geocities.ws">Kraftwerk</a> and the black American funk',
    'of Parliament, forced together in a small space in Detroit, with the',
    'machines to referee. That is the formula and it is exactly right. These',
    'were young black men in a collapsing industrial city building',
    'Afrofuturism out of German synth-pop and George Clinton’s spaceship, on',
    'gear that Detroit’s own car plants could have made and did not.</p>',
    '<p>Even the word carries it. “Techno” they took, in part, from Alvin',
    'Toffler, who wrote about the people who would master the new machines as',
    '“techno rebels”. Atkins read that and kept the word. So the name of the',
    'music is a piece of futurology, which is the most Detroit thing about the',
    'whole business.</p>',
    '<h2>The machine question</h2>',
    '<p>This is why the page links out to',
    '<a href="machine-question-ring.geocities.ws">the machine question ring</a>,',
    'where the theory people argue about what it means to hand thinking, or',
    'feeling, or making, over to a machine. Detroit techno is the case study',
    'those arguments do not use and should. It is not a man expressing himself',
    'through a machine and it is not a machine replacing a man. It is three',
    'people who understood that the machine was not neutral, that the drum',
    'machine had a grain and a will and a set of things it wanted to do, and who',
    'made music by arguing with it rather than pretending to master it.</p>',
    '<p>The boxes themselves are the cheap discontinued flops i keep pointing at,',
    'and they have their own page: <a href="roland-808-303.geocities.ws">the',
    'Roland 808 &amp; 303</a>. The lineage is clean. A drum machine nobody wanted',
    '(the 808), a bassline nobody wanted (the 303), a disco edit in Chicago',
    '(<a href="frankie-knuckles-house.geocities.ws">Knuckles</a>), and then this:',
    'the same shelf of failures, in Detroit, imagining a way out of a city that',
    'had stopped. My conclusion, and i hold it hard, is that techno is not dance',
    'music that got clever. It is the sound of people who had every reason to',
    'have no future making one anyway, out of the cheapest machines on the',
    'market, and getting it right.</p>',
    '<hr>',
    '<p><small>corrections on the discography welcome, i have argued the Cybotron',
    'dates with better men than me. best played in the dark. last updated 11 Mar.',
    '</small></p>',
    '<p><small>you are visitor 003344.</small></p>',
    '<p><small>rings: [ <a href="machines-beat-ring.geocities.ws">Machines That Made the Beat</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]</small></p>',
  ]);

export const MUSIC_G = [
  GRANDMASTER_FLASH,
  PLANET_ROCK,
  BOMB_SQUAD,
  ROLAND_808_303,
  FRANKIE_KNUCKLES,
  DETROIT_TECHNO,
];
