// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// THE MUSIC CORNER: ROOMS, LABELS AND BANDS THAT ARE NOT THERE ANY MORE.
//
// The cached web is full of institutions falling over, and this corner is for
// the small ones — the buildings a few thousand people loved and nobody
// listed. A venue is the right subject for an archive about a world that has
// stopped: its entire product was one night at a time, held by the people who
// were in the room, and when it goes there is nothing to consult. What survives
// is a page like this one, kept out of stubbornness, with the paper on it.
//
// AND THE PAPER IS REAL. The two listing sheets reproduced here are scans of
// actual JB's bills — King Street, Dudley for June 1990, and JB's Junction 10
// at Bentley Road North in Walsall for August 1989 — so every band named on
// this page is a band that was actually advertised on a specific night at a
// specific address, down to the biro somebody used to add Spiritualized in the
// margin. Nothing in the list is invented. Where the record is thin the page's
// keeper says so in his own voice rather than my supplying a date.
//
// Real people are described and cited, never ventriloquised: Sam Jukes and
// Geoff Tristram are written about, and neither is given a line to say.
//
// THE LOOK is the book's. Geoff Tristram's cover for the JB's history is
// concentric rings of red, orange, yellow, green, cyan and magenta stacked into
// an arch on a sunburst, so the masthead is that, built out of CSS gradients
// (`bg-jbs` in index.html), and everything below it goes quiet on cream.

import { pic, vid } from './archive-pic.js';

// The two listing sheets go across the column rather than floated small: they
// are documents, and the whole point of them is that the bands are readable.
const sheet = (name, cap) =>
  `<figure class="jb-sheet"><img src="assets/media/web/${name}.jpg" alt="${cap}">` +
  `<figcaption>${cap}</figcaption></figure>`;

export const VENUE_SITES = [
  // ---- JB's, Dudley --------------------------------------------------------
  //
  // Kept by Steve S., who has the sheets and was at the Blur night.
  {
    domain: 'jbs-dudley.org.uk',
    name: "JB'S",
    title: "JB's, Dudley — an appreciation",
    body: [
      '<!--bg:jbs-->',
      '<div class="jb-mast">',
      '<div class="jb-sun"></div>',
      '<div class="jb-arch"><span>JB’S</span></div>',
      '</div>',
      '<p class="jb-sub">King Street &middot; Castle Hill &middot; and a football club’s',
      'social room before either of them</p>',
      '<hr>',

      '<h2>What it was</h2>',
      '<p>A room in Dudley where bands played. That is the whole of it and it is',
      'nowhere near enough, so: it started in 1969, run by Sam Jukes, who had been',
      'a speedway rider, with two friends, as a disco night in the social club at',
      'a ground Dudley Town had played at. In the early seventies it moved to a',
      'room behind a menswear shop on King Street that held about two hundred and',
      'fifty. In 1994 it moved again, to Castle Hill, where it held a thousand.</p>',
      '<p>Same man, same name, three buildings, forty-two years. People used to',
      'say that made it the longest-running live music venue in the country. I',
      'have never seen anybody disprove it and I have never seen anybody produce',
      'the paperwork either, which is about right for Dudley.</p>',
      pic('jbs-front-door', 'The King Street door. NO ADMISSION AFTER 10 P.M., stencilled on the wall inside, which was enforced by nobody I ever met.', 'r'),

      '<h2>The sheets</h2>',
      '<p>I have two of the monthly bills. They were typed on a machine with a',
      'tired ribbon, run off, and left in a pile by the door for you to take one',
      'and put it in your pocket. Mine went on a wall for years, which is why they',
      'are creased like that.</p>',
      '<p>The first is <b>JB’s, King Street, Dudley</b> for June 1990, and it is',
      'the one I would save from a fire.</p>',
      sheet('jbs-listings-1990', 'JB’s, King Street, Dudley — June 1990 into August. Note the biro: somebody at the club has written in Balaam &amp; The Angel and, on the 25th, SPIRUALISED (EX SPACEMEN 3).'),
      '<p>Read down it. Trash Can Sinatras on the Friday. The Senseless Things',
      'the Friday after. The Katydids. Trevor Burton, who had been in The Move.',
      'Stan Webb’s Chicken Shack, twice in six weeks, because Stan Webb played',
      'JB’s the way other people go to work. Bridgewell Taxis. Teenage Fan Club,',
      'spelled as three words by whoever was at the typewriter.</p>',
      '<p>And on Friday 27th July 1990, in the same plain capitals as everything',
      'else on the sheet, with nothing round it: <b>BLUR</b>.</p>',
      '<p>I was at that one. I was at most of them — every other Friday for about',
      'four years, which is a sentence I can only defend by pointing at the paper.',
      'They were four lads on a stage the size of a kitchen table and the room was',
      'not full. You could not have told me then. Nobody could have.</p>',
      '<p>Two entries down, Saturday the 28th, somebody has written in <i>Cheap ’n’',
      'Nasty (featuring Nasty Suicide — Hanoi Rocks)</i>, which is exactly the',
      'sort of billing that got you thirty extra people through the door in 1990.',
      'The P.A. was Stage Audio Services on 0384 263629, whose name is at the top',
      'of the sheet because they printed it.</p>',

      '<h2>Junction 10</h2>',
      '<p>The other sheet is a year earlier and it is not Dudley: <b>JB’s',
      'Junction 10, Bentley Road North, Walsall</b>, August 1989. Same name, same',
      'kind of month, and the back of my 1990 Dudley sheet has the Walsall address',
      'showing through it, so the same office was running both bills off. I am not',
      'going to make a bigger claim than that because I do not know.</p>',
      sheet('jbs-listings-1989', 'JB’s Junction 10, Bentley Road North, Walsall — August 1989. Monday nights: under-18s disco, 7 till 10.'),
      '<p>Gaye Bykers On Acid on the 5th. The Fuzztones on the 26th. Horse from',
      'London supported by The Almighty. Steve Gibbons. Climax Blues Band. Cloven',
      'Hoof, who were from Wolverhampton and had no business being that heavy.',
      '<i>FROM THE U.S.A. FIRE HOSE</i> on Saturday the 9th of September, typed',
      'in capitals like a boast, which it was — that is Mike Watt’s fIREHOSE, in',
      'Walsall, for the price of a Rock Disco and a bit.</p>',
      '<p>Rock Disco was £1.50. It says so on the sheet.</p>',

      '<h2>What it was like</h2>',
      '<p>Hot. That is the first thing and everyone says it first. It was hot in',
      'there in a way that had nothing to do with the weather outside — four',
      'hundred people in a low room with no air in it, and by the third song the',
      'walls were running. You came out into King Street steaming in the cold and',
      'stood there letting it come off you.</p>',
      '<p>Loud. Properly loud, the kind you take home with you and still have the',
      'next morning, so that the kettle sounds wrong and you have to ask people to',
      'say things twice. Nobody wore anything in their ears. It did not occur to',
      'us that you could.</p>',
      '<p>And the carpet. You have to talk about the carpet. It was patterned',
      'once, and by the end of the eighties it was a single colour and it held on',
      'to your shoes — you could feel it letting go of each foot as you crossed to',
      'the bar, and you got used to walking on it the way you get used to a boat.',
      'Nobody ever cleaned it and nobody expected anyone to.</p>',
      '<p>The bar down one side, always three deep, and chips. Chips at JB’s were',
      'an institution in their own right: hot, greasy, in a polystyrene tray,',
      'eaten standing up with your back against a pillar between bands. I have',
      'eaten in a number of countries since and I have not improved on it.</p>',
      '<p>And the car park round the back, which is where you went when the room',
      'got too much for you — out through the fire door into the cold with a',
      'couple of dozen other people leaning on cars, ears ringing, everybody',
      'shouting because nobody could hear. Ten minutes of that and you went back',
      'in. Half the conversations I remember from those years happened out there',
      'rather than inside.</p>',
      '<p>You stood close enough to the band to be hit by things, and that was the',
      'arrangement: a room this size does not put on a show, it puts you in with',
      'four people who are trying something. Half the time it did not come off.',
      'You were there for the other half.</p>',

      '<h2>The indie years</h2>',
      '<p>What the sheets catch is the tail end of the eighties turning into the',
      'indie thing, and JB’s took the lot. Read the June 1990 bill again and it is',
      'a fanzine index: Trash Can Sinatras, The Senseless Things, The Katydids,',
      'Bridgewell Taxis, The Blessing, 5.30, Poets Town, Teenage Fan Club,',
      'Spiritualized in biro because they had only just stopped being Spacemen 3,',
      'and Blur on a Friday for whatever a Friday cost.</p>',
      '<p>None of that was a booking policy. It was one man taking whoever rang',
      'up, on a stage in Dudley, four and five nights a week, for decades. The',
      'blues bands and the metal bands are on the same sheet as the indie ones —',
      'Stan Webb one Sunday, Cloven Hoof the next Saturday — and nobody at the',
      'club appeared to think this was a contradiction.</p>',
      '<p>Pop Will Eat Itself, The Wonder Stuff and Ned’s Atomic Dustbin have all',
      'named the place as an influence, which is a polite word for where they',
      'learned to do it — and Ned’s in particular were around JB’s constantly.',
      'Not just playing it: in it, at the bar, at other people’s gigs, the way you',
      'are around a place when it is fifteen minutes from your house and there is',
      'nowhere else. Half of Stourbridge was in that room on a Friday whether or',
      'not their name was on the sheet.</p>',
      '<p>In 2000 the club put a two-day festival up the road at Dudley Castle',
      'with Terrorvision, Ned’s and Miles Hunt on it.</p>',
      '<p>The bands you saw at nineteen and forgot were, some of them, the same',
      'bands you would later pay to see from three hundred feet away. Nobody tells',
      'you at the time which nights those are.</p>',

      '<h2>How it ended</h2>',
      pic('jbs-castle-hill', 'Castle Hill, near the end. The sign is still lit. Above it the wall says MARTIAL ARTS CENTRE, with an arrow, and GYM, with another one.'),
      '<p>Administration in 2010. Closed in January 2011. Sold in late 2012, and',
      'the building was turned into a conference and banqueting centre. The room',
      'is still standing and there is nothing in it.</p>',
      '<p>I have been back. It is clean, it is carpeted, there are chairs out in',
      'rows, and it is a perfectly decent place to hold a wedding. I could not',
      'tell you where the stage was.</p>',

      '<h2>The book</h2>',
      '<p>Geoff Tristram did the one that matters: <i>JB’s — The Story of',
      'Dudley’s Legendary Live Music Venue, in words and pictures</i>. He did the',
      'cover as well, which is why the top of this page looks the way it does; I',
      'have tried to build his rings out of what a browser will give me and it is',
      'not as good as his. Buy the book instead of reading me.</p>',

      '<h2>Your bit</h2>',
      '<p>People send me these. I put them up as they arrive and I do not tidy',
      'them.</p>',
      '<div class="jb-book">',
      '<p><b>Ade, Netherton</b> — Saw a band there about ’91 whose name I have',
      'genuinely lost. Four of them, one played the whole set facing the drummer.',
      'Best forty minutes of my life. If that was you, write in.</p>',
      '<p><b>C. Whitehouse</b> — My dad worked the door at King Street. He said the',
      'trick was never to look like you were counting.</p>',
      '<p><b>no name given</b> — I met my wife in the queue. We were both there for',
      'someone else. Twenty-six years next March.</p>',
      '<p><b>Baz</b> — Went to a wedding in it. Sat down, got up again, went and',
      'stood in the corner where I used to stand. My mate came and stood next to',
      'me and neither of us said anything for about a minute.</p>',
      '<p><b>D.</b> — Ned’s Atomic Dustbin shirt, the black one with the word on',
      'it. I wore it to the club more times than was reasonable and I would have',
      'been wearing it that July as well. There is a photograph of me in it on',
      'somebody’s first-year page, and that is where it can stay.</p>',
      '</div>',
      '<hr>',
      '<p><small>Corrections welcome and acted on. I would rather this page were',
      'short and right than long. — <b>Steve S.</b></small></p>',
      '<p><small>elsewhere on this site: <a href="loca-tapes.org.uk">loca-tapes.org.uk</a> &middot;',
      '<a href="calvadosbeamtrio.fanpages.org.uk">calvadosbeamtrio.fanpages.org.uk</a> &middot;',
      '<a href="peelacres.fanpages.org.uk">peelacres.fanpages.org.uk</a>, who is the reason any of the rest of it',
      'was audible. And <a href="dmb.demon.co.uk">dmb.demon.co.uk</a>, who has his own page about a thing',
      'that stopped existing.</small></p>',
    ],
  },
  // ---- meme, and Loca -------------------------------------------------------
  //
  // A page about one gig and the label behind it. Loca's facts are documented
  // and stated plainly; the gig is one man's photographs and is described as
  // such, including the part where the photographs prove his own date wrong.
  {
    domain: 'loca-tapes.org.uk',
    name: 'MEME',
    title: 'meme, live, in a red room in Farringdon',
    body: [
      '<!--bg:loca-->',
      '<h1>meme &middot; live &middot; Farringdon</h1>',
      '<p><small>two photographs and what I can remember round them</small></p>',
      '<hr>',
      '<p>A basement bar in Farringdon, a room painted red with a mirrorball',
      'somewhere out of shot, forty or fifty people, and one man behind a plank',
      'on trestles with everything he owned plugged into everything else.</p>',
      pic('meme-farringdon', 'meme, Farringdon. A Roland MC-505, a small mixer, and a card with MEME written on it in biro taped to the front so the room knew who it was.'),
      '<p>That card is the part I always come back to. No banner, no backdrop,',
      'nobody announcing anybody. A postcard with the name on it in felt tip,',
      'stuck to the gear with gaffer, at eye level for the front row and nobody',
      'else. It is the whole economics of that scene in one object.</p>',
      '<h2>A correction, to myself</h2>',
      '<p>I had these filed as mid-nineties for about twenty years and told',
      'people so. The machine on the table is a Roland MC-505, which did not',
      'exist until 1998. So I am wrong and the photographs are right, and this is',
      'the back end of the decade rather than the middle of it. I have left the',
      'rest of the page as I wrote it and I am not going to quietly fix my',
      'memory to match.</p>',
      pic('meme-mc505', 'The same night, closer, and the film has gone. Both frames came out this red. The 505 is the only thing in focus and it is fair enough that it should be.', 'r'),
      '<h2>What it sounded like</h2>',
      '<p>Sequenced, patient, quite a lot of low end for a room that size, and',
      'built in front of you: he started with nearly nothing and put a part in',
      'every eight bars until the thing was standing up, then took it apart the',
      'same way. You could watch him decide. Whether or not you liked the record',
      'it was a genuinely different thing to watch than a band, because the',
      'construction was the performance.</p>',
      '<p>Nobody danced for the first fifteen minutes and everybody did after.</p>',
      '<h2>The label</h2>',
      '<p><b>Loca Records</b> was founded in 1999 by David M. Berry and Marcus',
      'McCallion, in Old Street, and ran out of Brighton: electronica and post',
      'rock, out on vinyl, CD and cassette, and every release under a copyleft',
      'licence.</p>',
      '<p>That last part was not a gesture. The first two releases in 1999 —',
      'Kinematic, and the Mandibles EP — went out under the <b>GNU General Public',
      'License</b>, the same licence as the operating system, applied to music.',
      'Later releases moved to the EFF’s Open Audio License and then to Creative',
      'Commons Attribution-ShareAlike. Copy it, re-release it, cut it up, sell the',
      'result: the one condition is that what you make carries the same licence',
      'forward.</p>',
      '<p>They said at the time that they were following the GNU/Linux model and',
      'trying to change how a record company does business. Whether that worked',
      'is a longer argument than this page. What is not arguable is the date: a',
      'record label putting music out under the GPL in 1999, which is four years',
      'before Creative Commons had a licence to offer them.</p>',
      '<h2>The other label</h2>',
      '<p>meme did not only come out on Loca. There was <b>Mirrordisc</b>',
      'Productions as well — Brighton, a PO box, downbeat electronica and video',
      'art — and their site is still in the cache at',
      '<a href="homepage.mac.com/mirrordisc">homepage.mac.com/mirrordisc</a>,',
      'frameset and all. Two releases on it: an LP with meme and tome on it,',
      'limited to five hundred, November 2001, and a DVD the September after.',
      'You paid by cheque, to a box number.</p>',
      '<p>Mirrordisc was <b>Joe Plant</b>\u2019s, and he built the site as well;',
      'the credit at the foot of every page is his.</p>',
      '<p>Three of its five pages were never written. ARTISTS, ABOUT and',
      'CONTACTS were up there with nothing on them but that footer.</p>',
      '<p><small>Later: two of the three have appeared. He has gone back into the',
      'directory and written <a href="homepage.mac.com/mirrordisc/about">ABOUT</a>',
      'and <a href="homepage.mac.com/mirrordisc/artists">ARTISTS</a>, years after',
      'the rest of it, and on the second one he says the thing the whole site had',
      'been arranged not to say: tome is Joe. The label is the band. Which also',
      'answers, sideways, the question I ask further down this page about',
      'williams, because they are all in the same pub —',
      '<a href="theheartandhand.geocities.ws">the Heart &amp; Hand</a>, and there',
      'is a page for that too now.</small></p>',

      '<h2>Reading md lp 000</h2>',
      '<p>The site gives you the record. The label gives you the record and who',
      'made it, and it is worth a minute.</p>',
      '<p>Look at the sides first. The label is on side two, so it calls side one',
      '<i>the other side</i> and itself <i>this side</i>. That is the correct',
      'solution to a problem nobody else solves and everybody has.</p>',
      '<p>Then the credits. Three tracks are <b>tome</b> on his own — sodium,',
      'imperfection is the soul, frontier. One is <b>meme</b> on his own, which',
      'is aufheben. The rest are both of them with somebody else in the room:',
      'the athlete, williams, camilleri, burgan, banks.</p>',
      '<p>A listing elsewhere has Steve Burgan on lead vocals and lyrics for',
      '<i>invisible</i>; the label credits burgan on <i>whatever you say</i>.',
      'Both can be true and I cannot settle it from here.</p>',
      '<p>And <b>williams</b> on <i>neon</i>. If that is the Richard Williams who',
      'played guitar in Ward and in the Calvados Beam Trio then the same man is',
      'on a Brighton IDM record and in a pub back room in Kings Heath, and three',
      'of my pages are one page. Somebody tell me either way.</p>',
      '<p>Last thing. There was a folder on the disc called <i>mirrordisc mp3’s</i>',
      'with eight .m3u files in it — one line each, a downloads.mp3.com address',
      'with a long key in it, all long dead. COLOUR, FRONTIER, EPIPHANY, SODIUM,',
      'NEON, INVISIBLE, WHATEVER_YOU_SAY, and one truncated to',
      'IMPERFECTION_IS_THE_SO because that is what a Mac did to a filename in',
      '2002.</p>',
      '<p>Eight files. Nine tracks. The one they never put up is <b>aufheben</b>:',
      'the shortest thing on the record, the only one meme made alone, and the',
      'only title that is not in English.</p>',

      '<h2>Ward</h2>',
      pic('ward-wall', 'Ward. Two of them against a brick wall in the cold, hands in pockets, which is the entire visual language of a British band press shot in about 2001.', 'r'),
      '<p>The other reason this page exists. <b>Ward</b> were on Loca, and their',
      'guitarist Richard Williams was also the guitarist in Calvados Beam Trio,',
      'which is how a Birmingham pub back room and a copyleft label in Old Street',
      'turn out to be the same address book.</p>',
      '<pre class="jb-list">',
      '  Sesquipedalian Origins / Calcium Taut Verdun',
      '                          Static Caravan &middot; VAN 36',
      '                                             2001  7" at 33⅓, blue, ltd',
      '                                             2001  7" white-label promo',
      '  It’s Not Necessarily Your Height It Could Be Your Feet',
      '                          Loca &middot; LOCA004     2002  CD',
      '  De Fernius / Armonica Or Something',
      '                          Static Caravan &middot; VAN 64',
      '                                             2004  lathe-cut 7", ltd',
      '  It Might Be Useful For Us To Know',
      '                          Loca &middot; LOCA009     2005  CD',
      '</pre>',
      '<p>A lathe cut on Static Caravan and two albums on a label that licensed',
      'everything it touched under copyleft. Those titles are doing the same',
      'thing Calvados’s two were: a whole sentence where a name should be.</p>',
      pic('ward-van36', 'Static Caravan VAN 36. Blue line drawings on a deep red ground — a chandelier, a monkey on a wire, a camera, a diamond, a thumb — and the titles set small in italic at the foot with a large 1 beside them.'),
      '<p>Collector’s note on VAN 36, because somebody will write in about it.',
      'The blue seven and the white-label promo are the same record with the same',
      'catalogue number, and the title is spelled two different ways across the',
      'listings for them: <i>Sesquipedalian</i> on one and <i>Sesquipadelian</i>',
      'on the other. The sleeve reads <b>Sesquipedalian</b>, which is also a real',
      'word and means given to using long ones. A band with these song titles was',
      'not going to misspell that. The other listing is a typing error and I am',
      'calling it.</p>',

      '<h2>The Peel thing</h2>',
      pic('ward-van36-label', 'The label. Brown paper on blue vinyl, Static Caravan’s hut logo top right, and in the largest type on the whole record: 33 rpm.', 'r'),
      '<p>John Peel played it. Twice that I know of — <b>5 February 2002</b> and',
      '<b>7 March 2002</b> — and on the second one he put it on at the wrong',
      'speed.</p>',
      '<p>Look at the label. It is a seven-inch single, so the needle goes down at',
      '45 without anybody thinking about it, and this one runs at 33⅓. The record',
      'knows that is going to happen: <i>33 rpm</i> is set in the biggest type on',
      'the label, in the middle, under the titles, where nothing else is. And it',
      'went out at 45 on national radio anyway.</p>',
      '<p>I have never been able to decide whether that is the most Peel thing',
      'that ever happened or the most Static Caravan one.</p>',

      '<h2>What the back of it says</h2>',
      sheet('ward-van36-back', 'The reverse of VAN 36. Every credit on the record, set in a stack of pale panels on the same deep red.'),
      '<pre class="jb-list">',
      '  Track 1  Sesquipedalian Origins    3:42   (c) 2000 Ward',
      '  Track 2  Calcium Taut Verdun       6:20   (c) 1999 Ward',
      '',
      '  Both tracks from the forthcoming album',
      '  “It’s not necessarily your height it could be your feet”',
      '',
      '  Vinyl by Static Caravan',
      '  All tracks written and produced by Ward',
      '  All tracks recorded at 570A Old Street, London, UK',
      '  Mastering and post-production in Brighton, UK',
      '',
      '  ward [ need to be David Meme &amp; Richard Williams ]',
      '',
      '  Thanks to Geoff at Static Caravan',
      '  Marcus &amp; Raquel for artwork',
      '',
      '  ALL 33⅓ LISTEN',
      '</pre>',
      '<p>Two things worth pulling out of that. The A-side is dated 2000 and the',
      'B-side 1999, so the record came out in 2001 carrying a track that had been',
      'sitting around for two years; and the album it trails, <i>It’s not',
      'necessarily your height it could be your feet</i>, did arrive — on Loca in',
      '2002, LOCA004, which is the row above this one in the list.</p>',
      '<p>Recorded at 570A Old Street and mastered in Brighton, which is the two',
      'ends of Loca written on somebody else’s sleeve. The artwork thanks go to',
      'Marcus, who is the Marcus in the label’s own founding line.</p>',
      '<p>And at the bottom, instead of a catalogue number or a barcode:',
      '<b>ALL 33⅓ LISTEN</b>. They knew.</p>',
      '<hr>',
      '<p><small>If you were at this one, or you know the room, write in. I have',
      'the negatives. — <b>Steve S.</b></small></p>',
      '<p><small>elsewhere: <a href="jbs-dudley.org.uk">jbs-dudley.org.uk</a>, which is the other room I',
      'keep a page about; <a href="calvadosbeamtrio.fanpages.org.uk">calvadosbeamtrio.fanpages.org.uk</a>, which is the',
      'other end of the same address book; and <a href="peelacres.fanpages.org.uk">peelacres.fanpages.org.uk</a>,',
      'for what happened to VAN 36 on the radio.</small></p>',
    ],
  },

  // ---- Calvados Beam Trio ---------------------------------------------------
  //
  // The most on-theme page in the corpus: a band with a documented gig history
  // and almost nothing else on the record. Everything asserted is checkable —
  // the Flapper, the Capsule bills, the company they kept. Everything else the
  // keeper marks as memory or as a gap, including the room in his own photo.
  {
    domain: 'calvadosbeamtrio.fanpages.org.uk',
    name: 'CBT',
    title: 'Calvados Beam Trio — a fan page',
    body: [
      '<!--bg:loca-->',
      '<h1>Calvados Beam Trio</h1>',
      '<p><small>Birmingham &middot; three of them &middot; almost no trace</small></p>',
      '<hr>',
      '<p>Guitar, bass, drums, no singing. Instrumental, angular, played quietly',
      'and then not quietly, with the sort of arrangements that sound like an',
      'argument being conducted very politely. If you know what people mean by',
      'math rock, that. If you do not, imagine three people who have agreed in',
      'advance to change at the same odd moment and are all concentrating.</p>',
      pic('calvados-beam-trio', 'The Flapper &amp; Firkin, Birmingham, 11 November 1998. Fireplace, mirror over it, yellow walls, floorboards, one speaker on a stand. Bass in the foreground, drums in the fireplace, guitar looking down at his pedal.'),
      '<p>That is my photograph and I can now tell you exactly where it is: the',
      '<b>Flapper &amp; Firkin</b>, Birmingham, the 11th of November 1998. I had',
      'it down as the Hare and Hounds for years on the strength of the fireplace',
      'and I was wrong. It is the Flapper, on the canal, and somebody recorded',
      'that night, so there is a tape of exactly what is happening in this',
      'frame.</p>',
      '<h2>The record</h2>',
      '<p>There is one, and for a long time I thought there was nothing.</p>',
      pic('calvados-bearos-014', 'Bearos 014. Clear vinyl in a clear plastic sleeve with a sticker on it, and the sticker is a block of text printed so faintly you have to hold it up to a window.', 'r'),
      '<pre class="jb-list">',
      '  Calvados Beam Trio — Calvados Beam Trio',
      '  Bearos Records &middot; Bearos 014 &middot; UK',
      '  7" single, limited edition of 400, clear vinyl',
      '  released 29 October 1999',
      '',
      '  A  Thank You For Your Shoe Time And Faster We All Go',
      '  B  Smiling Will Overtake Under Expedient Fire',
      '',
      '  recorded by Phil Rogers of Place Position,',
      '  in a rehearsal room at Rich Bitch Studios, Birmingham',
      '</pre>',
      '<p>Four hundred copies. Recorded in a rehearsal room rather than a studio,',
      'by somebody out of another band, and put out by Bearos, who were doing',
      'that for a lot of people around there at the time. Those two titles are',
      'the only writing of theirs I have ever seen and they tell you as much',
      'about the band as the record does.</p>',

      '<h2>What I can actually stand behind</h2>',
      '<p>They played the <b>Flapper &amp; Firkin</b> in Birmingham on the 11th of',
      'November 1998, and somebody recorded it. They were on Capsule bills at the',
      'Hare and Hounds — one of them with <b>The Fucking Champs</b> and',
      '<b>French Toast</b>. And they opened for <b>Don Caballero</b>, with',
      'Capricorns.</p>',
      '<p>That last one tells you what they were for. Nobody puts a local band on',
      'in front of Don Caballero unless the local band can play in that time',
      'signature and not embarrass anyone.</p>',
      pic('richard-williams-live', 'Richard Williams, playing. Black guitar, white shirt, a wall of somebody else’s gig posters behind him.', 'r'),
      '<p>The guitarist was <b>Richard Williams</b>, who was also in <b>Ward</b>,',
      'on Loca. Which is the join in this whole corner of my site: the man playing',
      'in a pub back room in Kings Heath and the label in Old Street putting',
      'records out under the GPL are the same few dozen people, and it took me',
      'years to notice.</p>',
      '<p>When they were down on the south coast they drank in',
      '<a href="theheartandhand.geocities.ws">the Heart &amp; Hand</a> in Brighton',
      'with the Loca lot, and somebody has put a page up about the pub. Read the',
      'bit about the jukebox.</p>',

      '<h2>The names, at last</h2>',
      '<p>I had this page up for years saying I could not name them. Then',
      'somebody pointed me at <b>Thirteen</b> — an album on Union Mill, six',
      'tracks: Exorcisms, Anne Carlisle, White Sands, To Achieve This End, Mimas,',
      'Bills Radio — and the credits on it are:</p>',
      '<pre class="jb-list">',
      '  Martin Grennall     bass',
      '  Stephen Taylor      drums',
      '  Richard Williams    guitar',
      '</pre>',
      pic('thirteen-council-house', 'Thirteen, on the steps in Chamberlain Square with the Council House behind them. Screened to bits, because this is a scan of a printed press sheet and not of a photograph.'),
      '<p>Guitar, bass, drums, and Richard on the guitar in both. Look at my',
      'photograph again: bass in the foreground, drums in the fireplace, guitar',
      'on the right looking at his pedal. Three of them, and one of them is',
      'certainly Richard.</p>',
      '<p>I am as good as sure that is Martin and Stephen either side of him and',
      'I want to be clear that being as good as sure is not the same as knowing.',
      'The credits I have are Thirteen’s. Nobody has ever handed me a Calvados',
      'sleeve with three names on it. If one of you has one, that is the thing',
      'this page has been waiting for since I put it up.</p>',

      '<hr>',
      '<p><small>Corrections, line-ups, dates, tapes: send them and I will put',
      'them up. — <b>Steve S.</b></small></p>',
      '<p><small>elsewhere: <a href="jbs-dudley.org.uk">jbs-dudley.org.uk</a> &middot;',
      '<a href="loca-tapes.org.uk">loca-tapes.org.uk</a> &middot; <a href="peelacres.fanpages.org.uk">peelacres.fanpages.org.uk</a>, who',
      'played a record by the guitarist\u2019s other band and got the speed',
      'wrong.</small></p>',
    ],
  },
  // ---- John Peel ------------------------------------------------------------
  //
  // The one page in this corner about a person rather than a room or a band,
  // and it earns its place because he is why any of the rest was audible. Every
  // fact is documented: the dates, the OBE, Radio 1 from the first day to the
  // last, the wrong-speed reputation (which the tribute compilation's own title
  // confirms), the Sessions, the Festive Fifty. Where the keeper is going on
  // memory he says so.
  //
  // He is written about and never ventriloquised. Not one line of dialogue is
  // put in his mouth, including the famous ones.
  {
    domain: 'peelacres.fanpages.org.uk',
    name: 'PEEL',
    title: 'John Peel — a listener’s page',
    body: [
      '<!--bg:parch-->',
      '<h1>John Peel</h1>',
      '<p><small>30 August 1939 – 25 October 2004 &middot; kept by somebody who',
      'was up at that hour for about fifteen years</small></p>',
      '<hr>',

      '<h2>The job he did</h2>',
      '<p>He was on Radio 1 from the day it started in 1967 and he was still on',
      'it when he died, which makes him the only one of the original intake who',
      'never got moved, promoted or quietly dropped. Thirty-seven years of the',
      'same job on the same network, done at the wrong end of the evening, and',
      'the job was: play the records nobody else would play.</p>',
      '<p>Not as a policy. As a habit, four nights a week, for longer than most',
      'of the people listening had been alive. If you sent him a tape he might',
      'play it. That sentence is the whole of British music between about 1970',
      'and about 2004 and I am not sure people who were not there believe it.</p>',

      '<h2>The Sessions</h2>',
      '<p>A band nobody had heard of got invited to Maida Vale, recorded four',
      'songs in a day, and went out on national radio a fortnight later. No deal,',
      'no label needed, no A&amp;R man’s permission. For a great many bands the',
      'Peel Session is the best recording of them that exists, because it was the',
      'only time anybody put them in a proper room with a proper engineer.</p>',
      '<p>People built careers on it. People got one and nothing else ever',
      'happened to them, and that session is still there, and it is still the',
      'thing they are on the internet for.</p>',

      '<h2>The Festive Fifty</h2>',
      '<p>His listeners voted, every year, and he counted it down between',
      'Christmas and New Year. It is the only chart I have ever taken seriously,',
      'on the grounds that it was the only one where nobody stood to make any',
      'money out of the result.</p>',

      '<h2>The wrong speed</h2>',
      '<p>He played records at the wrong speed. Frequently. On air. It is one of',
      'the two or three things everybody knows about him, and after he died one',
      'of the tribute compilations was actually called <i>Right Time, Wrong',
      'Speed</i>, so this is not a thing his listeners made up.</p>',
      '<p>By all accounts it genuinely annoyed him — he was embarrassed by it and',
      'said so, and it kept happening.</p>',
      '<p>I want to argue that it is the most important thing about him and not',
      'an endearing flaw. A man playing a seven-inch at 45 when it is cut at 33 is',
      'a man who has not heard the record before. He is finding out at the same',
      'time you are. Every other broadcaster in the country was playing you things',
      'they had already decided about; he was putting the needle down on something',
      'that had come in the post and taking his chances in public.</p>',
      '<p>Somebody I know had a single played on his show twice in 2002 and got',
      'the wrong speed on the second one. It is a seven-inch cut at 33⅓, which is',
      'a thing a very small label does when it wants six minutes a side, and the',
      'label says <i>33 rpm</i> in the largest type on the record. That is on my',
      '<a href="loca-tapes.org.uk">loca-tapes.org.uk</a> page with a photograph of the label.</p>',
      '<p>They were pleased. Everybody was pleased. Being played wrong by Peel was',
      'a better story than being played right by anybody else, and the tape of it',
      'went round the four people it mattered to for years.</p>',

      '<h2>Peel Acres</h2>',
      '<p>He broadcast from home in Suffolk a good deal in the later years, from a',
      'room in a house full of records, with his family audible in the background',
      'and the dog going off occasionally. Nobody else was allowed to sound like',
      'that. He had earned it by never once having pretended to be anything.</p>',
      '<p>The record collection is the other monument. Tens of thousands of them,',
      'catalogued by a man who knew where everything was, and after his death it',
      'was properly archived rather than sold off, which is the correct outcome',
      'and by no means the likely one.</p>',

      '<h2>The end of it</h2>',
      '<p>He died of a heart attack in October 2004, on holiday in Peru, at',
      'sixty-five. I remember exactly where I was standing and so does everybody',
      'else I have ever asked, which is not a thing that happens about disc',
      'jockeys.</p>',
      '<p>What went with him is a route. Before: a band in a rehearsal room in',
      'Birmingham makes four hundred singles and one man in London might put one',
      'on the radio at midnight, and if he does, everybody in the country who',
      'cares about that sort of thing hears it on the same night. There is no',
      'version of that arrangement left. There is more music reaching more people',
      'than ever and there is no longer one midnight that everybody is at.</p>',
      '<hr>',
      '<p><small>Corrections welcome, as ever. — <b>Steve S.</b></small></p>',
      '<p><small>elsewhere: <a href="jbs-dudley.org.uk">jbs-dudley.org.uk</a> &middot;',
      '<a href="loca-tapes.org.uk">loca-tapes.org.uk</a> &middot; <a href="calvadosbeamtrio.fanpages.org.uk">calvadosbeamtrio.fanpages.org.uk</a>',
      '&middot; and <a href="blackcountryboard.co.uk">blackcountryboard.co.uk</a>, where half of this started as',
      'an argument in a thread.</small></p>',
    ],
  },
  // ---- MIRRORDISC -----------------------------------------------------------
  //
  // NOT A FAN PAGE. This one is a primary document: the label's own site, off a
  // disc, rebuilt out of the files. Everything on it comes from the HTML —
  // the wording, the catalogue numbers, the prices, the PO box, the dead links,
  // the credit at the foot. The three pages that were never written are simply
  // not here, because there was nothing on them: the cache serves what was
  // served. A cached page does not annotate itself, so there are no editorial
  // brackets on it saying which of its links stopped resolving — the links are
  // reproduced as they were typed and the reader can try them.
  //
  // The frameset is flattened. index.html was 100 pixels of topbar over a body
  // frame, which a cache that serves one document at a time cannot reproduce
  // and should not pretend to; the nav bar is drawn as the row of words it was.
  //
  // AND NOBODY IS STANDING NEXT TO IT TALKING. Every reading of the record —
  // the sides, the credits, the eight playlists for nine tracks — lives on
  // Steve's page at loca-tapes.org.uk, where a person is entitled to have
  // opinions. What is here is what was served.
  {
    domain: 'homepage.mac.com/mirrordisc',
    name: 'MIRRORDISC',
    title: 'MIRRORDISC',
    body: [
      '<!--bg:mdisc-->',
      '<div class="md-bar">',
      '<img class="md-logo" src="assets/media/web/mirrordisc-logo.jpg" alt="Mirrordisc logo">',
      '<span class="md-nav">HOME &nbsp; MUSIC &nbsp; '
      + '<a href="homepage.mac.com/mirrordisc/artists">ARTISTS</a> &nbsp; '
      + '<a href="homepage.mac.com/mirrordisc/about">ABOUT</a> &nbsp; LINKS</span>',
      '</div>',
      '<hr>',
      '<p>Mirrordisc Productions is a small Brighton based independent record label</p>',
      '<p>currently specialising in downbeat electronica and video art.</p>',
      '<p><small>Run by <b>Joe Plant</b>.</small></p>',

      '<h2>MUSIC</h2>',
      pic('mirrordisc-cover', 'md lp 000. Letters coming up out of the black and going back down into it.', 'r'),
      '<pre class="jb-list">',
      '  cat no      artist        format              released   price',
      '  md lp 000   meme &amp; tome   vinyl LP,           Nov 2001   £10.99',
      '                            limited to 500',
      '  mddv 001    meme &amp; tome   DVD 5               Sep 2002   £9.99',
      '</pre>',
      '<p>Cheques / PO’s made payable to:</p>',
      '<p>Mirrordisc Productions<br>PO BOX 7<br>Brighton East Sussex<br>BN2 4WD<br>UK</p>',

      '<h2>md lp 000 — <i>Invisible</i></h2>',
      '<p><small>Meme &amp; Tome. Vinyl LP. 2001.</small></p>',
      '<pre class="jb-list">',
      '  side one [other side]',
      '  1. invisible                   meme / tome / the athlete   3:43',
      '  2. neon                        meme / tome / williams      4:10',
      '  3. sodium                      tome                        4:50',
      '  4. imperfection is the soul    tome                        4:58',
      '',
      '  side two [this side]',
      '  5. aufheben                    meme                        3:21',
      '  6. colour                      meme / tome / camilleri     4:30',
      '  7. whatever you say            meme / tome / burgan/banks  4:10',
      '  8. frontier                    tome                        4:56',
      '  9. epiphany                    meme / tome                 4:52',
      '',
      '  total playing time             39:30',
      '</pre>',

      '<h2>LINKS</h2>',
      '<p>To view the promo video to the forthcoming Invisible DVD release',
      '(mddv 001) please click on the link below and go to the animation',
      'section.</p>',
      '<p>www.mrkirkland.com</p>',
      '<p>You can also purchase a CD of Invisible from',
      '<a href="mp3.com">www.mp3.com/TOME</a>.</p>',
      '<p>Several tracks on this release plus many more Meme tracks can be found',
      'at www.locarecords.com</p>',
      '<p>Read a review of Invisible at www.overloadmedia.co.uk</p>',

      '<hr>',
      '<p class="md-foot"><i>Site designed by Joseph</i></p>',
      '<p class="md-foot"><small>Joe Plant, Mirrordisc Productions, Brighton.</small></p>',
      '<p class="md-foot"><small>mirrordisc@mac.com &middot; Made on a Mac</small></p>',
    ],
  },
  // ---- the ABOUT page, at last ----------------------------------------------
  //
  // The nav on the label's site had five items and three of the pages were
  // never written. This is the one at the ABOUT address, written years after
  // the rest of the site and left at the same host, which is what actually
  // happens to a page like that: somebody comes back to a directory they still
  // have the password for and finishes one thing.
  //
  // It is Joe's own, so the register is his and not the keeper's: first person,
  // no analysis, and no idea that anybody would ever read it.
  {
    domain: 'homepage.mac.com/mirrordisc/about',
    name: 'ABOUT',
    title: 'MIRRORDISC — about',
    body: [
      '<!--bg:mdisc-->',
      '<div class="md-bar">',
      '<img class="md-logo" src="assets/media/web/mirrordisc-logo.jpg" alt="Mirrordisc logo">',
      '<span class="md-nav"><a href="homepage.mac.com/mirrordisc">HOME</a> &nbsp; '
      + 'MUSIC &nbsp; <a href="homepage.mac.com/mirrordisc/artists">ARTISTS</a>'
      + ' &nbsp; ABOUT &nbsp; LINKS</span>',
      '</div>',
      '<hr>',
      '<h2>About</h2>',
      '<p>Joe Plant. I run Mirrordisc, which is me, a PO box and a lot of stamps.</p>',
      '<p>I put out two things. An LP by meme and tome in 2001, five hundred of',
      'them, and a DVD the September after. Both of them cost more to make than',
      'they took, which everybody told me they would, and I would do it again in',
      'the morning.</p>',
      pic('joe-vaughan-wales', 'Wales, on holiday. Me on the right doing the trick with the beer mat, which was a trick I could do, and Vaughan on the left about to explain why the hand he is holding is better than it looks. Cards, cans, and a caravan’s worth of flowers on every soft surface in the building.', 'r'),
      '<h2>Why a label</h2>',
      '<p>Because somebody has to be the one who says yes. A record does not need',
      'a good reason to exist, it needs one person with a box number who will',
      'take the cheques and get the sleeves printed, and the reason there are so',
      'few records is that being that person is boring and nobody wants to.</p>',
      '<p>I liked it. I liked the parcels. I liked the handwriting on the orders.',
      'One came from Japan with a note in it in English that had clearly taken an',
      'hour and I have still got it.</p>',
      '<h2>The site</h2>',
      '<p>I built this myself on the Mac, which is why it is a frameset and why',
      'the pages up there have mostly never had anything on them. I kept meaning',
      'to. <a href="homepage.mac.com/mirrordisc/artists">ARTISTS</a> was going to',
      'be a paragraph each. I never got one out of him, and I am the other one and',
      'I could not get one out of myself either, so in the end I sat down and did',
      'the pair of us in an evening.</p>',
      '<p>This one I have finally written, years late, on the same disk, because',
      'somebody asked me what Mirrordisc was and I found I did not have anywhere',
      'to point them.</p>',
      '<hr>',
      '<p class="md-foot"><i>Site designed by Joseph</i></p>',
      '<p class="md-foot"><small>Joe Plant, Mirrordisc Productions, Brighton.</small></p>',
    ],
  },
  // ---- the ARTISTS page, written by the wrong person -------------------------
  //
  // Joe's ABOUT page says the paragraph each never arrived, so this is the page
  // he wrote instead, at the same late sitting and in the same first person.
  // A label boss writing his own band's biography is doing PR, and the register
  // has to carry that: he sells the record, he is fond of them, and he says the
  // dull bits out loud because he was the one carrying the boxes.
  //
  // Every fact here is already on the label copy: the two catalogue numbers, the
  // per-track credits, the guests, mp3.com/TOME, locarecords.com, mrkirkland's
  // animation. The two press shots are the same two men at the same distance,
  // and nobody is named to a side of the frame, because the pictures do not say.
  {
    domain: 'homepage.mac.com/mirrordisc/artists',
    name: 'ARTISTS',
    title: 'MIRRORDISC — artists',
    body: [
      '<!--bg:mdisc-->',
      '<div class="md-bar">',
      '<img class="md-logo" src="assets/media/web/mirrordisc-logo.jpg" alt="Mirrordisc logo">',
      '<span class="md-nav"><a href="homepage.mac.com/mirrordisc">HOME</a> &nbsp; '
      + 'MUSIC &nbsp; ARTISTS &nbsp; '
      + '<a href="homepage.mac.com/mirrordisc/about">ABOUT</a> &nbsp; LINKS</span>',
      '</div>',
      '<hr>',
      '<h2>meme &amp; tome</h2>',
      pic('memetome-1', 'The press shot. Black paper behind them and a flash, taken in a front room, and it did the job for two years.', 'r'),
      '<p>Both of the records on this label are by these two, and one of the two',
      'is me, so we will have that out on line one. Mirrordisc exists because a',
      'record we made needed somebody to put it out and nobody else was going to.',
      'Every label starts like that. Most of them lie about it afterwards.</p>',
      '<p>They are a duo who work separately. Almost everything on <i>Invisible</i>',
      'is credited to the pair of them, and then there are four tracks that are',
      'not: <i>sodium</i>, <i>imperfection is the soul</i> and <i>frontier</i> are',
      'tome on his own, and <i>aufheben</i> is meme on his own. You can hear it.',
      'The solo ones are longer and they do not resolve.</p>',

      '<h2>meme</h2>',
      '<p>Brighton, mostly. He has been putting things out with Loca for years and',
      'there is more of him at www.locarecords.com than there is here, which I am',
      'not going to pretend otherwise about. His name turns up on other people’s',
      'sleeves as well, usually in small type and usually spelled the way he likes',
      'it, lower case.</p>',
      '<p>He plays live on his own with one box and a lead, and it is better than',
      'that sounds. No laptop. He starts something, leaves it running longer than',
      'is comfortable, and changes one thing.</p>',

      '<h2>tome</h2>',
      pic('memetome-2', 'The other one from the same roll. We sent both to the distributors and I could never tell you what the difference was. I am on the right behind the hair and he is on the left in the glasses, before anybody asks.', 'l'),
      '<p>tome is me. <b>Joe Plant</b>, guitarist, Brighton. I am aware that a man',
      'writing his own entry on his own label’s website is a bit much, and I have',
      'decided to live with it, because the alternative is an empty page and there',
      'has been one of those here for two years.</p>',
      '<p>Lead guitar. That is the job. I have been doing it since I was fifteen',
      'and I am good at it, and I say so because the people who are good at it and',
      'go quiet about it end up playing weddings. I also take photographs and I',
      'make films, both of which started as a way of having something to do at four',
      'in the morning when everybody else had gone home.</p>',
      '<p>The rest of it, in the order people usually put it to me: I can get a',
      'party out of a Tuesday and an empty flat, I will talk to anybody about',
      'anything for longer than is reasonable, and if you want to find me I am in',
      'the <a href="theheartandhand.geocities.ws">Heart &amp; Hand</a> on the',
      'corner, under the posters, near the jukebox, and I will have put something',
      'on it that you did not ask for.</p>',
      '<p>The CD of <i>Invisible</i> is on mp3.com under tome rather than the',
      'duo’s name, at <a href="mp3.com">www.mp3.com/TOME</a>, because of an',
      'argument with a form that neither of us won.</p>',
      '<p>I mixed the LP. Four days in a room in Hove with a window that did not',
      'open, and I came out with all nine of them and a cold.</p>',

      '<h2>The others on the record</h2>',
      '<p>Nine tracks and five other people on them. The athlete is on',
      '<i>invisible</i>. Williams is on <i>neon</i>. Camilleri is on',
      '<i>colour</i>. Burgan and Banks are both on <i>whatever you say</i>, which',
      'is the one with the singing on it and the one everybody picks.</p>',
      '<p>None of them were paid. All of them were asked, which I mention because',
      'people assume the opposite about small labels and they are usually right.</p>',

      '<h2>The DVD</h2>',
      '<p>mddv 001, September 2002. Mr Kirkland did the animation and the promo',
      'is in the animation section at www.mrkirkland.com. It is the record with',
      'pictures on it and the pictures are not illustrations of the record, which',
      'took me a while.</p>',

      '<h2>Getting hold of us</h2>',
      '<p>Write to the PO box on the front page and I will pass it on, or find me',
      'in the pub, which is quicker and has always worked. I am not putting his',
      'address on a web page and he would not thank me for putting mine.</p>',
      '<hr>',
      '<p class="md-foot"><i>Site designed by Joseph</i></p>',
      '<p class="md-foot"><small>Joe Plant, Mirrordisc Productions, Brighton.</small></p>',
    ],
  },
  // ---- the pub ---------------------------------------------------------------
  //
  // Every scene in this corner of the archive has been pointing at the same
  // room without naming it. The Loca lot, the Calvados Beam Trio, meme with his
  // one box and a lead, Joe on the guitar: they all drank in the same pub, and
  // the pub is the thing that connects them, not any of the labels.
  //
  // Kept by a regular, not by the brewery and not by the landlord. That is what
  // a pub page on the cached web actually was: somebody with a scanner and an
  // opinion about the jukebox. It starts in 1998 as text and the photographs
  // arrive later, which is also what happened to every page like it, and is why
  // the pictures on it are of a room that has already changed.
  //
  // Sourcing. The exterior and the interiors are photographs of the building.
  // Bert Read the landlord, his daughter Lara Read the landlady, and the death
  // of the old jukebox come from a press caption filed in Brighton in January
  // 2007; the stained glass is on record too. Everything else on the page is
  // the room in the pictures — the green glaze, the gold lettering, the wall of
  // framed bills, the Harvey's, the two cats — described and not invented.
  {
    domain: 'theheartandhand.geocities.ws',
    name: 'THE HEART & HAND',
    title: 'The Heart & Hand, Brighton',
    body: [
      '<!--bg:hnh-->',
      '<h1>The Heart &amp; Hand</h1>',
      '<p><small>North Laine, Brighton. On the corner, where it has always been.</small></p>',
      '<hr>',
      pic('hnh-outside', 'The corner. Green glaze to head height, gold cut into the tiles, and everything above it painted red so you can find it from the top of the street.', 'r'),
      '<p>This is not the pub’s page. The pub does not have a page and would not',
      'want one. This is mine, and it is here because I was asked for the third',
      'time in a month which pub it was that everybody meant, and I would rather',
      'type it once.</p>',
      '<p>It is the corner one. Dark green tiles up to head height with',
      '<b>THE HEART and HAND</b> and <b>United Ales and Stout</b> cut into them in',
      'gold, red round every window, a hanging sign, and a door set into the angle',
      'so that walking in feels like being let in. Window boxes. Yard opposite.',
      'You have walked past it.</p>',

      '<h2>The jukebox</h2>',
      pic('hnh-jukebox', 'It stands against the poster wall and it has stood there longer than most of the people looking at it.', 'l'),
      '<p>Start here, because everybody does. It is old, it is loud, it is lit up',
      'like a fairground, and for about ten years it was the single most argued-over',
      'object in the North Laine. Three ranks of buttons and a lamp behind them.',
      'You put your money in and then you had to stand there and take what came,',
      'because there was no cancelling anything and no skipping anything.</p>',
      '<p>What is in it is not what a jukebox company would put in it. People got',
      'their own records into it, which is the whole reason it mattered. There',
      'have been singles in that machine that were pressed five hundred at a time',
      'in somebody’s name, including at least one I can account for personally,',
      'and hearing your own record come out of a jukebox in a pub you drink in is',
      'a thing that happens to about four people a decade.</p>',
      '<p><small>Added later: it has finally died. Bert says a newer one is being',
      'delivered. I have asked whether the records are going across into it and',
      'have not had a straight answer.</small></p>',

      '<h2>The wall</h2>',
      '<p>Framed bills, floor to ceiling, all round the back room, and more of them',
      'going up than coming down. Gigs in the pub, gigs down the road, gigs that',
      'never happened, tours that got as far as the poster. Nobody curates it.',
      'Something goes up when somebody brings it in and it stays up until the',
      'frame is needed.</p>',
      '<p>Half the reason to stand up and go to the bar the long way round is to',
      'read a bit more of it.</p>',

      '<h2>Who is in</h2>',
      '<p>Musicians, mostly, which is not a boast about the pub, it is just where',
      'they went. Nobody chose it. It had a jukebox you could get your own records',
      'into, it did not have a stage, and that second one matters more than people',
      'think: nobody in there is on. You can talk to anyone.</p>',
      '<pre class="jb-list">',
      '  in on a given night, at one time or another',
      '',
      '  the Loca lot                   see loca-tapes.org.uk',
      '  meme                           tapes, then one box and a lead',
      '  Joe Plant (tome)               guitar, and the one who put the LP out',
      '  the Calvados Beam Trio         when they were down from Birmingham',
      '  people off records you own     who will not say so',
      '</pre>',
      '<p>Links, since you will ask:',
      '<a href="loca-tapes.org.uk">loca-tapes.org.uk</a>,',
      '<a href="homepage.mac.com/mirrordisc/artists">Mirrordisc</a>,',
      '<a href="calvadosbeamtrio.fanpages.org.uk">the Calvados Beam Trio</a>.</p>',

      '<h2>The bar</h2>',
      pic('hnh-bar', 'Harvey &amp; Son on the mirror, old, mild and pale ales, and the coloured glass along the top of the bar back that nobody notices until a weekday afternoon.', 'r'),
      '<p>Harvey’s. The mirror behind the bar says <i>Harvey &amp; Son</i> and',
      '<i>old, mild and pale ales</i> and has said it for longer than the brewery',
      'has been advertising anything. Above the bar back there is a run of',
      'coloured glass, and the only time you will ever see it properly is if you',
      'come in on a weekday afternoon when the lamps are off and the sun is',
      'getting through the front windows.</p>',
      '<p>Chalk board for the beer. No food to speak of. Do not come here for',
      'food.</p>',

      '<h2>The cats</h2>',
      pic('hnh-cat', 'On the bench, having a look at what is on the table, which is flyers, which are not food, which will not stop him.', 'l'),
      '<p>There is always a cat. Not the same cat. There has been a ginger one who',
      'sat on the bench seats and put his face in whatever was on the table, and a',
      'grey one who sits on a table herself and lets people go round her. Neither',
      'of them has ever been asked to move. You take the next seat along.</p>',

      '<h2>Behind the bar</h2>',
      '<p><b>Bert Read</b> has the licence. His daughter <b>Lara</b> is behind the',
      'bar most nights and is the one who will tell you to sit down. Between them',
      'they have run it the way it wants to be run, which is to say they have',
      'mostly not done anything to it, and that is harder than it sounds and',
      'costs money every year that somebody else would have spent on a',
      'refurbishment.</p>',

      '<hr>',
      '<p><small>Kept by Mick H., who is in most Thursdays. Corrections to the',
      'usual place. Started 1998, pictures added when I got the camera.</small></p>',
    ],
  },
  // ---- Ward ------------------------------------------------------------------
  //
  // Ward have been on three pages of this archive as somebody else's footnote:
  // Steve's Loca page reading the VAN 36 sleeve, the Calvados page working out
  // that Richard Williams is in both bands, and the pub page listing who drank
  // where. This is the page that is about them.
  //
  // A different keeper from Steve, on purpose. The web is supposed to have more
  // than one person on it, and this one came to the band the way a lot of people
  // did — through Peel putting the record on at the wrong speed — so the page is
  // organised round the records and the film rather than round having been there.
  //
  // The film is real and its own end card is the source: WARD / Generating Civil
  // Society / from the album "It might be useful..." / Animation by David Meme /
  // (c) 2005 locarecords.com / Creative Commons Attribution-Share-alike. That
  // licence is why it can be on a page at all, and the page says so.
  {
    domain: 'ward.fanpages.org.uk',
    name: 'WARD',
    title: 'Ward — a fan page',
    body: [
      '<!--bg:ward-->',
      '<h1>WARD</h1>',
      '<p><small>Two people, four records, one film, and a mistake on the radio',
      'that is the reason I am here.</small></p>',
      '<hr>',
      pic('ward-wall', 'Two of them against a brick wall in the cold with their hands in their pockets, which was the compulsory press shot of the period and they have not fought it.', 'r'),
      '<p><b>Ward</b> are David Meme and Richard Williams. They recorded at 570A',
      'Old Street in London and mastered in Brighton, put two seven-inches out on',
      'Static Caravan and two albums out on Loca, and every one of those Loca',
      'releases went out under a licence that lets you copy it.</p>',
      '<p>I have never seen them play. I am not going to pretend otherwise on the',
      'front page of a fan site. What I have is the records, one film, and a',
      'reasonably good ear.</p>',

      '<h2>How I got here</h2>',
      '<p>John Peel, <b>7 March 2002</b>, playing <i>Sesquipedalian Origins</i> at',
      '45 when it is a seven-inch cut at 33⅓. I did not know that was what had',
      'happened. I sat there and thought: that is a very odd record and I want it.',
      'Then I got it, and it was slower and lower and better, and I had spent a',
      'fortnight loving a version of a song that has never existed.</p>',
      '<p>He had played it on <b>5 February</b> as well, at the right speed, and I',
      'missed that one.</p>',

      '<h2>The records</h2>',
      '<pre class="jb-list">',
      '  Sesquipedalian Origins / Calcium Taut Verdun',
      '                         Static Caravan · VAN 36   2001   7" at 33⅓, blue',
      '                                                   2001   white-label promo',
      '  It’s Not Necessarily Your Height It Could Be Your Feet',
      '                         Loca · LOCA004            2002   CD',
      '  De Fernius / Armonica Or Something',
      '                         Static Caravan · VAN 64   2004   lathe-cut 7"',
      '  It Might Be Useful For Us To Know',
      '                         Loca · LOCA009            2005   CD',
      '</pre>',
      '<p>Four titles, and not one of them is a phrase. They are all sentences',
      'with the subject taken out, and once you have noticed that you cannot stop',
      'noticing it. <i>It’s not necessarily your height it could be your feet</i>',
      'is a thing somebody says to you. <i>It might be useful for us to know</i>',
      'is a thing somebody in an office says to you.</p>',
      '<p>Fuller reading of the VAN 36 sleeve, both sides, and the Peel business',
      'in more detail, is on <a href="loca-tapes.org.uk">Steve S.’s page</a>. He',
      'has that one in his hands and I am working off scans, so where we',
      'disagree on VAN 36, believe him.</p>',

      '<h2>VAN 64, which I do have</h2>',
      pic('ward-van64', 'Held up to the window, because that is the only way to photograph one. Clear disc, white label, and a line drawing of two lads having each other over on the floor.', 'r'),
      '<p>This is the one I can speak for. <i>De Fernius</i> on the a-side and',
      '<i>Armonica Or Something</i> on the b, Static Caravan, VAN 64, 2004, and',
      'it is a <b>lathe cut</b>, which is why it is see-through.</p>',
      '<p>If you have not had one: a lathe cut is not pressed. A pressed record is',
      'stamped out of hot vinyl by a die, hundreds an hour, and you need to order',
      'enough of them to justify making the die. A lathe cut is machined one at a',
      'time, in real time, by a cutting head going across a blank while the music',
      'plays. Four minutes of music takes four minutes of lathe. Nobody is making',
      'you order five hundred, and a run of a hundred is a fortnight of somebody',
      'standing over a machine.</p>',
      '<p>They are usually cut on clear polycarbonate rather than black vinyl,',
      'which is the look. Hold one up and you can see the room through it. They',
      'are also noisier, quieter in the groove, and they wear, so the fifteenth',
      'play is audibly not the first, and there is no getting round that and',
      'nobody who buys them wants it got round.</p>',
      '<p>The label is a line drawing of two children, one leaning across the',
      'other on the floor, both of them laughing, in the flat clean line of a',
      'schoolbook illustration from about 1962. <b>ward</b> in lowercase in the',
      'top right, under a small black shape. Static Caravan’s little boxed logo',
      'top left. The two titles running round the bottom curve in a face so small',
      'I had to take the record to a window, and then <b>VAN 64</b> underneath',
      'them in big hand-drawn capitals, which is the only thing on the whole',
      'record that is easy to read.</p>',
      '<p>No sleeve to speak of. It came in a plain one.</p>',
      '<p>Hold that small black shape in your head for the next section.</p>',

      '<h2>VAN 36, which Steve sent me a photograph of</h2>',
      pic('ward-van36-pair', 'The sleeve and the record next to each other on a white table. Blue line drawings on deep red, and a seven-inch you can see the light through.', 'r'),
      '<p>I wrote to Steve about the shape and he did better than answer: he took',
      'the earlier one out of its sleeve, put the two side by side and',
      'photographed them. So I can now say something I have wanted to say for',
      'about three years.</p>',
      '<p><b>It is on both records.</b> The same small black shape, above the word',
      '<i>ward</i>, on a lathe cut from 2004 and on a pressed seven from 2001,',
      'and it is not a printer’s mark or a bit of the artwork, because the',
      'artwork on the two is nothing like each other. It is theirs. Two people',
      'who never put a photograph out, never did an interview I can find, and',
      'named four records with four unfinished sentences, kept one mark and put',
      'it on everything.</p>',
      '<p>I still cannot tell you what it is. A boat seen end-on. A dish. A hat.',
      'Two upturned ends and a flat bottom, solid black, about the width of the',
      'word underneath it. Somebody will know and I would like to be told.</p>',
      '<h2>And while I have got the picture</h2>',
      '<p>It is translucent blue and you can see the table through the run-out.',
      'The label is the same deep red as the sleeve, and it says:</p>',
      '<pre class="jb-list">',
      '  ward',
      '',
      '  Sesquipedalian Origins    This Side:',
      '  Calcium Taut Verdun       That Side:',
      '',
      '                 33 rpm',
      '</pre>',
      '<p>Two things. <i>This Side</i> and <i>That Side</i> rather than A and B,',
      'which is a joke that only works on an object you can turn over. And',
      '<b>33 rpm</b> set larger than the band’s own name, in the middle of the',
      'label, where nothing else is. They knew what was going to happen to a',
      'seven-inch cut at 33⅓ and they did everything a record can do to stop it,',
      'and it went out at 45 on national radio anyway.</p>',
      '<p>Static Caravan’s logo is top right: a little hut, or a caravan, in a',
      'square frame with the name set small underneath.</p>',
      '<p>The sleeve is blue line drawing on deep red, inside a thin pale border.',
      'A chandelier on wires. A figure with wings at the bottom. A camera. A',
      'diamond. A hand. A monkey. Things floating with no ground under any of',
      'them. <i>ward</i> across the foot with the two titles beside it in small',
      'italic, and a large <b>1</b> in a bracket at the corner, which I take to',
      'mean somebody intended a second one and it did not come.</p>',

      '<h2>The film</h2>',
      vid('ward-civil-society', 'Ward — Generating Civil Society (2005)',
        'Four minutes of stop motion on a desk: drawing pins, beads and paper clips walking themselves into rings and lines under a lamp, in front of a shelf of books, with a CD propped against the spines.'),
      '<p><i>Generating Civil Society</i>, off <i>It Might Be Useful For Us To',
      'Know</i>. Animation by <b>David Meme</b>, which is to say one half of the',
      'band spent however many hundred hours it takes moving beads a millimetre at',
      'a time.</p>',
      '<p>Watch what is behind it, because it is not set dressing. That is a',
      'shelf, and the spines you can read are <i>rebel code</i>, <i>Capitalism and',
      'the Information Age</i>, <i>Frameworks of Power</i>, <i>The Future of',
      'Ideas</i>, <i>Political Machines</i>, and a red Antonio Negri. A film about',
      'small things arranging themselves into an order nobody imposed, shot in',
      'front of the shelf of books that argue about exactly that, made by a band',
      'on a label that licensed its records so other people could take them apart.',
      'Nobody is nudging you. It is just all in the same frame.</p>',
      '<p>It carries <b>Creative Commons Attribution-Share-alike</b>, © 2005',
      '<a href="locarecords.com">locarecords.com</a>, which is why I can put it',
      'on a fan page without asking anybody, and why you can take it off this',
      'page and do the same.</p>',

      '<h2>The other lot</h2>',
      '<p>Richard Williams also played guitar in the <a',
      ' href="calvadosbeamtrio.fanpages.org.uk">Calvados Beam Trio</a> in',
      'Birmingham, and a <b>williams</b> is credited on <i>neon</i> on the',
      'Mirrordisc LP in Brighton. Whether that is all one man is somebody else’s',
      'argument on somebody else’s page and I am staying out of it.</p>',
      '<p><b>What Ward is not.</b> I get this one about every six weeks, so:',
      'Ward is two people and they are David Meme and Richard Williams. That is',
      'the whole band. <b>Joe Plant is not in Ward.</b> He is the other half of',
      'meme &amp; tome, he runs',
      '<a href="homepage.mac.com/mirrordisc">Mirrordisc</a>, and he plays lead',
      'guitar, and I can see exactly how you got there — a Brighton guitarist,',
      'in the same pub, on a record with meme on it — but he is a different man',
      'in a different band and the sleeves say so.</p>',
      '<p>The overlap is meme. He is in both. That is the only person who is.</p>',
      '<p>Both of them turn up in <a href="theheartandhand.geocities.ws">the Heart',
      '&amp; Hand</a>, which appears to be where this entire scene was kept.</p>',

      '<h2>One answer to one question</h2>',
      '<p>I have written to them twice. The first one got nothing. The second',
      'one asked what their favourite computer was, because I had run out of',
      'sensible questions, and I got one line back:</p>',
      '<p><i>Spectrum 48K, and it is not close.</i></p>',
      '<p>So I have made <a href="spectrum48.geocities.ws">a page about that</a>',
      'as well, which tells you something about how much correspondence I have to',
      'work with.</p>',
      '<hr>',
      '<p><small>Kept by Andy R. If you have a gig list, a ticket stub or a date',
      'I have got wrong, that is what I am short of. I have the records. I do not',
      'have the room.</small></p>',
    ],
  },
  // ---- Loca Records, the label's own site -------------------------------------
  //
  // Not Steve's fan page — the label. A label that put records out under the GPL
  // had a site that read like documentation: white, small sans, one red, no
  // photograph of anybody, and the licence given in full rather than linked.
  // The theme is deliberately the opposite of bg-loca so the two are never
  // mistaken for one another.
  //
  // Nothing here is analysis. The label states its catalogue, its terms and its
  // two films, in the first person plural, the way a label writes about itself.
  {
    domain: 'locarecords.com',
    name: 'LOCA RECORDS',
    title: 'Loca Records',
    body: [
      '<!--bg:locaweb-->',
      '<h1>Loca Records</h1>',
      '<p><small>Brighton and Old Street · electronica, post rock · copyleft</small></p>',
      '<hr>',
      '<p>Loca is a record label. Everything we release is licensed so that you',
      'may copy it, play it in public, remix it, re-release it and sell what you',
      'make, on one condition: what you make carries the same licence forward.</p>',
      '<p>Founded 1999 by David M. Berry and Marcus McCallion.</p>',

      '<h2>The licence</h2>',
      '<p>Our first two releases went out under the <b>GNU General Public',
      'License</b> — the software licence, applied to a record, because in 1999',
      'there was nothing else that did the job. We moved to the EFF’s',
      '<b>Open Audio License</b>, and then to <b>Creative Commons',
      'Attribution-ShareAlike</b> when that existed.</p>',
      '<p>We are aware that this is unusual and we are not going to explain it',
      'every time. The short version: a record is not diminished by being copied,',
      'and a label that pretends otherwise is protecting a distribution',
      'arrangement rather than any music.</p>',

      '<h2>Catalogue</h2>',
      '<pre class="jb-list">',
      '  LOCA001   Kinematic                             1999   GPL',
      '  LOCA002   Mandibles EP                          1999   GPL',
      '  LOCA004   Ward                                  2002   CD',
      '            It’s Not Necessarily Your Height',
      '            It Could Be Your Feet',
      '  LOCA009   Ward                                  2005   CD',
      '            It Might Be Useful For Us To Know',
      '',
      '  meme      several releases and a good deal more',
      '            unreleased. Ask.',
      '</pre>',

      '<h2>Film</h2>',
      '<p>Two, both free to take, both under the same terms as the music.</p>',
      vid('ward-civil-society', 'Ward — Generating Civil Society (2005)',
        'Ward, Generating Civil Society, from It Might Be Useful For Us To Know. Stop motion, four minutes, animated by David Meme. © 2005 Loca Records, Creative Commons Attribution-Share-alike.'),
      vid('meme-invisible', 'meme — Invisible (2003)',
        'meme, Invisible. Live action in a green-gold workshop: a man in a lab coat and a head lamp bending wire over a bench, and the thing on the bench turning out to have a face. It ends when its eyes come on.'),
      '<pre class="jb-list">',
      '  meme · Invisible · 2003',
      '',
      '  Director            Dan Knight',
      '  Producer            Loca Records',
      '  Production company  Loca Records',
      '</pre>',
      '<p>We made that one ourselves rather than commissioning it out, which is',
      'why it says Loca twice. <i>Invisible</i> is also the title of the meme',
      '&amp; tome LP on Mirrordisc, whose record it is, at',
      '<a href="homepage.mac.com/mirrordisc">Mirrordisc Productions</a>,',
      'Brighton, by cheque to a box number. Several tracks off it and a great',
      'many other meme tracks are here.</p>',

      '<h2>Elsewhere</h2>',
      '<p>Somebody has written a long page about us that we did not ask for and',
      'have read twice: <a href="loca-tapes.org.uk">loca-tapes.org.uk</a>. There',
      'is a fan page for Ward at <a href="ward.fanpages.org.uk">',
      'ward.fanpages.org.uk</a>. Both of them have facts we do not.</p>',
      '<hr>',
      '<p><small>Loca Records. Copy this.</small></p>',
    ],
  },
];
