// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — orators, reformers & pioneering leaders.
//
// Cached fan and student pages, each ABOUT a political figure and never in that
// figure's own voice. A rally write-up for King; a reader's notes on Douglass;
// a plain-spoken shrine to Golda Meir; a coursework summary of Indira Gandhi; a
// student essay on Walesa and Solidarity; a rally page for Marti. The dates,
// offices and speeches are real; the framing and the enthusiasm are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Martin Luther King: the rally / march write-up -------------------------

const KING = P('martin-luther-king.geocities.ws', 'M L KING',
  'THE MARCH GOES ON // Dr King and the movement', [
    '<!--bg:pol-reformers-->',
    '<h1>THE MARCH GOES ON</h1>',
    '<p><small>notes written up after our branch meeting on the civil rights',
    'movement, for anyone who could not make it and for the sixth-formers who',
    'asked for a reading list. put together by the Tuesday history circle. all',
    'welcome, back room of the community hall, 7pm.</small></p>',
    '<hr>',
    '<p class="fs-epi"><i>A page about Dr Martin Luther King Jr (1929–1968),',
    'Baptist minister, and the leader the American civil rights movement is most',
    'remembered by. Read it and then read him.</i></p>',
    '<p>It starts with a bus. In December 1955, in Montgomery, Alabama, Rosa Parks',
    'refused to give up her seat to a white passenger, and the black community of',
    'the city stopped riding the buses. The boycott held for 381 days. A young',
    'minister new to the city, twenty-six years old, was chosen to lead it, and',
    'that was Martin Luther King. The buses were losing money and the courts',
    'finally struck the segregation down. The method that would run through the',
    'whole movement was there from the start: mass, disciplined, nonviolent',
    'refusal.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/mlk-01.jpg" alt=""><span class="indie-cap">Martin Luther King Jr (public domain)</span>',
    '<p>Where did the nonviolence come from. From the black church and the Sermon',
    'on the Mount, and also, openly, from India. King read Gandhi and travelled',
    'there in 1959, and he took from him the idea that you could refuse an unjust',
    'law and take the punishment for it and by doing so shame the law into',
    'changing. He owed Mohandas Gandhi that debt and said so plainly. There is a',
    'page on Gandhi\'s heir in Indian office, his granddaughter-in-law in politics',
    'if not in blood, over at the Indian side of this ring; do not confuse the two',
    'families, the movement did not.</p>',
    '<p>Then Birmingham, 1963, where the campaign met dogs and fire hoses turned on',
    'children, and the pictures went round the world. King was arrested and wrote,',
    'on the margins of a newspaper, the <i>Letter from Birmingham Jail</i>, an',
    'answer to white clergymen who had told him to wait and be patient. It is the',
    'best short statement of why a person of conscience breaks an unjust law that',
    'anyone has written.</p>',
    '<p class="fs-quote"><blockquote><p>&ldquo;Injustice anywhere is a threat to',
    'justice everywhere.&rdquo;</p><p>&mdash; Letter from Birmingham Jail, April',
    '1963</p></blockquote></p>',
    '<p>And then the March on Washington for Jobs and Freedom, 28 August 1963, a',
    'quarter of a million people at the Lincoln Memorial, where he gave the speech',
    'everyone knows by four words. The prepared text was good. Then the singer',
    'Mahalia Jackson called out to him to tell them about the dream, and he set the',
    'paper aside and preached.</p>',
    '<p class="fs-quote"><blockquote><p>&ldquo;I have a dream that my four little',
    'children will one day live in a nation where they will not be judged by the',
    'colour of their skin but by the content of their character.&rdquo;</p><p>&mdash;',
    'March on Washington, 28 August 1963</p></blockquote></p>',
    '<img class="indie-pic" src="assets/media/web/pol/douglass-01.jpg" alt=""><span class="indie-cap">Frederick Douglass (photo: G. K. Warren, public domain)</span>',
    '<p>The Civil Rights Act came in 1964 and the Voting Rights Act in 1965, the',
    'second after the marches from Selma to Montgomery. In 1964 King was awarded',
    'the Nobel Peace Prize, at thirty-five the youngest man then to have received',
    'it, and he gave the prize money to the movement. In his last years he widened',
    'the argument to poverty and to the war in Vietnam, which cost him allies, and',
    'he was planning a Poor People\'s Campaign when he was killed.</p>',
    '<div class="fs-aside"><p><b>The last night.</b> He had gone to Memphis to',
    'support the city\'s striking sanitation workers. On 3 April 1968 he told them',
    'he had been to the mountaintop and had seen the promised land. The next',
    'evening, 4 April, he was shot dead on the balcony of the Lorraine Motel. He',
    'was thirty-nine.</p></div>',
    '<p class="fs-pull"><b>&ldquo;The arc of the moral universe is long, but it',
    'bends toward justice.&rdquo;</b> He said it often. He did not claim to have',
    'coined it; it comes from the abolitionist minister Theodore Parker, and King',
    'wore it smooth with use.</p>',
    '<pre>',
    ' A MOVEMENT TIMELINE',
    ' 1955  Montgomery bus boycott begins (Dec)',
    ' 1957  founds the Southern Christian Leadership Conference',
    ' 1959  visits India, studies Gandhi',
    ' 1963  Birmingham campaign; Letter from Birmingham Jail',
    ' 1963  March on Washington, "I Have a Dream" (28 Aug)',
    ' 1964  Civil Rights Act; awarded the Nobel Peace Prize',
    ' 1965  Selma to Montgomery marches; Voting Rights Act',
    ' 1968  assassinated in Memphis (4 Apr)',
    '</pre>',
    '<p>Where to go next. He read the abolitionists, and the greatest of the',
    'orators who came before him has a page at',
    '<a href="frederick-douglass.geocities.ws">frederick-douglass</a>, kept by a',
    'reader who has clearly done the work. And for a very different figure of the',
    'same decades, a woman leading a nation while King was marching, see',
    '<a href="golda-meir.geocities.ws">golda-meir</a>.</p>',
    '<hr>',
    '<p><small>counter: 03521 · best viewed at 800x600 · this page is under',
    'construction, more speeches to add · last updated 15 Jan · the Tuesday history',
    'circle</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Frederick Douglass: the book-reading notes -----------------------------

const DOUGLASS = P('frederick-douglass.geocities.ws', 'F DOUGLASS',
  'reading the NARRATIVE // notes on Douglass', [
    '<!--bg:pol-reformers-->',
    '<h1>Reading Frederick Douglass</h1>',
    '<p><small>my notes as i work through the <i>Narrative</i> and the later',
    'autobiographies. i keep them here so i can find them and so a friend two towns',
    'over can read along. corrections welcome. — R.H.</small></p>',
    '<hr>',
    '<p>Frederick Douglass (c.1818–1895) was born into slavery in Maryland and did',
    'not know the year of his own birth, which is itself part of the argument he',
    'spent his life making: that slavery robs a person even of the ordinary facts',
    'of themselves. He taught himself to read against the law and against the will',
    'of those who held him, escaped to the North in 1838, and became the most',
    'powerful orator the abolition movement had.</p>',
    '<p>Book one, and the one to start with, is the <i>Narrative of the Life of',
    'Frederick Douglass, an American Slave, Written by Himself</i> (1845). That',
    'last clause is doing real work. Slave narratives were often introduced and',
    'vouched for by white editors; Douglass wrote his own, and wrote it so well',
    'that some doubted a former slave could have done it, which was exactly the',
    'prejudice he had set out to break.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/douglass-01.jpg" alt=""><span class="indie-cap">Frederick Douglass (photo: G. K. Warren, public domain)</span>',
    '<p class="fs-quote"><blockquote><p>&ldquo;You have seen how a man was made a',
    'slave; you shall see how a slave was made a man.&rdquo;</p><p>&mdash; Narrative',
    'of the Life of Frederick Douglass (1845)</p></blockquote></p>',
    '<p>That sentence sits at the hinge of the book, before the fight with the',
    'slave-breaker Covey, which Douglass makes the turning point of his life. My',
    'note in the margin just says: the whole abolitionist case in one line, that a',
    'man is not a thing and can be un-made into a thing and can make himself back.</p>',
    '<div class="fs-aside"><p><b>The speech.</b> On 5 July 1852, asked to mark the',
    'Fourth, he gave <i>What to the Slave is the Fourth of July?</i> He praised the',
    'founders and then turned the day on its head: the celebration of liberty was,',
    'to the enslaved, a mockery, and he said so to a hall of people who had come to',
    'feel good about their country. It is the sharpest thing he ever spoke.</p></div>',
    '<p class="fs-quote"><blockquote><p>&ldquo;This Fourth of July is yours, not',
    'mine. You may rejoice, I must mourn.&rdquo;</p><p>&mdash; What to the Slave is',
    'the Fourth of July?, 5 July 1852</p></blockquote></p>',
    '<p>He founded and edited his own newspaper, the <i>North Star</i>, from',
    'Rochester in 1847, and took its name from the star that guided people escaping',
    'north. Owning the press mattered to him; it meant the movement did not have to',
    'ask anyone else\'s leave to speak. He broke, over time, with the pacifist wing',
    'of abolition led by William Lloyd Garrison, and came to argue that the',
    'Constitution could be read as an anti-slavery document and that the vote and',
    'the law were weapons worth using.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/marti-01.jpg" alt=""><span class="indie-cap">Jose Marti (CC BY-SA 4.0)</span>',
    '<p>In the Civil War he pressed Abraham Lincoln to let black men enlist and to',
    'make emancipation the war\'s purpose, and he met the president more than once,',
    'a former slave advising the head of state. He recruited for the black',
    'regiments; two of his own sons served. After the war he kept on for the vote',
    'and, later, for women\'s suffrage, and he held federal offices. He revised his',
    'life story twice more, the last being <i>Life and Times of Frederick',
    'Douglass</i> (1881).</p>',
    '<p class="fs-pull"><b>&ldquo;If there is no struggle, there is no',
    'progress.&rdquo;</b> from an address on West India Emancipation, 1857. it is',
    'the line most people know, and it earns its keep.</p>',
    '<p>Reading on. The orator who took up this method for the next century has a',
    'page at <a href="martin-luther-king.geocities.ws">martin-luther-king</a>, and',
    'the debt is direct. For an independence orator of the Americas working the',
    'same years as Douglass\'s old age, see',
    '<a href="jose-marti.geocities.ws">jose-marti</a>, who wrote about the United',
    'States from the inside and was not fooled by it.</p>',
    '<hr>',
    '<p><small>bookworm counter: 01204 · best viewed at 800x600 · still reading,',
    'notes on the 1855 <i>My Bondage and My Freedom</i> to come · last updated',
    '9 Feb · R.H.</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Golda Meir: the personal fan shrine ------------------------------------

const MEIR = P('golda-meir.geocities.ws', 'GOLDA MEIR',
  'GOLDA // the schoolteacher who became PM', [
    '<!--bg:pol-reformers-->',
    '<h1>GOLDA</h1>',
    '<p><small>my page for Golda Meir, because my nan met her once at a fundraiser',
    'in the fifties and never stopped talking about it, and because there were not',
    'many women running countries then and there are not many now. — Sandra</small></p>',
    '<hr>',
    '<p>Golda Meir (1898–1978) was the fourth prime minister of Israel and, to',
    'this day on the page i am writing, the only woman to have held the office. She',
    'was born in Kiev, in the Russian Empire, and remembered as a small child the',
    'fear of the pogroms. The family emigrated to the United States and she grew up',
    'in Milwaukee, Wisconsin, where she trained and worked as a schoolteacher. That',
    'is the fact i love most about her and it is why i keep this page: a teacher',
    'from Milwaukee ended up running a state.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/golda-meir-01.jpg" alt=""><span class="indie-cap">Golda Meir (photo: Marion S. Trikosko, public domain)</span>',
    '<p>She emigrated to Mandatory Palestine in 1921 with her husband, lived on a',
    'kibbutz, and rose through the Labour Zionist movement and the trade union',
    'federation, the Histadrut. She was one of the people who signed the Israeli',
    'declaration of independence in 1948, served as the first ambassador to the',
    'Soviet Union, then as minister of labour and foreign minister, and became',
    'prime minister in 1969 when she was seventy and already unwell.</p>',
    '<div class="fs-aside"><p><b>Plain speech.</b> People called her plain-spoken',
    'and she was, sometimes bluntly so, in ways later readers argue about,',
    'especially on the Palestinians, and it is fair to say her flat certainties on',
    'that question have not worn well and belong in any fair account of her. She',
    'said what she thought and did not dress it. My nan said she made you feel she',
    'was talking only to you, and also that you would not want to cross her.</p></div>',
    '<p class="fs-quote"><blockquote><p>&ldquo;We can forgive you for killing our',
    'sons. But we will never forgive you for forcing us to kill yours.&rdquo;</p>',
    '<p>&mdash; attributed to Golda Meir, on the wars with the Arab states</p>',
    '</blockquote></p>',
    '<p>Her premiership is marked above all by the Yom Kippur War of October 1973,',
    'when Egypt and Syria attacked on the holiest day of the Jewish year and Israel',
    'was caught unready. The country recovered and held, but the shock of the near',
    'miss and the failure of the warnings to be heeded broke the public trust. A',
    'commission of inquiry, the Agranat Commission, looked into the failures. Meir',
    'was not found personally to blame for them, but the anger did not settle, and',
    'in April 1974 she resigned.</p>',
    '<p class="fs-pull"><b>&ldquo;I never did anything alone. Whatever was',
    'accomplished in this country was accomplished collectively.&rdquo;</b> she said',
    'it near the end. take it with the salt of a politician\'s modesty, but she did',
    'come up through a movement, not a family name.</p>',
    '<p>She wrote her memoir, <i>My Life</i>, in 1975, and died in 1978; it came',
    'out then that she had been living with leukaemia for years, through the war and',
    'the office both. A schoolteacher, an ambassador, a foreign minister, a prime',
    'minister. Not a bad run for someone the history books nearly filed under',
    'somebody\'s wife.</p>',
    '<p>Elsewhere in the ring. The other woman leading a large nation in these same',
    'years, and just as fiercely argued over, is at',
    '<a href="indira-gandhi.geocities.ws">indira-gandhi</a>. And for the man whose',
    'method of moral oratory she had no time for but whose century she shared, the',
    'reader\'s notes at',
    '<a href="frederick-douglass.geocities.ws">frederick-douglass</a> are worth',
    'your time.</p>',
    '<hr>',
    '<p><small>visitors: 00918 · best viewed at 800x600 · guestbook is fixed now,',
    'sorry · last updated 22 Nov · made by Sandra with a lot of coffee</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Indira Gandhi: the academic summary ------------------------------------

const INDIRA = P('indira-gandhi.geocities.ws', 'I GANDHI',
  'Indira Gandhi (1917–1984) — a summary', [
    '<!--bg:pol-reformers-->',
    '<h1>Indira Gandhi: a summary</h1>',
    '<p><small>a reference note kept up for a reading group on twentieth-century',
    'Asian politics. sources at the foot. we try to keep it factual and to name the',
    'hard parts as well as the achievements.</small></p>',
    '<hr>',
    '<p class="fs-epi"><i>Indira Priyadarshini Gandhi (1917&ndash;1984), prime',
    'minister of India 1966&ndash;77 and 1980&ndash;84. Note at the outset: she was',
    'the daughter of Jawaharlal Nehru, India\'s first prime minister, and was in no',
    'way related to Mohandas (Mahatma) Gandhi. The shared surname comes from her',
    'marriage to Feroze Gandhi and misleads many. Two different families, two',
    'different stories.</i></p>',
    '<p>She grew up in the household of the Indian National Congress; her father',
    'led the country from independence in 1947 until his death in 1964. She became',
    'Congress president, then a minister, and in 1966 the party\'s leaders chose her',
    'as prime minister, expecting, wrongly, that she would be easy to guide. She',
    'proved to be one of the most formidable and most divisive figures in the',
    'country\'s history.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/indira-gandhi-01.jpg" alt=""><span class="indie-cap">Indira Gandhi (photo: Warren K. Leffler, public domain)</span>',
    '<p><b>The record, plainly.</b> Under her governments India pushed the Green',
    'Revolution, the programme of high-yield seed, irrigation and fertiliser that',
    'turned a country of recurrent famine into one that could feed itself and',
    'eventually export grain. She nationalised the major banks in 1969 and abolished',
    'the privy purses of the former princes. Her slogan was <i>Garibi Hatao</i>,',
    '&ldquo;abolish poverty&rdquo;, and it won her elections whatever the results on',
    'the ground.</p>',
    '<p>In 1971 India went to war with Pakistan over the crisis in East Pakistan,',
    'where the Pakistani army was carrying out mass killings and millions were',
    'fleeing across the border. India\'s intervention was swift and decisive and',
    'ended in the creation of the new state of Bangladesh. It was the height of her',
    'standing, at home and abroad. India tested a nuclear device in 1974.</p>',
    '<div class="fs-aside"><p><b>The Emergency, stated plainly.</b> In 1975, with a',
    'court having found her guilty of an election malpractice and her opponents',
    'calling for her to go, Indira Gandhi advised the president to declare a state',
    'of emergency. For twenty-one months, from 1975 to 1977, civil liberties were',
    'suspended, opposition leaders were jailed, the press was censored, and a',
    'programme of forced sterilisations was carried out, associated with her son',
    'Sanjay. This was authoritarian rule, and it should be named as such. She',
    'called an election in 1977, lost it, and was voted out.</p></div>',
    '<p>She returned to power in 1980. Her last years were dominated by unrest in',
    'Punjab, where an armed Sikh separatist movement had taken hold. In June 1984',
    'she ordered the army into the Golden Temple at Amritsar, the holiest site of',
    'Sikhism, where militants had fortified themselves. The operation, Blue Star,',
    'left many dead and deeply wounded Sikh feeling. On 31 October 1984 she was',
    'shot dead in her garden by two of her own Sikh bodyguards, and her',
    'assassination was followed by anti-Sikh riots in which thousands were killed.</p>',
    '<p class="fs-quote"><blockquote><p>&ldquo;I am alive today, I may not be there',
    'tomorrow &hellip; I shall continue to serve until my last breath.&rdquo;</p>',
    '<p>&mdash; Indira Gandhi, Bhubaneswar, 30 October 1984, the day before her',
    'death</p></blockquote></p>',
    '<p>She was succeeded by her son Rajiv Gandhi, himself later assassinated. The',
    'assessment remains contested: a leader of real nerve and real achievement who',
    'also suspended her country\'s democracy when it suited her, and both halves',
    'belong in the account.</p>',
    '<pre>',
    ' SELECT SOURCES',
    ' Frank, K. (2001) Indira: The Life of Indira Nehru Gandhi. HarperCollins.',
    ' Guha, R. (2007) India After Gandhi. Macmillan.',
    ' Malhotra, I. (1989) Indira Gandhi: A Personal and Political Biography.',
    ' [group note: check the Emergency chapters in Guha against Frank]',
    '</pre>',
    '<p>See also, in the ring, the electrician who brought down a one-party state',
    'by organising, at <a href="lech-walesa.geocities.ws">lech-walesa</a>, and, for',
    'the other woman prime minister of the era, the shrine at',
    '<a href="golda-meir.geocities.ws">golda-meir</a>.</p>',
    '<hr>',
    '<p><small>hits: 01677 · best viewed at 800x600 · corrections to the reading',
    'group, we meet fortnightly · last updated 4 Dec</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Lech Walesa: the student coursework ------------------------------------

const WALESA = P('lech-walesa.geocities.ws', 'L WALESA',
  'HIST 214 essay // Walesa and Solidarity', [
    '<!--bg:pol-reformers-->',
    '<h1>Walesa and Solidarity: the shipyard that shook a bloc</h1>',
    '<p><small>HIST 214: The Cold War in Eastern Europe. coursework essay, second',
    'submission (the first got a note to &ldquo;narrow the argument&rdquo;, so this',
    'time i stick to Walesa). bibliography at the end, formatted the way the module',
    'guide wants, mostly. — student no. redacted</small></p>',
    '<hr>',
    '<p><b>Introduction.</b> This essay argues that Lech Walesa (born 1943) matters',
    'less as a thinker than as a catalyst: an ordinary worker whose refusal, at the',
    'right moment, gave a shapeless discontent an organisation and a face. He was',
    'an electrician at the Lenin Shipyard in Gdansk on the Baltic coast of Poland,',
    'a country then ruled by a communist party inside the Soviet bloc.</p>',
    '<p><b>The strike.</b> In August 1980, after years of price rises and shortages',
    'and earlier strikes that had been put down with bloodshed, the Gdansk shipyard',
    'workers struck again. Walesa, who had been sacked for earlier agitation,',
    'climbed over the yard fence to join them and was pushed to the front. The',
    'strike spread along the coast and an Inter-Factory Strike Committee formed. The',
    'government, unable to crush it, negotiated.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/walesa-01.jpg" alt=""><span class="indie-cap">Lech Walesa (photo: Artur Andrzej, CC0)</span>',
    '<p><b>Solidarity.</b> The result was the Gdansk Agreement of 31 August 1980,',
    'which conceded the right to form free trade unions independent of the party.',
    'Out of it came <i>Solidarno&#347;&#263;</i>, Solidarity, the first free trade',
    'union in the Soviet bloc, with Walesa as its chairman. Within a year it had',
    'something close to ten million members. It was a trade union and it was also,',
    'plainly, a national movement against one-party rule wearing a union\'s coat.</p>',
    '<p class="fs-quote"><blockquote><p>&ldquo;The walls will fall sooner or later.',
    'They must fall.&rdquo;</p><p>&mdash; Lech Walesa, on the communist system,',
    'attributed, early 1980s</p></blockquote></p>',
    '<p><b>Martial law.</b> Moscow would not tolerate it. In December 1981 the',
    'Polish leader General Wojciech Jaruzelski declared martial law, banned',
    'Solidarity, and interned Walesa and thousands of others. For most of the',
    'decade the union survived underground, printing, organising, kept alive by its',
    'members and encouraged by the Polish pope, John Paul II, and by Western',
    'support. Walesa was released but watched.</p>',
    '<div class="fs-aside"><p><b>The Nobel.</b> In 1983 Walesa was awarded the Nobel',
    'Peace Prize. Fearing that if he travelled to collect it he would not be let',
    'back into Poland, he stayed home and his wife Danuta accepted it for him. He',
    'gave the prize money to Solidarity.</p></div>',
    '<p><b>The turn.</b> By 1989, with the Soviet system weakening under Gorbachev,',
    'the Polish government was forced to negotiate at the Round Table talks.',
    'Solidarity was legalised, part-free elections were held in June 1989, and it',
    'won almost everything it could. Poland got the bloc\'s first non-communist',
    'government since the 1940s. In 1990 Walesa was elected the first president of a',
    'free Poland by direct vote.</p>',
    '<p><b>Conclusion.</b> As president he proved a harder fit than as a striker;',
    'the qualities that make a man climb a fence are not the ones that make a smooth',
    'head of state, and his single term was rocky and he lost the next election. The',
    'essay\'s claim stands regardless: the shipyard electrician did not theorise the',
    'end of communism in Eastern Europe, he helped start it, and the year to date',
    'it from is 1980, not 1989.</p>',
    '<pre>',
    ' BIBLIOGRAPHY (HIST 214 format)',
    ' Ash, T. G. (1983) The Polish Revolution: Solidarity. Cape.',
    ' Walesa, L. (1987) A Way of Hope. Henry Holt. [his memoir, use with care]',
    ' Garton Ash, T. (1990) We the People. Granta. [the 1989 chapters]',
    ' *lecture notes wk 7, "the Gdansk Agreement", if the seminar counts',
    '</pre>',
    '<p>Cross-references for the module. The independence orator we did in week two',
    'is at <a href="jose-marti.geocities.ws">jose-marti</a>, and for the other end',
    'of the &ldquo;strong leader in a young democracy&rdquo; question, the summary',
    'at <a href="indira-gandhi.geocities.ws">indira-gandhi</a> is useful, mind the',
    'Emergency section.</p>',
    '<hr>',
    '<p><small>counter: 00546 · best viewed at 800x600 · under construction, adding',
    'the map of the Baltic strikes · last updated 18 Mar · please do not copy this',
    'for your own HIST 214 essay, i will know</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

// ---- Jose Marti: the rally / speech write-up --------------------------------

const MARTI = P('jose-marti.geocities.ws', 'JOSE MARTI',
  'THE APOSTLE // Jose Marti and Cuba Libre', [
    '<!--bg:pol-reformers-->',
    '<h1>THE APOSTLE OF CUBAN INDEPENDENCE</h1>',
    '<p><small>write-up of the talk our reading circle gave on Jose Marti for the',
    'anniversary of Dos Rios. we are not Cuban and we are not experts, we just',
    'think he is not read enough in English. all quotations checked twice. —',
    'the Wednesday circle</small></p>',
    '<hr>',
    '<p class="fs-epi"><i>Jose Marti (1853&ndash;1895): poet, essayist,',
    'journalist, organiser, and the figure Cubans of every later faction claim as',
    'the father of the nation. He is called <b>el Ap&oacute;stol</b>, the apostle,',
    'of Cuban independence.</i></p>',
    '<p>He was born in Havana in 1853, when Cuba was still a Spanish colony and',
    'slavery was still legal there. At sixteen he was imprisoned and then exiled for',
    'writing against Spanish rule, and exile became the shape of his life. He lived',
    'in Spain, in Mexico, in Guatemala, in Venezuela, and for most of his last',
    'fifteen years in New York, writing for newspapers across Latin America and',
    'earning his living by the pen.</p>',
    '<p>Two things have to be held together to understand him. He was one of the',
    'great writers of the Spanish language, a founder of <i>modernismo</i>, whose',
    'simple verses everyone now knows because some of them became the song',
    '<i>Guantanamera</i>. And he was a working revolutionary who spent years doing',
    'the unglamorous labour of organising: raising money, uniting quarrelsome exile',
    'factions, founding the Cuban Revolutionary Party in 1892 to bring the war',
    'about.</p>',
    '<img class="indie-pic" src="assets/media/web/pol/marti-01.jpg" alt=""><span class="indie-cap">Jose Marti (CC BY-SA 4.0)</span>',
    '<p><b>&ldquo;Our America&rdquo;.</b> His most famous essay, <i>Nuestra',
    'Am&eacute;rica</i> (1891), written from the United States, warned the nations',
    'of Latin America to trust their own roots and their own mixed peoples rather',
    'than importing foreign models, and warned, with striking foresight, of the',
    'appetite of the powerful neighbour to the north. He knew the United States from',
    'the inside, admired much in it, and was not deceived by it.</p>',
    '<p class="fs-quote"><blockquote><p>&ldquo;I have lived inside the monster and',
    'know its entrails; and my sling is that of David.&rdquo;</p><p>&mdash; Jose',
    'Marti, unfinished last letter to Manuel Mercado, 18 May 1895</p></blockquote></p>',
    '<div class="fs-aside"><p><b>Dos Rios.</b> When the war of independence finally',
    'began in 1895, Marti did not stay safe in New York. He sailed to Cuba to join',
    'the fighting alongside the veteran generals Maximo Gomez and Antonio Maceo. On',
    '19 May 1895, at a place called Dos Rios, he rode into a Spanish position and',
    'was killed almost at once. He was forty-two, and had spent his life preparing a',
    'war he did not live to see won.</p></div>',
    '<p class="fs-pull"><b>&ldquo;A sincere man am I / From the land where palm',
    'trees grow.&rdquo;</b> the opening of the <i>Versos sencillos</i> (1891), the',
    'lines that the song took. plain words, which he preferred.</p>',
    '<p>Cuba became independent of Spain in 1898, though under heavy American',
    'influence, the very thing Marti had feared. That his name was later claimed by',
    'the revolution of 1959 and by its opponents alike tells you how large he',
    'looms; a nation argues through its founders. We ended the talk by reading the',
    '<i>Versos sencillos</i> aloud, which is the right way to leave him.</p>',
    '<p>Neighbours in the ring worth a visit. The abolitionist orator of the country',
    'to the north, whose late years overlapped Marti\'s exile there, is at',
    '<a href="frederick-douglass.geocities.ws">frederick-douglass</a>. And for a',
    'twentieth-century case of a worker who organised a nation into being, see',
    '<a href="lech-walesa.geocities.ws">lech-walesa</a>.</p>',
    '<hr>',
    '<p><small>counter: 00733 · best viewed at 800x600 · guestbook welcomes',
    'corrections, especially from readers who know the Spanish better than we do ·',
    'last updated 19 May · the Wednesday circle</small></p>',
    '<p><small>[ <a href="statesmen-ring.geocities.ws">Statespeople Ring</a> ]</small></p>',
  ]);

export const POL_F = [KING, DOUGLASS, MEIR, INDIRA, WALESA, MARTI];
