// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — the study of myth.
//
// Pages a folklore reader and a comparative-mythology enthusiast made in the
// late 1990s: a showpiece shrine to Campbell and the monomyth, a page on
// Frazer and The Golden Bough, and close readings of three great motifs (the
// trickster, the creation myth, the flood) plus the fairy tale and its
// collectors. The scholars, texts and dates are real; the enthusiasm, the
// wonky bibliographies and the webring furniture are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Campbell: the monomyth showpiece ---------------------------------------

const HERO = P('the-hero-with-a-thousand-faces.geocities.ws', 'HERO 1000 FACES',
  'THE HERO WITH A THOUSAND FACES // the monomyth (Campbell)', [
    '<!--bg:myth-study-->',
    '<h1>THE HERO WITH A THOUSAND FACES</h1>',
    '<p><small>a shrine to Joseph Campbell (1904&ndash;1987) and the idea that all',
    'the great stories are secretly one story. put together by a comparative-myth',
    'obsessive who has read the 1949 book more times than is healthy. corrections',
    'and quibbles welcome, i argue about this for fun. &mdash; Mara</small></p>',
    '<hr>',
    '<p class="fs-epi">&ldquo;A hero ventures forth from the world of common day into a',
    'region of supernatural wonder.&rdquo; &mdash; Joseph Campbell, 1949</p>',
    '<p>The book is <i>The Hero with a Thousand Faces</i> (1949). The big claim is',
    'that under the thousand hero tales of the world there is ONE pattern, and',
    'Campbell borrowed a word from James Joyce and called it the MONOMYTH. Read',
    'enough myths side by side, he said, and the same shape keeps surfacing: a',
    'departure, an initiation, a return. The names change, the shape holds.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;The standard path of the mythological',
    'adventure of the hero is a magnification of the formula represented in the',
    'rites of passage: separation, initiation, return.&rdquo;</p></blockquote>',
    '<p>He got the three-part skeleton partly from Arnold van Gennep on rites of',
    'passage, and a great deal of the depth reading from Carl Jung, whose',
    'archetypes and collective unconscious sit under the whole thing. That is worth',
    'saying up front, because people talk as if Campbell invented the pattern. He',
    'gathered it, compared it, and gave it a memorable name.</p>',
    '<h2>the stages of the journey</h2>',
    '<p>Here is the shape as he laid it out, boiled down so you can carry it in your',
    'head. The scholars call it the hero\'s journey now, and screenwriters call it',
    'gold.</p>',
    '<pre>',
    'THE HERO\'S JOURNEY  (Campbell 1949, in brief)',
    '===========================================',
    '',
    ' I.  DEPARTURE',
    '     1. The Call to Adventure ....... the ordinary world is disturbed',
    '     2. Refusal of the Call ......... fear, reluctance, first no',
    '     3. Supernatural Aid ........... the mentor, the gift, the talisman',
    '     4. Crossing the Threshold ..... the step past the known border',
    '     5. The Belly of the Whale ..... swallowed; the point of no return',
    '',
    'II.  INITIATION',
    '     6. The Road of Trials ......... the tests, the ordeals, the failures',
    '     7. Meeting / temptation ....... allies, the goddess, the tempter',
    '     8. Atonement with the Father .. the confrontation at the centre',
    '     9. Apotheosis / the Boon ...... the reward, the elixir, the truth won',
    '',
    'III. RETURN',
    '    10. The Refusal of the Return .. why go back?',
    '    11. The Crossing / Master ...... the flight home, master of two worlds',
    '    12. Freedom to Live ........... the boon brought back to the people',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/myth/golden-bough-01.jpg" alt=""><span class="indie-cap">The Golden Bough, J. M. W. Turner (Tate, public domain)</span>',
    '<p>Notice the ring shape. The hero ends where he began but is not who he was,',
    'and the community gets something back: fire, wisdom, medicine, a law. That',
    'last beat, the return with the boon, is the one adaptations always cut and the',
    'one Campbell cared about most.</p>',
    '<blockquote class="fs-pull"><p>&ldquo;Follow your bliss.&rdquo;</p></blockquote>',
    '<p>That line is the late-Campbell slogan, from the Bill Moyers television',
    'conversations <i>The Power of Myth</i> (1988). It made him famous to a huge',
    'audience and it also, if we are candid, flattened him a bit. The 1949 book is',
    'darker and stranger than the slogan suggests.</p>',
    '<div class="fs-aside"><p><b>DID YOU KNOW?</b> George Lucas has said Campbell',
    'shaped the writing of <i>Star Wars</i>, and later called Campbell his',
    '&ldquo;Yoda&rdquo;. From there the monomyth marched into the film schools.',
    'Christopher Vogler turned it into a studio memo, <i>The Writer\'s Journey</i>,',
    'and now half the blockbusters you know are the twelve stages wearing a new',
    'costume.</p></div>',
    '<h2>the comparative method</h2>',
    '<p>Campbell\'s way of working is the old comparative one: lay the traditions of',
    'the world beside each other, Greek and Buddhist and Aboriginal and biblical,',
    'and look for the deep pattern rather than the surface difference. It is the',
    'same instinct that drives Frazer over at',
    '<a href="the-golden-bough.geocities.ws">the-golden-bough</a>, the vast sweep',
    'that reads a thousand cultures for one recurring figure. When it works it is',
    'thrilling. When it fails it fails the same way, and here come the critics.</p>',
    '<h2>&ldquo;too neat&rdquo;: the case against</h2>',
    '<p>Plenty of folklorists think the monomyth is too tidy to be true. The charge,',
    'fairly put:</p>',
    '<p>ONE. It is elastic to the point of unfalsifiability. If every story can be',
    'bent to fit twelve stages, the pattern explains everything and therefore',
    'nothing. You can find a &ldquo;threshold&rdquo; in a shopping list if you want',
    'one badly enough.</p>',
    '<p>TWO. It smooths away exactly what makes a tradition itself. Reading the',
    'Popol Vuh and the Odyssey as the same story loses the K\'iche\' Maya world and',
    'the Greek one both.</p>',
    '<p>THREE. The hero is a man, the journey is a man\'s, and the feminine turns up',
    'mostly as goddess or temptation, something to be met rather than someone who',
    'travels. Later scholars have written the heroine\'s journey partly to answer',
    'this.</p>',
    '<p>FOUR. It leans hard on Jung, and if you do not buy a universal collective',
    'unconscious, a lot of the machinery is left hanging in the air.</p>',
    '<img class="indie-pic" src="assets/media/web/myth/fairy-tale-01.jpg" alt=""><span class="indie-cap">Little Red Riding Hood, Arthur Rackham (public domain)</span>',
    '<p>My own view, for what a fan page is worth: keep the pattern as a lens and',
    'never as a law. It is a wonderful way to notice what stories share and a',
    'terrible way to decide what they mean. Use it to open a tale, not to close it.',
    'And when you have had enough of neat archetypes, go and read a proper',
    'trickster, who breaks every stage on the chart, at',
    '<a href="the-trickster.geocities.ws">the-trickster</a>.</p>',
    '<hr>',
    '<p><small>a webring for myth-nuts, keep it going.</small></p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
    '<p><small>counter: 03571 · best viewed in Netscape at 800x600 · this corner of',
    'the web is under eternal construction · last updated 14 Oct · &mdash; Mara,',
    'comparative mythology since a very cheap paperback in 1994</small></p>',
  ]);

// ---- Frazer: the founding, flawed anthropology ------------------------------

const BOUGH = P('the-golden-bough.geocities.ws', 'GOLDEN BOUGH',
  'THE GOLDEN BOUGH // Frazer and the dying god', [
    '<!--bg:myth-study-->',
    '<h1>THE GOLDEN BOUGH</h1>',
    '<p><small>notes on Sir James George Frazer (1854&ndash;1941) and the great',
    'strange book that half the poets of this century read and half the',
    'anthropologists now disown. kept by a member of the folklore reading circle.',
    '&mdash; W. H.</small></p>',
    '<hr>',
    '<p><i>The Golden Bough: A Study in Magic and Religion</i> (first edition 1890,',
    'two volumes; the famous third edition ran to twelve). Frazer was a classicist',
    'at Cambridge who almost never left his study and read the whole world in it,',
    'through the reports of missionaries and travellers and colonial officers. That',
    'is both the method and the flaw, and we will come to the flaw.</p>',
    '<h2>the priest at Nemi</h2>',
    '<p>The book opens with a riddle. At the sacred grove of Diana at Nemi, by the',
    'lake in the Alban hills, there was a priest called the King of the Wood, and he',
    'held his office by a grim rule. He had killed the priest before him, and he',
    'would hold the post until a challenger, a runaway slave who could break a bough',
    'from a certain tree, killed him in turn. Why? To answer that one custom Frazer',
    'goes round the entire world and does not come back for twelve volumes.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;The priest who slew the slayer, / And',
    'shall himself be slain.&rdquo; &mdash; Macaulay, the lines Frazer took for his',
    'theme</p></blockquote>',
    '<p>His answer runs through the figure of the DYING-AND-RISING GOD. The king',
    'embodies the fertility of the land, so his strength is the land\'s strength;',
    'when he weakens the land weakens, so he must be killed while still vigorous and',
    'his power passed on unspent. Frazer gathered Osiris, Adonis, Attis, Tammuz and',
    'more under this pattern of the god who dies and returns with the turning year,',
    'the death and rebirth that mirrors the seasons and the grain.</p>',
    '<div class="fs-aside"><p><b>A NOTE ON REACH.</b> Beyond anthropology, the book',
    'soaked into literature. T. S. Eliot names it in the notes to <i>The Waste',
    'Land</i>; you can feel it in Yeats, in Lawrence, in a whole generation reaching',
    'for the dying god and the fertility rite. Whatever the scholars decided later,',
    'as a piece of imaginative furniture <i>The Golden Bough</i> furnished the',
    'century.</p></div>',
    '<img class="indie-pic" src="assets/media/web/myth/golden-bough-01.jpg" alt=""><span class="indie-cap">The Golden Bough, J. M. W. Turner (Tate, public domain)</span>',
    '<h2>magic, religion, science</h2>',
    '<p>Frazer\'s other big idea is a ladder of three stages the human mind is',
    'supposed to climb. Sympathetic magic first, in two flavours worth knowing:</p>',
    '<pre>',
    'FRAZER\'S SCHEME OF MIND (as he told it)',
    '======================================',
    'MAGIC     the world runs on hidden laws you can work',
    '            . homoeopathic / imitative : like produces like',
    '                (stick the doll, wound the man)',
    '            . contagious : things once in contact stay linked',
    '                (burn the hair, burn the head it grew on)',
    'RELIGION  the laws fail, so you petition persons: pray, appease',
    'SCIENCE   back to hidden laws, but this time really tested',
    '',
    '  magic  -->  religion  -->  science   (his arrow, not ours)',
    '</pre>',
    '<p>Notice that magic and science are cousins in his scheme, both bets that the',
    'world is law-bound, with religion as the humble middle that admits it cannot',
    'compel the powers and must ask them instead. It is a tidy story and, like most',
    'tidy stories about the whole of humanity, it is wrong in the tidy parts.</p>',
    '<h2>founding, and flawed</h2>',
    '<p>Let us be plain about the trouble. The armchair method meant Frazer trusted',
    'sources he could not check and tore customs out of the living contexts that',
    'gave them sense. The three-stage ladder is a Victorian progress myth dressed as',
    'science, with his own culture conveniently at the top. The comparisons flatten',
    'real differences between peoples into one big argument. Later anthropology, the',
    'fieldworkers who actually went and lived somewhere, largely set him aside.</p>',
    '<p>And yet the founding part is real too. He made the comparative study of myth',
    'and ritual a serious pursuit, he asked why a custom exists rather than merely',
    'cataloguing it, and he wrote so well that people outside the field actually',
    'read the thing. Campbell over at',
    '<a href="the-hero-with-a-thousand-faces.geocities.ws">the-hero-with-a-thousand-faces</a>',
    'is doing a late, tidier version of the same comparative move, and runs into',
    'some of the same objections. For the recurring story-types Frazer loved to',
    'line up, see the creation tales at',
    '<a href="the-creation-myth.geocities.ws">the-creation-myth</a>.</p>',
    '<hr>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
    '<p><small>hits: 01884 · best viewed at 800x600 · folklore reading circle,',
    'meets the first Thursday · page last tended 2 Sep · read the abridged one',
    'volume first, then decide if you want all twelve</small></p>',
  ]);

// ---- The trickster: a motif close reading -----------------------------------

const TRICKSTER = P('the-trickster.geocities.ws', 'TRICKSTER',
  'THE TRICKSTER // the one who crosses the line', [
    '<!--bg:myth-study-->',
    '<h1>THE TRICKSTER</h1>',
    '<p><small>a close reading of the trickster figure, gathered by someone who',
    'started with one Anansi story as a child and never stopped collecting. these',
    'are living traditions in many cases, so i try to say &ldquo;in the',
    'tradition&rdquo; and &ldquo;the story goes&rdquo; and mean it. &mdash; T. O.</small></p>',
    '<hr>',
    '<p>Every tradition seems to keep one, the figure who will not stay in his',
    'place. The trickster lies, steals, shapeshifts, breaks the rule, plays the',
    'fool and turns out to have handed the people something they could not have got',
    'any other way. He is the BOUNDARY-CROSSER: between gods and mortals, order and',
    'chaos, the sacred and the crude, the living and the dead.</p>',
    '<div class="fs-aside"><p><b>A CROWDED FIELD.</b> A rough gathering, and each',
    'belongs first to its own people and its own stories:</p>',
    '<p>LOKI, in the Norse tradition, the shape-changer among the Aesir who helps',
    'and harms by turns. ANANSI the spider, of the Akan of West Africa, keeper of',
    'the stories, who wins by wit and carries his tales across the Atlantic. COYOTE,',
    'across many Native North American traditions, creator and fool at once, who',
    'brings fire and, in some tellings, brings death. HERMES of the Greeks, the',
    'thief on the first day of his life, guide of souls and god of the crossroads',
    'and the road. And SUN WUKONG, the Monkey King of <i>Journey to the West</i>,',
    'who fights heaven itself before he is turned to the pilgrimage.</p></div>',
    '<p>Set them side by side and the family resemblance is hard to miss, though a',
    'good reader keeps the differences in view as well.</p>',
    '<blockquote class="fs-pull"><p>He is the one who gets caught by his own',
    'cleverness, and the one who gets away.</p></blockquote>',
    '',
    '<h2>the culture-bringer</h2>',
    '<p>Here is the turn that makes the trickster more than a clown. Again and',
    'again the thing a people cannot live without arrives by theft or trick, not by',
    'gift. Fire is stolen. The stories are bought from the sky-god by a bargain',
    'nobody thought could be met. The sun is snared, the tides are fixed, the shape',
    'of death itself is set by some careless or cunning act at the beginning. The',
    'trickster is a CULTURE-BRINGER: the disorder he carries is also the source of',
    'the order that follows.</p>',
    '<p>That is the paradox worth sitting with. The figure who breaks the boundary',
    'is the same figure who first draws it. The rule becomes visible in the moment',
    'it is broken, and the community learns what it values by watching him flout it.',
    'He is disorder that renews, the crack that lets the new thing in.</p>',
    '<h2>reading him</h2>',
    '<p>Jung called the trickster an archetype and read him as a stage of the',
    'psyche, the shadow before it is grown up. The anthropologist Paul Radin, in',
    '<i>The Trickster</i> (1956), read the Winnebago cycle as a portrait of mind',
    'becoming aware of itself. Lewis Hyde\'s later book <i>Trickster Makes This',
    'World</i> puts him where the traffic is, at every crossroads and threshold and',
    'market and border. Take what is useful and remember the warning from the',
    'monomyth page next door at',
    '<a href="the-hero-with-a-thousand-faces.geocities.ws">the-hero-with-a-thousand-faces</a>:',
    'a pattern that fits every figure risks explaining none of them. The trickster',
    'is precisely the character who will not sit still for a twelve-stage chart.</p>',
    '<p>He turns up in the folk tale too, as the clever youngest, the small animal',
    'who outwits the big one, the tailor who kills seven at a blow. For that end of',
    'him, and the people who collected the tales, see',
    '<a href="the-fairy-tale.geocities.ws">the-fairy-tale</a>.</p>',
    '<hr>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
    '<p><small>counter: 02260 · best viewed at 800x600 · under construction, like',
    'the trickster likes it · last updated 21 Jul · handle T. O., folklore society</small></p>',
  ]);

// ---- The creation myth: a motif close reading -------------------------------

const CREATION = P('the-creation-myth.geocities.ws', 'CREATION MYTH',
  'THE CREATION MYTH // how the world got started', [
    '<!--bg:myth-study-->',
    '<h1>THE CREATION MYTH</h1>',
    '<p><small>coursework page. FOLK 214 &mdash; Comparative Cosmogony. a survey of',
    'the ways traditions tell the beginning of things. living scriptures here are',
    'treated as living, and the retellings are given as the tradition gives them.',
    '&mdash; student no. withheld, but you can call me R.</small></p>',
    '<hr>',
    '<p>Ask any tradition where the world came from and you get a story, and the',
    'stories fall, more or less, into a handful of TYPES. The folklorists have',
    'names for them. Here is the working list for this module, with the great',
    'examples we read.</p>',
    '<pre>',
    'FOLK 214 : TYPES OF CREATION STORY',
    '==================================',
    'FROM NOTHING (creatio ex nihilo)',
    '    a maker speaks or wills, and there is world where there was none.',
    '    e.g. Genesis 1, in the Hebrew tradition: "let there be light".',
    'FROM CHAOS (the ordering)',
    '    stuff already churns, formless; creation is the sorting of it.',
    '    e.g. the Enuma Elish of Babylon; Greek Chaos before the gods.',
    'FROM A COSMIC EGG',
    '    the whole cosmos hatches, or splits, from a single egg.',
    '    e.g. tellings in the Indian, Chinese and Finnish traditions.',
    'THE EARTH-DIVER',
    '    water everywhere; an animal dives to bring up a little mud',
    '    that grows into the earth. widespread across North America',
    '    and northern Eurasia.',
    'FROM A SACRIFICED BODY (world-parent split)',
    '    a primal being is divided; sky from earth, and the world',
    '    made from the parts. e.g. Tiamat in the Enuma Elish; Ymir',
    '    in the Norse tradition.',
    'FROM EMERGENCE',
    '    the people climb up into this world through earlier worlds',
    '    below. e.g. in several Puebloan traditions of the Southwest.',
    '</pre>',
    '<h2>three read side by side</h2>',
    '<p>The <b>Enuma Elish</b>, the Babylonian creation, is a from-chaos and a',
    'world-parent story at once. In the tradition the young god Marduk defeats the',
    'salt-water goddess Tiamat and makes the sky and the earth from her divided',
    'body, and the ordering of the cosmos doubles as the rise of Babylon\'s own',
    'god. For the wider pantheon behind it, our set text points across to the',
    'Mesopotamian material catalogued off this ring.</p>',
    '',
    '<p><b>Genesis 1</b>, in the Hebrew scripture, is the classic from-nothing',
    'telling in the West, an ordered week of speech in which each day sorts one',
    'more part of the world from the deep, and it is worth noting that the Hebrew',
    'opens over a watery formlessness too, so the ordering motif is not far off.</p>',
    '<p>The <b>Popol Vuh</b> of the K\'iche\' Maya tells of makers who try more than',
    'once. The story goes that people of mud fail and people of wood fail, and only',
    'people of maize can hold thought and gratitude, so the staple crop and the',
    'human being are made of the same substance. It is a living heritage of the',
    'K\'iche\' people, not a museum piece, and it rewards being read whole.</p>',
    '<blockquote class="fs-pull"><p>Almost every cosmogony begins not with nothing',
    'but with water, and calls creation an act of sorting.</p></blockquote>',
    '<p>That is the pattern the module keeps circling. The ordering of the world is',
    'the deep motif under the surface variety, chaos or deep or egg or flood pushed',
    'back so that a shape can stand. Frazer would have lined these up in a heartbeat;',
    'see the comparative habit, and its dangers, at',
    '<a href="the-golden-bough.geocities.ws">the-golden-bough</a>. And the water',
    'that so many creations start in has a dark cousin, the water that ends a world',
    'and starts it again, over at <a href="the-flood-myth.geocities.ws">the-flood-myth</a>.</p>',
    '<hr>',
    '<p><b>Bibliography (as handed in, marker\'s red pen and all)</b></p>',
    '<p>Eliade, M. &mdash; <i>The Myth of the Eternal Return</i> (the cyclical bits).<br>',
    'Leeming, D. &mdash; <i>A Dictionary of Creation Myths</i> (used HEAVILY, sorry).<br>',
    'Sproul, B. &mdash; <i>Primal Myths</i>, the big anthology of texts.<br>',
    'the Popol Vuh, in the Tedlock translation, which the seminar preferred.<br>',
    'lecture 4 handout (the types list above is basically lecture 4).</p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
    '<p><small>counter: 00937 · best viewed at 800x600 · FOLK 214, term 2 · page put',
    'up 30 Nov the night before it was due · under construction until i get the mark</small></p>',
  ]);

// ---- The flood myth: a motif close reading ----------------------------------

const FLOOD = P('the-flood-myth.geocities.ws', 'FLOOD MYTH',
  'THE FLOOD MYTH // the water that starts the world over', [
    '<!--bg:myth-study-->',
    '<h1>THE FLOOD MYTH</h1>',
    '<p><small>a close reading of the deluge story, which turns up in more places',
    'than almost any other. put together by a member of the comparative-myth',
    'reading group. retellings are given as the tradition gives them. &mdash; D. K.</small></p>',
    '<hr>',
    '<p>A great water comes and washes the world away, and a few are saved to begin',
    'it again. The shape is startlingly steady across cultures: warning, vessel,',
    'survivors, the waters rise, the waters fall, a sign, a fresh start. Here are',
    'four of the most famous, each in its own tradition.</p>',
    '<p class="fs-epi">&ldquo;All that was light was turned into darkness. &hellip; Six',
    'days and seven nights the wind blew, the flood came.&rdquo; &mdash; from the',
    'Standard Babylonian Epic of Gilgamesh, tablet XI</p>',
    '<p><b>Utnapishtim</b>, in the Mesopotamian tradition, is the oldest written',
    'flood we have. In the Epic of Gilgamesh the god Ea warns him, he builds a great',
    'boat, he takes his family and the craftsmen and the animals aboard, the flood',
    'drowns the world, the boat grounds on a mountain, and he sends out birds, a',
    'dove and a swallow and a raven, to find dry land. He is granted immortality',
    'after. Anyone who knows the next story will feel a jolt reading this one.</p>',
    '<p><b>Noah</b>, in the Hebrew scripture, is the flood the Western reader knows',
    'best: the ark by measured cubits, the pairs of every living thing, the forty',
    'days, the raven and then the dove that returns with the olive leaf, the',
    'grounding on Ararat, the covenant sealed with a rainbow. The kinship with the',
    'Mesopotamian telling is close enough that scholars have argued about it for a',
    'century and a half.</p>',
    '',
    '<p><b>Deucalion</b>, in the Greek tradition, is warned by his father Prometheus',
    'when Zeus resolves to drown a corrupt age of men. He and his wife Pyrrha ride',
    'out the flood in a chest, come to rest on a mountain, and afterwards, the story',
    'goes, remake humankind by casting stones behind them, which become people.</p>',
    '<p><b>Manu</b>, in the Hindu tradition, is warned by a small fish he had spared,',
    'which grows vast and is understood as a form of Vishnu. The fish tows Manu\'s',
    'ship through the flood, tied by a rope to its horn, and brings him safe to the',
    'mountain, and from him the human race begins again.</p>',
    '<div class="fs-aside"><p><b>THE COMMON KIT.</b> Read enough of them and the',
    'furniture repeats: a divine warning to one righteous or favoured person, a',
    'vessel built to a plan, a remnant of humans and animals, a mountain landfall,',
    'birds sent to test for land, a sacrifice or a sign at the end, and a promise',
    'that it will not happen so again.</p></div>',
    '<h2>diffusion or archetype?</h2>',
    '<p>So why is the story everywhere? Two big answers, and the argument between',
    'them is the real interest of the topic.</p>',
    '<p><b>DIFFUSION.</b> The story spread. The Mesopotamian flood is demonstrably',
    'older than the Hebrew one and the two share too much detail for coincidence, so',
    'at least in the Near East the tale travelled from telling to telling, carried',
    'along trade routes and down the generations. On this view the resemblances are',
    'a family tree, not a coincidence.</p>',
    '<p><b>ARCHETYPE.</b> The story recurs because the human situation recurs. Rivers',
    'flood, memories of real inundations settle into story, and the deep wish for a',
    'clean slate and a second beginning finds the same shape wherever people tell',
    'tales. On this view the flood is something the mind reaches for, not only',
    'something a caravan carried. Campbell over at',
    '<a href="the-hero-with-a-thousand-faces.geocities.ws">the-hero-with-a-thousand-faces</a>',
    'would take the archetype side without blinking; a careful folklorist keeps both',
    'answers on the table and asks which one fits which case.</p>',
    '<p>The flood sits at the far end of the creation story, the water that unmakes',
    'so a remaking can follow. For the making itself, and the deep-water starts so',
    'many cosmogonies share, see <a href="the-creation-myth.geocities.ws">the-creation-myth</a>.',
    'For the small clever survivor who so often reshapes the world after, see the',
    'boundary-crosser at <a href="the-fairy-tale.geocities.ws">the-fairy-tale</a>,',
    'where the folk telling keeps him alive.</p>',
    '<hr>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
    '<p><small>hits: 01402 · best viewed in Netscape at 800x600 · comparative-myth',
    'reading group · last updated 8 Aug · corrections to D. K., who will defend the',
    'diffusion case to the last</small></p>',
  ]);

// ---- The fairy tale: an ORG / idea page --------------------------------------

const FAIRYTALE = P('the-fairy-tale.geocities.ws', 'FAIRY TALE',
  'THE FAIRY TALE // the folk tale, collected and counted', [
    '<!--bg:myth-study-->',
    '<h1>THE FAIRY TALE</h1>',
    '<p><small>the pages of the Folk Tale Study Circle. we are amateurs who love the',
    'old stories and the strange scholarship that grew up around them. new readers',
    'welcome; there is a reading list at the foot. &mdash; the circle secretary</small></p>',
    '<hr>',
    '<p>The fairy tale is not the same thing as myth. Myth tells of gods and the',
    'making of the world; the fairy tale, the Marchen, is the humbler cousin, the',
    'tale of the ordinary person and the youngest child and the talking animal, told',
    'by firesides long before anyone wrote it down. This page is about how it was',
    'collected, and how scholars learned to count it.</p>',
    '<h2>the collectors</h2>',
    '<p><b>Charles Perrault</b>, in France, published <i>Histoires ou contes du',
    'temps passe</i> in 1697, the book that gave the printed page its',
    '<i>Cinderella</i>, its <i>Sleeping Beauty</i>, its <i>Puss in Boots</i> and',
    '<i>Little Red Riding Hood</i>, polished for a court audience and fitted with a',
    'rhyming moral.</p>',
    '<p><b>Jacob and Wilhelm Grimm</b>, in Germany, brought out the',
    '<i>Kinder- und Hausmarchen</i> from 1812, and revised it across their lives.',
    'The Brothers Grimm meant it as a work of scholarship, a rescue of the folk',
    'voice, though Wilhelm kept smoothing and moralising the tales edition by',
    'edition, so the &ldquo;authentic&rdquo; Grimm is itself a made thing. From them',
    'come the household versions of <i>Hansel and Gretel</i>, <i>Rumpelstiltskin</i>,',
    '<i>Snow White</i> and the rest.</p>',
    '<blockquote class="fs-quote"><p>&ldquo;There was once a poor man who had an only',
    'son.&rdquo; &mdash; the way a hundred of them begin</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/myth/fairy-tale-01.jpg" alt=""><span class="indie-cap">Little Red Riding Hood, Arthur Rackham (public domain)</span>',
    '<h2>counting the tales: Aarne-Thompson-Uther</h2>',
    '<p>Here is where the folklorists get systematic. Antti Aarne, a Finn, built an',
    'index of tale TYPES in 1910; Stith Thompson, an American, translated and',
    'enlarged it (1928, 1961); and Hans-Jorg Uther revised it again in 2004. Hence',
    'the ATU number, the catalogue mark you will see everywhere in the scholarship.',
    'A type is a whole plot that recurs across languages; a motif is a single',
    'building block, and Thompson indexed those too, in six fat volumes.</p>',
    '<pre>',
    'THE ATU INDEX, IN BROAD BANDS (Aarne-Thompson-Uther)',
    '====================================================',
    '   1 - 299   Animal Tales        (the fox, the wolf, the clever hare)',
    ' 300 - 749   Tales of Magic      (the true "fairy tales": ATU 510 is',
    '                                   the Cinderella type)',
    ' 750 - 849   Religious Tales',
    ' 850 -999    Realistic Tales     (novelle: cleverness, riddles, luck)',
    '1000 -1199   Tales of the Stupid Ogre / Giant',
    '1200 -1999   Anecdotes and Jokes',
    '2000 -2399   Formula Tales       (the endless, the cumulative)',
    '</pre>',
    '<div class="fs-aside"><p><b>DID YOU KNOW?</b> Because the index counts types',
    'across languages, you can say that &ldquo;Cinderella&rdquo; (ATU 510A) is told',
    'from Europe to China, and one ninth-century Chinese telling, the tale of Ye',
    'Xian, is older than any European version on paper. The slipper travels.</p></div>',
    '<h2>Propp and the morphology</h2>',
    '<p>The other great tool came from Russia. Vladimir Propp, in <i>Morphology of',
    'the Folktale</i> (1928), took a hundred Russian magic tales and found that',
    'beneath the endless variety of persons the FUNCTIONS were few and always fell',
    'in the same order. A villain does harm, a hero leaves home, a helper appears, a',
    'task is set, the villain is beaten, the hero is married or crowned. He counted',
    'thirty-one such functions and seven roles. Not every tale uses all of them, but',
    'when they appear they appear in sequence.</p>',
    '<blockquote class="fs-pull"><p>The characters change; the functions do not.</p></blockquote>',
    '<p>If that reminds you of the hero\'s journey, you are right to notice it. Propp',
    'is the rigorous, tale-counting ancestor of the looser monomyth over at',
    '<a href="the-hero-with-a-thousand-faces.geocities.ws">the-hero-with-a-thousand-faces</a>.',
    'Campbell chased one universal story; Propp mapped the moving parts of one',
    'tradition and refused to leave the data.</p>',
    '<h2>the oral tradition and the printed page</h2>',
    '<p>One last tension the circle keeps returning to. These tales lived for',
    'centuries in the mouth, changing with every teller and every telling, fitted to',
    'the room and the night. The moment they were written down they were fixed, and',
    'the fixing was also a loss, because a living variant became a single',
    'authorised text. Perrault and the Grimms saved the tales and, in saving them,',
    'stopped them moving. The clever survivor who runs through so many of them is',
    'the same trickster the myths keep; follow him to',
    '<a href="the-trickster.geocities.ws">the-trickster</a>. And for the deluge that',
    'so many traditions set at the start of their own story, see',
    '<a href="the-flood-myth.geocities.ws">the-flood-myth</a>.</p>',
    '<hr>',
    '<p><b>Reading list (the circle\'s standbys)</b></p>',
    '<p>Grimm, J. &amp; W. &mdash; the tales, in a translation that keeps the darkness in.<br>',
    'Perrault, C. &mdash; the 1697 stories, for the version before the Grimms.<br>',
    'Propp, V. &mdash; <i>Morphology of the Folktale</i> (short, hard, worth it).<br>',
    'Zipes, J. &mdash; on the tales as social history, and who they were really for.<br>',
    'Warner, M. &mdash; <i>From the Beast to the Blonde</i>, on the tellers, mostly women.</p>',
    '<p><small>[ <a href="mythology-ring.geocities.ws">Mythology Ring</a> ]</small></p>',
    '<p><small>visitors: 01120 · best viewed at 800x600 · Folk Tale Study Circle,',
    'second Monday, upstairs at the Institute · last updated 5 Dec · all welcome,',
    'bring a tale</small></p>',
  ]);

export const MYTH_F = [HERO, BOUGH, TRICKSTER, CREATION, FLOOD, FAIRYTALE];
