// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH F — the laboratory & the institution.
//
// The pages a science enthusiast made in the late 1990s about the machinery of
// science itself rather than the scientists: a Fellow's tribute to the Royal
// Society; a lab technician's tour of the research bench; a sixth-form teacher's
// handout on method; a prize-watcher's page on the Nobel and its omissions; a
// PhD student griping about peer review; a museum volunteer on the specimen.
// The institutions, dates and mottoes are real; the enthusiasm is the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- The Royal Society: the Fellow's tribute (SHOWPIECE) --------------------

const ROYAL_SOCIETY = P('the-royal-society.geocities.ws', 'ROYAL SOCIETY',
  'THE ROYAL SOCIETY // take nobody\'s word for it', [
    '<!--bg:sci-institutions-->',
    '<h1>THE ROYAL SOCIETY</h1>',
    '<p class="fs-epi"><i>Nullius in verba</i> — take nobody\'s word for it.<br>',
    '— the motto of the Royal Society, adopted 1663</p>',
    '<p><small>a tribute page kept by a retired chemistry master who once, ONCE,',
    'gave a talk in a room where the Fellows meet, and has not stopped going on',
    'about it since. corrections welcome, but check your dates first. — R.H.</small></p>',
    '<hr>',
    '<p>The Royal Society of London for Improving Natural Knowledge is the oldest',
    'national scientific society in continuous existence. It was founded on 28',
    'November 1660, when a dozen men, Christopher Wren among them, met after a',
    'lecture at Gresham College and resolved to set up a college for the promoting',
    'of experimental learning. Charles II granted the Royal Charter in 1662. That',
    'is the whole beginning: a lecture, a resolution, a charter, and a motto that',
    'told the members to trust experiment and not authority.</p>',
    '<p class="fs-pull">Take nobody\'s word for it. Not Aristotle\'s, not the',
    'King\'s, not your own. Show me.</p>',
    '<p>That motto is the hinge of the whole thing. <i>Nullius in verba</i> is a',
    'tag from Horace, and the Fellows read it as a standing instruction to settle',
    'questions by appeal to experiment rather than to the say-so of any authority,',
    'however grand. In an age that still argued from the ancients, this was the',
    'radical move: put the matter to the test in front of witnesses, and write',
    'down what actually happened.</p>',
    '<img class="indie-pic" src="assets/media/web/sci/royal-society-01.jpg" alt=""><span class="indie-cap">The Royal Society arms, from Micrographia 1665 (public domain)</span>',
    '<h2>The Philosophical Transactions</h2>',
    '<p>In 1665 the Society\'s secretary Henry Oldenburg began publishing the',
    '<i>Philosophical Transactions</i>, and it is the oldest scientific journal in',
    'the world still running. It fixed a habit that we now take for granted: you',
    'do not simply discover a thing, you WRITE IT UP, you date it, you put your',
    'name to it, and you let others read it, repeat it and object. Oldenburg more',
    'or less invented the idea of registering a discovery in print so that priority',
    'could be settled and the work could be checked. For what that journal started,',
    'and for peer review, see the sister page at',
    '<a href="the-scientific-journal.geocities.ws">the-scientific-journal</a>.</p>',
    '<blockquote class="fs-quote"><p>"The Society will not own any hypothesis,',
    'system, or doctrine... nor dogmatically define, nor fix axioms of scientific',
    'things, but will question and canvass all opinions, adopting nor adhering to',
    'none, till by mature debate and clear arguments... the truth of such',
    'experiments be demonstrated."</p><p>— Thomas Sprat, <i>History of the Royal',
    'Society</i>, 1667</p></blockquote>',
    '<h2>Newton and the presidency</h2>',
    '<p>Isaac Newton served as President of the Royal Society from 1703 until his',
    'death in 1727, the longest early presidency and by far the most formidable.',
    'The Society had already published his <i>Principia</i> in 1687, though the',
    'money for the printing famously came from Edmond Halley\'s own pocket when the',
    'Society\'s funds were tied up in a book about fishes. Newton ran the place with',
    'an iron hand, and it is under him that the President\'s chair became a seat of',
    'real authority in English science.</p>',
    '<pre>',
    '  A ROYAL SOCIETY TIMELINE',
    '  ------------------------',
    '  1660   founding meeting at Gresham College (28 Nov)',
    '  1662   Royal Charter granted by Charles II',
    '  1663   the motto Nullius in verba adopted',
    '  1665   Philosophical Transactions begun by Oldenburg',
    '  1687   the Principia published by the Society',
    '  1703   Newton elected President (serves to 1727)',
    '  1753   the Society takes on the Copley Medal',
    '  1945   first women Fellows elected',
    '</pre>',
    '<p class="fs-aside"><b>DID YOU KNOW?</b> No woman was elected a Fellow until',
    '1945, when the crystallographer Kathleen Lonsdale and the microbiologist',
    'Marjory Stephenson were admitted. It took the oldest scientific society in the',
    'world two hundred and eighty-five years. Worth knowing when someone tells you',
    'the institutions were always open on merit alone.</p>',
    '<h2>A few of the Fellows (FRS)</h2>',
    '<pre>',
    '  Christopher Wren ..... founder, architect, astronomer',
    '  Robert Boyle ......... the chemist, Boyle\'s Law',
    '  Robert Hooke ......... curator of experiments, Micrographia',
    '  Isaac Newton ......... President 1703-1727',
    '  Edmond Halley ........ the comet, and paid for the Principia',
    '  Benjamin Franklin .... elected 1756, the lightning man',
    '  Humphry Davy ......... President 1820-1827',
    '  Charles Darwin ....... FRS 1839',
    '  Michael Faraday ...... declined the presidency, twice',
    '</pre>',
    '',
    '<p>The model spread. Every learned society and academy of science that',
    'followed, in Paris, in Berlin, in Washington, took something from the London',
    'pattern: fellowship by election, a journal of record, and the rule that a',
    'claim must be shown and not merely asserted. That rule of showing is exactly',
    'what the method page unpacks, over at',
    '<a href="the-scientific-method.geocities.ws">the-scientific-method</a>. Read',
    'the two together and you have the skeleton of how modern science is organised.</p>',
    '<hr>',
    '<p><b>a note on visiting</b></p>',
    '<p>The Society sits at Carlton House Terrace now, off the Mall. You cannot',
    'wander in as you like, it is a working body, but they hold public lectures and',
    'the odd open day, and the library is a wonder. If you ever get the chance to',
    'sit in that meeting room, take it, and mind you do not knock anything over.</p>',
    '<hr>',
    '<p><small>visitors: 03271 · best viewed in Netscape at 800x600 ·',
    'this corner still under construction (the Fellows list keeps growing) ·',
    'last updated 14 Oct · a proud page of the webring for science</small></p>',
    '<p><small>[ <a href="science-ring.geocities.ws">Science Ring</a> ]</small></p>',
  ]);

// ---- The Laboratory: the lab technician's tour ------------------------------

const THE_LABORATORY = P('the-laboratory.geocities.ws', 'THE LABORATORY',
  'THE LABORATORY // the bench, the apparatus, big science', [
    '<!--bg:sci-institutions-->',
    '<h1>THE LABORATORY</h1>',
    '<p><small>notes from a lab technician of thirty years, who has washed more',
    'glassware than any of you have ever seen, and who thinks the room itself',
    'deserves a page. the scientists get the statues. the bench does the work.',
    '— Sandy, senior technician (retired)</small></p>',
    '<hr>',
    '<p>A laboratory is a room built to make nature answer questions. That is not a',
    'flourish, it is the plain function. Everything in it, the bench, the fume',
    'hood, the balance, the controlled temperature, the running water and the gas',
    'tap, is there to hold conditions steady so that one thing can be varied and',
    'watched. The word comes from the Latin <i>laborare</i>, to labour. A lab is a',
    'workshop, and science is a trade done with the hands as much as the head.</p>',
    '<p>For most of history the natural philosopher worked alone, at home, at his',
    'own expense, in a private cabinet. Boyle had his air-pump in a room in Oxford;',
    'Lavoisier had a private laboratory paid for out of a fortune he made as a tax',
    'farmer, which is a story that ends badly. The change, across the nineteenth',
    'century, is that the laboratory left the private house and became an',
    'institution: a teaching laboratory, a university laboratory, a state or',
    'company laboratory, with staff, apprentices and a budget.</p>',
    '<h2>The Cavendish</h2>',
    '<p>The Cavendish Laboratory at Cambridge, opened in 1874 under James Clerk',
    'Maxwell as its first professor, is the great example of what a research',
    'laboratory could become. Under J. J. Thomson the electron was found there in',
    '1897. Under Rutherford the nucleus was probed and the atom first split. Later',
    'the structure of DNA was worked out in and around it. One room, one letterhead,',
    'a run of discoveries that rewrote physics and then biology. The Rockefeller',
    'Institute in New York, founded 1901, did the same for medicine on the other',
    'side of the Atlantic, with money instead of a single professor at the head.</p>',
    '<pre>',
    '  A WORKING BENCH (schematic, not to scale)',
    '',
    '     [ fume hood ]======================',
    '       |  retort   ___',
    '       |   \\      /   \\   <- condenser',
    '     __|__  \\____/     \\____',
    '    |     |  flask       |  |',
    '    | o o |  on stand    |==|  <- burette + stand',
    '    |_____|   |  |       |  |',
    '   balance    |__|       water',
    '              burner     bath',
    '',
    '  hold everything constant but the one thing you are asking about.',
    '</pre>',
    '',
    '<h2>Big science</h2>',
    '<p>By the middle of the twentieth century the lone worker at a bench had, in',
    'the biggest fields, given way to what the physicist Alvin Weinberg named "big',
    'science": teams of hundreds, machines the size of buildings, budgets the size',
    'of small nations. The particle accelerator, the great telescope, the genome',
    'project. The apparatus grew until running it became a collaboration in itself,',
    'and a single paper could carry a thousand author names. Something is gained in',
    'reach and something is lost in the old picture of the solitary genius, and it',
    'is worth being clear-eyed about both.</p>',
    '<p>Whatever the scale, the logic of the room does not change. A laboratory',
    'exists to isolate a question from the noise of the world and put it to the',
    'test. That logic is the method itself, laid out step by step over at',
    '<a href="the-scientific-method.geocities.ws">the-scientific-method</a>. And',
    'when the specimens will not come to the bench, the naturalists built a bench',
    'the size of a cathedral to go to them; see',
    '<a href="the-natural-history-museum.geocities.ws">the-natural-history-museum</a>.</p>',
    '<hr>',
    '<p><small>counter: 01044 · best viewed at 800x600 · a webring-for-science page ·',
    'mind the acid · last updated 2 Sep</small></p>',
    '<p><small>[ <a href="science-ring.geocities.ws">Science Ring</a> ]</small></p>',
  ]);

// ---- The Scientific Method: the teacher's handout ---------------------------

const THE_SCIENTIFIC_METHOD = P('the-scientific-method.geocities.ws', 'SCI METHOD',
  'THE SCIENTIFIC METHOD // how a claim becomes knowledge', [
    '<!--bg:sci-institutions-->',
    '<h1>THE SCIENTIFIC METHOD</h1>',
    '<p><small>a handout for my lower-sixth, put on the web so you stop losing the',
    'paper copy. read it before the practical, not after. — Mr Okafor, Science</small></p>',
    '<hr>',
    '<p>There is no single recipe that all scientists follow in lockstep, whatever',
    'the textbook flow-chart suggests. But there is a family of habits, and if you',
    'understand the habits you understand how a guess turns into knowledge that the',
    'rest of us can rely on. It goes roughly like this.</p>',
    '<pre>',
    '  1. OBSERVATION   you notice something that wants explaining',
    '  2. HYPOTHESIS    you propose an explanation you could be wrong about',
    '  3. PREDICTION    you work out what MUST follow if it is true',
    '  4. EXPERIMENT    you set up a fair test of that prediction',
    '  5. OBSERVATION   you record what actually happened',
    '  6. REPLICATION   others repeat it; a result nobody can repeat is nothing',
    '</pre>',
    '<p>The step most people skip is number three. A hypothesis is only worth',
    'anything if it sticks its neck out and tells you what you should expect to',
    'see, in a way that could turn out false. A story that fits absolutely any',
    'result explains nothing.</p>',
    '<h2>Bacon and the inductive turn</h2>',
    '<p>Francis Bacon, in the <i>Novum Organum</i> of 1620, made the early case for',
    'building knowledge up from careful observation and organised experiment rather',
    'than spinning it out of first principles the way the schoolmen did. Gather the',
    'instances, tabulate them, let the general law emerge from the particulars.',
    'This is induction, and it is the temper that the new experimental societies',
    'took as their own.</p>',
    '',
    '<h2>Popper and falsifiability</h2>',
    '<p>The twentieth-century philosopher Karl Popper argued that what marks a',
    'claim as scientific is not that it can be proved but that it can in principle',
    'be DISPROVED. He called this falsifiability. No number of white swans proves',
    'that all swans are white, but a single black one disproves it, and Australia',
    'duly obliged. A good scientific theory forbids things; it takes real risks; it',
    'can be broken by evidence. A theory that explains every outcome after the fact,',
    'and rules nothing out, is not being scientific however clever it sounds.</p>',
    '<blockquote class="fs-quote"><p>"A theory which is not refutable by any',
    'conceivable event is non-scientific. Irrefutability is not a virtue of a',
    'theory (as people often think) but a vice."</p><p>— Karl Popper,',
    '<i>Conjectures and Refutations</i>, 1963</p></blockquote>',
    '<h2>The control and the blind trial</h2>',
    '<p>Two pieces of practical kit make a test fair. The first is the CONTROL: you',
    'run the experiment a second time with the one thing you are testing left out,',
    'so that you can tell the effect of that one thing from everything else going',
    'on. Give one group of plants the fertiliser, give an identical group none, and',
    'keep all else the same. The difference between them is your answer.</p>',
    '<p>The second is BLINDING. If the people in a trial know whether they are',
    'getting the real pill or a dummy, their expectations muddy the result; if the',
    'experimenters know, their hopes leak into the measurements. So you hide it. In',
    'a double-blind trial neither the patient nor the assessor knows who got what',
    'until the code is broken at the end. This is how medicine tells a real drug',
    'from a hopeful one, and it is one of the most important ideas on this page.</p>',
    '<p class="fs-aside"><b>REMEMBER FOR THE EXAM.</b> Correlation is not causation.',
    'Two things rising together may share a hidden cause, or be pure coincidence. A',
    'controlled experiment is how you earn the right to say one thing CAUSES another,',
    'rather than merely keeps it company.</p>',
    '<p>None of this was handed down complete. It was hammered out by working',
    'scientists and the societies they built, above all the body that took',
    '"take nobody\'s word for it" as its motto; see',
    '<a href="the-royal-society.geocities.ws">the-royal-society</a>. And the place',
    'a finished claim goes to be checked, argued over and put on the record is the',
    'journal, over at',
    '<a href="the-scientific-journal.geocities.ws">the-scientific-journal</a>.</p>',
    '<hr>',
    '<p><small>counter: 00688 · best viewed in Netscape 800x600 · page still under',
    'construction, blind-trial section to be expanded · a science webring member ·',
    'last updated 21 Nov · Mr Okafor</small></p>',
    '<p><small>[ <a href="science-ring.geocities.ws">Science Ring</a> ]</small></p>',
  ]);

// ---- The Nobel Prize: the prize-watcher's page ------------------------------

const THE_NOBEL_PRIZE = P('the-nobel-prize.geocities.ws', 'NOBEL PRIZE',
  'THE NOBEL PRIZE // the will, the medals, the omissions', [
    '<!--bg:sci-institutions-->',
    '<h1>THE NOBEL PRIZE</h1>',
    '<p><small>every October i sit up for the announcements and i have kept notes',
    'for years, so here they are. i am a science fan, not the committee, and this',
    'page argues with the committee more than once. — the prize-watcher</small></p>',
    '<hr>',
    '<p>Alfred Nobel (1833-1896) was a Swedish chemist and engineer who made a vast',
    'fortune from inventing dynamite and manufacturing explosives. In 1888 a French',
    'newspaper, mistaking him for his dead brother, printed his obituary under the',
    'headline "The merchant of death is dead". Reading your own bad obituary while',
    'still alive tends to concentrate the mind. When he wrote his last will in 1895',
    'he left the bulk of his estate to fund annual prizes for those who had',
    'conferred the greatest benefit on humankind.</p>',
    '<p>The will named five prizes: Physics, Chemistry, Physiology or Medicine,',
    'Literature, and Peace. The Physics and Chemistry prizes are awarded by the',
    'Royal Swedish Academy of Sciences, Medicine by the Karolinska Institute, and',
    'Peace, oddly, by a committee of the Norwegian parliament. The first prizes',
    'were awarded in 1901, five years after his death. The Economics prize is a',
    'later addition, endowed by the Swedish central bank in 1968, and strictly it',
    'is not one of Nobel\'s own.</p>',
    '<pre>',
    '  THE FIVE ORIGINAL PRIZES (from Nobel\'s will, 1895)',
    '  -------------------------------------------------',
    '  Physics ................. Royal Swedish Academy of Sciences',
    '  Chemistry ............... Royal Swedish Academy of Sciences',
    '  Physiology or Medicine .. Karolinska Institute',
    '  Literature .............. Swedish Academy',
    '  Peace ................... Norwegian Nobel Committee',
    '',
    '  first awarded 1901 · a prize may be shared by up to three ·',
    '  it is not, by the statutes, awarded posthumously',
    '</pre>',
    '<p class="fs-aside"><b>DID YOU KNOW?</b> Marie Curie won two: Physics in 1903',
    'and Chemistry in 1911. She remains the only person to have won Nobel Prizes in',
    'two different sciences. Her daughter Irène Joliot-Curie won Chemistry in 1935,',
    'which makes them the most decorated family in the history of the prize.</p>',
    '',
    '<h2>The omissions, and why they matter</h2>',
    '<p>A prize is a judgement, and judgements can be wrong. The honour roll tells',
    'you a great deal, and so does the list of those passed over. I keep the second',
    'list on purpose.</p>',
    '<p>LISE MEITNER. She was the physicist who, with Otto Frisch, first explained',
    'nuclear fission and gave it its name, working from experiments she had guided',
    'before fleeing Nazi Germany. The 1944 Chemistry prize went to Otto Hahn alone.',
    'Meitner was nominated dozens of times across physics and chemistry and never',
    'won. Element 109, meitnerium, was named for her in 1997, a late and partial',
    'amends. It is one of the clearest misjudgements in the prize\'s history.</p>',
    '<p>ROSALIND FRANKLIN. Her X-ray photograph, the famous Photo 51, and her',
    'measurements were central to working out the double helix of DNA. The 1962',
    'Medicine prize went to Watson, Crick and Wilkins. Franklin had died of cancer',
    'in 1958 at thirty-seven, and the prize is not given posthumously, so we cannot',
    'know what the committee would have done. But the way her contribution was used',
    'and then underplayed is a real grievance, and not only a matter of the rules.</p>',
    '<p>The pattern is not an accident of two cases. For their own pages, done',
    'seriously and without sentiment, look on the women-of-science ring rather than',
    'here; i only note the prizes. The point i keep coming back to is that the',
    'medal records the work the institutions chose to see.</p>',
    '<h2>The ceremony</h2>',
    '<p>The prizes are presented on 10 December each year, the anniversary of',
    'Nobel\'s death, by the King of Sweden in Stockholm (the Peace Prize in Oslo).',
    'The laureate receives a gold medal, a diploma and a sum of money, and is asked',
    'to give a lecture on the work. The lectures, gathered over a century, are a',
    'history of modern science told by the people who made it.</p>',
    '<p>Where does the work come from that wins these things? Out of the rooms',
    'described at <a href="the-laboratory.geocities.ws">the-laboratory</a>, and it',
    'reaches the committee\'s notice through the journals and the learned bodies,',
    'the oldest of which is over at',
    '<a href="the-royal-society.geocities.ws">the-royal-society</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01590 · best viewed at 800x600 · updated every October ·',
    'a member of the science webring · last updated 12 Oct</small></p>',
    '<p><small>[ <a href="science-ring.geocities.ws">Science Ring</a> ]</small></p>',
  ]);

// ---- The Scientific Journal: the PhD student's gripe ------------------------

const THE_SCIENTIFIC_JOURNAL = P('the-scientific-journal.geocities.ws', 'SCI JOURNAL',
  'THE SCIENTIFIC JOURNAL // peer review, priority, the referee', [
    '<!--bg:sci-institutions-->',
    '<h1>THE SCIENTIFIC JOURNAL</h1>',
    '<p><small>written by a PhD student in her third year who has just had a paper',
    'sent back by Reviewer 2 and needs to explain to herself why the system is',
    'worth defending anyway. it is. mostly. — K., dept of biochemistry</small></p>',
    '<hr>',
    '<p>Science is not a private hobby, it is a public record. A result that stays',
    'in your notebook is not yet knowledge; it becomes knowledge when it is written',
    'up, submitted, checked, published, and made available for anyone to read,',
    'repeat and attack. The scientific journal is the machinery that does this, and',
    'it is nearly as old as organised science itself.</p>',
    '<p>It begins with the <i>Philosophical Transactions</i> of the Royal Society,',
    'started by Henry Oldenburg in 1665 and running to this day. Oldenburg did',
    'something quietly enormous: he made the DATED LETTER the unit of science.',
    'Send in your finding, he registers it, prints it, and now there is a public,',
    'time-stamped record of who found what and when. The body that started this is',
    'over at <a href="the-royal-society.geocities.ws">the-royal-society</a>.</p>',
    '<h2>Nature, and the great journals</h2>',
    '<p><i>Nature</i> was founded in 1869 by the astronomer Norman Lockyer and',
    'remains one of the two or three most important general science journals in the',
    'world. <i>Science</i>, its American counterpart, came in 1880. Alongside these',
    'general titles grew a vast forest of specialist journals, one or more for',
    'every field and sub-field, so that the literature of science now runs to',
    'millions of papers, each one a small brick in a very large wall.</p>',
    '<pre>',
    '  ANATOMY OF A PAPER',
    '  ------------------',
    '  Title & authors ..... who, and what they claim',
    '  Abstract ............ the whole thing in one paragraph',
    '  Introduction ........ what was known, what gap remains',
    '  Methods ............. exactly what you did (so others can repeat it)',
    '  Results ............. what you found, tables and figures',
    '  Discussion .......... what it means, and what it does not',
    '  References .......... whose shoulders you stood on',
    '</pre>',
    '',
    '<h2>Peer review and the referee</h2>',
    '<p>Before a paper is published in a serious journal it is sent out to two or',
    'three anonymous experts in the field, the REFEREES, who read it and advise the',
    'editor whether it is sound, original and worth printing. They can demand more',
    'experiments, pick holes in the statistics, or recommend rejection outright.',
    'This is peer review, and it is the closest thing science has to quality',
    'control. It is slow, it is unpaid, it is sometimes unfair, and the famous',
    'anonymous "Reviewer 2" is a figure of dread in every department common room.',
    'It is also far better than the alternative of printing anything at all.</p>',
    '<blockquote class="fs-quote"><p>"If I have seen further it is by standing on',
    'the shoulders of Giants."</p><p>— Isaac Newton, letter to Robert Hooke, 1675</p>',
    '</blockquote>',
    '<h2>Priority and citation</h2>',
    '<p>Two habits hold the whole edifice together. PRIORITY: the credit for a',
    'discovery goes to whoever published it first, which is why registering the',
    'dated paper matters so much, and why priority disputes (Newton and Leibniz over',
    'the calculus, Darwin and Wallace over natural selection) run so hot. And',
    'CITATION: every paper lists the earlier work it builds on, so that the',
    'literature forms a great connected web, each claim traceable back through the',
    'ones it rests upon. A reference is an intellectual debt paid in public.</p>',
    '<p>The journal is where the method meets the world. What counts as a fair test',
    'is set out over at',
    '<a href="the-scientific-method.geocities.ws">the-scientific-method</a>; the',
    'journal is where you have to prove, to hostile strangers, that you actually',
    'ran one.</p>',
    '<hr>',
    '<p><small>counter: 00932 · best viewed at 800x600 · under construction while i',
    'wait on Reviewer 2 · a science webring page · last updated 8 Nov · K.</small></p>',
    '<p><small>[ <a href="science-ring.geocities.ws">Science Ring</a> ]</small></p>',
  ]);

// ---- The Natural History Museum: the volunteer's page -----------------------

const THE_NATURAL_HISTORY_MUSEUM = P('the-natural-history-museum.geocities.ws', 'NAT HIST MUSEUM',
  'THE NATURAL HISTORY MUSEUM // the specimen and the great halls', [
    '<!--bg:sci-institutions-->',
    '<h1>THE NATURAL HISTORY MUSEUM</h1>',
    '<p><small>i volunteer on the gallery floor two days a week and answer the same',
    'wonderful questions over and over, so i wrote the answers down. bring the kids,',
    'they will love the whale. — a museum volunteer</small></p>',
    '<hr>',
    '<p>A natural history museum is not a warehouse of dead things dressed up for',
    'the public. It is a scientific instrument. The vast collections behind the',
    'galleries, most of which the visitor never sees, are the reference library of',
    'life on earth, the physical record against which every claim about what lives,',
    'or lived, can be checked. The great halls out front are the reading room; the',
    'stores behind are the library itself.</p>',
    '<p>The building most people picture, the one in South Kensington in London,',
    'opened in 1881. Alfred Waterhouse designed it as a cathedral to nature,',
    'terracotta beasts climbing the pillars, and that is exactly the right word for',
    'the feeling of the central hall. But the great museums are also in Paris, in',
    'Washington, in New York, and each holds tens of millions of specimens.</p>',
    '<h2>The specimen</h2>',
    '<p>The unit of the whole enterprise is the SPECIMEN: a single preserved',
    'organism, or part of one, labelled with where it was found, when, and by whom.',
    'A pinned beetle, a pressed plant, a jar of preserved fish, a drawer of bird',
    'skins, a fossil in its block of rock. A specimen without its label is nearly',
    'worthless; the data is half the science. Together they let a researcher a',
    'century later ask questions the original collector never dreamed of.</p>',
    '<p class="fs-aside"><b>DID YOU KNOW?</b> When a species is first named and',
    'described, one particular specimen is chosen as the TYPE SPECIMEN, and it',
    'becomes the permanent physical definition of that name for all time. If anyone',
    'ever doubts what "this species" really means, the answer is not an opinion or',
    'a picture in a book. It is that one specimen, in that one drawer, held in trust',
    'forever. That is why the type specimens are the crown jewels of any museum.</p>',
    '',
    '<h2>The great halls</h2>',
    '<p>The public galleries do a second job, just as serious: they turn the',
    'collection into wonder, and wonder into the next generation of naturalists.',
    'The blue whale slung from the ceiling, the towering cast of a dinosaur',
    'skeleton, the mineral gallery glittering under the lights. These are not mere',
    'spectacle. A child who stands under the whale and feels how small she is has',
    'learned something about the scale of life that no textbook delivers.</p>',
    '<pre>',
    '  WHAT IS KEPT, AND WHY',
    '  ---------------------',
    '  botany ....... pressed plants, the herbarium sheets',
    '  zoology ...... skins, skeletons, specimens in spirit',
    '  entomology ... the insects, in their millions of pins',
    '  palaeontology  fossils, the record of deep time',
    '  mineralogy ... rocks, minerals, and the meteorites',
    '',
    '  each item labelled: what, where, when, who. the label is the science.',
    '</pre>',
    '<p>Carl Linnaeus gave us the system of naming that every one of those labels',
    'uses, genus and species, two words in Latin, the same the world over. The',
    'collectors who filled these drawers, Humboldt and Darwin and Wallace among',
    'them, sent home the specimens on which whole theories were later built. A',
    'museum is a laboratory whose experiments run over centuries; for the room',
    'where the shorter experiments happen, see',
    '<a href="the-laboratory.geocities.ws">the-laboratory</a>. For the society that',
    'first gathered the collectors and read their reports, see',
    '<a href="the-royal-society.geocities.ws">the-royal-society</a>.</p>',
    '<hr>',
    '<p><small>visitors: 02106 · best viewed in Netscape at 800x600 · mind the',
    'whale · a page in the science webring · last updated 30 Sep · your friendly',
    'gallery volunteer</small></p>',
    '<p><small>[ <a href="science-ring.geocities.ws">Science Ring</a> ]</small></p>',
  ]);

export const SCI_F = [
  ROYAL_SOCIETY,
  THE_LABORATORY,
  THE_SCIENTIFIC_METHOD,
  THE_NOBEL_PRIZE,
  THE_SCIENTIFIC_JOURNAL,
  THE_NATURAL_HISTORY_MUSEUM,
];
