// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — connectionism & statistical machine learning.
//
// Fan pages, kept on a free host, each ABOUT a figure or idea and never in that
// figure’s own voice. A retro-net hobbyist’s shrine to Rosenblatt and the first
// neural spring; a clean student summary of backpropagation; a reading group
// working through the PDP volumes; a physics-minded summary of Hopfield nets; a
// careful account of Judea Pearl and cause; and a sober page on the statistical
// turn. The authors, titles and dates are real; the enthusiasms are the fans’.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Rosenblatt: the retro-net shrine (SHOWPIECE) ---------------------------

const PERCEPTRON = P('perceptron-rosenblatt.geocities.ws', 'PERCEPTRON',
  'FRANK ROSENBLATT & THE PERCEPTRON — the first spring', [
    '<!--bg:connectionist-->',
    '<h1>FRANK ROSENBLATT AND THE PERCEPTRON</h1>',
    '<p><small>a shrine to Frank Rosenblatt (1928–1971), kept by someone who solders',
    'her own logic boards on the kitchen table and wired up a two-input perceptron',
    'from relays one wet weekend just to watch it learn. he is my favourite of the',
    'lot and he does not get the pages he is owed. so, one. — Ada K.</small></p>',
    '<p class="fs-epi">“the embryo of an electronic computer that [the Navy] expects',
    'will be able to walk, talk, see, write, reproduce itself and be conscious of',
    'its existence.” — the New York Times, reporting the perceptron, 1958</p>',
    '<hr>',
    '<p>Frank Rosenblatt was a psychologist at the Cornell Aeronautical Laboratory,',
    'and in 1958 he built a machine that could LEARN. Not be programmed. Learn. The',
    'Mark I Perceptron was the first trainable artificial neural net anyone had made',
    'stand up and work, and it grew straight out of the McCulloch and Pitts neuron',
    'from 1943, the neuron modelled as a little logic gate. Rosenblatt took that idea',
    'and gave it a knob you could turn: weights that CHANGE with experience.</p>',
    '<p>Here is the whole trick, and it is beautiful because it is so plain. The',
    'machine takes some inputs, multiplies each by a weight, adds them up, and fires',
    'if the total clears a threshold. When it gets the answer wrong, it nudges the',
    'weights a touch in the direction that would have got it right, and tries again.',
    'Do that over and over with examples and the weights settle into something that',
    'WORKS. Nobody sat down and wrote the rule. The rule grew.</p>',
    '<p class="fs-pull">it was not programmed to know. it was built to find out.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/perceptron-01.jpg" alt=""><span class="indie-cap">Frank Rosenblatt (Wikimedia Commons, CC BY-SA)</span>',
    '<p>The Mark I was not a tidy simulation on paper either. It was HARDWARE, a',
    'room of it: an array of four hundred photocells for an eye, and the weights',
    'held as the settings of little motor-driven potentiometers that the machine',
    'turned itself as it learned. You could stand in front of the thing and watch it',
    'teach itself to tell one shape from another. I would have given anything to be',
    'in that room.</p>',
    '<div class="fs-aside"><p>a note on the maths, for the soldering crowd. a single',
    'perceptron draws ONE straight line and sorts the world into two sides of it.',
    'that is all a single layer can ever do, a straight cut. hold that thought,',
    'because it is the whole of the quarrel below.</p></div>',
    '<h2>The paper, and the book that answered it</h2>',
    '<p>He set it all out in “The Perceptron: A Probabilistic Model for Information',
    'Storage and Organization in the Brain” (1958), and then at length in',
    '<i>Principles of Neurodynamics</i> (1962), which is the one to hunt down. The',
    'promise, and the Navy press around it, ran hot. The New York Times printed the',
    'line up top. And then in 1969 Marvin Minsky and Seymour Papert published',
    '<i>Perceptrons</i>, a careful, cold, mathematical book that proved what a single',
    'layer could NOT do.</p>',
    '<blockquote class="fs-quote"><p>“the perceptron … cannot compute the exclusive',
    'or.”</p></blockquote>',
    '<p>XOR. The simplest little either-or you can name, and one straight line will',
    'not cut it, because there is no straight line that puts the right cases on the',
    'right sides. A multi-LAYER net could do it, everyone knew that in principle, but',
    'nobody had a way to TRAIN the middle layers yet. The book did not say the whole',
    'idea was dead. Readers heard it that way anyway.</p>',
    '<h2>What it cost, and what came back</h2>',
    '<p>The money went to the symbol people, the neural work went quiet, and the',
    'first neural spring closed into the long freeze. Rosenblatt did not see the',
    'thaw. He drowned in a boating accident in 1971, on his birthday, at forty-three.',
    'The training rule for the middle layers, backpropagation, arrived in force in',
    '1986, and everything he started came back up out of the ground. He was right',
    'far too early to enjoy it.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/neuralnet-01.jpg" alt=""><span class="indie-cap">a neural network (Cecbur, CC BY-SA)</span>',
    '<p>Neighbours worth a visit. Upstream is the neuron itself, McCulloch and Pitts',
    'at <a href="mcculloch-pitts.geocities.ws">mcculloch-pitts</a>, where this all',
    'starts. Downstream is the rule that fixed the middle layers,',
    '<a href="backpropagation.geocities.ws">backpropagation</a>. And for the wider',
    '“electronic brain” fever that the newspapers were running in those years, see',
    '<a href="giantbrains.geocities.ws">giantbrains</a>.</p>',
    '<hr>',
    '<p><small>counter: 00358 · best viewed at 800x600 · UNDER CONSTRUCTION (the',
    'relay-perceptron photos are coming once i borrow a scanner) · last updated 14',
    'March</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Backpropagation: the clean student summary -----------------------------

const BACKPROP = P('backpropagation.geocities.ws', 'BACKPROP',
  'BACKPROPAGATION // how the middle layers learn', [
    '<!--bg:connectionist-->',
    '<h1>BACKPROPAGATION</h1>',
    '<p><small>summary notes, kept tidy, for anyone coming to this cold. i am a',
    'maths postgrad and i wrote these to fix the idea in my own head. corrections',
    'welcome. — R. Okonkwo</small></p>',
    '<hr>',
    '<h2>The problem it solves</h2>',
    '<p>A single-layer perceptron can only draw a straight divide (see',
    '<a href="perceptron-rosenblatt.geocities.ws">perceptron-rosenblatt</a> for why',
    'that was such a wall). Stack layers and the net can carve any shape you like,',
    'but that raises a hard question: when the final answer is wrong, WHICH weight,',
    'buried in a middle layer, was to blame, and by how much? Backpropagation is the',
    'answer to exactly that question.</p>',
    '<h2>How it works, in one breath</h2>',
    '<p>Send the input forward through the layers to get an output. Measure the error',
    'at the end. Then push that error BACKWARD through the net, layer by layer, using',
    'the chain rule from calculus to hand each weight its own share of the blame.',
    'Nudge every weight a little against its share of the error. Repeat on thousands',
    'of examples and the whole net descends its error, step by step, toward something',
    'that works. It is gradient descent, wired through the layers by the chain rule,',
    'and that is the entire idea.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/neuralnet-01.jpg" alt=""><span class="indie-cap">a neural network (Cecbur, CC BY-SA)</span>',
    '<h2>Who found it</h2>',
    '<p>The paper that made it land is David Rumelhart, Geoffrey Hinton and Ronald',
    'Williams, “Learning Representations by Back-Propagating Errors”, in',
    '<i>Nature</i> (1986). Short paper, enormous consequence. It showed the middle',
    '(“hidden”) layers learning useful internal features on their own, which was the',
    'thing the 1969 objections had said could not be trained.</p>',
    '<p>The honest history is that it was found more than once. Paul Werbos set out',
    'the method in his Harvard PhD thesis in 1974. Seppo Linnainmaa had published the',
    'underlying reverse-mode automatic differentiation in 1970. Others circled it',
    'too. The 1986 paper did not invent the rule from nothing; it made the field',
    'finally SEE what the rule was good for, and on that the whole revival turned.</p>',
    '<h2>A short critical note</h2>',
    '<p>Two cautions the careful reader should keep. First, backpropagation is not',
    'how brains learn; real neurons do not run a tidy backward pass, and Hinton',
    'himself has spent years hunting for something more biologically plausible.',
    'Second, the method sat half-forgotten for years for want of data and computing',
    'power. The algorithm of 1986 needed the datasets and the fast hardware of the',
    '2000s before it could show its full hand.</p>',
    '<hr>',
    '<p>Neighbours. Backwards to the machine that could not yet do this,',
    '<a href="perceptron-rosenblatt.geocities.ws">perceptron-rosenblatt</a>.',
    'Forwards to the school that made the case for these nets as a theory of mind,',
    '<a href="connectionism-pdp.geocities.ws">connectionism-pdp</a>.</p>',
    '<hr>',
    '<p><small>visitor no. 00512 · best viewed at 800x600 · last updated 2 Feb ·',
    'these are study notes, cite the actual papers not me</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Connectionism / PDP: the reading-group notes ---------------------------

const PDP = P('connectionism-pdp.geocities.ws', 'PDP',
  'PARALLEL DISTRIBUTED PROCESSING — reading notes', [
    '<!--bg:connectionist-->',
    '<h1>PARALLEL DISTRIBUTED PROCESSING</h1>',
    '<p><small>notes from the Thursday reading group. we spent a whole term on the',
    'two PDP volumes and argued the whole way through. this is our shared crib,',
    'typed up by whoever remembered to. — the cog-sci reading group</small></p>',
    '<hr>',
    '<p>The books: <i>Parallel Distributed Processing: Explorations in the',
    'Microstructure of Cognition</i>, two volumes, David Rumelhart and James',
    'McClelland and the PDP Research Group (1986). The blue books. This is where',
    'connectionism stopped being a fringe interest and became a whole way of',
    'thinking about the mind. We read it as an argument, not a manual, and here is',
    'how the argument went, theme by theme.</p>',
    '<h2>Theme one: the mind is sub-symbolic</h2>',
    '<p>The claim that started the fights. Thought is not, at bottom, the shuffling',
    'of symbols by rules, the way the older AI had it. It is the settling of activity',
    'across a great many simple units wired together, none of which means anything on',
    'its own. Meaning is a PATTERN over the units, not a token sitting in a slot. The',
    'symbol, on this view, is a rough description of what the net is doing, not the',
    'thing itself.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/neuralnet-01.jpg" alt=""><span class="indie-cap">a neural network (Cecbur, CC BY-SA)</span>',
    '<h2>Theme two: distributed representation</h2>',
    '<p>This is the idea we spent the most time on. A concept is not stored in one',
    'place, one unit, one address. It is spread across many units, and each unit',
    'takes part in representing many different concepts. So knowledge is superimposed,',
    'not filed. The payoff is real: such a net degrades gracefully when damaged,',
    'generalises to cases it never saw, and fills in from a partial cue. The cost is',
    'that you cannot point at where “grandmother” lives, because she is nowhere and',
    'everywhere at once.</p>',
    '<blockquote class="fs-quote"><p>“knowledge is stored in the connections.”</p></blockquote>',
    '<h2>What we argued about</h2>',
    '<p>Half the room thought this was the honest picture of cognition and the symbol',
    'stuff had been a long detour. The other half held that you cannot get language',
    'and reasoning out of pattern-settling alone, and here they had a heavy weapon.</p>',
    '<h2>The Fodor and Pylyshyn objection</h2>',
    '<p>Jerry Fodor and Zenon Pylyshyn, “Connectionism and Cognitive Architecture”',
    '(1988), threw the hardest punch, and it still has not fully landed back. Thought',
    'is SYSTEMATIC, they said. Anyone who can think “the dog chased the cat” can',
    'think “the cat chased the dog”, automatically, because the thought has PARTS',
    'that combine by rules. A classical symbol system gets that for free. A network',
    'that just learns statistical associations does not obviously get it at all, and',
    'if a net does manage systematicity, they argued, it does so only by implementing',
    'a symbol system after all, at which point it is the plumbing and not the theory.</p>',
    '<p>We did not settle it. Nobody has, quite. The neat version of our term is that',
    'the connectionists had the better account of perception, memory and graceful',
    'failure, and the symbol people had the better account of language and reasoning,',
    'and the whole later history is people trying to have both.</p>',
    '<h2>Questions we left open</h2>',
    '<p>Is a distributed representation a real explanation or a very good description',
    'of a black box? If meaning is a pattern of activity, what fixes WHICH pattern',
    'means what? And is the systematicity objection a knockdown, or just a bill that',
    'the newer models have slowly been paying off? We put those in the minutes and',
    'went to the pub.</p>',
    '<hr>',
    '<p>Neighbours. The training rule under all of this,',
    '<a href="backpropagation.geocities.ws">backpropagation</a>. A different flavour',
    'of net, memory as an energy landscape, at',
    '<a href="hopfield-nets.geocities.ws">hopfield-nets</a>. And for the old worry',
    'about whether any of this amounts to understanding, the philosophers next door',
    'at <a href="chinese-room.geocities.ws">chinese-room</a>.</p>',
    '<hr>',
    '<p><small>counter: 00297 · best viewed at 640x480 · minutes kept by the group ·',
    'last updated 21 Nov · we still meet Thursdays</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Hopfield nets & Boltzmann machines: the physics-minded summary ---------

const HOPFIELD = P('hopfield-nets.geocities.ws', 'HOPFIELD NETS',
  'HOPFIELD NETS & BOLTZMANN MACHINES // memory as physics', [
    '<!--bg:connectionist-->',
    '<h1>HOPFIELD NETS AND BOLTZMANN MACHINES</h1>',
    '<p><small>a summary page kept by a lapsed physicist who wandered into neural',
    'nets and found her old thermodynamics waiting for her. clean and short, the way',
    'a summary should be. — S. Marsh</small></p>',
    '<hr>',
    '<h2>The core idea</h2>',
    '<p>In 1982 John Hopfield, a physicist, published “Neural Networks and Physical',
    'Systems with Emergent Collective Computational Abilities” and gave the field a',
    'net you could actually reason about with the tools of physics. A Hopfield net is',
    'a set of units all wired to one another, and the whole state of the net has a',
    'quantity attached to it that behaves exactly like ENERGY. The net always rolls',
    'downhill, toward lower energy, and comes to rest at the bottom of a valley.</p>',
    '<p>Those valleys are the memories. You set the connection weights so that the',
    'patterns you want to store sit at the bottoms of the energy landscape. Then you',
    'show the net a corrupted or partial pattern, drop it onto the slope, and it',
    'rolls down into the nearest valley, which is the whole clean memory. That is an',
    'associative memory: give it a fragment, it hands you back the whole.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/hopfield-01.jpg" alt=""><span class="indie-cap">John Hopfield (photo: bhadeshia123, CC BY)</span>',
    '<h2>The Boltzmann machine</h2>',
    '<p>Geoffrey Hinton and Terry Sejnowski took the energy picture and added chance.',
    'A Boltzmann machine (around 1985) is a Hopfield-style net with a temperature: it',
    'does not only roll downhill, it sometimes jumps up, with a probability borrowed',
    'straight from statistical mechanics, so it can shake itself out of a shallow',
    'valley and find a deeper one. Add hidden units and let it settle, and the',
    'machine can LEARN a probability distribution over its inputs rather than just',
    'memorising fixed patterns. It was slow, but it was one of the first nets that',
    'learned to generate, not only to recognise.</p>',
    '<div class="fs-aside"><p>why a physicist felt at home. “energy”, “temperature”,',
    '“ground state”, systems settling toward equilibrium: this is the language of',
    'spin glasses, borrowed almost word for word. the surprise was that memory and',
    'learning fit the same equations.</p></div>',
    '<h2>The 2024 Nobel</h2>',
    '<p>In 2024 the Nobel Prize in Physics went to John Hopfield and Geoffrey Hinton',
    '“for foundational discoveries and inventions that enable machine learning with',
    'artificial neural networks”. A physics prize, for work that grew into the',
    'machinery now running well outside physics. The committee reached back past all',
    'the recent noise to the two people who had written the equations down.</p>',
    '<h2>A short critical note</h2>',
    '<p>The plain Hopfield net has a small memory: crowd too many patterns in and the',
    'valleys merge and it hands back nonsense. The Boltzmann machine, in its full',
    'form, was too slow to train to be practical for years. Their importance is less',
    'as tools you would reach for today and more as the bridge that carried the',
    'physics of many interacting parts into the study of memory and learning.</p>',
    '<hr>',
    '<p>Neighbours. The learning rule that powered the next wave,',
    '<a href="backpropagation.geocities.ws">backpropagation</a>. And the man who',
    'shares the 2024 prize and carried these ideas into deep learning,',
    '<a href="hinton-deep.geocities.ws">hinton-deep</a>.</p>',
    '<hr>',
    '<p><small>visitors: 00431 · best viewed at 800x600 · no frames, no midi, sorry ·',
    'last updated 9 Dec</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Judea Pearl: the careful summary on cause ------------------------------

const PEARL = P('judea-pearl.geocities.ws', 'JUDEA PEARL',
  'JUDEA PEARL // networks, and the ladder of cause', [
    '<!--bg:connectionist-->',
    '<h1>JUDEA PEARL AND THE QUESTION OF CAUSE</h1>',
    '<p><small>a summary page for Judea Pearl, kept by a stats student who thinks he',
    'is the most under-read important person in the whole field. sober notes, one',
    'strong opinion, clearly marked. — T. Vance</small></p>',
    '<hr>',
    '<h2>First, he made uncertainty computable</h2>',
    '<p>Before the causal work, Pearl gave AI a way to reason under uncertainty that',
    'actually scaled. His book <i>Probabilistic Reasoning in Intelligent Systems</i>',
    '(1988) set out BAYESIAN NETWORKS: a diagram of nodes and arrows where each node',
    'is a variable and each arrow a direct dependence, so a tangle of probabilities',
    'becomes a graph you can compute over. It let a machine update its beliefs',
    'sensibly as evidence came in, and it is quietly everywhere now, from medical',
    'diagnosis to the spam filter.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/pearl-01.jpg" alt=""><span class="indie-cap">Judea Pearl (White House, public domain)</span>',
    '<h2>Then he went after cause itself</h2>',
    '<p>Pearl’s later and larger claim is that statistics, and by extension every',
    'machine that only learns correlations from data, is stuck on the bottom rung of',
    'a ladder it cannot climb by itself. He calls it the LADDER OF CAUSATION, and it',
    'has three rungs.</p>',
    '<blockquote class="fs-quote"><p>“you cannot answer a question you cannot ask.”',
    '</p></blockquote>',
    '<p>Rung one, SEEING: what does observing X tell me about Y? Pure association,',
    'and this is all a correlation-machine can do. Rung two, DOING: what happens to Y',
    'if I INTERVENE and set X myself? That is not in the data of passive observation;',
    'you need a model of what causes what. Rung three, IMAGINING: what WOULD have',
    'happened to Y had X been different, the counterfactual, the stuff of regret and',
    'responsibility and science. To climb past rung one you need a causal model, a',
    'picture of the machinery, which no amount of curve-fitting on observations will',
    'hand you.</p>',
    '<p>He built the tools to do it: the do-calculus, a way of writing and reasoning',
    'about interventions rather than mere observations. The technical account is in',
    '<i>Causality</i> (2000), and the version for the rest of us is <i>The Book of',
    'Why</i> (2018, with Dana Mackenzie), which is the one to read first.</p>',
    '<h2>The prize, and the argument he keeps making</h2>',
    '<p>Pearl won the Turing Award in 2011, largely for the Bayesian-network work.',
    'The opinion I flagged: he has become one of the sharpest critics of the',
    'deep-learning boom, and his charge is precise, not grumpy. These systems, he',
    'says, are superb curve-fitters stuck on rung one. They can predict astonishingly',
    'well and still not know what would happen if you reached in and changed',
    'something, because prediction and intervention are different questions and the',
    'data of the first does not contain the answer to the second.</p>',
    '<p>Whether the newest models are creeping up the ladder or only faking the climb',
    'with more data is, right now, one of the live fights in the field. Pearl’s',
    'framework is the clearest ruler anyone has for measuring the claim.</p>',
    '<hr>',
    '<p>Neighbours. The wider move from hand-coded rules to learning from data,',
    '<a href="statistical-ml.geocities.ws">statistical-ml</a>. And the training rule',
    'behind the correlation-machines he is so sharp about,',
    '<a href="backpropagation.geocities.ws">backpropagation</a>.</p>',
    '<hr>',
    '<p><small>counter: 00263 · best viewed at 800x600 · last updated 5 Jan · read',
    'The Book of Why, honestly, just read it</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- The statistical turn: the sober summary --------------------------------

const STATML = P('statistical-ml.geocities.ws', 'STATISTICAL ML',
  'THE STATISTICAL TURN // let the data do it', [
    '<!--bg:connectionist-->',
    '<h1>THE STATISTICAL TURN</h1>',
    '<p><small>a summary of how the field quietly changed its mind in the 1990s, kept',
    'by a sysadmin who reads this stuff on the night shift. no hero here, just a',
    'change of method that mattered more than most of the heroes. — nightdesk</small></p>',
    '<hr>',
    '<h2>The change of mind</h2>',
    '<p>For its first thirty years the field mostly tried to build intelligence by',
    'hand: write down the knowledge, write down the rules, and reason over them. The',
    'expert systems of the 1980s were the high-water mark of that faith. Through the',
    '1990s and 2000s a different faith took over. Stop hand-coding the knowledge. Let',
    'a machine LEARN the regularities from lots of data, with statistics and',
    'optimisation doing the work that logic used to. Fewer rules written by experts,',
    'more patterns pulled out of examples.</p>',
    '<p>The change showed up field by field. Machine translation went from grammars',
    'written by linguists to models trained on mountains of paired sentences. Speech',
    'recognition went statistical and started to work. The whole centre of gravity',
    'moved from KNOWING to LEARNING.</p>',
    '<h2>Support vector machines</h2>',
    '<p>The emblem of the era is the support vector machine, worked out by Vladimir',
    'Vapnik and Corinna Cortes and set out in Vapnik’s <i>The Nature of Statistical',
    'Learning Theory</i> (1995). The idea is elegant: to separate two classes, find',
    'the dividing boundary that leaves the widest possible margin on either side, and',
    'lean on the handful of awkward points near the frontier (the “support vectors”)',
    'to fix it. With a clever trick it can draw curved boundaries too. For a decade',
    'the SVM was the tool that just worked, and for a while it outran the neural nets',
    'entirely.</p>',
    '<img class="indie-pic" src="assets/media/web/ai/deepblue-01.jpg" alt=""><span class="indie-cap">Deep Blue (photo: James the photographer, CC BY)</span>',
    '<h2>Deep Blue, and what it did not prove</h2>',
    '<p>The public face of machine cleverness in this period was not learning at all.',
    'In 1997 IBM’s Deep Blue beat the world chess champion Garry Kasparov over six',
    'games. It was a landmark, and it was BRUTE FORCE: special hardware searching',
    'something like two hundred million positions a second, guided by an evaluation',
    'function tuned with human help. No understanding of chess in any human sense,',
    'no learning during play, just search, fast and deep.</p>',
    '<pre>  Kasparov  vs  Deep Blue, 1997\n  match: 3.5 - 2.5 to the machine\n  method: search + tuned evaluation\n  understanding of chess: none</pre>',
    '<p>The lesson people drew was mixed and worth keeping. A machine could now win at',
    'the game that had stood for intelligence for centuries, and it could do so with',
    'no thought of the kind we meant. Either chess was never the right test, or',
    '“intelligence” was going to keep retreating one step ahead of whatever the',
    'machines learned to do.</p>',
    '<p>The statistical turn set the table for everything after. Once the field',
    'believed that data plus optimisation could beat hand-built cleverness, the only',
    'questions left were how much data and how much computing power, and the answers',
    'to those turned out to be the whole of the next chapter.</p>',
    '<hr>',
    '<p>Neighbours. The critic who says these data-driven machines still cannot reason',
    'about cause, <a href="judea-pearl.geocities.ws">judea-pearl</a>. And the dataset',
    'that supplied the “how much data”, at',
    '<a href="imagenet-fei-fei.geocities.ws">imagenet-fei-fei</a>.</p>',
    '<hr>',
    '<p><small>counter: 00389 · best viewed at 800x600 · typed on the night shift ·',
    'last updated 17 Oct</small></p>',
    '<p><small>',
    '[ <a href="history-of-ai-ring.geocities.ws">History of AI Ring</a> ]',
    '[ <a href="techsociety-webring.geocities.ws">Technology &amp; Society</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const AIH_C = [PERCEPTRON, BACKPROP, PDP, HOPFIELD, PEARL, STATML];
