// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// LAB E — internet, society and critical computing.
//
// The centres that study the network from the human side rather than the
// silicon: Oxford's multidisciplinary department, the Weizenbaum Institute in
// Berlin, the new critical-computation institute at Frankfurt, Harvard's
// Berkman Klein, and Data and Society in New York. Institutional "about" pages
// and lab homepages on a free host, third person about the subject, the
// founders and dates real.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Oxford Internet Institute: the institutional showpiece -----------------

const OXFORD = P('oxford-internet-institute.geocities.ws', 'OII',
  'Oxford Internet Institute — about the department', [
    '<!--bg:lab-society-->',
    '<h1>The Oxford Internet Institute</h1>',
    '<p class="fs-epi">To study the social science of the internet, and to keep',
    'the human questions in the room while the engineers build. — the founding aim,',
    'University of Oxford, 2001</p>',
    '<hr>',
    '<p>The Oxford Internet Institute (OII) was founded in 2001 as a department of',
    'the University of Oxford, within the Division of Social Sciences. It was among',
    'the first departments in any major university given over wholly to the study of',
    'the internet and society, and it was built to be multidisciplinary from the',
    'start: sociologists, political scientists, economists, geographers, lawyers and',
    'computer scientists sharing a single common room at 1 St Giles.</p>',
    '<p>The founding was helped along by a benefaction from Dame Stephanie Shirley',
    'and by the work of Andrew Graham, then Master-elect of Balliol, with the',
    'Member of Parliament Derek Wyatt among those who pressed for it. William H.',
    'Dutton served as the founding director. The point of the place was set early:',
    'not to celebrate the technology and not to fear it, but to ask, patiently and',
    'with evidence, what the network was doing to the way people live, govern,',
    'learn and work.</p>',
    '<img class="indie-pic" src="assets/media/web/labs/arpanet-imp-01.jpg" alt=""><span class="indie-cap">An ARPANET IMP, the network these institutes study (photo: Erik Pitti, CC BY 2.0)</span>',
    '<blockquote class="fs-quote"><p>The internet is not a thing that happens to',
    'society. It is one of the places society now happens.</p></blockquote>',
    '<p>The department has always insisted that the internet is a proper object for',
    'the social sciences and not a curiosity to be left to the technologists. Its',
    'early work on the Oxford Internet Surveys tracked who in Britain was online,',
    'who was not, and what the gap meant. Its later work turned to digital',
    'governance, to the geography of information, to the ethics of data science, and',
    'to the question of how large platforms concentrate power.</p>',
    '<div class="fs-aside"><p><b>The taught degrees.</b> The OII runs graduate',
    'study, including the DPhil in Information, Communication and the Social',
    'Sciences and a set of masters programmes. The model is the seminar and the',
    'supervision rather than the lecture hall, and the students are expected to be',
    'as comfortable with a regression as with a reading of Weber.</p></div>',
    '<p>The research is organised loosely around a set of standing themes rather',
    'than fixed chairs. The list below is the sort of map a visitor would have found',
    'pinned by the common-room door.</p>',
    '<pre>',
    '  OII RESEARCH THEMES',
    '  -------------------',
    '  * digital governance and the regulation of platforms',
    '  * the information geography of the web (who is on the map)',
    '  * data science, ethics and the social study of algorithms',
    '  * internet, economy and the future of work',
    '  * education, learning and digital life',
    '  * connectivity, inclusion and the digital divide',
    '  * well-being, health and the networked self',
    '</pre>',
    '<p class="fs-pull">Evidence first, and the hype can wait its turn.</p>',
    '<p>That temper is the house style. When a new technology arrives wrapped in',
    'promises, the OII habit is to gather the data, ask who gains and who is left',
    'off the map, and publish. Sister institutions share the disposition. In Berlin',
    'the <a href="weizenbaum-institut-berlin.geocities.ws">Weizenbaum Institute</a> asks',
    'the same questions of the networked society from the German side, and at Harvard',
    'the <a href="berkman-klein.geocities.ws">Berkman Klein Center</a> has been',
    'working the law-and-internet seam since the 1990s.</p>',
    '<img class="indie-pic" src="assets/media/web/labs/cern-01.jpg" alt=""><span class="indie-cap">The first web server, a NeXT cube at CERN (photo: Coolcaesar, CC BY-SA 3.0)</span>',
    '<p>Scholars associated with the department over the years include Viktor',
    'Mayer-Schoenberger, Helen Margetts, Luciano Floridi and Gina Neff, whose work',
    'ranges from big data to the philosophy of information to the sociology of',
    'automation. The names change; the brief holds.</p>',
    '<hr>',
    '<p><small>hits: 03120 · best viewed at 800x600 · this department page is kept',
    'by a research assistant, corrections welcome · last updated 14 Mar</small></p>',
    '<p><small>[ <a href="research-labs-ring.geocities.ws">Research Labs Ring</a> ]</small></p>',
  ]);

// ---- Weizenbaum Institute: institutional "about" page -----------------------

const WEIZENBAUM = P('weizenbaum-institut-berlin.geocities.ws', 'WEIZENBAUM',
  'Weizenbaum Institute for the Networked Society (Berlin)', [
    '<!--bg:lab-society-->',
    '<h1>The Weizenbaum Institute for the Networked Society</h1>',
    '<p>The Weizenbaum Institute for the Networked Society, the German Internet',
    'Institute, opened in Berlin in 2017. It is a joint undertaking of a consortium',
    'of Berlin and Brandenburg universities and research institutes, funded by the',
    'Federal Ministry of Education and Research, and it takes as its subject the',
    'changes that digitalisation is working on society, the economy and politics.</p>',
    '<p>The institute is named after Joseph Weizenbaum (1923 to 2008), the',
    'Berlin-born computer scientist who spent his career at MIT, wrote the ELIZA',
    'program in the 1960s, and then spent his later years warning against exactly',
    'the credulity that program produced. His book <i>Computer Power and Human',
    'Reason</i> (1976) drew the line the institute still works along: there is a',
    'difference between what a computer can be made to do and what it ought to be',
    'asked to do, and the second question is not a technical one.</p>',
    '<div class="fs-aside"><p><b>Why the name matters.</b> Weizenbaum watched people',
    'confide in ELIZA, a few hundred lines of pattern-matching, as though it',
    'understood them. He concluded that the danger was not clever machines but',
    'trusting humans, and that judgement, as distinct from calculation, could not be',
    'handed to a machine without loss. The institute wears his scepticism as a',
    'charge.</p></div>',
    '<p>The work is arranged in research groups spread across the themes of',
    'digitalisation and democracy, work and cooperation, markets and data, and the',
    'foundations of a self-determined life in a networked world. The animating',
    'question is a political one: whether a society saturated with digital media can',
    'remain a self-governing one, and on what terms.</p>',
    '',
    '<p>The institute keeps company with the other centres that study the network',
    'from the human side. At Oxford the',
    '<a href="oxford-internet-institute.geocities.ws">Oxford Internet Institute</a>',
    'has asked these questions since 2001, and at Frankfurt the newer',
    '<a href="cccs-goethe.geocities.ws">Centre for Critical Computational Studies</a>',
    'presses harder on the computation itself. Berlin adds the democratic accent:',
    'digitalisation is examined not as fate but as something a public might still',
    'shape.</p>',
    '<p>Under construction: a fuller list of the research groups and their leads. In',
    'the meantime the short version is that this is a place built to keep',
    'Weizenbaum’s question open rather than to declare it settled.</p>',
    '<hr>',
    '<p><small>Besucher: 01188 · best viewed at 800x600 · Berlin · Seite zuletzt',
    'aktualisiert 9 Feb</small></p>',
    '<p><small>[ <a href="research-labs-ring.geocities.ws">Research Labs Ring</a> ]</small></p>',
  ]);

// ---- CCCS / C3S Goethe: lab homepage ----------------------------------------

const CCCS = P('cccs-goethe.geocities.ws', 'C3S',
  'Centre for Critical Computational Studies (C3S) — Goethe University', [
    '<!--bg:lab-society-->',
    '<h1>Centre for Critical Computational Studies (C3S)</h1>',
    '<p>Welcome to the homepage of the Centre for Critical Computational Studies,',
    'C3S, at Goethe University Frankfurt. We are a new institute, established as one',
    'of the university’s profile areas, and our brief is to study computation and',
    'artificial intelligence critically: as culture and as power, not only as',
    'engineering.</p>',
    '<p>Frankfurt is a fitting home for this. The city gave critical theory its',
    'name through the Institute for Social Research, and C3S carries a little of that',
    'inheritance forward into the computational present. We ask what it means that',
    'so much of social life is now organised by code and by learning machines, and',
    'we treat those machines as objects that can be read, argued with, and held to',
    'account.</p>',
    '<h2>what we do</h2>',
    '<p>We bring computer scientists together with people from the humanities and',
    'the social sciences and set them on the same problems. The work runs across',
    'the theory of computation, the politics of AI systems, the histories of the',
    'field, and the methods by which a critical account of a technical system can',
    'be made at all.</p>',
    '',
    '<pre>',
    '  C3S :: STANDING WORK',
    '  --------------------',
    '  [ ] critical theory of computation and AI',
    '  [ ] the politics and governance of learning systems',
    '  [ ] histories and archaeologies of the computational',
    '  [ ] methods for reading technical systems as culture',
    '</pre>',
    '<p>Because we take the archaeological question seriously, we keep in touch with',
    'the media-theory collections that preserve the older machines. The working',
    'collection at Berlin’s <a href="media-fundus.geocities.ws">media Fundus</a> is',
    'a natural neighbour for anyone who thinks you cannot criticise the computational',
    'without touching the hardware it grew from. On the society side we share ground',
    'with the <a href="weizenbaum-institut-berlin.geocities.ws">Weizenbaum Institute</a> in',
    'Berlin, which studies the networked society from the democratic angle.</p>',
    '<p>This site is still being built. Seminar listings, the working-paper series',
    'and the people pages will follow as the institute finds its feet.</p>',
    '<hr>',
    '<p><small>counter: 00341 · this is a new institute, pages under construction ·',
    'best viewed at 800x600 · last updated 21 Jan</small></p>',
    '<p><small>[ <a href="research-labs-ring.geocities.ws">Research Labs Ring</a> ]</small></p>',
  ]);

// ---- Berkman Klein Center: academic summary ---------------------------------

const BERKMAN = P('berkman-klein.geocities.ws', 'BERKMAN KLEIN',
  'The Berkman Klein Center for Internet & Society (Harvard)', [
    '<!--bg:lab-society-->',
    '<h1>The Berkman Klein Center for Internet &amp; Society</h1>',
    '<p><small>a summary prepared for a graduate reading group on internet law and',
    'governance. sources given where the group checked them.</small></p>',
    '<hr>',
    '<p>The Berkman Center for Internet &amp; Society was founded at Harvard Law',
    'School in 1997, and was renamed the Berkman Klein Center in 2016 after a gift',
    'from the Klein family. It grew out of the law school’s early engagement with',
    'the internet and became the leading centre for the study of how law, technology',
    'and the open network shape one another.</p>',
    '<p>Two figures are always named first. Lawrence Lessig, whose argument that',
    '<i>code is law</i> (in <i>Code and Other Laws of Cyberspace</i>, 1999) reframed',
    'the whole debate: the architecture of a system regulates behaviour as surely as',
    'a statute does, and often more quietly. And Jonathan Zittrain, whose <i>The',
    'Future of the Internet and How to Stop It</i> (2008) defended the',
    '<i>generative</i> network, the open platform that lets anyone build, against the',
    'drift toward locked-down appliances.</p>',
    '',
    '<p>The centre’s output has ranged widely: the Chilling Effects archive of',
    'legal takedown notices, work on internet filtering and censorship through the',
    'OpenNet Initiative, studies of online free expression, and later a large',
    'programme on the ethics and governance of artificial intelligence. The method',
    'is empirical and legal at once, and the disposition is toward openness: open',
    'access, open source, open network.</p>',
    '<p>For the reading group the useful contrast is with the department at Oxford.',
    'The <a href="oxford-internet-institute.geocities.ws">Oxford Internet',
    'Institute</a> comes at the network as social science; Berkman Klein comes at it',
    'as law and its architecture. The two meet on governance. On the New York side,',
    '<a href="data-and-society.geocities.ws">Data and Society</a> took up the social',
    'and cultural study of data-driven tools and became a close interlocutor.</p>',
    '<p>Reading for next week: Lessig, <i>Code</i>, chapters on regulability;',
    'Zittrain on generativity. Bring the objection that architecture is never as',
    'fixed as either author sometimes implies.</p>',
    '<hr>',
    '<p><small>reading-group page · hits: 00629 · best viewed at 800x600 · last',
    'updated 2 Apr</small></p>',
    '<p><small>[ <a href="research-labs-ring.geocities.ws">Research Labs Ring</a> ]</small></p>',
  ]);

// ---- Data & Society: institutional "about" page -----------------------------

const DATASOCIETY = P('data-and-society.geocities.ws', 'DATA & SOCIETY',
  'Data &amp; Society Research Institute (New York)', [
    '<!--bg:lab-society-->',
    '<h1>Data &amp; Society</h1>',
    '<p>Data &amp; Society is a research institute in New York City, founded in 2013',
    'by danah boyd. It was set up to study the social and cultural questions raised',
    'by data-driven technologies and automation, and to do so independently, outside',
    'both the companies building those tools and the hype that surrounds them.</p>',
    '<p>The founding idea was that the hard problems of data and AI are not mainly',
    'technical. They are questions about labour, about fairness, about who is',
    'watched and who is served, about how power moves when decisions are handed to',
    'systems. So the institute gathered not only computer scientists but',
    'ethnographers, lawyers, historians and journalists, and set them to studying',
    'the technology as it lands in ordinary life.</p>',
    '',
    '<p>The work has covered automated decision systems and their bias, the gig',
    'economy and the reshaping of work, disinformation and media manipulation, and',
    'the everyday experience of being measured. The house voice is empirical and',
    'sober, close to the ground, wary of grand claims in either direction.</p>',
    '<p>danah boyd, the founder, is a researcher of youth and social media whose',
    'book <i>It’s Complicated: The Social Lives of Networked Teens</i> (2014)',
    'argued against the easy panics about young people online. Under her the',
    'institute became a place where a critical account of data culture could be',
    'made carefully, with fieldwork behind it.</p>',
    '<p>The institute sits in a small network of like-minded centres. It has worked',
    'alongside the <a href="berkman-klein.geocities.ws">Berkman Klein Center</a> at',
    'Harvard on questions of governance, and it shares its city and much of its',
    'concern with the <a href="ai-now-institute.geocities.ws">AI Now Institute</a>,',
    'which took up the social implications of artificial intelligence from a base at',
    'New York University.</p>',
    '<hr>',
    '<p><small>visitors: 00908 · best viewed at 800x600 · New York, NY · page last',
    'updated 30 Nov</small></p>',
    '<p><small>[ <a href="research-labs-ring.geocities.ws">Research Labs Ring</a> ]</small></p>',
  ]);

export const LAB_E = [OXFORD, WEIZENBAUM, CCCS, BERKMAN, DATASOCIETY];
