// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH B — comedy. Six fan pages for the great comedies, kept on a free host
// by television obsessives: an episode-guide keeper cataloguing the Pythons; a
// top-ten list for the Simpsons; a catchphrase hoard for Seinfeld; a shrine to
// Fawlty Towers; a media-studies student's coursework on Blackadder; and a
// making-of write-up for Cheers. Creators, networks, years and catchphrases
// are real; the enthusiasm and the rankings are the fans'.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- Monty Python: the episode-guide keeper (SHOWPIECE) ---------------------

const MONTY_PYTHON = P('monty-python.geocities.ws', 'MONTY PYTHON',
  "MONTY PYTHON'S FLYING CIRCUS // the complete episode guide", [
    '<!--bg:tv-comedy-->',
    "<h1>MONTY PYTHON'S FLYING CIRCUS</h1>",
    '<p class="fs-epi">"And now for something completely different."<br>',
    '<small>— the Announcer, in dinner jacket, at a desk, in a field</small></p>',
    '<p><small>the episode guide i have been keeping since the VHS box set arrived.',
    'forty-five episodes across four series, catalogued, cross-referenced and',
    'argued over. corrections welcome, but check the tape first. — the curator</small></p>',
    '<hr>',
    '<p>It began on BBC1 on 5 October 1969, in the graveyard slot late on a Sunday',
    'night, and it took the sketch show apart. Six of them wrote it and performed',
    'it: Graham Chapman, John Cleese, Terry Gilliam, Eric Idle, Terry Jones and',
    'Michael Palin. Five Englishmen and one American who did the animations. What',
    'they threw out was the punchline. Sketches no longer had to END, they could',
    'collapse, be interrupted by a man in armour with a rubber chicken, or simply',
    'run into the next one through one of Gilliam\'s cut-out animations. The show',
    'flowed as one anarchic stream, which is why it reads as modern still.</p>',
    '<img class="indie-pic" src="assets/media/web/tv/cleese-01.jpg" alt=""><span class="indie-cap">John Cleese (photo: Miguel Discart, CC BY-SA 4.0)</span>',
    '<p class="fs-aside"><b>TRIVIA BOX.</b> The name meant nothing, which was the',
    'point. The BBC wanted a title; the team offered a stream of nonsense before',
    'settling on Monty Python, a seedy-sounding theatrical agent who never existed.',
    'The signature march that opens each show is Sousa\'s "The Liberty Bell",',
    'chosen partly because it was out of copyright. The giant foot that comes down',
    'at the end of the titles is from Bronzino\'s "Venus, Cupid, Folly and Time",',
    'cut out by Gilliam because he needed something to squash the music.</p>',
    '<h2>the sketches everyone knows</h2>',
    '<p>The DEAD PARROT (series 1, "Full Frontal Nudity", 1969). Praline, played',
    'by Cleese, returns a Norwegian Blue to a pet shop; the shopkeeper, Palin,',
    'insists it is merely resting, stunned, pining for the fjords. It is not. It',
    'is an ex-parrot. The sketch is a machine for finding new words for dead.</p>',
    '<p>The SPANISH INQUISITION (series 2, 1970). "NOBODY expects the Spanish',
    'Inquisition!" Three cardinals in red, led by Palin\'s Cardinal Ximénez, burst',
    'in whenever the phrase is spoken, then fumble their own catalogue of weapons:',
    'fear, surprise, ruthless efficiency, and an almost fanatical devotion to the',
    'Pope. The comfy chair. The soft cushions.</p>',
    '<p>The MINISTRY OF SILLY WALKS (series 2, 1970). Cleese, all six-foot-five of',
    'him, in bowler and pinstripe, high-kicking and buckling his way to a',
    'government office that funds the development of sillier walks. A civil-service',
    'sketch about wasted public money that happens to be a piece of physical',
    'comedy no one has bettered.</p>',
    '<p>THE LUMBERJACK SONG, THE ARGUMENT CLINIC, THE FISH-SLAPPING DANCE, NUDGE',
    'NUDGE, THE CHEESE SHOP (which stocks no cheese), SPAM (whence the other kind).',
    'Any list is a provocation. Here is mine, and yes, I will defend it.</p>',
    '<pre>',
    '   TEN GREATEST SKETCHES — the curator\'s ranking',
    '   ------------------------------------------------',
    '    1. Dead Parrot .................. s1e08  1969',
    '    2. The Spanish Inquisition ...... s2e02  1970',
    '    3. Ministry of Silly Walks ...... s2e01  1970',
    '    4. Argument Clinic .............. s3e03  1972',
    '    5. The Cheese Shop .............. s3e07  1972',
    '    6. Nudge Nudge .................. s1e03  1969',
    '    7. Spam ......................... s2e12  1970',
    '    8. The Lumberjack Song .......... s1e09  1969',
    '    9. Fish-Slapping Dance .......... s2e11  1971',
    '   10. Self-Defence Against Fruit ... s1e04  1969',
    '</pre>',
    '<p class="fs-pull">"I came here for a good argument!" "No you didn\'t, you',
    'came here for an argument."</p>',
    '<h2>the animations</h2>',
    '<p>Gilliam\'s cut-out films are the glue and the menace. Victorian engravings',
    'and Renaissance paintings, scissored out and made to move, a giant hobnail',
    'boot descending, a pram that eats its owner, a naked man playing a nose like',
    'a trumpet. They let one sketch bleed into the next without a link, and they',
    'gave the show its unmistakable look. He was the only American in the room and',
    'he drew the room together.</p>',
    '<img class="indie-pic" src="assets/media/web/tv/crt-tv-01.jpg" alt=""><span class="indie-cap">A vintage CRT television set (photo: Stefan Kuhn, CC BY-SA 3.0)</span>',
    '<p class="fs-aside"><b>AFTER THE CIRCUS.</b> Cleese left after series three,',
    'and the fourth ran to only six episodes in 1974 under the shortened title',
    '"Monty Python". By then the team had moved to film: "And Now for Something',
    'Completely Different" (1971), "Monty Python and the Holy Grail" (1975), "Life',
    'of Brian" (1979) and "The Meaning of Life" (1983). Graham Chapman died in',
    '1989, twenty years almost to the day after the first broadcast.</p>',
    '<blockquote class="fs-quote"><p>"Nobody expects the Spanish Inquisition! Our',
    'chief weapon is surprise. Surprise and fear. Fear and surprise. Our two',
    'weapons are fear and surprise, and ruthless efficiency."</p>',
    '<p><small>— Cardinal Ximénez, series 2</small></p></blockquote>',
    '<p>If you have got this far you belong at two neighbouring shrines. The',
    'natural next stop is Cleese solo, running a hotel very badly, at',
    '<a href="fawlty-towers.geocities.ws">fawlty-towers</a>. And for the other',
    'great tradition of British sketch-into-sitcom, the historical comedy done',
    'right, go to <a href="blackadder.geocities.ws">blackadder</a>. Spike Milligan',
    'and the Goons got here first, before there was a web page to say so.</p>',
    '<hr>',
    '<p><small>hit counter: 06942 · best viewed in Netscape Navigator at 800x600 ·',
    'this parrot is not dead it is merely under construction · last updated 11 Aug',
    '· a curator signs off — Nudge, Nudge</small></p>',
    '<p><small>[ <a href="television-ring.geocities.ws">Television Ring</a> ]</small></p>',
  ]);

// ---- The Simpsons: the top-ten list -----------------------------------------

const THE_SIMPSONS = P('the-simpsons.geocities.ws', 'THE SIMPSONS',
  'THE SIMPSONS // my thirteen best episodes, fight me', [
    '<!--bg:tv-comedy-->',
    '<h1>THE SIMPSONS — the best episodes</h1>',
    '<p><small>everyone has a list. this is mine and it is correct. Matt Groening\'s',
    'family started as crude little bumpers on the Tracey Ullman Show in 1987 and',
    'became a half-hour series on Fox in December 1989. i have watched all of it.',
    'the golden age is roughly seasons three to eight and i will not be taking',
    'questions on that. — a Springfield loyalist</small></p>',
    '<hr>',
    '<p>The premise is nothing and everything. A yellow, four-fingered family in a',
    'town called Springfield, its state forever unnamed. Homer, oaf and heart of',
    'the thing, whose strangled "D\'oh!" is in the dictionary now. Bart, the',
    'ten-year-old with the catapult and "eat my shorts". Marge and her tower of',
    'blue hair holding it together. Lisa, too clever for the room. Maggie and the',
    'dummy. Under the cartoon is the sharpest satire American television has run,',
    'on family, work, religion, television itself.</p>',
    '<pre>',
    '   THE THIRTEEN — best episodes, ranked',
    '   -----------------------------------------------------',
    '    1. Marge vs. the Monorail ............ s4  1993',
    '    2. Last Exit to Springfield .......... s4  1993',
    '    3. Homer at the Bat .................. s3  1992',
    '    4. You Only Move Twice ............... s8  1996',
    '    5. Cape Feare ........................ s5  1993',
    '    6. Homer the Heretic ................. s4  1992',
    '    7. Mr. Plow .......................... s4  1992',
    '    8. Lisa\'s Substitute ................. s2  1991',
    '    9. Rosebud ........................... s5  1993',
    '   10. Bart Sells His Soul ............... s7  1995',
    '   11. Lisa the Vegetarian .............. s7  1995',
    '   12. 22 Short Films About Springfield . s7  1996',
    '   13. Who Shot Mr. Burns? (Part One) ... s6  1995',
    '</pre>',
    '<p class="fs-aside"><b>WHY MONORAIL WINS.</b> Conan O\'Brien wrote it. A con',
    'man, Lyle Lanley, sells Springfield a monorail it does not need with a song',
    'lifted straight from "The Music Man", and the whole town sings along. It is a',
    'perfect half hour: a swindle, a musical number, Leonard Nimoy as himself, and',
    'a solar eclipse. "Is there a chance the track could bend?" "Not on your life,',
    'my Hindu friend."</p>',
    '<img class="indie-pic" src="assets/media/web/tv/groening-01.jpg" alt=""><span class="indie-cap">Matt Groening, the creator (photo: PhilipRomanoPhoto, CC BY 4.0)</span>',
    '<p>The couch gag is its own art form: every episode opens with the family',
    'racing to the sofa and something different going wrong, a joke smuggled into',
    'the furniture. And the guest voices, from Nimoy to Dustin Hoffman to Michael',
    'Jackson (credited under a pseudonym), never break the world; they get pulled',
    'into Springfield rather than the other way round.</p>',
    '<p class="fs-pull">"To alcohol! The cause of, and solution to, all of life\'s',
    'problems." — Homer J. Simpson</p>',
    '<p>Two doors down the comedy corridor, both from that same 1989 vintage. The',
    'live-action show that also turned nothing into everything is at',
    '<a href="seinfeld.geocities.ws">seinfeld</a>. And for the sitcom that taught',
    'a generation to love a place where the regulars never leave, see',
    '<a href="cheers.geocities.ws">cheers</a>. King of the Hill and Futurama came',
    'later from the same stable, but they can wait their turn.</p>',
    '<hr>',
    '<p><small>hit counter: 03019 · best viewed at 800x600 · this page is',
    'Comic-Book-Guy approved (worst website ever) · under construction, ay',
    'caramba · last updated 2 Jul · — El Barto woz here</small></p>',
    '<p><small>[ <a href="television-ring.geocities.ws">Television Ring</a> ]</small></p>',
  ]);

// ---- Seinfeld: the catchphrase hoard ----------------------------------------

const SEINFELD = P('seinfeld.geocities.ws', 'SEINFELD',
  'SEINFELD // a show about nothing — the phrasebook', [
    '<!--bg:tv-comedy-->',
    '<h1>SEINFELD — the complete phrasebook</h1>',
    '<p class="fs-epi">"No hugging, no learning."<br>',
    '<small>— the unofficial rule of the writers\' room</small></p>',
    '<p><small>every phrase this show gave the language, collected in one place,',
    'because half of you are quoting it without knowing where it came from. Larry',
    'David and Jerry Seinfeld built it for NBC and it ran from 1989 to 1998. four',
    'awful people in New York and not one lesson learned. perfection. — a close',
    'talker</small></p>',
    '<hr>',
    '<p>The legend is true: it is the show about nothing. In the fourth series the',
    'characters pitch a sitcom to NBC about nothing, which is the show you are',
    'watching, a joke folded inside itself. There is Jerry, more or less playing',
    'himself; George Costanza, based on Larry David, the neurotic engine of every',
    'catastrophe; Elaine Benes, the only one with a job worth naming and no more',
    'decent than the rest; and Kramer, who enters every room as if the door owes',
    'him money.</p>',
    '<p class="fs-aside"><b>THE SOUP NAZI.</b> Series 7, 1995, based on a real',
    'Manhattan soup vendor. The rules are strict, the queue is long, the soup is',
    'worth it, and one wrong word gets you the verdict: "NO SOUP FOR YOU!" Come',
    'back one year. The real vendor was reportedly not delighted with the',
    'nickname.</p>',
    '<pre>',
    '   THE PHRASEBOOK — with case notes',
    '   -----------------------------------------------------------',
    '   "yada yada yada" ...... skip the boring or damning bit (s8)',
    '   "no soup for you" ..... the Soup Nazi\'s sentence (s7)',
    '   "not that there\'s',
    '    anything wrong',
    '    with that" ........... the panicked disclaimer (s4)',
    '   "master of my domain" . the contest nobody names (s4)',
    '   "these pretzels are',
    '    making me thirsty" ... Kramer\'s one line of dialogue (s3)',
    '   "serenity now" ........ George\'s father\'s coping cry (s9)',
    '   "the puffy shirt" ..... the pirate blouse Jerry must wear (s5)',
    '   "double dipping" ...... one chip, one dip, one time (s4)',
    '   "shrinkage" ........... an unhelpful defence (s5)',
    '   "festivus" ............ a holiday for the rest of us (s9)',
    '</pre>',
    '<p>YADA YADA YADA is the one that escaped furthest into ordinary speech. A',
    'girlfriend of George\'s uses it to skate over the important parts of a story',
    '"and yada yada yada, I was in the Hamptons". George: "You yada yada\'d over',
    'the best part." She: "No, I mentioned the bisque."</p>',
    '<img class="indie-pic" src="assets/media/web/tv/seinfeld-01.jpg" alt=""><span class="indie-cap">Jerry Seinfeld (photo: Zafrir Keren, CC BY-SA 3.0)</span>',
    '<p class="fs-pull">"You know, we\'re gonna have to break up. It\'s not you, it\'s',
    'me." — George Costanza, inventing the phrase and then admitting he invented',
    'it</p>',
    '<p>The finale in 1998 put all four on trial for their years of callousness',
    'and jailed them, which enraged half the audience and delighted the other',
    'half. No hugging, no learning, right to the end. Whatever else you think, it',
    'kept its own rule.</p>',
    '<p>For the other 1989 comedy that made nothing into a network fortune, the',
    'cartoon version, go to <a href="the-simpsons.geocities.ws">the-simpsons</a>.',
    'And for the older New York-adjacent bar comedy where the regulars actually',
    'do like each other, see <a href="cheers.geocities.ws">cheers</a>. Curb Your',
    'Enthusiasm, later, is Larry David taking the gloves off; it has no page here',
    'yet.</p>',
    '<hr>',
    '<p><small>hit counter: 02718 · best viewed at 800x600 · these pretzels are',
    'making this page thirsty · under construction, serenity now · last updated',
    '14 Jun · — signed, a low talker</small></p>',
    '<p><small>[ <a href="television-ring.geocities.ws">Television Ring</a> ]</small></p>',
  ]);

// ---- Fawlty Towers: the personal shrine -------------------------------------

const FAWLTY_TOWERS = P('fawlty-towers.geocities.ws', 'FAWLTY TOWERS',
  'FAWLTY TOWERS // a shrine to the worst hotel in Torquay', [
    '<!--bg:tv-comedy-->',
    '<h1>FAWLTY TOWERS</h1>',
    '<p class="fs-epi">"Don\'t mention the war. I mentioned it once, but I think I',
    'got away with it."<br><small>— Basil Fawlty, "The Germans"</small></p>',
    '<p><small>my shrine to the most perfect comedy ever made in this country.',
    'twelve episodes. TWELVE. and not a weak one among them. John Cleese and',
    'Connie Booth wrote every word together, married while they wrote the first',
    'series and divorced by the second, and it never shows on the page. BBC2,',
    '1975 and 1979. — the night porter</small></p>',
    '<hr>',
    '<p>Basil Fawlty runs a small seaside hotel in Torquay and hates every guest',
    'who walks through the door. He is a snob without the means to be one, forever',
    'clawing at a respectability that keeps slipping, terrified of his wife and',
    'contemptuous of everyone below him. Cleese built him partly from a real',
    'hotelier the Pythons had once suffered under, a man so rude he became a muse.</p>',
    '<p class="fs-aside"><b>THE FOUR CORNERS.</b> Basil, all flailing limbs and',
    'held-in rage (John Cleese). Sybil, his wife, sharper than him and bored of',
    'him, with a laugh like a drain (Prunella Scales). Manuel, the waiter from',
    'Barcelona whose English defeats him, "Qué?" (Andrew Sachs). And Polly, the',
    'maid who actually keeps the place standing (Connie Booth). Four people, one',
    'lobby, endless catastrophe.</p>',
    '<p>The engine is farce built like clockwork. A lie in the first minute forces',
    'a second lie, then a hidden body, a health inspector, a dead guest, a fire',
    'drill gone wrong, all converging in the lobby at once. "The Germans", where a',
    'concussed Basil cannot stop mentioning the war to a party of German guests,',
    'is the one everyone cites; "The Kipper and the Corpse" and "Basil the Rat"',
    'are just as tightly wound.</p>',
    '<pre>',
    '   THE TWELVE — every episode, in order',
    '   -----------------------------------------------------',
    '   SERIES ONE (1975)',
    '     1. A Touch of Class',
    '     2. The Builders',
    '     3. The Wedding Party',
    '     4. The Hotel Inspectors',
    '     5. Gourmet Night',
    '     6. The Germans',
    '   SERIES TWO (1979)',
    '     7. Communication Problems',
    '     8. The Psychiatrist',
    '     9. Waldorf Salad',
    '    10. The Kipper and the Corpse',
    '    11. The Anniversary',
    '    12. Basil the Rat',
    '</pre>',
    '<img class="indie-pic" src="assets/media/web/tv/cleese-01.jpg" alt=""><span class="indie-cap">John Cleese (photo: Miguel Discart, CC BY-SA 4.0)</span>',
    '<p class="fs-pull">"A satisfied customer. We should have him stuffed." —',
    'Basil, on the rarest sight in his hotel</p>',
    '<p>They stopped at twelve on purpose, while every one was still a gem, and',
    'refused all the money waved at them for more. That restraint is half the',
    'legend now.</p>',
    '<p>Cleese before all this, in the sketch show that made him, is catalogued at',
    '<a href="monty-python.geocities.ws">monty-python</a>. For the other summit of',
    'British comedy writing, the one that does history as farce, go to',
    '<a href="blackadder.geocities.ws">blackadder</a>. Andrew Sachs deserved a',
    'knighthood for Manuel and never got one.</p>',
    '<hr>',
    '<p><small>hit counter: 01975 · best viewed in Netscape at 800x600 · this site',
    'is a mess, my wife is away · under construction (the builders are Irish, do',
    'not ask) · last updated 9 Apr · — signed, a worried little man from',
    'Waterloo</small></p>',
    '<p><small>[ <a href="television-ring.geocities.ws">Television Ring</a> ]</small></p>',
  ]);

// ---- Blackadder: the media-studies coursework -------------------------------

const BLACKADDER = P('blackadder.geocities.ws', 'BLACKADDER',
  'BLACKADDER // MDST 204 coursework — comedy & history', [
    '<!--bg:tv-comedy-->',
    '<h1>BLACKADDER: comedy, history and the sitcom form</h1>',
    '<p><small>Media Studies MDST 204, Popular Television Genres, assignment 2.',
    'word count 1,480. i have put my draft up here because the library printer ate',
    'it once already. marks and corrections to my pigeonhole please. — student no.',
    '9114227</small></p>',
    '<hr>',
    '<p><b>Abstract.</b> This essay argues that Blackadder (BBC, 1983 to 1989)',
    'reinvented the historical sitcom by moving its central character through four',
    'periods of English history while keeping a fixed comic engine underneath: a',
    'clever, thwarted schemer surrounded by fools. The essay traces the shift in',
    'authorship from series one to series two and considers the tonal gamble of',
    'the final episode of Blackadder Goes Forth.</p>',
    '<p><b>1. The premise across four series.</b> Richard Curtis and Rowan',
    'Atkinson devised the first series, "The Black Adder" (1983), set in a made-up',
    'medieval reign; it was expensive, filmed on location, and its Edmund was a',
    'snivelling coward. From series two, Ben Elton joined Curtis as co-writer,',
    'the budget moved into the studio, and the character flipped: Blackadder',
    'became the sharpest man in every room, held back by idiots above and below',
    'him. The four series run: the Middle Ages, the Elizabethan court',
    '("Blackadder II", 1986), the Regency ("Blackadder the Third", 1987) and the',
    'trenches of the First World War ("Blackadder Goes Forth", 1989).</p>',
    '<p class="fs-aside"><b>THE CAST THAT RECURS.</b> Atkinson as Edmund Blackadder',
    'in each age; Tony Robinson as Baldrick, his filthy, faithful dogsbody; and,',
    'across the series, Hugh Laurie, Stephen Fry, Miranda Richardson and Tim',
    'McInnerny. The same actors, different centuries, a repertory company doing',
    'English history as a sketch that will not end.</p>',
    '<p><b>2. The cunning plan.</b> Baldrick\'s recurring offer, "I have a cunning',
    'plan", is the show\'s clockwork. The plan is always idiotic; the phrase raises',
    'a hope the episode then dashes. It became a national catchphrase precisely',
    'because it is a promise of cleverness attached to the least clever person on',
    'screen. The comedy of Blackadder is verbal, a torrent of elaborate insult,',
    'and Baldrick is the flat surface all that wit bounces off.</p>',
    '<blockquote class="fs-quote"><p>BALDRICK: "I have a cunning plan."<br>',
    'BLACKADDER: "As cunning as a fox who\'s just been appointed Professor of',
    'Cunning at Oxford University?"</p><p><small>— Blackadder Goes Forth,',
    '1989</small></p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/tv/atkinson-01.jpg" alt=""><span class="indie-cap">Rowan Atkinson, who plays Blackadder (photo: Eva Rinaldi, CC BY-SA 2.0)</span>',
    '<p><b>3. The ending.</b> The final episode, "Goodbyeee", abandons the joke.',
    'Trapped in the trenches, out of schemes, Blackadder and the others go over',
    'the top into no-man\'s-land, and the image dissolves into a field of poppies.',
    'A sitcom about a coward ends by sending its characters to their deaths, and',
    'plays it straight. Media-studies scholarship treats this as a landmark: proof',
    'that half an hour of studio comedy could earn a genuinely tragic close',
    'without betraying the laughs that came before.</p>',
    '<p><b>Conclusion.</b> Blackadder shows that a sitcom can carry a fixed comic',
    'relationship across radically different settings, and that the form is elastic',
    'enough to end in the mud of the Somme.</p>',
    '<pre>',
    '   BIBLIOGRAPHY (provisional, will tidy)',
    '   ----------------------------------------------------',
    '   Curtis, R. and Elton, B. — Blackadder scripts, BBC',
    '   Atkinson, R. — interviews, Radio Times (various)',
    '   my lecture notes, weeks 4-6 (MDST 204)',
    '   the video box set my nan taped off the telly',
    '   [NB tutor said find a proper academic source, still looking]',
    '</pre>',
    '<p>Comparative pages for the wider essay: the farce tradition is best seen at',
    '<a href="fawlty-towers.geocities.ws">fawlty-towers</a>, and the sketch-show',
    'roots of this whole line of comedy are catalogued at',
    '<a href="monty-python.geocities.ws">monty-python</a>. Spike Milligan again',
    'stands behind all of it, uncredited on this webring.</p>',
    '<hr>',
    '<p><small>hit counter: 00204 · best viewed at 800x600 · this coursework is',
    'under construction and so is my degree · last updated 21 Mar · — a student',
    'with a plan so cunning you could put a tail on it and call it a weasel</small></p>',
    '<p><small>[ <a href="television-ring.geocities.ws">Television Ring</a> ]</small></p>',
  ]);

// ---- Cheers: the making-of write-up -----------------------------------------

const CHEERS = P('cheers.geocities.ws', 'CHEERS',
  'CHEERS // behind the bar where everybody knows your name', [
    '<!--bg:tv-comedy-->',
    '<h1>CHEERS — the making of the bar</h1>',
    '<p><small>a behind-the-scenes write-up, put together from years of reading and',
    're-watching. NBC ran it from 1982 to 1993, eleven series, and it very nearly',
    'died in its first year before it became one of the most loved comedies',
    'America ever made. here is how it was built. — the barfly historian</small></p>',
    '<hr>',
    '<p>Almost all of it happens in one room: a below-street Boston bar called',
    'Cheers, based loosely on a real place, the Bull &amp; Finch. The Charles',
    'brothers, Glen and Les, with director James Burrows, made a deliberate choice',
    'to keep the show in that single set, a stage play five nights a week, so the',
    'regulars and the room became the whole world. The theme tune, "Where Everybody',
    'Knows Your Name" by Gary Portnoy, states the entire premise before the first',
    'line of dialogue.</p>',
    '<p class="fs-aside"><b>THE SLOW START.</b> In its first season Cheers finished',
    'close to last in the ratings, seventy-something out of seventy-something. NBC',
    'held its nerve, the reviews were strong, and it climbed. Within a few years it',
    'was routinely the most-watched programme in the country. A reminder that the',
    'network almost pulled the plug on a classic.</p>',
    '<p>The heart of the early years is the will-they-won\'t-they between Sam Malone,',
    'the ex-baseball player and recovering drinker who owns the bar (Ted Danson),',
    'and Diane Chambers, the over-educated waitress who looks down on the place and',
    'cannot leave it (Shelley Long). Their sparring carried five seasons; when Long',
    'left, Kirstie Alley\'s Rebecca Howe changed the chemistry and the show carried',
    'on regardless.</p>',
    '<img class="indie-pic" src="assets/media/web/tv/tv-antenna-01.jpg" alt=""><span class="indie-cap">Rooftop television aerials (photo: B137, CC0)</span>',
    '<p>And around them the regulars who made it home. Norm, the accountant who',
    'lives on a barstool, greeted by the whole room shouting "NORM!" every time he',
    'enters (George Wendt). Cliff, the postman with a fact for everything and',
    'authority on nothing (John Ratzenberger). Coach, then Woody, the innocents',
    'behind the taps. And Frasier Crane, the psychiatrist who wandered in during',
    'the Diane years and never quite left (Kelsey Grammer).</p>',
    '<blockquote class="fs-quote"><p>"Can I draw you a beer, Norm?" "No, I know what',
    'they look like. Just pour me one."</p><p><small>— Woody and Norm, at the',
    'bar</small></p></blockquote>',
    '<p class="fs-aside"><b>THE SPIN-OFF.</b> When Cheers ended in 1993, watched by a',
    'vast farewell audience, Kelsey Grammer took Frasier Crane out of the Boston bar',
    'and off to a Seattle radio station. "Frasier" (1993 to 2004) ran another eleven',
    'seasons and won its own mountain of awards, one of the very few spin-offs to',
    'rival the show it grew from.</p>',
    '<p>For the network sitcom that turned callousness into an art in the same',
    'years, see <a href="seinfeld.geocities.ws">seinfeld</a>. And for the animated',
    'family that shared Cheers\' gift for a huge cast of regulars you never tire of,',
    'go to <a href="the-simpsons.geocities.ws">the-simpsons</a>. Taxi, from the same',
    'creative stable, walked so Cheers could run; it is off this ring for now.</p>',
    '<hr>',
    '<p><small>hit counter: 01982 · best viewed at 800x600 · this page is where',
    'everybody knows your frame rate · under construction, mind the wet paint ·',
    'last updated 30 May · — signed, NORM!</small></p>',
    '<p><small>[ <a href="television-ring.geocities.ws">Television Ring</a> ]</small></p>',
  ]);

export const TV_B = [MONTY_PYTHON, THE_SIMPSONS, SEINFELD, FAWLTY_TOWERS, BLACKADDER, CHEERS];
