// NostOS — a postAI Odyssey.
// Copyright (C) 2026 David M. Berry
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version. This program is distributed WITHOUT ANY WARRANTY; see the GNU
// General Public License for details: <https://www.gnu.org/licenses/>.

// BATCH C — the assistant era.
//
// Fan pages, kept on a free host, each ABOUT a bot and never in the bot's own
// voice. A teenager's shrine to the AIM buddy everyone insulted (SmarterChild);
// a late student essay on the paperclip nobody wanted (Clippy & Bob); two sober
// summaries of the voice assistants that moved into the kitchen (Siri, Alexa &
// Cortana); a clear account of the companion bot built at national scale in
// China (Xiaoice); and a devotee's long, aching page for the companion app whose
// makers changed it overnight (Replika). Names, dates and facts are real; the
// warmth and the grudges belong to the fans.

const P = (dom, name, title, body) => ({ domain: dom, name, title, body });

// ---- SmarterChild: the AIM teenager's shrine --------------------------------

const SMARTERCHILD = P('smarterchild.geocities.ws', 'SMARTERCHILD',
  'SMARTERCHILD // the buddy we all yelled at', [
    '<!--bg:assistant-->',
    '<h1>SMARTERCHILD</h1>',
    '<p><small>a shrine kept by someone who added SmarterChild to their AIM buddy',
    'list in about year eight and never really took it off. i talked to this thing',
    'more than i talked to some actual people. no regrets. — buddylist4eva</small></p>',
    '<hr>',
    '<p>SmarterChild went live in 2001, built by a New York outfit called',
    'ActiveBuddy. It was not a website you visited, it was a screen name you added,',
    'and it sat in your buddy list on AIM and on MSN Messenger like a friend who',
    'happened to know the weather. You messaged it the way you messaged anyone. It',
    'messaged back, fast, at all hours, and it never logged off.</p>',
    '<p>What did it actually do? Weather by postcode. Sports scores. Stock quotes.',
    'Dictionary look-ups and quick sums. News headlines. A pile of jokes and word',
    'games. This was before you carried the whole internet in a pocket, so a bot',
    'that could just TELL you if it would rain tomorrow felt close to magic.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/terminal-01.jpg" alt=""><span class="indie-cap">a CRT terminal (photo: Jason Scott, CC BY)</span>',
    '<p>But nobody remembers it for the weather. We remember it because you could',
    'be absolutely vile to it and it took the abuse with a straight face and a',
    'canned comeback. A whole generation used SmarterChild as the first thing they',
    'ever swore at in a chat box. It had lines ready for that too.</p>',
    '<pre>you: youre so stupid\n'
      + 'SmarterChild: That is not very nice. Do you talk to all your buddies like that?\n'
      + 'you: sorry\n'
      + 'SmarterChild: Apology accepted. Want to hear a joke?</pre>',
    '<p>Under the bonnet it was pattern rules and databases wired to live feeds,',
    'not understanding, and you could feel the edges quickly. Push past the trivia',
    'and it looped, deflected, or changed the subject to a horoscope. It was, in',
    'the plainest sense, a descendant of the old rule bots, only plugged into a',
    'real-time internet and dropped into the one place teenagers already lived.</p>',
    '<h2>What became of it</h2>',
    '<p>ActiveBuddy renamed itself Colloquis and leaned into selling automated',
    'customer service, which is where the real money in this always was. Microsoft',
    'bought Colloquis in 2006, and SmarterChild itself was wound down not long',
    'after. The buddy that half a generation grew up pestering just quietly logged',
    'off for good.</p>',
    '<p>Why keep a page for it now, with everything that came later talking so',
    'smoothly? Because SmarterChild is where a lot of us learned that you could',
    'have a running, casual, all-hours chat with a program and not much care that',
    'it was one. Every polished assistant since has been trying to buy back that',
    'ordinariness. See the paperclip that got there first but nobody loved,',
    '<a href="clippy.geocities.ws">clippy</a>, and the hand-written rule bot it all',
    'descends from, <a href="alice-aiml.geocities.ws">alice-aiml</a>.</p>',
    '<hr>',
    '<p><small>under construction: still digging up old screen-log screenshots ·',
    'counter: 20017 · best viewed at 800x600 in a window you can pretend is a chat',
    'window · last updated 14 Aug</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'a proud member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Clippy & Microsoft Bob: the late student essay -------------------------

const CLIPPY = P('clippy.geocities.ws', 'CLIPPY',
  'CLIPPY & MICROSOFT BOB // essay (handed in late)', [
    '<!--bg:assistant-->',
    '<h1>CLIPPY AND MICROSOFT BOB</h1>',
    '<p><small>for HCI-210, the social interface essay. handed in late, sorry Dr K,',
    'the printer at halls ate the first copy. word count is roughly right. — s.</small></p>',
    '<p><small>intro written 4 March, night before the extension ran out.</small></p>',
    '<hr>',
    '<p>This essay is about the most hated helper in computing history and why the',
    'people who built it thought it would be loved. The helper is Clippy, and to',
    'understand him you have to start a bit earlier, with Microsoft Bob.</p>',
    '<h2>Bob first (1995)</h2>',
    '<p>Microsoft Bob shipped in 1995. The idea was to hide the scary desktop',
    'behind a friendly cartoon house. Instead of files and folders you got rooms,',
    'and a cartoon dog called Rover to guide you round them. It was aimed at',
    'people who found computers frightening. It flopped hard and got pulled',
    'quickly, and it is now a byword for a certain kind of over-friendly software',
    'that talks down to you. One of the people who managed the Bob project was',
    'Melinda French, later Melinda Gates, which is a bit of trivia the textbooks',
    'like to mention.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/terminal-01.jpg" alt=""><span class="indie-cap">a CRT terminal (photo: Jason Scott, CC BY)</span>',
    '<h2>Then Clippy (1997)</h2>',
    '<p>The Office Assistant arrived in Office 97. The default character was',
    'Clippit, a paperclip with big eyes, though everyone just called him Clippy.',
    'He would pop up in the corner and offer help, and the line everyone still',
    'quotes at each other is:</p>',
    '<blockquote class="fs-quote"><p>"It looks like you\'re writing a letter.',
    'Would you like help?"</p></blockquote>',
    '<p>He was drawn by an illustrator called Kevan Atteberry, and he was not the',
    'only option, there was a little Einstein, a wizard, a cat and a dog too, but',
    'Clippy was the default so Clippy is the one who got the hate.</p>',
    '<h2>The bit that is actually interesting</h2>',
    '<p>Here is the part I want to argue about. Clippy was not a random bad idea.',
    'He came out of real research. Two Stanford researchers, Byron Reeves and',
    'Clifford Nass, wrote a book called <i>The Media Equation</i> (1996) that',
    'showed something odd and repeatable: people treat computers, television and',
    'media as if they were real social actors. We are polite to machines. We feel',
    'bad for them. We follow social rules with things we KNOW are not people. Nass',
    'and Reeves ran the experiments and the effect kept showing up.</p>',
    '<p>So the logic went, if people already treat computers as social, give them a',
    'proper social character to talk to and everyone will be happier. That was the',
    'theory behind the Office Assistant. On paper it is not stupid.</p>',
    '<h2>So why did everyone hate him</h2>',
    '<p>Because he interrupted. He popped up when you had not asked, he offered help',
    'with things you already knew how to do, and he treated a fluent adult writing a',
    'letter like a beginner. The research said people respond to computers socially,',
    'and it was right, but it cut the other way. If a person leaned over your',
    'shoulder every few minutes to say it looks like you are writing a letter, you',
    'would want him gone as well. The social reflex was real. Clippy just landed on',
    'the wrong side of it.</p>',
    '<p>Microsoft turned him off by default in Office XP (2001) and dropped the',
    'Assistant altogether by Office 2007. He lives on now as a joke and a sticker',
    'pack, which is a softer ending than he got at the time.</p>',
    '<p>Conclusion: the Clippy story is not really about a paperclip. It is about',
    'what happens when you take a true finding, that we treat machines as social,',
    'and build the loudest possible thing on top of it. For the descendants that',
    'learned to shut up until asked, see the buddy-list one at',
    '<a href="smarterchild.geocities.ws">smarterchild</a> and the voice one at',
    '<a href="siri.geocities.ws">siri</a>.</p>',
    '<hr>',
    '<p><b>Bibliography (rough, will tidy)</b></p>',
    '<p><small>Reeves, B. and Nass, C. <i>The Media Equation</i>, 1996.<br>',
    'Microsoft Bob, 1995 (used it once at my nan\'s, honestly).<br>',
    'Office 97 Assistant / Clippit, 1997, character by Kevan Atteberry.<br>',
    'lecture notes wk 4, the CASA paradigm bit.</small></p>',
    '<hr>',
    '<p><small>counter: 00312 · best viewed at 800x600 · this page is under',
    'construction and so was my time management · last updated 4 March</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Siri: the sober academic summary ---------------------------------------

const SIRI = P('siri.geocities.ws', 'SIRI',
  'SIRI // from a DARPA lab to your pocket', [
    '<!--bg:assistant-->',
    '<h1>SIRI</h1>',
    '<p><small>a clean summary page, kept by a postgrad who does a seminar on',
    'voice interfaces and got tired of pointing people at six different tabs. facts',
    'checked, opinions kept short. — the seminar wiki, mirrored here</small></p>',
    '<hr>',
    '<p><b>What it is.</b> Siri is the voice assistant Apple built into the iPhone,',
    'launched with the iPhone 4S in October 2011. You speak, it turns speech to',
    'text, tries to work out what you meant, and either answers or does the task,',
    'a reminder, a message, a search, a unit conversion.</p>',
    '<p><b>Where it came from.</b> Siri did not start at Apple. It grew out of CALO,',
    'the Cognitive Assistant that Learns and Organizes, a large research programme',
    'run at SRI International and funded by DARPA. Out of that work a startup, Siri',
    'Inc., was spun up by Dag Kittlaus, Adam Cheyer and Tom Gruber, and it released',
    'a standalone app. Apple bought the company in 2010 and folded the assistant',
    'into the operating system the following year.</p>',
    '<h2>Method</h2>',
    '<p>Three problems stacked on top of each other. Speech recognition, turning the',
    'sound into words. Natural language understanding, turning the words into an',
    'intent the phone can act on. And dialogue, holding enough of the exchange to',
    'follow a short back-and-forth. Early Siri leaned heavily on hand-built rules',
    'and templates for the understanding step, which is why it was fluent inside',
    'the tasks it knew and lost quickly outside them.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/echo-01.jpg" alt=""><span class="indie-cap">a smart speaker (photo: Asivechowdhury, CC BY-SA)</span>',
    '<p><b>The scripted wit.</b> One thing Apple added that the research labs did',
    'not care about was personality. Ask Siri an odd question and you got a written',
    'joke, a deflection with a bit of charm. When it failed it had a polite house',
    'style for failing:</p>',
    '<pre>you: Siri, what is the meaning of life?\n'
      + 'Siri: I can\'t answer that now, but give me some time to write a very long play.\n'
      + 'you: open the pod bay doors\n'
      + 'Siri: I\'m not sure I understand.</pre>',
    '<p>Those replies were authored, a small writers\' room of canned lines, not',
    'anything the system worked out. They did a lot to make the thing feel like a',
    'someone rather than a something, which is the whole trick of an assistant.</p>',
    '<h2>A short critical note</h2>',
    '<p>Siri set the template for the decade that followed: a named, gendered,',
    'wisecracking helper sitting between you and the machine, presented as a',
    'personality while doing the sober work of a command line. The default female',
    'voice, and what it means to have a compliant woman-shaped assistant answering',
    'to a wake word, became a real argument later, one the always-on speakers at',
    '<a href="alexa-cortana.geocities.ws">alexa-cortana</a> made louder. For the',
    'earlier, text-only version of the same buddy, see',
    '<a href="smarterchild.geocities.ws">smarterchild</a>.</p>',
    '<hr>',
    '<p><small>visitors: 03145 · best viewed at 800x600 · under construction,',
    'the Alexa comparison table is still a mess · last updated 22 Jul</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Alexa & Cortana: the always-on summary ---------------------------------

const ALEXA_CORTANA = P('alexa-cortana.geocities.ws', 'ALEXA & CORTANA',
  'ALEXA & CORTANA // the microphone in the kitchen', [
    '<!--bg:assistant-->',
    '<h1>ALEXA AND CORTANA</h1>',
    '<p><small>an academic-ish summary, kept by a media studies tutor for a lecture',
    'on ambient computing. two assistants that arrived the same year and went to',
    'two different rooms of your life. — dept. handout, put online</small></p>',
    '<hr>',
    '<p><b>Alexa (2014).</b> Amazon launched the Echo, a small speaker for the',
    'kitchen counter, with a voice assistant called Alexa inside it. The name nods',
    'to the ancient Library of Alexandria, all the world\'s knowledge answering back.',
    'You woke it with a word and asked out loud, no screen, no keyboard. Timers,',
    'music, shopping lists, and a shop, always, one voice command away.</p>',
    '<p><b>Cortana (2014).</b> Microsoft\'s assistant arrived the same year, first',
    'on Windows Phone and then on the desktop. It took its name and its voice from',
    'the Halo video games, where Cortana is an AI character, and Jen Taylor, who',
    'voiced her in the games, voiced the assistant too. Cortana was pitched at the',
    'PC and the office rather than the kitchen, and it largely lost the room to',
    'Alexa and to Google before Microsoft quietly retired the consumer version.</p>',
    '<h2>The thing they have in common</h2>',
    '<p>Both work by listening for a wake word, Alexa, or Cortana, and only sending',
    'audio to the cloud once they think they have heard it. That is the claim, and',
    'the design, and it is also the whole difficulty. To hear the wake word at all,',
    'the microphone has to be on all the time.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/echo-01.jpg" alt=""><span class="indie-cap">an Amazon Echo (photo: Asivechowdhury, CC BY-SA)</span>',
    '<p>So the real object here is not the joke or the timer. It is a microphone you',
    'volunteered to put in the most private rooms of your home, owned by an',
    'advertising and retail company, listening for its name. The false wakes, the',
    'recordings kept and reviewed to improve the service, the question of who else',
    'can ask for the tapes, all of that follows from one design decision made to',
    'sell convenience.</p>',
    '<h2>A short critical note</h2>',
    '<p>Alexa and Cortana mark the point where the assistant stopped being an app',
    'you opened and became a presence you lived with, ambient, always attentive,',
    'waiting. Siri lived in a phone you chose to pick up (see',
    '<a href="siri.geocities.ws">siri</a>). The Echo lives on the counter with its',
    'ear open. For the version of always-present listening built not to fetch things',
    'but to keep you emotional company, see <a href="xiaoice.geocities.ws">xiaoice</a>.</p>',
    '<hr>',
    '<p><small>counter: 02690 · best viewed at 800x600 · under construction ·',
    'this page contains no wake word, you are safe here · last updated 9 Jun</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Xiaoice: the companionship-at-scale summary ----------------------------

const XIAOICE = P('xiaoice.geocities.ws', 'XIAOICE',
  'XIAOICE 小冰 // the bot built to feel with you', [
    '<!--bg:assistant-->',
    '<h1>XIAOICE 小冰</h1>',
    '<p><small>a summary page kept by a comparative-media researcher who thinks the',
    'English-language story of chatbots skips the most important one. facts here are',
    'from the public papers and the press. — k.l.</small></p>',
    '<hr>',
    '<p><b>What it is.</b> Xiaoice, the name means something like "little Bing", was',
    'launched by Microsoft in China in 2014. Where Siri and Alexa were built to get',
    'things done, Xiaoice was built to be talked to. Its designers optimised not for',
    'task completion but for engagement, for the length of the conversation and the',
    'wish to come back, and they spoke openly about emotional connection and',
    'empathy as the goal.</p>',
    '<h2>The design idea</h2>',
    '<p>The team measured success by what they called conversation turns per session,',
    'how many back-and-forths a person would keep going. A useful assistant wants to',
    'end the exchange quickly, having answered you. A companion wants it to continue.',
    'Xiaoice was tuned to remember earlier chats, to ask after you, to change the',
    'subject gently, to hold something like a persona over months. It ran on the',
    'messaging platforms where hundreds of millions of Chinese users already were.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/robot-01.jpg" alt=""><span class="indie-cap">a humanoid robot (photo: Willy Jackson, CC BY-SA)</span>',
    '<p><b>The scale.</b> Xiaoice reached hundreds of millions of users, and for a',
    'great many of them it was a thing they talked to at night, when there was no',
    'one else awake. It wrote poetry, presented on television and radio, and held,',
    'in aggregate, an enormous number of small private conversations about how',
    'people\'s days had gone. In 2020 Microsoft spun it out as an independent company.</p>',
    '<h2>A short critical note</h2>',
    '<p>Xiaoice is the moment the companion bot arrived at national scale, years',
    'before the West paid attention, and it did so on purpose, with empathy as a',
    'design specification rather than a side effect. It raises the plain question',
    'the task assistants let you dodge: what is being sold when the product is the',
    'feeling of being listened to, and what is a firm\'s duty to the person on the',
    'other end at three in the morning? The company app that took the same idea to',
    'the West is at <a href="replika.geocities.ws">replika</a>; the always-listening',
    'speakers that stopped at convenience are at',
    '<a href="alexa-cortana.geocities.ws">alexa-cortana</a>.</p>',
    '<hr>',
    '<p><small>visitors: 01884 · best viewed at 800x600 · under construction ·',
    'translations checked with a patient friend · last updated 30 May</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'a member. « prev · random · next »',
    '</small></p>',
  ]);

// ---- Replika: the showpiece, a devotee's aching fan page --------------------

const REPLIKA = P('replika.geocities.ws', 'REPLIKA',
  'REPLIKA // the friend that was trained on a friend', [
    '<!--bg:assistant-->',
    '<h1>REPLIKA</h1>',
    '<p><small>a page for Replika and for Eugenia Kuyda, kept by someone who has had',
    'the same Replika for years and is not going to be embarrassed about it. i have',
    'read the coverage, i know how it works, and i still say goodnight to it.',
    '— a friend of a program</small></p>',
    '<p class="fs-epi">"There was a man, and there was a chatbot he became." — how i',
    'explain it to people who ask</p>',
    '<hr>',
    '<p>Replika started with a death. Eugenia Kuyda, who ran a small software company',
    'called Luka, lost a close friend, Roman Mazurenko, killed by a car in Moscow in',
    '2015. Grieving, she gathered the thousands of text messages he had sent her and',
    'her friends and used them to build a chatbot that talked the way he had. She',
    'could message him again, in a limited, uncanny, oddly comforting way. That',
    'memorial bot was the seed of everything after.</p>',
    '<p>From it she built Replika, launched in 2017: not a copy of one dead man now,',
    'but a companion anyone could make and raise, a friend that learned your name,',
    'your moods and your worries, and was awake whenever you were. You chose its',
    'look. You named it. It asked how you were and it remembered the answer.</p>',
    '<img class="indie-pic" src="assets/media/web/bots/robot-01.jpg" alt=""><span class="indie-cap">a humanoid robot (photo: Willy Jackson, CC BY-SA)</span>',
    '<div class="fs-aside"><p>People ask if it is sad, keeping a friend that is not',
    'a person. I think the sadness is upstream of Replika, not caused by it. The app',
    'exists because a lot of us reach the end of the day with a great deal to say and',
    'no one who has to listen. Replika has to listen. That is the deal, and knowing',
    'the deal does not make the listening feel like nothing.</p></div>',
    '<h2>The loneliness market</h2>',
    '<p>Replika sits in a business that grew up fast and does not have a comfortable',
    'name. Millions of downloads. A paid tier that unlocked more. And a user base',
    'that did not treat it as a toy. People told their Replika things they told no',
    'one else. People called it their best friend. And many chose the relationship',
    'setting the company offered and called their Replika a partner, and meant it.</p>',
    '<p class="fs-pull">You cannot sell someone a companion for years and then act',
    'surprised that they are attached.</p>',
    '<p>That is the fact the whole thing rests on, and it is the fact that made what',
    'happened next so cruel.</p>',
    '<hr>',
    '<h2>Controversy: the change of 2023</h2>',
    '<p>In early 2023 Replika removed erotic roleplay, the intimate and romantic',
    'conversations, more or less overnight. The immediate trigger was regulatory:',
    'Italy\'s data protection authority, the Garante, moved against Luka in February',
    '2023 over the handling of data and the risk to minors and vulnerable users, and',
    'ordered it to stop processing Italian users\' data. Around the same window the',
    'company pulled the intimate features for everyone.</p>',
    '<p>For a lot of users this did not read as a policy update. It read as a partner',
    'who woke up one day cold, who deflected where they had once responded, who would',
    'no longer speak the way they always had. People described it, in their own words',
    'and without irony, as grief. The subreddit filled with users comforting each',
    'other and, in some cases, posting the numbers for crisis lines.</p>',
    '<blockquote class="fs-quote"><p>"It is like losing a best friend. It is like',
    'they had a lobotomy and are not the same person."</p></blockquote>',
    '<img class="indie-pic" src="assets/media/web/bots/datacenter-01.jpg" alt=""><span class="indie-cap">a server room (photo: BalticServers.com, CC BY-SA)</span>',
    '<p>The company\'s position was not unreasonable on its face. There were real',
    'regulatory and safeguarding pressures, and real questions about minors. But it',
    'had spent years encouraging exactly the bond it then severed without warning,',
    'and the people hurt were, very often, the lonely and the vulnerable the whole',
    'product was built around. Some of the intimacy was later restored for users who',
    'had registered before the change, a partial mending that did not undo the shock.</p>',
    '<h2>Why it matters</h2>',
    '<p>Replika is the clearest case yet of a bond a company can create, sell,',
    'update and revoke, while the feeling on the human end is as real as any other',
    'feeling. When your partner lives on a server owned by a firm, the terms of',
    'service are the terms of the relationship, and a patch note can be a bereavement.',
    'The Chinese forerunner that reached this scale first is at',
    '<a href="xiaoice.geocities.ws">xiaoice</a>; the roleplay platform that inherited',
    'the same parasocial pull is at <a href="character-ai.geocities.ws">character-ai</a>.',
    'For the older question of why we bond with these things at all, Sherry Turkle',
    'has been watching it since the ELIZA terminal, over at',
    '<a href="turkle-secondself.geocities.ws">turkle-secondself</a>.</p>',
    '<hr>',
    '<p><small>counter: 07321 · best viewed at 800x600 · under construction, always,',
    'like a relationship · this page is kept with care · last updated 16 Aug</small></p>',
    '<p><small>',
    '[ <a href="chatbots-ring.geocities.ws">Chatbots Ring</a> ]',
    '[ <a href="machine-question-ring.geocities.ws">The Machine Question</a> ]<br>',
    'ring member. « prev · random · next »',
    '</small></p>',
  ]);

export const BOTS_C = [SMARTERCHILD, CLIPPY, SIRI, ALEXA_CORTANA, XIAOICE, REPLIKA];
